root-project/root

gui/browsable/inc/ROOT/Browsable/RElement.hxx, gui/browsable/src/TDirectoryElement.cxx, gui/browserv7/inc/ROOT/RBrowser.hxx, gui/browserv7/src/RBrowser.cxx, gui/browserv7/src/RBrowserData.cxx, gui/browserv7/src/RBrowserRCanvasWidget.cxx, gui/browserv7/src/RBrowserTCanvasWidget.cxx, gui/browserv7/src/RBrowserWidget.hxx
Backport of https://github.com/root-project/root/pull/10164
=> [rbrowser] improve browsing of subdirectories in TFile (6.26)

tree/dataframe/inc/ROOT/RDF/GraphNode.hxx, tree/dataframe/inc/ROOT/RDF/GraphUtils.hxx, tree/dataframe/inc/ROOT/RDF/RAction.hxx, tree/dataframe/inc/ROOT/RDF/RFilter.hxx, tree/dataframe/inc/ROOT/RDF/RRange.hxx, tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx, tree/dataframe/src/RDFGraphUtils.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/test/dataframe_helpers.cxx
See individual commits for changes and their rationale.
=> [DF] Misc improvements to GraphNode and GraphUtils

core/base/src/TSystem.cxx
Mention in docu option to set build dir via rootrc
https://github.com/root-project/root/issues/10147
=> [docu] Mention option to set build dir via Rootrc

tutorials/graphs/graphstruct.C, tutorials/math/testrandom.C
to avoid error when building documentation
=> guard to only run graphstruct tutorial if gviz ON, and more

proof/doc/confman/TDataSetManagerAliEn.md, proof/proof/src/TDataSetManager.cxx, proof/proof/src/TDataSetManagerFile.cxx, proof/proof/src/TProof.cxx, proof/proof/src/TProofChain.cxx, proof/proof/src/TProofLite.cxx, proof/proof/src/TProofMgr.cxx, proof/proof/src/TProofNodeInfo.cxx, proof/proof/src/TProofServ.cxx, proof/proofbench/src/TProofBench.cxx, proof/proofbench/src/TProofPerfAnalysis.cxx, proof/proofd/src/XrdProofWorker.cxx, proof/proofd/src/XrdProofdAux.cxx, proof/proofd/src/XrdProofdManager.cxx, proof/proofd/src/XrdProofdProofServMgr.cxx, proof/proofd/src/XrdProofdSandbox.cxx, proof/proofd/src/XrdROOT.cxx, proof/proofplayer/src/TOutputListSelectorDataMap.cxx, proof/proofplayer/src/TPacketizerAdaptive.cxx, proof/proofplayer/src/TProofDraw.cxx, proof/proofplayer/src/TProofPlayer.cxx, proof/proofx/src/TXProofMgr.cxx, proof/xrdinc/XrdClient/XrdClientSock.hh
=> [proof] fix doxygen warnings

tree/ntuple/v7/inc/ROOT/RNTuple.hxx
=> Typo in RNTuple.hxx

tutorials/math/testrandom.C
=> [tutorials] Remove extraneous `#endif`

CMakeLists.txt
Solves the problem reported at https://github.com/lobis/root-docker/pull/1 .
=> [cmake] Do not operate on install directory at build time

roofit/roofitcore/src/RooFormula.cxx
People use RooFormula a lot via RooGenericPdf and RooFormulaVar!
Performance matters here. This commit avoids non-static `std::regex` in
`RooFormula::processFormula`, because constructing these on the fly can
become a bottleneck.
This is a non-intrusive performance optimization that reduces the time spent for CMS workflows like the HZZ global fit by up to 5 %.
Example profiles:
* HZZ multi-dim fit before this PR: https://rembserj.web.cern.ch/rembserj/cgi-bin/igprof-navigator/hzz_1/74
* HZZ multi-dim fit after this PR: https://rembserj.web.cern.ch/rembserj/cgi-bin/igprof-navigator/hzz_3/1815
`RooFormula::processFormula` is now more than ten times faster.
=> [RF] Don't use non-static `std::regex` in `RooFormula::processFormula`

js/changes.md, js/scripts/JSRoot.core.js, js/scripts/JSRoot.io.js, js/scripts/JSRoot.more.js, js/scripts/JSRoot.painter.js, tutorials/eve7/projection_prescale.C, ui5/eve7/lib/EveElements.js
1. Fix projection_prescale.C macro
2. Fix REveBox geometry creation
3. Fix JSROOT `multi.json` submission
=> Several small fixes in eve7 and JSROOT

net/http/src/TRootSniffer.cxx, tutorials/eve7/projection_prescale.C, ui5/eve7/lib/EveElements.js
1. cmd.json processing was corrupted in THttpServer
2. Fix projection_prescale.C macro
3. Fix REveBox geometry creation
=> Several fixes in eve7 and THttpServer

gui/browsable/src/TDirectoryElement.cxx
=> [rbrowser] fix handling of multiple cycles in RBrowser (6.26)

core/textinput/src/textinput/Editor.cpp, core/textinput/src/textinput/Editor.h, core/textinput/src/textinput/KeyBinding.cpp
Adds forward history search support.
This PR fixes https://github.com/root-project/root/issues/10137
=> [textinput] implement forward history search

graf2d/graf/src/TGaxis.cxx, hist/hist/src/TAxis.cxx
Complete the ChangeLabel help as requested here:
https://github.com/root-project/root/issues/10279
=> Update ChangeLabel and GetNlabels helps

roofit/CMakeLists.txt, roofit/hs3/src/JSONParser.cxx
Now that HistFactory is also built on Windows, there should be no
problem with also removing the veto for RooFitHS3 on Windows.
Let's try it and see what the CI says.
=> [RF] Build RooFit HS3 also on Windows

hist/hist/src/TGraph2D.cxx
Graph2D with option P did not work with one point if that point has z<=0
=> Graph2D with option P did not work with one point

graf2d/graf/src/TGaxis.cxx, hist/hist/src/TAxis.cxx
- better image in TGaxis
- fix typo
- make sure the help shows properlly
=> Improve axis help

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx, tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDFUtils.cxx, tree/dataframe/test/dataframe_snapshot.cxx
In particular, the fixes for #10233 .
=> [DF] Backport several fixes in Snapshot to v6.26

hist/hist/src/TGraph2DErrors.cxx, hist/hist/src/TGraphAsymmErrors.cxx
- Fix wrong comments
- Add some doc
- Fix TGraph2DErrors::GetZminE and TGraph2DErrors::GetYminE
=> Fix some comments

core/cont/inc/TVirtualCollectionProxy.h, core/meta/inc/TListOfEnums.h, core/meta/src/TClass.cxx, core/meta/src/TListOfEnums.cxx, core/meta/src/TListOfEnumsWithLock.cxx, core/meta/src/TProtoClass.cxx, core/metacling/src/TCling.cxx, io/io/inc/TGenCollectionProxy.h, io/io/src/TBufferFile.cxx, io/io/src/TGenCollectionProxy.cxx, io/io/src/TStreamerInfo.cxx, io/rootpcm/src/rootclingIO.cxx
Back port of https://github.com/root-project/root/pull/10230
=> v626: Additional fixes for std::pair's StreamerInfo handling 

math/vecops/test/vecops_rvec.cxx
Tests suite now covers all possible combination of vectors both with
`swap` and `std::swap`. Previously, some special cases were omitted.
=> [VecOps] Several improvements in the RVec swap tests

ui5/browser/controller/Browser.controller.js
=> [rbrowser] escape characters in terminal output (6.26) [skip-ci]

hist/hist/src/TH1.cxx
as requested here: https://root-forum.cern.ch/t/bug-setrange-and-setrangeuser-affects-tf1/49516/4
=> [skip-ci] complete fitting range doc

tutorials/pyroot/pyroot005_tfile_context_manager.py, tutorials/pyroot/pyroot006_tcontext_context_manager.py
This PR creates tutorials for the TFile and TContext context managers introduced respectively with #9947 and #10167 .
=> [PyROOT] Add tutorial for TContext and TFile context managers

tutorials/CMakeLists.txt
Also disable tutorials, like it was done for roottest. Revert when #10061 is fixed
=> [DF] Disable also distributed tutorials on Mac ARM

builtins/davix/CMakeLists.txt
=> [cmake] Bump davix to 0.8.1:

tmva/sofie/inc/TMVA/ROperator_Pool.hxx
=> Fixed some Typos and Indentation issues in ROperator_Pool.hxx 

tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
=> Small spelling error during explaining lhcbOpenData.C

tree/dataframe/test/dataframe_snapshot.cxx
An alternative to #10302 .
Co-authored-by: @ellert
=> [DF] Fix long int + Snapshot test on 32 bit platforms

roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/test/testRooDataHist.cxx
When combining several RooDataHists to one, the binning of the variables
should be taken from the component histograms.
This was already done correctly when importing `TH1` directly, but not
when RooDataHists were given as imput.
The commit further introduces a check that makes sure the input
histograms have the same layout and binning, just like we already have
for the TH1 case.
Closes #8015.
=> [RF] Take binning from input RooDataHists when combining them

bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
The Snapshot operation file name is modified in-place to append the
range id of a certain task. This can lead to a task receiving the
input operation from a previous task with an already modified file
name. Thus, the current task would create a wrong file name with more
than one range id. Solve this by creating a deep copy of the Snapshot
operation arguments in each task, so that the filename is correctly
changed in isolation.
This PR fixes #10390
=> Copy Snapshot operation arguments in a distributed task

tutorials/dataframe/df103_NanoAODHiggsAnalysis.py
df103_NanoAODHiggsAnalysis.py could not be converted as notebook.
Fix suggested by @vepadulano
=> Make sure df103_NanoAODHiggsAnalysis.py can be converted as notebook

bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
=> [6.26] Copy Snapshot operation arguments in a distributed task

tutorials/dataframe/df105_WBosonAnalysis.py
Make sure nbconvert work on this script.
See: https://github.com/root-project/root/issues/10430
Thanks to @etejedor and @eguiraud
=> [skip-ci] df105 nbconvert fix

tree/treeplayer/src/TTreeIndex.cxx
`long double` is the most precise type for evaluating the TTreeFormula expressions.
For some platforms - notably Apple M1 - `long double` has the same precision as `double`,
and thus not enough bits to represent large numbers, as shown by roottest/tree/index/runindex64.C
failing on M1. The most reasonable way to deal with this is to warn if any of the relevant
indexing values exceeds the precision of `long double`.
For that, check whether an expression with a value 1 closer to zero
would result in the same result, i.e. this value is saturated.
Related: root-project/roottest#706
=> [treeplayer] Warn if indexed values too large for `long double`:

core/unix/src/TUnixSystem.cxx
In TUnixSystem.cxx's dynpath, the full result is know only when the TCling object is created but
it is called several before that.  Part of the work is to get information from the dynamic
linker via a call to popen("LD_DEBUG=libs LD_PRELOAD=DOESNOTEXIST ls 2>&1").
Enhanced the code so this call (and also to call to getenv) are only done once.
=> Improve startup by 15% (avoid redundant work).

math/matrix/doc/index.md, math/matrix/src/TMatrixT.cxx, math/matrix/src/TMatrixTBase.cxx, math/matrix/src/TMatrixTSym.cxx, math/matrix/src/TVectorT.cxx, montecarlo/eg/doc/index.md
=> [skip-ci] Fix undefined doxygen references

tree/treeplayer/src/TTreeReaderArray.cxx
Since this class now also supports shorts, longs, long longs and
their unsigned counterparts.
=> [treereader] Rename TUintOrIntReader -> TDynamicArrayReader

tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
=> [ntuple] Fix processing of classes with enum definitions

roofit/roofitcore/inc/RooHelpers.h, roofit/roofitcore/res/RooFit/BatchModeHelpers.h, roofit/roofitcore/res/RooFitDriver.h, roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/test/testRooFitDriver.cxx
The RooFitDriver is further refactored to make the code more
understandable.
Furthermore, some code in the constructor that was only relevant for the
CUDA mode is now only run when CUDA is enabled.
=> [RF] Continue RooFitDriver refactoring and improvements

roofit/histfactory/src/ConfigParser.cxx, roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/src/RooAddModel.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooRealSumFunc.cxx, tmva/tmva/src/DNN/Architectures/Reference/DataLoader.cxx
- `RooFit::HistFactory::ConfigParser`: function `ConfigParser::CreateMeasurementFromDriverNode()`fix null dereferences, improve logic, fix some other edge cases, optimise performance
- `TMVA::DataLoader`: calling `.front()` on an empty container is undefined, fix also null ptr dereference
- minor RooFit fixes for null ptr dereferences
=> Address -Wnonnull issues and further improvements

roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/test/testRooSimultaneous.cxx
A unit test based to check that this is done correctly was also
implemented.
Closes #10473.
=> [RF] Ignore categories with no PDF in RooSimultaneous helper code

tutorials/xml/DOMParsePerson.C, tutorials/xml/DOMRecursive.C, tutorials/xml/SAXHandler.C, tutorials/xml/xmlmodifyfile.C, tutorials/xml/xmlreadfile.C
There is no need to show the output of the tutorials.
=> [skip-ci] No need for XML output

roofit/roofit/test/CMakeLists.txt, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooHelpers.h, roofit/roofitcore/res/RooFit/BatchModeDataHelpers.h, roofit/roofitcore/res/RooFit/BatchModeHelpers.h, roofit/roofitcore/res/RooFit/CUDAHelpers.h, roofit/roofitcore/res/RooFitDriver.h, roofit/roofitcore/res/RooNLLVarNew.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/CUDAHelpers.cxx, roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFitDriver.cxx, roofit/roofitcore/test/testRooSimultaneous.cxx, roofit/roofitcore/test/testSumW2Error.cxx
This is a backport of all the RooFit PRs that were merged to `master` to `v6-26-00-patches` (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/10467
2. https://github.com/root-project/root/pull/10477
3. https://github.com/root-project/root/pull/10485
4. https://github.com/root-project/root/pull/10495
5. https://github.com/root-project/root/pull/10501
6. https://github.com/root-project/root/pull/10499
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 12

documentation/doxygen/Makefile
The doxygen Makefile need to be updated
=> [skip-ci] Update doc Makefile.

roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h, roofit/histfactory/inc/RooStats/HistFactory/Measurement.h, roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/histfactory/src/ParamHistFunc.cxx, roofit/histfactory/src/RooBarlowBeestonLL.cxx, roofit/roofitcore/inc/RooAddPdf.h, roofit/roofitcore/src/RooAddPdf.cxx
This is a backport of all the RooFit PRs that were merged to `master` to `v6-26-00-patches` (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/10516
2. https://github.com/root-project/root/pull/10525
3. https://github.com/root-project/root/pull/10550
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 13

hist/spectrum/src/TSpectrum.cxx
Fix typo that was introduced somehow in this commit https://github.com/root-project/root/commit/2b2d5b0eeabf16e066afc74977bcdf2d0555ca59#diff-0c661946530c21785a5dc0df61c398cfacd526ab455b2acd7b9dc761e7b99bdfR275
=> [hist][skip-ci] fix typo

interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp
This patch was proposed by @vgvassilev on mattermost.
When building with a macOS SDK before 12.0 and running with 12.0+ the
validation of private modulemaps fails due to a change in layout. This
change disables the check when DisablePCHValidation is active.
See these bug reports:
* https://root-forum.cern.ch/t/conda-root-and-macos-12-reprise/49135/5
* https://github.com/conda-forge/root-feedstock/issues/149
* https://github.com/conda-forge/root-feedstock/issues/167
=> Fix running with macOS 12.0+ SDK after building with an older SDK

gui/browsable/src/TDirectoryElement.cxx, gui/browsable/src/TObjectElement.cxx, gui/browserv7/src/RBrowserGeomWidget.cxx, ui5/browser/controller/Browser.controller.js
1. Let display TGeoNode object
2. Do not try to read object without class dictionary
3. Fix catched canvas title
=> [rbrowser] several fixes

gui/browsable/src/TDirectoryElement.cxx, gui/browsable/src/TObjectElement.cxx, gui/browserv7/src/RBrowserGeomWidget.cxx, ui5/browser/controller/Browser.controller.js
Backport of #10569 to 6.26 branch
1. Let display TGeoNode object
2. Do not try to read object without class dictionary
3. Fix catched canvas title
=> [rbrowser] several fixes in 6.26

roofit/roofitcore/inc/RooMinimizer.h, roofit/roofitcore/src/RooAbsMinimizerFcn.cxx, roofit/roofitcore/src/RooAbsMinimizerFcn.h, roofit/roofitcore/src/RooGradMinimizerFcn.cxx, roofit/roofitcore/src/RooMinimizer.cxx, roofit/roofitcore/src/RooMinimizerFcn.cxx, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
Add the possibility to get the parameter values for each function
evaluation during the minimization. This is useful to get a consistent
minimization path for benchmarking.
=> [RF] Add logging to dataset feature in RooMinimizer

js/changes.md, js/scripts/JSRoot.core.js, js/scripts/JSRoot.gpad.js, js/scripts/JSRoot.more.js, js/scripts/JSRoot.v7gpad.js
Also add TGraph point index to tooltip
=> [jsroot] correctly cleanup canvas painter 6.26 [skip-ci]

tmva/sofie/src/RModel.cxx
=> [TMVA][SOFIE] Add guards to the header file generated by SOFIE

interpreter/llvm/src/tools/clang/lib/AST/DeclBase.cpp
Revert https://github.com/vgvassilev/clang/commit/1c6cc386f62f9a5a87cf268b4d35199721aec0f4.
=> Revert assertion check in Declbase.cpp

ui5/eve7/controller/EveTable.controller.js, ui5/eve7/lib/GlViewerThree.js
Minor change in a table controller
Possible error on reloads of a page when elements are highlighted.
=> REve - Show only item idx in the first column of REveTable controller

tree/dataframe/inc/ROOT/RDataSource.hxx
...and point to example implementations.
=> [NFC][DF] Mention that RDataSource is for advanced users

roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/res/RooNLLVarNew.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNormalizedPdf.h, roofit/roofitcore/test/testSumW2Error.cxx, test/stressRooFit_tests.h
=> [RF] Bugfixes in RooFit BatchMode to enable also the passing of RooMCStudy tests in stressRooFit and support extended fits in subrange

roofit/histfactory/inc/RooStats/HistFactory/Channel.h, roofit/histfactory/inc/RooStats/HistFactory/Data.h, roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h, roofit/histfactory/inc/RooStats/HistFactory/Sample.h, roofit/histfactory/src/Channel.cxx, roofit/histfactory/src/Data.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/histfactory/src/Sample.cxx, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/res/RooNLLVarNew.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNormalizedPdf.h, roofit/roofitcore/test/testSumW2Error.cxx, test/stressRooFit_tests.h
This is a backport of all the RooFit PRs that were merged to `master` to `v6-26-00-patches` (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/10553
2. https://github.com/root-project/root/pull/10627
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 15

interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp
When building with a macOS SDK before 12.0 and running with 12.0+ the validation of private modulemaps fails due to a change in layout. This change disables the check when DisablePCHValidation is active.
(cherry picked from commit 85c757ad962e609779dcf8171e37cf70f611d238)
Backport of PR #10555
=> Fix running with macOS 12.0+ SDK after building with an older SDK [v6.26]

tree/dataframe/inc/ROOT/RDF/RResultMap.hxx, tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/test/SimpleFiller.h, tree/dataframe/test/dataframe_vary.cxx
With many thanks to @ikabadzhov who did the bulk of the work.
=> [DF] Add more tests for Vary

math/mathcore/inc/TMath.h, math/mathcore/src/TMath.cxx
as requested here:
https://github.com/root-project/root/issues/10681
=> Make sure the math functions are documented

tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/test/ntuple_extended.cxx
=> [ntuple] Several fixes for RNTuple's minifile

core/base/inc/TMathBase.h, math/mathcore/inc/TMath.h, math/mathcore/src/TMath.cxx
Some functions were not documented.
=> [skip-ci] Improve TMath doc

tree/dataframe/inc/ROOT/RDF/RResultMap.hxx, tree/dataframe/test/dataframe_vary.cxx
=> [DF] Add iteration support to RResultMap

roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/inc/RooNameReg.h, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooNameReg.cxx, roofit/roofitcore/src/RooRealBinding.cxx, roofit/roofitcore/src/RooUniformBinning.cxx, test/stressRooFit_tests.h
These changes speed up the stressRooFit test suite by about 5 %.
=> [RF] Speed optimizations relevant for RooAbsCachedPdf

bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx, bindings/tpython/src/TPython.cxx
A new beta release has been published this week:
https://docs.python.org/3.11/whatsnew/3.11.html
=> [PyROOT] Fixes for Python 3.11

tmva/tmva/src/MethodCategory.cxx
=> [TMVA] Backport in 6.26  the fix in  MethodCategory 

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/multiprocess/test/utils.h, roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/RooWorkspace.cxx, roofit/roofitcore/test/test_lib.h
This is an improvement to make other RooFit code less verbose.
=> [RF] Adapt `RooWorkspace::factory` to take std::string directly

roofit/roofitcore/inc/RooAcceptReject.h, roofit/roofitcore/inc/RooFitResult.h, roofit/roofitcore/inc/RooFracRemainder.h, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAcceptReject.cxx, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooDataProjBinding.cxx, roofit/roofitcore/src/RooFracRemainder.cxx
Some code modernization by using more range-based loops to iterate over
RooAbsCollections instead of `createIterator`.
=> [RF] Some code modernization by using more range-based loops

tmva/sofie/CMakeLists.txt, tmva/sofie/inc/TMVA/OperatorList.hxx, tmva/sofie/inc/TMVA/ROperator_LeakyRelu.hxx, tmva/sofie/src/RModel.cxx, tmva/sofie/test/TestCustomModelsFromONNX.cxx, tmva/sofie/test/input_models/LinearWithLeakyRelu.onnx, tmva/sofie/test/input_models/references/LinearWithLeakyRelu.ref.hxx, tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
=> [GSOC][TMVA][SOFIE]Adding a Leaky Relu ONNX Operator

tree/dataframe/inc/ROOT/RDF/RVariation.hxx
It is simpler to read and faster to compile.
=> [DF] Prefer function overloading to SFINAE where possible

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
E.g. in this scenario:
```
struct Filler {
void Fill(int) {}
void Merge(const std::vector<Filler *> &) {}
};
int main()
{
ROOT::RDataFrame(2).Define("x", [] { return 42; }).Fill<int, int>(Filler{}, {"x", "x"});
}
```
=> [DF] User-friendly error in case of Fill signature mismatch

documentation/doxygen/Makefile
Fixes this https://root-forum.cern.ch/t/root-documentation-up-to-date/50473/2
=> [skip-ci] qch only for master

core/gui/inc/TBrowser.h, core/gui/src/TBrowser.cxx, core/gui/src/TGuiFactory.cxx, gui/browserv7/src/RWebBrowserImp.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/RObjectPainter.mjs, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw/TASImagePainter.mjs, js/modules/draw/v7more.mjs, js/modules/gpad/RAxisPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist/hist3d.mjs
If "server" kind of web display is configured,
one still can use "new TBrowser". This requires that batch gui factory
allows to create web-based implementation
Update JSROOT, use nullptr in related classes
=> [rbrowser] let use web-based TBrowser in batch mode 

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RAction.hxx, tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDFColumnRegister.cxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/src/RDefineBase.cxx, tree/dataframe/src/RFilterBase.cxx, tree/dataframe/src/RVariationBase.cxx
- AddColumn -> AddDefine
- HasName -> IsDefineOrAlias
=> [DF] Better names for RColumnRegister methods

builtins/xrootd/CMakeLists.txt
This PR is a backport of PR #10725 for `v6.26`.
=> [cmake] Update XRootD to v5.4.3

README/ReleaseNotes/v626/index.md, documentation/doxygen/makeinput.sh
=> [skip-ci] Http doc

graf2d/cocoa/src/MenuLoader.mm
=> Fix warning

roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooCollectionProxy.h, roofit/roofitcore/inc/RooPolyFunc.h, roofit/roofitcore/inc/RooProduct.h, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooPolyFunc.cxx, roofit/roofitcore/src/RooProduct.cxx
After https://github.com/root-project/root/pull/10796, this should finally resolve all schema evolution issues with the RooProduct. This PR also makes some other improvements and bugfixes on the way (more detail in the commit description).
=> [RF] Second attempt to fix schema evolution for old RooProduct versions and other fixes

hist/histpainter/inc/TGraphPainter.h, hist/histpainter/src/TGraph2DPainter.cxx, hist/histpainter/src/TGraphPainter.cxx, hist/histpainter/src/THistPainter.cxx, hist/histpainter/src/TPainter3dAlgorithms.cxx, hist/histpainter/src/TPainter3dAlgorithms.h, hist/histpainter/src/TPaletteAxis.cxx
1. Use std::vector instead of plain arrays
2. More use of `nullptr`
3. Avoid usage of global variables for local data in `TGraphPainter` class
4. Test gPad before call gPad->GetView()
=> Improve histpainter classes

tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx, tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx, tree/dataframe/test/dataframe_utils.cxx
=> [DF] Declare single-argument ctor explicit

net/http/civetweb/civetweb.c
=> [civetweb] use proper methods with openssl 3.0 [6-26]

tmva/sofie/inc/TMVA/ROperator_Add.hxx, tmva/sofie/inc/TMVA/ROperator_BatchNormalization.hxx, tmva/sofie/inc/TMVA/ROperator_Conv.hxx, tmva/sofie/inc/TMVA/ROperator_Gemm.hxx, tmva/sofie/inc/TMVA/ROperator_Reshape.hxx, tmva/sofie/inc/TMVA/ROperator_Slice.hxx
This Pull request: fixes some error messages and spelling mistakes in operators
=> Some error messages and spelling mistakes fixed related to operators

tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/src/RModelParser_PyTorch.cxx, tmva/sofie/CMakeLists.txt, tmva/sofie/inc/TMVA/OperatorList.hxx, tmva/sofie/inc/TMVA/RModel.hxx, tmva/sofie/inc/TMVA/ROperator_Concat.hxx, tmva/sofie/inc/TMVA/ROperator_GRU.icc, tmva/sofie/inc/TMVA/ROperator_Identity.hxx, tmva/sofie/inc/TMVA/ROperator_Relu.hxx, tmva/sofie/inc/TMVA/ROperator_Reshape.hxx, tmva/sofie/inc/TMVA/ROperator_Softmax.hxx, tmva/sofie/inc/TMVA/ROperator_Transpose.hxx, tmva/sofie/inc/TMVA/SOFIE_common.hxx, tmva/sofie/src/RModel.cxx, tmva/sofie/src/SOFIE_common.cxx, tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx, tutorials/tmva/TMVA_SOFIE_ONNX.C
- Add Softmax, Identity and Concat operators 
- Add fusing of MatMul and Add in a Gemm operator
- Add support for generic input Batch Size in RModel
- Add support for un-order input ONNX graph and capability in teh ONNX parser to re-order correctly
=> [TMVA][SOFIE] New developments in SOFIE for parsing ONNX files 

tutorials/roofit/rf408_RDataFrameToRooFit.py
In db1a2ceb40 (#9352), the C++ version of the rf408 tutorial was
improved:
* simplify code
* remove race condition
* fix typos
In this commit, the same changes are also applied to the corresponding
Python tutorial.
Furthermore, two problems exclusive to the Python version were fixed:
* Replace second `RooDataSetHelper` with `RooDataHistHelper`
* Fix line breaks in data printing (now the output is formatted just
like in the C++ version)
Closes #9360.
=> [RF] Update Python version of rf408_RDataFrameToRooFit tutorial

roofit/roofitcore/src/RooMCStudy.cxx
It can easily happen that the fit parameter labels in the `plotPull()`
produced by the RooMCStudy don't fit on the canvas, for example in the
`rf801` tutorial:
https://root.cern.ch/doc/v626/rf801__mcstudy_8C.html
This commit suggests to improve the likelihood that the labels overshoot
the canvas in two ways:
* custom parameter label text with greek letters instead of
written-out variable letters to save space
* move the labels a bit to the left
If the legend is still not looking good in a given usecase, the Gaussian
should be fit to the pull distribution by the user outside of
`plotPull()`, which only takes a handful lines and then they have full
control over the plot. The built-in Gaussian fit to `plotPull()` is only
for quick visualizations anyway. It is now explained how to do the …
=> [RF] Improve content and position of the RooMCStudy pull plot legend

roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooAbsCachedReal.cxx, roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAbsTestStatistic.cxx, roofit/roofitcore/src/RooAddModel.cxx, roofit/roofitcore/src/RooBinnedGenContext.cxx, roofit/roofitcore/src/RooErrorVar.cxx, roofit/roofitcore/src/RooFitLegacy/RooMinuit.cxx, roofit/roofitcore/src/RooGenContext.cxx, roofit/roofitcore/src/RooLinearVar.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/src/RooProduct.cxx, roofit/roofitcore/src/RooRealBinding.cxx, roofit/roofitcore/src/RooRealMPFE.cxx
Replaced while loops with the legacy iterators fwdIterator() with range based for loops. 
This PR fixes #8777
=> [RF] Replaced legacy iterators with range-based loops

interpreter/cling/tools/packaging/cpt.py
=> [cling-cpt] Added extra whitespace around operators to get rid of E225 error. [skip-ci]

interpreter/cling/tools/packaging/cpt.py
=> [cling-cpt] Added extra spacing between functions to get rid of E302 error code. [skip-ci]

roofit/histfactory/inc/RooStats/HistFactory/PreprocessFunction.h, roofit/histfactory/src/PreprocessFunction.cxx, roofit/histfactory/src/RooBarlowBeestonLL.cxx, roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooConstraintSum.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooBinnedL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h, roofit/roofitcore/res/RooFitDriver.h, roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/NormalizationHelpers.cxx, roofit/roofitcore/src/NormalizationHelpers.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooConstraintSum.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx, roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx, roofit/roofitcore/src/TestStatistics/buildLikelihood.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooAddPdf.cxx
1. https://github.com/root-project/root/pull/10884
2. https://github.com/root-project/root/pull/10885
3. https://github.com/root-project/root/pull/10832
4. https://github.com/root-project/root/pull/10921
5. https://github.com/root-project/root/pull/10909
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 17

tree/ntuple/v7/src/RPageStorageDaos.cxx
This Pull request refactors `RPageSourceDaos::LoadClusters()` to coalesce the fetch requests for pages in the same cluster bunch before calling `RDaosContainer::ReadV`, instead of launching a call to remote storage for the pages of each cluster separately. A cluster bunch corresponds to all clusters being fetched together by `LoadClusters()` at a time. 
Since the call by `ReadV()` is ultimately blocking until all requests are done, this change enables the asynchronous page fetch requests from different clusters to share queue and flight time; thus, remote storage can parallelize them toward a higher read throughput. 
The requests are still coalesced according to object ID and distribution key resulting from the mapping strategy in `kDefaultDaosMapping`. The modification allows support for …
=> [ntuple,daos] Coalesce fetch requests for pages in cluster bunch

tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/test/dataframe_interface.cxx
Fix https://github.com/root-project/root/issues/11002
=> [DF] Fix regex substitution in code to jit (v6.26)

tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/test/dataframe_interface.cxx
This PR fixes https://github.com/root-project/root/issues/11002
=> [DF] Fix regex substiution in code to jit

roofit/roofitcore/src/RooProdPdf.cxx
In `RooProdPdf::getConstraints()`, the full computation graph was
traversed two or three times for each component pdf, depending on the
code branch. There were calls to `pdf->dependsOnValue()` and
`pdf->getParameters(&observables)`, but both are very expensive for
large computation graphs because they check if any of the observables is
in the server list of any RooAbsArg in the graph.
It is much cheaper to call `pdf->getParameters(nullptr)` to get all
value server variables of a pdf, and then use `overlaps` to check if the
pdf depends on observables or constrained parameters.
To get then the set of actual parameters, it is suggested to use
`tmp.remove(observables)`, which is is cheap for RooArgSets because of
the hash-assisted find by name.
This commit speeds up the `createNLL()` call for …
=> [RF] Speed up RooProdPdf::getConstraints() for large computation graphs

tmva/sofie/CMakeLists.txt, tmva/sofie/inc/TMVA/OperatorList.hxx, tmva/sofie/inc/TMVA/ROperator_Neg.hxx, tmva/sofie/test/TestCustomModelsFromONNX.cxx, tmva/sofie/test/input_models/Neg.onnx, tmva/sofie/test/input_models/references/Neg.ref.hxx, tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
=> [GSOC][TMVA][SOFIE]Neg ONNX Operator implemented in SOFIE with the corresponding unit tests

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx, tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/test/dataframe_snapshot.cxx
This is a backport of #10934 .
=> [DF] Backport fix for snapshot of array branch with out-of-order size branch (v6.26)

tutorials/dataframe/df004_cutFlowReport.C, tutorials/dataframe/df004_cutFlowReport.py
Correction of minor grammar mistakes in the documentation.
=> [skip-ci][DF] Df004 fixes

graf2d/graf/src/TGaxis.cxx
Improve help as suggested here: https://root-forum.cern.ch/t/how-to-move-exponent-when-draw-axis/50944
=> [skip-ci] Improve SetExponentOffset help

tutorials/graphics/canvas2.C
This forum post https://root-forum.cern.ch/t/need-help-to-draw-six-plots-using-multi-canvas/50898/7 suggested some improvements in the canvas2.C tutorial.
=> [skip-ci] Improve the tutorial canvas2.C

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/python/DistRDF/Ranges.py, bindings/experimental/distrdf/test/test_ranges.py
=> Use RDatasetSpec in distrdf task creation

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/python/DistRDF/Ranges.py, bindings/experimental/distrdf/test/backend/test_dist.py, bindings/experimental/distrdf/test/test_buildranges.py
Backport of https://github.com/root-project/root/pull/10939
=> Distrdf fix friends v626

tree/dataframe/src/RDFActionHelpers.cxx
In a synthetic benchmark that only fills a single histogram for
which no binning was provided (i.e. the case in which
BufferedFillHelper gets used), these are sample runtimes on my
laptop before this patch:
```
0         3735
1         3742
2         3534
4         3191
8         2733
16        1725
```
and after:
```
0         3552
1         3876
2         2466
4         1696
8         1202
16        1038
```
where over 8 threads hyper-threading kicks in and 0 threads means
no `EnableImplicitMT()` at all.
=> [DF] Remove false sharing from BufferedFillHelper

tutorials/CMakeLists.txt, tutorials/tmva/keras/ClassificationKeras.py, tutorials/tmva/keras/GenerateModel.py, tutorials/tmva/keras/MulticlassKeras.py, tutorials/tmva/keras/RegressionKeras.py, tutorials/tmva/pytorch/ClassificationPyTorch.py, tutorials/tmva/pytorch/MulticlassPyTorch.py, tutorials/tmva/pytorch/RegressionPyTorch.py
This PR fixes the TMVA tutorials for new Keras,PyTorch versions and for running them in parallel in the CI
=> [tmva] Fix Keras and PyTorch tutorials

tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/EmitFromKeras.cxx, tmva/pymva/test/TestRModelParserKeras.C, tmva/pymva/test/generateKerasModels.py
This PR adds support for parsing the Keras concat layer in SOFIE Keras parser.
=> [TMVA][SOFIE] Support for parsing Concat layer in Keras parser

tree/dataframe/inc/ROOT/RRootDS.hxx, tree/dataframe/src/RRootDS.cxx
=> [DF] Remove RDF::Internal::MakeRootDataFrame

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDFInterfaceUtils.cxx
=> [DF] Preserve ordering of snapshotted columns (v6.26)

geom/geom/src/TGeoMaterial.cxx
=> [v6.26] Fix 11115

tree/tree/inc/ROOT/InternalTreeUtils.hxx, tree/tree/src/InternalTreeUtils.cxx, tree/treeplayer/src/TTreeProcessorMT.cxx
@ikabadzhov @vepadulano I guess this could be interesting for distRDF+MT as well.
=> Add helper method to create a thread-friendly TChain, use it in TTreeProcessorMT

tmva/pymva/src/RModelParser_PyTorch.cxx
This is a backport in 6.26 of PR #10233
=> [tmva] Fix pytorch SOFIE parser

roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/RooFitDriver.cxx
This fixes the ASAN failures that are related to the BatchMode.
More detail can be found in the commit descriptions.
Should be backported to 6.26.
=> [RF] Fix memory and server redirection issues in BatchMode

tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/EmitFromKeras.cxx, tmva/pymva/test/TestRModelParserKeras.C, tmva/pymva/test/generateKerasModels.py
This PR adds support for parsing basic binary operators like Add, Subtract, and Multiply in the SOFIE Keras parser.
=> [TMVA][SOFIE] Support for parsing Basic Binary operators in Keras parser

core/metacling/src/TCling.cxx, core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingCallFunc.h, core/metacling/src/TClingClassInfo.cxx, core/metacling/src/TClingMethodInfo.cxx, core/metacling/src/TClingMethodInfo.h, core/metacling/test/CMakeLists.txt, core/metacling/test/TClingCallFuncTests.cxx
This patch reduces the code bloat in TClingCallFunc trying to make the code more readable.
cc: @sudo-panda
=> Simplify CallFunc

math/vecops/inc/ROOT/RVec.hxx, tree/dataframe/inc/ROOT/RDF/RCutFlowReport.hxx, tree/dataframe/inc/ROOT/RDF/RJittedDefine.hxx, tree/dataframe/inc/ROOT/RDF/RRangeBase.hxx, tree/dataframe/inc/ROOT/RDF/RVariationsDescription.hxx, tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/inc/ROOT/RDataFrame.hxx, tree/dataframe/inc/ROOT/RSqliteDS.hxx, tree/dataframe/src/RCsvDS.cxx, tree/dataframe/src/RCutFlowReport.cxx, tree/dataframe/src/RDFDisplay.cxx, tree/dataframe/src/RDFHelpers.cxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/src/RDataFrame.cxx, tree/dataframe/src/RJittedAction.cxx, tree/dataframe/src/RJittedDefine.cxx, tree/dataframe/src/RJittedVariation.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/src/RRootDS.cxx, tree/dataframe/src/RSqliteDS.cxx, tree/dataframe/src/RTrivialDS.cxx, tree/dataframe/src/RVariationBase.cxx, tree/dataframe/src/RVariationsDescription.cxx, tree/dataframe/test/dataframe_concurrency.cxx, tree/dataframe/test/dataframe_nodes.cxx, tree/dataframe/test/dataframe_snapshot.cxx, tree/dataframe/test/dataframe_utils.cxx, tree/dataframe/test/datasource_csv.cxx
This is not all the suggested fixes, but it should be an improvement w.r.t. the current situation.
=> [DF] Apply some include fixes from include-what-you-use

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
Consider the following code
```python
from dask.distributed import LocalCluster, Client
import ROOT
RDataFrame = ROOT.RDF.Experimental.Distributed.Dask.RDataFrame
def create_connection():
cluster = LocalCluster(n_workers=2, threads_per_worker=1, processes=False)
client = Client(cluster)
return client
if __name__ == "__main__":
connection = create_connection()
df = RDataFrame(100, daskclient=connection)
df = df.Define("x", "1").Define("y", "ROOT::RVecF{1., 2., 3.}")
g = df.Graph("x", "y")
gv = g.GetValue()
```
Before this PR, the output would be:
```
$: python test.py
RDataFrame::Run: event loop was interrupted
Warning in <TBufferFile::WriteObjectAny>: since runtime_error has no public constructor
which can be called without argument, objects of this class
can not be read with the current …
```
=> [DF] Catch and propagate C++ exceptions in the distributed tasks

graf2d/graf/src/TGaxis.cxx
=> [docu] fix typos

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C
Fix: https://github.com/root-project/root/issues/11124
This tutorial is not tested by the CI, hence CI is skipped.
=> [skip-ci][DF] Add a missing include + minor improvements in df103

graf3d/eve7/src/REveBoxSet.cxx, tutorials/eve7/boxset.C, ui5/eve7/controller/Ged.controller.js, ui5/eve7/controller/Summary.controller.js, ui5/eve7/lib/EveElements.js, ui5/eve7/view/Summary.view.xml
Add hexagon shape type in REveBoxSet
Remove unnecessary slider in the left most view by using FlexBox instead of Splitter.
Rebase of #11273
=> Add option to draw hexagon type in the REveBoxsSet

core/meta/src/TDataType.cxx, tree/treeplayer/src/TTreeReaderArray.cxx
This fixes #11246 and https://github.com/root-project/root/issues/10645
=> TTreeReaderArray: add support for Double32_t and Float16_t

geom/geom/src/TGeoMaterial.cxx
Fixes a bug when creating mixtures from repeating elements.
When adding an element that was already defined in the composition of a mixture, the element was not properly incorporated by modifying the weight fraction of the previous element, but rather added as new element.
This PR fixes #11272
=> [geom] Fix for mixture creation based on repeating elements.

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RAction.hxx, tree/dataframe/inc/ROOT/RDF/RDefine.hxx, tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx, tree/dataframe/inc/ROOT/RDF/RFilter.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx, tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/inc/ROOT/RDF/RRange.hxx, tree/dataframe/inc/ROOT/RDF/RVariation.hxx, tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx, tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/src/RActionBase.cxx, tree/dataframe/src/RDefineBase.cxx, tree/dataframe/src/RJittedFilter.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/src/RVariationBase.cxx, tree/dataframe/test/dataframe_helpers.cxx
The first commit is a pre-requisite for the second commit, which is the actual backport of a bug-fix.
=> [DF] Fix potential use-after-delete in Snapshot (v6.26)

hist/hist/src/TMultiGraph.cxx
Implement the X+ and Y+ options for TMultiGraph as requested here:
https://github.com/root-project/root/issues/11250
=> Option X+ and Y+ for TMultiGraph

tree/ntuple/v7/inc/ROOT/RCluster.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/test/ntuple_storage.cxx
=> [tree] Add missing override specifiers in tree/ntuple

graf2d/graf/src/TGaxis.cxx
Improve TGaxis doc as requested here: https://github.com/root-project/root/issues/11280
=> [skip-ci] improve TGaxis doc

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RAction.hxx, tree/dataframe/inc/ROOT/RDF/RDefine.hxx, tree/dataframe/inc/ROOT/RDF/RDefineBase.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/inc/ROOT/RDF/RJittedDefine.hxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/src/RDFUtils.cxx, tree/dataframe/test/dataframe_snapshot.cxx
"customCols" is an old denomination that is now confusing.
=> [DF] Rename customCols => colRegister everywhere 

geom/geom/src/TGeoMaterial.cxx
Ports fixes in TGeoMaterial from master to v6-24
All issues currently fixed in master
This PR is related to #11272
=> Porting material changes from master

io/io/src/TFile.cxx, io/io/test/TFileTests.cxx, net/davix/src/TDavixFile.cxx, net/net/src/TNetFile.cxx, net/net/src/TWebFile.cxx, net/netxng/src/TNetXNGFile.cxx
...as well as in TNetFile and TWebFile.
This fixes #10742.
@pcanal can you please suggest a test?
=> [IO] Honor READ_WITHOUT_GLOBALREGISTRATION in TNetXNGFile

tree/ntuple/v7/doc/specifications.md
=> improve RNTuple CRC32 checksum description

tree/dataframe/src/RDataFrame.cxx, tree/dataframe/src/RLoopManager.cxx
Users are usually not interested in this level of detail and
they will typically use log level kInfo.
=> [DF] Move logging of each task to debug log level 

requirements.txt
=> Bump minimum Dask version to 2022.2

builtins/xrootd/CMakeLists.txt
This PR is a backport of PR #11328 for `v6.26`.
=> [cmake] Update XRootD to v5.5.0

geom/geom/src/TGeoMaterial.cxx
Synchronizes all changes dome in the materials.
This PR is requested in #11272
=> [geom] Putting in sync the materials implementation file with the master

tmva/sofie/inc/TMVA/SOFIE_common.hxx
Broadcast the bias of a Conv or ConvTranspose operator when the input image is batched and there's no Session class.
=> [TMVA][SOFIE] Broadcast bias of Conv and ConvTranspose operators

tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/EmitFromKeras.cxx, tmva/pymva/test/TestRModelParserKeras.C, tmva/pymva/test/generateKerasModels.py, tmva/sofie/inc/TMVA/ROperator_LeakyRelu.hxx
This PR adds support for parsing activation functions like Softmax, LeakyRelu and Tanh in SOFIE Keras parser.
=> [TMVA][SOFIE] Support for parsing Softmax, LeakyRelu, and Tanh in Keras parser

roofit/histfactory/inc/RooStats/HistFactory/RooBarlowBeestonLL.h, roofit/histfactory/inc/RooStats/HistFactory/Sample.h, roofit/histfactory/src/HistFactoryModelUtils.cxx, roofit/histfactory/src/HistFactoryNavigation.cxx, roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx, roofit/histfactory/src/RooBarlowBeestonLL.cxx, roofit/histfactory/src/Sample.cxx
This PR avoids all calls to `delete` in HistFactory.
=> [RF] Use less manual memory allocation in HistFactory

hist/hist/src/THnBase.cxx, tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
The sum of weight, weight square and weigth * x used for statistics computation where not update when adding/merging THnBase classes.
This fixes #11333
=> [hist] Fix in THnBase::Add the computation of the running sums

hist/hist/src/HFitImpl.cxx
This PR fixes for #11304
The code handling the fitting option is improved separting better options for graphs and for histograms
=> [hist] Fix correct handling of fitting option WW

core/unix/src/TUnixSystem.cxx, math/matrix/src/TDecompLU.cxx, proof/proofplayer/src/TProofDraw.cxx
Let compile 6.26 branch on latest OpenSUSE Tumbleweed
=> Backport several fixes to 6.26 

tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/src/RDFHelpers.cxx, tree/dataframe/src/RLoopManager.cxx
I am not a fan of the boolean switch now passed to `RLoopManager::Run`, but I could not think of anything else.
=> [DF] Add logging to RunGraphs

cmake/modules/SearchInstalledSoftware.cmake
Backport of https://github.com/root-project/root/pull/11452
=> Update minimum dask version found with cmake

tree/readspeed/src/ReadSpeed.cxx, tree/readspeed/src/ReadSpeedCLI.cxx, tree/readspeed/test/readspeed_general.cxx
I extracted this commit from #11451 so it can be reviewed and merged on its own, since the nightly builds are affected by this issue.
=> [readspeed] Fix readspeed in noimt builds

hist/hist/inc/TSpline.h
Make `GetCoeff` `const` in `TSpline3` and `TSpline5`.
=> TSpline: make GetCoeff const

tree/dataframe/src/RDFColumnRegister.cxx
Before gcc 7.3 there is an issue passing a non-movable pair<string, unique_ptr<T>> into unordered_map::insert. A standalone reproducer is at https://godbolt.org/z/1ror6sqPx .
This patch works around it by using operator[] + assignment instead.
=> [DF] Fix RDF compilation with gcc < 7.3

js/build/jsroot.js, js/changes.md, js/modules/base/base3d.mjs, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/more.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/geom/csg.mjs, js/modules/geom/geobase.mjs, js/modules/hist/TH3Painter.mjs, js/modules/io.mjs, js/modules/three.mjs, ui5/eve7/lib/OutlinePassEve.js
Fix two bugs with composite shape in jsroot
Adjust eve7 code
=> [jsroot] update three.js to r145

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
This should fix the breakage seen across all platforms.
=> Add missing import to TMVA pythonizations

core/base/inc/TAttMarker.h, core/base/src/TAttMarker.cxx
Improve SetMarkerSize doc.
Fix typos.
=> [skip-ci] improve TAttMarker doc

tree/dataframe/inc/ROOT/RDF/RRange.hxx, tree/dataframe/test/dataframe_ranges.cxx
This fixes https://github.com/root-project/root/issues/11508.
=> [DF] Fix event selection in case of Range with stride

tree/dataframe/inc/ROOT/RDF/RRange.hxx, tree/dataframe/test/dataframe_ranges.cxx
This fixes https://github.com/root-project/root/issues/11508.
=> [DF] Fix event selection in case of Range with stride (v6.26)

tutorials/tmva/TMVA_SOFIE_RDataFrame.py
=> [tutorials] Simplify TMVA_SOFIE_RDataFrame.py.

tree/dataframe/inc/ROOT/RDF/RDefineReader.hxx
In line with what we did in https://github.com/root-project/root/pull/11217 .
=> [DF] Prefer the term "defined columns" to "custom columns"

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx, core/base/inc/Rtypes.h, core/clingutils/res/TClingUtils.h, core/clingutils/src/TClingUtils.cxx, core/doc/v600/index.md, core/foundation/test/FoundationUtilsTests.cxx, core/gui/src/TBrowser.cxx, core/imt/inc/ROOT/TThreadExecutor.hxx, core/imt/src/TThreadExecutor.cxx, core/metacling/src/TClingClassInfo.h, core/sanitizer/README.md, core/textinput/src/textinput/TerminalDisplay.cpp, core/winnt/src/TWinNTSystem.cxx, documentation/HttpServer/HttpServer.md, gui/doc/v600/index.md, hist/hist/src/TH1.cxx, math/genvector/doc/index.md, roofit/roofitcore/src/RooAbsCategoryLValue.cxx, roofit/roostats/inc/RooStats/PointSetInterval.h, roofit/roostats/inc/RooStats/ProfileLikelihoodTestStat.h, tree/dataframe/inc/ROOT/RDataFrame.hxx, tree/tree/src/TTree.cxx
=> [core/misc] fix some more doxygen warnings

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py, bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooTreeDataStore.cxx, roofit/roostats/src/SPlot.cxx
1. https://github.com/root-project/root/pull/11507
2. https://github.com/root-project/root/pull/10811
3. https://github.com/root-project/root/pull/11531
Except for the second commit that fixes something that was introduced in the 6.28 development cycle
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 23

tree/tree/inc/TBranch.h, tree/tree/src/TBranch.cxx
This fixes #8962
The code pattern is similar to 0987896c2d8d49a0e5723ee2ac792eb33fa3ee34
Add infrastructure for sharing memory in a TBuffer.
=> Add support for Bulk I/O with SetClusterPrefetch

hist/histpainter/inc/TPaletteAxis.h, hist/histpainter/src/TPaletteAxis.cxx
Complete the TPaletteAxis menu.
=> TPaletteAxis menu update

tmva/sofie/test/CMakeLists.txt
This Pull request should fix a failure seen in the nortcxxmod builds
=> [tmva][sofie] Fix SOFIE tests for nortcxxmodules

bindings/jupyroot/python/JupyROOT/helpers/utils.py, bindings/jupyroot/python/JupyROOT/kernel/rootkernel.py
Fixes #11048 according to the LGTM report:
https://lgtm.com/projects/g/root-project/root/rev/pr-90c6dd66f4cf355944bc8bc93a3e2749fe003f60
=> [JupyROOT][11048] Fixes in imports

roofit/roofitcore/inc/RooAbsCachedPdf.h, roofit/roofitcore/inc/RooAbsCachedReal.h, roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/src/RooAbsCachedPdf.cxx, roofit/roofitcore/src/RooAbsCachedReal.cxx, roofit/roofitcore/src/RooDataHist.cxx
=> [RF] Cleanup of RooDataHist

README/ReleaseNotes/v628/index.md, gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx, gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayArgs.cxx, gui/webdisplay/src/RWebDisplayHandle.cxx
It behaves exactly as Chrome
Provided only on Windows
Update release notes
=> [webgui] Introduce MS Edge browser support

tmva/sofie/inc/TMVA/ROperator_BasicBinary.hxx
Like seen here: https://github.com/root-project/root/pull/11561#issuecomment-1278788221
=> [sofie] fix compiler override warnings

interpreter/cling/tools/plugins/clad/CMakeLists.txt
This new release includes some improvements:
* Add support for pushforward- and pullback-style functions
* More supported constructs in forward and reverse mode
* Forward mode support for CUDA programs
* AD-based Floating Point Error Estimation Framework
* Integration with Enzyme
See more at: https://github.com/vgvassilev/clad/blob/v1.0/docs/internalDocs/ReleaseNotes.md
=> [clad] Bump clad version to v1.0.

.github/CODEOWNERS, core/imt/inc/ROOT/RSlotStack.hxx, main/CMakeLists.txt, tree/dataframe/src/RLoopManager.cxx, tree/readspeed/README.md, tree/readspeed/src/ReadSpeed.cxx, tree/readspeed/src/ReadSpeedCLI.cxx, tree/readspeed/test/readspeed_general.cxx
This PR is better reviewed commit by commit.
=> [readspeed] Misc improvements and fixes

config/thisroot.sh
See https://root-forum.cern.ch/t/problem-while-building-root-from-source/51895/4
=> clarify error message with bash

tmva/sofie_parsers/src/RModelParser_ONNX.cxx
=> [TMVA][SOFIE] Bring back Flatten, Squeeze, Unsqueeze and fix fused operators

core/base/inc/TSystem.h, core/base/src/TDirectory.cxx, core/base/src/TErrorDefaultHandler.cxx, core/base/src/TStorage.cxx, core/base/src/TSystem.cxx, core/foundation/src/TError.cxx, core/rint/src/TRint.cxx, core/unix/inc/TUnixSystem.h, core/winnt/inc/TWinNTSystem.h
In some corner cases, there might be some nullptr access problems. This solves the warnings found by clang-tidy
=> [core/base] Null ptr access safety

bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx, bindings/pyroot/cppyy/patches/gc_flags.patch
Backport of https://github.com/root-project/root/pull/11457
=> [PyROOT][6.26] Fixes for garbage collection in Python 3.11 (backport)

builtins/xrootd/CMakeLists.txt
This PR is a backport of PR #11613 for `v6.26`.
=> [cmake] Update XRootD to v5.5.1

hist/hist/inc/TH2Poly.h, hist/hist/src/TH2Poly.cxx
It was not clear in Doxygen which methods are not implemented in TH2Poly.
=> [skip-ci] clarify which methods are not implemented in TH2Poly

graf2d/graf/inc/TArrow.h, graf2d/graf/src/TArrow.cxx, graf2d/graf/src/TGaxis.cxx
Implement arrow on axis as requested here:
https://github.com/root-project/root/issues/11634
=> Arrow on axis

hist/hist/src/TGraph.cxx, hist/histpainter/src/TGraphPainter.cxx
requested here: https://root-forum.cern.ch/t/tgraph-synchronization/52211/4
=> [slip-ci] Improve the graph figures (add titles)

core/metacling/src/TCling.cxx
macOS 13 again moves many libraries into the binary blob: these files do not exist anymore on disk, but the linker "knows what to do". Linking against them would fail ("file not found"), so rely on the non-system libraries to pull them in. An exception are /usr/lib/system/libsystem_... which *do* exist on disk but must not be linked against.
(cherry picked from commit 00232a0ca4fdfea2b813158f2406a33ef3e2512b) (cherry picked from commit 43016f031b870f7ea1f30a245b8072017af485bb)
v6.26 backport of https://github.com/root-project/root/pull/11527
=> [ACLiC] For macOS, make sure the syslib exists (v6.26)

hist/hist/inc/THStack.h, hist/hist/src/THStack.cxx, tutorials/graphics/mandelbrot.C, tutorials/hist/ContourList.C, tutorials/hist/th2polyEurope.C
It generates all stack primitives - axis histogram and legend as Paint
method does, but does not perform Paint. 
Will be used in TWebCanvas.
Replace NULL by nullptr in hist tutorials
=> [hist] provide THStack::BuildPrimitives() method

core/base/src/TFolder.cxx, core/base/src/TTask.cxx, core/thread/src/TThread.cxx
fix https://github.com/root-project/root/issues/11663#event-7775318665
=> [skip-ci] Make TTask and TThread legacy

core/base/src/TStyle.cxx
Always use type of argument of setter method - do not mix int and bool. 
Add special hook to store boolean argument
=> Adjust TStyle::SavePrimitve

gui/canvaspainter/src/RCanvasPainter.cxx, gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/modules/base/TAttLineHandler.mjs, js/modules/base/TAttMarkerHandler.mjs, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/THistPainter.mjs, tutorials/graphics/canvas2.C, tutorials/graphics/gtime.C, tutorials/graphics/latex3.C, tutorials/graphics/markerwarning.C, tutorials/graphics/palettes.C, tutorials/graphics/triangles.C, ui5/canv/controller/Canvas.controller.js, ui5/canv/view/Canvas.view.xml
1. Y-axis range with histogram without content
2. Do not create title when not required (especially for TGraph)
3. Provide "Clear canvas", "Clear pad" and "Interrupt" menu items
4. Editing line attributes in GED - correctly update on ROOT side
5. Handling of complex TLatex like `{a}_{b}^{e}^{2}`
6. Adjust several tutorials
7. Update JSROOT
=> [webcanvas] better support of macros from `tutorials/graphics/` folder

graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx
Canvas height was not checked
Do not create execs when not necessary in TPad
Adjust TCanvas.cxx - use nullptr
=> Fix TPad::ResizePad() method

documentation/doxygen/filter.cxx
several functions have a return value that was not used/checked. This generated waring with the recent compilers.
Also, `sprintf` is deprecated.
=> There were several warnings in filter.cxx

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/inc/TWebPadOptions.h, gui/webgui6/src/TWebCanvas.cxx, hist/hist/src/THStack.cxx, js/build/jsroot.js, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/geom/csg.mjs, js/modules/geom/geobase.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/RH2Painter.mjs, js/modules/hist/RH3Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TGraphPainter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/hist2d/TMultiGraphPainter.mjs
All these classes using additional histogram to draw axes, therefore one need to create and access such 
histogram before drawing object in web canvas.
web canvas can address these histograms for context menu or when axis attributes are changed
Special handling of zoomed axis implemented. When necessary, `fMinimum`/`fMaximum` members are changed
=> [webcanvas] special handling of THStack, TMultiGraph, TGraph classes

roofit/roofitcore/src/RooAbsPdf.cxx
When iterating over the `clients()` to clear the clients caches, the list of clients itself might also be changed during the iteration. We therefore can't do a range-based loop.
This fixes the last remaining RooFit ASAN build failure in `testRooAddPdf`.
This is a followup to efd468b4947.
=> [RF] Account for mutation of client list within `sterilizeClientCaches`

tree/ntuple/v7/src/RField.cxx
Fix compilation error on MSVC after the merge of https://github.com/root-project/root/pull/11756.
=> Fix compilation error on Windows

core/base/src/TTask.cxx
=> TTask: don't assume that the list only contains TTask objects

js/build/jsroot.js, js/modules/core.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/hist2d/TH2Painter.mjs, ui5/canv/controller/Canvas.controller.js, ui5/canv/controller/CanvasPanel.controller.js, ui5/canv/controller/Panel.controller.js
Also exclude multiple import of JSROOT functionality for such side panel
=> [webcanvas] Fix TH2 projection drawing [skip-ci]

core/metacling/src/TClingBaseClassInfo.cxx, core/metacling/src/TClingBaseClassInfo.h
Replace casting of pointers to long that cannot work on Windows 64 bit (where pointers are 64 bit and long 32 bit)
=> Replace a couple of long by intptr_t

core/base/inc/Rtypes.h
allows to switch behavior based on the class version with `if constexpr`.
=> [base] Make ClassDef `Class_Version()` constexpr:

graf2d/x11/src/Rotated.cxx, math/foam/inc/TFoam.h, tmva/tmva/inc/TMVA/PDEFoam.h, tree/readspeed/src/ReadSpeed.cxx
=> Fix clang-15 warnings

gui/webdisplay/CMakeLists.txt
=> [webgui] add Net to list of librariy dependency

roofit/roofitcore/inc/RooHist.h, roofit/roofitcore/src/RooHist.cxx
Closes JIRA ticket ROOT-5805:
https://sft.its.cern.ch/jira/browse/ROOT-5805
=> [RF] Multiple small fixes to `RooHist`

.github/CODEOWNERS
=> [codeowners] for bindings/, Enric => [Vincenzo, me].

CMakeLists.txt, core/foundation/inc/RtypesCore.h
(cherry picked from commit e11fb101e6edc7616798efe253be733aef2f6197)# This Pull request:
=> [cmake] Regularize cmake output for internet check.

roofit/roofit/inc/RooLagrangianMorphFunc.h, roofit/roofit/src/RooLagrangianMorphFunc.cxx, roofit/roofitcore/inc/RooPolyFunc.h, roofit/roofitcore/src/RooPolyFunc.cxx
Adds small improvements to RooLagrangianMorphing and RooPolyFunc.
- RooLagrangianMorphing now allows observable names to be controlled more explicitly
- RooLagrangianMorphing now correctly handles normalization sets
- RooPolyFunc now provides a method to obtain the function as a string
=> [RF] RooLagrangianMorphing improvements

core/base/inc/TVirtualPad.h, core/base/src/TVirtualPad.cxx, documentation/users-guide/Graphics.md, graf2d/asimage/src/TASImage.cxx, graf2d/gpad/inc/TSlider.h, graf2d/gpad/src/TButton.cxx, graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TCreatePrimitives.cxx, graf2d/gpad/src/TInspectCanvas.cxx, graf2d/gpad/src/TRatioPlot.cxx, graf2d/gpad/src/TSlider.cxx, gui/fitpanel/src/TFitParametersDialog.cxx, gui/fitpanelv7/src/RFitPanel.cxx, gui/ged/src/TF1Editor.cxx, gui/gui/src/TRootBrowserLite.cxx, gui/gui/src/TRootCanvas.cxx, gui/gui/src/TRootContextMenu.cxx, gui/recorder/src/TRecorder.cxx, gui/webgui6/src/TWebCanvas.cxx, hist/hist/src/TF1.cxx, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx, tree/treeplayer/src/TFileDrawMap.cxx
Also fix `TSlider::SavePrimitive` method
Fix example in `Graphics.md` documentation
=> Use `gPad` and `TVirtualPad::TContext` in gui/hist/graf2d classes

README/ReleaseNotes/v628/index.md, geom/geom/inc/TGeoManager.h, geom/geom/src/TGeoManager.cxx, geom/webviewer/inc/ROOT/RGeomViewer.hxx, geom/webviewer/src/RGeoPainter.cxx, geom/webviewer/src/RGeomViewer.cxx, gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayHandle.cxx, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/files/geom_batch.htm, js/modules/geom/TGeoPainter.mjs, js/modules/main.mjs
Support batch mode in `RGeomViewer`. In such mode only png/jpeg images can be produced from GL drawing done with headless web browser. Just do in the macro:
```
ROOT::Experimental::RGeomViewer viewer(geom);
viewer.SaveImage("rootgeom.jpeg", 800, 600);
```
Support geometry drawings inside web canvas. Also with `TWebCanvas` batch image production which includes geometry is possible now.
=> Batch image productions with `RGeomViewer`

roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooClassFactory.h, roofit/roofitcore/inc/RooCustomizer.h, roofit/roofitcore/inc/RooSimWSTool.h, roofit/roofitcore/src/RooClassFactory.cxx, roofit/roofitcore/src/RooCustomizer.cxx, roofit/roofitcore/src/RooSimWSTool.cxx
* modernize memory management
* don't define factory interfaces in header files
* remove unneeded base classes, LinkDef entries, and ClassDefs for helper classes
=> [RF] Technical improvements to `RooWorkspace`-related helper classes

roofit/roofit/inc/LinkDef1.h, roofit/roofit/inc/RooLagrangianMorphFunc.h, roofit/roofit/src/RooLagrangianMorphFunc.cxx, roofit/roofitcore/src/RooClassFactory.cxx, roofit/roofitcore/src/RooFactoryWSTool.cxx, tutorials/roofit/rf512_wsfactory_oper.C, tutorials/roofit/rf512_wsfactory_oper.py
This is to avoid having to do hacks with the `RooStringVar`.
Closes #9845.
=> [RF] Implement proper factory interface for RooLagrangianMorphFunc

geom/webviewer/inc/ROOT/RGeoPainter.hxx, geom/webviewer/inc/ROOT/RGeomData.hxx, geom/webviewer/inc/ROOT/RGeomViewer.hxx, geom/webviewer/src/RGeoPainter.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gui/HierarchyPainter.mjs
Apply JSROOT release 7.3.0
Handle top node visibility in web geom painter
When drawing top volume, add geo manager itself to canvas
=> JSROOT 7.3.0, improve web geom painter

core/gui/src/TGuiFactory.cxx, etc/plugins/TControlBarImp/P010_TWebControlBar.C, graf2d/gpad/src/TControlBar.cxx, gui/webgui6/CMakeLists.txt, gui/webgui6/inc/LinkDef.h, gui/webgui6/inc/TWebControlBar.h, gui/webgui6/src/TWebControlBar.cxx, ui5/canv/ctrlbar.html
It is very old component, but still used in several demos.
Implementation is trivial - just list of HTML buttons and clicks handling.
Support vertical and horizontal direction.
After this PR one will be able directly use `tutorials/geom/geodemo.C` in web mode.
=> Provide web-based implementation for `TControlBar`

gui/browsable/src/TObjectElement.cxx, ui5/browser/controller/Browser.controller.js
Add possibility to select default draw option for the classes. 
Use default draw options from the beginning for `TH1` and `TProfile`
=> [rbrowser] use default draw options for `TH1` and `TProfile`

tutorials/geom/csgdemo.C, tutorials/geom/geodemo.C
Let reuse same canvas for different drawings
Use TString operations
Provide shortcuts to fill objects infos
Minimal adjustment to be able run with `root --web` mode
=> Update `geom/geodemo.C` and `geom/csgdemo.C` tutorials [skip-ci]

tmva/tmva/CMakeLists.txt, tmva/tmva/inc/TMVA/RSofieReader.hxx
Add a new class in TMVA , RSofieReader which giving an input model in ONNX, Keras or PyTorch format, compiles with the interpreter and provides a member function `Compute` to evaluate the model.
=> [tmva][sofie] Add RSofieReader class in TMVA

tmva/sofie/src/SOFIE_common.cxx
This Pull request fixes an issue in broadcasting
=> [tmva][sofie] Fix a bug in the MultiDirectionalBradcast function of SOFIE_Common

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs
Fix geometry update when drawn inside canvas
=> [jsroot] fix TGeo update in TWebCanvas [skip-ci]

tutorials/roostats/ModelInspector.C, tutorials/roostats/OneSidedFrequentistUpperLimitWithBands.C, tutorials/roostats/StandardBayesianMCMCDemo.C, tutorials/roostats/StandardBayesianNumericalDemo.C, tutorials/roostats/StandardFeldmanCousinsDemo.C, tutorials/roostats/StandardFrequentistDiscovery.C, tutorials/roostats/StandardHistFactoryPlotsWithCategories.C, tutorials/roostats/StandardHypoTestDemo.C, tutorials/roostats/StandardHypoTestInvDemo.C, tutorials/roostats/StandardProfileInspectorDemo.C, tutorials/roostats/StandardProfileLikelihoodDemo.C, tutorials/roostats/StandardTestStatDistributionDemo.C, tutorials/roostats/TwoSidedFrequentistUpperLimitWithBands.C
To be merged after the PR #11942
=> [skip-ci] Allow to run the roostats tutorials who are using the prepareHistFactory script on Windows

math/mathcore/inc/Math/Random.h
=> Fix compilation with gcc13.

roofit/roofit/inc/RooLandau.h, roofit/roofit/src/RooLandau.cxx, roofit/roofit/test/CMakeLists.txt, roofit/roofit/test/testRooCrystalBall.cxx, roofit/roofit/test/testRooLandau.cxx, roofit/roofitcore/inc/RooNumConvPdf.h, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooNumConvPdf.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitcore/src/RooRealVar.cxx, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/src/RooVectorDataStore.cxx, roofit/roofitcore/test/TestStatistics/RooRealL.cpp, roofit/roofitcore/test/testRooDataHist.cxx, roofit/roofitcore/test/testRooDataSet.cxx, roofit/roofitcore/test/testRooFormula.cxx, roofit/roofitcore/test/testWorkspace.cxx, test/stressRooFit_tests.h, tutorials/roofit/rf901_numintconfig.C, tutorials/roofit/rf901_numintconfig.py
I did a local update of root/master with this, i was not able to compile locally on my mac for few other reasons. Suggestions on changes and checks to add welcome. 
Add the CDF calls from Math/ProbFunc  to speed up the integrals of RooLandau PDFs. 
Code has been used in on-going analysis at LHCb, with significant speed-up 
=> [RF] Add analytical integral for RooLandau

roofit/roofitcore/src/RooAbsArg.cxx
In the implementation of `RooAbsArg::recursiveRedirectServers` a static variable was used to check for cyclic recursion. This is not thread safe an should be avoided. The problem is solved by creating a new `recursiveRedirectServersImpl` function that takes the `callStack` variable also as an argument, and this variable is instantiated separately in each `recursiveRedirectServers` call.
Since the code was touched and moved anyway, the implementation of `recursiveRedirectServers` was formatted with clang-format.
=> [RF] Make `RooAbsArg::recursiveRedirectServers` thread safe

roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooGlobalFunc.h, roofit/roofitcore/inc/RooNLLVar.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/test/testRooDataHist.cxx, roofit/roofitcore/test/testTestStatistics.cxx
=> [RF] Completely implement `Offset("bin")` feature for fits to RooDataHist

geom/gdml/src/TGDMLWrite.cxx
Fixes material handling when writing GDML.
This should already have been part of PR 11060.
Output GDML understood by Geant4
=> Remove renormalization which should have been part of PR 11060

tree/ntuple/v7/inc/ROOT/RDaos.hxx, tree/ntuple/v7/test/CustomStruct.hxx
Fixes compilation error with gcc 13.
~~~
In file included from .../root-6.26.10/tree/ntuple/v7/test/CustomStruct.cxx:1: .../root-6.26.10/tree/ntuple/v7/test/CustomStruct.hxx:40:24: error: 'uint32_t' does not name a type
40 | namespace SG { typedef uint32_t sgkey_t; }
|                        ^~~~~~~~
.../root-6.26.10/tree/ntuple/v7/test/CustomStruct.hxx:6:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
5 | #include <vector>
+++ |+#include <cstdint>
6 |
.../root-6.26.10/tree/ntuple/v7/test/CustomStruct.hxx:43:4: error: 'uint8_t' does not name a type
43 |    uint8_t m_nbits, m_nmantissa;
|    ^~~~~~~
.../root-6.26.10/tree/ntuple/v7/test/CustomStruct.hxx:43:4: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include …
=> Add missing #include <cstdint>

graf3d/eve7/src/REveGeoShape.cxx, graf3d/eve7/src/REvePointSet.cxx
This PR is back port of  #12060
=> REve backport fixes in v6-28-00-patches

core/dictgen/src/rootcling_impl.cxx
During ROOT's build of Core.pcm, byproduct modules are built. rootcling was complaining about some headers not appearing in Core.pcm, despite them ending up in the byproduct pcms.
Simply don't complain about headers not in the pcm if these headers are actually in a byproduct. In the same vein, do not forcefully include them in teh pcm, as they are already included in the byproduct which should be sufficient.
This circumvents the warnings:
```
[2751/6001] Generating G__Core.cxx, ../lib/Core.pcm
Warning in <CheckModuleValid>: after creating module "Core" the following headers are not part of that module:
strlcpy.h (already part of top-level module "ROOT_Foundation_C")
snprintf.h (already part of top-level module "ROOT_Foundation_C")
ESTLType.h (already part of top-level module …
```
=> [dictgen] Do not complain about headers in byproducts:

interpreter/cling/tools/plugins/clad/CMakeLists.txt
This new release includes some improvements:
* Improvements in the array handling in the Error Estimation Framework
* Fixed numerical stability of the pow pushforward
* Fixed handling of for-loop conditions in reverse mode
* LLVM15 Support
See more at: https://github.com/vgvassilev/clad/blob/v1.1/docs/internalDocs/ReleaseNotes.md
=> [clad] Bump clad version to v1.1.

gui/browsable/src/TDirectoryElement.cxx, tutorials/v7/filedialog.cxx
=> Fix RFileDialog [6.28]

gui/browsable/src/TDirectoryElement.cxx, tutorials/v7/filedialog.cxx
=> Fix `RFileDialog` [626]

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
This makes all functions end up in the same text section, which is important for TCling on macOS to catch exceptions from constructors: Stack unwinding requires information about program addresses to find out which objects to destroy and what code should be called to handle the exception. These addresses are relocated against a single __text section when loading the produced MachO binary, which breaks if the call sites of global constructors end up in a separate init section.
Fixes ROOT-10703 and ROOT-10962
(cherry picked from commit 028fcca0fa76111877751df876cf13968be602f9)
=> Reset function sections before JITting

core/clingutils/src/RStl.cxx, core/clingutils/src/TClingUtils.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TClingBaseClassInfo.cxx, core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingClassInfo.cxx, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/src/TClingDeclInfo.cxx, core/metacling/src/TClingMethodArgInfo.cxx, core/metacling/src/TClingMethodInfo.cxx, core/metacling/src/TClingTypeInfo.cxx, core/metacling/src/TClingTypedefInfo.cxx, core/rint/src/TRint.cxx, core/rint/src/TTabCom.cxx, interpreter/cling/lib/Interpreter/LookupHelper.cpp
=> [core/cling] modernize nullptr

tree/dataframe/src/RRootDS.cxx
Fixes https://github.com/root-project/root/issues/11971
leftover from https://github.com/root-project/root/commit/b1257ba27a7139e0c927693fded3b243b3f94b33
Unused variable, found by HenryDayHall
=> [DF] Remove unused variable in `RRootDS.cxx`

core/dictgen/src/rootcling_impl.cxx
During ROOT's build of Core.pcm, byproduct modules are built. rootcling was complaining about some headers not appearing in Core.pcm, despite them ending up in the byproduct pcms.
Simply don't complain about headers not in the pcm if these headers are actually in a byproduct. In the same vein, do not forcefully include them in teh pcm, as they are already included in the byproduct which should be sufficient.
This circumvents the warnings:
```
[2751/6001] Generating G__Core.cxx, ../lib/Core.pcm
Warning in <CheckModuleValid>: after creating module "Core" the following headers are not part of that module:
strlcpy.h (already part of top-level module "ROOT_Foundation_C")
snprintf.h (already part of top-level module "ROOT_Foundation_C")
ESTLType.h (already part of top-level module …
```
=> v6.28: [dictgen] Do not complain about headers in byproducts:

README/ReleaseNotes/v628/index.md
Please lmk if you want affiliations changed. FYI, @HDembinski @SimeonEhrig @matthewfeickert @olifre @sayang14 @weliveindetail @ShamrockLee @Moelf @mrexodia @tapaswenipathak @dkpoult @mphschmitt @Neel-Shah-29 @petrstepanov @saisoma123 @andriish @fwinkl @junaire 
And thank you 💐 for your contributions to ROOT v6.28 - much appreciated!
=> [RelNotes] Add all known contributors with >1 commit (NFC). [skip-ci]

core/macosx/CMakeLists.txt
=> Add missing include in core/macosx/CMakelists.txt

math/mathcore/inc/Math/CladDerivator.h, math/mathcore/test/CladDerivatorTests.cxx
This Pull request: updates `CladDerivator.h` to follow Clad custom derivative where all functions are based on pushforwards and pullbacks.
- [ X] tested changes locally
This PR fixes #  https://github.com/vgvassilev/clad/issues/510
=> Update `CladDerivator.h` to the pushforward/pullback model

roofit/batchcompute/src/Batches.h, roofit/batchcompute/src/RooBatchCompute.cxx, roofit/roofitcore/inc/RooBinSamplingPdf.h, roofit/roofitcore/src/RooBinSamplingPdf.cxx, roofit/roofitcore/test/testRooBinSamplingPdf.cxx
=> [RF] Final changes to make the ATLAS benchmarks run with `BatchMode`

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/roofit/inc/RooBMixDecay.h, roofit/roofit/src/RooBMixDecay.cxx
It was validated with the unbinned benchmarks in `rootbench` that the
implementation is correct.
=> [RF] Implement `RooBMixDecay` in RooBatchCompute for GPU support

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/src/Batches.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/batchcompute/src/RooBatchCompute.cxx, roofit/histfactory/src/HistFactoryNavigation.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.h, roofit/roofit/inc/RooBMixDecay.h, roofit/roofit/inc/RooExpPoly.h, roofit/roofit/inc/RooPower.h, roofit/roofit/src/RooBMixDecay.cxx, roofit/roofit/src/RooMomentMorphFuncND.cxx, roofit/roofit/src/RooMomentMorphND.cxx, roofit/roofitcore/inc/RooBinSamplingPdf.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooBinnedL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooSubsidiaryL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooSumL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooBinSamplingPdf.cxx, roofit/roofitcore/test/testRooBinSamplingPdf.cxx
This is a backport of all the relevant RooFit PRs that were recently merged to master to v6-28-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/12160
2. https://github.com/root-project/root/pull/12157
3. https://github.com/root-project/root/pull/12161
4. https://github.com/root-project/root/pull/12129
Related to https://github.com/root-project/root/issues/11856.
=> [v628][RF] Backports of RooFit PRs to `v6-28-00-patches`: Part 10

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
=> [DF][PyROOT] Avoid deprecated numpy.object

tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx, tree/dataframe/inc/ROOT/RDF/RSampleInfo.hxx, tree/dataframe/src/RDatasetGroup.cxx, tree/dataframe/src/RDatasetSpec.cxx, tree/dataframe/src/RLoopManager.cxx
Backport of https://github.com/root-project/root/pull/12174
=> 6.28: [DF] Remove performance overhead in construction of RSampleInfo

tmva/sofie/inc/TMVA/ROperator_ConvTranspose.icc, tmva/sofie/inc/TMVA/ROperator_Gather.hxx, tmva/sofie/inc/TMVA/ROperator_Reshape.hxx, tmva/sofie/src/SOFIE_common.cxx, tmva/sofie_parsers/src/ParseGather.cxx, tmva/sofie_parsers/src/ParseReshape.cxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
This Pull request fixes some issues fond with valgrind in the ConvTranspose operator
and fixes the Gather and Reshap operators
=> [tmva][sofie] Fix Gather and Squeeze operators and some memory issues in ConvTranspose

interpreter/cling/include/cling/std.modulemap
=> Add variant to the modulemap to address a cmssw-related issue.

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
This PR simplifies the trait whether an `RField` is mappable. It furthermore simplifies the use of this trait inside `RNTupleView`
=> [ntuple] Refactor Internal::IsMappable for RNTupleView

roofit/xroofit/inc/RooBrowser.h
Trying to make a documentation page for RooBrowser
=> [RF] Fix documentation for RooBrowser

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
It results in relocation targets that are out-of-range.
=> [cling] Switch back to large code model for macOS on AArch64

roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/roofit/inc/RooPolynomial.h
=> [RF] Support RooPolynomial in RooFit JSON IO and improve test suite

tmva/pymva/src/PyMethodBase.cxx, tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/testPyKerasClassification.C, tmva/pymva/test/testPyKerasMulticlass.C, tmva/pymva/test/testPyKerasRegression.C, tmva/pymva/test/testPyTorchClassification.C, tmva/pymva/test/testPyTorchMulticlass.C, tmva/pymva/test/testPyTorchRegression.C
This PR backport a commit of #10226 to use Keras model with not defined batch size
=> [tmva][pymva] Backport in 6.26 support in the Keras RModel parser to models with undefined batch size

hist/hist/inc/TGraph.h
MENU was missing on TGraph::SaveAs
=> MENU was missing on TGraph::SaveAs

documentation/doxygen/Doxyfile
The ROOT.qch file is generated only for master
=> do not generate qch file

tmva/pymva/inc/TMVA/MethodPyKeras.h, tmva/pymva/src/MethodPyKeras.cxx, tmva/pymva/test/testPyKerasClassification.C, tmva/pymva/test/testPyKerasMulticlass.C, tmva/pymva/test/testPyKerasRegression.C, tutorials/tmva/TMVA_CNN_Classification.C, tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/TMVA_Higgs_Classification.C, tutorials/tmva/TMVA_Higgs_Classification.py, tutorials/tmva/TMVA_RNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.py, tutorials/tmva/keras/ClassificationKeras.py, tutorials/tmva/keras/GenerateModel.py, tutorials/tmva/keras/MulticlassKeras.py, tutorials/tmva/keras/RegressionKeras.py
Disable tensorflow eager execution when evaluating the model in MethodPyKeras This speeds up by more than 100 the model prediction.
Re-arrange the code and fixes also a memory leak in allocating the input array
=> [tmva][pymva] Optimize Evaluation in PyKeras

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TArrowPainter.mjs, js/modules/draw/TLinePainter.mjs, js/modules/draw/TRatioPlotPainter.mjs, js/modules/draw/more.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gui/menu.mjs, js/modules/gui/utils.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, ui5/canv/controller/Canvas.controller.js
Now objects like `TText`, `TMarker`, `TPolyMarker`, `TEllipse`, `TLine`, `TPolyLine` and several others
can be moved and context menu can be invoked.
Fix several minors problems
=> [webcanvas] Provide interactivity for several basic classes

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/modules/core.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/THStackPainter.mjs
- Correctly set pad range and pad user range in case of log scale
- Properly set zooming scale to histogram without context
- Fix THStack update problem
=> [webcanvas] fix log2 support

gui/browsable/src/TLeafProvider.hxx, gui/browserv7/inc/ROOT/RBrowser.hxx, js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/geom/geobase.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TMultiGraphPainter.mjs
TTree::Draw expression was mail-formed in some case
Use TWebCanvas by default in RBrowser
Update JSROOT to support more kind of log scale
=> [rbrowser] Fix click in RBrowser on "@size" branch

gui/browsable/src/TLeafProvider.hxx
Backport of small fix from #12312
=> [rbrowser] fix click in `RBrowser` on "@size" branch [6.28]

tutorials/hist/ratioplot1.C
Improve this ratio plot example as requested here: https://github.com/root-project/root/issues/12306
=> [skip-ci] Improve example

hist/hist/inc/TH1K.h
=> Add missing TH1K::RetrieveBinContent 6.28

hist/hist/src/TMultiGraph.cxx, hist/histpainter/src/TGraphPainter.cxx, tutorials/graphs/graphreverse.C
Reversed graphs were not working in log scale. As explained here:
https://github.com/root-project/root/issues/11938
=> Implement reversed graphs for error bars and log scale.

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rtensor.py, bindings/pyroot/pythonizations/test/rtensor.py
This PR allows to convert directly a RTensor from a Numpy array without the need to use the shape.
Example:
```
import ROOT
import numpy as np
x = np.array([[1.,2.],[3.,4.]])
r = ROOT.TMVA.Experimental.RTensor('double')(x)
print(r.GetShape())
```
=> [tmva] Add RTensor constructor from a numpy array

js/build/jsroot.js, js/modules/base/BasePainter.mjs, js/modules/core.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/menu.mjs
Resize/enlarge canvas
Menu for axis label/title sizes
=> [jsroot] fixes from 23/02/2023 [skip-ci]

gui/qt5webdisplay/rootwebpage.h, gui/qt5webdisplay/rootwebview.h, js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TF2.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TEfficiencyPainter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/tree.mjs, tutorials/webgui/qt5web/CMakeLists.txt
1. Much improve TAxis drawings with JSROOT
2. Correctly link tutorials/webgui/qt5web example
3. Small adjustment in qt5web classes
=> Several fixes in webgui

roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3HistFactory.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/roofit/inc/RooTFnBinding.h, roofit/roofitcore/inc/RooMultiVarGaussian.h, roofit/roofitcore/src/RooAbsPdf.cxx, tutorials/roofit/rf515_hfJSON.json
This is one half of a bigger PR: https://github.com/root-project/root/pull/12340.
This half is better merged independently before the other one, because the other half is related only to the HistFactory JSON IO while this set of commits is not.
=> [RF][HS3] Support for more classes and other improvements

roofit/hs3/CMakeLists.txt, roofit/hs3/inc/RooFitHS3/HistFactoryJSONTool.h, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3SimultaneousFit.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/roofitcore/src/RooAbsReal.cxx, tutorials/roofit/rf515_hfJSON.json
The HistFactory implementation of HS3 is updated to conform with the latest draft of the standardization document.
A turnaround of a plain histfactory example in the new style is possible.
=> [RF] Update the HS3 HistFactory implementation

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, tutorials/roofit/rf515_hfJSON.json
Contains bugfixes from assorted use-cases of HS3 JSON conversion.
=> [RF][HS3] Small HS3 closure fixes

bindings/pyroot/pythonizations/python/ROOT/_facade.py
=> Graceful no distrdf v628

tutorials/CMakeLists.txt
This reverts commit 4c669d4ead82c3b328eaebc7f160a119c4dad31d.
Fixes #10061
=> Revert "[DF] Disable also distributed tutorials on Mac ARM"

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, tree/dataframe/CMakeLists.txt, tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx, tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/inc/ROOT/RDF/RMetaData.hxx, tree/dataframe/inc/ROOT/RDF/RSample.hxx, tree/dataframe/inc/ROOT/RDF/RSampleInfo.hxx, tree/dataframe/src/RDataFrame.cxx, tree/dataframe/src/RDatasetSpec.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/src/RSample.cxx, tree/dataframe/test/dataframe_datasetspec.cxx, tree/dataframe/test/dataframe_datasetspec.py, tree/dataframe/test/spec.json
This PR is split in two parts
* Changing occurences of "group" to "sample" everywhere
* Making sure the user specification conforms to the current discussion at #11624
=> Enforce 'sample' concept in the specification

geom/webviewer/CMakeLists.txt, geom/webviewer/inc/LinkDef.h, geom/webviewer/inc/ROOT/RGeoPainter.hxx, geom/webviewer/inc/ROOT/RGeomData.hxx, geom/webviewer/inc/ROOT/RGeomHierarchy.hxx, geom/webviewer/inc/ROOT/RGeomViewer.hxx, geom/webviewer/src/RGeoPainter.cxx, geom/webviewer/src/RGeomData.cxx, geom/webviewer/src/RGeomHierarchy.cxx, geom/webviewer/src/RGeomViewer.cxx, gui/webdisplay/src/RWebWindow.cxx, js/build/jsroot.js, js/modules/core.mjs, js/modules/geom/geobase.mjs, js/modules/webwindow.mjs, tutorials/webgui/geom/client.html, tutorials/webgui/geom/server.cxx, ui5/browser/model/BrowserModel.js, ui5/geom/controller/GeomHierarchy.controller.js, ui5/geom/controller/GeomViewer.controller.js, ui5/geom/index.html, ui5/geom/lib/ColorBox.js, ui5/geom/model/GeomBrowserModel.js, ui5/geom/view/GeomHierarchy.view.xml, ui5/geom/view/GeomViewer.view.xml
1. Split geometry viewer on two logical parts: hierarchy and drawing
2. Always show full geometry hierarchy
3. Add color and material column to hierarchy view
4. Allow to set top visible volume using context menu
5. Let search volume by name, material, color; use `TRegexp` for search
6. Fix cleanup of embed web window connection when main connection closed
7. Correctly count faces for `TGeoShape` instance, use diagonal as importance measure
=> [webgeom] many improvments in web geometry

gui/browsable/src/TDirectoryElement.cxx, ui5/browser/model/BrowserModel.js
Keep TTree ownership with TDirectory, let correctly cleanup it
=> [rbrowser] do not remove TTree from file when browse it [6.28]

interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/llvm/src/tools/clang/lib/Lex/HeaderSearch.cpp
Backport of https://github.com/root-project/root/pull/12418
=> v628:  Survive header inclusion with unreadable -I elements

.github/workflows/root-ci.yml
Adds a way to do buids from scratch by adding label 'clean-build' to a PR
=> [CI] Add option to force builds from scratch

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/Domains.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, tutorials/roofit/rf515_hfJSON.json
To comply with the HS3 standard version 0.2.
=> [RF][HS3] Migrate top-level fileds from dicts to lists

roofit/roofitcore/test/testRooFuncWrapper.cxx
Enable a previously disabled test to fix it if it still fails.
=> [RF] Enable AD code-gen test for RooFit.

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/test/ntuple_extended.cxx
=> [ntuple] Fixes for 32bit / non-x86_64 builds

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/roofitcore/inc/RooVectorDataStore.h, roofit/roofitcore/src/RooVectorDataStore.cxx, tutorials/roofit/rf515_hfJSON.json
More detail in the commit descriptions
=> [RF][HS3] Fix handling of RooConstVars and (string) attributes in JSONIO

.github/workflows/root-ci.yml
Nightly builds crashing immidiately
=> [CI] Fix nightly builds

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, tutorials/roofit/rf515_hfJSON.json
This fixes some bugs that got introduced by the recent move from dictionaries to arrays.
FYI, @cburgard
=> [RF][HS3] Fixups to JSON IO following up on migration from dicts to arrays

etc/RooFitHS3_wsexportkeys.json, etc/RooFitHS3_wsfactoryexpressions.json, roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx
Extends @guitargeek s fixups with a few small additional bugfixes. 
=> [RF][HS3] Bugfixes

core/base/inc/LinkDef2.h
=> [v628] Allow splitting of TTime objects

core/base/inc/TStyle.h, core/base/src/TStyle.cxx, graf2d/graf/inc/TGaxis.h, graf2d/graf/src/TGaxis.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/geom/bundle.mjs, js/modules/geom/geobase.mjs, js/modules/gpad/TAxisPainter.mjs
Redirect calls to:
* TGaxis::SetMaxDigits()
* TGaxis::GetMaxDigits()
* TGaxis::SetExponentOffset()
Let use these configurations also in TWebCanvas, which has access to
gStyle object
Small adjustment in TStyle class
Implement all these attributes in JSROOT
=> Move to `TStyle` static members from `TGaxis`

requirements.txt
This fixes building ROOT (and installing the prerequisite python packages) e.g. on Alma9.
=> [req.txt] dask needs modern Python: [skip-ci]

tree/dataframe/inc/ROOT/RCsvDS.hxx, tree/dataframe/src/RCsvDS.cxx, tree/dataframe/test/datasource_csv.cxx
...and add a test.
This fixes https://github.com/root-project/root/issues/12520.
=> [DF] Fix wrong data in CSV data source with user-defined column types 

geom/webviewer/inc/ROOT/RGeomData.hxx, geom/webviewer/src/RGeomData.cxx, ui5/geom/controller/GeomHierarchy.controller.js, ui5/geom/model/GeomBrowserModel.js
Show special symbol for selected node like:
=> [webgeom] add indicator for selected node

js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/display.mjs, js/modules/gui/utils.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, ui5/canv/controller/Canvas.controller.js, ui5/canv/controller/CanvasPanel.controller.js, ui5/canv/controller/Panel.controller.js, ui5/canv/view/Canvas.view.xml, ui5/canv/view/CanvasPanel.view.xml, ui5/canv/view/Panel.view.xml
Allows to show both projections at a time.
Also prevents websocket overloading.
Includes jsroot with standalone feature
Resolves #10660
=> [webcanvas] Implement `projxy` feature

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/scripts/geoworker.js
Bugfix release, tagged in JSROOT repository
=> [jsroot] 7.3.1 28/03/2023 [skip-ci] [6.28]

tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
Mimics one of the common user class patterns in CMS AODs.
=> [ntuple] Add unit test for templated user classes

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py
dedent does not work because {log} is not indented.
=> [ci] Print docker invocation; whitespace:

graf2d/graf/src/TArrow.cxx, graf2d/graf/src/TBox.cxx, graf2d/graf/src/TCandle.cxx, graf2d/graf/src/TCrown.cxx, graf2d/graf/src/TCurlyArc.cxx, graf2d/graf/src/TCurlyLine.cxx, graf2d/graf/src/TDiamond.cxx, graf2d/graf/src/TEllipse.cxx, graf2d/graf/src/TFrame.cxx, graf2d/graf/src/TGaxis.cxx, graf2d/graf/src/TGraphPolargram.cxx, graf2d/graf/src/TLatex.cxx, graf2d/graf/src/TLine.cxx, graf2d/graf/src/TMarker.cxx, graf2d/graf/src/TMathText.cxx, graf2d/graf/src/TPave.cxx, graf2d/graf/src/TPaveLabel.cxx, graf2d/graf/src/TPavesText.cxx, graf2d/graf/src/TPie.cxx, graf2d/graf/src/TPieSlice.cxx, graf2d/graf/src/TPolyLine.cxx, graf2d/graf/src/TText.cxx, graf2d/graf/src/TWbox.cxx
Protect graph2d class against gPad==0
=> Gpad protect

.github/workflows/root-ci-config/build_root.py
args.incremen**e**tal -> args.incremental
=> [CI] Fix breaking typo

roofit/histfactory/CMakeLists.txt, roofit/histfactory/inc/RooStats/HistFactory/Detail/HistFactoryImpl.h, roofit/histfactory/src/HistFactoryImpl.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONIO.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3HistFactory.cxx, roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/RooWorkspace.cxx, tutorials/roofit/rf515_hfJSON.json
Fixes various minor bugs in the HS3 implementation.
- avoid TH1 as intermediary objects
- flag overloads correctly
- add a "type" field to dataset exports
- add "parameter_name" field to histfactory PDF exports
=> DRAFT: [HS3][RF] More bugfixes

roofit/roofitcore/src/RooWorkspace.cxx
use aliasName to lookup existing objects on import
=> [RF] Use aliasName to lookup existing objects on RooWorkspace import

core/meta/src/TDictionary.cxx, tree/treeplayer/src/TTreeReaderArray.cxx, tree/treeplayer/src/TTreeReaderValue.cxx
=> TTreeReader add support for enum type as template args

gui/webgui6/src/TWebCanvas.cxx, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/TAttTextHandler.mjs, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TGaxisPainter.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/geom/geobase.mjs, js/modules/gpad/RAxisPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/display.mjs, js/modules/gui/menu.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/RH1Painter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/io.mjs, js/modules/tree.mjs, ui5/canv/controller/Ged.controller.js
1. Move and context menu for TGaxis
2. Support function inside `TGaxis` - see `tutorials/graphics/gaxis2.C`
3. Full context menu for `TAttText`
=> [webcanvas] provide interactivity for `TGaxis`

geom/geom/src/TGeoHype.cxx
Updates the TGeoHype reference documentation.
The definition of stin/stout were incorrect
https://root-forum.cern.ch/t/tgeohype-reference-documentation/54605/2
=> [geom] Updated reference docs for hyperboloid.

interpreter/cling/tools/plugins/clad/CMakeLists.txt, interpreter/cling/tools/plugins/clad/patches/clad_array_size_type.patch, interpreter/cling/tools/plugins/clad/patches/clad_local_array.patch, roofit/roofit/inc/RooPolynomial.h, roofit/roofit/src/RooPolynomial.cxx, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/inc/RooArgSet.h, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooFit/UniqueId.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/inc/RooPolyVar.h, roofit/roofitcore/inc/RooSTLRefCountList.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooPolyVar.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This PR adds support for RooPolyVar and also adds two utility functions to print the squashed code.
=> [RF] Add code-squash support for RooPolyVar and RooPolynomial

geom/webviewer/src/RGeomData.cxx
ROOT raw buffer for the shape may include more than 4 vertices in polygon. 
Support such case not seen before
=> [webgeom] support more than 4 vertices in polygon [6.28]

geom/webviewer/src/RGeomData.cxx
ROOT raw buffer for the shape may include more than 4 vertices in polygon. 
Support such case not seen before
=> [webgeom] support more than 4 vertices in polygon

interpreter/cling/tools/plugins/clad/CMakeLists.txt, interpreter/cling/tools/plugins/clad/patches/clad_fma.patch, roofit/roofit/inc/RooChebychev.h, roofit/roofit/inc/RooGamma.h, roofit/roofit/inc/RooLandau.h, roofit/roofit/src/RooChebychev.cxx, roofit/roofit/src/RooGamma.cxx, roofit/roofit/src/RooLandau.cxx, roofit/roofitcore/inc/RooAddPdf.h, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooFit/BatchModeDataHelpers.h, roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooFitDriver.h, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFuncWrapper.cxx
This PR adds code-squash support for the RooChebychev and RooAddPdf classes.
=> [RF] Add AD support for RooChebychev and RooAddPdf.

math/mathcore/inc/Math/Types.h, roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/src/RooBatchCompute.cu, roofit/batchcompute/src/RooBatchCompute.cxx, roofit/histfactory/test/testHistFactory.cxx, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooGlobalFunc.h, roofit/roofitcore/inc/RooNLLVar.h, roofit/roofitcore/inc/RooTreeDataStore.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
The BatchMode is invoked differently since ROOT 6.26, with a new NLL class and the new RooFitDriver class that manages the evalutaion of the computation graph.
=> [RF] Support RooNLLVarNew on the GPU

roofit/roofitcore/inc/RooConstraintSum.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooRealSumFunc.h, roofit/roofitcore/inc/RooRealSumPdf.h, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooConstraintSum.cxx, roofit/roofitcore/src/RooRealSumFunc.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
Add code squashing support for RooRealSumPdf, RooRealSumFunc, and RooConstratinSum.
=> [RF] Add AD support for Roo[RealSumPdf, RealSumFunc, ConstraintSum].

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/res/RooHeterogeneousMath.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/histfactory/src/ParamHistFunc.cxx, roofit/roofit/inc/RooGaussModel.h, roofit/roofit/src/RooGaussModel.cxx, roofit/roofitcore/inc/RooAbsAnaConvPdf.h, roofit/roofitcore/inc/RooAddModel.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooAddModel.cxx, roofit/roofitcore/src/RooMath.cxx
This is a backport of some RooFit PRs that were recently merged to master to v6-28-00-patches.
1. https://github.com/root-project/root/pull/12725
2. https://github.com/root-project/root/pull/12141
Related to https://github.com/root-project/root/issues/12319.
After merging this PR, the following RooFit commits in ROOT `master` (as of `tofillout`) are the ones that are not in `v6-28-00-patches` (as of `tofillout`).
=> [v628][RF] Backports of RooFit PRs to `v6-28-00-patches`: Part 19

interpreter/cling/include/cling/std.modulemap, interpreter/llvm/src/tools/clang/include/clang/AST/APValue.h, interpreter/llvm/src/tools/clang/include/clang/AST/AbstractBasicReader.h, interpreter/llvm/src/tools/clang/lib/AST/APValue.cpp, interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp, tmva/tmva/inc/TMVA/ROCCurve.h
Backport of https://github.com/root-project/root/pull/12737
=> 6-28: Make C++20 builds actually work for GCC version 10 through 13

.github/workflows/root-ci-config/buildconfig/fedora38.txt, .github/workflows/root-ci.yml
=> [ci] Add Fed38 with C++20. [skip-ci]

.lift/config.toml, .lift/setup.sh, CMakeLists.txt
=> [lift] Help Sonatype build ROOT. [skip-ci]

hist/histpainter/src/TGraphPainter.cxx
TGraph does not always have a list of functions.
fixes: https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/173815/testReport/projectroot/runtutorials/tutorial_graphics_AtlasExample/
=> Fix for palette drawing

tmva/pymva/test/CMakeLists.txt
=> [cmake] Ensure TMVA emitFromXYZ uses libs from  current ROOT build.

roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooMultiVarGaussian.h, roofit/roofitcore/src/RooMultiVarGaussian.cxx
Fix two warnings in RooFit:
* one new warning that popped up with gcc13
* one warning during compilation because I forgot to remove some class rules in #12754
=> [RF] Fix some new warnings in RooFit

graf2d/asimage/inc/TASImagePlugin.h, graf2d/asimage/inc/TASPluginGS.h, graf2d/asimage/src/TASPluginGS.cxx, graf2d/asimage/src/libAfterImage/import.c
1. Using latest libpng
2. Redefine Hash in image plugin
=> Backport libAfterImage fixes to 628

roofit/roofit/src/RooPolynomial.cxx, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooPolyVar.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
Fixed a minor bug in RooAddition and modified `addToCodeBody` such that it determines the correct scope to place the input string automatically.
=> [RF] Support RooSimultaneous in code generation and fix issues with RooAdd* classes

core/rint/src/TRint.cxx, rootx/src/rootx.cxx
Fixes https://github.com/root-project/root/issues/11977
by @ShamrockLee 
As well as a typo
=> Return 0 when calling root --help

interpreter/cling/lib/Interpreter/DeclUnloader.cpp
The order in which declarations are removed makes a difference, e.g. `MaybeRemoveDeclFromModule()` may require access to type information to make up the mangled name.
Thus, we segregate declarations to be removed in `TagDecl`s (i.e., struct / union / class / enum) and other declarations.  Removal of `TagDecl`s is deferred until all the other declarations have been processed. Declarations in each group are iterated in reverse order.
This PR fixes #12457.
=> [cling] DeclUnloader: remove `TagDecl`s after all other decls

interpreter/cling/lib/Interpreter/DeclUnloader.cpp
The order in which declarations are removed makes a difference, e.g. `MaybeRemoveDeclFromModule()` may require access to type information to make up the mangled name.
Thus, we segregate declarations to be removed in `TagDecl`s (i.e., struct / union / class / enum) and other declarations.  Removal of `TagDecl`s is deferred until all the other declarations have been processed. Declarations in each group are iterated in reverse order.
This PR is a backport of https://github.com/root-project/root/pull/12853 to v6.28.
This PR fixes #12457.
=> [cling][v6-28] DeclUnloader: remove `TagDecl`s after all other decls

tree/ntuple/v7/test/rfield_vector.cxx
=> [ntuple] Add more test coverage for RNTuple+RVec 

geom/webviewer/src/RGeomViewer.cxx, gui/browserv7/src/RFileDialog.cxx, gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebDisplayArgs.cxx, gui/webdisplay/src/RWebWindow.cxx
In GeometryViewer hierarchy is displayed using embed window. 
One need to support multiple connections for such embed window
=> [webgui] support multiple connections for embed web window

etc/RooFitHS3_wsexportkeys.json, etc/RooFitHS3_wsfactoryexpressions.json, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3HistFactory.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.cxx, roofit/jsoninterface/src/RYMLParser.h, roofit/roofit/inc/RooExpPoly.h, roofit/roofit/inc/RooPower.h, roofit/roofit/src/RooExpPoly.cxx, roofit/roofit/src/RooPower.cxx, tutorials/roofit/rf515_hfJSON.json, tutorials/roofit/rf515_hfJSON.py
improves the handling of combined Pdfs and Datasets in HS3
removes the assumption of exactly one simPdf/combData/ModelConfig being present, instead allowing to mix&match multiple possible modelConfigs, combData and simPdfs
=> [HS3] [RF] Improved simpdf handling

roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
This is related to https://github.com/root-project/root/issues/12783 (the symptom descriptions) and https://github.com/root-project/root/pull/12846 (the underlying fix) and as a side effect of being more efficient works around the issue (which is related to updating a file).
=> v628: HistFactory: open channel and combined files only once

roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
This is related to https://github.com/root-project/root/issues/12783 (the symptom descriptions) and https://github.com/root-project/root/pull/12846 (the underlying fix) and as a side effect of being more efficient works around the issue (which is related to updating a file).
=> v626 HistFactory: open channel and combined files only once

tree/treeplayer/src/TSelectorDraw.cxx
This address one of the issue noted in https://sft.its.cern.ch/jira/browse/ROOT-2869.
Instead of resetting`fNfill` (i.e. forgetting all cached data) right after taking an action (actual putting the data into the histogram), we now reset it at the beginning of the entry processing if we took action during the previous processing.
=> SelectorDraw: allow rebinning when using SetEstimate(GetEntries()).

io/io/src/TFile.cxx
=> [io] Update TFile spec to follow MIME magic bytes (NFC). [skip-ci]

tree/tree/src/TTree.cxx
as requested here: https://root-forum.cern.ch/t/problem-with-the-function-tree1-draw/54866/5
=> [skip-ci] Improve TTree::Draw help

math/mathcore/inc/Math/Minimizer.h
This Pull request updates the ROOT::Math::Minimizer reference documentation and adds the list of all Minimizer plugins that are available in ROOT. 
This PR fixes the JIRA issue [3452](https://sft.its.cern.ch/jira/browse/ROOT-3452)
=> [doc][math] Update Minimizer documentation

interpreter/cling/tools/plugins/clad/patches/clad_array_size_type.patch, interpreter/cling/tools/plugins/clad/patches/clad_fma.patch, interpreter/cling/tools/plugins/clad/patches/clad_local_array.patch
This guarantees valid patch files.
=> Re-download all Clad patches from GitHub

js/build/jsroot.js, js/changes.md, js/modules/base/math.mjs, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gui/display.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/tree.mjs
- fix normal_cdf function
- JavaScript stack limitation in TTree::Draw
- object status drawing
=> [jsroot] 7.3.2 release with several fixes [skip-ci]

js/build/jsroot.js, js/changes.md, js/modules/base/base3d.mjs, js/modules/base/latex.mjs, js/modules/base/math.mjs, js/modules/core.mjs, js/modules/d3.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist2d/TScatterPainter.mjs, js/modules/io.mjs, js/modules/three.mjs, js/modules/tree.mjs
1. Upgrade three.js to r152
2. Fix normal_cdf
3. Fix subpads moving/resize, also move/resize sub-sub pads
4. Fix - stack limitation with Math.min.apply in tree draw
=> [jsroot] dev 30/05/2023 [skip-ci]

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx, core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingCallFunc.h
=> [v6.28] Reduce usage of locks by TPluginHandler

math/minuit2/inc/Minuit2/AnalyticalGradientCalculator.h, math/minuit2/inc/Minuit2/GradientCalculator.h, math/minuit2/inc/Minuit2/LASymMatrix.h, math/minuit2/src/BFGSErrorUpdator.cxx, math/minuit2/src/DavidonErrorUpdator.cxx, math/minuit2/src/MnSeedGenerator.cxx, math/minuit2/src/NegativeG2LineSearch.cxx, math/minuit2/src/Numerical2PGradientCalculator.cxx, math/minuit2/src/VariableMetricBuilder.cxx
This Pull request fixes a bug in the assignment operator of the matrix object of Minuit2 and 
provides a fixes for correcting for the negative G2 when an external Hessian is provided to Minuit2
=> [math][minuit2] Some Minuit2 fixes 

geom/webviewer/inc/ROOT/RGeomHierarchy.hxx, geom/webviewer/src/RGeomHierarchy.cxx, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebWindow.cxx, ui5/geom/controller/GeomHierarchy.controller.js
1. Provide in RWebWindow methods to correctly work with connections, provided by master
2. Introduce public `RWebWindow::GetConnections()` method, simplify reply logic
3. Handle reply to multiple clients from geometry hierarchy widget - change top or change search should be handled
=> [webgeom] handle multiple connections to widget

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/hist2d/RH1Painter.mjs, js/modules/tree.mjs
Fixes issue reported on forum:
https://root-forum.cern.ch/t/horizontal-line-at-y-0-drawn-also-for-negative-y-values/55156
Plus several small fixes in Tree::Draw
=> [jsroot] 7.3.x 2/06/2023 [skip-ci]

etc/RooFitHS3_wsexportkeys.json, etc/RooFitHS3_wsfactoryexpressions.json, roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h, roofit/histfactory/src/HistFactoryModelUtils.cxx, roofit/histfactory/src/HistFactoryNavigation.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/hs3/src/Domains.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.cxx, roofit/jsoninterface/src/RYMLParser.h, roofit/roofit/src/RooGamma.cxx
Adds handling of ExternalConstraints to HS3.
=> [RF][HS3] Improvements for ModelConfig IO and other developments

tree/dataframe/src/RDatasetSpec.cxx
=> Updating RDatasetSpec docs with Cpp MWE

.github/workflows/sonartype.yml, sonar-project.properties
=> [ci] Add sonartype.io static checker. [skip-ci]

.github/workflows/sonartype.yml
=> [ci] SonarCloud: run on GH infra, better for security. [skip-ci]

hist/hist/src/HFitInterface.cxx, math/mathcore/src/FitUtil.cxx, math/mathmore/src/GSLMinimizer.cxx, math/minuit/src/TLinearMinimizer.cxx, math/minuit2/src/Minuit2Minimizer.cxx, test/stressHistoFit.cxx
This Pull request fixes some issues when fitting variable bins histograms.
In addition it provides a new version of the fitting test, stressHistoFit.cxx
=> [math] Fix fitting for variable bins histograms 

roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h, roofit/histfactory/src/ParamHistFunc.cxx, roofit/roofit/inc/RooParamHistFunc.h, roofit/roofit/inc/RooPoisson.h, roofit/roofit/src/RooParamHistFunc.cxx, roofit/roofit/src/RooPoisson.cxx, roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooHistFunc.h, roofit/roofitcore/inc/RooHistPdf.h, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooHistPdf.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFuncWrapper.cxx
This PR adds support for CodeGen-AD for RooHistPdf, RooHistFunc, RooParamHistFunc, ParamHistFunc, and RooPoisson.
=> [RF] Add CodeGen-AD support for the Hist* classes and RooPoisson

roofit/multiprocess/test/utils.h, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooSimultaneous.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooMCStudy.cxx, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx, roofit/roofitcore/test/testGlobalObservables.cxx, roofit/roofitcore/test/testRooProdPdf.cxx, roofit/roofitcore/test/testRooSimultaneous.cxx, roofit/roostats/inc/RooStats/ToyMCSampler.h, roofit/roostats/src/BayesianCalculator.cxx, roofit/roostats/src/PdfProposal.cxx, roofit/roostats/src/ToyMCImportanceSampler.cxx, roofit/roostats/src/ToyMCSampler.cxx, roofit/xroofit/src/xRooFit.cxx, test/stressHistFactory_tests.cxx, test/stressRooStats_models.h, test/stressRooStats_tests.h
=> [RF] Use `RooFit::OwningPtr<T>` in RooFit data generation functions

roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h, roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/histfactory/test/CMakeLists.txt, roofit/histfactory/test/testHistFactory.cxx, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/inc/RooGlobalFunc.h, roofit/roofitcore/inc/RooMinimizer.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/src/RooMinimizerFcn.cxx, roofit/roofitcore/src/RooRealVar.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This PR adds Code-Squash AD support for RooFlexibleInterpVar.
=> [RF] Add Code-Squash AD support for RooFlexibleInterpVar.

roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h, roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/histfactory/test/CMakeLists.txt, roofit/histfactory/test/testHistFactory.cxx, roofit/roofit/inc/RooLognormal.h, roofit/roofit/src/RooLognormal.cxx, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
Add Code-Squash AD support for RooPiecewiseInterpolation and RooLogNormal.
=> Add Code-Squash AD support for RooPiecewiseInterpolation and RooLogNormal. 

hist/hist/src/HFitInterface.cxx, math/mathcore/src/FitUtil.cxx, math/mathmore/src/GSLMinimizer.cxx, math/minuit/src/TLinearMinimizer.cxx, math/minuit2/src/Minuit2Minimizer.cxx, test/stressHistoFit.cxx
This Pull request is a back port of #12883
=> Backport in 6.28 fixes for fitting

core/metacling/src/TCling.cxx
skip executable, linker and vdso
This PR fixes #13080
=> [FreeBSD] Fix library registration in TCling

tree/dataframe/src/RDataFrame.cxx, tree/dataframe/src/RLoopManager.cxx
This maybe should also make us change the name into something more generic like `MakeUnregisteredChain` ?
=> [DF] Use MakeChainForMT everywhere

core/base/src/TApplication.cxx
Hi, I love the new `.gh` command (thank you very much @ferdymercury !).
Just a couple of minor improvement suggestions:
- remove extra newline from auto-filled GH issue
- log to terminal that a new browser tab should have been opened
=> Minor improvements to OpenGitHubIssue

gui/webdisplay/src/RWebDisplayHandle.cxx
For interactive session default web browser is used
But when producing image exact kind of browser is important. 
If exact browser kind not configured -
check if supported browsers are there.
Add also support of Edge browser on Windows
=> [webgui] detect available browser when producing image

cmake/modules/SetUpFreeBSD.cmake, core/base/inc/TVirtualMutex.h, core/base/inc/TVirtualRWMutex.h, core/cont/inc/TCollection.h, core/meta/inc/TInterpreter.h
this fixes the TThread tests
#13068
This PR fixes #13068
=> [FreeBSD] Fix TThread related tests

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/Domains.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testRooFitHS3.cxx
Improves some of the error messages by adding explicit checks for binning consistency to the HS3 HistFactory implementation
=> [RF][HS3] improved error reporting for HistFactory

core/unix/src/TUnixSystem.cxx
implements access to some cpu information via gSystem->GetSysInfo
This PR fixes #13128
=> [FreeBSD] Add access to some cpu information

core/base/src/TROOT.cxx
=> [core] Improve ROOT_MAX_THREADS doc wrt oversubscription (NFC).

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
=> Fixing template parameter typo for Profile2D

hist/hist/inc/TScatter.h, hist/hist/src/TScatter.cxx, hist/histpainter/src/TGraphPainter.cxx
Fix an issue with TSactter. Mentioned here:
https://root-forum.cern.ch/t/can-tgraph2d-be-draw-with-circle-and-circle-size-like-below/55474/12
=> Markers at the maximum did not have the right color

.github/workflows/root-ci.yml
EDIT: as discussed, tmate sessions might be a security breach.  Let's just disable this feature for now.
=> Disable tmate debugging facility

tree/dataframe/test/dataframe_vary.cxx
Just re-ordering. And making a test that should have been MT MT.
=> [DF] Move all single-thread vary tests together

hist/histpainter/inc/THistPainter.h, hist/histpainter/src/THistPainter.cxx, hist/histpainter/src/TPainter3dAlgorithms.cxx, js/build/jsroot.js, js/changes.md, js/modules/gpad/TFramePainter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist2d/THistPainter.mjs, tutorials/graphics/earth.C
Address request on forum:
https://root-forum.cern.ch/t/draw-option-for-mollweide-projection/55574
Also simplify a bit code in projection handling in hist painter
=> [histpainter] Implement Mollweide projection, in plain and web graphic

config/rootssh
Use `nc` instead of `netcat`
Use `open` instead of `xdg-open`
Adresses: #13215
=> Adjust rootssh for usage on Mac [skip-ci]

math/minuit2/src/Minuit2Minimizer.cxx, tmva/tmva/src/DataLoader.cxx, tmva/tmva/src/MethodBase.cxx
This PR fixes #13017 and also #13177
In addition the PR contains two additional unrelated commits for 2 improvements (see commit messages)
=> [tmva] Fix drawing of Progressbar when evaluating Regression 

interpreter/cling/lib/Interpreter/CIFactory.cpp
This makes it possible to drop our custom `CompilerInvocation::addOverlay` functionality (but the rest of the patch that introduced it is still needed with LLVM 13, so it cannot be reverted for now).
=> [cling] Use standard way to set up OverlayFS

graf2d/graf/src/TGaxis.cxx, hist/hist/src/TAxis.cxx, hist/hist/src/TF2.cxx, hist/hist/src/TF3.cxx
The changed labels were not saved in `.C` macros generated with `SaveAs`. This was pointed out here:
https://github.com/root-project/root/issues/13122
=> Changed labels were not saved in `.C` file

README/CREDITS, hist/histpainter/src/THistPainter.cxx
=> implemented mollweide projection

tmva/sofie/CMakeLists.txt, tmva/sofie/inc/TMVA/OperatorList.hxx, tmva/sofie/inc/TMVA/ROperator_Erf.hxx, tmva/sofie/test/TestCustomModelsFromONNX.cxx, tmva/sofie/test/input_models/Erf.onnx, tmva/sofie/test/input_models/references/Erf.ref.hxx, tmva/sofie_parsers/CMakeLists.txt, tmva/sofie_parsers/src/ParseErf.cxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
=> [GSOC][TMVA][SOFIE] Error function implemented successfully with the corresponding unit tests

roofit/histfactory/test/testHistFactory.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx
Fix the HistFactory HS3 implementation such that we don't need a large tolerance in the fit result comparisons anymore.
=> [RF][HS3][HF] Fix closure problems in HistFactory HS3 implementation

.github/workflows/issues-nudge.yml
Update to NodeJS 20 and Restrict `octokit` version to 3.x.
=> [skip-ci] Update and fix issues-nudge

hist/histv7/inc/ROOT/RHistBufferedFill.hxx, roofit/roofitcore/inc/RooVectorDataStore.h, roofit/roofitcore/src/RooDataSet.cxx
Partial application of commit edc0039c809a76f594ac21658402935eaeae9d36, some changes have already been applied in other backports.
=> Fix C++20 build of RooFit [v6.28]

tree/dataframe/src/RInterfaceBase.cxx, tree/dataframe/test/dataframe_datasetspec.cxx, tree/dataframe/test/dataframe_interface.cxx
It's a multiline string: for consistency it should end in a newline.
I realize this is a weird hill to die on, feel free to do what you want with this PR.
EDIT:
Meh on second thought I don't know anymore what's best here, what do you think?
=> [NFC][DF] Always add a new line at the end of Describe

tree/dataframe/test/dataframe_datasetspec.cxx
One extra newline was missing from the test. Follow-up of https://github.com/root-project/root/pull/13165
=> Fix rdatasetspec test

build/unix/pandoc-jira.sh, config/rootssh, configure, math/smatrix/CreateBinaryOp.sh, math/smatrix/CreateUnaryOp.sh
as described and discussed in #13174
This PR fixes #13174
=> [FreeBSD] Be more POSIX compliant bash->sh

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx
No actual drawing will be performed, but some extra objects like palette or stats box may be created
Behaves like batch image production was triggered - without real running of web browser.
=> [webcanvas] handle TCanvas::Update() also in batch mode

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Add support for scoped and unscoped enum types to RNTuple. Introspection is provided by TEnum.
=> [ntuple] Add support for enums

roofit/batchcompute/src/RooBatchCompute.cu
This commit fixes a problem in weighted fits with CUDA, replacing the kernel for weighted NLL sums with a new multi-block kernel that works for all unit tests.
The `stressRooFit` test suite is now passing again with the CUDA backend.
=> [RF] Fix bug in NLL summation in RooBatchCompute

gui/gui/src/TGFileBrowser.cxx, tree/tree/src/TBranchBrowsable.cxx
Prevent potential infinite recursion and simplify part of the code. This fixes the issue #13233 and doesn't affect the already closed Jira issue [#9260](https://sft.its.cern.ch/jira/browse/ROOT-9260)
=> Re-enable browsing of `TMethodBrowsable`

core/cont/inc/TVirtualCollectionProxy.h
The `TVirtualCollectionProxy` class has been proved to be weakly documented (see, e.g. issues in PR #13306 and #12948).  Given the situation, this pull request improves and extends the documentation of the aforementioned class.
=> [core] Improve documentation of the `TVirtualCollectionProxy` class (NFC)

bindings/pyroot/pythonizations/inc/RNumpyDS.hxx, core/foundation/res/ROOT/RSha256.hxx, core/foundation/src/TClassEdit.cxx, documentation/primer/macros/macro1.C, documentation/primer/macros/macro2.C, graf2d/cocoa/src/TGCocoa.mm, tmva/sofie/inc/TMVA/ROperator_LayerNormalization.hxx, tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
Misspelled length
This PR fixes https://github.com/root-project/root/issues/13276
=> Fix Lenght typos

.lift/config.toml, .lift/setup.sh
=> [ci] Remove sonatype-lift: does not work and is deprecated.

tmva/tmva/inc/TMVA/RTensor.hxx
Fix in ExpandDims the resulting strides. 
This PR fixes also  #13325 by not using the end() iterator in insert
=> [tmva] Fix RTensor::ExpandDims()

gui/qt6webdisplay/rootqt6.cpp
=> [qt6web] remove unused member [skip-ci]

tmva/tmva/src/TransformationHandler.cxx
Fix a debug assertion failure "can't decrement vector iterator before begin"
=> Fix yet another assertion failure on Windows

js/build/jsroot.js, js/changes.md, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TH1Painter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/tree.mjs, ui5/canv/controller/Canvas.controller.js, ui5/canv/controller/CanvasPanel.controller.js, ui5/canv/controller/ColorButton.js, ui5/canv/controller/Ged.controller.js, ui5/canv/controller/SVGSample.js
1. Fix GED initialization when canvas shown in nonui5 mode. In this mode only drawing is shown, but GED can be started in float HTML element.
2. Fix toggling of color palette after color is default draw option for TH2
3. Update JSROOT with `TGraph2D` Delaunay algorithm, many other fixes
=> [webcanvas] fix GED issues, update JSROOT [skip-ci]

.github/workflows/root-ci-config/build_root.py, .github/workflows/test-coverage.yml, .gitignore
=> [ci] Upload Test Coverage to codecov [skip-ci]

core/base/src/TApplication.cxx, core/base/src/TRemoteObject.cxx, documentation/doxygen/MakeRCanvasJS.C, documentation/doxygen/MakeTCanvasJS.C, documentation/doxygen/makeimage.C, graf2d/asimage/src/TASImage.cxx, graf2d/asimage/src/TASPaletteEditor.cxx, graf2d/asimage/src/TASPluginGS.cxx, graf2d/graf/src/TPaveText.cxx, graf2d/graf/src/TPie.cxx, graf2d/postscript/src/TPostScript.cxx, graf2d/postscript/src/TSVG.cxx, graf2d/postscript/src/TTeXDump.cxx, hist/histpainter/src/TGraphPainter.cxx, hist/histpainter/src/TPaletteAxis.cxx, io/io/src/TBufferJSON.cxx, main/src/roots.cxx
Especially `gROOT->ProcessLine(Form("pattern",...))` can be risky.
=> Replace `Form` by `TString::Format` in different places

cmake/modules/RootConfiguration.cmake, gui/webdisplay/src/RWebDisplayHandle.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/hist2d/TH2Painter.mjs
=> [webgui] extend tests for firefox/chrome for Gentoo distribution

documentation/doxygen/Doxyfile, documentation/doxygen/print_roofit_pyz_doctrings.py, roofit/roofitcore/doc/index.md, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooLinkedList.h, roofit/roofitcore/inc/RooLinkedListElem.h, roofit/roofitcore/inc/RooSTLRefCountList.h, roofit/roofitcore/inc/RooTObjWrap.h, roofit/roofitcore/src/BidirMMapPipe.cxx, roofit/roofitcore/src/BidirMMapPipe.h, roofit/roofitcore/src/RooLinkedList.cxx, roofit/roofitcore/src/RooSTLRefCountList.cxx, roofit/roofitcore/src/RooSentinel.cxx, roofit/roofitcore/src/RooSentinel.h, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/src/RooTFoamBinding.cxx, roofit/roofitcore/src/RooTFoamBinding.h, roofit/roofitcore/src/RooTObjWrap.cxx, roofit/roofitcuda/doc/index.md, roofit/roofitcuda/inc/RooFit/Detail/CudaInterface.h, roofit/roofitcuda/inc/RooFit/Detail/CudaKernels.cuh, roofit/roofitcuda/src/CudaHelpers.cxx, roofit/roofitcuda/src/CudaHelpers.h, roofit/roofitcuda/src/CudaInterface.cu, roofit/roofitmore/doc/index.md, roofit/roofitmore/src/RooAdaptiveGaussKronrodIntegrator1D.cxx, roofit/roofitmore/src/RooGaussKronrodIntegrator1D.cxx, roofit/roostats/doc/index.md
Also, update the doxygen configuration file such that CUDA sources and headers are scanned as well.
=> [RF] Add RooFit CUDA documentation and hide internal class docs

tmva/sofie/inc/TMVA/RModel.hxx, tmva/sofie/src/RModel.cxx, tmva/sofie/test/EmitFromONNX.cxx.in, tmva/sofie/test/EmitFromRoot.cxx.in, tmva/sofie/test/TestCustomModelsFromONNX.cxx, tmva/sofie/test/TestCustomModelsFromROOT.cxx
This PR is based on #13066 by @Neel-Shah-29 
- A weight file isn't created by default when generating the code
- Options to save the weights in a text file or in a ROOT binary file
=> [TMVA/SOFIE] Save weights in ROOT binary files

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py
=> [ci] Say explicitly which platform image to use. [skip-ci]

gui/cefdisplay/Readme.md, gui/cefdisplay/inc/RCefWebDisplayHandle.hxx, gui/cefdisplay/inc/gui_handler.h, gui/cefdisplay/inc/simple_app.h, gui/cefdisplay/src/RCefWebDisplayHandle.cxx, gui/cefdisplay/src/cef_main.cxx, gui/cefdisplay/src/gui_handler.cxx, gui/cefdisplay/src/gui_handler_linux.cxx, gui/cefdisplay/src/gui_handler_mac.mm, gui/cefdisplay/src/gui_handler_win.cc, gui/cefdisplay/src/simple_app.cxx
1. Support newest CEF 116
2. Skip support of older CEF up to 95
3. Remove log output, update comments
=> [cefdisplay] update CEF code [skip-ci]

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py, .github/workflows/root-ci.yml
Simplifies script and allows to capture (and log) essential config values. Some more drive-by code fixes.
=> [ci] Move logging to global, pass docker info in: [skip-ci]

.github/workflows/test-coverage.yml
=> [ci] Disable codecov for PRs: takes 4 hours. [skip-ci]

.github/workflows/root-ci.yml
=> [ci] Add alma9 to build matrix.

.github/workflows/root-ci.yml
=> [ci] Move newest Ubuntu to 23.04. [skip-ci]

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py
=> [ci] Fix untar dir in replication log. [skip-ci]

core/base/src/TDirectory.cxx
Fix https://github.com/root-project/root/issues/13449
=> io: Do not turn on automatically MustClean for TDirectory

hist/histpainter/src/TGraphPainter.cxx
Was found here https://root-forum.cern.ch/t/tscatter-drawing-nothing-with-legacy-cocoa/56067
=> Fix in case positions sizes or colors are the same for all points.

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py
=> [ci] Report summary of failed tests. [skip-ci]

tree/dataframe/test/datasource_arrow.cxx
Removes the dependency on  arrow/testing for dataframe tests.
Copies over the various ArrayFromVector / ASSERT_OK helpers dropping the arrow:: namespace for them.
This PR fixes #13516.
=> Avoid inclusion of arrow testing stuff

roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx
Give gaussian constrained parameters an initial error, and don't create lumi constraint if there is no error on it
=> [RF][HF] HistFactory improvements for gaussian constrained terms 

math/mathcore/src/TRandom.cxx
This PR fixes https://github.com/root-project/root/issues/13513
=> [NFC] fix typo docu

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/draw.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TScatterPainter.mjs, js/modules/three.mjs, ui5/eve7/lib/FXAAShader.js, ui5/eve7/lib/GlViewerJSRoot.js, ui5/eve7/lib/GlViewerThree.js, ui5/eve7/lib/OutlinePassEve.js
1. Update jsroot with several other fixes
2. Adjust eve7 where three.js is used
=> [webgui] update three.js to r155 [skip-ci]

.github/workflows/root-ci-config/build_root.py
=> [ci] Use Ninja as build system. [skip-ci]

tree/ntuple/v7/doc/specifications.md
This pull request extends the description of a ROOT compression block in the RNTuple binary format specification.
=> [ntuple] specifications.md: fully describe a Compression block

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TSplinePainter.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/RH3Painter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/RH1Painter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/hist2d/TMultiGraphPainter.mjs
=> [webgui] create stats when using "sames" draw option

bindings/experimental/distrdf/CMakeLists.txt, bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py, bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py, bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/python/DistRDF/LiveVisualize.py, bindings/experimental/distrdf/python/DistRDF/__init__.py, tree/dataframe/src/RDataFrame.cxx, tutorials/CMakeLists.txt, tutorials/dataframe/distrdf003_live_visualization.py
Performs real-time map-reduce using Dask framework allowing real-time data representation
Fixes #13607
=> Live visualization feature prototype

tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/test/dataframe_vary.cxx
Sets a unique name for each varied result
This PR fixes #13582
=> Variation names

.github/workflows/root-ci-config/build_utils.py
=> [ci] Make sure GH log group/endgroup end up on separate lines. [skip-ci]

io/io/src/TDirectoryFile.cxx
See https://github.com/root-project/root/issues/13182
=> [IO][v6-28] Backport of prevent infinite loop in `TFile::ls` #13217 

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph.py, bindings/pyroot/pythonizations/test/tgraph_getters.py
Backport of https://github.com/root-project/root/pull/13601
=> [6.28] 13601 backport

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph.py, bindings/pyroot/pythonizations/test/tgraph_getters.py
Backport of https://github.com/root-project/root/pull/13601
=> [6.26] 13601 backport

math/vecops/inc/ROOT/RVec.hxx, math/vecops/test/vecops_rvec.cxx
This is the new PR I mentioned here: https://github.com/root-project/root/pull/13408 
=> Implementing Range overload with recommended changes

gui/webdisplay/src/RWebDisplayHandle.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/ObjectPainter.mjs, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TASImagePainter.mjs, js/modules/draw/TTree.mjs, js/modules/geom/TGeoPainter.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/display.mjs, js/modules/gui/menu.mjs, js/modules/gui/utils.mjs, js/modules/hist2d/RH1Painter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/RHistPainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs
When producing single image for the canvas - do not add "%d" qualifier,
which is required for multiple files
Update JSROOT with minor fixes in interactive functions
=> [webgui] fix store file name, update jsroot

net/net/src/TNetFile.cxx, net/net/src/TS3WebFile.cxx, net/netx/src/TXNetFile.cxx
It improves ROOT's doc.
- [v] updated the docs (if necessary)
=> [skip ci][Doc] Revamp and Doxygenize doc of T(X)NetFile and TS3WebFile

documentation/doxygen/htmlheader.html
This PR removes the usage of two external services, preserving the look of the documentation, de facto changing nothing for the user.
=> [Doc][skip-ci]Remove 3rd party services

bindings/pyroot/pythonizations/test/CMakeLists.txt, tutorials/tmva/keras/RegressionKeras.py
This should fix some of the failures observed for builds without rdataframe
=> [pyroot] Fix dependency for pyroot rtensor test.

bindings/jupyroot/python/JupyROOT/helpers/utils.py, graf2d/gpad/inc/TCanvas.h, graf2d/gpad/src/TCanvas.cxx, graf2d/gpadv7/inc/ROOT/RCanvas.hxx, graf2d/gpadv7/src/RCanvas.cxx
1. Add flag in TCanvas/RCanvas which set when `Update()` method is called.
2. Use `can.IsUpdated()` flag in iPython to check if canvas was updated
3. Use iPython display handle to update drawing
4. Works with JSROOT and png-based drawings
5. Use latest released JSROOT version 7.4.3
6. Use TWebCanvas JSON for TCanvas drawings to handle all special cases like style, list of colors, stats box and so on
Resolves #13631
=> [ipython] implement `canvas.Update()` in notebooks

gui/webdisplay/src/RWebDisplayHandle.cxx, js/build/jsroot.js, js/changes.md, js/files/canv_batch.htm, js/modules/base/TAttFillHandler.mjs, js/modules/base/TAttLineHandler.mjs, js/modules/base/TAttMarkerHandler.mjs, js/modules/core.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs
Use canvas pixel size as page size - including margins
Also update JSROOT, preliminary 7.5 release
=> [webgui] set PDF page size when storing canvas in pdf

js/build/jsroot.js, js/changes.md, js/modules/base/colors.mjs, js/modules/draw/TASImagePainter.mjs, js/modules/draw/v7more.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/hist2d/TScatterPainter.mjs
Add support of grayscale flag in the canvas
=> [jsroot] 7.5.pre 19/09/2023 with grayscale support [skip-ci]

graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx
Instead direct call of Paint() call UpdateAsync()
Prevent Paint() when calling TCanvas::SetGrayscale
=> [webgui] Provide correct TCanvas::Draw and TPad::Draw for web canvas

cmake/modules/RootMacros.cmake, cmake/modules/SetUpMacOS.cmake, tree/treeplayer/inc/TTreeReaderValue.h, tree/treeplayer/src/TTreeReaderValue.cxx
=> [MacOS] Fix warnings appeared after moving to the 14.3 SDK

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml, README.md
=> [ci] Add generation of binary package artifacts.

core/foundation/src/FoundationUtils.cxx
=> Remove invalid value -1 as second arg  from substr

js/build/jsroot.js, js/changes.md, js/modules/base/TAttFillHandler.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Support TProfile3D
2. Support scaling of special fill patterns
This PR fixes #13678 and #13672
=> [jsroot] 7.5.pre 22/09/2023 with TProfile3D support [skip-ci]

montecarlo/pythia8/inc/TPythia8Decayer.h, montecarlo/pythia8/src/TPythia8Decayer.cxx
as per request by Peter Hristov, ALICE.
=> [pythia8] Fix license of TPythia8Decayer (NFC):

geom/webviewer/src/RGeomData.cxx
This PR is a simple backport that removes a warning on recent macos builds due to the presence of dead code.
=> [webgeom] Remove dead code

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml
=> [ci] Pass --binaries for all platforms; fix syntax of cpack invocation.

roofit/xroofit/CMakeLists.txt, roofit/xroofit/doc/index.md, roofit/xroofit/inc/LinkDef.h, roofit/xroofit/inc/RooBrowser.h, roofit/xroofit/inc/RooFit/xRooFit/Config.h, roofit/xroofit/inc/RooFit/xRooFit/xRooBrowser.h, roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h, roofit/xroofit/inc/RooFit/xRooFit/xRooHypoSpace.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h, roofit/xroofit/inc/XRooFit.h, roofit/xroofit/src/Asymptotics.cxx, roofit/xroofit/src/coutCapture.h, roofit/xroofit/src/xRooBrowser.cxx, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooHypoSpace.cxx, roofit/xroofit/src/xRooNLLVar.cxx, roofit/xroofit/src/xRooNode.cxx, roofit/xroofit/src/xRooNode_interactive.cxx
Should hold off merging this until last minute (I will push any further xroofit updates that come this week to it).
=> [RF] Update to latest xRooFit

requirements.txt
=> [req.txt] No numba for Python3.12 yet.

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR changes the size-related `RNTupleInspector` methods from `GetOnDiskSize` and `GetInMemorySize` to `GetCompressedSize` and `GetUncompressedSize`, respectively. An earlier version of `RNTuple` stored index fields as 32bit on-disk but kept them as 64bit in memory, causing a slight mismatch between the in-memory representation and actual non-compressed on-disk data. This is not the case anymore and moreover, the name `GetInMemorySize` may be confusing as it can be interpreted as the number of bytes that are actually currently stored in memory rather than the total uncompressed size.
=> [ntuple] Rename `RNTupleInspector` size-related methods

tutorials/legacy/thread/stressThreadPool.C, tutorials/legacy/thread/threadPool.C, tutorials/legacy/thread/threads.C, tutorials/legacy/thread/threadsh1.C, tutorials/legacy/thread/threadsh2.C
Ran every time by the CI and testing TThread, without reducing coverage.
=> [Testing] Significantly reduce duration of legacy tutorials

tmva/pymva/test/CMakeLists.txt, tutorials/CMakeLists.txt
Remove a test that always fails on macos. This is related to https://github.com/root-project/root/pull/13718/commits/5db2ace91a23ea495b9b6a6a87483fcc58ed9547 .
=> [TMVA][CMake] Remove failing keras test from macos battery

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml
=> [ci] Move resulting packages to package/ subdir to easily find them.

.github/workflows/root-ci-config/buildconfig/fedora39.txt, .github/workflows/root-ci.yml
=> [ci] Add Fed39 with C++20.

geom/geombuilder/src/TGeoMediumEditor.cxx, html/src/TDocParser.cxx, tmva/tmva/src/Classification.cxx, tree/tree/src/TBranch.cxx, tree/tree/src/TBranchElement.cxx, tree/tree/src/TBranchIMTHelper.h, tree/tree/src/TTree.cxx, tree/treeplayer/src/TTreeFormula.cxx
Backports of:
* https://github.com/root-project/root/pull/12776
* https://github.com/root-project/root/pull/13135
* https://github.com/root-project/root/pull/13153
=> [v628] Backports to fix warnings

tree/dataframe/CMakeLists.txt
=> [6.28] Add RDefinePerSample to CMakeLists.txt

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
This PR expands the `RNTupleInspector` documentation by adding proper Doxygen tags and adding additional information where necessary.
=> [ntuple] Improve `RNTupleInspector` documentation

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/draw.mjs
This is final 7.5.0 release.
Branch 7.5 will be used as base for ROOT 6.30
=> [jsroot] version 7.5.0 5/10/2023 [skip-ci]

build/unix/compiledata.sh
=> [Backport ] Fix rpath issues with aclic for 6.28

bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.cxx, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.h
This PR fixes # https://github.com/root-project/root/issues/13410
=> [Cppyy][Backport] Cppyy fix derived overload visibility

cmake/modules/SearchInstalledSoftware.cmake
=> [CMake][Backport] Update Vc version to 1.4.4

CMakeLists.txt, cmake/modules/RootConfiguration.cmake, cmake/modules/SearchInstalledSoftware.cmake, cmake/scripts/ROOTConfig.cmake.in, math/vecops/CMakeLists.txt, roofit/batchcompute/CMakeLists.txt, test/CMakeLists.txt, tmva/tmva/CMakeLists.txt
=> [Backport] VDT Usage Fix

.github/workflows/root-ci.yml
=> Switch CI to v6-30-00-patches. [skip-ci]

roofit/xroofit/src/xRooHypoSpace.cxx, roofit/xroofit/src/xRooNLLVar.cxx, roofit/xroofit/src/xRooNode.cxx
This fix will be needed for 6.30 too.
Opening this PR now so that you know it is needed, but I will be continuing to run some tests today and may push some more changes if I find more bugs!
=> [RF] Fix `xroofit` bugs in breakdown,impact,and error on histograms of RooRealSumPdf

.github/workflows/root-ci.yml
=> [ci] Add Ubuntu 23.10 (C++20); order images. [skip-ci]

core/gui/src/TBrowser.cxx, documentation/users-guide/WebDisplay.md, etc/plugins/TVirtualGeoPainter/P020_RGeoPainter.C, etc/plugins/TVirtualTreeViewer/P020_RTreeViewer.C, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist/TF1Painter.mjs, tutorials/webgui/panel/Readme.md
1. Update name of in geopainter plugin
2. Fix two errors in JSROOT
3. Fix name of tree viewer in plugin
4. Fix documentaion
=> [webgui] fix geopainter plugin, update jsroot [skip-ci]

main/src/hadd-argparse.py, main/src/hadd.cxx
https://github.com/root-project/root/issues/6438
=> Hadd improve help message and Doxygen documentation

cmake/modules/RootConfiguration.cmake, core/base/src/TROOT.cxx, gui/gui/src/TRootGuiFactory.cxx
Only when explicitly --web option specified web canvas will be used
=> [webcanvas] make default off for the TWebCanvas [6.30]

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
By using std::apply, now available after moving to C++17, the implementation can be greatly simplified.
This is a BP of https://github.com/root-project/root/pull/13619
=> [Cling][Backport] Simplify tuple value printer

bindings/pyroot/pythonizations/src/GenericPyz.cxx, bindings/pyroot/pythonizations/test/pretty_printing.py
This change is an optimization of the PyROOT value printing. Instead of jitting the value printing at every invocation of the __str__ method, the jitting now happens only once per type. The printer function pointers are stored in a map. The time needed to print is now equivalent to the previous one only for the first print, much faster afterwards. The memory used is also much lower, since traces in the AST are left only at the first print and only the type name and function pointer are stored in an unordered_map.
Fixes https://github.com/root-project/root/issues/12817
This PR fixes # https://github.com/root-project/root/issues/12817
=> [PyROOT] Optimize value printing by jitting only once per type

graf2d/cocoa/src/QuartzWindow.mm, graf2d/cocoa/src/ROOTOpenGLView.mm, graf2d/cocoa/src/TGCocoa.mm
Fix Cocoa GUI for MacOS14 and Clang15. 
The following collection of patches was provided by Timur Pocheptsoff <tpochep@mail.ru>
Fixes https://github.com/root-project/root/issues/13834
=> Fix Cocoa GUI for MacOS14 and Clang15

roofit/histfactory/test/testHistFactory.cxx, roofit/roofit/inc/RooChebychev.h, roofit/roofit/src/RooBernstein.cxx, roofit/roofit/src/RooChebychev.cxx, roofit/roofit/src/RooLagrangianMorphFunc.cxx, roofit/roofit/src/RooMomentMorphFuncND.cxx, roofit/roofitcore/src/BidirMMapPipe.cxx, roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooBinIntegrator.cxx, roofit/roofitcore/src/RooClassFactory.cxx, roofit/roofitcore/src/RooCustomizer.cxx, roofit/roofitcore/src/RooFactoryWSTool.cxx, roofit/roofitcore/src/RooLinkedList.cxx, roofit/roofitcore/src/RooRombergIntegrator.cxx, roofit/roofitcore/src/RooSimWSTool.cxx, roofit/roostats/inc/RooStats/DebuggingSampler.h, roofit/roostats/src/BayesianCalculator.cxx, roofit/roostats/src/SPlot.cxx
Thanks to this forum post for reporting this:
https://root-forum.cern.ch/t/roofit-how-to-fit-a-pdf-i-e-roobernstein-with-supporting-interval-smaller-than-data-range
=> [RF] Don't forget to copy `_refRangeName` in RooBernstein copy c'tor

bindings/pyroot/pythonizations/src/GenericPyz.cxx, bindings/pyroot/pythonizations/test/pretty_printing.py
This chane is an optimization of the PyROOT value printing. Instead of jitting the value printing at every invocation of the __str__ method, the jitting now happens only once per type. The printer function pointers are stored in a map. The time needed to print is now equivalent to the previous one only for the first print, much faster afterwards. The memory used is also much lower, since traces in the AST are left only at the first print and only the type name and function pointer are stored in an unordered_map.
Fixes https://github.com/root-project/root/issues/12817
=> [Backport][PyROOT] Value printing: jit once per type

hist/hist/src/TF1.cxx
In some old examples "same" and "sames" draw options for TF1 was used. 
Currently if "sames" used for TF1 - plain histogram painting is performed which is wrong for the function.
Also improve PMC/PLC/PFC handling
=> Paint `TF1` with default "lf" draw option also when "sames" was provided

gui/webgui6/inc/TWebSnapshot.h, gui/webgui6/src/TWebCanvas.cxx, gui/webgui6/src/TWebSnapshot.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw/TPolyMarker3D.mjs, js/modules/draw/draw3d.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui.mjs, js/modules/hist/RH3Painter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TGraphPainter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/THistPainter.mjs, tutorials/fit/fit2.C, tutorials/fit/fit2dHist.C, tutorials/fit/fitConvolution.C, tutorials/fit/fitConvolution.py, tutorials/fit/fitEllipseTGraphDLSF.cxx, tutorials/fit/fitEllipseTGraphRMM.cxx
1. Call TF1::Save with non-zero arguments, avoiding #13927 
2. Supports histogram creation for `TGraph2D`
3. Update JSROOT with correspondent changes
4. Adjust some tutorials where TF1/TF2 drawing is used
=> [webcanvas] Improve `TF1` / `TF2` / `TGraph2D` usage

documentation/doxygen/Doxyfile, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
- Add .json in Doxyfile
- Fix the author(s) section
=> Fixes for DF tutorials

gui/webgui6/inc/TWebSnapshot.h, gui/webgui6/src/TWebCanvas.cxx, gui/webgui6/src/TWebSnapshot.cxx, hist/hist/src/TF1.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Properly use saved buffers in functions
2. Properly invoke context menu
3. Support histograms creation for `TGraph2D`
4. Update JSROOT code
Backport some changes which will be submitted to master soon
=> [webcanvas] improve `TF1`, `TF2`, `TGraph2D` handling [6.30]

gui/gui/src/TRootBrowser.cxx
In "classical" TBrowser one want to use normal TCanvas - even if rootrc configured differently. Therefore change gEnv values for the time when canvas is created
=> [tbrowser] ensure that TCanvas created when web mode is not active [6.28]

README/ReleaseNotes/empty.md, README/ReleaseNotes/v630/index.md
Others are taken care by linked issues and will end up in the list of bugfixes of the release notes automatically
=> [skip-ci][relnotes] Add contributions by Vincenzo

README/ReleaseNotes/v630/index.md
Backport of https://github.com/root-project/root/pull/13944
=> Add 6.30 contributions by Vincenzo

bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
Backport of:
https://github.com/root-project/root/pull/13912
=> [v628][PyROOT] Prevent functions from crashing due to Python 3.12 assert

README/ReleaseNotes/v630/index.md
=> [skip-ci][relnotes] Mention ROOT_MAX_THREADS and alien removal; fomatting. (NFC)

js/scripts/JSRoot.core.js, js/scripts/JSRoot.more.js, js/scripts/JSRoot.v7hist.js, js/scripts/JSRoot.webwindow.js
Fix - do not draw empty TGraph
Fix - do not exclusion if distance too small
Fix - correctly open channel in web window
Fix - correctly get bin for RH3
=> [jsroot] 6.3.x 31/10/2023 with critical fixes from v7 [6.26] [skip-ci]

bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h, bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx, bindings/pyroot/cppyy/patches/gc_flags.patch, bindings/tpython/src/TPython.cxx
Backport of the Python 3.11 compatibility PRs:
* https://github.com/root-project/root/pull/10734
* https://github.com/root-project/root/pull/10047
* https://github.com/root-project/root/pull/11457
* https://github.com/root-project/root/pull/12857
=> [v624][PyROOT] Fixes for Python 3.11

README/ReleaseNotes/v630/index.md
=> [skip-ci] TScatter notes

hist/hist/src/TF1.cxx, hist/hist/src/TF2.cxx, hist/hist/src/TF3.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_tf1.cxx, hist/hist/test/test_tf2.cxx, hist/hist/test/test_tf3.cxx
Correctly write number of bins
Add testing
=> [6.30] Fix TF1/TF2/TF3 Save when called with default args 

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/math.mjs, js/modules/core.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TGraphPainter.mjs, net/http/inc/TRootSniffer.h, net/http/src/THttpServer.cxx, net/http/src/TRootSniffer.cxx
Correctly call TF1::Save with full range to be sure storing is correct
Support functions in TMultiGraph
Create real histogram for TGraph2D when `tri` option is configured
Update JSROOT with several fixes
=> [webcanv] better support TF1/TMultiGraph/TGraph2D [6.30]

bindings/pyroot/pythonizations/test/sofie_gnn.py, tmva/sofie/inc/TMVA/RFunction.hxx, tmva/sofie/inc/TMVA/SOFIE_common.hxx, tmva/sofie/src/RFunction.cxx, tmva/sofie/src/RModel_GNN.cxx, tutorials/tmva/TMVA_SOFIE_GNN.py
=> [tmva][sofie] Backport Fix in SOFIE GNN for senders/receivers

.github/workflows/root-ci-config/build_root.py
We currently fail to upload to S3 and I don't know / cannot see why.
=> [ci] Print exception connecting to S3.

README/ReleaseNotes/v630/index.md
This PR adds the changes and new implementations in TMVA SOFIE in the release notes for version 6.30
=> [relnotes] SOFIE changes and implementations for v630

.github/workflows/root-ci.yml
=> [ci] Build the binaries for workflow dispatch!

hist/hist/src/TH1.cxx, hist/hist/test/test_TH1.cxx
=> [hist] Code improvements to `TH1::SmoothArray()`

tutorials/v7/ntuple/ntpl004_dimuon.C
Commit cf78f40d60 made it use the RVec collection type.
=> [ntuple] Update comment in ntpl004_dimuon.C

tmva/sofie/README.md, tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h, tmva/tmva/inc/TMVA/DNN/Architectures/Reference.h, tmva/tmva/inc/TMVA/Executor.h, tmva/tmva/src/DNN/Architectures/Cpu/ActivationFunctions.hxx, tmva/tmva/src/DNN/Architectures/Cpu/Dropout.hxx, tmva/tmva/src/DNN/Architectures/Cpu/Initialization.hxx, tmva/tmva/src/DNN/Architectures/Cpu/OutputFunctions.hxx, tmva/tmva/src/DNN/Architectures/Cpu/Propagation.hxx, tmva/tmva/src/DNN/Architectures/Reference/ActivationFunctions.hxx, tmva/tmva/src/DNN/Architectures/Reference/Dropout.hxx, tmva/tmva/src/MethodPDERS.cxx
Several doxygen warnings found by doxygen in the TMVA classes
=> [TMVA] fix some inconsistencies and warnings found by doxygen

core/base/src/TAttText.cxx, graf2d/graf/src/TTF.cxx
Better description of fonts' names.
=> [skip-ci] Update fonts' documentation (CMS request)

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist/RH3Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/tree.mjs, js/scripts/geoworker.js
Fix - draw histogram with only negative bins jsroot:#276 
Fix - reading TLeaf with fixed-size array
Fix - correctly set pave name jsroot:#278
=> [jsroot] update for 6.28 branch

cmake/modules/FindZeroMQ.cmake
Backport of https://github.com/root-project/root/pull/13995.
=> [v630] Fix cmake/modules/FindZeroMQ.cmake

gui/browserv7/src/RWebBrowserImp.cxx, gui/gui/src/TRootGuiFactory.cxx, gui/webdisplay/src/RWebWindowsManager.cxx
=> [webgui] force loopback [6.30]

gui/browserv7/src/RWebBrowserImp.cxx, gui/webdisplay/src/RWebWindowsManager.cxx
=> [webgui] force loopback on [6.28]

hist/hist/test/test_tprofile2poly.cxx
This follows up on 46642ca1c40, reducing the relative tolerance in one case to make the test pass again on macOS ARM.
=> [hist] Reduce relative tolerance in an assert in test_tprofile2poly.cxx

cmake/scripts/ROOTConfig.cmake.in
=> Add `ROOT_CXX_STANDARD` in `ROOTConfig.cmake` 

cmake/modules/RootBuildOptions.cmake
=> [webgui] do not compile without http [6.30]

cmake/modules/RootBuildOptions.cmake
=> [webgui] do not build without http [6.28]

tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx, tree/dataframe/src/RDatasetSpec.cxx
Adding documentation for the RDatasetSpec class. 
This PR fixes #14101
=> [DF] Add documentation for RDatasetSpec class

interpreter/cling/CMakeLists.txt, interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h, interpreter/cling/lib/Interpreter/DeclUnloader.cpp, interpreter/cling/lib/Interpreter/DeclUnloader.h, interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/test/CodeUnloading/Classes.C, interpreter/cling/test/Driver/CommandHistory.C, interpreter/cling/test/lit.cfg
* https://github.com/root-project/root/pull/13565 - fixes ROOT-8084 and the first reproducer of https://github.com/root-project/root/issues/10049
* https://github.com/root-project/root/pull/13296
* https://github.com/root-project/root/pull/14183
* https://github.com/root-project/root/pull/14182
* https://github.com/root-project/root/pull/14197
=> Backport Cling fixes for v6.30

hist/hist/src/TH2.cxx
Fix GetRandom2 doc and a few typos.
=> [skip-ci] Fix GetRandom2 doc

roofit/roofit/inc/RooBifurGauss.h, roofit/roofit/src/RooBifurGauss.cxx, roofit/roofit/test/CMakeLists.txt, roofit/roofit/test/testRooBifurGauss.cxx, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/test/testRooFuncWrapper.cxx
Recently, I have seen some use of the `RooBifurGauss` in the wild, so this commit is completing its implementation for the newest RooFit features:
1. Support code generation of evaluation and analytical integral
2. Unit test for fitting with AD
3. Unit test for analytical integral, cross-checking with RooGaussian
4. Code formatting
=> [RF] Complete `RooBifurGauss` implementation

tutorials/tree/h1analysisTreeReader.C
Fix addressing this [Jira issue]( https://sft.its.cern.ch/jira/projects/ROOT/issues/ROOT-10543?filter=allopenissues). Indeed it makes no sense to open this example in a notebook.
=> [skip-ci] doc fix

gui/gui/src/TGNumberEntry.cxx
Bad formatting of list in https://root.cern.ch/doc/master/classTGNumberEntry.html
=> [NFC] Fix doxygen formating in tgnumberentry

README/ReleaseNotes/v630/index.md, tutorials/tmva/RBatchGenerator_NumPy.py, tutorials/tmva/RBatchGenerator_PyTorch.py, tutorials/tmva/RBatchGenerator_TensorFlow.py
=> [v630] Make RBatchGenerator more visible for the release

core/base/src/TString.cxx
=> [6.30] Backport of 14261

core/foundation/inc/TError.h, core/foundation/src/RLogger.cxx, core/foundation/src/TError.cxx
=> [6.30] Backport of #14276

core/metacling/test/TClingLoadUnloadFileTests.cxx
Fails sporadically, https://github.com/root-project/root/issues/14121
=> [core] Disable TClingLoadUnloadFileTests

roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h, roofit/xroofit/src/coutCapture.h, roofit/xroofit/src/xRooBrowser.cxx, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooHypoSpace.cxx, roofit/xroofit/src/xRooNLLVar.cxx, roofit/xroofit/src/xRooNode.cxx
Latest updates for xRooFit API. Includes a bug fix for jupyter notebook plot display in 6.30 onwards
Due to changes in the 6.30 jupyter notebook behaviour, this PR is required to fix the display of plots in these notebooks. 
Also includes a new method for creating a hypoSpace for limit calculations, with explicit specification of the test statistic type.
Some other minor improvements are included.
=> [RF] Update xroofit

cmake/modules/SetROOTVersion.cmake, config/root-config.in
Backport of https://github.com/root-project/root/pull/14231.
=> [v630][root-config] Fix --git-revision:

hist/hist/src/TH3.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_Project3D_name.cxx
Fix https://root-forum.cern.ch/t/project3d-letter-d-in-name-option/57612
=> Fix projection name

config/thisroot.sh
Solution provided by @dkonst13
Fixes https://github.com/root-project/root/issues/14324
=> thisroot.sh zsh compatibility

roofit/roofitcore/inc/RooRealIntegral.h, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooRealIntegral.cxx
Closes https://github.com/root-project/root/issues/14320.
=> [RF] Bugfixes and code improvements in RooRealIntegral

tmva/sofie/CMakeLists.txt, tmva/sofie/inc/TMVA/OperatorList.hxx, tmva/sofie/inc/TMVA/ROperator_EyeLike.hxx, tmva/sofie/test/TestCustomModelsFromONNX.cxx, tmva/sofie/test/input_models/EyeLike.onnx, tmva/sofie/test/input_models/references/EyeLike.ref.hxx, tmva/sofie_parsers/CMakeLists.txt, tmva/sofie_parsers/src/ParseEyeLike.cxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
This PR implements the EyeLike operator with corresponding unit tests which also includes the contribution of @lmoneta for fixing the generated code.
=> [TMVA][SOFIE] EyeLike ONNX operator implemented with tests

.github/CODEOWNERS
=> [Skip-CI] Update code owners

graf2d/graf/src/TLegend.cxx
This PR implements https://github.com/root-project/root/issues/14381
=> Exclusion graph legend.

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx
v6-30 version of https://github.com/root-project/root/pull/14200
=> v6-30 Core: Avoid (indirect) memory hoarding in TPluginManager.

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx
v6-28 version of https://github.com/root-project/root/pull/14200
=> v6-28 Core: Avoid (indirect) memory hoarding in TPluginManager.

tutorials/CMakeLists.txt, tutorials/tmva/TMVA_CNN_Classification.C, tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/TMVA_RNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.py
This is a back port of one commit of #13818
=> [v628][tmva] Backport fixes in tmva CNN and RNN tutorials

tutorials/gui/CPUMeter.C
avoid crash if picture not found
and allow compilation, there was a missing header
=> [tutorials] safer version of CPUMeter.C

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx
Fix random crashes of the `imt101_parTreeProcessing` tutorial on Windows
=> [core] Fix random crashes on Windows

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTPythonize.h, bindings/pyroot/pythonizations/src/TDirectoryPyz.cxx
There is no need to do this on the C++ side.
=> [PyROOT] Do `__getattr__` pythonization of TDirectory in Python

core/base/inc/TPluginManager.h
Fix random crashes of the `imt101_parTreeProcessing` tutorial on Windows
=> [v6-28][core][backport] Fix random crashes on Windows

tutorials/tmva/TMVA_CNN_Classification.C
Some improvements to the tutorial which might help with the frequent CI failures (as seen for example at https://github.com/root-project/root/actions/runs/7648815978/job/20842218312)
=> Improvements to tutorial TMVA_CNN_Classification 

core/rint/src/TRint.cxx
Simple PR, changes the year from 2023 to 2024
=> [skip-ci][Core] Change logo date from 2023 to 2024

core/rint/src/TRint.cxx
BP of https://github.com/root-project/root/pull/14447
=> [skip-ci]Banner dates bp630

core/rint/src/TRint.cxx
https://github.com/root-project/root/pull/14447
=> [skip-ci] Banner dates bp628

roofit/roofitcore/inc/RooEffProd.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/src/RooEffProd.cxx
=> Changes to RooEffProd class

hist/hist/inc/TFormula.h, roofit/roofitcore/inc/RooFormulaVar.h, roofit/roofitcore/inc/RooGenericPdf.h, roofit/roofitcore/src/RooFormula.h, roofit/roofitcore/src/RooFormulaVar.cxx, roofit/roofitcore/src/RooGenericPdf.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
RooFormulaVar.cxx
RooGenericPdf.cxx
RooFormulaVar.h
RooGenericPdf.h
=> RooFormulaVar and RooGenericPdf Changes

core/base/inc/TROOT.h, core/base/src/TApplication.cxx, core/base/src/TROOT.cxx, core/gui/src/TBrowser.cxx, core/gui/src/TGuiFactory.cxx, gui/gui/src/TRootGuiFactory.cxx, tree/treeplayer/src/TTreePlayer.cxx
=> [webgui] disable rootrc parameters for web-based widgets, disable --web flag [6.28]

gui/browserv7/src/RBrowser.cxx, gui/gui/src/TRootBrowser.cxx, gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx, gui/webdisplay/src/RWebWindowsManager.cxx, net/http/src/THttpServer.cxx
Backport of https://github.com/root-project/root/pull/14189
=> change loopback via API, do not expose server dirs [6.28]

bindings/tpython/src/TPyArg.cxx, bindings/tpython/src/TPyClassGenerator.cxx, bindings/tpython/src/TPyReturn.cxx, bindings/tpython/src/TPython.cxx
Avoid including any headers from the `CPyCppyy/src` directory.
=> [PyROOT] Use public CPyCppyy API in TPython

hist/hist/src/TF1.cxx
See details [here](https://github.com/root-project/root/issues/14385).
=> Fix TF1::Update which reset fHistogram attributes

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx
In preparation of moving RPageSource to Internal namespace.
=> [ntuple] remove page source based Create overload of inspector

tutorials/CMakeLists.txt, tutorials/graphics/arrows.C, tutorials/graphics/crown.C, tutorials/graphics/diamond.C, tutorials/graphics/ellipse.C
Simplify some graphics examples.
=> Simplify some graphics examples.

math/mathcore/src/Fitter.cxx, test/stressHistoFit.cxx
=> [math][fitter] Fix crash when doing a weighted likelihood fit

hist/hist/src/THStack.cxx
=> [skip-ci] Fix a few typos in the THStack doc

hist/histpainter/src/THistPainter.cxx
The same option did not work properly as explained here:
https://github.com/root-project/root/issues/6811
=> Make sure option SAME works for TGraph2D

hist/hist/src/HFitImpl.cxx
Use now a lock to create the TVirtualFitter class also in the case when ROOT is having MT enabled. Only the 'User' fitting option cannot be use din multi-thread mode, since it relies on a static global TVirtulFitter. Disable then that option when running in MT.
Fix also printing of FitResult in MT
This Pull request fixes issue #13041 and also still works (it is a better fix) for https://sft.its.cern.ch/jira/browse/ROOT-7300
In that case the correct fix was applied for histogram/graph fitting but not for TTree Unbinned fits. 
Fixes also the print of the fit results when running in multi-thread as in the example code posted in ROOT-7300
=> [hist] Fix creating the TVirtualFitter with MT

tutorials/hist/th2polyUSA.C
by adding more descriptive title, labels and reference for the population numbers.
=> [doc] Improve description on the USA map

graf2d/graf/inc/TPave.h, graf2d/graf/src/TPaveLabel.cxx, graf2d/graf/src/TPaveStats.cxx, graf2d/graf/src/TPaveText.cxx, graf2d/graf/src/TPavesText.cxx
Document how to remove shadow of TPave, as it is not evident (I only found explanations hidden here and there in the forum)
=> [skip-ci] document how to remove shadow of TPave, as it is not evident (only explained in the forum)

hist/hist/src/TH1.cxx
=> [skip-ci] add clarification to TH1::Chi2Test documentation

tree/dataframe/src/RDFHelpers.cxx
This PR fixes the stream formatting in RDataFrame ProgressBar.
This PR fixes [#14611](https://github.com/root-project/root/issues/14611).
=> [DF] restore stream state in ProgressBar

tree/tree/test/TChainParsing.cxx
Adds a test for https://github.com/root-project/root/issues/7159
=> [skip-ci][tree] Add unit test for issue #10556

hist/hist/src/TProfile.cxx
=> [skip-ci][doc] TProfile: clarify error calculation formula

tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/src/RColumn.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx
=> [ntuple] RColumn: Distinguish ConnectPage{Sink,Source}

tmva/sofie/test/TestSofieModels.cxx
Backport of https://github.com/root-project/root/pull/14535
=> [6.30] [tmva] Relax float comparison in test

tmva/sofie/test/TestSofieModels.cxx
Backport of https://github.com/root-project/root/pull/14535
=> [6.28] [tmva] Relax float comparison in test

core/foundation/src/RConversionRuleParser.cxx
Fixes #14462
- [n/a] updated the docs (if necessary)
This PR fixes #14462
=> Allow for whitespace between last brace and quote

README/ReleaseNotes/v632/index.md, roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.h, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx, roofit/roofitcore/test/testTestStatistics.cxx, tutorials/roostats/rs_numberCountingCombination.C
Part of the plan of work 2024.
The first two commits are final bugfixes to get all-green tests.
=> [RF] Make new CPU evaluation backend the default

core/base/inc/ROOT/TExecutorCRTP.hxx, core/base/inc/ROOT/TSequentialExecutor.hxx, core/imt/inc/ROOT/TExecutor.hxx, core/imt/inc/ROOT/TThreadExecutor.hxx, core/multiproc/inc/ROOT/TProcessExecutor.hxx
Closes https://github.com/root-project/root/issues/7872
=> [core] Prevent void return type from Map function

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h, interpreter/cling/test/Prompt/ValuePrinter/FileSystemPath.C
=> [cling] Implement value printing for `std::filesystem::path`

hist/hist/inc/TH2Poly.h, hist/hist/src/TH1.cxx, hist/hist/src/TH2Poly.cxx, hist/hist/test/test_TH2Poly_BinError.cxx
Add TH2Poly::Copy function and implement also using Copy the copy ctor and assignment operator
- [x ] updated the docs (if necessary)
This PR fixes #13075
=> [hist] Implement Copy for TH2Poly

math/genvector/inc/Math/GenVector/Cartesian2D.h, math/genvector/inc/Math/GenVector/Cartesian3D.h, math/genvector/inc/Math/GenVector/Cylindrical3D.h, math/genvector/inc/Math/GenVector/CylindricalEta3D.h, math/genvector/inc/Math/GenVector/DisplacementVector2D.h, math/genvector/inc/Math/GenVector/DisplacementVector3D.h, math/genvector/inc/Math/GenVector/LorentzVector.h, math/genvector/inc/Math/GenVector/Polar2D.h, math/genvector/inc/Math/GenVector/Polar3D.h, math/genvector/inc/Math/GenVector/PositionVector2D.h, math/genvector/inc/Math/GenVector/PositionVector3D.h, math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h, math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h, math/genvector/inc/Math/GenVector/PxPyPzE4D.h, math/genvector/inc/Math/GenVector/PxPyPzM4D.h, math/genvector/inc/Math/GenVector/Quaternion.h
This PR implements requested changes in [ROOT-8384](https://its.cern.ch/jira/browse/ROOT-8384)
=> [genvector] Add Dimension field

gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowsManager.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/draw/TGaxisPainter.mjs, js/modules/draw/TLinePainter.mjs, js/modules/draw/TTree.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui.mjs, js/modules/gui/display.mjs, js/modules/gui/menu.mjs, js/modules/gui/utils.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/io.mjs, js/modules/tree.mjs, net/http/src/THttpServer.cxx
Follow up of #14136 
Also update JSROOT with several fixes
=> [webgui] improve docu on new auth functionality

main/python/rootcp.py, main/python/rootmv.py
Fixes https://github.com/root-project/root/issues/6349
=> [root{cp,mv}] Improve documentation of compression settings

core/foundation/src/RConversionRuleParser.cxx
To avoid having to use regex to parse trailing curly brackets with/without trailing whitespaces, the code command string is cleaned with the following strategy:
- Trim whitespaces at the borders
- Get the inner command (i.e. the part between quotes)
- Trim whitespaces again
- Stitch back together
This should fix the unforeseen PyTorch failures brought by PyTorch's snafu (as described and https://github.com/pytorch/pytorch/issues/49460#issuecomment-911365091) and triggered by the use of std::regex introduced in https://github.com/root-project/root/pull/14716 
This replaces https://github.com/root-project/root/pull/14716 to fix https://github.com/root-project/root/issues/14462
=> [core] Clean code command in rule parsing

tmva/sofie/test/TestSofieModels.cxx
Backport of https://github.com/root-project/root/pull/14738
=> [6.28][tmva] Completely relax float comparison in TestSofieModels

core/imt/inc/ROOT/TExecutor.hxx, core/imt/src/TExecutor.cxx
- [ x] updated the docs (if necessary)
#7871
=> WIP - [TExecutor] Usability of TExecutor::MapReduce

cmake/modules/RootConfiguration.cmake, config/rootrc.in, gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayHandle.cxx
=> [webgui] Use `--headless=new` for newer chrome browser [6.30]

cmake/modules/RootConfiguration.cmake
On windows interactive browser is started - which is not intended
=> [cmake] do not test chrome version on windows

hist/hist/inc/TH1.h, hist/hist/src/TH1.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_TH1_SaveAs.cxx
Add SaveAs method to TH1, saving to .csv, .tsv or .txt
This PR fixes #10474
=> [hist] Add SaveAs method to TH1

math/mathcore/src/Fitter.cxx
Apply the suggestion by Jonas in PR #14763
=> [math][fit] Use enumerations instead of the integer values

tree/dataframe/inc/LinkDef.h, tree/dataframe/inc/ROOT/RDF/RCutFlowReport.hxx, tree/dataframe/test/dataframe_report.cxx
=> Enable I/O for RCutFlowReport

hist/hist/src/TLimit.cxx, hist/spectrum/src/TSpectrum.cxx, hist/spectrum/src/TSpectrum2.cxx, hist/spectrum/src/TSpectrum2Fit.cxx, hist/spectrum/src/TSpectrum2Transform.cxx, hist/spectrum/src/TSpectrum3.cxx, hist/spectrum/src/TSpectrumFit.cxx, hist/spectrum/src/TSpectrumTransform.cxx, math/minuit/doc/index.md, math/minuit/src/TFitter.cxx, math/minuit/src/TLinearFitter.cxx, math/minuit/src/TLinearMinimizer.cxx, math/minuit/src/TMinuit.cxx, math/minuit/src/TMinuitMinimizer.cxx, math/physics/src/TFeldmanCousins.cxx, math/physics/src/TGenPhaseSpace.cxx, math/physics/src/TLorentzRotation.cxx, math/physics/src/TQuaternion.cxx, math/physics/src/TRobustEstimator.cxx, math/physics/src/TRolke.cxx, math/physics/src/TRotation.cxx, math/physics/src/TVector2.cxx
Adds deprecation messages to classes that are no longer recommended.
This PR fixes https://github.com/root-project/root/issues/14582
Fixes https://its.cern.ch/jira/browse/ROOT-8594
=> [skip-ci] add deprecation messages to outdated classes

tmva/tmva/inc/TMVA/Results.h, tmva/tmva/inc/TMVA/ResultsClassification.h, tmva/tmva/inc/TMVA/ResultsMulticlass.h, tmva/tmva/inc/TMVA/ResultsRegression.h
Maybe it fixes https://github.com/root-project/root/issues/14438, maybe not.
I don't have tmva compiled in debug mode, so I'd appreciate if @vepadulano  you can run valgrind for me to cross-check ;)
=> [tmva] fix bug in classdef name

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
=> [ntuple] Allow RNTupleModel to create field tokens

hist/hist/inc/TH1.h, hist/hist/src/TH1.cxx, hist/hist/test/test_TH1_SaveAs.cxx
Fixes https://github.com/root-project/root/issues/14863
=> [hist] fix missing default parameters in save-as

.github/workflows/root-ci.yml, .github/workflows/root-master.yml
by delegating the schedule trigger to one file per branch.
=> [skip-CI][CI] Refactor the GHA code that nightly builds

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist/TGraph2DPainter.mjs
Support plain "TRI" draw option for TGraph2D
Fixes problem from forum:
https://root-forum.cern.ch/t/how-to-draw-a-3d-polygon/58371
=> [jsroot] 7.5.5 4/03/2024

io/io/src/TBufferFile.cxx, io/io/src/TBufferJSON.cxx, io/sql/inc/TBufferSQL2.h, io/sql/src/TBufferSQL2.cxx, io/xml/src/TBufferXML.cxx, tree/tree/src/TBufferSQL.cxx
Prevent infinite loops and add more security for overflows
Fixes in part https://github.com/root-project/root/issues/14770
=> [io] Prevent infinite loops and add more security for overflows

tmva/tmva/inc/TMVA/DecisionTreeNode.h, tmva/tmva/src/DecisionTreeNode.cxx
Absence of safety in public methods resulting in nullptr access if ftraininfo was undefined by constructor.
Fixes https://github.com/root-project/root/issues/14569
=> [tmva] fix nullptr access in public methods of ftraininfo

hist/hist/src/THStack.cxx
Fix GetZaxis - may fail while dimension was checked before checking histogram
Simplify code - avoid gPad testing
=> Improve THStack::GetAxis methods

io/io/src/TFile.cxx
https://sft.its.cern.ch/jira/browse/ROOT-7280
=> Prevent leaks from ExpandPathName (ROOT-7280)

js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw/TLinePainter.mjs, js/modules/draw/TRatioPlotPainter.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/menu.mjs, js/modules/gui/utils.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist2d/THistPainter.mjs
Now TRatioPlot appears as first object in list of primitives and one assign interactive handlers after all other pad primitives are drawn.
Keep support of older files with TRatioPlot as well
Better support of optdate, optfile options
Use localStorage for JSROOT settings storage - no cookies
This PR fixes #14842
=> [jsroot] dev 7/03/2024 with new TRatioPlot support

math/vecops/inc/ROOT/RVec.hxx, math/vecops/test/vecops_rvec.cxx
fixing issue
https://github.com/root-project/root/issues/14914
=> Fix boundary check for VecOps::Take

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/test/numbadeclare.py
BP of
https://github.com/root-project/root/pull/12159 and https://github.com/root-project/root/pull/12827
=> [backports] Numpy backports

bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
Given the following function declared to ROOT and accessed via a Python proxy:
```
int foo(int x);
```
Currently accessing its `func_doc`, which in turn calls `CPPMethod::GetPrototype`, gives:
'int ::foo(int x)'
The extra set of '::' can be avoided by checking that the function is not declared inside a namespace.
Note: this is a check, may be not worthy in the end if we find places that rely on those extra "::" being present
=> [PyROOT] Improve output of CPPMethod::GetPrototype

tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
Even if not writing anything, return the cluster size in bytes from `RPageNullSink::CommitCluster` because it is used by `RNTupleFillContext` to estimate the compression ratio. Returning zero resulted in severely oversized clusters which made it hard to evaluate overhead with it.
=> [ntuple] Return cluster size from RPageNullSink

core/base/src/TDirectory.cxx, core/base/src/TTimeStamp.cxx, core/base/src/TUri.cxx, core/base/src/TUrl.cxx, core/thread/src/TThread.cxx
https://github.com/root-project/root/pull/10961
=> [backports ] Remove warnings at build time

math/minuit/src/TLinearFitter.cxx, math/physics/src/TRobustEstimator.cxx
=> [skip-ci] fix typo docu stray braces

core/base/inc/TSystem.h, core/base/src/TSystem.cxx, core/base/test/TSystemTests.cxx, core/unix/CMakeLists.txt, core/unix/inc/TUnixSystem.h, core/unix/src/TUnixSystem.cxx, core/winnt/CMakeLists.txt, core/winnt/inc/TWinNTSystem.h, core/winnt/src/TWinNTSystem.cxx
=> Try to introduce TSystem::GetCryptoRandom

math/minuit/src/TMinuit.cxx
=> [Math] Do not modify dbg message if never printed

hist/hist/src/TSpline.cxx
=> [hist] Remove memory leak in TSpline3 copy ctor

math/mathcore/src/TMath.cxx
Fixes [ROOT-7289](https://its.cern.ch/jira/browse/ROOT-7289)
=> [skip-ci][math] Improve documentation of cumulative distributions in Math

hist/hist/src/TMultiDimFit.cxx
fixes ROOT-7801
https://its.cern.ch/jira/browse/ROOT-7801
=> [Math] Fix typo in generated code

roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooNode.cxx
Backport of https://github.com/root-project/root/pull/14900.
=> [v630][RF] Update xroofit

math/mlp/src/TMultiLayerPerceptron.cxx
fixes ROOT-8501
https://its.cern.ch/jira/browse/ROOT-8501
=> [math] Detach TEventList instances from gDirectory

gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx, gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowsManager.cxx
Used keys length will be 32 bytes or 256 bits.
Use hex for string representation.
Add in produced string "-" symbols as separator between every 4 bytes Keys string representation will be 32*2 + 7 = 71 characters. Like:
fca45856-41bee066-ff74cc96-9154d405-df85aa28-9a0a4794-ae70243f-1ac560f4
=> [webgui] use gSystem->GetCryptoRandom() to generate keys

tmva/pymva/src/MethodPyAdaBoost.cxx, tmva/pymva/src/MethodPyGTB.cxx, tmva/pymva/src/MethodPyRandomForest.cxx, tmva/pymva/src/RModelParser_PyTorch.cxx
With new version (1.4) of scikit-learn the bool parameters must be passed as bool and not anymore as integers.
In addition in AdaBoost base_estimator was renamed to estimator
This Pull request should fix failures observed in PR builds when the new version (1.4) of scikit-learn is used
=> [tmva][pymva] Changes for new version (1.4) of scikit-learn

tmva/pymva/src/MethodPyAdaBoost.cxx, tmva/pymva/src/MethodPyGTB.cxx, tmva/pymva/src/MethodPyRandomForest.cxx, tmva/pymva/src/RModelParser_PyTorch.cxx
=> [tmva][pymva] Backport in 6.30 pymva fixes for new versions of torch and sklearn

bindings/pyroot/pythonizations/python/ROOT/_facade.py, tutorials/dataframe/df035_RDFFromPandas.py
- Simplifies the importing of Pandas data frames to RDataFrame. 
- Added tutorial `df035_RDFFromPandas.py` to demonstrate this functionality
none
=> [RDF] Import a Pandas data frame to RDataFrame

roofit/roofitcore/inc/RooEfficiency.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/src/RooEfficiency.cxx
=> [RF] Added code generation support for RooEfiiciency

graf2d/graf/src/TGaxis.cxx
Use proper arguments, make similar output as
with TGaxis::ChangeLabel
Fixes building of documentation
=> Fix error in TGaxis::ChangeLabelByValue docu macro [skip-ci]

tutorials/CMakeLists.txt
Disable `df035_RDFFromPandas.py` test until a proper fix is found
=> [DF][Windows] Disable df035_RDFFromPandas

core/base/src/TColor.cxx
The inline code was "old style" without "auto".
This PR fixes it.
=> [skip-ci] Fix TColor inline code

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rtensor.py, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTPythonize.h, bindings/pyroot/pythonizations/src/PyzPythonHelpers.cxx
=> [628] Backport 15011

core/base/inc/TColor.h, core/base/src/TColor.cxx
This pull request adds two methods to TColor: ListColors()n and GetColorByname().
=> New methods

hist/hist/src/TH1.cxx, hist/hist/src/TH2Poly.cxx, hist/hist/src/THnBase.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-8274
=> [hist] explain better what computeIntegral does

tree/dataframe/src/RDataFrame.cxx
=> [skip-CI][DF][NFC] Mention AsRNode in the progress bar documentation

graf2d/asimage/CMakeLists.txt, graf2d/asimage/src/TASImage.cxx
https://github.com/root-project/root/pull/14960/
=> [Backport][graphics] Save memory when obtaining TImageDump instance

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/rfield_class.cxx
Adds a unit test for regular (non-virtual) inheritance. Forbids virtual inheritance (and tests for it).
Fixes #15048
=> [ntuple] clarify diamond inheritance

tutorials/roostats/CreateExampleFile.py, tutorials/roostats/HybridInstructional.py, tutorials/roostats/HybridStandardForm.py, tutorials/roostats/TestNonCentral.py, tutorials/roostats/TwoSidedFrequentistUpperLimitWithBands.C, tutorials/roostats/TwoSidedFrequentistUpperLimitWithBands.py
Converts HybridStandardForm.C, HybridInstructional.C, TwoSidedFrequentistUpperLimitWithBands.C, TestNonCentral.C, and CreateExampleFile.C to Python
Contributes to  https://github.com/root-project/root/issues/8758
=> [RF] Convert 4 RooStat tutorials to PyROOT

io/io/src/TFileMerger.cxx
Fixes https://github.com/root-project/root/issues/13531
@romainbqt could you verify if this patch solves your problem?
=> [hadd] avoid large RAM usage in hadd with multiple subdirs

tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/rfield_class.cxx
=> [ntuple] fix cycle detection for collection proxy classes

math/physics/src/TGenPhaseSpace.cxx
Fixes https://github.com/root-project/root/issues/14765
@jjerhot this class is marked as legacy, but if you want, feel free to propose how the normalization factor should look like and I can try to implement it.
=> [skip-ci,math] Specify that returned weight is not normalized

cmake/modules/RootCPack.cmake
Fix Jira issue ROOT-10926 https://its.cern.ch/jira/browse/ROOT-10926
=> [cmake][windows] Don't install system DLLs

hist/hist/src/TSpline.cxx
Fixes https://github.com/root-project/root/issues/13441
=> [hist] fix bug in TSpline3 TSpline5 save-as code

tutorials/CMakeLists.txt, tutorials/tmva/TMVA_SOFIE_Inference.py, tutorials/tmva/TMVA_SOFIE_RDataFrame.py
Fix the dependency of Python and C++ tutorials using the Higgs_trained_model.h5 file
=> [tmva][tutorials] Fix dependency of TMVA tutorials

.github/workflows/root-632.yml
=> [skip-ci][ci] Add scheduled builds for 6.32

hist/hist/src/TF1NormSum.cxx
Fixes Nullptr access after raising Error.
=> [hist] prevent nullptr access

io/io/src/TFile.cxx
BP of https://github.com/root-project/root/pull/14929
=> [skip-ci] [BP] [io] Collapse data format details of TFile class

hist/hist/src/TF1NormSum.cxx
BP of https://github.com/root-project/root/pull/15094
=> [v632][BP] [hist] prevent nullptr access

hist/hist/src/TSpline.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_spline.cxx
Fixes https://github.com/root-project/root/issues/12091
=> [hist] Improve precision of TSpline SaveAs

gui/fitpanel/src/TFitEditor.cxx
Fixes https://github.com/root-project/root/issues/11021
=> [gui] Do not reset FitPanel parameters when ADD on top of prefitted function

hist/hist/src/TSpline.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_spline.cxx
BP of https://github.com/root-project/root/pull/15078/commits
=> [Backport][hist] Improve precision of TSpline SaveAs

rootx/src/rootx.cxx
=> Fix sprintf warning

core/base/src/TApplication.cxx, core/base/src/root-argparse.py, core/metacling/src/TCling.cxx
Backport of https://github.com/root-project/root/pull/14813.
=> [v632][cling] Allow running named macro from shared library

hist/hist/inc/THnSparse.h, hist/hist/src/THnBase.cxx
Backport of https://github.com/root-project/root/pull/15066.
=> [v632][hist] THnSparse::Scale iterate only over non-filled bins

.ci/format_script.sh, tree/ntuple/v7/test/CustomStructLinkDef.h
=> Fix file exclusion in format checker

tree/tree/src/TChain.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-8129
The other option would be to add safety-checks in the code, but that would be probably detrimental to efficiency and defeat the purpose of option B ?
=> [skip-ci] TChain::AddFile clarify that no check is done if nentries>0

.github/workflows/code_analysis.yml
=> [ci] Fetch exactly the PR base sha for clang-format

main/src/hadd.cxx
Fixes https://github.com/root-project/root/issues/14910
=> [hadd] fix processing of indirect file when multiprocess is enabled

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rbdt.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, tmva/tmva/test/CMakeLists.txt, tutorials/CMakeLists.txt
Representing the current situation at https://github.com/root-project/root/issues/15197
=> [tmva] Warn when using RBDT and xgboost

tutorials/tmva/tmva101_Training.py, tutorials/tmva/tmva102_Testing.py
Backporting parts of 363373bb987 to make the tests green.
=> [v626][TMVA] Fix tutorials

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rbdt.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, tmva/tmva/test/CMakeLists.txt, tutorials/CMakeLists.txt
Representing the current situation at https://github.com/root-project/root/issues/15197
=> [6.32] Backport of #15198

rootx/src/rootx.cxx
which is more secure.
BP of https://github.com/root-project/root/pull/15134
=> [v632][Core] Fix sprintf warning

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rbdt.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, tmva/tmva/test/CMakeLists.txt, tutorials/CMakeLists.txt
Representing the current situation at https://github.com/root-project/root/issues/15197
=> [6.28] Backport of #15198

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rbdt.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, tmva/tmva/test/CMakeLists.txt, tutorials/CMakeLists.txt
Representing the current situation at https://github.com/root-project/root/issues/15197
=> [6.30] Backport of #15198

tutorials/tmva/TMVAClassification.C
Maybe this can help with timeouts such as https://github.com/root-project/root/actions/runs/8645662018/job/23703294577?pr=15200
=> Tmva tutorial improvements

tree/tree/inc/TTree.h, tree/tree/src/TTree.cxx, tree/treeplayer/src/TTreePlayer.cxx
=> [skip-ci] document TTree::SetScanField

hist/hist/inc/THnBase.h, hist/hist/src/THnBase.cxx, hist/hist/test/THn.cxx
Fixes https://github.com/root-project/root/issues/14173
=> [hist] THn: Add GetBinCenter and Integral helper methods

hist/histpainter/src/THistPainter.cxx
Smalle doc fixes in THistPainter
=> [skip-ci] small doc fixes

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx, tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RNTupleMerger.cxx, tree/ntuple/v7/src/RNTupleParallelWriter.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_merger.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
As discussed, backport the following two PRs to complete the RNTuple merging feature for 6.32:
* https://github.com/root-project/root/pull/15111
* https://github.com/root-project/root/pull/15154
@amete
=> [ntuple] Implement incremental merging + Use CommitSealedPagesV [v6.32]

cmake/modules/RootBuildOptions.cmake
Adds a comment in a cmake file
maybe improves notification probability
=> CMAKE: add comment for deprecating cmake options to notify SPI please

tree/treeplayer/src/TTreeFormula.cxx
BP of https://github.com/root-project/root/pull/15176
=> [v632][BP][tree] prevent crash in LoadCurrentDim

hist/hist/inc/TH2Poly.h, hist/hist/src/TH1.cxx, hist/hist/src/TH2Poly.cxx, hist/hist/test/test_TH2Poly_BinError.cxx
Backport of https://github.com/root-project/root/pull/14732
Add TH2Poly::Copy function and implement also using Copy the copy ctor and
assignment operator# This Pull request:
This PR fixes #13075
=> [v630][hist] Implement Copy for TH2Poly

requirements.txt
This PR is for testing on 6.28 in the Linux CI the using of Python ML tools in TMVA
=> Add Python ML packages in requirements

roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
We want to demo this class, but nobody should believe it is stable yet.
To be backported to 6.32.
=> [RF] Put `RooFuncWrapper` in experimental namespace

roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
We want to demo this class, but nobody should believe it is stable yet.
Backport of https://github.com/root-project/root/pull/15201.
=> [v632][RF] Put `RooFuncWrapper` in experimental namespace

bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx, bindings/pyroot/cppyy/cppyy/test/test_regression.py
Backport of https://github.com/root-project/root/pull/15228.
=> [v632] Fix for calling static method with default argument

tree/tree/src/TChain.cxx, tree/tree/test/ImplicitMT.cxx
=> [tree] Propagate IMT settings of TChain to internal TTrees

graf2d/gpad/src/TPad.cxx
Add the objects from the list of functions as suggested here:
https://root-forum.cern.ch/t/multigraph-fit-not-showing-in-the-legend/58876
=> Add the objects from the list of functions in the Legend.

roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooFormula.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/xroofit/CMakeLists.txt, roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooFitVersion.h, roofit/xroofit/src/xRooHypoSpace.cxx, roofit/xroofit/src/xRooNLLVar.cxx, roofit/xroofit/src/xRooNode.cxx
This PR backports the following commits:
1. https://github.com/root-project/root/pull/15177
2. https://github.com/root-project/root/pull/15266
3. https://github.com/root-project/root/pull/15268
=> [v632][RF] RooFit backports to 6.32

math/vecops/inc/ROOT/RVec.hxx
Fixes [ROOT-10865](https://its.cern.ch/jira/browse/ROOT-10865)
=> [skip-CI][doc] Improve RVec operations documentation

tree/treeplayer/src/TTreePlayer.cxx, tree/treeplayer/src/TTreeReaderGenerator.cxx
BP of https://github.com/root-project/root/pull/15271
=> [BP] MakeClass/Selector: replace more special characters in branch name.

roofit/roofitcore/src/RooFormula.cxx
=> [roofit] Document unused parameter in constructor

core/rint/src/TTabCom.cxx
BP of https://github.com/root-project/root/pull/15229
=> [v6.32][BP] tab completion: insert match but do not replace the content after it

tree/treeplayer/inc/TTreeReaderArray.h, tree/treeplayer/inc/TTreeReaderValue.h, tree/treeplayer/src/TTreeReaderValue.cxx, tree/treeplayer/test/readerarray_iterator.cxx
Fixes [ROOT-11006](https://its.cern.ch/jira/browse/ROOT-11006)
=> [TreeReader] Add value printers for TTreeReaderArray/Value

.github/workflows/root-ci-config/build_root.py, LICENSE, README.md
since no release is in sight to be able to have the same PR and nightly builds.
=> [ci] Add GPL options

cmake/modules/RootConfiguration.cmake, core/base/src/TROOT.cxx, gui/gui/src/TRootGuiFactory.cxx
6.32 version of https://github.com/root-project/root/pull/13872
=> [webcanvas] make default off for the TWebCanvas

tree/treeplayer/inc/TTreeReaderArray.h, tree/treeplayer/inc/TTreeReaderValue.h, tree/treeplayer/src/TTreeReaderValue.cxx, tree/treeplayer/test/readerarray_iterator.cxx
BP of https://github.com/root-project/root/pull/15317/commits
=> [BP-v6.32][TreeReader] Add value printers for TTreeReaderArray/Value

gui/CMakeLists.txt, gui/webdisplay/CMakeLists.txt, gui/webdisplay/src/RWebDisplayHandle.cxx
If local web display configured,
only build variants will be tested.
Fixes issue #15340
Backport of #15345
=> [webgui] try local displays only if they build [6.32]

.github/workflows/root-ci-config/build_root.py, LICENSE, README.md
BP of https://github.com/root-project/root/pull/15158/commits
=> [BP][ci] Add GPL options

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/d3.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/utils.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/io.mjs
JSROOT code for 6.32 release
It is copy of special branch from JSROOT repository: https://github.com/root-project/jsroot/tree/v6-32-00-patches
=> [jsroot] latest code for 6.32 branch

core/base/inc/TObject.h, core/base/inc/TStorage.h, core/base/src/TObject.cxx, core/base/src/TStorage.cxx, core/foundation/inc/ROOT/RConfig.hxx, core/newdelete/src/NewDelete.cxx
=> [v632] Fix Clang build with libstdc++

core/base/inc/TObject.h, core/base/inc/TStorage.h, core/base/src/TObject.cxx, core/base/src/TStorage.cxx, core/foundation/inc/ROOT/RConfig.hxx, core/newdelete/src/NewDelete.cxx
Backport of https://github.com/root-project/root/pull/15354
=> [v630] Fix Clang build with libstdc++

tutorials/roostats/FourBinInstructional.C, tutorials/roostats/FourBinInstructional.py, tutorials/roostats/rs101_limitexample.C, tutorials/roostats/rs101_limitexample.py
This can be problematic in test environments.
=> Don't write files in RooStats tutorials for no reason

tutorials/CMakeLists.txt
BP of https://github.com/root-project/root/pull/15365. See https://github.com/root-project/root/issues/15364
=> [BP][ci] Disable tutorial-roostats-rs101_limitexample-py on Win

tmva/tmva/src/ClassifierFactory.cxx
Fixes crash seen in https://its.cern.ch/jira/browse/ROOT-9918
=> [tmva] assert is ignored in Release mode, so return null

tmva/tmva/src/DataSet.cxx
Fixes https://github.com/root-project/root/issues/10010
All the credit for this fix goes to @pcanal and anaumann
=> [tmva] branches on stack, local scope, reset before return

roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/roofitmore/src/RooHypatia2.cxx
Fixes https://github.com/root-project/root/issues/15370
File was moved in https://github.com/root-project/root/pull/13929/commits/6bb813f99eb174af95cd21aae9eb93f790a0a6e2
=> [RF] Fix link to file moved on GitHub

CMakeLists.txt, build/unix/makedistsrc.sh
BP of https://github.com/root-project/root/pull/15380
=> [BP 632][cmake] Fix distsrc script. 

requirements.txt, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/roofit/src/RooMomentMorphFuncND.cxx, roofit/roofitmore/src/RooHypatia2.cxx, tmva/tmva/src/ClassifierFactory.cxx, tmva/tmva/src/DataSet.cxx, tutorials/roostats/FourBinInstructional.C, tutorials/roostats/FourBinInstructional.py, tutorials/roostats/rs101_limitexample.C, tutorials/roostats/rs101_limitexample.py
@ferdymercury FYI, since several of your commits are included in this backport.
=> [v632] Backports of recent fixes

.github/workflows/root-ci-config/buildconfig/fedora38.txt, .github/workflows/root-ci.yml
The distribution is at its EOL.
=> [ci] Remove Fedora 38 builds

core/clingutils/src/TClingUtils.cxx, core/clingutils/test/TClingUtilsTests.cxx
This PR fixes # https://github.com/root-project/root/issues/15384
=> [Tcling] Add more characters that are invalid in a C++ variable name
