- core/cont/inc/TVirtualCollectionProxy.h
- core/meta/inc/TListOfEnums.h
- core/meta/src/TClass.cxx
- core/meta/src/TListOfEnums.cxx
- core/meta/src/TListOfEnumsWithLock.cxx
- core/meta/src/TProtoClass.cxx
- core/metacling/src/TCling.cxx
- io/io/inc/TGenCollectionProxy.h
- io/io/src/TBufferFile.cxx
- io/io/src/TGenCollectionProxy.cxx
- io/io/src/TStreamerInfo.cxx
- io/rootpcm/src/rootclingIO.cxx
This repairs crash seem in [testProxiesAndCategories](https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/139900/testReport/projectroot.roofit.roofitcore/test/gtest_roofit_roofitcore_test_testProxiesAndCategories/) on the v6.24 branches and a few additional issues seen during testing.
> Additional fixes for std::pair's StreamerInfo handling

- roofit/roofitcore/inc/LinkDef.h
- roofit/roofitcore/inc/RooFit/UniqueId.h
- roofit/roofitcore/inc/RooNormSetCache.h
- roofit/roofitcore/src/RooNormSetCache.cxx
This change was considered for some time now, and a bug recently
reported on the forum was the final motivation to open this PR:
https://root-forum.cern.ch/t/roodecay-getval-normalization-problem/49457
There are many problems with the pointer comparisons:
1. If normalization sets are created on the stack it can often happen
that the same address gets reused (as happened in that forum post,
more precisely in the implementation of `RooAddModel`)
2. Memeory might also be reused on the heap, which lead to the
developement of a memory arena where memory is not reused. This
memory arena often causes other problems related to heap
fragmentation or dictionaries.
3. Pointer comparisons still work if the RooArgSets for the cache
entry are already out of scope, which can also cause problems
The …
> [RF] Use `RooArgSet::uniqueId` instead of pointers in RooNormSetCache

- tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
`RTreeColumnReader` now uses `swap` in stead of `std::swap`.
> [DF] Use swaps inside the RTreeColumnReader

- math/vecops/inc/ROOT/RVec.hxx
- math/vecops/test/vecops_rvec.cxx
* Rvec can now correctly swap small and adopting vectors with RVec's `swap` function
* Introduce ROOT::Detail::VecOps::IsSmall(v) and ROOT::Detail::VecOps::IsAdopting(v) to check whether an RVec is small and owning its memory respectively
* Added a corresponding test suite
This PR fixes #10297
> [VecOps] Fix #10297. Teach Rvec's to swap small and adopting vectors

- tutorials/hist/fillrandom.py
Use unique filenames in fillrandom.py and fillrandom.C
> Use unique filenames in fillrandom.py and fillrandom.C

- tutorials/gl/gltf3.C
Example failure:
562/1224 Test  #541: tutorial-gl-gltf3 ...................................................***Failed  Error regular expression found in output. Regex=[Error in <]  1.36 sec
Processing /builddir/build/BUILD/root-6.26.00/tutorials/gl/gltf3.C...
Error in <TList::Delete>: A list is accessing an object (0x7fffd1c959a0) already deleted (list name = Functions)
Error in <TList::Delete>: A list is accessing an object (0x7fffd1c95750) already deleted (list name = Functions)
> Avoid deleting TFormulas twice

- roofit/roofitcore/inc/RooFit/UniqueId.h
- roofit/roofitcore/inc/RooNormSetCache.h
- roofit/roofitcore/src/RooNormSetCache.cxx
This is to avoid crashes on 32-bit platforms. It's not necessary to use
64-bit integers anyway, because the return types of the caching codes
were `Int_t` anyway (now just int). And since caches are never part of
IO anyway, it's not important to be platform independent.
For the UniqueId, using `unsigned long` is fine too, because the unique
ID is transient and therefore doesn't need to be platform independent.
Any fixed-size choice here caused either problems on either 32- or
64-bit platforms.
This fixes crashes in the nightly builds on Debian 10 32-bit, which was verified on the Debian 10 build node.
> [RF] Change int types in UniqueId and RooNormSetCache

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/inc/RooAbsOptTestStatistic.h
- roofit/roofitcore/inc/RooArgSet.h
- roofit/roofitcore/inc/RooDataSet.h
- roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
- roofit/roofitcore/src/RooArgSet.cxx
- roofit/roofitcore/src/RooDataSet.cxx
Disables the memory pool for RooArgSet and RooDataSet to fix https://github.com/root-project/root/issues/8323.
This entails that we can't rely anymore on all RooDataSets allocated on the heap having a unique memory address, so a new `uniqueId` class member is introduced to replace the pointer comparisons.
The RooArgSet already had such a `uniqueId` class member, which is already used as a key for caching as of PR https://github.com/root-project/root/pull/10333, instead of doing pointer comparisons.
> [RF] Use UniqueId to replace pointer comparisons and disable memory pool

- roofit/batchcompute/src/RooBatchCompute.cxx
- roofit/roofitcore/src/RooFitDriver.cxx
* print the **value** of the `RF_ARCH` macro, not the macro name
* avoid looging same info repeatedly
> [RF] Fix architecture logging RooFitDriver

- roofit/batchcompute/src/Batches.h
- roofit/batchcompute/src/ComputeFunctions.cxx
- roofit/batchcompute/src/RooBatchCompute.cu
- roofit/batchcompute/src/RooBatchCompute.cxx
In the CPU case in `RooBatchCompute`, we can use `std::vector` instead
of fixed-size stack arrays to pass data around, and the `Batches` object
can be passed to the compute functions by reference.
This fixes crashes with models where the numer of inputs for a RooAbsArg
exceeds the maximum number of parameters supported by the fixed-size
array buffer, at least in the CPU case.
In the GPU case, we now throw a nicer error if the buffers are to small,
instead of just crashing.
The `stressRooFit` tests for the CPU or GPU batch mode still pass after
this commit.
> [RF] Don't used fixed-size stack arrays in RooBatchCompute in CPU case

- builtins/xrootd/CMakeLists.txt
For Ubuntu 22.04 we will otherwise get a build error.
See https://github.com/xrootd/xrootd/issues/1666
> [cmake] Enable openssl3 for xrootd:

- core/meta/src/TClass.cxx
This fixes #10357 (a race condition when reading vectors with custom
allocators with TTreeProcessorMT that also affected RDataFrame).
Co-authored-by: Philippe Canal <pcanal@fnal.gov>
EDIT: regression test at https://github.com/root-project/roottest/pull/866
> [I/O] Use thread-local collection proxy in TClass::Destructor

- core/meta/src/TClass.cxx
This fixes #10357 (a race condition when reading vectors with custom
allocators with TTreeProcessorMT that also affected RDataFrame).
Co-authored-by: Philippe Canal <pcanal@fnal.gov>
> [I/O] Use thread-local collection proxy in TClass::Destructor (v6.26)

- hist/hist/inc/TGraph.h
- hist/hist/src/TGraph.cxx
Implement the possibility to save TGraph* as .csv, .tsv and .txt
as requested here https://github.com/root-project/root/issues/9491
Test example:
```
{
auto c = new TCanvas("c","A Simple Graph without axis",700,500);
const Int_t n = 10;
auto gr = new TGraph(n);
gr->SetTitle("A Simple Graph");
gr->GetXaxis()->SetTitle("X axis");
gr->GetYaxis()->SetTitle("Y axis");
auto gre = new TGraphErrors(n);
gre->GetXaxis()->SetTitle("X axis");
gre->GetYaxis()->SetTitle("Y axis");
gre->SetTitle("A Simple Graph with errors");
auto gra = new TGraphAsymmErrors(n);
gra->GetXaxis()->SetTitle("X axis");
gra->GetYaxis()->SetTitle("Y axis");
gra->SetTitle("A Simple Graph with asymmetric errors");
auto grb = new TGraphBentErrors(n);
grb->GetXaxis()->SetTitle("X axis");
grb->GetYaxis()->SetTitle("Y axis"); …
```
> Implement SavesAs .csv, .tsv and .txt

- builtins/davix/CMakeLists.txt
Fixes macOS 12 builds (no "python", only "python3").
Davix now uses curl instead of neon.
(cherry picked from commit 4fb53c7adfb4df5fb2652b234c609af951a98edc)
> [cmake] Bump davix to 0.8.1 (v6.26)

- builtins/xrootd/CMakeLists.txt
For Ubuntu 22.04 we will otherwise get a build error.
See https://github.com/xrootd/xrootd/issues/1666
(cherry picked from commit f4bd8e740a99828d1232494b9d92a25fe2c39f65)
> [cmake] Enable openssl3 for xrootd (v626)

- roofit/hs3/src/RooJSONFactoryWSTool.cxx
Fixes a bug where snapshots were not imported from JSON.
> [RF] added missing snapshot creation

- roofit/hs3/src/RooJSONFactoryWSTool.cxx
This is a backport of all the RooFit PRs that were merged to `master` to `v6-26-00-patches` (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/10293
> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 11

- tutorials/pyroot/pyroot006_tcontext_context_manager.py
The TFile objects need to be closed before the ROOT files can be
deleted. Otherwise, we get errors such as these on Windows 10:
```
File "C:/build/night/LABEL/windows10/SPEC/default/V/master/root/tutorials/pyroot/pyroot006_tcontext_context_manager.py", line 56, in <module>
os.remove("pyroot006_file_{}.root".format(i))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pyroot006_file_1.root'
CMake Error at C:/build/night/LABEL/windows10/SPEC/default/V/master/build/RootTestDriver.cmake:227 (message):
error code: 1
```
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=windows10,SPEC=default,V=master/lastBuild/testReport/projectroot/runtutorials/tutorial_ …
> Close files before deleting them in TContext tutorial

- tutorials/tmva/TMVA_Higgs_Classification.C
On Windows, the `TMVA_Higgs_Classification.C` tutorial gives the
following error:
```
Processing C:/build/night/LABEL/windows10/SPEC/default/V/master/root/tutorials/tmva/TMVA_Higgs_Classification.C...
In file included from input_line_10:1:
C:\build\night\LABEL\windows10\SPEC\default\V\master\root\tutorials\tmva\TMVA_Higgs_Classification.C:322:27: error: no member named 'Python_Executable' in namespace 'TMVA'
gSystem->Exec(TMVA::Python_Executable() + " make_higgs_model.py");
~~~~~~^
CMake Error at C:/build/night/LABEL/windows10/SPEC/default/V/master/build/RootTestDriver.cmake:227 (message):
error code: 1
```
Using the same trick to get the Python executable name via
`gROOT->ProcessLine` that is also used in the other TMVA tutorials like
`TMVA_CNN_Classification.C` should fix the problem. …
> Fix `TMVA_Higgs_Classification.C` tutorial on Windows

- core/foundation/src/TClassEdit.cxx
This should fix issue #10353.
Use a spin lock to protect gInlined.
Also, use in-place lamba calls instead of checking at each call if the static was initialized.
In addition to the (slight) performance gain, this make those intialization thread safe.
> TClassEdit: make usage of static cache container thread safe.

- core/cont/inc/ROOT/TSeq.hxx
- tree/treeplayer/inc/TTreeReader.h
`std::iterator` is deprecated with C++17, hence alternative is applied.
> Avoid using deprecated `std::iterator` in TSeq and TTreeReader classes

- core/base/inc/Byteswap.h
This pull request improves the definition of the `Rbswap_{16,32,64}()` macros in `Byteswap.h` (see changes below).
- Define `R__bswap_64(x)` even if the compiler has no intrinsic for it. In that case, provide a fallback (unoptimized) implementation.
- In MSVC, implement `R__bswap_{16,32,64}(x)` in terms of the compiler intrinsic `_byteswap_xxx()`.
Follow-up PR: RNTuple read/write support in big-endian machines.
> [core] Improve implementation of `Rbswap_{16,32,64}()`

- io/io/src/TFile.cxx
A backport of #10318 . cc: @bendavid
> bypass UUID registration when using READ_WITHOUT_GLOBALREGISTRATION (v6.26)

- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/inc/RooAbsDataStore.h
- roofit/roofitcore/inc/RooCompositeDataStore.h
- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/inc/RooDataSet.h
- roofit/roofitcore/inc/RooTreeDataStore.h
- roofit/roofitcore/inc/RooVectorDataStore.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooCompositeDataStore.cxx
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooTreeDataStore.cxx
- roofit/roofitcore/src/RooVectorDataStore.cxx
- roofit/roofitcore/test/testRooDataSet.cxx
In the current implementation of `RooDataSet::reduceEng`, the dataset
itself was queried to get the weight variable used in the reduced
dataset. This didn't work with the `RooCompositeDataStore`, because a
dataset with this data store doesn't have a weight variable, as these
are encapsulated in the components of the composite store. Hence,
reducing a weighted dataset with a RooCompositeDataStore yields an
unweighted dataset, which is a bug.
To fix this problem, this commit implements a separate reduction logic
for the RooCompositeDataStore: the components are now reduced
individually, instead of naively creating a RooCompositeDataStore from a
RooVectorDataStore/RooTreeDataStore. To avoid further code branches in
RooDataSet, a new virtual function `RooAbsDataStore::reduce` is
introduced. …
> [RF] Correctly implement data reduction also for RooCompositeDataStore

- build/unix/makepchinput.py
- cmake/modules/RootBuildOptions.cmake
- tree/dataframe/test/dataframe_cache.cxx
- tree/dataframe/test/datasource_arrow.cxx
- tree/dataframe/test/datasource_csv.cxx
- tree/dataframe/test/datasource_root.cxx
- tree/dataframe/test/datasource_trivial.cxx
- tutorials/CMakeLists.txt
With the improvements in dataframe with better distinction between long, long long and pointers it works OK on ix86 when compiled with gcc 12.
```
Start   54: pyunittests-pyroot-pyz-rdataframe-asnumpy
Start   55: pyunittests-pyroot-pyz-rdataframe-makenumpy
134/1231 Test   #55: pyunittests-pyroot-pyz-rdataframe-makenumpy .........................   Passed   10.99 sec
151/1231 Test   #54: pyunittests-pyroot-pyz-rdataframe-asnumpy ...........................   Passed   23.56 sec
Start  363: gtest-tree-dataframe-test-dataframe-friends
Start  364: gtest-tree-dataframe-test-dataframe-colnames
Start  365: gtest-tree-dataframe-test-dataframe-cache
388/1231 Test  #364: gtest-tree-dataframe-test-dataframe-colnames ........................   Passed    4.40 sec
Start  366: …
```
> Restore 32-bit dataframe

- roofit/roofitcore/inc/LinkDef.h
- tmva/pymva/inc/LinkDef.h
- tmva/sofie/inc/LinkDef.h
See the commit messages for details.
> Add/remove namespaces from Linkdef

- tree/treeplayer/src/TTreeReaderArray.cxx
- tree/treeplayer/test/array.cxx
This fixes [ROOT-8827](https://sft.its.cern.ch/jira/browse/ROOT-8827).
@pcanal I'm not sure whether `Long_t` and `Long64_t` should also be in the picture, let me know.
> [TTreeReader] Add support for Short_t, UShort_t array sizes 

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/src/RooAbsData.cxx
The `RooAbsData::createHistogram` has two overloads, one taking RooFit
command arguments and one taking integers for bin numbers (the version
with command arguments is much more common in RooFit code).
They behave inconsistently when using default parameters, e.g. these two
calls result in different binnings:
```C++
// 1. overload with int bin numbers:
data->createHistogram(obs->GetName());
// 2. overload with command arguments:
data->createHistogram(data->GetName(), dataObs);
```
The function with integer bin numbers defaults to computing a binning
automatically from the distribution in the dataset. The function with
command arguments defaults to the binning stored in the variable, which
is much more suitable for RooFit.
To avoid confusion in the future, this commit marks the overload …
> [RF] Deprecate `RooAbsData::createHistogram` overload with `int` params

- config/thisroot.sh
Support for dash was added recently to thisroot.sh, but this has led to a problem when calling thisroot.sh from an executed script. The regression is fixed now by defaulting to the previous behaviour if the shell-name is not found.
This PR fixes [#](https://github.com/root-project/root/issues/10417)
> [config] Fix thisroot.sh when run from an executable script

- core/clingutils/res/TClingUtils.h
- core/clingutils/src/TClingUtils.cxx
Strip of ../ so that the search finds a valid longest match. With the upcoming upgrade of LLVM 13, this would otherwise lead to an error "File name too long" but it's already wrong now.
> TClingUtils: Avoid growing paths in GetFileName

- core/base/src/TROOT.cxx
The corresponding declaration in the header has already been removed
in 6.24, so this function cannot be called outside of this
source file.
See also #10413 .
> Remove "private" implementation of function deprecated in v6.24

- hist/histpainter/src/TGraphPainter.cxx
- hist/histpainter/src/THistPainter.cxx
- tutorials/graphs/graphpalettecolor.C
- tutorials/graphs/multigraphpalettecolor.C
Remove the ellipsis character in documentation.
It created problems during doxygen  build.
> [skip-ci] Remove ellipsis

- core/imt/inc/ROOT/TThreadExecutor.hxx
Fixed the types of the partial results after applying the function.
Otherwise, there is a problem if `retType` is different than the input type `T`.
> [core] Fix interaction of Maps of TThreadExecutor and std::vectors

- tutorials/image/hsumanim.C
On some machines the gif library is not available.
The animated gif production is disabled by default.
The tutorial header explains how to activate it.
> [skip-ci] Disable animated gif production by default.

- documentation/doxygen/Makefile
python3  is now used to build the reference because some tutorials like `distrdf001_spark_connection.py` require python3.
> [skip-ci] Some tutorials need python3

- tree/ntuple/v7/src/libdaos_mock/libdaos_mock.cxx
- Generalizes the fetch/update calls in the mocked-up version of DAOS to support multiple I/O descriptors per request. 
- This change will support planned improvements on the mapping between RNTuple and DAOS to leverage its backend parallelization. 
- Passes previously-existing v7 unit tests (which send a single IOD per request)
> [daos] Generalize daos_mock's fetch/update to accept multiple I/O descriptors

- tree/ntuple/v7/inc/ROOT/RField.hxx
The `resize` called a few lines above initializes elements as
necessary. We don't need to call GenerateValue on those memory
locations (which performs another placement new on them), rather
a CaptureValue is enough.
> [ntuple] Capture, do not generate value in RVecField::ReadGlobalImpl

- core/imt/inc/ROOT/TThreadExecutor.hxx
- core/imt/test/testRTaskArena.cxx
The last chunk of partial results of MapReduce with std::vectors had the
size of all other chunks. This is dangerous, since the default vector
values might cause unexpected results of the Reduce function.
Test added to verify the correctness.
> [core] Fix TThreadExecutor's MapReduce on std::vectors with chunks

- interpreter/cling/lib/MetaProcessor/Display.cpp
If you type ".typedef" in the ROOT prompt, it prints with weird format
> [cling] add missing newline and separating space

- graf2d/gpadv7/src/RColor.cxx
Most commonly seen on ppc64le. Backtrace:
```
===========================================================
The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#11 ROOT::Experimental::RColor::toHex[abi:cxx11](unsigned char) (v=<optimized out>) at /usr/include/c++/11/ext/new_allocator.h:82
#12 0x00007fff90c220ec in ROOT::Experimental::RColor::SetRGB (this=0x7fffeadf5d10, r=<optimized out>, g=<optimized out>, b=<optimized out>) at …
```
> Avoid crashes due to static initialization order

- core/base/src/root-argparse.py
specify that multiple ROOT files can be opened from CLI args
and point to manual for compilation flags
> specify that multiple ROOT files can be opened

- tutorials/geom/webdemo.C
- tutorials/graphs/zdemo.C
- tutorials/math/Rolke.C
- tutorials/math/exampleFunction.py
- tutorials/math/principal.py
- tutorials/rcanvas/raxis.cxx
- tutorials/roofit/rf710_roopoly.py
- tutorials/roofit/rf711_lagrangianmorph.py
- tutorials/roofit/rf712_lagrangianmorphfit.py
- tutorials/roostats/MultivariateGaussianTest.C
- tutorials/roostats/OneSidedFrequentistUpperLimitWithBands.C
- tutorials/roostats/Zbi_Zgamma.C
Uniformize the `\authors` directive in tutorials.
> [skip-ci] Uniformize \authors

- core/imt/inc/ROOT/TThreadExecutor.hxx
- core/imt/test/testRTaskArena.cxx
* Modified the logic of MapReduce and Map of the TThreadExecutor which were
initially broken for the TThreadExecutor;
* Added corresponding tests.
Fix https://github.com/root-project/root/issues/10404
> [core] Fix interaction of TThreadExecutor and TSeq with specified beginning/range

- cmake/modules/RootMacros.cmake
Prevent the parallel builds of tests from roottest to trigger rebuilding of rootcling_stage1.exe on Windows
> Fix parallel build of tests from roottest on Windows

- tutorials/roofit/rf102_dataimport.py
- tutorials/roofit/rf105_funcbinding.py
- tutorials/roofit/rf109_chi2residpull.py
- tutorials/roofit/rf208_convolution.py
- tutorials/roofit/rf210_angularconv.py
- tutorials/roofit/rf211_paramconv.py
- tutorials/roofit/rf303_conditional.py
- tutorials/roofit/rf401_importttreethx.py
- tutorials/roofit/rf403_weightedevts.py
- tutorials/roofit/rf503_wspaceread.py
- tutorials/roofit/rf508_listsetmanip.py
- tutorials/roofit/rf510_wsnamedsets.py
- tutorials/roofit/rf512_wsfactory_oper.py
- tutorials/roofit/rf601_intminuit.py
- tutorials/roofit/rf602_chi2fit.py
- tutorials/roofit/rf605_profilell.py
- tutorials/roofit/rf606_nllerrorhandling.py
- tutorials/roofit/rf705_linearmorph.py
- tutorials/v7/browser.cxx
- tutorials/v7/fitpanel6.cxx
Some tutorials had two `\author` lines. This generates the doxygen error:
```
\endcond command within this file
```
These double lines are replaced by the `\authors` single line.
> [skip-ci] Fix the double "author"

- tutorials/hist/ZoomHistogram.C
This was seen by the jupyter notebook which give the error:
```
input_line_42:2:2: warning: 'norm' shadows a declaration with the same name in the 'std' namespace; use '::norm' to reference this declaration
TH1F *norm = new TH1F("Normal Histogram", "Normal Histogram", 100, 0, 100);
^
```
> [skip] norm shadows a declaration in the 'std' namespace

- math/doc/index.md
`\page` was used instead of `\ref`
> [skip-ci] Fix wrong ref in math page

- math/minuit2/inc/Minuit2/FunctionMinimum.h
- math/minuit2/inc/Minuit2/MinimumError.h
- math/minuit2/inc/Minuit2/MnUserParameterState.h
- math/minuit2/src/MnHesse.cxx
- math/minuit2/src/MnUserParameterState.cxx
- math/minuit2/src/VariableMetricBuilder.cxx
This finally fixes https://github.com/scikit-hep/iminuit/issues/637
The following changes are implemented:
1) Store information that MnHesse reached call limit in MinimumError
- Add new states MnUnset, MnPosDef, and MnReachedCallLimit to MinimumError::Status
- Switch MinimumError status storage from bools to enum, since there is actually only one unique state at a time and toggling the bools correctly is error-prone; it also simplifies the implementation
2) Propagate information from MinimumError to FunctionMinimum via Add
I slightly simplified the implementation of VariableMetricBuilder, the variable `hessianComputed` was not needed, the information whether Hesse was run can be obtained from the MinimumState object.
Other changes (which could be broken into a separate PR):
- Removed …
> Fix hesse call limit

- tree/treeplayer/inc/TBranchProxy.h
Prevent access violation when executing the df017_vecOpsHEP.C tutorial with ROOT built in release mode. To be reviewed when updating Visual Studio or LLVM
> Fix access violation with df017_vecOpsHEP.C on Windows

- core/meta/src/TViewPubDataMembers.h
`std::iterator<...>` was deprecated in C++17; manually declare the expected member types instead.
This PR fixes #10351.
> [core] TViewPubDataMembersIter: avoid using deprecated `std::iterator`

- roofit/roofit/test/CMakeLists.txt
- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/res/RooFit/BatchModeHelpers.h
- roofit/roofitcore/res/RooNLLVarNew.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooFitDriver.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testRooFitDriver.cxx
- roofit/roofitcore/test/testSumW2Error.cxx
The extended term needs a special correction, it should not just be
reevaluated with the squared weights replacing the weights. This is not
implemented correctly.
The way how weights are handled in the batch mode was also simplified.
Previously, a dummy `RooRealVar` was created for the weight and the
squared weight each, but now the conventional name for the weight
variable is used directly to look up the names in the data map.
In the second commit, a unit test is added for this, inspired by the following forum post:
https://root-forum.cern.ch/t/batchmode-gives-wrong-errors-with-sumw2errors/49597/8
> [RF] Fix SumW2Error with extended term BatchMode

- tutorials/fit/fit1.C
- tutorials/histfactory/example.py
- tutorials/pyroot/fit1.py
- tutorials/pyroot/h1ReadAndDraw.py
- tutorials/tmva/tmva102_Testing.py
Using TFile::Open produces an Error message catch by the jenkins rules declaring the doc failure. These changes test the file existence before using them. A warning (not an Error) is printed if not.
> Test the files existence before using them

- tree/dataframe/src/RCsvDS.cxx
With these changes, reading in a CSV of 32M lines takes 43 seconds on my laptop instead of 1m48s.
> [DF] Avoid expensive stringstream construction in RCsvDS

- roofit/roofitcore/CMakeLists.txt
- roofit/roofitcore/res/RooFit/BatchModeDataHelpers.h
- roofit/roofitcore/res/RooFit/BatchModeHelpers.h
- roofit/roofitcore/res/RooFit/CUDAHelpers.h
- roofit/roofitcore/res/RooFitDriver.h
- roofit/roofitcore/src/BatchModeDataHelpers.cxx
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/CUDAHelpers.cxx
- roofit/roofitcore/src/RooFitDriver.cxx
The `RooFitDriver.cxx` source file was growing a lot recently, and many
functional parts were mixed together. For example, the loading of spans
from the dataset and the analysis of the computation graph are two
separate things but they were mixed in this file.
This commit suggests to improve the situation by moving all data related
functionality to a new file `BatchModeDataHelpers.cxx`. Some CUDA
helpers are also moved to `CUDAHelpers.cxx`. Another helper function was
moded to `BatchModeHelpers.cxx` to keep the footprint of
`RooFitDriver.cxx` small such that new contributors can get started more
easily.
> [RF] Refactor RooFitDriver and move some functionality to other files

- roofit/roofitcore/inc/RooFitResult.h
- roofit/roofitcore/src/RooFitResult.cxx
- roofit/roofitcore/test/testRooAbsPdf.cxx
The `RooFitResult::isIdentical` method so far only compared parameter
values and covariance matrix values. Even though comparing the final
parameter errors would be redundant with the covariance matrix checks,
it's still important to check parameter errors for two reasons:
1. Initial parameter errors need to be compared, because the the
initial error determins the initial step size which influences the
minimization path. If initial errors are different, the final
parameter values are almost never identical.
Catching differences in initial parameter errors informs the user
that differences in fit result are because of the starting
conditions.
2. In the case of `RooFitResult::isIdenticalNoCov`, we need to check
the error of final parameters because there is no comparison of
covariance …
> [RF] Also compare parameter errors in RooFitResult::isIdentical(NoCov)

- hist/histpainter/src/THistPainter.cxx
The following example produced a weird plot:
```
{
TH2D *blah = new TH2D("","",11,0.079,0.101,8,-0.0075,0.0005);
for (int i=1; i<=blah->GetNbinsX();i++) {
for (int j=1; j<=blah->GetNbinsY();j++) blah->SetBinContent(i, j, i*j);
}
blah->Draw("ARR");
}
```
This was because the bin center was shifted by an arbitrary value of 0.03. When the axis dynamic was large compared to 0.03 this was not visible. In the above example, it is not the case and therefore the plot was wrong. Removing that arbitrary shift gives the right plot.
This arbitrary shift comes from the 22 years old FORTRAN version of the code.
> PaintArrow shifted the bin center by an arbitrary value (0.03)

- math/mathcore/inc/Fit/Fitter.h
- math/mathcore/inc/Math/BasicMinimizer.h
- math/mathcore/inc/Math/MinimTransformFunction.h
- math/mathcore/src/BasicMinimizer.cxx
- math/mathcore/src/Fitter.cxx
- math/mathmore/inc/Math/GSLNLSMinimizer.h
- math/mathmore/inc/Math/MultiNumGradFunction.h
- math/mathmore/src/GSLMinimizer.cxx
- math/mathmore/src/GSLNLSMinimizer.cxx
- math/mathmore/src/GSLSimAnMinimizer.cxx
This Pull request fixes a memory leak reported in https://root-forum.cern.ch/t/gslmultifit-memory-leak-with-root-fitter/49566 when using GSLMultiFit. 
In addition for fixing for the leak the handling of the internal transformation function is improved and an extra un-needed clone of the objective function in the Fitter class is avoided.
> [Math] Fix memory leak when using GSLMultiFit and improve Fitter class

- core/meta/src/TViewPubDataMembers.h
`std::iterator<...>` was deprecated in C++17; manually declare the expected member types instead.
This PR fixes #10351.
This PR is a backport of https://github.com/root-project/root/pull/10457 to v6-26-00-patches.
> [core,v6-26] TViewPubDataMembersIter: avoid using deprecated `std::iterator`

- core/meta/src/TClass.cxx
- io/io/src/TGenCollectionProxy.cxx
Previously it was reused it just 'happened' to have the expected size. (This applies only for the treatment of the TClass for an std::pair) and help fix the tests on 32 bits platforms.
See test: https://github.com/root-project/roottest/pull/869
backport of https://github.com/root-project/root/pull/10416
> v624 stdpair: Don't reuse of emulated StreamerInfo (when having compiled info)

- core/meta/src/TClass.cxx
- io/io/src/TGenCollectionProxy.cxx
Previously it was reused it just 'happened' to have the expected size. (This applies only for the treatment of the TClass for an std::pair) and help fix the tests on 32 bits platforms.
See test: https://github.com/root-project/roottest/pull/869
backport of https://github.com/root-project/root/pull/10416
> v626 stdpair: Don't reuse of emulated StreamerInfo (when having compiled info)

- tutorials/xml/DOMParsePerson.C
- tutorials/xml/DOMRecursive.C
- tutorials/xml/xmlnewfile.C
More XML tutorials generate errors when converted into notebooks.
> [skip-ci] Xml tutorials generate errors

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
Fix #10041 - Teach `GraphAsymmErrors` to accept systematic variations.
This is tested against the test [here](https://github.com/eguiraud/root/blob/e5dd150ac29bb2d6439c2138891cd65fab61a2f5/tree/dataframe/test/dataframe_vary.cxx#L941) (yet to be pushed to master).
> [DF] Teach `GraphAsymmErrors` to accept systematic variations

- roofit/roofitcore/inc/RooAbsCollection.h
- roofit/roofitcore/src/RooAbsCollection.cxx
Add member function to RooAbsCollection to sort topologically: the
servers of any RooAbsArg will be before that RooAbsArg in the
collection. Will throw an exception if servers are missing in the
collection.
This function is useful for computation graph analysis like in the
RooFitDriver.
In a second commit in this PR, some general code modernization to RooAbsCollection.cxx is done such that the total number of lines doesn't increase with the newly-added member function.
> [RF] Add `RooAbsCollection::sortTopologically()` member function

- core/metacling/src/CMakeLists.txt
Export a couple of missing symbols on Windows 32 and 64 bit
> Fix issue #10452 Cling symbols not exported in win32 and win64

- roofit/roofitcore/inc/RooTreeDataStore.h
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooTreeDataStore.cxx
In RooDataSet, there are constructors to create a dataset as a subset of
another RooDataSet or a TTree, passing either a cut string or a
RooFormulaVar as the cut variable.
There were two implementations for the cut string and the RooFormulaVar
case, but it's better to implement one in terms of the other to avoid
code duplication and divergence.
The RooFormulaVar version has to be implemented in terms of the cut
string version, because the cut string version is more general: it can
also take an empty string, signifying no cut.
Removing functions from the public interface of the data store classes is
okay, because as implementation details of the RooFit dataset classes
they are not supposed to be public anyway.
> [RF] Less code duplication in RooDataSet subset constructors

- documentation/doxygen/Doxyfile
Some files in the webgui tutorials should not be scanned by doxygen. They produce errors.
> [skip-ci] Some files in the webgui tutorials should not be scanned by doxygen.

- interpreter/cling/include/cling/std.modulemap
This resolves a merging bug with libstdc++12. Fixes root-project/root#10478
> [cxxmodules] Reduce the amount of header duplications in the modules.

- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/CustomStructLinkDef.h
- tree/ntuple/v7/test/ntuple_types.cxx
Add a unit test that checks RNTuple serialization/deserialization of classes using empty base optimization.
This PR fixes #10323.
> [ntuple] Add test for classes using empty base optimization

- cmake/modules/RootConfiguration.cmake
- config/RConfigure.in
- config/__cplusplus.cxx
Building external applications that use ROOT oftentimes fail if there is a mismatch in the C++ standard between ROOT and the application.
To make this visible, diagnose if there is a mismatch in the value of the `__cplusplus` macro w.r.t. when ROOT was configured.
The check is performed in `RConfigure.h`, a common header also included in backports, e.g. RStringView.hxx.
- Generated `RConfigure.h` during build defines `ROOT__cplusplus`, which contains the value of the  `__cplusplus` macro at the time ROOT was configured.
- Because `RConfigure.h` is included from many ROOT headers (e.g., backports), it seems a viable candidate to also add the mismatch check.
On mismatch, emit a warning (should it be an `#error` instead?).
This PR fixes #8063.
> [cmake,config] Warn if the C++ standard does not match ROOT's

- roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h
- roofit/histfactory/src/ParamHistFunc.cxx
- roofit/histfactory/src/RooBarlowBeestonLL.cxx
Also make isBinnedDistribution depend on the vars rather than always return true.
Makes ParamHistFunc more flexible/powerful
> Allow any RooAbsReal instead of just RooRealVar for params. 

- roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
- roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
In HistFactory, normalization uncertainties and shape uncertainties were
treated differently when setting the constraint type to uniform, e.g.:
```xml
<ConstraintTerm Type="Uniform" RelativeUncertainty="1">NP_shape</ConstraintTerm>
<ConstraintTerm Type="Uniform" RelativeUncertainty="1">NP_norm</ConstraintTerm>
```
See #9070 for a very good explanation of the problem.
For non-shape uncertainties, the uniform constraint was treated as a
special case of the Gaussian constraint with "infinite" sigma. For shape
uncertainties, the `Uniform` type was ignored.
This commit suggests to refactor the creation of Gaussian constraints
such that the logic that considers the "Uniform" tag is also used for
shape uncertainties.
Closes #9070.
> [RF] Consistent behavior for uniform constraint terms in HistFactory

- graf2d/gpadv7/src/RCanvas.cxx
- gui/browsable/inc/ROOT/Browsable/TObjectElement.hxx
- gui/browsable/src/TDirectoryElement.cxx
- gui/browsable/src/TObjectElement.cxx
Before only list of TKeys was shown in TBrowser,
now also objects are shown. Fixes #10389 
Do not try to remove histograms from gDirectory.
Small fix for RCanvas cleanup
> [rbrowser] let access in-memory objects from TDirectory

- interpreter/cling/include/cling/std.modulemap
The header `bits/utility.h` only exists since libstdc++-12.
> [cxxmodules] Fix std.modulemap for older GCC

- tree/treeplayer/inc/ROOT/TTreeReaderFast.hxx
`std::iterator` was deprecated in C++17; manually declare the member types.
> [DF] Avoid using deprecated `std::iterator` in `TTreeReaderFast`

- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/src/RooAddPdf.cxx
The `RooAbsPdf::_normSet` member should be not used, because it can
happen in many situations that the RooArgSet it points to gets out of
scope and then you get a crash. There were several cases reported on the
forum where this happened with a RooAddPdf recently, becaues with ROOT
6.26 some logic of the RooAddPdf got changed to better deal with empty
normalization sets.
This commit avoids using `_normSet` by overriding `getValV` in RooAddPdf
directly, instead of `evaluate()`. This way, it has access to the actual
normalization set that is passed to the call to `getVal()`.
For the batch mode, we now pass `nullptr` to
`RooAddPdf::getNormAndCache()` instead of `_normSet`. In this case it
falls back to using `_copyOfLastNormSet`, which is guaranteed to still
be valid because it's a unique_ptr …
> [RF] Avoid using `_normSet` member in RooAddPdf

- roofit/roofitcore/inc/LinkDef.h
In ROOT 6.28, some proxy classes were replaced:
`RooSetProxy` -> `RooCollectionProxy<RooArgSet>`
`RooListProxy` -> `RooCollectionProxy<RooListProxy>`
This breaks reading workspaces created with 6.28 by 6.26.
Even though we generally don't guarantee forward compatibility, the
problem can be fixed easily in this case by adding a class rule to treat
the new class names as aliases for the old ones.
> [RF] Add class rules for `RooCollectionProxy` for forward compatibility

- roofit/roofitcore/inc/LinkDef.h
This is a followup to abdf727ae05, removing a classrule that is unused
since that commit.
> [RF] Removing unused `RooMinimizerFcn` class rule

- interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_abs.C
Just pass the absolute path, do not prefix with `-l` which confuses `ld`.
> [cling] Fix test/DynamicLibraryManager/callable_lib_L_AB_abs.C

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
...because we'd only redefine the _nominal_ value, which would be extremely confusing.
A test for this case will soon be added as part of a general improvement to Vary's test coverage.
> [DF] Throw if a varied column is redefined

- interpreter/cling/lib/Interpreter/Exception.cpp
See https://github.com/root-project/root/issues/7541 for details.
Closes #7744
> [cling] Do not throw CompilationExceptions on Apple M1

- interpreter/cling/lib/Interpreter/Exception.cpp
See https://github.com/root-project/root/issues/7541 for details.
Closes #10548, backport of #10561
> [cling] Do not throw CompilationExceptions on Apple M1 [v6.26]

- interpreter/cling/lib/Interpreter/Exception.cpp
See https://github.com/root-project/root/issues/7541 for details.
Closes #10548, backport of #10561
> [cling] Do not throw CompilationExceptions on Apple M1 [v6.24]

- core/unix/src/TUnixSystem.cxx
- graf2d/asimage/src/TASImage.cxx
- graf2d/gpad/src/TPad.cxx
- gui/fitpanel/src/TFitEditor.cxx
- gui/gui/src/TGView.cxx
- proof/proof/src/TProof.cxx
some unused variables warnings in MacOs cocoa
I not sure how to fix this one:
```
Building CXX object graf2d/cocoa/CMakeFiles/GCocoa.dir/src/MenuLoader.mm.o
/Users/rdm/rootsrc/graf2d/cocoa/src/MenuLoader.mm:92:16: warning: variable 'menuItem' set but not used [-Wunused-but-set-variable]
NSMenuItem *menuItem = [aMenu addItemWithTitle : NSLocalizedString(@"Minimize", nil)
```
This PR fixes https://github.com/root-project/root/issues/10572
> remove unused variable warnings in macos cocoa

- math/matrix/src/TDecompLU.cxx
The logic in `TDecompLU` where a separate `bool` was tracking if a given
pointer should be "deleted" caused some compiler errors warnings like:
```
root/math/matrix/src/TDecompLU.cxx: In static member function ‘static Bool_t TDecompLU::InvertLU(TMatrixD&, Double_t, Double_t*)’:
root/math/matrix/src/TDecompLU.cxx:883:17: warning: ‘void operator delete [](void*)’ called on unallocated object ‘workd’ [-Wfree-nonheap-object]
883 |       delete [] pWorkd;
|                 ^~~~~~
root/src/root/math/matrix/src/TDecompLU.cxx:847:13: note: declared here
847 |    Double_t workd[kWorkMax];
```
> [math] Avoid warnings about deleting unallocated objects in `TDecompLU`

- graf2d/gpad/src/TPad.cxx
The current file name is painted on the bottom right of each plot if
the option `File` is set on via `gStyle->SetOptFile()`.
> Implement the option "File"

- core/base/v7/inc/ROOT/RIndexIter.hxx
- core/cont/inc/TBtree.h
- core/cont/inc/TList.h
- core/cont/inc/TMap.h
- core/cont/inc/TObjArray.h
- core/cont/inc/TOrdCollection.h
- core/cont/inc/TRefArray.h
- core/meta/src/TViewPubFunctions.h
Deprecated `std::iterator` since C++17 is substituted in:
* `TViewPubFunctionsIter`
* `TBtreeIter`
* `TListIter`
* `TMapIter`
* `TObjArrayIter`
* `TOrdCollectionIter`
* `TRefArrayIter`
* `RIndexIter`
> [core] Avoid deprecated `std::iterator`

- README/ReleaseNotes/v628/index.md
- roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
- roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
- roofit/histfactory/src/hist2workspace-argparse.py
- roofit/histfactory/src/hist2workspace.cxx
In a binned likelihood fit, it is possible to skip the PDF normalization
when the unnormalized binned PDF can be interpreted directly in terms of
event yields. This is now done by default for models HistFactory models,
which results in great speedups for binned fits with many channels. Some
RooFit users like ATLAS were already using this for a long time, so this
feature is battle-tested.
To disable this optimization when using the `hist2workspace` executable,
add the `-disable_binned_fit_optimization` command line argument.
Directly in C++, you can also set the `binnedFitOptimization` to `false`
in the HistFactory configuration as follows:
```C++
RooStats::HistFactory::MakeModelAndMeasurementFast(measurement, {.binnedFitOptimization=false});
```
If your compiler doesn't support aggregate …
> [RF] Introducing binned likelihood fit optimization in HistFactory

- tmva/sofie/inc/TMVA/SOFIE_common.hxx
```
In file included from /builddir/build/BUILD/root-6.26.00/tmva/sofie/inc/TMVA/RModel.hxx:14,
from /builddir/build/BUILD/root-6.26.00/tmva/sofie/src/RModel.cxx:3:
/builddir/build/BUILD/root-6.26.00/tmva/sofie/inc/TMVA/SOFIE_common.hxx: In member function 'void TMVA::Experimental::SOFIE::InitializedTensor::CastPersistentToShared()':
/builddir/build/BUILD/root-6.26.00/tmva/sofie/inc/TMVA/SOFIE_common.hxx:75:12: error: 'memcpy' is not a member of 'std'; did you mean 'wmemcpy'?
75 |       std::memcpy(tData.get(), fPersistentData,fSize * sizeof(float));
|            ^~~~~~
|            wmemcpy
gmake[2]: *** [tmva/sofie/CMakeFiles/ROOTTMVASofie.dir/build.make:79: tmva/sofie/CMakeFiles/ROOTTMVASofie.dir/src/RModel.cxx.o] Error 1
```
(cherry picked from commit …
> Add #include <cstring> for std::memcpy [v6.26]

- interpreter/cling/include/cling/std.modulemap
This resolves a merging bug with libstdc++12. Fixes root-project/root#10478
Backport includes the following commit:
[cxxmodules] Fix std.modulemap for older GCC (#10529)
The header bits/utility.h only exists since libstdc++-12.
(cherry picked from commits e88d533f1c79754dae892249818f53d0155e88fa
and 2750395660c5c8c3ae617a18fefd27193587ec79)
Backport of PRs https://github.com/root-project/root/pull/10498 and https://github.com/root-project/root/pull/10529
> [cxxmodules] Reduce the amount of header duplications in the modules. [v6.24]

- builtins/xrootd/CMakeLists.txt
- builtins/zeromq/cppzmq/CMakeLists.txt
hashes are not stable when downloading release sources from github, see
https://security.stackexchange.com/a/240209
https://github.com/root-project/root/issues/10503
> [cmake] Use lcgpackages@cern, rather than unstable github:

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The git diff looks "complicated" but I actually just swapped which
function corresponds to which docstring. This should effectively
be a non-functional change.
Fixes the wrong docs at https://root.cern.ch/doc/master/classROOT_1_1RDF_1_1RInterface.html#a18ce8fb41d50fe364abe921d07ab70c1
> [DF] Fix documentation of two Vary overloads

- roofit/roofitcore/inc/RooChi2Var.h
- roofit/roofitcore/src/RooChi2Var.cxx
- test/stressRooFit_tests.h
In the RooChi2Var, there was another case of inconsistency between
constructors that seemingly do the same but actually don't.
A RooChi2Var should be created with the constructors that take RooFit
command arguments. However, there were also other constructors used by
the RooFit test statistic implementation details (i.e. in
`RooAbsOptTestStatistic::create`) that when used with default aruments
behave inconsistently with the command arg constructors: the default
error type is different, and errors will be estimated from the pdf and
not from the data.
This lead to the confusing situation that when creates a `RooChi2Var`
without any command arguments, the default error mode is suddenly
different. This inconsistency should be removed by having only the
command argument constructors part of …
> [RF] Make non-command arg constructors of `RooChi2Var` private

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
- roofit/roofitcore/src/RooChi2Var.cxx
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooXYChi2Var.cxx
- roofit/roofitcore/src/TestStatistics/RooAbsL.cxx
- roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx
- roofit/roofitcore/test/testRooDataHist.cxx
This commit removes some functions from the RooFit data classes:
* `RooAbsData::valid()` (virtual method that was overridden in
RooDataHist but not RooDataSet)
* `RooDataHist::valid(std::size_t i)` and `RooDataHist::valid()`
* `RooDataHist::cacheValidEntries()`
The `cacheValidEntries` method was originally intended to be used in
`RooAbsOptTestStatistic` to mask histogram entries out of the variable
range in case of a subrange fit. The reasons why `cacheValidEntries` and
the related `valid()` methods should be removed are:
1. It is redundant. In a subrange fit, the `RooAbsOptTestStatistic` is
creating a clone of the dataset with the subrange only using
`RooAbsData::reduce()`. So all entries are valid by definition.
2. RooDataHist and RooDataSet have inconistent implementations. For
the …
> [RF] Remove entry masking feature from RooDataHist

- geom/geom/inc/TGeoVolume.h
- geom/geom/src/TGeoManager.cxx
- geom/geom/src/TGeoVolume.cxx
- Returns the newly added node from call to TGeoVolume::AddNode
- Allows an option to avoid voxelation
Profiling geometry building in CMSSW turned up two issues
1. Doing a linear lookup for newly added nodes to a TGeoVolume was very slow2. 
2. CMS uses DD4Hep (which uses ROOT) as a geometry description system not as a geometry navigation system. The building of the voxels was slow and is never used in CMSSW. 
This change was temporarily incorporated into CMS' development branch and did not cause any noticeable problems and did give a speed boost.
> Minor Geometry optimization

- roofit/histfactory/inc/RooStats/HistFactory/Channel.h
- roofit/histfactory/inc/RooStats/HistFactory/Data.h
- roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
- roofit/histfactory/inc/RooStats/HistFactory/Sample.h
- roofit/histfactory/src/Channel.cxx
- roofit/histfactory/src/Data.cxx
- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/histfactory/src/Sample.cxx
In HistFactory, the presence of a `Channel::GetAdditionalDatas` function
hinted to the possibility of defining additional datases for a
HistFactory model, besides the nominal observations dataset named
`"obsData"`.
When reading a user-generated HistFactory XML, the additional datasets
were in fact read into the `Channel::fAdditionalData` member, and
corresponding RooDataSets were created in the per-channel proto
workspaces.
However, when defining the Measurement object in C++ and dumping the XML
via `PrintXML`, the additional datasets were not considered. They were
also not considered when merging the datasets in the per-channel proto
workspaces into the simultaneous dataset. This commit suggests to
implement this correctly.
Now, one can define additional datasets as follows in the XML: …
> [RF] Correctly implement additional dataset feature in HistFactory

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/test/dataframe_vary.cxx
With this solution `TStatistic` never resets its result that is being varied.
Fix https://github.com/root-project/root/issues/10545.
> [DF] Teach `Vary` to accept `Stats`

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Before this patch, in order to assert that the column type
returned by a Vary expression matched the type of the column we
always asked cling to provide a type id for the existing column
via TypeName2TypeID(GetColumnType(colName)). That failed if the
column had a type not known to the interpreter, e.g. because it
was Define'd and the expression returned a user-defined type.
With this patch we use the typeid information coming from the
RDefine node if it is available, otherwise we try with cling.
A corresponding test is coming soon in another PR.
> [DF] Do not ask cling a typeid if it does not know the type

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/histfactory/src/RooBarlowBeestonLL.cxx
- roofit/roofit/src/RooChi2MCSModule.cxx
- roofit/roofitcore/test/testRooFitDriver.cxx
- roofit/roostats/inc/RooStats/MaxLikelihoodEstimateTestStat.h
- roofit/roostats/inc/RooStats/MinNLLTestStat.h
- roofit/roostats/inc/RooStats/ProfileLikelihoodTestStat.h
- roofit/roostats/inc/RooStats/RatioOfProfiledLikelihoodsTestStat.h
- roofit/roostats/inc/RooStats/SimpleLikelihoodRatioTestStat.h
- roofit/roostats/src/AsymptoticCalculator.cxx
- roofit/roostats/src/BernsteinCorrection.cxx
- roofit/roostats/src/HybridResult.cxx
- roofit/roostats/src/LikelihoodInterval.cxx
- roofit/roostats/src/MetropolisHastings.cxx
- roofit/roostats/src/ProfileLikelihoodCalculator.cxx
- roofit/roostats/src/ProfileLikelihoodTestStat.cxx
- roofit/roostats/src/UpperLimitMCSModule.cxx
- test/fit/testFitPerf.cxx
- test/stressRooFit_tests.h
- tutorials/roofit/rf403_weightedevts.C
- tutorials/roofit/rf403_weightedevts.py
- tutorials/roofit/rf602_chi2fit.C
- tutorials/roofit/rf602_chi2fit.py
- tutorials/roofit/rf606_nllerrorhandling.C
- tutorials/roofit/rf606_nllerrorhandling.py
- tutorials/roofit/rf609_xychi2fit.C
- tutorials/roofit/rf705_linearmorph.C
- tutorials/roofit/rf705_linearmorph.py
- tutorials/roostats/rs401d_FeldmanCousins.C
- tutorials/roostats/rs_bernsteinCorrection.C
The direct creation of RooFit test statistics instances is discouraged
because the more configurable `createNLL` and `createChi2` should be
prefered.
> [RF] Avoid using test statistics constructors directly in user code

- interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
The error occurs only when `loadLibrary()` is called with the argument `resolved = false`.
The const reference of lResolved in the statement `const std::string& canonicalLoadedLib = resolved ? libStem.str() : lResolved;` is a copy because the compiler insert the copy constructor and creates a temporary object. This is required, that the return type of libStem.str() and  lResolved has the same value
type: prvalue.
Related cling PR: https://github.com/root-project/cling/pull/455
> DynamicLibraryManager::loadLibrary if the parameter resolve is false

- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/src/RFieldVisitor.cxx
- tree/ntuple/v7/test/ntuple_show.cxx
- tree/ntuple/v7/test/rfield_vector.cxx
This PR:
- adds the RRVecField type for type-erased I/O of RVecs with RNTuple
- removes some special-casing of `RVec<bool>` which is unnecessary now that we have RVec 2.0
- adds RPrintValueVisitor support for RVecs
- adds tests for type-erased I/O of RVecs
- adds tests for `ntuple->Show` + RVecs
- adds tests for interop I/O of std::vectors and RVecs (i.e. writing one and reading the other)
This PR fixes #6347 .
> [ntuple] Add RRVecField for type-erased I/O of RVecs

- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RRange.hxx
- tree/dataframe/test/dataframe_vary.cxx
When previous node of a RRange or RFilter node was a RJittedFilter,
we were wrongly downcasting _varied_ filters to the RJittedFilter type,
but varied filters are _not_ jitted filters, they are copies of the
actual concrete filter.
With this patch, if the type of the previous node is RJittedFilter,
we treat it everywhere as the generic base class RFilterBase, which
fixes the problem and it is consistent with what we already do in
RVariedAction.
The PR comes with the corresponding regression test.
> [DF] Fix wrong downcast in {RRange,RFilter}::GetVariedFilter 

- bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
- bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
- bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py
- bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
- bindings/experimental/distrdf/python/DistRDF/DataFrame.py
- bindings/experimental/distrdf/python/DistRDF/HeadNode.py
- bindings/experimental/distrdf/python/DistRDF/Proxy.py
- bindings/experimental/distrdf/python/DistRDF/Ranges.py
- bindings/experimental/distrdf/test/backend/test_dist.py
- bindings/experimental/distrdf/test/test_callable_generator.py
- bindings/experimental/distrdf/test/test_friendinfo.py
- bindings/experimental/distrdf/test/test_headnode.py
- bindings/experimental/distrdf/test/test_node.py
- bindings/experimental/distrdf/test/test_proxy.py
- bindings/experimental/distrdf/test/test_ranges.py
This class is not really needed, we can use free functions instead. This removes an implicit inter-dependency between the head node and the backend. Now it's only the head node that stores a reference to the backend needed to execute the graph, similarly to RLoopManager
> Refactor dependency between head node and its backend

- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/src/RField.cxx
This pull request applies some changes (see below) in the implementation of RRecordField in order to support `std::pair` and `std::tuple` fields (as follow-up PRs).
- Compute once the offset for each member in the `RRecordField` constructor and reuse this information in other member functions.
- Provide a constructor that takes the list of member offsets and corresponding C++ type.  This is required for the implementation of `std::pair` and `std::tuple` fields.  Make the private members protected.
- Given that `RRecordField` takes the ownership of the child fields passed in the `std::vector<std::unique_ptr<Detail::RFieldBase>> &itemFields`, provide also a constructor that takes a rvalue reference.
Follow-up PRs: support for `std::pair`; support for `std::tuple` fields.
> [ntuple] Requirements in `RRecordField` for supporting `std::pair` and `std::tuple` fields

- geom/geom/inc/TGeoVolume.h
- geom/geom/src/TGeoManager.cxx
- geom/geom/src/TGeoVolume.cxx
- Returns the newly added node from call to TGeoVolume::AddNode
- Allows an option to avoid voxelation
back port of #10576
Profiling geometry building in CMSSW turned up two issues
1. Doing a linear lookup for newly added nodes to a TGeoVolume was very slow2.
2. CMS uses DD4Hep (which uses ROOT) as a geometry description system not as a geometry navigation system. The building of the voxels was slow and is never used in CMSSW.
This change was temporarily incorporated into CMS' development branch and did not cause any noticeable problems and did give a speed boost.
> Minor Geometry optimization [v6-26]

- math/unuran/CMakeLists.txt
The warning was observed on fedora32 with gcc 10.3.1
Warning:
root/src/methods/mvtdr_init.ch:886:17: warning: argument 1 value ‘18446744073709551608’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
886 |   GEN->etable = malloc( size * sizeof(E_TABLE*) );
It can  be fixed by casting to an int the input to malloc or checking if it is not larger than 2^63-1
This warning could be probably disabled in the code by casting from size_t to int the input to malloc
> [math] Backport of Disable a warning compiling Unuran code.

- roofit/roofitcore/src/NormalizationHelpers.cxx
Can be seen when compiled with `-Ddev=ON` option
> Add missing TClass.h include in NormalizationHelpers.cxx [6.26]

- roofit/roofitcore/src/NormalizationHelpers.cxx
Need when compiled with `-Ddev=ON` option
> Add missing TClass.h include in NormalizationHelpers.cxx

- tmva/sofie/src/RModel.cxx
This is a backport in 6,.26. This fixes  #10586
> [TMVA][SOFIE] Backport: Add header guards to the include file generated by SOFIE

- interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp
This reverts https://github.com/vgvassilev/clang/commit/a5ee33ae48
This patch previous tried to solve some problems with virtual files, but
when trying to upstream it, it brokes the tests below:
* Modules/module-file-modified.c
* Modules/explicit-build-missing-files.cpp
> Complain about invalid sources again

- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RRange.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/inc/ROOT/RDFHelpers.hxx
- tree/dataframe/src/RActionBase.cxx
- tree/dataframe/src/RDefineBase.cxx
- tree/dataframe/src/RJittedFilter.cxx
- tree/dataframe/src/RVariationBase.cxx
- tree/dataframe/test/dataframe_helpers.cxx
Before this commit, whenever a function was constructing a node
of the computation graph it had to "remember" to also register
that node with the RLoopManager, which needs to know which nodes
are around so it can tell them e.g. to execute task initialization
and task finalization logic.
Deregistration happened in the node's destructors.
With this patch, registration happen in the constructor and
deregistration in the destructor of a node, i.e. this logic is
where a reader might expect it to be and new code does not have
to "remember" to register objects with the RLoopManager.
Jitted nodes of the computation graph (e.g. RJittedAction,
RJittedDefine) don't need to register themselves with the
RLoopManager: the _concrete_ nodes will be registered right
before the event loop, at jitting time, …
> [DF] Simplify reg-/deregistration with RLoopManager

- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
- tree/dataframe/inc/ROOT/RDF/RResultMap.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/inc/ROOT/RDFHelpers.hxx
With this patch, RResultMap points to the one and only nominal
result and we do not duplicate work for the nominal value (i.e.
we don't handle the nominal case in RVariedAction anymore).
Vincenzo please check whether things make sense for RMergeableValues.
> [DF] Do not duplicate work for nominal case when variations are present

- tree/dataframe/test/datasource_ntuple.cxx
These tests are expected to fail at the moment. RNTupleDS needs a little tweak to use RRVecField instead of RVectorField to read collections.
Re-test and merge after #10623 is in.
> [DF] Add tests for RNTupleDS + RVecs

- tree/dataframe/src/RDFInterfaceUtils.cxx
TL;DR:
Jit `auto f1(..) { ... }` instead of `auto l1 = [](..) { ... };`
Now that we have C++14 support available, we can jit functions
with auto return types instead of lambda expressions as helper
functions for filters and defines. Functions might compile a bit
faster (it might matter when we have thousands) and make our
jitted code a bit more readable.
There is also a chance that it will help with some symbol resolution issues with `perf` and jitted code (cc: @amadio ).
Most of the patch is non-functional renames of variables and functions,
the only functional change is:
```diff
--- a/tree/dataframe/src/RDFInterfaceUtils.cxx
+++ b/tree/dataframe/src/RDFInterfaceUtils.cxx
@@ -229,7 +229,7 @@ BuildLambdaString(const std::string &expr, const ColumnNames_t &vars, const Colu
}; …
```
> [DF] Jit helper functions instead of helper lambdas

- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/src/RooAbsData.cxx
One of the overloads of `RooAbsData::createHistogram` was deprecated
because it behaved inconsistently with another more frequently used
overload (see https://github.com/root-project/root/pull/10411).
However, I forgot to mention the deprecation in the documentation and
pointed it out only in the source code with the deprecated macro. This
commit adds the corresponding `\deprecated` note to the reference guide.
Also, some code modernizations were applied to the source file while at it:
* replace `TString` with `std::string`
* replace `0` with `nullptr`
* replace iterator loops with range-based loops
* memory management with `std::unique_ptr`
> [RF] RooAbsData code modernization and docmumentation update

- interpreter/cling/lib/Interpreter/Interpreter.cpp
The crash occurs due to a missing guard that prevents `libcudart.so` from being loaded. Loading a library requires an executor which is not available in syntax-only mode.
Without guard, the following assert is triggered in a debug build:
```
cling: /home/sehrig/workspace/cling/llvm/tools/cling/lib/Interpreter/Interpreter.cpp:1657: const cling::DynamicLibraryManager *cling::Interpreter::getDynamicLibraryManager() const: Assertion `m_Executor.get() && "We must have an executor"' failed.
```
> Fix crash, if cling is started with the arguments `-xcuda -fsyntax-only`

- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDF/RRange.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/src/RJittedFilter.cxx
- tree/dataframe/src/RLoopManager.cxx
We now use Register/Deregister instead of Book/Deregister (where "booking" is an overloaded term in RDF too).
> [DF] More uniform naming for internal RLoopManager methods

- cmake/modules/FindXROOTD.cmake
Detection of XrootD built from git commit
This PR fixes #10604
> Better detection of XrootD version

- roofit/roofit/inc/RooNDKeysPdf.h
- roofit/roofit/src/RooIntegralMorph.cxx
- roofit/roofit/src/RooNDKeysPdf.cxx
Some speedups to targeted RooFit classes to speed up the RooFit tests such that the performance gain with the batch mode is more prominent relatively (as this PR removes unnecessary overhead that affected both the batch mode and the scalar mode).
More detail in the commit messages.
All changes are tested by the stressRooFit suite, including the multidimentional case in the RooNDKeysPdf.
> [RF] Some speedups in RooIntegralMorph and RooNDKeysPdf

- roofit/roofit/src/RooGaussModel.cxx
In the RooDecay case, the evalCerf function called internally in
RooGaussModel passes a purely imaginary argument to
`RooMath::faddeeva_fast`. In this case, the Faddeeva function is equal
to a scaled complementary error function, which can be evaluated more
efficiently using `std::erfc`.
The speedup can be seen in the stressRooFit tests that involve the
RooDecay, for example:
`Test 22 : Full per-event error p.d.f. F(t|dt)G(dt)`
The test can be run individually to verify this speedup:
```
`./stressRooFit -n 22`
```
> [RF] Speed up RooDecay by at least a factor two by optimizing `evalCerf` in RooGaussModel

- tutorials/roostats/rs401d_FeldmanCousins.C
Avoid using a deprecated function in RooAbsData::createHistogram
> Fix use of RooFit::Extended in createNLL

- roofit/roofitcore/src/RooMinimizer.cxx
This Pull request resets correctly the original error definition in the Minimizer class and fixes the problem of calling two times RooMinimizer::contour() (issue #10440)
The problem is that resetting as before using the FitConfig class does not work because the 
values stored in the FitConfig are set in the Minimizer only before Fitting or when calling Hesse or Minos. So, the resetting works for a following call to migrad() but not for a call to contour(). 
This PR fixes #10440
> [RF] Correctly restore the error definition in the Minimizer class after contour()

- math/mathcore/inc/Math/TDataPointN.h
This makes it part of the template instantiation and requires the compiler / linker to de-duplicate it.
> [math] Define TDataPointN::kDimension in template

- core/unix/src/TUnixSystem.cxx
When compiled with latest gcc / clib, one get warnings like:
```
/usr/include/string.h:241:27: error: ‘char* __builtin_strchr(const char*, int)’ argument 1 declared attribute ‘nonstring’
```
It is because of declaration:
```
char ut_host[UT_HOSTSIZE]
__attribute_nonstring__;    /* Hostname for remote login.  */
```
Seems to be, `ut_host` cannot be used as null-terminated string.
Therefore copy value in TString before using it.
Plus replace 0 -> nullptr
>  fix attribute nonstring warning in TUnixSystem.cxx

- builtins/xrootd/CMakeLists.txt
- builtins/zeromq/cppzmq/CMakeLists.txt
hashes are not stable when downloading release sources from github, see
https://security.stackexchange.com/a/240209
https://github.com/root-project/root/issues/10503
(cherry picked from commit 8f05559cb9d74e5bc6c65bbd39a0dce82b18a3eb)
> [v626][cmake] Use lcgpackages@cern, rather than unstable github:

- math/mathcore/inc/Fit/Fitter.h
- math/mathcore/src/Fitter.cxx
In case of an objective funciton (FCN) given by the user, like in case of RooMinimizer, we don't clone the FCN before fitting, but we do after fitting or after running Hesse/Minos.
In this way the user can have the correct FCN state information updated during the fit.
For example, with this Pull request, the correct number of function call can be returned by `RooMinimizer::evalCounter()`
> [Math] Avoid cloning before fitting the user provided FCN

- hist/hist/inc/Math/WrappedMultiTF1.h
- hist/hist/src/TF1.cxx
- hist/hist/src/TFormula.cxx
- math/fumili/inc/TFumili.h
- math/fumili/src/TFumili.cxx
- math/mathcore/inc/Fit/Chi2FCN.h
- math/mathcore/inc/Fit/FitUtil.h
- math/mathcore/inc/Fit/LogLikelihoodFCN.h
- math/mathcore/inc/Fit/PoissonLikelihoodFCN.h
- math/mathcore/inc/Math/FitMethodFunction.h
- math/mathcore/src/FitUtil.cxx
- math/mathmore/inc/Math/GSLNLSMinimizer.h
- math/mathmore/src/GSLNLSMinimizer.cxx
- tutorials/fit/minuit2GausFit.C
This PR fixes allows to use external gradient (for example computed with CLAD in TFormula) in the GSLMultiFit algorithm. 
A fix is applied also in TF1::GradientPar where in case of CLAD gradient a vector is allocated for storing the gradient. Using an external pointer, for example coming from GSL has shown to be problematic.
> [math] Improve gsl multifit algorithm with support for external gradient

- core/base/inc/ROOT/TExecutorCRTP.hxx
- core/base/inc/ROOT/TSequentialExecutor.hxx
- core/foundation/inc/ROOT/RNotFn.hxx
- core/foundation/inc/ROOT/TypeTraits.hxx
- core/imt/inc/ROOT/TExecutor.hxx
- core/imt/inc/ROOT/TFuture.hxx
- core/imt/inc/ROOT/TThreadExecutor.hxx
- core/multiproc/inc/ROOT/TProcessExecutor.hxx
- core/multiproc/inc/TMPWorker.h
- tree/treeplayer/inc/ROOT/TTreeProcessorMP.hxx
- tree/treeplayer/inc/TMPWorkerTree.h
`ROOT::TypeTraits::InvokeResult_t` is a wrapper for `std::invoke_result_t` that falls back to
`std::result_of_t` if the former is not available. It is useful as a
C++-standard-agnostic wrapper for this functionality, as
`std::result_of` has been deprecated in C++17 but `std::invoke_result`
is only available since C++17.
I substituted all usages of `std::result_of` in `tree/` and `core/` with usages of `InvokeResult_t`, which removes deprecation warnings when building ROOT with C++17 (esp. with clang) and indirectly provides _a lot_ of test coverage.
> [code] Add `InvokeResult_t`, use that instead of deprecated `std::result_of` 

- math/mathcore/src/TMath.cxx
typo in the previous commit.
Sorry
> [skip-ci] fix typo

- tmva/tmva/inc/TMVA/Executor.h
std::result_of is deprecated in C++17, use the
C++-standard-agnostic alternative InvokeResult_t instead.
> [TMVA] Use InvokeResult_t instead of std::result_of

- tree/dataframe/inc/ROOT/RDF/RJittedDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/src/RJittedDefine.cxx
- tree/dataframe/test/dataframe_vary.cxx
**First two commits**:
Sanity checks for a non-jitted Vary asked the nominal Define'd
columns static type information that a jitted Define did not have.
With this patch RJittedDefine should also have that type
information in most if not all cases.
**Last commit**:
Fix potential invalid memory access when using Vary.
Users can vary a single column or multiple columns simultaneously.
In the latter case, RVariation::fLastResults contains, for each
processing slot, an RVec of RVecs of results where the outer
dimension runs over the different columns and the inner one over
the varied values of each column.
Before this commit, RVariation was initializing fLastResults to
the wrong size in the case of multiple columns varied simultaneously,
which ended up causing invalid memory accesses during …
> [DF] Fix crash with jitted Define and non-jitted Vary

- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/test/dataframe_vary.cxx
When varying multiple columns simultaneously, RVariation was destroying
and re-creating the per-column RVecs of varied values at every entry,
which resulted in a change in  the address of the varied values between
entries, which caused invalid reads on the part of the RVariationReader
(which assumes the addresses of varied values are stable).
The issue was hidden by RVec's small buffer optimization, which was
keeping addresses stable as long as the number of variations fit the
small buffer.
> [DF] Fix invalid reads in Vary with many variations and multiple columns

- core/base/src/TUUID.cxx
At FreeBSD 13.1, the following compilation error appears:
```
core/base/src/TUUID.cxx:444:33: error: member access into incomplete type 'struct sockaddr'
if (ifa->ifa_addr->sa_family != AF_INET) { // check only IP4
^
/usr/include/ifaddrs.h:37:9: note: forward declaration of 'sockaddr'
struct sockaddr *ifa_addr;
^
1 error generated.
```
The `struct sockaddr` is defined in the header file sys/socket.h ([specification](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/sys_socket.h.html#tag_13_61)), which is missing. The header is added in this request.
> Add missing header sys/socket.h.

- gui/webdisplay/src/RWebWindowWSHandler.hxx
- js/build/jsroot.js
- js/changes.md
- js/modules/base/latex.mjs
- js/modules/core.mjs
- js/modules/gpad/TFramePainter.mjs
- js/modules/gui/HierarchyPainter.mjs
- js/modules/hist/TH3Painter.mjs
- js/modules/hist/TPavePainter.mjs
- js/modules/hist2d/RH1Painter.mjs
- js/modules/hist2d/TH1Painter.mjs
- js/modules/hist2d/THistPainter.mjs
- tutorials/geom/webdemo.html
- tutorials/geom/webhelp.html
- tutorials/webgui/ping/ping.html
- tutorials/webgui/webwindow/client.html
- ui5/browser/browser.html
- ui5/canv/canvas.html
- ui5/canv/canvas6.html
- ui5/canv/controller/Canvas.controller.js
- ui5/eve7/geom.html
- ui5/eve7/index.html
- ui5/panel/panel.html
Use import like:
import { connectWebWindow } from  './jsrootsys/modules/webwindow.mjs';
import { source_dir } from './jsrootsys/modules/core.mjs';
This let use widgets also with http redirection where top server path
may be handled not directly by the `THttpServer`
Correctly use client versioning for JSROOT modules
Update JSROOT - fixing TPaveText problems
> [webgui] always use relative path when loading JSROOT

- tree/dataframe/test/CMakeLists.txt
Fix the following compilation error on Windows 64:
```
dataframe_vary.cxx : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```
> [skip-ci][win64] Fix fatal compilation error on Windows 64

- interpreter/cling/lib/Interpreter/PerfJITEventListener.cpp
Including that header from cling breaks building ROOT with
external llvm and clang (which is needed e.g. for the conda
package): `config.h` is not avaiable in that scenario.
cc: @chrisburr
> [cling] Remove unused include of "llvm/Config/config.h"

- tmva/tmva/src/MethodCategory.cxx
This Pull request removes a log message reported when using MethodCategory, see 
https://root-forum.cern.ch/t/stray-cout-in-tmva-getmvavalue/50287
> [TMVA] Fix printout message in MethodCategory::GetMvaValue

- tree/dataframe/test/dataframe_snapshot.cxx
...in an attempt to avoid bogus broken comparisons in the
RDFSnapshotArrays.SingleThread test case in dataframe_snapshot
on some platforms.
> [DF] Simplify EXPECT_EQ call

- math/mathcore/inc/Fit/Fitter.h
- math/mathcore/src/Fitter.cxx
- tutorials/fit/fit2dHist.C
This Pull request fixes the handling of the FCN function provided when using the template 
signature of SetFCN and FitFCN. 
This PR fixes  #10732
> [Math] Fix template Fitter::SetFCN and FitFCN

- interpreter/cling/tools/packaging/cpt.py
Fixes the cmakeDIr undefined error that occurs on Windows 
Added cmakeDir variable to cpt.py
This PR fixes issue 426 (ihttps://github.com/root-project/cling/issues/426)
> Added cmakeDir for Windows- Cling Packaging Tool (cpt.py)

- cmake/modules/RootMacros.cmake
This makes sure that the list of directories is actually empty in case neither `inc/` nor `v7/inc/` exist, and does not contain left-overs that were stored in this variable in a parent scope.
After this change, `roottest/root/meta/rootcling/module.modulemap` is much shorter and in particular free of non-existent entries complained about by the LLVM 13 upgrade.
> [cmake] Reset variable in ROOT_FIND_DIRS_WITH_HEADERS

- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/src/RLoopManager.cxx
- tree/tree/inc/LinkDef.h
- tree/tree/inc/ROOT/InternalTreeUtils.hxx
- tree/tree/src/InternalTreeUtils.cxx
- tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
- tree/treeplayer/src/TTreeProcessorMT.cxx
Having that bit set on TBranches causes _a lot_ of thread
contention (~TBranch -> ~TNamed -> RecursiveRemove).
Similarly for leaves.
This mitigates performance issues with MT runs on certain samples
where all branches and leaves have this bit set.
For a reproducer provided by a CMS user, this patch provides a factor 9 speed-up, up to a factor 30 for a stripped down version of said reproducer that exacerbates the issue.
> [DF] Reset kMustCleanup bit on all branches in MT runs

- tree/tree/src/InternalTreeUtils.cxx
I was failing to build ROOT on Fedora 36 (gcc 12) with the following error
```
/home/vpadulan/Programs/rootproject/rootsrc/tree/tree/src/InternalTreeUtils.cxx: In function ‘void ROOT::Internal::TreeUtils::ClearMustCleanupBits(TObjArray&)’:
/home/vpadulan/Programs/rootproject/rootsrc/tree/tree/src/InternalTreeUtils.cxx:238:13: error: invalid use of incomplete type ‘class TBranch’
238 |       branch->ResetBit(kMustCleanup);
|             ^~
In file included from /home/vpadulan/Programs/rootproject/rootsrc/tree/tree/inc/TTree.h:30,
from /home/vpadulan/Programs/rootproject/rootsrc/tree/tree/inc/TChain.h:24,
from /home/vpadulan/Programs/rootproject/rootsrc/tree/tree/inc/ROOT/InternalTreeUtils.hxx:21,
from /home/vpadulan/Programs/rootproject/rootsrc/tree/tree/src/InternalTreeUtils.cxx:9: …
```
> [tree] Add missing include in InternalTreeUtils.cxx

- interpreter/cling/tools/packaging/cpt.py
Fixes the undefined llvm_flags error that occurs when --last-stable is called
Added a call to the download_llvm_binary function, which sets the llvm_flags variable
This PR fixes issue 423 (https://github.com/root-project/cling/issues/423)
> [cling-cpt] Fixed llvm_flags undefined error that occurred when --last-stable option used [skip-ci]

- roofit/roofitcore/src/RooAbsReal.cxx
The `RooAbsReal::getPropagatedError()` function was using some of the
most expensive operations in RooFit for larger computation graphs:
cloning the model, and figuring out parameters and observables.
This was done for no apparent reason, as the `RooAbsReal` is not mutated
by `getPropagaterError`. Parameter values are slightly changed for
reevaluation, but they are reset right after. A final call to `getVal()`
is enough to reset the original state, which is much more efficient than
cloning everything.
This change was motivated by the following forum post:
https://root-forum.cern.ch/t/getpropagatederror-method-taking-too-long-to-run/50392
> [RF] Don't deep clone the RooAbsArg in `RooAbsReal::getPropagatedError`

- roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
HistFactory allows to set nuisance parameters to given values (and
possibly set them to constant) by using something like
```
<ParamSetting Val=1 Const="True"> myNP </ParamSetting>
```
However the Asimov dataset created by `hist2workspace` does not respect
this setting, because in
[MakeCombiendModel](https://root.cern/doc/master/HistoToWorkspaceFactoryFast_8cxx_source.html#l02109)
the Asimov workspace is created before the ParamSettings are applied.
This commit is fixing this problem.
The problem can be reproduced with the following script/instructions:
```C++
using namespace RooStats;
using namespace HistFactory;
// Step 1: initialize the XML files
//
// Run prepareHistFactory before in this directory
//
// Modify the GaussExample in the generated example to be:
//
// <Measurement …
```
> [RF] Don't ignore ParamSetting values in HistFactory Asimov dataset

- roofit/histfactory/src/RooBarlowBeestonLL.cxx
- roofit/roofit/src/RooMomentMorphFuncND.cxx
- roofit/roofit/src/RooMomentMorphND.cxx
- roofit/roofitcore/inc/RooExpensiveObjectCache.h
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooExpensiveObjectCache.cxx
- roofit/roofitcore/src/RooFitResult.cxx
- roofit/roofitcore/src/RooGradMinimizerFcn.cxx
- roofit/roofitcore/src/RooLinearVar.cxx
- roofit/roofitcore/src/RooMCStudy.cxx
- roofit/roofitcore/src/RooProdGenContext.cxx
- roofit/roofitcore/src/RooWorkspace.cxx
This is part of the RooFit code modernization. After this PR, we will
probably only need one more to replace the remaining occurences of
`createIterator`.
> [RF] Replace more `createIterator` occurences by range-based loops

- roofit/roofitcore/src/RooFactoryWSTool.cxx
- roofit/roofitcore/test/testWorkspace.cxx
So far, the a constructorr match was reported for
`RooWorkspace::factory` when the number of constructor args was larger
than the number of args passed to `factory`.
Obviously, this lead to false positives, and it should actually check if
the number of passed args (plus 2 for name and title) is somewhere
between the number of minimum and maximum arguments that the constructor
can take. In other works, instead of assuming there is an arbitrary
number of default arguments one should do the check with their exact
number.
A unit test to check that this works now is also implemented.
Closes #7965.
> [RF] Improve the constructor matching in `RooFactoryWSTool`

- build/win/w32pragma.h
- core/foundation/inc/ROOT/RConfig.hxx
Replace `__x86_64__` by `R__x86_64__` on Win64 to prevent possible conflicts, as [reported on the forum](https://root-forum.cern.ch/t/preprocessor-macro-x86-64-problem-with-clhep-on-windows/50431)
> Replace __x86_64__ by R__x86_64__ on Win64

- build/win/w32pragma.h
- core/foundation/inc/ROOT/RConfig.hxx
Replace `__x86_64__` by `R__x86_64__` on Win64 to prevent possible conflicts, as [reported on the forum](https://root-forum.cern.ch/t/preprocessor-macro-x86-64-problem-with-clhep-on-windows/50431)
> [skip-ci][v6-26]Replace __x86_64__ by R__x86_64__ on Win64

- tree/ntuple/v7/doc/specifications.md
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/ntuple_types.cxx
This pull request adds `std::tuple<...>` RField support (see notes below).  Follow-up PR of #10631.
- Amend `RRecordField` offsets computation: account for padding inserted before each member to comply with the alignment requirements of the type.
- Add `std::tuple` RField support.
ISO C++ does not guarantee neither specific layout nor member names for `std::tuple`.
Therefore, for the type-erased `RTupleField`, we guess the offsets assuming that most implementations store it as a standard-layout type with members reversed w.r.t. the type list.  A test has been added to check that this renders usable `RTupleField`s in all CI configurations, even when padding is added (see `char` members). 
**EDIT:** most implementations including libstdc++ (gcc), libc++ (llvm), and MSVC name members as …
> [ntuple] `std::tuple` RField support

- bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
Fix the following crash when running `roodataset-numpy` and `roodatahist-numpy` on Windows 64:
```
*** Break *** abort
==========================================
=============== STACKTRACE ===============
==========================================
================ Thread 0 ================
C:\build\night\LABEL\windows64\SPEC\default\V\master\root\bindings\pyroot\cppyy\cppyy-backend\clingwrapper\src\clingwrapper.cxx(198): `anonymous namespace'::TExceptionHandlerImp::HandleException()
C:\build\night\LABEL\windows64\SPEC\default\V\master\root\core\winnt\src\TWinNTSystem.cxx(1766): TWinNTSystem::DispatchSignals()
ucrtbase!raise()
ucrtbase!abort()
ucrtbase!terminate()
VCRUNTIME140!_std_terminate()
VCRUNTIME140_1!??
VCRUNTIME140_1!_NLG_Return2()
VCRUNTIME140_1!_NLG_Return2() …
```
> [skip-ci][win64] Fix potential crash in clingwrapper on Windows 64

- tree/ntuple/v7/inc/ROOT/RDaos.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
- tree/ntuple/v7/inc/ROOT/libdaos_mock/daos.h
- tree/ntuple/v7/src/RDaos.cxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
- tree/ntuple/v7/src/libdaos_mock/libdaos_mock.cxx
- tree/ntuple/v7/test/CMakeLists.txt
- tree/ntuple/v7/test/ntuple_storage_daos.cxx
Makes changes to ROOT v7 in order to comply with the API for DAOS 2.0.x, affecting the libraries `RPageStorageDaos`, `RDaos` and `libdaos_mock`, as well as the `ntuple_storage_daos` test suite.
- As of DAOS 2.0, pool service replica ranks are not longer specified in DAOS URIs.  Thus, `daos_pool_connect` now forgoes the `svc_rank_list` argument.
- Container addresses follow the simplified pattern `daos://($pool)/($container)`. 
- `RPageStorageDaos` consequently drops parsing enforcement of the previous pattern.
- DAOS 2.0 introduced support for creating pools and containers from a label that is then hashed internally as a UUID. Pool and containers are now identifiable by user-provided labels of up to 127 characters (alphanumeric, colon, period, hyphen or underscore) or by 36-character …
> [ntuple,daos] Adapt I/O backend to DAOSv2 API

- roofit/roofitcore/inc/LinkDef.h
- roofit/roofitcore/inc/RooCollectionProxy.h
There was a bug in a schema evolution rule for a very old RooProduct
version, where a `RooSetProxy` member was replaced by a `RooListProxy`.
The problem was that only the content was copied to the new proxy list,
not the other members. This lead to an invalid state for the
RooSetProxy, because it had no registered owner.
The fix is to use a real copy constructor from `RooSetProxy` to
`RooListProxy`, which is also introduced in this commit with the schema
evolution rule fix.
> [RF] Fix schema evolution rule for old RooProduct versions

- roofit/roofit/inc/RooParametricStepFunction.h
- roofit/roofit/src/RooParametricStepFunction.cxx
The `RooParametricStepFunction` is not used much, but still there is an
issue requesting to explain its usage better that needs to be closed.
I don't think it's worth it to have a tutorial for it, but nothing
speaks about having a little complete usage example script in the
reference guide instead of the code stub that is there right now.
This change to the documentation goes together with some gentle code
modernization in this commit.
Closes #7748.
> [RF] Clarify usage of RooParametricStepFunction

- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/ntuple_types.cxx
Although padding is implementation-dependent, most add enough padding at the end to comply with the requirements of the type with strictest alignment.
Given that `GetValueSize()` is used to allocate memory for the described type, not accouting trailing padding may cause issues.
`ROOT::Experimental::RFieldDescriptor::CreateField()` has a direct use of RRecordField. Despite it seems to be working in all tested platforms, be on the safe side and add this padding.
This, does not affect derived classes `RPairField` and `RTupleField`, that override determination of the size of the type.
> [ntuple] RRecordField: accout for trailing padding

- tutorials/webgui/ping/ping.cxx
On some platforms first start of web browser takes longer than 15 s.
Make it now 70 s.
> [webgui] increase startup time of ping test [6.26]

- roofit/roofitcore/inc/RooProdPdf.h
- roofit/roofitcore/inc/RooProduct.h
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/src/RooProduct.cxx
- roofit/roofitcore/test/testWorkspace.cxx
This commit fixes two issues:
1. Introduce `RooProduct` constructor from two RooAbsReals to be
consistent with the `RooRrodPdf`, which has a constructor from two
RooAbsPdfs.
2. Remove a useless dummy constructor for a `RooProdPdf` with no
factors, which somehow prevented the constructor from a RooFit
collection to be picked up correctly by `RooWorkspace::factory()`
The request to change the RooProduct and RooProdPdf constructors from
RooFit collections to take RooArgSets and not RooArgLists (https://github.com/root-project/root/issues/7809#issuecomment-817683625) was not
followed. This would be a breaking change for people that use
`RooProduct` to square a function for example.
A unit test for the issue was also implemented.
Closes https://github.com/root-project/root/issues/7809.
> [RF] Fix problem of RooProduct and RooProdPdf with RooWorkspace factory

- roofit/roostats/src/SPlot.cxx
In SPlots, `RooAbsArg::attachDataSet()` is called on the input pdf,
redirecting the parameters of the pdf to the RooRealVars in the dataset.
This is not reversed, leaving the pdf in a corrupt state when the
dataset gets deleted. This can happen in particular if the SPlots object
created an owning clone of the dataset, attaches the pdf, and then goes
out of scope.
This commit suggests to not attach the pdf to the dataset, as it is not
necessary. When looping over the dataset and evaluating the pdf later,
the pdf variables get synced with the dataset variables anyway. This was
done via `RooStats::SetParameters`, which is just a wrapper around
`RooAbsCollection::assign()`. I suggest to use `assign()` directly to make
more explicit to the reader what happens.
It was verified that SPlot still …
> [RF] Fix corruption of input pdf after using RooStats::SPlot

- roofit/roofitcore/inc/RooXYChi2Var.h
- roofit/roofitcore/src/RooXYChi2Var.cxx
If a RooXYChi2Var is not a "Slave" in the RooAbsOptTestStatistic
framework, it doesn't do any actual computation and no initialization is
needed. It would not even work and causes a crash, because `_funcObsSet`
would be a `nullptr`.
> [RF] Fix crash when using RooXYChi2Var with RooSimultaneous

- roofit/roofit/inc/RooBernstein.h
In commit 0d1f0bbde0, the IO constructor of RooBernstein has
accidentally been removed, which broke reading RooBernstein instances
from ROOT files. Hence, this commit brings it back.
No backport needed, because the IO constructor was removed in the same
development cycle (leading up to 6.28).
> [RF] Bring back missing IO constructor to RooBernstein

- graf3d/eve7/inc/ROOT/REveBoxSet.hxx
- graf3d/eve7/inc/ROOT/REveDigitSet.hxx
- graf3d/eve7/src/REveBoxSet.cxx
- graf3d/eve7/src/REveDigitSet.cxx
- tutorials/eve7/boxset.C
- tutorials/eve7/collection_proxies.C
- ui5/eve7/lib/EveElements.js
Add support for visualization of digit sets in the context of physics collections:
* tooltip related to selected collection item
* optimization  for filtered items, e.g. only visible digits are streamed to client
Exmaple of RecHits visualization in CMS
> REve: Support DigitSet visualization in the context of REveDataCollection

- graf2d/asimage/src/TASImage.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/graf/src/TAttImage.cxx
- graf2d/graf/src/TPolyLine.cxx
- hist/histpainter/src/TGraphPainter.cxx
- hist/histpainter/src/THistPainter.cxx
Ensure that static members line `Int_t *x` or `TBox *zoombox` correctly managed can cleanup even 
when mouse event handling is not working properly. Especially when exit application.
> [graphics] use c++ classes for temporary data in ExecuteEvent methods

- hist/hist/src/TGraph2D.cxx
- hist/histpainter/src/THistPainter.cxx
The CONT5 option is for TGraph2D only.
> [skip-ci] put CONT5 option in the right place

- hist/histpainter/inc/THistPainter.h
- hist/histpainter/src/THistPainter.cxx
1. Fix leak with using TGraph2DPainter
2. Fix leak with "cont list" draw option
3. Use `std::unique_ptr` for all objects created and managed by hist painter, ensure proper deletion
4. Use `std::vector` instead of plain C arrays, avoid any potential memory leak
5. Replace plain `Form()` by `TString::Format()`
6. Simplify some `TIter` loops
7. Use more `nullptr`
> [histpainter] Fix memory leaks, use more c++

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
Inline C++ needs double quotes, Python is ok with single quotes.
> [NFC][DF] Fix typo in Python example

- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
We now register all RDefine nodes, incuding varied defines, with
RLoopManager, which is in charge of calling InitSlot on all
registered nodes, so we do not need to propagate the InitSlot call
from RVariation or RDefine to other RDefines.
> [DF] Remove redundant calls to RDefine::InitSlot

- etc/RooFitHS3_wsexportkeys.json
- etc/RooFitHS3_wsfactoryexpressions.json
- roofit/hs3/src/JSONFactories_HistFactory.cxx
Fixes a bug in RooFitHS3 that could lead to segfaults in cases observables names in HistFuncs and their DataHists would mismatch.
Adds new classes to importer and exporter json definitions.
> [RF] HS3 improvements

- roofit/roofitcore/inc/RooRealSumFunc.h
- roofit/roofitcore/inc/RooRealSumPdf.h
- roofit/roofitcore/src/RooRealSumFunc.cxx
- roofit/roofitcore/src/RooRealSumPdf.cxx
All functions in RooRealSumFunc and RooRealSumPdf are overloaded in
exactly the same way. The two classes only differ in the base class.
To avoid code duplication, the member functions are implemented as private
static functions in RooRealSumPdf, which the friend class RooRealSumFunc
can also use. This pattern might be used also to avoid further code
duplication, also with the other addition classes like RooAddition and
RooAddPdf in the future.
This solution was preferred over changing the classes themselves, because
the right to run into schema evolution problems is much higher then.
This closes also the RooRealSumFunc modernization issue #8374, as now
its implementation uses the code from the RooRealSumPdf which is already
modernized.
> [RF] Avoid code duplication in RooRealSumFunc/RooRealSumPdf

- interpreter/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp
This commit reverts root-project/root@69568116cd
The CtorsConstants variable is not used. The commit log has a simple tests which now works without this patch.
Thanks to Jonas Hahnfeld (@hahnjo) for pointing this out!
> Revert "Merge Ctors from nested transactions"

- interpreter/cling/tools/packaging/cpt.py
Fixes the verbose output flag for cpt.py
Added cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON, then make -j (number of cores) install is called
This PR fixes issue mentioned in meta issue list for cpt.py 406 (https://github.com/root-project/cling/issues/406)
> Edited verbose output flag- Cling Packaging Tool (cpt.py) [skip-ci]

- graf2d/graf/inc/TGaxis.h
- graf2d/graf/inc/TLatex.h
- graf2d/graf/inc/TPieSlice.h
- graf2d/graf/src/TCandle.cxx
- graf2d/graf/src/TCutG.cxx
- graf2d/graf/src/TGaxis.cxx
- graf2d/graf/src/TGraphPolar.cxx
- graf2d/graf/src/TGraphPolargram.cxx
- graf2d/graf/src/TGraphQQ.cxx
- graf2d/graf/src/TLatex.cxx
- graf2d/graf/src/TLegend.cxx
- graf2d/graf/src/TMarker.cxx
- graf2d/graf/src/TPaveStats.cxx
- graf2d/graf/src/TPaveText.cxx
- graf2d/graf/src/TPie.cxx
- graf2d/graf/src/TPieSlice.cxx
- graf2d/graf/src/TPolyLine.cxx
1. Fix error with copy and destroy of `TLatex::fTabSize`. Now it is `std::vector` and can be easily copied - if necessary. Also using as stack is much more convenient - just by using `emplace_back` and `pop_back`
2. Fix bug in `TPie` copy constructor
3. Fix memory leak with `TGaxis::fModLabs`. Array was never deleted and never copied properly. Extra problem because it may have pointer on list of labels from `TAxis`. Provide workaround for `TGaxis` objects stored before in ROOT files.
4. Use stack variables while painting - no need to call `new/delete` for simple objects like `TLine` or `TMarker`
5. Fix memory leak reading old version of TPolyLine
6. Use `TString::Form` instead of `snprinf`
7. Use `nullptr`
> Fix several memory leaks and problems in graf2d/graf classes

- tree/dataframe/src/RDFColumnRegister.cxx
Before this patch, we were iterating until the end of the map
rather than until the end of the equal_range (this was not a
problem in practice because program logic guaranteed that we would
find what we were looking for and break out of the loop early).
> [DF] Fix iteration over multimap

- net/http/civetweb/civetweb.c
This is to get rid of deprecation warninigs when building on Ubuntu
22.04.
Should cause no backwards compatibility poblems, as the functions that
are used now are around at least since OpenSSL 1.0.2:
https://www.openssl.org/docs/man1.0.2/man3/EVP_DigestInit_ex.html
This patch was already applied to upstream civet:
https://github.com/civetweb/civetweb/pull/1072
> Using higher-level wrapper of OpenSSL SHA1 hash function in civetweb

- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/test/testRooAbsPdf.cxx
If the proxy normSet changed, we also have to set the value dirty flag
of the proxy owner. Otherwise, value for the new normalization set might
not get recomputed, which causes bugs!
The issue can be reproduced with this small code snippet:
```C++
RooRealVar x("x", "x", 0, -10, 10);
RooGaussian gauss("gauss", "gauss", x, RooConst(0), RooConst(2));
RooAddition add("add", "add",  {gauss});
std::cout << add.getVal() << std::endl;
std::cout << add.getVal(x) << std::endl;
```
Without this commit, the value will be the same with and without
normalization set, because changing only the normalization set didn't
trigger a recomputation.
This code snippet has also been implemented as a unit test now, where it
is tested that the values are different.
> [RF] Fix dirty flag resetting when the normalization set is changed

- roofit/roofitcore/inc/RooAddition.h
- roofit/roofitcore/inc/RooRealSumPdf.h
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooAddition.cxx
- roofit/roofitcore/src/RooRealSumPdf.cxx
Much of the functionality of RooAddition and RooAddPdf is implemented in exactly the
same way as in RooRealSumPdf. Hence, to avoid code duplication, we can
reuse the static functions in RooRealSumPdf that provide this
implementation.
> [RF] Avoid code duplication in RooFit addition classes

- hist/hist/src/TF1.cxx
- hist/hist/src/TFormula.cxx
- hist/hist/src/TFormula_v5.cxx
- hist/hist/src/TGraph.cxx
- hist/hist/src/TGraphTime.cxx
- hist/hist/src/TH1.cxx
- hist/hist/src/TMultiGraph.cxx
- hist/hist/src/TPrincipal.cxx
- hist/hist/src/TProfile2D.cxx
System crashes when calling `strlen(nullptr)`, therefore protect in cases when argument can be directly set as external parameter.
Fix memory leak in TF1 constructor NSUM(...) parsing - created objects are not deleted
Use `std::make_unique<>()` to create `unique_ptr`. Provided as standard from c++14.
Use `TString::Data() ` instead of casting into `(const char *)`
> Protect `strlen(nullptr)` in hist classes, fix memory leak in TF1 constructor

- tutorials/roostats/rs101_limitexample.py
Add rs101_limitexample.py - Converted from rs101_limitexample.C
This PR fixes # Part of [8758](https://github.com/root-project/root/issues/8758)
> [RF] Translate RooStats tutorial rs101_limitexample.C to Python

- bindings/experimental/distrdf/python/DistRDF/Operation.py
- bindings/experimental/distrdf/test/test_operation.py
- tree/dataframe/src/RDataFrame.cxx
If the user doesn't provide a histogram model in distributed mode, the
merging of different histograms coming from different distributed tasks
would not work since the histograms would most probably have
incompatible bins. Rather than wait for failures like
`Error in <Merge>: Cannot merge histograms - limits are inconsistent`
that happen only when the distributed execution has already started and
may be hidden inside worker logs, raise an error in the local user
machine.
An example of the error raised with this change: running this snippet
```python
import ROOT
RDataFrame = ROOT.RDF.Experimental.Distributed.Dask.RDataFrame
from dask.distributed import Client, LocalCluster
def create_connection():
cluster = LocalCluster(n_workers=2, threads_per_worker=1, processes=True)
client = …
```
> Distrdf histoxd nomodel error

- bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
- bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
- bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py
- bindings/experimental/distrdf/python/DistRDF/HeadNode.py
- bindings/experimental/distrdf/test/backend/test_dist.py
- bindings/experimental/distrdf/test/test_callable_generator.py
- bindings/experimental/distrdf/test/test_node.py
- bindings/experimental/distrdf/test/test_proxy.py
- bindings/pyroot/pythonizations/test/dependency_versions.py
- requirements.txt
The number of cores available in the Dask cluster object, i.e. those
that are already known to the scheduler, can be retrieved from the
client object through the `ncores()` method.
In some cases, the scheduler has no information about the worker
nodes when the user first creates it. Most notably, when connecting
to batch resources with e.g. an HTCondorCluster. In this case, the
number of cores is actually known only when the resource manager
starts the requested jobs and this can happen much later in the
application. In these cases, we can infer the number of cores that
will be available from the specification that was passed by the user
to when creating the cluster object. This is stored in dictionary
attributes of the cluster itself.
In order to dispatch the logic on the types of …
> Refactor optimize_npartitions and improve it for the Dask backend

- tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
- tree/ntuple/v7/src/RPageSinkBuf.cxx
- tree/ntuple/v7/src/RPageStorage.cxx
- tree/ntuple/v7/test/ntuple_storage.cxx
This pull request extends `RPageSink` to allow for vector commit of sealed pages.  The prototype of the new functions is as follows:
```c++
virtual std::vector<RNTupleLocator> CommitSealedPageVImpl(std::span<RPageStorage::RSealedPageGroup> ranges);
void CommitSealedPageV(std::span<RPageStorage::RSealedPageGroup> ranges);
```
These changes enable (parallel) vector writes in concrete backends, e.g. in DAOS.  Derived classes that do not override the base implementation will see a sequence of calls to `CommitSealedPage()`.
The first measurements of vector writes on DAOS based on this PR, indicate an improvement of _an order of magnitude_ in the write throughput.
The refactor in this PR passes all the RPageSinkBuf tests.
- Add `CommitSealedPageV()` to the public interface of `RPageSink`. This …
> [ntuple] Allow for vector commit of sealed pages

- graf2d/gpad/src/TButton.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/graf/src/TPaveLabel.cxx
- graf2d/graf/src/TPaveText.cxx
- graf2d/graf/src/TPolyLine.cxx
- hist/hist/src/TMultiGraph.cxx
System crashes when calling `strlen(nullptr)`,  therefore protect in cases when argument can be directly set as external parameter
Simplify TMultiGraph::PaintPads, do not use `TString` as `strlen()` argument
> Protect `strlen(nullptr)` in gpad and graf classes, improve/simplify TMultiGraph "pads" drawing

- core/base/src/TObject.cxx
- core/base/src/TString.cxx
- core/base/src/TStyle.cxx
- core/cont/src/TClassTable.cxx
- core/meta/src/TClass.cxx
Prevent crash when user specifies `nullptr` as argument for `const char*`
> Control `strlen(nullptr)` in several core classes

- tmva/sofie/inc/TMVA/ROperator_Transpose.hxx
Compilation fails with `-Ddev=ON`
> [tmva] add missing include

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabscollection.py
- bindings/pyroot/pythonizations/test/roofit/rooabscollection.py
There are two overloads of RooAbsCollection::addClone():
- RooAbsArg *addClone(const RooAbsArg& var, bool silent=false);
- void addClone(const RooAbsCollection& list, bool silent=false);
In the case of the RooAbsArg overload, we need to tell Python that it
doesn't own the returned pointer. That's because the function name
contains "Clone", which makes cppyy guess that the returned pointer
points to a clone owned by the caller. In the case of the
RooAbsCollection input, the return value will be `None` and we don't
need to change any ownership flags (in fact, calling
SetOwnership(None, False) would cause a crash).
The check for the `None` return value was so far not done in the
pythonization and is added with this commit.
A unit test was also added to check that the RooAbsCollection …
> [RF] Correcly pythonize RooAbsCollection::addClone() for all overloads

- hist/hist/src/TGraph.cxx
Prevent from crash when calling `gr->Fit(nullptr)`
> Protect TGraph::Fit against nullptr in strstr function call

- tree/tree/src/TTree.cxx
In methods like `FindBranch` or `GetBranch` nullptr as argument causing failure.
Avoid casting to `(char *)`
Use `nullptr`
> [tree] protect `strstr`, `strchr`, `strlen` from nullptr argument

- roofit/roofit/inc/RooLagrangianMorphFunc.h
- roofit/roofit/src/RooLagrangianMorphFunc.cxx
WIP will fill this shortly 
This PR is to address #9845
> [RF] Cleanup RooLagrangianMorphFunc

- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/inc/ROOT/RDF/RVariationsDescription.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/src/RDFColumnRegister.cxx
- tree/dataframe/src/RDFGraphUtils.cxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/src/RDefineBase.cxx
- tree/dataframe/src/RFilterBase.cxx
- tree/dataframe/src/RVariationsDescription.cxx
This simplifies client code and it makes it simpler to evolve RColumnRegister internals in the future, which will be needed e.g. for bulk processing in RDF.
> [DF] Improve encapsulation of RColumnRegister data members

- tutorials/roofit/rf102_dataimport.C
- tutorials/roofit/rf104_classfactory.C
- tutorials/roofit/rf201_composite.C
- tutorials/roofit/rf203_ranges.C
- tutorials/roofit/rf207_comptools.C
- tutorials/roofit/rf303_conditional.C
- tutorials/roofit/rf306_condpereventerrors.C
- tutorials/roofit/rf401_importttreethx.C
- tutorials/roofit/rf402_datahandling.C
- tutorials/roofit/rf403_weightedevts.C
- tutorials/roofit/rf404_categories.C
- tutorials/roofit/rf505_asciicfg.C
- tutorials/roofit/rf506_msgservice.C
- tutorials/roofit/rf507_debugtools.C
- tutorials/roofit/rf508_listsetmanip.C
- tutorials/roofit/rf509_wsinteractive.C
- tutorials/roofit/rf510_wsnamedsets.C
- tutorials/roofit/rf511_wsfactory_basic.C
- tutorials/roofit/rf601_intminuit.C
- tutorials/roofit/rf603_multicpu.C
- tutorials/roofit/rf606_nllerrorhandling.C
- tutorials/roofit/rf609_xychi2fit.C
- tutorials/roofit/rf610_visualerror.C
- tutorials/roofit/rf702_efficiencyfit_2D.C
- tutorials/roofit/rf705_linearmorph.C
- tutorials/roofit/rf801_mcstudy.C
- tutorials/roofit/rf803_mcstudy_addons2.C
- tutorials/roofit/rf901_numintconfig.C
- tutorials/roofit/rf902_numgenconfig.C
- tutorials/roofit/rf903_numintcache.C
It's important to follow modern ROOT code patterns in the tutorials,
such that the users will also get it right. Hence, the following
replacements are made in the RooFit tutorials:
* `Double_t` to `double`
* `Bool_t` to `bool`
* `kTrue` to `true`
* `kFalse` to `false`
> [RF] Code modernization in RooFit tutorials

- roofit/histfactory/inc/RooStats/HistFactory/PreprocessFunction.h
- roofit/histfactory/src/PreprocessFunction.cxx
Some improvements are made to the `PreprocessFunction` class:
* add `const` to all the relevant member functions
* remove the `fCommand` member, because it can be inferred from the
other 3 members and it should not be set independently
* use `std::string` by const-reference when possible
* follow the RooFit coding style of using lower-case vor function
argument names
Furthermore, a bugfix is also done:
* in `PreprocessFunction::PrintXML`, replace the XML special
characters which almost always appear in any formula with the XML
escape codes
The bugfix addresses a problem where it was not possible to read an XML
generated by `Measurement::PrintXML` because the special characters in
the formula expression were not properly escaped.
With all these changes applied, the source files for this …
> [RF] Improve RooStats::HistFactory::PreprocessFunction class

- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testRooAddPdf.cxx
When getValV() was directly implemented in RooAddPdf, it was missed to
copy-paste the part from RooAbsPdf::getValV() where the normalization
sets for the proxies was synced.
A unit test with the reproducer for an issue caused by missing the
syncing is also introduced with this commit, involving the SPlot from
RooStats.
Closes #10869.
> [RF] Correctly sync proxy normalization sets in `RooAddPdf::getValV()`

- tree/ntuple/v7/src/RPageStorageDaos.cxx
- tree/ntuple/v7/test/ntuple_storage_daos.cxx
This Pull request fixes a bug in `RPageSourceDaos` in which the cluster bunch default size does not get overridden by the one provided in `RNTupleReadOptions`. This change thus enables the prefetching of a configurable number of clusters while the current bunch is being processed, similarly to what is done in the constructor for `RPageSourceFile`.
- `RPageSourceDaos` ctor now uses the value in `RNTupleReadOptions::fClusterBunchSize` to initialize its `RClusterPool` with configurable read-ahead number of clusters, overwriting the default value of `1`. The change parallels the constructor implementation of `RPageSourceFile`. 
Related to PR #9100, which introduced the prefetching capability.
> [ntuple,daos] Enable configurable cluster prefetching

- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/src/RLoopManager.cxx
Before this patch, each node in the computation graph was
re-creating or re-requesting column readers for datasource and TTree/TChain
columns separately.
We now create column readers for datasource and TTree/TChain columns early and
store them in RLoopManager which then gives out pointers to the
same RColumnReaderBase objects to all nodes.
This is the first part of a series of changes aimed at
centralizing ownership and creation of all kinds of column
readers (defines and variations will come in a subsequent PR).
Sharing column readers among nodes of the computation
graph saves some redundant work and it is a pre-requisite for bulk
processing at the level of RDF.
> [DF] Share datasource/tree column readers between all nodes in the computation graph

- tree/dataframe/test/dataframe_snapshot.cxx
In order to debug not understood test failures that we could
not reproduce outside of the CI.
> [TO REVERT] Add debug prints to dataframe_snapshot

- cmake/modules/RootMacros.cmake
Fix generation of `G__NetxNG.cxx` in paths with special characters, as described on the forum:
https://root-forum.cern.ch/t/6-26-04-build-error-in-debian-bullseye/50412
> Fix generation of G__NetxNG.cxx in paths with special characters

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RNodeBase.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/test/dataframe_simple.cxx
- tree/dataframe/test/datasource_csv.cxx
- tree/dataframe/test/datasource_sqlite.cxx
This way we can check if they are still useful with modern compilers (e.g. with gcc 12.1 I get no warnings).
> [DF] Remove some protections from compiler warnings

- builtins/zstd/CMakeLists.txt
This fixes a warning seen on macOS:
```
zstd_compress_superblock.c:412:12: warning: variable 'litLengthSum' set but not used
```
As we won't fix those there's no need to emit them.
> [cmake] Suppress all warnings compiling builtin-zstd:

- bindings/experimental/distrdf/python/DistRDF/HeadNode.py
There is a logging statement to estimate whether the number of requested
partitions is reasonable given the entries in the first file. This
should not happen every time, but on explicit user request. Python
logging defaults to WARNING, so move the statement to DEBUG to give
better control.
> [DF][NFC] Move logging statement to DEBUG

- graf2d/graf/inc/TMathText.h
- graf2d/graf/src/TLegend.cxx
- graf2d/graf/src/TMathText.cxx
- graf2d/graf/src/TPaveText.cxx
1. Major memory leak in `TMathText` - renderer was never deleted
2. `TMathTex`t copy constructor and assign operator
3. `TLegend` assign operator
4. `TPaveText` copy constructor and assign operator
5. Errors in `TPaveText::GetLine` and `TPaveText::GetLineWidth`
> Fix problems in several graf classes

- tree/ntuple/v7/inc/ROOT/RDaos.hxx
- tree/ntuple/v7/src/RDaos.cxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
This pull request generalizes the `RDaos` backend to support multiple attribute keys per read-write operation, grouping requested blobs by their corresponding <object id, distribution key> pairs - defined as a struct `RDaosContainer::ROidDkeyPair(daos_obj_id_t, DistributionKey_t)`. 
- `RDaosObject::FetchUpdateArgs`, which prepares the arguments for requests to `daos_obj_fetch` or `daos_obj_update`. Now supports multiple attribute keys, I/O operation descriptors and I/O vectors, to send in one RW call to distributed storage.
- `RDaosContainer::RWOperation`, which interfaces between `RPageStorageDaos` and `RDaosObject`, supports multiple attribute keys and I/O vectors. 
- `RPageSourceDaos::LoadClusters` collects requested pages in an `unordered_map<ROidDkeyPair, RWOperation, …
> [ntuple,daos] Support RW operations with multiple attribute keys

- roofit/roofitcore/inc/RooFit/TestStatistics/RooBinnedL.h
- roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h
- roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx
- roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
- roofit/roofitcore/src/TestStatistics/buildLikelihood.cxx
We found and fixed two bugs in the RooFit TestStatistics likelihoods that negatively affected performance:
1. TestStatistics likelihoods were being recalculated every time. They now have caching enabled, so they are only recalculated when parameters change.
2. While cloning the dataset inside the likelihood builder for simultaneous components, all parameters were cloned. Now we only clone the parameters relevant to the specific pdf component.
With these fixes, single-worker performance of MultiProcess enabled fits is now on par with old style RooFit fits, at least with batch mode disabled.
> [RF] RooFit::TestStatistics performance fixes

- core/base/src/TStyle.cxx
- graf3d/g3d/inc/TXTRU.h
- graf3d/g3d/src/TAxis3D.cxx
- graf3d/g3d/src/THelix.cxx
- graf3d/g3d/src/TXTRU.cxx
- hist/hist/inc/TPolyMarker.h
- hist/hist/src/TAxis.cxx
- hist/hist/src/TPolyMarker.cxx
Typical problem - direct copy of self-allocated memory which will lead to error in destructor
Also adjust some assign operators where `Copy` can be used.
> Fix several `Copy(TObject &)` methods

- cmake/modules/RootConfiguration.cmake
Fix an issue with `root-config --has-whatever` as described on the forum: https://root-forum.cern.ch/t/tpythia8-h-file-not-found/50682
The `all_features` list in the `root-config` script was empty when installing it (but was OK in the build directory)
> [skip-ci] Fix an issue with `root-config --has-whatever`

- config/thisroot.bat
Fix correct substring length when setting ROOTSYS
> [skip-ci][win] Fix thisroot.bat

- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooChi2Var.cxx
In the RooChi2Var and the related `createChi2` functions in RooAbsReal
and RooAbsPdf, the `DataError` was not explained precisely enough.
This commit changes the documentation of the RooChi2Var constructor to
exactly explain what is going on, and the the documentation of the
`createChi2` is updated to link to the RooChi2Var documentation to avoid
code duplication.
This commit also replaces some LaTeX formulae from titiles in the
documentation because they are not rendered there.
Closes #8615.
> [RF] Improve documentation for RooChi2Var

- graf2d/graf/src/TLatex.cxx
TAttLine::Copy was using wrong cast for target object.
As a result, line attributes were overwriting some base TObject
members
> Fix bug in TLatex::Copy method [6.26]

- graf2d/graf/src/TLatex.cxx
TAttLine::Copy was using wrong cast for target object.
As a result, line attributes were overwriting some base TObject
members
> Fix bug in TLatex::Copy method [6.24]

- graf2d/graf/src/TLatex.cxx
TAttLine::Copy was using wrong cast for target object.
As a result, line attributes were overwriting some base TObject
members
> Fix bug in TLatex::Copy method [6.22]

- documentation/doxygen/Makefile
- documentation/doxygen/makeCollaborationDiagrams.sh
- documentation/doxygen/modifyClassWebpage.sh
- documentation/doxygen/modifyClassWebpages.sh
This pull request applies a number of fixes after the merge or PR #5913 (see below).
- Fix issues with documentation generation on macOS.  In particular: 
1. Fix `mktemp` command lines to only use template `X`s at the end.
2. Use `sysctl -n hw.ncpu` instead to get the number of available CPUs on Darwin.
3. Move OS-dependent variable assignments to the `Makefile`
- Ensure `libs.C` is ACLiC'ed before `modifyClassWebpage.sh` runs.  Specifically, `modifyClassWebpages.sh` might spawn many `modifyClassWebpage.sh` processes via `xargs -P`.  In turn, `modifyClassWebpage.sh` depends on `libs.C` which is ACLiC'ed if to generate `libs_C.so` where required.
However, if `libs_C.so` does not exist, multiple processes might race to create it. Thus, ensure that the macro is ACLiC'ed before …
> [Doxygen] fix generation of collaboration diagrams

- core/gui/inc/TApplicationImp.h
- core/gui/inc/TCanvasImp.h
- core/gui/inc/TContextMenuImp.h
- core/gui/src/TApplicationImp.cxx
- core/gui/src/TBrowser.cxx
- core/gui/src/TCanvasImp.cxx
- core/gui/src/TContextMenuImp.cxx
Do not split methods declaration and implementation because of compiler warnings
Use `(void) arg` instead.
> Adjust core gui classes

- roofit/histfactory/src/RooBarlowBeestonLL.cxx
Avoid removing elements of `RooArgSet` in `RooBarlowBeestonLL` while looping over them. This was broken since ROOT v6.18, after `RooAbsCollection` was moved to `std::vector` . This (re)enables the analytical treatment of statistical uncertainties in bins with the Barlow-Beeston-Lite procedure.
As described above.
> [RF] RooBarlowBeestonLL: Avoid removing elements of RooArgSet while looping over them 

- core/meta/inc/TEnum.h
- core/meta/src/TDataMember.cxx
- core/meta/src/TEnum.cxx
- core/meta/src/TFunctionTemplate.cxx
- core/meta/src/TGlobal.cxx
- core/meta/src/TProtoClass.cxx
1. Fix memory leak in TDataMember assign operator
2. Provide copy constructor and assign operator for TEnum - default will not work or should be deleted
3. Not forget to reset pointer in TGlobal assign operator
4. Make TProtoClass::Delete reentrant
> Fixes several issues with `core/meta` classes

- core/base/src/TColor.cxx
- core/base/src/TStyle.cxx
- graf2d/gpad/src/TPaveClass.cxx
- graf2d/graf/inc/TPaveLabel.h
- graf2d/graf/src/TArc.cxx
- graf2d/graf/src/TArrow.cxx
- graf2d/graf/src/TCrown.cxx
- graf2d/graf/src/TEllipse.cxx
- graf2d/graf/src/TFrame.cxx
- graf2d/graf/src/TLatex.cxx
- graf2d/graf/src/TLegend.cxx
- graf2d/graf/src/TLegendEntry.cxx
- graf2d/graf/src/TMarker.cxx
- graf2d/graf/src/TPaveLabel.cxx
- graf2d/graf/src/TPolyLine.cxx
- graf3d/g3d/src/TAxis3D.cxx
- graf3d/g3d/src/TXTRU.cxx
- hist/histpainter/src/TPaletteAxis.cxx
This is virtual method and can be overriden in derived classes.
Therefore when such method used in copy constructor or assignment
operator, one have to explicitly specify class which used.
Fix bug in `TLatex::Copy()`
Provide proper implementation of `TLegend::Copy()`
> Properly use `Copy(TObject &)` methods in `graf` classes 

- tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
This pull request introduces a structure (`RDaosKey`) to represent a blob's location within DAOS containers (comprising object ID, distribution key and attribute key) and adds a new mapping between ntuple pages to DAOS.
The new mapping ( `kOidPerCluster` ) allocates one object per cluster and determines the distribution key from the column ID - with each page addressable by its own attribute key - , thus perpetuating the adjacency of values in the same cluster and column in the distributed store. I.e., neighboring values that are likely to be fetched together are coalesced to the same physical device in DAOS.
The original mapping remains available as `kOidPerPage`, where each page is uniquely allocated its own object. In future, other mappings may be easily added by modifying the …
> [ntuple,daos] Generalize and introduce page-object mapping

- documentation/doxygen/libs.C
- documentation/doxygen/modifyClassWebpage.sh
This pull request fixes a remaining issue after merging #5913 and #10930 (see below).
- Remove the `.so` suffix and any trailing whitespace in the output generated by `libs.C`.  This should fix the following errors found in the log:
```
Error: file /home/sftnight/build/workspace/root-makedoc-master/rootspi/rdoc/master_TMP/html/libRMVA.so __coll__graph.svg not found.
```
- Remove dead code in `libs.C`.
> [Doxygen,skipci] `modifyClassWebpage.sh`: remove trailing whitespace after library name

- tutorials/roostats/IntervalExamples.py
- tutorials/roostats/rs401c_FeldmanCousins.py
- tutorials/roostats/rs_numbercountingutils.py
Add rs401c_FeldmanCousins.py, IntervalExamples.py, rs_numbercountingutils.py
This PR is a partial fix for #8758
> [RF] Convert three RooStats tutorials to Python

- tree/dataframe/test/dataframe_datasetspec.cxx
`RDatasetSpec({{"tree"s}, {"specTestFile0.root"s}})` was calling the first ctor on unix systems and was failing on windows. Neither behaviour was desired.
The modified `RDatasetSpec({{"tree"s, "specTestFile0.root"s}})` always invokes the third ctor as requested.
> [DF] Fix the broken RDatasetSpec test

- tutorials/roofit/rf212_plottingInRanges_blinding.C
- tutorials/roofit/rf212_plottingInRanges_blinding.py
Sone changes are made to both the Python and C++ version of the
`rf212_plottingInRanges_blinding` tutorial:
* move around the `-----` that denote section headers to fix the
notebook formatting
* rename `exp` to `expo` to avoid an ambiguity error because of
`std::expr` in C++ tutorial notebook
* use `std::unique_ptr` to avoid leaking of datasets
In particular, the call to `fitTo` includes now the
`Range("left,right")` command argument. Otherthise, the fit would also
try to make the model adapt to the empty bins in the blinded region,
giving a wrong fit result (it can be easily seen that the fit was wrong
before by increasing the number of events in the toy dataset to 100k).
To avoid that the plotting takes the (now correct) fit range as
`NormRange()` and we can't show what happens if the …
> [RF] Fix wrong fit and improve rf212_plottingInRanges_blinding tutorial

- tree/dataframe/test/dataframe_datasetspec.cxx
The guard R__USE_IMT was wrongly put around the class declaration, hence
none of the tests inside RDatasetSpecTest would compile if R__USE_IMT is
not defined.
> [DF] Remove the extra R__USE_IMT fixture in the RDatasetSpec tests

- core/base/src/TTimeStamp.cxx
- core/base/src/TUri.cxx
- core/base/src/TUrl.cxx
- core/thread/src/TThread.cxx
This is to suppress the warnings we see now in the nightlies on the
macbeta nodes:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=macbeta,SPEC=cxx17,V=master/lastBuild/parsed_console/
> [core] Replace `sprintnf` calls with `snprintf` in ROOT core

- roofit/roofitcore/inc/RooConvGenContext.h
- roofit/roofitcore/src/RooConvGenContext.cxx
The RooConvGenContext code is modernized to use `std::unique_ptr`
instead of manual memory allocation.
In two cases, this also fixes memory leaks where the `RooArgSet * `
returned by `getParameters` was not deleted.
> [RF] Avoid manual memory allocation in RooConvGenContext

- interpreter/cling/.github/workflows/ci.yml
- interpreter/cling/.travis.yml
- interpreter/cling/tools/packaging/cpt.py
This PR fixes issue in list #406 (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Fixed argument nomenclature [skip-ci]

- tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
This Pull request extends `RPageSink::RPageSinkDaos` to implement `RPageSinkDaos::CommitSealedPageVImpl()`, of signature: 
```c++
vector<RNTupleLocator> RPageSinkDaos::CommitSealedPageVImpl(span<RPageStorage::RSealedPageGroup> ranges)
```
, which is virtually declared in the parent class `RPageSink` since PR #10775. 
The implemented method modifies the default behavior for committing page ranges, i.e. calling `::CommitSealedPage` repeatedly for each individual page. 
Instead, it coalesces the buffered page ranges - e.g. all pages in a column or cluster - into a batch of vector writes, enabling I/O parallelization after recent optimizations to the `RDaos` library. 
As with the batched fetching case in `RPageSourceDaos::LoadClusters()`, the page write requests are aggregated by the pair …
> [ntuple,daos] Parallelizable page vector writes

- interpreter/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp
This patch was developed as part of an llvm upgrade in 2015. This patch is not needed anymore considering that the LLVM JIT has advanced significantly.
> Revert "Avoid dupe "llvm.ident" operands."

- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooRealIntegral.cxx
In the `RooRealIntegral` constructor, there was a `O(N^2)` operation on
the computation graph, checking the dependency of the top-level function
on each other node. This is very expensive in the numer of RooAbsArgs N
is large. Instead of calling `dependsOnValue` for each leaf node, which is
very expensive because it's a recursive function, the value server
leaves are all put in a RooArgSet before the leaf iteration to check
quickly if a leaf is also a value server.
This change speeds up the `createNLL` step of large models like the
ATLAS Higgs combination by at least a factor of two or three.
In the same PR, I also bring a little other commit, where the ownership of the `cloneSet` in `cloneTree` is released before removing the top node element, in order to avoid ownership ambiguities.
> [RF] Speed up integral creation for large computation graphs

- roofit/roofit/src/RooKeysPdf.cxx
- roofit/roofit/test/CMakeLists.txt
- roofit/roofit/test/testRooKeysPdf.cxx
So far, a `RooKeysPdf` produced wrong kernel estimations for weighted
datasets, as sometimes the number of entries was used in place of the
sum of weights. This is fixed now. Also, the normalization by the sum of
weights is moved from the private `RooKeysPdf::g()` function that is
called for each event to the global normalization constant.
A new unit test that checks if weighted datasets are correctly handled
by both the RooKeysPdf and the RooNDKeysPdf is also implemented.
> [RF] Support weighted datasets in RooKeysPdf

- interpreter/cling/tools/packaging/cpt.py
This PR fixes issue mentioned in #406 (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Added new dependent arguments [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] Fixed invalid escape characters to get rid of W605 error. [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] Added indentation for visual indent to get rid of E128 error code. [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
This PR fixes issue in meta-issue list #406 (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Added skip-cleanup flags for check-requirements and create-dev-env [skip-ci]

- tutorials/eve/histobrowser.C
- tutorials/fft/FFT.C
- tutorials/fit/fitLinear.C
- tutorials/fit/langaus.C
- tutorials/fit/vectorizedFit.C
Fix improper display of vectorizedFit documentation/tutorial.
The header was badly formatted (everything on one line) which resulted in only part it being displayed.
This can be seen here (https://root.cern/doc/master/vectorizedFit_8C.html) where only `use it for fitting an histogram` is displayed instead of the complete sentence: `tutorial for creating a Vectorized TF1 function using a formula expression and use it for fitting an histogram`
Also, fixed some typos.
> Fix typos in tutorials

- tmva/tmvagui/src/BDT.cxx
- tmva/tmvagui/src/BDTControlPlots.cxx
- tmva/tmvagui/src/BDT_Reg.cxx
- tmva/tmvagui/src/BoostControlPlots.cxx
- tmva/tmvagui/src/likelihoodrefs.cxx
- tmva/tmvagui/src/probas.cxx
- tmva/tmvagui/src/rulevisCorr.cxx
- tmva/tmvagui/src/rulevisHists.cxx
This is to suppress the warnings we see now in the nightlies on the
macbeta nodes:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=macbeta,SPEC=cxx17,V=master/lastBuild/parsed_console/
> [TMVA] Replace `sprintnf` calls with `snprintf` in TMVA

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/src/NormalizationHelpers.cxx
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooCustomizer.cxx
- tutorials/roofit/rf212_plottingInRanges_blinding.C
- tutorials/roofit/rf212_plottingInRanges_blinding.py
So far, one had to remove string attributes of a RooAbsArg with the
`RooAbsArg::removeStringAttribute(const char* key, const char* value)`
method, passing `nullptr` as a value. Passing a `nullptr` to a function
that takes a `const char*` is not supported in PyROOT, as explained in
GitHub issue #10954. Therefore, a new function is added to RooAbsArg to
remove a string attribute without having to use `nullptr`.
This new function called `removeStringAttribute()` is now used in all
the ROOT code to remove string attributes from RooAbsArgs, and also
mentioned in the warnings that tell the user that they might want to
remove the `fitrange` attribute.
The verb `remove` was chosen instead of `delete`, `clear`, or `erase`,
because there was already a `RooAbsArg::removeServer()` method.
> [RF] New `RooAbsArg::removeStringAttribute(const char* key)` method

- roofit/histfactory/src/ParamHistFunc.cxx
Last year, with commit 3657e7c, the parameter index calculation was
changed to be on the fly instead of using a look-up map, which is much
faster.
However, the implemented formula was not correct for two or three
dimensions, which is fixed by this commit.
To make sure that the index computation is correct this time, the new
code was tested in this code snippet with various inputs:
```C++
void runTest(int nx = 42, int ny = 42, int nz = 42) {
const int nxy = nx * ny;
const int nyz = ny * nz;
for (int i = 0; i < nx; ++i) {
for (int j = 0; j < ny; ++j) {
for (int k = 0; k < nz; ++k) {
const int index = k + j * nz + i * ny * nz;
const int gammaIndex = i + j * nx + k * nx * ny;
const int i2 = index / nyz;
const int tmp = index % nyz;
const int j2 = tmp / nz;
const int k2 = tmp % nz;
const int …
```
> [RF] Fixup to parameter index calculation in ParamHistFunc

- graf2d/graf/src/TCandle.cxx
- gui/gui/src/TGFont.cxx
- gui/guihtml/src/TGHtmlDraw.cxx
- io/xml/src/TBufferXML.cxx
- io/xml/src/TXMLEngine.cxx
- io/xml/src/TXMLFile.cxx
- math/minuit/src/TMinuit.cxx
- test/guitest.cxx
- test/stressGraphics.cxx
- test/stressRooFit.cxx
This is to suppress the warnings we see now in the nightlies on the
macbeta nodes:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=macbeta,SPEC=cxx17,V=master/lastBuild/parsed_console/
After this PR, there will only be a final PR necessacy to fix these
warnings in TMVA.
> Replace `sprintnf` calls with `snprintf` in multiple packages

- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/test/testRooAddPdf.cxx
When the normalization range for coefficient determination of a
RooAddPdf is changed, the AddPdf's projection cache needs to be reset,
just like it is already done in `RooAddPdf::fixCoefNormalization`.
Otherwise, there will be problems in the pdf evaluation and integration
because the projection cache is invalid.
A unit test based on the GitHub issue that reported this problem is also
implemented.
Closes https://github.com/root-project/root/issues/10988.
Furthermore, another potential RooAddPdf problem is fixed, where several instances of RooRecursiveFraction were created with the same name (which could become problematic for example when using the new BatchMode).
> [RF] Fix RooAddPdf::fixCoefRange cache issue with createIntegral

- tmva/tmva/src/DataSetInfo.cxx
Precondition. On the **training (classification)** stage user adds array of variables to the `TMVA::DataLoader` object with a new method introduced in ROOT 6.20:
```
TMVA::DataLoader *loader = new TMVA::DataLoader(...)
loader->AddVariablesArray("vars", nBins);
```
On the next stage - **classification application** user creates `TMVA::Reader` object and adds an array of variables to it:
```
TMVA::Reader* reader = new TMVA::Reader(...);
std::vector<float> fValues(nBins);
reader->DataInfo().AddVariablesArray("vars", nBins, "", "", 0, 0, 'F', kFALSE, &fValues[0]);
```
Pointer to the first element of the `&fValues[0]` passed to the `TMVA::DataSetInfo::AddVariablesArray(..., void *external)` function. Inside `AddVariablesArray()` pointer is **not incremented** in the loop where variables are …
> TMVA::DataSetInfo incorrectly handles reading of array of variables

- hist/hist/src/THStack.cxx
THStack fHistogram line width should be 0 as suggested here: https://root-forum.cern.ch/t/continuing-the-discussion-from-an-unwanted-horizontal-line-is-drawn-at-y-0/50877/17
> THStack histogram line width should be 0

- roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
- roofit/RDataFrameHelpers/test/testActionHelpers.cxx
The RDataFrameHelper should be consistent with creating a RooDataSet
from a TTree, meaning out-of-range events should be skipped. This is
implemented in this commit, borrowing the logic from
`RooTreeDataStore::loadValues()`. A unit test is also implemented.
The previous logic of just taking just all values to fill the dataset
was very dangerous, because these values then clipped to the RooRealVar
limits and biased the number of events observed at the boundaries.
Closes https://github.com/root-project/root/issues/11017.
> [RF] Skip out-of-range events in RDataFrame to RooDataSet Helper

- tmva/sofie/inc/TMVA/RModel.hxx
- tmva/sofie/src/RModel.cxx
- tmva/sofie/test/EmitFromRoot.cxx
- tmva/sofie/test/TestSofieModels.cxx
Use enum as flags for RModel::Generate().
By default, SOFIE will generate a session class and store the weights in a file:
```
using namespace TMVA::Experimental::SOFIE;
RModelParser_ONNX parser;
RModel model = parser.Parse("path/to/model.onnx");
model.Generate();
```
Here's how the options can be used to :
- not use the session class
```
model.Generate(Options::kNoSession);
```
- not save the weights in a file
```
model.Generate(Options::kNoWeightFile);
```
- not use both
```
model.Generate(Options::kNoSession | Options::kNoWeightFile);
```
- [] updated the docs (if necessary)
> [TMVA][SOFIE] Use enum for options.

- tutorials/roostats/FourBinInstructional.py
- tutorials/roostats/MultivariateGaussianTest.C
- tutorials/roostats/MultivariateGaussianTest.py
- tutorials/roostats/Zbi_Zgamma.C
- tutorials/roostats/Zbi_Zgamma.py
- tutorials/roostats/rs601_HLFactoryexample.py
- tutorials/roostats/rs701_BayesianCalculator.C
- tutorials/roostats/rs701_BayesianCalculator.py
- tutorials/roostats/rs_bernsteinCorrection.C
- tutorials/roostats/rs_bernsteinCorrection.py
These new tutorial translations are added:
* tutorials/roostats/FourBinInstructional.py
* tutorials/roostats/MultivariateGaussianTest.py
* tutorials/roostats/Zbi_Zgamma.py
* tutorials/roostats/rs601_HLFactoryexample.py
* tutorials/roostats/rs701_BayesianCalculator.py
* tutorials/roostats/rs_bernsteinCorrection.py
This PR is a partial fix for #8758
> [RF] Convert RooStats tutorials to Python 

- math/mathcore/inc/TMath.h
- math/mathcore/src/TMath.cxx
- math/mathcore/test/testTMath.cxx
- tutorials/math/BreitWigner.C
Implemented relativistic version of breit wigner (non-relativistic case already exists in TMath).
Define BreitWignerRelativistic(Double_t x, Double_t median=0, Double_t gamma=1) in TMath.h and then calculate in TMath.cxx, a similar non relativistic function BreitWigner already exists in the same location which was used as a template. A tutorial BreitWigner.C has been added in tutorials/math which produces plots comparing the non relativistic and relativistic case.
The output plot from tutorials/math/BreitWigner.C which produces a plot using the BreitWignerRelativistic function which is added in this pull request is [here](https://cernbox.cern.ch/index.php/s/JreHs4sOPzLiU2T)
This pull request has been discussed previously in this pull request: …
> Add Relativistic Breit Wigner Function to TMath

- roofit/roofit/inc/LinkDef1.h
- roofit/roofit/inc/RooLagrangianMorphFunc.h
- roofit/roofit/src/RooLagrangianMorphFunc.cxx
- tutorials/roofit/rf711_lagrangianmorph.C
- tutorials/roofit/rf711_lagrangianmorph.py
This PR enables the streaming of the RooLagrangianMorph by creating dictionaries also for `RooLagrangianMorph::Config`.
Furthermore, some improvements are made to the RooLagrangianMorphFunc and its tutorials in separate commits.
Tons of memory leaks are fixed in the `RooLagrangianMorphFunc` as well.
> [RF] Enable streaming of RooLagrangianMorphFunc and other improvements

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/test/dataframe_snapshot.cxx
This PR fixes https://github.com/root-project/root/issues/10920 and https://github.com/root-project/root/issues/6932 (see those for more information).
> [DF] Fix snapshot of array branch with out-of-order size branch

- tree/tree/inc/TEntryList.h
- tree/tree/inc/TEntryListFromFile.h
- tree/tree/src/TEntryList.cxx
- tree/tree/src/TEntryListFromFile.cxx
Change signature of methods in TEntryList and derived class that expect
an entry index. Usually this is stored as Long64_t, but in `GetEntry`
and `GetEntryAndTree` methods this was passed as `Int_t` leading to
integer overflows.
Fixes https://github.com/root-project/root/issues/11026
With respect to the reproducer in the linked issue, this PR outputs the following
```
$: ./repro.o
std::numeric_limits<int>::max(): 2147483647
Total entries in chain: 2168958436
Total entries in entrylist: 2168958436
Giving input entry 2147483647
Got input index: 2147483647
Got tree index 100 and entry index 47
Giving input entry 2147483648
Got input index: 2147483648
Got tree index 100 and entry index 48
Got input index: 2147483648
With entryAfterList=2147483648 got loadResult=48
What is the entry status? …
```
> [tree] Fix integer overflow in TEntryList

- tutorials/dataframe/df002_dataModel.C
- tutorials/dataframe/df002_dataModel.py
Typos and grammar mistakes are now fixed.
> [skip-ci][DF] Fix typos and grammar mistakes in df002 tutorials

- graf2d/gpad/src/TCanvas.cxx
Clarifies ambiguous doxygen documentation of TCanvas constructor parameters concerning window vs canvas size
> [docu] Clarify window size vs canvas size

- tree/dataframe/CMakeLists.txt
- tree/dataframe/inc/ROOT/RDF/InternalUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDataFrame.hxx
- tree/dataframe/src/RDFInternalUtils.cxx
- tree/dataframe/src/RDataFrame.cxx
- tree/dataframe/src/RDatasetSpec.cxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/CMakeLists.txt
- tree/dataframe/test/dataframe_datasetspec.cxx
- tree/tree/inc/ROOT/InternalTreeUtils.hxx
- tree/tree/src/InternalTreeUtils.cxx
As an intermediate step, needed was to add interface to add a friend in RFriendInfo. The current v6-26 RDatasetSpec resides in the internal namespace.
This is needed to allow the fix for friends support in DistRDF.
> [tree] Introduce the RDatasetSpec as internal in v6-26-06

- core/zip/inc/Compression.h
- tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx
Fix typo in `CompressionSettings()` function declaration to match definition in `Compression.cxx`.  Many thanks for reporting @mnowakgit!
This typo caused the following to fail:
```
root [0] auto c = ROOT::RCompressionSetting::EAlgorithm::kZSTD;
root [1] CompressionSettings(c, 5);
input_line_10:2:3: error: no matching function for call to 'CompressionSettings'
(CompressionSettings(((*(enum ROOT::RCompressionSetting::EAlgorithm::EValues*)0x7f02285f4010)), 5))
^~~~~~~~~~~~~~~~~~~
/home/jalopezg/_build/include/Compression.h:124:5: note: candidate function not viable: no known conversion from 'enum ROOT::RCompressionSetting::EAlgorithm::EValues' to 'RCompressionSetting::EAlgorithm' for 1st argument
int CompressionSettings(RCompressionSetting::EAlgorithm algorithm, int compressionLevel);
^ …
```
> [core] Fix typo in `CompressionSettings()` declaration

- roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
- roofit/RDataFrameHelpers/test/testActionHelpers.cxx
- roofit/histfactory/src/ParamHistFunc.cxx
- roofit/roofit/inc/LinkDef1.h
- roofit/roofit/inc/RooLagrangianMorphFunc.h
- roofit/roofit/src/RooLagrangianMorphFunc.cxx
- tutorials/roofit/rf711_lagrangianmorph.C
- tutorials/roofit/rf711_lagrangianmorph.py
1. https://github.com/root-project/root/pull/9912
2. https://github.com/root-project/root/pull/10989
3. https://github.com/root-project/root/pull/11018
4. https://github.com/root-project/root/pull/11023
> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 18

- interpreter/cling/lib/Utils/Output.cpp
- roofit/roofitcore/src/BatchModeDataHelpers.cxx
- roofit/roofitcore/src/RooAbsRealLValue.cxx
This addresses a warning of recent Clang versions about the `use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]`.
> Use logical operators for boolean operands

- core/meta/src/TClass.cxx
This pull request updates the description of `TClass:CopyCollectionProxy()`, which was (sort of) misleading.  Probably the name of the member function is not descriptive either, but that's a different topic.
> [core][skip-ci] Clarify documentation of `TClass::CopyCollectionProxy()`

- interpreter/cling/tools/packaging/cpt.py
This PR fixes #406 mentioned in (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Created new extract_tar function to extract tar files [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
This PR fixes #406 mentioned in (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Added build option for the platform tags to the argument parser [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] Added indentation and spacing as well as fixing variable references [skip-ci]

- interpreter/cling/tools/packaging/cpt.py
the Build object cores instance variable will be set to the user passed number.
> [cling-cpt] Allows for user to specify the number of cores used during make [skip-ci]

- hist/histpainter/src/THistPainter.cxx
The overflow and underflows were plotted as integers.
As pointed [here](https://root-forum.cern.ch/t/format-of-numbers-in-the-underflow-overflow-table-in-2d-histograms/50967) the output might be incorrect.
> Overflows and underflows are floating points

- interpreter/cling/tools/packaging/cpt.py
This PR fixes #406 mentioned in meta issue list (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Removed 2 globals and implemented them with parameter passing [skip-ci]

- roofit/roofit/inc/RooMomentMorph.h
- roofit/roofit/inc/RooMomentMorphFunc.h
- roofit/roofit/inc/RooMomentMorphFuncND.h
- roofit/roofit/inc/RooMomentMorphND.h
- roofit/roofit/src/RooMomentMorph.cxx
- roofit/roofit/src/RooMomentMorphFunc.cxx
- roofit/roofit/src/RooMomentMorphFuncND.cxx
- roofit/roofit/src/RooMomentMorphND.cxx
In commit https://github.com/root-project/root/commit/0d1f0bbde0fda028f01b116f8e5506bc3b1a11bd, some of the legacy iterator usage in
RooMomentMorph was repaced, but not all of it. When the code branches of
the remaining usage is hit now, there will be a crash because the
iterators are uninitialized. This commit fixes that problem by not using
the iterators anymore.
Closes https://github.com/root-project/root/issues/11061.
Doesn't need any backport, because the problem only got introduced in
this development cycle.
Since this PR already touched the RooMomentMorph class, it also includes a commit with some code modernization of it.
> [RF] Fix usage of uninitialized iterators in RooMomentMorph

- tmva/pymva/src/RModelParser_Keras.cxx
- tmva/pymva/test/EmitFromKeras.cxx
- tmva/pymva/test/TestRModelParserKeras.C
- tmva/pymva/test/generateKerasModels.py
This PR adds support for parsing Convolution layers from PyTorch and Keras models into an RModel object.
> [TMVA][SOFIE] Add support for Conv Operator in Keras parser

- tmva/pymva/src/RModelParser_Keras.cxx
- tmva/pymva/test/EmitFromKeras.cxx
- tmva/pymva/test/TestRModelParserKeras.C
- tmva/pymva/test/generateKerasModels.py
This PR adds support for parsing the Keras Reshape layer in SOFIE RModel.
> [TMVA][SOFIE] Add support for Reshape layer in Keras parser

- roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
- roofit/roofit/src/Roo2DKeysPdf.cxx
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooStudyManager.cxx
- roofit/roofitcore/src/RooWorkspace.cxx
- roofit/roostats/src/HLFactory.cxx
- roofit/roostats/src/HypoTestInverter.cxx
- roofit/roostats/src/HypoTestInverterResult.cxx
In quite a few places in RooFit, TFile objects were manually allocated
but not deleted afterwards.
> [RF] Fix various memory leaks in RooFit from opened TFile objects

- hist/hist/inc/TF1.h
People know that they can use `TF1::SetParameters()` to set the
parameter values of a TF1. For example, when you have two parameters:
```C++
TF1 myexpo("myexp", "[coef] * std::exp(-[rate] * x)", 0, 10);
myexpo.SetParameters(1.0, 0.5);
```
When people get rid of all parameters except for one, they therefore
automatically assume that this will work:
```C++
TF1 myexpo("myexp", "std::exp(-[rate] * x)", 0, 10);
myexpo.SetParameters(0.5);
```
However, it doesn't work because `SetParameters` requires at least two
arguments. This commit suggests to fix that and generalize the function
to take only one parameter as well.
This reduces the surprises people have when interacting with a TF1 and
therefore improves the user experience for first-time ROOT users.
> Allow also only one parameter in `TF1::SetParameters()`

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] Used wget function to replace 3 subprocess calls and fixed up download_llvm_binary function [skip-ci]

- roofit/multiprocess/inc/RooFit/MultiProcess/Config.h
- roofit/multiprocess/src/Config.cxx
- roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
- roofit/roofitcore/src/TestStatistics/LikelihoodJob.h
- roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
- roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
- roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx
**Commit 1 (2932c2af9ce19d346807a39d990d77efd1169e09): bug fix.** When using a fractional event range smaller than an actual (integral) event, rounding to integers would cause the extended term in unbinned likelihoods in `RooUnbinnedL` to be added multiple times.
**Commit 2 (18cb82c9ef0aed0b30f08b62b3161aa3a2bc3a29): new `LikelihoodJob` mode.** `LikelihoodJob` would parallelize over events, just like the old bulk parallelization mode of `RooNLLVar` (through `RooRealMPFE`). Now it can also parallelize over components and the two modes can be mixed as well to parallelize over both, allowing the user to define an optimal splitting for their usecase.
> [RF] component-based LikelihoodJob mode

- roofit/roofitcore/inc/RooAbsRealLValue.h
- roofit/roofitcore/src/RooAbsRealLValue.cxx
Replaced `RooAbsVar::setVal` with `RooRealVar::setValFast`, which does 
not call `RooAbsRealLValue::inRange`, in `RooAbsRealLValue::setBin`.
It is possible to make this change because `setBin` gets passed a bin center, 
and thus the bin is already in range by construction. This led to a big 
improvement in speed for `setBin`.
> [RF] Speed up `RooAbsRealLValue::setBin` by removing `inRange` check

- tmva/pymva/src/RModelParser_Keras.cxx
- tmva/pymva/test/EmitFromKeras.cxx
- tmva/pymva/test/TestRModelParserKeras.C
- tmva/pymva/test/generateKerasModels.py
- tmva/sofie/inc/TMVA/ROperator_Transpose.hxx
This PR fixes the way in which the shape tensor is extracted and then copied & added as an Initialized tensor in the RModel for the Reshape layer in SOFIE Keras parser.
> [TMVA][SOFIE] Fix copying shape tensor for reshape layer in SOFIE Keras parser

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/inc/RooAbsRealLValue.h
- roofit/roofitcore/inc/RooRealVar.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooAbsRealLValue.cxx
- roofit/roofitcore/src/RooRealVar.cxx
Copy assignment for RooAbsArgs was implemented in an unexpected and
inconsistent way. While one would expect that the copy assignment is
copying the object, it said in the documentation of
`RooAbsArg::operator=` that it will "assign all boolean and string
properties of the original bject. Transient properties and client-server
links are not assigned." This contradicted with the implementation,
where the server links were actually copied too. Indeed it is
questionable that adding also the servers of the `other` RooAbsArg makes
sense when the proxies are not changed.
There was also a memory leak of the `_ownedComponents`, because
`_ownedComponents` got reset to `nullptr` without deleting the
pointed-to owned collection.
Furthermore, in `RooAbsRealLValue`, the assigment operator was …
> [RF] Disable copy assignment for RooAbsArg and derived types

- roofit/roofit/src/RooLagrangianMorphFunc.cxx
- roofit/roofitcore/inc/RooHistFunc.h
- roofit/roofitcore/inc/RooHistPdf.h
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooHistPdf.cxx
It happens often that you want to create a RooDataHist just to serve a
RooHistPdf or a RooHistFunc. In this case, it is convenient for the
HistPdf/HistFunc to take ownership of the RooDataHist.
The cleanest way to implement this is probably via additional
constructors that take the RooDataHist via `std::unique_ptr`, such that
the ownership is always clear. A new transient member of
HistPdf/HistFunc is then taking over the ownership.
With this change, it is easy to fix one of the remaining memory leaks in
the RooLagrangianMorphFunc.
I second commit in this PR applies also some general code modernization to RooHistPdf and RooHistFunc.
> [RF] New mechanism to create RooHistPdf/Func that own the RooDataHist

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] Split long lines to get rid of E501 error [skip-ci]

- cmake/modules/RootMacros.cmake
In the `rootcint` command defined in `RootMacros.cmake`, the
`COMPILE_DEFINITIONS` from the target are forwarded as compiler flags.
The `COMPILE_DEFINITIONS` are stored in the `module_defs` variable with
a generator expression:
```
set(module_defs $<TARGET_PROPERTY:${ARG_MODULE},COMPILE_DEFINITIONS>)
```
Then, the definitions are added to the rootcint command with this
expression:
```
"$<$<BOOL:${module_defs}>:-D$<JOIN:${module_defs},;-D>>"
```
This code was almost copied exactly from the CMake documentation
example:
https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html
In particular, the `BOOL` check makes sure that the if the target
property is empty, we will not get a bare `-D` with nothing after it,
corrupting the rootcint command.
However, there is no …
> [cmake] Protect against empty `COMPILE_DEFINITIONS` in rootcint command

- roofit/roofitcore/inc/RooAbsGenContext.h
- roofit/roofitcore/inc/RooAdaptiveIntegratorND.h
- roofit/roofitcore/inc/RooBinIntegrator.h
- roofit/roofitcore/inc/RooGrid.h
- roofit/roofitcore/inc/RooIntegrator1D.h
- roofit/roofitcore/inc/RooNumRunningInt.h
- roofit/roofitcore/src/BidirMMapPipe.cxx
- roofit/roofitcore/src/RooAbsGenContext.cxx
- roofit/roofitcore/src/RooAdaptiveIntegratorND.cxx
- roofit/roofitcore/src/RooBinIntegrator.cxx
- roofit/roofitcore/src/RooClassFactory.cxx
- roofit/roofitcore/src/RooFactoryWSTool.cxx
- roofit/roofitcore/src/RooGrid.cxx
- roofit/roofitcore/src/RooIntegrator1D.cxx
- roofit/roofitcore/src/RooMCIntegrator.cxx
- roofit/roofitcore/src/RooNumRunningInt.cxx
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitmore/inc/RooAdaptiveGaussKronrodIntegrator1D.h
- roofit/roofitmore/inc/RooGaussKronrodIntegrator1D.h
- roofit/roofitmore/src/RooAdaptiveGaussKronrodIntegrator1D.cxx
- roofit/roofitmore/src/RooGaussKronrodIntegrator1D.cxx
- roofit/roostats/src/MCMCInterval.cxx
- roofit/roostats/src/MarkovChain.cxx
This is part of the effort of making memory management in RooFit more
automatic and safer.
> [RF] Replace some manually-allocated C-style arrays with `std::vector`

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
Before this patch (and since a2156969b4), Snapshot was enforcing
alphabetical ordering of the output branches. The ordering
specified as argument, however, could carry meaning: it might
make sense to have branches carrying related physics information
close together in the TTree so that they appear close to each
other e.g. in TTree::Print or in TBrowser.
With this patch we keep the original column ordering (the one
explicitly specified by the user or the one coming from TTree)
when creating output branches.
One exception are branches from the input TTree that are
Redefine'd in case of auto-generated lists of output columns:
Define'd and Redefine'd columns appear before TTree branches,
which might move the position of branches that have been
Redefine'd with respect to others that have not.
> [DF] Preserve ordering of snapshotted columns

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreallvalue.py
- bindings/pyroot/pythonizations/test/roofit/roodatahist_ploton.py
- roofit/roofitcore/inc/RooPlot.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooPlot.cxx
- test/stressRooFit_tests.h
* Avoid coning of plot variable twice then plotting a `RooAbsReal`, as the new BatchMode doesn't like model cloning
* Some minor fixes in `BatchModeHelpers`
* Improving the interface of `RooAbsReal::createPlotProjection`
* Use also the different BatchMode backends in the `createNLL` calls in `stressRooFit`, extending text coverage also to (profile) likelihood scans with the new BatchMode
The likelihood scans in the tutorials are up to 10 times faster now when using the new BatchMode compared to RooFit legacy.
More detail can be found in the commit descriptions.
> [RF] Necessary changes to RooFit plotting and BatchMode to plot likelihoods that use BatchMode

- cmake/modules/RootMacros.cmake
In the `rootcint` command defined in `RootMacros.cmake`, the
`COMPILE_DEFINITIONS` from the target are forwarded as compiler flags.
The `COMPILE_DEFINITIONS` are stored in the `module_defs` variable with
a generator expression:
```
set(module_defs $<TARGET_PROPERTY:${ARG_MODULE},COMPILE_DEFINITIONS>)
```
Then, the definitions are added to the rootcint command with this
expression:
```
"$<$<BOOL:${module_defs}>:-D$<JOIN:${module_defs},;-D>>"
```
This code was almost copied exactly from the CMake documentation
example:
https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html
In particular, the `BOOL` check makes sure that the if the target
property is empty, we will not get a bare `-D` with nothing after it,
corrupting the rootcint command.
However, there is no …
> [v6-26][cmake] Protect against empty `COMPILE_DEFINITIONS` in rootcint command

- roofit/roofitcore/inc/RooWorkspace.h
- roofit/roofitcore/src/RooWorkspace.cxx
The export of RooWorkspace contents to CINT didn't work anymore since
ROOT 6, and the code associated to it should be removed to reduce
maintanance burden.
> [RF] Remove CINT export code from RooWorkspace

- roofit/roofitcore/res/RooFit/BatchModeDataHelpers.h
- roofit/roofitcore/res/RooFitDriver.h
- roofit/roofitcore/src/BatchModeDataHelpers.cxx
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/NormalizationHelpers.cxx
- roofit/roofitcore/src/RooFitDriver.cxx
The new RooFit batchMode skipped zero-weight events to optimize the
likelihood calculation. However, this should not be done in general,
because it is unexpected to users is the output of batched computations
is not aligned with the original dataset.
This commit also adds a smaller commit with a change to ensure that
norm set args are part of the graph in NormalizationHelpers, also used
in the new BatchMode.
> [RF] Don't skip zero-weight events by default in new BatchMode

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/tree/inc/ROOT/InternalTreeUtils.hxx
- tree/tree/src/InternalTreeUtils.cxx
Moves GetTopLevelBranchNames from the RDF Internals namespace to the Internal TreeUtils namespace, as it does not rely on RDF and creates unnecessary dependencies.
- Move GetTopLevelBranch names and its implementation from `/tree/dataframe` to `/tree/tree`.
This PR fixes N/A
> [tree/RDF] Move GTLBN from RDF to TreeInternalUtils

- roofit/roofitcore/CMakeLists.txt
- roofit/roofitcore/inc/RooAddGenContext.h
- roofit/roofitcore/inc/RooAddModel.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/src/RooAddGenContext.cxx
- roofit/roofitcore/src/RooAddHelpers.cxx
- roofit/roofitcore/src/RooAddHelpers.h
- roofit/roofitcore/src/RooAddModel.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
The `RooAddModel::CacheElem` was exactly the same as for the RooAddPdf.
Hence, the RooAddPdf was refactored a bit such that the code to generate
the CacheElem could be reused in the RooAddModel.
> [RF] Avoid code duplication in RooAddModel cache generation

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooAbsBinning.h
- roofit/roofitcore/inc/RooBinning.h
- roofit/roofitcore/inc/RooLinTransBinning.h
- roofit/roofitcore/inc/RooParamBinning.h
- roofit/roofitcore/inc/RooRangeBinning.h
- roofit/roofitcore/inc/RooUniformBinning.h
- roofit/roofitcore/src/RooAbsBinning.cxx
- roofit/roofitcore/src/RooBinning.cxx
- roofit/roofitcore/src/RooLinTransBinning.cxx
- roofit/roofitcore/src/RooParamBinning.cxx
- roofit/roofitcore/src/RooUniformBinning.cxx
The `RooAbsBinning` interface for bin index lookups was changed to
enable vectorized implementations. Instead of having the override
`RooAbsBinning::binNumber()`, the binning implementations now have to
override the `RooAbsBinning::binNumbers()` function to evaluate the bin
indices of multiple values in one function call.
The interface of `RooAbsBinning::binNumbers()` is designed to facilitate
the accregation of bin indices over multiple dimensions, and it uses a
`double` ouput vector such that the caller can reuse the output buffer
for other computations.
The former `RooAbsBinning::binNumber()` method is now implement in terms
of the vectorized version, such that we automatically get wide test
coverage. It was verified that this doesn't come with a performance
overhead.
This will greatly …
> [RF] Vectorize `RooAbsBinning` interface for bin index lookups

- math/vecops/inc/ROOT/RVec.hxx
The file uses `std::numeric_limits`, defined in `<limits>` . That header is transitively included in most configurations, but for example not when building with a recent libstdc++ (with less transitive includes) and configuring with cxx14 and without VDT.
> [VecOps] Add missing #include <limits> to RVec.hxx

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
This fixes the following compilation errors on Windows:
```
C:\Users\bellenot\git\master\tree\dataframe\inc\ROOT/RDF/RInterface.hxx(1123,64): error C2039: 'TreeUtils': is not a member of 'ROOT::RDF::Internal' [C:\Users\bellenot\build\x86\release\tree\dataframe\test\datasource_sqlite.vcxproj]
C:\Users\bellenot\git\master\tree\dataframe\inc\ROOT/RSqliteDS.hxx(27): message : see declaration of 'ROOT::RDF::Internal' [C:\Users\bellenot\build\x86\release\tree\dataframe\test\datasource_sqlite.vcxproj]
C:\Users\bellenot\git\master\tree\dataframe\inc\ROOT/RDF/RInterface.hxx(1120): message : while compiling class template member function 'ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::RDF::RInterface<Proxied,DataSource>::RLoopManager,void>> …
```
> Add a couple of missing "ROOT::" namespaces

- math/vecops/inc/ROOT/RVec.hxx
The file uses `std::numeric_limits`, defined in `<limits>`. That header is transitively included in most configurations, but for example not when building with a recent libstdc++ (with less transitive includes) and configuring with cxx14 and without VDT.
(cherry picked from commit d2e56f982e303d83784f28e1524bc24c39b350c4)
Backport of PR https://github.com/root-project/root/pull/11152
> [VecOps] Add missing #include <limits> to RVec.hxx [v6.26]

- roofit/roofitcore/src/RooPolyFunc.cxx
Soon-to-be-released Clang 15 will complain:
```
warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
```
> [RF] Qualify calls to std::move in RooPolyFunc

- roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h
- roofit/histfactory/src/ParamHistFunc.cxx
- roofit/histfactory/test/CMakeLists.txt
- roofit/histfactory/test/testParamHistFunc.cxx
So far, the `ParamHistFunc` BatchMode implementation was still
sub-uptimal because it used the non-vectorized interface of the
RooDataHist.
Using the new `RooAbsBinning::binNumbers()` function too look up
multiple bin indices at once, the implementaiton can be improved and
sped.
In the three-dimensional many-bin case, the new implementation is a bit
more than three times faster than the old one. This should benefit
HistFactory fits with many bins.
A new `testParamHistFunc` unit test was also introduced to validate the
results of a ParamHistFunc both with and without the batch mode,
comparing to manually computed reference results.
> [RF] Better ParamHistFunc::computeBatch with RooAbsBinning::binNumbers

- roofit/roofitcore/inc/RooAbsRealLValue.h
- roofit/roofitcore/src/RooAbsRealLValue.cxx
- roofit/roofitcore/test/testRooWrapperPdf.cxx
Integrating a RooAbsRealLValue like a RooRealVar doesn't work in RooFit,
which one can check with this code:
```C++
RooRealVar x{"x", "x", 2.0, -5.0, 5.0};
std::unique_ptr<RooAbsReal> xint{x.createIntegral(x)};
xint->Print();
```
The integral of x from -5 to 5 should be zero, but the integral object
only returns the current value of the variable.
Some users expect the integral to work, and give the same result as
this, which correctly prints out zero:
```C++
RooRealVar x{"x", "x", 2.0, -5.0, 5.0};
RooProduct xId{"xId", "xId", RooArgList{x}};
std::unique_ptr<RooAbsReal> xint{xId.createIntegral(x)};
xint->Print();
```
This is assumed in two RooFit unit tests:
* [testRooWrapperPdf](https://github.com/root-project/root/blob/master/roofit/roofitcore/test/testRooWrapperPdf.cxx#L27)
* …
> [RF] Explicitly forbid integration of a `RooAbsRealLValue`

- core/clib/src/Demangle.c
- core/clib/src/attach.c
- core/clib/src/detach.c
- core/clib/src/keys.c
- core/clib/src/mcalloc.c
- core/clib/src/mfree.c
- core/clib/src/mmalloc.c
- core/clib/src/mmapsup.c
- core/clib/src/mmcheck.c
- core/clib/src/mmemalign.c
- core/clib/src/mmstats.c
- core/clib/src/mrealloc.c
- core/clib/src/mvalloc.c
Soon-to-be-released Clang 15 complains:
```
a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
```
> core/clib: Remove K&R function definitions

- build/rmkdepend/cppsetup.c
- build/rmkdepend/def.h
- build/rmkdepend/ifparser.c
- build/rmkdepend/ifparser.h
- build/rmkdepend/include.c
- build/rmkdepend/main.c
- build/rmkdepend/parse.c
- build/rmkdepend/pr.c
Soon-to-be-released Clang 15 complains:
```
a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
```
and
```
passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
```
> rmkdepend: Remove K&R function definitions and add arguments to function pointer types

- graf2d/x11/src/gifencode.c
- graf3d/x3d/src/x3d.c
Soon-to-be-released Clang 15 complains:
```
a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
```
> graf2d/x11, graf3d/x3d: Remove K&R function definitions

- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/inc/RooAddModel.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/src/RooAddHelpers.cxx
- roofit/roofitcore/src/RooAddHelpers.h
- roofit/roofitcore/src/RooAddModel.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
This PR applies several improvements to the RooAddPdf class:
1. Avoid code duplication of `updateCoefficients()` with RooAddModel
2. Reduce footprint of cache object by using `std::vector` and avoid creating dummy RooRealVars
3. Avoid redundant computation of raw coefficient values in BatchMode, which fixes performance problems in important fits like the ATLAS Higgs combination
More details can be found in the commit descriptions.
> [RF] Multiple RooAddPdf improvements that also speed up the evaluation in BatchMode

- roofit/roofit/inc/RooNonCPEigenDecay.h
- roofit/roofit/src/RooNonCPEigenDecay.cxx
- roofit/roofitcore/inc/RooArgProxy.h
- roofit/roofitcore/inc/RooRealIntegral.h
- roofit/roofitcore/src/RooRealIntegral.cxx
In pass through mode, the RooRealIntegral should have registered the
function as a value server, because we directly depend on its value.
It's important to do this correctly, because the new BatchMode uses the
value server interface to analyze the computation graph.
Furthermore, it is now ensured that in pass-through mode, no servers are
registered other than the actual function and the additional factorized
observables.
There are also some other commits to ensure no invalid proxies are created
via copy/move assignment and construction.
Final commit in this PR does some code modernization of the RooRealIntegral.
> [RF] Make RooRealIntegral conform with the client-server interface

- tree/dataframe/test/dataframe_snapshot.cxx
`NeverWrittenOut.root` is actually written out (because the exception
is thrown during the event loop).
Change the file name so that it's deleted at the end of the test.
> [DF] Better name for test file

- math/vecops/inc/ROOT/RVec.hxx
- math/vecops/test/vecops_rvec.cxx
Before this PR, the lambda passed to VecOps::Map could not
take arguments by non-const reference as the implementation was
adding a const qualifier to the RVec arguments.
We now instead forward RVecs from Map to MapImpl keeping their
cv qualifiers.
A test has been added.
> [VecOps] Do not enforce const-ness in Map function parameters

- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/inc/RooHistPdf.h
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooHistPdf.cxx
This PR improves the speed for evaluating weights in `RooHistPdf`
and `RooHistFunc` for one dimensional histograms with no interpolation.
In the future, `RooDataHist::weights()` can be extended to cover
cases with higher dimensions and interpolation.
The function `RooDataHist::weights()` was implemented to enable
vectorized evaluations of bin weights. In `RooHistPdf` it is implemented
using the new function `RooHistPdf::computeBatch()`, which calls
`RooDataHist::weights()` in the case of no interpolation and 1D
histograms, and `RooAbsReal::computeBatch()` otherwise. In
`RooHistFunc::computeBatch`, `RooDataHist::weights()` is called in the
case of no interpolation and 1D histograms and is unchanged in the other cases.
To calculate the weight, bin indices are stored as a vector
using …
> [RF] Vectorize weight evaluation with ```RooDataHist::weights()```

- io/io/src/TGenCollectionStreamer.cxx
Current `clang-16` from main complains: "case value is not a constant expression". Even if that error is probably relaxed before Clang 16 is released early next year, there is really no point in converting an integer into an enum just to get a numeric value back.
This is (intentionally) a partial revert of commit https://github.com/root-project/root/commit/ac36d879629fd67cf6fc9e955923ec9f98a2361c. An alternative solution appears to be replacing `EProperty` (which refers
to the enum type in `TVirtualCollectionProxy`) with `::EProperty` from `TDictionary.h`. However, since the enum values are used as a bit mask and `fCase` is defined as `UInt_t` anyhow, it makes more sense to compare integer constants from the start.
This PR fixes #11128
> [io] Make case values constant expressions

- io/io/src/TGenCollectionStreamer.cxx
Current `clang-16` from main complains: "case value is not a constant expression". Even if that error is probably relaxed before Clang 16 is released early next year, there is really no point in converting an integer into an enum just to get a numeric value back.
This is (intentionally) a partial revert of commit ac36d879629f. An alternative solution appears to be replacing `EProperty` (which refers to the enum type in `TVirtualCollectionProxy`) with `::EProperty` from `TDictionary.h`. However, since the enum values are used as a bit mask and `fCase` is defined as `UInt_t` anyhow, it makes more sense to compare integer constants from the start.
Closes #11128
(cherry picked from commit cc28da57f0b8e2878a2c047504a49762d7d8dfb5)
Backport of PR https://github.com/root-project/root/pull/11148
> [io] Make case values constant expressions [v6.26]

- interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
The overload taking a path opens the file and then `mmap` its contents. This can cause bus errors when another process truncates the file while we are trying to read it. Instead just read the first 128 bytes, which should be enough for `identify_magic` to do its work.
> [cling] Try to avoid crashes in llvm::identify_magic

- core/newdelete/src/NewDelete.cxx
By leveraging std::max_align_t, insure that the return addressed (offset-ed
compared to the address allocated by TStorage::ObjectAlloc) is still well
aligned.
In https://root-forum.cern.ch/t/libnew-so-and-tcanvas/51039/8, executing
in rootn.exe:
TMapFile *mf=TMapFile::Create("test.map","recreate")
TH1 *h=new TH1F("test","test",100,-5,5)
h->Fill (0)
h->Draw()
led to a segmentation fault in
during the execution of:
=> 0x00007ffff2a62a12 <+162>:	movaps %xmm0,0x10(%r12)
with an address that was ending in '8'.  When allocating
the TMethodCall, the address returned was aligned on a 16 bit
boundary but the memory counting over-allocating was shifting
the address by 'only' 8 bits, leading to a mis-aligned access
by this vector memcpy.
> [libNewDelete] Over-align the allocation.

- interpreter/cling/tools/packaging/cpt.py
This PR fixes #406 mentioned in (https://github.com/root-project/cling/issues/406)
> [cling-cpt] Made a new build option for last-stable and current-dev [skip-ci]

- math/minuit2/inc/Minuit2/FunctionMinimum.h
Minuit2's MnHesse sometimes returns success, but the matrix contains only NaN values (this should be fixed, but that is a bigger issue not addressed here).
In this case, IsAboveMaxEdm() returns false, since NaN < threshold is false, irregardless of the threshold. This leads to Minuit2 wrongly reporting that the minimum is "valid".
This fix makes sure that IsAboveMaxEdm() returns true if the Edm value is NaN and the fit is reported as **invalid**, which is not perfect but better than the current confusing behavior.
> Make IsAboveMaxEdm() return true if Edm is NaN

- roofit/histfactory/inc/RooStats/HistFactory/RooBarlowBeestonLL.h
- roofit/histfactory/src/RooBarlowBeestonLL.cxx
- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/inc/RooFFTConvPdf.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooDerivative.cxx
- roofit/roofitcore/src/RooFFTConvPdf.cxx
- roofit/roofitcore/src/RooFormulaVar.cxx
- roofit/roofitcore/src/RooGenericPdf.cxx
- roofit/roofitcore/src/RooNumConvolution.cxx
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/src/RooProfileLL.cxx
- roofit/roofitcore/src/RooProjectedPdf.cxx
- roofit/roofitcore/src/RooRealIntegral.cxx
- roofit/roofitcore/src/RooResolutionModel.cxx
- test/stressRooFit_tests.h
If one overloads `RooAbsArg::redirectServersHook()`, one also needs to
call the `redirectServersHook()` of the base class. Otherwise, important
things that must be done when redirecting the servers of a `RooAbsReal`
or `RooAbsPdf` for example are not done.
In particular, this fixes some ASAN build test failures where the
`RooAbsPdf::_normSet` member was not reset when redirecting servers
because `RooAbsPdf::redirectServersHook()` was not called.
A second, minor commit in this PR cleans the includes in `stressRooFit_tests.h`.
> [RF] Don't forget to call `redirectServersHook()` of the base class 

- graf3d/gl/inc/TGLUtil.h
- graf3d/gl/src/TGLUtil.cxx
Use as:
```
TGLUtil::SetSimpleAxisWidthScale(4)
TGLUtil::SetSimpleAxisBBoxScale(1.1)
```
Requested by Rene.
> [GL] Add scaling factors for width and bounding-box size used when drawing simple axes in TGLViewer

- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
In RooAbsPdf, the following check is done to check if the normalization
set has changed:
```C++
RooFit::getUniqueId(nset) != RooFit::getUniqueId(_normSet)
```
This works, but like the previous pointer comparison it still gives
false results if the `_normSet` was replaced buy another RooArgSet at
the same memory location. The problem can be reproduced with this code:
```C++
// Create observables
RooRealVar x("x", "x", -5, 5);
RooRealVar y("y", "y", -5, 5);
// Create signal pdf gauss(x)*gauss(y)
RooGaussian gx("gx", "gx", x, RooConst(0), RooConst(1));
RooGaussian gy("gy", "gy", y, RooConst(0), RooConst(1));
RooProdPdf sig("sig", "sig", {gx, gy});
// Create composite pdf
RooAddPdf model("model", "model", RooArgList(sig), RooConst(100.));
// The results of the last two …
```
> [RF] New mechanism to detect if `_normSet` in RooAbsPdf is invalid

- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooRealIntegral.cxx
In the RooRealIntegral constructor a integrand function.getVal() is called probably to initialise the cache. 
The intention is to remove this, and for the time being keep only if the normalisation set is defined.
> [RF] Remove evaluation of pdf in RooRealIntegral constructor if the normalisation set is not defined

- hist/hist/inc/TH1.h
- hist/hist/inc/TH2.h
- hist/hist/inc/TH3.h
- hist/hist/src/TAxis.cxx
- hist/hist/src/TEfficiency.cxx
- hist/hist/src/TF1.cxx
- hist/hist/src/TF12.cxx
- hist/hist/src/TF1Convolution.cxx
- hist/hist/src/TF1NormSum.cxx
- hist/hist/src/TF2.cxx
- hist/hist/src/TF3.cxx
- hist/hist/src/TFormula.cxx
- hist/hist/src/TFormula_v5.cxx
- hist/hist/src/TH1.cxx
- hist/hist/src/TH2.cxx
- hist/hist/src/TH3.cxx
- hist/hist/src/TPolyMarker.cxx
- hist/hist/src/TProfile.cxx
- hist/hist/src/TProfile2D.cxx
- hist/hist/src/TProfile3D.cxx
This is virtual method and can be overriden in derived classes.
Therefore when such method used in copy constructor or assignment
operator, one have to explicitly specify class which used.
Fixes #10919
> Properly use `Copy(TObject &)` methods in `hist` classes

- core/base/src/TROOT.cxx
- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- gui/webdisplay/src/RWebDisplayArgs.cxx
- gui/webdisplay/src/RWebWindowsManager.cxx
When specified `root --web=default` or `root --web=browser`, default web browser will be used to open web widgets
web display can be configured with `WebGui.Display` rootrc parameter or `ROOT_WEBDISPLAY` environment variable.
Improve webgui documentation
> [webgui] let configure default browser to used with web widgets

- roofit/roofitcore/inc/RooCmdConfig.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooCmdConfig.cxx
- roofit/roofitcore/src/RooMCStudy.cxx
When plotting the single curves in `RooAbsReal::plotOnWithErrorBand()`,
the `"FillColor"` command should be removed because it has no effect on
plotting single curves and would cause warnings, as can be seen when
running the `rf610_visualerror` tutorial.
Closes https://github.com/root-project/root/issues/9859.
This PR includes two other tangentially related commits for general code improvement.
> [RF] Remove FillColor command for single curves in error band plots

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/GraphNode.hxx
- tree/dataframe/src/RDFGraphUtils.cxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_datasetspec.cxx
- tree/dataframe/test/dataframe_helpers.cxx
- tree/dataframe/test/dataframe_vary.cxx
HTML cannot recognize some special symbols, which are valid tree/chain/action names. Hence SaveGraph now does not put labels in HTML, but instead uses strings.
Fix #11173
> [DF] Use strings instead of html in SaveGraph labels

- core/winnt/src/TWinNTSystem.cxx
Fix potential crash when quitting ROOT from RBrowser on Windows and simplify the code used to close the TBrowser main Window
> [skip-ci] Fix potential crash with RBrowser on Windows

- core/winnt/src/TWinNTSystem.cxx
Fix potential crash when quitting ROOT from RBrowser on Windows and simplify the code used to close the TBrowser main Window
> [v6-26] [skip-ci] Fix potential crash with RBrowser on Windows

- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/inc/RooHistPdf.h
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooHistPdf.cxx
- roofit/roofitcore/test/testRooDataHist.cxx
With the function `RooDataHist::interpolateLinear` it is now possible to use
`RooDataHist::weights()` (implemented in https://github.com/root-project/root/pull/11171) to evaluate weights for one
dimensional histograms with up to first order interpolation.
`RooDataHist::interpolateLinear` finds the coefficients of a straight line
between two neighboring bin centers by solving a system of two linear
equations. With the coefficients of the straight line, the interpolated weight
for an event between two bin centers can be calculated.
If an event in a bin is to the left of the bin center coordinates, the
corresponding weight is found by interpolating between the current bin and the
neighboring bin to the left. If the event is to the right of the bin center,
the weight is found by …
> [RF] Enable vectorized first order interpolation for weight evaluation

- cmake/modules/SearchInstalledSoftware.cmake
- graf3d/eve7/inc/ROOT/REveElement.hxx
Version 3.11 of `nlohmann/json` introduced "versioned, ABI-tagged inline namespace"s, which breaks our forward declaration. Fortunately, we can assume the `json_fwd.hpp` header to be present starting from that same version because the `JSON_MultipleHeaders` option now defaults to `ON` and even if not, `json_fwd.hpp` is installed since patch version 3.11.2. For
earlier versions, both methods work but `json_fwd.hpp` isn't guaranteed to be installed. Still use it if available.
Fixes https://github.com/root-project/root/issues/11130
> [eve7] Include json_fwd.hpp if available

- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- gui/webdisplay/inc/ROOT/RWebWindow.hxx
- gui/webdisplay/src/RWebDisplayArgs.cxx
- gui/webdisplay/src/RWebDisplayHandle.cxx
- gui/webdisplay/src/RWebWindow.cxx
- gui/webdisplay/src/RWebWindowsManager.cxx
If specified, enforce unique key every time client connect to
web window. Once key used, it is not possible to use it again for reconnect.
If one wants to connect to window again, one should
call RWebWindow::Show() method again.
Now parameter is off, but once tested - will be enabled by default.
This should significantly increase security for web applications.
Fix problem with random seed for key generation  
Add warning when browser on remote node is started - by checking DISPLAY variable
> [webgui] introduce `WebGui.OnetimeKey` rootrc parameter

- cmake/modules/SearchInstalledSoftware.cmake
- graf3d/eve7/inc/ROOT/REveElement.hxx
Fixes https://github.com/root-project/root/issues/11130
Backport of https://github.com/root-project/root/pull/11205
> [eve7] Include json_fwd.hpp if available [v6.26]

- cmake/modules/RootMacros.cmake
- cmake/modules/RootTestDriver.cmake
Some Python tests define `PRE_` and `POST_CMD`; they should not get the ASan runtime preloaded. Invent a new `CMD_ENV` that supports exactly one environment variable that is applied to `CMD`. This fixes another 16 test failures.
> [asan] Only preload ASan runtime for CMD

- core/meta/inc/TClass.h
Given
```cpp
// tree_with_pair.cpp
void tree_with_pair() {
TTree t("t", "t");
auto x = std::make_pair(42, 84);
//t.Branch("topbranch", &x, "a/I:b/I")
t.Branch("topbranch", &x);
t.Fill();
t.Scan();
}
```
, without this patch the output is:
```
Error in <HandleInterpreterException>: Trying to dereference null pointer or trying to call routine taking non-null arguments
Execution of your code was aborted.
In module 'Core':
/home/blue/ROOT/dev/cmake-build-foo/include/TClass.h:635:38: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
size_t hint_offset = ((char*)&(p->second)) - (char*)p;
^
```
with this patch:
```
Processing tree_with_pair.cpp...
************************************
*    Row   * topbranch * topbranch *
************************************
*        0 …
```
> [IO] Avoid nullptr dereference in I/O of std::pair

- math/mathcore/inc/Fit/BinData.h
- math/mathcore/inc/Fit/Chi2FCN.h
- math/mathcore/inc/Fit/FitData.h
- math/mathcore/inc/Fit/FitResult.h
- math/mathcore/inc/Fit/Fitter.h
- math/mathcore/inc/Fit/LogLikelihoodFCN.h
- math/mathcore/inc/Fit/PoissonLikelihoodFCN.h
- math/mathcore/inc/Fit/SparseData.h
- math/mathcore/inc/Fit/UnBinData.h
- math/mathcore/src/BinData.cxx
- math/mathcore/src/FitData.cxx
- math/mathcore/src/FitResult.cxx
- math/mathcore/src/Fitter.cxx
- math/mathcore/src/SparseData.cxx
- math/mathcore/src/UnBinData.cxx
This PR implements the correct copy constructors for the FitData classes and, when the user provides to teh Fitter, a reference to a Fit data classes, the data are copied. 
An interface using a `shared_ptr` to the data exists to avoid copying. 
This PR fixes #11154
> [math][fit] Fix Fitter class for temporary FitData (issue #11154)

- CMakeLists.txt
Fixes the following warning with CMake 3.24:
```
CMake Warning (dev) at /usr/share/cmake/Modules/ExternalProject.cmake:3071 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
```
> [cmake] Add POLICY CMP0135 and set it to NEW

- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooHistPdf.cxx
- roofit/roofitcore/test/testRooDataHist.cxx
With the function `RooDataHist::interpolateQuadratic()` it is now possible to
use `RooDataHist::weights()` (implemented in #11171) to evaluate weights for
one dimensional histograms with up to second order interpolation.
The structure of `RooDataHist::interpolateQuadratic()` is similar to that of
`RooDataHist::interpolateLinear()`, which was implemented in #11211
It finds the coefficients of a second order polynomial between three
neighboring bin centers by solving a system of three quadratic equations. With
the coefficients of the quadratic function, the interpolated weight for an event
between two bin centers can be calculated.
If an event in a bin is to the left of the bin center coordinates, the
corresponding weight is found by interpolating between the current bin and the
two …
> [RF] Enable vectorized second order interpolation for weight evaluation

- CMakeLists.txt
Fixes the following warning with CMake 3.24:
```
CMake Warning (dev) at /usr/share/cmake/Modules/ExternalProject.cmake:3071 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
```
> [v6-26][cmake] Add POLICY CMP0135 and set it to NEW

- tree/dataframe/inc/ROOT/RDFHelpers.hxx
RDFHelpers.hxx provides ROOT::RDF::RunGraphs(std::vector<RResultHandle>).
In order for the handy implicit conversion from RResultPtr<T> to
RResultHandle to be available for client code that include
RDFHelpers.hxx, it is not enough that this header forward-declares
RResultHandle, but it needs to transitively provide the whole type
declaration.
In practice, before 8bbd543f3d56, this worked fine:
```
...
RunGraphs({resultptr1, resultptr2});
```
while after that commit it would require an extra `#include
<ROOT/RResultHandle.hxx>`. This patch restores the previous situation.
> [DF] Re-add a useful transitive include

- core/imt/CMakeLists.txt
- core/imt/inc/ROOT/RSlotStack.hxx
- core/imt/src/RSlotStack.cxx
- tree/dataframe/CMakeLists.txt
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_nodes.cxx
Moves the RSlotStack implementation from tree/dataframe/ to core/imt/.
Makes RSlotStack useable without requiring the whole of RDataFrame as a dependency.
This PR fixes # N/A
> Move RSlotStack from RDF to Imt

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_regression.cxx
Before this commit, if an action with a sample callback (currently
only Snapshot) or a DefinePerSample went out of scope, we did not
deregister the corresponding callbacks from the RLoopManager, which
would try to run them anyway during the following event loop.
As callbacks typically perform a call on the original action or
define objects, this could cause a use-after-delete.
With this patch, we now associate each callback to the address of
the corresponding node of the computation graph and remove callbacks
when the nodes go out of scope.
This fixes https://github.com/root-project/root/issues/11222.
> [DF] Fix potential use-after-delete in sample callbacks 

- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_nodes.cxx
A recent commit moved `RSlotStack` to `core/imt`, so now we can only include it if `R__USE_IMT` is defined.
> [DF] Fix builds with imt=OFF

- core/metacling/src/TClingCallFunc.cxx
Fixes the following error when building:
```
/home/vpadulan/programs/rootproject/rootsrc/core/metacling/src/TClingCallFunc.cxx: In member function ‘void TClingCallFunc::exec(void*, void*)’:
/home/vpadulan/programs/rootproject/rootsrc/core/metacling/src/TClingCallFunc.cxx:1539:20: error: ‘this’ pointer is null [-Werror=nonnull]
1539 |             ::Error("TClingCallFunc::exec(void*)",
|             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1540 |                     "Invalid type '%s'", BT->getTypeClassName());
```
Co-authored-by: Vassil Vassilev <v.g.vassilev@gmail.com>
> [core] fix typo in TClingCallFunc::exec

- builtins/nlohmann/CMakeLists.txt
- builtins/nlohmann/LICENSE.MIT
- builtins/nlohmann/json.hpp
- builtins/nlohmann/json_fwd.hpp
- graf3d/eve7/inc/ROOT/REveElement.hxx
Provide json_fwd.h which can be used now in eve7
Also update forward declaration in REveElement.hxx
> Update nlohmann/json.hpp to version 3.10.5

- tree/tree/src/TBranch.cxx
- tree/tree/src/TBranchElement.cxx
When called repeatedly via TTree::GetBranch, the string allocations in
GetFullName have a notable runtime cost.
Here, the allocation is reduced to a single one in every branch.
See here for a performance analysis where repeated invocations produced significant overhead.
This seems to matter most if the branches have mothers, because in this case, the string composition kicks in.
@pcanal
- Do you know if there's a test that covers this case?
- Do you agree that this brings down TString allocations?
> [tree] Reduce string allocations in TBranch*::GetFullName.

- roofit/roofitcore/src/RooSimPdfBuilder.cxx
Appears with `-Ddev=on` builds
> Add missing includes in RooSimPdfBuilder.cxx

- core/clingutils/src/TClingUtils.cxx
Improves cast safety by using static_cast instead of old C-style cast.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/1992/WG21%201992/X3J16_92-0122%20WG21_N0199.pdf
> [clingutils] Modernize C++ casting in generated dictionaries to avoid potential warnings in derived applications

- core/cont/inc/TList.h
Prevent warnings when project compiled with -Wsuggest-override option
> Mark TObjOptLink methods as override

- tmva/tmva/src/CvSplit.cxx
- tmva/tmva/test/crossvalidation/TestCrossValidationSplitting.cxx
The maximum unsigned int value was used for an integer resulting in a negative integer value and this was causing a bug when accessing the numfold parameter in the CvSplit expression formula.
The bug is present when the parameter "NumFold" is not used in the SPlit expression.
See https://root-forum.cern.ch/t/tmva-crossvalidation-crashes-on-destructor-pyroot/51195
> [tmva] Fix maximum value for indexing the NumFolds parameter

- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooDataSet.cxx
More detail can be found in the commit descriptions.
This addresses the following forum issue:
Related forum post:
https://root-forum.cern.ch/t/error-for-unbinned-binned-weighted-fits/51336
> [RF] Improve sum-of-weight-squares handling with RooDataSet and bugfix for asymptotic error correction

- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/test/CMakeLists.txt
- tree/dataframe/test/dataframe_regression.cxx
Given a string expression such as "alias.subbranch" (where
`subbranch` is _not_ also the name of a valid data member of
the type of the "alias" top-level branch), we used to transform
the expression to `[](T &var0) { return var0.subbranch; }`,
which does not compile.
Now aliases in jitted expressions are resolved in a first step
and only then we try to match the expression against known branch
names, fixing the problem.
This PR fixes https://github.com/root-project/root/issues/11207 (and adds a test).
> [DF] Fix jitted expressions with sub-branches of aliases

- core/base/v7/inc/ROOT/RIndexIter.hxx
- core/cont/inc/ROOT/TSeq.hxx
- core/cont/inc/TBtree.h
- core/cont/inc/TList.h
- core/cont/inc/TMap.h
- core/cont/inc/TObjArray.h
- core/cont/inc/TOrdCollection.h
- core/cont/inc/TRefArray.h
- core/meta/src/TViewPubFunctions.h
- hist/histv7/inc/ROOT/RAxis.hxx
- tmva/tmva/inc/TMVA/RTensor.hxx
- tree/treeplayer/inc/ROOT/TTreeReaderFast.hxx
- tree/treeplayer/inc/TTreeReader.h
Cherry-picked commits that are updating the deprecated std::iterator in several classes.
Spotted here: https://root-forum.cern.ch/t/deprecated-iterator-in-ttreereader-h-and-tseq-hxx/51344/2.
> [backport-v626] Avoid using deprecated std::iterator in several classes

- tree/dataframe/src/RDFInterfaceUtils.cxx
Given a string expression such as "alias.subbranch" (where
`subbranch` is _not_ also the name of a valid data member of
the type of the "alias" top-level branch), we used to transform
the expression to `[](T &var0) { return var0.subbranch; }`,
which does not compile.
Now aliases in jitted expressions are resolved in a first step
and only then we try to match the expression against known branch
names, fixing the problem.
This fixes https://github.com/root-project/root/issues/11207 .
> [DF] Fix jitted expressions with sub-branches of aliases (v6.26)

- hist/hist/src/TMultiGraph.cxx
The "I" option (axis are Invisible) was implemented for graphs but was not for TMultigraphs.
> Implement the "I" option for multigraphs

- core/clingutils/src/TClingUtils.cxx
- tutorials/CMakeLists.txt
This addresses the issue described in #11259.  In particular it handles the case where the template parameter
is a value.  i.e. in the inner template of
```
__and_<is_constructible<_Rb_tree_iterator<pair<const unsigned int,string> >,const _Rb_tree_iterator<pair<const unsigned int,string> >&>,is_constructible<bool,const bool&> >
```
> cling: Improve support for expression in template re-substitution.

- core/meta/src/TDataType.cxx
- tree/treeplayer/src/TTreeReaderArray.cxx
This fixes https://github.com/root-project/root/pull/11246 and https://github.com/root-project/root/issues/10645
> v624: TTreeReaderArray: add support for Double32_t and Float16_t

- core/meta/src/TDataType.cxx
- tree/treeplayer/src/TTreeReaderArray.cxx
This fixes https://github.com/root-project/root/pull/11246 and https://github.com/root-project/root/issues/10645
> v626: TTreeReaderArray: add support for Double32_t and Float16_t 

- interpreter/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.cpp
- interpreter/llvm/src/tools/clang/lib/CodeGen/CodeGenModule.h
- interpreter/llvm/src/tools/clang/lib/CodeGen/ModuleBuilder.cpp
The previous cling patches wraps `DeferredDeclsToEmit(vector<GlobalDecl>)`
into a struct that contains a `llvm::GlobalVlaue`, but it seems that this
field is useless and can be dropped. I have tested this patch in Cling and
spotted no new tests failing, so let's give ROOT a try.
Signed-off-by: Jun Zhang <jun@junz.org>
> Drop llvm::GlobalValue in DeferredDeclsToEmit

- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx
- tree/dataframe/src/RDFColumnRegister.cxx
Rather than constructing a different reader for each node that
needs it, with this patch we now leverage RColumnRegister as
a "cache" of RDefineReaders and RVariationReaders so that nodes
in the computation graph share the same reader objects (per
processing slot). This is analogous to what RLoopManager does
for RDSColumnReaders and RTreeColumnReaders.
Sharing column readers across the computation graph will be useful
for bulk loading of event values (which we do not want to repeat
for different instances of a given column's reader).
> [DF] Centralize RDefineReaders and RVariationReaders 

- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
With the latest refactorings, MakeColumnReaders does not actually
create the column readers but simply gets them from RLoopManager or RColumnRegister.
> [DF] Rename MakeColumnReaders => GetColumnReaders

- roofit/roofitcore/src/RooAbsArg.cxx
Discovered that in 6.26 verbose print of lots of classes doesn't work. e.g. you can do:
```
RooWorkspace ws;
ws.factory("SUM::model(RooExponential::pdf1(obs1[0,5],tau1[-1]))"); 
ws.pdf("model")->Print("v")
```
and it will crash.
Fixes verbose printout of roofit object that uses RooListProxy (lots of classes do). 
- [x ] updated the docs (if necessary)
> fix verbose printing of proxies in 6.26

- core/clingutils/src/TClingUtils.cxx
- tutorials/CMakeLists.txt
This addresses the issue described in #11259.  In particular it handles the case where the template parameter
is a value.  i.e. in the inner template of
```
__and_<is_constructible<_Rb_tree_iterator<pair<const unsigned int,string> >,const _Rb_tree_iterator<pair<const unsigned int,string> >&>,is_constructible<bool,const bool&> >
```
> [v626] cling: Improve support for expression in template re-substitution.

- documentation/doxygen/Doxyfile
- hist/spectrum/src/TSpectrum.cxx
There are a lot of questions about TSpectrum being dis-recommended in the ROOT forum, and what alternatives there are.
For example https://root-forum.cern.ch/t/which-package-or-class-supersede-the-tspectrum-for-searching-peaks/51459 
This PR makes the formulation more detailed. The `legacy` alias has been redefined. It has now 2 parameters. The 2nd one is free text (without comma) allowing to precise, for instance, possible replacements of the class.
> [skip-ci] redefine the legacy alias

- tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx
- tree/dataframe/inc/ROOT/RDF/RDefine.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/src/RDFColumnRegister.cxx
- tree/dataframe/src/RLoopManager.cxx
Rather than sharing ownerhsip of column readers between different
components of the computation graph, now:
- RLoopManager has unique ownership of TTree/datasource readers
- RColumnRegister has unique ownership of define/variation readers
- everything else uses non-owning raw pointers
> [DF] Simplify column reader ownership model

- io/io/src/TFile.cxx
- net/davix/src/TDavixFile.cxx
- net/net/src/TNetFile.cxx
- net/net/src/TWebFile.cxx
- net/netxng/src/TNetXNGFile.cxx
...as well as in TNetFile, TDavixFile and TWebFile.
This fixes #10742.
> [IO] Honor READ_WITHOUT_GLOBALREGISTRATION in TNetXNGFile (v6.26)

- tutorials/CMakeLists.txt
- tutorials/tmva/TMVA_SOFIE_ONNX.C
- tutorials/tmva/keras/ClassificationKeras.py
- tutorials/tmva/keras/GenerateModel.py
- tutorials/tmva/keras/MulticlassKeras.py
- tutorials/tmva/keras/RegressionKeras.py
- tutorials/tmva/pytorch/ClassificationPyTorch.py
- tutorials/tmva/pytorch/MulticlassPyTorch.py
- tutorials/tmva/pytorch/RegressionPyTorch.py
* [cmake] Fix dependency of some TMVA_SOFIE tutorials
* [tmva] Set unique model file names for tutorials
The tutorials were using the same model file name and this was causing a problem when running the tutorials in parallel as in the CI builds.
Fix also some deprectations happening when using now the  new Keras  version based on tensorflow.keras Fix dependency also for Python Keras tutorials
Disable also Regression Keras tutorials in CI builds since they are too slow for the regression evaluation on single events
> [tmva] Backport in 6.26 to fix Keras and PyTorch tutorials 

- tutorials/tmva/TMVA_RNN_Classification.py
This PR should fix TMVA_RNN_Classification.py tutorial failures seen in many CI node in the nightly builds
> [tmva] Fix a TMVA tutorial  when Keras is not installed

- tree/dataframe/src/RDFHelpers.cxx
- tree/dataframe/test/dataframe_helpers.cxx
RunGraphs kindly warns the user if some of the results that were passed to it correspond to results that are already "ready" (i.e. for which the event loop has already run), since that is typically not the intended usage.
At that point it should not quit though: it should run the event loop for the results that still need running.
This patch fixes that.
@vepadulano afaict the distributed version does not check this at all?
> [DF] Warn and run, do not just warn in RunGraphs

- tree/dataframe/CMakeLists.txt
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
- tree/dataframe/src/RInterfaceBase.cxx
This is to reduce the amount of code generated for every separate
RInterface instantiation.
The PR should not otherwise modify any logic or functionality.
I hoped this would reduce compile times of RDF-heavy code, but on an artificial benchmark the changes have little to no effect. This might be a good refactoring to have nonetheless. What do people think?
In order to minimize conflicts with other PRs, this must be merged after:
- https://github.com/root-project/root/pull/11314
- https://github.com/root-project/root/pull/11307
- https://github.com/root-project/root/pull/11306
- https://github.com/root-project/root/pull/11149
> [DF] Move large parts of RInterface to a non-template base class

- interpreter/llvm/src/tools/clang/lib/AST/DeclCXX.cpp
- interpreter/llvm/src/tools/clang/lib/Sema/SemaInit.cpp
Backport of commit 1b5404aff3.
Original commit message:
```
We would previously pick between calling an initializer list constructor
and calling a default constructor unstably in this situation, depending
on whether the inherited default constructor had already been used
elsewhere in the program.
```
This commit first appeared in LLVM 10 and fixes some problems with modules when building with GCC 12, for example ODRHash asserts in `roottest-root-io-uniquePointer`.
> PR44540: Prefer an inherited default constructor over an initializer list constructor when initializing from {}.

- interpreter/llvm/src/tools/clang/lib/AST/DeclCXX.cpp
- interpreter/llvm/src/tools/clang/lib/Sema/SemaInit.cpp
Backport of commit 1b5404aff3.
Original commit message:
```
We would previously pick between calling an initializer list constructor
and calling a default constructor unstably in this situation, depending
on whether the inherited default constructor had already been used
elsewhere in the program.
```
This commit first appeared in LLVM 10 and fixes some problems with modules when building with GCC 12, for example ODRHash asserts in `roottest-root-io-uniquePointer`.
(cherry picked from commit cf32d2bc738367fe0d5c8ccbc0856d345f824228)
Backport of PR https://github.com/root-project/root/pull/11359
> PR44540: Prefer an inherited default constructor over an initializer list constructor when initializing from {}. [v6.26]

- graf2d/asimage/inc/TASImage.h
- graf2d/fitsio/inc/TFITS.h
- graf2d/gpad/inc/TRatioPlot.h
- graf2d/graf/inc/TAttImage.h
- graf2d/graf/inc/TCurlyLine.h
- graf2d/graf/inc/TImage.h
- graf2d/graf/inc/TPie.h
- graf2d/gviz/inc/TGraphNode.h
- hist/histpainter/inc/TGraph2DPainter.h
- hist/histpainter/inc/THistPainter.h
Allows to use `-Wzero-as-null-pointer-constant` compiler flag in derived projects
> Use `nullptr` in graf classes

- requirements.txt
To fix the timeouts seen in our CI runs of the distributed RDataFrame with Dask suite. In particular, the Dask version used was 2021.10.0. Version 2021.11.2 fixes a couple of deadlock bugs which were most probably responsible for the timeouts (see https://distributed.dask.org/en/stable/changelog.html#v2021-11-2).
We bump the minimum Dask version to 2022.02.0 (
https://distributed.dask.org/en/stable/changelog.html#v2022-02-0) because it is the last version with support for Python 3.7 (the current minimum Python version for distributed RDataFrame).
The test suite was run with Dask 2021.10.0 on both Ubuntu and Fedora, showing the timeout. Version 2021.11.2 doesn't timeout.
> Bump minimum Dask version to 2022.2

- tree/dataframe/src/RDFHelpers.cxx
- better name for a variable, nNotRun -> nToRun
- substitute raw for loop with count_if (for readability)
- substitute raw for loop with for_each (for consistency with the multi-thread version, which uses TThreadExecutor::Foreach)
> [DF] Minor improvements to RunGraphs

- bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
- requirements.txt
It was there to test whether the user wants to connect to a batch system with Dask and consequently get the number of cores requested. Now this is done lazily, and if the module is not found it means that there is no connection to a batch system involved. Thus we can just get the number of cores through the more generic Client API.
> Remove dependency from dask_jobqueue

- builtins/xrootd/CMakeLists.txt
* Update XRootD builtin from v5.4.3 to v5.5.0
- c.f. https://github.com/xrootd/xrootd/releases/tag/v5.5.0
* Follow up to https://github.com/root-project/root/pull/10725
* Update XRootD builtin from v5.4.3 to v5.5.0
- c.f. https://github.com/xrootd/xrootd/issues/1751 for details.
I didn't build ROOT from source (though c.f. https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/73 for a source build with effectively this change)
- [N/A] updated the docs (if necessary)
> [cmake] Update XRootD to v5.5.0

- roofit/roofitcore/inc/RooEffProd.h
- roofit/roofitcore/src/RooEffProd.cxx
In ROOT 6.26, the default constructor of the RooEffProd was accidentally removed. This commit is bringing it back, and it also needs to be backported to the 6.26 development branch.
Thanks to this forum post for noticing the problem: https://root-forum.cern.ch/t/trouble-with-rooworkspace-since-rooeffprod-default-constructor-is-deleted-in-v6-26/50577
> [RF] Bring back accidentally removed RooEffProd default constructor

- tmva/sofie/inc/TMVA/ROperator_Shape.hxx
End axis value passed as attribute in Shape is included. So a +1 was missing when computing the output tensor length
This PR should fix the failure observed in the TestCustomModelFromONNX
> [tmva][sofie] Fix operator Shape

- interpreter/cling/lib/Interpreter/LookupHelper.cpp
The signed and unsigned logic was reversed for long long and unsigned long long. This PR fixes that.
> Fix long long error in findBuiltinType

- tutorials/roofit/rf204b_extendedLikelihood_rangedFit.C
- tutorials/roofit/rf204b_extendedLikelihood_rangedFit.py
- tutorials/roofit/rf212_plottingInRanges_blinding.py
The PR #7719 changed the behavior of multi-range fits in RooFit, and from then one the relative yields in the multiple regions were also considered in the fit.
The tutorial `rf204b_extendedLikelihood_rangedFit` was explaining the old caveat that relative yields are not considered in non-extended fits, but since that is not a problem anymore, a big chunk of explanation in the tutorial should be removed.
A Python translation of the tutorial was also added.
Closes #8808.
> [RF] Update RooFit `rf204b_extendedLikelihood_rangedFit` tutorial

- roofit/roofitcore/src/RooAddPdf.cxx
There is a constructor of the RooAddPdf that takes no coefficients and
only a list of PDFs. This only makes sense if all of the PDFs are
extendible. Indeed, there are error messages when a PDF is not
extendible, but it would be better to throw an exception because this is
an error that will certainly break your model.
This change is inspired by the following forum post:
https://root-forum.cern.ch/t/roofftconvpdf-not-working-in-product-with-rooaddpdf-even-in-new-root-versions/51442
One user error that resulted in the post was using the no-coefficient constructor with non-extendible PDFs, which would have been prevented by throwing an error as suggested in this PR.
> [RF] Error out for non-extendible PDFs in no-coef RooAddPdf constructor

- core/base/src/TErrorDefaultHandler.cxx
Previously if a message (for example warning of duplicate dictionary) happened during intialization, it would trigger the initialization of gROOT and could trigger a nested Warning. for example due to the duplicate rootmap file entry and would cause a dead lock (recursiverly taking the non recursive lock GetErrorMutex().
> Fix #11383 (deadlock at initialization)

- roofit/roofitcore/inc/RooHelpers.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooHelpers.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
When the `SplitRange` command arguemnt is used in
`RooAbsPdf::createNLL`, the actual range names used for the fit depend on the channel, with the range names suffixed by the category name. This should be considered correctly in the overlap checks.
Closes #11396.
> [RF] Consider the `SplitRange` in overlap checks for simultaneous PDFs

- tmva/sofie/inc/TMVA/ROperator_Softmax.hxx
- Initialize the size and the stride of the axis
- throw an error when the input tensor has more than 5 dimensions
> [TMVA][SOIFE] Fix warnings in the Softmax operator

- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
- test/stressRooFit_tests.h
Unlike in the old RooFit, the PDF was not cloned in the BatchMode when a
likelihood object was created with `RooAbsPdf::createNLL`. This caused
trouble in a few places, because changing the state of the NLL changed
the state of the original model.
Actually, the model was already cloned when a RooSimultaneous was used,
and because the cloning is only expensive for large simultaneous models,
this change is not expected to have a negative performance impact for
realistic workflows.
The `testRooSimultaneous` closure test with a one-channel
RooSimultaneous is now extended to use also the BatchMode, because this
was one of the cases where it failed before the suggested change in this
commit.
This PR includes a second technical commit with some code modernization in `stressRooFit`.
> [RF] Always clone the PDF in RooFit BatchMode `RooAbsPdf::createNLL`

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py
- bindings/pyroot/pythonizations/test/rdf_define_pyz.py
- bindings/pyroot/pythonizations/test/rdf_filter_pyz.py
Introduces a couple of fixes for Define and Filter pythonizations, namely:
- Fixes #10092 so that Python lists can be passed in `Filter` operations to specify column names.
- Restores support for C++ functors and `std::function`s passed as callable arguments of `Define` and `Filter`.
and adds the corresponding tests.
> [PyROOT][RDF] Fixes for Define and Filter pythonizations

- roofit/roofitcore/inc/RooHelpers.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooHelpers.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
1. https://github.com/root-project/root/pull/11401
2. https://github.com/root-project/root/pull/11406
Only the last commit that changes the PDF cloning behavior, also excluding the `testRooSimultaneous` changes in that commit
> [v626][RF] Backports of RooFit PRs to v6-26-00-patches: Part 20

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py
- bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/inc/RooAbsDataStore.h
- roofit/roofitcore/inc/RooCompositeDataStore.h
- roofit/roofitcore/inc/RooDataHist.h
- roofit/roofitcore/inc/RooTreeDataStore.h
- roofit/roofitcore/inc/RooVectorDataStore.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooCompositeDataStore.cxx
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooTreeDataStore.cxx
- roofit/roofitcore/src/RooVectorDataStore.cxx
- test/stressRooFit_tests.h
There still was a constructor of `RooDataSet` that was hardcoded to use
the TreeDataStore. This needs to be changed, because the
RooVectorDataStore is more performant and compatible with the new
BatchMode.
This PR also includes some other commits that improve the memory management in the dataset classes with `std::unique_ptr`.
> [RF] Use VectorDataStore by default in all RooDataSet constructors

- roofit/roofitcore/src/RooAbsCategory.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooChi2Var.cxx
- roofit/roofitcore/src/RooDataHist.cxx
* Explain better which functions should be used to get category indices
* Make documentation of RooChi2Var less verbose
* Avoid duplicate deprecation notice in `RooDataHist::set()`: the `RooDataHist::set()` function is marked deprecated in the header file with `R__SUGGEST_ALTERNATIVE`. This already adds a deprecation notice to the doxygen, so it is not necessary to add a `\deprecated` tag manually to the documentation. https://root.cern.ch/doc/v626/classRooDataHist.html#a3053f0f1a21eb39bb2508be61e30d8b9
* Replace `NumEvent()` with the correct `NumEvents()` in the RooAbsPdf documentation
Closes #11418.
> [RF] Some RooFit documentation updates

- roofit/roofitcore/inc/RooHist.h
- roofit/roofitcore/src/RooHist.cxx
- roofit/roofitcore/src/RooPlot.cxx
When plotting a pdf in 2 separate ranges, 2 RooCurve objects are created with the same name . When using pullHist or whatever function of RooPlot accessing the RooCurve by its name, only the last of the two curve can be retrieved. Since RooPlot has no way to access its list of containing objects, apart than given the name, only the RooCurve with the upper range will be used.
Code to reproduce the problem:
```Python
import ROOT as r
ws = r.RooWorkspace("workspace")
x = ws.factory("x[-10, 10]")
x.setRange("lo", -10, -5)
x.setRange("hi", 5, 10)
pdf = ws.factory("Gaussian::pdf(x, m1[0], s1[3])")
ds = pdf.generate(r.RooArgSet(x), 1000)
fr = x.frame()
ds.plotOn(fr)
pdf.plotOn(fr, r.RooFit.Range("lo,hi"))
pull = fr.pullHist()
c = r.TCanvas()
fr2 = x.frame()
fr2.addPlotable(pull, "P")
fr2.Draw() …
```
> [RF] Consider all curves for `RooPlot::pullHist` in multi-range fits

- hist/hist/src/TH1Merger.cxx
- hist/hist/src/TH1Merger.h
- test/stressHistogram.cxx
Create a new type of merging, a special case when the histogram has an axis with label and the other axis is numeric and different but compatible. 
A new test is added also in stressHIstogram for this new case
This fixes  #10828
> [hist] Fix label merge when one axis is numerical and extendable

- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooDataSet.cxx
When overriding `SetName` in RooDataHist and RooDataSet, we need to use the function from the direct base class RooAbsData, because this one is already overriding the TNamed function to deal with the RooNameReg correctly.
Closes #11414.
> [RF] Correctly override `SetName` in RooDataHist and RooDataSet

- roofit/hs3/src/JSONFactories_HistFactory.cxx
The HistFactory exporter tends to crash with "edited" HistFactory pdfs that look like genuine HistFactory upon first inspection but turn out not to be.
This PR delays the writing to the node of the JSOn structure until after all components have been found and identified, such that the exporter can cleanly abort in case an export with the HistFactory template is not possible.
> [RF] [HS3] Solve HistFactory exporter crashes

- roofit/roofitcore/inc/RooCmdArg.h
- roofit/roofitcore/inc/RooCmdConfig.h
- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooChi2Var.cxx
- roofit/roofitcore/src/RooCmdArg.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
- roofit/roofitcore/src/RooMCStudy.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooSimultaneous.cxx
As reported in issue https://github.com/root-project/root/issues/11421, the fact that in the RooFit command
arguments, the `RooArgSet`s are often stored by pointer is still a
problem. I attempted before to circumvent the problem by detecting
potential lifetime issues by having a dedicated `RooArgSet&&` overloads
that resulted in RooCmdArgs that owned copied of the RooArgSets.
However, this still didn't work for the case where the Python collection
pythonizations are used in PyROOT, because there the `RooArgSet &&`
overloads are not hit.
I realized now that the `RooCmdArg` class already has the slots to store
RooArgSets by value, which was alredy used by a few RooFit command
arguments. When these `set` slots are used, there are no ownership
issues.
This commit suggests to always use these …
> [RF] Always pass RooArgSets to RooCmdArgs by value

- interpreter/cling/tools/packaging/cpt.py
> [cling-cpt] More splitting lines for getting rid of E501 error cont. [skip-ci]

- cmake/modules/RootMacros.cmake
This applies the change made to ROOT_GENERATE_DICTIONARY in the main branch commit 08ab7e0306 to GENREFLEX_GENERATE_DICTIONARY.
This commit in conjunction with 08ab7e0306 fixes #11312.
See commit 08ab7e0306 and issue #11312 for more details on the issue and solution.
> [cmake] Protect against empty COMPILE_DEFINITIONS in genreflex command

- proof/proofplayer/src/TProofDraw.cxx
Fixing compiler warning:
```
/home/linev/git/root6/proof/proofplayer/src/TProofDraw.cxx: In member function ‘virtual void TProofDrawHist::SlaveBegin(TTree*)’:
/home/linev/git/root6/proof/proofplayer/src/TProofDraw.cxx:783:51: error: dangling pointer to an unnamed temporary may be used [-Werror=dangling-pointer=]
783 |       if (objname && strlen(objname) > 0 && strcmp(objname, "htemp")) {
|                                             ~~~~~~^~~~~~~~~~~~~~~~~~
/home/linev/git/root6/proof/proofplayer/src/TProofDraw.cxx:782:62: note: unnamed temporary defined here
782 |       const char *objname = fTreeDrawArgsParser.GetObjectName();
|                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/linev/git/root6/proof/proofplayer/src/TProofDraw.cxx:789:30: error: dangling pointer to …
```
> [proof] use proper string type to store object name in TProofDraw

- tree/dataframe/src/RDataFrame.cxx
With this patch we create chains with kWithoutGlobalRegistration in
RDF's constructors -- this is the chain object that RDF uses for
single-thread runs and to look up which branches exist and other
information about the input dataset.
The deregistration of that chain from the global lists can take
some time in certain cases.
This PR depends (and is based) on #11321 .
> [DF] Avoid registration of inner TChain with global lists 

- bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py
- bindings/pyroot_legacy/JupyROOT/helpers/cppcompleter.py
- core/base/inc/TObject.h
- core/base/src/TObject.cxx
- core/base/src/TQConnection.cxx
- core/base/src/TROOT.cxx
- core/cont/src/TClonesArray.cxx
- core/cont/src/TCollection.cxx
- core/cont/src/THashList.cxx
- core/cont/src/TList.cxx
- core/cont/src/TObjArray.cxx
- core/cont/src/TObjectTable.cxx
- core/gui/src/TContextMenu.cxx
- etc/valgrind-root.supp
- graf2d/gpad/src/TButton.cxx
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/gpad/src/TRatioPlot.cxx
- graf2d/graf/src/TPaveText.cxx
- graf3d/g3d/src/TGeometry.cxx
- graf3d/g3d/src/TNode.cxx
- gui/gui/src/TGFileBrowser.cxx
- gui/gui/src/TGFrame.cxx
- gui/gui/src/TGMdiMainFrame.cxx
- gui/gui/src/TGTextEntry.cxx
- hist/hist/src/TEfficiency.cxx
- hist/hist/src/TH1.cxx
- net/net/src/TApplicationServer.cxx
- tutorials/net/spyserv.C
On some platform operator delete taints the memory, so even right after the deletion the information stored by ~TObject is already erased.  On those platform we no longer rely on the kNotDelete bit hack and rely on the system (which has tainted the memory assumingly for a reason) to detect the use-after-delete problems.
Introduce 2 new functions.
TObject::IsDestructed (used by TClonesArray) that detects that the destructor has been run and is active in all configuration.  This should be used if the code knows that the memory has not been freed/deleted.
ROOT::Detail::HasBeenDeleted(TObject*) with returns true if the platform does not taint the memory and if the kNotDeleted is not set (in all other case, it returns false)
This fixes #11330
> core: Disable check for already deleted object.

- bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py
- bindings/pyroot_legacy/JupyROOT/helpers/cppcompleter.py
- core/base/inc/TObject.h
- core/base/src/TObject.cxx
- core/base/src/TQConnection.cxx
- core/base/src/TROOT.cxx
- core/cont/src/TClonesArray.cxx
- core/cont/src/TCollection.cxx
- core/cont/src/THashList.cxx
- core/cont/src/TList.cxx
- core/cont/src/TObjArray.cxx
- core/cont/src/TObjectTable.cxx
- core/gui/src/TContextMenu.cxx
- etc/valgrind-root.supp
- graf2d/gpad/src/TButton.cxx
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/gpad/src/TRatioPlot.cxx
- graf2d/graf/src/TPaveText.cxx
- graf3d/g3d/src/TGeometry.cxx
- graf3d/g3d/src/TNode.cxx
- gui/gui/src/TGFileBrowser.cxx
- gui/gui/src/TGFrame.cxx
- gui/gui/src/TGMdiMainFrame.cxx
- gui/gui/src/TGTextEntry.cxx
- hist/hist/src/TEfficiency.cxx
- hist/hist/src/TH1.cxx
- net/net/src/TApplicationServer.cxx
- tutorials/net/spyserv.C
On some platform operator delete taints the memory, so even right after the deletion the information stored by ~TObject is already erased.  On those platform we no longer rely on the kNotDelete bit hack and rely on the system (which has tainted the memory assumingly for a reason) to detect the use-after-delete problems.
Introduce 2 new functions.
TObject::IsDestructed (used by TClonesArray) that detects that the destructor has been run and is active in all configuration.  This should be used if the code knows that the memory has not been freed/deleted.
ROOT::Detail::HasBeenDeleted(TObject*) with returns true if the platform does not taint the memory and if the kNotDeleted is not set (in all other case, it returns false)
This fixes #11330
Backport of …
> v626 core: Disable test for already deleted object.

- bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
- bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx
- bindings/pyroot/cppyy/patches/null-safety.patch
Prevents some null ptr access. Detected by clang-tidy.
> Cppy nulls

- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/test/testRooAbsReal.cxx
- roofit/roofitcore/test/testRooAddPdf.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
The recent commit `565e9aa19a` updated the `getPropagatedError` with
some additional checks, but these checks caused segfaults in some
specifit usecases:
* where the `RooAbsReal` is a parameter in the fit result itself
* where the `RooAbsReal` is a variable unrelated to the fit result
* where the `RooAbsReal` depends only on some of the parameters in the
fit result
This commit fixes these usecases again.
A unit test that checks that these usecases don't fail anymore is now
implemented in `testRooAbsReal`.
This PR also adds some other new unit tests that cover recent PRs and issues.
> [RF] Fix recently-introduced `RooAbsReal::getPropagatedError` problems and add several new unit tests

- bindings/pyroot/pythonizations/CMakeLists.txt
Before this commit, when you update the code in
`bindings/pyroot/pythonizations/python/ROOT/_pythonization` and recompile ROOT, the corresponding `build` directory (`root_build/lib/ROOT/_pythonization`) doesn't get updated, and consequently also not the `root_install/lib/ROOT/_pythonization` directory when installing the build.
This commit fixes this situation by introducing intermediate CMake targets, resulting in the Python sources in the build and install directories being updated when changed in the source directory.
Closes #11233.
> [cmake][PyROOT] Properly deal with PyROOT pythonization sources

- tutorials/CMakeLists.txt
- tutorials/dataframe/distrdf001_spark_connection.py
- tutorials/dataframe/distrdf002_dask_connection.py
The distributed RDataFrame tutorials/tests have to create cluster objects, which take up resources on the machine. This is another step towards a clearer resource usage for both tutorials and tests. Whenever a cluster object is created, it now uses RESOURCE_LOCK test property to signal that no other cluster object should be created while the previous one is still running.
This PR addresses the tutorials in the root repository, a sibling PR will address the tests in roottest
> Improvements on resource restrictions for distributed tests

- cmake/modules/RootMacros.cmake
This corrects the content of https://github.com/root-project/root/commit/6efc1684a62d37ccfa582cbbe3605995201ea7cb [cmake] Protect against empty COMPILE_DEFINITIONS in genreflex command
> [cmake] Correct typo in REFLEX_GENERATE_DICTIONARY. 

- tmva/sofie/inc/TMVA/ROperator_Shape.hxx
Fix a warning when compiling the generated code of the Shape operator
> [tmva][sofie] Fix warning with unused input tensor in Shape operator

- core/metacling/src/TClingCallbacks.cxx
Before we do name lookups, we must ensure any later redeclaration of the DeclContext has been loaded, since they may add names to the result of this lookup.
Signed-off-by: Jun Zhang <jun@junz.org>
> [cxxmodules] Update redeclaration chain after loading modules

- tree/dataframe/inc/ROOT/RArrowDS.hxx
- tree/dataframe/inc/ROOT/RCsvDS.hxx
- tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RFilterBase.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDF/RRange.hxx
- tree/dataframe/inc/ROOT/RDF/RRangeBase.hxx
- tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
- tree/dataframe/inc/ROOT/RDF/RVariation.hxx
- tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx
- tree/dataframe/inc/ROOT/RDataSource.hxx
- tree/dataframe/inc/ROOT/RRootDS.hxx
- tree/dataframe/inc/ROOT/RTrivialDS.hxx
- tree/dataframe/src/RNTupleDS.cxx
- tree/dataframe/test/RNonCopiableColumnDS.hxx
- tree/dataframe/test/dataframe_definepersample.cxx
- tree/dataframe/test/dataframe_regression.cxx
- tree/dataframe/test/dataframe_samplecallback.cxx
For developers, it is unconvenient that the `override` specifier
that flags member functions as overriding on first sight is not used so
much in `hist`.
I think it is a good time to add the missing `override` specifiers
to more ROOT components now, as I have already done it for `roofit`,
`math`, and `hist`, where it was really a game changer for me because it
made reading und understanding the code easier!
See:
* https://github.com/root-project/root/pull/10083
* https://github.com/root-project/root/pull/9808
* https://github.com/root-project/root/pull/9883
This commit was generated more or less automatically with this Python
script that uses `clang-tidy`:
```Python
import os
import glob
import subprocess
import tqdm
"""
For clang-tidy to work, you have to copy the compile_commands.json …
```
> [tree] Add missing `override` specifiers in tree/dataframe

- tutorials/roostats/rs301_splot.C
The tutorial is actually using the SPlots class wrong. It is calculating
sWeights for the isolation based on the invariant mass and the isolation
itself. That’s wrong. For sPlots, the control variable should not be in
the set of discriminating variables for the likelihood fit! See
https://arxiv.org/pdf/physics/0402083.pdf.
That means when using the SPlot class, you should exclude the isolation
variable from the dataset that you pass.
Big thanks to Dongliang for reporting this on the ROOT Forum!
https://root-forum.cern.ch/t/strange-results-in-rs301-splot-c
A second commit applies some other improvements to the tutorial:
* Code modernization
* Don't define number of events in toy data redundantly
* Add also plots of isolation models
> [RF] Fix tutorial for `RooStats::SPlot`

- roofit/roofitcore/inc/RooVectorDataStore.h
- roofit/roofitcore/src/RooVectorDataStore.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testTestStatistics.cxx
The `RooVectorDataStore` had two different buffers to store the row data in: the so-called "attached buffers" and the "native buffers".
The problem is that when external buffers are attached, the call to `RooVectorDataStore::get()` is not loading the native buffers anymore, which is breaking some code that assumes this, like `RooVectorDataStore::loadValues`, which is used in `RooDataSet::reduce`. This breaks the reduction of datasets with externally attached buffers, which breaks the copy constructor of the `RooNLLVar`.
This commit suggests to always load both the native and attached buffers if `RooVectorDataStore::get()` is called. This has almost no performance overhead and is much safeter.
Since this change fixes the copy constructor of the `RooNLLVar`, which is used when plotting the …
> [RF] Make no distinction in VectorDataStore between `get` and getNative

- roofit/roofitcore/inc/RooAddModel.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/inc/RooBinSamplingPdf.h
- roofit/roofitcore/inc/RooHelpers.h
- roofit/roofitcore/res/RooNLLVarNew.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooAddGenContext.cxx
- roofit/roofitcore/src/RooAddHelpers.cxx
- roofit/roofitcore/src/RooAddHelpers.h
- roofit/roofitcore/src/RooAddModel.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooBinSamplingPdf.cxx
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooHelpers.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/src/RooNormalizedPdf.h
- roofit/roofitcore/test/testRooAddPdf.cxx
- roofit/roofitcore/test/testRooBinSamplingPdf.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
- roofit/roofitcore/test/testTestStatistics.cxx
Multi-range fits in RooFit are more complicated than they should be.
In principle, all that is required is to change the normalization range of the PDF to the union of the ranges.
There is a RooAbdPdf interface to suggest that this could be done easily like this:
```C++
pdf.setNormRange("range1,range2")
```
But this doesn't work well for RooAddPdfs, which is probably why it was chosen to implement mulit-range fits as a sum of separate RooNLLVars. But in this case, the PDFs are normalized separately, and extra terms need to be introduced to correct for that. This resulted in lots of complicated code, and still there are issues like #11447, i.e. is still doesn't work for simultaneous fits.
That's why I decided to fix the `setNormRange()` for RooAddPdfs, and then starting from that …
> [RF] Re-implement multi-range fits

- tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
- tmva/sofie_parsers/src/RModelParser_ONNX.cxx
Move definition of free function defining the parser operator functions in the implementation, since these are only for internal use
This should fix some of the issues seen when using PCH
> [tmva][sofie] Move parser definition for operators in implementation

- bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx
- bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
- bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx
- bindings/pyroot/cppyy/patches/gc_flags.patch
According to the list of changes in Python 3.11:
https://docs.python.org/3.11/whatsnew/3.11.html
types defined with the Py_TPFLAGS_HAVE_GC flag set but with no traverse function (PyTypeObject.tp_traverse) will cause an error.
The above is true for a few types that are defined in cppyy. This commit removes the aforementioned flag from those type definitions with no traverse function. It also sets the right flags for the nonified object type; this fixes the teardown GC crashes observed when the internal memory management of ROOT was involved (e.g. the garbage collection of a tree that belongs to a file).
This PR fixes https://github.com/root-project/root/issues/10799
> [PyROOT] Fixes for garbage collection in Python 3.11

- bindings/pyroot/pythonizations/python/ROOT/_facade.py
- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
This should fix the failure observed when RDF is not built that one needs to not include the RTensor pythonizations
> [pyroot][tmva] Fix importing RTensor pythonization when RTensor is not available

- core/base/src/TString.cxx
A potential memleak or sanity-check in TString found by clang-tidy
> TString sanity check nchar not larger than capacity

- io/io/src/TStreamerInfo.cxx
This fix #11436
Corresponding roottest PR: https://github.com/root-project/roottest/pull/906
> Force storing of StreamerInfo for nested non-split but memberwise streamed collection.

- interpreter/cling/include/cling/std.modulemap
The C++ modules marks the std::vector<int> instantiation as not visible because it came from the `regex` header file which we did not explicitly include.
root-project/root@a785402 introduces checks if certain declaration is visible in dictionary generation time which was intending to semantically improve the coherence by what the user "allowed" (or requested) rootcling to see vs what it can see globally. While this model works well it seems to not work for template instantiations as they won't be re-instantiated with visible modifier.
This patch works around the current issue seen with libstdc++ 12 but a better solution would be to implement a finer grained control over the implicit template instatiations when generating a dictionary.
Fixes root-project/root#11329
> gcc12's regex header file relies on a std::vector<int> instance, export it

- config/root-config.bat.in
Fix the output of `root-config.bat` that makes several TMVA tests failing due to extra spaces
> [skip-ci][Windows] Fix root-config.bat

- tree/readspeed/src/ReadSpeed.cxx
Fix the following compilation error on Win64:
```
ReadSpeed.cxx(334,89): error C2398: Element '1': conversion from 'unsigned __int64' to 'T' requires a narrowing conversion
```
> Fix a compilation error on Win64

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFDisplay.cxx
- tree/dataframe/test/dataframe_display.cxx
Fixes #11390
Improves the workflow of `DisplayHelper::Exec` as follows:
1. We always check whether there are entries to be displayed with `RDisplay::HasNext`. If so, add one row to the display object
2. If no more entries should be displayed, signal this node has finished its job. Make sure the call to `StopProcessing` is done only once with a boolean flag, to avoid early stop of the execution due to more stop signals than the children who actually have finished their job.
> Respect the user-provided number of entries to be displayed

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimultaneous.py
- bindings/pyroot/pythonizations/test/CMakeLists.txt
- bindings/pyroot/pythonizations/test/roofit/rooglobalfunc.py
- bindings/pyroot/pythonizations/test/roofit/roosimultaneous.py
- tutorials/roofit/rf102_dataimport.py
- tutorials/roofit/rf309_ndimplot.py
- tutorials/roofit/rf401_importttreethx.py
- tutorials/roofit/rf501_simultaneouspdf.C
- tutorials/roofit/rf501_simultaneouspdf.py
- tutorials/roofit/rf509_wsinteractive.py
- tutorials/roofit/rf802_mcstudy_addons.py
- tutorials/roofit/rf803_mcstudy_addons2.py
- tutorials/roofit/rf804_mcstudy_constr.py
- tutorials/roofit/rf902_numgenconfig.py
Obviously the `Link` pythonization should call the original `_Link`
function.
Also, the constructor that takes a map of categories to PDFs should be able to
accept a Python dictionary directly.
The RooFit Python tutorials are covering this constructor, acting as a
unit test.
Closes https://github.com/root-project/root/issues/11496.
> [RF] Fix `RooFit::Link()` pythonization and pythonize RooSimultaneous constructor

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimultaneous.py
- bindings/pyroot/pythonizations/test/CMakeLists.txt
- bindings/pyroot/pythonizations/test/roofit/rooglobalfunc.py
- bindings/pyroot/pythonizations/test/roofit/roosimultaneous.py
1. https://github.com/root-project/root/pull/11500
Excluding the last commit that only updates the tutorials
> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 22

- roofit/roofitcore/src/RooDataSet.cxx
Due to a copy-paste error, `RooDataSet::binnedClone` was overwriting the name of the clone if no title was provided. This PR fixes that
Since this is my first PR in ROOT, I have a couple of questions:
- since this was a small change I did not open an issue in the repo, should I do that regardless?
- do I need to write a test?
> [RF] Fix copy-paste error in `RooDataSet::binnedClone`

- bindings/pyroot/pythonizations/CMakeLists.txt
- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_utils.py
Fixes #11437 .
This PR:
- Separates Python sources that are compatible with Python3 only and those that are supported both in 2 and 3.
- Makes a TMVA pythonization module compatible with Python2.
> [TMVA][CMake] Fixes for Python2/3 compatibility in pythonization modules

- roofit/roofitcore/inc/RooAddModel.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAddHelpers.cxx
- roofit/roofitcore/src/RooAddHelpers.h
- roofit/roofitcore/src/RooAddModel.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/test/testRooAddPdf.cxx
- roofit/roofitcore/test/testRooProdPdf.cxx
The commit implements a few new unit tests and also fixes one bug related to the normalization of a RooAddPdf when the custom normalization set of its components is reset.
There is also some code improvement by removing a redundant data member of the `RooAddPdf` and `RooAddModel` classes.
> [RF] More fixes and unit tests related to the RooAddPdf normalization

- tree/dataframe/inc/ROOT/RDF/RColumnReaderBase.hxx
Column readers are now shared among all nodes in the computation graph, so `Get` can be called several times for the same column.
> [NFC][DF] Remove a comment that does not apply anymore.

- bindings/pyroot/cppyy/cppyy-backend/cling/python/cppyy_backend/loader.py
- bindings/pyroot/cppyy/patches/remove_o2_cppyy.patch
Fixes #11344 .
Mostly quoting @eguiraud in #11344 :
import ROOT (via cppyy) causes the setting of the environment variable EXTRA_CLING_ARGS to -O2 -- but too late (after interpreter initialization), so that the setting actually has no effect: cling will still use its default of -O1, but checking EXTRA_CLING_ARGS will give users the wrong impression.
Since there is no reason to set the environment variable in the first place, it has no effect anyway, and it can be confusing for users trying to figure out what options cling is running with, this PR removes the behavior from PyROOT.
> [PyROOT][11344] Remove sterile setting of EXTRA_CLING_ARGS by cppyy

- core/metacling/src/TCling.cxx
macOS 13 again moves many libraries into the binary blob: these files do not exist anymore on disk, but the linker "knows what to do". Linking against them would fail ("file not found"), so rely on the non-system libraries to pull them in. An exception are /usr/lib/system/libsystem_... which *do* exist on disk but must not be linked against.
> [ACLiC] For macOS, make sure the syslib exists:

- tmva/pymva/test/generateKerasModels.py
- tmva/sofie/src/RModel.cxx
- tmva/sofie/test/CMakeLists.txt
- tmva/sofie/test/EmitFromRoot.cxx
- tmva/sofie/test/TestCustomModelsFromROOT.cxx
- tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
-Fix the correct dependency of sofie tests. No ned to depend on protobuf
- Use weight file for Linear tests from ROOT
- Test also the case where the weight file is not present but the session is enabled
- Produce a runtime error when a weight file is enabled but the Session is disabled
> [tmva][sofie] Some improvements in TMVA SOFIE tests

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py
- bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
- roofit/roofitcore/src/RooAbsCategory.cxx
- roofit/roofitcore/src/RooTreeDataStore.cxx
The recently-introduced `RooDataSet.from_numpy()` function was clipping
out-of-range events to the variable boundaries instead of clipping them.
This behavior was misleading and confusing to the users, because the
import of a TTree just skips out out-of-range events.
This commit implements the skipping for `RooDataSet.from_numpy()` as
well, logging also the same warnings when that happens.
A unit test that checks the skipping works correctly for categories and
real-valued variables is also implemented.
Closes https://github.com/root-project/root/issues/10447.
Some other things are also fixed by the two first commits, see more detail in the commit descriptions.
> [RF][PyROOT] Skip out-of-range events in `RooDataSet.from_numpy()` and other fixes

- tree/dataframe/src/RLoopManager.cxx
If subBranchName is already in bNamesReg, then we don't need to try to reinsert it.
This patch shaves off ~10% from the runtime of an exploration of a large test TTree.
> [DF] Avoid useless calls to TTree::GetBranch

- gui/gui/src/TGListTree.cxx
This fixes a display issue on TBrowser on the mac (compiled to coca) where items in the list that had checkboxes against them have their text erroneously displayed that the top of the list rather than next to the item.
Please can we backport this fix as well into the patch releases. Thanks!
> fix display of items in TBrowser that have a checkbox on MAC

- tmva/pymva/inc/TMVA/MethodPyKeras.h
- tmva/pymva/src/MethodPyKeras.cxx
- tutorials/tmva/TMVA_CNN_Classification.py
- tutorials/tmva/TMVA_Higgs_Classification.py
- Protect usage of pymva when it is available
- Enable tf.keras by default in MethodPyKeras since this is now the standard for Keras. Call also the option `tfkeras`
in addition to `tf.keras` since this form will not work as cmd arg in Python.
> [tmva][pymva] Fix and improve Python tutorials and enable  tf.keras by default

- CMakeLists.txt
- cmake/modules/RootMacros.cmake
We replace it with a combination of a global property and an additional custom target.
The global property is used to collect the dependencies created before the modules.idx target is created.
The custom target is used as a direct dependency of the custom_command (add_dependencies can not be used on the target of a custom_command).  Then we can use
this custom target to collect the dependencies created after the modules.idx target.
This fixes #10510.
To test:
```
ls -rtl lib/modules.idx lib/libEve.so
rm lib/*Eve*
ninja # or make or cmake --build ; this should update modules.idx
ls -rtl lib/modules.idx lib/libEve.so
```
> cmake: Replace ever expanding modules_idx_deps cached variable

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreal.py
- roofit/roofitcore/inc/RooLinearVar.h
- roofit/roofitcore/src/RooLinearVar.cxx
- roofit/roostats/src/SPlot.cxx
- roofit/roostats/test/testSPlot.cxx
* fixes a memory leak in `testSPlot`
* make sure the last normalization set is kept alive in PyROOT even when the last normalization set was implicitly created from a Python collection via the new Pythonizations
* make sure no derived coefficients are evaluated without normalization sets in `SPlot` to fix undefined behavior when calling `getVal()` and `RooAbsReal::getValV()` checks for the last normalization set that might not be alive anymore
* improving the code of the `RooLinearVar` that is used by the `SPlot`
Closes #11221.
> [RF] Fix remaining RooFit ASAN failures

- interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
The test autoloads an `Outer` class that has `Inner<int>` as a member. Because we suspend autoloading, the 'Inner<int>' specialization may not be complete at all times, which triggers a `static_assert` in newer versions of libstdc++.
Backport of [D86765](https://reviews.llvm.org/D86765), commit [bf890dcb0f](https://github.com/llvm/llvm-project/commit/bf890dcb0f5eb05b1a98cbd1cdd24c0c4ece8f8d); original commit message:
```
[clang] Don't emit "no member" diagnostic if the lookup fails on an invalid record decl.
The "no member" diagnostic is likely bogus.
```
> Fix ROOT-7462 with libstdc++ >= 10

- interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
The test autoloads an `Outer` class that has `Inner<int>` as a member. Because we suspend autoloading, the `Inner<int>` specialization may not be complete at all times, which triggers a `static_assert` in newer versions of libstdc++.
Backport of D86765, commit bf890dcb0f; original commit message:
```
[clang] Don't emit "no member" diagnostic if the lookup fails on an invalid record decl.
The "no member" diagnostic is likely bogus.
```
(cherry picked from commit 06fd8e9e798919fdc29d8d6ec65d13d55ea30aa7, backport of PR https://github.com/root-project/root/pull/11551)
> Fix ROOT-7462 with libstdc++ >= 10 [v6.26]

- tmva/pymva/inc/TMVA/PyMethodBase.h
- tmva/pymva/src/PyMethodBase.cxx
- tutorials/CMakeLists.txt
- tutorials/tmva/TMVA_CNN_Classification.C
- tutorials/tmva/TMVA_RNN_Classification.C
- tutorials/tmva/TMVA_SOFIE_Keras.C
- tutorials/tmva/TMVA_SOFIE_PyTorch.C
With the new MacOS update python (and python2) is not existing anymore, only python3. Add then a new function TMVA::Python_executable() using ROOT config to determine if ROOT is using python version 2 or 3. In case of 3 returns as executable "python3".
Fix also the correct location of the input ONNX file for TMVA_SOFIE_ONNX.C (copying the file at configure time)
This PR is a backport in 6.26 of PR #10160
> [tmva] Backport fix of TMVA tutorials

- tmva/pymva/test/CMakeLists.txt
- tmva/sofie/test/CMakeLists.txt
- tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
- tmva/sofie_parsers/src/RModelParser_ONNX.cxx
This PR backports in 6.26 some fixes from master in the build configuration for SOFIE. 
- backport fix from #PR 11481 (movie some Sofie parser definition in implementation)
- backport fix from #PR 11545 (fix some issues with no rt modules)
- backport fix from the tests #11529 (apply some fixes in the building of SOFIE tests)
> [tmva][sofie] Backport some fixes in  tmva sofie for 6.26 

- tree/dataframe/test/datasource_arrow.cxx
Explicitly include `arrow/testing/builder.h` to make sure ArrayFromVector is available. Probably it was being included implicitly before.
> Fix datasource_arrow.cxx test

- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- gui/webdisplay/inc/ROOT/RWebWindow.hxx
- gui/webdisplay/src/RWebDisplayArgs.cxx
- gui/webdisplay/src/RWebDisplayHandle.cxx
- gui/webdisplay/src/RWebWindow.cxx
- gui/webdisplay/src/RWebWindowsManager.cxx
- js/build/jsroot.js
- js/modules/core.mjs
- js/modules/webwindow.mjs
- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/Browser.view.xml
- ui5/canv/controller/Canvas.controller.js
- ui5/canv/view/Canvas.view.xml
- ui5/fitpanel/controller/FitPanel.controller.js
- ui5/geom/controller/GeomViewer.controller.js
- ui5/geom/index.html
- ui5/geom/lib/GeomDrawing.js
- ui5/geom/view/GeomViewer.view.xml
- ui5/panel/Controller.js
- ui5/panel/panel.html
- ui5/tree/controller/TreeViewer.controller.js
1. Use default system web browser by default for interactive session
2. Provide way to reload RWebWindow content with key generation
3. Provide `Ctrl-R` handler in RBrowser, RGeomViewer, RWebCanvas, RFitPanel
4. Fix problem in `RGeomViewer` - removing last refs from eve7  
5. Fix problem with `RFitPanel` - still was using global JSROOT handle which is removed in `v7`
> [webgui] use default web browser, let reload RWebWindow

- interpreter/cling/include/cling/std.modulemap
- interpreter/cling/include/cling/std_msvc.modulemap
- interpreter/llvm/src/tools/clang/lib/Basic/Module.cpp
ROOT 6.24 only requires C++11 and we want to continue supporting the likes of GCC 4.8.5 (on CentOS 7) and GCC 5.4.0 (on Ubuntu 16.04).
This reverts commit 44a0c8dcc3e47b3bc7d9677f940384d63074fd97.
> Revert "Revert "[cxxmodules] Allow submodules to contain headers which may be missing.""

- geom/CMakeLists.txt
- gui/browsable/src/TDirectoryElement.cxx
- gui/browsable/src/TObjectElement.cxx
- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- js/modules/webwindow.mjs
- ui5/browser/controller/Browser.controller.js
- ui5/browser/model/BrowserModel.js
- ui5/canv/controller/Canvas.controller.js
1. When filter expression entered, reopen folders again. Means if `TFile` keys were shown, they will be shown again. 
2. When object like `TH1` or `TTree` read from `TFile`, it will be removed from managed objects and owned by `RBrowser`. This allows to correctly work with different histograms version at the time.
3. Show `TFile` size 
4. Fix two LGTM warnings
5. Add `root7` as dependency for `RGeomViewer`
> [webgui] improve RBrowser, fix other problems

- roofit/roofitcore/inc/RooPlot.h
- roofit/roofitcore/src/RooPlot.cxx
The iteration over the plotted `_items` should be in reverse order to
consider the last-plotted curve for the residual histogram.
Also, this commit imporves the support for multi-range residuals by
making sure that multiple curves with the same name are only considered
if the curves are not overlapping.
This commit is a fixup to commit https://github.com/root-project/root/commit/b4bf80c63a8097c2e1fde274bec5d5380e043080.
The PR also includes another commit that removed the dummy member function `RooPlot::GetBinContent()`.
> [RF] Fix wrong order of iterating over curves in `RooPlot::residHist() `

- config/thisroot.fish
- config/thisroot.sh
*   `thisroot.sh`:
*   Pass `shellcheck`
```sh
shellcheck -s sh config/thisroot.sh
shellcheck -s dash config/thisroot.sh
shellcheck -s ksh config/thisroot.sh
shellcheck -s bash config/thisroot.sh
```
Notable fixes:
*   <code>&DiacriticalGrave;my-command&DiacriticalGrave;</code> -> `$(my-command)`
(SC2006, &DiacriticalGrave;&DiacriticalGrave; is a legacy Bourn shell syntax with several issues)
*   `[ "x$foo" = "x" ]` -> `[ -z "${foo-}" ]` and `[ "x$foo" != "x" ]` -> `[ -n "${foo-}"]`
*   `cond && run-true || run-false` -> `if cond; then run-true; else run false; fi`
(SC2015: run-false may be triggered when run-true fails)
*   [ "$foo" == "$bar" ] -> [ "$foo" = "$bar" ] (SC3014, POSIX-conformance)
*   Fix unbound variables
*   Whenever a variable `$foo` is possibly not set, call it like …
> thisroot.sh: refactor with shellcheck; thisroot.fish: `dirname` -> `path dirname` to reduce deps

- roofit/roofitcore/src/RooWorkspace.cxx
In this forum post, the point was made that
`RooWorkspace::getSnapshot()` should not print an error if a snapshot
with the passed name is not found.
https://root-forum.cern.ch/t/roofit-check-if-snapshot-exist-without-showing-objecthandling-error
Just like in the other `RooWorkspace` access functions, like `arg()`,
`pdf()`, or `function()`, users expect to use `getSnapshot()` also to
query if a snapshot exists and check if the returned value is `nullptr`.
So there should be no error printed in `getSnapshot()` itself. If it is
actually an error for th caller that no snapshot has been found, an
error or exception should be raised by the caller.
A second commit in this PR applies some general code modernization to `RooWorkspace.cxx`.
> [RF] Remove error in `RooWorkspace::getSnapshot()` if no snapshot found

- core/metacling/src/TClingClassInfo.cxx
> [6.26] [core] Guard gInterpreterMutex in TClingClassInfo::IsEnum 

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py
- bindings/pyroot/pythonizations/test/stl_vector.py
Fixes #11581 
`std::vector<const char*>` does not provide a `value_type` attribute. This PR makes the pythonization of `std::vector<char>` resilient to the absence of such attribute.
> [PyROOT][11581] Fix std::vector pythonization

- roofit/roofitcore/inc/RooProjectedPdf.h
- roofit/roofitcore/src/RooAbsCollection.cxx
- roofit/roofitcore/src/RooProjectedPdf.cxx
- roofit/roofitcore/src/RooRealIntegral.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testRooRealIntegral.cxx
Integrals of derived PDFs have their client-server interface messed up,
and it's inconsistent with non-derived PDFs. Here is a reproducer:
```C++
void repro() {
RooRealVar x("x", "", 0, 1);
RooRealVar par("par", "", -0.005, -5, 5);
RooProduct parMod("par_mod", "", RooArgSet(par, RooConst(10)));
RooGaussian gauss("gauss", "", x, parMod, RooConst(2.0));
RooGenericPdf pdf("pdf", "gauss", gauss);
std::unique_ptr<RooAbsReal> integ1{gauss.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
integ1->Print("v");
std::cout << std::endl;
std::unique_ptr<RooAbsReal> integ2{pdf.createIntegral(x, *pdf.getIntegratorConfig(), nullptr)};
integ2->Print("v");
}
```
The integral of the Gaussian has the correct value (`V`) servers (the parameters of the Gaussian):
``` …
```
> [RF] Make sure value servers of integrals are next direct value servers

- tutorials/CMakeLists.txt
Veto also tutorial tests of RooStats and HistFactory if ROOT was built without RooFit.
Also removes the `fit/RooFitdemo.C` tutorial from the veto list, as this tutorial doesn't exist anymore.
Partially closes #11605.
> [RF] Veto `.py` tutorial tests of RooStats and HistFactory if ROOT is built without `roofit`

- bindings/pyroot/pythonizations/test/CMakeLists.txt
- bindings/pyroot/pythonizations/test/roofit/rooabscollection.py
- bindings/pyroot/pythonizations/test/roofit/roodataset.py
- bindings/pyroot/pythonizations/test/roofit/rooglobalfunc.py
This is more practical, because most RooFit tests are already here and and different from when these tests were in `roottest`, it's also to exclude them if ROOT is not built with RooFit enabled.
Technically independent of https://github.com/root-project/roottest/pull/909, but they go together.
Closes https://github.com/root-project/root/issues/11605.
> [RF][PyROOT] Move RooFit pythonization tests from roottest to main repo

- core/metacling/src/TClingCallbacks.cxx
Avoid loading ROOT modules while Clang is instantiating a template class from STL, leading to ODR checks with an incomplete class.
> [cxxmodules] Avoid lookup from system headers

- bindings/pyroot/pythonizations/CMakeLists.txt
- bindings/pyroot/pythonizations/python/ROOT/__init__.py
- bindings/pyroot/pythonizations/python/ROOT/_asan.py
- bindings/pyroot/pythonizations/test/import_load_libs.py
Address a number of AddressSanitizer failures with Python tests, due to the way we need to preload the ASan runtime and our configuration.
If I count correctly (there were a number of failures introduced last night, so I don't have a proper baseline), this fixes 7 tests:
* `pyunittests-pyroot-import-load-libs`
* `tutorial-roofit-rf104_classfactory-py`
* `roottest-python-JupyROOT-simpleCppMagic_notebook`
* `roottest-python-JupyROOT-thread_local_notebook`
* `roottest-python-JupyROOT-ROOT_kernel_notebook`
* `roottest-python-basic-basic`
* `roottest-python-regression-regression`
Moreover, `tutorial-rcanvas-df104-py` will show a proper AdressSanitizer failure.
> Tweaks for AddressSanitizer

- interpreter/cling/cmake/modules/CMakeLists.txt
- interpreter/cling/tools/driver/CMakeLists.txt
- The `CMAKE_GENERATOR_PLATFORM` is only set when manually specified with `cmake -A <platform>`. The `CMAKE_SIZEOF_VOID_P` variable is set automatically by the `project()` call (and it's used elsewhere in the code). This also breaks building with Ninja for Windows x64
- The `ClingTargets.cmake` where no correctly generated when running `cmake --install` on Cling. It looks like the `CLING_HAS_EXPORTS` was removed at some point, but the packaging code was never updated
Closes https://github.com/root-project/cling/issues/454
> Fix MSVC build

- tmva/sofie/inc/TMVA/ROperator_Shape.hxx
Fix the following issue in SOFIE:
```
n file included from /usr/include/c++/12.2.0/vector:70,
from /home/ahmat/cern/root/tmva/sofie/inc/TMVA/RModel.hxx:6,
from /home/ahmat/cern/root/tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx:4,
from /home/ahmat/cern/root/tmva/sofie_parsers/src/ParseShape.cxx:1:
In member function ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {long unsigned int}; _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>]’,
inlined from ‘void std::vector<_Tp, _Alloc>::push_back(value_type&&) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>]’ at /usr/include/c++/12.2.0/bits/stl_vector.h:1294:21,
inlined from ‘virtual std::vector<std::vector<long unsigned int> > …
```
> [TMVA][SOFIE] Fix SOFIE tests

- roofit/roofitcore/inc/RooHelpers.h
- roofit/roofitcore/res/RooFit/BatchModeDataHelpers.h
- roofit/roofitcore/res/RooFit/BatchModeHelpers.h
- roofit/roofitcore/res/RooFitDriver.h
- roofit/roofitcore/res/RooNLLVarNew.h
- roofit/roofitcore/src/BatchModeDataHelpers.cxx
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooFitDriver.cxx
- roofit/roofitcore/src/RooHelpers.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
- roofit/roofitcore/test/testTestStatistics.cxx
This PR applies many fixes to the new RooFit BatchMode to make sure that the NLL is created correctly, respecting all the command arguments of `RooAbsPdf::fitTo()` that were so far not considered.
More detail in the individual commit descriptions.
> [RF] Make NLL creation in new BatchMode feature complete

- tree/dataframe/test/datasource_arrow.cxx
Explicitly include `arrow/testing/builder.h` to make sure ArrayFromVector is available. Probably it was being included implicitly before.
> [v6.24][backport] Fix datasource_arrow.cxx test

- tmva/sofie/src/RModel.cxx
- tmva/sofie/test/TestCustomModelsFromONNX.cxx
This PR fixes the ordering of input tensors in the generated `infer` function. Previously, the tensors were iterated from an unordered map and thus were not in the order in which they were added. The correct ordering in which they are added is necessary for different layers in other parsers like Keras, and in the inference of GNN. With this PR, the tensors are iterated from a vector, thus the ordering is correct.
> [TMVA][SOFIE] Fix infer function input tensors order

- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/tabsmenu.fragment.xml
Parse and provide output of `.g` command
Automatically create such widget when `.g` typed in `RBrowser` command prompt
Use `TreeTable` element for more structured output
Using idea of @ferdymercury from #11295,
> Provide cling globals list in special RBrowser widget

- bindings/pyroot/pythonizations/test/tarray_getitem.py
- bindings/pyroot/pythonizations/test/tclass_dynamiccast.py
- bindings/pyroot/pythonizations/test/tvector3_getitem.py
- bindings/pyroot/pythonizations/test/tvectort_getitem.py
The changed tests were failing with errors like the one below:
```
File "root/bindings/pyroot/pythonizations/test/tclass_dynamiccast.py",
line 22, in test_dynamiccast
self.assertEquals(type(o_upcast), TObject)
^^^^^^^^^^^^^^^^^
AttributeError: 'TClassDynamicCast' object has no attribute 'assertEquals'.
Did you mean: 'assertEqual'?
```
These errors were observed with Python 3.12, but I guess they also happen with earlier versions of Python.
> [PyROOT] Replace non-existent assertEquals with assertEqual

- math/minuit/src/TMinuit.cxx
Fixing a dead link to `minuit.pdf` in `TMinuit.cxx`
> Fixing a dead link to minuit.pdf in TMinuit.cxx

- math/minuit2/src/DavidonErrorUpdator.cxx
This Pull Request adds more speaking information to users to make warnings of the type
`delgam < 0 : first derivatives increasing along search line`
useful.
Note that I do not have too much knowledge on the details of Minuit2, and the information messages of course reflect my state of knowledge. If someone else with more in-depth knowledge on Minuit2 could check that this is valid, that would of course be very valuable!
The motivation for this PR is that these warnings can hint to significant issues in the minimized function, however as a user, it is difficult to understand the problem or what to look for if one does not know how Minuit exactly works. Also they so far miss information needed to actually use these warnings to find problems with the minimized function. This commit adds …
> Minuit2: Explained delgam warning messages in info

- tutorials/xml/person.dtd
The bogus XML designation causes the file to fail XML diagnostic tests.
Test description:
Check that XML files included in the RPM payload are well-formed.
======================================== Test Output ========================================
xml:
----
Result: VERIFY
1) /usr/share/doc/root/tutorials/xml/person.dtd is not a well-formed XML file in root-tutorial on noarch
Waiver Authorization: Anyone
Details:
Extra content at the end of the document
Suggested Remedy:
Correct the reported errors in the XML document
> DTD files are not in XML format and should not claim to be

- roofit/roofitcore/inc/RooRealIntegral.h
- roofit/roofitcore/src/RooRealIntegral.cxx
- roofit/roofitcore/test/testRooRealIntegral.cxx
Recently, in commit https://github.com/root-project/root/commit/47c250898f3d3a1bb1718c73b84014a70809ffdf, the algorithm to figure out the value
and shape servers of integrals was rewritten. However, the new
implementation analyzed the computation graph by pointer, which caused a
wrong list of servers if one passed clones of the integration variables
to the integral constructor.
This commit fixes that, and also implements a unit test for this case.
Closes https://github.com/root-project/root/issues/11637, as the issue was caused by the integration variable
wrongly being registered as a value server of the integral. This made
the reproducer code in the issue thread very slow, because the integral
was reevaluated for each event.
> [RF] Ensure that using variable clones also works to specify integrals

- documentation/doxygen/Makefile
For some reason, `UNAME` was tested instead of `OS`
> [skip-ci] wrong variable was tested in Makefile

- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/ConstraintHelpers.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
Even though cloning the constraint term is technically only required when the computation graph is changed because global observables are taken from data, it is safer to clone the constraint model in general to reset the normalization integral caches and avoid ASAN build failures (the PDF of the main measurement is cloned too anyway, so not much overhead).
This can be reconsidered after the caching of normalization sets by pointer is changed to a more memory-safe solution.
> [RF] Always clone constraint term in `createNLL`

- tmva/sofie_parsers/src/RModelParser_ONNX.cxx
Register operators in the constructor of RModelParser_ONNX so that they can be updated when RegisterOperator is called  with the name of an existing operator.
>  [TMVA ][SOFIE] Register operators in the constructor of RModelParser_ONNX

- graf2d/graf/inc/TPave.h
Wrongly `Option_t `* was used.
> Use `const char *` as return type for `TPave::GetName()` method

- .github/workflows/code_analysis.yml
- .github/workflows/issues-nudge.yml
The previous versions use Node.js 12, which is deprecated for GitHub Actions.
> Update GitHub Actions

- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
As per a request by @mnowakgit, it would be useful if `RNTupleWriter::Fill()` returns the number of (uncompressed) bytes written - IIRC, TTree does a similar thing.
As `RFieldBase::Append()` already provides the count of written bytes, the changes included in this PR are minimal.
This PR fixes #11672.
> [ntuple] Make `RNTupleWriter::Fill()` return the number of uncompressed bytes written

- tree/ntuple/v7/doc/specifications.md
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/src/RFieldVisitor.cxx
- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/CustomStructLinkDef.h
- tree/ntuple/v7/test/SimpleCollectionProxy.hxx
- tree/ntuple/v7/test/ntuple_show.cxx
- tree/ntuple/v7/test/ntuple_types.cxx
This pull request introduces RField support for user-defined classes that behave as collections of elements.  These classes specify a "collection proxy" that provides access to the elements in the collection.
A legacy collection proxy is provided in the form of an instance of a class derived from `TVirtualCollectionProxy`.  The collection proxy for a class is typically set during initialization, usually using `TClass::CopyCollectionProxy()` or similar.
In this pull request, we introduce support for legacy collection proxies derived from the `TVirtualCollectionProxy` class, although in later stages, RNTuple might provide this functionality through an interface different interface.
At a bare minimum, the user is required to provide an implementation for the following functions in …
> [ntuple] Support the storage of collections using the `TVirtualCollectionProxy` interface

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py
As returning an unpacked tuple without parenthesis is only supported since Python 3.8
This patch fixes the following:
```
python3.7 -m py_compile _rdf_pyz.py
File "_rdf_pyz.py", line 253
return v, *args[1:]
^
SyntaxError: invalid syntax
```
> [PyROOT] Enclose tuple unpacking in return statement with parenthesis

- cmake/modules/RootConfiguration.cmake
- core/base/src/TSystem.cxx
ld: warning: -undefined dynamic_lookup may not work with chained fixups
Rely on explicit linking, and only specify -undefined dynamic_lookup where really needed.
> [cmake] Current Xcode issues a warning on -undefined dynamic_lookup:

- README/ReleaseNotes/v628/index.md
- io/io/src/TFile.cxx
In a meeting in IT I saw that ~200PB/year are being read from the `eoshome` instance via fuse, and I thought that maybe ROOT at least could try to do something smart and just redirect fuse traffic to XRootD if possible. The patch in this pull request does just that. When I talked to Axel about making this work, we wanted the redirection to not happen when using `file://file.root`, but it created some inconsistencies when using `TFile::Open` vs using `TChain` so the final implementation always attempts to redirect.
Below is a demo session of ROOT opening a file on EOS with (a former version of) the patch:
```sh
$ pwd
/eos/home-a/amadio
$ ls *.root
Run2012BC_DoubleMuParked_Muons.root
$ root.exe
------------------------------------------------------------------
| Welcome to ROOT 6.27/01 …
```
> Redirect TFile::Open() calls to XRootD protocol if possible

- main/CMakeLists.txt
`TCling.cxx`’s `RegisterCxxModules` loads explicitly several modules including `Core`, `Rint` and `RIO`.
When executing rootcling (for example for G__Net.cxx) *before* `G__Rint.cxx` was created and thus before `lib/Rint.pcm` was properly created, a default `lib/Rint.pcm` is auto-generated and registered as one of the dependencies.  Later the real `lib/Rint.pcm` is created is creation date is later than other `pcm` than depends-on/uses it’s creation time.  For example:
```
$ ls -lart lib/Net.pcm lib/MultiProc.pcm  lib/Imt.pcm lib/MathCore.pcm lib/Rint.pcm
-rw-r--r-- 1 pcanal pcanal  1158548 Nov 10 20:26 lib/Net.pcm
-rw-r--r-- 1 pcanal pcanal  1278392 Nov 10 20:27 lib/MultiProc.pcm
-rw-r--r-- 1 pcanal pcanal  2032752 Nov 10 20:27 lib/Imt.pcm
-rw-r--r-- 1 pcanal pcanal 12911448 Nov 10 20:27 …
```
> Add Rint as a dependency of rootcling

- tree/ntuple/v7/inc/ROOT/libdaos_mock/daos.h
This pull request adds the attribute `uint64_t iod_flags`, introduced in DAOS v2.0, to the definition of `daos_iod_t` in our mock implementation of libdaos for development. See: https://docs.daos.io/v2.0/doxygen/html/structdaos__iod__t.html.
> [ntuple,daos] Add missing attribute to IOD structure mock definition

- math/genvector/inc/Math/GenVector/LorentzVector.h
- math/physics/CMakeLists.txt
- math/physics/inc/TLorentzVector.h
- test/stressVector.cxx
As a wonderful side-effect, this adds support for construction from a TLorentzVector.
See https://root-forum.cern.ch/t/problem-initializing-a-4-vector/50789
> [physics] Add conversion to ROOT::Math::XYZTVector

- tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
- tree/ntuple/v7/test/ntuple_storage_daos.cxx
This pull request introduces ntuple management at the DAOS container level, extending support for more than one ntuple to populate a container.
- Support for up to 2\^32 - 1 ntuples in a DAOS container, by assigning an index to a previously-unused portion of the DAOS Object ID address space. The index thus induces a subspace dedicated for all objects belonging to a given ntuple. The zeroth space (index `0`) is reserved for any container-wide metadata objects that may need to be stored in the future.
- `ROOT::Experimental::Detail::RDaosContainerNTupleLocator` is a structure that concentrates the functionality for locating and retrieving stored metadata from an ntuple by its name.
- The structure hashes the name into a well-distributed 32-bit index. Collisions are expressly forbidden to …
> [ntuple,daos] Support multiple ntuples per container

- tmva/tmvagui/src/rulevisCorr.cxx
- tmva/tmvagui/src/rulevisHists.cxx
```
rulevisCorr.cxx:173:43: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
173 |             snprintf( cn, 20, "rulecorr%d_", countCanvas+1 );
|                                           ^
rulevisCorr.cxx:173:21: note: ‘snprintf’ output between 11 and 21 bytes into a destination of size 20
173 |             snprintf( cn, 20, "rulecorr%d_", countCanvas+1 );
|             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> [tmvagui] Fix snprintf warning:

- io/io/src/TFile.cxx
In order to mark the file as zombie when this happens, I had to change a `goto zombie` into calls to a dedicated helper lambda (done in a separate commit). Otherwise I would have had to move around a few lines just so that the compiler would let me jump from the sanity check to the zombie label (compilers don't allow jumps across variable initializations).
This fixes https://github.com/root-project/root/issues/10039.
> [IO] Improve error message when no TFile::Open for remote files 

- core/base/src/TApplication.cxx
- gui/gui/src/TGApplication.cxx
Allow to use the `Canvas.UseScreenFactor` entry in `system.rootrc` to automatically resize the `TCanvas` and `TBrowser` on high resolution displays
> Use Canvas.UseScreenFactor on high resolution screens

- tutorials/io/loopdir11.C
~~~~
Start  672: tutorial-io-loopdir
690/1156 Test  #666: tutorial-io-double32 ................................................   Passed    2.42 sec
Start  673: tutorial-io-loopdir11
691/1156 Test  #673: tutorial-io-loopdir11 ...............................................   Passed    0.76 sec
Start  674: tutorial-io-mergeSelective
692/1156 Test  #672: tutorial-io-loopdir .................................................***Failed  Error regular expression found in output. Regex=[Error in <]  1.23 sec
Processing /builddir/build/BUILD/root-6.26.10/tutorials/io/loopdir.C...
Info in <TCanvas::Print>: ps file hsimple.ps has been created
Info in <TCanvas::Print>: Current canvas added to ps file hsimple.ps
Info in <TCanvas::Print>: Current canvas added to ps file hsimple.ps
Info in …
> Use different filename in loopdir.C and loopdir11.C to avoid race condition

- math/vecops/inc/ROOT/RVec.hxx
- math/vecops/test/vecops_rvec.cxx
Before this commit, calling `RVec<T> v(n)` where `T` is a move-only type would fail to compile because, internally, the operation was implemented in terms of a std::uninitalized_fill of the first `n` elements in the buffer, and std::uninitalized_fill needs the type to be copy-assignable.
With this patch we use (a backport of) C++17's
std::uninitialized_value_construct instead for that case, which is works for move-only types as well.
> [VecOps] Fix compilation errors in case of RVec of move-only types

- tree/ntuple/v7/doc/architecture.md
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/CustomStructLinkDef.h
- tree/ntuple/v7/test/ntuple_types.cxx
- tree/ntuple/v7/test/rfield_vector.cxx
Introduces the "trivially constructible" and "trivially destructible" traits for the types wrapped by an RField. Maintaining these traits allows for optimizations when reading collections: for collections of simple types (e.g., `int`s, `float`s), we don't need to call the element constructors and destructors when the collection changes size from event to event.
For the vector-heavy ATLAS OpenData benchmark, this results in a 5-10% performance improvement both with RDF and with RNTuple views (hot disk cache, zstd compressed input).
Fixes #10520
> [ntuple] Store and use type traits in RField

- io/io/src/TFile.cxx
- tree/treeplayer/src/TFileDrawMap.cxx
As described [here](https://github.com/root-project/root/issues/11723), `TFile::DrawMap` produced a weird plot, mostly black. With this PR the plot is improved.
```
auto f = new TFile("hsimple.root");
f->DrawMap();
```
Gives:
- Use the current color map to paint the various branches of trees,
- Paint the axis label and titles,
- Improve the help,
- fix typos
> Improve TFile::DrawMap

- config/rootrc.in
- core/base/src/TApplication.cxx
- etc/plugins/TVirtualTreeViewer/P010_TTreeViewer.C
- etc/plugins/TVirtualTreeViewer/P020_RTreeViewer.C
- proof/proof/src/TDSet.cxx
- tree/treeplayer/src/TTreePlayer.cxx
- tree/webviewer/inc/ROOT/RTreeViewer.hxx
- tree/webviewer/src/RTreeViewer.cxx
There is fictional `TVirtualTreeViewer` class and `RTreeViewer` plugin is activated when web display is configured.
Allows to use web-based canvas and tree viewer together like in `tutorials/tree/tree0.C` example
> Provide plugin for RTreeViewer

- graf2d/gpad/inc/TCanvas.h
- graf2d/gpad/inc/TPad.h
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TPad.cxx
- gui/webgui6/src/TWebCanvas.cxx
1. Let assign private members directly - without workaround with GetClassMemberOffset
2. Use `TString::Format()` instead of `Form()` in TPad.cxx
3. Provide function to generate unique canvas name - used 3 times in TCanvas.cxx
> [gpad] Declare TWebCanvas as friend class for TPad/TCanvas

- graf2d/postscript/src/TPDF.cxx
The problem was seen here:
https://root-forum.cern.ch/t/pattern-style-3004-looks-different-on-screen-and-when-saved-into-pdf/52369
> fix pdf patterns

- core/base/src/TApplication.cxx
- core/base/src/TColor.cxx
- core/base/src/TEnv.cxx
- core/base/src/TMacro.cxx
- core/gui/src/TContextMenu.cxx
- core/gui/src/TGuiFactory.cxx
- core/thread/src/TThread.cxx
Reduce usage of unsafe `Form()` function, especially in Thread.cxx
> Use `TString::Format()` instead `Form()` in core classes

- interpreter/cling/lib/UserInterface/UserInterface.cpp
A minor memleak in cling::UserInterface::runInteractively() reported by valgrind.
> [cling] Delete UITabCompletion* with unique_ptr to prevent memleak

- roofit/roofitcore/inc/RooPlot.h
- roofit/roofitcore/src/RooPlot.cxx
- roofit/roofitcore/src/RooWorkspace.cxx
This is a backport of all the relevant bugfix RooFit PRs that were recently merged to master to v6-26-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/11566
2. https://github.com/root-project/root/pull/11584
Only the first commit that is not code modernization
Related to https://github.com/root-project/root/issues/11534.
> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 24

- cmake/modules/SearchInstalledSoftware.cmake
Newer CMake uses extraction timestamps for extracted files, instead of the timestamp as stored in the tar file, see
https://cmake.org/cmake/help/latest/policy/CMP0135.html#policy:CMP0135 This causes (massive) problems with configure/Makefile tar files, where the configure/Makefile dependencies (e.g. autoconf) might be newer than configure/Makefile, causing configure/Makefile to wanting to regenerate themselves because they are supposedly out of date.
For anything with "./configure", force the timestamp as stored in the tar file.
Fixes https://github.com/root-project/root/issues/11743
> [cmake] Tell CMake >= 3.24 to use tared timestamps:

- hist/hist/src/TH2.cxx
- hist/hist/src/TH3.cxx
The Sum in x and y was not updated when the X and Y axis are not extendable or are not alphanumerics. 
This PR fixes ROOT #11746
> [hist] Fix computation of statistics in TH2::Fill(nameX, nameY)

- builtins/nlohmann/CMakeLists.txt
- builtins/nlohmann/json_fwd.hpp
For systems with old `nlohmann/json.hpp` ROOT fails to build while it can find not matching `json_fwd.hpp`.
Master branch uses newer nlohmann/hson.hpp, therefore one cannot backport changes directly
> Provide json_fwd.hpp for nlohmann 3.9.1 [6.26]

- roofit/roofitcore/inc/RooRealIntegral.h
- roofit/roofitcore/src/RooGenProdProj.cxx
- roofit/roofitcore/src/RooRealIntegral.cxx
- roofit/roofitcore/test/testRooRealIntegral.cxx
In the RooRealIntegral and RooGenProdProj classes, the normalization sets were so far not forwarded to the servers, which resulted in undefined normalization sets for integrated PDFs as reported in #11476.
A unit test that covers #11476 and the related JIRA issue ROOT-9436 is also implemented.
Closes #11476.
> [RF] Use of proxy norm sets in RooRealIntegral and RooGenProdProj

- documentation/doxygen/MakeRCanvasJS.C
- documentation/doxygen/MakeTCanvasJS.C
Now the .C scripts used to build the reference guide are compiled using AClic to build the doc faster.
Some includes were missing.
> [skip-ci] add missing includes

- roofit/roofit/inc/RooVoigtian.h
- roofit/roofit/src/RooVoigtian.cxx
The RooVoigtian uses the FWHM (Full width half maximum) as the width of the Breit-Wigner part, which is the usual definition from HEP text books because it corresponds to the decay width.
However, other sources define the Breit-Wigner profile with the HWHM (half width half maximum), for example the Wikipedia article: https://en.wikipedia.org/wiki/Cauchy_distribution
This can easily lead to mistakes if people use the RooVoigtian with the HWHM.
With this commit, it is explicitly stated in the docs that the RooVoigtian takes the FWHM, both in the constructor and the overall class documentation.
Furthermore, some other small improvements are made to the docs of the RooVoigtian, like converting some of the function documentations to doxygen.
Closes #11757.
> [RF] Improve RooVoigtian documentation

- roofit/roofitcore/inc/RooAbsMCStudyModule.h
- roofit/roofitcore/inc/RooMCStudy.h
- roofit/roofitcore/src/RooMCStudy.cxx
The functionality to fit pulls in the RooMCStudy with a Gaussian is
widely used, and it's not good that it uses a RooGenericPdf because of
the numeric integration.
Probably the RooGaussian was not used because unlike the RooMCStudy, the
RooGaussian is not in RooFitCore and using it would result in a circular
dependency.
This commit suggests a way to use the RooGaussian anyway, via the
RooWorkspace factory interface.
The PR also includes a second commit that gets rid of manual memory management in the `RooMCStudy` class, which also affects the friend class `RooAbsMCStudyModule` that accesses some protected members of the RooMCStudy.
> [RF] Don't use RooGenericPdf for pull fitting in RooMCStudy

- roofit/roofit/src/RooPoisson.cxx
- roofit/roofit/test/testRooPoisson.cxx
In the RooPoisson integration code, it is hardcoded to return 1.0 if the upper boundary is infinite. But this should only be done if the lower boundary is not greater than zero.
Closes #10868.
> [RF] Correct RooPoisson integral if integrated from a > 0 to infinity

- tree/ntuple/v7/doc/specifications.md
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/CustomStructLinkDef.h
- tree/ntuple/v7/test/ntuple_types.cxx
This pull request introduces RField support for C style arrays.  In particular, it provides a `RField<T[N]>` template specialization and allows for parsing of types of the form `T[n][m]...` in `RFieldBase::Create()`
Actual RField implementation is provided by RArrayField, which currently does not support multi-dimensional arrays, although it should be trivial to extend it (if need be in a future PR) to support row-major (C order) multi-dimension arrays.
Additionally, prior to this PR, class members whose type was an array of the form `T[n]` were stored as a scalar.  This is considered a bug (see #11732 for all the details).
The implementation provided here also fixes issue #11732.
- Add `RField<ItemT[N]>` template specialization that matches single-dimension arrays.
- Update …
> [ntuple] C-style array RField support

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RResultPtr.hxx
It's not the responsibility of RResultPtr to check for unused lazy Snapshots.
> [DF] Move warning about lazy Snapshot to appropriate helpers

- tree/dataframe/src/RDFInterfaceUtils.cxx
Removes ambiguity in case a column name ends with a dot, which incidentally is something that causes "unknown column name" error messages commonly enough.
Sibling PR in roottest: https://github.com/root-project/roottest/pull/917
> [DF] Add "" around unknown column names in error message

- roofit/roofitcore/src/RooMinimizer.cxx
- roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
- roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
- roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
- roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
Note that this PR includes the commit of #11716.
Apart from the stuff in #11716, this PR fixes the additions previously made in #10966. The implementation there had some bugs, most importantly:
1. Creation went wrong when using MultiProcess-mode for the gradient, but serial mode for the likelihood. This led to larger differences from full-serial mode than expected. We can now tighten expectations in tests again due to this fix.
2. Double-MultiProcess-mode (both gradient and likelihood) did not work when using offsetting, because setOffsetting would not propagate to worker processes correctly for all involved objects. This is now fixed as well.
> [RF] Fixes for using MultiProcess LikelihoodJob

- roofit/roofitcore/inc/RooMinimizer.h
- roofit/roofitcore/src/RooAbsMinimizerFcn.cxx
- roofit/roofitcore/src/RooAbsMinimizerFcn.h
- roofit/roofitcore/src/RooMinimizer.cxx
- roofit/roofitcore/src/RooMinimizerFcn.cxx
- roofit/roofitcore/src/RooMinimizerFcn.h
- roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
- roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
In https://github.com/root-project/root/pull/11604, many redundancies in the RooMinimizer design became apparent,
and this PR aims to avoid them. The following changes are made:
* The signature of `RooAbsMinimizerFcn::Synchronize()` is changed to not
take a `bool optConst` argument anymore. Ths is because the value of
the argument that was passed by the RooMinimizer instance was always a
member of the `RooAbsMinimizerFcn` anyway.
* Change type of `RooMinimizer::Config::verbose` to `bool`, because
`setVerbose()` also takes a `bool` flag.
* Give `RooAbsMinimizerFcn` access to the RooMinimizer configuration
such that configuration data does not need to be duplicated.
A separate commit in this PR formats the code of the `RooMinimizerFcn`.
> [RF] Remove redundant configuration members of `RooAbsMinimizerFcn`

- roofit/roofitcore/src/RooRealIntegral.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testGenericPdf.cxx
- roofit/roofitcore/test/testRooPolyFunc.cxx
- roofit/roofitcore/test/testRooRealIntegral.cxx
This is a direct fixup to commit https://github.com/root-project/root/commit/faa42a17e3614efbd97a91194243157b77e74fde. That commit tried to make
it possible to use also variable clones as integration variables, but it
failed to cover the case where the integration variable is only an
indirect server of the integrated function. This was because
`valueClients()` used for the graph traversal was still called on the
clone, not the variable in the actual computation graph of the
integrated function.
This commit fixes this by passing the correct variable to
`unmarkDepValueClients` to begin with.
A unit test for this case is also implemented.
As such, this PR is part of the series of PRs that redesigned the
RooRealIntegral client-server interface:
* …
> [RF] Ensure using variable clones also works for integrals - part 2

- roofit/roofitcore/inc/RooAbsTestStatistic.h
- roofit/roofitcore/res/RooNLLVarNew.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
It is possible to set ranges for a `RooCategory`, suggesting that this
is a possible way to select only a subset of channels in a simultaneous
fit. However, this was not working so far, and this commit implements
that.
This commit implements that feature for both the old test statistic
classes and the new BatchMode.
As now it also makes sense to fit to a range that is not defined for the
observables but for the categories only, the message that is printed
when your observables don't define the range is demoted from a warning
to an info message.
The debug message that was printed when channels are not selected also
got removed, because it had some overhead from `sumEntries`, the
debugging prints are rarely used, and the message is not true anymore
because chanels might also be skipped now …
> [RF] Implement consideration of category range in simultaneous fits

- gui/browsable/src/RNTupleBrowseProvider.cxx
- gui/browsable/src/TDirectoryElement.cxx
- gui/browserv7/src/RBrowserTCanvasWidget.cxx
- gui/webgui6/inc/TWebCanvas.h
- gui/webgui6/src/TWebCanvas.cxx
- js/build/jsroot.js
- js/modules/core.mjs
- js/modules/gpad/TPadPainter.mjs
- ui5/browser/controller/Browser.controller.js
- ui5/canv/controller/Canvas.controller.js
- ui5/canv/view/Canvas.view.xml
Fix introduced recently bug which broke handling of subdirectories and RNTuple
Provide "Divide" method for TCanvas, use in `RBrowser` active pad for drawing. 
It is convenient method to display many objects at the same time.
> [rbrowser] Fix handling of RNTuple and sub-directories

- geom/geom/src/TGeoManager.cxx
The default was to lock the units by default, but this forced the user to unlocking via LockDefaultUnits(false) even if no geometry was created, otherwise a Fatal was issued. The patch allows changing the units once in the beginning and locks them automatically upon the definition of any element/material
Fixes an unintended behavior
The static flag `gGeometryLocked` is now set to false by default, and changed to true upon the first invocation of SetDefaultUnits, which all element/material constructors call. As a result, any subsequent attempt to change the units must be made by manual unlocking via `LockDefautUnits(false)`, or it will issue a fatal error.
> [Geom] Fix behaviour of locking default units

- geom/geompainter/src/TGeoChecker.cxx
Fixes #11784
Fixes a bug in overlap checking.
Tessellated shapes cannot be used for overlap checking, because they do not provide navigation functionality. This PR skips checks when one of the two shapes potentially overlapping is a tesselation.
This PR fixes #11784
> [Geom] Skip overlap checking if a partner is a tessellated shape.

- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
- roofit/roofitcore/test/testGlobalObservables.cxx
- roofit/roofitcore/test/testRooAbsPdf.cxx
- roofit/roofitcore/test/testRooProdPdf.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
Get rid of the remaining memory leaks, avoid code duplication for simultaneous binned fit test, etc.
There is also an additional commit that continues the campaign of making the `roofitcore` tests depend less on `roofit`.
> [RF] Refactor `testLikelihoodGradientJob.cxx`

- io/io/src/TStreamerInfo.cxx
On Ubuntu 22, gcc 11.2 with get the apparently spurious message:
```
aliceesdProjectSource.cxx: In copy constructor ‘AliESDkink::AliESDkink(const AliESDkink&)’:
aliceesdProjectSource.cxx:992:54: warning: writing 16 bytes into a region of size 8 [-Wstringop-overflow=]
992 |    for (Int_t i=0;i<4;i++) (&(fTPCdensity[0][0]))[i] = (&(rhs.fTPCdensity[0][0]))[i];
|                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from aliceesdProjectHeaders.h:20,
from aliceesdProjectSource.cxx:3:
AliESDkink.h:36:26: note: destination object ‘AliESDkink::fTPCdensity’ of size 8
36 |    Float_t               fTPCdensity[2][2];    //tpc cluster density before and after kink
|                          ^~~~~~~~~~~
^~~~~~~~~~~
```
I.e. complaining about having only …
> MakeProject: workaound deficiency in gcc 11.2 warning

- roofit/multiprocess/test/test_Queue.cxx
#11627 still had minor compile warnings from wrong printf formatting. This PR fixes that.
> [RF] MultiProcess test_Queue.cxx compile warning fix

- geom/gdml/inc/TGDMLParse.h
- geom/gdml/src/TGDMLParse.cxx
In case TGeoManager is set to work with default ROOT units [cm,deg] and the GDML parser reads entities missing explicit units, it issues now a warning. This is due to the fact that the default unit in this case will not match the unit types defined in the GDML schema [mm,rad]. An automatic fix cannot be done because it would introduce backward incompatibilities. This closes #11781
Produces warnings for GDML files with entities missing explicit unit declaration
The number of entities missing declaration of units is reported. The warning proposes the alternative fix of using Geant4 units supported by TGeo. 
This PR addresses #11781
> [Geom] GDML parser warns about entities missing a unit definition.

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The RDF returned by a Snapshot action comes with a default column list that corresponds to the names of the columns that have been snapshotted. This is a fairly obscure feature which probably does not get much use, but in the case of aliased columns there was a mismatch: in the snapshotted file columns would retain the alias, while in the default column list the _resolved alias_ (i.e. the original column name) would be used.
> [DF] Fix default columns for Snapshot result

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
It's an anti-pattern that introduces extra copies when moving from these objects. See also
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c12-dont-make-data-members-const-or-references .
> [DF] Do not mark data members as const

- core/base/inc/TSystem.h
- core/base/src/TSystem.cxx
- core/unix/inc/TUnixSystem.h
- core/unix/src/TUnixSystem.cxx
As mentioned [here](https://root-forum.cern.ch/t/regex-usage-in-tsystem-listlibraries/52503), it is difficult to list libraries using regular expressions. The `regexp` parameter is in fact a wildcard that does not work when the libraries names contain `/` (see the help of [TRegexp::MakeWildcard](https://root.cern/doc/master/classTRegexp.html#ab2762d059ace7f79a45b76b0f3b1a1b1). An additional optional parameter allows to use the `regexp` parameter as a simple string. Only the libraries containing this character string will be listed.
Example:
```
root [0] gSystem->ListLibraries("Core")
Loaded shared libraries
=======================
-----------------------
0 libraries loaded
=======================
root [1] gSystem->ListLibraries("Core",kFALSE)
Loaded shared libraries …
```
> Improve ListLibraries

- roofit/roofitcore/inc/RooHist.h
- roofit/roofitcore/src/RooHist.cxx
- roofit/roofitcore/test/CMakeLists.txt
- roofit/roofitcore/test/testRooHist.cxx
In the non-uniform binning case, the `RooHist` that you get from
plotting a RooDataHist doesn't contain the number of events, but the
number of events normalized by the bin width.
This means that `RooHist::getFitRangeNEvt()` was returning wrong
results. To fix this, a new data member is added to the `RooHist`, which
tracks the original number of events in each bin before the scaling.
A unit test that covers this is also implemented.
Closes JIRA ticket ROOT-9649:
https://sft.its.cern.ch/jira/browse/ROOT-9649
A second commit in this PR also does some code modernization of the `RooHist`.
> [RF] Keep track of the original number of events per bin in `RooHist` for `RooHist::getFitRangeNEvt()`

- cmake/modules/RootConfiguration.cmake
- config/rootssh.sh
- core/base/src/TROOT.cxx
- gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
- gui/webdisplay/src/RWebWindowsManager.cxx
- net/http/CMakeLists.txt
- net/http/civetweb/civetweb.c
- net/http/src/TCivetweb.cxx
- net/http/src/THttpServer.cxx
1. Support unix sockets in `THttpServer`, fix civetweb warning
2. Let configure unix socket for webgui widgets
3. Introduce `rootssh.sh` script which use such ferature
In `rootssh.sh` special tunnel is created which forward requests from local http port to remote unix socket.
In remote session root will automatically use socket which specified as `ROOT_WEBGUI_SOCKET` environment variable.
This socket file by default get `0700` mode - means only user can accuse it. 
This solves most of security issues with using of ROOT webgui on public nodes!
`rootssh.sh`  also creates listener which get informed when new window is started on remote session
and automatically popup web browser using `xdg-open $url` command
Typical session should look like:
```
[localhost] rootssh.sh user@remotehost …
```
> [webgui] let use unix sockets, introduce `rootssh.sh` script

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The weak pointer was used to track whether the node that Report was hanging from went out of scope, but since a while the ownership model of nodes in the computation graph (child owns parent) guarantees that as long as the ReportHelper (and the corresponding action node) is around, the node it hangs from will be around as well.
We can use a simple raw pointer instead.
> [DF] Remove unnecessary weak ptr from ReportHelper

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py
From this 
```python
>>> df = ROOT.RDataFrame("Events", "root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root")
>>> df.GetColumnNames()
<cppyy.gbl.std.vector<string> object at 0x55c82c6e17a0>
```
To this
```python
>>> df = ROOT.RDataFrame("Events", "root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root")
>>> df.GetColumnNames()
{ "Muon_charge", "Muon_eta", "Muon_mass", "Muon_phi", "Muon_pt", "nMuon" }
```
> [PyROOT] Show std::vector contents at the prompt instead of default repr

- core/thread/inc/ROOT/RConcurrentHashColl.hxx
- core/thread/src/RConcurrentHashColl.cxx
As reported by Chris Jones:
> https://github.com/root-project/root/blob/6a1389a16625718f2750ba90156d3f8f9d5dfe8a/core/thread/src/RConcurrentHashColl.cxx#L53-L62
> There is a race condition between line 57 and 58. Between releasing the read lock and taking the write lock, another thread could have inserted the same hash.
And indeed, the unconditional return of `true` within the write lock means that in the case of the race condition then the result is incorrect.
(a) the only consequence of the race is a small performance loss and the return value of the function is incorrect (true instead of false)
(b) but the function does not seem to be called anywhere.
The consequence of (a) should be if (b) is incorrect that a StreamerInfo is being re-read when it does not need to, so 'only'  a …
> RConcurrentHashColl: remove unused (internal) function

- tutorials/roostats/rs101_limitexample.C
- tutorials/roostats/rs101_limitexample.py
- tutorials/roostats/rs_numberCountingCombination.C
This is done because the manual memory management in the `rs101_limitexample` tutorial deleted the object in the wrong way.
For example, it deleted the workspace first, and then the `lrinterval` object that pointed to the PDF stored in the workspace. This caused crashes in configurations that are sentitive to the resulting dangling pointers, like in the new BatchMode.
> [RF] Avoid manual memory management in the rs101 tutorial

- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooVectorDataStore.cxx
- roofit/roofitcore/test/testRooDataSet.cxx
Make CutRange() also considers the variables not selected by electVars()
in RooAbsData::reduce().
If CutRange() does consider the unselected variables or not was not
specified in the documentation so far, but now it is clearly stated.
This change supports the workflow where a dataset contains additional
observables not used by the fit model, but you still want to use these
variables to select a subset of the data via the `Range()` command
argument to `RooAbsPdf::fitTo()`.
Closes JIRA ticket ROOT-8040:
https://sft.its.cern.ch/jira/browse/ROOT-8040
@will-cern FYI
> [RF] Make `CutRange()` also consider unselected vars in `RooAbsData::reduce()`

- gui/webdisplay/src/RWebWindowsManager.cxx
Fix the following warning on Windows:
```
RWebWindowsManager.cxx(673,8): warning C4067: unexpected tokens following preprocessor directive - expected a newline
```
> Fix preprocessor warning on Windows

- roofit/roofitcore/src/RooMinimizer.cxx
nWorkers setting was actually not being set when the RooMinimizer was called with the nWorkers setting enabled in `RooMinimizer::Config`. Now that is fixed by passing the `RooMinimizer::Config::nWorkers` setting to the multiprocessing internal config.
> [RF] Fix nWorker setting in RooMinimizer input config

- tree/dataframe/src/RDFHelpers.cxx
RunGraphs makes a summary log entry for the jitting time of all computation graphs that are being run concurrently. Generally this is ok, but in the case users specifically requested a log level of kDebug+10 or higher this would accidentally silence the logging of what code is being jitted.
With this patch, if log level is kDebug+10 or higher, RunGraphs avoids silencing inner logs.
> [DF] Let RunGraphs log what code is being jitted

- roofit/roofit/inc/RooHistConstraint.h
- roofit/roofit/inc/RooLagrangianMorphFunc.h
- roofit/roofit/src/RooHistConstraint.cxx
The new BatchMode uncovered another inconsistency in one of the old
RooFit classes, this time the RooHistConstraint.
The RooHistConstraint was only used for constrainet PDFs, which get
collected by the RooConstrained sum. The old RooFit evaluates these
constrained PDFs via `RooAbsPdf::getLogVal()`, while the new BatchMode
uses the usual PDF evaluation code paths.
Now, the problem is that the RooHistConstraint is self normalized,
meaning it doesn't need to be divided by its integral. This is correctly
considered in `getLogVal()`, where the normalization set is ignored.
However, in the usual evaluation code path via `getVal()`, the PDF is
not considered as self normalized. This results in numeric integral
terms that make fits with the new BatchMode take forever.
To fix this, this commit …
> [RF] Syncronize RooHistConstraint::evaluate() with getLogVal()

- roofit/roofitcore/inc/RooProdPdf.h
- roofit/roofitcore/src/NormalizationHelpers.cxx
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/test/testRooProdPdf.cxx
The RooProdPdf is not trivial to deal with in BatchMode, because its
actual servers depend on the normalization set.
One should rather think of the RooProdPdf as something like a caching
PDF, but instead of creating a cached HistPdf for a given normalization
set, it creates an internal computation graph representing the
normalized product for a given normalization set.
This internal computation graph is not expsed via the usual
client-server interface. However, this is strictly required for the new
BatchMode: internal computation graphs are not allowed because the
RooFitDriver would not be able to manage memory copies between host and
device, and also schedeuling.
For this reason, BatchMode support is removed from the RooProdPdf class.
We only keep a `RooProdPdf::calculateBatch` function …
> [RF] New mechanism to evaluate a `RooProdPdf` for a given normalization set in BatchMode

- graf2d/gpad/src/TPad.cxx
This fixes #11747
As seen in https://github.com/cms-sw/cmssw/issues/40091 the code in `TPad::Close`:
```
if (fPrimitives)
fPrimitives->Clear();
if (fView) {
if (!ROOT::Detail::HasBeenDeleted(fView)) delete fView;
fView = nullptr;
}
if (fFrame) {
if (!ROOT::Detail::HasBeenDeleted(fFrame)) delete fFrame;
fFrame = nullptr;
}
```
is failing in the case of reading a pad from a file in at least some circumstances.
`TPad::Streamer` explicit set the bit `kCanDelete` on all objects in the list of primitives, thus including the view and the frame which have their `kCanDelete` bit explicitly reset elsewhere (in the code run during the initial creation of the frame and view).
This means that avoiding the a double deletion (the first is now during the `fPrimitives->Clear()`) relies on the heuristic of …
> Avoid TPad::fFrame double delete when read from file

- tree/treeplayer/src/TTreeReaderArray.cxx
This applies the change similar to 16f11e363c5 and 53a610fa2de that were done on TTreeReaderValue to the array case.
In particular it properly handle the double/Double32_t, float/Float16_t, Long64_t, char/signed char 'spurrious' difference/rejection.
> TTreeReaderArrayBase::CreateProxy Improve numerical type matching.

- graf2d/gpad/src/TPad.cxx
This fixes #11747
As seen in https://github.com/cms-sw/cmssw/issues/40091 the code in `TPad::Close`:
```
if (fPrimitives)
fPrimitives->Clear();
if (fView) {
if (!ROOT::Detail::HasBeenDeleted(fView)) delete fView;
fView = nullptr;
}
if (fFrame) {
if (!ROOT::Detail::HasBeenDeleted(fFrame)) delete fFrame;
fFrame = nullptr;
}
```
is failing in the case of reading a pad from a file in at least some circumstances.
`TPad::Streamer` explicit set the bit `kCanDelete` on all objects in the list of primitives, thus including the view and the frame which have their `kCanDelete` bit explicitly reset elsewhere (in the code run during the initial creation of the frame and view).
This means that avoiding the a double deletion (the first is now during the `fPrimitives->Clear()`) relies on the heuristic of …
> v6-26: Avoid TPad::fFrame double delete when read from file

- core/base/inc/TApplication.h
- core/base/inc/TROOT.h
- core/base/src/TApplication.cxx
- core/base/src/TColor.cxx
- core/base/src/TROOT.cxx
- core/gui/inc/TBrowser.h
- core/gui/src/TBrowser.cxx
- core/gui/src/TGuiFactory.cxx
- graf2d/gpad/src/TCanvas.cxx
- tree/treeplayer/src/TTreePlayer.cxx
If respective widget (TBrowser, TCanvas, TTreeViewer) want to start web-based implementation,
only minimal graphics initialization is necessary.
Let possibility to really initialize graphics when web display is disabled and normal widget is started.
In TCanvas use batch gui factory to create web-based TWebCanvas. It is done for the case when normal graphics (with its gui factory) was loaded, but then web display was enabled.
> Adjust `TApplication::InitializeGraphics()` for web case

- bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
- bindings/pyroot/cppyy/patches/0001-cppyy-Do-not-set-batch-mode-let-ROOT-handle-that.patch
- bindings/pyroot/pythonizations/python/ROOT/__init__.py
With `ROOTSYS` unset and no `DISPLAY` variable, this setup causes a spurious warning about an unset `DISPLAY`. `TROOT()` calls `SetBatch(true)`, then cppyy "agrees", and `ROOT/__init__.py` tries to revert that. Just let everyone keep their hands off `SetBatch()` (as is done in newer cppyy anyway).
> [cppyy] Do not set batch mode, let ROOT handle that:

- CMakeLists.txt
- cmake/modules/SearchInstalledSoftware.cmake
We always wanted to use "old", and my prior attept to convince CMake to use "DOWNLOAD_EXTRACT_TIMESTAMP false" did not work. So instead of passing this to each ExternalProject_Add, just switch the global policy to OLD.
> [cmake] Switch CMP0135 to OLD:

- core/base/inc/TColor.h
Hello ROOTers! This is a proposal to allow `kRainBow` or `kRainbow`. I think I have accidentally called `kRainbow` a thousand times. But it is a justified accident, since rainbow is one word.
C/C++ enums allow multiple keys to have the same value, so this proposal would not impact existing use of `kRainBow`.
> Update TColor enum since rainbow is one word

- tree/tree/src/TBranch.cxx
* TBranch::GetEntriesSerialized: actually reuse baskets inside of simply leaking them
This applies fixes that were introduce to GetBulkEntries in 61c9927 and 60ad148
* Prevent leak of ready-to-reuse basket.
This fixes https://github.com/root-project/root/issues/11853
> Avoid leaking TBaskets in Bulk I/O operations

- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/ntuple_basics.cxx
- tree/ntuple/v7/test/ntuple_types.cxx
As per a conversation with @jblomer on 16/11/2022, and ROOT I/O meeting on 25/11/2022 (and probably also related to https://github.com/root-project/root/pull/11628#discussion_r1023123773), this pull request adds support for per field post-read callback functions to be invoked after reading a value object.
Such callbacks can be used to inspect/modify the value object after reading, e.g. to initialize transient members.
The conclusion of a previous discussion is that we should not allow views on fields with a mappable type and that have a read callback.
The signature of a read callback function is
```c++
void callback_func(RFieldValue &);
```
- Fields with a mappable type need to be distinguished from "simple" fields (i.e. those that have no additional actions after reading).  Thus, the …
> [ntuple] RField: add support for (per field) post-read callback functions

- interpreter/cling/include/cling/std.modulemap
this causes issues with C++20 module composability and the need for textual is unclear.
> [cling] Make string_view module non-textual:

- interpreter/cling/lib/Interpreter/CIFactory.cpp
This PR fixes the issue #10875 _HAS_CONDITIONAL_EXPLICIT=0 won't work with VS 2022 17.4
> Fix compilation with VS 2022 v17.4

- bindings/jupyroot/python/JupyROOT/helpers/utils.py
- graf2d/gpad/src/TPad.cxx
- graf2d/gpadv7/src/RCanvas.cxx
- gui/webgui6/inc/TWebCanvas.h
- gui/webgui6/inc/TWebSnapshot.h
- gui/webgui6/src/TWebCanvas.cxx
- gui/webgui6/src/TWebPadPainter.cxx
- gui/webgui6/src/TWebSnapshot.cxx
- js/build/jsroot.js
- js/changes.md
- js/modules/core.mjs
- js/modules/draw/TASImagePainter.mjs
- js/modules/draw/draw3d.mjs
- js/modules/draw/more.mjs
- js/modules/geom/TGeoPainter.mjs
- js/modules/geom/geobase.mjs
- js/modules/gpad/RFramePainter.mjs
- js/modules/gpad/TCanvasPainter.mjs
- js/modules/gpad/TFramePainter.mjs
- js/modules/hist/RH3Painter.mjs
- js/modules/hist/TH2Painter.mjs
- js/modules/hist/TH3Painter.mjs
- js/modules/hist/TPavePainter.mjs
- js/modules/hist/hist3d.mjs
- js/modules/hist2d/RH1Painter.mjs
- js/modules/hist2d/RH2Painter.mjs
- js/modules/hist2d/TH1Painter.mjs
- js/modules/hist2d/TH2Painter.mjs
- js/modules/hist2d/THistPainter.mjs
For "png", "jpg", "pdf" and "svg" headless web browser will be used inside `TPad::Print()` method.
Fix small issue and improve `TPad::Print()`
Update JSROOT
> [wegui] use web-based `TPad::Print()`  method when web output is enabled

- interpreter/cling/lib/Interpreter/IncrementalParser.cpp
- interpreter/cling/lib/Interpreter/IncrementalParser.h
- interpreter/llvm/src/include/llvm/IR/DebugInfoMetadata.h
LLVM currently has an issue that a completely empty source file is stored as a `nullptr`, but `DIFile::getSource()` does not correctly deal with this situation. A crash can be observed if just attempting to launch root.exe with `EXTRA_CLING_ARGS="-gdwarf-5 -gembed-source"`.
> [cling] Create non-empty source file

- core/base/inc/TVirtualPad.h
- core/base/src/TObject.cxx
- core/base/src/TVirtualPad.cxx
- core/meta/src/TClass.cxx
- graf2d/gpad/inc/TPad.h
- graf2d/gpad/src/TButton.cxx
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TGroupButton.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/graf/src/TLegend.cxx
- gui/webgui6/src/TWebCanvas.cxx
- hist/histpainter/src/THistPainter.cxx
- net/httpsniff/src/TRootSnifferFull.cxx
Class to preserve `gPad` from the position where TContext is created.
Supports two modes - interactive and fast. In interactive mode `pad->cd()` call is used. 
In the fast modes `gPad = saved_value` uses which should not invoke any graphics update.
Use this class mainly in `TPad.cxx` and `TCanvas.cxx`, but also in several other sources
> Introduce `TVirtualPad::TContext` class

- geom/gdml/src/TGDMLWrite.cxx
- Ensure proper NCN names for surfaces (No '/' and '#' characters) for surfaces
- Make GDML refs to physical volumes unique. Unique physical volume names are mandatory for GDML to properly address surfaces, where local uniqueness is insufficient.
- Change the references of surfaces to physical volumes accordingly.
Creation of proper GDML files understood by Geant4
> Fix physical volume names in GDML, which must be globally unique

- geom/gdml/inc/TGDMLWrite.h
- geom/gdml/src/TGDMLWrite.cxx
Move call to set the export precision to the lowest level of WriteGDML.
At the lower level interface setting the precision was impossible,
> Move call to set the export precision to the lowest level of WriteGDML

- roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h
- roofit/hs3/src/HistFactoryJSONTool.cxx
- roofit/hs3/src/JSONFactories_HistFactory.cxx
- roofit/hs3/src/JSONFactories_RooFitCore.cxx
- roofit/hs3/src/RooJSONFactoryWSTool.cxx
A `histfactory` PDF type in the JSON always needs to have the
histogram sample specifications in the `samples` field. Therefore, it is
better to code the import of the histogram stacks directly into the
function that imports the full HistFactory PDF.
Like this, we can get around some of the hacks in the HistFactory JSON
IO that make assumptions on how functions are imported from the JSON,
and we have more flexibility to change the top-level structure later.
This means that the "type" field for each sample in the histogram stack
is also not necessary anymore.
This PR also includes some other code improvements that are explained in the commit descriptions.
> [RF] Hardcode import of hist-samples in JSONFactoriesHistFactory

- core/metacling/src/TCling.cxx
With LLVM 13, this exclusion is not required anymore. Closes issue #9944
Note that the issue #9809 is still present with LLVM 13
> [win] Restore code commented out for MSVC

- geom/gdml/inc/TGDMLWrite.h
- geom/gdml/src/TGDMLWrite.cxx
- Remove default argument for creating GDML positions. The default arguments always define lengths in "cm",
which is wrong for Geant4 units (mm). Instead the digested units string fDefault_lunit is used, which 
has the correct value depending on the chosen system of units.
Creating correct GDML files understood by Geant4.
> Remove default argument for creating GDML positions. 

- geom/gdml/inc/TGDMLWrite.h
- geom/gdml/src/TGDMLWrite.cxx
TGeo uses internally a material "dummy", which is not a valid material, but gets ejected into the GDML.
This material is not understood by Geant4 and inhibits produced GDML files being loaded to Geant4.
A user switch `TGDMLWrite::SetIgnoreDummyMaterial(true)` allows to inhibit to eject this material into the GDML.
Badly produced GDML files.
> Allow users to ignore material 'dummy', which is not understood by Geant4

- interpreter/cling/include/cling/Utils/Utils.h
- interpreter/cling/lib/Interpreter/CIFactory.cpp
- interpreter/cling/lib/Interpreter/CMakeLists.txt
- interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
- interpreter/cling/lib/Interpreter/PerfJITEventListener.cpp
This feature, originally added in commit 22b1606f, was reverted to make the LLVM upgrade to version 13 easier. This commit adds back all functionality as it was just before the LLVM upgrade.
Edit: Unfortunately, still doesn't work with embedded debugging info:
```
epsftws build $ env CLING_DEBUG=1 EXTRA_CLING_ARGS='-gdwarf-5 -gembed-source' gdb -- bin/root.exe
GNU gdb (Gentoo 12.1 vanilla) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration …
```
> Re-enable support for profiling/debugging interpreted/JITted code

- geom/gdml/src/TGDMLParse.cxx
- geom/gdml/src/TGDMLWrite.cxx
- Eject material property refs as first child elements as required from the GDML schema
- Add the atomic number N to the `<atom>` attributes.
- Eject **const properties** as matrices in GDML with one element rather than constants.
- Consequently, when reading a 1x1 matrix, it will be declared as `const property` to the TGeoManager.
Creation of GDML files understood by Geant4
> GDML: Fix material properties

- geom/geom/inc/TGeoMaterial.h
- geom/geom/inc/TGeoMatrix.h
- geom/geom/inc/TGeoMedium.h
- geom/geom/inc/TGeoVolume.h
- geom/geom/src/TGeoMaterial.cxx
- geom/geom/src/TGeoMatrix.cxx
- geom/geom/src/TGeoMedium.cxx
- geom/geom/src/TGeoPcon.cxx
- geom/geom/src/TGeoPgon.cxx
- geom/geom/src/TGeoScaledShape.cxx
- geom/geom/src/TGeoTube.cxx
- geom/geom/src/TGeoVolume.cxx
- geom/geom/src/TGeoXtru.cxx
- tutorials/geom/geodemo.C
- tutorials/geom/mp3player.C
After introducing cling it is not allowed to redefine already existing variables in the macro.
Therefore one always should use unique names.
Also type of created variable always should be specified - at least `auto`.
Now one can store geometry which is defined in `tutorials/geom/mp3player.C` macro together with all other components.
Adjust `tutorials/geom/mp3player.C` macro to avoid many duplicated transformation objects - it is enough to have few of them.
Do not use canvas with spaces in names in `tutorials/geom/geodemo.C`
> [geom] fix SavePrimitive methods

- roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h
- roofit/hs3/src/HistFactoryJSONTool.cxx
- roofit/hs3/src/JSONFactories_HistFactory.cxx
- roofit/hs3/src/JSONFactories_RooFitCore.cxx
- roofit/hs3/src/RooJSONFactoryWSTool.cxx
- tutorials/roofit/rf515_hfJSON.json
Export RooSimultaneous channels as dictionary of names instead of having
the full pdf specification as the value.
This change is done because all pdfs should be specified in the
top-level `pdf` structure.
The code of the `RooJSONFactoryWSTool` is also refactored such that
`exportObject` doesn't need to take the node where is should put the
object. It's better if it figures out itself to avoid errors when
calling it.
Also, I suggest to not strip the `model_` prefix of the name from the
pdf that specifies a HistFactory channel. Otherwise, the name values in
the RooSimultaneous don't match anymore, which is a problem now that we
use names as values.
> [RF] Export RooSimultaneous channels as dictionary of names in JSON

- bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabspdf.py
- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
Closes https://github.com/root-project/root/issues/11875.
As the number of command arguments for fitTo and createNLL is very large by now, their signatures were changed to take an arbitrary number of command arguments via variadic templates.
> [RF] Enable setting max minimizer iterations and calls in `fitTo()`

- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/inc/RooMinimizer.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
- roofit/roofitcore/src/RooMinimizer.cxx
- roofit/roofitcore/test/TestStatistics/testInterface.cpp
- roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
- roofit/roofitcore/test/TestStatistics/testPlot.cpp
Some minor interface changes to reflect better the underlying TestStatistics classes and how we intend to bring it to users in the upcoming release. 
The 'NewStyle' name was changed to 'ModularL' to reflect the fact that these new test statistics are modular. Note that we are undecided on 'ModularL' versus just 'Modular', so if you have a strong opinion on this feel free to change it.
Some of the functionality included in the added named arguments is not implemented yet, this is because we plan to add the respective backend for these new features in the near future. Therefore these named arguments were added under RooFit::Experimental namespace.
Do we also need to add these not yet functioning arguments already to the RooMinimizer config struct, since we plan to add them in the near …
> [RF] Minor interface changes for TestStatistics classes

- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/inc/RooBinIntegrator.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooBinIntegrator.cxx
The batched evaluation mode in the RooBinIntegrator was still
implemented with the old `getValues()` interface. Nowadays,
`getValues()` can still be used, but it's not the intended entry point
to the batched evaluation anymore. There is still a compatibility layer,
but it has lots of overhead because the new `RooFitDriver` is created
everytime `getValues()` is called.
Therefore, it is better to disable the batched evaluation code path for
now. Until the `RooRealBinding` is refactored to not create a new
RooFitDriver everytime `getValues()` is called.
Two other minor changes are also done in this PR in the first two commits. For more detail, see the commit description.
> [RF] Disable the BatchMode usage in RooBinIntegrator for now

- roofit/multiprocess/CMakeLists.txt
- roofit/multiprocess/inc/RooFit/MultiProcess/Config.h
- roofit/multiprocess/inc/RooFit/MultiProcess/HeatmapAnalyzer.h
- roofit/multiprocess/res/RooFit/MultiProcess/ProcessTimer.h
- roofit/multiprocess/src/Config.cxx
- roofit/multiprocess/src/HeatmapAnalyzer.cxx
- roofit/multiprocess/src/ProcessManager.cxx
- roofit/multiprocess/src/ProcessTimer.cxx
- roofit/multiprocess/src/worker.cxx
- roofit/multiprocess/test/CMakeLists.txt
- roofit/multiprocess/test/test_HeatmapAnalyzer.cxx
- roofit/multiprocess/test/test_ProcessTimer.cxx
- roofit/multiprocess/test/test_logs/p_0.json
- roofit/multiprocess/test/test_logs/p_1.json
- roofit/multiprocess/test/test_logs/p_999.json
- roofit/roofitcore/inc/RooAbsPdf.h
- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/inc/RooMinimizer.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
- roofit/roofitcore/src/RooMinimizer.cxx
- roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
- roofit/roofitcore/src/TestStatistics/RooSumL.cxx
This MR contains mostly two classes: 
- `RooFit::MultiProcess::ProcessTimer` which keeps a set of potentially overlapping timers per process that can be started and stopped by referring to their identifier string. Timings are written out in json format. Some extra functionality is added to write out at a specified interval.
- `RooFit::MultiProcess::HeatmapAnalyzer` which translates the timings output in log format by the process timer to a heatmap which it can return in the form of a TH2I with the correctly labeled x and y axes. Some extra functionality is available for inspecting the log files and retrieving its metadata.
Tests are included for both classes.
Note that also the interface to enable timing logging is included in the `RooMinimizer::Config` object which can be given to the …
> [RF] ProcessTimer for logging timings in `RooFit::MultiProcess` and `RooFit::TestStatistics`, and HeatmapAnalyzer for analysing them

- math/minuit2/inc/Minuit2/FumiliMinimizer.h
We can avoid quite some code repetition by employing a single `using` statement to ensure that the base class methods are not hidden.
> [math][minuit2] Avoid hiding member functions with `using`

- roofit/roofitcore/inc/RooAbsOptTestStatistic.h
- roofit/roofitcore/inc/RooAbsTestStatistic.h
- roofit/roofitcore/inc/RooChi2Var.h
- roofit/roofitcore/inc/RooDataWeightedAverage.h
- roofit/roofitcore/inc/RooNLLVar.h
- roofit/roofitcore/inc/RooXYChi2Var.h
The IO for the tests statistics never worked anyway, not even for a simple Gaussian likelihood. It is better to exclude the old test statistics classes complete from IO. Like this, the users don't even attempt to do IO with them, and to developers it's clear that IO backwards compatibility is not necessary, taking away some maintenance burden.
Here are some simple scripts to show that storing test statistics doesn't work anyway.
Create a NLL object, write it of file and minimize it:
```c++
void write()
{
RooRealVar x("x", "x", -10, 10);
RooRealVar mean("mean", "mean of gaussian", 1, -10, 10);
RooRealVar sigma("sigma", "width of gaussian", 1, 0.1, 10);
RooGaussian gauss("gauss", "gaussian PDF", x, mean, sigma);
auto *data = gauss.generateBinned(x, 10000);
auto nll = …
```
> [RF] Make old test statistic classes transient with `ClassDef(0)`

- tree/ntuple/v7/doc/specifications.md
- tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
- tree/ntuple/v7/src/RNTupleSerialize.cxx
- tree/ntuple/v7/src/RPageStorageDaos.cxx
- tree/ntuple/v7/src/RPageStorageFile.cxx
- tree/ntuple/v7/test/ntuple_serialize.cxx
- tree/ntuple/v7/test/ntuple_storage.cxx
- tree/ntuple/v7/test/ntuple_test.hxx
This pull request improves the internal in-memory layout of `RNTupleLocator`, its serialization/deserialization, and introduces some changes to the binary specification (see list of individual changes below).
- **FIX** discrepancy between non-disk locators specification and implementation: [specifications.md, Section "Locators and Envelope Links"](https://github.com/root-project/root/blob/master/tree/ntuple/v7/doc/specifications.md#locators-and-envelope-links) stated that on non-disk locators, the 24LSb of _Size_ specify the size of the locator (and not only the size of the payload).  However, _Size_ stored only the size of the payload.
- Use a `std::variant<...>` to represent type-specific information stored in the locator.
- Separate serialization of non-simple locators (i.e. those …
> [ntuple] Improve definition of `RNTupleLocator`s

- roofit/xroofit/inc/RooBrowser.h
In case the nightly builds are failing with `root7`, I think this is the fix.
Follow up to https://github.com/root-project/root/pull/11851.
> [RF] Add missing `XROOFIT_NAMESPACE` definition

- core/base/inc/TExec.h
- core/base/inc/TString.h
- core/base/src/TExec.cxx
- core/base/src/TMacro.cxx
- core/base/src/TString.cxx
- graf2d/gpad/src/TButton.cxx
- graf2d/gpad/src/TSlider.cxx
- graf2d/graf/src/TLatex.cxx
- graf2d/graf/src/TText.cxx
Handle obvious escape characters.
Fix #11913
> Fixing `TExec::SavePrimitive` and `TMethod::SavePrimitive` 

- roofit/roofitcore/inc/LinkDef.h
- roofit/roofitcore/inc/RooFitLegacy/RooMinuit.h
- roofit/roofitcore/inc/RooMinuit.h
- roofit/roofitcore/src/RooFitLegacy/RooMinuit.cxx
Officially deprecate RooMinuit with attributes for the compiler, indicating that it will be removed in ROOT 6.30.
The dictionary generation via `ClassDef` etc. is also removed, because otherwise we would get the deprecation warning in the dictionary generation.
> [RF] Officially deprecate RooMinuit

- geom/geombuilder/inc/TGeoManagerEditor.h
- geom/geombuilder/src/TGeoManagerEditor.cxx
Not allowed to put implementation of static method in header file Windows will not work
One of the reasons for crash, but not only
> [geo] fix TGeoManagerEditor::LoadLib

- core/base/inc/TColor.h
- core/base/src/TAttAxis.cxx
- core/base/src/TAttFill.cxx
- core/base/src/TAttLine.cxx
- core/base/src/TAttMarker.cxx
- core/base/src/TAttText.cxx
- core/base/src/TColor.cxx
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TGroupButton.cxx
- graf2d/gpad/src/TPad.cxx
- graf2d/graf/src/TGaxis.cxx
- graf2d/graf/src/TPaveText.cxx
- graf2d/graf/src/TPie.cxx
- graf2d/graf/src/TPieSlice.cxx
- graf2d/graf/src/TPolyLine.cxx
- hist/hist/src/TF1.cxx
- hist/hist/src/TF2.cxx
- hist/hist/src/TF3.cxx
- tree/tree/src/TChain.cxx
Fixes #11916
When `TColor` object with required index not exists, it will not be saved.
Making produced macro either not working or not correctly working.
To resolve problem making `TColor::SaveColor` return boolean to decide that to do. 
Adjust all methods where `SaveColor` was used.
Code based on old behavior will work as before.
Shrink many `SavePrimitive` methods using attributes method to save fill/line/text attributes.
> Fix `TColor::SaveColor`, optimize `SavePrimitive` methos

- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/inc/RooNLLVar.h
- roofit/roofitcore/src/BatchModeHelpers.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooFit/BatchModeHelpers.h
- roofit/roofitcore/src/RooGlobalFunc.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/src/RooNLLVarNew.h
Add support for a new `Offset("bin")` command argument to create NLL.
With this new offset mode, the NLL is offsetted by the likelihood for a
template histogram model based on the obersved data. This can
drastically improve numeric stability, because the offsetting is done
for each bin. This results in per-bin values that are all in the same
order of magnitude, which reduces precision loss in the sum.
So far, it is only supported in the old test statistics when do do the
fit with a `RooDataHist` with the old test statistics.
> [RF] New `Offset("bin")` command argument for createNLL 

- tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
- tree/ntupleutil/v7/src/RNTupleImporter.cxx
- tree/ntupleutil/v7/test/CMakeLists.txt
- tree/ntupleutil/v7/test/CustomStructUtil.cxx
- tree/ntupleutil/v7/test/CustomStructUtil.hxx
- tree/ntupleutil/v7/test/CustomStructUtilLinkDef.h
- tree/ntupleutil/v7/test/ntuple_importer.cxx
- tutorials/v7/ntuple/ntpl008_import.C
Implements the class `RNTupleImporter` from the ntuple utility package. The class reads a ROOT tree and writes the data out as RNTuple. Most branch types map directly to RNTuple field types, with some exceptions:
- C strings are converted to `std::string`
- C fixed-size arrays are converted to `std::array`
- Leaf lists are converted to untyped records
- Count leaf arrays are converted to untyped collections with generic names (`_collection0`, `_collection1`, etc.). In a follow up PR, RNTuple should receive functionality for "stored projections". That will allow storing virtual fields whose data comes from physical columns. In this way, the data from the untyped collections can be presented with their original TTree names (e.g., `njets`, `jet_pt`, etc.).
At this point, the importer can …
> [ntuple] Importer for TTrees 

- roofit/histfactory/CMakeLists.txt
- roofit/histfactory/config/prepareHistFactory.bat
After this commit, all the tutorials containing the following lines:
```
#ifdef _WIN32
cout << "HistFactory file cannot be generated on Windows - exit" << endl;
return;
#endif
```
can be enabled on Windows (another PR will follow)
> [skip-ci][Windows] Add the prepareHistFactory.bat script

- math/mathcore/inc/Math/Util.h
- math/mathcore/test/testKahan.cxx
The behavior of `-=` and `+=` on a `KahanSum` were not symmetric, leading to slight bit-wise inaccuracies. In fits, where such operations are done a lot of times (e.g. through the offsetting mechanism in RooFit which subtracts a constant `KahanSum` term after each likelihood evaluation), this can add up to significant numerical divergence. This in turn makes it hard to test the accuracy of new numerical implementations. In particular, we are trying to fix a bug in `MultiProcess::LikelihoodJob`, which builds on this `KahanSum` fix.
This commit adds test cases around the precision limits, making sure that all behavior is now symmetric and internally consistent.
To aid in the test cases and also make the `KahanSum` objects more versatile, the commit also adds some extra `-` and `+` …
> [math] make KahanSum::operator+= and -= consistent

- interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp
- interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
- interpreter/cling/lib/Interpreter/IncrementalJIT.h
With the upgrade, BackendPasses was modifying a TargetMachine that was not used by SimpleCompiler.
Change that by
- using a SimpleCompiler that uses IncrementalJIT::TM;
- moving the TM creation to IncrementalJIT, and giving access to it
This reduces the runtime of https://github.com/root-project/root/issues/11927 to
- before llvm upgrade: 2.69s
- llvm13, without this commit: ???
- llvm13, with this commit: 2.89s i.e, a slow-down of 7% (that is likely caused by the different emission mechanism of Orc-v2; to be confirmed...)
> [cling] Re-enable CodeGen-OptLevel after llvm13 upgrade:

- math/mathcore/inc/Math/Util.h
- roofit/roofitcore/inc/RooAbsTestStatistic.h
- roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodWrapper.h
- roofit/roofitcore/inc/RooFit/TestStatistics/RooBinnedL.h
- roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooBinIntegrator.cxx
- roofit/roofitcore/src/RooCurve.cxx
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooNLLVarNew.cxx
- roofit/roofitcore/src/RooNLLVarNew.h
- roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
- roofit/roofitcore/src/TestStatistics/LikelihoodWrapper.cxx
- roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx
- roofit/roofitcore/src/TestStatistics/RooSumL.cxx
- roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
- roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cpp
- roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
- roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
- roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx
Follow-up on #11940; ~please merge that one before this one~ it has been merged, so this one can also be merged.
The auto-conversion to type `T` and implicit type `T` constructor in `KahanSum` make it hard to debug `KahanSum`, because it is easy to overlook implicit conversions in code, especially in lines where the type of the return value is `auto`. The second commit in this PR (the first commit is the same as that in #11940) removes them and where they were necessary replaces them with an explicit construction or explicit conversion to double via `Sum()`
> [math] remove implicit conversions to/from KahanSum

- tmva/pymva/inc/TMVA/PyMethodBase.h
- tmva/pymva/src/PyMethodBase.cxx
- tmva/pymva/src/RModelParser_Keras.cxx
- tmva/pymva/test/EmitFromKeras.cxx
- tmva/pymva/test/TestRModelParserKeras.C
This PR fixes compiling the code for parsing Keras model when the C-API of Python 2 is used. In this case some functions are not available in Python.h. Those functions are used to parse the convolutional layers from Keras. 
This PR excludes the parsing of this layer and avoid calling those functions available only in Python3. 
Also the tests using the cone layer parsing are disabled.
> [tmva][sofie] Fix Keras parsing for  Python2

- roofit/roofit/inc/RooMomentMorphFuncND.h
- roofit/roofit/src/RooFit/Detail/Algorithms.h
- roofit/roofit/src/RooMomentMorphFuncND.cxx
- roofit/roofit/src/RooMomentMorphND.cxx
The `RooMomentMorphND` and `RooMomentMorphFuncND` classes duplicated some copy-pasted code from stackoverflow. This is not factored out into a new private header file to avoid code duplication.
Also, a semicolon is added after `TRACE_CREATE` and `TRACE_DESTROY` in order to not confuse clang-format.
> [RF] Avoid code duplication with new private `Algorithms.h` file

- hist/hist/src/TH1.cxx
This PR fixes the `TH1::GetCumulative()` method by assigning the cumulative error to the newly generated histogram instead of the original one.
This PR fixes #11947
> [hist] TH1::GetCumulative: fix error setting

- roofit/roofitcore/inc/LinkDef.h
- roofit/roofitcore/inc/RooGrid.h
- roofit/roofitcore/src/RooGrid.cxx
- roofit/roofitcore/src/RooMCIntegrator.cxx
The `RooGrid` is a utility class for the `RooMCIntegrator`, which doesn't support IO itself. Therefore, it doesn't make sense to have a `ClassDef(1)` macro. It is only putting the unnecessary burden of keeping backwards compatibility on the developers.
Therefore, this commit suggests to leave out the `ClassDef` macro out of `RooGrid`, and also remove the unnecessary base classes `TObject` and `RooPrintable`. There is only one printing function that makes sense anyway, which is kept without implementing the full `RooPrintable` interface.
> [RF] Exclude `RooGrid` class from IO

- math/mathcore/src/Fitter.cxx
- math/minuit/inc/TLinearMinimizer.h
- math/minuit/src/TLinearMinimizer.cxx
This PR fixes a problem in fixing the parameter when using the linear fitter. 
This simple examples shows the problem (the fixed parameter is always the first one) instead of the second one
```
{
auto h1 = new TH1D("h1","h1",20,0,10);
h1->FillRandom("pol0");
auto f1 = new TF1("f1","pol1");
f1->FixParameter(1,0);
h1->Fit(f1,"");
}
```
the bug is caused by `TLinearMinimizer::SetVariable` returning false instead of true. 
The PR fixes also the counting of the total number of free parameters
> [math] Do correctly the setting of fix  variables in TLinearMinimizer

- roofit/xroofit/src/xRooNode.cxx
On the Snap build of ROOT, the parameters were assumed to be int, double
Errors from build log, running Ubuntu 20.04 GCC9 C++17
```
/root/parts/root/src/roofit/xroofit/src/xRooNode.cxx:5778:105: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘double’)
5778 |                                    : (h->GetBinContent(1) + std::max(abs(h->GetBinContent(1) * 0.1), 50.)));
```
This doesn't appear to occur in normal builds, but the guard code seems trivial enough to include and this may prevent compilation errors in other scenarios.
- [Y] tested changes locally
- [Y] updated the docs (if necessary)
> [RF] Prevent accidental casting from `double` to `int` in xroofit

- roofit/roofitcore/inc/RooPlot.h
- roofit/roofitcore/src/RooMCStudy.cxx
- roofit/roofitcore/src/RooPlot.cxx
- roofit/roofitcore/src/RooUnitTest.cxx
This is a followup to commit 8679898a. In that commit, the RooPlot was changed to not create an internal clone of the plot variables anymore.
However, in rare cases like for the RooUnitTest, it is necessary that the RooPlot owns the plot plot variables to avoid dangling pointers when the RooPlot lives longer than the original plot variables.
To support these cases, a new member function
`RooPlot::createInternalPlotVarClone()` is introduced. It can be used to convert the RooPlot to a plot that owns a clone of the plot variable at any point in time of the RooPlot lifetime.
> [RF] New `RooPlot::createInternalPlotVarClone()` function for RooUnitTest

- test/stressRooFit_tests.h
- tutorials/roofit/rf205_compplot.C
- tutorials/roofit/rf205_compplot.py
In the `rf205` tutorial and the associated stressRooFit test, the `bkg` RooAddPdf was created using the `sig1frac`, while it is clearly the idea to use the `bkg1frac` parameter.
This is fixed in this commit, also fixing the name of the `bkg1frac` parameter, which was accidentally set to `sig1frac` (probably a copy-paste error).
However, to not change the output of the tutorial and the stressRooFit test, the value of `bkg1frac` was set to the same value as `sig1frac`, such that this commit only fixes the model but doesn't change the tutorial and test output.
> [RF] Fix copy-paste error in `rf205` tutorial and related stressRooFit test

- README/ReleaseNotes/v630/index.md
- tree/dataframe/inc/ROOT/RArrowDS.hxx
- tree/dataframe/inc/ROOT/RCsvDS.hxx
- tree/dataframe/inc/ROOT/RNTupleDS.hxx
- tree/dataframe/inc/ROOT/RSqliteDS.hxx
- tree/dataframe/src/RArrowDS.cxx
- tree/dataframe/src/RCsvDS.cxx
- tree/dataframe/src/RDataFrame.cxx
- tree/dataframe/src/RNTupleDS.cxx
- tree/dataframe/src/RSqliteDS.cxx
This pull request removes deprecated RDataFrame functions marked for removal in ROOT v6.30.  These changes fix the warnings reported by the CI on pull requests targeting `master`, e.g. 
```
.../build/include/ROOT/RCsvDS.hxx:112:1: warning: unknown attribute 'REMOVE_THIS_NOW' ignored [-Wunknown-attributes]
.../build/include/ROOT/RSqliteDS.hxx:117:1: warning: unknown attribute 'REMOVE_THIS_NOW' ignored [-Wunknown-attribute]
```
Sibling PR in roottest: https://github.com/root-project/roottest/pull/931
> [DF] Remove deprecated functions marked for removal in v6.30

- tutorials/v7/ntuple/ntpl008_import.C
RNTupleImporter appends keys to the output file; make sure a second run of the tutorial does not fail with
```
terminate called after throwing an instance of 'ROOT::Experimental::RException'
what():  Key 'Events' already exists in file ntpl008_import.root
```
by removing the output file.
This PR fixes #11987.
> [ntuple] Fix tutorial `ntpl008_import.C`

- .github/CODEOWNERS
This should set me as a default reviewer for changes in tree/ntupleutil
> Set jblomer as code owner for ntupleutil

- interpreter/CMakeLists.txt
`verifyPreservedAnalysis()` is super slow these days. It gets run when assertions are one (!NDEBUG). Turn this off unless told to build a Debug build of ROOT (where time does not matter, and is expected to not be representative for reality) or where LLVM_BUILD_TYPE is turning asserts on.
> [cmake] Disable llvm-assertions for ROOT=RelWithDebInfo:

- README/ReleaseNotes/v628/index.md
- roofit/roofitcore/inc/RooNumber.h
- roofit/roofitcore/src/RooAbsRealLValue.cxx
- roofit/roofitcore/src/RooNumber.cxx
The different overloads of `RooAbsRealLValue::inRange()` implemented
different tolerances when checking if a value `x` falls inside a
specific range. Some overloads checked if the interval
`[x - 1e-6, x + 1e6]` is overlapping with the range, an other overload
checked if the interval `[x - 1e-8*x, x + 1e8*x]` is overlapping.
It's better is this is done consistently and predictably so this commit
suggests to leave out these epsilon margins that were never documented.
For backwards compatibility, one can set a custom relative or absolute
epsilon via the `RooNumber` interface.
Also, the checks if the range limits are `RooNumber::isInfinite()` were
removed. They were mathematically redundant, since in RooFit, +/-
infinity is simply defined as +/-1e30.
This PR fixes some corner cases in which …
> [RF] Make margin in `RooAbsRealLValue::inRange()` zero by default 

- roofit/roofit/inc/RooMomentMorphFuncND.h
- roofit/roofit/inc/RooMomentMorphND.h
- roofit/roofit/src/RooMomentMorphFuncND.cxx
- roofit/roofit/src/RooMomentMorphND.cxx
In order to merge the `RooMomentMorphND` and the `RooMomentMorphFuncND`, it is better to rename things first such that the code becomes comparable. Like this, it will be easier to spot the residual differences.
> [RF] Rename stuff in RooMomentMorph(Func)ND to ease spotting difference

- gui/webgui6/src/TWebControlBar.cxx
> [webgui] no need to provide dummy disconnect handler in TWebControlBar [6.28]

- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/CustomStructLinkDef.h
- tree/ntuple/v7/test/ntuple_types.cxx
Pull request #11731 introduced internal support for per field post-read callbacks.  This follow-up pull request registers a callback for each `#pragma read` rule on user-defined classes.
Currently, `#pragma read` rules referencing non-transient members as a `target` are intentionally disallowed -- a warning is logged in that case.  Only target class version is checked, i.e. checksum is ignored.
Raw read rules are not (and will likely not be) supported, as they take a `TBuffer &`.
- Introduce `RFieldBase::AddReadCallbacksFromIORules()`. This function registers a post-read callback for each of the given `ROOT::TSchemaRule`s.
- `RFieldBase::ConnectPageSource()`: cache C++ type version as stored in the RNTupleDescriptor.  This information can be accessed via `GetOnDiskTypeVersion()`. …
> [ntuple] Register post-read callbacks for `#pragma read` rules on user-defined classes

- tree/ntupleutil/v7/src/RNTupleImporter.cxx
Apparently this is ill-formed with C++17 and fails to compile with Clang version 14.
> [ntuple] Avoid lambda capture of structured binding

- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooGenProdProj.cxx
- roofit/roofitcore/test/testRooRealIntegral.cxx
- roofit/roofitcore/test/testTestStatistics.cxx
The idea of the RooGenProdProj is that we divide two integral objects
each created with this makeIntgral() function to get the normalized
integral of a product. Therefore, we don't need to normalize the
numerater and denominator integrals themselves. Doing the normalization
would be expensive and it would cancel out anyway. However, if we don't
specify an explicit normalization integral in createIntegral(), the
last-used normalization set might be used to normalize the pdf,
resulting in redundant computations.
For this reason, the normalization set of the integrated pdfs is fixed
to an empty set in this case. Note that in RooFit, a nullptr
normalization set and an empty normalization set is not equivalent. The
former implies taking the last-used normalization set, and the latter
means …
> [RF] Explicitly set empty normalization set in `RooGenProdProj`

- tutorials/CMakeLists.txt
Disable several tests who are using `hist2workspace` (which requires xml) when `ROOT_xml_FOUND` is not set
> Disable tests depending on xml when xml is not found

- roofit/roofitcore/inc/RooFitResult.h
- roofit/xroofit/src/xRooFit.cxx
This allows non-friends to construct RooFitResults, which allows for the removal of protected->public override in xRooFit for this class.
> [RF] Make RooFitResult set methods public 

- tree/ntupleutil/CMakeLists.txt
- tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
- tree/ntupleutil/v7/src/RNTupleInspector.cxx
- tree/ntupleutil/v7/test/CMakeLists.txt
- tree/ntupleutil/v7/test/ntuple_importer.cxx
- tree/ntupleutil/v7/test/ntuple_inspector.cxx
- tree/ntupleutil/v7/test/ntupleutil_test.hxx
This PR adds the RNTupleInspector class to the RNTuple utility package and can be used for (static) inspection of RNTuples. It currently provides basic information on the size and compression of a given RNTuple.
Next steps will adding functionality for for getting size and compression data on a per-column and per-type basis, and to provide a way to visualize this information.
-[x] Add unit tests
-[x] Add usage documentation
> [ntuple] Add Inspector skeleton

- gui/browsable/src/RFieldProvider.hxx
- tree/dataframe/src/RNTupleDS.cxx
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/src/RFieldVisitor.cxx
- tree/ntuple/v7/src/RNTupleModel.cxx
- tree/ntuple/v7/test/ntuple_project.cxx
- tree/ntuple/v7/test/rfield_vector.cxx
- tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
- tree/ntupleutil/v7/src/RNTupleImporter.cxx
- tree/ntupleutil/v7/test/ntuple_importer.cxx
The cardinality field presents an offset column as vector sizes. It supports reading only. It is used in the importer to project the offset columns of untyped collections stemming from leaf count arrays to their count leaf names.
> [ntuple] Add cardinality field

- roofit/roofitcore/inc/RooSimultaneous.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooSimGenContext.cxx
- roofit/roofitcore/src/RooSimSplitGenContext.cxx
- roofit/roofitcore/src/RooSimultaneous.cxx
- roofit/roofitcore/test/testRooSimultaneous.cxx
When generating such a pdf from prototype data, the prototype needs to
contain all the subcategories of the super-category, and it does so by
checking the super-category servers. However, recently
`RooSuperCategory` was changed to contain a `RooMultiCategory`
internally, and the only reported direct server is the internal
multi-category. This leads to a wrong generation (the prototype data is
ignored, the gen context refers to the current labels).
The solution that this commit suggests is to use
`RooSuperCategory::inputCatList()` to inspect the internal categories
instead of using the client-server interface. Actually, the
client-server interface is not meant to be used for inspection like
that, just for general dependency management in the evaluation.
Closes …
> [RF] Fix problems with dataset generation from a nested `RooSimultaneous` with proto data

- roofit/roofitcore/inc/RooAbsArg.h
This memory leak is demonstrated with the following ROOT macro:
```
{
{
RooExpensiveObjectCache::instance(); // force the standard instance construction (otherwise created in factory method call)
cout << "make ws" << endl;
RooWorkspace w("combined", "combined");
cout << "factory method:" << endl;
w.factory("RooGaussian::gaus(x[-5,5],mean[0,-5,5],sigma[1,0.1,3])");
w.writeToFile("/tmp/test.root");
cout << "reading back" << endl;
{
TFile f("/tmp/test.root");
RooWorkspace *w2 = f.Get<RooWorkspace>("combined");
std::cout << "deleting w2" << endl;
delete w2;
}
std::cout << "deleting w" << endl;
}
}
```
along with a modification to `RooExpensiveObjectCache` to printout when an instance is being constructed or destructed. Before this fix the above then prints out (I annotated the output a bit): …
> [RF] Do not stream RooAbsArg eocache to avoid memory leak when reading back workspaces

- tree/ntupleutil/v7/src/RNTupleImporter.cxx
This patch also reports the branch name when a class cannot be loaded by the importer to make debugging easier.
> [ntuple] Report the branch name when a class cannot be loaded

- tree/dataframe/test/dataframe_datasetspec.cxx
According to https://github.com/root-project/root/issues/9137, we get bogus data if a friend is shorter than the main tree. The `datasetspec` test acknowledges this, but still checks the results in the MT case. This miraculously seems to work most of the time, but we sometimes see failures in the nightlies, especially on macOS, so remove it.
> [DF] Removing failing test with shorter friends

- roofit/roofitcore/inc/RooHistFunc.h
- roofit/roofitcore/inc/RooHistPdf.h
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooHistPdf.cxx
Explanation is in comments for new methods - allows underlying dataHist to be cloned if necessary to take ownership
> [RF] Add `cloneAndOwnDataHist()` method to RooHistFunc and RooHistPdf

- tree/ntuple/v7/src/RField.cxx
- tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
Visible with `-Ddev=On` on macOS
> [rntpl] Do not rely on transient include; unused member.

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/inc/RooAbsTestStatistic.h
- roofit/roofitcore/inc/RooWorkspace.h
- roofit/roostats/inc/RooStats/HypoTestResult.h
A set of, hopefully, non-controversial changes to some roofit classes to allow certain data members to be accessed publicly.
> [RF] New public accessor methods for various roofit data members

- tutorials/CMakeLists.txt
This Pull request should fix the tutorial timeout observed in CI
> [tmva] Fix the parallel running in ctest of some TMVA tutorial

- geom/geom/src/TGeoVoxelFinder.cxx
warns of overflow with an error message
See https://root-forum.cern.ch/t/break-segmentation-violation-while-using-geometry-package/53087/7
Side note: To allow for Long64_t, a complete rewrite of all variables' data types would be needed.
> TGeoVolume class is designed for Int_t, not Long64_t

- roofit/roofit/inc/RooMomentMorphFuncND.h
- roofit/roofit/inc/RooMomentMorphND.h
- roofit/roofit/src/RooMomentMorphFuncND.cxx
- roofit/roofit/src/RooMomentMorphND.cxx
The member that points to the last normalization set should not take part in IO.
Also, a memory leak is fixed and some code is modernized by using `std::unique_ptr`.
> [RF] Fix IO and memory problems in RooMomentMorph(Func)ND

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/inc/RooSTLRefCountList.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooGenProdProj.cxx
The `RooAbsArg::replaceServer()` function is quite dangerous to use,
because it leaves your RooFit objects in an invalid state. See for
example this code:
```c++
RooRealVar x("x", "x", -10, 10);
RooRealVar mean("mean", "mean of gaussian", 1, -10, 10);
RooRealVar sigma("sigma", "width of gaussian", 1, 0.1, 10);
RooGaussian gauss("gauss", "gaussian PDF", x, mean, sigma);
RooRealVar mean2(mean);
gauss.replaceServer(mean, mean2, true, false);
gauss.Print("v");
std::cout << "x    : " << &gauss.getX() << std::endl;
std::cout << "mean : " << &gauss.getMean() << std::endl;
std::cout << "sigma: " << &gauss.getSigma() << std::endl;
```
Here, the proxy for `mean` will still point to the original `mean`, but
the server was redirected to the copy `mean2`. This is dangerous, and
desyncing of the proxy …
> [RF] Improve implementation of `RooAbsArg::redirectServers()`

- tree/ntuple/v7/src/RField.cxx
The `target` attribute in a rule specification is mandatory, but the list can be empty, in which case `TSchemaRule::GetTarget()` returns `nullptr`.
In particular, @Nowakus reported the following error for read rules associated with class `ElementLinkBase`, which happens to have an empty `target` list
```
Fatal: rule->GetTarget() != nullptr violated at line 1006 of
`/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/tree/ntuple/v7/src/RField.cxx'
aborting
```
Therefore, in principle we should also allow these rules for now.
> [ntuple] Allow I/O customization rules with an empty target list

- roofit/roofitcore/src/RooProduct.cxx
The IO of RooFit proxies can be quite fragile sometimes, and it can happen when reading a RooProduct that the `_proxyList` is not synced with the proxy members.
In dbc96810, I decided to throw an exception is this case, but I realized this was too strong: too many old workspace are affected. In all cases that I know of, one can simply recover by correctly resetting the `_proxyList`. This is now what is done, and only a warning is printed. The warning includes information on all the proxies, so the user can figure out themselves if what RooFit is doing here is correct.
> [RF] Don't throw exception if proxies are inconsistent in RooProduct

- build/rmkdepend/def.h
- build/rmkdepend/include.c
```
build/rmkdepend/include.c:306:28: warning: ‘%s’ directive writing up to 8190 bytes into a region of size between 1 and 8191 [-Wformat-overflow=]
306 |          sprintf(path, "%s/%s", *pp, include);
|                            ^~
```
> [rmkdepend] Use snprintf against warning (GCC 12.2):

- graf2d/quartz/src/QuartzMarker.mm
The marker size in Quartz was using fixed value 1, ignoring that the size must be scaled for retina displays.
Propagates the scaled marker size to the CGContextFillRect method in charge of the actual drawing
Fixes (among others) the wrong ray-tracing output mentioned in #12035
> Plot markers using their actual size

- roofit/roofitcore/inc/RooProdPdf.h
- roofit/roofitcore/inc/RooProduct.h
- roofit/roofitcore/src/RooProdPdf.cxx
Adds public methods to allow access and modification of the underlying factors of RooProdPdf and RooProduct
> [RF] additional public methods for accessing/modifying product factors

- graf3d/eve7/src/REveGeoShape.cxx
- graf3d/eve7/src/REvePointSet.cxx
This PR fixes a possible crash in streaming REveGeoShape because local geo manger forgot to be set.
It also fixes crash in projecting empty point set.
> REve: Correction in streaming of REveGeoShape render data

- core/clingutils/res/TClingUtils.h
- core/metacling/src/TCling.cxx
- interpreter/cling/lib/Interpreter/CIFactory.cpp
- interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
- interpreter/llvm/src/include/llvm/IR/DataLayout.h
The issue was the in-process lookup of C++ symbols failed with a `GlobalPrefix`.
> Revert LLVM patch for win32

- bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py
- core/base/inc/TDirectory.h
- core/base/inc/TROOT.h
- core/base/inc/TThreadSlots.h
- core/base/src/TDirectory.cxx
- core/thread/src/TThread.cxx
- io/io/inc/TDirectoryFile.h
- io/io/src/TDirectoryFile.cxx
This fixes #11907
Inadvertently a previous commit (79a669b) disabled the ability to cleanup the thread local gDirectory in other
threads when the TFile they pointed to is deleted.
Also fix a set of rare race conditions:
Fix race condition between RegisterContext and gDirectory cleanup.
Description of the race conditions:
(1) thread one create TFile, gDirectory now points to that file.
(2) thread two delete TFile, the destructor calls CleanTargets which has 4 distinct phase
(a) take the TFile spin lock and update all the TContext that points to the file
(b) still hold the spin lock, clean the other thread's directory.
(c) deal with the TContext that were being destructed at the same time
(d) update the local gDirectory
If between (2)(a) and (2)(b), thread (1) starts the creation of a …
> Reenable the cleanup of gDirectory in other threads upon file deletion.

- interpreter/cling/tools/driver/CMakeLists.txt
LLVM component must be registered as LLVM_LINK_COMPONENTS to be compatible with LLVM Dylib. Otherwise they are loaded twice in the final binary, once through LLVM Dylmib and once through individual component, and this results in some options being registered twice.
Fix root-project/cling#440
> Do not register LLVMSupport as a library when it should be a component

- math/foam/inc/TFoam.h
- math/foam/inc/TFoamCell.h
- math/foam/src/TFoam.cxx
- math/foam/src/TFoamCell.cxx
This fixes a memory leak related to the usage of `TRef` in `TFoamCell`
that can be reproduced with the following code:
```C++
class MyTFoamBinding : public TFoamIntegrand {
public:
double Density(Int_t ndim, double *) override { return 1.0; }
};
void reproTFoam()
{
ProcInfo_t procinfo;
const float toMB = 1.f / 1024.f;
std::size_t nToys = 5000;
TRandom3 rand{};
for (std::size_t index_toy = 1; index_toy <= nToys; index_toy++) {
if (index_toy % 500 == 0) {
gSystem->GetProcInfo(&procinfo);
std::cout << index_toy << ": " << procinfo.fMemResident * toMB
<< "   " << procinfo.fMemVirtual * toMB << std::endl;
}
MyTFoamBinding binding{};
TFoam tfoam{"TFOAM"};
tfoam.SetkDim(1);
tfoam.SetRho(&binding);
tfoam.SetPseRan(&rand);
tfoam.SetnCells(30);
tfoam.SetnSampl(200);
tfoam.SetPseRan(&rand); …
```
> [math] Replace TRef with array indices in `TFoamCell`

- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
- tree/ntuple/v7/src/RNTuple.cxx
- tree/ntuple/v7/test/ntuple_show.cxx
This PR introduces a new format option for `RNTupleReader::Show()` that shows all fields if no model is specified, and only the fields present in the model if there is one. It also changes the default show format to this option.
> [ntuple] Show all fields unless a model is specified

- tree/ntupleutil/v7/src/RNTupleImporter.cxx
- tree/ntupleutil/v7/test/CustomStructUtilLinkDef.h
- tree/ntupleutil/v7/test/ntuple_importer.cxx
This PR fixes the incorrect fetching of the type for branches containing split collections of user-defined classes.
> [ntuple] Fix loading of class for split collections

- bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py
- core/base/inc/TDirectory.h
- core/base/inc/TROOT.h
- core/base/inc/TThreadSlots.h
- core/base/src/TDirectory.cxx
- core/thread/src/TThread.cxx
- io/io/inc/TDirectoryFile.h
- io/io/src/TDirectoryFile.cxx
This fixes #11907
Inadvertently a previous commit (79a669b) disabled the ability to cleanup the thread local gDirectory in other
threads when the TFile they pointed to is deleted.
Also fix a set of rare race conditions:
Fix race condition between RegisterContext and gDirectory cleanup.
Description of the race conditions:
(1) thread one create TFile, gDirectory now points to that file.
(2) thread two delete TFile, the destructor calls CleanTargets which has 4 distinct phase
(a) take the TFile spin lock and update all the TContext that points to the file
(b) still hold the spin lock, clean the other thread's directory.
(c) deal with the TContext that were being destructed at the same time
(d) update the local gDirectory
If between (2)(a) and (2)(b), thread (1) starts the creation of a …
> v628: Reenable the cleanup of gDirectory in other threads upon file deletion.

- math/foam/inc/TFoam.h
- math/foam/inc/TFoamCell.h
- math/foam/src/TFoam.cxx
- math/foam/src/TFoamCell.cxx
- roofit/roofitcore/inc/RooProdPdf.h
- roofit/roofitcore/inc/RooProduct.h
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/src/RooProduct.cxx
This is a backport of all the relevant RooFit PRs that were recently merged to master to v6-28-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/12048
2. https://github.com/root-project/root/pull/12061
3. https://github.com/root-project/root/pull/12071
Only the first commit that is not a fixup to a recent typo is `master`
Related to https://github.com/root-project/root/issues/11856.
> [v628][RF] Backports of RooFit PRs to `v6-28-00-patches`: Part 6
