roofit/roofitcore/src/RooGenProdProj.cxx, roofit/roofitcore/src/RooProduct.cxx
handle case where p0 or p1 are null -> ensure not null by time expectProxyIs is called
=> [RF] RooProduct schema-evolved i/o bug fix

tmva/sofie/inc/TMVA/ROperator.hxx, tmva/sofie/inc/TMVA/ROperator_BasicBinary.hxx, tmva/sofie/inc/TMVA/ROperator_BasicNary.hxx, tmva/sofie/inc/TMVA/ROperator_BatchNormalization.hxx, tmva/sofie/inc/TMVA/ROperator_Conv.hxx, tmva/sofie/inc/TMVA/ROperator_ConvTranspose.hxx, tmva/sofie/inc/TMVA/ROperator_GRU.hxx, tmva/sofie/inc/TMVA/ROperator_Gemm.hxx, tmva/sofie/inc/TMVA/ROperator_LSTM.hxx, tmva/sofie/inc/TMVA/ROperator_LayerNormalization.hxx, tmva/sofie/inc/TMVA/ROperator_RNN.hxx, tmva/sofie/inc/TMVA/ROperator_Selu.hxx, tmva/sofie/inc/TMVA/ROperator_Sigmoid.hxx, tmva/sofie/inc/TMVA/ROperator_Tanh.hxx, tmva/sofie/src/RModel.cxx
Properly initialize `std::vector<std::string>`, gcc13 do not like to automatically convert array of const char* to it.
=> Fix gcc13 warning in TMVA Sofie includes

graf2d/graf/src/TPaveText.cxx
gcc13 complains that `name` can be null.
=> Fix gcc13 warning in TPaveText

roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commit adds a C/C++ function wrapper class that takes in code as a string, declares it, and stores it as a function pointer. Currently, only functions of type `double (*)(double* )` are supported. This class will later be used to store a roofit model as code for automatic differentiation.
=> [RF] Add a C/C++ function wrapper class in roofit.

tmva/pymva/src/RModelParser_Keras.cxx, tmva/sofie/inc/TMVA/ROperator_Identity.hxx
This PR adds the handling of the Dropout layer in SOFIE Keras Parser. As dropout will not have any effect on inference, thus it should be mimicked as an identity operator while parsing and in the generated inference code.
=> [TMVA][SOFIE] Handling Dropout layer in SOFIE Keras Parser

README/ReleaseNotes/v628/index.md, math/mathcore/inc/Math/Util.h
Adds release notes for 6.28, as requested in #11856.
Additionally, it adds two equality operators and a note in the documentation of an existing operator. These operators will be used in a later PR.
=> [math] KahanSum release notes for 6.28

bindings/pyroot/pythonizations/CMakeLists.txt
Like this, we are polluting the build and install directories less with unneeded files and it also speeds up the build process a bit if RooFit and/or TMVA are disabled. Their pythonization files don't need to be compiled to `.pyc` files.
=> [PyROOT] Only build RooFit and TMVA pythonizations if needed

gui/gui/inc/TGFileBrowser.h, gui/gui/inc/TRootBrowser.h
This is a small MR for the addition of a few extra public accessor methods for some parts of the root browser classes. These classes are using in the new, experiment, RooBrowser. Having public access to these data members will help with the future development of that feature, and I hope the methods added will be acceptable. 
Please Note: Will need pulling into the 6.28 branch!
=> Extra public accessor methods in root browser classes

core/base/inc/TDirectory.h, core/base/src/TDirectory.cxx
Registrering the thread-local gDirectory with the gROOT (which is special TDirectory) allows to keep the
shared_pointer alive until gROOT is destructed.
Technically we would only need to keep around the one associated with the main thread.  Thread local
storage (and hence the original shared_ptr for the thread local gDirectory) is destructed
(even for the thread local associated with the main thread) before the static storage is destructed.
So prior to this commit, the main thread's gDirectory shared pointer was destructed before
the start of the TROOT destructor and then TDirectory::CleanTargets when using explicitly
'gDirectory' was reading deleted memory.
=> Re-enable registration of thread-local gDirectory to gROOT.

gui/browsable/src/TDirectoryElement.cxx, tutorials/v7/filedialog.cxx
Reported in https://root-forum.cern.ch/t/53224/
=> Fix ROOT files selection with RFileDialog class

tree/ntuple/v7/inc/ROOT/RDaos.hxx, tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/src/RDaos.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/libdaos_mock/libdaos_mock.cxx, tree/ntuple/v7/test/ntuple_storage_daos.cxx
This pull request adds support for the concatenation of RNTuple pages into 'cages' that are then written to, and read from, DAOS containers as a single value of the key-value object store under the same attribute key, thus the smallest addressable unit. Pages from the same page-group are concatenated in the order they are handled on the DAOS side through vector I/O from the sealed pages' buffers. The name 'cage' is a portmanteau of "concatenated pages" and suggests the fact that pages caged together must be read together in DAOS.
This change emancipates the DAOS backend from the original, on-disk ntuple page size. The option to concatenate sealed and buffered pages avoids unnecessary throughput constraints caused by the original page size (e.g., the on-disk default, 64KiB, generally leads …
=> [ntuple,daos] Page concatenation for buffered page-groups

graf3d/gl/src/TGLEventHandler.cxx
Corrects camera center picking feature in GL-based geometry display. The bug is described in #12035 
Applies the screen scaling factor for camera center picked screen coordinates. Fixes the bug reported in this forum [subject](https://root-forum.cern.ch/t/mouse-position-shifts-in-geometry-display/52937/4)
This PR fixes #12035
=> Fix GL viewer camera center picking for retina displays.

core/textinput/src/textinput/TextInput.cpp, core/textinput/src/textinput/TextInput.h, interpreter/cling/lib/UserInterface/UserInterface.cpp, interpreter/cling/test/Driver/CommandHistory.C, interpreter/cling/test/Driver/Inputs/cling_history
1. Environment variable `CLING_HISTFILE` to specify history file path.
2. Environment variable `CLING_HISTSIZE` to specify history size. The original behavior is to not set the history size explicitly.
That is equivalent to unlimited history size according to `textinput::History::AppendToFile()`  (history file will never be pruned so it grows indefinitely). This is probably not most users expect. @Axel-Naumann, @vgvassilev do you think it makes sense to set default cling history size to something like 500 ?   (That changes current behavior.)
=> [Cling] improve cmd history support

roofit/roofitcore/inc/RooRealVar.h
In ecd98632, the class version of the `RooAbsArg` class was incremented.
As explained in #8791, there are sometimes warnings in the IO of derived classes if their version number is not increased as well.
Increasing the class version of RooRealVar indeed fixes this warning that one gets right now when reading old workspaces:
```
Warning in <TStreamerInfo::BuildCheck>:
The StreamerInfo of class RooRealVar read from file toyws/WS-VHbb-STXS_mu_toy_new.root
has the same version (=8) as the active class but a different checksum.
You should update the version to ClassDef(RooRealVar,9).
Do not try to write objects with the current class definition,
the files will not be readable.
Warning in <TStreamerInfo::CompareContent>: The following data member of
the on-file layout version 8 of class …
```
=> [RF] Increase version number of `RooRealVar`

core/base/inc/TVirtualPad.h, graf2d/gpad/inc/TPad.h, graf2d/gpad/src/TPad.cxx
This is needed so that the new RooBrowser doesn't need to access the private collision grid of the TPad. These additional options allow the placement of the box with choice of priority over directions as well as option to place within the margins of the pad. 
Wanted for 6.28 release too!
=> [graf] Additional options for `TPad::PlaceBox()` method

roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/src/RooAbsPdf.cxx
Adds offsetting named argument to `RooAbsPdf::fitTo()` as requested in #11856. I have decided to use the naming convention for the named argument options that was already present in `RooAbsPdf::CreateNLL()` to avoid confusion and for the potential case that the other named argument options in the latter will also be added to `RooAbsPdf::fitTo()`
=> [RF] Added offsetting to `RooAbsPdf::fitTo`

core/metacling/src/TClingCallFunc.cxx, core/metacling/test/TClingCallFuncTests.cxx
This fixes root-project/root#11930
=> Check if a callfunc returns void before setting the return result.

tree/ntuple/v7/inc/ROOT/RClusterPool.hxx, tree/ntuple/v7/src/RClusterPool.cxx
This pull request slighly improves RClusterPool to reduce contention (due to `fLockXxxQueue` being held) in I/O and unzip
threads.
To this end, each thread keeps its local buffer of elements to be processed.  On wakeup, the local copy is swapped with `fXxxQueue`, which not only reduces contention but also reduces the overall number of allocations, as the internal storage of both copies is reused.  The local copy should be cleared before the `std::swap()` in the next iteration.
Also, the unzip thread is just notified once after all the elements are pushed into the queue.
=> [ntuple] Improve I/O and unzip queue management in `RClusterPool`

core/base/inc/TVirtualPad.h, graf2d/gpad/inc/TPad.h, graf2d/gpad/src/TPad.cxx, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooRealVar.h, roofit/roofitcore/src/RooAbsPdf.cxx
This is a backport of all the relevant RooFit PRs that were recently merged to master to v6-28-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/12114
2. https://github.com/root-project/root/pull/12066
3. https://github.com/root-project/root/pull/12001
Related to https://github.com/root-project/root/issues/11856.
=> [v628][RF] Backports of RooFit PRs to `v6-28-00-patches`: Part 8

CMakeLists.txt, core/CMakeLists.txt, core/base/CMakeLists.txt, core/clib/CMakeLists.txt, core/clingutils/CMakeLists.txt, core/cont/CMakeLists.txt, core/foundation/CMakeLists.txt, core/gui/CMakeLists.txt, core/imt/CMakeLists.txt, core/lz4/CMakeLists.txt, core/lzma/CMakeLists.txt, core/macosx/CMakeLists.txt, core/meta/CMakeLists.txt, core/metacling/src/CMakeLists.txt, core/multiproc/CMakeLists.txt, core/newdelete/CMakeLists.txt, core/rint/CMakeLists.txt, core/sanitizer/CMakeLists.txt, core/testsupport/CMakeLists.txt, core/textinput/CMakeLists.txt, core/thread/CMakeLists.txt, core/unix/CMakeLists.txt, core/winnt/CMakeLists.txt, core/zip/CMakeLists.txt, core/zstd/CMakeLists.txt, tmva/pymva/test/CMakeLists.txt, tmva/sofie/test/CMakeLists.txt
This is an old branch I had from when I was working on ROOT, but at the time I could not merge it because it required at least CMake 3.12 to work, and we were still requiring only 3.9 at the time. I took the time to rework the commits against the current master yesterday and today, as rebasing was too hard. The original pull request that contained these changes was https://github.com/root-project/root/pull/4299, but the refactoring of core/ was removed. I hope now this would be ok to merge to simplify a bit how libCore is built and avoid having to add include directories by hand to targets that link against libCore.
=> Some refactoring of the build system of core/

roofit/roofitcore/inc/RooWorkspace.h, roofit/roostats/src/RooStatsUtils.cxx
For ROOT 6.26, the `RooWorkspace::getSnapshots()` method was introduced in commit 460a58cb28.
However, the signature was not what it should have been: it returned a copy of the snaphot list instead of a `const` reference.
This is fixed now, which also uncovered a bug in some RooStats code where the snapshots are supposed to be transferred from one workspace to another, but they were just appended to the new list that was returned by `getSnapshots()`, so whe whole code had no effect.
This is fixed now by correctly using `RooWorkspace::saveSnapshot()`.
=> [RF] Fix signature of `RooWorkspace::getSnapshots()`

tutorials/roofit/rf613_global_observables.C, tutorials/roofit/rf613_global_observables.py, tutorials/roofit/rf614_binned_fit_problems.C, tutorials/roofit/rf614_binned_fit_problems.py
A new tutorial is added that explains how to deal with the bias and numerical instabilities in binned fits.
=> [RF] New tutorial about bias and numeric issues in binned fits

core/CMakeLists.txt
Commit a74454ae2d moved `rootcling_stage1` before the other directories, which broke sanitized builds because `core/sanitizer` defines the library `ROOTStaticSanitizerConfig` that `ROOT_EXECUTABLE` links in - if available. Solve this by moving `add_subdirectory(sanitizer)` first in the list.
=> Fix AddressSanitizer build

gui/browsable/src/TDirectoryElement.cxx
Move GetContent method to TDirectoryElement where it should be.
Fixes #12110
=> Fix compilation error in rbrowsable

interpreter/CMakeLists.txt
`verifyPreservedAnalysis()` is super slow these days. It gets run when assertions are one (!NDEBUG). Turn this off unless told to build a Debug build of ROOT (where time does not matter, and is expected to not be representative for reality) or where LLVM_BUILD_TYPE is turning asserts on.
(cherry picked from commit 92c90e8deff323fd2eab700e384dd3944b754471)
=> 6.28: [cmake] Disable llvm-assertions for ROOT=RelWithDebInfo:

tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/ntuple_storage_daos.cxx
This Pull request adds Google Test fixture functionality in the RNTuple DAOS test suite, enabling automatic storage cleanup when running unit tests with real DAOS clusters.
- Introduces a fixture class for the test suite and registers all five existing tests under it through the `TEST_F` macro. 
- Consolidates shared functionality in the fixture definition. Namely, pool and container label data and expected diagnostics messages from `ROOT::TestSupport`. 
- Uses the `TearDownTestSuite()` call to automatically destroy DAOS containers created for the unit tests when all of them are completed.
- Replaces some duplicated string literals that specify ntuples and models for variables.
- Introduces preproc definition `R__DAOS_TEST_MOCK` to CMake to bypass container destruction system call if …
=> [ntuple,daos] Improve test suite with fixture class and teardown functionality

build/rmkdepend/def.h, build/rmkdepend/include.c
```
build/rmkdepend/include.c:306:28: warning: ‘%s’ directive writing up to 8190 bytes into a region of size between 1 and 8191 [-Wformat-overflow=]
306 |          sprintf(path, "%s/%s", *pp, include);
|                            ^~
```
Apple needs to be told to expose snprintf...
(cherry picked from commit 19909eb71a5ce5a066ca4588e62ff012dec0bb7c)
=> v6.28: [rmkdepend] Use snprintf against warning (GCC 12.2):

interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.h
With the upgrade, BackendPasses was modifying a TargetMachine that was not used by SimpleCompiler.
Change that by
- using a SimpleCompiler that uses IncrementalJIT::TM;
- moving the TM creation to IncrementalJIT, and giving access to it
This reduces the runtime of https://github.com/root-project/root/issues/11927 to
- before llvm upgrade: 2.69s
- llvm13, without this commit: ???
- llvm13, with this commit: 2.89s i.e, a slow-down of 7% (that is likely caused by the different emission mechanism of Orc-v2; to be confirmed...)
(cherry picked from commit d3793f2bb8c5948f4c64947c7f76fb0b0e1a3567)
=> v6.28: [cling] Re-enable CodeGen-OptLevel after llvm13 upgrade:

tree/treeplayer/src/TTreeReaderArray.cxx
This alleviates #11769 by explicitly failing rather than doing the wrong thing silently
=> TTreeReader: error out for STL within TClonesArray.

bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py, core/base/inc/TDirectory.h, core/base/inc/TROOT.h, core/base/inc/TThreadSlots.h, core/base/src/TDirectory.cxx, core/thread/src/TThread.cxx, io/io/inc/TDirectoryFile.h, io/io/src/TDirectoryFile.cxx
This fixes #11907
Inadvertently a previous commit (79a669b) disabled the ability to cleanup the thread local gDirectory in other
threads when the TFile they pointed to is deleted.
Also fix a set of rare race conditions:
Fix race condition between RegisterContext and gDirectory cleanup.
Description of the race conditions:
(1) thread one create TFile, gDirectory now points to that file.
(2) thread two delete TFile, the destructor calls CleanTargets which has 4 distinct phase
(a) take the TFile spin lock and update all the TContext that points to the file
(b) still hold the spin lock, clean the other thread's directory.
(c) deal with the TContext that were being destructed at the same time
(d) update the local gDirectory
If between (2)(a) and (2)(b), thread (1) starts the creation of a …
=> v626: Reenable the cleanup of gDirectory in other threads upon file deletion.

interpreter/CMakeLists.txt
Fixes that CMake was still trying to look for `llvm-config-9` instead of `llvm-config-13` after for #10294.
To prevent this I added two variable in the beginning of the file so that it is less likely to be forgotten next time. I also moved the versioned version before the unversioned one. This should make sure it actually takes the right version if `llvm-config` defaults to a version that is not 13 (currently the case in Debian e.g.).
/cc @hahnjo @vgvassilev @bellenot
=> CMake: fix incorrect version for finding llvm-config

cmake/modules/RootConfiguration.cmake
This might fix e.g. `-mmacosx-version-min=12.6` not being passed to ACLiC, causing linker warnings about incompatible deployment targets.
=> [cmake] There is no CMAKE_EXE_FLAGS, use CMAKE_EXE_LINKER_FLAGS:

roofit/histfactory/src/HistFactoryNavigation.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.h, roofit/roofit/inc/RooExpPoly.h, roofit/roofit/inc/RooPower.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooBinnedL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooSubsidiaryL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooSumL.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
This is a follow-up to https://github.com/root-project/root/pull/12040.
The `RooAbsArg::redirectServer()` method is dangerous and should not be used directly. It was for example used wrongly in HistFactory. In the RooAbsAnaConvPdf is was actually used correctly, but it's still better to use `redirectServers()` consistently, which avoids the new warnings you get when using `redirectServer()`.
More detail in the commit description.
Also includes a commit that irons over RooFit with `clang-tidy`, adding some missing overrides.
=> [RF] Avoid using `RooAbsArg::redirectServer()` in RooFit

tmva/pymva/test/testPyKerasClassification.C, tmva/pymva/test/testPyKerasMulticlass.C, tmva/pymva/test/testPyKerasRegression.C, tmva/pymva/test/testPyTorchMulticlass.C, tmva/pymva/test/testPyTorchRegression.C
This PR should fix the failures of some PyTorch tests caused by using Python2 instead of Python3
=> [tmva][pymva] Use correct python executable for the Keras and PyTorch  tests

interpreter/cling/lib/Interpreter/BackendPasses.cpp, interpreter/cling/lib/Interpreter/BackendPasses.h, interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.h
With the upgrade to llvm-13, the JIT lost the ability to re-use existing weak
symbols that the JIT had already emitted, instead only looking at dlsym. This
causes a significant increase in JITted symbols, and thus a significant slow-down
of cling / its JIT.
This restores the old behavior, with an identical set of symbols that jet jitted.
(cherry picked from commit 23ca9fe)# This Pull request:
=> [cling] Reuse existing weak symbols, also from JIT:

core/base/inc/TDirectory.h, core/base/src/TDirectory.cxx
It is broken by design, there is no way that this interface can
be used in a safe way. Just get rid of it.# This Pull request:
=> v6.28: [base] Deprecate TDirectory::EncodeNameCycle():

builtins/zeromq/libzmq/CMakeLists.txt
GitHub repacks archives from time to time, which changes the hash.
(cherry picked from commit 43003424171111fb2d8ec6fd182001c57ed6901a)
Backport of https://github.com/root-project/root/pull/12175
=> 6.28: [cmake] Use lcgpackages for libzmq.tar.gz:

builtins/zeromq/libzmq/CMakeLists.txt
GitHub repacks archives from time to time, which changes the hash.
=> [cmake] Use lcgpackages for libzmq.tar.gz:

core/base/inc/TDirectory.h, core/base/src/TDirectory.cxx, core/foundation/inc/ROOT/RConfig.hxx
=> Remove `TDirectory::EncodeNameCycle()`, enable `R__DEPRECATED(6,32`

tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx, tree/dataframe/inc/ROOT/RDF/RSampleInfo.hxx, tree/dataframe/src/RDatasetGroup.cxx, tree/dataframe/src/RDatasetSpec.cxx, tree/dataframe/src/RLoopManager.cxx
The important commit is [[DF] Make dataset group an optional data member of RSampleInfo](https://github.com/root-project/root/commit/ad6ecd8227786f363f48be207d45b0f86d6357e5): it short-circuits some logic so that we don't construct a RDatasetGroup object if we don't have to, and we copy pointers to RDatasetGroups instead of RDatasetGroup objects.
It also introduces a change in behavior: RDF now throws if a user asks for information about the dataset group but there is no group available. Before that commit it would return some arbitrary value for each of the properties (e.g. empty string, 0, ...).
This should fix the performance regression seen in some Grafana benchmarks on the evening of the 15th of December.
=> [DF] Remove performance overhead in construction of RSampleInfo

interpreter/llvm/src/include/llvm/Support/Compiler.h
We really need these symbols to be hidden. Solves
https://github.com/root-project/root/issues/12170
```
Unable to find target for this triple (no targets are registered) *** Break *** abort
```
where the llvm of PyTorch ends up using the RegisterTarget function of the llvm of cling.
=> [llvm] Override llvm-visibility-default:

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx, bindings/pyroot/cppyy/patches/PyROOT-Use-non-deprecated-API-to-initialize-Python.patch
Taken from part of https://github.com/wlav/CPyCppyy/commit/64fd89050a66bf8cb119f236cadd365efa07b005
=> [PyROOT] Use non-deprecated API to initialize Python interpreter

hist/histpainter/src/TPaletteAxis.cxx
The TH3 Palette title was wrongly equal to the za-xis title.
this was found here:
https://root-forum.cern.ch/t/z-bad-label-for-palette-axis-in-th3d/53317/4
=> TH3 palette title was equal to the z-axis title

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
=> [6.28] Avoid deprecated numpy.object

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
The custom memory manager is only needed to avoid freeing the memory segments; the default `InProcessMemoryManager` (which is mostly copied) already does slab allocation to keep all segments together which is
needed for exception handling support.
A limitation of this rudimentary support is that `CLING_DEBUG` and `CLING_PROFILE` do not work, they need to be registered as plugins.
=> [cling] Add back basic support for JITLink

roofit/roofitcore/inc/RooEffGenContext.h, roofit/roofitcore/src/RooEffGenContext.cxx, roofit/roofitcore/src/RooRealIntegral.cxx
Fixes some small issues with debug printout during integration or generation
The first commit changes the debug printout in `RooRealIntegral::evaluate`. `_mode` here is the analytical integral code, `_intOperMode` is the variable that can be `Hybrid`, `Analytic` or `PassThrough` (like in the switch-case above).
The second commit adds `printMultiline` to `RooEffGenContext`. This is used when requesting verbose printout during dataset generation, which is supposed to recursively print all gen contexts. Before this change, having a `RooEffProd` inside the model stopped the recursive printout.
=> [RF] Small fixes to debug printout in RooRealIntegral and RooEffGenContext

build/rmkdepend/include.c
```
/home/vpadulan/programs/rootproject/rootsrc/build/rmkdepend/include.c:306:37: warning: ‘%s’ directive output may be truncated writing up to 8190 bytes into a region of size between 1 and 8191 [-Wformat-truncation=]
306 |          snprintf(path, BUFSIZ, "%s/%s", *pp, include);
```
=> [rmkdepend] Work around GCC format truncation warning:

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/inc/RooVDTHeaders.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/roofitcore/inc/RooTruthModel.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooTruthModel.cxx, test/stressRooFit_tests.h, tutorials/roofit/rf704_amplitudefit.C, tutorials/roofit/rf704_amplitudefit.py
1. Don't use RooTruthModel in `rf704_aplitudefit` tutorial
2. Register correct servers in RooTruthModel
3. Ignore whitespaces diffs in RooTruthModel basis code matching
4. Change some casts that were too specialized
5. Implement RooTruthModel in RooBatchCompute library
=> [RF] Fixes and improvements to `RooTruthModel` and related tutorials

tree/ntuple/v7/doc/specifications.md
See also the former PR that introduces this projected field: #12008.
=> [skip-ci][ntuple] specifications.md: document `RNTupleCardinality`

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RColumnModel.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Add the concept of column representations to fields. Every fields can have a set of possible column representations for writing and additional column representations for reading. When reading, the column representation is fixed by the on-disk data. On writing, there is a default column representation but the user can pick a different one.
This provides the framework to store data in different encodings (e.g., split, unsplit) and to load data from "compatible columns", e.g. `kInt32` column into `std::int64` type.
As an example, the PR adds support for split and unsplit storage of `double`s. Follow-up PRs will complete the available encodings and select split encode as the default for writing.
=> [ntuple] Allow for storing fields in different column representations

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
This PR re-exposed the field type of an `RNTupleView` which otherwise must be matched out from the template signature (e.g. via `boost::mp11::mp_first).
=> [ntuple] Re-expose field type of RNTupleView

tree/dataframe/test/dataframe_datasetspec.cxx
This is a backport of #12025 by @hahnjo and fixes the corresponding test failure in v6-28-00-patches.
=> [DF] Removing failing test with shorter friends (v6.28)

core/metacling/test/TClingCallFuncTests.cxx
Detected with -Ddev=ON cmake flags
=> Add missing include to metacling test

math/vecops/CMakeLists.txt
The performance gains are unclear and the option can harm users linking against the library with gcc<13, see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55522 .
EDIT: relevant forum conversation: https://root-forum.cern.ch/t/rootvecops-enables-ffast-math/53422
=> [VecOps] Avoid -ffast-math

.github/workflows/rootci-installers/buildconfig/global.txt, .github/workflows/rootci-installers/buildconfig/mac12.txt, .github/workflows/rootci-installers/buildconfig/ubuntu18.txt, .github/workflows/rootci-installers/buildconfig/ubuntu20.txt, .github/workflows/rootci-installers/buildconfig/windows.txt, cmake/modules/RootBuildOptions.cmake, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/jsoninterface/CMakeLists.txt, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONInterface.cxx
ROOT introduced a build flag in 6.26.00 that allowed you to build it using the `ryml` library instead of nlohmann-json as the backend for the JSON IO.
But that was not particularly great. The `ryml` backend code is at risk of rotting, because to try and test it one needs a special ROOT build.
It would be much better to just build both backends if `ryml` is installed on the system, and have a mechanism for developers to try this other backend. This is implemented in this commit.
=> [RF] Make it possible to switch to `ryml` backend after building ROOT

.github/workflows/buildroot.yml, .github/workflows/rootci-installers/build_root.py
[skip-ci]
Makes the CI load OpenStack object-store credentials from files on runners instead of using GitHub secrets.
When `pull_request` is a workflow trigger, the job can't access secrets, which means that the S3 secret token is unavailable. Adding S3 credentials to the runners themselves solves this issue.
The OpenStack credentials are defined [here](https://gitlab.cern.ch/ai/it-puppet-hostgroup-lcgapp/-/blob/rootci_test/code/manifests/build/root.pp#L43) (using [teigi](https://configdocs.web.cern.ch/secrets/adding.html))
If a malicious actor makes a PR with a job to print the credentials, or to upload a malicious artifact, it would still have to be approved by a maintainer.
A safer alternative is not allowing pull request jobs to upload artifacts at all but then we can't run tests in a …
=> [CI] load openstack credentials from file

roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/src/static_execute.h, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONInterface.cxx, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.cxx
RooFit uses doubles everywhere else, so if importing a model from JSON
should give the same biswise results as creating the model in the
workspace factory language, `double` needs to be used in the JSON
interface too.
There is also another commit  that fixes a typo, and another commit that adds an easy way to fill lists via the JSON interface in order to reduce the number of lines of code needed.
=> RF] Use `double` and not `float` all the way in RooFit JSON IO 

.clang-format
We use the `clang-format` style of ROOT for all the new source files in RooFit, but some code looks pretty ugly. For example, here in the constructor of `RooNLLVarNer`:
```C++
RooNLLVarNew::RooNLLVarNew(const char *name, const char *title, RooAbsPdf &pdf, RooArgSet const &observables,
bool isExtended, RooFit::OffsetMode offsetMode, bool binnedL)
: RooAbsReal(name, title), _pdf{"pdf", "pdf", this, pdf}, _observables{getObs(pdf, observables)},
_isExtended{isExtended}, _binnedL{binnedL}, _weightVar{"weightVar", "weightVar", this, *dummyVar(weightVarName),
true,        false,       true}, ...
```
Really not great to have all the elements in the constructor initializer list in one line. It's hard to read, there are weird line breaks, and if you only change one member it looks like you have …
=> Change `clang-format` style to have line breaks in c'tor initializer

roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/test/testRooAbsPdf.cxx
Since a few weeks, having pdfs with the same name in a RooSimultaneous fit with BatchMode didn't work anymore. This was because when setting up the computation graph for a given normalization set, all pdfs are cloned and redirected with `RooAbsArg::redirectServers()`, which doesn't work if servers have the same name.
This commit suggests to instead delete the pdf servers and proxies and then recreate them by hand.
Also, the logic of `RooSimultaneous::compileForNormSet()` was updated to iterate directly over the pdfs instead of iterating over the index categories and then getting the pdfs.
The unit tests in `testAbsPdf` are now also parametrized to cover both BatchMode on and off, such that the case of the `RooSimultaneous` with one pdf in used in two channels is also covered buy the tests …
=> [RF] Support again same-name pdfs in RooSimultaneous with BatchMode

tree/tree/src/TSelectorList.cxx
Should fix the failure of tutorial/tree/run_h1analysis.C on Win64
=> Don't cast a TDirectory pointer argument to a Long_t (even if its value is 0)

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/draw/TRatioPlotPainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Do not create title for second histogram in web canvas
2. Preserve custom stats box
3. Properly handle violin and candle draw options
4. Labels position on reversed axes
=> Fixes in web canvas and JSROOT for 6.28 branch

roofit/roofitcore/test/testRooAbsPdf.cxx, roofit/roofitcore/test/testRooBinSamplingPdf.cxx, roofit/roofitcore/test/testRooProdPdf.cxx, roofit/roofitcore/test/testRooRealIntegral.cxx, roofit/roofitcore/test/testTestStatistics.cxx
Some new tests need the backward compatibility tweaks to work with the system gtest on RHEL/EPEL 8.
=> Fix build with -Dbuiltin_gtest:BOOL=OFF on EPEL 8

hist/hist/inc/TGraph.h
Backport the TGraph::SaveAs MENU fix from master
=> Backport the SaveAs MENU fix from master

tree/tree/inc/ROOT/InternalTreeUtils.hxx, tree/tree/inc/ROOT/RFriendInfo.hxx, tree/tree/src/InternalTreeUtils.cxx, tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx, tree/treeplayer/src/TTreeProcessorMT.cxx
First draft of creating a new utility function that allows creating the friend trees starting from an RFriendInfo object and attaching them to a tree. This required also taking care of the possibility of knowing/using entries of the friends. As a first example, the new functionality is used in TTreeProcessorMT
=> Add utility function to retrieve friend entries and use it in TTreeProcessorMT

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/test/test_headnode.py, bindings/experimental/distrdf/test/test_proxy.py, tree/dataframe/CMakeLists.txt, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/src/RInterface.cxx, tree/dataframe/src/RLoopManager.cxx
UPDATE:
The RDataFrame created in each task can now be modified with the correct entry range of the task via an internal function. The internal representation in case of an RDataFrame with no data source has been modified to store a pair of integers indicating the range, instead of only one integer. This is only for internal purposes, the public API is unchanged
See https://github.com/root-project/roottest/pull/923 for test changes
=> Remove usage of Range in empty source distributed mode

roofit/batchcompute/inc/RooSpan.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/inc/RooHelpers.h, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooHelpers.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This PR uses clad to calculate the AD-based derivatives for the C/C++ functions wrapped by the RooFuncWrapper class and introduces the 'getGradient' interface to get these derivatives from the generated gradient function. It also replaces a `std::span` templated type with `std::size` to avoid conflicts with system headers.
=> [RF] Add clad derivative support to RooFuncWrapper

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/test/test_headnode.py
We do not support it at the moment, so better to raise an explicit error.
=> [DF] Error out when TTreeIndex is used in distributed mode

tree/ntuple/v7/src/RColumnElement.cxx
Apparently, this is not required as the symbol is always emitted; removing as it also triggers the `clang` warning below
```
/home/jhahnfel/ROOT/src/tree/ntuple/v7/src/RColumnElement.cxx:62:49: warning: explicit instantiation of 'Generate<void>' that occurs after an explicit specialization has no effect [-Winstantiation-after-specialization]
ROOT::Experimental::Detail::RColumnElementBase::Generate<void>(EColumnType type);
^
/home/jhahnfel/ROOT/src/tree/ntuple/v7/inc/ROOT/RColumnElement.hxx:597:57: note: previous template specialization is here
std::unique_ptr<RColumnElementBase> RColumnElementBase::Generate<void>(EColumnType type);
^
1 warning generated.
```
Thanks for reporting @hahnjo!
=> [ntuple] Remove unneeded `RColumnElementBase::Generate<void>` instatiation

roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commit separates the parameters and observables passed to RooFuncWrapper. Now, the wrapper function accepts two different arrays and only calculates the gradient of the underlying func wrt. the parameter array.
=> [RF] Add observables as another parameter in RooFuncWrapper.

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/inc/RooDataSet.h, roofit/roofitcore/inc/RooGlobalFunc.h, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooBinnedGenContext.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/src/RooVectorDataStore.cxx, roofit/roofitcore/test/testRooBinSamplingPdf.cxx, roofit/roofitcore/test/testRooDataSet.cxx, roofit/roofitcore/test/testTestStatistics.cxx, roofit/roostats/src/DetailedOutputAggregator.cxx
Several improvements to the [`RooDataSet` constructor](https://root.cern.ch/doc/master/classRooDataSet.html#a6a2302f27e1b016a0351f6e0a0329fa2) that takes command arguments to import other data:
1. Automatically create weight variable when importing multiple data slices (closes #11487)
2. Support importing also RooDataHists (also as slices for combined datasets), and filling the weight errors correctly to match the `weightSquared()`
3. Create the weight variable on the fly if it was specified by name in `WeightVar()` but is not in the list of variables
4. Have a default argument for `WeightVar(="weight")`, because that's usually the name anyway
5. Fix `RooVectorDataStore::loadValues()` for loading values from another vector data store: so far it used `assignValueOnly` to copy the values …
=> [RF] Improve importing other `RooAbsData` when creating a `RooDataSet`

roofit/histfactory/src/ParamHistFunc.cxx, roofit/roofit/inc/RooIntegralMorph.h, roofit/roofit/src/RooIntegralMorph.cxx, roofit/roofit/src/RooParamHistFunc.cxx, roofit/roofitcore/inc/RooAbsCategoryLValue.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooAbsCategory.cxx, roofit/roofitcore/src/RooAbsCategoryLValue.cxx, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooBinIntegrator.cxx, roofit/roofitcore/src/RooBinSamplingPdf.cxx, roofit/roofitcore/src/RooCategory.cxx, roofit/roofitcore/src/RooCompositeDataStore.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooDataProjBinding.cxx, roofit/roofitcore/src/RooFormula.cxx, roofit/roofitcore/src/RooFormulaVar.cxx, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooHistPdf.cxx, roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooRealAnalytic.cxx, roofit/roofitcore/src/RooRealBinding.cxx, roofit/roofitcore/src/RooRealVar.cxx, roofit/roofitcore/src/RooTreeDataStore.cxx, roofit/roostats/src/BayesianCalculator.cxx, roofit/roostats/src/HypoTestInverter.cxx, roofit/roostats/src/HypoTestResult.cxx
In `RooAbsCategoryLValue::setBin()`, there is a check for passing a
named binning, because the function doesn't support named binnings.
However, if a binning with that name doesn't exist, it is fine to not
error out, because the default range is used.
This supports the fit in this forum post:
https://root-forum.cern.ch/t/roosimultaneous-and-roofftconvpdf/53606
There are also two additional commits with some code modernization as usual.
=> [RF] Support `RooAbsCategoryLValue::setBin()` for non-existing ranges 

roofit/roofit/test/testRooKeysPdf.cxx, roofit/roofitcore/src/RooGenContext.cxx
The code branch without a proto data in `RooGenContext` already did this, and now it's also done when using proto dataset generation.
Closes #12286.
=> [RF] Correctly normalize max possible val in generation with proto data

tutorials/tmva/TMVA_CNN_Classification.C, tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/TMVA_RNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.py
Run tutorials with a maximum of 4 threads to avoid MT problems on some machines. Disable also OpenMP when running in MT in ROOT
Reduce also by a factor of 5 the number of input events
=> [tmva] Speed up TMVA CNN and RNN tutorials

tmva/pymva/src/PyMethodBase.cxx
fixed a bug in tmva/pymva/src/PyMethodBase.cxx
=> fix a line in PyMethodBase.cxx which make it fail to build

hist/hist/src/TGraph.cxx, hist/hist/src/TH1.cxx
`SetOptStats` --> `SetOptStat`
=> Fixing a typo in the documentation: `SetOptStats --> SetOptStat`

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
It would be nice if HistFactory propagated some additional information from the input objects to the workspace. For starters, the titles of observables could be taken from the axis of the input histograms, and channel and sample names from the titles of histograms. 
It would be good to think about how to best port over additional info (like histogram styling) once we have settled on a convention for that!
=> HistFactory improvement: where appropriate, take titles from input objects

gui/canvaspainter/src/RCanvasPainter.cxx, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebWindowWSHandler.hxx, gui/webdisplay/src/RWebWindowsManager.cxx, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/modules/core.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/webwindow.mjs, ui5/canv/controller/Canvas.controller.js, ui5/canv/view/Canvas.view.xml
In Chrome browser one can change window size from JavaScript using `window.resizeTo` method
This solves problem when different `RWebWindow` instances with different sizes need to be used - 
like in `tutorials/geom/geodemo.C`.
Introduce also X and Y coordinate for `RWebWindow`, use `window.moveTo` to move browser to specified position.
Use this features for `TWebCanvas` to preserve/enforce configured canvas size.
Let change canvas size via context menu.
=> [webwindow] use `window.resizeTo` function for changing web browser size

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RColumnModel.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_merger.cxx, tree/ntuple/v7/test/ntuple_types.cxx
As a follow up of #12133, this PR adds support for the column types
- kSplitReal64
- kSplitReal32
- kSplitInt64
- kSplitInt32
- kSplitInt16
It makes the split encoding the default unless the ntuple is stored uncompressed.
A follow-up PR will take care of kSplitIndex[32|64].
=> [ntuple] Add support for float, double, Int split encodings

README/ReleaseNotes/v630/index.md, math/mathcore/inc/TMath.h, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooNumber.h, roofit/roofitcore/src/RooNumber.cxx, roofit/roofitcore/src/RooTruthModel.cxx
Changing the definition of infinity in RooFit from `1e30` to `std::numeric_limits<double>::infinity()`, and making some other changes that ensure no evaluation errors are logged with this new definition.
* Code-format RooNumber.h and RooNumber.cxx
* Inline infinity constant and checks in `RooNumber`
* Make `TMath::AreEqualAbs()` return `true` when comparing `inf`
* Define infinity as `std::numeric_limits<double>::infinity()`
* RooTruthModel: local `xmin` and `xmax` to make code more readable
* Avoid `sin` or `cos` of infinity in RooTruthModel integral code
* Note change of infinity definition in RooFit
With the increased use of inlined code and simpler comparisons in `RooNumber`, this is also speeding up RooFit.
=> [RF] Define infinity as `std::numeric_limits<double>::infinity()`

geom/geom/inc/TGeoTessellated.h, geom/vecgeom/src/TGeoVGShape.cxx, tutorials/CMakeLists.txt, tutorials/geom/tessellatedNav.C
Added support for tesselated, ellipsoid, hyperboloid and cut tube in the ROOT to VecGeom converter. Added the macro tutorials/geom/tessellatedNav.C importing and raytracing a tessellated solid.
Completes solid conversion to VecGeom support
Adding the macro tutorials/geom/tessellatedNav.C
This PR fixes #11271
=> [geom] Extended TGeoVGShape with extra solids

hist/hist/inc/TH1K.h
Makes lot of warnings when drawing TH1K like in `tutorials/hist/hksimple.C` - any zoom operation makes:
```
Warning in <TH1K::RetrieveBinContent>: this method must be overridden!
```
=> Add missing TH1K::RetrieveBinContent

core/base/inc/TStyle.h, core/base/src/TStyle.cxx, graf2d/graf/inc/TCandle.h, graf2d/graf/src/TCandle.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist2d/TH2Painter.mjs, tutorials/hist/candlescaled.C
* Introduce new `TStyle` attributes
* Keep old `TCandle` static methods - just redirect them to gStyle
* Fix `candlescaled.C` tutorial - was drawing scaled violin, but title was saying un-scaled
* Adjust JSROOT to support new attributes
With these changes TWebCanvas will correctly display histogram from `candlescaled.C` tutorial
=> Use gStyle attributes for candle and violin

roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooMinimizer.h, roofit/roofitcore/src/RooAbsMinimizerFcn.cxx, roofit/roofitcore/src/RooMinimizer.cxx
For the minimization, the RooMinimizer sets the error logging mode
temporarily to `CollectErrors`, which collects all error messages in
strings. This results in a HUGE overhead, which is completely
unnecessary if evaluation error printing is disabled. In that case, the
error evaluation mode should be set to counting only, which is what this
commit implements.
This speeds up fits with frequent evaluation errors a lot, for example
the `testNaNPacker` tests are sped up by 25x.
=> [RF] Avoid overhead of tracking evaluation error messages when not needed

roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/RooAbsCategoryLValue.cxx, roofit/roostats/src/RooStatsUtils.cxx
This is a backport of all the relevant bugfix RooFit PRs that were recently merged to master to v6-26-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/12119
2. https://github.com/root-project/root/pull/12305
Only the first commit that is not code modernization.
Related to https://github.com/root-project/root/issues/11534.
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 27

roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx
Marking the `CloneData()` argument for createNLL explicitly as deprecated and noting in the docs that it is ignored.
There is no reason to support it now. The new BatchMode doesn't clone the data anyway, the new test statistics with multiprocessing need to clone the data for each process anyway, and the old test statistics classes will be deprecated at some point.
Closes the following Jira ticket:
https://sft.its.cern.ch/jira/browse/ROOT-10372
=> [RF] Clearly mark `RooFit::CloneData()` as deprecated

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
Otherwise `LLJIT`'s constructor will ask the `LLJITBuilder`'s `JTMB` to create a `DataLayout`. As we don't propagate the `JTMB` (yet -- we probably should!), this will be wrong if target features influence the `DataLayout`.
This should fix #12293.
=> [cling] Set DataLayout from our TargetMachine

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RColumnModel.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx, tree/ntuple/v7/inc/ROOT/RPage.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_serialize.cxx
In preparation of adding support for the `SplitIndex[32|64]` and `Index64` column types, this PR bumps `RClusterSize_t` from 32bit to 64bit. On-disk representation stays as is, 32bit. This change makes sure that "big clusters" (>512MB) with 64bit offset columns will be properly supported.
=> [ntuple] Bump in-memory representation of offsets to 64bit

math/minuit2/inc/Minuit2/FCNGradAdapter.h
SetErrorDef was not implemented for the FCNGradAdapter used to wrap the user functions in the Minuit interface. This causes that the current set ErrorDef was not used when minimizing but the one set when constructed the function.
This fixes issue #12338
=> [math][minuit] Add missing SetErrorDef for the Minuit2 gradient function

.github/workflows/root-ci.yml
Makes `root-ci` get skipped on forks of the repository
=> [CI] skip root-ci on forks

interpreter/cling/include/cling/std.modulemap
That should fix a recent nightly failure with gcc11
=> [cxxmodules] Add a module for experimental/string_view

tree/dataframe/test/dataframe_friends.cxx, tree/tree/inc/ROOT/RFriendInfo.hxx, tree/tree/inc/TVirtualIndex.h, tree/tree/src/InternalTreeUtils.cxx, tree/tree/src/RFriendInfo.cxx, tree/treeplayer/inc/TChainIndex.h, tree/treeplayer/inc/TTreeIndex.h, tree/treeplayer/src/TChainIndex.cxx, tree/treeplayer/src/TTreeIndex.cxx
This in turn fixes a problem with TTreeProcessorMT and multi-thread
RDataFrame "forgetting" about the TTreeIndexes associated with
input friend trees.
It fixes https://github.com/root-project/root/issues/12260,
"[DF] Bogus data read from indexed friend trees in multi-thread runs".
A test is added for this case as well.
=> [tree] Propagate TTreeIndex info through GetFriendInfo/MakeFriends 

roofit/hs3/CMakeLists.txt, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/Domains.cxx, roofit/hs3/src/Domains.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/JSONIO.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/CMakeLists.txt, roofit/hs3/test/testHS3HistFactory.cxx, roofit/hs3/test/testHS3SimultaneousFit.cxx, tutorials/roofit/rf515_hfJSON.json
* Use proper infinity checks in RooFit HS3
* New `domains` section in JSON to store variable ranges
* Some refactoring of RooFit HS3
* Decouple `RooDataHist` reading from rest of workspace in RooFitHS3
* Add likelihoods and analyses fields for HS3 v2
* Complete also the reading of likelihoods and analysis fields
* Rename fields in JSON file to match new standard
More description in the commit descriptions.
=> [RF] HS3: updates to reflect the suggested changes in the RooFit JSON standard

hist/hist/inc/Math/WrappedTF1.h, math/fumili/inc/TFumiliMinimizer.h, math/fumili/src/TFumiliMinimizer.cxx, math/mathcore/inc/Fit/Fitter.h, math/mathcore/inc/LinkDef2.h, math/mathcore/inc/Math/BasicMinimizer.h, math/mathcore/inc/Math/IFunction.h, math/mathcore/inc/Math/Minimizer.h, math/mathcore/src/BasicMinimizer.cxx, math/mathcore/src/Fitter.cxx, math/mathmore/inc/Math/GSLMinimizer.h, math/mathmore/inc/Math/GSLNLSMinimizer.h, math/mathmore/inc/Math/Polynomial.h, math/mathmore/src/GSLNLSMinimizer.cxx, math/minuit/inc/TLinearMinimizer.h, math/minuit/inc/TMinuitMinimizer.h, math/minuit/src/TLinearMinimizer.cxx, math/minuit/src/TMinuitMinimizer.cxx, math/minuit2/inc/Minuit2/Minuit2Minimizer.h, math/minuit2/src/Minuit2Minimizer.cxx, roofit/roofitcore/src/RooAbsMinimizerFcn.h, roofit/roofitcore/src/RooMinimizer.cxx, roofit/roofitcore/src/RooMinimizerFcn.h, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
The fact that gradient computations are supported in a `ROOT::Math`
function wrapper was only transmitted by the static class type.
However, this is rather inconvenient:
1. If you forget to downcast your function to the gradient type, the
provided gradient won't be used.
2. Many minimizer function signatures must be overloaded for both the
function with and without gradients
3. In RooFit, this caused particular pain: depending on if an external
gradient is provided, the function wrapper in the `RooMinimizer`
needs to have a different base class, and the RooMinimizer needs to
cast it correctly when fitting.
This commit suggests two new virtual functions:
* `IBaseFunctionMultiDimTempl::HasGradient()` for multi-dim functions
* `IBaseFunctionOneDim::HasGradient()` for 1D functions
Like this, …
=> [math] Add virtual HasGradient() to ROOT::Math function base classes and simplify them

math/minuit/src/TMinuitMinimizer.cxx
Because of a mistake in git commit management, merged 4bfa7c58e to master but it was missing a fixup for the `TMinuitMinimizer`.
=> [math] Fixup to commit that added HasGradient() to ROOT::Math functions

roofit/roofitcore/src/RooMinimizer.cxx, roofit/roofitcore/src/RooMinimizerFcn.cxx, roofit/roofitcore/src/RooMinimizerFcn.h, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h
This results in more modular code that is also safer: the `ROOT::Fit::Fitter` has no access to the RooAbsMinimizerFcn anymore, only to the member that is a lightweight adapter. This means the `RooAbsMinimizerFcn` also doesn't get cloned unexpectedly, so we don't need extra checks in the RooMinimizer to account for that!
=> [RF] Composition over inheritance in RooAbsMinimizerFcn implementations

tree/dataframe/src/RDatasetGroup.cxx, tree/dataframe/src/RLoopManager.cxx, tree/tree/src/TChain.cxx, tree/tree/test/TChainParsing.cxx
Fixes https://github.com/root-project/root/issues/11483 .
=> [tree][DF] Backport fix for globbing with `?#` treename token (v6.28)

tree/tree/src/InternalTreeUtils.cxx
In C++14, this would require a definition. This should solve the linking errors about "undefined reference"s in the incrementals.
=> [tree] Avoid odr-using TTree::kMaxEntries

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/test/test_headnode.py, tree/dataframe/test/dataframe_friends.cxx, tree/tree/inc/ROOT/InternalTreeUtils.hxx, tree/tree/inc/ROOT/RFriendInfo.hxx, tree/tree/inc/TVirtualIndex.h, tree/tree/src/InternalTreeUtils.cxx, tree/tree/src/RFriendInfo.cxx, tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx, tree/treeplayer/inc/TChainIndex.h, tree/treeplayer/inc/TTreeIndex.h, tree/treeplayer/src/TChainIndex.cxx, tree/treeplayer/src/TTreeIndex.cxx, tree/treeplayer/src/TTreeProcessorMT.cxx
To avoid the largest merge conflicts this PR also backports some refactoring of RFriendInfo and TTreeProcessorMT.
Fixes #12260 .
=> [DF][tree] Backport fix for MT RDF + TTreeIndex (v6.28)

tutorials/fit/NumericalMinimization.C, tutorials/fit/NumericalMinimization.py
Convert `NumericalMinimization.C` tutorial to Python
=> [math] Add new Python tutorial for minimization

interpreter/cling/lib/Interpreter/CIFactory.cpp
The routines `__aarch64_*` are defined in the static library libgcc.a and not necessarily included in libCling or otherwise present in the process, so the interpreter has a hard time finding them.
Fixes #12294
=> [cling] Disable outline-atomics on AArch64

roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h, roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx, roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx, roofit/roofitcore/test/TestStatistics/testRooRealL.cxx, roofit/roofitcore/test/test_lib.h
* Since the `RooAbsMinimizeFcn` implementations don't need to be copied
anymore, we can use `std::unique_ptr` instead of `shared_ptr` for
clear ownership and less overhead
* Name variables to be consistent with RooFit style
* Streamline `public` and `private` scopes
* Avoid code duplication with new private member function that applies a
specific call to both the regular likelihood and the likelihood in the
gradient
* Additional commit fixes memory leaks of toy datasets in `TestStatistics` tests
=> [RF] Improve code in `MinuitFcnGrad`

core/base/src/TAttText.cxx
Avoid gPad usage when text size given in pixels.
=> Improve TAttText::Modify

tree/tree/src/InternalTreeUtils.cxx
Backport of https://github.com/root-project/root/pull/12352 .
=> [tree] Avoid odr-using TTree::kMaxEntries (v6.28)

tutorials/webgui/qt5web/CMakeLists.txt
One should link now against web geometry viewer library
=> Fix webgui/qt5web cmake file [628] [skip-ci]

tree/ntuple/v7/src/RPageSinkBuf.cxx
This pull request is a backport of https://github.com/root-project/root/pull/12298 to the `v6-28-00-patches` branch.
This fixes an unfortunate memory leak we introduced in https://github.com/root-project/root/pull/10775.
=> [ntuple,v6-28] RPageSinkBuf: add missing call to ReleasePage()

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds a `GetNEntries` method to the `RNTupleInspector` class, so that won't be necessary to have to do this via the `RNTupleReader` or `RNTupleDescriptor` directly.
=> [ntuple] Add GetNEntries to inspector

tree/ntuple/v7/test/ntuple_packing.cxx
As suggested by @pcanal in #12220, adds unit tests to verify the on-disk encoding of split encoded columns
=> [ntuple] improve unit testing of split encodings

math/mathcore/inc/Math/Functor.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commit adds a ROOT::Math::Functor based interface to the minimizer for RooFuncWrapper. A functor based approach allows for the wrapper to choose between using AD/analytical and numerical derivatives easily.
=> [RF] Add initial minimizer interface for RooFuncWrapper

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/SimpleCollectionProxy.hxx
This pull request improves the support for storage of collections that use `TVirtualCollectionProxy`, which was initially landed in #11525.  However, `TVirtualCollectionProxy` allows for traversing a collection using iterators, which should be faster than using `TVirtualCollectionProxy::At()`.  Also, this interface avoids (where possible) an additional copy during element insertion.
- Switches from using `TVirtualCollectionProxy::{Size,At}()` to the use of iterators.  After merging this PR, an implementation for the following functions is required instead: `TVirtualCollectionProxy::GetFunctionCreateIterators()`, `GetFunctionNext()`, and `GetFunctionDeleteTwoIterators`.
This PR fixes #11671.
=> [ntuple] Improve support for classes with an associated collection proxy

tree/tree/src/TBranch.cxx, tree/tree/src/TTree.cxx
as requested here: https://root-forum.cern.ch/t/draw-short-integers-as-numbers-not-characters/52530/31
=> [skip-ci] Update ttree doc

math/minuit2/test/CMakeLists.txt, tutorials/CMakeLists.txt
Then clad is disabled, some tests that use it are still run causing test failures.
This PR vetos thos tests.
(Also removed duplicates in minuit2 veto.)
=> Veto tests using clad when clad is disabled

CMakeLists.txt, build/CMakeLists.txt, core/base/CMakeLists.txt
When roofit is disabled, some roofit related files are still installed.
This PR makes the installation of those files conditional.
=> Don't install roofit files when roofit is disabled

tree/tree/src/TTree.cxx
Recent changes introduced some weird alignment of text in the comments.
This PR restores the alignment.
=> Restore text alignment

math/mathcore/inc/Fit/Fitter.h
When constructing in Python a derived class from Fitter an error occurred caused probably of a not understanding a typedef. See issue #12391
This PR fixes #12391
=> [math] Add virtual destructor to Fitter and fix an issue for PyROOT

interpreter/cling/lib/Interpreter/CIFactory.cpp
The routines `__aarch64_*` are defined in the static library libgcc.a and not necessarily included in libCling or otherwise present in the process, so the interpreter has a hard time finding them.
Fixes #12294
(cherry picked from commit ddf9a8c3d113e3a3d48dbe13b6b4a6bf2338fb7a)
Backport of https://github.com/root-project/root/pull/12353
=> [cling] Disable outline-atomics on AArch64 [v6.28]

bindings/pyroot/pythonizations/python/ROOT/_facade.py
Missing experimental add-on module ROOT.RDF.Experimental.Distributed (DistRDF) should not fail the loading of the rest of the ROOT.RDF namespace.
Also addresses a mismatch in the minimum Python version check in the code vs. cmake.
This PR fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2173518
=> Graceful no DistRDF

tree/tree/inc/TChain.h, tree/tree/src/TChain.cxx, tree/tree/test/TChainParsing.cxx
Davix interprets certain parameters that are passed in the anchor part of the URL (after the `#`). The anchor, however, is also used by `TChain` to pass the treename. This patch looks at the anchor and if it contains an equal sign (`=`), it assumes that it is a parameter list for Davix and not a treename.
See also https://root-forum.cern.ch/t/problem-with-tchain-and-https-turls/53545/7
=> Fix URL parsing in TChain for fragment parameters

cmake/modules/SetUpLinux.cmake
gold is not evolving anymore and causes problems.
=> [cmake] Remove gold as linker option for -Ddev=On:

build/CMakeLists.txt
Use FILTER instead of REMOVE_ITEM since GLOB returns absolute paths
=> Use FILTER instead of REMOVE_ITEM since GLOB returns absolute paths

hist/histpainter/src/THistPainter.cxx
Fix https://github.com/root-project/root/issues/11212
The fix proposed in this PR was not correct: https://github.com/root-project/root/pull/12401
```
void testProblem(){
int   nb = 4;
float x2 = 0.005;
float x1 = 0.0;
auto h1 = new TH1F("h1" ,"h1" ,nb ,x1 ,x2);
auto h2 = new TH1F("h2" ,"h2" ,nb ,x1 ,x2);
double xr1 = h1->GetXaxis()->GetBinLowEdge(2);
h1->GetXaxis()->SetRangeUser(xr1, x2);
h2->SetBinContent(1 ,1000);
h2->SetBinContent(2 ,500);
h2->SetBinContent(3 ,300);
h2->SetBinContent(4 ,50);
h1->SetBinContent(1 ,1000);
h1->SetBinContent(2 ,500);
h1->SetBinContent(3 ,300);
h1->SetBinContent(4 ,50);
h1->SetLineColor(kRed);
auto c = new TCanvas;
c->SetLogx();
h1->Draw();
h2->Draw("same"); //only 3 bins should be visible, the 2 histograms should overlap.
}
```
=> Undesired behaviour with SetRangeUser & Draw->(“same”) & Log Scale

core/cont/src/TList.cxx, roofit/multiprocess/src/HeatmapAnalyzer.cxx
The example for range-based iteration in `TList.cxx` uses a pattern that
can yield compiler warnings for some GCC versions:
```
warning: loop variable 'obj' is always a copy because the range of type 'TList' does not return a reference [-Wrange-loop-analysis]
```
To avoid spreading this pattern, this commit suggests to change the
example to explicitly use the `TObject *` type, which also makes the
example clearer.
One of the occurrences of this pattern in RooFit is also changed to `TObject *` to avoid a warning in the Ubuntu 18 nightlies:
https://lcgapp-services.cern.ch/root-jenkins/job/root-incremental-master/LABEL=ROOT-ubuntu1804-clangHEAD,SPEC=noimt/11389/parsed_console/log_content.html#WARNING1
A memory leak in the `HeatmapAnalyzer.cxx` is also fixed.
=> Avoid warnings when iterating over a TList in a range-based loop with `auto const&&`

tree/ntuple/v7/src/RColumnElement.cxx
Clang 15 warns that the variable v may be used uninitialized because it does not understand the pointer hackery to read individual bytes.
=> [ntuple] Avoid warning about possibly uninitialized variable

roofit/roofitcore/inc/RooProdPdf.h, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/test/testRooProdPdf.cxx
In the ROOT 6.26 development cycle, the RooProdPdf was partially rewritten in moden C++ with less manual memory allocation to improve performance (PR #7907).
In that PR, a unit test that verifies the RooProdPdf can correctly deal with factorizing PDFs was implemented. However, that test used an arbitrary PDF where the correct factorization was checked in a rather crude way: check by hashing the content of the RooProdPdf cache element for a given normalization set that said PR doesn't change any behavior (the reference hash was hardcoded in the unit test).
This commit suggests a better alternative for the unit test, checking for a multidimensional product pdf of factorizing uniform pdfs that the pdf values for differenc normalization sets is as expected. This should cover the same …
=> [RF] Rewrite `RooProdPdf.TestGetPartIntList` unit test

core/base/src/TObject.cxx, io/io/src/TStreamerInfoActions.cxx, io/io/src/TStreamerInfoReadBuffer.cxx, io/io/src/TStreamerInfoWriteBuffer.cxx, test/stress.cxx
Rather than reading from the file the value of kIsOnHeap, preserve the value that was
calculated at object creation time (i.e. in the current execution).  For example, for
an embedded object (inside an object created on the heap or stack), the bit always
need to be off (i.e. it can never be explicitly deleted)# This Pull request:
When reading back the "heap status" is determine by how the
read-into object was allocated, so there is no need to record
that information.
When reading back, the kNotDeleted is always on, (and should
always be on when writing :) ), so there is no need to record it.
Recording '0' for both allow for (slightly) better compression.
Fix https://github.com/root-project/root/issues/12438
=> Do not record kIsOnHeap nor kNotDeleted

hist/histpainter/src/TGraphPainter.cxx, hist/histpainter/src/THistPainter.cxx
When two histograms created with different upper edges of the last bin are drawn in the same pad with a Log y-axis. The edge of the last bin should be drawn as the minimum y value of the pad, instead, it is always set to 1. This artifact is most noticeable when the histogram values are less than 1.
This occurred only when the histogram was drawn as a line, it was correct with a filled area. This patch uses the same algorithm for line drawing as fill area drawing. The problem was seen here: https://github.com/root-project/root/issues/12394
The following macro can be used as a reproducer:
```
{
gStyle->SetOptStat(0);
gStyle->SetOptTitle(0);
auto C = new TCanvas();
C->Divide(2,1);
auto h15 = new TH1F("h15","h15", 3, 10, 15);
auto h25 = new TH1F("h25","h25", 5, 0, 25);
h15->Fill(11,.5); …
```
=> Fix multiple hist drawing in log scale.

core/base/src/TDatime.cxx
Fix a wrong value of `TDatime::GetDateFromGlobalDay()` as reported [on the Forum](https://root-forum.cern.ch/t/correct-global-day-conversion-functions-for-root-tdatime/53938)
=> [skip-ci][windows] Fix TDatime on Windows

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml, .github/workflows/test-result-comment.yml
- (https://github.com/root-project/root/issues/12186) Adds test summaries to builds. Writes comments on pull-requests: [example](https://github.com/olemorud/root/pull/9)
- Adds the `--rm` flag to containers as a temporary fix for the disk space problem (puppet fix coming soon)
[skip-ci]
=> [ci] Add test summary to pull requests

.github/workflows/root-ci.yml
Resolves #12297
Changes the matrix to do some jobs with different options, e.g. `DLLVM_BUILD_TYP=Debug` for one of the ubuntu22 builds. (can be changed).
Also rewrites the matrix to explicitly type each job, instead of doing a N x M jobs. I believe this syntax is easier to configure and makes implementation cleaner, as opposed to using nested lists to provide matrix options.
Example run (picture added in case it expires): https://github.com/olemorud/root/actions/runs/4284703493
=> [CI] Add fine-grained matrix

core/base/src/TDatime.cxx
Fix a wrong value of `TDatime::GetDateFromGlobalDay()` as reported [on the Forum](https://root-forum.cern.ch/t/correct-global-day-conversion-functions-for-root-tdatime/53938)
=> [v6-28][skip-ci][windows] Fix TDatime on Windows

tree/ntuple/v7/src/RField.cxx
After merging #12380, @Nowakus noticed issues when trying to fill entries for a model that includes the ATLAS' `DataVector<T>` type.
This is because a proxied collection, notably those deriving from `TGenCollectionProxy`, apparently rely on an active object also for using iterators. This PR should fix the error below.
```
TGenCollectionProxy    FATAL Size> Logic error - no proxy object set.
```
=> [ntuple] RCollectionClassField: restore missing calls to `PushProxy()`

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/roofit/src/RooNDKeysPdf.cxx, roofit/roofit/test/testRooKeysPdf.cxx, roofit/roofitcore/inc/RooDataSet.h, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/test/testRooDataSet.cxx, roofit/roofitcore/test/testSumW2Error.cxx, roofit/roofitcore/test/testTestStatistics.cxx, roofit/roostats/inc/RooStats/MarkovChain.h, roofit/roostats/src/MarkovChain.cxx, roofit/roostats/src/ToyMCImportanceSampler.cxx
This pull request:
1. Closes #12453, where is was reported that weight errors are lost when splitting weighted datasets.
2. Avoids the associated errors printed when doing the JSON IO of combined RooDataSets (run the unit test `gtest-roofit-hs3-test-testHS3SimultaneousFit` with ROOT master to see them)
3. Avoids the creation of dummy weight variables when constructing RooDataSets in all of RooFit.
=> [RF] Fix splitting of RooDataSets with weight errors and avoid creating dummy weight variables

etc/RooFitHS3_wsexportkeys.json, etc/RooFitHS3_wsfactoryexpressions.json, roofit/hs3/src/Domains.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.cxx, roofit/jsoninterface/src/RYMLParser.h, tutorials/roofit/rf515_hfJSON.json
This is a follow-up on #12467, where  only the top-level fields got migrated from dicts to lists.
This PR migrates the remaining sub-fields that also should be lists according to the HS3 specification.
Also, some other improvements and fixes explained in the commit descriptions are applied.
=> [RF][HS3] Migrate remaining relevant fileds from dicts to lists

tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
This PR is a continuation of #12145 and adds the option to specify the maximum number of entries in the original `TTree` to import.
=> [ntuple] Add `RNTupleImporter::SetMaxEntries()`

README/ReleaseNotes/v630/index.md, roofit/roofitcore/inc/LinkDef.h, roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/inc/RooDataSet.h, roofit/roofitcore/inc/RooHistError.h, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooHistError.cxx, roofit/roofitcore/test/testRooDataHist.cxx
It was not good to have this signature in RooAbsData, because the
implementations in RooDataHist and RooDataSet were inconsistent.
The RooDataSet indeed took the weight error as the third argument, but
the RooDataHist version instead took the sum of weights squared, which
is equivalent to the squared weight error.
That means using `RooAbsData::add(row, weight, weightError)` results in
different weight uncertainties depending on which data implementation
you use. This should not happen. It probably didn't happen to many
people, but I was affected by this when implementing
`RooAbsData::split()` (see https://github.com/root-project/root/pull/12459/commits/909d2564045d1cdb99865c4da6b7e79e463b548f).
The solution to this problem it to remove the `add(row, weight,
weightError)` from the virtual …
=> [RF] Remove `add(row, weight, weightError)` from RooAbsData interface

gui/gui/src/TRootCanvas.cxx
Fix a problem with the editor not appearing when the TCanvas is embedded, [as reported on the Forum](https://root-forum.cern.ch/t/editor-not-appearing-in-gui-canvas/53968)
=> Fix an issue with the canvas editor when the canvas is embedded

tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_test.hxx
Use the replacement `TYPED_TEST_SUITE`, and have a compatibility define for gtest version < 1.10.0.
=> [ntuple] Avoid gtest warnings about deprecated `TYPED_TEST_CASE`

hist/histpainter/src/THistPainter.cxx
Fix https://github.com/root-project/root/issues/12493
=> The option TEXT90 did not work together with COL

roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooFormulaVar.h, roofit/roofitcore/inc/RooGenericPdf.h, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooFormulaVar.cxx, roofit/roofitcore/src/RooGenericPdf.cxx, roofit/roofitcore/src/RooRealIntegral.cxx
The last normalization set should not be stored by pointer because this
can result is false positives when comparing normalization sets by
pointer: a new normalization set might have the same address as the
previous one.
=> [RF] Replace `RooAbsReal::_lastNSet` pointer with ID of last normSet

roofit/roofitcore/inc/RooHistFunc.h, roofit/roofitcore/inc/RooHistPdf.h, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooHistPdf.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooHistPdf.cxx
The RooHistPdf and RooHistFunc should be able to do analytic integration if the input is a linear transformation of a variable using RooLinearVar.
This makes the fits faster where one wants to shift a template on the x-axis, which is for example talked about in this forum post: https://root-forum.cern.ch/t/roofit-pdf-normalization-integration/53905
=> [RF] Enable analytic integration of RooHistPdfs with RooLinearVars

hist/hist/src/TEfficiency.cxx
This Pull request fixes a crash occurring in 6.26 (and older versions) when fitting Efficiency with 2D or 3D functions. 
The crash is caused by copying the TF2 using the copy constructor of TF1. 
It is not happening in 6.28 due to a fix in the Copy function of the TFx classes (see #10942)
=> Fix TEfficiency::Fit  for 2D or 3D fits 

hist/hist/src/TBinomialEfficiencyFitter.cxx, hist/hist/src/TEfficiency.cxx, math/mathcore/inc/Fit/FitResult.h, math/mathcore/inc/Fit/Fitter.h, math/mathcore/src/FitResult.cxx, math/mathcore/src/Fitter.cxx
- Fix also the copying of the TF1 object after fitting. Use IsA()->New() instead of copy constructor which will not work correctly for TF2 and TF3 objects
- Improve the binomial fit used by TEfficiency::Fit by setting the correct chi2 and number of degree of freedom.
For this, add a function in the Fitter class to set number of fit points and to set the fit type flag. When the fit type is a binned likelihood fit use in FitResult as chi2 value to report 2 * NLL
=> [hist] Improve TEfficiency::Fit and handling of binned likelihood fits in FitResult

tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
This PR adds an extra factory function for creating an `RNTupleImporter` by directly providing a pointer to the `TTree` to import, rather than the tree name and file name. With this, it should also become possible to import `TChain`s down the road, but this will require another PR.
=> [ntuple] Add direct importing of TTree objects

hist/histpainter/src/TGraphPainter.cxx, hist/histpainter/src/THistPainter.cxx
Fit params were concerted to float in stats display.
The problem was seen here: https://root-forum.cern.ch/t/root-gstyle-setoptfit-1111/54071/30
=> Fit params were converted to float.

roofit/roofit/src/RooGaussian.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commits adds support for including analytical integrals into the mock code-squashing test by introducing a private header that stores the stateless implementation details.
=> [RF] Add support for differentiating Gaussian integrals using AD.

cmake/modules/RootConfiguration.cmake
This breaks the pattern used when undefining and then defining a variable in the same flag:
```
$ echo | g++ -Wp,-UVAR,-DVAR=1 -c -x c++ -
```
Here -Wp,-UVAR,-DVAR=1 will first undefine VAR and then define it to 1
If the -Wp, is dropped, this fails:
```
$ echo | g++ -UVAR,-DVAR=1 -c -x c++ -
<command-line>: warning: extra tokens at end of #undef directive
```
Now it will only undefine VAR, but not define it. I.e.
instead of
```
#undef VAR
#define VAR 1
```
you get
```
#undef VAR,-DVAR=1
```
which explains the rather cryptic warning about extra token after #undef.
This PR fixes  https://bugzilla.redhat.com/show_bug.cgi?id=2177136
=> Do not remove -Wp, before -D and -U when recording used compiler flags

interpreter/cling/include/cling/std.modulemap
It causes build failures on GCC 12.2.1 / c++17 with
```
[ 70%] Generating G__Core.cxx, ../lib/Core.pcm
In file included from input_line_7:111:
/home/linev/build/webgui/include/ROOT/RDirectoryEntry.hxx:31:33: error: missing '#include <bits/chrono.h>'; 'system_clock' must be declared before it is used
using clock_t = std::chrono::system_clock;
^
/usr/include/c++/12/bits/chrono.h:1110:12: note: declaration here is not visible
struct system_clock
^
In module 'std' imported from input_line_1:1:
/usr/include/c++/12/bits/move.h:204:11: error: missing '#include <bits/chrono.h>'; 'time_point' must be defined before it is used
_Tp __tmp = _GLIBCXX_MOVE(__a);
^
/home/linev/build/webgui/include/ROOT/RDirectoryEntry.hxx:89:4: note: in instantiation of function template specialization …
```
=> Revert recent C++20 related modulemap commits

graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx
`TRatioPlot` defines three pads named `upper_pad`, `lower_pad` and `top_pad`. If single canvas contains two or more `TRatioPlot`s, the saved C macro declares same object variable names resulting in runtime error. This fix adds counter suffix to pads (like for histograms) resulting in unique pad names.
Modifications to `SavePrimitive` members of `TPad` and `TCanvas` to count instances and renumerate written object variable names.
Consider MWE
```c++
{
TH1I * h1 = new TH1I("h1", "h1", 10, -5, 5);
TH1I * h2 = new TH1I("h2", "h2", 10, -5, 5);
h1->FillRandom("gaus", 1000);
h2->FillRandom("gaus", 1000);
TCanvas * can = new TCanvas("c_pads_test", "c_pads_test", 800, 400);
can->cd(0);
TPad * p1 = new TPad("p1", "p1", 0, 0.3, 0.5, 1.0);
p1->Draw();
p1->cd();
TRatioPlot ratio1(h1, …
```
=> Fix issue of multiple declaration of same objects in the saved C macros

core/testsupport/inc/ROOT/TestSupport.hxx, core/testsupport/src/TestSupport.cxx
ROOT::TestSupport checks info/warning/error messages during unit tests. Previously, it would generate one global failure irrespective of how many messages have been received, or how many were missing. It would then list all messages that are being checked, irrespective of whether they were received or not.
Now, each missing or unexpected message generates a dedicated test failure.
```
../../../root-src/core/testsupport/src/TestSupport.cxx:93: Failure
Failed
ROOT::TestSupport::CheckDiagsRAII: Unexpected diagnostic messages received.
../../../root-src/core/testsupport/src/TestSupport.cxx:96: Failure
Failed
ROOT::TestSupport::CheckDiagsRAII: Diagnostic message missing.
-------------------------
Pre-registered messages:
kError	1x received	(required, subMatch)	'prepareMethod' msg='Can't …
```
=> [core] Improve readbility of unit-test-support messages.

tree/dataframe/src/RCsvDS.cxx
When some column types were specified explicitly by the user, RCsvDS forgot to add that type to fColTypesList, which in turn caused RCsvDS::SetEntry to skip the proper loading of some column data.
This fixes #12520.
=> [DF] Fix wrong data in CSV data source with user-defined column types (v6.28)

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx, core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingCallFunc.h
When running RDF/TTreeProcessorMT with large numbers of threads and files with files on xrootd significant lock contention is still present through ```TPluginHandler::LoadPlugin()``` and ```TPluginHandler::ExecPlugin()``` which are called from ```TFile::Open()```.  This PR minimizes the use of locks, which are now only needed the first time a given TPluginHandler is called for various initialization steps.
This change now completely eliminates the use of the global write lock during RDF event loops also for files read from xrootd and finishes addressing https://github.com/root-project/root/issues/7710
For a simple test case:
Create the files:
```cpp
#include "TFile.h"
#include "TTree.h"
#include "TString.h"
#include <thread>
void testwrite() {
const unsigned int nfiles = 4000;
const …
```
=> Reduce usage of locks by TPluginHandler

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/test/SimpleCollectionProxy.hxx
This pull request fixes a misuse of the `TVirtualCollectionProxy` iterator interface.  Specifically the `Next()` and `DeleteTwoIterators()` functions take a pointer to the iterator itself (not a pointer-to-pointer).
The misuse was most likely due to the lack of proper documentation on the `TVirtualCollectionProxy` class.  The documentation for this class should be thus updated in a follow-up PR.
The issue was originally introduced in https://github.com/root-project/root/pull/12380 and first noticed by @Nowakus on March 13, when trying to write a `xAOD::DataVector<T>` into RNTuple.  This PR should fix the observed misbehavior.
=> [ntuple] Fix misuse of the `TVirtualCollectionProxy` iterator interface

tmva/tmva/inc/TMVA/RTensor.hxx, tmva/tmva/test/rtensor.cxx
This PR adds the Resize method in RTensor. The function operates similarly to that of NumPy's [`resize()`](https://numpy.org/doc/stable/reference/generated/numpy.resize.html) method.
=> [TMVA] Resize method for RTensor

roofit/roofit/inc/RooGaussian.h, roofit/roofit/src/RooGaussian.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooAddition.h, roofit/roofitcore/inc/RooConstVar.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/inc/RooNumber.h, roofit/roofitcore/inc/RooProduct.h, roofit/roofitcore/inc/RooRealIntegral.h, roofit/roofitcore/inc/RooRealVar.h, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooConstVar.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNormalizedPdf.cxx, roofit/roofitcore/src/RooNormalizedPdf.h, roofit/roofitcore/src/RooNumber.cxx, roofit/roofitcore/src/RooProduct.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/src/RooRealVar.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commit adds the initial implementation of the code-squashing approach for AD. Users can now squash their models into a single function that can then be used for evaluation, derivative calculation, minimization, etc., through the RooFuncWrapper.
=> [RF] Add initial interface and implementation for code-squashing.

tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
This pull request replaces a variable's type from `size_t` to `uint64_t` to avoid warnings on 32-bit platforms.
The variable is the output of a hashing function and undergoes shifting by 32 bits as the seeding step of a hash combination between the two-halves of a 64-bit value.
The change has no functional impact. It prevents the following compilation warning in 32-bit systems:
```
In file included from /path/to/src/RPageStorageDaos.cxx:29:
/path/to/src/tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx: In static member function ‘static ROOT::Experimental::Detail::ntuple_index_t ROOT::Experimental::Detail::RDaosContainerNTupleLocator::Hash(const string&)’:
/path/to/src/tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx:120:43: warning: right shift count >= width of type [-Wshift-count-overflow]
120 …
```
=> [ntuple,daos] Cast variable to preclude warning in 32-bit

core/metacling/src/TCling.cxx, core/metacling/src/TClingClassInfo.cxx
This fixes #12358.
When unloading a 'compiled' TClass, TClass sets the state of the TClass to the most information possible.  This usually means setting the ClassInfo if the interpreter information is still known about the class.  In the case of `std::tuple` is order to do that we need to generate code that depends on other types (that may also be unloaded), so skip that steps (which lead to 'compilation error' from the interpreter in the report cases (and a crash due to a couple of others issues solved also in this PR).
=> Resolve issue when dictionary with std::tuple is unloaded.

roofit/roofit/inc/RooExponential.h, roofit/roofit/src/RooExponential.cxx, roofit/roofit/src/RooGaussian.cxx, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNormalizedPdf.cxx, roofit/roofitcore/src/RooProduct.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
* fix invalid memory access in RooFuncWrapper by getting observables and parameters of the original function, and not the one that is compiled for a normalization set, which is temporary. What matters are the names of the parameters and observables, and they are the same anyway
* new `CodeSquashContext::buildCall()` function to avoid code duplication
* add support for `RooExponential`, including unit test
Followup to #12529.
=> [RF] Minor improvements to RooFit evaluation code generation

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
It doesn't make sense to have the weight variable in the set of observables. This causes problems in various places, e.g.:
* this dummy `weightVar` is polluting the JSON file when exporting the workspace
* it is a nuisance for normalization because it will also appear in the normalization sets
This commit suggests to not add some dummy weight variable to the workspace.
=> [RF] Don't add `weightVar` to observables in HistFactory

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Adds a type-erased `RBitsetField` and a templated `RField<std::bitset<N>>`. Compilers implement bitsets as arrays of `unsigned long`. On disk, bitsets get stored as `Bit` column. Bit sets occur in the CMS EDM.
=> [ntuple] Add support for std::bitset<N>

graf2d/asimage/src/libAfterImage/asimage.h, graf2d/asimage/src/libAfterImage/asvisual.h
Fix several `warning C5033: 'register' is no longer a supported storage class` in asimage
=> Fix compilation warnings on Windows

.github/workflows/root-ci.yml
```
if: github.repository_owner == 'root_project' || github.event_name == 'pull_request'
^^^^^^^^^^^^: changed to 'root-project'
```
<details><summary></summary>
<p>
[skip-ci]
</p>
</details>
=> [CI] Fix macOS and Windows not building outside of pull requests

roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/src/RooRealVar.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This commit adds support for using RooNllVarNew in code-squashing/AD. It also adds a new test that uses code-squashing and AD based derivatives to minimize a simple model.
=> [RF] Add 'translate' to RooNllVarNew.

tree/ntuple/v7/doc/specifications.md
Add a few clarifications to the description of the `std::variant<T1, T2, ..., Tn>` type in the RNTuple Reference Specifications document.
Currently, the dispatch tag is `== 0` _iif_ the variant was in the invalid state when the entry was filled.  This condition is also expected to happen after the late model extension PRs are merged, given that late-added fields of type `std::variant<Ts...>` are in an invalid state for entries for which there is no data.
=> [ntuple][skip-ci] Update `std::variant` section in specifications.md

.github/workflows/root-ci-config/build_root.py
I know there's "add debug output" - but this is something we'll want to have available anyway, without having to re-run. I'm not dumping `env` because that can trigger the log grepper (not too concerned by tokens - GH is doing a good job at hiding those).
=> [ci] Show node and config state. [skip-ci]

.github/workflows/root-ci-config/build_root.py
Makes it easier to understand what's enabled etc when no `cmake` config happens.
=> [ci] Print CMake cache vars for incr build. [skip-ci]

.github/workflows/root-ci.yml
We only have release builds for incrementals, i.e. only release builds use artifacts, so there is no point in building debug artifacts.
=> [ci] For Windows, only build artifacts for Release: [skip-ci]

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3HistFactory.cxx, roofit/hs3/test/testHS3SimultaneousFit.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, tutorials/roofit/rf515_hfJSON.json
Put all the information necessary in the JSON to correctly reconstruct combined datasets and simultaneous pdfs.
Also, fix the export of `RooHistPdf` and `RooHistFunc` to not normalize the content of the template histograms, which can cause numerical precision problems.
=> [RF][HS3] Correct support for combined datasets and simultaneous pdfs

core/metacling/src/TCling.cxx, core/metacling/src/TClingClassInfo.cxx
When unloading a 'compiled' TClass, TClass sets the state of the TClass to the most information possible. This usually means setting the ClassInfo if the interpreter information is still known about the class. In the case of std::tuple is order to do that we need to generate code that depends on other types (that may also be unloaded), so skip that steps (which lead to 'compilation error' from the interpreter in the report cases (and a crash due to a couple of others issues solved also in this PR).
=> [v628] Resolve issue when dictionary with std::tuple is unloaded.

core/base/inc/TString.h
In the following code (from `TFormula.cxx`):
```
map< std::pair<TString,Int_t>, pair<TString,TString> > functions;
pair<TString, Int_t> key = make_pair(funName, dim);
if (functions.find(key) == functions.end()) {
```
`functions.find(key)` always returns `functions.end()`. Adding the spaceship operator `<=>` in TString fixes the issue. This fixes also many failing tests with `std:c++20`
=> [c++20] Add spaceship operator <=> in TString

cmake/modules/SearchInstalledSoftware.cmake
This should obviously be `CUDA_TOOLKIT_ROOT` with an L.
I don't know if this typo has any negative consequences, but it's maybe better to fix it before there are bugs creeping up because of that.
=> [cmake] Fix `CUDA_TOOKIT_ROOT` typo in SearchInstalledSoftware.cmake

README/ReleaseNotes/v630/index.md, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooGlobalFunc.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx, roofit/roofitcore/src/RooRealVar.cxx
Two changes: 
1. Removes the deprecated `RooFit::Format(const char* option, int)` command argument
2. Remove deprecated `RooAbsPdf::paramOn()` overload that take a formatting string directly
3. Make it possible to use parameter titles instead of variables in `RooAbsPdf::paramOn()`, closing the followng JIRA ticket:
https://sft.its.cern.ch/jira/browse/ROOT-6039
=> [RF] Improvements to `RooAbsPdf::paramOn()` formatting

roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/test/testRooFuncWrapper.cxx
Instead of guessing the number of parameters for the model represented by RooFuncWrapper, we now introduce a parameter size function that can be used to declare gradient output arrays of the right size. Possibly fixes some of the ASAN failures @hahnjo reported earlier.
=> [RF] Fix wrong size for gradient output array in testRooFuncWrapper.

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/Domains.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/JSONIO.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testHS3HistFactory.cxx, roofit/hs3/test/testHS3SimultaneousFit.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h, roofit/jsoninterface/src/RYMLParser.cxx, roofit/jsoninterface/src/RYMLParser.h
This PR achieves several things in the RooFit HS3 format:
* JSON -> WS -> JSON closure in the HistFactory test (the JSON is now invariant)
* Fix export of RooDataSets with only one entry
* Automatically export RooDataSets that represents binned datasets to the same format at binned datasets
* Also export special `Lumi` parameter from HistFactory
* Achieve exactly the same fit results with the same parameters when exporting HistFactory workspace to JSON and importing it back
=> [RF][HS3] Fix some closure issues between HistFactory and HistFactory HS3 implementation

roofit/roofitcore/inc/RooRealVar.h
In 13670912, the class version of the `RooAbsReal` class was incremented.
As explained in #8791, there are sometimes warnings in the IO of derived classes if their version number is not increased as well.
Increasing the class version of RooRealVar indeed fixes this warning that one gets right now when reading old workspaces:
```
Warning in <TStreamerInfo::CompareContent>: The following data member of
the on-file layout version 9 of class 'RooRealVar' differs from
the in-memory layout version 9:
RooAbsBinning _binning; //
vs
unique_ptr<RooAbsBinning,default_delete<RooAbsBinning> > _binning;
```
Thanks to @will-cern for catching this problem!
=> [RF] Increase version number of `RooRealVar` from 9 to 10

core/base/inc/TDirectory.h
Addresses an infelicity in the definition of the `gDirectory` macro.
The leading `ROOT` namespace qualification in the macro definition is prefixed with the global namespace (`::`).
This PR fixes #12623.
=> Fully qualify ROOT namespace

hist/histv7/inc/ROOT/RHistBufferedFill.hxx, roofit/roofitcore/inc/RooFit/TestStatistics/RooAbsL.h, roofit/roofitcore/inc/RooVectorDataStore.h, roofit/roofitcore/src/RooDataSet.cxx
I observed these building on macOS 13.2.1 and XCode 14.2.
- Construction of `std::span` from vector iterators directly fails to compile due to not finding a conversion. This can be worked around by passing in a pointer and a size.
- Warning about C++20 preferring symmetric equality operators (this is not a failure (yet)).
=> C++20 fixes: add missing include, fix span constructor, symmetric equality operator

interpreter/cling/lib/Interpreter/CMakeLists.txt, proof/proofd/inc/XProofProtocol.h
isysroot influences where clang will pick up libc++. Without this, and with
Xcode 14.3, cling will use libc++ from Xcode (or the command line tools) rather
than stdc++ from the macOS SDK, as clang would normally use. Passing the isysroot
(which point to the SDK) fixes this.
This solves build errors such as:
```
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:309:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:462:1: error: cannot template a using declaration
using _BoolConstant _LIBCPP_NODEBUG_TYPE = …
```
=> [cmake] Pass isysroot to clang when determining stdlib incpath:

roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONParser.cxx, roofit/roofitcore/inc/LinkDef.h
This is a follow-up to 82d17fb69c9a, fixing these warnings seen in the nightlies (Ubuntu 20.04):
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=ROOT-ubuntu2004-clang,SPEC=soversion,V=master/lastBuild/parsed_console/
```
/home/sftnight/build/night/LABEL/ROOT-ubuntu2004-clang/SPEC/soversion/V/master/build/roofit/roofitcore/G__RooFitCore.cxx:8047:11: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
if(onfile._vecEL) _vecEL = *onfile._vecEL; \
^
/home/sftnight/build/night/LABEL/ROOT-ubuntu2004-clang/SPEC/soversion/V/master/build/roofit/roofitcore/G__RooFitCore.cxx:8046:7: note: previous statement is here
if(onfile._vecE) _vecE = *onfile._vecE;    \
^ …
```
=> [RF] Fix RooFit warnings in the nightlies

core/cont/src/TRefArray.cxx, roofit/roofitcore/src/RooAbsArg.cxx
In `TRefArray::GetObjectUID(int &uid, TObjet *obj)`, there is a code
branch for the case of an empty TRefArray and an object with a UID
assigned. Is this case a new process ID corresponding to the object is
assigned to the `TRefArray`. However, the `uid` output parameter is not
correctly assigned in this code branch, which is fixed in this commit.
The consequence of this bug is that the, since the `uid` output
parameter is not correctly assigned, that the implementation of
`TRefArray::Add*()` does not correctly work then.
Closes https://github.com/root-project/root/issues/12329.
=> [core] Always assign correct `uid` output in TRefArray::GetObjectUID()

roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/RooWorkspace.cxx
Many users expect to use `Clone()` to copy RooWorkspaces, but so far this resulted in corrupt workspaces because the `Clone()` function was not overridden.
This is an important fix that needs to be backported at least to 6.28 and 6.26, better yet every ROOT release used in production.
=> [RF] Override `TObject::Clone()` in RooWorkspace

.github/workflows/root-ci.yml
Fixes wrong variable being used to specify branch for windows nightlies
```diff
--platform     windows10
--incremental  false
-                    --base_ref     ${{ github.base_ref }}
+                    --base_ref     ${{ github.ref_name }}
--repository   ${{ github.server_url }}/${{ github.repository }}
```
=> [CI] Fix nightlies on Windows

tree/ntuple/v7/test/ntuple_storage.cxx, tree/ntuple/v7/test/ntuple_storage_daos.cxx
This pull request fixes failing tests for ROOT builds configured with `-Dimt=OFF`.  Those tests incorrectly assumed that multi-threading support is just there after a call to `ROOT::EnableImplictMT()`.
=> [ntuple] Fix failing tests for `-Dimt=OFF` builds

roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/test/TestStatistics/testInterface.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx, roofit/roofitcore/test/TestStatistics/testPlot.cxx, roofit/roofitcore/test/testTestStatistics.cxx, roofit/roostats/inc/RooStats/BayesianCalculator.h, roofit/roostats/inc/RooStats/MaxLikelihoodEstimateTestStat.h, roofit/roostats/inc/RooStats/ProfileLikelihoodCalculator.h, roofit/roostats/inc/RooStats/ProfileLikelihoodTestStat.h, roofit/roostats/inc/RooStats/SimpleLikelihoodRatioTestStat.h, roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h, roofit/roostats/src/AsymptoticCalculator.cxx, roofit/roostats/src/BayesianCalculator.cxx, roofit/roostats/src/FeldmanCousins.cxx, roofit/roostats/src/FrequentistCalculator.cxx, roofit/roostats/src/MCMCCalculator.cxx, roofit/roostats/src/ProfileInspector.cxx, roofit/roostats/src/ProfileLikelihoodCalculator.cxx, roofit/roostats/src/ProfileLikelihoodTestStat.cxx, roofit/roostats/src/SimpleLikelihoodRatioTestStat.cxx, roofit/roostats/src/ToyMCImportanceSampler.cxx, roofit/xroofit/src/xRooNLLVar.cxx
Migrate `RooAbsPdf::createNLL()` to use the `RooFit::OwningPtr<T>`, and change all RooFit code such that it would still compile when defining the `OwningPtr` as `std::unique_ptr<T>`.
See https://github.com/root-project/root/pull/12614.
=> [RF] Migrate `RooAbsPdf::createNLL()` to use the `RooFit::OwningPtr<T>`

roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/inc/RooHelpers.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooHelpers.cxx, roofit/roofitcore/src/RooSimultaneous.cxx
Some time ago, I introduced the `RooHelpers::cloneTreeWithSameParameters()` function to eventually speed up cloning a RooAbsArg tree and then redirecting the parameters in a single pass.
This speeds up the likelihood creation in ATLAS Higgs combination fits for example, because the parameter redirection pass is quite expensive.
Things are now rewritten such that the parameters are not cloned to begin with, and therefore also don't need to be redirected to the original ones.
Since `RooHelpers::cloneTreeWithSameParameters()` and its implementation helpers are now generalizations of `RooAbsArg::cloneTree()` and `RooAbsCollection::snapshot()`, these methods are not implemented in terms of the RooHelpers.
=> [RF] Speed up implementation of `RooHelpers::cloneTreeWithSameParameters()` and friends

tree/ntuple/v7/src/RField.cxx
On Windows, the type `ROOT::Experimental::ClusterSize_t` is resolved to the underlying type `ROOT::Experimental::RClusterSize`. `ROOT::Experimental::ClusterSize_t` is already in its canonical form and `typedef` resolution should not be attempted.
TL;DR, if the type is resolved to `ROOT::Experimental::RClusterSize`, the logic in `RFieldBase::Create()` falls back to creating a `RClassField` instance, which is obviously not intended.
This fixes the `ntuple_packing` test on Windows.
=> [ntuple] Do not try to resolve `ROOT::Experimental::ClusterSize_t`

roofit/roofitcore/src/RooProdPdf.cxx
For some of the args created in the RooProdPdf cache, the ownership
model was wrong. They were attempted to be added to a list that is
actually not owning, but they should be added to the owning container of
the cache.
This fixes an issue with 6.28 reported on the forum:
https://root-forum.cern.ch/t/plot-normalization-after-rooaddpdf-fixaddcoefrange/54480
=> [RF] Fix error in RooProdPdf that comes from wrong `addOwned()`

roofit/roofitcore/inc/RooSimultaneous.h, roofit/roofitcore/src/RooSimultaneous.cxx
1. Fix proxy-server desync for nested RooSimultaneous
2. Remove obsolete `RooSimultaneous::plotOn()` override
3. Fix plotting of nested RooSimultanous when projection with data over index category
Closes #12652.
FYI, @elusian
=> [RF] Fixes for nested RooSimultaneous pdfs

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/ntuple_descriptor.cxx, tree/ntuple/v7/test/ntuple_schemaext.cxx, tree/ntuple/v7/test/ntuple_serialize.cxx
This pull request implements the foundations for late model extension, i.e. extending the ntuple model with new fields after the initial schema has been fixed.
Per this PR, we only allow extending the model before the first entry is filled.  This restriction will be removed in a follow-up PR.
**NOTE:** after the changes in this PR, all the currently existing ntuple files remain readable.
The user-facing API is based on a new class `RNTupleModel::RUpdater` that can be used as follows:
```c++
auto model = RNTupleModel::Create();
auto field1 = model->MakeField<float>("field1", 42.0);
auto ntuple = RNTupleWriter::Recreate(std::move(model), "myNTuple", "some/file.root");
auto modelUpdater = ntuple->CreateModelUpdater();
modelUpdater->BeginUpdate();
float field2 = 10.0; …
```
=> [ntuple] Implement foundations for late model extension (1/2)

interpreter/cling/include/cling/std.modulemap, interpreter/llvm/src/tools/clang/lib/Serialization/ASTWriterDecl.cpp
It is needed for C++11 support of #include <chrono>. Failures:
```
Processing /home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C...
In file included from input_line_10:1:
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/root/tutorials/multicore/mt201_parallelHistoFill.C:55:51: error: no member named 'duration' in namespace 'std::chrono'
std::this_thread::sleep_for(std::chrono::duration<double, std::nano>(500));
~~~~~~~~~~~~~^
```
and
```
root [11] #include <bits/chrono.h>
/home/sftnight/build/night/LABEL/ROOT-fedora36/SPEC/default/V/master/build/etc/cling/std.modulemap:432:10: error: module 'std.bits/chrono.h' requires feature 'cplusplus17'
module "bits/chrono.h" [optional] {
^
ROOT_prompt_11:1:10: …
```
=> [modulemap] bits/chrono.h exists already with C++11:

math/vecops/inc/ROOT/RVec.hxx
This is a low-level function to reset the buffer for which this RVec is acting as a view. Before this commit, the only way to reset the pointed-to address of a non-owning RVec was to construct a new RVec and swap it with the old one, which is much more expensive than the two assignments ResetView performs.
It is immediately useful for RDF bulk processing.
=> [VecOps] Add VecOps::ResetView

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/histfactory/src/ParamHistFunc.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/histfactory/test/testHistFactory.cxx, roofit/roofit/inc/RooPolynomial.h, roofit/roofit/inc/RooUniform.h, roofit/roofit/src/RooPolynomial.cxx, roofit/roofit/src/RooUniform.cxx, roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/inc/RooAbsDataStore.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooBinWidthFunction.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h, roofit/roofitcore/inc/RooFormula.h, roofit/roofitcore/inc/RooPolyVar.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooBinSamplingPdf.cxx, roofit/roofitcore/src/RooBinWidthFunction.cxx, roofit/roofitcore/src/RooFormula.cxx, roofit/roofitcore/src/RooGenericPdf.cxx, roofit/roofitcore/src/RooPolyVar.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitmore/inc/RooHypatia2.h, roofit/roofitmore/inc/RooLegendre.h, roofit/roofitmore/src/RooHypatia2.cxx, roofit/roofitmore/src/RooLegendre.cxx
The existing implementation in RooBatchCompute for polynomials was not
adequate, because it couldn't deal with coefficients that are different
for each event.
This PR is re-implementing the support for RooPolynomial, and also
re-uses the same code for the `RooPolyVar`, which is identical to the
`RooPolynomial` apart from the base class.
Also, this PR is removing the old `RooAbsReal::evaluateSpan()` family of functions that was used for the BatchMode before ROOT 6.26.
Furthermore, this PR also reduces the use of the `RunContext` class that was connected to the old BatchMode implementation.
=> [RF] Implement `RooPolynomial` plus `RooPolyVar` in BatchMode and remove some old code

tree/tree/inc/TTree.h, tree/tree/src/TTree.cxx, tree/tree/src/TTreeCache.cxx, tree/treeplayer/src/TTreePlayer.cxx
On an extreme example:
```
15,272,928 entries
152,739 baskets (and as many clusters)
10,000 Actual TTreeCache buffer size (minimum allowed)
8,442 estimated buffer size of TTreeCache (1.5 times compressed buffer size)
400 bytes per baskets
100 entries per baskets (i.e. per clusters)
25 number of cluster per TTreeCache buffer for single branch with default size.
1 float per entry (reading a single branch).
```
This repairs the performance of a simple `TTree::Draw` of a single branch
from 1 hour back down to 7s (performance seem in v6.12).
One additional improvement, increase the performance by 20% on that same example.
This fixes #12649.
=> Fix TTreeCache Scaling with the number of clusters/baskets.

hist/hist/src/TH1.cxx
SetTitle doc was miss-formatted.
=> [skip-ci] Fix wrong doxygen formating

roofit/roofitcore/src/RooPolyVar.cxx
There was a bad interaction between commit 8a67cf611c changing the signature of `compute()` to take a non-const reference, requiring an lvalue, and commit aa47d71aae introducing a new call to that same function with a temporary argument. Fix it in the same way as other call sites were changed in commit 8a67cf611c, by introducing a local variable.
=> [RF] Fix build due to changed compute() signature

core/multiproc/inc/TMPWorkerExecutor.h, math/mathmore/inc/Math/VavilovAccurate.h, math/minuit/inc/TMinuit.h, math/minuit/src/TMinuit.cxx, math/minuit2/inc/Minuit2/MnTiny.h, math/minuit2/src/MnTiny.cxx, roofit/roofit/inc/RooKeysPdf.h
* Fix unused variable warning in `TMPWorkerExecutor` by moving variable in the only code branch where it's actually used
* Fix some warnings about deprecated enum arithmetics by using `constexpr static int` instead of `enum`
* Fix warnings about the deprecation of `volatile` in C++ by not using it
With these changes, I can compile RooFit again without seeing warnings.
=> [RF][math][core] Fix some C++20 warnings

interpreter/cling/lib/Interpreter/IncrementalParser.cpp, interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/cling/test/Prompt/decls.C
Make `FilteringDiagConsumer` also ignore -Wunused-result. Whether or not such diagnostic is filtered depends on `CompilationOptions::IgnorePromptDiags`.
In particular, `IgnorePromptDiags` should _only_ be enabled for code parsed via `Interpreter::EvaluateInternal()`.  Thus, as of this commit `IgnorePromptDiags` defaults to 0 in `makeDefaultCompilationOpts()`
The observable effect of this change is ignoring `-Wunused-result` for wrapped code, e.g.
```c++
[[nodiscard]] int f() { return 0; }
// This yields `warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]`
void g() { f(); }
f(); // but this should not
```
Alternatively, as discussed with @Axel-Naumann, we could insert `#pragma clang diagnositc ...` directives in …
=> [cling] Ignore -Wunused-result in wrapped code

core/cont/inc/TClassTable.h, core/cont/src/TClassTable.cxx, tree/tree/src/TBranch.cxx
This fixes https://github.com/root-project/root/issues/12552
This commit add a mutex for the TClassTable inner operations.
Several changes were needed to insure that operation that can
either take the ROOT global lock or recursively call TClassTable
are executed outside of the TClassTable critical sections.
=> TClassTable: fix data race between dlopen and other uses

tree/ntuple/v7/src/RNTupleSerialize.cxx
Constructing a `std::span<T>` from a pair of `std::vector<T>::iterator` fails in Apple clang with libc++.  Revert to the pointer/pointer constructor, which should work in both GCC/clang and libstdc++/libc++.
See also: https://stackoverflow.com/questions/72935737/stdspan-on-apple-clang-cant-be-constructed.
This fixes the following error seen in the nighlies for cxx20 builds.
```
std::span<const DescriptorId_t> fieldList{onDiskFields.begin() + fieldListOffset, onDiskFields.end()};
^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/span:405:41: note: candidate constructor not viable: no known conversion from 'std::__wrap_iter<const unsigned long long *>' to 'std::span<const unsigned long long, …
```
=> [ntuple][cxx20] RNTupleSerialize: do not use iterators to construct `std::span`

tree/tree/src/TTreeCache.cxx
Address: https://github.com/root-project/root/pull/12650#issuecomment-1517450219
From @hahnjo:
Hi @pcanal, our AddressSanitizer build reports a heap-buffer-overflow: https://lcgapp-services.cern.ch/root-jenkins/job/root-asan/LABEL=ROOT-centos8,SPEC=asan,V=master/lastCompletedBuild/testReport/projectroot.roottest.root.tree/stl/roottest_root_tree_stl_make/
I bisected this to commit https://github.com/root-project/root/commit/2fa93de2a51e248a56418d8c6488b043746d0925; the error message says "0x60700022d458 is located 8 bytes to the left of 80-byte region". However, the stack trace points to the loop immediately after the added condition to perform the binary search. Could you take a look, please? What does TMath::BinarySearch return in case the element is not found?
Answer: yep it was missing …
=> Fix to https://github.com/root-project/root/pull/12650

roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooRealIntegral.cxx
In the RooRealIntegral constructor, there is a code section to figure out if the list of integration variables can be re-expressed in lvalues that are higher in the expression tree.
To check this, the clients of the integration variables are followed recursively. This doesn't work if *copies* of the integration variables are passes to the integral, because they have no clients. Therefore, when filling the initial list of leaf servers, they need to be filled with the instances of the integration variables that are in the actual computation graph of the function.
Closes #12646.
=> [RF] Sopport `RooRealIntegral` variable re-expression also for clones

roofit/roofit/src/RooGamma.cxx
This fixes the JIRA ticket ROOT-4188:
https://sft.its.cern.ch/jira/browse/ROOT-4188
The solution to the problem was already written in the linked JIRA ticket by @lmoneta.
This fix can be validated with this macro:
```c++
void repro()
{
RooRealVar x{"x", "", 0.0005, 0.001};
RooRealVar gamma{"gamma", "", 0.5};
RooRealVar beta{"beta", "", 2};
RooRealVar mu{"mu", "", 0};
RooGamma pdf{"pdf", "", x, gamma, beta, mu};
std::unique_ptr<RooDataSet> data{pdf.generate(x, 1000000)};
auto frame = x.frame(RooFit::Title("RooGamma(x, 0.5, 2, 0)"));
TCanvas c1;
data->plotOn(frame);
pdf.plotOn(frame);
frame->Draw();
c1.SaveAs("plot.png");
}
```
Result before this PR:
And with this PR:
=> [RF] Implement correct sampling for RooGamma with `gamma < 1`

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
There is an error here that was introduced in `dc65afe`:
https://github.com/root-project/root/blob/6abb8e90d9bea276269f375a67855c4065813343/roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx#L760-L762
This error should only be thrown when the number of observables is not 1, 2 or 3, but currently fires if the number is equal to 3.
See the change from `dc65afe` here where the mistake is evident:
https://github.com/root-project/root/commit/dc65afe00ec72d18ebc5d31e7b2d6b50c6a20423#diff-42ea09980f1ed2bacde4381f212c35d78be6ddedccf746953dc99d6455525d8aL1256-R1221
The conditional should be
`if (fObsNameVec.empty() || fObsNameVec.size() > 3)`
This needs to be backported to ROOT 6.26 and 6.28 to make it into the next patch releases.
Thanks to @CoffeeIntoScience for reporting this bug!
=> [RF] Fix off-by-one error in HistoToWorkspaceFactoryFast

roofit/histfactory/test/testHistFactory.cxx, roofit/roofit/inc/RooIntegralMorph.h, roofit/roofit/src/RooIntegralMorph.cxx, roofit/roofitcore/inc/RooAbsMCStudyModule.h, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooAbsStudy.h, roofit/roofitcore/inc/RooMCStudy.h, roofit/roofitcore/inc/RooUnitTest.h, roofit/roofitcore/src/RooAbsMCStudyModule.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAbsStudy.cxx, roofit/roofitcore/src/RooDLLSignificanceMCSModule.cxx, roofit/roofitcore/src/RooFactoryWSTool.cxx, roofit/roofitcore/src/RooGenFitStudy.cxx, roofit/roofitcore/src/RooMCStudy.cxx, roofit/roofitcore/src/RooUnitTest.cxx, roofit/roostats/src/BayesianCalculator.cxx, roofit/roostats/src/BernsteinCorrection.cxx, roofit/roostats/src/ToyMCStudy.cxx, test/fit/testFitPerf.cxx, test/fit/testRooFit.cxx, test/stressHistFactory_tests.cxx, test/stressRooFit_tests.h
In particular, this commit migrates `RooAbsPdf::fitTo()` and the functions to create cumulative density functions.
=> [RF] Migrate more RooFit functions to `RooFit::OwningPtr<T>`

core/multiproc/inc/TMPWorkerExecutor.h, math/mathmore/inc/Math/VavilovAccurate.h, math/minuit/inc/TMinuit.h, math/minuit/src/TMinuit.cxx, math/minuit2/inc/Minuit2/MnTiny.h, math/minuit2/src/MnTiny.cxx, roofit/batchcompute/src/Initialisation.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/roofit/inc/RooKeysPdf.h, roofit/roofit/src/RooGamma.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooRealIntegral.cxx
This is a backport of some RooFit PRs that were recently merged to master to v6-28-00-patches.
1. https://github.com/root-project/root/pull/12682
2. https://github.com/root-project/root/pull/12696
3. https://github.com/root-project/root/pull/12699
4. https://github.com/root-project/root/pull/12702
5. https://github.com/root-project/root/pull/12707
Related to https://github.com/root-project/root/issues/12319.
After merging this PR, the following RooFit commits in ROOT `master` (as of `d6cb771d7f`) are the ones that are not in `v6-28-00-patches` (as of `to fill out after merging`).
```txt
7c88a7414b [RF] Migrate more RooFit functions to `RooFit::OwningPtr<T>`
5d5e1bcce1 [RF] Fix build due to changed compute() signature
f69a346520 [RF] Update FitParabola test in `testNaNPacker` to also run …
```
=> [v628][RF] Backports of RooFit PRs to `v6-28-00-patches`: Part 17

roofit/batchcompute/src/Initialisation.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
This is a backport of all the relevant bugfix RooFit PRs that were recently merged to master to v6-26-00-patches (in the right order, to not have the commit history diverge too much).
1. https://github.com/root-project/root/pull/12696
2. https://github.com/root-project/root/pull/12707
Related to https://github.com/root-project/root/issues/11534.
=> [v626][RF] Backports of RooFit PRs to `v6-26-00-patches`: Part 28

cmake/modules/RootMacros.cmake
Backport of these three PRs to ROOT 6.24:
1. https://github.com/root-project/root/pull/11111
2. https://github.com/root-project/root/pull/11408
3. https://github.com/root-project/root/pull/11462
Like this, I can build the ROOT 6.24 branch in my Arch Linux environment again to debug some RooFit stuff.
=> [v624][cmake] Protect against empty COMPILE_DEFINITIONS in genreflex and rootcint commands

tree/tree/inc/TTree.h, tree/tree/src/TTree.cxx, tree/tree/src/TTreeCache.cxx, tree/treeplayer/src/TTreePlayer.cxx
See https://github.com/root-project/root/pull/12650
On an extreme example:
```
15,272,928 entries
152,739 baskets (and as many clusters)
10,000 Actual TTreeCache buffer size (minimum allowed)
8,442 estimated buffer size of TTreeCache (1.5 times compressed buffer size)
400 bytes per baskets
100 entries per baskets (i.e. per clusters)
25 number of cluster per TTreeCache buffer for single branch with default size.
1 float per entry (reading a single branch).
```
This repairs the performance of a simple TTree::Draw of a single branch
from 1 hour back down to 7s (performance seem in v6.12).
One additional improvement, increase the performance by 20% on that same example.
=> v628: Fix TTreeCache Scaling with the number of clusters/baskets.

interpreter/cling/lib/Interpreter/IncrementalParser.cpp, interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/cling/test/Prompt/decls.C
Make `FilteringDiagConsumer` also ignore -Wunused-result. Whether or not such diagnostic is filtered depends on `CompilationOptions::IgnorePromptDiags`.
In particular, `IgnorePromptDiags` should _only_ be enabled for code parsed via `Interpreter::EvaluateInternal()`.  Thus, as of this commit `IgnorePromptDiags` defaults to 0 in `makeDefaultCompilationOpts()`
The observable effect of this change is ignoring `-Wunused-result` for wrapped code, e.g.
```c++
[[nodiscard]] int f() { return 0; }
// This yields `warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]`
void g() { f(); }
f(); // but this should not
```
This PR is a backport of #12654.
=> [cling][v6-28] Ignore -Wunused-result in wrapped code

core/cont/inc/TClassTable.h, core/cont/src/TClassTable.cxx
This fixes https://github.com/root-project/root/issues/12552
This commit add a mutex for the TClassTable inner operations.
Several changes were needed to insure that operation that can
either take the ROOT global lock or recursively call TClassTable
are executed outside of the TClassTable critical sections.
=> v628: TClassTable: fix data race between dlopen and other uses

roofit/roofitcore/inc/RooUnitTest.h, roofit/roofitcore/src/RooUnitTest.cxx, roofit/roofitcore/test/TestStatistics/testPlot.cxx, test/stressRooFit.cxx, test/stressRooFit_tests.h
The same is done already in `stressRooStats`. Instead of manually propagating the BatchMode flag to all calls of `createNLL()` and `fitTo()`, it is easier and safer to just override the default, because then it can't be forgotten to add it in one of the calls.
In particular, this is done now because it will make it much easier the extend the possible `stressRooFit` options to also use the codegen plus AD backend.
=> [RF] Set BatchMode in `stressRooFit` via global configuration flag

roofit/roofitcore/inc/RooProjectedPdf.h, roofit/roofitcore/src/RooProjectedPdf.cxx
This is a suggestion for two improvements to the class:
1. The projected pdf should be extended if the pdf it is projecting is also extended.
2. The projection should respect the normalization range if one is given.
Submitting this PR to solicit feedback on these proposals
=> [RF] RooProjectedPdf support extended pdfs and normalization ranges

roofit/histfactory/src/ParamHistFunc.cxx
the assertion seems bogus - the param value is not the coordinate in the paramHistFunc, so just get rid of that assert
=> [RF] Update ParamHistFunc.cxx - remove bogus assertion

builtins/tbb/patches/gcc13.patch, cmake/modules/SearchInstalledSoftware.cmake
The new compiler complains that the declaration of `task_prefix::task()` changes meaning of `task`, as used in `task* next_offloaded`.
=> Patch builtin_tbb for GCC 13

roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/res/RooHeterogeneousMath.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/roofit/inc/RooGaussModel.h, roofit/roofit/src/RooGaussModel.cxx, roofit/roofitcore/inc/RooAbsAnaConvPdf.h, roofit/roofitcore/inc/RooAddModel.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooAddModel.cxx, roofit/roofitcore/src/RooMath.cxx
The output of the `rootbench/build/root/roofit/roofit/RooFitUnBinnedBenchmarks.cxx` benchmark is now (using 1M events):
```
--------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations
--------------------------------------------------------------------------------
BDecayWithMixing__BatchMode_CUDA             403 ms          129 ms            1
BDecayWithMixing__BatchMode_CPU             2086 ms         2084 ms            1
BDecayWithMixing__NumCPU_1                  8412 ms         8408 ms            1
BDecayWithMixing__NumCPU_2                  4739 ms         12.9 ms            1
BDecayWithMixing__NumCPU_4                  2974 ms         17.0 ms            1
BDecayWithMixing__NumCPU_8 …
```
=> [RF] Support Analytical convolution classes in the RooFit BatchMode CPU and GPU

interpreter/llvm/src/utils/TableGen/GlobalISel/GIMatchDag.cpp
Differential Revision: https://reviews.llvm.org/D119213
=> [v6-28] Qualify calls to llvm::format that have ::std:: types as parameters to avoid ambiguity in overload resolution when ADL finds `std::format`.

graf2d/cocoa/src/FontCache.mm
On macOS 13.3 with Xcode 14.3, vector construction begin begin/end iterators -to-dofferent-type (here, casting char to UniChar aka unsigned short) fails in optimized mode for seemingly dubious reasons (i.e. likely an optimizer bug). Short-circuit this by returning 0 early for an extent of 0 characters - which is the only case where this construction (i.e. end==begin) is known to fail.
=> [cocoa] Prevent cocoa FontCache::GetTextWidth() crash:

hist/hist/src/TGraph.cxx
Use `TAttAxis::Copy` method to ensure that all attributes are copied 
Axis and labels color were missing
Problem can be observed with `tutorials/hist/xyplot.C` macro.
If invoke `InsertPoint` method for TGraph via context menu, histogram axes will be drawn.
=> [graph] copy all attributes to new histogram

cmake/modules/RootBuildOptions.cmake
Compilers (at least clang) configure this internally; at least with the current efforts on compiler and CMake sides to put this into action our build system should keep away from interfering with this configuration.
Oh and it also does not work with macOS and builtin_glew.
=> [cmake] Deprecate cxxmodules:

math/unuran/test/unuranDistr.cxx
In that test, using `f->SetParameters(par)` gives a compiler warning, becaues internally, this does `std::copy(par, par + npars, ...)`. The `par + npars` gives an out-of-bounds warning, because par is a C-style array with compile-time size.
=> [math] Fix GCC 13 warning in `math/unuran/test/unuranDistr.cxx`

roofit/roofitcore/inc/RooAbsSelfCachedReal.h
Otherwise generation of `modules.idx` fails with "Failed to materialize symbols", naming this exact template specialization. An alternative would be outline this function to a source file and compile it into the library.
Fixes commit 9357c9842a ("[RF] Unify RooAbsSelfCachedPdf and RooAbsSelfCachedReal code").
=> [RF] Mark template specialization as inline

core/base/inc/TVirtualPad.h, core/base/src/TVirtualPad.cxx, graf2d/gpad/src/TPad.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist2d/TGraphPainter.mjs, tutorials/graphics/gtime.C
In some cases gPad can be set to tmpGuideLinePad, which is deleted
any time ShowGuidelines method is called. In that case pointer on
this temporary pad should be removed from TContext object
Also fix graphics/gtime.C tutorial and several bugs in JSROOT
=> Fix seldom crash in `TPad::ShowGuidelines`

math/mathcore/inc/Math/Random.h, tree/ntuple/v7/inc/ROOT/RDaos.hxx, tree/ntuple/v7/test/CustomStruct.hxx
Backport two PRs that fix compilation of 6.26 with gcc 13:
* https://github.com/root-project/root/pull/11958
* https://github.com/root-project/root/pull/12065
=> [v626] Backport some commits that add missing includes

interpreter/cling/lib/Interpreter/DefinitionShadower.cpp, interpreter/cling/test/CodeUnloading/DeclShadowing.C
This PR is a backport of #12781.
The change in this PR fixes a segfault when defining a C++20 concept if definition shadowing is enabled.
In principle, for a `TemplateDecl`, `isDefinition()` issues a recursive call passing the templated decl as a parameter.  A `ConceptDecl`, however, should always be considered a definition.
Also, update the DeclShadowing test incorporating a C++20 concept.
This PR fixes #12779.
=> [cling][v6-28] DefinitionShadower: fix crash with C++20 concepts

interpreter/cling/lib/Interpreter/DefinitionShadower.cpp, interpreter/cling/test/CodeUnloading/DeclShadowing.C
The change in this PR fixes a segfault when defining a C++20 concept if definition shadowing is enabled.
In principle, for a `TemplateDecl`, `isDefinition()` issues a recursive call passing the templated decl as a parameter.  A `ConceptDecl`, however, should always be considered a definition.
Also, update the DeclShadowing test incorporating a C++20 concept.
This PR fixes #12779.
=> [cling] DefinitionShadower: fix crash with C++20 concepts

graf2d/gpad/src/TPad.cxx
In some cases gPad can be set to tmpGuideLinePad, which is deleted any time ShowGuidelines method is called. In that case pointer on this temporary pad should be removed from TContext object
=> Fix seldom crash in `TPad::ShowGuidelines` [6.26]

gui/webdisplay/src/RWebDisplayHandle.cxx
With previous chrome it was possible to launch it as fork of main root process. With very recent chrome it is no longer possible. Therefore use exec instead.
Moreover, one need to add artificial `--dump-dom >/dev/null` to really let chrome wait for not-loaded `root_batch_holder.js` script while headless session is running.
Should fix problem with `macphsft26` and latest OpenSUSE
=> [webgui] change launch string for headless chrome

gui/gui/src/TRootCanvas.cxx
Add forgotten `Resize(w, h);` when the editor is displayed in a stand-alone canvas. This fix an issue reported on the Forum https://root-forum.cern.ch/t/minor-issue-with-new-root-6-28-04/54792
=> Resize the canvas when displaying the editor

gui/gui/src/TRootCanvas.cxx
Add forgotten `Resize(w, h);` when the editor is displayed in a stand-alone canvas. This fix an issue reported on the Forum https://root-forum.cern.ch/t/minor-issue-with-new-root-6-28-04/54792
=> [v6-28][skip-ci] Resize the canvas when displaying the editor

gui/webdisplay/src/RWebDisplayHandle.cxx
With previous chrome it was possible to launch it as fork of main root process. With very recent chrome it is no longer possible. Therefore use exec instead.
Moreover, one need to add artificial `--dump-dom >/dev/null` to really let chrome wait for not-loaded `root_batch_holder.js` script while headless session is running.
Should fix problem with `macphsft26` and latest OpenSUSE
=> [webgui] change launch string for headless chrome [6.28]

interpreter/cling/include/cling/std.modulemap
Since adding `bits/utility.h` in commit e9a8c48e4f, a C++14 build with GCC 12 (and potentially also other compiler versions) failed with
```
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:38:
/opt/gcc/12.2.0/include/c++/12.2.0/functional:337:35: error: missing '#include <bits/utility.h>'; 'tuple_size' must be declared before it is used
= typename enable_if<(__i < tuple_size<_Tuple>::value),
^
/opt/gcc/12.2.0/include/c++/12.2.0/bits/utility.h:49:12: note: declaration here is not visible
struct tuple_size;
^
```
Apparently, once the module is declared, it must also be enabled for C++14 and not restricted with `cplusplus17`.
=> [cxxmodules] Fix C++14 build with GCC 12

core/base/inc/TString.h
The feature test __cpp_lib_three_way_comparison is for library support of the three-way comparison. libc++ doesn't expose this yet, presumably because the operator has not been added yet for all classes. However, some classes already use it, which requires us to implement the operator as discussed in https://github.com/root-project/root/pull/12525.
(cherry picked from commit b85231d2ad62645f0fe7291a64284f61bb8a83c2)
=> TString: Enable spaceship operator with libc++ [v6.28]

graf2d/asimage/src/libAfterImage/import.c
Starting from libpng16 it is not allowed to set 0 as screen gamma. See comments:
https://chromium.googlesource.com/chromium/src/+/master/third_party/libpng/pngrtran.c#830
=> Always set positive screen gamma in libAfterImage

graf2d/asimage/inc/TASImagePlugin.h, graf2d/asimage/inc/TASPluginGS.h, graf2d/asimage/src/TASPluginGS.cxx
All derived classes should also redefine Hash and call recursive remove
=> Fix warning in asimage about redefinition of TObject::Hash()

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RColumnModel.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/test/ntuple_descriptor.cxx, tree/ntuple/v7/test/ntuple_extended.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_test.hxx
Add support for 64bit split and unsplit column types. It also makes them the default for index columns. When compressed, the difference to 32bit on-disk offsets is [almost none](https://docs.google.com/spreadsheets/d/1M7DR5obCOG0aTx_5zTLBjXJZb1uXWkHXPBcUpDIkSEc/edit?usp=sharing).
64bit on-disk index columns are the missing piece for supporting large events/clusters (>512MB). In memory, offsets are already 64bit, always. Validation of large events is for a follow-up PR.
Uncompressed, 64bit index columns may still hurt, so there is an option to use 32bit columns instead. In this case, the attempt to write large clusters will fail/throw.
=> [ntuple] Add support for (Split)Index64 column types

bindings/pyroot/pythonizations/python/ROOT/_facade.py
The deprecated overload returned None instead of an RDataFrame after printing the deprecation warning.
=> [DF] Fix MakeNumpyDataFrame

bindings/pyroot/pythonizations/python/ROOT/_facade.py
The deprecated overload returned None instead of an RDataFrame after printing the deprecation warning.
=> [DF] Fix MakeNumpyDataFrame in v6.28

roofit/roofitcore/inc/RooStringVar.h, roofit/roofitcore/src/RooStringVar.cxx, roofit/roofitcore/test/testRooDataSet.cxx
I discovered that RooDataSets that contain RooStringVar aren't cloneable, because the SetBranchAddress method of TTree expects the address of a string pointer, not the address of the string.
I added a test that would crash before I implemented the fix in RooStringVar.
Should be backported to 6.28
=> [RF] Make datasets that contain strings cloneable

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The fallback DefineImpl overload that was supposed to fire an helpful static_assert in this case was out of sync with the main overload, so it could not do its job.
=> [DF] Re-introduce diagnostics for Define expr returning void

net/http/src/THttpServer.cxx, tutorials/http/httpaccess.C, tutorials/http/httptextlog.C
With JSROOT v7 URL links to JSROOT sources are changed for THttpServer.
Now syntax is like:
```
import { redraw } from './jsrootsys/modules/main.mjs';
```
One need to handle also these links for custom JSROOT locations
=> [http] fix custom JSROOT usage with `THttpServer`

.github/workflows/root-ci.yml
Commit c8c0ea7c59 made the step and job fail in case of a test error. We still want the results to be uploaded to show them on GitHub.
=> [ci] Upload test results unless cancelled

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The fallback DefineImpl overload that was supposed to fire an helpful static_assert in this case was out of sync with the main overload, so it could not do its job.
=> [DF] Re-introduce diagnostics for Define expr returning void (v6.28)

bindings/pyroot/pythonizations/test/numbadeclare.py
The alias was deprecated with `numpy-1.20` and now expired in `numpy-1.24`:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations
This change also works with older versions (tested with `numpy-1.19`).
=> [PyROOT] Replace deprecated np.bool by plain bool

.github/workflows/root-ci-config/build_root.py
We want to upload any successful build, even if it fails testing (which makes the step and job fail since commit c8c0ea7c59).
=> [ci] Upload build artifacts before testing

interpreter/llvm/src/CMakeLists.txt, interpreter/llvm/src/include/llvm/Config/llvm-config.h.cmake, interpreter/llvm/src/include/llvm/Support/Compiler.h
This reverts commit 0363aed.
Use llvm-upstream commit instead!# This Pull request:
=> Revert "[llvm] Override llvm-visibility-default:"

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds a new `Create` factory method to the `RNTupleInspector` that takes the name and source path of the `RNTuple` to be inspected as its arguments. This removes the need for the user to open the relevant `TFile` and load the `RNTuple` manually, which can be useful in case one is only interested in inspecting an `RNTuple`.
Additionally, a check is added to the existing `Create(RNTuple *sourceNTuple)` method to make sure the pointer that was passed does not refer to null.
=> [ntuple] Add `RNTupleInspector::Create` for ntuple name and source path

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Adds a nullable field as a base class for unique pointer support. A follow-up PR will add `std::optional` support using the same base class. The nullable field is usually stored like a collection that can have zero or one element per entry. Optionally, nullable fields can be stored in "dense mode", with a bitmap mask and default-constructed values for the null entries.
=> [ntuple] Add support for unique pointers

tree/dataframe/test/datasource_ntuple.cxx, tree/ntuple/v7/test/ntuple_extended.cxx, tree/ntuple/v7/test/ntuple_rdf.cxx, tree/ntuple/v7/test/ntuple_schemaext.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/readspeed/test/readspeed_general.cxx
* Protect `EnableImplicitMT()` with `R__USE_IMT`.
* Expect error about non existent file in `readspeed` test.
Those should have been caught by the `TestSupport` library, but that one doesn't work at the moment (see https://github.com/root-project/root/issues/12828).
=> Solve warnings in tests

requirements.txt
Python 3.11 is supported by the latest Numba release https://numba.readthedocs.io/en/stable/release-notes.html#version-0-57-0-1-may-2023
=> Add numba compatible with Python 3.11 to requirements.txt

interpreter/cling/lib/Interpreter/IncrementalParser.cpp, interpreter/cling/test/CodeUnloading/Macros.C, interpreter/cling/test/CodeUnloading/Macros.h, interpreter/cling/test/DynamicLibraryManager/cached_realpath.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_order1.C
This pull request fixes a number of failures in cling tests.  See below for the specific tests that are fixed by this PR.
After this PR and https://github.com/root-project/root/pull/12853, the remaining tests that still fail are
```
1: Failed Tests (2):
1:   Cling :: CodeUnloading/AtExit.C
1:   Cling :: MultipleInterpreters/MultipleInterpreters.C
```
, which seem to have a common underlying cause: child interpreters are unable to resolve symbols defined in the parent.  @hahnjo, @vgvassilev, do you have time to take a look?
- SourceCall/ErrorMacro.C: the failure here is due to `diag::warn_falloff_nonvoid_function` not being promoted from warning to error.  This should always be done, regardless of the ignoring state in `FilteringDiagConsumer`.
The failure became visible after merging …
=> [cling] Fix a number of failures in cling tests

interpreter/cling/lib/Interpreter/IncrementalParser.cpp, interpreter/cling/test/CodeUnloading/Macros.C, interpreter/cling/test/CodeUnloading/Macros.h, interpreter/cling/test/DynamicLibraryManager/cached_realpath.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_order1.C
This pull request fixes a number of failures in cling tests.  See below for the specific tests that are fixed by this PR.
This is a backport of PR #12855.
- SourceCall/ErrorMacro.C: the failure here is due to `diag::warn_falloff_nonvoid_function` not being promoted from warning to error.  This should always be done, regardless of the ignoring state in `FilteringDiagConsumer`.
The failure became visible after merging https://github.com/root-project/root/pull/12654, given that `IgnorePromptDiags`
now defaults to 0 in `makeDefaultCompilationOptions()`.
- CodeUnloading/Macros.C: clang diagnostic verification was unhappy with the previous state of affairs. Move affected `expected-(warning|note)` markers to `Macros.h`.
- DynamicLibraryManager/callable_lib_L_AB_order1.C: `--enable-new-dtags` is …
=> [cling][v6-28] Fix a number of failures in cling tests

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx
In the `RPageStorage` destructor: wait for unterminated tasks, if any, as they may still hold a reference to `this`.
This is known to happen, e.g. in `RPageSinkBuf` if `CommitClusterImpl()` is not called after committing some pages via `CommitPageImpl()` and the `RPageSinkBuf` is immediately destructed.
This fixes the ntuple_extended:`RNTuple.SmallClusters` test.
=> [ntuple] Make sure that all tasks have finished in `~RPageStorage`

core/base/src/TObject.cxx, io/io/src/TStreamerInfoActions.cxx, io/io/src/TStreamerInfoReadBuffer.cxx
In v6-30 we no longer record the kIsOnHeap and kNotDeleted, however older version of ROOT do not yet set them properly when reading.  This leads to spurrious error message like:
```
Error in <TList::Clear>: A list is accessing an object (0x2d77b50) already deleted (list name = TList)
```
But also failure in some case where action is not taken because the object is incorrect thought to be already deleted.
=> Fix forward compatibility with v6-30

roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx
The testRooAbsL test compares two doubles and fails due to rounding errors.
The failure happens on ppc64le and aarch64.
This PR changes EXPECT_EQ to EXPECT_DOUBLE_EQ in the affected test.
~~~
[ RUN      ] SimBinnedConstrainedTest.SubEventSections
/builddir/build/BUILD/root-6.28.00/roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx:293: Failure
Expected equality of these values:
whole.Sum()
Which is: -1263.796050661927
N_events_total_parts.Sum()
Which is: -1263.7960506619268
/builddir/build/BUILD/root-6.28.00/roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx:303: Failure
Expected equality of these values:
whole.Sum()
Which is: -1263.796050661927
thrice_N_events_total_parts.Sum()
Which is: -1263.7960506619268
[  FAILED  ] SimBinnedConstrainedTest.SubEventSections (199 ms)
~~~
=> [RF] The testRooAbsL test compares two doubles and fails due to rounding errors

net/http/civetweb/civetweb.c, net/http/inc/THttpServer.h, net/http/src/TCivetweb.cxx, net/http/src/THttpServer.cxx
Allows to access files from `THttpServer` when it protected with `htdigest` password.
Addresses issue discussed here:
https://root-forum.cern.ch/t/localhost-jsroot-server/54607/60
Example of starting such server on localhost:8011:
```
THttpServer* serv = new THttpServer("http:8011?auth_file=auth.txt&auth_domain=root&cred_cors&cors=http://localhost:8000");
```
Here crucial exact CORS url and `cred_cors` option which enables `Access-Control-Allow-Credentials`  header.
Server `localhost:8000` is just plain JSROOT installation with python3.
To open ROOT file on such server:
```
http://localhost:8000/jsroot/?with_credentials&file=http://localhost:8011/currentdir/hsimple.root
```
=> [http] Let configure `Access-Control-Allow-Credentials` header

cmake/modules/RootBuildOptions.cmake
Otherwise variable `ROOT_qt5web_FOUND` will be set and depend project may try to build libraries which using it
=> [cmake] disable qt5web option when webgui is not enabled [6.28]

bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx, bindings/pyroot/cppyy/patches/gc_flags.patch
The `pyobj`'s `tp_flags` can have a number of other bits set, for example `Py_TPFLAGS_HEAPTYPE` and `Py_TPFLAGS_BASETYPE`. Only forward the two bits for `Py_TPFLAGS_HAVE_GC` and (since Python 3.11) `Py_TPFLAGS_MANAGED_DICT`. This fixes test failures seen with a Debug build on Fedora 38, but likely affecting all builds against Python 3.11.
=> [PyROOT] Only forward some tp_flags

README/ReleaseNotes/v630/index.md, roofit/roofitcore/inc/RooGenericPdf.h, roofit/roofitcore/src/RooFormula.cxx, roofit/roofitcore/src/RooFormula.h, roofit/roofitcore/src/RooFormulaVar.cxx, roofit/roofitcore/src/RooGenericPdf.cxx, roofit/roofitcore/test/testRooFormula.cxx
With PR https://github.com/root-project/root/pull/12800, the `RooFormula` was taken out of the public user
interface, because it is an implementation detail of the RooFormulaVar
and RooGenericPdf.
However, there are cases where people used the RooFormula interface to
access some information that was otherwise unavailable, like the set of
actual variables that the formula depends on.
There is some code in RooFormulaVar and RooGenericPdf that makes it seem
like these classes provide an interface to the actual variables
themselves:
```c++
const RooArgList& dependents() const { return _actualVars; }
...
RooListProxy _actualVars ;     ///< Actual parameters used by formula engine
```
However, `_actualVars` is containing **all** variables, not the actual
variables as the name suggests!
Fixing …
=> [RF] Only register actual vars as server in `RooFormulaVar`/`GenericPdf`

hist/histpainter/src/THistPainter.cxx
PaintInit and PaintInitH differed for the content axis definition.
This problem was mentionned here: https://github.com/root-project/root/issues/12567
=> Make PaintInitH and PaintInit similar

roofit/roofitcore/inc/RooFit/ModelConfig.h, roofit/roofitcore/src/RooWorkspace.cxx
Improves exception handling of RooWorkspace for non-existing objects
Adding a non-existing object to RooWorkspace prints an error message but doesn't terminate the program, which might lead to segmentation faults. The fix prints the error message and then throws a runtime error to handle such cases.
This PR fixes [JIRA: ROOT-7922](https://sft.its.cern.ch/jira/browse/ROOT-7922)
=> [RF] Add exceptions to set methods for non-existing objects

net/http/src/TCivetweb.cxx, tutorials/http/httpaccess.C
Add commented code to httpsccess.C macro which configures authentication.
And server can be used with external JSROOT
=> Add comments for CORS usage of THttpServert [skip-ci]

roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONInterface.cxx
In the RooFit `JSONInterface` there are some template specializations that are defined in the translation unit but are not declared in the header file.
This causes linker errors, because the compiler doesn't know that it has to look for the specializations, as explained here: https://stackoverflow.com/questions/11773960/do-template-specialisations-belong-into-the-header-or-source-file
To solve this problem, these small one-line functions are just inlined in the header.
Needs to be backported to 6.28.
=> [RF] Add missing declarations for JSONInterface template specializations

roofit/roofitcore/inc/RooFit/ModelConfig.h, roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/ModelConfig.cxx, roofit/roofitcore/src/RooWorkspace.cxx, roofit/roostats/inc/RooStats/AsymptoticCalculator.h, roofit/roostats/src/AsymptoticCalculator.cxx
* Add a new `ExternalConstraints()` field to the model config, to be directly passed to `createNLL`. This follows exactly the same pattern as the fields for `GlobalObservables()` and `ProjectedObservables()`.
* New `ModelConfig::createNLL()` and `fitTo()` functions, such that the user doesn't need to manually transfer the information from the ModelConfig to `RooAbsPdf::createNLL/fitTo()`
* Use the new `ModelConfig::createNLL()` in RooStats to give it a little bit of test coverage
FYI @cburgard
=> [RF] Add `ExternalConstraints`, createNLL() and fitTo() to ModelConfig

tree/treeplayer/src/TTreeGeneratorBase.cxx
This makes the test `roottest-root-treeproxy-make` pass on macOS 13, where a proxy pulling in `pair<int,int>` was trying to include the (private) header `__bit_reference`.
=> TTreeGeneratorBase::AddHeader: Move special case for pair before custom file

bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx, bindings/pyroot/cppyy/patches/gc_flags.patch, bindings/pyroot/pythonizations/test/numbadeclare.py, interpreter/llvm/src/tools/clang/lib/Serialization/ASTReaderDecl.cpp, roofit/roofitcore/src/RooCurve.cxx, roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx, tree/dataframe/test/datasource_ntuple.cxx, tree/ntuple/v7/test/ntuple_extended.cxx, tree/ntuple/v7/test/ntuple_rdf.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/readspeed/test/readspeed_general.cxx, tree/treeplayer/src/TTreeGeneratorBase.cxx
Backport of
* https://github.com/root-project/root/pull/12808
* https://github.com/root-project/root/pull/12827
* https://github.com/root-project/root/pull/12811
* https://github.com/root-project/root/pull/12829
* https://github.com/root-project/root/pull/12389
* https://github.com/root-project/root/pull/12857
* https://github.com/root-project/root/pull/12890
See also https://github.com/root-project/roottest/pull/970
=> Fixes for v6.28

core/base/inc/Rtypes.h, core/clingutils/src/TClingUtils.cxx, core/cont/inc/TClassTable.h, core/cont/src/TClassTable.cxx, core/meta/inc/TGenericClassInfo.h, core/meta/src/TGenericClassInfo.cxx, core/metacling/src/TCling.cxx
This problem appears "only" in newer OS/compiler (as seen in the original reports leading to #12715) the dependent library are now dlclose'd when the 'main' library is dlclose'd.  In the example a cmake generated library is linked against `libHist` and  `libHist` is then loaded and unloaded when the example's library is (intentionally) loaded and unloaded.  `libHist` happens to share a STL collection's dictionary (`std::vector<TString>`) with `libCore` (and this collection is used for the reading of rootpcm files and thus during the loading of the example's library). 
Details:
Unload only the TClass actually generated by the unloaded library.
The TGenericClassInfo's destructor now passes the TClass that they actually generated in
addition to the name so that only that TClass is destroyed. …
=> Fix dictionary issues when unloading/reloading the same libraries

.gitignore
ROOT's build directory (or any project's) should be included in .gitignore (it helps with a lot of tools as well as IDE/code editor file switchers).
Now, 2 years ago [I proposed to reserve "_build"](https://github.com/root-project/root/pull/8009) in .gitignore as a simple build directory name that we could use. That PR was closed in favor of [removing the "build" directory](https://github.com/root-project/root/issues/8031) from ROOT's sources and use that name instead.
Since then I have been naming my build directories something that the current .gitignore would ignore: `cmake-build-foo` or similar. I realize it might seem silly, but it would be a non-negligible quality of life improvement for me if I could just use `cmake-build` instead, hence this PR (while we wait for #8031).
=> [NFC] Tell git to ignore cmake-build* instead of cmake-build-*

interpreter/cling/include/cling/std.modulemap
This is needed also in v6-28-00-patches for building with GCC 13 since adding the `memory_resource` header in commit f7adbd2b04.
(cherry picked from commit e9a8c48e4f207d7015bbd212116486bbecbac066 and commit aae1cd064679f440ad80f39e4ee56bb0c1d9d396)
Backport of the following two PRs:
* https://github.com/root-project/root/pull/12765
* https://github.com/root-project/root/pull/12793
=> Fix std.modulemap for gcc13

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx
This pull request is a follow-up from PR #12824.  This cannot be in the base class destructor (`~RPageStorage`), given non-static members have been destroyed by the time the base class destructor is invoked.
Second try at fixing the ntuple_extended:`RNTuple.SmallClusters` test.
=> [ntuple] Move the `WaitForAllTasks()` call to `~RPageSinkBuf`

roofit/roofitcore/src/RooAbsReal.cxx
A one-line fix, but should be backported!
If the parameter was negative, it was slipping past this line and causing nan error to come back from the function!
=> [RF] RooAbsReal::getPropagatedError: fix for case of negative parameter with zero error

build/misc/argparse2help.py
Fix this error:
```
$ python3.12 build/misc/argparse2help.py
/home/blue/ROOT/master-py312/build/misc/argparse2help.py:57: SyntaxWarning: invalid escape sequence '\ '
options = "\ ".join(listOptions)
```
=> [skip-ci] fix an issue with python 3.12

tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx, tutorials/v7/ntuple/ntpl008_import.C
This PR removes the `RResult` wrapper from the public `RNTupleImporter` interface; private methods are still wrapped.
=> [ntuple] Remove `RResult` from public importer interface

roofit/roofitcore/src/BatchModeHelpers.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooFit/BatchModeHelpers.h, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooFitDriver.h
When creating a likelihood for the batch mode, there are two distinct steps:
1. Create the computation graph for the likelihood
2. Instantiate a RooFitDriver instance to evaluate the likelihood
The first step will the shared with the new RooFit Automatic Differentiation (AD) backend. To make this easy, the likelihood creation for the BatchMode is refactored such that both steps listed above don't happen in the same function anymore.
After this PR, it will only require small changes to make the codegen+AD backend available to `RooAbsPdf::createNLL()`.
=> [RF] Refactor BatchMode likelihood creation code

interpreter/cling/lib/Interpreter/DeclExtractor.cpp, interpreter/cling/lib/Interpreter/IncrementalExecutor.cpp, interpreter/cling/lib/Interpreter/IncrementalExecutor.h, interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.h, interpreter/cling/lib/Interpreter/Interpreter.cpp
This pull request fixes the remaining failing cling tests.  See below for the concrete changes.
@vgvassilev After the changes proposed in this PR, _all_ the cling tests are passing.
- Restore symbol lookup in child interpreters: prior to the upgrade to LLVM13, child interpreters used to also lookup symbols
in their parent.  This PR introduces a `DefinitionGenerator` that allows for symbol lookup across different `IncrementalJIT` instances, which restores the old behavior.
This change fixes the following tests: CodeUnloading/AtExit.C, MultipleInterpreters/MultipleInterpreters.C.
- `cling::DeclExtractor::EnforceInitOrder`: do not use `ActOnReturnStmt()`, given that the scope returned by `m_Sema->getCurScope()` might be == m_Sema->TUScope which obviously is not a function scope; use …
=> [cling] Fix remaining test failures

graf2d/win32gdk/inc/TGWin32.h
Fix 203 warnings like the following:
```
TGWin32.h(154,14): warning GEB472421: 'DrawText' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
```
=> [windows] Fix many warnings on Windows

tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/test/dataframe_simple.cxx
Following up on github issue #12870, fixing RDataFrame::Graph SetTitle to y-axis-variable vs. x-axis-variable (was the opposite before).
=> RDF:Graph() fix graph title to y-axis vs. x-axis

test/stressHistoFit.cxx
This causes a flood of "NON_XML_CHAR" etc output in Jenkins, cluttering the output and making the actual failure virtually invisible.
=> [test] HistoFit: remove color output:

core/base/inc/Rtypes.h, core/clingutils/src/TClingUtils.cxx, core/cont/inc/TClassTable.h, core/cont/src/TClassTable.cxx, core/meta/inc/TGenericClassInfo.h, core/meta/src/TGenericClassInfo.cxx, core/metacling/src/TCling.cxx
back port of https://github.com/root-project/root/pull/12863
This problem appears "only" in newer OS/compiler (as seen in the original reports leading to #12715) the dependent library are now dlclose'd when the 'main' library is dlclose'd.  In the example a cmake generated library is linked against `libHist` and  `libHist` is then loaded and unloaded when the example's library is (intentionally) loaded and unloaded.  `libHist` happens to share a STL collection's dictionary (`std::vector<TString>`) with `libCore` (and this collection is used for the reading of rootpcm files and thus during the loading of the example's library). 
Details:
Unload only the TClass actually generated by the unloaded library.
The TGenericClassInfo's destructor now passes the TClass that they actually generated …
=> v628 Fix dictionary issues when unloading/reloading the same libraries

cmake/modules/SetUpMacOS.cmake
Otherwise the externals are built in x86_64 mode and are not compatible with the rest of the libraries. The error message is then something like:
```
ld: warning: ignoring file lib/liblzma.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```
See also https://discourse.cmake.org/t/building-application-using-externalproject-add-on-m1-cpu/4931/7
=> Build: Prevent using of x86_64 Ninja on MacOS/arm64.

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ntuple_types.cxx
Enables support for doubles stored as float on disk (`Double32_t`). The field has `double` as its type with a `kReal32` column representation. The field's type alias is set to `Double32_t`. This PR only implements basic support, i.e. storing a `double` in memory as `float` on disk. Custom bit lengths and value ranges are for a future PR.
=> [ntuple] Add basic support for Double32_t

roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooFit/Detail/DataMap.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooFit/Detail/DataMap.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooFitDriver.h
The RooFitDriver mutates the RooAbsArgs it evaluates by setting a
specific index token to quickly look up cached information for a given
RooAbsArg.
Because of this, it's not possible to evaluate two computation graphs
that share RooAbsArgs with two separate RooFitDrivers.
However, this usecase needs to be supported, because in RooStats is
often happens that different likelihoods based on the same model are
instantiated.
The key to the solution in this commit is the insight that for each
likelihood, almost the full compute graph is cloned anyway, *except* for
the parameters. Therefore, the solution proposed in this commit is to
not set the data tokens for the parameters and not fill the data map
with their values. Instead, when querying their values, they are just
retrieved from the object …
=> [RF] Support multiple NLL with BatchMode existing at the same time

gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx, gui/webdisplay/src/RWebDisplayArgs.cxx
Backport from master
Let use newest qtweb tutorial also with 6.26 branch
=> [webgui] support qt6 version when create embedding qualifier [skip-ci]

roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsProxy.h, roofit/roofitcore/inc/RooArgProxy.h, roofit/roofitcore/inc/RooCollectionProxy.h, roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h, roofit/roofitcore/src/NormalizationHelpers.cxx, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAbsCachedPdf.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooArgProxy.cxx, roofit/roofitcore/src/RooConstraintSum.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/src/RooProjectedPdf.cxx, roofit/roofitcore/src/RooRealSumFunc.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx
If one wants to replace some servers of a RooAbsArg with
other servers, this is the the only option you have:
```c++
bool RooAbsArg::redirectServers(const RooAbsCollection& newSetOrig,
bool mustReplaceAll, bool nameChange,
bool isRecursionStep)
```
That's not so great, because if the new servers have different names,
thes old names must be set as the `"ORIGNAME:<myname>"` attribute for
the function to know which servers should be replaced.
These attributes are generally not reset, and this mutation of the
server attributes can cause trouble down the line.
Notably, this causes trouble in the BatchMode when compiling the
computation graph for a given normalization set. One single new server
might replace differently-named original servers. In that case, the new
servers get *two* "ORIGNAME:" …
=> [RF] New function for server changing without setting attributes

roofit/roostats/src/HypoTestResult.cxx
While I believe this class and others probably could do with a big rework, in my attempts so far to find ways to use them in their current form I have stumbled across some very annoying behaviours -- this PR fixes one of these: that the results wouldn't copy reliably at all.
=> [RF] Improve Copy Constructor of HypoTestResult

gui/browsable/src/RFieldProvider.hxx, tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/ntuple_project.cxx, tree/ntuple/v7/test/rfield_vector.cxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
Provides support for both 32bit and 64bit cardinality fields. This has no implication on the width of the on-disk offsets but the cardinality field width (32bit or 64bit) is for the width of the collection sizes that are computed from the offsets.
For converted TTree files with leaf count arrays, 32bit widths cardinality fields must be used because the count leaf is 32bit. This makes sure that the (projected) leaf count field in the RNTuple (e.g., `nJets`) can be accessed with the same type than the TTree branch, e.g. in RDataFrame.
=> [ntuple] Distinguish between 32bit and 64bit cardinality fields

bindings/jupyroot/python/JupyROOT/helpers/cppcompleter.py, bindings/jupyroot/python/JupyROOT/kernel/utils.py
* [windows][skip-ci] Fix the C++ notebooks on Windows
* [windows][skip-ci] Fix the C++ notebooks on Windows
Fix the following errors in `bindings/jupyroot/python/JupyROOT/kernel/utils.py`:
```
File "C:\Users\bellenot\build\x86\release\bin\JupyROOT\kernel\utils.py", line 70, in __init__
module = importlib.import_module(module_path)
File "c:\python39-32\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'JupyROOT.kernel.magics.magics\\cppmagic'
During …
```
=> [windows] Fix the C++ notebooks on Windows (#12912)

test/stressMathMore.cxx
The Steffenson algorithm make the interpreter crash without any info or stack trace in interpreted mode (but works well when compiled). So disable it for now on Windows, in interpreted mode only.
=> Disable the Steffenson algorithm in stressmathmore in interpreted mode on Windows

roofit/roofitcore/inc/RooCurve.h, roofit/roofitcore/inc/RooPlotable.h, roofit/roofitcore/src/RooCurve.cxx
This commit fixes the resetting of the y-axis limits at the end of `RooCurve::shiftCurveToZero()`. In particular, it now sets also the minimium limit correctly, which was not changed before even though it needs to be changed too.
Here is an example of a liklihood plot that looks good after this commit, but had wrong y-ranges before:
```c++
RooRealVar x("x", "", 100, 160);
RooRealVar sigmean("sigmean", "", 125, 100, 140);
RooGaussian signalModel("signal", "", x, sigmean, RooConst(2.0));
RooExponential background("background", "", x, RooConst(-0.03));
// double nbkgVal = 10;
// double nbkgVal = 200;
double nbkgVal = 5000;
RooRealVar nsig("nsig", "", 200, 0., 1000);
RooRealVar nbkg("nbkg", "", nbkgVal, 0., 10000);
RooAddPdf model("model", "", {signalModel, …
```
=> [RF] Correctly reset y-axis limits after `RooCurve::shiftCurveToZero()`

hist/histpainter/src/THistPainter.cxx
Stats were missing for some TH3 drawing options.
See here:
https://root-forum.cern.ch/t/statistical-box-does-not-appear-on-3d-histogram/55173/
=> Stats for some th3 painting options.

interpreter/cling/lib/MetaProcessor/MetaParser.cpp
On Ubuntu 22.04 , execute standalone cling binary. In cmd prompt execute .x meta command without giving a filename, cling crashes.
The proposed solution is to directly reject the .x command without giving clear diagnostics. This is not user friendly but this is currently how `MetaParser.cpp` handles all parsing/input error. At least it prevents crashing.
=> [cling] meta cmd .x should not crash if no file is given

roofit/histfactory/inc/LinkDef.h
This completes the list of LinkDef entries for the classes in `RooStats/HistFactory/Systematics.h`.
Closes #12967.
=> [RF][HF] Add missing LinkDefs for systematics classes in HistFactory

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py, bindings/pyroot/pythonizations/test/roofit/rooworkspace.py
Adds a feature in PyROOT to create new objects in RooWorkspace using a key-value pair, which has the object name as its key and an initialization string as its value.
For example, the following snippet creates a gaussian p.d.f. - 
```Python
import ROOT
ws = ROOT.RooWorkspace("ws")
ws["gauss"] = "Gaussian(x[0.0, 10.0], mu[5.0], sigma[2.0, 0.01, 10.0])"
````
=> [PyROOT] Feature to initialise RooWorkspace objects in PyRoot using strings

math/vecops/inc/ROOT/RVec.hxx, math/vecops/test/vecops_rvec.cxx
Adds a new overload for Take that allows a default value to fill the returned RVec if 
the absolute value of `n` is larger than the size of the vector. 
=> Adding new Take Overload and fixing Docs

cmake/modules/SearchInstalledSoftware.cmake
This should fix the error [reported on the forum](https://root-forum.cern.ch/t/windows-visual-studio-binary-root-v6-28-04-win64-vc17-exe-fitio-fails/55244)
=> [skip-ci][windows] Install also cfitsio.dll

roofit/roofitcore/inc/RooAddPdf.h, roofit/roofitcore/inc/RooRealIntegral.h, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooRealIntegral.cxx
This fixes remaining problems with the BatchMode that would have become apparent when using it for data projections in `RooAbsReal::plotOn()`.
=> [RF] Implement `compileForNormSet()` for RooRealIntegral and RooAddPdf

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
This fixes a bug in the creation of Snapshot actions. We were writing and then reading back booleans from uninitialized memory (just reserve'd). It happens to work, but of course it is incorrect.
=> [DF] Actually push back values, do not write to uninitialized memory

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
This fixes a bug in the creation of Snapshot actions. We were writing and then reading back booleans from uninitialized memory (just reserve'd). It happens to work, but of course it is incorrect.
=> [DF] Actually push back values, do not write to uninitialized memory (v6.28)

tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_modelext.cxx, tree/ntuple/v7/test/ntuple_types.cxx
This pull request adds the `EmptyBase` class to CustomStructLinkDef.h (required now by the `ntuple_modelext` test).  It also renames the class to `EmptyStruct`, which probably makes more sense now.
This should fix the `ntuple_modelext` on Windows, that was complaining due to
```
unknown file: error: C++ exception with description: "RField: no I/O support for type EmptyBase
At:
_cdecl ROOT::Experimental::RClassField::RClassField(class std::basic_string_view<char,struct std::char_traits<char> >, class std::basic_string_view<char,struct std::char_traits<char> >, class TClass *) [C:\ROOT-CI\src\tree\ntuple\v7\src\RField.cxx:1117]
" thrown in the test body.
```
=> [ntuple] Rename `struct EmptyBase` and add to CustomStructLinkDef.h

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
Some columns may have no pages in a given cluster (e.g. a field with type `std::string` that contains no data).  In such cases, it is still okay to use `CommitSealedPageV()`.  However, the previous implementation of `RColumnBuf::HasSealedPagesOnly()` prevented that.
This pull request fixes the issue and updates the unit tests accordingly.
=> [ntuple] Fix issue in `RPageSinkBuf::CommitClusterImpl()`

math/physics/src/TRolke.cxx
From Isabel Goos:
I am just writing because I found a mistake on your reference guide that should be corrected.
On this page: https://root.cern.ch/doc/master/classTRolke.html#a77ed9095b5fe47050eeec195eb3b669d
we see the example "SetPoissonBkgGaussEff(x,y,em,sde,tau)"
but later "void 	SetPoissonBkgGaussEff (Int_t x, Int_t y, Double_t em, Double_t tau, Double_t sde)".
So, in the example sde and tau are interchanged. 
We lost some nerves finding this out :) so, if we can avoid this for someone else, we are happy.
=> [skip-ci] doc fix.

cmake/modules/SearchInstalledSoftware.cmake
This should fix the error [reported on the forum](https://root-forum.cern.ch/t/windows-visual-studio-binary-root-v6-28-04-win64-vc17-exe-fitio-fails/55244)
=> [v6-28][skip-ci][windows] Install also cfitsio.dll

tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
This PR adds the importer option to convert dot characters in branch names to underscores, preventing the importer from raising an exception if such branch names are encountered (because dot characters are not allowed in field names).
=> [ntuple] Add importer option for converting dots in branch names

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml, CMakeLists.txt
The search for a candidate repository and branch for `roottest` now works as follows: 
- If the current head is a well-known branch, e.g. `master` or `v6-28-00-patches`, use the matching branch upstream as the forked repository may be out-of-sync.
- Otherwise, try a branch that matches the name of the current head in the forked repository, if it exists; else try using the closest upstream head/tag below `HEAD`'s parent commit.
- As a last resort, if there is no preferred candidate, checkout the remote's default head.
This patchset also adds some minor changes to the new CI in order to forward additional information about pull requests.
=> [cmake][ci] Improve selection of a candidate `roottest` branch to checkout

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx
In fact, `std::deque` does NOT guarantee that iterators remain valid:
> An insertion at either end of the deque invalidates all the iterators to the deque, but has no effect on the validity of references to elements of the deque
(https://eel.is/c++draft/deque.modifiers#1.sentence-2)
Instead use references to the elements, that remain valid.
=> [ntuple] Use references in RPageSinkBuf

net/monalisa/src/TMonaLisaWriter.cxx
Apparently the new Apple clang does not allow unscoped make_pair and runtime_error anymore.
=> Fix missing namespace

core/meta/src/TDataMember.cxx
This failure exists since ROOT 6: while CINT happily converted 1 to the world, cling refuses to convert it to e.g. const char*. Pass `0` which is "more compatible" with datatypes. This is still terrible design, but at least it is not making things worse, only better...
Before TNamed::SetName was looked up as a call `named.SetName(1)` which - with cling - means that no method is found. Now `named.SetName(0)` finds the right method.
=> [meta] Getter should take `0`, not `1`:

roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooAddPdf.h, roofit/roofitcore/inc/RooExtendPdf.h, roofit/roofitcore/inc/RooProdPdf.h, roofit/roofitcore/inc/RooRealSumPdf.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooExtendPdf.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/src/RooNormalizedPdf.h, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
Introduce the new `RooAbsPdf::createExpectedEvents()` method to
explicitly create an object that represents the expected number of
events. Like this, the expected number of events is fully exposed in the
computation graph, just like the integrals.
This makes adding support of RooFit codegen+AD for extended fits
trivial, and also optimizes the BatchMode because the RooFitDriver can
de-duplicate integrals that appear both in the regular evaluation path
and `RooAbsPdf::expectedEvents()`.
Now that a function that represents the expected events is
part of the computation graph, using it in the RooFit code generation
for the NLL is straight forward.
=> [RF] Support extended fits in RooFit code generation for AD

math/mathcore/inc/Math/Delaunay2D.h, math/mathcore/src/Delaunay2D.cxx, math/mathcore/test/CMakeLists.txt, math/mathcore/test/testDelaunay2D.cxx
Fix Delaunay 2D interpolation when the interpolated points are on at tringle's edges.
This is often the case when interpolating points laying in a grid, see https://root-forum.cern.ch/t/tgraph2d-interpolate-returns-0/54172 (linked also from the issue report). 
Before a crude hack was present, which could not work if the edge is horizontal.  
Clean up also the class code and improve comments
Add also a test for the interpolation on points on the edges
This PR fixes  #12535
=> [math] Fix Delaunay 2D interpolation

tree/ntuple/v7/test/ntuple_extended.cxx
Apparently, this test continues to be broken for some CI configs, which needs to be investigated carefully; thus disable temporarily.
Related PRs fixing issues found while investigating this test: #13021, #13022.
=> [ntuple] Temporarily disable the `RNTuple.SmallClusters` test

math/mathcore/src/Delaunay2D.cxx
Follows up on:
https://github.com/root-project/root/pull/12545
To fix the errors seen here, for example:
https://github.com/root-project/root/pull/12955#issuecomment-1592735649
=> [math] Add missing `<limits>` include to `Delaunay2D.cxx`

roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooFitDriver.cxx, roofit/roofitcore/src/RooFitDriver.h, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx
In the `getParameters()` implementation of the RooFitDriver wrapper,
there was a call to `RooAbsArg::getParameters()`, which is expensive.
It's better to let the Driver figure out what the parameters are, given
that it already stores all the information to figure this out very
quickly.
This speeds up the likelihood creation for ATLAS Higgs combination
models by about 20 % when using the BatchMode.
This commit also fixes some memory leaks in the `compileForNormSet()` implementations that were put there on purpose in lack of a better solution at the time, but now they are not needed anymore.
=> [RF] Speed up `getParameters()` for BatchMode NLL 

roofit/roofitcore/inc/RooExtendedTerm.h, roofit/roofitcore/src/RooExtendedTerm.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/test/testRooProdPdf.cxx
If one of the pdfs in a RooProdPdf is extended, it should not be
considered to be extracted as a constraint term. Also, fix
`RooProdPdf::getConnectedParameters()` which should not consider the
extended pdf as disconnected, as the expected events of this RooProdPdf
depend on it.
Closes this old Jira ticket:
https://sft.its.cern.ch/jira/browse/ROOT-7604
FYI, @will-cern, sorry that it took almost 10 years :)
=> RF] Don't consider extended pdf in RooProdPdf as constraint term

roofit/roofitcore/inc/RooBinWidthFunction.h, roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooBinWidthFunction.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooSimultaneous.cxx
Since ROOT 6.26, the HistFactory models include the RooBinWidthFunction
to multiply the yields in the RooHistFuncs with the inverse bin widths,
in order to get the correct probability density.
That's great and fixes HistFactory for non-uniform binnings, but it is
not optimal for the `BinnedLikelihood` code path. Here, the bin widths
need to multiplied back again to get the event yields in each bin.
This commit suggests to improve the situation for the new BatchMode by
propagating the information that we are building a binned likelihood
down to the RooBinWidthFunctions, such that they can remove themselves.
Then, if such RooBinWidthFunctions were encountered and disabled, the NLL
knows that it can skip the multiplication with the bin widths.
What is proposed here looks like a small …
=> [RF] Avoid RooBinWidthFunction in final likelihood computation graphs

tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx
RPageSinkBuf calls `ReservePage()` as part of a `CommitPageImpl()` call. This memory is release in `CommitClusterImpl()` by calling `ReleasePage()` accordingly.
However, if `CommitClusterImpl()` is never invoked (e.g., because the 'small cluster' check failed in RNTuple.cxx:336), this memory is leaked.
This patch fixes that by making `RColumnBuf` adopt the pages. `DrainBufferedPages()` gives back the ownership to the caller, who is then responsible of calling `ReleasePage()`.
FWIW, this bug was found while hunting the issues seen in the CI for the `RNTuple.SmallClusters` test.
=> [ntuple] Fix a memory leak in `RPageSinkBuf`

interpreter/cling/test/Driver/Inputs/.cling.d/startup0.C, interpreter/cling/test/Driver/Inputs/.cling.d/startup1.C, interpreter/cling/test/Driver/StartupFile.C, interpreter/cling/tools/driver/cling.cpp
Implement startup script support according to this post:
https://root-forum.cern.ch/t/cling-startup-scripts-support/51358
=> [cling] Startup script support

hist/hist/src/TPrincipal.cxx
When using option "x" for TPrincipal::MakeHistograms(), the histogram is made with the number of bins as calculated by:
`Int_t xbins = fNumberOfDataPoints/100;`
If the number of data points is less than 100, this will try to make a histogram with 0 bins. The code still functions, as TH1 itself compensates by setting the number of bins to 1, and issuing a warning. But clearly TPrincipal could be smarter to avoid the unnecessary / unhelpful warning.
The same happens for the calculation of `dbins` with the "d" option.
Sidenote: this was a non-urgent issue I raised 7 years ago, but if no one else has been complaining, it's clearly a low priority ;-)
https://sft.its.cern.ch/jira/browse/ROOT-8238
-Gene
=> PCA : Appropriately handle histogram bins for few data points

math/vecops/inc/ROOT/RVec.hxx
Adds two forward slashes for comment of output in example docs for Take
=> Adding comment forward-slashes in docs

roofit/roofitcore/src/RooAbsCollection.cxx
if the hashAssistedFind feature is active, the old code gave an invalid read because of the delete further up. This change ensures the deletion happens last
=> [RF] Update RooAbsCollection.cxx - fix invalid read bug in remove

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_extended.cxx
`AppendImpl()` returns the number of bytes written.  For collections, this accounts for the size of the written elements + one element in the index column.  However, `sizeof(RColumnElement<T>)` was erroneously taken as the size of the latter.
Instead, use the packed size of an element in the principal column.  Note that such size may be either 64 or 32 bit, depending on whether small clusters are used.  The `RNTuple.SmallClusters` test was adjusted accordingly.
As side effect, this PR should fix the RNTuple.SmallClusters test on Win32 (and thus supersedes #13004).
- Fix return value of `AppendImpl()` for collection fields.
- Adjust RNTuple.SmallClusters; also, set the target zipped cluster size and no compression, as otherwise the estimation of the zipped cluster size hits in.
=> [ntuple] Fix `RXxxField::AppendImpl()` return value

cmake/modules/RootBuildOptions.cmake
The options `minuit2_omp` and `minuit2_mpi` are dangerous because it means you can only minimize thread-safe functions with Minuit2. If you want Minuit2 with OpenMP or MPI support, it is better to build Minuit2 standalone.
Related to #12940.
=> [CMake] Add warning for the `minuit2_omp` or `minuit2_mpi` build options

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py, bindings/pyroot/pythonizations/test/numbadeclare.py
Fixes #11294 .
In particular:
- Properly parses const modifier in type of input argument
- Fixes wrong addition of extra ampersand when passing a reference
- Allows passing temporaries as arguments from RDataFrame
=> [PyROOT] Fixes for Numba.Declare

tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
The warning seems to be a false positive since the referenced object is a std::type_info, which should always have static lifetime.
This patch somehow silences it.
Possibly related gcc bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109671
=> [DF] Work around gcc 13 dangling reference warnings

math/mathmore/src/GSLRndmEngines.cxx, test/stressHistoFit.cxx, tutorials/tmva/keras/ClassificationKeras.py, tutorials/tmva/keras/RegressionKeras.py
This PR fixes: 
- stressHistoFit - so not use colour (even black) to keep a nice output log
- TMVA Keras tutorial: use different output file to avoid sporadic failures
- mathmore (GSL) : add a check for correct GSL version (2.3) introducing the new function `gsl_linalg_cholesky_decomp1`. Use the older `gsl_linalg_cholesky_decomp` for the old versions.
=> Apply some fixes in stressHistoFit, TMVA Keras tutorials and mathmore

core/metacling/src/TClingCallbacks.cxx
When instantiating templates, all Decls are present in the AST (with possibly deserialization pending). At that point, we should not load more modules which could find an implicit template instantiation that is lazily loaded.
Fixes #12003
=> [cxxmodules] Avoid loading more modules while instantiating templates

core/metacling/src/TClingCallbacks.cxx
When instantiating templates, all Decls are present in the AST (with possibly deserialization pending). At that point, we should not load more modules which could find an implicit template instantiation that is lazily loaded.
Fixes #12003
(cherry picked from commit ffdc579bbcd858e966db879c4258d0623eb520f1)
Backport of https://github.com/root-project/root/pull/13046
=> [cxxmodules] Avoid loading more modules while instantiating templates [v6.28]

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/improvement_report.yml, core/base/inc/TApplication.h, core/base/src/TApplication.cxx, etc/gdb-backtrace.sh
- Mentions/Suggests in the GH template how to paste the setup information when reporting a bug via the web browser
- Adds the ability to submit a bug report by opening web browser from the ROOT prompt, with command `.gh`
- Adds the ability to auto-populate a GitHub bug report with your current system setup.
- Similarly for reporting a crash or bug in the forum
- [FOR LATER BY AXEL] Add backtrace also in form, if any
- [NOT NEEDED] Strip or Obfuscate paths of backtrace that are outside of ROOT folder, or within GetHomeDirectory. Potentially also in GetBinaryDirectory within GetSetup function
This PR fixes https://github.com/root-project/root/issues/8795
The way to submit a bug report without opening ROOT by hand would be:
```
root -b -e '.gh bug' -q
root -b -e '.gh feature' -q
root -b -e …
```
=> [GH] Allow starting Bug Report from ROOT prompt with prepopulated setup field

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/improvement_report.yml
Fixes a couple of syntax issues introduced in the last PR, which prevents from correctly opening new Issues on GitHub
=> Fix YML syntax in github templates

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/improvement_report.yml
- multiple fields have been unified, reducing the level of noise in the templates
- commands to retrieve ROOT version have been made copiable
- text style/tone has been made more uniform
Personally I find the current tone of the templates slightly condescending and the process of filling them less streamlined than it could be. I fully understand that some of the style decisions are completely subjective but even if only some of the suggestions are accepted I think it is worth it. Just wanted to bring this up :smile:
=> Improvement suggestions for GitHub templates

build/misc/argparse2help.py, main/src/hadd-argparse.py
Related to #11245 . The `-O` option of hadd can be used to force the recompression of the whole target tree (including branches and baskets) to the compression algorithm set with `-f` option. This is not clear in the current `hadd` help message.
The first commit updates the help for the `-O` option, most probably this can be further improved so suggestions are welcome!
Other commits are style changes to the message for a clearer output and code.
After this PR:
```
$: hadd -h
usage: hadd [-a A] [-k K] [-T T] [-O O] [-v V] [-j J] [-dbg DBG] [-d D] [-n N]
[-cachesize CACHESIZE]
[-experimental-io-features EXPERIMENTAL_IO_FEATURES] [-f F]
[-fk FK] [-ff FF] [-f0 F0] [-f6 F6]
TARGET SOURCES
OPTIONS:
-a                                   Append to the output
-k …
```
=> Update hadd docs

core/metacling/src/CMakeLists.txt
Export the following missing symbols:
```
void * __ptr64 __cdecl operator new(unsigned __int64,struct std::nothrow_t const & __ptr64)
void * __ptr64 __cdecl operator new[](unsigned __int64,struct std::nothrow_t const & __ptr64)
```
and
```
void * __cdecl operator new[](unsigned int,struct std::nothrow_t const &)
void * __cdecl operator new(unsigned int,struct std::nothrow_t const &)
```
=> [windows] Add a couple of missing symbols in the export list

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/test/ntuple_descriptor.cxx
This PR adds the `RNTupleDescriptor::GetColumnIterable()` method, which returns an iterator over all (logical) columns of the RNTuple (without having to specify a field).
Some questions to still consider:
1. The original `RNTupleDescriptor::GetColumnIterable(const RFieldDescriptor &field)` method returns an iterator over the _logical_ columns. Would it make more sense to return physical columns for this method or should we stay consistent across methods? For the `RNTupleInspector`, we're interested in physical columns but if we have the logical columns we could filter out the non-physical ones.
2. The original method only returns the columns for the specified field, without considering its potential sub-fields. Would it be useful to add a flag to toggle whether the columns for sub-fields …
=> [ntuple] Add iteration over all available columns

geom/geombuilder/src/TGeoBBoxEditor.cxx, geom/geombuilder/src/TGeoManagerEditor.cxx, geom/geombuilder/src/TGeoMaterialEditor.cxx, geom/geombuilder/src/TGeoMatrixEditor.cxx, geom/geombuilder/src/TGeoMediumEditor.cxx, geom/geombuilder/src/TGeoSphereEditor.cxx, geom/geombuilder/src/TGeoTabManager.cxx, geom/geombuilder/src/TGeoTrd1Editor.cxx, geom/geombuilder/src/TGeoTrd2Editor.cxx, graf3d/eve/src/TEveProjectionAxesEditor.cxx, graf3d/eve/src/TEveTrackEditor.cxx, graf3d/eve/src/TEveTrackPropagatorEditor.cxx, gui/ged/src/TH1Editor.cxx, gui/ged/src/TH2Editor.cxx
Use the proper `kFitWidth` value (from the frame enum) in several TGCompositeFrame constructors instead of the `kLHintsExpandX` value (from the layout hints enum)
=> Fix TGCompositeFrame constructor flags

.github/workflows/root-ci.yml
This also has the advantage that they don't try to upload test results that the nodes happen to find in the filesystem.
=> [ci] Exclude Debug configurations on Windows from the matrix [skip-ci]

roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h, roofit/jsoninterface/src/JSONInterface.cxx, roofit/roofitcore/inc/RooAddition.h, roofit/roofitcore/inc/RooFit/Config.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAddition.cxx, roofit/roostats/src/HypoTestInverterResult.cxx
importing workspaces from JSON now successfully fills the NPs and Globs lists in ModelConfigs
The solution for now is a bit makeshift, as it relies on the const/non-const properties to be set correctly at the time of creation.
However, it's better than not doing anything, as this now allows the ```ModelConfig::createNLL``` to do its job correctly on imported workspaces.
=> [HS3][RF] importing workspaces from JSON now successfully fills the NPs and Globs lists in ModelConfigs

roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/src/RooFitResult.cxx
in some user cases there are things in the constPar list that aren't a RooRealVar, so make this printout more flexible by using the printValue method.
=> [RF] Update RooFitResult.cxx - use printValue for constPars 

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/draw/TLinePainter.mjs, js/modules/draw/more.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TPavePainter.mjs
Via special command from client move object in list of primitives to the
end. Reflect changes which are done with "Bring to front" menu command
on client side. Supported for objects like `TLine`, `TBox`, `TMarker`, `TPave` and few
others
It is more safer version of `TObject::Pop()` method - do not relies on `gPad`.
=> [webcanv] support "Bring to front" command for different classes

core/base/src/TApplication.cxx
Use the correct syntax for the `START` command, which is:
```
START "title" [/D path] [options] "command" [parameters]
```
This prevent the following error with the `.forum bug` command:
```
root [0] .forum bug
The system cannot accept the START command parameter  "https://root-forum.cern.ch/new-topic?category=ROOT&tags=bug&body=___%0A_Please read [tips for efficient and successful posting](https:%2F%2Froot-forum.cern.ch%2Ft%2Ftips-for-efficient-and-successful-posting%2F28292) and [posting code](https:%2F%2Froot-forum.cern.ch%2Ft%2Fposting-code-read-this-first%2F28293)_%0A%0A%23%23%23 Describe the bug%0A%0A%23%23%23 Expected behavior%0A%0A%0A%23%23%23 To Reproduce%0A%0A%0A%23%23%23 Setup%0A%60%60%60%0AROOT v6.29%2F01%0ABuilt for win32 on Jun 26 2023, 07:55:07%0AFrom …
```
=> [skip-ci][windows] Use the correct syntax for the `START` command

gui/browserv7/src/RBrowserTCanvasWidget.cxx
In special engines like qt5web or cefweb synchronous update of the canvas may block normal event loop of such engines.
=> [rbrowser] use TWebCanvas in async mode

gui/browserv7/src/RBrowserTCanvasWidget.cxx
In special engines like qt5web or cefweb synchronous update of the canvas may block normal event loop of such engines.
=> [rbrowser] use TWebCanvas in async mode [6.28]

gui/canvaspainter/src/RCanvasPainter.cxx, gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayHandle.cxx, tutorials/rcanvas/df104.py, tutorials/rcanvas/df105.py, tutorials/rcanvas/rline.cxx
Used in `RCanvas::SaveAs()` method to avoid failure message when image production in 
tutorials macros is not possible.
Should fix newly introduced errors in Jenkins
=> [webgui] provide method which checks if image can be produced with web browsers

gui/webgui6/src/TWebCanvas.cxx
When gPad->Modified() called without real change in the content, produced TWebCnavas JSON will be equivalent with previous one. Therefore one can assume that newer version already was send to the client and do not need to be updated again
=> [webcanvas] fix update optimization

gui/webgui6/src/TWebCanvas.cxx
When gPad->Modified() called without real change in the content, produced TWebCnavas JSON will be equivalent with previous one. Therefore one can assume that newer version already was send to the client and do not need to be updated again
=> [webcanvas] fix update optimization [6.28]

tree/treeplayer/src/TFormLeafInfo.cxx, tree/treeplayer/src/TTreeFormula.cxx
Warning like this:
```
tree/treeplayer/src/TFormLeafInfo.cxx: In member function ‘virtual Bool_t TFormLeafInfo::IsString() const’:
tree/treeplayer/src/TFormLeafInfo.cxx:361:36: warning: arithmetic between different enumeration types ‘TStreamerInfo::EReadWrite’ and ‘EDataType’ is deprecated [-Wdeprecated-enum-enum-conversion]
361 |       case TStreamerInfo::kOffsetL + kChar_t:
|            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
tree/treeplayer/src/TFormLeafInfo.cxx: In member function ‘T TFormLeafInfo::ReadValueImpl(char*, Int_t)’:
tree/treeplayer/src/TFormLeafInfo.cxx:890:36: warning: arithmetic between different enumeration types ‘TStreamerInfo::EReadWrite’ and ‘EDataType’ is deprecated [-Wdeprecated-enum-enum-conversion]
890 |       case TStreamerInfo::kOffsetL + kULong64_t:
| …
```
=> [treeplayer] fix compiler warnings concerning enum combination

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py, bindings/pyroot/pythonizations/test/CMakeLists.txt, bindings/pyroot/pythonizations/test/roofit/rooworkspace.py, roofit/hs3/CMakeLists.txt, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONIOUtils.cxx, roofit/hs3/src/JSONIOUtils.h, roofit/hs3/src/RooJSONFactoryWSTool.cxx
Adds a feature in PyROOT to initialize objects in RooWorkspace using dictionaries.
For example - 
```python
import ROOT
ws = ROOT.RooWorkspace("ws")
ws["m1"] = dict({ "max": 5, "min": -5, "value": 0 })
ws["m2"] = dict({ "max": 5, "min": -5, "value": 1 })
ws["mean"] = dict({ "type":"sum", "summands":["m1", "m1"] })
```
=> [PyROOT][RF] Feature to initialise RooWorkspace objects in PyRoot using dictionaries

roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h, roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
The `FlexibleInterpVar` and the `PiecewiseInterpolation` classes in
HistFactory can both interpolate asymmetric up-and-down variations
between the +/- one standard deviation such that both the first and
second derivatives of the scale factors are smooth.
The `PiecewiseInterpolation` class is more general, because instead of
taking constant interpolation parameters, it takes other `RooAbsReals`.
That means it makes no sense for that class to cache the polynomial
coefficients that have to re recomputed anyway each time the input
changes. It uses an optimized formula to do the interpolation on the
fly.
The `FlexibleInterpVar` however precomputes and caches the polynomial
coefficients. This has serveral disadvantages:
* High cost in memory (the big ATLAS models can have thousands of …
=> [RF][HF] Consistent 6th-degree polynomial interpolation in HistFactory

tree/dataframe/src/RDataFrame.cxx
=> [NFC][DF] Fix link in RDF docs, wording

cmake/modules/SetUpFreeBSD.cmake, config/root-config.in, core/base/inc/TVirtualMutex.h, core/base/inc/TVirtualRWMutex.h, core/base/src/TDatime.cxx, core/base/src/TSystem.cxx, core/base/src/TTimeStamp.cxx, core/cont/inc/TCollection.h, core/meta/inc/TInterpreter.h, core/thread/src/TThread.cxx, graf2d/x11/src/GX11Gui.cxx, interpreter/cling/lib/Interpreter/CIFactory.cpp, net/net/src/TS3HTTPRequest.cxx, net/rpdutils/src/error.cxx, rootx/src/rootx.cxx
According to `feature_test_macros`, this macro is obsolete and "glibc has been thread-safe by default for many years." Other platforms don't use it at all, for example FreeBSD.
Some parts of ROOT used it to determine if we are compiling with `-pthread`, but this is essentially unused these days because the CMake build always enables threading support and there exists no option to turn it off.
=> Remove checks for deprecated _REENTRANT macro

bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
It causes dask to print a warning since they are
typically C++ headers, not Python modules.
The `load=False` parameter only has an effect since dask.distributed v2023.06 and it will be ignored
by previous versions.
=> [DF] Do not try to import distributed headers

tmva/tmva/src/Classification.cxx
It is:
```
tmva/tmva/src/Classification.cxx: In lambda function:
tmva/tmva/src/Classification.cxx:265:23: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
265 |       auto executor = [=](UInt_t workerID) ->ClassificationResult {
|                       ^
tmva/tmva/src/Classification.cxx:265:23: note: add explicit ‘this’ or ‘*this’ capture
```
=> [tmva] fix capture warning from c++20

interpreter/cling/lib/Interpreter/CMakeLists.txt, interpreter/cling/tools/libcling/CMakeLists.txt
When cling is compiled standalone without the help of the Cling Packaging Tool, errors about missing ```llvm::jitlink``` symbols may occur. For example, I could not build cling against [an external instance of LLVM + clang](https://github.com/root-project/llvm-project/tree/cling-llvm13) compiled with ```BUILD_SHARED_LIBS=ON```.
This PR fixes it by updating 2 offensive CMakeLists.txt's.
(Contributing to the ROOT repository rather than the cling one by request of @Axel-Naumann)
=> Add jitlink to LLVM_LINK_COMPONENTS in relevant cling parts

tree/ntuple/v7/test/CustomStructLinkDef.h
This fixes the test `gtest-tree-ntuple-v7-test-ntuple-types` when building with `runtime_cxxmodules=OFF`, see #13058.
=> [ntuple] Add LowPrecisionFloats to LinkDef.h

graf3d/eve7/CMakeLists.txt, graf3d/eve7/src/REveManager.cxx, gui/browserv7/inc/ROOT/RFileDialog.hxx, gui/browserv7/src/RBrowser.cxx, gui/browserv7/src/RFileDialog.cxx, gui/canvaspainter/src/RCanvasPainter.cxx, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebWindow.cxx, gui/webgui6/src/TWebCanvas.cxx
One have to provide connection id when accepting file dialog request from client.
This allows to use file dialogs for window with multiple connections at the same time.
In eve7 use `RWebWindow` methods to avoid direct dependency from `RBrowser`
`RFileDialog` also used in `RBrowser`, `RCanvas`, `TWebCanvas`
=> Support multiple connections in `RFileDialog`

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/src/RInterface.cxx
I took the chance to also move the function to a better header, since we discussed that `InterfaceUtils` is for stuff which `RInterface` depends from and not the other way around.
=> [DF] Move TriggerRun to more appropriate header and fix signature

documentation/doxygen/ROOT.css
Before vs after this change:
Related forum post:  https://root-forum.cern.ch/t/root-reference-webpage-theme-option/55524
=> [doc] Fix PyROOT boxes background color in dark mode

cmake/modules/RootConfiguration.cmake, config/rootrc.in, core/base/src/TROOT.cxx, gui/gui/inc/TRootGuiFactory.h, gui/gui/src/TRootGuiFactory.cxx
1. Create TWebCanvas from TRootGuiFactory if nothing else is configured
2. Add warning message when web-based canvas started by default
3. Add `Canvas.Name` parameter to rootrc to be able change default behaviour back
4. Set `Canvas.Name` during configure depending if `webgui` compiled or not
Should behaves similar as with `TBrowser`.
If no extra command-line arguments are specified, web canvas will be started and warning message will appear.
Via `.rootrc ` file or with `--web=off` web canvas can be disabled.
In batch mode one have to use `root --web -b tutorials/hsimple.C` to use web-based image generation.
=> Use TWebCanvas by default in interactive sessions

bindings/pyroot/pythonizations/test/roofit/rooworkspace.py, roofit/histfactory/test/testHistFactory.cxx, roofit/hs3/inc/RooFitHS3/JSONIO.h, roofit/hs3/src/JSONIO.cxx, roofit/hs3/test/testHS3SimultaneousFit.cxx, roofit/hs3/test/testRooFitHS3.cxx
Loads factory expressions  and export keys in RooFit automatically to avoid unnecessary imports
It's not required to call `loadExportKeys` and `loadFactoryExpressions` every time to load default JSON I/O keys.
=> [RF] Automatic JSON I/O key management

bindings/experimental/distrdf/python/DistRDF/__init__.py, tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/inc/ROOT/RResultHandle.hxx, tree/dataframe/src/RDFHelpers.cxx
This is mostly useful to assert that things worked as expected whenever RunGraphs is invoked.
=> [DF] Return the number of graphs actually processed from RunGraphs

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/draw/draw3d.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/tree.mjs
1. When function value cannot be calculated by the client, TWebCanvas will call `TF1::Save` method to store actual values on C++ side.
2. Fix several issues showing such stored values on the client - including handling infinite values.
3. Improve `TF1`/`TF2` tooltips handling.
4. Fix zooming on 3D plots - was affected by new pad moving functionality
5. Update `TWebCanvas` docu - mention some 'rootrc' parameters
=> [webcanvas] Let use saved values from `TF1`/`TF2`

tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx, tree/dataframe/test/dataframe_vary.cxx
RVariedAction needs to register one callback for each varied result, not just one of the callbacks.
=> [DF] Fix RVariedAction::GetSampleCallback 

tree/dataframe/src/RDataFrame.cxx
I don't know why doxygen does not put those titles in bold, but it doesn't:
=> [skip-ci][NFC][DF] Fix doxygen formatting

tree/tree/src/TChain.cxx
=> [tree] Actually set TTree's fChainOffset data member

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/inc/TWebSnapshot.h, gui/webgui6/src/TWebCanvas.cxx, gui/webgui6/src/TWebSnapshot.cxx, js/build/jsroot.js, js/modules/core.mjs, js/modules/hist2d/TScatterPainter.mjs
Update JSROOT with `TScatter`
Also add batch mode flag when creating JSON
Data may differ when JSON created for image production or for
interactive drawing. Like interactively TF1 can fail and request new
data with saved buffers. In batch mode saved buffer must be there
to be able do fallback immediately.
=> [webcanvas] support latest `TScatter` changes

html/inc/TClassDocOutput.h, html/inc/TDocDirective.h, html/inc/TDocInfo.h, html/inc/TDocOutput.h, html/inc/TDocParser.h, html/inc/THtml.h, html/src/TDocParser.cxx
This commit only contains changes that were automatically generated by `clang-tidy`, plus replacing `ClassDef` with `ClassDefOverride` where appropriate.
Several directories in the ROOT repo were already treated like this.
=> Automatically add `override` to html with clang-tidy

montecarlo/eg/inc/TAttParticle.h, montecarlo/eg/inc/TDatabasePDG.h, montecarlo/eg/inc/TDecayChannel.h, montecarlo/eg/inc/TGenerator.h, montecarlo/eg/inc/TParticle.h, montecarlo/eg/inc/TParticleClassPDG.h, montecarlo/eg/inc/TParticlePDG.h, montecarlo/eg/inc/TPrimary.h, montecarlo/eg/inc/TVirtualMCDecayer.h, montecarlo/eg/src/TGenerator.cxx, montecarlo/pythia6/inc/TMCParticle.h, montecarlo/pythia6/inc/TPythia6.h, montecarlo/pythia6/inc/TPythia6Decayer.h, montecarlo/pythia8/inc/TPythia8.h, montecarlo/pythia8/inc/TPythia8Decayer.h
This commit only contains changes that were automatically generated by `clang-tidy`, plus replacing `ClassDef` with `ClassDefOverride` where appropriate.
Several directories in the ROOT repo were already treated like this.
=> Automatically add `override` to montecarlo with clang-tidy

graf2d/gpad/src/TCanvas.cxx, gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/hist/TH1Painter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/RHistPainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Support "pol", "cyl", "sph" and "psr" coordinates systems with lego and surf plots
2. Use "col" as default draw option for TH2, "box2" for TH3
3. Allow to move/resize chrome browser window when calling `TCanvas::SetWindowPosition`, `TCanvas::SetWindowSize`, `TCanvas::SetWindowTitle`
=> [webcanvas] TH2 col default, support coordinates, let move browser

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/SimpleCollectionProxy.hxx, tree/ntuple/v7/test/ntuple_types.cxx
This follow-up PR further improved the situation after #12380.
In particular, the staging area of a collection cannot (apparently) be iterated -- see
https://github.com/root-project/root/blob/master/io/io/src/TGenCollectionProxy.cxx#L1573.
Other uses in the ROOT repository rely on `TVirtualCollectionProxy::At()`.  However, we can instead exploit the fact that the staging area is backed by an array, i.e. the elements are contiguous in memory.
Use this optimization also for `kSTLvector` collections, which was a TODO anyways.
This should also provide an advantage/simplification to PR #12948.
=> [ntuple] Fix `ReadGlobalImpl()` for proxied collections using a staging area

CMakeLists.txt
`git describe` is used to find the closest head/tag to checkout (see relatedrepo_GetClosestMatch).  A failed `git describe`, which happens e.g. in shallow clones, should be handled gracefully.
As noted by @hahnjo, however, a call to `relatedrepo_GetClosestMatch()` is not even required provided that the repository was found locally, and that we are not forcing checkout.  This is for a follow-up PR though.
=> [cmake] roottest: gracefully handle a failed `git describe`

README/ReleaseNotes/v630/index.md, tree/dataframe/inc/ROOT/RDF/RResultMap.hxx, tree/dataframe/inc/ROOT/RResultHandle.hxx, tree/dataframe/test/dataframe_vary.cxx
So that RunGraphs can be invoked from RResultMaps as well, without the need of a RResultPtr.
In order for RResultHandle's API to treat RResultPtr and RResultMap consistently, we also deprecate `RResultHandle::GetResultPtr`.
=> [DF] Make it possible to convert RResultMap to RResultHandle

graf2d/asimage/src/libAfterImage/ungif.c
Is a resubmit of #10999 with additional needed changes (as discussed in that original PR)
Fixes: #10990
This PR fixes #10990
=> libAfterImage: Properly set len parameter for GifAddExtensionBlock and iterate extensions

graf3d/gl/inc/TGLHistPainter.h, graf3d/gl/src/TGLHistPainter.cxx, hist/hist/inc/TH2.h, hist/hist/inc/TVirtualHistPainter.h, hist/hist/src/TH2.cxx, hist/histpainter/inc/THistPainter.h, hist/histpainter/src/THistPainter.cxx
Adds XY projection capabilities simultaneously for a standard TCanvas with a TH2. (This is needed for users in some applications where they do not use the new TWebCanvas, which was kindly implemented by @linev, but the traditional one).
This PR fixes https://github.com/root-project/root/issues/10660
=> [gui] TH2 SetShowProjectionXY

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
`RColumnElement` template specializations follow the same schema.  This pull request proposes judicious use of preprocessor macros, which results in more readable and maintanable code.
- Define PP macros: `DECLARE_RCOLUMNELEMENT_SPEC` and `DECLARE_RCOLUMNELEMENT_SPEC_SIMPLE`, which can be used to declare `RColumnElement` template specializations.
- Rewrite current specializations in terms of the aforementioned macros.
=> [ntuple] RColumnElement: use preprocessor macros to describe specializations 

core/clingutils/src/TClingUtils.cxx, interpreter/cling/lib/Interpreter/ForwardDeclPrinter.cpp, interpreter/cling/lib/Utils/AST.cpp
The other methods, such as directly calling begin() and end() as well as getNumArgs() and getArgs() will go away in LLVM 16, see commit https://github.com/llvm/llvm-project/commit/1acffe81ee.
=> [cling] Unify access to template_arguments

bindings/experimental/distrdf/python/DistRDF/Backends/Utils.py, bindings/experimental/distrdf/python/DistRDF/DataFrame.py, bindings/experimental/distrdf/python/DistRDF/Proxy.py, bindings/experimental/distrdf/python/DistRDF/__init__.py, bindings/experimental/distrdf/test/test_callable_generator.py, bindings/experimental/distrdf/test/test_node.py, bindings/experimental/distrdf/test/test_proxy.py
The new names should better represent the part of the computation graph each proxy refers to.
=> Change naming of classes in DistRDF.Proxy

roofit/roofitcore/inc/RooCacheManager.h, roofit/roofitcore/inc/RooNormSetCache.h, roofit/roofitcore/src/RooNormSetCache.cxx
Re-implement the RooNormSetCache with the appropriate STL containers. In particular, it now uses `std::set` and `std::deque` instead of `std::map` and `std::vector`, which was not efficient for the round-robin replacement.
This change was motivated because it could happen in the past that the round-robin replacement was dereferencing invalid iterators.
=> [RF] Modernize RooNormSetCache to fix invalid iterator dereferencing 

gui/browsable/inc/ROOT/Browsable/RProvider.hxx, gui/browsable/src/RProvider.cxx, gui/browsable/src/TLeafProvider.hxx, gui/browserv7/inc/ROOT/RBrowser.hxx, gui/browserv7/src/RBrowser.cxx, gui/browserv7/src/RBrowserRCanvasWidget.cxx, gui/browserv7/src/RBrowserTCanvasWidget.cxx, tree/webviewer/inc/ROOT/RTreeViewer.hxx, tree/webviewer/src/RTreeViewer.cxx, ui5/browser/controller/Browser.controller.js
1. Introduce progress handlers for browsables objects
2. Provide progress information when performing `TTree::Draw`
3. Display such progress on the client side in the warning dialog - while waiting on result of double click
4. Use `TVirtualMonitoringWriter` handle to hook inside `TTree::Draw` processing loop
5. Execute long operations (like tree draw) outside of websocket data handler to let receive other messages
6. Fix cleanup problem of widgets in RBrowser - JSROOT elements were not destroyed properly
=> [rbrowser] provide progess handlers, use for TTree::Draw

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RPageAllocator.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_endian.cxx
This pull request makes `UnsealPage()` a no-op for the page zero.  To this end, the prototype of `RPageSource::UnsealPage()` had to be changed to return an `RPage`, per previous conversation.
The buffer for the returned page is usually allocated using the `RPageAllocatorHeap`, and thus `RPageAllocatorHeap::DeletePage()` should be called to delete the returned object.
Note that storage backends may still provide their own page unsealing code, e.g. for custom memory allocation.
This PR fixes #12958.
=> [ntuple] Make `UnsealPage()` a no-op for the page zero

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx
This pull request is a follow-up of #13197, improving the implementation of the internal class `RCollectionClassField::RCollectionIterableOnce`.
- Allow for faster iteration of elements in a collection whose elements are guaranteed to be contiguous in memory (e.g. a vector), i.e. the address of each element is known given the base pointer.  For such cases, a non-zero value for the `stride` argument can be provided, thus avoiding an indirect call on each `operator++` call.
- Fix and clarify the use of read/write iterators on a proxied collection.  The meaning of the `read` argument in many
TVirtualCollectionProxy functions is "read from disk", i.e. write in memory.
This should improve the situation for the PR introducing support for `std::set<T>` fields (#12948).
=> [ntuple] Faster iteration of array-backed proxied collections

core/meta/src/TDataMember.cxx
This pull request fixes / improves the documentation for the `TDataMember::GetXyzTypeName()` member functions.
=> [core][skip-ci] Improve TDataMember documentation

gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayHandle.cxx, gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/files/canv_batch.htm
Using approach as before, just perform multiple `JSROOT.draw` inside
this special HTML file. When producing PDF - all these images should
be dump in single file. In all other cases correspondent number of
image files will be created.
Advantage of such approach - starting web browser and loading JSROOT
scripts happens only once.
Improve PDF generation
Simple 100 images can be generated in ~3 seconds (instead of 70s if doing one by one)
=> [webgui] provide API to create several images at once

bindings/experimental/distrdf/CMakeLists.txt
Uses the same logic as https://github.com/root-project/root/blob/9d0ae186d7b0556e7673987d3c50594697e73bb3/bindings/pyroot/pythonizations/CMakeLists.txt#L139
=> Make sure Python files are copied in incremental builds

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldValue.hxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/src/RColumn.cxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/rfield_vector.cxx
As discussed in the last I/O meeting, the current RFieldBase API for reading and writing is flawed.  The `RFieldBase::Read()` and `RFieldBase::Append()` methods take `RFieldValue` parameters, as thin wrappers around the target/source memory location. This is a misuse of the `RFieldValue` class and does not provide any additional benefit.
This PR changes the RFieldBase read/write APIs to use void pointers instead. It applies a similar change to the underlying `RColumn` read/write API (note that `RColumn` is supposed to be an internal API. NB: it still needs to move from `ROOT::Detail` to `ROOT::Internal`).
In a follow-up PR, the following change is foreseen:
- Make `RFieldValue` an inner class of `RFieldBase`, i.e. `RFieldBase::RValue`
- Make `RFieldBase::Read()` and `RFieldBase::Append()` …
=> [ntuple] Improvements to the RField read/write API

bindings/experimental/distrdf/python/DistRDF/__init__.py
- warn rather than raising an error in case of empty list of handles
- run sequentially if IMT is not enabled
@vepadulano I'm not sure what is the right place where to insert an `import ROOT`?
=> [DF] Make DistRDF's RunGraphs behave like RDF's RunGraphs

tree/dataframe/src/RDataFrame.cxx
`**note**` -> `\note`, and that PyROOT and RDataFrame are required for distRDF is kind of obvious and anyways they are included in virtually any ROOT installation.
=> [skip-ci][NFC][DF] Fix doxygen formatting, simplify wording

tree/tree/inc/ROOT/InternalTreeUtils.hxx, tree/tree/src/InternalTreeUtils.cxx, tree/tree/src/TChain.cxx, tree/tree/test/TChainParsing.cxx
First attempt at moving the globbing logic in `TChain::Add` out of the method. The main remaining question is where will this new free function actually live. It depends on `TRegexp`, `TString` and `TSystem`, so I guess  somewhere in `core/base`. Any ideas here?
I removed usage of `TList` in the function, with C++17 support I could use `std::filesystem` instead of `gSystem` which could be another small improvement in the logic.
=> Move globbing logic out of TChain::Add

roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/src/RooAbsData.cxx
Looking at the code, it was probably the idea at some point in the `RooAbsData` design that the ownership of the variables in the dataset can be shared, i.e. that the outside world can "claim" and "release" the variables in a RooAbsData. If anything else is still claiming the variables, they will not be deleted by the RooAbsData destructor.
That's quite messy. For example, if the RooAbsData is destructed before the external "claimers" releases the variables, the claimers suddenly has the responsability to delete the variables themselves. And who of them should do it then? The ownership model is completely unclear.
This and other reasons explain probably why the
`RooAbsData::claimVars()` and `RooAbsData::releaseVars()` are not used at all outside the RooAbsData, and this commit suggests to …
=> [RF] Remove useless variable ownership management from RooAbsData

README/ReleaseNotes/v630/index.md, roofit/roofitcore/inc/RooDataWeightedAverage.h, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooDataWeightedAverage.cxx
Use the CPU BatchMode instead of the RooDataWeightedAverage for data
projection plots. This greatly speeds up the plotting of conditional
models when averaging one observable over the dataset.
=> [RF] Use BatchMode for data projection plots

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roojsonfactorywstool.py, roofit/hs3/inc/RooFitHS3/JSONIO.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/JSONIO.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/roofitcore/inc/RooFormulaVar.h, roofit/roofitcore/inc/RooGenericPdf.h
- adds helper functions to RooGenericPdf and RooFormulaVar
- makes sure the HS3 JSON contains the names of the variables entering RooFormula-based PDF and function types also in cases where the functions have been constructed with the "x[0]" notation
=> [RF][HS3] RooFormulaArg bugfixes

roofit/roofitcore/inc/RooAbsOptTestStatistic.h, roofit/roofitcore/inc/RooAbsTestStatistic.h, roofit/roofitcore/inc/RooDataWeightedAverage.h, roofit/roofitcore/inc/RooHelpers.h, roofit/roofitcore/inc/RooNLLVar.h, roofit/roofitcore/inc/RooXYChi2Var.h, roofit/roofitcore/src/RooAbsOptTestStatistic.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsTestStatistic.cxx, roofit/roofitcore/src/RooHelpers.cxx, roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooProdPdf.cxx, roofit/roofitcore/src/RooRealSumPdf.cxx, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/src/RooXYChi2Var.cxx, roofit/roofitcore/test/testTestStatistics.cxx
At the moment the BinnedLikelihood feature only becomes active when doing an initSimMode inside a RooAbsTestStatistic. This change, I think, will allow for RooNLLVar to be used directly on a RooRealSumPdf and still get the BinnedLikelihood behaviour.
=> [RF] Allow BinnedLikelihood to be used without requiring it to be in a RooSimultaneous

core/metacling/src/CMakeLists.txt
This fixes the following type of error with recent versions of Visual Studio (v17.6):
```
800: Processing C:/root-dev/git/debug/tutorials/roofit/rf614_binned_fit_problems.C...
800: IncrementalExecutor::executeFunction: symbol '__std_find_trivial_8' unresolved while linking [cling interface function]!
800: You are probably missing the definition of __std_find_trivial_8
800: Maybe you need to load the corresponding shared library?
```
=> [windows] Export several potentially missing symbols

roofit/xroofit/src/xRooNLLVar.cxx
This avoids compiler warnings on 32bit platforms such as
```
warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but
argument 2 has type ‘std::vector<std::tuple<int, double, double> >::size_type’
{aka ‘unsigned int’} [-Wformat=]
```
As seen in PR https://github.com/root-project/root/pull/13243
=> [xroofit] Use std::string to format vector::size

roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testRooAbsL.cxx, roofit/roofitcore/test/TestStatistics/testRooRealL.cxx, roofit/roofitcore/test/gtest_wrapper.h, roofit/roofitcore/test/testNaNPacker.cxx, roofit/roofitcore/test/testProxiesAndCategories.cxx, roofit/roofitcore/test/testRooAbsPdf.cxx, roofit/roofitcore/test/testRooAddPdf.cxx, roofit/roofitcore/test/testRooBinSamplingPdf.cxx, roofit/roofitcore/test/testRooDataHist.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx, roofit/roofitcore/test/testRooProdPdf.cxx, roofit/roofitcore/test/testRooRealIntegral.cxx, roofit/roofitcore/test/testTestStatistics.cxx
Closes #12832.
There is also a commit that reduces code duplication in the unit tests by adding one single header where the gtest backwards compatibility changes are made.
=> [RF] Change precision for comparisons in `testLikelihoodJob` and `testRooAbsL`

roofit/roofitcore/src/RooRealSumPdf.cxx
According to the [documentation](https://en.cppreference.com/w/cpp/container/list/merge), the lists need to be sorted before merging them. This fixes a `Debug Assertion Failed! Expression sequence not ordered` error on Windows.
=> [RF] Sort the lists before merging

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py, bindings/pyroot/pythonizations/test/roofit/rooworkspace.py, roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONIOUtils.cxx, roofit/hs3/src/JSONIOUtils.h, roofit/hs3/src/RooJSONFactoryWSTool.cxx
Refactors the code and moves the logic of creating variables in RooWorkspace to C++-backend
Moves `make_json_for_variable` from `_rooworkspace.py` to `varJSONString` in `JSONIOUtils`
=> [RF][PyROOT] Refactor: move RooWorkspace variable creation logic to C++ backend

ui5/eve7/eve.mjs
It is no longer provided, alternative library used directly from TGeoPainter
=> [eve7] no need import dat.gui from JSROOT [skip-ci]

io/io/src/TDirectoryFile.cxx
Prevent infinite loop in TFile::ls
This bug was introduced in commit
72a3242c91b7ca3e4cf31e7a6d5ddc9638270d27
Solution found by SilentAssassinMa
This PR fixes https://github.com/root-project/root/issues/8650 and https://github.com/root-project/root/issues/13182
=> [IO] Prevent infinite loop in TFile::ls

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Apparently, `TClassEdit::ResolveTypedef()` is unable to resolve a typedef that aliases a fundamental data type if the `typedef` declaration is not known to cling.  In non-C++-modules builds, making it known typically involves parsing the corresponding header.
In addition, `TDataMember::GetTrueTypeName()`, however, correctly provides the information, which seems to be inconsistent behavior in ROOT meta.
This pull request is twofold: _(i)_ it cleans up the code for type name normalization, and _(ii)_ circumvents this issue by directly using the resolved type name provided by `TDataMember::GetTrueTypeName()`.
- Separate the internal `GetNormalizedType()` function in `GetCanonicalTypeName()` (which returns the canonical name of a type, resolving typedefs where needed) and …
=> [ntuple] Avoid the use of `TClassEdit::ResolveTypedef()` in the creation of class members' fields

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/core.mjs, js/modules/draw/more.mjs, js/modules/gpad/RCanvasPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gui/display.mjs, js/modules/gui/menu.mjs
Only when window geometry reported by the client - return it with methods like `c1->GetWindowWidth()` or `c1->GetWindowTopX()`. If value is not known yet - keep initial values
Small updates in JSROOT
=> [webcanvas] correctly return window geometry

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/modules/gpad/TCanvasPainter.mjs
1. Introduce special timer to send data to clients. If not everything can be send at once, after short timeout will be tried again
2. Extend functionality of control message, manage it per connection. All special messages like enabling editor, moving web browser, enable/disable tooltip - all belong now to control message
3. Change message priority, try to send as much as possible. First one sends control message, then specially requests for menu or projection and finally update for canvas drawing.
4. Implement `Raise() / Iconify()` methods, they fully depend on the web browser
=> Improve `TWebCanvas` communication, more use of control messages

interpreter/cling/lib/Interpreter/Value.cpp, interpreter/cling/test/MultipleInterpreters/MultipleInterpreters.C
The return type of `foo(int)` is `void`, which causes an assertion failure in `lib/Interpreter/Value.cpp:163`: "Type not supported".
=> [cling] Fix test MultipleInterpreters.C

interpreter/cling/test/CodeUnloading/PCH/VTables.C, interpreter/cling/test/lit.cfg, interpreter/cling/test/lit.site.cfg.in
This fixes `test/CodeUnloading/PCH/VTables.C` with C++17 and later.
=> Automatically adjust C++ version of PCH in Cling's test

interpreter/cling/include/cling/Interpreter/Interpreter.h, interpreter/cling/lib/Interpreter/CMakeLists.txt
When cling is compiled standalone against an external instance of LLVM and clang, cling cannot be reliably used. This is because ```createCI()``` throws an error about a non-existing clang resource directory inside the cling directories and a crash occurs shortly afterwards, when a code to be interpreted is entered.
The reason of the above seems to be the inability of cling and its build system to flag properly that there is no built-in LLVM/clang and therefore cling should use the external one instead.
This PR fixes it by introducing the ```LLVM_PATH``` pre-processor definition which is populated automatically by CMake with the detected LLVM directory as soon as both ```builtin_llvm``` and ```builtin_clang``` are off.
If I should have done this in a different way, there are pieces of …
=> Fix cling incorrect LLVM path for external LLVM + clang

tutorials/CMakeLists.txt
They currently trigger segfaults in TClass*/cling of the like:
```
RAssertion failed: ((*I)->isCompleted() && "Nested transaction not completed!?"), function endTransaction, file IncrementalParser.cpp, line 511.
*** Break *** abort
Error in <TClingCallFunc::make_dtor_wrapper>: Failed to compile
==== SOURCE BEGIN ====
__attribute__((used)) extern "C" void __dtor_32(void* obj, unsigned long nary, int withFree)
{
if (withFree) {
if (!nary) {
delete (TMVA::Experimental::Internal::RBatchGenerator<float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &, float &>*) obj;
}
else {
delete[] …
```
=> [tmva] Disable RBatchGenerator tutorials

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
These symbols may not be found automatically. See also upstream issue https://github.com/llvm/llvm-project/issues/61289. This fixes the test `DynamicLibraryManager/cached_realpath.C`, approach by Lang Hames.
=> [cling] Inject symbols from libc_nonshared.a

tutorials/CMakeLists.txt
In that case `PYTHON_VERSION_STRING_Development_Main` is not set:
```
CMake Error at tutorials/CMakeLists.txt:80 (if):
if given arguments:
"VERSION_LESS" "3.8"
Unknown arguments specified
```
=> Fix CMake configuration without Python

core/clingutils/src/TClingUtils.cxx
We compile our code (including the dictionaries) with warnings about C-Style casts. We would like to also reduce the warnings about the dictionaries.
=> Avoid C-Style Casts in Dictionary

montecarlo/eg/inc/TPDGCode.h
`LinkDef.h` specifies a `pragma link C++ enum PDG_t` but actually `PDG_t` was a `typedef` to an anonymous `enum`.
=> [montecarlo] Fix enum PDG_t

tree/treeplayer/inc/TBranchProxy.h, tree/treeplayer/src/TBranchProxy.cxx
In particular this should prevent issues that are noticed on Windows as:
"Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.
This is usually a result of calling a function declared with one calling convention with a
function pointer declared with a different calling convention."
And a related (but 'harmless') case of `fLeafCount` being set right after `fBranchCount` was set.
=> TBranchProxy: Improve logic of fBranchCount/fLeafCount

tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
This PR fixes issue #13088. As the title title suggests, when an unnamed `TChain` is provided to `RNTupleImporter::Create`, it will use the name of the name of the first `TTree` as a default.
=> [ntuple] Use name of first `TTree` when importing unnamed `TChain`

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/test/SimpleCollectionProxy.hxx
Per the last ROOT I/O meeting (where the correct use of iterators to array-backed collections, e.g. `std::vector<T>`): an iterator on an array-backed container is just a pointer; thus, it can be directly stored in `*xyz_arena`, saving one dereference (see [here](https://github.com/root-project/root/blob/master/io/io/inc/TVirtualCollectionIterators.h#L34)).
This pull request, fixes both the implementation of `RCollectionIterableOnce` and the unit test.  As a result, this PR should fix the use case in PR #12948.
Given that this behavior was not documented at all, a follow-up PR will update the documentation for `TVirtualCollectionProxy`.
=> [ntuple] Fix iteration of proxied array-backed collections

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci.yml
The `/tmp` area in macOS seems to be restricted in size, failing jobs when upgrading to LLVM 16.
=> [ci] Build in home directory [skip-ci]

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds some (mostly size and compression-related) methods to the `RNTupleInspector` utility class. There are some small TODOs left, but I first wanted to collect some feedback.
=> [ntuple] Add column- and field-related RNTupleInspector functionality

tree/dataframe/src/RNTupleDS.cxx, tree/dataframe/test/CMakeLists.txt, tree/dataframe/test/NTupleStruct.cxx, tree/dataframe/test/NTupleStruct.hxx, tree/dataframe/test/NTupleStructLinkDef.h, tree/dataframe/test/datasource_ntuple.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx
Fix setting the field IDs of fields with subfields in the RNTuple RDF data source. It also fixes field IDs for clones of RClassField instances.
This PR fixes #12852
=> [ntuple] fix setting field IDs for complex fields in RDF DS

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/cling/test/CodeUnloading/PCH/VTables.C, interpreter/cling/test/lit.cfg, interpreter/cling/test/lit.site.cfg.in
This makes `check-cling` clean on `v6-28-00-patches`.
=> Backport fixes for Cling tests [v6.28]

core/metacling/src/TCling.cxx
There can be multiple attributes in the forward declaration, see the added test in [`roottest/cling/dict/enum` ](https://github.com/root-project/roottest/pull/986) (reduced from a case reported by CMS in https://github.com/cms-sw/cmssw/issues/42234), so we have to look for the last closing parentheses.
=> [TCling] Fix suppression of enum forward declarations

README/ReleaseNotes/v630/index.md
This pull request updates the release notes for ROOT v6.30 (changes up to 25-Jul).
=> [relnotes][skip-ci][v6-30] Update release notes incl. RNTuple and Build system changes

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx
Rename `...By()` methods in `RFieldBase` to `Call...On()`.
Follow-up from #13317
=> [ntuple] Rename of RFieldBase internal methods

math/minuit2/src/MnContours.cxx
Print info before inserting a value in the vector (therefore invalidating the iterator). This fixes a debug assertion failure "can't dereference invalidated vector iterator", as explained [in the standard](https://en.cppreference.com/w/cpp/container/vector/insert):
> Causes reallocation if the new size() is greater than the old capacity(). If the new size() is greater than capacity(), all iterators and references are invalidated.
=> Fixes an assertion "can't dereference invalidated vector iterator"

tutorials/v7/ntuple/ntpl007_mtFill.C
Add several missing includes, possibly fixing a crash on Windows (x64)
=> Add missing includes

core/dictgen/src/SelectionRules.cxx, io/rootpcm/src/rootclingIO.cxx
Found while debugging `roottest-root-multicore-tsenums` with LLVM 16.
=> Fixes to `rootcling`'s handling of (unnamed) enums

core/metacling/src/TCling.cxx
There can be multiple attributes in the forward declaration, see the added test in `roottest/cling/dict/enum` (reduced from a case reported by CMS in https://github.com/cms-sw/cmssw/issues/42234), so we have to look for the last closing parentheses.
(cherry picked from commit 9d2f7612a6e88d3a7148b19e131402349bac509b, backport of https://github.com/root-project/root/pull/13319)
=> [TCling] Fix suppression of enum forward declarations [v6.28]

core/metacling/src/TCling.cxx
There can be multiple attributes in the forward declaration, see the added test in `roottest/cling/dict/enum` (reduced from a case reported by CMS in https://github.com/cms-sw/cmssw/issues/42234), so we have to look for the last closing parentheses.
(cherry picked from commit 9d2f7612a6e88d3a7148b19e131402349bac509b, backport of https://github.com/root-project/root/pull/13319)
=> [TCling] Fix suppression of enum forward declarations [v6.26]

hist/histpainter/src/THistPainter.cxx
Recently Color option was defined as default for TH2. Means if any other option is set, it should be removed. But if 'col' or 'colz' option was specified, one have to deliver it.
Causes problem with TH2Poly drawings like 'AL COLZ' which is valid combination
Addresses issue in CMSSW:  https://github.com/cms-sw/cmsdist/pull/8590
=> [histpainter] reset color option only if not explicitly specified

.github/workflows/llvm-diff.yml, interpreter/llvm-project/.clang-format, interpreter/llvm-project/.clang-tidy, interpreter/llvm-project/.gitignore, interpreter/llvm-project/llvm/.gitattributes, interpreter/llvm-project/llvm/.gitignore
The `.gitignore` files were traditionally skipped to not exclude the `tools/clang/` directory, but this isn't necessary since adopting the monorepo. Adding them back will correctly ignore the compiled Python `pyc` files after running `check-cling`.
=> [skip-ci] Add LLVM's gitignore

roofit/roofitcore/inc/RooIntegrator1D.h, roofit/roofitcore/src/RooIntegrator1D.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooIntegrator1D.cxx
The RooIntegrator1D class is refactored such that it is a wrapper around a free function with only STL dependencies that does the Romberg integration.
This is very useful for R & D projects, because the integration code can be reused standalone outside of RooFit. This can serve as a reference when implementing and benchmarking new integration methods.
=> [RF] Refactor RooIntegrator1D to use free functions

bindings/experimental/distrdf/python/DistRDF/__init__.py
Making the decision on the scheduling mode based on `IsImpliciMTEnabled` would mean forcing users to run `EnableImplicitMT` every time they want to submit distributed graphs concurrently.
If the user has already chosen to run a distributed RDataFrame application, RunGraphs should just submit all the computations concurrently to the distributed scheduler. The "sequential" mode of operation can still be achieved by e.g. calling `GetValue` on distributed proxies in a for loop.
=> Distributed RunGraphs always submits concurrently

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
With this PR, a new method `GetFieldsByName` is added to the `RNTupleInspector` and the option to get the number of fields whose type matches a certain regular expression is added. The first is useful for RNTuples where field names have certain semantic meaning (e.g. `.*AuxDyn`). The second can be used to group certain templated types (e.g. `std::vector<.*>`).
These additions are also in anticipation of a larger PR that will add functionality to get more complete statistics about a set of fields (and columns).
=> [ntuple] Add more field-related inspector functions 

tree/ntuple/v7/test/CustomStructLinkDef.h
This fixes `gtest-tree-ntuple-v7-test-ntuple-types` in a PCH build.
=> [ntuple] Correct LinkDef entries for enum classes

core/metacling/src/TCling.cxx, core/metacling/test/CMakeLists.txt, core/metacling/test/TClingLoadUnloadFileTests.cxx
It modifies the interpreter state, thus needs locking.
UPDATE:
As suggested by @hahnjo I tried to write a small unit test to see the data race in action. In fact it was pretty easy, and it also highlighted another data race in `TCling::LoadFile`. In the latest commits I take care both of adding the lock to the other method and adding the test.
=> Add lock in TCling::UnloadFile

hist/hist/inc/TH2Poly.h, hist/hist/src/TH2Poly.cxx, tutorials/hist/th2polyHoneycomb.C
New parameter `option` for Honeycomb.
- If the option "v" is specified, the hexagons are drawn "vertically" (default).
- If the option "h" is selected they are drawn "horizontally".
The option "h" has been suggested by Sam Liechty in this forum thread:
https://root-forum.cern.ch/t/rotate-a-figure-90-degrees/55623/7
Thanks Sam !
=> Implement options for Honeycomb

gui/browserv7/inc/LinkDef.h, gui/browserv7/inc/ROOT/RBrowserData.hxx, gui/browserv7/src/RBrowserData.cxx
This fixes the test `roottest-root-core-execStatusBitsCheck` when building with `runtime_cxxmodules=OFF`, see #13058.
---
I don't know if there is an easier / better solution for this...
=> [rbrowser] Move RBrowserDataCleanup into header and LinkDef.h

roofit/roofitcore/inc/RooMultiVarGaussian.h, roofit/roofitcore/src/RooMultiVarGaussian.cxx
So far, the RooMultiVarGaussian required a TMatrixDSym as an input for the covariance matrix, but it would be more convenient to accept the TMatrixDBase class such that questions like on this forum post don't even come up:
https://root-forum.cern.ch/t/multivariate-gaussian-object-creation/55721
The only logic that needs to be added is if the input matrix is symmetric, and an exception will be thrown if it is not.
This change doesn't break backwards compatibility
=> [RF] Generalize RooMultiVarGaussian to be constructed from TMatrixDBase

roofit/histfactory/src/HistFactoryNavigation.cxx, roofit/roofit/inc/RooNDKeysPdf.h, roofit/roofit/src/RooChi2MCSModule.cxx, roofit/roofit/src/RooNDKeysPdf.cxx, roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/inc/RooDataSet.h, roofit/roofitcore/inc/RooFit/Config.h, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsGenContext.cxx, roofit/roofitcore/src/RooAbsOptTestStatistic.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roofitcore/test/testRooDataSet.cxx, roofit/roostats/inc/RooStats/MCMCInterval.h, roofit/roostats/inc/RooStats/MarkovChain.h, roofit/roostats/src/MCMCInterval.cxx, roofit/roostats/src/MarkovChain.cxx, test/stressRooFit_tests.h
It's not clear to users whether the `RooDataSet` passed to a
RooNDKeysPdf has to live as long as that pdf or not.
Right now it has to live just as long, because the RooNDKeysPdf contains
the RooDataSet by non-owning pointer. However, there was no reason for
that, because the dataset is only used in the constructor.
This commit suggests to drop this unused `_data` member of the
RooNDKeysPdf, solving potential lifetime problems: the dataset doesn't
need to live as long as the RooNDKeysPdf anymore.
With this change, it was possible to use some more of the `RooFit::OwningPtr<T>` alias in RooFit, which is done in the second commit of this PR.
=> [RF] Don't store reference to `RooDataSet` in RooNDKeysPdf

math/mathcore/inc/Math/Types.h
Similar to 736644bce3b, ignoring some warnings from `Vc` that will not be fixed upstream for the foreseeable time because `Vc` is in maintainance mode.
=> [math] Avoid warnings from Vc.h from deprecated enum comparisons

core/base/inc/TBuffer3D.h, core/base/src/TBuffer3D.cxx, geom/geom/src/TGeoScaledShape.cxx, graf3d/gl/src/TGLScenePad.cxx
Fixes GL drawing for scaled shapes which are normally optimized to use GL primitives and appeared un-scaled (e.g. tubes)
Added new flag `TBuffer3D::fScaled` set by `TGeoScaledShape::GetBuffer3D` and used by the viewer to decide if `TBuffer3D::kRaw` section needs to be filled/used
=> Correct GL drawing for scaled shapes

geom/gdml/inc/TGDMLParse.h, geom/gdml/inc/TGDMLWrite.h, geom/gdml/src/TGDMLParse.cxx, geom/gdml/src/TGDMLWrite.cxx
Adds GDML support for `scaledSolid` tag
Given that Geant4 supports the `scaledSolid` tag, all TGeo scaled solids are exported using this tag now. Below is a snapshot of the solids produced after importing the Geant4 persistency example `examples/extended/persistency/gdml/G01/scaledSolids.gdml` <img src="https://github.com/root-project/root/assets/18400453/dd95e08f-a3b7-47c1-8e86-844a66aae167" width="600">
This PR fixes #13194
=> Added support for GDML read/write of scaled solids.

interpreter/CMakeLists.txt, interpreter/cling/CMakeLists.txt, interpreter/cling/tools/packaging/cpt.py
Remove usage of `--src-root`, which is removed in LLVM16 (https://github.com/root-project/root/pull/13273). See also https://github.com/hahnjo/root/pull/1. Only relevant for external LLVM and works without this anyway.
=> [cmake] Remove usage of --src-root with llvm-config

cmake/modules/SearchInstalledSoftware.cmake
If `builtin_gtest` was initially off (since commit 28ddffca94), we first try to look for an installed version of GTest. If not found, this falls back to `builtin_gtest`, but also sets `GTEST_INCLUDE_DIRS` to `GTEST_INCLUDE_DIRS-NOTFOUND`, which is not a valid value to have in `INTERFACE_INCLUDE_DIRECTORIES`.
=> [cmake] Remove faulty GTEST_INCLUDE_DIRS

html/src/TDocParser.cxx, tree/tree/src/TBranch.cxx, tree/tree/src/TBranchElement.cxx, tree/tree/src/TBranchIMTHelper.h, tree/tree/src/TTree.cxx, tree/treeplayer/src/TTreeFormula.cxx
e.g.
```
bitwise operation between different enumeration types ‘TBranch::EStatusBits’ and ‘TBranchElement::EStatusBits’ is deprecated [-Wdeprecated-enum-enum-conversion]
```
```
implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
```
=> [tree,html] Fix C++20/GCC13 warnings (enum arithmetic, this capture):

tree/ntuple/v7/src/RPageStorageDaos.cxx
This pull request simplifies the implementation of `RPageSourceDaos::LoadClusters()` as a prior step to handling the population of the page zero.
A follow-up PR factors out common code for handling `kTypePageZero` locators in storage backends + enables their population in the DAOS backend.
=> [ntuple] Simplify `RPageSourceDaos::LoadClusters()`

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_bulk.cxx
Adds optimized `BulkRead` implementations for RVec of simple types and cardinality fields. Along the way, fixes an issue with RNTuple's handling of adopted RVecs.
@eguiraud @vepadulano If RDF relies on the elements of a bulk of RVec<PoD> being all consecutively in memory, we also need to implement `BulkRead` for `RArrayAsRVecField` (#13040)
=> [ntuple] Bulk read optimizations for RVec

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds an additional method to get the IDs of all columns with the given type. It also restructures the `RNTupleInspector` file structure to better group column- and field-related methods.
=> [ntuple] Add `GetColumnsByType`

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
This PR adds `std::set` fields. For type-erased fields, we use virtual collection proxies. This already implemented for `RCollectionClassField` fields, but reading from disk for associative containers works slightly different. Therefore, a `RProxiedCollectionField` class is introduced that takes care of all proxy-related implementation and can be used for custom collections, and `RSetField` which inherits from this and specializes for `std::set` (and other related STL collections that will be addressed in a follow-up PR).
=> [ntuple] Add support for `std::set` fields

core/dictgen/src/rootcling_impl.cxx
Removes a -W quirk for old clang version, has since been added to clang: https://releases.llvm.org/13.0.0/tools/clang/docs/DiagnosticsReference.html#wnoexcept-type
=> [dictgen] remove -Wno-noexcept-type quirk for old clang versions

roofit/roofit/inc/RooParametricStepFunction.h, roofit/roofit/inc/RooStepFunction.h, roofit/roofit/src/RooParametricStepFunction.cxx, roofit/roofit/src/RooStepFunction.cxx, roofit/roofitcore/inc/RooCurve.h, roofit/roofitcore/src/RooCurve.cxx, roofit/roofitcore/src/RooHistPdf.cxx
The RooFit plotting did not work well for variables of small orders of
magnitude, because there was a hardcoded check with an absolute value to
see if two points are considered the same: `x2 - x1 < 1e-20`. If this
condition is true, the point at x2 was not plotted. This meant that some
points that were actually different were skipped.
The fix is to change this condition to a relative one, considering xmin
and xmax. The code to generate sampling hints for histograms was also
moved inside RooCurve, such that it's easier to syncronize the relevant
magic constants.
Here is a demo of a plot that didn't work before but now works:
```C++
void repro()
{
int nBins = 4;
double scale = 1e-31;
double xmin = 0. * scale;
double xmax = 1. * scale;
double binWidth = (xmax - xmin) / nBins;
// Fill the bin …
```
=> [RF] Make plotting of histograms work for all orders of magnitude

core/foundation/inc/ROOT/RConfig.hxx
Since version 2.38, glibc provides strlcpy and strlcat. No need to provide our own.
In fact ROOT's definitions clash with glibc's: the latter are marked `noexcept`.
=> [core] Do not provide our own strlcpy if glibc >= 2.38

roofit/roofit/inc/RooBCPEffDecay.h, roofit/roofit/inc/RooBCPGenDecay.h, roofit/roofit/inc/RooBDecay.h, roofit/roofit/inc/RooBMixDecay.h, roofit/roofit/src/RooBCPEffDecay.cxx, roofit/roofit/src/RooBCPGenDecay.cxx, roofit/roofit/src/RooBDecay.cxx, roofit/roofit/src/RooBMixDecay.cxx
This is done to close the following Jira issue:
https://sft.its.cern.ch/jira/browse/ROOT-7994
The parameter explanations are taken from the proxy titles in the constructor initializer lists.
=> [RF] Add documentation to `RooB*Decay` constructors

core/foundation/inc/ROOT/RConfig.hxx
Since version 2.38, glibc provides strlcpy and strlcat. No need to provide our own.
In fact ROOT's definitions clash with glibc's: the latter are marked `noexcept`.
=> [core] Do not provide our own strlcpy if glibc >= 2.38 (v6.28)

tree/dataframe/src/RDFHelpers.cxx
Fix several `warning C4129: 'e': unrecognized character escape sequence` on Windows
=> Fix warnings on Windows

test/stressTMVA.cxx
Fix a crash with stressTMVA on Windows x86 in debug mode, due to memory exceeding 2 Gb
=> Fix memory leaks in stressTMVA

gui/browserv7/inc/LinkDef.h, gui/browserv7/inc/ROOT/RBrowserData.hxx, gui/browserv7/src/RBrowserData.cxx
This also fixes the test `roottest-root-core-execStatusBitsCheck` when building with `runtime_cxxmodules=OFF`.
Closes https://github.com/root-project/root/issues/13058
=> [rbrowser] Make fCleanupHandle a pointer to TObject

interpreter/cling/cmake/modules/CMakeLists.txt
Potential fix for #12151. Needs input from @vgvassilev for why `cling_cmake_builddir` was changed in 2b283ccf3a624f70dab3e8783d361d25c13e2c65.
I did not test this for the non-builtin case and I can't confirm this works fully since testing it is blocked by #12152.
This PR fixes #11920.
=> CMake: use CLING_BINARY_DIR instead of LLVM_BINARY_DIR to configure ClingConfig.cmake

geom/geom/inc/TGeoVolume.h, geom/geom/src/TGeoVolume.cxx
This Pull request allows to set in TGeo the transparency of objects at the level of individual TGeoVolume instances.
ROOT was attributing the volume transparency to the material of the volume.
This is not always the desired behavior. The PR preserves the current functionality if the transparency level is not
explicitly set to the volume instance. 
Improved functionality: If the transparency level is set directly to the volume instance, the volume transparency 
takes precedence over the material transparency. The default behavior can be restored by setting a transparency 
level of -1 to the volume.
Improves the flexibility to set transparency to geometry volumes.
- [xxx] tested changes locally
=> Allow geometry transparency at the volume level

core/meta/inc/TInterpreter.h
Avoids warnings when -Wzero-as-null-pointer-constant is used like:
```
include/TInterpreter.h: In member function ‘virtual TypeInfo_t*
TInterpreter::MethodArgInfo_TypeInfo(MethodArgInfo_t*) const’:
include/TInterpreter.h:520:95: warning: zero as null pointer constant
[-Wzero-as-null-pointer-constant]
520 |    virtual TypeInfo_t *MethodArgInfo_TypeInfo(MethodArgInfo_t *
/* marginfo */) const {return 0;}
|
include/TInterpreter.h: In member function ‘virtual void*
TInterpreter::TypeInfo_QualTypePtr(TypeInfo_t*) const’:
include/TInterpreter.h:535:80: warning: zero as null pointer constant
[-Wzero-as-null-pointer-constant]
535 |    virtual void  *TypeInfo_QualTypePtr(TypeInfo_t * /* tinfo */)
const {return 0;}
```
=> Use nullptr in TInterpreter.h

hist/hist/inc/HFitInterface.h, hist/hist/src/HFitImpl.cxx, hist/hist/src/HFitInterface.cxx, hist/hist/src/TGraph.cxx, hist/hist/src/TGraph2D.cxx, hist/hist/src/TH1.cxx, hist/hist/src/TMultiGraph.cxx, math/mathcore/src/BinData.cxx, math/mathcore/src/FitUtil.cxx, test/stressHistoFit.cxx
In case of a weighted histogram a weight was applied to compute the expected error for every histogram when the error is not equal to sqrt(N).  Now this is done only in case the user perform the fit using the new option "PW", otherwise it is assumed the histogram is not weighted and no correction is used for the expected error.
See also post https://root-forum.cern.ch/t/does-pearson-chi-square-fit-use-expected-error-or-observed-error-in-th1-fit/55816/3
=> [math] Fix Pearson chi2 fit for weighted histograms

interpreter/CMakeLists.txt, interpreter/cling/CMakeLists.txt
Ensure that LLVM is always linked statically. While doing so this fixes #12156 and #12152. Tested with both LLVM 13 and LLVM 16.
This PR fixes #12156 #12152
=> Fix building with external LLVM

graf3d/eve7/src/REveDataCollection.cxx, ui5/eve7/controller/EveTable.controller.js
In the REveDataTable list of suggestion was limited to 100. The limit was inherited with openui5 input widget.
In  REveDataCollection::StreamPublicMethods suggestion list is created with TClass::GetListOfAllPublicMethods() where void functions are omitted.
=> [REve] Remove the limit of REveDataCollection table suggestions

math/mathcore/src/FitResult.cxx
=> [mathcore] Fix return of FitResult::ParameterBounds as doc says.

core/base/inc/TStyle.h, core/base/src/TStyle.cxx, js/build/jsroot.js, js/modules/core.mjs, js/modules/gui/menu.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/THistPainter.mjs
1. Introduce TStyle::fOrthoCamera flag
2. Use it only with JSROOT lego plots
Usage example is:
```
root --web=chrome hsimple.root -e 'gStyle->SetOrthoCamera();hpxpy->Draw("lego2")'  
```
Produce output:
=> [webgui] let configure orthographic camera for lego plots

core/cont/inc/TVirtualCollectionProxy.h
Fix typos in `TVirtualCollectionProxy` class documentation accidentally introduced in #13307.
=> [core][skip-ci] Fix typos in TVirtualCollectionProxy documentation

graf2d/graf/src/TLatex.cxx
Used only for `#odot` processing
Fixes: https://root-forum.cern.ch/t/55967
=> Fix rounding problem in circle drawing in latex parser

graf2d/graf/src/TLatex.cxx
Used only for #odot processing
Fixes: https://root-forum.cern.ch/t/55967
=> Fix rounding problem in circle drawing in latex parser [6.28]

interpreter/cling/test/Driver/CommandHistory.C, interpreter/cling/test/Driver/CurrentDirRm.C, interpreter/cling/test/Driver/Gnu.C, interpreter/cling/test/Driver/StartupFile.C, interpreter/cling/test/DynamicLibraryManager/cached_realpath.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_subst.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_subst1.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_subst2.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_subst3.C, interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_subst4.C, interpreter/cling/test/DynamicLibraryManager/pie.C, interpreter/cling/test/lit.cfg
With LLVM 16 and https://reviews.llvm.org/D141007, this will not be
supported anymore. As a replacement, use `system-{darwin,linux,windows}`.
Also replace `REQUIRES: not_system-windows` by `UNSUPPORTED: system-windows`.
=> [cling] Stop using triple substrings in UNSUPPORTED

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx
Per #12676, all storage backends should be able to populate the page zero from `kTypePageZero` locators.  This pull request adds the missing pieces in the DAOS backend.
- Add the `RPageStorage::PrepareLoadCluster()` helper which can be used in the implementation of `LoadClusters()` in derived classes to prepare the read of page ranges.  This function takes care of filling zero pages in the given `ROnDiskPageMap`.
- Add the missing pieces in `RPageSourceDaos`.
This PR fixes #12960.
=> [ntuple,daos] RPageSourceDaos: populate the page zero from `kTypePageZero` locators

hist/hist/src/TF1.cxx, hist/hist/src/TF12.cxx, hist/hist/src/TFormula_v5.cxx, hist/hist/src/TFractionFitter.cxx, hist/hist/src/TGraphTime.cxx, hist/hist/src/THnBase.cxx, hist/hist/src/TMultiDimFit.cxx, hist/hist/src/TPrincipal.cxx
It is not allowed to call
```
new TH1I(Form("name%d",i), Form("title%d",i), ...)
```
It is not allowed to store return value of Form() function and use it for a longer time.
There were several places like that
=> Fix illegal usage of Form function in hist/hist classes

interpreter/CMakeLists.txt, interpreter/cling/CMakeLists.txt, interpreter/cling/cmake/modules/CMakeLists.txt
Backport of https://github.com/root-project/root/pull/12153 and https://github.com/root-project/root/pull/13420
https://github.com/root-project/root/issues/12151 / https://github.com/root-project/root/issues/11920
https://github.com/root-project/root/issues/12152 + https://github.com/root-project/root/issues/12156
=> Fix building with external LLVM [v6.28]

cmake/modules/RootConfiguration.cmake
Was introduced by
https://github.com/root-project/root/commit/e7d80140e6847bbffa0765c4610c4e7d0266a0c6
Seems to be bug was resolved:
https://bugs.launchpad.net/chromium-browser/+bug/1893020
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1894216
=> [cmake] remove chrome workaround for Ubuntu

graf2d/gpad/src/TCanvas.cxx, gui/gui/src/TRootCanvas.cxx
Currently after `c1->SetCanvasSize(800,700)` area for painting is fixed-size. If necessary, gui shows scrollbars.
There was no method to switch this mode back - only via canvas context menu.
I propose to use `c1->SetCanvasSize(0,0)` to enable autofit mode again. 
Also minimize usage of `gVirtualX` with web-based canvas. 
The only exception - usage of  `gVirtualX->IsCmdThread()`.
=> Let enable autoresize mode again for TCanvas

roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/src/RooAbsReal.cxx
* Use `Corr` instead of `Cov` in the documentation of
`RooAbsReal::getPropagatedError()
* Add missing backslashes
Closes https://github.com/root-project/root/issues/13404.
=> [RF] Improve docs of RooAbsReal::getPropagatedError()

tree/ntuple/v7/src/RNTupleSerialize.cxx
Commit 6abb8e90d9 reverts to the `std::span` pointer/pointer constructor. Unfortunately, per https://en.cppreference.com/w/cpp/container/vector/end, dereferencing the end iterator of a vector results in undefined behavior. This actually triggers an assertion on MSVC:
```
Assertion failed: can't dereference out of range vector iterator
```
Change the constructor to use pointer/size instead, which is also compatible with the original fix for libc++ in commit 6abb8e90d9.
This should fix the aforementioned assertion on Windows.
=> [ntuple] RNTupleSerialize: construct `std::span` from pointer + size

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageStorage.cxx
Commit 2b54b792fc (added by PR #13388) changed the type of the third argument to `std::function`. However, the correct type should be
```
std::function<void(DescriptorId_t, NTupleSize_t,
const RClusterDescriptor::RPageRange::RPageInfo &)> perPageFunc)
```
Otherwise, passing by value incurs in an extra copy in `std::function<...>::operator()`.
=> [ntuple] Fix typo in `RPageSource::PrepareLoadCluster` signature

cmake/modules/RootConfiguration.cmake, gui/webdisplay/src/RWebDisplayHandle.cxx
=> [webgui] backport gentoo chrome paths, remove ubuntu workaround [6.28]

gui/qt5webdisplay/CMakeLists.txt, gui/qt5webdisplay/rootqt5.cpp, gui/qt5webdisplay/rooturlschemehandler.cpp, gui/qt5webdisplay/rooturlschemehandler.h, gui/qt5webdisplay/rootwebpage.cpp, gui/qt5webdisplay/rootwebpage.h, gui/qt5webdisplay/rootwebview.cpp, gui/qt5webdisplay/rootwebview.h, gui/qt6webdisplay/CMakeLists.txt, gui/qt6webdisplay/rootqt6.cpp, tutorials/webgui/qtweb/TCanvasWidget.cpp
1. Always register custom "rootcheme" to the Qt WebEngine libs before starting any widget. Was missing when QApplication was created by user
2. Correctly cleanup QApplication in qt5 - only when ROOT shutdown procedure started, it should be deleted. Requires special workaround to detect shutdown
3. Fix c++20 compiler warnings in qtweb tutorial
4. Show full qt version in error printouts
=> [qt5web] imrpove creation and cleanup of QApplication

core/base/src/TROOT.cxx
For example this allows unique_ptr to be deleted first and thus inform TROOT if need be
Fix #13462
=> Delete the object held by gROOT after we reset the globals.

roofit/histfactory/test/CMakeLists.txt, roofit/histfactory/test/testHistFactory.cxx, roofit/histfactory/test/testHistFactoryPlotting.cxx, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooBinWidthFunction.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAddHelpers.cxx, roofit/roofitcore/src/RooBinWidthFunction.cxx, roofit/roofitcore/src/RooExtendPdf.cxx, roofit/roofitcore/src/RooRealIntegral.cxx
Make component plots also work with HistFactory models and include a unit test. More detail on the fixes in the commit descriptions. There were in fact two separate bugs that resulted in this not working:
1. Wrong component (sample) selection because the same RooBinWidthFunction is used for all samples
2. Wrong normalization integrals for plots with component selection of pdfs with numeric normalization integrals
The bug affects for example the user in this forum post: https://root-forum.cern.ch/t/problems-plotting-individual-components-with-roofit-histfactory
Thanks a lot to Veronica for reporting this issue!
=> [RF] Fix bugs in HistFactory component plots

core/metacling/test/TClingLoadUnloadFileTests.cxx
Use correct suffix (`.dll` on Windows and `.so` elsewhere) and test also loading/unloading` in threads
=> Fix TClingLoadUnloadFileTests

hist/hist/src/TScatter.cxx
TScatter::Print crashed if color or size were not defined.
=> [skip-ci] fix TScatter::Print

interpreter/cling/CMakeLists.txt, math/minuit2/CMakeLists.txt
Recent cmake version `3.27.2` makes following warnings:
```
CMake Deprecation Warning at interpreter/cling/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Set in ` interpreter/cling` and `math/minuit2` this minimal version as 3.5 (release in 2018).
Also for cling call `cmake_minimum_required` before calling `project`
=> [cmake] increase minimal required version to 3.5

core/winnt/inc/TWinNTSystem.h, core/winnt/src/TWinNTSystem.cxx
Create a struct holding the flag, `HANDLE`, and `WIN32_FIND_DATA` used by `OpenDirectory`, `GetDirEntry`, and `FreeDirectory`, so each thread creates its own instance of it. This fixes randome failures in mutithreaded applications on Windows, like for example in the `R__USE_IMT` part of the `datasource-root` test:
```
[ RUN      ] TRootTDS.DefineSlotMT
Error in <TFile::TFile>: file C:/root-dev/build/x64/debug/tree/dataframe/test/G__NTupleStruct.vcx does not exist
[       OK ] TRootTDS.DefineSlotMT (191 ms)
[ RUN      ] TRootTDS.FromARDFMT
Error in <TFile::Init>: C:/root-dev/build/x64/debug/tree/dataframe/test/INSTALL.vcxproj not a ROOT file
C:\root-dev\git\master\tree\dataframe\test\datasource_root.cxx(175): error: Expected equality of these values:
29.
Which is: 29
*max
Which is: 23
[ …
```
=> [windows] Make `OpenDirectory` and `GetDirEntry` thread safe

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, tutorials/roofit/rf515_hfJSON.json
In scenarios where a HS3 JSON file without a "misc" field is read, there are some issues in trying to construct a main pdf that could be associated with the ModelConfig.
This PR adds some coping mechanisms to improvise something in case the extra info from the misc field is missing.
Adds code to RooJSONFactoryWSTool::importAnalysis that can either use a non-simultaneous pdf as the pdf of the ModelConfig in cases where there is only one pdf, or create an improvised simultaneous pdf ad-hoc in order to capture the distributions listed under likelihood of the analysis.
=> [RF][HS3] Bugfix for segfault without misc and rewrite constraint term handling

.github/workflows/root-ci.yml
Should fix
```
WARNING:discardable_shared_memory_manager.cc(197)] Less than 64MB of free space in temporary directory for shared memory files: 62
```
and similar errors with headless chromium.
See https://stackoverflow.com/a/56941767
=> [ci] Tell docker to use 1GB /dev/shm: [skip-ci]

CMakeLists.txt, builtins/pcre/CMakeLists.txt, cmake/modules/SearchRootCoreDeps.cmake
If development part of python3/python2 not found, try to find only executable to make ROOT compilation
Also set policy CMP0144 to 'OLD'. With new cmake 3.27 shell variable `JAVA_ROOT` will be used for `find_package(Java...`
To keep ignoring such variables, one should set policy to `OLD`
=> [cmake] find any python3 if PYTHON_EXECUTABLE not specified

core/testsupport/CMakeLists.txt, hist/histdrawv7/test/CMakeLists.txt, roofit/roofitcore/test/TestStatistics/testPlot.cxx, tree/ntuple/v7/test/ntuple_modelext.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
For static libraries, the linker can decide to skip it and not include the contained object files. This defeats the purpose of `TestSupport` which registers a global `ForbidDiagnostics noDiagCheckerInstance` to call `SetErrorHandler` and fail the test if there is an unexpected diagnostic. Object libraries, on the other hand, propagate their files directly and are guaranteed to be included.
Fixes https://github.com/root-project/root/issues/12828
=> Make `ROOT::TestSupport` an `OBJECT` library 

interpreter/cling/include/cling/Interpreter/RuntimeUniverse.h, interpreter/cling/lib/Interpreter/ExternalInterpreterSource.cpp, interpreter/cling/lib/Interpreter/ValueExtractionSynthesizer.cpp
(For context, this is important for multi-dimensional constant arrays as described in [ROOT-7016](https://sft.its.cern.ch/jira/browse/ROOT-7016) and tested in Cling's `Interfaces/evaluate.C` test. But for reasons unknown to me, the ROOT prompt now seems to have a different way of handling this case because just reverting commit https://github.com/root-project/root/commit/d97e4dca36370a1f036026cb6976416670882bc6 still works there...)
Instead of using relying on recursive templated calls, perform the type cast in the `ValueExtractionSynthesizer`. This has the advantage of avoiding an ODR violation warning in `MultipleInterpreters.C` with LLVM 16 (while unclear if that one is correct or not).
=> [cling] Cast to base element type pointer before calling copyArray

interpreter/cling/lib/Interpreter/Interpreter.cpp
We don't need it, and with the upgrade to LLVM 16 the NVPTX target (correctly) errors that there is no (direct) JIT execution support.
=> [cling] Skip IncrementalExecutor for CUDADevice

core/foundation/src/TError.cxx
I had apparently overlooked that in 5455bbc3b5210bb73fffd0c6a3ab8833bf1dbfec.
=> [foundation] Remove leftover `gErrorMutex`:

tree/dataframe/src/RDFHelpers.cxx, tree/dataframe/test/dataframe_helpers.cxx
- make get_tty_size() returning 0 when called without terminal (e.g. when redirecting output)
- check for nonzero return value of `_isatty()`. According to the doc, `_isatty` returns a nonzero value if the descriptor is associated with a character device. Otherwise, `_isatty` returns 0.
- in `dataframe_helpers.cxx`, don't use `f1.root` and `f2.root`, they are already used in `dataframe_nodes.cxx` and might conflict when running tests concurrently
This fixes the following errors on Windows:
```
unknown file: error: C++ exception with description "string too long" thrown in the test body.
[  FAILED  ] RDFHelpers.ProgressHelper_Existence_ST (5009 ms)
[ RUN      ] RDFHelpers.ProgressHelper_Existence_MT
C:\ROOT-CI\src\core\testsupport\src\TestSupport.cxx(77): error: Failed
Received unexpected …
```
=> Fix dataframe helpers on Windows

interpreter/CMakeLists.txt
We see several timeouts when running in coverage mode; this might help. We also really do not care about coverage of interpreter/: there are dedicated test suites that are not run as part of testing ROOT.
=> [ci] Build interpreter/ without coverage:

net/davix/inc/TDavixFile.h
Fixes to TDavixFile documentation when accessing files on Amazon S3.  The options suggested do not work.  Instead the options must be used without the underscore.
e.g. 
"S3_SECKEY" -> "S3SECKEY"
"S3_ACCKEY" -> "S3ACCKEY"
"S3_TOKEN" -> "S3TOKEN"
etc.
You can see the source code here: https://github.com/root-project/root/blob/4e8c577dfd6a19d7c38a74e3074b406a598bf76a/net/davix/src/TDavixFile.cxx#L69
where they are defined without the underscore.
```c
const char* s3_seckey_opt = "s3seckey=";
const char* s3_acckey_opt = "s3acckey=";
const char* s3_region_opt = "s3region=";
const char* s3_token_opt = "s3token=";
const char* s3_alternate_opt = "s3alternate=";
```
For example, this works:
```
const std::string options("S3SECKEY=" + aws_secret_access_key + " " 
+ "S3ACCKEY=" + aws_access_key_id + …
```
=> Correct documentation options for TDavixFile when using Amazon S3

tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/src/RColumn.cxx
As measured, there is an improvement if the expansion of `R__ASSERT()` is out of the inlined code path due to slighly more compact code.
Additionally, the `R__ASSERT(count > 0)` has been removed, given that `ClusterSize_t::ValueType` is an unsigned integral type.
This was seen during the evaluation of the relative overhead of RField's post-read callbacks, which for reference I provide below.
Two different tests were carried out: _(i)_ 4 fields of type `std::uint32_t`; and _(ii)_ 2 fields of type `std::uint32_t` + 2 fields of a user-defined struct, where:
- BASE refers to the current `master` with `RFieldBase::Read()` slightly changed to not support read callbacks.
- [1] refers to the current `master` + the changes in this PR
- [2] refers to the current `master` where …
=> [ntuple] Move `R__ASSERT` out of the inlined code path

core/metacling/src/TCling.cxx
It improves the warnings of ROOT when two identical autoload keys are found for two different libraries. 
This PR fixes #13431
=> Warn on identical autoload keys from two different libraries

roofit/roofitcore/inc/RooAbsData.h, roofit/roofitcore/src/RooAbsData.cxx
In https://github.com/root-project/root/issues/13087, it was noted that `RooAbsData::split()` does not split
observables. However, there is already one overload of this function to
do this, taking a RooSimultaneous as an input to know what the
observables are. This PR improves the docs of `RooAbsData::split()` by
adding a comment that links to this other overload, such that it is
easier to find.
Closes https://github.com/root-project/root/issues/13087.
=> [RF] Improve documentation of `RooAbsData::split()`

core/winnt/inc/TWinNTSystem.h, core/winnt/src/TWinNTSystem.cxx
* [windows] Make `OpenDirectory` and `GetDirEntry` thread safe
Create a struct holding the flag, `HANDLE`, and `WIN32_FIND_DATA` used by `OpenDirectory`, `GetDirEntry`, and `FreeDirectory`, so each thread creates its own instance of it. This fixes randome failures in mutithreaded applications on Windows, like for example in the `R__USE_IMT` part of the `datasource-root` test:
```
[ RUN      ] TRootTDS.DefineSlotMT
Error in <TFile::TFile>: file C:/root-dev/build/x64/debug/tree/dataframe/test/G__NTupleStruct.vcx does not exist
[       OK ] TRootTDS.DefineSlotMT (191 ms)
[ RUN      ] TRootTDS.FromARDFMT
Error in <TFile::Init>: C:/root-dev/build/x64/debug/tree/dataframe/test/INSTALL.vcxproj not a ROOT file
C:\root-dev\git\master\tree\dataframe\test\datasource_root.cxx(175): error: Expected …
```
=> [v6.28][backport][windows] Make `OpenDirectory` and `GetDirEntry` thread safe (#13472)

CMakeLists.txt
Well-known branch names, e.g. `master` or `v6-28-00-patches` always use the equivalent upstream roottest branch.  However, we should be careful not to match a substring.  Concretely, before this patch, `master-14449` was incorrectly taken as a well-known branch causing the error below.
```
Cloning into 'roottest'...
fatal: Remote branch master-13449 not found in upstream origin
CMake Error at CMakeLists.txt:780 (message): Expected roottest at 'C:/ROOT-CI/src/roottest' (not a directory?)
```
=> [cmake] relatedrepo_GetClosestMatch: fix well-known branch regex

README/ReleaseNotes/v630/index.md, core/base/src/TDirectory.cxx, graf2d/gpad/inc/TCanvas.h, graf2d/gpad/src/TCanvas.cxx, gui/webdisplay/src/RWebDisplayHandle.cxx, gui/webgui6/src/TWebCanvas.cxx, io/io/src/TDirectoryFile.cxx, tutorials/graphics/saveall.C
Allows to create images for vector of pads at once.
Using "%d" or "%03d" or any similar printf qualifier one can put image
number into the file name. Like "image%d.png".
Special handling for PDF. If qualifier in PDF file name not specified,
all provided pads will be placed into single PDF document.
Can use normal (default) and web-based image production.
Only if web display is explicitly specified with `root --web`, will run chrome browser. 
For web following formats are supported: "png", "svg", "pdf", "jpg", "jpeg", "webp".
Also extend export into ROOT file - now it is possible to append object to existing ROOT file using "a" option.
Means if "file.root" is specified, all pads will be saved into that single ROOT file.
But if file name includes printf qualifier like "file%d.root", N root …
=> Introduce TCanvas::SaveAll method

tutorials/eve7/event_demo.C, tutorials/eve7/geom_cms.C, ui5/eve7/lib/EveElements.js, ui5/eve7/lib/EveElementsRCore.js
Sets main transparency of REveGeoShapes in three.js and RenderCore viewer.
The change fixes ignored transparency of REveGeoShape.
=> [REve] Propagate transparency of REveGeoShape to the renderer

tmva/pymva/src/RModelParser_Keras.cxx
With the latest tensorflow (2.13) tf.keras.__version__ is not existing anymore, oone needs to use tf.__version__
=> [pymva] Fix retrieving Keras version when using new version of tensorflow

roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/test/test_lib.h
The `if (_normSet)` did not behave as intended, because the `RooAbsPdf::_normSet` member is a TString, and not a `char*`. And TStrings always convert to `true` booleans, even if they are empty. This commit fixes the empty normalization range check by using `TString::IsNull()` instead.
This fix helps to benchmark RooAddPdfs with the new `codegen` backend, because it avoids the creation of unnecessary normalization integrals that codegen can't handle.
This is a follow-up to 74e3099.
=> [RF] Fix to empty `_normSet` check in RooAddPdf createExpectedEventsFunc

roofit/histfactory/test/testHistFactory.cxx, roofit/histfactory/test/testParamHistFunc.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/inc/RooFit/Evaluator.h, roofit/roofitcore/inc/RooFit/TestStatistics/RooUnbinnedL.h, roofit/roofitcore/src/Buffers.cxx, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.h, roofit/roofitcore/src/RooFit/Detail/Buffers.h, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx, roofit/roofitcore/test/testRooDataHist.cxx
As explained in 85c5cb4e3f, it was planned to make the RooFitDriver a public class to greatly improve the developer experience when working on the GPU backend of RooFit. Before, it was only possible to use the GPU backend in the likelihood evaluation, and with this commit it can be used from any context.
This makes it possible to run the script listed in the description of PR #13389.
To be more clear in what the new class does, which is purely focusing on the evaluation of computation graphs, it got renamed from RooFitDriver to `RooFit::Evaluator`.
=> [RF] Rename the RooFitDriver to `RooFit::Evaluator` and make it public

interpreter/cling/lib/Interpreter/DeclUnloader.cpp
This pull request moves helper functions to an anonymous namespace at the beginning of the TU.  **There are no functional changes in this PR**; instead it makes the code more readable.
The follow-up PR, which is the important thing, fixes a number of issues in the handling of instantiation of member functions of templated classes, which should fix https://github.com/root-project/root/issues/10049 and all the issues mentioned there :rocket:.
- Move helper functions to anonymous namespace at the beginning of the TU
- Fix unmatched `#pragma clang diagnostic push`
- Fix wrong indentation in some parts of the file
=> [cling][NFC] Cleanup `DeclUnloader`

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTuple.cxx
- Makes the state transition of a field during its lifetime explicit
- Adds state checks to some of the methods
- Removes `RFieldBase::Flush()`
=> [ntuple] Minor safety improvements to the RField API

roofit/roofitcore/src/RooAddHelpers.cxx, roofit/roofitcore/src/RooAddModel.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/test/testRooAddPdf.cxx
If you add components where each component only depends on a subset of the union set of the observables, the RooAddPdf should understand that the component is uniform in the missing observables. This is validated in a new unit test for both the getVal() interface and evaluation with the RooFit::Evaluator.
To make this work, the projection integrals are evaluated for no specific normalization set in `RooAddPdf::computeBatch()` the supplementary normalization terms are already included in `RooAddPdf::compileForNormSet()` and they should not be double counted.
This commit also makes the RooAddPdf tests less verbose by using more the RooWorkspace.
=> [RF] Avoid double counting norm integrals in RooAddPdf with BatchMode

graf2d/gpad/src/TPad.cxx
When primitive add to the pad via `TObjectt::AppendPad()` method, 
`kMustCleanup` bit is automatically set for that object. 
But when primitives read from the IO buffer,
TH1::Streamer reset `kMustCleanup` in IO.
This has side effect afterwards, when pad is deleted during ROOT shutdown and when pad has same histogram twice in list of primitives.
Replaces #13506
=> Set kMustCleanup bit for all pad primitives when streaming

bindings/tpython/src/TPython.cxx
Two implementations are provided, i.e. for Python versions older than 3.8, for which PEP 587 is not in force, and newer.
Implements TPython::ExecFile for Python 3
- [] updated the docs (if necessary)
This PR fixes #9058
=> [PyROOT][9058] Implement TPython::ExecScript for Python 3

gui/webdisplay/src/RWebWindowsManager.cxx, net/http/src/TCivetweb.cxx, net/http/src/TCivetweb.h
civetweb server creates pre-coinfigured number of threads and this number cannot be change once server running.
Each active websocket consumes one thread, where all communication handling is performed. 
To avoid situation that simple http requests fails just while websockets blocked all threads number of
websocket connection will be limited by 90% of configured threads.
Issue warning message from `TCivetweb.cxx`  when websocket connection refused because of threads number like:
```
Error in <TCivetweb::WebSocketHandler>: Only 2 threads are available, reject connection request for win3. Increase WebGui.HttpThreads parameter in rootrc, now it is 7
```
=> [http] control used threads number, limit websocket connections

math/minuit2/src/CMakeLists.txt
Installing missing header MnMatrixfwd.h when building standalone Minuit2.
=> minuit2: missing header

README/ReleaseNotes/v630/index.md, core/base/inc/TVirtualPad.h, core/gui/inc/TCanvasImp.h, graf2d/gpad/inc/TCanvas.h, graf2d/gpad/inc/TPad.h, graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx, gui/browserv7/src/RBrowserTCanvasWidget.cxx, gui/fitpanelv7/CMakeLists.txt, gui/fitpanelv7/src/RFitPanel.cxx, gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx
It performs asynchronous canvas update.
In case of web-based canvas triggers update of the canvas
on the client side, but does not wait that real update is completed.
Avoids blocking of caller thread.
Have to be used if called from other web-based widget to avoid logical
dead-locks. In case of normal canvas just canvas->Update() is performed.
Use it in `RFitPanel` and `RBrowser`
=> Introduce `TPad::UpdateAsync` method

gui/cefdisplay/src/gui_handler.cxx, tree/dataframe/test/datasource_arrow.cxx
Now CEF uses standard types like `int64_t` instead of `int64`
=> Backport CEF and Arrow fixes [6.28][skip-ci]

README/ReleaseNotes/v630/index.md, roofit/histfactory/test/testHistFactory.cxx, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/src/RooAbsArg.cxx
Fixes a problem where RooFormulaVar instances using the `@1`, `@2` syntax were not properly exported.
Variables referenced by `@N` in the expression of RooFormulaVar or RooGenericPdf are now replaced by the variable names upon export.
=> [RF][HS3] RooFormulaVar at syntax bug

net/netxng/src/TNetXNGFile.cxx
Check if fFile pointer still available
=> Make TNetXNGFile::Close() reentrant [6.28] [skip-ci]

hist/histv7/inc/ROOT/RHistImpl.hxx
Fix issue #13569 `[RHist] variable bins_per_hyperplane is being used without being initialized`
=> [RHist] Fix variable being used without being initialized

roofit/histfactory/inc/RooStats/HistFactory/Detail/HistFactoryImpl.h, roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h, roofit/histfactory/src/HistFactoryImpl.cxx, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/histfactory/test/testHistFactory.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx
* Refactor the original HistFactory code such that pieces can be reused in the HS3 JSON IO implementation
* Fix problems with "reverse engineering" the name of the `ShapeSys` systematics from the ParamHistFunc name
* The `testHistFactory` unit test now validates full JSON roundtripping closure of workspaces with `ShapeSys`, both with Gaussian and Poisson constraints
More details in the commit descriptions
=> [RF] Fix problems with `ShapeSys` support in the HS3 HistFactory implementation

tmva/pymva/test/Classification.C, tmva/rmva/test/Classification.C, tutorials/tmva/TMVAClassification.C, tutorials/tmva/TMVAClassificationCategory.C, tutorials/tmva/TMVACrossValidation.C, tutorials/tmva/TMVACrossValidationRegression.C, tutorials/tmva/tmva003_RReader.C
Use different file names (instead of `TMVA.root` everywhere), to prevent potential conflicts when running the test concurrently. Trying to solve the following kind of error on Windows:
```
SysError in <TFile::TFile>: could not delete C:\ROOT-CI\build\runtutorials\TMVA.root (errno: 13) Permission denied
```
=> [TMVA] Don't use the same file name (`TMVA.root`) everywhere

cmake/modules/CheckCompiler.cmake, cmake/modules/RootBuildOptions.cmake
They were deprecated since commit 82763af605b in 2018 and don't make much sense anymore after ROOT requires C++17.
=> [cmake] Remove deprecated options cxx11/14/17

hist/hist/src/TGraph2D.cxx, hist/histpainter/src/TGraph2DPainter.cxx
This Pull request fixes this issue:
https://github.com/root-project/root/issues/13424
Along the Z axis, there was no check to drop, at drawing time, the triangles having at least one vertex smaller than the minimum of the underlying histogram or greater than the maximum of the underlying histogram. This produced the artifacts reported in the issue. Also, The minimum and maximum of the underlying histogram might be respectively bigger or smaller than the real minimum and maximum of the points. A fix is done also for that too.
=> The TRI1/2 TGraph2D options produced artifacts.

core/base/src/Stringio.cxx
Apply changes suggested in the `Notes` section of the `isspace` [C++ standard](https://en.cppreference.com/w/cpp/string/byte/isspace) This fixes the following error when reading the character `'ò' (-14 )` in stressgraphics:
```
Debug Assertion Failed!
Program:
C:\root-dev\build\x86\debug_test\test\Debug\stressGraphics.exe
File: minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp
Line 36
Expression c > = -1 && c < = 255
```
From `isspace((Int_t)c)`, in `core\base\src\Stringio.cxx`, in `std::istream& TString::ReadToken(std::istream& strm)`:
```
while ((wid == 0 || Length() < (Int_t)wid) &&
strm.get(c).good() && (hitSpace = isspace((Int_t)c)) == 0) {
```
=> Fix a debug assertion failure on Windows when running stressgraphics

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx
Instead of aborting after `R__ASSERT` fails, a proper exception is now thrown when the `RNTupleInspector` detects inconsistent compression across columns or clusters.
Additionally, this PR improves the documentation related to this.
N.B. Because at this point there is no way to have different compression across columns or clusters, no tests for checking this assumption have been added yet. When at one point this becomes possible, this should obviously be added.
=> [ntuple] Throw when `RNTupleInspector` encounters inconsistent compression

.github/workflows/root-ci-config/build_root.py
Ninja shows dependency issues in our build system; fix those first before switching to Ninja.
This reverts commit fcfca4ccdaf97099a180e154c60bc3c621abfafe.
=> Revert "[ci] Use Ninja as build system everywhere but Windows." [skip-ci]

interpreter/CMakeLists.txt
This was naturally available before commit 92807f3591 from LLVM's configuration file.
Fixes #13597
=> [interpreter] Add builtin_llvm's CMake modules

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph.py, bindings/pyroot/pythonizations/test/tgraph_getters.py
Extend the regex passed to 'compose_method' to include 'E*(low,high)[d]' getters.
Fixes #13600
=> Extend Pythonization of TGraph* getters

bindings/experimental/distrdf/python/DistRDF/Operation.py, tree/dataframe/inc/LinkDef.h
GraphAsymmErrors was missing from the list of allowed operations for DistRDF
This PR fixes #13588
=> Add GraphAsymmErrors to DistRDF operations

bindings/pyroot/pythonizations/test/sofie_gnn.py
This PR increases the tolerance for SOFIE-GNN testing. Due to different floating representations in Python frameworks and C++ implementations, it will be better to have a tolerance of 10^-5 and not 10^-7 which was the default previously.
=> [tmva][sofie-gnn] Increase tolerance for sofie-gnn tests

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py, bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
=> [RF][PyROOT] Fix `RooDataSet.from_numpy()` for contiguous input arrays

tree/ntuple/v7/src/RField.cxx
For RVecs of simple types, do a vector read of the item's principal columns instead of reading items one by one.
=> [ntuple] Speed up reading/writing of simple vectors

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_batchgenerator.py, core/meta/src/TFunction.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TClingMethodInfo.cxx, core/metacling/src/TClingTypeInfo.cxx, tutorials/CMakeLists.txt
Attempting to improve the situation regarding segfaults seen in the RBatchGenerator tutorials. Generally, the situation triggering the segfaults is:
1. Main process is running Python code
2. Spawns a C++ thread, which runs RDataFrame code
3. Main thread will call into the interpreter via cppyy
4. Data races happen
UPDATE:
The commits were update after discussion with @pcanal. The general strategy is to write the locks further deep in the call chain when possible (e.g. in the context of this PR, `TFunction` is a higher-level class than `TClingMethodInfo`, so the locks are better placed in the latter).
=> Increase thread safety to fix RBatchGenerator tutorials segfaults

tree/dataframe/test/CMakeLists.txt, tree/dataframe/test/dataframe_concurrency.cxx, tree/dataframe/test/dataframe_helpers.cxx, tree/dataframe/test/dataframe_simple.cxx
Reduce duration of DF unit tests, eliminating jitting in favor of compilation where possible and optimizing obvious parameters, all without loosing any coverage.
The df battery of unit tests now runs a few minutes faster than before.
=> [DF] Shorten RDF unit tests

bindings/pyroot/pythonizations/test/dependency_versions.py
The `report` attribute is not present in all types of errors, as seen in e.g. https://lcgapp-services.cern.ch/root-jenkins/job/root-pullrequests-build/184277/testReport/projectroot.bindings.pyroot.pythonizations/test/pyunittests_pyroot_dependency_versions/
=> [build] Format error as string in dependency_versions.py test

tree/dataframe/src/RLoopManager.cxx, tree/dataframe/test/dataframe_helpers.cxx
Exceptions thrown in an event loop are caught to print a message. This catch block is leveraged to finalize all scheduled actions in order to properly deallocate memory where needed and save the partial results which are obtained.
Is work in progress and lacks a test battery
Allows to finalize actions scheduled in a RDF analysis in case an exception is thrown during the event loop.
- [V] tested changes locally
This PR fixes #10484
=> [DF][10484] Finalize actions if an exception occurs during evt loop

roofit/batchcompute/src/RooBatchCompute.cu
The number of thread blocks in kernel calls should not be excessively large, it's sufficient if it's in the order of the number of streaming multiprocessors.
In particular, this circumvents a problem with the NLL reduction kernels with grid sizes larger than 512.
With this change, there are potentially less threads than events when summing likelihoods, so in the NLL reduction kernels, each thread also has to reduce a few elements in a loop.
Closes #13603.
=> [RF] Limit maximum number of thread blocks in RooFit CUDA code

roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooGlobalFunc.cxx
There are different overloads of `RooFit::Import()` for importing different object types to RooFit dataset classes.
However, they return a `RooCmdArg` that is named after the type of the imported object. That causes some inconsistencies. For example, if you import a map of `std::unique_ptr<RooDataHist>`, the name will be different than for `RooDataHist*` because there is a special overload for the latter.
It is better to fixup this inconsistency, and then disentangle the different types in the functions that consume these `RooFit::Import()` command arguments.
This caused some trouble when importing RooDataHists into a combined dataset, which is why this fix is coming now.
These changes are covered by the tutorial tests.
=> [RF] Consistent RooCmdArg names for all `RooFit::Import()` overloads

roofit/roofitcore/inc/RooClassFactory.h, roofit/roofitcore/src/RooClassFactory.cxx
1. Reduce code duplication
2. Support expressions with complex numbers, as generated by `sympy` for example
3. Use `std::string` instead of C-style strings
4. Don't recompile when requesting the same class instance twice (to better support jupyter notebook workflows)
=> [RF] Several improvements to RooClassFactory

bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx, gui/browserv7/src/RBrowser.cxx, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx, gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowWSHandler.hxx, gui/webdisplay/src/RWebWindowsManager.cxx, gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, net/http/inc/THttpServer.h, net/http/src/THttpServer.cxx
pyROOT uses special thread for events processing, where `gSystem->ProcessEvents()` are called.
Both in script and interactive mode.
Problem that thread id is not known from beginning and changing once when running python in script mode.
Therefore special mode is now implemented, which simply uses `gSystem->ProcessEvents()` calls to allow processing
of web-windows communication. RWebWindow simply "trust" that ProcessEvents will not be called concurrently.
Also improve timeout handling in THttpServer and in TWebCanvas. Both using special timers to process their events.
While it is not always possible `TurnOn/TurnOff` timers (it fails from inside timeout handler), just increase/decrease timeout interval, but always let run timer.
=> [webgui] correctly use python processing thread in web widgets

roofit/roofitcore/src/RooGlobalFunc.cxx, tutorials/roofit/rf501_simultaneouspdf.C, tutorials/roofit/rf501_simultaneouspdf.py
Also, throw an exception with a helpful error message if the user attempts to use `RooFit::Slice()` with a comma-separates list of category states, which is not supported.
This addresses a question on the forum:
https://root-forum.cern.ch/t/plotting-two-categories-of-simultaneous-fit-in-a-single-plot/56250
=> [RF] Give example for multiple categories plot in rf501_simultaneouspdf

bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
The `n_in_range` reference value in the unit test
`roodataset_numpy.TestRooDataSetNumpy.test_ignoring_out_of_range` apparently doesn't get computed right on some 32 platforms.
I can't reproduce the problem, but I'm sure it will be fixed by avoiding the use of the operators `&` and `|` with numpy arrays. Just doing a manual loop in Python should be more platform independent.
Closes #12162.
=> [RF][PyROOT] Avoid boolean operators on numpy arrays in unit test

net/net/src/TNetFile.cxx
which is `root/net/net/src/TNetFile.cxx:19:29: warning: '/*' within block comment [-Wcomment]` on clang on macos 13.5.1
=> [Doc] Reformulate Doxy doc not to trigger a compiler warning

math/mathcore/CMakeLists.txt, math/mathcore/inc/Fit/ParameterSettings.h, math/mathcore/inc/Math/IOptions.h, math/mathcore/inc/Math/Minimizer.h, math/mathcore/src/IOptions.cxx, math/mathcore/src/Minimizer.cxx, math/mathcore/src/ParameterSettings.cxx, math/minuit2/src/Minuit2Minimizer.cxx, math/minuit2/src/math/CMakeLists.txt, roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodWrapper.h
The "Math/Error.h" header is not shipped with standalone Minuit2.
It is not a perfect solution to just ship it with Minuit2, because the Error.h header behaves differently depending on the `MATHCORE_STANDALONE` macro being defined or not. The code would only work correctly if the user defines the `MATHCORE_STANDALONE` herself in the user code that uses standalone Minuit2, which would be annoying.
Instead, this commit proposes another solution to the problem: for all headers also used in Minuit2 standalone, MathCore
moves the definitions of all functions that use `Math/Error.h` out of the header files in the cxx files. Like this, the `Math/Error.h` is only a build dependency of standalone Minuit2, and the user doesn't need to define the `MATHCORE_STANDALONE` macro for it to work.
Including …
=> [math] Don't `#include "Math/Error.h"` and `"Math/Util.h"` in Minuit2 headers

roofit/roofitcore/inc/RooAbsOptTestStatistic.h, roofit/roofitcore/inc/RooAbsTestStatistic.h, roofit/roofitcore/src/RooAbsOptTestStatistic.cxx, roofit/roofitcore/src/RooAbsTestStatistic.cxx, roofit/roofitcore/src/RooChi2Var.cxx, roofit/roofitcore/src/RooDataWeightedAverage.cxx, roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooXYChi2Var.cxx
There was an evil hack in `RooAbsOptTestStatistic`:
```c++
_dataClone->cacheArgs(this,_cachedNodes,_normSet,!_funcClone->getAttribute("BinnedLikelihood")) ;
```
The final parameter determins if zero weights should be skipped when recalculating the caches. Indeed, for the NLL case, this corresponds to the BinnedLikelihood attrribute being present or not, but it broke the other test statistics for which zero weights should not be skipped at all.
This commit suggests a safer way to manage this with a new `RooAbOptTestStatistic::_skipZeroWeights` flag.
In particular, this change fixed a bug that got uncovered during a forum discussion:
https://root-forum.cern.ch/t/failing-chi2-fit/56309/3
=> [RF] Fix skipping of zero weights in tests statistic caching

README/ReleaseNotes/v630/index.md, roofit/batchcompute/README.md, roofit/batchcompute/res/RooHeterogeneousMath.h, roofit/batchcompute/src/Batches.h, roofit/batchcompute/src/ComputeFunctions.cxx, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooAbsReal.h, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAbsRealLValue.cxx, roofit/roofitcore/src/RooChi2Var.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooErrorVar.cxx, roofit/roofitcore/src/RooFactoryWSTool.cxx, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooPlot.cxx, roofit/roofitcore/src/RooWorkspace.cxx, roofit/roofitcore/src/TestStatistics/buildLikelihood.cxx
It is confusing to the users that the chi2 fit is by default not extended, even if the pdf is extended. Because this is what happens in normal likelihood fits.
This commit makes that behavior consistent and explains it in the release notes.
Also, a new error message is added for the case you forcing a non extended fit on a pdf that must be extended, because this is guaranteed to give wrong results.
This change addresses the confusion on the forum:
https://root-forum.cern.ch/t/failing-chi2-fit/56309
=> [RF] Make extended fit default of RooAbsPdf::fitChi2() same as in fitTo

bindings/jupyroot/python/JupyROOT/helpers/utils.py
Use GetCanvasWidth()/GetCanvasHeight() for obtain proper dimension 
Do not swap width/height arguments
Use correspondent JSROOT release
=> [ipython] fix canvas width/height usage [6.28]

cmake/modules/FindOracle.cmake
Nicer to distribute a BSD licensed version.
The file `COPYING-CMAKE-SCRIPTS` is missing virtually worldwide, not even CMake includes it: https://gitlab.kitware.com/search?search=COPYING-CMAKE-SCRIPTS&nav_source=navbar&project_id=541&group_id=415&search_code=true&repository_ref=master
=> [cmake] Replace FindOracle.cmake:

tutorials/hist/histpalettecolor.C
=> Fixing a typo in histpalettecolor.C

js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/base/TAttFillHandler.mjs, js/modules/core.mjs, js/modules/draw/more.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TGraphPainter.mjs
1. TText/TLatex scaling to pad size
2. Handle TAxis with ndiv = 0
3. TGraph B draw option - proper bar width
4. Correctly use fixed label font size in TLegend, not always autoscale
5. Adjust columns width in TLegend to content
6. Correctly store/restore defs with fill patterns when producing screenshot 
This PR fixes #13693
=> [jsroot] dev 21/09/2023 with fixes [skip-ci]

hist/hist/inc/TGraph.h, hist/hist/inc/TGraphAsymmErrors.h, hist/hist/inc/TGraphBentErrors.h, hist/hist/inc/TGraphErrors.h, hist/hist/inc/TGraphMultiErrors.h, hist/hist/src/TGraph.cxx, hist/hist/src/TGraphAsymmErrors.cxx, hist/hist/src/TGraphBentErrors.cxx, hist/hist/src/TGraphErrors.cxx, hist/hist/src/TGraphMultiErrors.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_TGraph_sorting.cxx
Reimplement the TGraph::Sort function using std::sort to avoid a segmentation fault when used with a large number of entries.
It's also faster, ex. for a `10000 points`:
```
BEFORE CHANGES -> Sort execution time: 148100 microseconds
AFTER CHANGES -> Sort execution time: 7065 microseconds
```
This PR fixes #13632
=> Reimplement TGraph::Sort using std::stable_sort

tutorials/CMakeLists.txt
if imt is not specified, this tutorial should not be run as a test.
Avoids running the `TMVA_CNN_Classification.C` when ROOT is not built with imt, since it is a requirement and trying to proceed nevertheless causes errors.
=> [TMVA] Do not run CNN tutorial if imt not specified

cmake/modules/RootConfiguration.cmake
Failure to install ROOT because root-help.el was removed in f4f8133607572b862998fcecf5efb9dba5402eb6
=> [config] remove install of removed root-help.el

hist/hist/inc/TGraphSmooth.h, hist/hist/src/TGraphSmooth.cxx
After consultation with Christian Stratowa, the intent was to use the same license as that of ROOT. Given the commit 041f9ed55290e7edcfd78a15dfcd3c0eb7b8c9fc which sets the (c) to Fons+Rene, the copyright for Christian must end around that time that Christian has donated the code to Fons&Rene. Use consistent header for .h and .cxx.
=> [hist] Fix license for TGraphSmooth (NFC): [skip-ci]

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds the functionality to print per-column type information for a given RNTuple. Output can be formatted in both a text-based table as well as CSV (and may be extended with more formats where desired).
For an RNTuple with 75 rows each containing one [ComplexStructUtil](https://github.com/root-project/root/blob/3acc0e601bd74ffd876c755069e8e989d922521c/tree/ntupleutil/v7/test/CustomStructUtil.hxx#L36) field, the default (table-formatted) output is as follows:
```
root [1] inspector->PrintColumnTypeInfo()
column type    | count   | # elements      | bytes on disk   | bytes in memory
----------------|---------|-----------------|-----------------|-----------------
SplitIndex64 |       2 |             150 |              72 |            1200 
SplitReal32 |       4 |             300 | …
```
=> [ntuple] Add `PrintColumnTypeInfo` to `RNTupleInspector`

interpreter/llvm/src/tools/clang/lib/Sema/SemaExpr.cpp
This is an adaptation of commit 6627da727b88ef70b74b7d87f274e0a21a9cea45 Fixes https://github.com/root-project/root/issues/13698, a problem with the new C++ headers from the new macOS SDK.
Unfortunately the directory structure of our llvm changed, and it was not possible to cherry-pick.
This PR fixes #13698
=> [LLVM] Backport commit

roofit/histfactory/test/testHistFactory.cxx, roofit/hs3/src/HistFactoryJSONTool.cxx, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx
The HistFactory JSON IO had some problems with models that were produced prior to ROOT 6.26, e.g., prior to this PR:
https://github.com/root-project/root/pull/8167
In particular, the problem was that the JSON export assumed that the multiplication with the inverse bin width as always done with the RooBinWidthFunction.
Also, the first commits in this PR makes sure that the `BinnedLikelihood` attribute is correctly preserved by the JSON IO.
=> [RF][HS3] Fix JSON import of older HistFactory models

roofit/histfactory/inc/LinkDef.h
This completes the list of LinkDef entries for the classes in `RooStats/HistFactory/Systematics.h`.
Backport of https://github.com/root-project/root/pull/12969.
=> [v628][RF][HF] Add missing LinkDefs for systematics classes in HistFactory

geom/geombuilder/src/TGeoBBoxEditor.cxx, geom/geombuilder/src/TGeoManagerEditor.cxx, geom/geombuilder/src/TGeoMaterialEditor.cxx, geom/geombuilder/src/TGeoMatrixEditor.cxx, geom/geombuilder/src/TGeoMediumEditor.cxx, geom/geombuilder/src/TGeoSphereEditor.cxx, geom/geombuilder/src/TGeoTabManager.cxx, geom/geombuilder/src/TGeoTrd1Editor.cxx, geom/geombuilder/src/TGeoTrd2Editor.cxx, graf3d/eve/src/TEveProjectionAxesEditor.cxx, graf3d/eve/src/TEveTrackEditor.cxx, graf3d/eve/src/TEveTrackPropagatorEditor.cxx, gui/ged/src/TH1Editor.cxx, gui/ged/src/TH2Editor.cxx, math/mathcore/inc/Math/Types.h
Backport two PRs to fix warnings about enum comparisons in the nightlies:
* https://github.com/root-project/root/pull/13360
* https://github.com/root-project/root/pull/13082
The warnings can be seen here:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-v6-28-00-patches/LABEL=ROOT-ubuntu2204,SPEC=cxx20,V=6-28/lastBuild/parsed_console/
=> [v628] Backports to fix warnings about enum comparisons in the nightlies

graf2d/gpad/src/TPad.cxx, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/draw/TASImagePainter.mjs, js/modules/draw/TSplinePainter.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TGraphTimePainter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/TMultiGraphPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/hist2d/TMultiGraphPainter.mjs, js/modules/hist2d/TScatterPainter.mjs, ui5/canv/controller/Canvas.controller.js, ui5/canv/view/Canvas.view.xml
1. Do not draw hist title when "AXIS" option is used; do not create title in TWebCanvas
2. Use factor 0.66666 when draw custom axis labels.
3. Correctly position axis labels - extra offset as in ROOT
4. If there are many frames on the pad - only one with axes drawing will be interactive
5. Copy Z axis attributes to color palette - labels offset, colors and so on 
Fixes #13719 
Fixes #13707
=> [webcanvas] several fixes for axis and palette drawing [skip-ci]

math/minuit2/src/SimplexBuilder.cxx
=> [bugfix] Update SimplexBuilder.cxx to fix #6775

tutorials/CMakeLists.txt
Prevent running xml tests when xml is disabled, suppressing the following test failures:
```
TEST FAILURES:
971:tutorial-xml-DOMParsePerson
972:tutorial-xml-DOMRecursive
973:tutorial-xml-SAXHandler
```
=> Append to the `xml_veto` list instead of (re-)creating it

bindings/pyroot/pythonizations/python/ROOT/_application.py, gui/webdisplay/src/RWebWindow.cxx, net/http/src/THttpServer.cxx
First of all, make handling for Mac and Linux similar.
In non-interactive mode run special thread where `gSystem->ProcessEvents()` are called.
In interactive mode try to use input hook.
In webgui in python non-interactive mode allow to use calling thread for callbacks invocation. 
It is the only chance to get processing of http requests from clients.
Probably fixes #13744
=> [pyroot] adjust GUI events processing

cmake/modules/SearchInstalledSoftware.cmake
With this change, the reproducer provided in #12631 works for me, while it indeed fails to find `xrootd` in the configuration step without this commit.
See:
https://github.com/xrootd/xrootd/blob/master/cmake/XRootDConfig.cmake.in
Closes #12631.
=> [CMake] Use `find_package(XRootD)` and not `XROOTD` (case sensitivity)

geom/vecgeom/CMakeLists.txt
The `-fabi-version=6` flag was added to the compilation of
`geom/vecgeom` in https://github.com/guitargeek/root/commit/ded69d0daad299f528fb172a0e922215ac18615b without any explanation.
But recently, it caused some compilation problems with `std::unique-ptr`
in newer GCC versions.
Simple reproducer:
```c++
#include <memory>
int main() { std::unique_ptr<int>(nullptr); }
```
Compile with `g++ -fabi-version=6 -o test test.cpp`, using GCC 13.2.
So the implementation of `std::unique_ptr` in the standard library
version that comes with gcc 13.2.1 is incompatible with that (super old)
gcc abi version.
Since it's not clear why this flag is there to begin with, I suggest to
remove it so it doesn't cause further problems.
The ABI version 6 is very old anyway (it came with GCC 4.7 in 2012).
Closes …
=> [geom] Don't use `-fabi-version=6` when compiling geom/vecgeom with GCC 

CMakeLists.txt, cmake/modules/RootConfiguration.cmake, cmake/modules/SearchInstalledSoftware.cmake, cmake/scripts/ROOTConfig.cmake.in, math/vecops/CMakeLists.txt, roofit/batchcompute/CMakeLists.txt, test/CMakeLists.txt, tmva/tmva/CMakeLists.txt
Simplified/fixed how VDT would be used. Did this by making `ROOTVecOps`, `RooBatchCompute` and `TMVA` link against `VDT::VDT` in all circumstances (as long as VDT is being used). Regardless of whether VDT is used as a "builtin" or as an "external". At the same time made `ROOTVecOps` and `RooBatchCompute` depend on `VDT::VDT` publicly, as they actually do.
- Made sure that an imported `VDT::VDT` library would be set up when `builtin_vdt` is being used.
- Simplified how `ROOTVecOps`, `RooBatchCompute` and `TMVA` would just (publicly) link against `VDT::VDT` if either `vdt` or `builtin_vdt` is `TRUE`. Instead of the spaghetti of options that it had before.
- Made sure that all of those targets would explicitly depend on the `VDT` target if `builtin_vdt` is set to `TRUE`.
- Made sure that VDT …
=> VDT Usage Fix, master branch (2022.12.06.)

bindings/pyroot/pythonizations/python/ROOT/_application.py
This revert is in place because python scripts now hang whenever the ROOT module is imported on macos 12, 13 and 14.
This reverts commit 06b86c3a3408fec00eaa615790a9298bb9b7eb41.
=> 🚨  Revert "[pyroot] make Mac and Linux events handling similar"

build/unix/compiledata.sh
The generated compiler invocation in TSystem::CompileMacro doesn't add the `-rpath` option. The output of `root-config --libs` contains that option on MacOS, so we should also have it here. This should fix errors seen in MacOS 14 when loading a shared library obtained via ACLiC.
Fixes #13734
=> [core] Add rpath on MacOS when compiling shared libraries via ACLiC

core/rint/src/TRint.cxx
Just updates the banner shown when booting the command line interpreter.
- [V] tested changes locally
=> [Core] Update year in the ROOT banner

builtins/lz4/CMakeLists.txt, builtins/zstd/CMakeLists.txt
This PR is a WIP and has been posted to collect feedback.
It proposes a fix for warnings on MacOS which are prompted when linking the libCore shared library due to two links to libxxHash, which are there only if xxhash and lz4 are builtins.
This seems to be a non trivial CMake problem, which is fixed with some perhaps non-hortodox CMake code.
=> [CMake] Fix warning about xxhash linked more than once when building libCore.

bindings/pyroot/pythonizations/python/ROOT/_facade.py, bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py
The RDF FromNumpy was silently reading wrong values if sliced arrays (arrays with strides) were given as an input. This PR fixes the issue by producing copies of the sliced arrays that are then read correctly. 
TODO for the future: a neater solution, without making copies. 
This PR fixes #13690
=> [DF] Fix RDataFrame FromNumpy wrong reading of values from sliced arrays

tmva/tmva/CMakeLists.txt, tmva/tmva/inc/LinkDef1.h, tmva/tmva/inc/LinkDefUtils.h, tutorials/CMakeLists.txt
This PR removes the dependency of libTMVA from libROOTDataFrame. 
The dependency is needed only for the test programs. 
This should fix the conflict seen when loading PyTorch models on some architectures. See https://github.com/root-project/root/pull/13674#issuecomment-1733208800 
In addition the PR veto some Keras tutorials which time-out on macOS due to need to keep eager execution on MacOS
(see https://github.com/root-project/root/pull/13634/commits/e1d2ed4a937e546d197a1c1c026c17f671a16bcc )
=> [tmva] Fix dependency of libTMVA from 

builtins/lz4/CMakeLists.txt, builtins/zstd/CMakeLists.txt
of the libxxhash.a library when building libCore.so
=> [Backport][CMake] Remove N-1 identical link statements

cmake/modules/RootMacros.cmake
ninja rightfully said:
```
ninja explain: output core/newdelete/move_header_core_newdelete of phony edge with no inputs doesn't exist
ninja explain: core/newdelete/move_header_core_newdelete is dirty
ninja explain: move_headers is dirty
```
which likely triggered MSBUILD to re-run the move-headers target (during roottest). This might fix it, and in general gets rid of useless "rebuilds" of move_headers.
=> [cmake] Only add a move_header_XYZ target if there are headers:

hist/hbook/src/THbookFile.cxx
This will fix some warnings seen in the nightlies: https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-asan/lastBuild/LABEL=ROOT-centos8,SPEC=asan,V=master/parsed_console/
Commented out and not removed because there is some TODO in that file related to these variables (although it's probably obsolete).
=> [hist] Comment out unused variables in `THbookFile.cxx`

tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/src/RModelParser_PyTorch.cxx, tmva/pymva/test/CMakeLists.txt, tmva/tmva/CMakeLists.txt, tmva/tmva/inc/LinkDef1.h, tmva/tmva/inc/LinkDefUtils.h, tutorials/CMakeLists.txt
Backporting some PRs to avoid test failures in the nightlies:
* https://github.com/root-project/root/pull/12693
* https://github.com/root-project/root/pull/13712
* https://github.com/root-project/root/pull/13718
* https://github.com/root-project/root/pull/13765
* https://github.com/root-project/root/pull/13524
* https://github.com/root-project/root/pull/13525
* https://github.com/root-project/root/pull/13613
After these trivial backports, the only PR that needs to be backported to fix the remaining failures is this one:
* https://github.com/root-project/root/pull/13533
However, this would not be a simple conflict-less backport because the changes interact with new feature development for ROOT 6.30. It's maybe better if @lmoneta takes care of this.
=> [v628] Backports to fix TMVA nightly errors

core/zip/inc/Compression.h, core/zip/src/Compression.cxx, tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds a new `RNTupleInspector` method that returns the compression settings as a string next to the internal integer representation.
The format of the string is "`A` (level `L`)", where `A` is the name of the compression algorithm and `L` the compression level.
=> [ntuple] Add `GetCompressionSettingsAsString()` to inspector

tmva/tmva/test/rreader.cxx
Delete the `TFile` pointers, preventing a potential crash in `TROOT::CloseFiles()` when trying to call the `Close()` method on `TWebSocket`/`TWebFile` via the interpreter `CallFunc_Exec` on Windows (visible with LLVM 16)
=> Fix potential crash of the rreader test on Windows

tree/dataframe/CMakeLists.txt
This is just a quickfix PR to add the header to the library generation (before it worked due to transitive inclusion in `RInterface.hxx`). In a followup PR I will propose a way to automatise this and avoid further cases
=> Add RDefinePerSample to CMakeLists.txt

documentation/doxygen/ROOT.css
The "legacy code" boxes were not readable in dark mode (tanks @eguiraud to have seen it).
=> [skip-ci] make sure the legacy box is readable in dark mode.

net/net/inc/TWebFile.h, net/net/src/TWebFile.cxx
This is needed to properly close and delete the socket when closing the file in `TROOT::CloseFiles()`, preventing a potential issue when trying to close the socket afterwards
=> Add the `TWebFile::Close(Option_t *option)` method

tree/dataframe/src/RLoopManager.cxx, tree/dataframe/test/dataframe_cloning.cxx, tree/dataframe/test/dataframe_definepersample.cxx
This PR fixes https://github.com/root-project/root/issues/12043 . It should also address sporadic failures seen in our jenkins CI due to sometimes Dask assigning two tasks to the same worker process, thus the second task using the same DefinePerSample node of the first task and collapsing into the same situation as the linked issue.
The first commit contains the actual fix, then tests.
=> Fix interactions in RDF machinery with the DefinePerSample operation

interpreter/cling/test/CodeGeneration/const.C, interpreter/llvm/src/lib/ExecutionEngine/Orc/LLJIT.cpp, interpreter/llvm/src/tools/clang/lib/AST/ASTContext.cpp
Otherwise they are emitted as internal and we get double-construction and -destruction on the same memory address due to the way we promote internal declarations in KeepLocalGVPass.
According to upstream tests, the de-duplication doesn't work on Windows (yet), but I think this problem is severe enough to fix it on the other platforms sooner rather than later.
Fixes #13429, backport of https://github.com/root-project/root/pull/13614
=> [cling] Emit const variables only once [v6.28]

bindings/jupyroot/python/JupyROOT/helpers/utils.py
Addresses forum post:
https://root-forum.cern.ch/t/disable-jsroot-in-jupyter-notebook/56581/
=> [jupyter] correctly handle %jsroot off command

tree/ntupleutil/CMakeLists.txt, tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds the feature to get a histogram representing different possible column type-related properties. These properties are the type count, number of elements per type, compressed size per type and uncompressed size per type.
The current version automatically sets the histogram title based on the information it shows. The title can be changed after returning it using `TH1::SetTitle`. An alternative could be to add another argument which has the default value that is currently used but can be used to provided an alternative title.
=> [ntuple] Add `GetColumnTypeInfoAsHist` to `RNTupleInspector`

bindings/pyroot/pythonizations/python/ROOT/_facade.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
Removes invocations to the root-config executable at *ROOT module import time*. The executable `root-config` was invoked twice to check if RDataFrame was available. Such a behaviour causes a severe slowdown, especially on cvmfs. This has been replaced by a simple string comparison, which is fast and which has no impact in terms of memory (as a query to the type system would have caused with modules),
More in general, this simple PR could be considered as the first of a series to reduce the time needed to `import ROOT` as much as possible.
=> [PyROOT] Speedup inclusion of ROOT module

roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h
I haven't restored the coefficient caching at this time, however. The new interpolation is put in interpCode=5. Added option to use PiecewiseInterpolation with interpCode=5 which correspondings to FIV InterpCode=4 (confusing, I know!)
=> [RF] Restore FlexibleInterpVar interpolation for interpCode=4

math/mathcore/inc/Fit/FitUtil.h, math/mathcore/inc/Math/Types.h, roofit/batchcompute/inc/RooBatchCompute.h, roofit/batchcompute/src/RooBatchCompute.cu, roofit/batchcompute/src/RooBatchCompute.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx
There was a problem in the `IntegralEvaluator` class in the FitUtils.h
in case veccore and vc is used. To evaluate the integral, some input
doubles `x` need to be transferred each of them into a different
`ROOT::Double_v` to call the underlying function.
However, the `ROOT::Double_v` can't load just a single double. Calling
the `Load()` function should be done with a pointer to a `double *`
arrary that is large enough to hold as many doubles as the
`ROOT::Double_v` for SIMD instructions.
If you use pointers to single doubles anyway, then you get rightly and
out-of-bounds warning.
This commits suggests to get gid of this problem by first transferring
the doubles to the beginning of temporary buffers of the right size, and
then passing these buffers to `vecCore::Load()`.
Furthermore, I …
=> [math] Avoid out-of-bounds array access with `vc` in FitUtil.h

tmva/pymva/src/MethodPyKeras.cxx, tmva/pymva/src/PyMethodBase.cxx, tmva/tmva/src/DataSetInfo.cxx, tmva/tmva/src/MethodBase.cxx
This PR fixes backports the fix to keep eager execution on macOS to avoid multi-processing issue that gives timeout of tests
=> Backport in 6.28 fixes in pymva to avoid timeout in keras tests

tree/ntuple/v7/inc/ROOT/RField.hxx
Adds a method to drop ownership of the object pointer in RValue. That is useful for framework code that uses RNTuple to construct an object and would then want to decouple that object from the RValue class.
=> [ntuple] add RFieldBase::RValue::Release()

bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.cxx, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.h
The changes in the commits are taken from upstream. Each commit references the upstream commit(s) that were needed to implement those changes. This should fix #13410 and hopefully not provoke other test failures
=> Cppyy fix derived overload visibility

cmake/modules/SearchInstalledSoftware.cmake
bumps the version of built-in Vc to 1.4.4 which does not use any more the deprecated std::iterator in favour of traits.
This PR fixes warnings on Fedora
=> [CMake] Update Vc version to 1.4.4

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
The comment in the code snippet mentions a column "x", but this is not reflected in the call to `Aggregate`.
=> [DF][NFC] Add missing column name in Aggregate code example

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
to fix warnings due to an unused variable in non-debug builds.
compilation warnings of TMVA
=> [TMVA] Use R__ASSERT instead of assert

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
to avoid warnings about unused variable. This is possible because in master c++17 is enforced.
=> [TMVA] Annotate variable with [[maybe_unused]]

roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h, roofit/roofitcore/inc/RooFuncWrapper.h, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooClassFactory.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooRealIntegral.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
This also includes rudimentary support for numeric integrals in 1D with
the codegen backend as a demonstrator.
A second commit cleans up the `RooFuncWrapper` class a little bit.
A unit test that fits a 1D function created with the RooClassFactory using `codegen` is also added.
=> [RF] Support PDFs produced by `RooClassFactory` in codegen + AD

tutorials/CMakeLists.txt, tutorials/tmva/TMVA_CNN_Classification.C, tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/TMVA_RNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.py
Speed-up CNN and RNN tutorials in TMVA (use less epochs) and add some fixes for IMT and to not use root-config in the python versions. 
Add also a dependency in the Python tutorials on the C++ to avoid conflicts with the same file name.
Remove not needed veto for the no-imt case for the TMVA_CNN_Classification.C tutorial introduced in #13712
=> [tmva] Improve CNN and RNN tutorials

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
This PR implements the same functionality of https://github.com/root-project/root/pull/13835, but without using cpp17 functionality.
=> [TMVA] Work around warning about unused variables

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
BP of https://github.com/root-project/root/pull/13835 . The usage of the annotation is possible since for 6.30 cpp17 is enforced.
=> [Backport][TMVA] Fix unused variable warnings

core/thread/inc/ROOT/RConcurrentHashColl.hxx, core/thread/src/RConcurrentHashColl.cxx, io/io/inc/TFile.h, io/io/src/TFile.cxx
Fix #12783
Since "66dfb08bd7 - [IO] Do not process the streamerinfo record of a file if we read the si already read"
which was extended in scope by "7cf9d5dc8c - fix hashing of streamer info,"
if a file is opened in update mode and the reading of its `StreamerInfo` record is skip (but
an identical record was already read) *and* some data is stored in the file, the new
`StreamerInfo` record written was missing all the classes in the original record that
were not used during the update.
To resolve this we record not only the fact that the record has been read and process
but also its content (via a collectin of uid of the `TStreamerInfo` objects).
Upon skipping the `StreamerInfo` record, we now mark of its `TStreamerInfo` objects has
been used by the file (and thus upon writing the record …
=> IO: Fix StreamerInfo record write during file update.

core/thread/inc/ROOT/RConcurrentHashColl.hxx, core/thread/src/RConcurrentHashColl.cxx, io/io/inc/TFile.h, io/io/src/TFile.cxx
Fix #12783
Since "66dfb08bd7 - [IO] Do not process the streamerinfo record of a file if we read the si already read"
which was extended in scope by "7cf9d5dc8c - fix hashing of streamer info,"
if a file is opened in update mode and the reading of its `StreamerInfo` record is skip (but
an identical record was already read) *and* some data is stored in the file, the new
`StreamerInfo` record written was missing all the classes in the original record that
were not used during the update.
To resolve this we record not only the fact that the record has been read and process
but also its content (via a collectin of uid of the `TStreamerInfo` objects).
Upon skipping the `StreamerInfo` record, we now mark of its `TStreamerInfo` objects has
been used by the file (and thus upon writing the record …
=> v628: IO: Fix StreamerInfo record write during file update.

interpreter/cling/lib/Utils/SourceNormalization.cpp, interpreter/cling/test/Prompt/DontWrap.C
This expands the handling introduced in commit 31e46a65f6 to include the length modifiers `short` and `long` as mentioned back then. It still doesn't handle the cases of multiple modifiers such as `unsigned long long int` and `long int unsigned long` (being the same type).
Fixes https://github.com/root-project/root/issues/13288
=> [cling] Handle length modifiers in IsClassOrFunction

roofit/roofitcore/inc/RooBinning.h, roofit/roofitcore/src/RooBinning.cxx, roofit/roofitcore/src/RooDataHist.cxx
When importing a `TH1` into a RooDataHist, the RooFit variable ranges are automatically adjusted to the nearest `TH1` bin boundaries. Then, the number of the corresponding `TH1` bin is stored in a "offset" variable to be used later when filling the RooDataHist.
For this range adjustment, there are two code branches. One for the uniform case, and one for non-uniform binning.
The uniform binning code branch was a bit weird, because it also created a non-uniform `RooBinning` object, only used to determine the original `TH1` bin of the lower adjusted boundary via
`RooBinning::rawBinNumber()`. But this can just be done with `TAxis::FindBin()`. Hence, we don't even need this confusing `rawBinNumber()` function as an implementation detail of RooFit and can get rid of it.
With this change, we …
=> [RF] Use `TAxis::FindBin()` to determine bin offsets for TH1 import

core/foundation/inc/ROOT/TypeTraits.hxx, hist/hist/inc/TF1.h, hist/hist/inc/TFormula.h, hist/hist/src/TF1.cxx, hist/hist/src/TFormula.cxx
This PR aims to fix the problem of inconsistency in `TFormula::SetParNames()` and `TFormula::SetParameters()` functions as described in #7805.
I have added warning if more values are provided than the actual number of parameters of `TFormula` object, original behaviour of the function is maintained apart from the added warning.
Some test will fail due to the added warning, please tell if I should remove the warning or resolve the root cause of the warnings ( For instance, `TF1` using `TFormula::SetParameters()` and always passing 11 arguments is one cause of failing tests) 
I would also like to slightly modify behaviour of these functions such that value and names of only specified parameters should be changed, current behaviour is to reset the value and names of parameters which aren't …
=> [math] Fix inconsistent behaviour of TFormula parameter functions

roofit/hs3/LinkDef.h
This is to fix build warnings.
Seen for example here:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=ROOT-centos9,SPEC=noimt,V=master/lastBuild/parsed_console/
```
Warning: Unused class rule: RooStats::HistFactory::JSONTool
```
=> [RF] Remove unused `JSONTool` entry in the LinkDef file

cmake/modules/RootBuildOptions.cmake
The `if(roofit_multiprocess AND NOT minuit2)` check should be done after `ROOT_APPLY_OPTIONS()`, because otherwise the variables will not be defined as the defaults if the user didn't define them explicitly.
This avoids warnings when not defining the `minuit2` option when setting `roofit_multiprocess=ON`.
Follows up directly on 3acc0e601bd.
To be backported to the 6.30 branch.
=> [cmake] Don't check `minuit2` option before `ROOT_APPLY_OPTIONS()`

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
By using std::apply, now available after moving to C++17, the implementation can be greatly simplified.
The way the value of a std::ntuple is printed.
Nothing, it reduces the overall maintenance cost of the root codebase by simplifying it.
=> [Cling] Simplify std::tuple value printer

hist/hist/inc/TFormula.h
Fix the following  compilation error with the `-Wpedantic` compiler flag
```
[81%] Building... ... ... ... error: extra ';' [-Wpedantic]
```
=> [skip-ci] Remove extra semicolon

interpreter/llvm/src/tools/clang/lib/AST/ExprConstant.cpp
Fixes https://github.com/root-project/root/issues/13851
See also https://github.com/llvm/llvm-project/issues/68702
(cherry picked from commit 0919a5359eefda0fc9e56a3198da21596114d62f)
=> [clang] Fix crash with constexpr destructor [v6.28]

builtins/xrootd/CMakeLists.txt
Hey! One commit I found locally, may be used to fix #7441 
- Enabled by the XRDCL_LIB_ONLY=ON cmake flag
- Prevents building the client binaries such as xrdcp in our build dir
but not exposing them in the installation
Fixes #7441
=> [cmake] Build only the library of the xrootd client

bindings/pyroot/pythonizations/test/root_module.py
I see some import failures from `ROOT.RVec` in #5310, added a test here.
=> [PyROOT] Add test for implicit import from the ROOT namespace
