root-project/root

js/build/jsroot.js, js/changes.md, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/gpad/RAxisPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist2d/THistPainter.mjs
1. Fix - expand item in hierarchy painter
2. Fix - correctly use saved TF1 values for non-equidistant bins 
3. Fix - in log scales replace 10^1 label by 10
4. Fix - vertical align of log labels on X axis
5. Fix - second click of the same item in hierarchy painter
Branch 7.5 of jsroot is base for 6.30 release
=> [jsroot] 7.5.1 18/10/2023 [6.30][skip-ci]

tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/src/RDFHelpers.cxx
After a quick discussion at one of the recent PPP round tables, we decided that the ProgressBar feature is missing a nice finalization, which prints the final status with all processed events. This PR introduces this feature. It now looks as on the attached screen-shot (both for MT and non MT modes, checked with df106_HiggsToFourLeptons and df102_NanoAODDimuonAnalysis tutorials).
=> [DF] Improve progress bar finalization

tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/src/RDFHelpers.cxx
A method to improve the way the ProgressBar is finalized (only on one line with total number of files and events being printed).
=> [Backport][DF] ProgressBar finalize update

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx
Adds RNTuple support for `std::atomic<T>`. The inner type `T` has to be an I/O supported type. On-disk representation is identical between atomic `T` and plain `T` except for an extra marker field for the atomic wrapper. CMS MiniAOD use atomic types.
=> [ntuple] add support for std::atomic<T>

core/dictgen/src/rootcling_impl.cxx
These changes allow the user to generate a dictionary with rootcling and selecting classes with a selection XML file, the selection file format of genreflex, instead of a traditional LinkDef file.
This PR is coupled with ROOT Test PR https://github.com/root-project/roottest/pull/1014 .
https://github.com/dpiparo/root/pull/new/issue_13543
=> [Dict][13543] Correct dicts with rootcling+selection xml

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx, tree/ntuple/v7/test/rfield_blob.cxx
Adds support for the `std::byte` type. Vectors of bytes can be used to represent BLOBs in RNTuple. The unit test shows an example where a `TMemFile` is stored in such a vector. A follow-up PR should provide a convenient interface to store BLOBs.
=> [ntuple] Add support for std::byte

tutorials/CMakeLists.txt, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
This PR is based on PR #11200. 
The systematic variations in the Higgs to four leptons tutorial are implemented. The improved plot shows the up and down variations of the total Monte Carlo weight (scale factor) on top of what was previously shown. Now the C++ version of the full tutorial is also available.
I decided to rename the tutorial from df106_HiggsToFourLeptons.py to df106_HiggsToFourLeptons_withVaariations.py but it's just a suggestion, I can change it back to what it was. 
Note (I suppose only relevant since I run it on Mac ARM)- in order to use the Interpolator I built root with `-Dbuiltin_gsl=ON` option.
=> [DF] Add systematic variations to HiggsToFourLeptons tutorials

tutorials/CMakeLists.txt, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
Implemented the systematic variations in the Higgs to Four Leptons tutorial.
The revised plot shows the up and down variations
of the total Monte Carlo weight (scale factor), together with
the uncertainty band in between those lines.
The C++ version of the full tutorial is now also available.
=> [Backport][DF] Add tutorials with systematics

bindings/pyroot/pythonizations/python/ROOT/_facade.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
by removing invocations to the root-config executable. This executable was invoked twice to check if RDataFrame was available. Such a behaviour causes a severe slowdown, especially on cvmfs. This has been replaced by a simple string comparison.
Backport of 4c863d
=> [Backport] [PyROOT] Speedup inclusion of ROOT module

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/draw.mjs, js/modules/gpad/RAxisPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TH2Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/hist2d/TMultiGraphPainter.mjs, tutorials/fit/fit2dHist.C
1. Correctly fill stats box with fit function parameters
2. Correctly show `#chi^{2}` in stats box
3. Support color palette in th3 drawings
4. Support "logv" draw option for all histogram classes - log scale for content
5. Support "[cutg]" draw option for TH2/TF2 surface plots
6. Fix fit2dHist.C macro - do not draw interim fit results
7. Implement tickz draw option, used for color palette ticks
8. Implement skewness and kurtosis calculations for histogram stats box
=> [webcanvas] Improve TF1/TF2 drawings

tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/src/RDFHelpers.cxx, tree/dataframe/src/RDataFrame.cxx, tree/dataframe/test/dataframe_helpers.cxx, tutorials/dataframe/df102_NanoAODDimuonAnalysis.C, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
For consistency since progress bar is two words we should use it as ProgressBar in all functions - AddProgressBar and PrintProgressBar
=> [DF] Fix AddProgressbar to AddProgressBar and related typos

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
As suggested by https://docs.python.org/3/whatsnew/3.12.html#other-language-changes
=> [PyROOT] Avoid SyntaxWarning about invalid escape sequence

roofit/roostats/src/LikelihoodInterval.cxx, test/CMakeLists.txt
Don't check the Minos output code, because if the Minos errors are
at the limit, Minuit2 will return nonzero, unlike Minuit 1.
This case where the errors are at limit should not cause a failure
though. The `stressRooStats` test suite actively provokes it, by fitting
a dataset with a single observed value that corresponds to a best-fit
parameter value at the limit.
With these changes, the `stressRooStats` suite will also pass with
Minuit2 and BatchMode, which is now added as a unit test.
=> [RF] Don't check Minos output code in RooStats LikelihoodInterval

bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
Since Python 3.12, in the implementation of 'classobject.h' the function PyMethod_GET_SELF performs an assert to check that the passed function argument is a method:
```
\#define _PyMethod_CAST(meth) \
(assert(PyMethod_Check(meth)), _Py_CAST(PyMethodObject*, meth))
[...]
static inline PyObject* PyMethod_GET_SELF(PyObject *meth) {
return _PyMethod_CAST(meth)->im_self;
}
```
It's fair that the assert fails, because the Python type of `meth` in this context is not a `PyMethod_Type`, but the
`CustomInstanceMethod_Type` from cppyy. However, as can be seen in the implementation of `CustomInstanceMethod_New`, the actual C++ type that implements this custom cppy type is just the regular `PyMethodObject`.
Hence, this commit suggests new assert-free `CustomInstanceMethod_GET_*` macros that replace …
=> [PyROOT] Prevent functions from crashing due to Python 3.12 assert

bindings/pyroot/pythonizations/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_runtime_error.py
This commit enables serialization of the Python proxy defined within cppyy to the C++ std::runtime_error class. By doing so, we avoid errors that happen in certain configurations of Dask tasks where a std::runtime_error may be thrown within the event loop itself. Recent CI failures report the following:
```
RDataFrame::Run: event loop was interrupted
Warning in <TBufferFile::WriteObjectAny>: since runtime_error has no public constructor
which can be called without argument, objects of this class
can not be read with the current library. You will need to
add a default constructor before attempting to read it.
Warning in <TStreamerInfo::Build>: runtime_error: base class exception has no streamer or dictionary it will not be saved
Warning in <TStreamerInfo::Build>: runtime_error: …
```
=> [PyROOT] Fix distributed RDataFrame tests due to error serialization

bindings/pyroot/pythonizations/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_runtime_error.py
Backport of  https://github.com/root-project/root/pull/13926
=> [6.30] Fix distributed RDataFrame tests due to error serialization

bindings/pyroot/pythonizations/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_runtime_error.py
=> [6.28] Fix distributed RDataFrame tests due to error serialization

hist/histpainter/inc/TGraph2DPainter.h, hist/histpainter/src/TGraph2DPainter.cxx
TGraph2DPainter keep pointers on TGraph2D data,
but was not checking if these values were changed.
Fixes problem reported https://root-forum.cern.ch/t/56816/
=> Update TGraph2D properties before painting [6.30]

math/minuit2/inc/Minuit2/MinosError.h, math/minuit2/src/MnContours.cxx, math/minuit2/src/MnSeedGenerator.cxx, math/minuit2/src/NegativeG2LineSearch.cxx, tutorials/roofit/rf601_intminuit.C, tutorials/roofit/rf601_intminuit.py
This pull request fixes the search for contour points in Minuit2. 
Three separated problems were identified (see the commit messages)
- a bug in Minos for computing errors when close to the border
- an issue in finding the contour point in case the first attempt failed.
- an issue in the seed when one of the second derivative is zero. Use now an arbitrary value (e.g. 1) instead of using a very small g2, resulting in a very large covariance causing later on problem in the minimization. 
This PR fixes the issue #13729
=> [minuit2] Fixes in Minuit2 for  finding contour points

net/http/src/TRootSniffer.cxx, proof/proofplayer/src/TEventIter.cxx, roofit/histfactory/src/Channel.cxx
`ReadObj` returns an owning pointer.
Using `dynamic_cast` and ignoring the "not castable" case can leak memory.
See: https://root-forum.cern.ch/t/possible-leak-with-dynamic-cast-and-tkey-readobj/56799
=> fix: Use TKey::ReadObject<T> instead of ReadObj

gui/gui/src/TRootBrowser.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist/TPavePainter.mjs
In "classical" TBrowser one want to use normal TCanvas - even if rootrc configured differently. 
Therefore change gEnv values for the time when canvas is created
Address issue from forum:
https://root-forum.cern.ch/t/web-browser-off-not-working/56859/
=> [tbrowser] ensure that TCanvas created when web mode is not active

gui/gui/src/TRootBrowser.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist/TPavePainter.mjs
In "classical" TBrowser one want to use normal TCanvas - even if rootrc configured differently. Therefore change gEnv values for the time when canvas is created
=> [tbrowser] ensure that TCanvas created when web mode is not active [6.30]

cmake/modules/FindMySQL.cmake
- Changes FindMyQL.cmake to find the installation of MySQL if mysql_config fails because it has been relocated
=> [cmake] make FindMySQL.cmake more tolerant

math/mathcore/src/Fitter.cxx
This fixes using the fit2dHist.C when using the global fit (user defined FCN)
This PR fixes #13906
=> [mathcore] Fix creating the ParameterSetting when calling SetFCN

math/mathcore/src/Fitter.cxx
This fixes using the fit2dHist.C when using the global fit (user defined FCN)
This PR fixes #13906
=> Backport mathcore : Fix creating the ParameterSetting when calling SetFCN

tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
Remove the usage of `RResult`-related function as the returned importer object is not wrapped in it anymore. Also point to the tutorial, and mention the specification for type compatibility.
=> [skip-ci][ntuple][NFC] Update importer documentation

graf3d/eve7/glu/render.c
parameter 'size' set but not used [-Wunused-but-set-parameter]
=> [eve7] Silence "unused par" warning on Mac release builds:

core/dictgen/src/rootcling_impl.cxx
These changes allow the user to generate a dictionary with rootcling and selecting classes with a selection XML file, the selection file format of genreflex, instead of a traditional LinkDef file.
Fixes https://github.com/root-project/root/issues/13543
=> [Backport v6-30][Dict] Correct dicts with rootcling+sel xml

bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/patches/avoiding-python312-assert.patch
=> [PyROOT] Fix typo in recent PyROOT commit

graf2d/cocoa/src/QuartzWindow.mm
From Timur! Fixes black area on top of canvas region in non-batch (i.e. interactive) GUI save-as. I.e. fixes issue #13964.
Backport of https://github.com/root-project/root/pull/13970
=> v6.30: [cocoa] Fix wrong boundary of cocoa to-bitmap:

graf2d/cocoa/src/QuartzWindow.mm
From Timur! Fixes black area on top of canvas region in non-batch (i.e. interactive) GUI save-as. I.e. fixes issue #13964.
=> [cocoa] Fix wrong boundary of cocoa to-bitmap:

hist/hist/src/TF1.cxx, hist/hist/src/TF2.cxx, hist/hist/src/TF3.cxx, hist/hist/test/CMakeLists.txt, hist/hist/test/test_tf1.cxx, hist/hist/test/test_tf2.cxx, hist/hist/test/test_tf3.cxx
Since the beginning when 0 ranges were specified by Save method, 
half a bin was add to coordinate. But wrong number of bins was stored and 
therefore produced buffer was not able to use. Error was from very beginning  - 
already by initial import from rcs to svn 23 years ago.
Now proper number of bins are stored. It still stores middle of bins when `f1->Save(0,0,0,0,0,0)` is called.
There was also failure to use such saved buffer when trying to get approximation at upper boundaries. Now it is fixed.
Adding tests for all TF1/TF2/TF3.
Fixes #13927
=> Fix [TF1,TF2,TF3] Save methods

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/math.mjs, js/modules/core.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TGraph2DPainter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/TH1Painter.mjs, net/http/inc/TRootSniffer.h, net/http/src/THttpServer.cxx, net/http/src/TRootSniffer.cxx
1. Draw functions from `TMultiGraph`
2. Fill content of TGraph2D histogram - if drawn with triangle options
3. Use interpolation of saved TF1 buffers
4. Several fixes in JSROOT concerning TFormula parsing
5. Resolve problem in THttpServer recursive processing
Improves a lot handling of fit tutorials with `TF1`, `TF2`, `TMultiGraph`, `TGraph2D` drawings
=> [webcanvas] improve usage of  `TF1` saved buffers, better `TMultiGraph` support

roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx
In simultaneous fits with more than one channel, the NLL variable adds by default a normalization term so that the probability is normalized over the full measurement including all channels.
In case of bin-by-bin offsetting, this should not be done because the same term appears in the likelihood in the denominator and cancels out.
Also, fixes a problem where the name of the `_offsetPdf` was not correctly reset (previously, only the name of the proxy was changed, not the name of the pdf).
=> [RF] Yet another fix to bin-by-bin offsetting

tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
In the current version of the tutorials, the ROOT::Math::Interpolator was used which required ROOT to be built with Mathmore or gsl. Since it was a linear interpolation, it can be replaced by simply creating a TGraph and using the TGraph::Eval() method.
=> [DF] Avoid usage of Mathmore/gsl in df106 tutorials

bindings/pyroot/pythonizations/test/sofie_gnn.py, tmva/sofie/inc/TMVA/RFunction.hxx, tmva/sofie/inc/TMVA/SOFIE_common.hxx, tmva/sofie/src/RFunction.cxx, tmva/sofie/src/RModel_GNN.cxx, tutorials/tmva/TMVA_SOFIE_GNN.py
The SOFIE GNN must support having different senders and receivers (adjacent matrix) for every event as it is the case in the GraphNet library
This is now achieved by including the list(vector)  of sender/receivers in the GNN data structure which is passed to the generated infer function. Before the list was used as a static data member of the generated GNN secton class
=> [tmva][sofie] Fix the issue with GNN receivers/senders different every by event

roofit/roofitcore/src/RooNLLVar.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx
In simultaneous fits with more than one channel, the NLL variable adds by default a normalization term so that the probability is normalized over the full measurement including all channels.
In case of bin-by-bin offsetting, this should not be done because the same term appears in the likelihood in the denominator and cancels out.
Also, fixes a problem where the name of the `_offsetPdf` was not correctly reset (previously, only the name of the proxy was changed, not the name of the pdf).
Backport of https://github.com/root-project/root/pull/13986.
=> [v630][RF] Yet another fix to bin-by-bin offsetting

cmake/modules/FindZeroMQ.cmake
Fix cmake/modules/FindZeroMQ.cmake
It now finds ZeroMQ in Fedora 40.
=> Fix cmake/modules/FindZeroMQ.cmake

core/base/inc/TColor.h, core/base/inc/TColorGradient.h, core/base/src/TColor.cxx, graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx, graf3d/gviz3d/src/TStructViewerGUI.cxx, tutorials/gl/gviz3d.C
1. If called once with argument TColor::DefinedColors(1), all saved canvas will include color and palette. One can reset flag with TColor::DefinedColors(-1)
2. When reading canvas with stored colors - correctly restore all colors attributes and support gradients
3. Provide default constructors for color gradient classes. Let correctly read canvases with gradients
4. Fix TPad::GetViewer3D(), prevent crash in gviz3d.C tutorial
=> Extend `TColor::DefinedColors()` functionality

math/mathcore/src/AdaptiveIntegratorMultiDim.cxx
Make changes in the class AdaptiveIntegratorMultiDim.
Delete obscure conditions on evaluating integration status. The mentioned conditions are absent in the original RadMul algorithm. The problem with these conditions is in that they compare some arbitrary hard-coded constants with the absolute value of the integrated function. This lead to incorrect integration of some complicated function. Moreover, if one multiply integrand by some arbitrary factor and then divide the integral by it, then time and accuracy integration will change, but it shouldn't be so.    For example, if integrated function return result of order 10^-38, then sometimes integration gives nonsense result with very low number of integrated function calls. The parameter RelAccuracy is not accounted for by the algorithm …
=> [mathcore] Delete obscure conditions in class for adaptive quadrature integration in multi-dimensions (AdaptiveIntegratorMultiDim)

graf2d/graf/src/TLegend.cxx, hist/histpainter/src/TGraphPainter.cxx
Reproducer:
```
void gerrors() {
TCanvas *c1 = new TCanvas("c1","A Simple Graph with error bars",200,10,700,500);
const Int_t n = 10;
Float_t x[n]  = {-0.22, 0.05, 0.25, 0.35, 0.5, 0.61,0.7,0.85,0.89,0.95};
Float_t y[n]  = {1,2.9,5.6,7.4,9,9.6,8.7,6.3,4.5,1};
Float_t ex[n] = {.05,.1,.07,.07,.04,.05,.06,.07,.08,.05};
Float_t ey[n] = {.8,.7,.6,.5,.4,.4,.5,.6,.7,.8};
TGraphErrors *gr = new TGraphErrors(n,x,y,ex,ey);
gr->SetTitle("TGraphErrors Example");
gr->SetMarkerColor(4);
gr->SetMarkerStyle(21);
gr->Draw("AP|>");
c1->Update();
auto l = new TLegend(0.45,0.65,0.8,0.8,"","NDC");
l->SetBorderSize(0.);
l->SetTextFont(42);
l->AddEntry(gr, "TGraphErrors new title", "e");
l->Draw();
}
```
=> Make sure the legend endcaps fill style matches the graph one

graf2d/graf/src/TPaveText.cxx
When drawing label, "NDC" should be removed otherwise real user coordinates will be handled as NDC
Fixes: https://github.com/root-project/root/issues/14032
=> Fix drawing of the TPaveText label

core/base/CMakeLists.txt, core/base/v7/inc/ROOT/RFloat16.hxx, tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RColumnElement.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_types.cxx
This PR adds support to 16-bit (IEEE 754-2008) floating point numbers to RNTuple. In similar vein to 32-bit doubles, this is enabled by changing the column representation of ordinary `float` fields (i.e., regular `float` fields are used, but the values are saved to disk using half precision).
Because half-precision floats are only part of the C++ standard from C++23 onwards, for now we use parts of the [`half`](https://half.sourceforge.net/) library (MIT-licensed) for converting between half- and single-precision floats. For x86 processors, the [F16C](https://en.wikipedia.org/wiki/F16C) ISA extension can be enabled to do this conversion on the hardware directly. However, this appears to mess with `TFormulaTests`.
=> [ntuple] Add support for half-precision floats

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_batchgenerator.py, tmva/tmva/inc/TMVA/RBatchGenerator.hxx, tmva/tmva/inc/TMVA/RChunkLoader.hxx
Changed the internal handeling of filters in RBatchGenerator. 
Instead of adding a new filter for each filter, the filters are concatenated to a string and applied as a single filter 
Note: The Python interface of the RBatchGenerator does not change.
=> Changed filters used by RBatchGenerator to a single string

cmake/scripts/RootUseFile.cmake.in, graf2d/asimage/src/libAfterImage/CMakeLists.txt, math/genetic/test/CMakeLists.txt, math/minuit2/CMakeLists.txt, math/minuit2/StandAlone.cmake, math/minuit2/examples/simple/CMakeLists.txt, math/minuit2/test/CMakeLists.txt, test/CMakeLists.txt, test/RootShower/CMakeLists.txt, test/periodic/CMakeLists.txt, tutorials/CMakeLists.txt, tutorials/tree/dictionary/CMakeLists.txt, tutorials/webgui/qtweb/CMakeLists.txt
With CMake `3.27` I get this warning:
```
CMake Deprecation Warning at interpreter/cling/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Thus I bumped the minimum required CMake version to `3.10`, which is the version included in Ubuntu 18.04 LTS. In theory `3.6` would also work, but `3.10` gives a bit of margin for the future. The version in cling is synced with LLVM.
=> [cmake] Bump minimum CMake version

core/foundation/inc/ROOT/StringUtils.hxx, core/foundation/test/testStringUtils.cxx
Adds `','.join(strings)` capabilities to `TString.h`.
Right now it is as a variadic argument, but it could be expanded to std::array, std::vector or even TObjArray
This PR depends on https://github.com/root-project/root/pull/13243
=> counterpart of Python's join function in C++

tree/dataframe/CMakeLists.txt, tree/dataframe/inc/ROOT/RDF/RMetaData.hxx, tree/dataframe/src/RMetaData.cxx
It's better if the RDataFrame doesn't depend on `nlohmann::json` for this reason:
If you build ROOT **without** the builtin nlohmannjson, it finds the json header with `find_package(nlohmann_json)`, which is fine.
However, if the `nlohmann/json.hpp` header is not in the default include path, one is now forced to also do `find_package(nlohmann_json)` in every compiled project that uses RDataFrame!
This happened to one of our students recently, which is why I got aware of the problem. On most Linux systems, this is not a problem because `json.hpp` is in a standard location, but for macOS this doesn't seem to be the case necessarily.
=> [DF] Avoid public dependency of RDataFrame on `nlohmann::json`

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
This avoids the following warning when building `rootbench` (gcc 13.2.1):
```txt
In file included from /home/rembserj/spaces/master/root/src/build/include/ROOT/RDF/RInterface.hxx:15,
from /home/rembserj/spaces/master/root/src/build/include/ROOT/RDataFrame.hxx:21,
from /home/rembserj/spaces/master/root/src/root/rootbench/root/tree/dataframe/RDataFrameBenchmarks.cxx:1:
/home/rembserj/spaces/master/root/src/build/include/ROOT/RDF/ActionHelpers.hxx: In instantiation of ‘void ROOT::Internal::RDF::SnapshotHelperMT<ColTypes>::UpdateCArraysPtrs(unsigned int, ColTypes& ..., std::index_sequence<S ...>) [with long unsigned int ...S = {}; ColTypes = {}; std::index_sequence<S ...> = std::integer_sequence<long unsigned int>]’:
/home/rembserj/spaces/master/root/src/build/include/ROOT/RDF/ActionHelpers.hx …
```
=> [DF] Avoid unused parameter warning in RDF ActionHelpers

tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/TMVA_RNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.py
After the recent update of the TMVA classification tests, some comments were not updated to reflect the changes, which is confusing. This PR makes the comments the same in all tests to reduce the conusion.
=> Use consistent wording of the comments in the different TMVA classification tests to avoid confusion

cmake/modules/RootMacros.cmake, tmva/tmva/test/DNN/CMakeLists.txt, tree/tree/test/CMakeLists.txt, tutorials/CMakeLists.txt
Increase some test timeouts
Fixes occasional test timeout failures. Mostly seen on aarch64.
```
The following tests FAILED:
330 - TMVA-DNN-MethodDL-Adam-Optimization-Cpu (Timeout)
967 - tutorial-tmva-TMVAMulticlass (Timeout)
```
The timeout has been seen for various tutorial-tmva-TMVA* tests, not just the one mentions above.
=> Increase test timeout

tmva/tmva/inc/TMVA/Reader.h, tmva/tmva/src/Reader.cxx, tutorials/tmva/TMVAClassificationApplication.C, tutorials/tmva/TMVAClassificationCategoryApplication.C
Since cling can deal with `dynamic_cast` correctly, the `TMVA::Reader::FindCutsMVA()` workaround is not needed anymore.
That's one of the changes necessary to address #10058.
=> [TMVA] Remove workaround from the CINT era

core/base/src/TColor.cxx
TColor::GetColor(r,g,b) uses 5bit threshold by
default to create new colors. This differs
from normal X11 with 8bit colors. As  a result,
images produced in batch and in interactive
session may differ - see greyscale.C macro.
Make default 8bit resolution for colors, and
reduce it only if detecting such display.
=> Change default TColor resolution

bindings/pyroot/cppyy/cppyy-backend/cling/create_src_directory.py, etc/runfirefox.sh, gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx, gui/webdisplay/src/RWebDisplayHandle.cxx
1. Create custom firefox profile for interactive session. In this profile set several parameters to hide URL and tabs widget
2. Custom profile allows to configure initial -width and -height URL parameters for window geometry
3. Introduce `runfirefox.sh` shell script to use 'trap' functionality to cleanup temporary profile after firefox is exiting. Trying to cleanup from ROOT does not work - while ROOT exit faster than firefox.
With these changes Firefox behaves much better than before - one gets normal window without extra decorations.
The only missing part for Firefox - support of PDF output in headless mode.
=> [webgui] Improve firefox support 

hist/hist/inc/TH1.h, hist/hist/src/TH1.cxx
Made the static function `TH1::CheckConsistency` public and changed the return type to `Bool_t`.
The exceptions types it throws were also made public, so that user code could catch them
At the moment `TH1::CheckConsistency` is called internally by `TH1::Add`, and prints error messages in case of failure, but continues the execution.
Making it public allows user code to manually check the consistency to catch errors and stop the program.
This is especially useful for programs that make hundreds of `Add`s, out of which only a few fail, and the error messages may be lost in logs and go unnoticed.
=> [hist] Avoid `try-catch` in TH1

README/ReleaseNotes/v632/index.md, roofit/roofitcore/inc/RooAbsArg.h, roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/inc/RooWorkspace.h, roofit/roofitcore/src/RooWorkspace.cxx
The STL-compatible alternatives are now around long enough (since ROOT 6.18, 4 years ago) so after this grace period it is time to deprecate and eventually remove the old iterators.
=> [RF] Deprecate RooFit legacy iterators

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
This PR extends the support for `std::set` fields with `std::unordered_set` fields.
N.B. We might want to consider moving the dictionary entries for the tests of these types (along with the ones for `std::map` fields) to a dedicated LinkDef file, since technically they don't have anything to do with the `CustomStruct` test type. This can be addressed in a separate PR.
=> [ntuple] Add support for `std::unordered_set` fields

tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ProxiedSTLContainer.hxx, tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
This PR moves the dictionaries for STL containers required for testing to a separate LinkDef. The rationale behind this is that these dictionaries are not directly related to the `CustomStruct` and once #13904 and #14069 are merged even more (unrelated) dictionary entries would be added, so it would be good to avoid clutter and separate these.
=> [ntuple] Move STL dictionary entries to separate file

graf2d/cocoa/src/QuartzWindow.mm, graf2d/cocoa/src/ROOTOpenGLView.mm, graf2d/cocoa/src/TGCocoa.mm
Backport Fix Cocoa GUI for MacOS14 and Clang15
=> [v6-28] Backport Cocoa

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_types.cxx
This PR adds support for `std::map` fields through collection proxies (similar to `std::set`).
In theory, other (custom) associative collections (provided they implement a collection proxy) should now also be able to be added as fields. Because the use case for this is not yet obvious, this is still disabled.
=> [ntuple] Add support for `std::map` fields

cmake/modules/RootMacros.cmake
Fix shared library output name if the generator is not `Visual Studio` but e.g. `Ninja`
=> Don't check CMAKE_GENERATOR use MSVC instead

config/rootrc.in
Default value is on in C++ code,
but was remained off in system.rootrc and over-rulling C++
=> [webgui] use loopback by default [6.28]

config/rootrc.in
Default value is `ON` in C++ code,
but was remained off in system.rootrc and over-rulling C++
Reported in forum: 
https://root-forum.cern.ch/t/root-web-is-insecure/57164
=> [webgui] use loopback by default

sql/sqlite/src/TSQLiteServer.cxx
Function `sqlite3_prepare` in `sql/sqlite/src/TSQLiteServer.cxx` with info about [tail](https://sqlite.org/c3ref/prepare.html). `sqlite3_prepare` only compile the first statement in "sql", so "tail" is left pointing to what remains uncompiled.
```
void test()
{
TSQLServer *db = TSQLServer::Connect("sqlite://test.sqlite", "", "");
TSQLResult *res = db->Query("CREATE TABLE test(name TEXT)");
if (res) { res->Next(); delete res; }
res = db->Query("INSERT INTO test VALUES('1st');"
"INSERT INTO test VALUES('2nd');");
if (res) { res->Next(); delete res; }
}
```
```
$ root test.C
root [0]
Processing test.C...
Warning in <TSQLiteServer::Query>: Don't use multiple queries, 'INSERT INTO test VALUES('2nd');' query was ignored
root [1]
```
=> small improvements in sqlite3_prepare

tree/ntuple/v7/doc/specifications.md
This PR is a leftover update of the specifications after adding #14069.
=> [NFC][ntuple] Add `std::unordered_set` to specification

tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ProxiedSTLContainer.hxx
This PR is a minor follow-up from #14072, moving some leftover `#include`s from `CustomStruct.hxx` to `ProxiedSTLContainer.hxx`.
=> [ntuple] Move includes in test helpers to correct header file

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RClusterPool.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx
- Respect cluster boundaries when assigning entry ranges to slots
- Add RPageSource::SetEntryRange to avoid cluster read-ahead into other slots entry range
Fixes RDF-IMT with RNTuple
=> [ntuple] use cluster boundaries in RDF iteration

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ProxiedSTLContainer.hxx, tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
This PR extends the support for `std::map` fields with `std::unordered_map` fields.
=> [ntuple] Add support for `std::unordered_map` fields

hist/hist/test/test_tprofile2poly.cxx
As seen in #9601, using `EXCEPT_NEAR` with an absolute error is not so good, because if the numbers are large the hardcoded absolute error can be smaller than the double precision. In these cases, `EXPECT_DOUBLE_EQ` is recommended instead.
@ellert, I'm suggesting this as an alternative to what you suggested in #9601, but without magic numbers of two. Can you maybe check if this approach with `EXPECT_DOUBLE_EQ` also works? Thanks!
=> [math] Use `EXPECT_DOUBLE_EQ` in test_tprofile2poly.cxx

io/io/inc/ROOT/TBufferMerger.hxx, io/io/src/TBufferMerger.cxx, io/io/src/TBufferMergerFile.cxx, io/io/test/TBufferMerger.cxx
At least according to my limited tests, removing the queuing mechanism from TBufferMerger is equally fast because it avoids the overhead of preparing a TBufferFile for queuing, and uses less memory.
=> Avoid memory blowup of TBufferMerger

tmva/tmva/src/DNN/Architectures/Cpu/LossFunctions.hxx, tmva/tmva/src/DNN/Architectures/Cuda/Kernels.cuh
Improve the calculation for the binary cross entropy loss when the inputs are very large (and also very large negative). Use correct log approximation to avoid loss of precisions and returning infinity values.
Fix both the CPU and GPU calculations
This has been initiated by this post https://root-forum.cern.ch/t/when-tmva-comput-loss-some-eopchs-loss-is-inf/57018/ where `inf` loss values were obtained during training
=> [tmva] Fix cross entropy calculation for large input values

config/rootrc.in
Default value is on in C++ code,
but was remained off in system.rootrc and over-rulling C++
=> [webgui] use loopback by default [6.30]

gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowsManager.cxx
In RBrowser different widgets are embed.
Add dummy pending connection handle to get possibility for widget wait for such connection been established
=> [webgui] improve handling of embed widgets [6.30]

tutorials/tmva/pytorch/ClassificationPyTorch.py, tutorials/tmva/pytorch/MulticlassPyTorch.py, tutorials/tmva/pytorch/RegressionPyTorch.py
These tutorials don't need to create an output root file of the traiining. This avoids potential problem of running the tutorials in parallel and writing on the same file
=> [tmva][pymva] Avoid creating the output file tmva.root

gui/webdisplay/src/RWebWindowsManager.cxx
Disregard of rootrc parameters always assign loopback. 
FastCGI is also disabled for the moment; it is alternative to civetweb
Backport #14119
=> [webgui] always use loopback [6.26]

.clang-format
The key IncludeCategories appeared twice in the file which caused tools other than clang-format (.e.g CLion) to fail to parse the file and format correctly. clang-format took the settings from the second occurrence (as indicated by running `clang-format --dump-config`), so the first occurrence of IncludeCategories was deleted.
Fixes CLion's parser for the `.clang-format` file.
=> Remove duplicated key from .clang-format

interpreter/cling/lib/Interpreter/DeclUnloader.cpp, interpreter/cling/lib/Interpreter/DeclUnloader.h, interpreter/cling/test/ErrorRecovery/IncompleteType.C
Fixes https://github.com/root-project/root/issues/13815
=> [cling] Handle variable templates in DeclUnloader

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
With this PR, `RNTupleInspector::RColumnInfo` and `RNTupleInspector::RFieldTreeInfo` are renamed to `RNTupleInspector::RColumnInspector` and `RNTupleInspector::RFieldTreeInspector`, along with their getters. The rationale behind this change is to make the class names more symmetric with the general `RNTupleInspector` name and remove any potential ambiguity.
=> [ntuple] Rename `R*Info` classes to `R*Inspector`

tree/ntuple/v7/src/RColumn.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_friends.cxx, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/ntuple/v7/test/ntuple_storage_daos.cxx
With this PR, a proper exception is thrown when a user tries to load an out-of-bounds RNTuple entry (instead of aborting due to a failed assert statement).
To prevent the `RColumn` destructor from attempting to again clean up the page for the entry that was (potentially) loaded prior to attempting to read the out-bounds entry, `fReadPage` in `RColumn` is reset to a null page before attempting to populate it.
=> [ntuple] Throw exception when trying to load out-of-bounds entries

math/minuit2/StandAlone.cmake
Fixes #14157. When building minuit2 standalone with root 6.30/02 (-Dminuit2_standalone=ON), cmake errors out when looking for the version file 'RVersion.hxx' in 'core/foundation/inc/ROOT/RVersion.hxx' whereas it is copied to the top-level dir (i.e. 'math/minuit2/'). This is because the variable VERSION_FILE is incorrectly set to the file path matching the full path of the file. Fixed by setting the parent dir path of 'RVersion.hxx' as the `SOURCE` in `copy_standalone()` so that `VERSION_FILE` is set to just the base file name.
This PR fixes #14157
=> Minuit2: Fix VERSION_FILE path for standalone mode

tmva/sofie/inc/TMVA/ROperator_Gemm.hxx, tmva/sofie/inc/TMVA/ROperator_Pool.hxx, tmva/sofie_parsers/src/ParseMatMul.cxx, tmva/sofie_parsers/src/RModelParser_ONNX.cxx
Fix the parsing of the single MatMul operator:
- the beta attribute used for Gemm when generating code must be set to zero and not 1
- When MatMul is the last operator a bug was present looking for the next operator that was not existing. This is now fixed
- Fix also the default padding in the MaxPool operator. When auto_pad is at default ("notset") and padding is not specified a zero value should be used instead of 1
=> [tmva][sofie] Fix parsing of single MatMul and fix Pool padding

builtins/xrootd/CMakeLists.txt, cmake/modules/FindXROOTD.cmake, cmake/modules/SearchInstalledSoftware.cmake, net/netxng/CMakeLists.txt
This reverts commit 2ee691da61ca51e4dd857ac8c88f778948fb49a7, it breaks configuration with the latest XRootD 5.6.3, for example already found in EPEL.
=> Revert "[cmake] Migrate to `XRootDConfig.cmake` shipped by XRootD"

roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h, roofit/histfactory/src/ParamHistFunc.cxx, roofit/roofit/inc/RooMomentMorphFuncND.h, roofit/roofit/inc/RooNDKeysPdf.h, roofit/roofit/src/RooBernstein.cxx, roofit/roofit/src/RooChebychev.cxx, roofit/roofit/src/RooExpPoly.cxx, roofit/roofit/src/RooJeffreysPrior.cxx, roofit/roofit/src/RooMomentMorph.cxx, roofit/roofit/src/RooMomentMorphFunc.cxx, roofit/roofit/src/RooMomentMorphFuncND.cxx, roofit/roofit/src/RooNDKeysPdf.cxx, roofit/roofit/src/RooParametricStepFunction.cxx, roofit/roofit/src/RooPolynomial.cxx, roofit/roofit/src/RooPower.cxx, roofit/roofit/src/RooStepFunction.cxx, roofit/roofitcore/inc/RooAbsCollection.h, roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooConstraintSum.cxx, roofit/roofitcore/src/RooPolyFunc.cxx, roofit/roofitcore/src/RooPolyVar.cxx, roofit/roofitcore/src/TestStatistics/RooSubsidiaryL.cxx, roofit/roofitmore/src/RooAdaptiveGaussKronrodIntegrator1D.h
It's a very common pattern in the RooFit implementation and user code to check the type when adding to a `RooAbsCollection`, and erroring out if the type is not correct.
This commit suggests a function in `RooAbsCollection` to do exactly this, drastically reducing the code duplication in RooFit and experiment frameworks like CMS combine.
=> [RF] Introduce `RooAbsCollection::addTyped()` method

interpreter/cling/CMakeLists.txt
In standalone builds, it could otherwise happen that the variable is not set during the first CMake invocation and tests fail because they are unable to locate the LLVM headers.
=> [cling] Provide fallback for LLVM_INCLUDE_DIRS

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/ntuple_types.cxx
Adds type support for multidimensional C style arrays. For the time being, the support is limited to the construction of fields from type strings through `RFieldBase::Create`. Support for construction through template parameters `MakeField` is subject to a follow-up PR.
Enables RNTuple support for classes with multidimensional C array members .
=> [ntuple] Add support for n-dim C arrays in EDMs

roofit/histfactory/test/testParamHistFunc.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooFit/Detail/BatchModeDataHelpers.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
By moving the header currently hidden in `src/RooFit` to `inc/RooFit` we can allow a roottest build to work when built with an external installation of ROOT. To preserve the intent of the header, the functions declared are moved to the `RooFit::Internal` namespace, as they are not meant for public use.
This is required for the conda nightlies builds, which build roottest after having built ROOT.
=> [RF] Enable external roottest build

README/ReleaseNotes/v632/index.md, roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h, roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofit/src/RooIntegralMorph.cxx, roofit/roofitcore/inc/RooAbsPdf.h, roofit/roofitcore/inc/RooAddition.h, roofit/roofitcore/inc/RooDataHist.h, roofit/roofitcore/inc/RooFit/Config.h, roofit/roofitcore/inc/RooStringVar.h, roofit/roofitcore/src/RooAbsAnaConvPdf.cxx, roofit/roofitcore/src/RooAbsCategory.cxx, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAbsReal.cxx, roofit/roofitcore/src/RooAddition.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooFFTConvPdf.cxx, roofit/roofitcore/src/RooMCStudy.cxx, roofit/roofitcore/src/RooMinimizer.cxx, roofit/roofitcore/src/RooSimultaneous.cxx, roofit/roostats/src/MarkovChain.cxx, roofit/roostats/src/ProfileLikelihoodCalculator.cxx
* The `ROOFIT_MEMORY_SAFE_INTERFACES` macro is explained in the release notes, so that users and framework developers can use it to detect memory leaks
* Since people are now encouraged to use it, the `RooFit::Detail::owningPtr` helper function was renamed to `RooFit::makeOwningPtr`, because this is now not an implementation detail anymore but part of the user interface
* Remove `takeOwnership` constructor arguments from `PiecewiseInterpolation` and `RooAddition`, because there are not memory-safe and it's not easily possible to only exclude selected parameters behind the `ROOFIT_MEMORY_SAFE_INTERFACES` macro without also changing the sources. Like this, we ensure that the memory-safe interfaces can be used without re-building ROOT.
=> [RF] Promote `ROOFIT_MEMORY_SAFE_INTERFACES` to users in release notes

roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/src/RooFFTConvPdf.cxx
Since ROOT 6.30, we are not building ROOT with the `math/fftw`
subpackage anymore (`fftw3=OFF`). It is the interface between ROOT and
fftw3, but is incompatible with fftws GPL license.
That means that for default ROOT builds, the `RooFFTConvPdf` class for
FFT convolutions is not working anymore, because it uses `math/fftw`.
This commit implements a solution to make the `RooFFTConvPdf` work
again in this situation: the routine that uses fftw is declared
on-the-fly to the interpreter. This will work if the user has an
external install of `fftw3`, which is usually available in all Linux
distributions.
Closes #14162.
Note: the error that you get if `fftw3.h` can't be found looks like this:
```txt
input_line_21:1:10: fatal error: 'fftw3.h' file not found
#include "fftw3.h"
^~~~~~~~~
[#0] …
```
=> [RF] Make `RooFFTConfPdf` also work if ROOT was built with `fftw3=OFF`

tree/dataframe/inc/ROOT/RNTupleDS.hxx, tree/dataframe/src/RNTupleDS.cxx, tree/dataframe/test/datasource_ntuple.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx
Adds a new constructor to the RNTuple RDF data source that takes an ntuple name and a list of files. The data source then treats these files as a chain.
Slightly simplifies the prototype construction in the RNTuple data source: instead of constructing full column reader prototypes, only the corresponding field prototypes are constructed.
Multi-threaded work scheduling is as follows:
- As long as there are more files than slots: every slots get a file
- For the tail: slots get distributed over the remaining files and align on cluster boundaries
Some optimizations for follow-up PRs:
- Load the next ranges in the background. In particular that would open the next batch of files in the backgound
- Clone page sources without reopening the file
- The next set of ranges currently gives up to …
=> [ntuple] Add chain support for RDF data source

tree/dataframe/inc/ROOT/RNTupleDS.hxx, tree/dataframe/src/RNTupleDS.cxx
Adds `FromRNTuple` for vectors of file names. Gives easy access to the RNTuple chains in RDF through PyROOT.
=> [ntuple] Add RDF factory for datasource with chain

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
This reverts commit bfbb58e6f74c38b883ce6e6e096b6c6e44028869. cling needs to be able to interpret C++11, even if built with C++17.
=> Revert "[Cling] Simplify std::tuple/pair value printer"

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/src/RooFFTConvPdf.cxx, roofit/roofitcore/test/testRooTruthModel.cxx
This is a backport of some RooFit PRs that were recently merged to master to v6-30-00-patches:
- https://github.com/root-project/root/pull/14164
- https://github.com/root-project/root/pull/14185
- https://github.com/root-project/root/pull/14174
Related to https://github.com/root-project/root/issues/13458.
Link to the previous backport PR:
https://github.com/root-project/root/pull/14047
=> [v630][RF] Backports of RooFit PRs to `v6-30-00-patches`: Part 7

tree/tree/src/InternalTreeUtils.cxx, tree/tree/src/TChain.cxx, tree/tree/test/TChainParsing.cxx
`ROOT::Internal::TreeUtils::ExpandGlob` now expands  the globbing string recursively to support patterns with wildcards for subdirectories e.g.,  `path/to/tree/files/*/*/*.root`.  Subdirectories are only expanded when it is explicitly included in the pattern. For example, `dir/*` will only add the files in the subdirectories of `dir`, but `dir/*/*` will add the files in the subsubdirectories of `dir`. This behavior resembles Python's glob.glob.
Some other options for expanding a directory wildcard e.g., `dir/*` is to also add files in the subdirectories of `dir` (behavior of `ls`)  or also all the files in all the subdirectories, subsubdirectories, subsubsubdirectories etc. (behavior of `find`).  I believe this would be unwanted since it breaks backwards compatibility.
This currently uses …
=> [tree] Add globbing for subdirectories in TChain::Add

test/stressInterpreter.cxx
It's not important, but I discovered by chance that `InterpreterStress::stressSTLDict()` was doing one iteration less than expected.  Fix that.
=> [test] Fix number of iterations in `InterpreterStress::stressSTLDict()`

builtins/zlib/deflate.c, builtins/zlib/inflate.c
Fix the K&R style definitions in builtin zlib as they will no longer be supported by future C standards and currently emit warnings on clang builds:
```
zlib/deflate.c:393:13: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
int ZEXPORT deflateResetKeep (strm)
```
This also seems to have landed in upstream zlib in version 1.3 (see [zlib.net](https://zlib.net/)
The same changes as in iLCSoft/SIO#20
=> Remove the K&R style definitions from builtin zlib

interpreter/cling/lib/Interpreter/DeclUnloader.cpp, interpreter/cling/lib/Interpreter/DeclUnloader.h, interpreter/cling/test/CodeUnloading/Classes.C
This pull request is a backport of PR #13534 (a NFC; makes the code more readable) and PR #13565 (actual fix for unloading member functions of templated classes).
The aforementioned PRs have been reviewed separately.
For the actual list of changes, see
- https://github.com/root-project/root/pull/13534
- https://github.com/root-project/root/pull/13565
This PR fixes #10049, #6439, #7970, [ROOT-10848](https://sft.its.cern.ch/jira/browse/ROOT-10848) and [ROOT-8084](https://sft.its.cern.ch/jira/browse/ROOT-8084) and (hopefully also [ROOT-8245](https://sft.its.cern.ch/jira/browse/ROOT-8245)).
=> [v628][cling] DeclUnloader: fix unloading of member functions of templated classes

core/metacling/src/TCling.cxx, core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingCallbacks.h, interpreter/cling/include/cling/MetaProcessor/MetaSema.h, interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.cpp, interpreter/cling/lib/Interpreter/IncrementalJIT.cpp, interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp, interpreter/cling/lib/MetaProcessor/MetaParser.cpp, interpreter/cling/lib/MetaProcessor/MetaSema.cpp
=> [cling] Replace llvm::Optional, llvm::None with their std equivalents

core/metacling/src/TClingCallbacks.cxx, interpreter/cling/lib/Interpreter/LookupHelper.cpp, interpreter/cling/lib/Utils/AST.cpp
Removes the usage of `llvm::makeArrayRef` in cling and use deduction guides (https://reviews.llvm.org/D140896) instead.
This PR fixes #14219
=> [cling] Use deduction guides for llvm::ArrayRef

tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx
This PR fixes the way data member offsets are determined for `std::pair` fields. The previous implementation used an auto-generated TClass for `std::pair` without its information loaded in the interpreter (as explained in #14084), which for ROOT builds *with* runtime C++ modules enabled is no problem, but without would need the addition of some dictionaries, most notably for `std::map` fields.
In #14084, a fix is proposed which works. However, I also discovered that the way that is currently used to get the data member offsets for `std::tuple` fields through `TRealData` also works, so I opted to implement that one instead for consistency's sake (if there are reasons this implementation is problematic, we should also change it for `RTupleField`).
=> [ntuple] Fix the way `RPairField` determines member offsets

math/matrix/src/TDecompBase.cxx, math/matrix/test/CMakeLists.txt, math/matrix/test/testMatrixTDecomp.cxx
Small bug in calculation of product of diagonal terms in LU matrix decompositions
This PR fixes #13110
=> Fix bug in DiagProd calculation

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
The RooWorkspace factory language should not be used inside the HistFactory implementation, because each time you use `RooWorkspace::factory()`, the interpreter is called.
For very large workspaces, the excessive number of interpreter calls can crash the process, because memory allocation is growing.
This avoids the memory allocation problem in the interpreter that was reported on the forum:
https://root-forum.cern.ch/t/cling-jit-session-error-cannot-allocate-memory/56744
=> [RF] Avoid factory language in HistFactory

math/minuit2/src/CMakeLists.txt, math/minuit2/src/math/CMakeLists.txt
Instead of hard-coding 'lib' as the path to which minuit2 is installed as a standalone library, use the user configurable CMAKE_INSTALL_LIBDIR. As a particularly common example, this allows a user to specify the library installation path to '${_prefix}/lib64' for 64-bit machines from the cmake command line.
This is part of upstreaming patches that I use to build packages for root on openSUSE [1].
[1] https://build.opensuse.org/package/show/science/root6
=> Minuit2: Install libs to CMAKE_INSTALL_LIBDIR.

gui/browsable/inc/ROOT/Browsable/RProvider.hxx
Prevent a potential crash on Windows in Debug mode when the multimap is empty
=> Add a safety check on `std::multimap::empty()`

gui/browsable/inc/ROOT/Browsable/RProvider.hxx
Prevent a potential crash on Windows in Debug mode when the multimap is empty
=> [v6-30] Add a safety check on `std::multimap::empty()`

gui/browsable/inc/ROOT/Browsable/RProvider.hxx
Prevent a potential crash on Windows in Debug mode when the multimap is empty
=> [v6-28] Add a safety check on `std::multimap::empty()`

roofit/hs3/src/JSONFactories_HistFactory.cxx
In the current implementation, shapesys with no valid data (all constraints constant) are written out in an invalid way, making it impossible for the reader to then instantiate the correct number of parameters.
This PR fixes this by forcing the write-out of data with all-zeros for such invalid shapesys.
Alternatively, one could imagine dropping these shapesys completely, but that's maybe something of a policy decision that I don't want to make in a bugfix patch :)
=> [RF][HS3] Bugfix for fully constrained shapesys

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
Fixing a crash in HistoToWorkspaceFactoryFast.cxx where a parameter that was globally set to be constant was not found a given region, but the code was still accessing the parameter even when it was nullptr. 
Now the parameter is set to constant only when found in a given region. Also demoting the error to warning as this does not always indicate a wrong setup.
This PR fixes #14225
=> [RF][HF] Do not access non-existent parameter when setting it to const in HistoToWorkspaceFactoryFast

interpreter/CMakeLists.txt
This looks like a regression from https://github.com/root-project/root/commit/7a1cc8ffe576490b2f977ba2c262e10ec53a797a#diff-93558e500b17901f800fbb40a2c2fdfd6ee229077db63413bd4a91ee7ec66ea7. It seems like interpreter/llvm-project/llvm/tools/clang would not be a thing, while a following compilation error is observed with builtin_llvm=OFF:
In file included from interpreter/cling/lib/Utils/AST.cpp:12:
In file included from interpreter/llvm-project/clang/include/clang/AST/ASTContext.h:18:
interpreter/llvm-project/clang/include/clang/AST/ASTFwd.h:21:10: fatal error: 'clang/AST/DeclNodes.inc' file not found
#include "clang/AST/DeclNodes.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
=> [cling] interpreter/CMakeLists.txt: correct CLANG_INCLUDE_DIRS

config/thisroot.sh
This PR aims to address #14085 by making thisroot.sh identify the shell correctly even when run under qemu, for example in emulated docker containers.
When qemu is run, then `/proc/$$/comm` contains the name of the command that is emulated.
This PR fixes #14085.
Before:
```console
(Fri Dec-15 2:11:32pm)-(CPU 20.2%:0:Net 1)-(root:/)-(64K:21)
> source thisroot.sh
ERROR: must "cd where/root/is" before calling ". bin/thisroot.sh" for this version of "aarch64-binfmt-P"!
(ERROR)-(Exit Code 1)-(General error)
(Fri Dec-15 2:11:37pm)-(CPU 20.2%:0:Net 1)-(root:/)-(64K:21)
```
After:
```console
(Fri Dec-15 2:12:57pm)-(CPU 20.2%:0:Net 1)-(root:/)-(16M:23)
> source thisroot.sh
(Fri Dec-15 2:13:00pm)-(CPU 20.2%:0:Net 1)-(root:/)-(16M:23)
```
=> thisroot.sh: if exe contains qemu, use /proc/$$/comm instead

interpreter/CMakeLists.txt
This looks like a regression from https://github.com/root-project/root/commit/7a1cc8ffe576490b2f977ba2c262e10ec53a797a#diff-93558e500b17901f800fbb40a2c2fdfd6ee229077db63413bd4a91ee7ec66ea7. It seems like interpreter/llvm-project/llvm/tools/clang would not be a thing, while a following compilation error is observed:
In file included from interpreter/cling/lib/Utils/AST.cpp:12:
In file included from interpreter/llvm-project/clang/include/clang/AST/ASTContext.h:18:
interpreter/llvm-project/clang/include/clang/AST/ASTFwd.h:21:10: fatal error: 'clang/AST/DeclNodes.inc' file not found
#include "clang/AST/DeclNodes.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
(cherry picked from commit 1477d3adebf27a19f3a8b85f21c27a0a5649c7ff)
=> [cling] interpreter/CMakeLists.txt: correct CLANG_INCLUDE_DIRS [v6.30]

roofit/roofitcore/src/RooGenProdProj.cxx
At some point in `RooGenProdProj::createIntegral()`, an intermediate integral object that should only live during the scope of the function is accidentally put in the `saveSet` output parameter. This needs to be fixed.
Thanks to the following forum post for noticing this: https://root-forum.cern.ch/t/error-inputarguments-rooargset-error-argument-with-name-is-already-in-this-set-in-roomcstudy/57571
=> [RF] Fix ownership problem in `RooGenProdProj`

tmva/sofie/inc/TMVA/ROperator_Comparision.hxx, tmva/tmva/src/MethodDL.cxx
=> [tmva] Fix warnings in TMVA

core/base/src/TString.cxx
By defining `TString::kNPOS` out of class, the symbol is materialized properly also with LLVM>=13.
Related to https://github.com/cms-sw/cmssw/issues/43077
Using the snippet at https://github.com/cms-sw/cmssw/issues/43077#issuecomment-1781108225 , these are the numbers reported by different ROOT versions:
```
$: for n in `ls *.log`; do echo $n; grep openat $n | sed 's|.*, "||;s|".*||' | sort | uniq | wc -l; done
master-2023-12-18-knpos-constexpr-run.log
2579
master-2023-12-18-knpos-out-of-class-run.log
307
master-2023-12-18-run.log
2577
v6-26-14-run.log
293
v6-28-00-knpos-constexpr-run.log
2578
v6-28-00-knpos-out-of-class-run.log
304
v6-28-00-run.log
2798
```
Note specifically `v6-28-00-knpos-out-of-class-run.log` and `master-2023-12-18-knpos-out-of-class-run.log` which correspond to …
=> [core] Properly define TString::kNPOS data member according to standard C++

cmake/scripts/ROOTConfig.cmake.in
if `find_package(ROOT)` command list required components like: `find_package(ROOT REQUIRED COMPONENTS Gpad)`
one can decide if external `nlohmann/json` really needed. If no components specified - always search for external, of course if builtin is not used
Address #14188
=> [cmake] clarify search for nlohmann_json

tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx, tree/dataframe/inc/ROOT/RDF/RMetaData.hxx, tree/dataframe/inc/ROOT/RDF/RSample.hxx, tree/dataframe/inc/ROOT/RDF/RSampleInfo.hxx, tree/dataframe/inc/ROOT/RDFHelpers.hxx, tree/dataframe/src/RDatasetSpec.cxx, tree/dataframe/src/RMetaData.cxx, tree/dataframe/src/RSample.cxx, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
Several of the RDF classes (RMetaData, RSample, RSampleInfo) were missing some of the documentation and examples of usage. Additionally, in the process of fixing those noticed a few typos in RDatasetSpec and df106 tutorials.
=> [DF][NFC] Add missing documentation to several RDF classes. 

math/mathmore/inc/Math/Polynomial.h, math/mathmore/src/complex_quartic.h, math/mathmore/test/CMakeLists.txt, math/mathmore/test/testPolynomialRoots.cxx
Uncomment some different code that is used to compute the discriminat of the
resolvent cubic equation used to find the roots of a quartic equation. 
This different code seems to be better numerically. 
This fixes #6900
Add tests for quartic equations to validate code.
=> Fix in complex_quartic  problem reported in issue #6900 and add test

README/ReleaseNotes/v632/index.md, build/unix/makepchinput.py, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooAbsOptTestStatistic.h, roofit/roofitcore/inc/RooAbsTestStatistic.h, roofit/roofitcore/inc/RooChi2Var.h, roofit/roofitcore/inc/RooNLLVar.h, roofit/roofitcore/inc/RooXYChi2Var.h
The old test statistic headers and classes should not be used anymore,
since the test statistics should be created with the higher-level
functions `createNLL()` and `createChi2()`. This allows us more
flexibility in the implementation, and to phase out the old test
statistics classes eventually.
=> [RF] Deprecate old test statistics headers

roofit/roofit/inc/RooGExpModel.h, roofit/roofit/inc/RooGaussModel.h, roofit/roofit/src/RooGExpModel.cxx, roofit/roofit/src/RooGaussModel.cxx, roofit/roofitcore/inc/RooTruthModel.h, roofit/roofitcore/src/RooTruthModel.cxx
This gives us more freedom when refactoring things to also support code
generation with AD.
Also apply other code modernizations, like less use of `TString` or
delegating constructors.
=> [RF] Move internal enums of RooResolutionModels out of public interface

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
I noticed that later bits of the code assume globalObservables set exists, so we should create it, even if it is empty at this point in time
=> [RF][HF] Ensure globalObservables is always created, even if no lumiError

CMakeLists.txt
As done by `interpreter/llvm-project/cmake/Modules/CMakePolicy.cmake`, but this resolves many warnings when building with `builtin_llvm=OFF` (but `builtin_clang=ON`):
```
CMake Warning (dev) at /usr/lib64/cmake/llvm/TableGen.cmake:95 (add_custom_command):
Policy CMP0116 is not set: Ninja generators transform DEPFILEs from
add_custom_command().  Run "cmake --help-policy CMP0116" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Call Stack (most recent call first):
interpreter/llvm-project/clang/cmake/modules/AddClang.cmake:25 (tablegen)
interpreter/llvm-project/clang/include/clang/AST/CMakeLists.txt:73 (clang_tablegen)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> [cmake] Set policy CMP0116 to OLD

cmake/modules/FindR.cmake
- On Windows, attempts to find R in the default installation paths if not found via `find_program`.
- Does the same for the `R_LIBRARY` variable, which may not be reported by the R executable on Windows.
- Adds an `R_SCRIPT` variable to provide the path to RScript. This is useful if the parent CMake script wants to call R non-interactively to run a script. Fixed a typo in the comments.
Adds support for CMake to find R on Windows.
=> Enhance CMake FindR module

tree/treeplayer/inc/TBranchProxy.h
nvc++ issued a warning on the last return statement being unreachable.
Said warning
=> Refactor TBranchProxy::GetReadType to fix nvc++ warning

core/foundation/inc/TError.h, core/foundation/src/RLogger.cxx, core/foundation/src/TError.cxx
The variables present in TError.h are used throughout the ROOT libraries. Anytime one of these variables is requested, e.g. with a simple test such as `python -c "import ROOT; ROOT.kError"`, the interpreter will lookup the corresponding symbol. Previously, the variables were declared and defined in the header directly but were not generating any symbol since the linkage was internal. With this commit, provide external linkage to these variables so that the corresponding symbols are materialized in libCore.so. As a consequence, a huge number of extra lookups by cling is avoided.
This is in direct reference to https://github.com/root-project/root/pull/14261#issuecomment-1863067950 , a followup issue to the original issue at https://github.com/cms-sw/cmssw/issues/43077
These are the results …
=> [core] Materialize symbols for TError variables

core/base/inc/TString.h
Makes std::string_view comparison operators constexpr to be consistent with the std defintions.
This PR fixes #14244
=> Remove std::string_view comparison operators

core/foundation/inc/TError.h, core/foundation/src/RLogger.cxx, core/foundation/src/TError.cxx
=> [6.28] Backport of #14276

math/mathmore/test/CMakeLists.txt
```
CMake Warning (dev) at cmake/modules/RootMacros.cmake:1409 (add_executable):
Policy CMP0115 is not set: Source file extensions must be explicit.  Run
"cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
```
=> [cmake] Fix warning about implicit file extensions

tmva/tmva/src/MethodLD.cxx
Fix  a debug assertion failure with `vector iterators incompatible` error on Windows in debug mode.
In `std::vector<Float_t>::const_iterator it = ev->GetValues().begin()`, `it` is initialised to `GetValues().begin()` and is then compared by `!=` to `GetValues().end()`. But `getValue()` returns a vector by value, not by reference, so it returns a copy, which means that every time we call `getValue()`, we get a different vector, so we get incompatible iterators. For the compiler, this does not make any difference. Type safety does not help, two iterators which belong to different container instances have the same type, so the code compiles. At run time, however, additional checks are made to ensure that two iterators that are being compared really belong to the same container object. (As …
=> Fix an assertion failure on Windows

io/io/src/TDirectoryFile.cxx
If one does:
```
TFile* aFile = new TFile("/tmp/tnamed.root", "RECREATE");
TNamed("TIME/CLK", "0x6").Write();
aFile->ls();
```
nothing is printed
Solution proposed by pcanal in https://github.com/root-project/root/pull/13217
=> [io] TFile::ls skips keys with slash in their name

bindings/pyroot/cppyy/CPyCppyy/inc/CPyCppyy/API.h, bindings/pyroot/cppyy/CPyCppyy/src/API.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPDataMember.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h, bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CallContext.h, bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx, bindings/pyroot/cppyy/CPyCppyy/src/Converters.h, bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/CPyCppyy/src/DeclareConverters.h, bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx, bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.h, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.cxx, bindings/pyroot/cppyy/CPyCppyy/src/PyStrings.h, bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx, bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx, bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx, bindings/tpython/src/TPython.cxx
Since ROOT 6.22 is the second latest ROOT version that CMS uses in production, I need to make it compile again in order to do some validations. This means some PyROOT fixes need to be backported to make it compile again with newer Python versions:
* https://github.com/root-project/root/pull/10734
* https://github.com/root-project/root/pull/6994
* https://github.com/root-project/root/pull/7022
* https://github.com/root-project/root/pull/7961
* https://github.com/root-project/root/pull/8036
* https://github.com/root-project/root/pull/8257
* https://github.com/root-project/root/pull/10047
=> [v622] Backport some PyROOT fixes

math/mathmore/src/complex_quartic.h
This restores the old computation before commit f65064583d and instead solves the problem by allowing a small numerical difference from 0. Fixes the test `testPolynomialRoots` on `mac14arm` where floating point operations are fused differently from other platforms.
=> Avoid strict zero comparison in complex_quartic

hist/hist/src/TEfficiency.cxx
Fix the legend as reported and suggested in the ROOT Forum [here](https://root-forum.cern.ch/t/tefficiency-example-slightly-wrong-what-is-the-default-confidence-level/57480)
=> [hist] [skip-ci] Fix legend in TEfficiency doc example

interpreter/cling/tools/plugins/clad/CMakeLists.txt
This fixes `builtin_llvm=OFF` builds on at least EL8 platforms that currently have exactly LLVM 16.0.6.
=> [cling] Fix clad build with LLVM_LIBDIR_SUFFIX

.github/workflows/root-ci.yml
Fedora 37 reached end-of-life on 2023-12-05:
https://en.wikipedia.org/wiki/Fedora_Linux
See the section "Releases".
We should therefore consider removing it from the CI.
This commit is made now because the outdated xrootd version in the Fedora 37 repos is a problem from migrating to the XRootDConfig.cmake file shipped by XRootD itself (see #14180).
=> [CI] Remove Fedora 37 from the CI workflows

tmva/tmva/inc/TMVA/RReader.hxx
fixes bug reported in the forum [here](https://root-forum.cern.ch/t/rreader-and-spectator-variables/42844)
=> [TMVA] RReader: allow spectators in xml file

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/test/ntuple_types.cxx
Items of vectors are read using ReadInClusterImpl, i.e. relative to the cluster of the enclosing vector. The default implementation of the cluster-relative read translates the call into a global-index read using the principle column of the field. Enum fields, however, don't have columns (their sub field has). Thus, the enum field needs to implement the cluster-relative read callback.
=> [ntuple] fix reading of vector of enums

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_batchgenerator.py
Expanded the types that RBatchGenerator can support to all accepted numeric values supported by TTree and RVec.
This PR fixes the problem that some types that should be supported were not.
=> Expanded the types that RBatchGenerator can support

documentation/users-guide/Trees.md
While looking at the documentation for split branches, I noticed a direct contradiction in the user guide:
>   As of ROOT 4.01/00, only `std::vector` of objects can be split.
>   Support for splitting the other type of STL containers will be
>    introduced in the near future.
vs.
> All STL containers are supported.
As now all STL containers are supported, I remove the bullet discussion the ROOT 4.01/00 state.
=> User guide: remove contradiciton on STL splitting

core/metacling/src/CMakeLists.txt
This should fix the following error
```
C:\ROOT-CI\src\core\metacling\src\TCling.cxx : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj
```
=> Use the `/bigobj` compiler flag for `TCling.cxx` in Debug mode on Windows 64

cmake/modules/SetROOTVersion.cmake, config/root-config.in
Fixes https://github.com/root-project/root/issues/14229
=> [root-config] Fix --git-revision:

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
With this change, the use of TFile when creating an `RNTupleInspector` object from an RNTuple name and source path is removed by directly creating the page source instead. This is in accordance with other places that require the opening of an RNTuple (i.e. `RNTupleReader` and `ROOT::RDF::Experimental::FromRNTuple`).
=> [ntuple] Create `RNTupleInspector` directly from page source

geom/gdml/src/TGDMLWrite.cxx, geom/geom/inc/TGeoTessellated.h, geom/geom/src/TGeoTessellated.cxx, geom/vecgeom/inc/LinkDef.h, geom/vecgeom/inc/TGeoVGShape.h, geom/vecgeom/src/TGeoVGShape.cxx
The previous implementation required TGeoTessellated shapes to be read attached to a TGeoManager. This removes the limitation, and allows also reading geometry files containing shapes converted to VecGeom corresponding solids.
* Restructured the `TGeoFacet` helper class, eliminating referencing vertices stored in the associated `TGeoTessellated` object, since this required calling a specific method `TGeoTessellated::AfterStreamer` to fix all the facet objects. The new version moves all vertex operations from TGeoFacet to the TGeoTessellated class, making the latter readable from a root file even if not connected to a `TGeoManager`
* Added persistency to the class `TGeoVGShape` which interfaces `TGeoShape` to `vecgeom::VPlacedVolume`. This allows to write/read geometry files after being …
=> Fixes for TGeoTessellated and TGeoVGShape persistency.

roofit/roofit/inc/RooPoisson.h, roofit/roofitcore/inc/RooMCStudy.h, roofit/roofitcore/inc/RooNameReg.h, roofit/roofitcore/inc/RooNumIntFactory.h, roofit/roofitcore/inc/RooPlot.h, roofit/roofitcore/src/RooHistFunc.cxx, roofit/roofitcore/src/RooMCStudy.cxx, roofit/roofitcore/src/ValueChecking.h, roofit/roostats/inc/RooStats/DebuggingSampler.h, roofit/roostats/inc/RooStats/DebuggingTestStat.h, roofit/roostats/inc/RooStats/MinNLLTestStat.h
When doing binned toy studies with the `RooMCStudy`, one gets nice
printouts every 10 events for progress information.
In the unbinned case, there is an extra printout per toy dataset that
should be removed to be consistent with the binned case and to not
clutter the output.
Closes https://github.com/root-project/root/issues/9489.
The PR also has some commits with code modernization.
=> [RF] Avoid too verbose printout when doing unbinned toy studies

tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR fixes the incorrect calculation of the compressed size by the `RNTupleInspector`. Because the vector of compressed page sizes is not cleared after each loop iteration, the accumulation needs to happen only after the loop has finished.
=> [ntuple] Fix calculation of compressed size with multiple clusters

tutorials/roofit/rf303_conditional.C, tutorials/roofit/rf307_fullpereventerrors.C, tutorials/roofit/rf316_llratioplot.C, tutorials/roofit/rf401_importttreethx.C, tutorials/roofit/rf402_datahandling.C, tutorials/roofit/rf403_weightedevts.C, tutorials/roofit/rf404_categories.C, tutorials/roofit/rf405_realtocatfuncs.C, tutorials/roofit/rf408_RDataFrameToRooFit.C, tutorials/roofit/rf408_RDataFrameToRooFit.py, tutorials/roofit/rf602_chi2fit.C, tutorials/roofit/rf603_multicpu.C, tutorials/roofit/rf605_profilell.C, tutorials/roofit/rf706_histpdf.C, tutorials/roostats/rs101_limitexample.C
Don't rely on implicit `GetValue()` via dereferencing in the RooFit
tutorial `rf408_RDataFrameToRooFit`, because it obscures the fact that
`Book` returns an RResultPtr, which is important to know for the user.
Closes https://github.com/root-project/root/pull/1429.
A second commit in this PR fixes some more memory leaks in the RooFit tutorials.
=> [RF] Clarify in rf408_RDataFrameToRooFit that `Book` yields RResultPtr

README/ReleaseNotes/v630/index.md
Backport of #14005 
Now also backports https://github.com/root-project/root/pull/14019 and https://github.com/root-project/root/pull/14028
=> [v630][relnotes] Add missing contributors

.github/workflows/root-ci-config/buildconfig/ubuntu20.txt
Since commit 9030460858 ("[ntuple] add xxhash3 checksum handling to anchor"), we require xxHash 0.8 while Ubuntu 20.04 only has version 0.7.3 in its package repositories.
=> [ci] Use builtin_xxhash=ON on Ubuntu 20.04

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx
Instead of writing one key per page, the vector of sealed pages can be written into a single key by first reserving an appropriate size.
---
This PR changes the RNTuple embedding into `TFile`s, in particular we can have both schemes now (key per page, key per cluster, or mixture). I think this is fine because the locator information is solely an offset.
=> [ntuple] Implement RPageSinkFile::CommitSealedPageVImpl

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
Without a task scheduler, seal in `CommitPage`. This avoids a page allocation and, in most cases, a copy of the uncompressed buffer (unless the element type is mappable and compression is disabled, in which case the sealed page would otherwise alias the page buffer). It also ensures that `CommitCluster` can vector-commit all sealed pages.
=> [ntuple] RPageSinkBuf: Always seal before CommitCluster

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/src/RNTupleMerger.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx
... instead of the total number of entries. This will make parallel writing much easier because every thread only needs to know about its own cluster size.
=> [ntuple] Pass entries in cluster to `CommitCluster`

geom/geom/inc/TGeoTessellated.h
The function is no longer implemented, see #14327
Can lead to linking issues when undefined symbols are not ignored, e.g., DD4hep DDCAD
=> TGeoTessellated remove TGeoFacet::ComputeNormal declaration

geom/geom/inc/TGeoExtension.h, geom/geom/src/TGeoExtension.cxx
Remove `#include <cassert>` from `TGeoExtension.h` and move it to the `TGeoExtension.cxx` source file, fixing a potential crash of JupyROOT when running on a machine with a different version of the Windows SDK than the one used to build ROOT, as described in the Github issue #14302 and as shown below. The issue comes from this code in `JupyROOT\helpers\utils.py`:
```
def GetGeometryDrawer():
if not hasattr(ROOT,'gGeoManager'): return
if not ROOT.gGeoManager: return
if not ROOT.gGeoManager.GetUserPaintVolume(): return
vol = ROOT.gGeoManager.GetTopVolume()
if vol:
return NotebookDrawer(vol)
```
triggering the autoloading of libGeom, leading to this error:
```
In file included from libGeom dictionary payload:17:
In file included from C:/root-dev/root\include\TGeoExtension.h:15:
In file …
```
=> Fix JupyROOT crash on Windows. Fixes the issue #14302

cmake/modules/FindZeroMQ.cmake, cmake/modules/RootBuildOptions.cmake, cmake/modules/SearchInstalledSoftware.cmake, roofit/roofitZMQ/CMakeLists.txt
So far, ROOT, in particular the `roofit_multiprocess` feature was depending on a feature developed by @egpbos that was not part of the ZeroMQ 4.3.4 release yet. Therefore, it was a bit awkward to check if ZeroMQ had that feature. Now that it's released, we can just do a proper cmake version check.
The only caveat is that ZeroMQ needs to be built with `-DENABLE_DRAFTS`
to work for `roofit_multiprocess`, which is explained in the build
options documentation.
Also, move some compilation flags to specifically RooFitZMQ, where they
are needed.
This PR superseeds two other PRs:
* https://github.com/root-project/root/pull/13995
* https://github.com/root-project/root/pull/9473
=> [cmake] Adapt to ZeroMQ 4.3.5 being now released

geom/geom/inc/TGeoExtension.h, geom/geom/src/TGeoExtension.cxx
Remove `#include <cassert>` from `TGeoExtension.h` and move it to the `TGeoExtension.cxx` source file, fixing a potential crash of JupyROOT when running on a machine with a different version of the Windows SDK than the one used to build ROOT, as described in the Github issue #14302 and as shown below. The issue comes from this code in `JupyROOT\helpers\utils.py`:
```
def GetGeometryDrawer():
if not hasattr(ROOT,'gGeoManager'): return
if not ROOT.gGeoManager: return
if not ROOT.gGeoManager.GetUserPaintVolume(): return
vol = ROOT.gGeoManager.GetTopVolume()
if vol:
return NotebookDrawer(vol)
```
triggering the autoloading of libGeom, leading to this error:
```
In file included from libGeom dictionary payload:17:
In file included from C:/root-dev/root\include\TGeoExtension.h:15:
In file …
```
=> [v6-30] Fix JupyROOT crash on Windows. Fixes the issue #14302

README/ReleaseNotes/v632/index.md, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py, roofit/RDataFrameHelpers/test/testActionHelpers.cxx, roofit/roofitcore/inc/RooDataSet.h, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/test/TestStatistics/testRooRealL.cxx, roofit/roofitcore/test/stressRooFit_tests.h, roofit/roofitcore/test/testRooDataSet.cxx, roofit/roostats/inc/RooStats/NumberCountingPdfFactory.h, roofit/roostats/src/NumberCountingPdfFactory.cxx, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooNLLVar.cxx, roofit/xroofit/src/xRooNode.cxx, test/fit/testFitPerf.cxx, test/fit/testRooFit.cxx, tutorials/roofit/rf609_xychi2fit.C, tutorials/roostats/rs701_BayesianCalculator.C, tutorials/roostats/rs701_BayesianCalculator.py
The other constructors can cause some confusion to the users.
For now, this change is only to see the result of the CI.
=> [RF] Deprecate some RooDataSet constructors

core/foundation/inc/TError.h, core/foundation/src/RLogger.cxx, core/foundation/src/TError.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingCallbacks.h, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/test/TClingDataMemberInfoTests.cxx
The llvm9 JIT issued callbacks when a symbol was missing and we reacted on it by loading the relevant library. In root-project/root@9b2041e3 we have kept the logic but now the JIT started querying more often even for symbols which are okay to be missing. In turn that leads to scanning all libraries causing performance issues.
This patch tries to limit this functionality only in contexts where automatic loading is allowed. In addition when computing the offsets of a constant variable declaration we compute the initializers instead of searching in the shared objects.
=> [core] Reduce symbol search only to when autoloading is enabled.

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
This PR adds the following fixes and improvements to `RNTupleInspector::GetPageSizeDistribution`:
* When the provided column type is not present in the RNTuple being inspected, an empty histogram is returned.
* When a provided column ID is not present in the RNTuple being inspected, an exception is thrown.
* Default axis titles have been added.
* An overloaded method to provide multiple column IDs at once has been added. The method taking only one ID has been adapted to use this overload.
* The option to provide multiple column types at once has been added. Here, a `THStack` is returned rather than a `TH1D`. The method taking only one type has been adapted to use this overload.
=> [ntuple] Further improve `RNTupleInspector::GetPageSizeDistribution`

tutorials/tmva/TMVA_SOFIE_GNN_Parser.py
Fix the creation of TTree branches in PyROOT using std::vector for C++20
One does not need to use std::address of std::vector object in the `TTree::Branch` function, but just the std::vector object directly thanks to PyROOT pythonizations
=> [tmva][sofie] Fix TMVA_SOFIE_GNN_Parser  tutorial for C++20

core/base/inc/TString.h, core/base/src/TString.cxx, core/foundation/inc/RtypesCore.h
Now that the machinery of https://github.com/root-project/root/pull/14287 is available, we can begin the process of making constants in ROOT `constexpr` to get the benefit of a faster initialization. I began with `TString::kNPOS` and the ones in `RTypesCore.h`, but do let me know if you see other candidates for the same procedure.
=> [core] Make some constants constexpr

tree/tree/inc/ROOT/RFriendInfo.hxx, tree/tree/src/InternalTreeUtils.cxx, tree/tree/src/RFriendInfo.cxx, tree/tree/test/friendinfo.cxx
For consistency with the rest of libTree.
=> [tree] Prefer Long64_t to int64_t for the number of TTree entries 

math/mathcore/src/Fitter.cxx, tutorials/fit/combinedFit.C
This fixes a bug introduced in 6.30 for returning the chi2 value when the user provides his own chi2 using `Fitter::FitFCN`, for example in the tutorial combinedFit.C
See https://root-forum.cern.ch/t/problem-with-root-chi2/57649
=> [math][fitter] Fix return chi2 when fitting user provided chi2 functions

core/base/inc/TString.h, core/base/src/TString.cxx, core/foundation/inc/RtypesCore.h, core/foundation/inc/TError.h, core/foundation/src/RLogger.cxx, core/foundation/src/TError.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingCallbacks.h, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/test/TClingDataMemberInfoTests.cxx
Backports of #14287 and #14352
=> Backport cling fixes for CMS

hist/hist/src/TH1.cxx
Fix the case of using KS test when one of the histogram has zero errors (i.e is a function). Improve KS test adding possibility to specify number of toys by using option "X=number" for example "X=1000"
This PR fixes  the issue #13697
=> [hist] Fix TH1::KolmogorovTest with option X when one histogram has zero errors

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_gnn.py, tmva/sofie/src/RFunction.cxx, tmva/sofie/src/RFunction_MLP.cxx, tmva/sofie/src/RModel_GraphIndependent.cxx
Support now using Linear updates for edges, nodes and globals and support also null  updates. When no updates are provided, the output nodes/edges/globals should be equal to input ones This PR provides now the support for this in the parsing and in the generated code.
The tutorial TMVA_SOFIE_GNN_Parser.py creates as example a graph_nets model containing an output transform where the edge update is Linear and the Node/global updates is Null.
=> [tmva][sofie] Add support for parsing Linear layers from graph_nets and null updates

CMakeLists.txt, core/CMakeLists.txt
Make sure `etc/gitinfo.txt` is generated before building ROOT. This should fix the following errors when building from scratch:
```
Generating G__Gui.cxx, ../../bin/libGui_rdict.pcm, ../../bin/libGui.rootmap
Error in <UnknownClass::ReadGitInfo()>: Cannot determine git info: etc/gitinfo.txt not found!
```
=> Always generate `etc/gitinfo.txt` before building ROOT

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h, interpreter/cling/lib/Interpreter/ValuePrinter.cpp, interpreter/cling/test/Prompt/ValuePrinter/SourceLocation.C
Implements value printing for std::source_location.
Running `std::source_location::current()` 
now shows 
`(std::source_location) filename:line:function_name`. 
Using `std::source_location` requires C++20: https://en.cppreference.com/w/cpp/utility/source_location
```
root [0] std::source_location::current()
(std::source_location) ROOT_prompt_0:1:__cling_Un1Qu30
```
This PR fixes #14211
=> [cling] Implement value printing for std::source_location

core/base/inc/TPluginManager.h, core/base/src/TPluginManager.cxx
This was reported at https://github.com/art-framework-suite/art/issues/142 and is due to the combination of
(a) We do not generate dictionary for std::tuple instances (b) When TClass::GetClass is called it tries to load the dictonary until there is a full TClass object is in memory (c) The emulated std::tuple TClass are marked as 'not loaded' (d) Searching for the TClass for a templated class will cost memory (during the lookup of the instantiation). (e) TPluginManager::ExecPluginImpl was looking up the TClass for the typle `std::type< list of arguments>`
The lookup induced in (e)  in the user's case (root built with runtime cxx module on) lead to some memory allocation in Clang while trying to find out if there was now a library or dictionary to load.
This fixes #14199
=> Core: Avoid (indirect) memory hoarding in TPluginManager.

tutorials/tmva/TMVA_CNN_Classification.C, tutorials/tmva/TMVA_RNN_Classification.C
When creating the test data sets for the CNN and RNN tutorials, it is better to create the TTree attached to the output file so we can avoid a potential issue when deleting the file and the TTree's
=> [tmva][tutorial] Fix a potential issue when creating the test data sets for TMVA CNN and RNN tutorials

math/genvector/inc/Math/GenVector/AxisAngle.h, math/genvector/inc/Math/GenVector/Cartesian2D.h, math/genvector/inc/Math/GenVector/Cartesian3D.h, math/genvector/inc/Math/GenVector/Cylindrical3D.h, math/genvector/inc/Math/GenVector/DisplacementVector2D.h, math/genvector/inc/Math/GenVector/DisplacementVector3D.h, math/genvector/inc/Math/GenVector/EulerAngles.h, math/genvector/inc/Math/GenVector/LorentzRotation.h, math/genvector/inc/Math/GenVector/LorentzVector.h, math/genvector/inc/Math/GenVector/Polar2D.h, math/genvector/inc/Math/GenVector/Polar3D.h, math/genvector/inc/Math/GenVector/PositionVector2D.h, math/genvector/inc/Math/GenVector/PositionVector3D.h, math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h, math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h, math/genvector/inc/Math/GenVector/PxPyPzE4D.h, math/genvector/inc/Math/GenVector/PxPyPzM4D.h, math/genvector/inc/Math/GenVector/Quaternion.h, math/genvector/inc/Math/GenVector/Rotation3D.h, math/genvector/inc/Math/GenVector/RotationZYX.h, math/genvector/inc/Math/GenVector/Transform3D.h, math/genvector/inc/Math/GenVector/Translation3D.h
Closes the following JIRA ticket:
https://sft.its.cern.ch/jira/browse/ROOT-9320
=> [math] Add `constexpr` to GenVector constructors

tutorials/dataframe/df014_CSVDataSource.C, tutorials/dataframe/df014_CSVDataSource.py
Fix https://github.com/root-project/root/issues/14333
With this default maker style being the dot, the 3rd plot for this macro looked empty.
It will be fixed when the auto-style will appear. For the time being one needs to set
the marker to something more visible.
=> [skip-ci] The default marker style is dot.

tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/ntuple_limits.cxx
For the moment, there is a test for 10k fields, which is dominated by `RContext::MapSchema()` iterating over columns during the writing, and tests for 100k clusters as well as one for 100k cluster groups, which are spending most of their time to find the next cluster during reading.
=> [ntuple] Add initial limit testing

core/macosx/CMakeLists.txt
=> Build core/macosx only when cocoa=ON

core/base/inc/LinkDef.h
Without this patch we get:
ld: Undefined symbols:
TMacOSXSystem::TMacOSXSystem(), referenced from:
ROOT::new_TMacOSXSystem(void*) in G__Core.cxx.o
ROOT::new_TMacOSXSystem(void*) in G__Core.cxx.o
ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
TMacOSXSystem::~TMacOSXSystem(), referenced from:
ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
ROOT::newArray_TMacOSXSystem(long, void*) in G__Core.cxx.o
ROOT::deleteArray_TMacOSXSystem(void*) in G__Core.cxx.o
typeinfo for TMacOSXSystem, referenced from:
ROOT::GenerateInitInstanceLocal(TMacOSXSystem const*) in G__Core.cxx.o
clang: error: linker command failed with exit code 1
=> core: Allow build on MacOS with Cocoa disable.

core/macosx/CMakeLists.txt
The part
```
"-F/System/Library/PrivateFrameworks -framework CoreSymbolication"
```
is necessary whether Cocoa in enabled or not.
=> Revert "Build core/macosx only when cocoa=ON"

sql/mysql/src/TMySQLServer.cxx
* [sql] alternative for deprecated or removed methods
Fixes https://github.com/root-project/root/issues/14376
See https://dev.mysql.com/doc/relnotes/mysql/8.3/en/news-8-3-0.html#mysqld-8-3-0-deprecation-removal
* fix syntax
Backport of #14378
=> [mysql] alternative for deprecated or removed methods in v8 (#14378)

core/base/inc/TROOT.h, core/base/src/TApplication.cxx, core/base/src/TROOT.cxx, core/gui/src/TBrowser.cxx, core/gui/src/TGuiFactory.cxx, gui/gui/src/TRootGuiFactory.cxx, tree/treeplayer/src/TTreePlayer.cxx
Shrink version of #14189 
I can add generic `TROOT::PrintWebIssuseWarning()` static method if required.
=> [webgui] disable rootrc parameters for web-based widgets, disable --web flag

graf2d/graf/src/TLegend.cxx
As said here:
https://github.com/root-project/root/pull/14382#pullrequestreview-1830470315
This drawing mode is activated when the absolute value of the graph line width (set by [SetLineWidth()](https://root.cern.ch/doc/master/TGWin32VirtualXProxy_8cxx.html#a18a240c3a19b7b71d058ce1da94747e9)) is greater than 99
the condition be changed to >99 instead of >999?
=> [skip-ci] the condition should be >99

tree/dataframe/inc/ROOT/RNTupleDS.hxx, tree/dataframe/src/RNTupleDS.cxx, tree/dataframe/test/CMakeLists.txt, tree/dataframe/test/ClassWithArrays.h, tree/dataframe/test/ClassWithArraysLinkDef.h, tree/dataframe/test/datasource_ntuple.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/ntuple_print.cxx
The most common way to deal with columns containing collections in an
RDataFrame execution is through RVec. The changes in this commit allow
reading on-disk std::array fields as RVecs in memory. A new RArrayAsRVec
RField subclass is implemented with this aim.
UPDATE:
Tests are present for:
1. `std::array`
2. Combinations of `std::array` and `ROOT::RVec` up to 4 levels of nestedness
3. Custom classes containing `std::array` and combinations with `ROOT::RVec` in the data members
=> Enable reading on-disk std::array as RVec 

tutorials/graphs/scatter.C
No need to specify the marker color in that example.
=> [skip-ci] remove useless setting

gui/gui/src/TGComboBox.cxx
Fix bug introduced in https://github.com/root-project/root/commit/bc4e3d3787a30a5e4ccad5371044975f4481232e
fSelEntry is a nullptr or not, depending on which constructor is called. Editable-combo-box constructor leaves fSelEntry as a nullptr, thus guards are needed. There are guards everywhere in the code except in this function.
=> [gui] Editable combo box nullptr access if SetEnabled is called

.github/CODEOWNERS
Fixes a typo in the code owners file
=> [CI] Correct typo in code owners

gui/gui/src/TGComboBox.cxx
Fix bug introduced in https://github.com/root-project/root/commit/bc4e3d3787a30a5e4ccad5371044975f4481232e
fSelEntry is a nullptr or not, depending on which constructor is called. Editable-combo-box constructor leaves fSelEntry as a nullptr, thus guards are needed.
=> [v6-30][gui] Editable combo box nullptr access if SetEnabled is called

cmake/scripts/ROOTConfig.cmake.in
if find_package(ROOT) command list required components like: find_package(ROOT REQUIRED COMPONENTS Gpad)
one can decide if external nlohmann/json really needed. If no components specified - always search for external, of course if builtin is not used
Backport of https://github.com/root-project/root/pull/14192
=> [cmake] clarify search for nlohmann_json [6.30]

math/mathmore/inc/Math/GSLMCIntegrator.h, math/mathmore/inc/Math/MCParameters.h, math/mathmore/src/GSLMCIntegrationWorkspace.h, math/mathmore/src/GSLMCIntegrator.cxx, math/mathmore/src/MCParameters.cxx
Calling `GSLMCIntegrator::SetMode` crashed because the internal workspace was not yet created. 
This PR fixes this and also the way the extra option parameters are retrieved and set in the GSLMCIntegrator. 
A small change in the interface is done by returning now a unique_ptr instead of a row pointer in 
`GSLMCIntegrator::ExtraOptions()`
=> [math][mathmore] Fix setting optional parameters for GSLMCIntegrator

tree/ntuple/v7/doc/architecture.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
Introduces the RFieldBase::RDeleter functor that can destroy a value created by an RField. The deleter interface is virtual and RField descendents implement their own version of it. The deleter works without the corresponding field and therefore is the basis to hand out shared pointers to objects in the RValues returned by the field.
Also switches to new and delete for allocation instead of malloc/free.
=> [ntuple] replace RFieldBase::DestroyValue by deleter

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_modelext.cxx, tree/ntuple/v7/test/ntuple_types.cxx, tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
A context is responsible for preparing a cluster, and will be the unit of parallelisation for concurrent writing. Also has a commit to return `const` reference from `RNTupleWriter::GetModel()`.
=> [ntuple] Refactor RNTupleWriter into RNTupleFillContext

etc/RooFitHS3_wsfactoryexpressions.json, roofit/histfactory/src/ParamHistFunc.cxx, roofit/hs3/src/Domains.cxx, roofit/hs3/src/Domains.h, roofit/hs3/src/JSONFactories_HistFactory.cxx, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/jsoninterface/src/JSONParser.cxx, roofit/jsoninterface/src/JSONParser.h
Fixes various small bugs, makes the implementation more robust and improves error reporting for JSON import of HS3 files.
- errors from the nlohmann_json importer are now correctly forwarded to the user, rather than giving an unspecific "std_exception".
- some missing keys or values no longer trigger segfaults, but instead lead to an actual error being emitted. this includes errors being emitted by ParamHistFuncs if the number of bins is incorrect.
- the version tag has been correctly updated to 0.2
- gaussians can now be imported with "normal_dist" as well, as described by the standard
- the implementation is a bit more lenient when missing some values (e.g. ignoring cases where the histfactory modifier name has been omitted and instead just numbers the systematics)
- the list of …
=> [RF][HS3] Fixes for ATLAS usecase

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/inc/ROOT/RPage.hxx, tree/ntuple/v7/inc/ROOT/RPagePool.hxx, tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RColumn.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RPagePool.cxx, tree/ntuple/v7/src/RPageSourceFriends.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx, tree/ntuple/v7/test/ntuple_endian.cxx
This follows the C++ Core Guidelines item F.16, 'For "in" parameters, pass cheaply-copied types by value and others by reference to const.' `RClusterIndex` consists of two 64-bit values which for most recent platforms with 64-bit pointers is cheap to copy and better to pass in two registers instead of passing a pointer to stack memory. This in turn helps some recursive calls in RNTuple, for example `RColumn::ReadV` (at the moment of writing).
In numbers, this scores a single-digit performance improvement in the usual ATLAS analysis benchmark, -5% analysis runtime on my system. The other usual benchmarks show no changes beyond fluctuations.
This changes was prepared by running
```
$ git grep -l "RClusterIndex &" | xargs sed -i "s/const \(ROOT::Experimental::\)\?RClusterIndex …
```
=> [ntuple] Pass RClusterIndex by value

cmake/modules/RootCPack.cmake
E.g. "root_v6.30.02.Linux-fedora linux39-x86_64-gcc13.2.tar.gz" should really be "root_v6.30.02.Linux-fedora39-x86_64-gcc13.2.tar.gz".
=> [cmake] Remove " linux" in package names:

tree/ntuple/v7/inc/ROOT/REntry.hxx, tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
Can be replaced by `REntry::Get<void>` where needed.
=> [ntuple] remove REntry::GetRawPtr()

bindings/pyroot/pythonizations/python/ROOT/__init__.py, bindings/pyroot/pythonizations/python/ROOT/_facade.py, bindings/pyroot/pythonizations/test/root_module.py
This reimplements the mechanism to provide C++ namespace as Python
modules without replacing the built-in `__import__` function.
Credits to @chrisburr!
=> [PyROOT] Better way to make C++ namespaces appear as Python modules

core/base/inc/TString.h, core/base/src/TString.cxx, core/foundation/inc/RtypesCore.h, core/metacling/src/TCling.cxx, core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingCallbacks.h, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/test/TClingDataMemberInfoTests.cxx
Backports of https://github.com/root-project/root/pull/14358
=> v6-28 Backport cling fixes for ATLAS

hist/hist/src/TGraph.cxx
fixes a typo in the documentation of `TGraph::SetHighlight` in `TGraph.cxx`
=> Fixing a typo in the documentation of TGraph::SetHighlight in TGraph.cxx

documentation/doxygen/htmlheader.html
This PR removes the matomo code in `htmheader.html` for ROOT 6.28
=> Remove matomo code in 6.28

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/src/REntry.cxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_show.cxx, tree/ntuple/v7/test/rfield_vector.cxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx
- Instead of a raw pointer, a deleter, and some custom memory management methods, RValue now stores a shared void pointer to the object to be written to / read from disk. Follow-up PRs are coming to change the `RField::BindValue` API to a shared pointer interface and to change RValue to not return raw pointers.
- Splits the `REntry::CaptureValueUnsafe` API into a shared-pointer based safe `BindValue` and a `BindRawPtr` unsafe version. This could be a separate PR but it ended up here...
It probably makes sense to review the final change set and not go through the transitional commits.
=> [ntuple] use shared pointer in RFieldBase::RValue

interpreter/cling/lib/MetaProcessor/InputValidator.cpp, interpreter/cling/lib/MetaProcessor/MetaLexer.cpp, interpreter/cling/test/Prompt/MetaProcessor/InputValidator.C
=> [cling] Support bare `#` in input line:

core/metacling/test/TClingDataMemberInfoTests.cxx
This is a forward-port of https://github.com/root-project/root/pull/14358/commits/d4f8f6aa802bacb0dd592ae66c90f2a1eeb0cb07 as it was necessary for https://github.com/root-project/root/pull/14358
=> Fix statements at global scope in TCling test

tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx
This solves reading strings of more than 128 characters. It is still wrong for longer strings where the first byte is 255 and the following four bytes hold an integer with the actual length.
=> [ntuple] RTFString: Length is unsigned

tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/src/RDataFrame.cxx
An attempt to make Vary() documentation more clear and consistent (given we have 11 overloads) and up to date, as requested on the forum. 
I built the website locally to check if everything looks ok.
=> [NFC][DF] Improve documentation for Vary()

math/matrix/src/TMatrixT.cxx, math/matrix/test/CMakeLists.txt, math/matrix/test/testMatrixT.cxx
Fixes TMatrixT constructor behavior when it calculates a^(-1) b, which is now possible even when the number of columns of b does not equal the size of a.
Fixes [ROOT-10231](https://its.cern.ch/jira/browse/ROOT-10231).
=> [matrix] fix TMatrixT(a,TMatrixT::kInvMult,b) constructor

gui/browserv7/src/RBrowser.cxx, gui/gui/src/TRootBrowser.cxx, gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx, gui/webdisplay/src/RWebWindowsManager.cxx, net/http/src/THttpServer.cxx
Introduce `RWebWindowsManager::SetLoopbackMode()` to let change binding to loopback device 
Do not expose current directory via webgui http server
Do not provide list of window on default webpage
Do not allow to reconnect to RBrowser
=> [webgui] change loopback via API, do not expose server dirs [6.30]

main/CMakeLists.txt
Use `python3` in the shebang instead of the full path of Python used to build ROOT.
=> Use `python3` in the python tools. Fixes #14416

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/test/ntuple_limits.cxx
This requires some changes to the read path of `RColumn`, first to deduplicate the code and then avoid recursive `RColumn::ReadV` which makes the difference on my system between being able to limit test a single `std::vector` element of size 200k.
=> [ntuple] Limit test many small and large pages

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/test/rfield_vector.cxx
Connect the sub fields prior to connecting the field itself. All uses of ConnectPageSource() are also connecting the sub fields anyway. That makes sense because a connected field without connected sub fields is in a broken state.
@Nowakus This probably affects you
=> [ntuple] make RFieldBase::ConnectPageSource() recursive

interpreter/cling/lib/Interpreter/BackendPasses.cpp, interpreter/cling/lib/Interpreter/BackendPasses.h
- Moves away from the legacy pass manager to the new llvm pass manager. Care is take to ensure the same behavior before and after the update. Could benefit from more testing.
- Adapt the existing passes for the new pass manager.
=> [cling] Move from legacy to new pass manager

main/CMakeLists.txt
Use `python3` in the shebang instead of the full path of Python used to build ROOT.
=> [v6-30] Use `python3` in the python tools. Fixes #14416

bindings/tpython/src/TPyClassGenerator.cxx, bindings/tpython/src/TPython.cxx
This is not much better than using the internals via including private headers, which already got avoided in a previous PR.
=> [PyROOT] Avoid using CPyCppyy internals in TPython via forward declarations

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx
This should be done by the caller to properly handle errors and ensure lifetime longer than the `RPageSinkFile`.
=> [ntuple] Remove API to recreate TFile from RPageSinkFile

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RNTupleMerger.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
Rename the Create() overload the initialized the on-disk dataset to `Init()`. The other overload creates the `RPageSink` object.
Additionally remove unused parameter from `InitImpl()`.
=> [ntuple] disambiguate RPageSink::Create()

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/inc/ROOT/RPage.hxx, tree/ntuple/v7/src/RColumn.cxx
It was called from `GetPackedSize()` which was on the hot path in `RFieldBase::Append()` for mappable fields and various `AppendImpl()`, for example `RVectorField::AppendImpl()`. This change yields more than 10% lower overhead for writing 5 floats, either as separate fields or in a `std::vector`.
---
(the last two commits are optional, found while looking some more into `RPage::GrowUnchecked`, but nothing successful came out)
=> [ntuple] Replace virtual GetBitsOnStorage() with member

core/metacling/test/TClingDataMemberInfoTests.cxx
EXPECT_EQ(A, B) gives more informative errors on failures than EXPECT_TRUE(A == B).
=> Better errors on failures

hist/histpainter/src/THistPainter.cxx, hist/histpainter/src/TPaletteAxis.cxx
This PR fixes [this issue](https://github.com/root-project/root/issues/14499).
It is now possible to set a TH3 palette title with:
```
h3->SetTitle("h3-Title;XXXXX;YYYYY;ZZZZZ;TTTTTT");
```
=> Implement the title for the palette of a TH3

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tclass.py, bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx, bindings/pyroot/pythonizations/src/GenericPyz.cxx, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx, bindings/pyroot/pythonizations/src/PyzCppHelpers.cxx, bindings/pyroot/pythonizations/src/PyzCppHelpers.hxx, bindings/pyroot/pythonizations/src/PyzPythonHelpers.cxx, bindings/pyroot/pythonizations/src/RDataFramePyz.cxx, bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx, bindings/pyroot/pythonizations/src/RTensorPyz.cxx, bindings/pyroot/pythonizations/src/RVecPyz.cxx, bindings/pyroot/pythonizations/src/TClassPyz.cxx, bindings/pyroot/pythonizations/src/TMemoryRegulator.cxx, bindings/pyroot/pythonizations/src/TMemoryRegulator.h, bindings/pyroot/pythonizations/src/TObjectPyz.cxx, bindings/pyroot/pythonizations/src/TPyDispatcher.cxx, bindings/pyroot/pythonizations/src/TTreePyz.cxx
We have to avoid using the CPyCppyy internals in the ROOT pythonization
libray. Otherwise, the ROOT pythonizations will break when updating to the
new CPyCppyy, where the internals have changed a lot.
This commit makes sure the internals are not used where it can easily
avoided by using the public CPyCppyy API, or using the C Python API
directly instead of some private compatibility  macros defined in
CPyCppyy (that were necessary in the past to support both Python 2 and
3).
Furthermore, the private sources of `CPyCppyy` are now not publically
exposed anymore at the CMake level. This means that we are now forced to
include them via relative paths in the ROOT repository. This makes is
much easier to spot remaining usage of the internal headers (it is quite
hard to tell otherwise that …
=> [PyROOT] More use of public CPyCppyy API instead of internals

core/base/inc/TString.h
The `size_type` member is required by the helper macros in the new CPyCppyy that can be used to declare string converters.
See also https://github.com/root-project/root/pull/14507
=> [core] Add `TString::size_type` member

tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx, tree/ntuple/v7/test/ntuple_descriptor.cxx, tree/ntuple/v7/test/ntuple_merger.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/ntuple/v7/test/ntuple_view.cxx, tree/ntuple/v7/test/rfield_variant.cxx, tree/ntuple/v7/test/rfield_vector.cxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx
**Edit**: also removes the `nullptr` checks for user-provided unique pointers. It seems like non-neglible amount of code (if done consistently, which it is currently not) for little benefit. Such cases will crash immediately with a null pointer de-reference. We can still add such checks consistently at a later point.
=> [ntuple] avoid page source/sink in public reader/writer interface

cmake/scripts/ROOTConfig.cmake.in
Fixes ROOTConfig when Vdt was built externally
https://github.com/root-project/root/issues/14113#issuecomment-1925245792
This PR fixes #14113
=> [cmake] ROOTConfig: if not builtin Vdt find it

tree/ntuple/CMakeLists.txt, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RNTupleParallelWriter.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/ntuple_parallel_writer.cxx, tree/ntuple/v7/test/ntuple_test.hxx, tutorials/v7/ntuple/ntpl007_mtFill.C, tutorials/v7/ntuple/ntpl009_parallelWriter.C
A parallel writer enables the creation of multiple `RNTupleFillContext`, where each context prepares independent clusters that are appended to the common ntuple with internal synchronization. At the moment, this synchronization makes sure that only one thread is writing to the file at any moment. Fully parallel writing into reserved offsets can be a future extension, pending further investigation and evaluation.
=> [ntuple] Add initial version of RNTupleParallelWriter

gui/browsable/src/RFieldHolder.hxx, gui/browsable/src/RFieldProvider.hxx, gui/browsable/src/RNTupleBrowseProvider.cxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/test/ntuple_view.cxx
Changes the RNTuple support in RBrowser from page source to the reader interface along the way. It turns out that the views are not only an interface for zero-copy reading but they also provide a quite useful way to read individual fields from a reader.
=> [ntuple] remove page source from pulic view interface

.git-commit-template, CONTRIBUTING.md
This follows the proposal and discussion during the ROOT team meeting on 22/01/2024 (https://indico.cern.ch/event/1368009/). The goal for these new guidelines is to keep the git history as organized as possible, as well as have something to point (new) contributors to.
A few related points/questions remain open:
=> [NFC][CONTRIBUTING] Extend contribution guidelines

README/ReleaseNotes/v632/index.md, bindings/pyroot/pythonizations/python/ROOT/__init__.py, bindings/pyroot/pythonizations/python/ROOT/_facade.py
Wild card imports like `from ROOT import *` stopped working with Python 3.11 given some changes in the CPython API.
For that reason, upstream `cppyy` also dropped support for lazy lookups, which was the feature that enabled wildcard imports: https://github.com/wlav/CPyCppyy/commit/64fd89050a66bf8cb119f236cadd365efa07b005#diff-6160c0eb004dabeedaeb58d804a7ecd3e563d9379e9e7af39623fd38d0bc6a37R352
This commit suggests to document `from ROOT import *` officially as unsupported and remove the corresponding code path in the ROOT facade.
Closes #7669.
=> [PyROOT] Drop support for `from ROOT import *`

tree/ntuple/CMakeLists.txt, tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx, tree/ntuple/v7/test/ntuple_storage.cxx
This class is for internal testing only and can be used to measure the software overhead of serializing elements into pages, without actually writing them onto disk or even serializing the RNTuple headers and footers.
=> [ntuple] Implement RPageNullSink

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/capi.h, bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx, bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/cpp_cppyy.h, core/meta/inc/TDictionary.h, core/metacling/src/TClingClassInfo.cxx
This the upstream version of a patch to ROOT meta that exposes the `isAggregate()` class property from Cling.
The current `master` branch of CPyCppyy relies on this property.
Originally implemented in this commit by @wlav:
https://github.com/wlav/cppyy-backend/commit/fe1c0f114800ab45b8136fa74ade3a71c137e86f
This PR is part of the larger effort to sync `CPyCppyy`:
https://github.com/root-project/root/pull/14507
=> [meta][cppyy] Export `isAggregate` property to TDictionary

tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RNTupleParallelWriter.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_merger.cxx
`RPagePersistentSink::Create` guesses the concrete derived sink without wrapping it in a `RPageSinkBuf`, which is now entirely left in the responsibility of the `RNTupleWriter`.
(as suggested in https://github.com/root-project/root/pull/14519#discussion_r1477061194)
=> [ntuple] Refactor sink creation

tree/ntuple/v7/src/RNTupleModel.cxx, tutorials/v7/ntuple/ntpl010_skim.C
Gives an example of how to create a derived dataset with the RNTuple API.
As an API change, allows accessing a model's default entry while the entry is building. This is safe as values are only added to the entry and existing values remain untouched.
=> [ntuple] add skimming tutorial

.github/workflows/code_analysis.yml, .github/workflows/root-ci.yml, .github/workflows/test-result-comment.yml
If the tag `[skip-ci]` is present in the PR title, the CI builds for that PR will not be executed.
=> [skip-ci] Introduce condition to skip CI for pull requests

core/lzma/src/ZipLZMA.c, core/zip/CMakeLists.txt, core/zip/src/RZip.cxx, core/zip/test/CMakeLists.txt, core/zip/test/ZipTest.cxx
The compression algorithms only see the buffers without the header, so the sizes have to be adjusted accordingly.
Fixes https://github.com/root-project/root/issues/14508
FYI @Dr15Jones
=> [core/zip+lzma] Properly account for header size

core/lzma/src/ZipLZMA.c, core/zip/CMakeLists.txt, core/zip/src/RZip.cxx, core/zip/test/CMakeLists.txt, core/zip/test/ZipTest.cxx
The compression algorithms only see the buffers without the header, so the sizes have to be adjusted accordingly.
Fixes https://github.com/root-project/root/issues/14508, backport of https://github.com/root-project/root/pull/14523
=> [core/zip+lzma] Properly account for header size [v6.30]

core/lzma/src/ZipLZMA.c, core/zip/CMakeLists.txt, core/zip/src/RZip.cxx, core/zip/test/CMakeLists.txt, core/zip/test/ZipTest.cxx
The compression algorithms only see the buffers without the header, so the sizes have to be adjusted accordingly.
Fixes https://github.com/root-project/root/issues/14508, backport of https://github.com/root-project/root/pull/14523
=> [core/zip+lzma] Properly account for header size [v6.26]

interpreter/cling/lib/Interpreter/BackendPasses.cpp
Before the passmanager update, the function `populateModulePassManager` was called instead of `buildPerModuleDefaultPipeline` to set the default passes. But the former did not have `RelLookupTableConverterPass` turned on by default.
This PR fixes #14598
=> [cling] Explicitly disable `RelLookupTableConvertedPass`

tutorials/CMakeLists.txt
Disable tutorials failing on Windows (x86) with VS 2022 v17.8 This is needed to update the build nodes and add the new ones
=> [roofit][skip-ci] Disable failing tests on Windows (x86)

tutorials/CMakeLists.txt
Disable tutorials failing on Windows (x86) with VS 2022 v17.8 This is needed to update the build nodes and add the new ones
=> [v6-30][roofit][skip-ci] Disable failing tests on Windows (x86)

geom/geom/inc/TGeoMaterial.h, geom/geom/inc/TGeoOpticalSurface.h, geom/geom/src/TGeoOpticalSurface.cxx
Adds the support to CONST properties (double scalars) to TGeoOpticalSurface instances.
This MR enables the TGeoOpticalSurface to have the same functionality as the G4OpticalSurface from Geant4.
Since the class TGeoOpticalSurface is only enhanced by additional member data/functions,  the backwards 
compatibility is ensured.
=> Add CONST properties to optical surfaces (as they are supported by Geant4)

tutorials/tree/dictionary/CMakeLists.txt
tutorial/tree/dictionary C++ stand-alone application can not be compiled when the cmake project is generated for xcode. The solution is to explicitly tell cmake that the shared library depends on the ROOT dictionary
New line in the CMakeLists specifying the dependency 
This PR fixes https://github.com/root-project/root/issues/14595
=> Fixed tutorial. Added explicit dependency of shared library on ROOT dictionary

bindings/experimental/distrdf/python/DistRDF/Proxy.py
The error was overly optimistic and may confuse users. This can be the result of literally anything going wrong in the distributed execution
=> Be explicit about reason for error in distributed execution

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
Allows to search for field names only once and not every time the top-level fields get a new binding.
@Dr15Jones This should improve the writing
=> [ntuple] add token-based addressing to REntry

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/ntuple_model.py
By creating an overload with no arguments instead of having one with a default argument. The overload taking a `std::unique_ptr` cannot work with current PyROOT. See #14425
=> Enable RNTupleModel usage in PyROOT

graf2d/graf/src/TTF.cxx
Improvements in the error message displayed when the call to `FT_Set_Char_Size` fails in `TTF::SetTextSize`:
- The error code returned by the call to TTF FT_Set_Char_Size function was lost in the if condition, now it is displayed.
- Adding the display of passed parameters to the error message helps distinguish TTF related errors from context related ones.
This PR fixes the easy part of #14592
=> [graf2d][TTF] Improve SetTextSize error: show code and values

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx
Their `AppendImpl` must return all bytes written by its sub fields.
=> [ntuple] Fix writing of RCollectionFields

tree/dataframe/src/RNTupleDS.cxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/rfield_vector.cxx
Includes moving CommitCluster out of the public RFieldBase interface.
=> [ntuple] remove page source/sink from public RField interface

.github/workflows/root-ci-config/buildconfig/mac12.txt, .github/workflows/root-ci-config/buildconfig/mac13.txt, .github/workflows/root-ci-config/buildconfig/mac14.txt
This PR turns on CCache for mac builds. This will remove a bit of pressure from the build nodes, e.g. for the build of ROOT's llvm during nightlies and all executables of the tests (unless they need to be rebuilt, of course)
=> [ci] Turn on ccache for  macos builds

.github/workflows/root-ci.yml
On apple M2 chips, LLVM assertion slow down the execution of the test suite (>2k tests) by some 20%. This PR aims to check whether this is the case on the Core i7 mac, too.
=> [ci] Disable LLVM assertions on mac X86 builds

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/src/RField.cxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_importer.cxx
Otherwise we get an `RProxiedCollectionField` with identical column representations, but getting the pointer to `RVec` from an `REntry` fails because of the mismatch between `ROOT::VecOps::RVec` and `ROOT::RVec`. Also normalize the latter to the fully qualified name to allow reading previously written ntuples and those by other implementations.
=> [ntuple] Create proper RVec alias fields from importer

interpreter/cling/tools/plugins/clad/CMakeLists.txt, roofit/histfactory/test/testHistFactory.cxx, roofit/roofitcore/test/CMakeLists.txt, roofit/roofitcore/test/testRooFuncWrapper.cxx
This new release includes performance and stability improvements.
See more at: https://github.com/vgvassilev/clad/releases/tag/v1.3
=> [clad] Bump clad version to v1.3.

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_bulk.cxx
Includes a fix in RRVecField::BulkRead for adopted buffer handling.
=> [ntuple] add support for bulk reading into adopted buffer

bindings/jupyroot/python/JupyROOT/helpers/utils.py
Printing a welcome message when importing a module is uncommon in Python and quite old fashioned.
If one wants to see the ROOT version, one can always print `ROOT.__version__` like for many other modules.
=> [PyROOT] Remove JupyROOT welcome message

interpreter/cling/lib/Interpreter/CIFactory.cpp
As noted in #14593, the build fails during a `rootcling` execution when setting `CLING_DEBUG=1` in the environment with
```
error: invalid integral value '0 -fno-omit-frame-pointer' in '-O0 -fno-omit-frame-pointer'
```
Upon investigation, it only works in the ROOT prompt because TCling turns on basic `-O1` unless in `rootcling`. This overrides the (misformed) `"-O0 -fno-omit-frame-pointer"`. Split the argument in two entries and move it after inserting the user-provided arguments to properly apply also on the prompt by now taking precedence over `-O1`.
Closes #14593
=> [cling] Fix disabling optimizations with CLING_DEBUG

math/mathcore/inc/TRandom.h, math/mathcore/src/TRandom.cxx
Add error message for overflow in converting double to ULong64_t
This routine returns now an unsigned 64 bit integer
For large values, larger than 1.84e+19, we print an error message
advising to use the Trandom::PoissonD for such large values,
and return the max value UINT64_MAX
This PR fixes #6927
=> [Math] Change TRandom::Poisson to return a ULong64_t

hist/hist/src/TProfile.cxx
Call ResetStats in TProfile::Add for negative coefficients
This PR fixes #6365
=> [Hist] Call UpdateStats() in TProfile::Add for negative coefficients

bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py, bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py, bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py
The `getattr` pythonization for TDirectory is caching the retrieved objects as attributes of the TDirectory. To check that the objects are not cached initially, there is a check that the TDirectory instance has no attributes at all. This is too strict, as we care only that the supposedly cached attribute is not there.
This commit suggests to explicity check for at attribute with the name of the object.
The reason for changing this now is because the old check would not work anymore with the new CPyCppyy. With the new version, additional lifeline attributes are set by cppyy to manage the lifetimes of objects.
This is a spinoff of the CPyCppyy syncronization PR, which was created to factorize the review process.
=> [PyROOT] Relax overly pedantic `getattr` pythonization tests

graf3d/gl/src/TGLViewer.cxx
Only changes to documentation. Previously `hRotate` and `vRotate` were documented to be degrees while they should be radians. Also `hRotate` appeared twice instead of `vRotate`.
Closes https://github.com/root-project/root/issues/14576
=> [skip-ci] Correct documentation for `TGLViewer::SetPerspectiveCamera`

core/meta/inc/TClass.h
=> [meta] Use correct type in the signature of TClass::SetDeclFile

.clang-format
I noticed that the current `.clang-format` file does not fully comply with the schema (https://clang.llvm.org/docs/ClangFormatStyleOptions.html). I updated the configuration file so it's compliant (I made the choices based on what I thought the original authors wanted to achieve with the selected options). I am not sure if the lack of compliance with the schema is because of updates to `clang-format` or not.
The changes in this PR should only affect style, but these updates may make `clang-format` behave differently than before (because previous options may have being ignored).
=> [skip-ci] Update .clang-format to comply with schema

core/base/inc/TString.h, core/base/src/TRegexp.cxx
Documents preference for std::regex rather than TRegexp
Documentation
This PR fixes #14585
=> [doc][skip-ci] Document preference for std::regex, #14585

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/test/ntuple_basics.cxx
Makes it easy to have an entry whose values are partially managed by RNTuple and partially be the application.
=> [ntuple] add REntry::EmplaceNewValue()

hist/hist/inc/THnSparse.h, hist/hist/src/TH1.cxx, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx
Passing an out-of-range bin to `TH1::AddBinContent`  leads to undefined behavior
Comment added to documentation: `TH1::AddBinContent` do not check bin boundaries, passing an out-of-range bin leads to undefined behavior. The boundary check is not needed because this method should be used only internally, despite being public.
- [x ] updated the docs (if necessary)
https://github.com/root-project/root/issues/14575
=> [skip-ci] AddBinContent does not check bounds: comment added to documentation

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
A templated factory method for the field's type. Returns a unique_ptr<T>. If called with void, returns a unique pointer with a deleter that complains when called. The `unique_ptr<void>` is supposed to be explicitly released (ownership transfer).
@Nowakus FYI
=> [ntuple] add RFieldBase::CreateObject()

roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.h, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/test/testGlobalObservables.cxx
Iron out some inconsistencies in the treatment of global observables with the new CPU evaluation backend.
To check that everything works now, all the tests in `testGlobalObservables` are now done with both the old legacy backend and the new CPU evaluation backend.
=> [RF] Iron out inconsistencies in treatment of global observables

tutorials/v7/ntuple/ntpl001_staff.C, tutorials/v7/ntuple/ntpl002_vector.C, tutorials/v7/ntuple/ntpl003_lhcbOpenData.C, tutorials/v7/ntuple/ntpl004_dimuon.C, tutorials/v7/ntuple/ntpl005_introspection.C, tutorials/v7/ntuple/ntpl006_friends.C, tutorials/v7/ntuple/ntpl007_mtFill.C, tutorials/v7/ntuple/ntpl008_import.C, tutorials/v7/ntuple/ntpl009_parallelWriter.C
C++ runtime modules are now used by default, and it actually seems to not pose any issues for builds that don't have it enabled.
=> [ntuple] Remove `R__LOAD_LIBRARY` from tutorials

bindings/pyroot/pythonizations/test/CMakeLists.txt, bindings/pyroot/pythonizations/test/stl_set.py, bindings/pyroot/pythonizations/test/stl_vector.py
Closes https://github.com/root-project/root/issues/14573.
The pythonization of stl containers should behave in a pythonic way: empty containers should evaluate to false in an `if` statement, etc.
While working on the issue I realized this is already the case, so this PR just adds some python tests that should cover this.
I also added a new test file that checks the `std::set` also behaves as expected.
=> [PyROOT] Add tests for stl containers pythonic behaviour

math/mathcore/inc/TRandom1.h, math/mathcore/inc/TRandom2.h, math/mathcore/src/TRandom.cxx, math/mathcore/src/TRandom1.cxx, math/mathcore/src/TRandom2.cxx
Documentation involving inconsistencies in `TRandom::GetSeed()` methods. In the derived classes the seed variable is used to store internal state of the generator not to keep track of the initial state with which it was invoked.
This PR fixes #14580
=> Improving TRandom::GetSeed() documentation

.clang-format
I authored PR https://github.com/root-project/root/pull/14690 which updated some .clang-format options which were not compliant with the (atleast) latest schema. Some of these options appear not to work with older version of `clang-format` so I simplify them in this PR. the behaviour should remain the same.
=> [ci] Simplify clang-format options for compatibility with older versions

hist/hist/src/TAxis.cxx
As requested here: https://github.com/root-project/root/issues/9917
=> Print a warning when the range given to SetRange is invalid.

tutorials/dataframe/df034_SaveGraph.C, tutorials/eve7/geom_cms.C, tutorials/io/testTMPIFile.C, tutorials/math/Bessel.C, tutorials/math/FeldmanCousins.C, tutorials/math/Legendre.C, tutorials/math/LegendreAssoc.C, tutorials/rcanvas/raxis.cxx, tutorials/rcanvas/rcanvas_mt.cxx, tutorials/rcanvas/rh1.cxx, tutorials/rcanvas/rh1_large.cxx, tutorials/rcanvas/rh1_twoscales.cxx, tutorials/rcanvas/rh2.cxx, tutorials/rcanvas/rh2_colz.cxx, tutorials/rcanvas/rh2_large.cxx, tutorials/rcanvas/rh3.cxx, tutorials/rcanvas/rh3_large.cxx, tutorials/rcanvas/rlegend.cxx, tutorials/rcanvas/subpads.cxx
This PR is a follow-up from #14570 and fixes #14715. It turns out that this is not required anymore, even for builds/platforms without runtime modules enabled.
=> [DF,io,eve7,math,rcanvas] Remove `R__LOAD_LIBRARY` call from tutorials

core/base/src/TSystem.cxx
Unload the library before deleting it (might be needed on Windows)
Delete also the associated files generated with CompileMacro()
Fixes https://github.com/root-project/root/issues/10395
=> [core][aclic] Improve CleanCompiledMacros()

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/test/ntuple_limits.cxx
`NameWithDescription_t` takes a `std::string_view`, but the compiler only attempts one implicit conversion so `std::string` -> `std::string_view` and then to `NameWithDescription_t` doesn't work. Enabling this overload is particularly helpful for programmatically generated field names, as demonstrated by the `Limits_ManyFields` test.
=> [ntuple] Allow MakeField with a std::string

tree/tree/src/TTree.cxx
This PR fixes #14550. I've opted for now to just clarify the documentation, mostly because I'm not sure to what extent we can and want to change the TTree interface at this point.
=> [tree] Further clarify how to clone subsets of branches

tree/ntuple/v7/inc/ROOT/RField.hxx
With some more minimal cmake configurations `assert` is not declared in `RField.hxx` and needs an `#include <cassert>`. `R__ASSERT` is declared however. Additionally, this makes it more consistent with other assertions in `RField`.
=> [ntuple] Use `R__ASSERT` in `RArrayAsRVecField::GenerateColumnsImpl`

tmva/sofie/test/TestSofieModels.cxx
Follow up to https://github.com/root-project/root/pull/14535 , apply the same rule in the rest of the test since it may still fail as seen e.g. in this PR https://github.com/root-project/root/pull/14666
=> [tmva] Completely relax float comparison in TestSofieModels

CMakeLists.txt
This ought to fix the mac12/13 hanging on checking the repository (that does not exist)
FIx #14708
=> Fix GitHub Actions stuck on mac12 and mac13

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx
Adds a dummy shared pointer to RValue: the dummy shared pointer holds the control block with a noop deleter if BindRawPtr is used. The object shared pointer, in this case, shares the control block with the dummy shared pointer (aliasing constructor). In this way, we avoid a memory allocation for the control block every time BindRawPtr is called.
Also some minor improvements to the internals of REntry.
@Dr15Jones FYI
=> [ntuple] reduce memory allocations in BindRawPtr

roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx, roofit/roofitcore/test/TestStatistics/testRooRealL.cxx
The new multiprocessing test statistics were designed to be bit-by-bit compatible with the old test statistics, not the new CPU evaluation backend. Therefore, the old NLL evaluation backend has to be used for the offsetting tests (the new CPU backend is not bit-by-bit compatible with the legacy backend).
This is a followup to commit 65b15d333c, which didn't apply this change to all relevant tests. Doing `EXPECT_EQ` on floats is quite fragile...
=> [RF] Explicitly use legacy backend for references in `testRooRealL`

tree/dataframe/src/RInterfaceBase.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/test/dataframe_datasetspec.cxx
In `ROOT::RDF::SaveGraph`, write "TChain" in the output `.dot` if the `TChain` is unnamed, instead of a blank. In `ROOT::RDF::RInterfaceBase::Describe`, if the `TChain` is unnamed, do not write a blank.
This PR fixes [#10928](https://github.com/root-project/root/issues/10928).
=> [DF] fix SaveGraph display and Describe printout for unnamed TChain

tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
Fixes https://github.com/root-project/root/issues/8711
It was suggested in the issue to enable something like:
```cpp
auto ntuple = RNTupleWriter::Recreate({
RField<std::uint32_t>("id"),
RField<std::vector<float>>("vpx"),
RField<std::vector<float>>("vpy"),
RField<std::vector<float>>("vpz")
}, "NTuple", kNTupleFileName);
```
However, `std::initializer_list` needs homogeneous types, so after discussion with @jblomer , I tried an approach with the list of the pairs of strings, i.e.:
```cpp
auto writer = RNTupleWriter::Recreate({
{"std::uint32_t", "id"},
{"std::vector<float>", "vpx"},
{"std::vector<float>", "vpy"},
{"std::vector<float>", "vpz"},
}, "NTuple", fileGuard.GetPath());
```
=> [ntuple] Allow inline model definition in RNTupleWriter::Recreate

core/base/src/TSystem.cxx, core/base/test/CMakeLists.txt, core/base/test/Foo.C, core/base/test/IncludePathTest.cxx
Should fix https://github.com/root-project/root/issues/10866
=> [core] Improve Include PATH handling & add test

net/http/inc/TRootSniffer.h, net/http/src/TRootSniffer.cxx, net/httpsniff/inc/TRootSnifferFull.h, net/httpsniff/src/TRootSnifferFull.cxx
For any registered to http server object
now one can sumbit request like:
http://localhost:8080/hpx/file.root
THttpServer will create file in memory and store
specified object there.
Either object name will be used or "object" when
name cannot be obtained.
This PR implement new feature from #14594
=> [http] implement `file.root` handler

roofit/roofitcore/src/RooWorkspace.cxx
Imported RooAbsArgs should have their workspace set to the workspace they are being imported to.
Can we please sweep this into 6.30 patches too please.
=> [RF] Set workspace on imported roofit objects

roofit/xroofit/src/xRooNode.cxx
This change needs backporting into 6.30
It fixes issues with display of plots drawn by xRooFit in jupyter notebooks.
=> [RF] Fix for display of canvases in jupyter notebooks

tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/test/ntuple_show.cxx
This PR for now fixes #14748, but IMO down the line we might need a more tailored representation for friends (at least in how they are presented to the user).
Friends are (virtually) represented as untyped records. To properly create them as fields (neede e.g. for `Show` and `PrintInfo`), we artificially bind them to an untyped `RRecordField`.
=> [ntuple] Fix field construction for friends

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_compat.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/ntuple/v7/test/ntuple_test.hxx
The bare file container is only used for testing and therefore should not be part of the public interface.
=> [ntuple] remove ENTupleContainerFormat

math/matrix/inc/TMatrixTSparse.h, math/matrix/src/TMatrixTSparse.cxx, math/matrix/test/testMatrixTSparse.cxx
Enables Transpose to work with rectangular matrices. SetMatrixArray has been modified to reshape the matrix, if needed. A Google Test has been added to test this functionality.
This PR fixes [ROOT-9261](https://its.cern.ch/jira/browse/ROOT-9261)
=> [matrix] Enable Transpose for rectangular matrices

tmva/tmva/inc/TMVA/TSpline1.h, tmva/tmva/inc/TMVA/TSpline2.h, tmva/tmva/src/PDF.cxx, tmva/tmva/src/TSpline1.cxx, tmva/tmva/src/TSpline2.cxx
* Avoids deleting non-owned pointer in destructor
* In a case where the graph does not have enough points for interpolation graph values are returned directly and a warning is emitted; this avoids heap overflow when trying to address graph points outside of the point array range
This PR resolves #8021
=> [TMVA] TSpline2: fix memory issues

tmva/sofie/test/TestSofieModels.cxx
Backport of https://github.com/root-project/root/pull/14738
=> [6.30] [tmva] Completely relax float comparison in TestSofieModels

hist/hist/inc/TF1.h, math/mathcore/inc/Fit/FitResult.h, math/mathcore/inc/Fit/Fitter.h, math/mathcore/inc/Math/FitMethodFunction.h, math/mathcore/src/Fitter.cxx
In the FitFCN/SetFCN functions use a flag for the fit type instead of passing a boolean for the chi2 fit.
The flag is by default 0 (undefined type), but can be 1 (for chi2 fit), so compatible as passing a boolean as before, 2 for unbinned likelihood and 3 for binned likelihood (FCN is defined to be the Baker-Cousins log-likelihood ratio)
By passing the correct flag the function FitResult::Chi2() returns the corresponding Chi2() and the Baker-Cousins chi2 equivalent  in case a binned likelihood fits.
This PR fixes #11143
=> [math][fit] Change FitFCN/SetFCN to pass a flag for the type of fit

tree/ntuple/CMakeLists.txt, tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleCollectionWriter.hxx, tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/src/RNTupleWriter.cxx, tree/ntuple/v7/test/ntuple_test.hxx, tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
Along the way renames RCollectionNTupleWriter class to RNTupleCollectionWriter.
=> [ntuple] split off RNTupleCollectionWriter header

tree/ntuple/CMakeLists.txt, tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx, tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx, tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx, tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx, tree/ntuple/v7/inc/ROOT/RNTupleWriteOptionsDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RNTupleFillContext.cxx, tree/ntuple/v7/src/RNTupleWriteOptions.cxx, tree/ntuple/v7/src/RNTupleWriter.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageSourceFriends.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_test.hxx, tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx, tree/ntupleutil/v7/src/RNTupleImporter.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx, tree/ntupleutil/v7/test/ntupleutil_test.hxx, tutorials/v7/ntuple/ntpl005_introspection.C, tutorials/v7/ntuple/ntpl011_global_temperatures.C
Split RNTupleOptions header in RNTupleReadOptions, RNTupleWriteOptions, and RNTupleWriteOptionsDaos.
=> [ntuple] split RNTupleOptions header

interpreter/cling/lib/Interpreter/AutoloadCallback.cpp, interpreter/cling/lib/Interpreter/BackendPasses.cpp, interpreter/cling/lib/Interpreter/ClangInternalState.cpp, interpreter/cling/lib/Interpreter/ClingCodeCompleteConsumer.cpp, interpreter/cling/lib/Interpreter/DeclUnloader.cpp, interpreter/cling/lib/Interpreter/DefinitionShadower.cpp, interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp, interpreter/cling/lib/Interpreter/ExternalInterpreterSource.cpp, interpreter/cling/lib/Interpreter/ForwardDeclPrinter.cpp, interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/cling/lib/Interpreter/LookupHelper.cpp, interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp, interpreter/cling/lib/MetaProcessor/InputValidator.cpp, interpreter/cling/lib/MetaProcessor/MetaParser.cpp, interpreter/cling/lib/Utils/AST.cpp, interpreter/cling/lib/Utils/Paths.cpp, interpreter/cling/lib/Utils/PlatformWin.cpp, interpreter/cling/lib/Utils/SourceNormalization.cpp
Follows the changes introduced in https://reviews.llvm.org/D136030 to be more compatible with std::string and std::string_view.
=> [NFC][cling] Use StringRef::{starts,ends}_with

tree/dataframe/test/CMakeLists.txt
If external nlohmann/json.hpp used in ROOT,
it also has to be used in the tests
Should fix #14769
=> [cmake] properly use nlohmann in ctest

core/base/inc/TSystem.h, core/base/src/TSystem.cxx, core/base/test/CMakeLists.txt, core/base/test/TSystemTests.cxx, core/unix/inc/TUnixSystem.h, core/unix/src/TUnixSystem.cxx, core/winnt/inc/TWinNTSystem.h, core/winnt/src/TWinNTSystem.cxx, gui/webdisplay/src/RWebDisplayHandle.cxx
Allows to specify extension of temporary-created file.
Used in webgui to create temporary html files to start web widgets
=> [core] Introduce suffix in `TSystem::TempFileName()` method

hist/hist/src/TH1.cxx, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx
=> [skip-ci] fix typo trailing brace in docu

core/metacling/src/CMakeLists.txt
Fix `mt201_parallelHistoFill.C` failing with the following error:
```
779: Processing C:/root-dev/git/master/tutorials/multicore/mt201_parallelHistoFill.C...
779: [runStaticInitializersOnce]: Failed to materialize symbols: { (main, { ?_Swap@?$_Ptr_base@VTH1F@@@std@@IEAAXAEAV12@@Z,
[...]
779: [runStaticInitializersOnce]: Failed to materialize symbols: { (main, { __orc_init_func.cling-module-9 }) }
779: cling JIT session error: Failed to materialize symbols: { (main, { ?mt201_parallelHistoFill@@YAHXZ }) }
779: CMake Error at C:/root-dev/build/x64/debug/RootTestDriver.cmake:232 (message):
779:   error code: 1
```
=> [v6-30][win] Fix failing `std::this_thread::sleep_for` (#14786)

tree/dataframe/test/dataframe_vecops.cxx
The following, very particular, combination triggers a test failure:
* Fedora 39
* C++20
* ROOT built in Release mode (-O3)
* The test `dataframe-vecops`, which needs to be run via ctest and using gtest infrastructure
* The test being compiled in release mode too
The failure is:
```
730/2406 Test  #393: gtest-tree-dataframe-test-dataframe-vecops ........................................................***Failed    5.01 sec
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from RDFAndVecOps
[ RUN      ] RDFAndVecOps.ReadStdVectorAsRVec
[       OK ] RDFAndVecOps.ReadStdVectorAsRVec (4678 ms)
[ RUN      ] RDFAndVecOps.DefineRVec
[       OK ] …
```
=> [DF] Change test to avoid double free on Fedora39

roofit/batchcompute/src/RooBatchCompute.cu, roofit/batchcompute/src/RooBatchCompute.cxx, roofit/roofitcore/inc/RooAddModel.h, roofit/roofitcore/inc/RooAddPdf.h, roofit/roofitcore/inc/RooCompositeDataStore.h, roofit/roofitcore/inc/RooCustomizer.h, roofit/roofitcore/inc/RooFit/Detail/BatchModeDataHelpers.h, roofit/roofitcore/inc/RooLinkedListElem.h, roofit/roofitcore/inc/RooMinimizer.h, roofit/roofitcore/inc/RooMsgService.h, roofit/roofitcore/inc/RooNumConvPdf.h, roofit/roofitcore/inc/RooTreeDataStore.h, roofit/roofitcore/inc/RooVectorDataStore.h, roofit/roofitcore/src/BatchModeDataHelpers.cxx, roofit/roofitcore/src/RooAbsArg.cxx, roofit/roofitcore/src/RooCustomizer.cxx, roofit/roofitcore/src/RooDataSet.cxx, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooGenProdProj.cxx, roofit/roofitcore/src/RooHistPdf.cxx, roofit/roofitcore/src/RooObjCacheManager.cxx, roofit/roofitcore/src/RooPolyFunc.cxx, roofit/roofitcore/src/RooVectorDataStore.cxx, roofit/roofitcore/src/RooWorkspace.cxx, roofit/roofitcore/test/testTestStatistics.cxx, roofit/roofitcore/test/test_lib.h, roofit/roostats/src/BayesianCalculator.cxx, roofit/xroofit/src/xRooNode.cxx
As we discovered in a CMSSW ROOT `master` sync PR, the new RooFit CPU
backend treats empty datasets differently from the legacy NLL evaluation
backend:
https://github.com/cms-sw/cmsdist/pull/9025
This commit is fixing this, in particular removing the assumption that
datasets used for fits with the new CPU backend are never empty.
A unit test that validates the behavior for empty data objects is also
added.
I set the priority to "high" because this is a blocker for CMSSW to use ROOT master.
=> [RF] Consistent treatment of empty datasets with new CPU backend 

tree/dataframe/test/CMakeLists.txt
If external nlohmann/json.hpp used in ROOT,
it also has to be used in the tests
Backport of #14784
=> [cmake] properly use nlohmann in ctest [6.30]

js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/ObjectPainter.mjs, js/modules/base/latex.mjs, js/modules/core.mjs, js/modules/draw/TGraphPolarPainter.mjs, js/modules/draw/TTree.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/display.mjs, js/modules/gui/menu.mjs, js/modules/hist/RH3Painter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TH3Painter.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist/hist3d.mjs, js/modules/hist2d/RH2Painter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/io.mjs, js/modules/tree.mjs, js/scripts/JSRoot.core.js, js/scripts/geoworker.js
List of changes in JSROOT
1. Fix - abort tree draw operation faster
1. Fix - catch exception when parsing TF1 formula
2. Fix - properly check THStack histograms axes when doing sum
3. Fix - correctly handle negative offset on time axis
4. Fix - do not use `inset` because of old Chrome browsers
5. Fix - properly provide object hints
1. Fix - draw histograms with negative bins #276
2. Fix - correctly read TLeaf with fixed-size array
3. Fix - bug in options handling in startGUI
4. Fix - greyscale support in TLegend drawing
5. Fix - correctly use text font for TGaxis title
6. Fix - preserve auto colors in THStack #277
7. Fix - correctly set pave name #278
=> [jsroot] 7.5.x  from 14.02.2024

cmake/modules/RootBuildOptions.cmake
To avoid reports in the forum worrying about whether Minuit2 is gonna be removed.
See https://root-forum.cern.ch/t/will-minuit2-be-removed-from-root/58078
=> [cmake] Make Minuit2 build option deprecation warning less alarming

cmake/modules/RootBuildOptions.cmake, roofit/roofitcore/src/RooWorkspace.cxx, roofit/xroofit/src/xRooNode.cxx
This is a backport of some RooFit PRs that were recently merged to master to v6-30-00-patches:
- https://github.com/root-project/root/pull/14759
- https://github.com/root-project/root/pull/14762
- https://github.com/root-project/root/pull/14814
Related to https://github.com/root-project/root/issues/13458.
Link to the previous backport PR:
https://github.com/root-project/root/pull/14407
=> [v630][RF] Backports of RooFit PRs to `v6-30-00-patches`: Part 10

cmake/modules/RootBuildOptions.cmake
It was deprecated in ROOT 6.30 and should now be removed.
See also 1c74d59d.
=> Remove the `exceptions` build option

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/test/test_headnode.py
Add support for experimental distributed RDataframe when the RDataframe is constructed from an RDatasetSpec object. See https://root-forum.cern.ch/t/using-rdataframe-with-dask-and-rdatasetspec/58230
- Add a class to [HeadNode.py](bindings/experimental/distrdf/python/DistRDF/HeadNode.py) to handle the case where the RDataframe with distributed backend is constructed from an RDatasetSpec object
- Use the above class when constructing the appropriate RDataframe instance
=> Add support for distributed RDataFrame constructed from RDatasetSpec

core/base/src/TApplication.cxx
`root.exe -a`
returns right now a non-understandable error message.
=> [core] note splash screen not seen with root.exe

geom/geompainter/src/TGeoChecker.cxx
Honors the overlap limit requested via the `CheckOverlaps` method when checking overlaps by sampling
This PR fixes #14675
=> When checking overlaps by sampling, use user limit

graf2d/gpad/src/TRatioPlot.cxx, tmva/sofie/src/RModel.cxx
The wrong index was used when filling the TGraphError for the lower plot. TGraph starts from 0 while histogram binning from 1.
Fix also retrieving the fitted function from the histogram
This PR fixes #14838
=> Fix the computation of the Confidence band of TRatioPlot

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageStorage.cxx
`RPageSource` now lives in the `Internal` namespace, so we can make the `UnsealPage` method public. This gives the possibility to get the contents of individual columns for benchmarking and testing purposes.
=> [ntuple] Make `RPageSource::UnsealPage` public

js/build/jsroot.js, js/changes.md, js/modules/base/BasePainter.mjs, js/modules/base/ObjectPainter.mjs, js/modules/base/base3d.mjs, js/modules/core.mjs, js/modules/draw/TLinePainter.mjs, js/modules/draw/TRatioPlotPainter.mjs, js/modules/draw/TTree.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/io.mjs
Correctly scale axes labels and title sizes. One have to use main pad dimensions.
Do not rescale vertical axis labels if space is too low.
Correctly draw ratio plot lines after zooming
Fix rounding problem with TLine positions
Fixes #14842 and #14546 (web part)
=> [jsroot] dev 28/02/2024 with TRatioPlot fixes

tutorials/CMakeLists.txt
`mtbb201_parallelHistoFill.C` fails on Windows x86 and VS v17.9 with the following error:
```
IncrementalExecutor::executeFunction: symbol '_Thrd_sleep_for@4' unresolved while linking [cling interface function]!
```
Due to this line:
```
std::this_thread::sleep_for(std::chrono::duration<double, std::nano>(500));
```
=> [windows] disable mtbb201_parallelHistoFill.C

tutorials/CMakeLists.txt
`mtbb201_parallelHistoFill.C` fails on Windows x86 and VS v17.9 with the following error:
```
IncrementalExecutor::executeFunction: symbol '_Thrd_sleep_for@4' unresolved while linking [cling interface function]!
```
Due to this line:
```
std::this_thread::sleep_for(std::chrono::duration<double, std::nano>(500));
```
=> [skip-ci][v6-30][windows] disable mtbb201_parallelHistoFill.C

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx, tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
`RNTupleDescriptor::GetColumnIterable` returns an iterator over all *logical* columns, causing projected fields to be considered as well in the size calculation by the RNTupleInspector. With this fix, projected fields are skipped.
=> [ntuple] Fix size calculation for projected fields

bindings/experimental/distrdf/python/DistRDF/HeadNode.py, bindings/experimental/distrdf/python/DistRDF/Ranges.py
This is a very quick fix in order to test the distributed RDF with RNTuples. It was locally tested with some tutorials and AGC, but no tests are added yet (to be done soon).
=> [DF] Add support for RNTupleHeadNode for the distributed RDF

core/testsupport/src/TestSupport.cxx, io/io/src/TFileMerger.cxx, tree/ntuple/v7/src/RNTupleMerger.cxx, tree/ntuple/v7/test/ntuple_merger.cxx
This PR integrates recently developed `RNTupleMerger` (#13858) into `TFileMerger` so that it can be used via `hadd` etc. For the time being, the PR is in draft mode to facilitate the discussion.
=> [ntuple] Integrate RNTupleMerger into TFileMerger

gui/gui/src/TGFSContainer.cxx
Silence "Can't read file attributes" with protected system files on Windows.
This addresses the following topic on the Forum:
[TGFileDialog multiple "Can't read file attributes" errors on Windows](https://root-forum.cern.ch/t/tgfiledialog-multiple-cant-read-file-attributes-errors-on-windows/58342)
=> [GUI] Silence TGFileDialog error messages

core/meta/src/TClass.cxx
Typo in `TClass *TClass::GetClass` docs in `TClass.cxx` file.
=> Fixing Typo in TClass *TClass::GetClass

geom/geom/inc/TGeoVolume.h, hist/hist/inc/TGraph.h, hist/hist/inc/TSpline.h
@pcanal mentioned that ::SaveAs overloads should have the same number of default arguments as TObject::SaveAs, see https://github.com/root-project/root/pull/14713/files#r1508200980.
This fixes it, together with https://github.com/root-project/root/pull/14864.
=> missing defaults in SaveAs overload

io/io/CMakeLists.txt, io/io/inc/ROOT/RRawFileTFile.hxx, io/io/test/RRawFile.cxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_merger.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
The `RRawFileTFile` wraps an open `TFile`, but does not take ownership. This enables opening `RNTuple` anchors from `TFile`s that are not natively supported by `RRawFile`, for example `TMemFile` as used by `TBufferMerger`.
=> [io/ntuple] Use RRawFileTFile for non-supported protocols

main/src/hadd.cxx
Fixes https://github.com/root-project/root/issues/6616
While looking into this, I noticed that the `newcomp` variable is passed down the line to `TFileMerger::OutputFile`, which is declared at https://github.com/root-project/root/blob/master/io/io/inc/TFileMerger.h#L115 with a wrongly named parameter `compressionLevel`. That is in fact the full compression setting integer. Maybe the logic in `hadd` was misguided by the parameter name, I can take care of that in a separate PR.
Sibling roottest PR at https://github.com/root-project/roottest/pull/1074
=> [main] Pass full compression setting from hadd

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx, tree/ntuple/v7/inc/ROOT/RNTupleView.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleReader.cxx, tree/ntuple/v7/test/ntuple_view.cxx
Enable an ATLAS use case where the reading pattern is to read one specific entry of one specific field into a previously allocated memory location. Using the RNTupleView ensures only that field is actually read from disk.
@Nowakus FYI
=> [ntuple] Enable binding view to external memory

core/base/inc/TVirtualPad.h, graf2d/gpad/inc/TPad.h, graf2d/gpad/src/TPad.cxx
Short cut to call Modified() and Update() in a single call.
On Mac with Cocoa, it performs an additional ProcessEvents().
=> A shortcut to perform Modified and Update

.github/workflows/root-ci-config/buildconfig/ubuntu2304.txt, .github/workflows/root-ci.yml
because it's not supported since February 1st:
https://ubuntu.com/about/release-cycle
=> [ci] Remove Ubuntu 23.04 from testing platforms

.github/workflows/root-630.yml, .github/workflows/root-ci.yml, .github/workflows/root-master.yml
and allow to use the root-ci.yml in the v6-30-00-patches to treat the configuration of the builds of branches as regular code.
=> [skip-CI][ci] Simplify yml files configuring nightlies

interpreter/cling/tools/plugins/clad/CMakeLists.txt
This new release includes several fixes helping to simplify RooFit AD backend.
See more at: https://github.com/vgvassilev/clad/releases/tag/v1.4
=> [clad] Bump clad version to v1.4.

graf2d/gpad/CMakeLists.txt, graf2d/gpad/inc/TRatioPlot.h, graf2d/gpad/src/TRatioPlot.cxx, graf2d/gpad/test/CMakeLists.txt, graf2d/gpad/test/ratioplot.cxx
Delete only objects which are created by TRatioPlot and not drawn in the canvas.
All other objects like TGaxis and TGraph handled by the canvas and therefore not touched in the destructor.
Add special handling for histogram which created from THStack but may not be drawn. 
One need extra flag to handle this. Therefore increase class version.
Provide test which writes and read ratio plot from the file.
Fixes #14855
=> Handle ownership in TRatioPlot

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/rfield_class.cxx
Fixes #14809 
Note that support for unsplittable classes will be reintroduced through the `RUnsplitField` (#14728).
=> [ntuple] forbid RClassField I/O of unsplittable classes

core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingCallFunc.h, core/metacling/test/TClingCallFuncTests.cxx
TClingCallFunc provides an interface between compiled and interpreted code. That is, we can create at compile time a function to be called by the interpreter and get back its result into compiled code. To do that we require connecting to a function declaration available in the interpreter and calling it by setting input arguments. However, the input arguments are set with the SetArg which can resolve to a type and argument representation different from the signature of the interpreter function we will call. This is practically not a problem integral types because their representation is mostly the same. The problem becomes visible when we call SetArg with a double and the function signature expects a float. That works out of the box when the compiler can see both ends and insert proper …
=> Readjust the representation of CallFunc arguments to match the callee signature

documentation/doxygen/Makefile, documentation/doxygen/filter.cxx, documentation/doxygen/modifyNamespacesWebpage.sh
After doxygen is run, the Python tutorials appeared in the namespaces list. This PR remove them.
It was mentioned in this issue: https://github.com/root-project/root/issues/10317
=> Remove the Python tutorials form the list of Namespaces

roofit/batchcompute/CMakeLists.txt, roofit/batchcompute/src/RooBatchCompute.cxx
In the original implementation of the RooBatchCompute library, the
evaluation was done multi-threaded in implicit multi-threading was
enabled in ROOT with `ROOT::EnableImplicitMT()`.
This commit removes this feature now, because it was never really
validated, overlapped with other parallelization capabilities of RooFit,
and keeping it will have many unforeseen consequences on users now that
the new CPU evaluation backend is the default in RooFit.
See also:
https://github.com/cms-sw/cmsdist/pull/9047
=> [RF] Don't consider implicit MT in RooBatchCompute

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx, tree/ntuple/v7/src/RNTupleModel.cxx, tree/ntuple/v7/test/ntuple_basics.cxx
The model keeps track of field names to avoid creating the same top-level field multiple times. Fix this mechanism under exceptions, so that the used field name is not registered as taken.
=> [ntuple] fix exception handling when adding fields

tree/tree/src/InternalTreeUtils.cxx, tree/treeplayer/inc/TChainIndex.h, tree/treeplayer/inc/TTreeIndex.h, tree/treeplayer/src/TChainIndex.cxx, tree/treeplayer/src/TTreeIndex.cxx, tree/treeplayer/test/CMakeLists.txt, tree/treeplayer/test/ttreeindex_clone.cxx
The current logic for processing TTree/TChain datasets with IMT and when a TTreeIndex is involved requires a copy of each index in each thread, since their state depends on the TTree/TChain they are attached to.
Previously, the copy was done via `TObject::Clone` which inevitably makes use of I/O functions, i.e. serialising/deserialising the TTreeIndex/TChainIndex, thus making the copy more costly than necessary.
This commit introduces overloads of `Clone` for TTreeIndex and TChainIndex enabling their copy in memory.
=> [tree] Allow bypassing I/O when copying TTreeIndex

core/base/src/TApplication.cxx
Some of these cases forgot to delete the returned char[]; the TString overload takes care of that.
This is the first commit of another PR from Axel:
https://github.com/root-project/root/pull/6874
Requesting @linev as a reviewer, because he fixed several of such issues before.
See also:
https://its.cern.ch/jira/browse/ROOT-7280
=> [core] Use ExpandPathName(TString&) to prevent mem leaks (ROOT-7280):

.github/workflows/root-ci-config/buildconfig/global.txt, cmake/modules/RootBuildOptions.cmake, math/mathmore/test/CMakeLists.txt, roofit/roostats/test/CMakeLists.txt
The `minuit2` build option was deprecated in ROOT 6.30 and should be
removed for ROOT 6.32. Minuit 2 is now always built.
=> [cmake] Remove deprecated `minuit2` build option

math/unuran/inc/TUnuran.h, math/unuran/src/TUnuran.cxx, math/unuran/src/TUnuranSampler.cxx, tutorials/unuran/unuranDemo.C
The default method for chaning multi-dim distributions is now `vnrou` instead of the Markov CHain based method hitro, which generates (being a MC MC) correlated values and not iid.
Update also documentation and tutorial
This fixes ROOT #10222
=> [math][unuran] Change default method for sampling multi-dim distributions

roofit/CMakeLists.txt, tutorials/roostats/HybridInstructional.C, tutorials/roostats/HybridStandardForm.C
I noticed that `roofit_legacy_eval_backend` variable in CMake was not
cached, and therefore it didn't propagate to the RooFit test
subdirectories. This meant several unit tests were not executed.
This commit is fixing that.
Furthermore, another commit in this PR reduces the time of the tutorial tests by reducing the number of toys in the RooStats tutorials.
=> [RF] Make sure RooFit legacy backend is still tested

bindings/pyroot/cppyy/cppyy/test/bindexplib.py, bindings/pyroot/cppyy/cppyy/test/test_aclassloader.py, bindings/pyroot/cppyy/cppyy/test/test_advancedcpp.py, bindings/pyroot/cppyy/cppyy/test/test_api.py, bindings/pyroot/cppyy/cppyy/test/test_boost.py, bindings/pyroot/cppyy/cppyy/test/test_boost_any.py, bindings/pyroot/cppyy/cppyy/test/test_conversions.py, bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py, bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py, bindings/pyroot/cppyy/cppyy/test/test_datatypes.py, bindings/pyroot/cppyy/cppyy/test/test_doc_features.py, bindings/pyroot/cppyy/cppyy/test/test_eigen.py, bindings/pyroot/cppyy/cppyy/test/test_fragile.py, bindings/pyroot/cppyy/cppyy/test/test_lowlevel.py, bindings/pyroot/cppyy/cppyy/test/test_operators.py, bindings/pyroot/cppyy/cppyy/test/test_overloads.py, bindings/pyroot/cppyy/cppyy/test/test_pythonify.py, bindings/pyroot/cppyy/cppyy/test/test_pythonization.py, bindings/pyroot/cppyy/cppyy/test/test_stltypes.py, bindings/pyroot/cppyy/cppyy/test/test_streams.py, bindings/pyroot/cppyy/cppyy/test/test_templates.py
This pull request removes unused Python modules (sys, os, py) from PyROOT/cppyy tests. The modules were imported in certain files, but they were not actually referenced in the code.
Changes PyROOT/cppyy test files by removing unused Python modules.
[CTestCostData.txt](https://github.com/root-project/root/files/13743203/CTestCostData.txt)
[LastTest.log.gz](https://github.com/root-project/root/files/13743200/LastTest.log.gz)
=> Remove unused Python modules from PyROOT/cppyy tests by backporting commit from cppyy

core/imt/inc/ROOT/TTaskGroup.hxx, core/imt/src/TTaskGroup.cxx, tree/ntuple/v7/inc/ROOT/RClusterPool.hxx, tree/ntuple/v7/inc/ROOT/RNTupleImtTaskScheduler.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RClusterPool.cxx, tree/ntuple/v7/src/RPageStorageDaos.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_cluster.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
The user expects ROOT to honor their number of threads provided as argument to `ROOT::EnableImplicitMT()`, yet facilities using `TTaskGroup` (for example RNTuple) were not using the created task arena and therefore as many resources as they could get.
This reverts commit af25fb986 ("[TTaskGroup] Isolate work with tbb::arena::isolate and not task_arena") and adds changes to use `ROOT::Internal::GetGlobalTaskArena()`.
=> [TTaskGroup] Use global task arena

core/base/src/String.cxx, core/base/src/TSystem.cxx, core/cont/src/TList.cxx, core/dictgen/src/rootcling_impl.cxx, core/foundation/src/TClassEdit.cxx, core/meta/src/TClass.cxx, core/meta/src/TStreamerElement.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TClingBaseClassInfo.cxx, core/metacling/src/TClingCallFunc.cxx, core/metacling/src/TClingTypeInfo.cxx, core/textinput/src/Getline_color.cxx
This is just a suggestion to align a bit more with Clang's coding standards https://opensource.apple.com/source/lldb/lldb-112/llvm/docs/CodingStandards.html#ll_ns_std
If the change is welcome, I can extend to the rest of parts of ROOT that have this statement.
=> [core] do not use whole std namespace, only what's needed

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_generic.py
The pretty-print pythonization should sxclude classes which have the method `__str__` already defined in C++ Since version 1.12.11, CPyCppyy is internally renaming any direct C++ `__str__` attribute to `__cpp_str` and replaces `__str__` with a pythonic wrapper [1]. Therefore, the "CPPOverload" name check below doesn't work anymore with that version. Fortunately, we can just check if the `__cpp_str` attribute exists instead. Still, this code does both checks for maximum compatibility.
[1] https://github.com/wlav/CPyCppyy/commit/10b15d8a5950125b8e1f2fbf289b1fc4398a6df6
Spinoff of the bigger synchronization PR for easier review:
https://github.com/root-project/root/pull/14507
=> [PyROOT] Forward compatibility of pretty printing with CPyCppyy

tutorials/CMakeLists.txt
Disable tutorials failing on Windows with VS 2022 v17.8
=> [roofit] Disable failing tests on Windows

bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
In older cppyy, template instanciations are cached by fully-qualified
name directly in the namespace. Therefore, no extra code is required to
cover template instances in the pythonization code.
With the new cppyy, this is not the case anymore, and instances are
instead cached in the `_instatiations` attribute of the template class [1].
This commit considers this, in a way that is backwards compatible also
with the older cppyy version that ROOT currently uses.
A second commit in this PR removes some not so Pythonic "C++-style" code from PyROOT.
[1] https://github.com/wlav/cppyy/commit/f2e1ea783afd2e4f195b6cbaf09d72b9fa3cd865
Spinoff of the bigger synchronization PR for easier review:
https://github.com/root-project/root/pull/14507
=> [PyROOT] Forward compatibility of user pythonizations with newer cppyy

cmake/modules/FindTBB.cmake
Even if not supported anymore, we must be able to determine the old TBB versions to *not* pick it up. Add back the check for the previous header that was removed in commit a1d969d8ca.
=> [cmake] Fix version detection for old TBB

roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h, roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h, roofit/xroofit/src/xRooFit.cxx, roofit/xroofit/src/xRooNode.cxx
This PR addresses:
- Bug fix to plotting datasets horizontal error bars
- Bug fix to obtaining datasets of reduced pdfs (i.e. get the corresponding reduced dataset)
- Beginning to add some documentation for xRooNode
- Adds a cling interpreter method for xRooNode to print the names of the child nodes
=> [RF] Update xroofit

geom/geom/inc/TGeoBBox.h
Deprecates flawed method TGeoBBox::AreOverlapping
The function fails to detect some box overlaps, and it is not used inside ROOT.
Added deprecation macro after the function definition
This PR fixes [ROOT-8712](https://its.cern.ch/jira/browse/ROOT-8712)
=> Deprecation of TGeoBBox::AreOverlapping

core/metacling/src/TClingCallbacks.cxx, core/metacling/test/TClingTests.cxx
Declarations without the auto keyword are not part of standard C++. Even though it is a nice feature to have, it requires a patch on top of clang and is one of the hurdles preventing us from using the upstream clang.
Implicit auto injection is currently only supported at the prompt (and only in the top-most function-level scope). So it should ideally not break other features.
There are a few GitHub and JIRA issues related to this feature that can also be closed if we completely remove it.
For the warning messages, I'm reusing one of the existing clang warning message (to not introduce more patches on top of the clang with custom error messages).
EDIT:
Glancing through JIRA issues, these are the issues that can be closed (list might not be exhaustive): …
=> [cling] Add deprecation warning for declarations without `auto`

graf2d/asimage/CMakeLists.txt, graf2d/asimage/src/TASImage.cxx
by using TClass instead of the interpreter. As a side effect, the whole process is much faster. This fixes an incarnation of #14156, mitigating the overall effect of the highlighted behaviour.
NOTE: A test is available but not yet pushed to this PR and will be added in stressgraphics.
=> [graphics] Save memory when obtaining TImageDump instance

hist/histpainter/src/TGraphPainter.cxx, hist/histpainter/src/THistPainter.cxx
TH2Poly with drawn option L did not get the line attributes correctly. This PR fixes this problem which was found here: https://github.com/couet/root/pull/new/th2poly-line
A small reproducer can be:
```
{
TH2Poly* h2pol = new TH2Poly("p2","p2",0,4,0,4);
Double_t x[4] = {0.5,0.,2.,2.};
Double_t y[4] = {0.,2.,2.,0.5};
TGraph *g = new TGraph(4,x,y);
h2pol->AddBin(g);
h2pol->Fill(1.,1.,3);
g->SetLineColor(kRed);
g->SetLineStyle(2);
g->SetLineWidth(8);
g->SetFillColor(kYellow);
h2pol->Draw("L");
}
```
=> Make sure the option L draws closed polygon for TH2Poly

graf2d/asimage/src/TASPaletteEditor.cxx
When saving palette, interpreter with wrong arguments was invoked.
Call directly `gROOT->SaveObjectAs` with correct argument.
Use TString for file name operations
When reading palette - check return values and also use TString for filename operations
=> Fix Load and Save in TASPaletteEditor

hist/hist/src/THnBase.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-10705
=> [hist] fix x0 printEntries in THnSparse/THnBase

bindings/pyroot/pythonizations/python/ROOT/_facade.py
Addresses https://github.com/root-project/root/pull/14844#pullrequestreview-1941023212
Sorry about that @guitargeek
=> [skip-CI][PyROOT] Correct typo in the name of a helper function

.github/workflows/root-626.yml, .github/workflows/root-628.yml
namely to 1 build/day for 6.26 and 2 builds/day for 6.28.
=> [skip-CI][ci] Modify scheduled build time for old branches

js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/gui.mjs, js/modules/gui/HierarchyPainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs
Handle line and fill attribute from individual bins 
Support "p" and "*" for markers drawing
Switch off color draw optimization
Now JSROOT should be very close to ROOT graphics
Other changes in JSROOT as:
- use localStorage instead of cookies (not exposed to network)
- support URL options export when using "Show in new tab" menu command
=> [jsroot] better TH2Poly support

documentation/doxygen/Doxyfile, tutorials/dataframe/df105_WBosonAnalysis.py, tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py, tutorials/dataframe/df107_SingleTopAnalysis.py
The dataframe tutorials json spec files were not displayed properly. Moreover there was no direct correspondence between the code source and the json file. Those files do not have any doc in them. This PR makes a direct link to the GitHub source file. The dependency between source code and json is therefore more obvious.
=> Make links to json spec files

gui/webgui6/src/TWebCanvas.cxx
In TPad::WaitPrimitive method selected pad
is used to check which mouse button or key was pressed While key events already delivered to the ROOT application, only selected pad was missing to make WaitPrimitive working.
Now it will block TWebCanvas until double-click in the frame.
Editor mode will be implemented separately only in the ROOT master.
Solves: https://root-forum.cern.ch/t/web-canvas/58551/
=> [webgui] set selected pad in TWebCanvas

gui/webgui6/src/TWebCanvas.cxx
In TPad::WaitPrimitive method selected pad
is used to check which mouse button or key was pressed While key events already delivered to the ROOT application, only selected pad was missing to make WaitPrimitive working.
Now it will block TWebCanvas until double-click in the frame.
Editor mode will be implemented separately only in the ROOT master.
=> [webgui] set selected pad in TWebCanvas [6.30]

roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/src/RooNLLVarNew.cxx
Made changes to fix guardrails in RooNLL and EvalFuncs.h for visualising differences between codegen and codegen without gradient. 
@guitargeek
=> Changes to RooNLL and Eval Funcs to fix visualizations

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rtensor.py, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTPythonize.h, bindings/pyroot/pythonizations/src/PyzPythonHelpers.cxx
Substitute the C++ functions GetSizeOfType and GetDataPointer in our CPython extension library for the equivalent cppyy functions.
This PR fixes #14981
=> Avoid the interpreter to query info for array pythonizations

core/base/src/TROOT.cxx
If method `TROOT::GetFunction()` called multiple times 
with non-existing function name, each call causes invocation of interpreter.
If repeated many times, it may crash ROOT
Simple reproducer:
```
for (int n=0;n<100000;++n) gROOT->GetFunction("any");
```
In current ROOT it takes ~3 GB for nothing.
=> Avoid memory leak in TROOT::GetFunction()

roofit/roofitcore/test/CMakeLists.txt
They need to be temporarily disabled until a fix is available in clad.
=> [RF] Disable RooFit AD tests on Windows

net/http/inc/TRootSniffer.h, net/http/src/TCivetweb.cxx, net/http/src/THttpCallArg.cxx, net/http/src/THttpServer.cxx, net/http/src/THttpWSHandler.cxx, net/http/src/TRootSniffer.cxx, net/http/src/TRootSnifferStore.cxx, net/httpsniff/inc/TRootSnifferFull.h, net/httpsniff/src/TRootSnifferFull.cxx, tutorials/http/custom.C, tutorials/http/custom.htm, tutorials/webgui/ping/ping.cxx, tutorials/webgui/webwindow/server.cxx
1. Do not use plain `Form()` macro
2. Do not use `gROOT->ProcessLine()` to create sniffer instance
3. Set full paths to custom HTML files in tutorials
4. Other minimal formatting
=> [http] Improve syntax, avoid interpreter calls

tutorials/histfactory/ModifyInterpolation.C, tutorials/roostats/ModelInspector.C, tutorials/roostats/StandardBayesianMCMCDemo.C, tutorials/roostats/StandardHistFactoryPlotsWithCategories.C
Thanks @ferdymercury for noticing this!
https://github.com/root-project/root/pull/14993#issuecomment-2007683434
=> [RF] Avoid deprecated `createIterator()` function in RooStats tutorials

graf2d/postscript/src/TSVG.cxx
Fix [this issue](https://github.com/root-project/root/issues/9514).
The change inserts a new line in the SVG file before the <\text> tag. This avoids the syntax error the user sees when inserting a very long text.
=> Very long text string generated a wrong SVG file

roofit/roofitcore/test/CMakeLists.txt
Re-enable `testRooFuncWrapper` with recent versions of Visual Studio
=> [RF][Windows] Re-enable `testRooFuncWrapper`

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/rfield_check.cxx
Adds a new static method, `RFieldBase::Check()`, that produces a support status report of a type wrt. to RNTuple I/O. The method uses `RFieldBase::Create()` internally. Instead of throwing an exception when a (sub) type fails to be constructed, in the case of `Check()`  an `RInvalidField` is inserted in the field tree instead. The invalid fields are then collected to produce a report of failures.
=> [ntuple] Add RFieldBase::Check(<type name>)

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py, bindings/experimental/distrdf/test/backend/test_common.py
Historically, the distributed initialize function also ran the user-provided function in the local session. In general, this may not be the desired effect.
A user calling distributed initialize may only want to see the effects of the input function on the executors and not on the driver of the distributed application.
=> Restrict distributed initialization to executors only

interpreter/cling/lib/Interpreter/CIFactory.cpp
We should have separate cases for unix and apple, otherwise the modulemaps go on top of each other.
=> [runtime_cxxmodules] Do not overlay on top of the unix modulemaps.

roofit/roofit/inc/RooMomentMorph.h, roofit/roofit/inc/RooMomentMorphFunc.h, roofit/roofit/src/RooMomentMorph.cxx, roofit/roofit/src/RooMomentMorphFunc.cxx
The RooAbsReal::getVal function should not be overloaded. It is the getValV function that is a virtual function which might be overloaded in derived classes. Otherwise, virtual calls don't work.
=> [RF] Rename RooMomentMorph::getVal to RooMomentMorph::getValV

cmake/modules/RootBuildOptions.cmake
since the warning is not needed in case the graphics system, cocoa or x11, is OFF.
A spourious warning when libafterimage is OFF without X11/Cocoa being ON.
- [V] tested changes locally
This PR fixes #15027
=> [ci] Contextualize cmake warning about builtin_afterimage=OFF

bindings/pyroot/pythonizations/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py, tree/dataframe/CMakeLists.txt, tree/dataframe/inc/ROOT/RVecDS.hxx
Re-implement `MakeNumpyDataFrame` with no interpreter calls, and avoid a
explicit lifetime management of Python objects in the RDNumpyDS helper.
Like this, the former `RNumpyDS.hxx` helper could be moved to
`tree/dataframe`, as it doesn't import `Python.h` anymore.
The `RNumpyDS` also got renamed to `RVecDS`, because it takes RVecs and
not NumPy arrays directly.
=> [RF] Re-implement `MakeNumpyDataFrame` with no interpreter calls

config/rootrc.in, core/base/src/TObject.cxx, io/io/inc/TFile.h, io/io/src/TFile.cxx, io/io/src/TStreamerInfoWriteBuffer.cxx
Calling `file->SetBit(TFile::k630forwardCompatibility);` will request to file to store the current value of the bit kIsOnHeap and kNotDeleted for reading in older version that were not setting their value based on the actual state of the read into object.
This fixes #14793
=> Allow producing forward compatible file for fBits value.

interpreter/cling/lib/Interpreter/CIFactory.cpp
Backport of https://github.com/root-project/root/pull/15043 and https://github.com/root-project/root/pull/14974
=> [Backport 6.30][runtime_cxxmodules] Allow for changing the modulemap name to match the overlay

tutorials/CMakeLists.txt
Fixes the nightly failure.
I could not have anticipated this, because the PR tests of the PR that caused the regression were just fine:
https://github.com/root-project/root/actions/runs/8426692299
It seems the build configuration of the scheduled builds in inconsistent with the PR builds: it misses `mathmore=ON`.
Follows up on https://github.com/root-project/root/pull/14743.
=> [RF] Also veto Python version of TestNonCentral when `mathmore=OFF`

tree/ntuple/v7/doc/specifications.md
follow up of #14949
I can see why it's not stored in cumulative format, because the "writer" can track the incremental easily (length of the current item). But I can't quite figure out why not just store the entire thing incremental 
@jblomer
=> [RNTuple] describe how exactly `Index` columns are relative to cluster

core/metacling/test/TClingLoadUnloadFileTests.cxx
Fails sporadically, https://github.com/root-project/root/issues/14121
(cherry picked from commit 5560b67e7f4e5ce1013a4f39bd61ae81470b5343; backport of https://github.com/root-project/root/pull/14281 as discussed during the team meeting)
=> [core] Disable TClingLoadUnloadFileTests [v6.30]

roofit/roofitcore/inc/RooFit/EvalContext.h, roofit/roofitcore/inc/RooFit/Evaluator.h, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.h, roofit/roofitcore/src/RooFit/EvalContext.cxx, roofit/roofitcore/src/RooFit/Evaluator.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/test/testTestStatistics.cxx
The logic that determined the offset hiding of not was coded inside the `RooNLLVarNew` evaluation function so far.
This caused trouble, because a change in the global `RooAbsReal::hideOffset()` state did not mark the NLL as dirty. Therefore, it was unpredictable if the offset was actually hidden or not.
This commit suggests an improved logic:
* Reducer nodes like the NLL always register a value and an offset to the `EvalContext`
* The evaluator decides whether to subtract the offset or not
* A change in `hideOffset()` makes the evaluator wrapper set all reducer nodes to dirty
A new unit test to cover this was also implemented.
FYI, @will-cern
=> [RF] Fix dirty state propagation for offsetting with new CPU backend

interpreter/cling/lib/Interpreter/CIFactory.cpp
Backport of https://github.com/root-project/root/pull/15043 and https://github.com/root-project/root/pull/14974
=> [Backport 6.28][runtime_cxxmodules] Allow for changing the modulemap name to match the overlay

bindings/pyroot/cppyy/CPyCppyy/src/CPPDataMember.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPExcInstance.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx, bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx, bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx, bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx, bindings/pyroot/cppyy/CPyCppyy/src/TupleOfInstances.cxx, bindings/pyroot/cppyy/sync-upstream
Adapting to a new field in Python 3.12:
https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_watched
Corresponding CPyCppyy PR: https://github.com/wlav/CPyCppyy/pull/24
=> [cppyy] Fix `missing-field-initializers` with Python 3.12

README/ReleaseNotes/v632/index.md, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py, bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py, tutorials/dataframe/df007_snapshot.py, tutorials/dataframe/df017_vecOpsHEP.py, tutorials/pyroot/pyroot005_tfile_context_manager.py
The new recommended way to get objects from a `TFile` or any
`TDirectory` in general is now via `__getitem__`:
```python
tree = my_file["my_tree"] # instead of my_file.my_tree
```
This is more consistent with other Python collections (like
dictionaries), makes sure that member functions can't be confused with
branch names, and easily allows you to use string variables as keys.
The old pythonization with the `__getattr__` syntax still works, but
emits a deprecation warning and will be removed from ROOT 6.34.
=> [PyROOT] Replace `TDirectory.__getattr__` with `__getitem__`

roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.cxx, roofit/roofitcore/src/RooEvaluatorWrapper.h, roofit/roofitcore/src/RooFuncWrapper.cxx, roofit/roofitcore/src/RooNLLVarNew.cxx, roofit/roofitcore/src/RooNLLVarNew.h, roofit/roofitcore/test/testRooSimultaneous.cxx
Only register actual observables as value servers in the `RooEvaluatorWrapper` this avoids that spurious variables appear in user code, which were only meant to be used internally by the new CPU evaluation backend.
To make the management of the parameter easier, impose the new reasonable constraint that when resetting the data via `setData()`, the new dataset needs to have the same structure as the old one.
It was confirmed with an ATLAS model provided by Will that this commit is fixing the problem of spurious variables.
A unit test is also implemented.
FYI @will-cern
=> [RF] Improve parameter management in `RooEvaluatorWrapper`

roofit/roofitcore/src/RooFit/Evaluator.cxx
=> [RF] Work around deleted move constructor in `std::span` backport

bindings/experimental/distrdf/python/DistRDF/Backends/Utils.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/test/rdataframe_asnumpy.py
Motivated by the distributed execution use case
=> Properly clone `AsNumpyResult` objects

roofit/roofitcore/src/RooFit/Evaluator.cxx
This is a followup to #15089, where I missed a second change.
Closes #15087.
=> [RF] Fixup work around deleted move constructor in `std::span` backport

math/minuit2/src/Minuit2Minimizer.cxx
Changes the letter case in the minuit2 status report when the minimum is invalid such that the report is consistent with the case when the minimum is valid. Currently, I get the following output when grep my logs:
```
Minuit2Minimizer : Invalid Minimum - status = 3
Minuit2Minimizer : Valid minimum - status = 0
```
=> [minuit2] make letter case consistent

math/vecops/inc/ROOT/RVec.hxx, math/vecops/test/vecops_rvec.cxx
Makes it possible to call `VecOps::DeltaPhi`, `VecOps::DeltaR`, `VecOps::DeltaR2`, `VecOps::InvariantMass` and `VecOps::InvariantMasses` with different floating point types.
Previously all arguments where deduced to be the same types which does not allow to call these with mixed floating point type arguments. Now each argument get's its own template type, making it possible to call them with mixed floating point types. The return type and any intermediate calculations will be done by the largest necessary floating point type, as determined via `std::common_type`.
I tried to follow existing conventions, e.g. using `Common_t` as an additional defaulted template argument for a bit less typing in the implementations. This also requires at least c++14 as it uses the `common_type_t` helper type …
=> Relaxed rvec utils

io/io/src/TFile.cxx
Supersedes https://github.com/root-project/root/pull/9616
=> [skip-ci] [io] Collapse data format details of TFile class

core/meta/inc/TInterpreter.h, core/metacling/src/TCling.cxx, core/metacling/src/TCling.h, core/metacling/test/TClingTests.cxx, documentation/doxygen/libs.C
Bug introduced in commit from 2019 Jun 2nd, where gInterpreter->GetClassSharedLibs() returns nullptr for any class inside the ROOT core base classes.
Fixes https://github.com/root-project/root/issues/11667
=> [core] Do not skip libCore when finding out to what library the class belongs

math/foam/src/TFoam.cxx
Clarifies meaning of TFoam::GetIntNorm parameters, as requested by @mchrzasz
This PR fixes https://github.com/root-project/root/issues/14528
=> [math] Clarify meaning of TFoam::GetIntNorm parameters

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_rtensor.py
To avoid warnings such as `_rvec.py:95: SyntaxWarning: invalid escape sequence '\p'`
=> [skip-ci] [pyroot] Use raw string to allow escaped character in docstring

.github/workflows/root-ci-config/buildconfig/global.txt, cmake/modules/RootBuildOptions.cmake, cmake/modules/RootConfiguration.cmake, cmake/modules/SearchInstalledSoftware.cmake, config/Makefile.in
The option was deprecated in ROOT 6.32 and should be removed for the next release, as anticipated by the deprecation warnings in 6.32.
Follows up on https://github.com/root-project/root/pull/14395.
=> [CMake] Remove `builtin_libafterimage` option

core/base/src/TApplication.cxx, core/base/src/root-argparse.py, core/metacling/src/TCling.cxx
Allows running named macro from shared library as it was the case with CINT and was documented in users guide.
See https://root-forum.cern.ch/t/cannot-run-shared-object-in-batch-mode/58213
Fixes https://github.com/root-project/root/issues/14772
=> [cling] Allow running named macro from shared library

hist/hist/inc/TPrincipal.h, hist/hist/src/TPrincipal.cxx
Clarifies covariance matrix format
Adds safety-bounds-checking
See https://root-forum.cern.ch/t/tprincipal-fails-for-a-very-large-number-of-entries/58795
=> [hist] TPrincipal bounds check and format

tmva/sofie/inc/TMVA/SOFIE_common.hxx, tmva/sofie/src/RModel.cxx
* remove wrong multiplication of type size in `CastPersistentToShared`
* restructure `InitializeTensor` to only provide read-only accessors, enforcing invariance of the right combination between type, shape and data
* avoid **memory leak** of persistified data when reading back from file
* reset `fSize` member in `CastSharedToPersistent` to avoid wrong size info when persistifying the same model twice (otherwise, the multiplication with the element size in bytes would happen twice, resulting in overruns when copying the transient data)
Extends on #15162.
=> [tmva][sofie] Fix issues with RModel streamer

tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/rfield_class.cxx
Implement special treatment for fBits. Disable RNTuple I/O for referenced objects. Locks I/O support for TObject to class version 1, assuming that TObject won't further evolve.
Fixes #14808
=> [ntuple] specialize RField for TObject

tmva/sofie/inc/TMVA/RModel.hxx, tmva/sofie/inc/TMVA/RModel_Base.hxx, tmva/sofie/inc/TMVA/RModel_GNN.hxx, tmva/sofie/inc/TMVA/RModel_GraphIndependent.hxx, tmva/sofie/test/EmitFromRoot.cxx.in
As a followup to https://github.com/root-project/root/pull/15163 and in relation to https://github.com/root-project/root/issues/15156
* Apply rule of five
* Use correct `ClassDef` macro only when necessary
* Remove relationship to `TObject` from `RModel_Base`
* Properly implement virtual hierarchy for `RModel_GNNBase` and derived
Also apply clang-format changes in a separate commit
=> [tmva] Cleanup RModel classes layout

io/io/inc/TFileCacheRead.h, io/io/src/TFileCacheRead.cxx, tree/tree/inc/TTreeCache.h, tree/tree/inc/TTreeCacheUnzip.h, tree/tree/inc/TTreeCloner.h, tree/tree/src/TTree.cxx, tree/tree/src/TTreeCache.cxx, tree/tree/src/TTreeCacheUnzip.cxx, tree/tree/src/TTreeCloner.cxx
Fixes https://github.com/root-project/root/issues/9292
=> [tree,io] prevent integer overflow when dealing with cachesize

core/base/inc/TString.h
Backport of https://github.com/root-project/root/pull/14245
To address https://github.com/root-project/root/issues/14244#issuecomment-2042589340
=> [v630] Remove std::string_view comparison operators

tmva/tmva/inc/TMVA/RBatchGenerator.hxx
`EnableThreadSafety()` is called in `_batchgenerator.py` making another call for it redundant and `class RBatchGenerator` depends to Internal namespace
=> [tmva] Remove supefluous EnableThreadSafety()

core/base/inc/TAttMarker.h
Fixes https://its.cern.ch/jira/browse/ROOT-7408
ClassDef jitter between @couet and @pcanal, this class was missing the fix.
See:
https://github.com/root-project/root/commit/269ba25ed73ae5e9b2fd020955fffb52d28ca557
https://github.com/root-project/root/commit/08fe57178a020ae8223f2fa0688e6fad7acf2dbc
https://github.com/root-project/root/commit/bf1b5448f0caea2116b1ca77e1507525d67da520
=> [core] 1 missing Undo revert Classdef version

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py, bindings/pyroot/pythonizations/test/rdataframe_asnumpy.py, tree/dataframe/src/RDFUtils.cxx
The `bool` columns in RDF are special, because the Take action returns a `std::vector<bool>`, which has an implementation-depended memory layout for space optimization.
Therefore, I suggest supporting taking `bool` columns as `unsigned char` with `Take()`, such that in `RDataFrameAsNumpy` the values can be directly taken as bytes. This avoids superfluous copying in the code, and keeps the special logic in the pythonization side minimal.
Closes #8639.
=> [PyROOT][RDF] Support conversion of `bool` columns to NumPy arrays

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, requirements.txt, tmva/tmva/test/CMakeLists.txt, tmva/tmva/test/rbdt_xgboost.py, tutorials/tmva/tmva101_Training.py
This should be added so we can test RBDT in the CI.
=> [CI] Add `xgboost` and `scikit-learn` to requirements

tmva/tmva/test/CMakeLists.txt
Disabled because RBDT doesn't support the imbalanced tree structure of XGBoost models.
We need to disable this test right now, because we have now installed XGBoost on the GitHub action runners, and this test will be red.
This test never worked, we just never noticed because XGBoost was not installed on any CI platform.
Backport of a commit from #15183.
=> [v626][TMVA] Disable `rbdt_xgboost` test

tmva/tmva/test/CMakeLists.txt
Disabled because RBDT doesn't support the imbalanced tree structure of XGBoost models.
We need to disable this test right now, because we have now installed XGBoost on the GitHub action runners, and this test will be red.
This test never worked, we just never noticed because XGBoost was not installed on any CI platform.
Backport of a commit from #15183.
=> [v628][TMVA] Disable `rbdt_xgboost` test

tmva/tmva/test/CMakeLists.txt
Disabled because RBDT doesn't support the imbalanced tree structure of XGBoost models.
We need to disable this test right now, because we have now installed XGBoost on the GitHub action runners, and this test will be red.
This test never worked, we just never noticed because XGBoost was not installed on any CI platform.
Backport of a commit from #15183.
=> [v630][TMVA] Disable `rbdt_xgboost` test

tmva/sofie_parsers/src/RModelParser_ONNX.cxx
Byte swap values read from the protobuf raw data stream on big endian
This PR fixes #10146
=> Byte swap values read from the protobuf raw data stream on big endian

hist/hist/inc/TH2.h, hist/hist/inc/TH3.h, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx
You can call `TH1::SetBinContent(1, 5)` and `TH2::SetBinContent(1, 1, 5)`
You can call `TH1::AddBinContent(1,5)` but you cannot call `TH2::AddBinContent(1, 1, 5)`
This PR makes the latter option available, for symmetry.
=> 2D/3D version of TH1::AddBinContent, as with TH2::SetBinContent/TH3::SetBinContent

hist/hist/inc/TH1.h, hist/hist/inc/TH2.h, hist/hist/inc/TH3.h, hist/hist/src/TH1.cxx, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx
Adds a reasonable max bin content (and explicitly stated) for TH1F to prevent nasty silent data drawing errors
If the solution is welcome, I can extend it for TH2 and TH3.
Fixes https://github.com/root-project/root/issues/6671
=> [hist,skip-ci] document max bin content for th1f,th2f,th3f

tree/ntuple/v7/src/RNTupleMerger.cxx
This uses a bit more memory because all sealed pages of a cluster must be kept in memory, but is up to a factor 2x faster.
FYI @amete
=> [ntuple] Use CommitSealedPagesV in RNTupleMerger

interpreter/cling/include/cling/Interpreter/InvocationOptions.h, interpreter/cling/lib/Interpreter/BackendPasses.cpp, interpreter/cling/lib/Interpreter/Interpreter.cpp, interpreter/cling/lib/Interpreter/InvocationOptions.cpp
Adds plugin support to cling. This patch enables loading clang/pass plugins with the flag: 
`EXTRA_CLING_ARGS="-fplugin=path/to/plugin.so -fpass-plugin=path/to/plugin.so"`
=> [cling] Add plugin support

tree/tree/src/TTree.cxx, tree/treeplayer/src/TTreeFormula.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-8269
Fixes https://its.cern.ch/jira/browse/ROOT-7993
Probably fixes https://its.cern.ch/jira/browse/ROOT-8709
I am not sure if the full function code itself is correct, ie why fNcodes is bigger than fLeaves.size()
=> [tree] prevent crash in LoadCurrentDim

config/root-config.bat.in
Should fix a problem when using `root-config.bat` in `execute_process`
when the output of `root-config.bat` contains a newline
=> [win] echo without newline in `root-config.bat`

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_tree_inference.py, requirements.txt, tmva/tmva/test/rbdt_xgboost.py, tutorials/tmva/tmva101_Training.py
Backport of https://github.com/root-project/root/pull/15183.
=> [v630][CI] Add `xgboost` and `scikit-learn` to requirements

bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx, bindings/pyroot/cppyy/cppyy/test/test_regression.py
Backports of 
https://github.com/wlav/CPyCppyy/commit/e40a3fbab87304deb4ed37e217f66d87cc3ceba7
https://github.com/wlav/cppyy/commit/6556a62ee1a3e53b4b2057f46d87b5fe2fe89dbf
Fixes #15217
=> Fix for calling static method with default argument

tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx
Mention that it is thread-safe and can be called after some data has already been written. Explain that the model is cloned internally and therefore recommend `RNTupleModel::CreateBare`.
FYI @makortel @Dr15Jones
=> [ntuple] Extend documentation of `CreateFillContext`

graf3d/eve7/inc/ROOT/REveBoxSet.hxx, graf3d/eve7/src/REveDataCollection.cxx, graf3d/eve7/src/REveElement.cxx, tutorials/eve7/calorimeters.C, ui5/eve7/lib/EveElementsRCore.js, ui5/eve7/lib/GlViewerRCore.js, ui5/eve7/view/EveTable.view.xml
Print warning if eve element does not have a dictionary. The commit   264404b also fixes the crash on streaming to client when element's dictionary is not existing and does not need non-REveElement remote method invocation. 
The other 3 commits contains minor corrections to the problems located in testing of CMS event display (table view layout, debug prints, background color setting at connect time).
=> [reve] Print warning on missing  eve element dictionary

io/io/inc/ROOT/RRawFile.hxx, io/io/inc/ROOT/RRawFileTFile.hxx, io/io/inc/ROOT/RRawFileUnix.hxx, io/io/inc/ROOT/RRawFileWin.hxx, io/io/src/RRawFile.cxx, io/io/src/RRawFileUnix.cxx, io/io/src/RRawFileWin.cxx, io/io/test/RRawFile.cxx, net/davix/inc/ROOT/RRawFileDavix.hxx, net/netxng/inc/ROOT/RRawFileNetXNG.hxx, tree/dataframe/src/RSqliteDS.cxx
Remove unused or unnecessary code (`RRawFile::Map()` and `RRawFile::GetFeatures()`), modernize class members (`unique_ptr` and default initialization), and improve handling of empty requests.
=> [io] Clean up RRawFile implementation

graf2d/gpad/src/TPad.cxx
The declaration of `obj` has been moved to an outer scope in PR #15179, resulting in a warning (or error) from `-Wshadow`.
=> [gpad] Remove variable redeclaration

cmake/modules/RootMacros.cmake
Partially revert commit d487a42b311 ("[cmake] Set CMAKE_CXX_STANDARD explicitly in RootUseFile.cmake") because this is required to propagate the C++ standard via CMake library targets, as advertised on the website.
Fixes #15253 (needs to be backported to `v6-32-00-patches`)
=> [cmake] Add back `cxx_std_` compile feature

roofit/jsoninterface/CMakeLists.txt
The RapidYAML of the RooFit JSON interface is now always disabled because it doesn't work anymore for RooFitHS3. The `nlohmann_json` interface is always used and works well, hence rapidyaml was not tested anymore and the code was rotting until it didn't work. The relevant code is still left in the CMakeLists.txt in case someone wants to revive the RapilYAML backend.
Closes #15118.
Should be backported up to 6.28.
=> [RF] Comment out `ryml` backend for RooFit JSON interface

roofit/jsoninterface/CMakeLists.txt
The RapidYAML of the RooFit JSON interface is now always disabled because it doesn't work anymore for RooFitHS3. The `nlohmann_json` interface is always used and works well, hence rapidyaml was not tested anymore and the code was rotting until it didn't work. The relevant code is still left in the CMakeLists.txt in case someone wants to revive the RapilYAML backend.
Closes #15118.
Backport of https://github.com/root-project/root/pull/15247.
=> [v630][RF] Comment out `ryml` backend for RooFit JSON interface

roofit/jsoninterface/CMakeLists.txt
The RapidYAML of the RooFit JSON interface is now always disabled because it doesn't work anymore for RooFitHS3. The `nlohmann_json` interface is always used and works well, hence rapidyaml was not tested anymore and the code was rotting until it didn't work. The relevant code is still left in the CMakeLists.txt in case someone wants to revive the RapilYAML backend.
Closes #15118.
Backport of https://github.com/root-project/root/pull/15247.
=> [v632][RF] Comment out `ryml` backend for RooFit JSON interface

roofit/jsoninterface/CMakeLists.txt
The RapidYAML of the RooFit JSON interface is now always disabled because it doesn't work anymore for RooFitHS3. The `nlohmann_json` interface is always used and works well, hence rapidyaml was not tested anymore and the code was rotting until it didn't work. The relevant code is still left in the CMakeLists.txt in case someone wants to revive the RapilYAML backend.
Closes #15118.
Backport of https://github.com/root-project/root/pull/15247.
=> [v628][RF] Comment out `ryml` backend for RooFit JSON interface

cmake/modules/RootMacros.cmake
Partially revert commit d487a42b311 ("[cmake] Set CMAKE_CXX_STANDARD explicitly in RootUseFile.cmake") because this is required to propagate the C++ standard via CMake library targets, as advertised on the website.
Fixes #15253
(cherry picked from commit 9e67151fac9c9d61692375c27604370451b7148b; backport of https://github.com/root-project/root/pull/15254)
=> [cmake] Add back cxx_std_ compile feature [v6.32]

net/netxng/src/RRawFileNetXNG.cxx
The maximum number of requests per vector read and the maximum size of a single request in that vector read were mixed up.  As a result, for a typical server, requests >1kB would not end up in a vector read.
This PR is fixing it.
=> [xrootd] fix setting readv limits for raw file

roofit/roofitcore/src/RooFormula.cxx
After commit a27e60a6d4f, it is not important anymore that only the variables used by the expression are passed to RooFormula.
Removing the corresponding warnings helps to get rid of useless warnings in the case where you want to try out variations of the formula that omit certain terms, and in particular it helps in
`RooAbsData::reduce()`, where the formula is always passed all the varaiables in the dataset, whether the reduction uses them or not.
To be backported to 6.32.
=> [RF] Remove warning about unused variables in `RooFormula`

roofit/roofitcore/src/RooAbsCollection.cxx, roofit/roofitcore/src/RooRealIntegral.cxx
Needs to be backported to 6.32.
=> [RF] Fix double-ownership in RooRealIntegral copy constructor

tmva/pymva/test/CMakeLists.txt
BLAS should be linked like in the main TMVA library:
https://github.com/root-project/root/blob/master/tmva/tmva/CMakeLists.txt#L420
=> [TMVA] Correctly link `blas` in PyMVA tests

requirements.txt
We do not support Tensorflow >2.15 since Keras 3.x brings several breaking changes https://github.com/keras-team/keras/issues/18467
=> [TMVA] Enforce supported version of TensorFlow

tutorials/tmva/TMVA_CNN_Classification.py, tutorials/tmva/pytorch/ApplicationClassificationPyTorch.py, tutorials/tmva/pytorch/ApplicationRegressionPyTorch.py, tutorials/tmva/pytorch/ClassificationPyTorch.py, tutorials/tmva/pytorch/MulticlassPyTorch.py, tutorials/tmva/pytorch/RegressionPyTorch.py
Apply the same fix as in a561a9fe09, but for PyTorch.
Needs to be backported up to 6.28.
=> [TMVA] Avoid torch-cppyy symbol clashing problem in tmva tutorials

requirements.txt
Only TensorFlow 2.16 is compatible with Python 3.12, but not with ROOT (see commit e30dc626a6).
=> requirements.txt: Skip tensorflow with Python 3.12

tutorials/tmva/TMVA_CNN_Classification.py
This is a follow-up on 872886bcc.
That commit was reordering code in the wrong way: the initialization of the `useKerasCNN` and `usePyTorchCNN` variables should have also been moved to the top.
This fixes the current failures on Windows.
=> [skip-ci][v628][tutorials] Fix `tensorflow` and `pytorch` detection in TMVA tutorial

tutorials/tmva/TMVA_CNN_Classification.py
This is a follow-up on 872886bcc.
That commit was reordering code in the wrong way: the initialization of the `useKerasCNN` and `usePyTorchCNN` variables should have also been moved to the top.
This fixes the current failures on Windows.
=> [skip-ci][v630][tutorials] Fix `tensorflow` and `pytorch` detection in TMVA tutorial

tutorials/tmva/TMVA_CNN_Classification.py
This is a follow-up on 872886bcc.
That commit was reordering code in the wrong way: the initialization of the `useKerasCNN` and `usePyTorchCNN` variables should have also been moved to the top.
This fixes the current failures on Windows.
=> [v632][tutorials] Fix `tensorflow` and `pytorch` detection in TMVA tutorial

tutorials/tmva/TMVA_CNN_Classification.py
This is a follow-up on 872886bcc.
That commit was reordering code in the wrong way: the initialization of the `useKerasCNN` and `usePyTorchCNN` variables should have also been moved to the top.
This fixes the current failures on Windows.
=> [tutorials] Fix `tensorflow` and `pytorch` detection in TMVA tutorial

core/rint/src/TTabCom.cxx
Fixes https://github.com/root-project/root/issues/11238
Reverts https://github.com/root-project/root/pull/2585
Reverts https://github.com/root-project/root/commit/9d459ce6141daf108587d85737bdc50e70c775d3
Re-Fixes https://its.cern.ch/jira/browse/ROOT-9597
=> [core] tab completion: insert match but do not replace the content after it

.github/workflows/root-ci-config/buildconfig/alma9.txt, tutorials/CMakeLists.txt
The `tmva-cpu` BLAS-accelerated TMVA backend uses the openblas version found on the system, but NumPy also ships its own `openblas` library when installed with pip.
If both openblas versions are loaded, segfaults can occur if they are incompatible. We currently see this on the `alma9` CI runners.
The minimal remedy for this is to just disable the TMVA BLAS backend. Nobody is using the CPU to train neural nets nowadays anyway.
Like this, we don't have to disable features like PyMVA or RBDT.
=> [CI] Disable `tmva-cpu` on `alma9` to avoid openblas clashes with NumPy

.github/workflows/root-ci-config/buildconfig/alma9.txt, tutorials/CMakeLists.txt
The `tmva-cpu` BLAS-accelerated TMVA backend uses the openblas version found on the system, but NumPy also ships its own `openblas` library when installed with pip.
If both openblas versions are loaded, segfaults can occur if they are incompatible. We currently see this on the `alma9` CI runners.
The minimal remedy for this is to just disable the TMVA BLAS backend. Nobody is using the CPU to train neural nets nowadays anyway.
Like this, we don't have to disable features like PyMVA or RBDT.
Backport of https://github.com/root-project/root/pull/15302.
=> [v630][CI] Disable `tmva-cpu` on `alma9` to avoid openblas clashes with NumPy

.github/workflows/root-ci-config/buildconfig/alma9.txt, tutorials/CMakeLists.txt
The `tmva-cpu` BLAS-accelerated TMVA backend uses the openblas version found on the system, but NumPy also ships its own `openblas` library when installed with pip.
If both openblas versions are loaded, segfaults can occur if they are incompatible. We currently see this on the `alma9` CI runners.
The minimal remedy for this is to just disable the TMVA BLAS backend. Nobody is using the CPU to train neural nets nowadays anyway.
Like this, we don't have to disable features like PyMVA or RBDT.
Backport of https://github.com/root-project/root/pull/15302.
=> [v632][CI] Disable `tmva-cpu` on `alma9` to avoid openblas clashes with NumPy

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx, bindings/pyroot/cppyy/patches/CPyCppyy-Disable-implicit-conversion-to-smart-ptr.patch, bindings/pyroot/cppyy/sync-upstream
The automatic conversion of ordinary obejcts to smart pointers is disabled for PyROOT because it can cause trouble with overload resolution. If a function has overloads for both ordinary objects and smart pointers, then the implicit conversion to smart pointers can result in the smart pointer overload being hit, even though there would be an overload for the regular object. Since PyROOT didn't have this feature before 6.32 anyway, disabling it was the safest option.
Closes #15117.
Backport of https://github.com/root-project/root/pull/15125.
=> [v632][PyROOT] Disable automatic conversion of regular to smart pointers

tree/ntuple/v7/doc/architecture.md, tree/ntuple/v7/src/RPageStorageFile.cxx
After discussion, we only want to use `RRawFile` for files of dynamic type `TFile`, `TDavixFile`, and `TNetXNGFile`. Otherwise the native `TFile` (subclass) is wrapped in a `RRawFileTFile`.
FYI @makortel @Dr15Jones
=> [ntuple] Tweak TFile ownership model for reading

roofit/roofit/inc/RooUniform.h, roofit/roofit/src/RooUniform.cxx, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/inc/RooRecursiveFraction.h, roofit/roofitcore/src/RooRecursiveFraction.cxx, roofit/roofitcore/test/testRooFuncWrapper.cxx
These classes are used in the CMS Higgs discovery analysis, that's why we want to support this now.
=> [RF] Add codegen+AD support for `RooUniform` and `RooRecursiveFraction`

tree/treeplayer/src/TTreeFormula.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-10923
k starts at 0 and should go at max until Ndim-1
This bug was here since 24y :)
https://github.com/root-project/root/commit/6b5ac6dbb79d33682e7e3b815abf6ca4eb3db03e#diff-76114d41c696ac3adf8349c86c2be74751b8ed81cebf74a075144aa727654372
At that point, there was fUsedCumulSizes which had a size of MAXDIM+1 instead of MAXDIM
=> [tree] Fix subscript overflow in cumulSizes

io/io/inc/ROOT/RRawFile.hxx, io/io/src/RRawFile.cxx, io/io/src/RRawFileUnix.cxx, io/io/src/RRawFileWin.cxx, io/io/test/RRawFile.cxx, net/davix/src/RRawFileDavix.cxx, net/netxng/src/RRawFileNetXNG.cxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RPageStorageFile.cxx
The RPageSourceFile's use of RRawFile should not use the raw file's block cache layer for the page reads. The page source knows exactly which byte ranges are required. It makes itself I/O scheduling decisions (e.g., coalescing, vector reads) to optimize the read pattern.
For opening the file, getting the RNTuple anchor and meta-data, however, we keep the buffered reads.
=> [ntuple] Don't use RRawFile cache for page reads

tutorials/v7/ntuple/ntpl008_import.C, tutorials/v7/ntuple/ntpl010_skim.C
I was going through the [RNTuple tutorials](https://root.cern/doc/master/group__tutorial__ntuple.html) and I noticed that there are two of them that fail to compile because there are headers that are not included (although they run fine in interactive mode).
I just added the missing headers so that they can be compiled.
=> [tutorials] Add missing headers in RNTuple tutorials

tree/treeplayer/inc/TTreeReaderArray.h
as is the case with function GetReadStatus
This prevents the crash on line 35 (stack trace by @amadio on https://its.cern.ch/jira/browse/ROOT-11006):
The test for this PR is the same as in https://github.com/root-project/root/pull/15317/files
=> [tree] public method should be safe against fImpl = null

io/io/inc/ROOT/RRawFile.hxx
This was changed in commit 09010c5ed5 ("[io] make buffering state explicit in RRawFile").
=> [io] Remove wrong comment in RRawFile

tree/treeplayer/src/TTreeFormula.cxx
Avoids the crash reported in https://its.cern.ch/jira/browse/ROOT-10795
It does not solve the underlying cause, which is that TFormLeafInfo line 219 is called, that returns type = 64. Then:
switch (type) reaches the default and returns a null:
=> [tree] prevent crash due to null access in clones

tree/treeplayer/src/TTreeFormula.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-8256
With the change, you would get error messages of this type:
`Error in <TTreeFormula::TTreeFormula>: The length of the formula (1035) exceeds the maximum allowed (1024)`
=> [tree] Warn about too long TTreeFormula and double limit

gui/webdisplay/CMakeLists.txt, gui/webdisplay/src/RWebDisplayHandle.cxx
If local web display configured,
only build variants will be tested.
Fixes issue #15340
=> [webgui] try local displays only if they build

gui/CMakeLists.txt, gui/webdisplay/src/RWebDisplayHandle.cxx
Check qt5/qt6/cef in cmake before building ROOTWebDisplay library
Required to correctly detect if such displays can be used by default
=> [webgui] check local displays first

tree/tree/src/TChain.cxx, tree/tree/test/TChainParsing.cxx
When ? is used in TChain::Add in both the filename for globbing and as a starter for a string, TChain::Add fails to find the file, because everything after the ? is interpreted as the query string.
This commit changes the behaviour so that `?` characters before the _last_ (should it be the first or something else?) '.root' are wildcard characters.
This PR fixes #10239
=> [Tree] Fix globbing of ? when also used as query

tutorials/CMakeLists.txt
=> [ci] Disable tutorial-roostats-rs101_limitexample-py on Win32

requirements.txt
Numba 0.59 with Python 3.12 was already released:
https://github.com/numba/numba/releases
With this change, we make sure the numba features in ROOT are still tested in environments with Python 3.12 (like for example Ubuntu 24.04 or Arch Linux as of today).
=> Add Python 3.12-compatible `numba` version in requirements.txt

roofit/roofit/src/RooMomentMorphFuncND.cxx
The `_pdfMode` data member was added for ROOT 6.30,and I forgot to consider it in the copy constructor. A classic mistake.
This fix needs to be backported up to ROOT 6.30.
Thanks to this forum post for noticing the problem:
https://root-forum.cern.ch/t/using-roomomentmorphfuncnd/58889
=> [RF] Consider `_isPdfMode` member in RooMomentMorphFuncND copy constructor

CMakeLists.txt, build/unix/makedistsrc.sh
Fixes the `make distsrc` command in the release checklist, so far working until 6.30
=> [cmake] Fix distsrc script.

core/base/test/TBitsTests.cxx, core/base/test/TNamedTests.cxx, core/base/test/TQObjectTests.cxx, core/meta/test/testTEnum.cxx, core/thread/test/testRWLock.cxx, hist/hist/test/test_THBinIterator.cxx, math/mathcore/test/stress/testGenVector.cxx, math/mathcore/test/stress/testSMatrix.cxx, math/mathcore/test/stress/testVector.cxx, math/mathcore/test/stress/testVector34.cxx, math/mathcore/test/testGradient.cxx, math/mathcore/test/testGradientFitting.cxx, math/mathmore/test/testStress.cxx, math/vecops/test/vecops_rvec.cxx, roofit/multiprocess/test/test_Job.cxx, roofit/roofitZMQ/test/test_ZMQ.cpp, roofit/roofitcore/test/gtest_wrapper.h, tmva/tmva/test/DNN/RNN/TestRecurrentForwardPass.cxx, tmva/tmva/test/DNN/RNN/TestRecurrentForwardPassCpu.cxx, tree/dataframe/test/dataframe_datasetspec.cxx, tree/dataframe/test/dataframe_definepersample.cxx, tree/dataframe/test/dataframe_regression.cxx, tree/dataframe/test/dataframe_samplecallback.cxx, tree/dataframe/test/dataframe_simple.cxx, tree/dataframe/test/dataframe_vary.cxx, tree/ntuple/v7/test/ntuple_test.hxx, tree/readspeed/test/readspeed_general.cxx, tree/tree/test/TOffsetGeneration.cxx, tree/tree/test/friendinfo.cxx
It appears ROOT already depends on at least GTest 1.10.0, by using the following in some places without compatibility code:
* `GTEST_SKIP`
* `TestWithParam` with non-default constructible type
* The new "test suite" naming instead of the old "test case" (I found at least `TYPED_TEST_SUITE` and `SetUpTestSuite` + `TearDownTestSuite`).
Given that an older version is only found on EL8, where we have been using `builtin_gtest` since a while, I propose to drop the remaining compatibility code.
=> Globally assume at least GTest version 1.10.0

.github/workflows/root-ci-config/buildconfig/fedora38.txt, .github/workflows/root-ci.yml
The distribution is at its EOL.
[I tried to resubmit the PR and test automatic backporting]
=> [skip-ci][ci] Remove Fedora 38 builds

core/metacling/src/TClingCallbacks.cxx, core/metacling/src/TClingCallbacks.h, interpreter/cling/include/cling/Interpreter/InterpreterCallbacks.h, interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp, interpreter/cling/lib/Interpreter/MultiplexInterpreterCallbacks.h
This will allow us to simplify our ASTConsumer model instead of creating many multiplexers that are not needed. That should simplify adoption of latest versions of clad.
=> [core] Remove never used code from the callbacks.

tree/dataframe/CMakeLists.txt, tree/dataframe/inc/ROOT/RDF/GraphNode.hxx, tree/dataframe/inc/ROOT/RDF/RAction.hxx, tree/dataframe/inc/ROOT/RDF/RColumnRegister.hxx, tree/dataframe/inc/ROOT/RDF/RDefinePerSample.hxx, tree/dataframe/inc/ROOT/RDF/RDefineReader.hxx, tree/dataframe/inc/ROOT/RDF/RFilter.hxx, tree/dataframe/inc/ROOT/RDF/RInterface.hxx, tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx, tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/inc/ROOT/RDF/RRange.hxx, tree/dataframe/inc/ROOT/RDF/RVariationReader.hxx, tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx, tree/dataframe/src/RDFColumnRegister.cxx, tree/dataframe/src/RDFGraphUtils.cxx, tree/dataframe/src/RDFInterfaceUtils.cxx, tree/dataframe/src/RDefineReader.cxx, tree/dataframe/src/RInterfaceBase.cxx, tree/dataframe/src/RJittedFilter.cxx, tree/dataframe/src/RLoopManager.cxx, tree/dataframe/src/RVariationReader.cxx, tree/dataframe/test/dataframe_utils.cxx
Move the actual creation of an RDefineReader and the relative string representing its column name to a centralized register in the RLoopManager. The RColumnRegister only holds references to that.
Fixes #14510
=> Reduce the memory footprint of the computation graph

bindings/jupyroot/CMakeLists.txt, bindings/jupyroot/python/JupyROOT/helpers/handlers.py, bindings/pyroot/pythonizations/src/IOHandler.cxx, bindings/pyroot/pythonizations/src/PyROOTModule.cxx
Having only one CPython extension for PyROOT definitely makes things easier. The `libJupyROOT` was very small.
=> [PyROOT] Merge `libROOTPythonizations` and `libJupyROOT`

roofit/multiprocess/src/Job.cxx, roofit/roofitcore/CMakeLists.txt, roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodGradientWrapper.h, roofit/roofitcore/inc/RooFit/TestStatistics/LikelihoodWrapper.h, roofit/roofitcore/inc/RooFit/TestStatistics/SharedOffset.h, roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx, roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.h, roofit/roofitcore/src/TestStatistics/LikelihoodGradientWrapper.cxx, roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx, roofit/roofitcore/src/TestStatistics/LikelihoodJob.h, roofit/roofitcore/src/TestStatistics/LikelihoodSerial.cxx, roofit/roofitcore/src/TestStatistics/LikelihoodSerial.h, roofit/roofitcore/src/TestStatistics/LikelihoodWrapper.cxx, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx, roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.h, roofit/roofitcore/src/TestStatistics/SharedOffset.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx, roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
Triggered by a failure to run an ATLAS Higgs combination fit using the MultiProcess-parallelized LikelihoodJob, this PR changes the way offsetting is handled in the TestStatistics::LikelihoodWrapper family of classes. This in turn improves precision of evaluations, making many parallelized likelihood evaluations now bit-wise exactly equal to non-parallel evaluations. This allows us to better debug the Higgs fit. After this PR, the public Higgs workspace used in rootbench can be fit with LikelihoodJob enabled.
In detail, this PR changes the following:
- Increased precision:
* Per-component offsets: instead of one offset for the total LikelihoodWrapper, we switched to a vector of offsets: one for each likelihood component. This makes a difference only for RooSumL fits, i.e. simultaneous PDF …
=> [RF] LikelihoodJob improved precision

bindings/pyroot/pythonizations/CMakeLists.txt, bindings/pyroot/pythonizations/python/ROOT/JsMVA/__init__.py
Follow-up to 38ac97e5a.
Before that commit, the `JsMVA` Python sources were always included in
the build, even if `tmva=OFF`. This was accidentally changed, and breaks
`import ROOT` in a notebook if `tmva` is not enabled.
=> [PyROOT] Correct JsMVA module path and always include JsMVA in build 

core/unix/CMakeLists.txt, core/unix/src/TUnixSystem.cxx
Systems with older versions of glibc do not have modern functions to get cryptographically secure random numbers. Introduce a fallback to using `/dev/urandom` in such cases. A notable example is the conda-build environment which is based on Centos7 where the glibc version is 2.17
This change is *required* to fix the conda build, so it must be backported to 6.32
=> [core] Fallback to urandom for increased compatibility

cmake/modules/RootBuildOptions.cmake, cmake/modules/SearchInstalledSoftware.cmake
The `builtin_openssl` option was specifically introduced with ROOT 6.06 for macOS support:
* https://root.cern.ch/doc/v606/release-notes.html
* https://github.com/root-project/root/commit/e113fd8e9c56f5cdf23f2fd7d5f2504234ffca0e
For Linux or Windows, it is not needed.
@jblomer
=> [CMake] Don't support `builtin_openssl` on Linux

bindings/pyroot/pythonizations/python/ROOT/JsMVA/DataLoader.py, bindings/pyroot/pythonizations/python/ROOT/JsMVA/Factory.py, bindings/pyroot/pythonizations/python/ROOT/JsMVA/JPyInterface.py, bindings/pyroot/pythonizations/python/ROOT/JsMVA/OutputTransformer.py
JsMVA was moved to ROOT.JsMVA, so "from JsMVA import ..." no longer works
=> Update JsMVA imports

core/base/src/TDirectory.cxx, core/cont/inc/TClassTable.h, core/cont/src/TClassTable.cxx
This fixes https://github.com/root-project/root/issues/12552
This commit add a mutex for the TClassTable inner operations.
Several changes were needed to insure that operation that can
either take the ROOT global lock or recursively call TClassTable
are executed outside of the TClassTable critical sections.
=> [v626] TClassTable: fix data race between dlopen and other uses

core/base/src/TAttFill.cxx, core/base/src/TAttMarker.cxx, graf2d/gpad/src/TColorWheel.cxx, graf2d/graf/src/TGaxis.cxx, graf3d/g3d/src/TPolyLine3D.cxx, graf3d/g3d/src/TView3D.cxx, hist/histpainter/src/TGraphPainter.cxx, math/mathcore/src/TMath.cxx, tutorials/legacy/rootenv.C
warning: declaration without the 'auto' keyword is deprecated: function '...' [-Wdeprecated-declarations]
=> [skip-ci] fix deprecation warnings in macros

bindings/pyroot/pythonizations/python/ROOT/_facade.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_drawables.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabscollection.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_utils.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tseqcollection.py, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/test/tcollection_iterable.py, bindings/pyroot/pythonizations/test/tcollection_listmethods.py, bindings/pyroot/pythonizations/test/tcollection_operators.py, bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py, bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py, bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py, bindings/pyroot/pythonizations/test/titer_iterator.py, bindings/pyroot/pythonizations/test/tobject_contains.py, bindings/pyroot/pythonizations/test/tseqcollection_itemaccess.py, bindings/pyroot/pythonizations/test/tseqcollection_listmethods.py, bindings/pyroot/pythonizations/test/ttree_branch_attr.py, bindings/pyroot/pythonizations/test/ttree_iterable.py, bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py
The `libcppyy` is an implementation detail of `cppyy` that we should not include directly.
This is done to anticipate more refactoring later.
=> [PyROOT] Don't import `libcppyy` directly in PyROOT

core/meta/src/TEnum.cxx
This allows to resolved using statement and find the target enum.
This fixes #15406 and is tested by https://github.com/root-project/roottest/pull/1118
This also fixes: https://github.com/root-project/root/issues/12685
=> TEnum::GetEnum normalize name before search.

tree/ntuple/v7/inc/ROOT/RColumn.hxx, tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx, tree/ntuple/v7/src/RColumn.cxx, tree/ntuple/v7/test/ntuple_storage.cxx
It costs a factor 3x in memory, so experiments might want to disable the optimization for large models with many fields - in that case it is not expected to provide a sufficient benefit because most columns will have less elements per cluster than the target page size.
=> [ntuple] Add option to turn off tail page optimization

core/foundation/inc/ROOT/StringUtils.hxx, tmva/sofie/inc/TMVA/ROperator_ConvTranspose.hxx
to avoid warnings when building docu
=> [skip-ci] fix doxygen parnames

README/ReleaseNotes/v632/index.md, roofit/roofit/inc/RooParamHistFunc.h, roofit/roofit/src/RooParamHistFunc.cxx, roofit/roofit/test/testRooParamHistFunc.cxx, tutorials/roofit/rf709_BarlowBeeston.C, tutorials/roofit/rf709_BarlowBeeston.py
The `RooParamHistFunc` doesn't take any observable RooRealVar as
constructor argument. It assumes as observable the internal variables in
the passed RooDataHist. This means it is in most contexts unusable,
because the input can't be changed, other than loading a different bin
in the dataset.
This also breaks the Barlow-Beeston tutorial since the new evaluation
backend is the default, and it is more sentitive to these issues:
https://root.cern.ch/doc/master/rf709__BarlowBeeston_8C.html
There was actually a constructor that took a `RooAbsArg x`, but it was
simply ignored.
To fix all these problems, the existing constructors were replaced by a
new one that takes the observable explicitly, and this is mentioned in
the release notes.
The class is not used much, because ussually people use …
=> [RF] Fix computation graphs with RooParamHistFunc

.github/workflows/root-ci-config/buildconfig/alma9.txt, .github/workflows/root-ci-config/buildconfig/fedora39.txt, tutorials/CMakeLists.txt
Now that we're using a system-compatible version of NumPy on the CI images for these platforms, the TMVA tests should all pass again.
=> [TMVA] Enable again all tests on `alma9` and `fedora39`

roofit/roofit/inc/RooCBShape.h, roofit/roofit/src/RooCBShape.cxx, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/test/testRooFuncWrapper.cxx
The test of using the code in the RooFit AD backend is not enabled yet, because it doesn't seem to work with the current version of Clad in ROOT.
However, the code is reused also for the normal `evaluate()` function, which is tested by `testRooCrystalBall.cxx`. So it would be good to integrate this change now, such that we can easily test in the CI if the `RooCBShape` works with a future version of Clad.
=> [RF] Implement code generation for `RooCBShape`

cmake/modules/RootBuildOptions.cmake
Don't disable the runtime C++ modules when specifying `-Dminimal=ON`
=> [cmake] Fix issue #15447

tree/treeplayer/src/TTreeFormula.cxx
Fixes https://its.cern.ch/jira/browse/ROOT-10390
=> [tree] raise error instead of crash when trying to access null GetTree

tree/treeplayer/src/TTreeFormula.cxx
Remove trailing whitespaces to avoid warnings like these:
```
/home/rembserj/code/root/tree/treeplayer/src/TTreeFormula.cxx:3760:97: warning: backslash and newline separated by space
3760 |           "Could not init branch associated to this leaf (%s).", leaf->GetName());              \
|
/home/rembserj/code/root/tree/treeplayer/src/TTreeFormula.cxx:3829:97: warning: backslash and newline separated by space
3829 |          }                                                                                      \
|
```
=> [tree] Remove trailing whitespaces that trigger warnings at config time

core/meta/test/testTEnum.cxx, core/metacling/src/TClingClassInfo.cxx
This fixes #15460.
Extend the test accordingly.
=> [v632] TEnum::GetUnderlying add support for typedefs.

hist/hist/src/TH1.cxx, hist/hist/src/TH2.cxx, hist/hist/src/TH3.cxx
/opt/root_src/hist/hist/src/TH3.cxx:63: warning: multiple use of section label 'intmax' while adding anchor, (first occurrence: /opt/root_src/hist/hist/src/TH2.cxx, line 61)
and fix repeated asterisks too, as well as add line break for easier readability
=> [skip-ci] fix doxygen warnings about duplicate labels

cmake/modules/RootBuildOptions.cmake, cmake/modules/SearchInstalledSoftware.cmake
The `-Dall` option is for enabling all ROOT features, which should not include dedicated tests. The DistRDF tests should only be used by developers and packagers, so it's not a "feature" that should automatically be enabled.
Also, if someone enables these tests it's clearly intentional. If the requirements for the tests are not present, there should therefore be a configuration failure, no matter if `fail-on-missing` is enabled or not.
=> [CMake] Don't treat DistRDF tests as features

math/matrix/src/TDecompChol.cxx
Replace repeated divisions by multiplications of 1/x
=> remove repeatative divisions in TDecompChol::Decompose

core/meta/test/testTEnum.cxx, core/metacling/src/TClingClassInfo.cxx
This fixes #15460.
Extend the test accordingly.
=> TEnum::GetUnderlying add support for typedefs.

core/meta/src/TEnum.cxx, core/meta/test/testTEnum.cxx, core/metacling/src/TClingClassInfo.cxx
This allows to resolve using statement and find the target enum.
This fixes #15406# This Pull request:
=> [v630] TEnum::GetEnum normalize name before search.

cmake/modules/RootBuildOptions.cmake
This is a followup to 5e424e4, where the Python finding was moved into `SearchInstalledSoftware.cmake`.
However, what I missed is that there was a check in `RootBuildOptions` that disabled PyROOT by default if Python is not found, which is now not the case at that point! Therefore, ROOT builds won't have PyROOT by default anymore, which is a bad mistake.
Fortunately, the check is entirely redundant and this commit suggests to remove it. There is already a check in `SearchInstalledSoftware` where PyROOT (and `tmva-pymva`) are disabled when the Python development headers where not found.
Also, this kind of logic to conditionally change the defaults it bad because it doesn't go well with the "fail on missing" paradigm (if `fail-on-missing` is enabled).
=> [CMake] Don't check if Python headers are found in `RootBuildOptions`

.typos.toml, roofit/roofit/test/testRooGaussian.cxx, roofit/roofitZMQ/src/ZeroMQPoller.cpp, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/test/stressRooFit_tests.h, roofit/roofitcore/test/testRooSimultaneous.cxx, roofit/roostats/src/LikelihoodInterval.cxx, roofit/xroofit/src/xRooNode.cxx
Thanks to this forum post:
https://root-forum.cern.ch/t/extended-option-removed-from-fitto-and-createnll/59283
Needs to be backported to 6.32 and 6.30.
=> [RF] Add back accidentally removed docs for `RooFit::Extended()`

README/ReleaseNotes/v632/index.md
Closes #15153, as confirmed in this comment:
https://github.com/root-project/root/issues/15153#issuecomment-2042301817
=> [relnotes] Mention different `std::string` representation in PyROOT

gui/webdisplay/src/RWebWindow.cxx
Prevent situation with manipulated packet send without HMAC at all could be accepted
=> [webgui] strict check for HMAC signature

gui/webdisplay/src/RWebWindow.cxx
Prevent situation with manipulated packet send without HMAC at all could be accepted
=> [webgui] strict check for HMAC signature [6.32]

CMakeLists.txt
There is a `if(clad)` in the CMakeLists.txt to disable clad if there is no internet connection. However, it doesn't work right now, because it's after `include(RootBuildOptions)`, meaning the `clad` flag is not even set yet (only if explicitly set by the user, but not if we go with the default `clad=ON`).
This logic error is fixed by this commit.
To be backported to the 6.32 release branch.
=> [CMake] Move connection check for `clad` after RootBuildOptions

README/ReleaseNotes/v632/index.md, proof/proof/inc/TProofOutputList.h
This is a follow-up on c97ec173ee589ab2.
In particular, this will avoid a flood of warnings on Jenkins, i.e. for roottest, where proof is still enabled, like here:
https://github.com/root-project/roottest/pull/1125
To be backported to 6.32, where this `TList` constructor is already deprecated.
=> [proof] Remove call to deprecated `TList` constructor

.typos.toml, README/ReleaseNotes/v632/index.md, bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx, bindings/pyroot/pythonizations/python/ROOT/JsMVA/OutputTransformer.py, interpreter/cling/include/cling/Utils/Platform.h, roofit/roofit/test/testRooGaussian.cxx, roofit/roofitZMQ/src/ZeroMQPoller.cpp, roofit/roofitcore/src/RooAbsData.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooAddPdf.cxx, roofit/roofitcore/src/RooDataHist.cxx, roofit/roofitcore/test/stressRooFit_tests.h, roofit/roofitcore/test/testRooSimultaneous.cxx, roofit/roostats/src/LikelihoodInterval.cxx, roofit/xroofit/src/xRooNode.cxx, tutorials/CMakeLists.txt
Backport of recent fixes and improvements. The fix for the cppyy regression is important in particular.
=> [v632] Backport of recent fixes and improvements

interpreter/CMakeLists.txt, interpreter/cling/CMakeLists.txt
See https://cmake.org/cmake/help/latest/policy/CMP0148.html
=> Comply with CMP0148

roofit/roofit/inc/RooBernstein.h, roofit/roofit/src/RooBernstein.cxx, roofit/roofit/src/RooLandau.cxx, roofit/roofit/test/testRooBernstein.cxx, roofit/roofitcore/inc/RooFit/Detail/AnalyticalIntegrals.h, roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h, roofit/roofitcore/test/testRooFuncWrapper.cxx
Adding code generation and AD support for the final class in upstream RooFit that is used in the CMS Higgs discovery workspace: the RooBernstein.
Also:
* fix missing variable warning in `RooCBShape.cxx`
* fix AD support for RooLandau by using code that clad can digest
* implement test for RooLandau fits with AD
=> [RF] Support RooBernstein in code generation for AD

interpreter/cling/tools/driver/CMakeLists.txt
Export the following missing symbols:
```
void * __ptr64 __cdecl operator new(unsigned __int64,struct std::nothrow_t const & __ptr64)
void * __ptr64 __cdecl operator new[](unsigned __int64,struct std::nothrow_t const & __ptr64)
```
and
```
void * __cdecl operator new[](unsigned int,struct std::nothrow_t const &)
void * __cdecl operator new(unsigned int,struct std::nothrow_t const &)
```
Fixes root-project/cling#442
=> [skip-ci][windows][cling] Export missing symbols

tree/ntuple/v7/inc/ROOT/REntry.hxx, tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/test/ntuple_descriptor.cxx, tree/ntuple/v7/test/ntuple_limits.cxx
Several fixes to meta-data handling that grew quadratic in the number of fields. The RNTuple limits tests is adjusted from 10k to 40k fields (30s --> 2s).
Finding pages in the RPagePool is a remaining contributor to a noticeable slowdown with a growing number of fields. That will be addressed in a follow-up PR.
=> [ntuple] Improve handling of large numbers of fields

tree/ntuple/v7/inc/ROOT/RField.hxx
This makes it consistent with `GetColumnRepresentations()` where the default implementation does not attach any columns to the field.
=> [ntuple] Provide default RFieldBase::GenerateColumnsImpl

tree/ntuple/v7/inc/ROOT/RField.hxx
Commit 05167a99e0 ("Provide default RFieldBase::GenerateColumnsImpl") introduced compiler warnings with GCC because `RArrayAsRVecField` only overrides one of the two overloads with default implementations.
=> [ntuple] Fix warning about hidden virtual function

tree/ntuple/CMakeLists.txt, tree/ntuple/v7/doc/architecture.md, tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx, tree/ntuple/v7/inc/ROOT/RNTupleFillStatus.hxx, tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx, tree/ntuple/v7/test/ntuple_basics.cxx, tree/ntuple/v7/test/ntuple_test.hxx
This method can be called instead of `Fill` if the `RNTupleWriter` or `RNTupleFillContext` should not commit the cluster automatically. Instead the calling code must check `ShouldCommitCluster()` and call it explicitly if necessary.
FYI @makortel this should be the interface that we were discussing some time ago, and should also allow to append multiple RNTuples into a single `TFile` using parallel writing: The framework must only call `FillNoCommit` and manually synchronize access to the underlying `TFile` while explicitly invoking `CommitCluster`.
=> [ntuple] Add FillNoCommit method and RNTupleFillStatus

graf2d/gpad/src/TCanvas.cxx
Call `Modified()` method for the canvas itself - there are no logical reasons why `gPad->Modified()`  was called
Instead calling `SetName(name)` directly set `fName` member in all TCanvas constructors. 
This avoids triggering of `Modified()` signal from the constructor itself.
Fix logic around empty canvas name in `TCanvas::SaveSource`. 
There also use direct assignment of `fName` member.
=> [gpad] Change TCanvas::SetName() implementation

tree/dataframe/src/RDFInterfaceUtils.cxx
In the jitted version of the `Vary` transformation a node is allocated on the heap and its address is passed down to the function `JitVariationHelper`, which is also responsible for deleting the allocated memory. In case a mismatch in the return type of the jitted function given to the Vary call is detected, we throw an error to inform the user they should return an RVec for the Vary to properly work. This means that the call to JitVariationHelper does not happen, thus the memory of the node is not deallocated. This commit corrects that behaviour by properly deleting the pointer before throwing the exception.
Thanks to the address sanitizer:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f28c78d9e28 in operator new(unsigned long) (/lib64/libasan.so.8+0xd9e28) (BuildId: …
```
=> [df] Delete allocated node before throwing error

gui/cefdisplay/src/gui_handler.cxx, gui/webdisplay/src/RWebWindow.cxx, gui/webgui6/src/TWebCanvas.cxx, net/http/src/THttpServer.cxx
1. Do not use `gSystem->AccessPath` from CEF handler, may block because of mutex usage
2. Remove debug output from THttpServer and TWebCanvas
3. Properly handle `local` connection in auth check
=> [webgui] Fix CEF handler, reduce debug output

.github/workflows/root-ci.yml
if "[skip ci]" is detected in the PR title, the CI does not start. This is done to have at least one string in common with the ones the GH CI uses for commits.
The test of this PR is that the CI does not start given its title.
=> [skip ci][ci] New string to skip CI

tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
This avoids the following type of warning (obtained when compiling ROOT with -fsanitize=thread)
```
inlined from ‘virtual std::vector<ROOT::Experimental::RNTupleLocator> ROOT::Experimental::Internal::RPageSinkDaos::CommitSealedPageVImpl(std::__ROOT::span<ROOT::Experimental::Internal::RPageStorage::RSealedPageGroup>)’ at /rootproject/rootsrc/tree/ntuple/v7/src/RPageStorageDaos.cxx:417:28:
/usr/include/c++/13/bits/basic_string.h:1079:16: warning: ‘*(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)((char*)&locator + offsetof(ROOT::Experimental::RNTupleLocator, ROOT::Experimental::RNTupleLocator::fPosition.std::variant<long unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, …
```
=> [rntuple] Default initialize data member of RNTupleLocator

roofit/roofitcore/test/testNaNPacker.cxx
This is a new test that got introduced with eb7d8190ba3.
Unfortunately, it didn't pass in the nightlies on Windows 10 x86 Debug, so it needs to be disabled on Windows.
=> [RF] Disable RooNaNPacker.PackedNaNPreservedAfterArithmetic on Windows

roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofitcore/inc/RooHistFunc.h
The PiecewiseInterpolation class is used in the context of HistFactory models, where is is always used the same way: all RooAbsReals in _lowSet, _histSet, and also nominal are 1D RooHistFuncs with with same structure.
Therefore, we can make a big optimization: we get the bin index ony once here in the generated code for PiecewiseInterpolation. Then, we also rearrange the histogram data in such a way that we can always pass the same arrays to the free function that implements the interpolation, just with a dynamic offset calculated from the bin index.
This change is covered by the `testHistFactory` unit test.
Together with the change suggested in the other draft PR, where the generated code is split up into separate functions for each channel, this PR addresses the plan of work item …
=> [RF] Optimize code generated from `PiecewiseInterpolation` for use in AD

core/testsupport/src/TestSupport.cxx
Many RooFit test fails on s390x due to a warning about RooNaNPacker not being implemented for big endian.
There are too many of them to add RAIIs for each of them, so I added the warning to the default list in this PR.
=> Ignore warnings

math/mathcore/inc/Math/CladDerivator.h, roofit/histfactory/src/PiecewiseInterpolation.cxx
To avoid fallback to numeric differentiation because the function is not
inlined.
The pullbacks were automatically generated with Clad master, and then
manually simplified. It was carefully checked that the updated unit
tests cover all code branches of the pullback.
=> [math][RF] Define pullback of `ROOT::Math::landau` functions for AD

.github/workflows/root-ci.yml, builtins/zlib/adler32.c, builtins/zlib/compress.c, builtins/zlib/crc32.c, builtins/zlib/gzclose.c, builtins/zlib/gzlib.c, builtins/zlib/gzread.c, builtins/zlib/gzwrite.c, builtins/zlib/infback.c, builtins/zlib/inffast.c, builtins/zlib/inftrees.c, builtins/zlib/trees.c, builtins/zlib/uncompr.c, builtins/zlib/zutil.c, cmake/modules/SearchInstalledSoftware.cmake
No longer supported by (future) C standards. Currently just emits warnings (eg. MacOS 14)
Currently not tested in CI.
=> Remove the K&R style definitions from builtin zlib (part 2)

graf2d/asimage/src/libAfterImage/export.c, graf2d/asimage/src/libAfterImage/import.c
- When building in MacOS with afterimage (building ROOT from spack), I consistently get the following error:
```
export.c:159:18: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
realfilename = safemalloc( dirname_len+filename_len+1 );
^
./asim_afterbase.h:220:24: note: expanded from macro 'safemalloc'
#define safemalloc(s)   malloc(s)
^
export.c:159:18: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
./asim_afterbase.h:220:24: note: expanded from macro 'safemalloc'
#define safemalloc(s)   malloc(s)
^
export.c:177:2: error: call to undeclared library function 'free' with type 'void (void *)'; ISO C99 and later do not …
```
=> Do not undef HAVE_STDLIB_H in export.c for libAfterImage

etc/runfirefox.sh, gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowWSHandler.hxx
When reloading web widget in QT5/QT6/CEF widget,
new widget loads faster than old connection is closed.
Therefore allow new key checks when loading HTML page
Remove debug output from firefox start script
=> [webgui] fix handling of local displays like qt5 or cef

bindings/pyroot/pythonizations/test/CMakeLists.txt, requirements.txt, tutorials/CMakeLists.txt
Closes https://github.com/root-project/root/issues/14553.
This PR adds the dependencies for the TMVA GNN unit tests to the
docker images via the `requirements.txt`. However, this will only have a
delayed effect until the images are re-built. Therefore, we can't
validate for now that the tests actually work.
Once the missing packages make it into the CI images, a PR should be
opened to revert this commit.
For the JsMVA dependency, we don't have to worry about anything.
The JsMVA tests have already been temporarily disabled by @dpiparo 7 years ago:
https://github.com/root-project/roottest/blame/master/python/JsMVA/CMakeLists.txt
Note: adding the new dependencies only grows the environment by 20 MB, which is less then 1 % of a size increase (the size of the environment is currently 2.3 GB).
=> [TMVA] Add missing TMVA python dependencies to requirements.txt

bindings/pyroot/pythonizations/test/CMakeLists.txt, requirements.txt, tutorials/CMakeLists.txt
The last commit adds the dependencies for the TMVA GNN unit tests to the docker images via the `requirements.txt`. However, this will only have a delayed effect until the images are re-built. Therefore, we can't validate for now that the tests actually work.
Once the missing packages make it into the CI images, a PR should be opened to revert this commit.
Backport of https://github.com/root-project/root/pull/15512.
=> [v632][TMVA] Add missing TMVA python dependencies to requirements.txt

bindings/pyroot/pythonizations/test/CMakeLists.txt, requirements.txt, tutorials/CMakeLists.txt
The last commit adds the dependencies for the TMVA GNN unit tests to the docker images via the `requirements.txt`. However, this will only have a delayed effect until the images are re-built. Therefore, we can't validate for now that the tests actually work.
Once the missing packages make it into the CI images, a PR should be opened to revert this commit.
Backport of https://github.com/root-project/root/pull/15512.
=> [v630][TMVA] Add missing TMVA python dependencies to requirements.txt

roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Using template functions in the generated code can cause linker errors,
which is avoided with this suggested commit.
To be backported to the 6.32 branch.
=> [RF] Small fixup for using RooFit with new Clad 1.5

roofit/histfactory/src/FlexibleInterpVar.cxx, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
Using template functions in the generated code can cause linker errors, which is avoided with this suggested commit.
Backport of https://github.com/root-project/root/pull/15502.
=> [v632][RF] Small fixup for using RooFit with new Clad 1.5

README/ReleaseNotes/v632/index.md, roofit/histfactory/src/PiecewiseInterpolation.cxx, roofit/roofit/test/testFitPerf.cxx, roofit/roofitcore/src/FitHelpers.cxx, roofit/roofitcore/src/RooAbsPdf.cxx, roofit/roofitcore/src/RooDerivative.cxx, tutorials/roofit/rf514_RooCustomizer.C, tutorials/roofit/rf514_RooCustomizer.py, tutorials/roofit/rf611_weightedfits.C
Added correct treatment of extended term in asymptotically correct method for uncertainty determination in the presence of weights. This improvement will allow for extended unbinned maximum likelihood fits to use the asymptotically correct method. 
-Added extended term to asymptotically correct method to allow for weighted extended maximum likelihood fits
-Usage of logarithmic PDFs for derivatives may have some numerical benefits
-Fixed RooDerivative to not use the parameter range in the step size calculation in case the parameter supplied has no range. This now allows to use the method (and RooDerivative in general) for parameters that do not specify a range. 
-Added warning in case of binned fits. In this case a chi2 fit using the std. treatment of weights should be preferrable.
This PR …
=> [RF] Determine asymptotically correct uncertainties for extended unbinned maximum likelihood fits

core/foundation/inc/TError.h
Adds brief documentation to `R__ASSERT` and `R__CHECK` underlining how they do not get stripped in release mode (which might be unexpected for some users).
Additionally, it uses `R__likely` for the check itself, since the condition is expected to be true.
=> Add doc comments to R__ASSERT/CHECK 

gui/webgui6/inc/TWebCanvas.h, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/index.htm, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/gpad/RAxisPainter.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/hist/TF1Painter.mjs, js/modules/hist/TF2Painter.mjs, js/modules/hist/TF3Painter.mjs, js/modules/hist2d/RHistPainter.mjs, js/modules/hist2d/TGraphPainter.mjs, js/modules/hist2d/THistPainter.mjs, js/modules/io.mjs
By default saved points is fallback solution when evaluation on the client fails.
But one can force usage of saved points with "WebGui.TF1UseSave: 2"
Or one can disable saved points usage "WebGui.TF1UseSave: 0"
Update JSROOT to v 7.7.0 which will be reference for 6.32 release
=> [webcanvas] improve TF1 saved points handling

requirements.txt
The name of the most up-to-date `sonnet` packge is actually `dm-sonnet`:
https://github.com/google-deepmind/sonnet
The old `sonnet` can't be used, because it maximally supports Python 3.8. With ROOT, we want to support all Python versions starting from 3.8.
Follows up on 7d83c00605c4.
I tested locally that the GNN tests work in the updated Python environment.
=> [PyROOT] Replace `sonnet` with `dm-sonnet` in requirements.txt

hist/hist/inc/TPolyMarker.h
Using `pm->SetPoint(pm->GetN(), x, y)` iteratively, as is usual with `TGraph`, leads to an exponentially growing result. Prevent it by clarifying the documentation.
=> [skip-ci] clarify TPolyMarker::GetN difference wrt TGraph::GetN

cmake/modules/FindCUDNN.cmake
The CUDNN version is defined in `cudnn_version.h` and not `cudnn.h` anymore for newer CUDNN versions.
This is the same fix that is also done in PyTorch: https://github.com/pytorch/pytorch/blob/main/cmake/Modules_CUDA_fix/FindCUDNN.cmake
=> [CMake] Fix version detection in `FindCUDNN.cmake`

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/src/RPageStorageFile.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx
Also apply clang-format to the involved files in the process.
`RNTupleFileWriter::Recreate` and `RNTupleFileWriter::Append ` now return a `unique_ptr` rather than a raw pointer, to make it obvious that the caller gets ownership of that pointer.
=> [ntuple] Make RNTupleFileWriter::Recreate/Append return unique_ptr

hist/hist/inc/TH1.h, hist/hist/src/TH1.cxx
Implement the method requested here: https://root-forum.cern.ch/t/a-few-new-member-functions-for-various-classes/59434/3
By default: linecolor = markercolor = fillcolor = -1
If a color is < 0 this method does not change the corresponding color if positive or null it set the color.
For instance:
```
h->SetColor(kRed, kRed);
```
will set the line color and the marker color to red.
=> New Method TH1::SetColors

bindings/pyroot/pythonizations/python/ROOT/JsMVA/Factory.py, bindings/pyroot/pythonizations/python/ROOT/JsMVA/JPyInterface.py, bindings/pyroot/pythonizations/python/ROOT/JsMVA/OutputTransformer.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_crossvalidation.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py, bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx, bindings/pyroot/pythonizations/src/IOHandler.cxx, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTPythonize.h, bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx, bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx, bindings/pyroot/pythonizations/src/RPyROOTApplication.h, bindings/pyroot/pythonizations/src/TClassPyz.cxx, bindings/pyroot/pythonizations/src/TTreePyz.cxx, bindings/pyroot/pythonizations/test/roofit/rooabscollection.py, bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
Fixes https://github.com/root-project/root/issues/15610
As reported on the forum:
https://root-forum.cern.ch/t/memory-leak-in-pyroot-when-using-user-defined-c-macros-from-python-and-ttree-friends/59432
According to that post, the problem is present at least since 6.26/04, but I suspect it has been there forever (at least 6.22 with with cppyy upgrade in 2019). 
I fixed the memory leak in the Pythonization is in the usual way how I fix problems with the PyROOT CPython extension: re-implementing the offending parts in Python and hoping that the problem is gone. Which it is!
Note that the code also had no obvious memory leak before. where it was
using the `CPyCppyy::Instance_FromVoidPtr` function from the CPyCppyy
API. If similar problems appear, this function might have to be
investigated in …
=> [PyROOT] Fix memory leak in TTree `__getattr__` pythonization

geom/geom/src/TGeoMatrix.cxx
When copying the registered identity transformation, the registered flag was not reset appropriately. Observed when rotating overlapping volumes in the pad.
=> [geom] Fix registered identity matrix removal warning

tree/tree/src/TBranch.cxx
Introduced by https://github.com/root-project/root/commit/617f5fb4fab9b92b2a95e506b4801364473672bc
The change to a variable length size was not properly propagated to the rest of the `TBranch::Init` function.
Fixes the recent ubuntu24 failures of the type
```
2400/2509 Test #2432: roottest-root-tree-branches-make ..................................................................***Failed    1.79 sec
-- TEST COMMAND -- 
cd /github/home/ROOT-CI/roottest/root/tree/branches
/usr/bin/timeout -s USR2 1770s /usr/bin/gmake cleantest
-- BEGIN TEST OUTPUT --
/usr/bin/gmake -f Makefile test
gmake[1]: Entering directory '/github/home/ROOT-CI/roottest/root/tree/branches'
Processing runnoname.C...
Warning in <TBranch::TBranch>: No name was given to the leaf number '1' in the leaflist of the branch …
```
=> [tree] Avoid buffer overflow in TBranch

tree/tree/src/TBranch.cxx
Introduced by https://github.com/root-project/root/commit/617f5fb4fab9b92b2a95e506b4801364473672bc
The change to a variable length size was not properly propagated to the rest of the `TBranch::Init` function.
Related to https://github.com/root-project/root/issues/15621
=> [6.32] Backport of #15620

tree/dataframe/src/RDFInterfaceUtils.cxx
It's a small change and it may help with the sporadic `dataframe-vary` unittest failures
=> [6.32] Backport of #15477

bindings/pyroot/pythonizations/test/CMakeLists.txt, tutorials/CMakeLists.txt
This reverts commit baf092324e6e2a9301daff36a780cd064b232c2d.
We can either merge this as-is if the tests pass, or if they don't I'll close this PR without merging and open a GitHub issue about fixing these tests.
=> Revert "[TO REVERT] Never run TMVA GNN tests and tutorials as unit tests"

math/matrix/inc/TMatrixT.h, math/matrix/inc/TMatrixTSym.h, math/matrix/test/testMatrixT.cxx
This PR defines a new method `SetElement()` that allows to efficiently set matrix elements. 
This PR fixes [#15285](https://github.com/root-project/root/issues/15285)
=> [matrix] Fast element setter method

interpreter/cling/CMakeLists.txt
The officially supported way to build LLVM/Clang as a shared library is via the LLVM_BUILD_LLVM_DYLIB and LLVM_LINK_LLVM_DYLIB CMake options (see: https://llvm.org/docs/BuildingADistribution.html).  When built this way, the whole of Clang API is exposed as a shared library (libclang-cpp.so).
* CMakeLists.txt: Query if we're in shared mode via llvm-config, and register the result as LLVM_LIB_IS_SHARED.
[LLVM_LIB_IS_SHARED] <target_link_libraries>: Use the PUBLIC interface of the LLVM shared library.
* lib/Interpreter/CMakeLists.txt [LLVM_LIB_IS_SHARED]: When defined, replace the individual Clang components by clang-cpp.
* lib/MetaProcessor/CMakeLists.txt: Likewise.
* lib/Utils/CMakeLists.txt: Likewise.
* tools/Jupyter/CMakeLists.txt: Likewise.
* tools/driver/CMakeLists.txt: Likewise.
* …
=> build: Allow building Cling using the Clang shared library.

tree/dataframe/inc/ROOT/RDF/RDefineReader.hxx, tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx, tree/dataframe/inc/ROOT/RDF/Utils.hxx, tree/dataframe/src/RDFColumnRegister.cxx, tree/dataframe/src/RDFUtils.cxx, tree/dataframe/src/RDefineReader.cxx
Implement and use a thread-safe container for caching strings that are created and used in the computation graph. Notably, these include the strings representing column names generated by `Define`.
This fixes the recent failures seen on MacOS in the `dataframe-vary` unittest. Since that underlines a thread-safety issue in the overall initialisation phase of MT RDF runs, it should be backported to 6.32
=> Make string caching in RLoopManager thread-safe

tree/ntuple/v7/src/RMiniFile.cxx
This reverts commit 19caf55b88d16ac67d9bfb39380a4d1c89f935e6.
which was failing on Windows and is breaking master
=> Revert "[ntuple] add ClassDefInline to RKeyBlob"

tree/dataframe/inc/ROOT/RCsvDS.hxx, tree/dataframe/inc/ROOT/RDF/RDFDescription.hxx, tree/dataframe/inc/ROOT/RDataSource.hxx, tree/dataframe/inc/ROOT/RNTupleDS.hxx, tree/dataframe/inc/ROOT/RRootDS.hxx, tree/dataframe/src/RDFDescription.cxx, tree/dataframe/src/RInterfaceBase.cxx, tree/dataframe/src/RRootDS.cxx, tree/dataframe/test/datasource_csv.cxx, tree/dataframe/test/datasource_ntuple.cxx
This PR fixes #15617, where the number of files is incorrectly returned by `RInterfaceBase`/`RDFDescription` for RDF's constructed from an `RDataSource`. It involves the addition of `GetNFiles` to the public interface of `RDataSource` and calling it in the relevant places.
=> [DF] Correctly return number of files in `RDFDescription`

CMakeLists.txt
fixes an issue when installing as root changes the permissions of the `etc` folder and makes the installation unusable for other users. This happened because `etc` didn't have enough permissions in the source tree for other users and those are preserved in the installation directory.
The issue is the following, if `etc` has permissions, for example, 700 in the source tree, after compiling as a user and then using `sudo ninja install`, the folder `etc` keeps the same permissions. This is an ls of the installation folder when I install to `/usr/local`:
```
Permissions Size User Date Modified Name
drwxr-xr-x     - root  3 Apr 18:08  bin
drwxr-xr-x     - root  3 Apr 18:08  cmake
drwxr-xr-x     - root  3 Apr 18:08  config
drwx------     - root  3 Apr 18:08  etc
drwxr-xr-x     - root 28 Jan …
```
=> [cmake] Set the permissions for etc and other folders that are in the source tree when installing

core/base/src/TMemberInspector.cxx, core/clingutils/res/TClingUtils.h, core/clingutils/src/TClingUtils.cxx, core/meta/inc/TDictionary.h, core/meta/inc/TInterpreter.h, core/meta/src/TClass.cxx, core/meta/src/TDataMember.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TCling.h, core/metacling/src/TClingBaseClassInfo.cxx, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/src/TClingMethodInfo.cxx, core/metacling/src/TClingTypeInfo.cxx, core/metacling/test/TClingDataMemberInfoTests.cxx, io/rootpcm/src/rootclingIO.cxx
This fixes #13574
This prevents complains about the internals of `unique_ptr` when we are just investigating its suitability for streaming.  
Also do not complains about a transient `std::tuple` even if we can not stream it (for example if one of component is a private entity).
Test at https://github.com/root-project/roottest/pull/1030
=> Do not complain about the internal of unique_ptr.  Do not complain about transient std::tuple.

core/base/src/TMemberInspector.cxx, core/clingutils/res/TClingUtils.h, core/clingutils/src/TClingUtils.cxx, core/meta/inc/TDictionary.h, core/meta/inc/TInterpreter.h, core/meta/src/TClass.cxx, core/meta/src/TDataMember.cxx, core/metacling/src/TCling.cxx, core/metacling/src/TCling.h, core/metacling/src/TClingBaseClassInfo.cxx, core/metacling/src/TClingDataMemberInfo.cxx, core/metacling/src/TClingMethodInfo.cxx, core/metacling/src/TClingTypeInfo.cxx, core/metacling/test/TClingDataMemberInfoTests.cxx, io/rootpcm/src/rootclingIO.cxx
This fixes #13574
This prevents complains about the internals of `unique_ptr` when we are just investigating its suitability for streaming.  
Also do not complains about a transient `std::tuple` even if we can not stream it (for example if one of component is a private entity).
=> [v632] Do not complain about the internal of unique_ptr. Do not complain about transient std::tuple.

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_packing.cxx, tree/ntuple/v7/test/ntuple_serialize.cxx
Addresses several bugs on big-endian architecture, some in the testing code only, some in the actual code. Tested manually on Power8/EL7. Also tested that RNTuple data written on little-endian can be read on big-endian and vice versa.
Fixes #12426
=> [ntuple] Various fixes for big-endian

io/io/src/TKey.cxx
The comment was not considering fDatime, thus reporting the wrong format and size.
=> [io] Update TKey::Sizeof doc comment

hist/hist/inc/TGraph2DAsymmErrors.h, hist/hist/inc/TGraph2DErrors.h, hist/hist/inc/TGraphAsymmErrors.h, hist/hist/inc/TGraphBentErrors.h, hist/hist/inc/TGraphErrors.h, hist/hist/src/TGraph2DAsymmErrors.cxx, hist/hist/src/TGraph2DErrors.cxx, hist/hist/src/TGraphAsymmErrors.cxx, hist/hist/src/TGraphBentErrors.cxx, hist/hist/src/TGraphErrors.cxx
Extends the functionality of `TGraphErrors` class on the manner of the `TGraph` class such that one does not need to prepare arrays with data before creating the `TGraphErrors` class and simply add points one-by-one.
The pull request adds a new method to the class `TGraphErrors` called `AddPointError`
(run as a root script)
```c++
void apge() {
TCanvas *c1 = new TCanvas("c1","A Simple Graph Example",200,10,700,500);
c1->SetGrid();
const Int_t n = 20;
TGraphErrors *gr = new TGraphErrors;
for (Int_t i=0;i<n;i++) {
Double_t x = i*0.1;
gr->AddPointError(i*0.1, 10*sin(x+0.2), 0.3/(x*x+3.), x*x/(x*x + 8.));
}
gr->SetTitle("a simple graph");
gr->GetXaxis()->SetTitle("X title");
gr->GetYaxis()->SetTitle("Y title");
gr->Draw("AP");
// TCanvas::Update() draws the frame, after which one can change …
```
=> [TGraphErrors] add AddPointError method

tree/ntuple/v7/src/RMiniFile.cxx
Same as https://github.com/root-project/root/commit/19caf55b88d16ac67d9bfb39380a4d1c89f935e6 but this time moving RKeyBlob out of the anon namespace which causes compile errors on windows (I missed this in the previous commit, now reverted).
=> [ntuple] add ClassDef to RKeyBlob

tutorials/CMakeLists.txt
After last modification they should be removed from list of tutorials returning not void value.
PR fixes recent problem in CI
See 6.32 Backport here https://github.com/root-project/root/pull/15680
=> Fix problem with timeonaxis tutorials

io/io/src/TKey.cxx
removes commented-out code from TKey involving `kMAXFILEBUFFER`. That code has been commented-out since 2001 and it's unlikely to see use again.
=> [io] TKey: remove dead code

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/test/CMakeLists.txt, tree/ntuple/v7/test/CustomStruct.hxx, tree/ntuple/v7/test/CustomStructLinkDef.h, tree/ntuple/v7/test/ntuple_types.cxx, tree/ntuple/v7/test/rfield_variant.cxx
=> [ntuple] fixes and more testing for std::variant

interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h, interpreter/cling/test/Prompt/ValuePrinter/Regression.C
Fix hard error when checking if non-[common_range](https://en.cppreference.com/w/cpp/ranges/common_range) is printable. I.e., [std::ranges::enumerate_view](https://en.cppreference.com/w/cpp/ranges/enumerate_view).
Although root does not support C++20 currently, a range that returns different type for `begin()` and `end()` is still legal in other C++ versions.
Fixes https://github.com/root-project/root/issues/14966
=> Fix hard error when checking if non-common_range is printable

tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/test/ntuple_test.hxx
- Removes some dead or redundant code from RMiniFile.cxx (see commit comment for more details)
- adds a utility to FileRaii to preserve the file after running. Useful to quickly debug a test file locally without having to recompile ntuple_test.hxx or doing some weird tricks.
=> [ntuple] RMiniFile cleanups

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RField.hxx, tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx, tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx, tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx, tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx, tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/src/RNTupleParallelWriter.cxx, tree/ntuple/v7/src/RNTupleSerialize.cxx, tree/ntuple/v7/src/RPageSinkBuf.cxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/Unsplit.hxx, tree/ntuple/v7/test/UnsplitLinkDef.h, tree/ntuple/v7/test/ntuple_endian.cxx, tree/ntuple/v7/test/ntuple_serialize.cxx, tree/ntuple/v7/test/ntuple_storage.cxx, tree/ntuple/v7/test/ntuple_test.hxx, tree/ntuple/v7/test/rfield_unsplit.cxx
Follow-up of #14728
Stores the streamer info records seen during serialization of unsplit fields in the extra type information of the extension header. To this end, proper serialization and deserialization of the extra type information frame in the header / extension header is implemented.
This will be accompanied by a roottest PR (TODO)
=> [ntuple] store streamer info of unsplit fields

CMakeLists.txt
Disallows linking with mold, which doesn't work. Even when building is possible by changing some CMake, the build seems to be broken. See  https://github.com/root-project/root/issues/15473.
=> [CMake] Do not allow linking with mold

roofit/roofit/src/RooBernstein.cxx
Setting the size of the transient buffer only in the constructor was a mistake, because it's never called when the RooBernstein is read back from a file.
To be safe, the buffer size should be checked everytime that it's used.
Closes #15690.
=> [RF] Fix segfault with RooBernstein instances read back from files

hist/hist/inc/TProfile2D.h
Don't use a default w=1.0 in the Fill functions, but instead declare inlined no-weight overloads to correctly override TH2 methods.
Note that the overrides are actually quite questionable, because they don't respect the actual TH2 interface, where the third parameter is the weight "w" and not an additional coordinate "z". However, that's how the TProfile2D interface was defined a long time ago, so these overrides are preserved for backwards compatibility. The better design would have been to give the function a different name, or always require an explicit `w` parameter such that the signatures are always different.
Closes #15688.
=> [hist] Don't define default `w=1.0` parameter in `TProfile2D::Fill()`

roofit/roofitcore/src/RooRealSumPdf.cxx
This little bug was already introduced a few years ago in 1ecd30e, and became apparent now that the vectorized evaluation is the default.
The logic should be to clip all values to be >= 0.
Closes #15694.
=> [RF] Fix vectorized evaluation for RooRealSumpdf with `_doFloor`

tree/ntuple/v7/doc/specifications.md
Explicitly specify that integers in the RNTuple anchor are encoded in big-endian.
=> [skip-ci][ntuple] update RNTuple anchor doc

tree/ntupleutil/v7/src/RNTupleInspector.cxx
Add the physical column ID to the error message shown when a different compression setting than expected is encountered. This should help in locating potential bugs/mistakes.
=> [ntuple] Improve inspector error for compression setting mismatch

tutorials/dataframe/df106_HiggsToFourLeptons.C
Explicitly declares the signatures of types that are used in jitted expressions so that the tutorial runs properly even when compiled AOT.
Partially fixes https://github.com/root-project/root/issues/15638
=> [RDF] Make df106_HiggsToFourLeptons.C run properly when compiled

io/io/src/TKey.cxx
Fixes https://github.com/root-project/root/issues/7236
This bug has been there since >24y.
=> [io] fix memory leak in TKey constructor

hist/hist/src/TGraph.cxx
Warns user when resulting TGraph is empty, ie when no points were found in the file, most likely due to the format argument not matching the input file.
=> [graph] warn user when input format mismatch / no points found in file

graf3d/eve7/inc/ROOT/REveElement.hxx, graf3d/eve7/src/REveElement.cxx, tutorials/eve7/error_ellipse.C
This PR:
Removes CINT from function name
Minor improvement in error ellipsoid example
=> [reve] Rename function ExportToCINT to ExportToInterpreter (remake of #15705)

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RNTupleMerger.cxx, tree/ntuple/v7/test/rfield_unsplit.cxx
Unsplit fields update the extra type info block in the RNTuple meta-data, which needs to be explicitly merged. Also, the unsplit field revealed a lifetime issue with the output model, which is now fixed.
=> [ntuple] fix merging of unsplit fields

roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
When `std::copy`ing into a vector, it needs to have the right size before. Doing only `std::reserve` is not enough.
Fixes #15730.
=> [RF] Set size of offsets vector in LikelihoodJob correctly

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx, tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
Currently, the default compression setting for a column range is `0`, which is an actual, valid compression setting (i.e., no compression has been applied). We should distinguish between "no compression has been applied" and "we don't know the compression" (for example in the case of columns created through late model extension, where some ranges may not come from a physical storage location). This PR partly addresses #15661.
=> [ntuple] Add `kUnknownCompressionSettings`

bindings/pyroot/pythonizations/python/ROOT/JsMVA/JsMVAMagic.py
Fix an import error in JsMVA:
```
$ ipython
Python 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.23.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from ROOT.JsMVA import JsMVAMagic
In [2]: %jsmva on
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 get_ipython().run_line_magic('jsmva', 'on')
File /usr/lib/python3.12/site-packages/IPython/core/interactiveshell.py:2480, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
2478     kwargs['local_ns'] = self.get_local_scope(stack_depth)
2479 with self.builtin_trap:
-> 2480 …
```
=> Fix one more broken import in JsMVA

gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/core.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist2d/TH1Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Handle Y-axis zooming from stack histogram
2. Ignore drawing of empty stack
3. Properly update `kIsZooming` bit on server side
4. Adjust JSROOT code 
Fully resolves #14051
=> [webcanvas] properly handle THStack zooming

core/base/inc/TStyle.h, core/base/src/TStyle.cxx, graf2d/graf/src/TLegend.cxx
=> Add SetLegendFillStyle

tutorials/dataframe/df106_HiggsToFourLeptons.C, tutorials/dataframe/df106_HiggsToFourLeptons.py
Main problem - stack was drawn twice and only while histograms in original stack were destroyed 
producing canvas had nice look. 
Changes:
* do not draw stack twice.
* clone histograms once and use in stack and in legend
* do not use sames - make no sense when calling `SetStats(false)` at the same time
* simplify text drawing
* make C++ and Python macro closer to each other
=> Improve `df106` tutorials

hist/hist/inc/TF1.h
Returns true if `fSave` buffer not empty
May help to understand if `TF1::GetSave()` method can be used
=> Introduce TF1::HasSave method

tree/ntuple/v7/src/RNTupleDescriptor.cxx, tree/ntuple/v7/test/ntuple_modelext.cxx
For deferred columns (i.e. columns created during late model extension) for subfields that have been created after one or more clusters have already been written, their (synthetic) column ranges were not properly initialized upon read back. This resulted in incorrect metadata and problems reading back the data in the subfields only (so not the complete field they are part of). This PR partly addresses #15661.
=> [ntuple] Fix column range construction for extended fields

tree/ntupleutil/v7/src/RNTupleInspector.cxx, tree/ntupleutil/v7/test/ntuple_inspector.cxx
Upon creating an RNTupleInspector, we check whether the compression settings are consistent across all columns. Some column ranges may have been constructed upon read (e.g. in the context of late model extension) and therefore have no compression settings to begin with. These column ranges should not cause the RNTupleInspector to throw. This PR partially addresses #15661.
=> [ntuple] Ignore unkown compression settings in the `RNTupleInspector` construction

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
=> [RF] Use `std::min` and `std::max` in MathFuncs

.github/workflows/root-ci-config/build_utils.py, .github/workflows/root-ci.yml, interpreter/cling/lib/Interpreter/CIFactory.cpp, math/mathcore/test/stress/testGenVector.cxx, test/stressMathCore.cxx
Special builds are those builds that test particular configurations, which are not meant to be considered for binaries of releases.
Besides the new category, two special builds are introduced:
- The "march=native" build, that fixes #12291
- The "runtime modules off" build
=> [ci] Introduce the category of special builds

tree/ntuple/v7/test/CMakeLists.txt
Fixes build of ntuple tests which sometimes break due to RIO not being regenerated properly
=> [ntuple] add RIO Dependencies for RXTuple

cmake/modules/RootCPack.cmake
to avoid malformed names in the string passed to CPack for the creation of the binary archive.
=> [ci] Correctly parse Debian version

.github/workflows/root-ci-config/build_utils.py
when running GitHub actions. This is done in order to monitor how much time each individual step of the workflows is taking.
=> [ci] Display time per group

tree/ntuple/v7/doc/specifications.md, tree/ntuple/v7/inc/ROOT/RMiniFile.hxx, tree/ntuple/v7/inc/ROOT/RNTuple.hxx, tree/ntuple/v7/src/RMiniFile.cxx, tree/ntuple/v7/src/RNTuple.cxx, tree/ntuple/v7/test/ntuple_minifile.cxx
adds a field in the RNTuple anchor that specifies the max key size, i.e. the biggest payload that can be stored in a TKey.
This will allow the RNTuple readers and writers to handle payloads bigger than that limit (currently 1 GiB) by splitting it into multiple TKeys.
Bumped RNTuple class version to 6.
**NOTE**: this change doesn't break forward compatibility because old readers weren't able to read payloads larger than `maxKeySize` anyway.
=> [ntuple] add fMaxKeySize field to RNTuple

tree/ntuple/v7/test/CustomStruct.hxx
Fix the following error with Visual Studio 2019:
```
error C2440: 'initializing': cannot convert from 'int' to 'std::byte'
```
=> [windows] Fix compilation error with VS 2019

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py, bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
For compatibility with Python 3.13
See: https://docs.python.org/3.13/whatsnew/3.13.html
From the above page:
* Classes have a new __firstlineno__ attribute, populated by the compiler, with the line number of the first line of the class definition. (Contributed by Serhiy Storchaka in gh-118465.)
* Classes have a new __static_attributes__ attribute, populated by the compiler, with a tuple of names of attributes of this class which are accessed through self.X from any function in its body. (Contributed by Irit Katriel in gh-115775.)
Without adding the new attributes to the blacklist there are errors:
AttributeError: 'int' object attribute 'doc' is read-only from the __firstlineno__ attribute.
AttributeError: 'tuple' object attribute 'doc' is read-only from the __static_attributes__ …
=> [pyroot] Add __firstlineno__ and __static_attributes__ to blacklist

hist/hist/src/THStack.cxx
As said in this old forum post https://root-forum.cern.ch/t/thstack-th2-with-negative-values/16161/5, stacking a histogram with negative bin content does not make sense. This issue is not relevant https://github.com/root-project/root/issues/15740. But it is goo to make it clear in the documentation and to prevent adding such histograms in a stack. That's what this PR is doing.
=> Update THStack documentation

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py, bindings/pyroot/pythonizations/src/PyROOTModule.cxx, bindings/pyroot/pythonizations/src/PyROOTPythonize.h, bindings/pyroot/pythonizations/src/TTreePyz.cxx
The pythonization of `TTree::SetBranchAddress` was implemented in C++, hacking into CPyCppy by using implementation details like data member caches (this call: `((CPPInstance *)address)GetDatamemberCache()`). Not too surprising that it apparently breaks with the upcoming Python 3.13.
It's better to implement the pythonizations in Python and also manage the lifetime of the necessary data in Python. This is done in this commit.
The pythonization is extensively tested in `ttree_setbranchaddress.py`.
Closes #15799.
=> [PyROOT] Implement TTree SetBranchAddress pythonization in Python

tree/ntuple/v7/doc/architecture.md, tree/ntuple/v7/src/RNTupleDescriptor.cxx
This PR aims to add an overview of what happens during reading and writing with regard to late model extension. Most of this is already documented in the code, but adding it to the `architecture.md` should prevent the need of having to jump back and forth between different parts of the source code.
=> [skip-ci][ntuple] Add architecture documentation for late model extension

math/mathcore/src/Integrator.cxx
plugin, otherwise heavy checks in the PluginHandler take place that perform interpreter lookups.
Fixes #15579
=> [math] Use correct type when invoking the GSLIntegrator

.github/workflows/root-ci.yml
since the hosts on which we run the containers do not all provide the same instruction sets.
=> [ci] Remove the march-native special build

gui/webgui6/src/TWebCanvas.cxx
Workaround for multi-threaded environment
Ensure main thread id picked when canvas implementation is created otherwise it may be assigned in other thread and screw-up `gPad` access. Workaround may not work if main thread id was wrongly initialized before
This resolves issue https://github.com/root-project/root/issues/15498
=> [webgui] ensure main thread id set when TWebCanvas is created

graf2d/gpad/src/TPad.cxx, gui/webgui6/src/TWebCanvas.cxx, js/build/jsroot.js, js/changes.md, js/modules/base/ObjectPainter.mjs, js/modules/core.mjs, js/modules/geom/geobase.mjs, js/modules/gpad/RFramePainter.mjs, js/modules/gpad/RPadPainter.mjs, js/modules/gpad/TAxisPainter.mjs, js/modules/gpad/TCanvasPainter.mjs, js/modules/gpad/TFramePainter.mjs, js/modules/gpad/TPadPainter.mjs, js/modules/gui/menu.mjs, js/modules/hist/THStackPainter.mjs, js/modules/hist/TPavePainter.mjs, js/modules/hist2d/TH2Painter.mjs, js/modules/hist2d/THistPainter.mjs
1. Correctly detect and use saved buffer in `TF1`. In some circumstances valid buffer was overwritten by 0 - and making webcanvas not displaying `TF1`
2. Do not support `TPad::WaitPrimitive()` with web canvas. Creation of primitives not yet implemented, but original method requires `gROOT->SetSelectedPad()` and this screw-up `obj->DrawClone()`. Therefore do not set selected pad for web canvas.
3. Update JSROOT with several fixes - including #15791
=> [webgui] better TF1 handling, no WaitPrimitive

tree/dataframe/test/dataframe_interface.cxx
The test previously build an expression with 4096 occurrences of the 'x' variable. This was causing a segfault with the address sanitizer that is independent of RDataFrame and tracked at
https://github.com/root-project/root/issues/15818.
Shorten the test expression to 100 occurences of 'x' which still represents a realistically long one-line expression and better decouples the clang-related asan issue from the rest of the RDataFrame testing infrastructure.
=> [df] Shorten jitted expression in test

core/base/inc/TVirtualPad.h, core/base/src/TObject.cxx, graf2d/gpad/inc/TPad.h, graf2d/gpad/src/TCanvas.cxx, graf2d/gpad/src/TPad.cxx, graf2d/gpad/src/TRatioPlot.cxx, gui/browsable/src/TLeafDraw6Provider.cxx, gui/browsable/src/TObjectDraw6Provider.cxx, gui/webgui6/src/TWebCanvas.cxx, tutorials/webgui/qtweb/ExampleWidget.cpp
Let add and remove primitives from the pad without set of `gPad` pointer.
Automatically set modified flag when primitives are changing.
Use methods in `TObject::Draw()`, `TObject::DrawClone()`, `TObject::Pop()` methods
Also in webgui and `graf2d/gpad` classes
=> [gpad] Introduce `TPad::Add()`, `TPad::AddFirst()` and `TPad::Remove()` methods

core/base/inc/Bswapcpy.h, io/io/src/TBufferFile.cxx
Add back the immediate return whne n = 0 in WriteFastArray.
This PR fixes #15738
=> [io] WriteFastArray: return early if n == 0, to prevent crash in bswapcpy

tmva/pymva/inc/TMVA/RModelParser_Keras.h, tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/TestRModelParserKeras.C, tmva/sofie/inc/TMVA/RFunction.hxx, tmva/sofie/src/RModel.cxx, tmva/tmva/inc/TMVA/RSofieReader.hxx
This Pull request fixes the use case when the batch size is specified in RModel::Generate and the input model does not have a given batch size, but a parametric one
=> [tmva][sofie] Fix when specifying input batch size in Model

core/base/src/TObject.cxx, graf2d/gpad/src/TPad.cxx
Set such bit in new `TPad::Add()` and `TPad::AddFirst()` methods. 
Bit was already set in `TObject::AppendPad()`,
now it also will be set for other use cases where `TPad::Add()` is used
=> [gpad] Always set `kMustCleanup` bit when object add to pad

gui/webgui6/src/TWebCanvas.cxx
Workaround for multi-threaded environment
Ensure main thread id picked when canvas implementation is created otherwise it may be assigned in other thread and screw-up gPad access. Workaround may not work if main thread id was wrongly initialized before
This resolves issue https://github.com/root-project/root/issues/15498
Backport of #15825
=> [webgui] ensure main thread id set when TWebCanvas is created [6.32]

core/zip/inc/Compression.h, test/stress.cxx, tree/dataframe/inc/ROOT/RSnapshotOptions.hxx, tree/dataframe/test/CMakeLists.txt, tree/dataframe/test/dataframe_cache.cxx, tree/dataframe/test/dataframe_simple.cxx, tree/dataframe/test/dataframe_snapshot.cxx
is the first half of #15714. It deprecates `ECompressionAlgorithm` in favor of `RCompressionSetting::EAlgorithm` and fixes the code to use the new enum.
This PR should be much safer and less problematic to merge than #15714, so we can start with this and later discuss about changing the `RCompressionSetting` enums to enum classes.
Depends on #15820
=> Deprecate ECompressionAlgorithm

tree/ntuple/v7/src/RPageStorageFile.cxx
Saves one round trip when opening an RNTuple. Also adds reading the header and the footer to the accounting.
As a follow-up, we should store the location of the first page list in the anchor. That would give us the option to load that page list in the same vector read, too.
=> [ntuple] read header and footer in vector read

math/vecops/inc/ROOT/RVec.hxx, math/vecops/test/vecops_rvec.cxx
Implements a numerically stable algorithm for Invariant Masses computation in single precision for RVec.
This PR fixes [#9646](https://github.com/root-project/root/issues/9646)
=> [RVec] Numerically stable invariant masses computations

core/clib/src/mmapsup.c, roofit/xroofit/src/xRooNode.cxx, tree/dataframe/src/RDFDisplay.cxx, tree/dataframe/src/RDFHelpers.cxx
Fixes compiler warnings from format strings (size_t not using %z).
=> Correct format - warnings seen on 32 bit architectures

hist/hist/test/test_tprofile2poly.cxx
```
167/1341 Test  #120: gtest-hist-hist-test-testTProfile2Poly ....................................***Failed   11.00 sec
Running main() from /builddir/build/BUILD/googletest-1.14.0/googletest/src/gtest_main.cc
Note: Google Test filter = -RCsvDS.Remote:RNTuple.OpenHTTP:RRawFile.Remote:RSqliteDS.Davix:TChainParsing.DoubleSlash:TChainParsing.RemoteGlob:TFile.ReadWithoutGlobalRegistrationNet:TFile.ReadWithoutGlobalRegistrationWeb
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from TProfile2Poly
[ RUN      ] TProfile2Poly.GlobalCompare
/builddir/build/BUILD/root-6.32.00-build/root-6.32.00/hist/hist/test/test_tprofile2poly.cxx:30: Failure
Expected equality of these values:
tp2d->GetMeanError(c)
Which is: 0.0030918045191081229 …
```
=> Fix test failure on ppc64le and s390x

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h, roofit/hs3/src/JSONFactories_RooFitCore.cxx, roofit/hs3/src/JSONIOUtils.cxx, roofit/hs3/src/JSONIOUtils.h, roofit/hs3/src/RooJSONFactoryWSTool.cxx, roofit/hs3/test/testRooFitHS3.cxx, roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h
Make sure that when transforming workspaces with these classes, roundtripping from RooFit -> JSON -> RooFit -> JSON leaves both the RooFit workspace and the JSON unchanged.
Closes #15756.
=> [RF] Clean HS3 roundtripping of RooExponential and RooLogNormal

roofit/roofitcore/src/RooFit/Evaluator.cxx
It's not necessary because the data token is not set for `RooRealVar`s to begin with:
https://github.com/root-project/root/blob/master/roofit/roofitcore/src/RooFit/Evaluator.cxx#L185
And by not doing this unnecessary resetting, we avoid potential crashes in case the `RooRealVar`s live not as long as the evaluator.
=> [RF] Don't call `resetDataToken()` on RooRealVars in Evaluator d'tor

roofit/roofitcore/test/testRooFuncWrapper.cxx
Since this works now with Clad 1.5.
=> [RF] Enable RooCrystalBall test for AD

tmva/pymva/inc/TMVA/RModelParser_Keras.h, tmva/pymva/src/RModelParser_Keras.cxx, tmva/pymva/test/TestRModelParserKeras.C, tmva/sofie/inc/TMVA/RFunction.hxx, tmva/sofie/src/RModel.cxx, tmva/tmva/inc/TMVA/RSofieReader.hxx
This Pull request is a back port of #15819
=> Backport SOFIE fixes in 6.32

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/build_utils.py, .github/workflows/root-ci.yml
The preprocessor defines enabled by the `march=native` flag are made part of the string of options to be hashed to create the artifact tarball names, therewith avoiding incompatible binaries. Moreover, the special builds preserve their overrides also for nightly builds.
=> [ci] Add back the march=native build

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx, tree/ntuple/v7/src/RPageStorage.cxx, tree/ntuple/v7/test/ntuple_extended.cxx
So far, non-vectorized committing of pages misuses the compressor buffer as a temporary storage. The compressor buffer is limited to `kMAXZIPBUF` (16MB) and a page can be larger.
=> [ntuple] fix unbuffered compression of large pages

hist/hist/inc/TGraphTime.h, hist/hist/src/TGraphTime.cxx, tutorials/graphs/gtime.C, tutorials/graphs/gtime2.C
1. Use new `TPad::Add()` and `TPad::Remove()` methods to manipulate primitives
2. Do not implement `TGraphTime::Paint()` method. It is illegal to add this object to list of primitives and painting is not allowed. 
3. Provide protected `TGraphTime::DrawStep()` method which used both in drawing and creation animated gif 
4. Remove unnecessary `gSystem->Sleep` and `gPad->Update` when creating animated gif, check if `gPad` is there, only plain ROOT canvas can be used here
5. Implement `TGraphTime::Animate()` to let run animation without blocking of main loop.
6. Adjust tutorials macros
=> Improving `TGraphTime` class

CMakeLists.txt, cmake/modules/RootConfiguration.cmake
The compiler invokations run by ACLiC were not updated in case of a build with address sanitizer options enabled. This resulted in spurious warnings of the sort:
```
$: root -q -l -b test.C+
Processing test.C+...
Info in <TUnixSystem::ACLiC>: creating shared library /tmp/./test_C.so
/usr/bin/ld: /lib64/libasan.so.8: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib64/libasan.so.8: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib64/libasan.so.8: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib64/libasan.so.8: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /lib64/libasan.so.8: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: …
```
=> [cmake] Add asan options to ACLiC

gui/browsable/src/RFieldProvider.hxx, tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx, tree/ntuple/v7/src/RField.cxx, tree/ntuple/v7/src/RFieldVisitor.cxx
This change makes the visitor consistent with the other integer visitors, which all use a fixed-width representation.
=> [ntuple] Change `VisitIntField` to `VisitInt32Field`

core/metacling/src/CMakeLists.txt
Fixes https://github.com/root-project/root/issues/15336
Fix the following compilation errors with Visual Studio v17.10 on x86
```
libCling.exp : error LNK2001: unresolved external symbol "char const * __cdecl __std_find_trivial<char const ,char>(char const *,char const *,char)" (??$__std_find_trivial@$$CBDD@@YAPBDPBD0D@Z)
libCling.exp : error LNK2001: unresolved external symbol "char * __cdecl __std_find_trivial<char,char>(char *,char *,char)" (??$__std_find_trivial@DD@@YAPADPAD0D@Z)
libCling.exp : error LNK2001: unresolved external symbol "int * __cdecl __std_find_trivial<int,int>(int *,int *,int)" (??$__std_find_trivial@HH@@YAPAHPAH0H@Z)
libCling.exp : error LNK2001: unresolved external symbol "unsigned int * __cdecl __std_find_trivial<unsigned int,int>(unsigned int *,unsigned int …
```
=> [came][win32] Fix error with VS v17.10

core/metacling/src/CMakeLists.txt
Fixes https://github.com/root-project/root/issues/15336
Fix the following compilation errors with Visual Studio v17.10 on x86
```
libCling.exp : error LNK2001: unresolved external symbol "char const * __cdecl __std_find_trivial<char const ,char>(char const *,char const *,char)" (??$__std_find_trivial@$$CBDD@@YAPBDPBD0D@Z) [C:\
root-dev\build\x86\release\core\metacling\src\Cling.vcxproj]
libCling.exp : error LNK2001: unresolved external symbol "char * __cdecl __std_find_trivial<char,char>(char *,char *,char)" (??$__std_find_trivial@DD@@YAPADPAD0D@Z) [C:\root-dev\build\x86\release\co
re\metacling\src\Cling.vcxproj]
libCling.exp : error LNK2001: unresolved external symbol "int * __cdecl __std_find_trivial<int,int>(int *,int *,int)" (??$__std_find_trivial@HH@@YAPAHPAH0H@Z) …
```
=> [v6-32][win32] Fix error with VS v17.10

roofit/histfactory/src/ParamHistFunc.cxx, roofit/roofitcore/inc/RooDataHist.h
ParamHistFunc currently does not adhere to the convention that if it is independent of the variable passed to binBoundaries method that it should return nullptr. This is fixed, along with more correct obtaining of the bin boundaries, from the RooDataHist itself.
=> [RF] Improve binBoundaries method of ParamHistFunc

gui/webdisplay/inc/ROOT/RWebWindow.hxx, gui/webdisplay/src/RWebWindow.cxx, gui/webdisplay/src/RWebWindowsManager.cxx
For security reasons this option is off by default. 
Only when desired `win.SetUseCurrentDir(true)` should be invoked. 
It happens automatically when "localapp." namespace configured as main ui5 panel for the window
Required for `tutorials/webgui/panel` example.
Will be required for local fonts or special apps in eve7.
=> [webgui] let enable usage of currentdir

interpreter/llvm/src/lib/ExecutionEngine/Orc/LLJIT.cpp
Constructors with the same priority should keep their relative order that was specified. This is important for `clang-repl` with many `const` variables after commit https://github.com/llvm/llvm-project/commit/05137ecfca0bd2f7fa6cd30c771dfacbb8188785 ("[clang-repl] Emit const variables only once").
---
Fixes #15511
(version of commit a60f3538220e298f14c0ea5824d2fda91b71f39e for LLVM 13 in `v6-28-00-patches`, backport of https://github.com/root-project/root/pull/15854)
=> [ORC] Preserve order of constructors with same priority [v6.28]

.github/workflows/root-ci-config/build_root.py, .github/workflows/root-ci-config/buildconfig/alma9-clang.txt, .github/workflows/root-ci.yml
To correctly manage build artifacts, make the compiler name part of the string to be hashed.
=> [ci] Add alma9 clang build

tree/ntuple/v7/src/RField.cxx
After b5d751c069df2725dbc0d96bb1a6a677addc3895, RField.cxx on clang yields the warning:
```
/home/jp/root/tree/ntuple/v7/src/RField.cxx:2504:58: error: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Werror,-Wpotentially-evaluated-expression]
errMsg += "Item field type: " + std::string(typeid(*fSubFields[0]).name());
```
Fixing the warning is just a matter of splitting the ptr dereference from the `typeid` expression.
=> [ntuple] Fix clang compile warning due to typeid in RField
