interpreter/cling/lib/Interpreter/IncrementalParser.cpp

Fixes commit 68769cd980 ("[cling] Move parts of Parse to another function").

[cling] Fix build with assertions

---

core/clingutils/test/TClingUtilsTests.cxx

[TCling] Separate test for GetCppName

---

core/meta/src/TEnum.cxx

BP of https://github.com/root-project/root/pull/15408

[BP][v6.32] TEnum::GetEnum normalize name before search.

---

interpreter/cling/include/cling/Utils/Platform.h

Function was removed here https://github.com/root-project/cling/commit/c23abbc88b6ee61b966291c785794743b1bd5c62
Fixes https://github.com/root-project/cling/issues/456

[cling] remove remnant declaration of removed function

---

bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx

Closes #15375 by backporting a commit from upstream: https://github.com/wlav/CPyCppyy/commit/02072bbd818501364b37c133364e02976af4cc10
Needs to be backported to the 6.32 branch.

[PyROOT] Report the exception type (instead of TypeError) is multiple overloads raise C++ exceptions of the same type

---

tutorials/CMakeLists.txt

Import some of the changes applied in 6.28 from commit https://github.com/root-project/root/commit/c2cacce4ca9e2e8368932f9678e8979fecd065d3

[tmva] Fix dependency of tutorials

---

tree/ntuple/v7/src/RMiniFile.cxx

properly formats RMiniFile.cxx with clang-format

[ntuple] run clang-format on RMiniFile.cxx

---

gui/cefdisplay/src/gui_handler.cxx
gui/webdisplay/src/RWebWindow.cxx
gui/webgui6/src/TWebCanvas.cxx
net/http/src/THttpServer.cxx

Backport of https://github.com/root-project/root/pull/15521

[webgui] Fix CEF handler, reduce debug output[6.32]

---

.github/workflows/root-626.yml
.github/workflows/root-628.yml
.github/workflows/root-630.yml
.github/workflows/root-632.yml

Schedule nightly builds from 1 am onwards, spaced by 15 minutes.

[skip-ci][ci] New schedule for nightly builds

---

interpreter/CMakeLists.txt

Alternative to https://github.com/root-project/root/pull/15483

[interpreter] Disable warnings when compiling LLVM / Clang

---

core/meta/src/TMethodCall.cxx

[skip ci][doc] Clarify current limitation of TMethodCall

---

core/meta/src/TMethodCall.cxx

BP of https://github.com/root-project/root/pull/15545

[skip ci][BP][6.32][doc] Clarify current limitation of TMethodCall

---

main/python/cmdLineUtils.py
main/python/rootls.py

Adds recursivity to rootls
I am not sure what's the best way to do the same for rootprint, so marking this as draft
Fixes https://github.com/root-project/root/issues/13659

[cmd] add recursive version of rootls

---

main/python/cmdLineUtils.py
main/python/rootls.py

BP of https://github.com/root-project/root/issues/13659

[BP][6.32] [cmd] add recursive version of rootls

---

bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py
bindings/pyroot/pythonizations/test/rtensor.py
tutorials/CMakeLists.txt

Fix some issues with test dound in 6.30.00

Test glitches

---

cmake/modules/SearchInstalledSoftware.cmake
graf2d/asimage/src/libAfterImage/configure
graf2d/asimage/src/libAfterImage/export.c
graf2d/asimage/src/libAfterImage/import.c
graf2d/asimage/src/libAfterImage/ungif.c

Since the possibillity to use an external libAfterImage was removed, the built-in version needs some fixes.
See commit messages for details.

Afterimage fixes

---

etc/runfirefox.sh
gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowWSHandler.hxx

[webgui] fix handling of local displays like qt5 or cef [6.32]

---

core/metacling/src/CMakeLists.txt
hist/hist/src/TFormula.cxx
interpreter/cling/tools/plugins/clad/CMakeLists.txt

This new release includes several fixes helping to scale the RooFit AD backend.
See more at: https://github.com/vgvassilev/clad/releases/tag/v1.5

[clad] Bump Clad to v1.5

---

hist/hist/src/TFormula.cxx

[hist] Comment unused parameter in TFormula

---

.github/workflows/root-ci-config/buildconfig/ubuntu2404.txt
.github/workflows/root-ci.yml
bindings/experimental/distrdf/python/DistRDF/HeadNode.py
bindings/experimental/distrdf/python/DistRDF/Ranges.py
bindings/experimental/distrdf/test/test_headnode.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/pyroot/pythonizations/src/TMemoryRegulator.cxx
bindings/pyroot/pythonizations/src/TMemoryRegulator.h
tree/tree/inc/ROOT/InternalTreeUtils.hxx
tree/tree/src/InternalTreeUtils.cxx

~~Situation should be better but there may be still some leftover issues.~~
All issues should now be fixed, the PR is ready for review!

Fix PyROOT for Ubuntu 24.04

---

README/ReleaseNotes/v632/index.md
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofit/test/testFitPerf.cxx
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooDerivative.cxx
tutorials/roofit/rf514_RooCustomizer.C
tutorials/roofit/rf514_RooCustomizer.py
tutorials/roofit/rf611_weightedfits.C

Backport of #14751 to the 6.32 release branch. Thanks again, @langenbruch!

[v632][RF] Determine asymptotically correct uncertainties for extended unbinned maximum likelihood fits

---

.github/workflows/root-ci-config/buildconfig/ubuntu2404.txt
.github/workflows/root-ci.yml
bindings/experimental/distrdf/python/DistRDF/HeadNode.py
bindings/experimental/distrdf/python/DistRDF/Ranges.py
bindings/experimental/distrdf/test/test_headnode.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/pyroot/pythonizations/src/TMemoryRegulator.cxx
bindings/pyroot/pythonizations/src/TMemoryRegulator.h
tree/tree/inc/ROOT/InternalTreeUtils.hxx
tree/tree/src/InternalTreeUtils.cxx

[6.32] Backport of #15415

---

README/ReleaseNotes/v632/index.md

Release notes

---

README/ReleaseNotes/v632/index.md

[v632][skip-ci] Update release notes

---

io/io/src/TFile.cxx

io: Avoid infinite recursion in TFile::Open

---

tree/tree/src/TBranch.cxx

Related to https://github.com/root-project/root/issues/15621

[6.30] Backport of #15620

---

tree/tree/src/TBranch.cxx

Related to https://github.com/root-project/root/issues/15621

[6.28] Backport of #15620

---

bindings/pyroot/pythonizations/python/ROOT/JsMVA/Factory.py
bindings/pyroot/pythonizations/python/ROOT/JsMVA/JPyInterface.py
bindings/pyroot/pythonizations/python/ROOT/JsMVA/OutputTransformer.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/_crossvalidation.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx
bindings/pyroot/pythonizations/src/IOHandler.cxx
bindings/pyroot/pythonizations/src/PyROOTModule.cxx
bindings/pyroot/pythonizations/src/PyROOTPythonize.h
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx
bindings/pyroot/pythonizations/src/RPyROOTApplication.h
bindings/pyroot/pythonizations/src/TClassPyz.cxx
bindings/pyroot/pythonizations/src/TTreePyz.cxx
bindings/pyroot/pythonizations/test/roofit/rooabscollection.py
bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
cmake/modules/FindCUDNN.cmake
requirements.txt

Needs to go into the release.
* https://github.com/root-project/root/pull/15605
* https://github.com/root-project/root/pull/15602
* https://github.com/root-project/root/pull/15608

[v632] Backport of yesterdays fixes

---

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu.h
tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h
tmva/tmva/inc/TMVA/DNN/Architectures/TCudnn.h
tmva/tmva/inc/TMVA/DNN/CNN/ContextHandles.h
tmva/tmva/inc/TMVA/DNN/RNN/GRULayer.h
tmva/tmva/inc/TMVA/DNN/RNN/LSTMLayer.h
tmva/tmva/inc/TMVA/DNN/RNN/RNNLayer.h
tmva/tmva/src/DNN/Architectures/Cpu/RecurrentPropagation.hxx
tmva/tmva/src/DNN/Architectures/Cuda/CudaTensor.cu
tmva/tmva/src/DNN/Architectures/Cudnn/RecurrentPropagation.cu

This PR migrates the TMVA Deep Learning classes (RNN) for new cud version 9

[tmva] Fix tmva DL packages for new cudnn v9

---

tmva/tmva/src/DNN/Architectures/Cudnn/RecurrentPropagation.cu

This Pull request removes a printout left from previous commit

[tmva] Fix tmva for new cudnn v9

---

io/io/src/TFile.cxx

[v628] io: Avoid infinite recursion in TFile::Open

---

tmva/tmva/inc/TMVA/DNN/Architectures/Cpu.h
tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h
tmva/tmva/inc/TMVA/DNN/Architectures/TCudnn.h
tmva/tmva/inc/TMVA/DNN/CNN/ContextHandles.h
tmva/tmva/inc/TMVA/DNN/RNN/GRULayer.h
tmva/tmva/inc/TMVA/DNN/RNN/LSTMLayer.h
tmva/tmva/inc/TMVA/DNN/RNN/RNNLayer.h
tmva/tmva/src/DNN/Architectures/Cpu/RecurrentPropagation.hxx
tmva/tmva/src/DNN/Architectures/Cuda/CudaTensor.cu
tmva/tmva/src/DNN/Architectures/Cudnn/RecurrentPropagation.cu

BP of https://github.com/root-project/root/pull/15601 and https://github.com/root-project/root/pull/15634 , de facto the second PR minimally amends the first one.

[BP][632] Fix tmva DL packages for new cudnn v9

---

tree/ntuple/v7/src/RMiniFile.cxx

[ntuple] add ClassDefInline to RKeyBlob

---

README/ReleaseNotes/v632/index.md

[skip-ci][RN] Update 632 version with closed items

---

gui/gui/src/TGFSContainer.cxx

Fixes https://github.com/root-project/root/issues/15643

[gui] Fix issue #15643

---

tutorials/graphs/timeonaxis.C
tutorials/graphs/timeonaxis2.C
tutorials/graphs/timeonaxis3.C
tutorials/hist/candleplot.C
tutorials/hist/candleplotstack.C

improve labeling in candle plot examples.

[skip-ci] improve labelling in candle plot examples.

---

tutorials/CMakeLists.txt

BP of https://github.com/root-project/root/pull/15679

[BP-v632] Fix problem with timeonaxis tutorials

---

js/build/jsroot.js
js/changes.md
js/modules/core.mjs
js/modules/geom/bundle.mjs
js/modules/hist/TF1Painter.mjs
js/modules/hist/TF2Painter.mjs
js/modules/hist/TF3Painter.mjs
js/modules/hist2d/TH1Painter.mjs

1. Fix - properly select TF1 range after zooming
2. Fix - TH1 y-range selection

[jsroot] version 7.7.1 [6.32]

---

math/minuit/src/TMinuit.cxx

fixes [ROOT-9673](https://its.cern.ch/jira/browse/ROOT-9673)

[math] [ROOT-9673] Print message only if verbosity level allows

---

CMakeLists.txt
builtins/xrootd/CMakeLists.txt
hist/hist/inc/TProfile2D.h
math/minuit/src/TMinuit.cxx
roofit/roofit/src/RooBernstein.cxx
roofit/roofitcore/src/RooMCStudy.cxx
roofit/roofitcore/src/RooRealSumPdf.cxx

Backports of some recent fixes.

[v632] Backports for 6.32.02 patch release

---

tmva/tmva/inc/TMVA/Config.h
tmva/tmva/inc/TMVA/ExpectedErrorPruneTool.h
tmva/tmva/inc/TMVA/FitterBase.h
tmva/tmva/inc/TMVA/GeneticAlgorithm.h
tmva/tmva/inc/TMVA/GeneticPopulation.h
tmva/tmva/inc/TMVA/KDEKernel.h
tmva/tmva/inc/TMVA/LDA.h
tmva/tmva/inc/TMVA/ModulekNN.h
tmva/tmva/inc/TMVA/OptimizeConfigParameters.h
tmva/tmva/inc/TMVA/QuickMVAProbEstimator.h
tmva/tmva/inc/TMVA/Reader.h
tmva/tmva/inc/TMVA/RuleCut.h
tmva/tmva/inc/TMVA/RuleFit.h
tmva/tmva/inc/TMVA/RuleFitAPI.h
tmva/tmva/inc/TMVA/SimulatedAnnealing.h
tmva/tmva/inc/TMVA/Timer.h
tmva/tmva/inc/TMVA/Tools.h
tmva/tmva/inc/TMVA/Types.h

Fixes [#9792](https://github.com/root-project/root/issues/9792)

[tmva] Make all instances of fLogger transient

---

.github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
.github/workflows/root-ci.yml

BP of https://github.com/root-project/root/pull/15709

[BP 632][ci] Remove ubu2310 build

---

.github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
.github/workflows/root-ci.yml

BP of https://github.com/root-project/root/pull/15709

[BP630][ci] Remove ubu2310 build

---

math/matrix/inc/TMatrixTSym.h
math/matrix/src/TMatrixT.cxx
math/matrix/src/TMatrixTSparse.cxx
math/matrix/src/TMatrixTSym.cxx

Fixes https://github.com/root-project/root/issues/14561
pinging @eoffermann

[skip-ci] amend TMatrixT documentation

---

hist/hist/src/TGraph.cxx
hist/hist/src/TH2Poly.cxx
hist/hist/src/TProfile.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_MapCppName.cxx

Make  sure the saved TGraph is a proper C++ variable.
As suggested here: https://its.cern.ch/jira/browse/ROOT-8277
it works also for the classes inheriting from TGraph

Make sure the saved TGraph is a proper C++ variable

---

tree/ntuple/v7/src/RField.cxx

Follow-up of https://github.com/root-project/root/pull/15482#discussion_r1621338404

[ntuple] minor improvement to ROptionalField

---

io/io/src/TBufferJSON.cxx
io/sql/src/TBufferSQL2.cxx
io/xml/src/TBufferXML.cxx
tree/tree/src/TBufferSQL.cxx

[skip-ci] stray parenthesis in comment

---

tree/ntuple/v7/test/ntuple_types.cxx

Follow-up of https://github.com/root-project/root/pull/15482#discussion_r1621341594

[ntuple] additional testing for std::optional

---

tree/ntuple/v7/src/RClusterPool.cxx

Fixes commit 29118d578f ("Remove unzipping thread from RClusterPool").

[ntuple] Call UnzipCluster on all clusters

---

gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/BasePainter.mjs
js/modules/base/base3d.mjs
js/modules/core.mjs
js/modules/draw.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/geom/bundle.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/display.mjs
js/modules/gui/lil-gui.mjs
js/modules/gui/menu.mjs
js/modules/hist/TF1Painter.mjs
js/modules/hist/TF2Painter.mjs
js/modules/hist/TF3Painter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/io.mjs
js/modules/tree.mjs

Title object always created - even when empty.
But if drawn - it must be hidden to remove TPave decoration
Fix problem with TFrame when  `THStack` and `TMultiGraph` are drawn - frame object is required
Update JSROOT with recent changes in master

[webcanvas] hide empty title

---

gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/BasePainter.mjs
js/modules/core.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist/TPavePainter.mjs

[webcanvas] hide empty title [6.32]

---

tree/dataframe/inc/ROOT/RDF/RAction.hxx
tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/dataframe_compgraph.cxx

Ensure execution order of Define operations

---

cmake/scripts/ROOTConfig.cmake.in

Fixes https://github.com/root-project/root/issues/15727

[cmake] Fix find_library() on Windows

---

gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/core.mjs
js/modules/hist/THStackPainter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/THistPainter.mjs

Backport of https://github.com/root-project/root/pull/15747

[webcanvas] Properly handle THStack zooming [6.32]

---

cmake/scripts/ROOTConfig.cmake.in

Fixes https://github.com/root-project/root/issues/15727

[v6-32][cmake] Fix find_library() on Windows

---

tutorials/dataframe/df106_HiggsToFourLeptons.C
tutorials/dataframe/df106_HiggsToFourLeptons.py

Improve `df106` tutorials [6.32]

---

tutorials/dataframe/df101_h1Analysis.C

First draw cloned histogram and then fit it.
By this canvas, histogram and function can be used after original data destroyed - keeping possibility for interactivity

Improve df101_h1Analysis.C macro

---

.github/workflows/root-ci-config/buildconfig/ubuntu2310.txt
.github/workflows/root-ci.yml

BP of https://github.com/root-project/root/pull/15709

[BP 628][ci] Remove ubu2310 build

---

roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx

When compiling a RooSimultaneous for a given normalization set, we can only prefix the observables after everything related the compiling of the compute graph for the normalization set is done. This is because of a subtlety in conditional RooProdPdfs, which stores the normalization sets for the individual pdfs in RooArgSets that are disconnected from the computation graph, so we have no control over them. An alternative would be to use recursive server re-direction, but this has more performance overhead.
Closes #15751 and fixes the CMS Run 1 Higgs combination with the new NLL evaluation backend.

[RF] Fix conditional RooProdPdfs in RooSimultaneous with new backend

---

tree/ntuple/v7/test/ntuple_storage.cxx

This file will be modified by a future PR so it needs to be formatted.

[skip-ci] clang-format ntuple_storage.cxx

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/ntuple_modelext.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

Backport of #15699, #15698 and #15759.

[v632][ntuple] Fix deferred column range construction 

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tmva/__init__.py
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx
tree/ntuple/v7/test/CustomStruct.hxx

[v632] Recent backports and fixes for 6.32

---

bindings/pyroot/pythonizations/test/memory.py

Forward-port of the last commit from https://github.com/root-project/root/pull/15809 to align the commit histories.

[PyROOT] Relax memory test

---

tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
tree/dataframe/test/dataframe_cache.cxx
tree/dataframe/test/dataframe_simple.cxx
tree/dataframe/test/dataframe_snapshot.cxx

clang-formats some RDF tests (that will need to be modified by a later PR)

[skip-ci][RDF] clang-format some RDF tests

---

graf2d/gpad/src/TPad.cxx
gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/core.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/hist/THStackPainter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs

[webgui] `TF1` save buffer, skip WaitPrimitive support, update jsroot [6.32]

---

math/mathcore/src/Integrator.cxx

BP of https://github.com/root-project/root/pull/15816

[BP 630] [math] Use correct type when invoking the GSLIntegrator

---

math/mathcore/src/Integrator.cxx

BP of https://github.com/root-project/root/pull/15816

[BP 632] [math] Use correct type when invoking the GSLIntegrator

---

graf3d/eve/src/TEveGeoNode.cxx
graf3d/eve/src/TEveGeoPolyShape.cxx
graf3d/eve/src/TEveScene.cxx
gui/browsable/src/RNTupleDraw6Provider.cxx
hist/hist/src/TGraphTime.cxx
hist/hist/src/TH1.cxx
hist/hist/src/THStack.cxx
hist/histpainter/src/THistPainter.cxx
test/Tetris.cxx
tree/treeplayer/src/TTreePerfStats.cxx
tutorials/eve7/lego.C

Use the new TPad Shortcuts provided by https://github.com/root-project/root/pull/15822

Use the new TPad shortcuts

---

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx

Move the implementation in the base class as currently its identical for the file and the DAOS backend. Additional minor simplification.

[ntuple] Improvement of RPageStorage::UnzipClusterImpl

---

tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
tree/ntuple/v7/test/ntuple_types.cxx

@pcanal IIRC you suggest a while ago that we should add a test for this.

[ntuple] add test for std::set<std::array<...>>

---

tutorials/dataframe/df027_SQliteDependencyOverVersion.C
tutorials/dataframe/df029_SQlitePlatformDistribution.C
tutorials/dataframe/df103_NanoAODHiggsAnalysis.C
tutorials/dataframe/df103_NanoAODHiggsAnalysis.py

1. When `TLegend` created - use exactly the histograms which are drawn
2. Do not use `legend.DrawClone();` - otherwise all data histograms will be cloned again
3. In `df027` tutorial first create all histograms and then draw them, otherwise dummy inactive canvas (web or normal) displayed for many seconds. 
4. Use in `df027` canvas with subpads and new `TPad::Add(TObject *)` method.
5. Prefer direct setting of `hist->SetStats(kFALSE)` instead of global `gStyle->SetOptStat(0);`

[DF] improve graphics in several tutorials

---

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx

[ntuple] remove parameter from simple SealPage overload

---

roofit/xroofit/inc/RooFit/xRooFit/xRooBrowser.h
roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
roofit/xroofit/inc/RooFit/xRooFit/xRooHypoSpace.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
roofit/xroofit/src/Asymptotics.cxx
roofit/xroofit/src/xRooBrowser.cxx
roofit/xroofit/src/xRooFit.cxx
roofit/xroofit/src/xRooFitVersion.h
roofit/xroofit/src/xRooHypoSpace.cxx
roofit/xroofit/src/xRooNLLVar.cxx
roofit/xroofit/src/xRooNode.cxx
roofit/xroofit/src/xRooNode_interactive.cxx

Updates to latest xRooFit version

[RF] xroofit update

---

core/base/inc/Bswapcpy.h

@pcanal pointed out a typo I meade,

[core] Fix typo in comment

---

roofit/histfactory/src/ParamHistFunc.cxx
roofit/roofitcore/src/RooFit/Evaluator.cxx
roofit/roofitcore/test/testRooFuncWrapper.cxx
roofit/xroofit/inc/RooFit/xRooFit/xRooBrowser.h
roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
roofit/xroofit/inc/RooFit/xRooFit/xRooHypoSpace.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
roofit/xroofit/src/Asymptotics.cxx
roofit/xroofit/src/xRooBrowser.cxx
roofit/xroofit/src/xRooFit.cxx
roofit/xroofit/src/xRooFitVersion.h
roofit/xroofit/src/xRooHypoSpace.cxx
roofit/xroofit/src/xRooNLLVar.cxx
roofit/xroofit/src/xRooNode.cxx
roofit/xroofit/src/xRooNode_interactive.cxx

A few bugfixes and improvements.

[v632][RF] Backports for RooFit for the next patch release

---

tree/ntuple/v7/src/RField.cxx

Temporary patch to help debugging  writing CMS MiniAOD in RNTuple

[ntuple] add debug output to RVectorField

---

gui/webgui6/inc/TWebCanvas.h
gui/webgui6/inc/TWebPadOptions.h
gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/core.mjs
js/modules/draw/v7more.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/display.mjs
js/modules/gui/menu.mjs
js/modules/hist/RPavePainter.mjs
js/modules/hist/TH1Painter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist/hist3d.mjs
js/modules/hist2d/RH2Painter.mjs
js/modules/hist2d/RHistPainter.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/hist2d/TScatterPainter.mjs

Fix annoying web-browser resize after reload of TWebCanvas after Ctrl-R
Handle phi/theta in TPad for lego views
Many-many fixes in JSROOT around zooming and scales handling for TH1/THStack/TScatter
Other small fixes in JSROOT

`TWebCanvas` - improve browser resize, `TScatter` Z scale, interactive `fMinimum`/`fMaximum` change

---

js/build/jsroot.js
js/changes.md
js/modules/core.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gui/menu.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/hist2d/TScatterPainter.mjs

1. Fix - interactive zooming on log color palette
2. Fix - keyboard handling while input dialog active
3. Fix - legend entry with not configured fill attributes
4. Fix - prevent that color palette exceed graphical range
5. Fix - exponential log axis labels with kMoreLogLabels bit set

[jsroot] 7.7.2 19/06/2024 [6.32]

---

hist/hist/inc/TH2.h
hist/hist/inc/TH3.h
hist/hist/src/TH2.cxx
hist/hist/src/TH3.cxx

Backport of https://github.com/root-project/root/pull/14154

[BP] [6.32] 2D/3D version of TH1::AddBinContent, as with TH2::SetBinContent/TH3::SetBinContent

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

[cling] Simplify mangling by using mangleAndIntern

---

roofit/roofitcore/inc/RooFuncWrapper.h
roofit/roofitcore/inc/RooRealSumPdf.h
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooAddPdf.cxx
roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx
roofit/roofitcore/src/RooFormulaVar.cxx
roofit/roofitcore/src/RooFuncWrapper.cxx
roofit/roofitcore/src/RooGenericPdf.cxx
roofit/roofitcore/src/RooRealSumFunc.cxx
roofit/roofitcore/src/RooRealSumPdf.cxx
roofit/roofitcore/test/testRooFuncWrapper.cxx

[RF] Some fixups to the RooFit code generation for AD in order to support CMS likelihoods

---

roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooAbsMinimizerFcn.cxx
roofit/roofitcore/src/RooAbsMinimizerFcn.h
roofit/roofitcore/src/RooMinimizer.cxx
roofit/roofitcore/src/RooMinimizerFcn.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodJob.h
roofit/roofitcore/src/TestStatistics/LikelihoodSerial.cxx
roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx
roofit/roofitcore/src/TestStatistics/RooRealL.cxx
roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/TestStatistics/testPlot.cxx

Backport of #15797 to fix the ATLAS Higgs combinations with multiprocessing.

[v632][RF] MultiProcess error handling

---

documentation/doxygen/Makefile

should fix https://github.com/root-project/web/issues/1007

[skip-ci] the generation of tag and qch files was removed

---

tree/ntuple/v7/src/RMiniFile.cxx

Currently is not backward-compatible (will fail if we read an old RNTuple version with a newer one which adds new members from version 4). Was unnoticed so far because RTFNTuple v4 and v6 (current) happen to have the same size.

[ntuple] fix check on key.fObjLen < sizeof(RTFNTuple)

---

math/minuit2/inc/Minuit2/HessianGradientCalculator.h
math/minuit2/inc/Minuit2/InitialGradientCalculator.h
math/minuit2/src/HessianGradientCalculator.cxx
math/minuit2/src/InitialGradientCalculator.cxx
math/minuit2/src/Numerical2PGradientCalculator.cxx
math/minuit2/src/SimplexSeedGenerator.cxx

Remove some unused parameter getters and setters for algorithms where these parameters are not relevant.
This makes it easier for the reader of the code what the algorithm parameters actually are.

[Minuit2] Remove unused Minuit2 code

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py

Backport of https://github.com/root-project/root/pull/15943

[jupyter] Correctly handle TCanvas with same names [6.32]

---

gui/CMakeLists.txt
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindowsManager.cxx

Always compile RBrowser when `webgui` is on, add `SetUseConnectionKey` [6.32]

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooFuncWrapper.h
roofit/roofitcore/src/RooFuncWrapper.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/src/RooProduct.cxx
roofit/roofitcore/src/RooRealIntegral.cxx
roofit/roofitcore/test/testRooFuncWrapper.cxx

This is spinning off the commits from #15616 that don't depend on a new Clad release, so we can merge and validate the development in the nightlies early.

[RF] Updates to the RooFit code generation

---

main/src/hadd.cxx

Fixes https://root-forum.cern.ch/t/change-to-hadd-that-breaks-previously-working-code/60126

[hadd] allow ROOT files without .root extension

---

main/src/hadd.cxx
roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
tutorials/roofit/rf508_listsetmanip.py

Backports of recent fixes and improvements for the next 6.32 patch release.

[v632] Backports of recent fixes and improvements

---

tree/ntuple/v7/doc/specifications.md

Follow-up of https://github.com/root-project/root/pull/16006#discussion_r1670655733

[skip-ci][NFC][ntuple] minor style change in specification

---

bindings/pyroot/pythonizations/test/memory.py

Let's see if this new configuration of the test still shows issues on some CI runs

[pyroot] Isolate potentially leaking function in test

---

tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx

[ntuple] fix-up column flags in RNTupleSerializer

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofit/src/RooParamHistFunc.cxx
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooFuncWrapper.h
roofit/roofitcore/inc/RooHistPdf.h
roofit/roofitcore/src/RooAddition.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx
roofit/roofitcore/src/RooFuncWrapper.cxx
roofit/roofitcore/src/RooHistFunc.cxx
roofit/roofitcore/src/RooHistPdf.cxx
roofit/roofitcore/src/RooRealIntegral.cxx

Update RooFit AD to support ATLAS and CMS Higgs combinations.

[RF] Update RooFit AD to support ATLAS and CMS Higgs combinations

---

core/meta/src/TMethodCall.cxx

fixes [ROOT-6968](https://its.cern.ch/jira/browse/ROOT-6968)

[skip-ci][Core] Update TMethodCall documentation

---

tree/treeplayer/inc/TTreeFormula.h
tree/treeplayer/src/TTreeFormula.cxx

fixes [ROOT-6822](https://its.cern.ch/jira/browse/ROOT-6822)

[Tree][skip-ci] Update documentation of TTreeFormula

---

math/vecops/inc/ROOT/RVec.hxx
math/vecops/test/vecops_rvec.cxx

BP of https://github.com/root-project/root/pull/16053

[BP][632] [VecOps] Use the correct type for BINARY_FUNCTION

---

graf2d/graf/src/TCurlyArc.cxx
graf2d/graf/src/TMarker.cxx

Fixes https://github.com/root-project/root/issues/15977
Improve also doxygen documentation

[graf2d] Prevent int overflow when computing squared distance

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofit/src/RooParamHistFunc.cxx
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooFuncWrapper.h
roofit/roofitcore/inc/RooHistPdf.h
roofit/roofitcore/src/RooAddition.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx
roofit/roofitcore/src/RooFuncWrapper.cxx
roofit/roofitcore/src/RooHistFunc.cxx
roofit/roofitcore/src/RooHistPdf.cxx
roofit/roofitcore/src/RooRealIntegral.cxx

[v632][RF] Update RooFit AD to support ATLAS and CMS Higgs combinations

---

bindings/r/inc/TRInternalFunction.h
net/rpdutils/CMakeLists.txt
net/rpdutils/src/DaemonUtils.cxx
net/rpdutils/src/DaemonUtils.h
tutorials/net/authclient.C
tutorials/net/authserv.C

Backports of recent fixes and improvements to the 6.32 release series.

[v632] Backport recent fixes and improvements

---

documentation/users-guide/Graphics.md
documentation/users-guide/WritingGUI.md
gui/ged/doc/index.md
hist/doc/v530/index.html

Fix partially this issue: https://github.com/root-project/root/issues/16087

[skip-ci] fix typo: DistanceToPrimitive

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/rfield_class.cxx

Follow up of https://github.com/root-project/root/pull/16060#issuecomment-2239370921 and https://github.com/root-project/root/pull/16060/files#r1684497745

[ntuple] rename StreamerChecksum to TypeChecksum

---

core/foundation/inc/ROOT/RConfig.hxx
roofit/roofitcore/inc/RooPlot.h
roofit/roofitcore/src/RooPlot.cxx

[RF] More consistent RooPlot constructors

---

roofit/roofit/src/RooHistConstraint.cxx
roofit/roofit/test/testFitPerf.cxx
roofit/roofit/test/testRooFit.cxx
roofit/roofit/test/testRooJohnson.cxx
roofit/roofitcore/inc/RooGenContext.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooGenContext.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/stressRooFit_tests.h
roofit/roofitcore/test/testRooFuncWrapper.cxx
roofit/roostats/src/NeymanConstruction.cxx
roofit/roostats/src/ToyMCSampler.cxx
roofit/roostats/test/stressRooStats_models.h
roofit/roostats/test/stressRooStats_tests.h
roofit/xroofit/src/xRooNode.cxx

Fix reported typos and improve memory management in RooFit.

[RF] Fix typos and improve memory management in RooFit

---

graf2d/graf/src/TCurlyArc.cxx
graf2d/graf/src/TMarker.cxx

BP of https://github.com/root-project/root/pull/15983

[BP][632][graf2d] Prevent int overflow when computing squared distance

---

config/thisroot.csh
config/thisroot.sh

Fixes https://github.com/root-project/root/issues/16024

[thisroot] drop also potential path from gnuinstall=ON

---

bindings/jupyroot/README.md
core/foundation/inc/ROOT/RConfig.hxx
roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
roofit/RDataFrameHelpers/test/testActionHelpers.cxx
roofit/roofit/src/RooHistConstraint.cxx
roofit/roofit/test/testFitPerf.cxx
roofit/roofit/test/testRooFit.cxx
roofit/roofit/test/testRooJohnson.cxx
roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/RooAbsDataFiller.h
roofit/roofitcore/inc/RooGenContext.h
roofit/roofitcore/inc/RooPlot.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsDataFiller.cxx
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooGenContext.cxx
roofit/roofitcore/src/RooPlot.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/stressRooFit_tests.h
roofit/roofitcore/test/testRooFuncWrapper.cxx
roofit/roostats/src/NeymanConstruction.cxx
roofit/roostats/src/ToyMCSampler.cxx
roofit/roostats/test/stressRooStats_models.h
roofit/roostats/test/stressRooStats_tests.h
roofit/xroofit/src/xRooNode.cxx

Backports of recent fixes and improvments to the 6.32 branch.

[v632] Backports of recent fixes and improvments to the 6.32 branch

---

etc/RooFitHS3_wsexportkeys.json
etc/RooFitHS3_wsfactoryexpressions.json
roofit/hs3/src/Domains.cxx
roofit/hs3/src/Domains.h
roofit/hs3/src/JSONFactories_HistFactory.cxx
roofit/hs3/src/JSONFactories_RooFitCore.cxx
roofit/hs3/src/RooJSONFactoryWSTool.cxx
roofit/hs3/test/testRooFitHS3.cxx
roofit/roofitcore/inc/RooProduct.h
roofit/roofitcore/inc/RooRealIntegral.h
roofit/roofitcore/src/RooRealIntegral.cxx

- Adds protection when exporting workspaces with defuct proxy pointers
- Adds import and export facilities for RooRealIntegral

[HS3] Fixes for stability & RooRealIntegral

---

tree/ntuple/v7/inc/ROOT/RField.hxx

Move `RIntegralField::CloneImpl` to `RField<T>` and introduce `RSimpleField`

[ntuple] Deduplicate code in `RField.hxx`

---

roofit/hs3/src/RooJSONFactoryWSTool.cxx

Follow-up on yesterdays changes.

[RF][HS3] Fix compiler warnings about binding a temporary value

---

roofit/hs3/src/RooJSONFactoryWSTool.cxx

[v632][RF][HS3] Fix compiler warnings about binding a temporary value

---

interpreter/cling/docs/conf.py
interpreter/cling/docs/tools/in2pod.py
interpreter/cling/test/lit.cfg
interpreter/cling/tools/Jupyter/kernel/clingkernel.py
interpreter/cling/tools/Jupyter/kernel/setup.py
interpreter/cling/tools/packaging/cpt.py

copy-pasted from pitkajuh https://github.com/root-project/cling/pull/519

[cling] remove references to Python2

---

tmva/sofie_parsers/src/ParseConstant.cxx

[tmva] Remove warning raised by Wshadow

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Allows for extending not only entire fields and their columns but also only columns for existing fields.

[ntuple] Allow for extending column representations

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
bindings/experimental/distrdf/python/DistRDF/HeadNode.py

[6.32] Clean RDF caches of Dask workers

---

graf2d/asimage/src/libAfterImage/.shared

[afterimage] Add new sources in .shared file

---

gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/core.mjs
js/modules/draw/TASImagePainter.mjs
js/modules/draw/TBoxPainter.mjs
js/modules/draw/more.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist/TF3Painter.mjs
js/modules/hist/TGraph2DPainter.mjs
js/modules/hist/TGraphTimePainter.mjs
js/modules/hist2d/RH1Painter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THStackPainter.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/hist2d/TMultiGraphPainter.mjs
tutorials/hist/haxis.C
ui5/canv/controller/Canvas.controller.js
ui5/canv/view/Canvas.view.xml

1. Now PDF can be created on client and just send to server
2. Also WEBP image standard supported via menu
3. Print created file size
4. Use canvas name as file name for image
5. Update 'haxis.C' tutorial - show TBox and TLatex usage on haxis frame
6. Update JSROOT with correspondent functionality, plus TProfile2D empty bin fix

[webcanvas] Support PDF and WEBP on client side

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_types.cxx

[ntuple] Add missing RField signed char specialization

---

hist/hist/inc/LinkDef.h
hist/hist/inc/THnSparse.h

[hist] Add backwards-compatibility for THnSparseL typedef

---

geom/geom/src/TGeoManager.cxx
js/build/jsroot.js
js/modules/core.mjs
js/modules/gpad/TFramePainter.mjs
tutorials/geom/parallel_world.C

[webgui] fix typo in web-based geom painter initialization

---

hist/hist/inc/TScatter.h
hist/hist/src/TScatter.cxx
hist/histpainter/src/TGraphPainter.cxx
tutorials/graphs/scatter.C

Implement properly the scatter plot palette attributes as requested here: https://github.com/root-project/root/issues/15922
Simplify scatter.C

Implement proper palette attributes for the scatter plot palette

---

roofit/roofitcore/src/RooBinnedGenContext.cxx
roofit/roofitcore/src/RooSimultaneous.cxx

Fixes https://github.com/root-project/root/issues/11565

[RF] prevent accessing empty vector (histOut)

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roocategory.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodatahist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimultaneous.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_utils.py
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooGlobalFunc.h
roofit/roofitcore/inc/RooSimultaneous.h
roofit/roofitcore/src/RooGlobalFunc.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
tutorials/CMakeLists.txt

Backport fixes and improvements.

[v632] Backport fixes and improvements

---

bindings/pyroot/pythonizations/src/TTreePyz.cxx
bindings/pyroot/pythonizations/test/TreeHelper.h
bindings/pyroot/pythonizations/test/ttree_branch_attr.py

Closes the following JIRA ticket:
https://its.cern.ch/jira/browse/ROOT-2811

[PyROOT] Correctly set shape info in TTree `__getattr__` pythonization

---

hist/hist/inc/TH2.h
hist/hist/inc/TH3.h
hist/hist/src/TH2.cxx
hist/hist/src/TH3.cxx

Closes https://its.cern.ch/jira/browse/ROOT-9297.

[hist] Add some `const` keywords to arithmetic operators

---

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx

In preparation of some changes to those files

[ntuple] clang-format some files

---

bindings/pyroot/pythonizations/test/memory.py

[6.32] [pyroot] Isolate potentially leaking function in test 

---

roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx

Improve RooFit code, mostly reducing code duplication in concatenating lists of names with comma delimiter.

[RF] RooFit code improvements

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_conversion_maps.py
roofit/roofitcore/inc/RooFit/Detail/EvaluateFuncs.h

Backport RooFit bugfix and NumPy 2 compatibility fix

[v630] Backport RooFit bugfix and NumPy 2 compatibility fix

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_conversion_maps.py
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

Backport RooFit bugfix and NumPy 2 compatibility fix

[v632] Backport RooFit bugfix and NumPy 2 compatibility fix

---

graf2d/gpad/src/TCanvas.cxx

Fixes https://github.com/root-project/root/issues/16163

[gpad] silence unused variable in release mode

---

hist/hist/inc/TGraph.h
hist/hist/inc/TGraph2D.h
hist/hist/src/TGraph.cxx
hist/hist/src/TGraph2D.cxx

Fixes https://github.com/root-project/root/issues/9637

[hist] TGraph::Add (TF1)

---

core/metacling/test/TClingTests.cxx

This PR fixes [ROOT-6913 ](https://its.cern.ch/jira/browse/ROOT-6313)

[meta] Thoroughly test TClingInfo property

---

.github/workflows/root-ci.yml
core/CMakeLists.txt
interpreter/cling/include/cling/std_darwin.modulemap

BP of https://github.com/root-project/root/pull/16225

[BP 632] [cling] Fix build with latest MacOSX15.0.sdk beta

---

geom/webviewer/CMakeLists.txt
geom/webviewer/inc/ROOT/RGeoPainter.hxx
geom/webviewer/src/RGeoPainter.cxx

For some reason implemented in painter and not in TGeoManager itself
Fixes https://github.com/root-project/root/issues/16167

[webgeom] support TGeoTrack creation

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx

Fixes https://github.com/root-project/root/issues/15919, backport from master https://github.com/wlav/cppyy-backend/pull/24

[PyROOT] Return scope in GetActualClass based on Interpreter ClassInfo

---

.github/workflows/root-ci-config/build_root.py
.github/workflows/root-ci-config/build_utils.py
.github/workflows/root-ci.yml

[ci] Improve instructions on how to replicate builds locally

---

README/ReleaseNotes/v634/index.md
hist/unfold/CMakeLists.txt
hist/unfold/inc/LinkDef.h
hist/unfold/inc/TUnfold.h
hist/unfold/inc/TUnfoldBinning.h
hist/unfold/inc/TUnfoldBinningXML.h
hist/unfold/inc/TUnfoldDensity.h
hist/unfold/inc/TUnfoldIterativeEM.h
hist/unfold/inc/TUnfoldSys.h
hist/unfold/src/TUnfold.cxx
hist/unfold/src/TUnfoldBinning.cxx
hist/unfold/src/TUnfoldBinningXML.cxx
hist/unfold/src/TUnfoldDensity.cxx
hist/unfold/src/TUnfoldIterativeEM.cxx
hist/unfold/src/TUnfoldSys.cxx

See: https://www.desy.de/~sschmitt/tunfold.html
Motivated also by this forum post:
https://root-forum.cern.ch/t/unable-to-run-tunfold-17-9-version-with-root-6-24

[hist] Update TUnfold to most recent version 17.9

---

.github/workflows/root-ci-config/buildconfig/mac-beta.txt

[ci] Enable clad on mac beta

---

core/base/src/TApplication.cxx

fixes [ROOT-5843](https://its.cern.ch/jira/browse/ROOT-5843)
See https://github.com/root-project/roottest/pull/1175

[Core] Add the .libraries command at the prompt

---

.github/workflows/root-ci.yml

BP of https://github.com/root-project/root/pull/16303

[BP632][ci] Instruct Checkout action to fetch the correct branch

---

io/io/test/CMakeLists.txt

BP of https://github.com/root-project/root/pull/16302

[BP632] Disable tmapfiletest 632

---

roofit/hs3/src/RooJSONFactoryWSTool.cxx

Small extensions on the documentation of RooJSONFactoryWSTool, adding a C++ example as well.

[RF][HS3] improved documentation of RooJSONFactoryWSTool

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

The `ClingMMapper` must remain available until all `ClingMemoryManager`s are destructed, which is typically during shutdown of `IncrementalJIT`. This was not the case for the global object `MMapperInstance` that was introduced during the upgrade to LLVM 13 because `libCling` variables are destructed before running `TROOT` `atexit` handlers that shut down the JIT. In practice, it happened to work but this will change with the upgrade to LLVM 18 where we see crashes in some tests, potentially because of upstream commit https://github.com/llvm/llvm-project/commit/47f5c54f997a59bb2c65abe6b8b811f6e7553456.
See also commits e0f6c04660 ("Prevent static destruction from ending DefaultMMapper too early") and 80c14bb948 ("Extend lifetime of SectionMemoryManager::DefaultMMapper, again") for the same …

[cling] Fix lifetime of `ClingMMapper`

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

The `ClingMMapper` must remain available until all `ClingMemoryManager`s are destructed, which is typically during shutdown of `IncrementalJIT`. This was not the case for the global object `MMapperInstance` that was introduced during the upgrade to LLVM 13 because `libCling` variables are destructed before running `TROOT` `atexit` handlers that shut down the JIT. In practice, it happened to work but this will change with the upgrade to LLVM 18 where we see crashes in some tests, potentially because of upstream commit https://github.com/llvm/llvm-project/commit/47f5c54f997a59bb2c65abe6b8b811f6e7553456.
See also commits e0f6c04660 ("Prevent static destruction from ending DefaultMMapper too early") and 80c14bb948 ("Extend lifetime of SectionMemoryManager::DefaultMMapper, again") for the same …

[cling] Fix lifetime of `ClingMMapper` [v6.32]

---

tree/treeplayer/test/leafs.cxx

Fixes [ROOT-9354](https://its.cern.ch/jira/browse/ROOT-9354)

[Tree] Extend testing of TTreeReader

---

core/metacling/test/TClingTests.cxx

This PR fixes #12108 by providing a test.
We want to make sure that on Windows the test passes as well.

[core] Add test for #12108

---

roofit/roofitcore/test/testTestStatistics.cxx

The data resetting should work seamlessly with the new NLL evaluation backend, so as far as I can tell there is nothing to be done to address #15763.
However, it is good to add a unit test for it, so that we can also easily add tests for potentially problematic corner cases in the future.
Possibly closes #15763, if there are no corner cases where data resetting doesn't work.

[RF] Add unit test for resetting data of NLL variables

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx

[rdf] fix gcc14 warning in InterfaceUtils #16360

---

tree/dataframe/test/dataframe_datasetspec.cxx
tree/dataframe/test/dataframe_friends.cxx
tree/treeplayer/inc/TFriendProxy.h
tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TFriendProxy.cxx
tree/treeplayer/src/TTreeProcessorMT.cxx
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/src/TTreeReaderArray.cxx
tree/treeplayer/src/TTreeReaderValue.cxx
tree/treeplayer/test/CMakeLists.txt
tree/treeplayer/test/ttreereader_friends.cxx

Fixes #9137
This PR includes changes from https://github.com/root-project/root/pull/16162

Detect mismatched event counts in TTreeReader with friends

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx

Gives no any advantage
Follow up of https://github.com/root-project/root/pull/16362

[rdf] remove lambda from InterfaceUtils.hxx

---

tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_evolution.cxx

* Removal of members
* Removal of base class
* Reordering of members
Some more tests of cases that we probably want to support eventually are available in a branch: https://github.com/hahnjo/root/tree/ntuple-evolution-tests

[ntuple] Add first evolution tests for transparently supported cases

---

core/base/inc/Bytes.h

[core] Do not drop constness with casts

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx

[NFC][ntuple] Fixes to writing out streamer info record

---

interpreter/cling/lib/Interpreter/BackendPasses.cpp
interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

Fixes extracted from https://github.com/root-project/root/pull/14246

[cling] Two fixes for JITLink on Linux

---

js/build/jsroot.js
js/changes.md
js/modules/core.mjs
js/modules/draw.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/geom/geobase.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gui.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/gui/utils.mjs
js/modules/hist/TGraph2DPainter.mjs
js/modules/hist2d/TH2Painter.mjs
ui5/canv/controller/Canvas.controller.js
ui5/canv/view/Canvas.view.xml

In case of exception in  JavaScript painting code show warning sign and let easily see associated log message.
Before some printout was done in browser console which is not easily accessible by users.

[webcanv] Clearly indicate error in the canvas

---

hist/hist/inc/TFormula.h
hist/hist/test/CMakeLists.txt
hist/hist/test/test_tf1_simple.cxx
test/stress.cxx

This PR is a revamp of https://github.com/root-project/root/pull/16187
This PR fixes #16184
Associated PR in roottest: https://github.com/root-project/roottest/pull/1185

[Hist] Improve I/O of TFormula

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_conversion_maps.py
roofit/roofitcore/inc/RooCustomizer.h
roofit/roofitcore/src/RooCustomizer.cxx

Backports of recent PyROOT fixes and improvements to address #16402.

[v632][PyROOT] Backports of recent PyROOT fixes and improvements

---

roofit/roofitcore/src/RooHist.cxx

This PR fixes  [ROOT-8271](https://its.cern.ch/jira/browse/ROOT-8271)

[RF] Protect against calculating 0/0

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
tutorials/CMakeLists.txt
tutorials/dataframe/df106_HiggsToFourLeptons.py
tutorials/roofit/rf615_simulation_based_inference.py
tutorials/roofit/rf616_morphing.C
tutorials/roofit/rf616_morphing.py
tutorials/roofit/rf617_simulation_based_inference_multidimensional.py
tutorials/roofit/rf618_mixture_models.py

- added morphing tutorial in cpp and python.

[RF] Added tutorials for morphing and SBI

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Bump clad to version v1.7 to support macOS 15.

[v632][clad] Bump clad to version v1.7

---

gui/browsable/src/RSysFile.cxx

[rbrowser] use "File system" for top folder name

---

gui/fitpanelv7/inc/ROOT/RFitPanel.hxx
gui/fitpanelv7/src/RFitPanel.cxx
gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/changes.md
js/modules/base/BasePainter.mjs
js/modules/core.mjs
js/modules/draw/TLinePainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/hist2d/TGraphPainter.mjs
ui5/canv/controller/Canvas.controller.js
ui5/canv/controller/CanvasPanel.controller.js
ui5/panel/Controller.js

RWebWindow provides method for embeding other widgets and sharing existing connection.
Use this functionality for RFitPanel - when started from canvas menu.
Like with GED, special area created on the left side and fit panel is embed
Chrome browser will be resized to preserve canvas painting size.
When started via context menu - fit panel will be independently running as before

[webcanv] Let embed fit panel into TWebCanvas

---

graf2d/gpad/inc/TRatioPlot.h
graf2d/gpad/src/TRatioPlot.cxx

Add a new TRatioplot constructor as requested here: https://github.com/root-project/root/issues/16479

New ctor using THStack

---

roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
roofit/RDataFrameHelpers/test/testActionHelpers.cxx

[v632][RF] Explicitly cast to double in RooAbsDataHelper

---

tutorials/CMakeLists.txt

webgui: Disable tutorials that requires webgui (when off) [6.32]

---

ui5/browser/controller/Browser.controller.js
ui5/browser/controller/FileDialog.controller.js
ui5/browser/model/BrowserModel.js
ui5/geom/controller/GeomHierarchy.controller.js
ui5/geom/controller/GeomViewer.controller.js
ui5/geom/index.html
ui5/geom/lib/ColorBox.js
ui5/geom/lib/GeomDrawing.js

Like in RBrowser, allows smooth resize of geometry hierarchy in geometry viewer
Also fix spelling and formatting there

[webgui] improve resize of master in SplitApp

---

tree/dataframe/src/RDFUtils.cxx

The TypeID2TypeName function looks for generic types via TClass::GetClass, thus taking a lock. If we only need to check for simple types such as bool or unsigned char, we should not need that.
This change decreases contention in heavily multithreaded runs. In a test run of the AGC with 1 file and 128 threads, these are the results:
Before:
Executing the computation graphs took 23.37 seconds After:
Executing the computation graphs took 5.55 seconds
I was investigating a performance degradation of the AGC signalled on the forum https://root-forum.cern.ch/t/rootdataframe-and-multithreading-in-6-32/61752 . git bisect brought me to [this commit](https://github.com/root-project/root/commit/4cac104e75d15c6744144b1f0e43dcf87c35bc8a) which seems to be at least contributing to the degradation.

[df] Avoid lock to check simple typeids

---

.github/workflows/root-ci.yml

Change the builds from Debug to RelWithDebInfo and re-enable x86

[CI][skip-ci] Change from Debug to RelWithDebInfo

---

core/cont/inc/TCollectionProxyInfo.h
core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx
core/meta/src/TStreamerElement.cxx
io/io/src/TBufferFile.cxx
io/io/src/TGenCollectionProxy.cxx
io/io/src/TStreamerInfo.cxx
io/io/src/TStreamerInfoActions.cxx

No actual behavior change is expected.
CollectionProxy's `next wrapper/implementation` for Bitset is seemingly currently unused (hence the problem was not seen), however it will be used start in the next set of PRs introducing more Writing StreamerInfoActions (hence the existing bitset test will serve as tests).
Related roottest PR: https://github.com/root-project/roottest/pull/1189

io: Misc code improvement in io/io

---

tree/dataframe/src/RDataFrame.cxx

Adding a very simple example (as we were showing in the student course) to showcase the difference between running the event loop vs running it multiple times. 
This PR fixes #13440.

[skip-ci][DF] Add example how to correctly vs incorrectly run event-loop.

---

tutorials/CMakeLists.txt

fixes the issues about dependencies mentioned in #16553

[cmake] Correct dependencies for tutorial-tmva-TMVA_SOFIE_RDataFrame-py

---

tree/ntuple/v7/doc/specifications.md

[skip-ci][NFC][ntuple] clarify column order with late model extension

---

.github/workflows/root-ci-config/build_root.py
.github/workflows/root-ci.yml

- Add a new step running on self-hosted arm machines.
- Add a machine tag to S3 URL to not clash with x86 builds.

[CI] Add a first arm run.

---

core/meta/inc/TVirtualStreamerInfo.h
core/meta/src/TStreamerElement.cxx
io/io/inc/TStreamerInfo.h
io/io/src/TStreamerInfo.cxx

Also add 'missing' `EReadWrite` values.

Remove StreamerInfo `EReadWrite` duplication

---

tree/dataframe/src/RDFUtils.cxx

[df] Use maps for internal type lookups

---

tutorials/v7/ntuple/ntpl014_framework.C

[ntuple] Add tutorial for framework usage

---

js/changes.md
js/modules/base/FontHandler.mjs
js/modules/base/ObjectPainter.mjs
js/modules/base/TAttMarkerHandler.mjs
js/modules/base/latex.mjs
js/modules/base/svg2pdf.mjs
js/modules/core.mjs
js/modules/draw/more.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gui/menu.mjs
js/modules/gui/utils.mjs
tutorials/CMakeLists.txt
tutorials/index.md
tutorials/webcanv/fonts_ttf.cxx
tutorials/webcanv/haxis.cxx
tutorials/webcanv/inframe.cxx
tutorials/webcanv/latex_url.cxx
tutorials/webcanv/logN.cxx
tutorials/webcanv/twoscales.cxx

1. `haxis.cxx` - horizontal Y axis and TH1 drawing
2. `logN.cxx` - different log scales
3. `twoscales.cxx` - fully interactive two Y and two X scales 
4. `inframe.cxx` - drawing text, line, rect, marker in the frame with clipping
5. `latex_url.cxx` - demo for `#url[link]{label}` functionality (with PDF support)
6. `fonts_ttf.cxx` - using of custom TTF fonts in canvas (with PDF support)
Update JSROOT which implements now `#url[link]{label}` in latex parsing
Add tutorial macros in testing

[webcanv] introduce dedicated TWebCanvas tutorials

---

.github/workflows/root-ci.yml

- Enable ccache for arm linux builds
- Add steps that print ccache stats

Try using ccache in CI

---

core/meta/src/TStreamerElement.cxx

This PR is chained with/after https://github.com/root-project/root/pull/16538 only the last commit is relevant.
This PR requires the roottest PR [#195](https://github.com/root-project/roottest/pull/1195)

meta: Add newtype info to TStreamerSTL::ls

---

.github/workflows/root-ci.yml
.github/workflows/test-coverage.yml

[CI] Add CPU label for standard jobs; update upload-artifact action.

---

.github/workflows/root-ci.yml
.github/workflows/test-coverage.yml

[v6-30][CI] Add a cpu label to github workflows; update actions. 

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_cast.cxx

Allows for reading integers from other integer types. Includes bounds checking where necessary. The tests are a little mechanical but I'm not sure if the code would improve with more templates.

[ntuple] add integer type casts

---

documentation/doxygen/MakeTCanvasJS.C

Such JSON supports much more features like custom fonts or proper handling of THStack.

[doxygen] use TWebCanvas to create JSON

---

js/changes.md
js/modules/base/latex.mjs
js/modules/core.mjs
js/modules/draw/more.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TH1Painter.mjs

1. Fix - do not force style 8 for hist markers
2. Fix - ensure minimal hist title height
3. Fix - proper font-size handling in latex

[jsroot] dev 8/10/2024

---

tmva/tmva/inc/TMVA/RReader.hxx

To make the RReader usable in multi-thread we ned to move the loch to all the COmpute funcitions in order to protect the setting of the input variables
This fixes #16600 as suggested in https://root-forum.cern.ch/t/tmva-rreader-not-multithread-safe/59662

[tmva] Fix multi-threading issue with TMVA RReader

---

gui/webdisplay/src/RWebDisplayHandle.cxx
js/files/canv_batch.htm
js/modules/base/jspdf.mjs
js/modules/core.mjs

Browser will  read all data and all scripts from HTML file directly - 
no need to manage access to file system.
Make more robust batch mode of web canvas

[webcanvas] Embed JSROOT into canv_batch.htm

---

cmake/modules/RootMacros.cmake

[cmake] Make pyunittests and gtests name uniform

---

requirements.txt

See https://github.com/pytorch/pytorch/issues/138333

[TMVA] Require torch<2.5 otherwise on ARM an error is prompted

---

tree/ntuple/v7/src/RField.cxx

Use consistently new/delete instead of malloc/free. Except for the RVec handling, because RVec itself uses malloc/free.

[ntuple] replace malloc() by new where possible

---

core/zip/inc/Compression.h
core/zip/inc/RZip.h
core/zip/src/RZip.cxx

- R__getCompressionAlgorithm(): inspects the compression algorithm used by a given buffer;
- AlgorithmFromCompressionSettings(): convert a compression settings int to a EAlgorithm.

[core] add utility functions for compression

---

bindings/pyroot/pythonizations/test/CMakeLists.txt

This PR adds a test for #14710

[cmake] Re-add python stl_set tests

---

tmva/sofie/README.md
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

Remove also a duplication in registering operator in RModelParser_ONNX

[tmva][sofie] Update documentation with list of supported ONNX operators

---

tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/src/RField.cxx

This clearly signals ownership transfer and avoids circumventing smart pointer semantics. For more details on passing the vector by value, see also commit c7dac7370d.

[ntuple] Construct RVariantField with vector of unique_ptr

---

.github/workflows/root-ci-config/buildconfig/ubuntu20.txt
.github/workflows/root-ci-config/buildconfig/ubuntu22.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2404.txt

This is an attempt to fix https://github.com/root-project/root/issues/16774 once the next release is created.

[ci] Enable Sofie on all Ubuntu versions

---

hist/hist/inc/TF1.h
hist/hist/inc/TH1.h
hist/hist/src/TF1.cxx
hist/hist/src/TH1.cxx

Fixes https://github.com/root-project/root/issues/16736
following suggestions by @AntoniMarcinek
original code is from @eoffermann

[hist] more consistent notation of GetQuantile function

---

bindings/experimental/distrdf/python/DistRDF/Proxy.py
bindings/experimental/distrdf/test/test_proxy.py

Simple addition of the GetColumnType function to distributed RDF. 
This PR fixes #15039

[df] Add GetColumnType function to distrRDF

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/test/ntuple_serialize.cxx

for consistency with C++20 ranges.

[ntuple] rename iterators' count() -> size()

---

tree/ntuple/v7/test/ntuple_view.cxx

I realized we were missing a test for accessing a view out of bounds, so I added one.

[ntuple] add a test for accessing a RNTupleView out of bounds

---

js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/base/base3d.mjs
js/modules/core.mjs
js/modules/draw.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gui/menu.mjs
js/modules/gui/utils.mjs
js/modules/hist/RH3Painter.mjs
js/modules/hist/TH3Painter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/io.mjs

1. Fix - handle reordering of fragments in multipart reply https://github.com/root-project/jsroot/issues/319
2. Fix - properly show non-zero entries https://github.com/root-project/jsroot/issues/320
3. Fix - display empty hist bin if fSumw2 not zero
4. Fix - let use batch_mode script injection in interactive session

[jsroot] dev 30/10/2024

---

roofit/roofitcore/inc/RooBinSamplingPdf.h

https://github.com/root-project/root/issues/16796

forward call to createExpectedEventsFunc to subpdf

---

README/ReleaseNotes/v636/index.md
bindings/tpython/inc/TPython.h
bindings/tpython/src/TPython.cxx
core/zip/inc/Compression.h
core/zip/inc/RZip.h
core/zip/src/Compression.cxx
core/zip/src/RZip.cxx
geom/geom/inc/TGeoBBox.h
geom/geom/src/TGeoBBox.cxx
roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/src/RooAbsCollection.cxx

Superseeds https://github.com/root-project/root/pull/16822
Sister PR in roottest: https://github.com/root-project/roottest/pull/1212

TPython, Geo, RF and Core removal of deprecated components

---

hist/hist/src/TH1.cxx

Fixes https://github.com/root-project/root/issues/12251

[hist] fine-tune getquantile computation

---

js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/base/base3d.mjs
js/modules/core.mjs
js/modules/draw/more.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/menu.mjs
js/modules/hist/TH1Painter.mjs
js/modules/hist/TH2Painter.mjs
js/modules/hist/TH3Painter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist/hist3d.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs
ui5/canv/controller/Canvas.controller.js
ui5/canv/controller/Ged.controller.js
ui5/canv/view/Axis.fragment.xml
ui5/canv/view/Ged.view.xml
ui5/canv/view/Hist.fragment.xml

1. Let select histograms and axes on lego/surf plots
2. Add support of TH3 draw options to GED
3. Fix web browser resize problem after reloading canvas with GED enabled
4. Update JSROOT with correspondent changes

[webcanvas] improve GED for lego plots, support TH3

---

graf3d/eve7/src/REveManager.cxx
gui/webdisplay/src/RWebWindow.cxx

Now this mode by default off for all web widgets
Disable it for REve which is very special application anyway
After #16455

[reve] allow multiple connections

---

hist/hist/src/TH2Poly.cxx

[v630][hist] prevent nullptr access with copy from default constructor

---

hist/hist/src/TH2Poly.cxx

[v632][hist] prevent nullptr access with copy from default constructor

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md

Backport of https://github.com/root-project/root/pull/16813

[6.34] [ntuple] Add naming rules to the specification

---

js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/base/base3d.mjs
js/modules/core.mjs
js/modules/draw/more.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/menu.mjs
js/modules/hist/TH1Painter.mjs
js/modules/hist/TH2Painter.mjs
js/modules/hist/TH3Painter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist/hist3d.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs
ui5/canv/controller/Canvas.controller.js
ui5/canv/controller/Ged.controller.js
ui5/canv/view/Axis.fragment.xml
ui5/canv/view/Ged.view.xml
ui5/canv/view/Hist.fragment.xml

[webcanvas] improve GED for lego plots, support TH3 [6.34]

---

tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/inc/ROOT/RPagePool.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RPagePool.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_pages.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

Backport of #16810 
Fixes #16815

[v6.34][ntuple] Fix IMT reading with type cast

---

.github/workflows/root-ci-config/buildconfig/ubuntu2410.txt
.github/workflows/root-ci.yml
bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tformula.py
bindings/pyroot/pythonizations/src/PyROOTModule.cxx
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/pyroot/pythonizations/src/PyROOTWrapper.h
bindings/pyroot/pythonizations/src/TMemoryRegulator.cxx
bindings/pyroot/pythonizations/src/TMemoryRegulator.h

With *all* these changes, I do not see anymore failures in a local run with the ubuntu 24.10 CI image. let's see if the rest of the CI agrees. Note that one of the changes is equivalent to https://github.com/root-project/root/pull/16671

Simplify memory regulation logic

---

js/changes.md
js/modules/base/FontHandler.mjs
js/modules/core.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/hist/TH2Painter.mjs
js/modules/hist/hist3d.mjs
js/modules/hist2d/TGraphPainter.mjs
ui5/canv/controller/Ged.controller.js
ui5/canv/view/Axis.fragment.xml

1. Select title and labels fonts for axis
2. Support labels and title rotation on lego plots
3. Properly center labels on 3d plots
4. Fix toggling 2d/3d mode with canvas resize in-between

[webcanvas] select axes fonts in GED

---

README/ReleaseNotes/v634/index.md

BP of https://github.com/root-project/root/pull/16871

[BP 6.34][skip-ci][rn] Update information about contributors, deprecations and builtins

---

graf2d/gpad/src/TPad.cxx
graf2d/graf/src/TBox.cxx
graf2d/graf/src/TCurlyArc.cxx
graf2d/graf/src/TCurlyLine.cxx
graf2d/graf/src/TEllipse.cxx
graf2d/graf/src/TLine.cxx
graf2d/graf/src/TMarker.cxx
graf2d/graf/src/TText.cxx

1. Adjust TPad methods - check `gPad` as well
2. Remove double check in TEllipse
3. Replace `return (p)` with `return p`

[gpad] Check gPad in bbox methods

---

README/ReleaseNotes/v634/index.md

* [NFC][ntuple] add v6.34 release notes
* [NFC][ntuple] clarify v6.34 release notes
Co-authored-by: Florine de Geus <git@fwdg.nl>
* [NFC][ntuple] clarify v6.34 release notes
Co-authored-by: Philippe Canal <pcanal@fnal.gov>
* [NFC][ntuple] clarify v6.34 release notes
Co-authored-by: Philippe Canal <pcanal@fnal.gov>
---------
Co-authored-by: Florine de Geus <git@fwdg.nl>
Co-authored-by: Philippe Canal <pcanal@fnal.gov>
(cherry picked from commit dd1b0087667f3218b57d192852b6b1448abeeaf8)

[v6.34][NFC][ntuple] add v6.34 release notes (#16887)

---

js/changes.md
js/modules/core.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/hist2d/RHistPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs

This will be base version for ROOT 6.34 branch
See full change log in release: https://github.com/root-project/jsroot/releases/tag/7.8.0

[jsroot] 7.8.0 11/11/2024

---

js/changes.md
js/modules/core.mjs
js/modules/geom/TGeoPainter.mjs
js/modules/hist2d/RHistPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs

This will be base version for ROOT 6.34 branch
See full changelog in release: https://github.com/root-project/jsroot/releases/tag/7.8.0

[jsroot] 7.8.0 11/11/2024 [6.34]

---

README/ReleaseNotes/v634/index.md

Backport of https://github.com/root-project/root/pull/16881

[BP 6.34][skip-ci][rn] Add notes about setting initial error values for Minuit2 minimiser

---

test/CMakeLists.txt

BP of https://github.com/root-project/root/pull/16876

[6.34]Disable stress graphics chrome

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooMultiVarGaussian.h
roofit/roofitcore/src/RooMultiVarGaussian.cxx

[RF] Implement code generation for RooMultiVarGaussian

---

README/ReleaseNotes/v634/index.md

BP of https://github.com/root-project/root/pull/16904

[6.34][skip-ci][rn] Update and consolidate

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_regression.cxx

Backport of https://github.com/root-project/root/pull/16872

[6.34] [rdf] Allow for more complex file names in constructor

---

README/ReleaseNotes/v634/index.md

[6.34] [relnotes] Add more notes for RDataFrame, TTree, RNTuple

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_regression.cxx
tree/tree/src/TChain.cxx
tree/tree/test/TChainParsing.cxx

[6.32] [rdf] Allow for more complex file names in constructor

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

Backport of https://github.com/root-project/root/pull/16855

[6.34][ntuple] Merger: properly handle columns with different representations 

---

README/ReleaseNotes/v634/index.md

[skip-ci] update release notes

---

README/ReleaseNotes/v634/index.md

Mirror changes from 6.34 release notes

[skip-ci] 6.34 rel notes

---

core/testsupport/src/TestSupport.cxx
tree/ntuple/v7/doc/BinaryFormatSpecification.md
tree/ntuple/v7/inc/ROOT/RNTuple.hxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/rfield_class.cxx
tutorials/v7/ntuple/ntpl001_staff.C
tutorials/v7/ntuple/ntpl002_vector.C
tutorials/v7/ntuple/ntpl004_dimuon.C
tutorials/v7/ntuple/ntpl005_introspection.C
tutorials/v7/ntuple/ntpl006_friends.C
tutorials/v7/ntuple/ntpl007_mtFill.C
tutorials/v7/ntuple/ntpl008_import.C
tutorials/v7/ntuple/ntpl009_parallelWriter.C
tutorials/v7/ntuple/ntpl010_skim.C
tutorials/v7/ntuple/ntpl011_global_temperatures.C
tutorials/v7/ntuple/ntpl012_processor.C
tutorials/v7/ntuple/ntpl013_staged.C
tutorials/v7/ntuple/ntpl014_framework.C

[v6.34][ntuple] Binary format version 1.0.0.0

---

core/foundation/inc/ROOT/RVersion.hxx

otherwise, the release version will be 6.32.007

[core] Set patch number to 7 and not 07

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tstyle.py
bindings/pyroot/pythonizations/test/memory.py

[v634][PyROOT] Retain C++ memory ownership for TStyle

---

gui/gui/src/TGNumberEntry.cxx

[v634] Fix buffer overflow when opening the Fit Panel

---

gui/gui/src/TGNumberEntry.cxx

[v632] Fix buffer overflow when opening the Fit Panel

---

core/foundation/inc/ROOT/RVersion.hxx

otherwise, the release version will be 6.35.001

[core] Set patch number to 1 and not 01

---

.github/workflows/root-ci-config/buildconfig/ubuntu20.txt
.github/workflows/root-ci.yml

the EOL is in April, ROOT 6.36 is foreseen in May

[ci] Remove ubu20 from master

---

tree/tree/test/TTreeRegressions.cxx

[tree] Add test for ROOT-9961

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf3.py
bindings/pyroot/pythonizations/test/memory.py

Backport of https://github.com/root-project/root/pull/16945

[6.34] [PyROOT] Retain C++ ownership for TF2, TF3

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_regression.cxx

Fixes https://github.com/root-project/root/issues/16946

[df] Check for empty file list in constructor

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tcolor.py
bindings/pyroot/pythonizations/test/memory.py

Prevent crashes due to TColor memory ownership

[PyROOT] Retain C++ ownership for TColor

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_regression.cxx

BP of https://github.com/root-project/root/pull/16961

[6.34][df] Check for empty file list in constructor

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tcolor.py
bindings/pyroot/pythonizations/test/memory.py

BP of https://github.com/root-project/root/pull/16950

[6.34][PyROOT] Retain C++ ownership for TColor

---

README/ReleaseNotes/v634/index.md

REve information for v6-34-00 ReleaseNotes.

[reve] Addition to v6-34-00 ReleaseNotes

---

core/meta/src/TClass.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-5439

[core] print -> symbol when dumping pointer in showMembers

---

hist/hist/src/TGraph.cxx
hist/hist/src/TH1.cxx
hist/hist/test/test_MapCppName.cxx

Fixes https://github.com/root-project/root/issues/16687

[hist] increase precision of TH1's and TGraph's SavePrimitive to double

---

core/meta/src/TClass.cxx

BP of https://github.com/root-project/root/pull/16978

[6.34][core] print -> symbol when dumping pointer in showMembers

---

README/ReleaseNotes/v634/index.md

(cherry picked from commit cea09713dbf295f7333ce0fe5cc29bc74e8c54cb)

[skip-ci] add hadd-related notes

---

README/ReleaseNotes/v634/index.md

Hope this is still in time for the release.

[RF] MultiProcess additions to release notes

---

roofit/roofitcore/inc/RooFit/CodegenContext.h
roofit/roofitcore/src/RooFit/CodegenContext.cxx

The produced code from the RooFit codegen backend is hard to follow. We add clarification comments with extra information from the RooFit grapn which can help the reader to correlate for which node the code was produced. That helps in understanding complex fits and should aid the adoption and debugging of AD in CMS Combine.
The implementation reworks the lexical scopes handling by implementing a stack to enable (mostly) correct indentations for both the generated code and the generated comments.

[RF] Implement an initial version of comment annotations for codegen.

---

hist/hist/test/test_TH1.cxx

[core] Test dumping pointers in ShowMembers

---

tree/treeplayer/inc/TTreeReaderGenerator.h
tree/treeplayer/src/TTreePlayer.cxx
tree/treeplayer/src/TTreeReaderGenerator.cxx

So convert wherever need in produced selector code
Fixes https://its.cern.ch/jira/browse/ROOT-8775

[tree] valid branch names or filenames does not ensure valid C++ variable names

---

gui/gui/src/TGPicture.cxx

Parameter Doxygen documentation was missing

[skip-ci] Complete parameter documentation

---

tree/ntuple/v7/src/RFieldSequenceContainer.cxx

By allowing the compiler to use a single instruction for quotient and remainder, there is a significant improvement in the RNTuple serialization throughput (writing to `/dev/null`):
* For my "standard" benchmark of writing random float values into a vector with a size determined by a Poisson distribution (mu = 5), this change reduces run time by around 2%.
* For well tuned sequential writing of constant data (one fixed size vector), the reduction can be up to 7.5%.

[ntuple] Micro-optimize `RVectorField::AppendImpl`

---

roofit/codegen/inc/RooFit/CodegenImpl.h
roofit/codegen/src/CodegenImpl.cxx
roofit/roofitcore/inc/RooRealSumPdf.h
roofit/roofitcore/src/RooRealSumPdf.cxx
roofit/roofitcore/test/testRooFuncWrapper.cxx

Reusing existing translate method since integration is linear

[RF] Add analytic integral for RooRealSumPdf (Codegen backend)

---

core/meta/inc/TInterpreter.h
core/metacling/src/TCling.h

as suggested by pcanal in the previous MR, see https://github.com/root-project/root/pull/16966#discussion_r1854043894

[meta] Add TInterpreter::IsValid

---

README/ReleaseNotes/v634/index.md

BP of https://github.com/root-project/root/pull/17016

[6.34][skip-ci][rn] Update set of closed items for 6.34.00

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
tree/tree/src/TTree.cxx

Focus in particular on the Python interface.

[skip-ci][tree] Revamp TTree documentation

---

tutorials/roofit/rf102_dataimport.C
tutorials/roofit/rf102_dataimport.py
tutorials/roofit/rf303_conditional.C
tutorials/roofit/rf303_conditional.py
tutorials/roofit/rf401_importttreethx.C
tutorials/roofit/rf401_importttreethx.py
tutorials/roofit/rf609_xychi2fit.C
tutorials/roofit/rf609_xychi2fit.py

This demonstrates the good practice of not relying of global variables.

[RF] Use TRandom3 explicitly in RooFit

---

tmva/tmva/src/DataLoader.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-10018

[tmva] fix crash in addEvent if no addVariable was called before

---

README/ReleaseNotes/v634/index.md

BP of https://github.com/root-project/root/pull/17063

[skip-ci][6.34][rn] Update closed issues

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py

[skip-ci] add awkward to-from rdataframe documentation

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tscatter.py

Added TScatter python documentation as a part of https://github.com/orgs/root-project/projects/18?pane=issue&itemId=88466000

Add pyroot documentation for TScatter

---

tree/ntuple/v7/doc/Architecture.md

[skip-ci][doc][ntuple] Update Architecture document

---

tutorials/v7/ntuple/index.md
tutorials/v7/ntuple/ntpl011_global_temperatures.C

[skip-ci][tutorials][ntuple] Add comments to ntuple tutorilas category

---

tree/ntuple/v7/inc/ROOT/RPagePool.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RPagePool.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_pages.cxx

- Improves the search complexity for pages in a given column from linear to logarithmic
- Prevents the same page from being added multiple times to the page pool
- Evicts unused pages from clusters before the currently active one

[ntuple] Several page pool improvements

---

geom/geom/inc/bvh/v2/bvh.h
graf3d/gl/src/TGLSdfFontMakerLowLevel.icxx
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx
roofit/roostats/src/HLFactory.cxx
tutorials/roofit/rf903_numintcache.C
tutorials/roofit/rf903_numintcache.py

Backport of #17042, plus some other small commits to let the codebase not diverge too much at this point.

[v634][RF] Skip normalization over nEvents in RooSimultaneous if necessary

---

bindings/pyroot/pythonizations/python/ROOT/__init__.py
tutorials/tmva/keras/ClassificationKeras.py
tutorials/tmva/keras/MulticlassKeras.py
tutorials/tmva/keras/RegressionKeras.py

Yet again attempting this to see what happens in our CI. In some preliminary tests in a development environment built against the latest LCG release, this helps avoiding segfaults.

[python] Avoid interfering with gc at exit time

---

bindings/pyroot/pythonizations/python/ROOT/__init__.py
tutorials/tmva/keras/ClassificationKeras.py
tutorials/tmva/keras/MulticlassKeras.py
tutorials/tmva/keras/RegressionKeras.py

Backport of https://github.com/root-project/root/pull/17085

[6.34] Avoid interfering with gc at exit time 

---

gui/webdisplay/src/RWebDisplayHandle.cxx

[webgui] Use posix_spawn to start chrome in headless for ping [6.34]

---

core/base/src/TSystem.cxx

[core] Prevent buffer underrun in SplitAclicMode (thanks, SonarCloud)

---

roofit/xroofit/CMakeLists.txt
roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
roofit/xroofit/src/xRooFit.cxx
roofit/xroofit/src/xRooFitVersion.h
roofit/xroofit/src/xRooHypoSpace.cxx
roofit/xroofit/src/xRooNLLVar.cxx
roofit/xroofit/src/xRooNode.cxx
roofit/xroofit/test/CMakeLists.txt
roofit/xroofit/test/xroofit_python.py

This is a latest version of the xRooFit API. I have also made a first attempt at adding a python test for the API, which also provides an example of how to build a simple workspace and run a CLs limit.

update xroofit for next ROOT release

---

math/minuit2/src/CMakeLists.txt

[v634][Minuit2] Remove deleted header file reference

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
bindings/pyroot/pythonizations/test/import_load_libs.py
roofit/xroofit/CMakeLists.txt
roofit/xroofit/inc/RooFit/xRooFit/xRooFit.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
roofit/xroofit/src/xRooFit.cxx
roofit/xroofit/src/xRooFitVersion.h
roofit/xroofit/src/xRooHypoSpace.cxx
roofit/xroofit/src/xRooNLLVar.cxx
roofit/xroofit/src/xRooNode.cxx
roofit/xroofit/test/CMakeLists.txt
roofit/xroofit/test/xroofit_python.py

Backport #17124 and some other minor improvements.

[v643][RF] Update xroofit and add a first test for it

---

README/ReleaseNotes/v634/index.md

backport of https://github.com/root-project/root/pull/17166

[6.34] Small fix to 6.34 release notes

---

tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
tree/dataframe/inc/ROOT/RDF/RResultMap.hxx

Backport of https://github.com/root-project/root/pull/17159

[6.34] Fix wrong interaction between VariationsFor,Vary,GetMergeableValue

---

tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
tree/dataframe/inc/ROOT/RDF/RResultMap.hxx

Backport of https://github.com/root-project/root/pull/17159

[6.32] Fix wrong interaction between VariationsFor,Vary,GetMergeableValue

---

tutorials/analysis/dataframe/df105_WBosonAnalysis.py
tutorials/analysis/dataframe/df106_HiggsToFourLeptons.C
tutorials/analysis/dataframe/df106_HiggsToFourLeptons.py
tutorials/analysis/dataframe/df107_SingleTopAnalysis.py

Updates dataframe tutorials path, according to https://github.com/root-project/root/pull/17091

[skip-ci] Update dataframe tutorials path

---

.github/workflows/root-ci-config/build_root.py

Try cloning 6 times and sleep in between attempts and, at each attempt, increase linearly the sleep time.

[ci] Try cloning 6 times and sleep in between attempts

---

tutorials/analysis/unfold/TSVDUnfoldExample.C
tutorials/index.md

deletes extra items from the main index list, now moved to submodules' indices

[skip-ci][tutorials] Delete extra items

---

interpreter/cling/lib/Utils/SourceNormalization.cpp
interpreter/cling/test/Prompt/DontWrap.C

This PR fixes # https://its.cern.ch/jira/projects/ROOT/issues/ROOT-10780

[cling] Handle trailing return types at prompt

---

gui/webgui6/inc/TWebPainting.h
gui/webgui6/src/TWebCanvas.cxx
js/modules/base/BasePainter.mjs
js/modules/base/ObjectPainter.mjs
js/modules/base/base3d.mjs
js/modules/base/makepdf.mjs
js/modules/core.mjs
js/modules/draw/TWebPaintingPainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist/hist3d.mjs
tree/treeplayer/inc/TFileDrawMap.h
tree/treeplayer/src/TFileDrawMap.cxx

1. Provide context menu support, show proper class name in header
2. Handle object click events for such custom painted objects
3. In `TFileDrawMap` for web canvas use position of last event to get info
4. Use `TString` instead of direct `char[]` allocation in `TFileDrawMap`

Better support of `TFileDrawMap` in web canvas

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tefficiency.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/test/memory.py

Fixes https://github.com/root-project/root/issues/17222

Give ownership to C++ for objects with directory registration logic

---

tmva/pymva/src/MethodPyAdaBoost.cxx

BP of https://github.com/root-project/root/pull/17231

[6.30][tmva][pymva] Change default algorithm for AdaBoost to SAMME 

---

tmva/pymva/src/MethodPyAdaBoost.cxx

BP of  https://github.com/root-project/root/pull/17231

[6.34][tmva][pymva] Change default algorithm for AdaBoost to SAMME

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tefficiency.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/test/memory.py

[6.34]  Give ownership to C++ for objects with directory registration logic

---

tmva/pymva/src/MethodPyAdaBoost.cxx

BP of https://github.com/root-project/root/pull/17231

[6.32][tmva][pymva] Change default algorithm for AdaBoost to SAMME 

---

roofit/roofitcore/inc/RooVectorDataStore.h

Fix Assertion failed: can't dereference out of range vector iterator

Fix assertion failure in roofitcore

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_memory_utils.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tentrylist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_teventlist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tgraph2d.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py

[6.34][python] Factor memory utility functions in one module

---

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/test/ntuple_view.cxx

ALICE requested a backport of https://github.com/root-project/root/pull/17123 to facilitate RNTuple developments. We can consider only backporting `RNTupleViewBase::CreateBulk` for a narrower scope...

[ntuple] Support bulk-reading with views [v6.34]

---

tree/ntuple/v7/test/ntuple_evolution.cxx

These are currently not supported because changing the class hierarchy influences the field names in the base class, or some renaming cases would be confusing to users.
This completes the set of evolution tests that I originally came up with in August.

[ntuple] Add evolution tests for added, renamed, removed intermediate classes

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleReader.cxx

adds two overloads to `RNTupleReader::Open` that allow passing `RCreateModelOptions` to it. These options will be used by the internal `CreateModel` calls.

[ntuple] allow passing RCreateModelOptions to RNTupleReader::Open

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx

Fixes https://github.com/root-project/root/issues/17295
Credits go to @wlav

[core] Fix const detection in TClassEdit

---

tree/tree/src/InternalTreeUtils.cxx

Currently, in the creation of the friends to attach to the main chain to be processed in a MT task, if a friend was attached to a TVirtualIndex-derived instance, this needs to be rebuilt. Evidence in the past showed that just cloning was not enough because the cloned index could not appropriately probe the task-local friend chain afterwards due to a misconfigured connection with the branches. A call to `LoadTree(0)` before connecting the chain to the cloned index makes sure that the dataset schema is loaded and the probing can happen succesfully. In turn, this optimizes the task creation by avoiding the rebuilding of the chain index for every task.
FYI @TomasDado

[tree] Avoid rebuilding the TChainIndex in every MT task

---

roofit/roostats/inc/LinkDef.h

[RF] Remove unused sel rule for RooStats::ToyMCPayload

---

tutorials/CMakeLists.txt

[cmake] Remove race in RS demo tutorials input creation

---

tmva/sofie/inc/TMVA/ROperator_Tile.hxx

Fix the casting of the input repeats vector data of the Tile operator. The type of data should be int64_t and not size_t
The previous code had some issue when the size of size_t is 32 bits.
This PR should fix #17305

[tmva][sofie] Fix Tile operator

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx

[v634][ntuple] Fix storing RNTuples in subdirectories

---

tmva/sofie/inc/TMVA/ROperator_Tile.hxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

Backport in 6.34 of: 
#17314 
#17307

[tmva][sofie] BP of fixes for s390x and 32 bit architecture

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt
roofit/hs3/src/JSONFactories_RooFitCore.cxx

Backporting recent fixes to the 6.34 branch.

[v634] Backporting recent fixes

---

.github/workflows/root-ci-config/build_root.py

Solves the problem seen at: https://github.com/root-project/root/actions/runs/12508911424/job/34897691604

CI: remove stray parathensis.

---

.github/workflows/root-ci-config/build_root.py
.github/workflows/root-ci-config/build_utils.py

[ci] Do not print docker instructions if on macOS

---

interpreter/cling/tools/packaging/cpt.py

This PR fixes #406 mentioned in meta-issue list (https://github.com/root-project/cling/issues/406)

[cling-cpt] Added fixes for debian packaging [skip-ci]

---

hist/hist/src/TAxis.cxx
hist/hist/src/TH1.cxx

See https://root-forum.cern.ch/t/confusing-behavior-of-setrangeuser-and-fitting-range/58591

[skip-ci] clarify side effects of SetRange when fitting

---

roofit/roofit/test/testRooCrystalBall.cxx
roofit/roofitmore/CMakeLists.txt
roofit/roofitmore/inc/RooHypatia2.h
roofit/roofitmore/src/RooHypatia2.cxx
roofit/roofitmore/test/CMakeLists.txt
roofit/roofitmore/test/testRooHypatia2.cxx

To address https://github.com/root-project/root/issues/7254
The analytical integrals code in Hypatia2 is un-commented, except a few lines that are not needed.

[RF] Turn on the Analytical integrals for Hypatia2

---

.github/workflows/root-ci.yml

[ci] Temporarily disable arm64 linux builds

---

.github/workflows/root-ci.yml

until the builders are back.
BP of https://github.com/root-project/root/pull/17348

[634][ci] Temporarily disable arm64 linux builds

---

roofit/roofitcore/inc/RooFit/ModelConfig.h
roofit/roofitcore/src/ModelConfig.cxx
roofit/roostats/inc/RooStats/AsymptoticCalculator.h
roofit/roostats/inc/RooStats/CombinedCalculator.h
roofit/roostats/inc/RooStats/FeldmanCousins.h
roofit/roostats/inc/RooStats/FrequentistCalculator.h
roofit/roostats/inc/RooStats/HybridCalculator.h
roofit/roostats/inc/RooStats/HybridPlot.h
roofit/roostats/inc/RooStats/HypoTestCalculatorGeneric.h
roofit/roostats/inc/RooStats/HypoTestInverterPlot.h
roofit/roostats/inc/RooStats/NeymanConstruction.h
roofit/roostats/src/AsymptoticCalculator.cxx
roofit/roostats/test/CMakeLists.txt
roofit/roostats/test/testAsymptoticCalculator.cxx

Adds more options to generate asimov datasets by
- allowing to generate asimov datasets for RooMultiVarGaussian
- adding a new constructor to RooExtendPdf that allows to more easily extend pdfs to fixed nEvents
- improving error messages emitted by AsymptoticsCalculator when creating error messages

[RF] Asimov dataset generation for RooMultiVarGaussian with counting experiment

---

tree/ntupleutil/v7/inc/ROOT/RNTupleExporter.hxx
tree/ntupleutil/v7/src/RNTupleExporter.cxx
tree/ntupleutil/v7/test/ntuple_exporter.cxx

[ntuple] Exporter: add a way to blacklist/whitelist column types

---

tutorials/visualisation/image/rose_image.C

After the tutorials reorganisation this macro needs a change

[skip-ci] after the tutorials reorganisation this macro needs a change

---

documentation/doxygen_s3/Doxyfile
documentation/doxygen_s3/Makefile
documentation/doxygen_s3/makeinput.sh

Enable the full documentation build on s3

Make the full doc on s3

---

documentation/doxygen_s3/makeinput.sh

[skip-ci] make doc build shorter

---

documentation/doxygen_s3/Makefile

Makefile changes for s3 doc to avoid errors when the doc is short

[skip-ci] Makefile changes for s3 doc

---

.github/workflows/root-docs.yml

[skip-ci] the docdir was incorrect add debug messages

[skip-ci] the docdir was incorrect

---

documentation/doxygen_s3/Makefile

[skip-ci] avoid error with short doc.

[skip-ci] avoid error with short doc.

---

.github/workflows/root-docs.yml

[skip-ci] put back _TMP

---

.github/workflows/root-docs.yml

[skip-ci] add debug pwd and ls

[skip-ci] add debug pwd and ls

---

.github/workflows/root-docs.yml

[skip-ci] debug s3

---

gui/webgui6/src/TWebCanvas.cxx
js/changes.md
js/modules/core.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/THistPainter.mjs

When histogram axis configured like `h1->GetXaxis()->SetRange(0, 6);`,
JSROOT and TWebCanvas will display underflow and overflow bins.
Address issue #16976

[webcanv] let display underflow/overflow histogram bins

---

documentation/doxygen_s3/makeinput.sh

[skip-ci] Add more doc

---

documentation/doxygen_s3/Makefile

[skip-ci] restore the full Makefile

---

documentation/doxygen_s3/Makefile

do not generate the notebooks to see if that's what causes the problem.

[skip-ci] debug Makefile

---

documentation/doxygen_s3/Makefile
documentation/doxygen_s3/makeNotebooks.sh

add protection makeNotebooks.sh

[skip-ci] add protection makeNotebooks.sh

---

documentation/doxygen_s3/makeinput.sh

[skip-ci] full doc

---

tutorials/hist/index.md

Fixes broken link because of typo

[skip-ci] Fix typo

---

tmva/tmva/inc/TMVA/ROCCalc.h

Less risky alternative to #4685.

[TMVA] Specify ownership of histograms in the ROCCalc documentation

---

.github/workflows/root-ci.yml

The arm runners were re-registered.

Re-enable arm builds

---

tutorials/hist/hist010_TH1_two_scales.py

removes includes in a python tutorial

[skip-ci][tutorials] Remove includes in a python tutorial

---

documentation/doxygen_s3/makeinput.sh

[skip-ci] min doc

---

documentation/doxygen_s3/makeinput.sh

[skip-ci] add some tutorials in the doc

---

.github/workflows/root-docs-ci.yml

[skip-ci] add debug

---

CMakeLists.txt

* Support linking with mold>=2.32.0
This PR fixes #15473

Support linking with mold>=2.32.0

---

js/changes.md
js/modules/base/latex.mjs
js/modules/base/makepdf.mjs
js/modules/core.mjs
js/modules/draw.mjs
js/modules/draw/TGaxisPainter.mjs
js/modules/draw/TGraphPolarPainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/THistPainter.mjs

1. Fix - correctly position title according to gStyle->GetTitleAlign()
2. Fix - tooltips on TGraphPolar
3. Fix - use 'portrait' orientation for PDF pages where width smaller than height
4. Fix - font corruption after PDF generation
5. Fix - support drawing of `RooEllipse` class

[jsroot] 7.8.1 22/01/2025 [6.34]

---

tutorials/index.md

to give justice to the overhaul of the entire material.

[skip-ci][doc][nfc] Reorganise tutorials' index.md

---

roofit/roofit/inc/RooCrystalBall.h

Same reasoning as in commit bce142c from #12114.
Closes #17163.

[RF] Increase version number of RooCrystalBall

---

tutorials/CMakeLists.txt
tutorials/analysis/mp_processSelector.C
tutorials/legacy/multicore/mp104_processH1.C

Together with https://github.com/root-project/roottest/pull/1251

Fix location of h1analysis

---

.github/workflows/root-ci.yml

This reverts commit 14b36ff29cfe987788a3adacedc1676e5968c296.

Revert "[ci] Temporarily disable arm64 linux builds"

---

gui/webdisplay/inc/ROOT/RWebWindow.hxx
tutorials/hist/hist102_TH2_contour_list.C

fix warnings while building doc

[skip-ci] fix warnings while building doc

---

hist/spectrum/src/TSpectrum.cxx
hist/spectrum/src/TSpectrum2.cxx

spectrum tutorials have been moved to legacy

[skip-ci] spectrum tutorials have been moved

---

graf2d/gpadv7/inc/ROOT/RVirtualCanvasPainter.hxx
misc/minicern/src/cernlib.c
tmva/tmva/inc/TMVA/RTensor.hxx

Backport missing includes for compilation with gcc-15

---

gui/cefdisplay/CMakeLists.txt
main/CMakeLists.txt
roofit/histfactory/CMakeLists.txt
rootx/CMakeLists.txt

Fixes https://github.com/root-project/root/issues/11448

[cmake] Don't export all executables

---

.github/workflows/root-docs-ci.yml

To fix this:
https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz       
thanks @linev

[skip-ci] use doxygen 1.12

---

.github/workflows/root-docs-ci.yml

try to install doxygen using dnf to have a more coherent picture of the softwares installed

[skip-ci] install doxygen using dnf

---

.github/workflows/root-docs-ci.yml

Build doxygen from sources. This allows us to choose the version we want.

[skip-ci] build doxygen from sources

---

.github/workflows/root-docs-ci.yml

Installing from sources did not work

[skip-ci] go back to doxygen 10

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
bindings/pyroot/pythonizations/test/string_view.py

Fixes #17497 
@guitargeek These changes, taken from https://github.com/wlav/cppyy-backend/blob/master/clingwrapper/src/clingwrapper.cxx , fix the reproducer at the linked issue. Let's see what the rest of the CI says. Then we may want to discuss how to incorporate these changes into the repository.

Avoid infinite recursion in implicit conversion 

---

documentation/doxygen/makeNotebooks.sh
documentation/doxygen/parallelNotebooks.py
documentation/users-guide/Graphics.md
documentation/users-guide/Histograms.md
hist/histpainter/doc/index.md
test/stressGUI.cxx
tutorials/demos.py
tutorials/hist/hist006_TH1_bar_charts.C

Fixes required after some tutorials have been renamed.

[skip-ci] fixes needed after tutorials renaming

---

documentation/doxygen/Doxyfile

This Pull request excludes directories not needed in the reference guide

[skip-ci] Exclude directories not needed in the reference guide

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/rdataframe_misc.py

This PR is related to https://github.com/root-project/root/issues/17485, fixing the first issue reported on it.

[df] Add Python test with empty list of filenames

---

js/changes.md
js/modules/core.mjs
js/modules/d3.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/io.mjs
js/modules/three.mjs
js/modules/three_addons.mjs
js/modules/tree.mjs
ui5/eve7/eve.mjs

Add directly method for OrbitsControl only in eve7 - the only place where it used.

[jsroot] update with three.js r173

---

core/base/src/TStyle.cxx

Candle marker width Initialisation

[skip-ci] Candle marker width Initialisation

---

io/io/src/TFile.cxx
io/io/test/TFileTests.cxx

https://github.com/root-project/root/pull/17542#issuecomment-2631958782

[BP6.32] [io] Apply TFile::k630forwardCompatibility when creating new file if set in rootrc

---

io/io/src/TFile.cxx
io/io/test/TFileTests.cxx

https://github.com/root-project/root/pull/17542#issuecomment-2631958782

[BP6.34] [io] Apply TFile::k630forwardCompatibility when creating new file if set in rootrc

---

geom/geom/src/TGeoArb8.cxx
geom/geom/src/TGeoBBox.cxx
geom/geom/src/TGeoCone.cxx
geom/geom/src/TGeoEltu.cxx
geom/geom/src/TGeoHype.cxx
geom/geom/src/TGeoPara.cxx
geom/geom/src/TGeoParaboloid.cxx
geom/geom/src/TGeoPcon.cxx
geom/geom/src/TGeoPgon.cxx
geom/geom/src/TGeoSphere.cxx
geom/geom/src/TGeoTorus.cxx
geom/geom/src/TGeoTrd1.cxx
geom/geom/src/TGeoTrd2.cxx
geom/geom/src/TGeoTube.cxx
geom/geom/src/TGeoXtru.cxx

Add protections to the geom examples.

[skip-ci] Add protection in the shapes' examples

---

geom/geom/src/TGeoParaboloid.cxx

[skip-ci] more protection in a geom example

---

io/io/src/TFileMerger.cxx

Fixes first part of https://its.cern.ch/jira/browse/ROOT-5820

[io] Do not copy whole single file if trees should not be merged

---

roofit/xroofit/inc/RooFit/xRooFit/xRooNLLVar.h
roofit/xroofit/inc/RooFit/xRooFit/xRooNode.h
roofit/xroofit/src/Asymptotics.cxx
roofit/xroofit/src/xRooFit.cxx
roofit/xroofit/src/xRooHypoSpace.cxx
roofit/xroofit/src/xRooNLLVar.cxx
roofit/xroofit/src/xRooNode.cxx
roofit/xroofit/test/xroofit_python.py

Updates xroofit and slightly improves the coverage of the test/example

xroofit update

---

core/base/src/TUrl.cxx
core/base/test/CMakeLists.txt
core/base/test/TUrlTest.cxx

Fixes second part of https://its.cern.ch/jira/browse/ROOT-5820

[core] accept input from file.GetPath() in TUrl

---

tutorials/visualisation/graphics/AtlasExample.C
tutorials/visualisation/graphics/pstable.C
tutorials/visualisation/graphics/psview.C
tutorials/visualisation/graphics/splines_test.C

remove sprintf
`feynman.C` was moved

[skip-ci] remove sprintf

---

core/base/inc/TSystem.h
core/base/src/TSystem.cxx
core/unix/inc/TUnixSystem.h
core/unix/src/TUnixSystem.cxx
core/winnt/inc/TWinNTSystem.h
core/winnt/src/TWinNTSystem.cxx
net/net/CMakeLists.txt
net/net/inc/TParallelMergingFile.h
net/net/inc/TServerSocket.h
net/net/inc/TSocket.h
net/net/src/TParallelMergingFile.cxx
net/net/src/TServerSocket.cxx
net/net/test/CMakeLists.txt
net/net/test/nettests.cxx
tutorials/net/parallelMergeClient.C
tutorials/net/parallelMergeServer.C

BP of https://github.com/root-project/root/pull/17599 and https://github.com/root-project/root/pull/17600

[BP][632]Sockets and File Merger

---

core/base/inc/TSystem.h
core/base/src/TSystem.cxx
core/unix/inc/TUnixSystem.h
core/unix/src/TUnixSystem.cxx
core/winnt/inc/TWinNTSystem.h
core/winnt/src/TWinNTSystem.cxx
net/net/CMakeLists.txt
net/net/inc/TParallelMergingFile.h
net/net/inc/TServerSocket.h
net/net/inc/TSocket.h
net/net/src/TParallelMergingFile.cxx
net/net/src/TServerSocket.cxx
net/net/test/CMakeLists.txt
net/net/test/nettests.cxx
tutorials/net/parallelMergeClient.C
tutorials/net/parallelMergeServer.C

BP of https://github.com/root-project/root/pull/17599 and https://github.com/root-project/root/pull/17600

[634][BP] Sockets and file merger

---

tutorials/visualisation/graphs/index.md

[skip-ci] fix malformed table

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

Fixes https://github.com/root-project/root/issues/17658
with the changes suggested by @TomHadavizadeh

[RF] avoid infinities in power with high N in cbshape

---

net/net/test/nettests.cxx

BP of https://github.com/root-project/root/pull/17670

[BP][632] [net] TServerSocket: let ROOT find a port for the test

---

net/net/test/nettests.cxx

BP of https://github.com/root-project/root/pull/17670

[BP][634] [net] TServerSocket: let ROOT find a port for the test

---

tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RLoopManager.cxx

Misc changes, see commits for description.

RLoopManager misc improvements

---

tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx

[ntuple] Deduplicate column representatives in RFieldBase

---

tree/tree/src/TBranch.cxx
tree/tree/src/TTree.cxx
tutorials/io/tree/dictionary/CMakeLists.txt

Fixes https://github.com/root-project/root/issues/14583

[skip-ci] more complete SetMakeClass docu

---

core/cont/inc/TCollection.h
core/cont/src/TCollection.cxx
core/cont/src/TIterator.cxx
core/cont/src/TList.cxx

Fixes https://github.com/root-project/root/issues/8421

[skip-ci] improve iterator and casting documentation

---

.github/workflows/root-docs-ci.yml

[ci] Do not trigger doc gen on forks

---

.github/workflows/root-docs-ci.yml

BP of https://github.com/root-project/root/pull/17716
fixes #17715

[BP][634][ci] Do not trigger doc gen on forks

---

.github/workflows/root-docs-ci.yml

BP of https://github.com/root-project/root/pull/17716
fixes https://github.com/root-project/root/issues/17715

[skip-ci][BP][632][ci] Do not trigger doc gen on forks 

---

README/ReleaseNotes/v636/index.md

See 
https://github.com/root-project/root/pull/17708#issuecomment-2657707357

[skip-ci] mention deleted Ttreeformula default constructor

---

bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
graf2d/gpad/src/TPad.cxx

@ellert thanks for your good work! I hope with this I'm backporting everything related to gcc-15. Let me know if I overlooked something.
Fixes for #17456

Backport gcc-15 fixes for #17456

---

core/gui/src/TBrowser.cxx

Avoid creation of `TG` classes for web case

Do not create context menu for web-based `TBrowser`

---

gui/gui/src/TGFileBrowser.cxx

Some elements are not deleted correctly.

Fix memory leaks in TGFileBrowser

---

hist/hist/inc/TGraphSmooth.h
hist/hist/inc/TKDE.h

Copy constructor and assign operator for  `TGraphSmooth` and `TKDE`

[hist] Mark not implemented methods as delete

---

tree/tree/src/TTree.cxx
tree/tree/test/TTreeRegressions.cxx

This explores the alternative way suggested by @pcanal in https://github.com/root-project/root/pull/17724
https://its.cern.ch/jira/browse/ROOT-7926

[Tree] Account correctly for top branches v2

---

hist/histpainter/src/THistPainter.cxx

Always paint relative to pad center
Angle range corresponds to pad user axis X range
Radius range corresponds to pad user axis Y range
When zooming is performed, range changes and
therefore less number of bins are drawn. But
painting always remains in the center.
With such approach one always can identify bin -
no any TCrown painting with "negative" radius performed.
Produced image matches to "lego pol" painting.
Demo: [pol.cxx.txt](https://github.com/user-attachments/files/18908366/pol.cxx.txt)

Change implementation of "pol" painting for TH2

---

tree/ntupleutil/v7/src/RNTupleInspector.cxx

[RNTuple] Update RNTupleInspector.cxx

---

tree/dataframe/test/datasource_ntuple.cxx

The test for alternative column types was accidentally defined inside the `R__USE_IMT` ifdef, but should be tested in all cases.

[ntuple] Move `RNTupleDSTest.AlternativeColumnTypes` test outside IMT macro

---

tree/dataframe/test/datasource_ntuple.cxx

Adds a test that defines a new column by modifying the values of an existing value in-place (i.e., by passing a non-const ref to `Define`) and subsequently using this new column. To mirror the behaviour of TTree-based dataframes, we expect the original column to be modified iff the modified column is also (indirectly) accessed in the action of the event loop. If only the original column is used in the action, its values shouldn't be modified. Vice-versa, if only the columns defined from this original column are used, their values (of course) should be modified.
Originally suggested by @vepadulano in https://github.com/root-project/root/pull/17749#discussion_r1967328154.

[DF] Add test for modified input values

---

tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx

With the removal of the `RCollectionField` (#16585), all collections can now be treated the same in `RNTupleDS::AddField`. This change removes the addition of a redundant cardinality field, and fixes the column name of untyped collections that contain untyped records where before, it would include the field name of the inner record field in the collection.

[ntuple][DF] Update handling of untyped collections in `RNTupleDS`

---

core/base/src/TDirectory.cxx
io/io/src/TDirectoryFile.cxx
io/io/test/TFileTests.cxx

Fixes https://github.com/root-project/root/issues/17824
Analogous to https://github.com/root-project/root/pull/5264

[io] mkdir should return created subdir

---

gui/guihtml/src/TGHtmlUri.cxx
hist/hist/src/TFormula_v5.cxx

Fix compiler warnings

---

tutorials/visualisation/graphics/greyscale.C

greyscale.C was in the wrong group

[skip-ci] greyscale.C was in the wrong group

---

core/base/inc/TObject.h
core/base/src/TObject.cxx
graf2d/graf/src/TCutG.cxx
graf2d/graf/src/TPolyLine.cxx
hist/hist/src/TGraph.cxx
hist/hist/src/TGraphAsymmErrors.cxx
hist/hist/src/TGraphBentErrors.cxx
hist/hist/src/TGraphErrors.cxx
hist/hist/src/TPolyMarker.cxx

Add extra argument to SavePrimitiveArray for better formatting of produced macro

Use SavePrimitiveArray for TCutG and TPolyLine

---

roofit/roofit/src/RooCrystalBall.cxx

analogous to https://github.com/root-project/root/pull/17660

[RF] numerical stabilities in rooCB

---

tree/ntuple/v7/test/ntuple_processor.cxx

We previously only pretended the join was unaligned by providing a join key. To further strengthen the test, now a join between two actual unaligned ntuples is used.

[ntuple] Use actual unaligned ntuples in test for chained joins

---

math/mathcore/inc/Fit/FitConfig.h
math/mathcore/inc/Fit/Fitter.h
math/mathcore/inc/Math/Minimizer.h
math/mathcore/inc/Math/MinimizerOptions.h

See https://root-forum.cern.ch/t/root-fitter-fails-on-linear-fitting/62966/3

[skip-ci] improve and sync Fitter docu

---

tree/tree/src/TTree.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-5729

[skip-ci] Clarify GetEntry behavior in combination with all branches disabled

---

.github/workflows/root-rn-ci.yml

and not only to S3 to allow them to be served by WebEOS.
Thanks to @amadio for being instrumental to the success of this endeavour.

[skip-ci][ci] Copy the release notes also to EOS

---

documentation/doxygen/modifyNamespacesWebpage.sh
tutorials/hist/hist000_TH1_first.C
tutorials/hist/hist000_TH1_first.py
tutorials/io/tree/tree500_cernbuild.C

Better version of modifyNamespacesWebpage.sh. The previous was not precise enough.

[skip-ci]  better version of modifyNamespacesWebpage.sh

---

tmva/tmva/src/DataLoader.cxx
tmva/tmva/test/rreader.cxx

Tests https://its.cern.ch/jira/browse/ROOT-9833
That issue was inadvertently fixed by https://github.com/root-project/root/pull/17031

[tmva] fix spacing in error message and add test

---

documentation/doxygen/makeinput.sh

[doc] Block the generation of doc for the tutorials

---

requirements.txt

- Add the uhi dependency to the requirements, needed for running uhi related tests

Add uhi dependency needed for uhi related tests

---

tree/treeplayer/test/ttreereader_friends.cxx

Fixes/Tests https://its.cern.ch/jira/browse/ROOT-9886

[test] for TTreeReader loads wrong entry from chain friend

---

hist/histpainter/src/TPaletteAxis.cxx
tree/treeviewer/src/TParallelCoord.cxx
tree/treeviewer/src/TParallelCoordVar.cxx

One need to use provided methods to correctly store colors

Properly store colors in palette, attributes in TParallelCoord

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
js/changes.md
js/modules/base/FontHandler.mjs
js/modules/core.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TPadPainter.mjs

Fixes issue reported in the forum  https://root-forum.cern.ch/t/63097/
Use latest JSROOT as fallback link in Jupyter Lab

Update JSROOT, fix hidden canvas in Jupyter [6.34]

---

tree/dataframe/CMakeLists.txt
tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx
tree/dataframe/inc/ROOT/RDF/RDefaultValueFor.hxx
tree/dataframe/inc/ROOT/RDF/RFilterWithMissingValues.hxx
tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
tree/dataframe/src/RDFColumnReaderUtils.cxx
tree/dataframe/src/RTreeColumnReader.cxx
tree/dataframe/test/dataframe_regression.cxx
tree/dataframe/test/dataframe_snapshot.cxx

Part 5 of N for https://github.com/root-project/root/pull/17895
Sibling PR in roottest at https://github.com/root-project/roottest/pull/1272

Remove typed TTree column readers

---

.github/workflows/root-docs-ci.yml

Remove incremental to build ROOT

[skip-ci] Remove incremental to build ROOT

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Backports of:
* https://github.com/root-project/root/pull/17880
* https://github.com/root-project/root/pull/17888

[v634][cmake] Build Clad with one core only when needed

---

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py

Backport of the essential commit from:
* https://github.com/root-project/root/pull/17972
We need it, otherwise we get red nightlies with the updated docker images.

[v632] Fix numba tests with Python 3.13+

---

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py

Backport of the essential commit from:
* https://github.com/root-project/root/pull/17972
We need it, otherwise we get red nightlies with the updated docker images.

[v634] Fix numba tests with Python 3.13+

---

math/minuit2/inc/Minuit2/MinimumParameters.h
math/minuit2/inc/Minuit2/MinuitParameter.h
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnApplication.cxx
math/minuit2/src/MnContours.cxx
math/minuit2/src/MnFunctionCross.cxx
tutorials/roofit/roofit/rf601_intminuit.C

This PR improve the search for contour points when contour touches the parameter limits. 
Improve also debugging and simplify the case when all parameters are fixed

[Minuit2] Improve finding contour points when parameters are at limits

---

tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_test.hxx

[ntuple] Move RColumn(Index|Switch) out of Experimental

---

bindings/jupyroot/CMakeLists.txt

@guitargeek could you check if this fixes the problem?
Fix #17859.

[pyroot] Move JupyROOT files at build time.

---

tree/tree/src/TChain.cxx
tree/tree/src/TTree.cxx
tree/tree/test/TChainRegressions.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-7855

[tree] CloneTree should clone even if zero entries in chain

---

tutorials/CMakeLists.txt

- tutorial-dataframe-df014_CSVDataSource
- tutorial-dataframe-df015_LazyDataSource
- tutorial-hist-th2polyUSA

[tut] Impose dependency on python tutorials for downloading the inputs

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_storage.cxx

Moves `RColumn` out of Experimental.

[ntuple] Move RColumn out of Experimental

---

core/metacling/src/TClingCallFunc.cxx

As part of our efforts in the area of cppyy and libInterOp we need to port CallFunc. These parts help code reuse and I'd prefer to keep in sync the to the two versions.

Simplify CallFunc. NFC

---

hist/hist/src/TFormula.cxx

1. Modified the doxygen to look better.
Improved the doxygen docs for the HandlePolN function.

[skip-ci] Update TFormula.cxx for doxygen

---

documentation/doxygen/Doxyfile

[skip-ci] put back the ML tutorials.

---

bindings/pyroot/cppyy/CPyCppyy/pyproject.toml
bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPClassMethod.h
bindings/pyroot/cppyy/CPyCppyy/src/CPPEnum.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPFunction.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPFunction.h
bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/DeclareConverters.h
bindings/pyroot/cppyy/CPyCppyy/src/DeclareExecutors.h
bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.cxx
bindings/pyroot/cppyy/CPyCppyy/src/LowLevelViews.h
bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
bindings/pyroot/cppyy/cppyy/README.rst
bindings/pyroot/cppyy/cppyy/doc/source/changelog.rst
bindings/pyroot/cppyy/cppyy/doc/source/cppyy_features_header.rst
bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py
bindings/pyroot/cppyy/cppyy/test/test_fragile.py
bindings/pyroot/cppyy/cppyy/test/test_pythonify.py
bindings/pyroot/cppyy/cppyy/test/test_regression.py
bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
bindings/pyroot/cppyy/sync-upstream

Sync `cppyy` and `CPyCppyy` with current master branches to start validating recent fixes in cppyy for the next ROOT release.

[Python] Sync `cppyy` and `CPyCppyy` with current master branches

---

gui/browsable/src/RFieldProvider.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RFieldVisitor.cxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/test/ntuple_test.hxx

And move its child classes to Internal.

[ntuple] Move RFieldVisitor out of Experimental

---

js/changes.md
js/modules/base/latex.mjs
js/modules/core.mjs
js/modules/io.mjs

1. Fix - latex super-script without leading symbol, https://root-forum.cern.ch/t/63114/
2. Fix - correctly read `std::pair<>` without dictionary, https://root-forum.cern.ch/t/63114/

[jsroot] 7.8.x 12/03/2025 [6.34]

---

.github/workflows/root-docs-ci.yml

make root-docs-ci.yml similar to the one in 6.34 which is working

[skip-ci] make root-docs-ci.yml similar to the one in 6.34 

---

.github/workflows/root-docs-ci.yml

add some debugging in the doxygen step

[skip-ci] add some debugging in the doxygen step

---

roofit/roofitcore/src/RooCurve.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-9204

[RF] average should interpolate if xFirst==xLast

---

.github/workflows/root-docs-ci.yml

[skip-ci] previous version did not worrk

---

.github/workflows/root-docs-ci.yml

[skip-ci] put back the make command

---

test/stressGeometry.cxx

(cherry picked from commit a8a879ce252e45405452db38d9178c7883582a7d)

[test][BP 6.30] Fetch the geometries from EOS and not from the website

---

core/metacling/src/TClingCallFunc.cxx

These improvements are based on https://github.com/vgvassilev/root/tree/simplify-cf-tors and latest changes in JitCall

Simplify TClingCallFunc code based on InterOp's JitCall

---

tree/dataframe/src/RDataFrame.cxx

Improves docu of scrambling behavior, while a solution of https://github.com/root-project/root/issues/18014 is investigated.

[skip-ci] be more explicit on scrambling behavior of RDF with MT

---

config/thisroot.sh

revert https://github.com/root-project/root/pull/17970

[skip-ci] revert the change in config/thisroot.sh

---

hist/hist/inc/TF1.h
hist/hist/src/TF1.cxx

Closes https://its.cern.ch/jira/browse/ROOT-6874
Credit goes to @jasondet

TF1 EvalUncertainty function

---

.github/workflows/root-docs-ci.yml
documentation/doxygen/Doxyfile

Turn off the Machine Learning tutorials because of many TSring errors message while building the doc.

[skip-ci] Turn off the Machine Learning tutorials.

---

.github/workflows/root-docs-ci.yml

[skip-ci] Remove more debugging lines

---

hist/hist/src/TH1.cxx

Backport of:
* https://github.com/root-project/root/pull/18099

[v634][hist] fix bug in SmoothArray

---

core/meta/src/TClass.cxx

BP of https://github.com/root-project/root/pull/17994

[BP 634] Fix spurrious auto parsing when looking up a TClass

---

tree/treeplayer/src/TSelectorDraw.cxx
tree/treeplayer/test/regressions.cxx

Fixes https://github.com/root-project/root/issues/18066

[tree] Fix column count when ternary operator

---

gui/browserv7/src/RBrowser.cxx
gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx
ui5/canv/view/Canvas.view.xml

Backport of https://github.com/root-project/root/pull/18109

[webcanv] fix TCanvas::Update() problem for closed canvas [6.34]

---

roofit/roofitcore/inc/RooAICRegistry.h
roofit/roofitcore/src/RooAICRegistry.cxx
roofit/roofitcore/src/RooAbsCachedPdf.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-10579

[RF] prevent crash in analyticalIntegralWN

---

core/metacling/src/TClingDataMemberInfo.cxx
core/metacling/src/TClingTypeInfo.cxx

Use GetSizeOfType from CppInterOp.

[metacling] Use GetSizeOfType from CppInterOp

---

tutorials/CMakeLists.txt
tutorials/analysis/index.md
tutorials/analysis/parallel/index.md
tutorials/analysis/parallel/mp_parallelHistoFill.C
tutorials/analysis/parallel/mp_processSelector.C
tutorials/analysis/parallel/mt_fillHistos.C
tutorials/analysis/parallel/mt_parallelHistoFill.C
tutorials/analysis/parallel/mtbb_fillHistos.C
tutorials/analysis/parallel/mtbb_parallelHistoFill.C

- Creates a new Parallel subtopic in the analysis tutorials
- Fixed comments in the parallel analysis tutorial files

[tutorials][doc][skip-ci] Improve parallel analysis docs

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
js/build/jsroot.js
js/changes.md
js/modules/base/latex.mjs
js/modules/core.mjs
js/modules/draw.mjs
js/modules/io.mjs

1. Fix - latex super-script without leading symbol, https://root-forum.cern.ch/t/63114/
2. Fix - correctly read std::pair<> without dictionary, https://root-forum.cern.ch/t/63114/
3. Fix - chromium in mobile device emulation mode, https://root-forum.cern.ch/t/63201/
4. Fix - files remap for root.cern site using fallback URL

[jsroot] version 7.7.6 26/03/2025 [6.32]

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
js/changes.md
js/modules/core.mjs
js/modules/hist2d/TScatterPainter.mjs
js/modules/io.mjs

1. Fix - repair small bug in `TF3` painting
2. Fix - latex super-script without leading symbol, https://root-forum.cern.ch/t/63114/
3. Fix - correctly read std::pair<> without dictionary, https://root-forum.cern.ch/t/63114/
4. Fix - chromium in mobile device emulation mode, https://root-forum.cern.ch/t/63201/
5. Fix - files remap for root.cern site using fallback URL

[jsroot] version 7.8.2 [6.34]

---

tree/ntuple/v7/inc/ROOT/REntry.hxx

This PR updates the documentation of the `REntry` class.

[skip-ci][ntuple] update REntry's documentation

---

tutorials/visualisation/index.md

alphabetically orders categories under the visualization section

[skip-ci][tutorial] Alphabetically order categories

---

tutorials/math/fit/index.md

Add tables for grouping the fit tutorials

[skip-ci][tutorials] Enhance fit tutorial presentation

---

tutorials/io/index.md
tutorials/math/index.md

The high level descriptions of io and math categories improvements - some typo fixing and improvement to organisation.

[skip-ci][tutorials] Further improve index files in io and math categories

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx

This PR updates the documentation of the `RNTupleReader` class.

[skip-ci][ntuple] update RNTupleReader's documentation

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx

Also make `RFieldInfo` members `private` and mark classes as `final`.

[ntuple] Revise documentation in RNTupleDescriptor.hxx

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx

The internal `CPyCppyy::CPPMethod::SetPyError_()` method currently handles three different cases related to method calls:
1. When there is something wrong with the arguments or any other problem when setting up the function call, `CPyCppyy` itself will set a **new error**. Example usage in [VerifyArgCount_](https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx#L75)..
2. Adding context information when dealing with a **C++ exception** when [calling the function](https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx#L981).
3. Dealing with a **Python error** when executing the function. In this case, the current logic resets the exception to something that looks like the C++ exception, only mentioning the …

[CPyCppyy] Preserve Python errors when executing C++ function

---

hist/hist/inc/TF1.h
hist/hist/src/TF1.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-7322

[hist] For consistency, provide also GetParError(name), and constify some functions

---

tree/tree/src/TTree.cxx
tree/tree/test/TTreeRegressions.cxx

Fixes https://github.com/root-project/root/issues/9319

[tree] count non-full clusters when reporting

---

hist/hist/src/TGraphMultiErrors.cxx

Fixes https://github.com/root-project/root/issues/9335

[skip-ci] improve TGraphMultiErrors docu

---

main/python/cmdLineUtils.py

Fixes https://github.com/root-project/root/issues/11675

[rootls] prevent nullptr access

---

tree/tree/test/TChainRegressions.cxx

Tests https://its.cern.ch/jira/browse/ROOT-8112

[test] TChain AddFile should work with non-standard extensions

---

tree/tree/src/TTreeCloner.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-5137

[tree] check for return values in WriteBaskets

---

hist/histpainter/src/THistPainter.cxx

Fixes https://github.com/root-project/root/issues/12497

[hist] fix red highlight box in log mode

---

documentation/users-guide/WebDisplay.md
geom/webviewer/src/RGeomViewer.cxx

Do not use `RDirectory::Heap()`.
Just create shared_ptr variable outside of function scope
Use "\n" instead of std::endl
Update `WebDisplay.md` manual, need to be moved later to documentation

Modify RGeomViewer::SaveAsMacro()

---

roofit/roofitcore/src/RooAbsPdf.cxx

See https://github.com/root-project/root/issues/17344 (partial fix)

[skip-ci] cpu backend specify it's single threaded

---

tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_project.cxx

Setting a projected field to quantized or truncated works and read proper data but it doesn't do what one would probably expect. The projected field can correctly read values from any fields that can be read as float, but the value range and bits of precision set on the projected field are silently ignored (since they only make sense for physical columns that are actually stored on disk). To reduce confusion, we now emit a warning if a user tries to call AddProjectedField with a quantized or truncated field.

[ntuple] Add tests and a warning for projected Real32(Quant|Trunc)

---

graf2d/asimage/README
graf2d/asimage/src/libAfterImage/libpng/pngpriv.h

Thanks to @ktf (ALICE) for this fix.

[graf] Patch libAsimage: fp.h is now part of math.h

---

interpreter/cling/README.md
interpreter/cling/www/index.html
interpreter/cling/www/jupyter.html

Clarify standalone and LLVM-integrated build methods, along with usage instructions. Improved installation steps to ensure successful execution.
Clarify the distinct build processes for standalone Cling and Cling integrated with LLVM, addressing common user errors related to missing dependencies and incorrect build commands. Standalone Cling's header file locations differ from LLVM-integrated builds, causing potential file not found.
```shell
$ ./bin/cling                   
input_line_2:1:10: fatal error: 'cling/Interpreter/RuntimeUniverse.h' file not found
#include <cling/Interpreter/RuntimeUniverse.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             * …
```

[skip-CI][cling] Refine build and usage guide

---

hist/hist/inc/TH1.h
hist/hist/src/TH1.cxx

Fixes https://github.com/root-project/root/issues/8951

[hist] function to get sum of weights including under/overflows

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

Clang may emit calls to compiler-rt symbols such as __divdc3 for
std::complex<T> division. These may not be resolved during JIT'ing
on macOS when using Cling.
This patch forward-declares the relevant symbols and explicitly
injects them into the JIT symbol table
Similar to: https://github.com/root-project/root/commit/4b6075b

[cling][JIT] Inject compiler-rt complex division symbols on  macOS

---

graf2d/asimage/src/libAfterImage/libpng/pngpriv.h

following https://github.com/pnggroup/libpng/commit/893b8113f04d408cc6177c6de19c9889a48faa24
@devajithvs fyi

Properly format the preprocessor if clause

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

[cling][JIT] Adapt compiler-rt changes for LLVM16

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

BP of https://github.com/root-project/root/pull/18269

[BP][6.34][cppyy] Disable warnings for invalid function casts

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

BP of https://github.com/root-project/root/pull/18269

[BP][6.32][cppyy] Disable warnings for invalid function casts

---

bindings/pyroot/pythonizations/test/memory.py

Backport of https://github.com/root-project/root/pull/17960

Remove fragile test

---

tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

We were creating new output column ids even when doing incremental merging, which may end up associating the wrong output column to an input column that is already present in the destination. By prefilling the column id map with the destination columns we avoid this problem.
This PR fixes [this use case](https://gitlab.cern.ch/amete/rootparallelmerger/-/blob/master-rntuple-prototype) by @amete

[ntuple] Merger: fix improper output column id assignment in incremental merging

---

tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx

Fixes https://github.com/root-project/root/issues/18251

[ntuple] more informative error message on failed open RMiniFile

---

io/io/src/TBufferJSON.cxx

Backport of https://github.com/root-project/root/pull/18266

[Json] check dictionary of std::map [6.34]

---

io/io/src/TBufferJSON.cxx

Backport of https://github.com/root-project/root/pull/18266

[Json] check dictionary for std::map [6.32]

---

bindings/experimental/distrdf/python/DistRDF/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_facade.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py
tree/dataframe/src/RDataFrame.cxx

This feature was requested on multiple occasions (also on the forum) and it is now added to distributed RDataFrame. 
The test is added in roottest PR here: https://github.com/root-project/roottest/pull/1296

[df] Add FromSpec functionality to distributed RDF

---

roofit/roostats/inc/RooStats/MCMCInterval.h
roofit/roostats/src/MCMCInterval.cxx

Use smart pointers in `RooStats::MCMCInterval` for more memory safety. Also avoid a leaking `RooArgList` and specify in the documentation that one of the setter functions takes ownership of the argument.

[RF] Use smart pointers in `RooStats::MCMCInterval`

---

net/net/inc/TSQLStatement.h
net/net/src/TSQLStatement.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-10553

[skip-ci] Document memory management convention of TSQLStatement::GetBinary API

---

graf2d/x11ttf/src/TGX11TTF.cxx
gui/browsable/src/RGroup.cxx
gui/browsable/src/RNTupleBrowseProvider.cxx
gui/browsable/src/RSysFile.cxx
gui/browsable/src/TBranchBrowseProvider.cxx
gui/browsable/src/TDirectoryElement.cxx
gui/browsable/src/TObjectElement.cxx
gui/browserv7/src/RBrowser.cxx
gui/browserv7/src/RBrowserGeomWidget.cxx
gui/browserv7/src/RBrowserTCanvasWidget.cxx
gui/browserv7/src/RBrowserTreeWidget.cxx
gui/canvaspainter/src/RCanvasPainter.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-8302

[gui,graf][nfc] apply clang-tidy fixit modernize-use-override

---

core/base/src/TSystem.cxx
gui/sessionviewer/src/TSessionDialogs.cxx
io/io/src/TFile.cxx
io/io/src/TFilePrefetch.cxx
proof/proof/src/TProofLite.cxx
proof/proofbench/src/TProofBench.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
test/stressProof.cxx

Fixes https://github.com/root-project/root/issues/18329

[RF][io][core][gui][proof] fix memleak after openDirectory

---

tree/tree/inc/TLeafObject.h
tree/tree/test/TTreeRegressions.cxx

Fixes https://github.com/root-project/root/issues/12537

[tree] prevent nullptr access in TLeafObject

---

tree/treeplayer/src/TTreeFormula.cxx
tree/treeplayer/test/regressions.cxx

This explores a variation of https://github.com/root-project/root/pull/17707#issuecomment-2662281919 homogeneizing checks
Fixes https://its.cern.ch/jira/browse/ROOT-4012
Regression since https://github.com/root-project/root/commit/bfbfe8783d0a216e8efff5f4aaff991bdba47563

[tree] TTree::SetAlias() properly interpret the constant v2

---

core/base/src/TQConnection.cxx
core/base/src/TQObject.cxx
core/base/src/TTimer.cxx
core/dictgen/src/rootcling_impl.cxx
core/gui/src/TBrowser.cxx
core/meta/src/TClass.cxx
core/textinput/src/Getline.cxx
tree/dataframe/src/RNTupleDS.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-8302

[core,tree][nfc] apply clang-tidy fixit modernize-use-override

---

interpreter/cling/lib/Interpreter/AutoSynthesizer.h
interpreter/cling/lib/Interpreter/DeclCollector.h
interpreter/cling/lib/Interpreter/DeclExtractor.h
interpreter/cling/lib/Interpreter/DynamicLookup.cpp
interpreter/cling/lib/Interpreter/DynamicLookup.h
interpreter/cling/lib/Interpreter/ExternalInterpreterSource.cpp
interpreter/cling/lib/Interpreter/ExternalInterpreterSource.h
interpreter/cling/lib/Interpreter/IncrementalParser.cpp
interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp
interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.h
interpreter/cling/lib/Interpreter/PerfJITEventListener.cpp
interpreter/cling/lib/Interpreter/ValueExtractionSynthesizer.h
interpreter/cling/lib/Interpreter/ValuePrinterSynthesizer.h

Fixes https://its.cern.ch/jira/browse/ROOT-8302

[cling][nfc] apply clang-tidy fixit modernize-use-override

---

bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/PyException.h
bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/pythonizations/inc/TPyDispatcher.h

Fixes https://its.cern.ch/jira/browse/ROOT-8302
Upstream: https://github.com/wlav/CPyCppyy/pull/49

[pyroot][nfc] apply clang-tidy fixit modernize-use-override

---

tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/src/SOFIE_common.cxx

Some small improvements for the AD support with Clad that factorize from the remaining development.

[TMVA][SOFIE] Small improvements necessary for AD support

---

builtins/xrootd/CMakeLists.txt

[cmake] Update XRootD version to 5.8.0

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
bindings/pyroot/pythonizations/test/rvec_asrvec.py
bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py

Fixes https://github.com/root-project/root/issues/18365

[pyroot] add np.int16 and np.uint16 to conversion map

---

hist/hist/inc/TFormula.h
roofit/hs3/src/JSONFactories_RooFitCore.cxx
roofit/hs3/test/testRooFitHS3.cxx

Fixes https://github.com/root-project/root/issues/14637
Credit for the solution goes to @mark-owen
Fyi @cburgard @Mathyuu @gartrog

[RF] Allow scientific notation in JSONfactory formula

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
bindings/pyroot/pythonizations/test/rvec_asrvec.py
bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py

Backport of the following two PRs:
* https://github.com/root-project/root/pull/18087
* https://github.com/root-project/root/pull/18366

[v634][Python] Backports for NumPy compatibility

---

.github/workflows/root-ci.yml

They are already defined globally.

[ci] Remove duplicate env variables

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTuple.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTuple.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_test.hxx

[ntuple] Move RMiniFileReader/RNTupleFileWriter out of Experimental

---

.github/workflows/root-ci.yml

this is a STS release and capacity is needed to integrate and test the forthcoming 6.36

[ci] Reduce the amount of builds of 6.34

---

.github/workflows/root-docs-ci.yml

[skip-ci][doc] force full build

---

.github/workflows/root-docs-ci.yml

try another way o force incremental

[skip-ci][doc] force incremental

---

tree/ntuple/test/ntuple_merger.cxx

Add a test to verify that the merger properly refuses to merge projected fields with a different source field.

[ntuple] add test for merging projected fields with diff sources

---

.github/workflows/root-ci.yml

[BP 632][ci] Do not run mac-beta builds on workflow dispatch triggers

---

core/base/src/TObject.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-9013

[skip-ci] Clarify documentation of AbstractMethod

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/regression_18441.py

Improve check logic in pythonization decorator

---

bindings/pyroot/pythonizations/python/ROOT/_facade.py

Currently, the `root_module.py` unit test is failing if ROOT was built with `dataframe=OFF`, because it assumes that the `RDF` attribute can be evaluated without any exception
This commit suggests to fix this by rearranging the code in the `RDF` attribute of the facade such that it also works in that case. Notably that means:
* pythonizing the `FromCSV` function only if it exists
* do the imports of helper modules that might not exist only in the Python functions of RDF, to delay errors about modules that are not found
Also, since there is no reason anymore why pythonizing the RDF namespace would fail, remove a try-except block.

[Python] Fix RDF attribute of ROOT facade in case of `dataframe=OFF`

---

io/io/src/TStreamerInfoActions.cxx

@TomasDado could you verify if this solves the memleak? Thanks for the report!
Fixes https://github.com/root-project/root/issues/18455
Please: Squash on Merge.

[io] fix small memleak in streamerInfoActions

---

roottest/root/io/hadd/merge_changeComp_check_output.C
tree/ntuple/inc/ROOT/RCluster.hxx
tree/ntuple/inc/ROOT/RClusterPool.hxx
tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/inc/ROOT/RPageStorage.hxx
tree/ntuple/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/src/RCluster.cxx
tree/ntuple/src/RClusterPool.cxx
tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/src/RPageStorage.cxx
tree/ntuple/src/RPageStorageDaos.cxx
tree/ntuple/src/RPageStorageFile.cxx
tree/ntuple/test/ntuple_cluster.cxx
tree/ntuple/test/ntuple_endian.cxx
tree/ntupleutil/v7/src/RNTupleExporter.cxx

[ntuple] Move RCluster/RClusterPool out of Experimental

---

graf2d/gpad/src/TPad.cxx

Fixes https://github.com/root-project/root/issues/18477
Backport of https://github.com/root-project/root/pull/18488

[gpad] Fix illegal access to vector.at(-1) [6.36]

---

roottest/cling/staticinit/CMakeLists.txt

Fixes #18499 once the caches are refreshed.

[test] Do not create a symlink and just copy the directory

---

bindings/pyroot/pythonizations/python/ROOT/_facade.py
core/cont/inc/TCollectionProxyInfo.h
hist/hist/src/TFormula.cxx
math/mathcore/inc/Math/CladDerivator.h
math/mathcore/inc/Math/DistSampler.h
math/mathcore/inc/Math/Functor.h
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/dataframe_nodes.cxx
tree/ntuple/inc/ROOT/RNTupleMetrics.hxx
tutorials/CMakeLists.txt

Backport some recent fixes to the release branch.

[v636] Backports fixes to 6.36 branch

---

README/ReleaseNotes/v636/index.md

[rn] mention JSROOT 7.9.0 for jupyter [skip-ci] [6.36]

---

math/mathcore/src/TMath.cxx

Improves loop performance, found out by clang-tidy

[math] improve Binomial function

---

math/minuit/src/TMinuit.cxx

Fixes https://github.com/root-project/root/issues/18542

[math] fix out of bounds array

---

roofit/roofitcore/src/RooFormula.cxx
roofit/roofitcore/src/RooFormula.h
roofit/roofitcore/src/RooFormulaVar.cxx
roofit/roofitcore/src/RooGenericPdf.cxx

Backport of the bugfix in #18543.

[v636] [RF] Use the actual proxy list as input for RooFormula::doEval()

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/regression_18441.py

Backport of #18448 as requested in https://github.com/root-project/root/issues/18441#issuecomment-2826724279.

[v632] Improve check logic in pythonization decorator

---

CMakeLists.txt

[cmake] Do not delete the roottest dir during configuration

---

README/ReleaseNotes/v636/index.md

- Add information about RResultPtr::GetSharedPtr().
- Remove a duplicate section title.
- Fix a typo.
- Add a note about the HistFactory ListOfCleanups speedup
- Add Stephan to contributors.

[skip-ci] Update release notes for 6.36

---

tree/tree/test/TChainRegressions.cxx

See https://github.com/root-project/root/issues/7567

[test] add test for single-file chain getEntries+deactivateBranches

---

cmake/modules/SearchInstalledSoftware.cmake

[nfc][cmake] fix gsl typo

---

core/meta/src/TStreamerElement.cxx

[skip-ci][nfc] Clarify internal object change even if const

---

.github/workflows/root-ci-config/buildconfig/alma10.txt
.github/workflows/root-ci.yml

The AlmaLinux 10 stable preview is now available:
https://wiki.almalinux.org/development/almalinux-os-kitten-10.html#mirrors-isos-and-update-frequency

[ci] Add AlmaLinux 10

---

tree/ntuple/doc/BinaryFormatSpecification.md

... about the deferred column index.

[skip-ci][ntuple] Reorder column flags paragraphs

---

bindings/pyroot/pythonizations/src/TTreePyz.cxx
cmake/modules/RootConfiguration.cmake
cmake/modules/SearchInstalledSoftware.cmake
roofit/roofitcore/test/stressRooFit_tests.h
tree/dataframe/test/dataframe_nodes.cxx

Backport of recent fixes to the release branch, in particular motivated by the fix for the memory leak in the TTree `getattr` pythonization.

[v636] Backport of recent fixes

---

math/mathcore/inc/Math/PdfFuncMathCore.h

[skip-ci][nfc] fix doxy docu of 2D dist

---

core/unix/src/TUnixSystem.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-6118

[skip-ci][unix] document caveat of FindFile function

---

io/io/src/TFile.cxx

BP of https://github.com/root-project/root/pull/18626

[BP 6.36][io] Remove from url parameters parsed by TXNetFile

---

io/io/src/TFile.cxx

BP of https://github.com/root-project/root/pull/18626

[BP 6.34][io] Remove from url parameters parsed by TXNetFile

---

tree/tree/src/TTree.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-7615

[skip-ci][tree] document the return value of Draw when selection has array loop

---

README/ReleaseNotes/v636/index.md

[v636] Add RNTuple-related release notes

---

tmva/sofie/inc/TMVA/ROperator_Comparision.hxx
tmva/sofie/inc/TMVA/ROperator_GRU.hxx
tmva/sofie/inc/TMVA/ROperator_GRU.icc

Consistently using the `RModel::AddIntermediateTensor()` interface will
make it easier to restructure the generated code for AD support with
Clad.

[tmva][sofie] Correctly add intermediate tensors for ROperator GRU

---

core/rint/src/TRint.cxx

BP of https://github.com/root-project/root/pull/18648

[core] Set the year to the correct value (2025)

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
bindings/pyroot/pythonizations/test/rdataframe_asnumpy.py

Calling `AsNumpy` on a dataframe (python api) now read `RVec` entries and `std::vector` as `numpy.ndarray` of the corresponding type. The implementation should be practically free besides some type checking.
It's not inmediate where to draw the line between what to convert into a `numpy.ndarray`. An `RVec` is clear but I also chose to convert `std::vector`, but not things such as `std::array`. Maybe `std::vector` shouldn't be converted. I haven't updated all the tests related to the conversion of `std::vector` so they are currently failing (I would like to have official confirmation).
We could also return a 2D (or N-D) regular array in the case the data is regular. This can be checked also without much overhead and the transformation into a regular array can be done via `numpy.stack`. …

[PyROOT][DF] `AsNumpy` automatically converts to numpy arrays

---

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/inc/ROOT/RTTreeDS.hxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/src/RTTreeDS.cxx
tree/dataframe/test/dataframe_interface.cxx
tree/dataframe/test/dataframe_snapshot_emptyoutput.cxx

Some code is not necessary anymore since the functionalities have been moved to RTTreeDS.

Move some functionality away from RLoopManager

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
bindings/pyroot/pythonizations/test/rdataframe_asnumpy.py
bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py
bindings/pyroot/pythonizations/test/rvec_asrvec.py

This PR backports the following fixes:
-  #18571
- #14717
-  #18585

[python][RDF] Backport recent fixes for 6.36

---

main/src/hadd-argparse.py
main/src/hadd.cxx

Fixes https://github.com/root-project/root/issues/8444

[nfc][hadd] improve docu of hadd compression algorithm

---

tree/ntuple/src/RNTupleProcessor.cxx
tree/ntuple/test/ntuple_processor.cxx

Instead of using a plain untyped record field for auxiliary processors, a lightweight field type specialization only meant for reading by the `RNTupleProcessor`, the `RAuxiliaryProcessorField`, is introduced. This way, we can recognise if the auxiliary processor to be added to the model contains nested auxiliary processors. When this is the case, their subfields are added as well.

[ntuple] Fix handling of composed auxiliary processors

---

io/io/src/TFileMerger.cxx
main/src/hadd.cxx

[skip-ci][io] fix docu of fMaxOpenedFiles

---

hist/hist/src/THnSparse.cxx

Fix some incorrect code formatting as mentioned here: https://github.com/root-project/root/issues/18631

[skip-ci] fix doxygen formatting

---

tree/dataframe/src/RDFHistoModels.cxx

Clarify that it is not a Clone, but just a copy of basic parameters
See https://github.com/root-project/root/issues/18712

[skip-ci][DF] Clarify documentation of RDFHistoModels

---

roofit/codegen/inc/RooFit/CodegenImpl.h
roofit/codegen/src/CodegenImpl.cxx
roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/hs3/CMakeLists.txt
roofit/roofitcore/inc/RooWrapperPdf.h
roofit/roofitcore/test/testRooFuncWrapper.cxx
roofit/xroofit/CMakeLists.txt
tutorials/roofit/roofit/rf101_basics.C

Backport the recent RooFit commits that we want to have in the release.

[v636][RF] Backport recent RooFit commits

---

.github/workflows/root-ci.yml

BP of https://github.com/root-project/root/pull/18716

[636][ci] Enable C++23 for macOS Beta and 15

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx
core/meta/test/testTClass.cxx

Backport of #18625 
Fix #18654

[v636] [core] Fix a TClass lookup for STL containers / fix the crash in df104_CSVDataSource

---

montecarlo/eg/src/TDatabasePDG.cxx
montecarlo/eg/test/pdg.cxx

[MC] Correctly report stability of particles

---

hist/hist/src/TFormula_v5.cxx
roottest/root/treeformula/array/runArrayTest.C
tree/treeplayer/src/TTreeFormula.cxx

A re-organisation of the commits by @ferdymercury in this PR https://github.com/root-project/root/pull/18579 . All the credit goes to the original author - here the original commits are just reshuffled.
Fixes https://github.com/root-project/root/issues/11712

[hist, tree] Do not parse string to int if it's not a digit

---

tutorials/CMakeLists.txt

The tutorials use numba and sklearn, but didn't specify this for CMake.

[Tutorials] Add Python dependencies for df101 and rf617.

---

ui5/canv/view/Hist.fragment.xml

openui5 has only tooltip attributes

[webgui][ui5] replace title by tooltip in CheckBox [6.36][skip-ci]

---

core/base/src/TSystem.cxx

Follow-up of discussion https://github.com/root-project/root/pull/18748#issuecomment-2887215110

[skip-ci] mention deprecated ConcatFileName

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/ClassWithNestedSameName.hxx
tree/dataframe/test/ClassWithNestedSameNameLinkDef.hxx
tree/dataframe/test/datasource_tree.cxx
tree/tree/inc/TTree.h
tree/tree/src/TTree.cxx

Backport of https://github.com/root-project/root/pull/18358

[6.36] Speedup retrieval of branch names

---

core/clingutils/src/dequeLinkdef.h
core/clingutils/test/TClingUtilsTests.cxx

Add some dicts of deque types that could be useful

[core] add more dicts for deque variants

---

tree/ntuple/inc/ROOT/REntry.hxx
tree/ntuple/inc/ROOT/RNTupleReader.hxx

Also add method documentations in `REntry`.

[skip-ci][ntuple] Add notes about disabled type checks

---

.github/workflows/root-ci-config/buildconfig/alma10.txt
.github/workflows/root-ci.yml
bindings/pyroot/pythonizations/test/import_load_libs.py

Add AlmaLinux 10 to the 6.34 branch.

[v634][ci] Add AlmaLinux 10

---

tree/ntuple/inc/ROOT/REntry.hxx
tree/ntuple/inc/ROOT/RNTupleReader.hxx

Also add method documentations in `REntry`.
Backport of PR https://github.com/root-project/root/pull/18695

[skip-ci][ntuple] Add notes about disabled type checks [v6.36]

---

.github/workflows/root-ci-config/buildconfig/alma9.txt

[v626][ci] Enable `tmva` on alma9

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx

For example `fFuncTemplate` was never initialized, which could be problematic.
Also, move the initialization of all class members to the class declaration, such that these problems can be seen more easily.
I noticed this when thinking about the following PR:
* https://github.com/root-project/root/pull/18770

[core] Make sure all pointer members of TROOT are initialized

---

tree/ntuple/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/src/RColumnElement.hxx
tree/ntuple/test/ntuple_packing.cxx

BP of https://github.com/root-project/root/pull/18629

[6.36][ntuple] Fix some inconsistencies in Real32Quant

---

tree/ntuple/doc/Architecture.md
tree/ntuple/inc/ROOT/RFieldBase.hxx
tree/ntuple/inc/ROOT/RNTupleModel.hxx
tree/ntuple/inc/ROOT/RNTupleView.hxx
tree/ntuple/src/RFieldBase.cxx
tree/ntuple/src/RNTupleModel.cxx
tree/ntuple/test/ntuple_bulk.cxx
tree/ntuple/test/ntuple_multi_column.cxx

[v636][ntuple] Rename `RBulk` to `RBulkValues`

---

README/ReleaseNotes/v636/index.md

Backport of https://github.com/root-project/root/pull/18802

[skip-ci][6.36] Add RDF release notes

---

core/base/src/TROOT.cxx
core/cont/src/TClassTable.cxx
core/meta/src/TClass.cxx
core/meta/src/TEnum.cxx
core/meta/src/TProtoClass.cxx
core/metacling/src/TCling.cxx

BP of https://github.com/root-project/root/pull/18793/

[636] [meta] Correct thread behavior in TEnum::GetEnum.

---

tree/dataframe/test/dataframe_friends.cxx

[6.36][df] Another workaround for attempt to delete stack memory

---

geom/geom/inc/TGeoPhysicalConstants.h

[geom] Update Planck's constant to CODATA2022

---

builtins/zlib/inffast.c
builtins/zlib/inftrees.c

BP of https://github.com/root-project/root/pull/18526 and https://github.com/root-project/root/pull/18527

[636] Misc backport for zlib

---

gui/webdisplay/src/RWebDisplayHandle.cxx
js/changes.md
js/modules/base/jspdf.mjs
js/modules/core.mjs
js/modules/draw/TASImagePainter.mjs
js/modules/draw/more.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/hist/TH1Painter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/TMultiGraphPainter.mjs
js/modules/webwindow.mjs

1. Backport fix from #18771 
2. JSROOT 7.9.1 release with several other fixes

[webgui] Workaround WebGL problem in Firefox [6.36]

---

core/base/src/TROOT.cxx
core/cont/src/TClassTable.cxx
core/meta/src/TClass.cxx
core/meta/src/TEnum.cxx
core/meta/src/TProtoClass.cxx
core/metacling/src/TCling.cxx

BP of https://github.com/root-project/root/pull/18793

[632] [meta] Correct thread behavior in TEnum::GetEnum.

---

core/foundation/src/TClassEdit.cxx
roottest/root/meta/rootcling/CMakeLists.txt
roottest/root/meta/rootcling/streamerInfoStdFunction.h
roottest/root/meta/rootcling/streamerInfoStdFunction.xml

This PR fixes #18833
All the credit goes to @scott-snyder

Allow to TStreamerInfo::Compile with type involving std::function

---

core/foundation/src/TClassEdit.cxx
roottest/root/meta/rootcling/CMakeLists.txt
roottest/root/meta/rootcling/streamerInfoStdFunction.h
roottest/root/meta/rootcling/streamerInfoStdFunction.xml

I.e.:
- commit 9ff60071f40ed88086e527b78bd0fc807458c83a
- commit d3385237f0908cf7d0f2a3e1cb7bcf062a343d7d
LCG nightlies revealed an issue that ROOT's test battery did not catch: https://github.com/root-project/root/issues/18842
This PR fixes #18842 (it does fix that issue, but reopens https://github.com/root-project/root/issues/18833 )

Revert PR #18839

---

core/foundation/src/TClassEdit.cxx

This reverts commit 69bcc3ec7b50b606eaad75d8439df132318817d1.

Revert "[meta] Fix parsing of parentheses in ResolveTypedef"

---

README/ReleaseNotes/v636/index.md
math/mathcore/src/ProbFuncMathCore.cxx

Backport of:
* https://github.com/root-project/root/pull/18426

[v636][math] Optimize CrystalBallIntegral to avoid issues with high N

---

graf2d/graf/inc/TLine.h
graf2d/graf/src/TLine.cxx
roottest/root/meta/MemberComments.ref
roottest/root/meta/MemberComments_win32.ref
roottest/root/meta/MemberComments_win64.ref

Implement TLine::GetSlope and TLine::GetYIntercept as requested here:https://root-forum.cern.ch/t/possibility-to-get-a-slope-and-a-y-intercept-of-a-tline/63598/1

Implement TLine::GetSlope and TLine::GetYIntercept

---

gui/webdisplay/src/RWebWindow.cxx

Backport RWebWindow fixes from https://github.com/root-project/root/pull/18882

[webgui] fix RWebWindow methods for embed widgets

---

.github/workflows/root-ci-config/buildconfig/alma10.txt
.github/workflows/root-ci.yml

1) Turn mySQL off for alma10
2) Re-enable Windows because in 1 month, 6.32 and 6.36 will be the active branches

Misc ci fixes

---

core/meta/inc/TMethodCall.h
net/httpsniff/src/TRootSnifferFull.cxx
roottest/root/meta/execExecuteObjArray.C

Fixes https://its.cern.ch/jira/browse/ROOT-7439

[core] Add missing Execute signature

---

.github/workflows/root-ci-config/buildconfig/alma8.txt
.github/workflows/root-ci-config/buildconfig/alma9-clang.txt
.github/workflows/root-ci-config/buildconfig/debian125.txt
.github/workflows/root-ci-config/buildconfig/global.txt
.github/workflows/root-ci-config/buildconfig/mac-beta.txt
.github/workflows/root-ci-config/buildconfig/mac13.txt
.github/workflows/root-ci-config/buildconfig/mac14.txt
.github/workflows/root-ci-config/buildconfig/mac15.txt
.github/workflows/root-ci-config/buildconfig/ubuntu22.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2404.txt
README/ReleaseNotes/v638/index.md
cmake/modules/RootBuildOptions.cmake
math/mathcore/inc/Math/Minimizer.h
math/minuit2/CMakeLists.txt
math/minuit2/doc/Minuit2.md
math/minuit2/inc/Minuit2/GradientCalculator.h
math/minuit2/inc/Minuit2/Minuit2Minimizer.h
math/minuit2/src/GradientCalculator.cxx
math/minuit2/src/Numerical2PGradientCalculator.cxx

Fixes https://github.com/root-project/root/issues/18816
Credit for the solution goes to @SilentAssassinMa

[minuit2] disable parallelization by default even if openMP is active, allow switch

---

core/clingutils/src/TClingUtils.cxx

BP of https://github.com/root-project/root/pull/18930
Fixes #18811

[634][meta] Remove redundant check

---

core/clingutils/src/TClingUtils.cxx

BP of https://github.com/root-project/root/pull/18930
Fixes https://github.com/root-project/root/issues/18811

[632][meta] Remove redundant check

---

core/clingutils/src/TClingUtils.cxx

[636][meta] Remove redundant check

---

gui/gui/src/TGNumberEntry.cxx

Fixes https://github.com/root-project/root/issues/18951

[gui] stop copying when finding a null terminator char

---

roottest/root/tree/index/Dupe.ref
roottest/root/tree/index/runDupe.C
tree/treeplayer/src/TTreeIndex.cxx

Fixes https://github.com/root-project/root/issues/18963

[tree] emit warning if duplicate keys in TTreeIndex

---

io/io/src/TFile.cxx

see https://root-forum.cern.ch/t/how-to-get-the-string-branch-created-in-geant4/63662/4?u=ferhue

[skip-ci][io] document behavior of READ mode and directories

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx

BP of https://github.com/root-project/root/pull/18925 but for the root part only (roottest in the sibling PR https://github.com/root-project/roottest/pull/1328)

[636][meta] Correctly treat data member types containing functions

---

io/io/src/TFile.cxx

it's called too late in some cases

[io] be more consistent with upper case in TFile options

---

bindings/distrdf/python/DistRDF/HeadNode.py
bindings/distrdf/python/DistRDF/Ranges.py
bindings/distrdf/test/test_ranges.py
tree/dataframe/inc/ROOT/RDF/RDatasetSpec.hxx
tree/dataframe/inc/ROOT/RDF/RMetaData.hxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/src/RMetaData.cxx

Backporting #18819 this to 6.36 patches as this is making the incomplete feature (using distributed RDataFrame with RDatasetSpec) complete now. It has been requested by users as well. 
Sibling PR in roottest https://github.com/root-project/roottest/pull/1330

[6.36][df] Backport of add parsing of metadata for distributed RDataFrame

---

math/physics/src/TVector3.cxx

see https://geant4-forum.web.cern.ch/t/rotateuz-looks-fishy/14131/7

[skip-ci][math] mention gimbal lock

---

interpreter/cling/lib/UserInterface/UserInterface.cpp
interpreter/cling/www/index.html

Improves start message when running standalone cling

[cling] Show shortcut for help when starting

---

.github/workflows/root-ci-config/buildconfig/mac-beta.txt
core/foundation/inc/ROOT/StringUtils.hxx
math/mathcore/inc/Math/StdEngine.h
math/minuit2/inc/Minuit2/MnPlot.h
math/vecops/inc/ROOT/RVec.hxx
roofit/roofitcore/inc/RooCmdConfig.h
tmva/tmva/inc/TMVA/Pattern.h

BP of the following PRs
https://github.com/root-project/root/pull/19057
https://github.com/root-project/root/pull/19059
https://github.com/root-project/root/pull/19072
https://github.com/root-project/root/pull/19073

[636] Misc backports for xcode26 

---

tree/treeplayer/inc/TTreeReaderValue.h
tree/treeplayer/src/TTreeReaderValue.cxx
tree/treeplayer/test/basic.cxx

[6.36] Allow catching entry beyond end from TTreeReaderValueBase 

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/pythonizations/test/stl_vector.py

BP of https://github.com/root-project/root/pull/18999

[636][cppyy] fix iadd pythonization for np/array buffers

---

interpreter/CMakeLists.txt
roottest/cmake/modules/RoottestMacros.cmake
tutorials/CMakeLists.txt

- Mark two tutorials that are using numpy
- Make a CMake condition not depend on testing, but on the actual target that it's setting properties for
- Fix CMake with asan=On

[CMake] Three small updates

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/cppyy/test/test_datatypes.py

[cppyy] handle polymorphic types when converting from class fields

---

ui5/eve7/lib/GlViewerRCore.js

This PR fixes errors in selection in GL view and geometry table browser.

[reve] Correct selection in REveGeoTopNode

---

tree/ntuple/inc/ROOT/RNTuple.hxx
tree/ntuple/inc/ROOT/RNTupleWriter.hxx

Improves the documentation of RNTupleWriter, in particular Recreate and Append.
This PR fixes #19168

[skip-ci][ntuple] Improve RNTupleWriter doc

---

js/changes.md
js/modules/base/svg2pdf.mjs
js/modules/core.mjs
js/modules/draw.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/io.mjs
js/modules/rntuple.mjs
js/modules/tree.mjs

1. Fix - THttpServer UI, click on histogram
1. Support `Xall` and `Yall` as projections 
1. Fix - reading TLeafC leafs
1. Fix - support BigInt in object inspector

[jsroot] dev 26/06/2025

---

tree/dataframe/inc/ROOT/RCsvDS.hxx
tree/dataframe/src/RCsvDS.cxx
tree/dataframe/test/datasource_csv.cxx

In preparation for deprecation of template Snapshot overload.

Use new GetColumnReaders API in RCsvDS

---

roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h
roofit/hs3/src/JSONFactories_HistFactory.cxx
roofit/hs3/src/RooJSONFactoryWSTool.cxx

Backport RooFit HS3 fixes needed by ATLAS.

[v636] Backport RooFit HS3 fixes needed by ATLAS

---

roottest/cling/staticinit/ROOT-10426/CMakeLists.txt

Re-enable test.
Fixes [ROOT-10463](https://its.cern.ch/jira/browse/ROOT-10463)

[test] Enable test once broken without modules

---

cmake/modules/RootConfiguration.cmake

Was rightfully on in 6.34, development release STS.

[636][gui] Make TBrowser the default for 6.36

---

hist/hist/inc/THnBase.h
hist/hist/src/THnBase.cxx
hist/hist/test/THn.cxx

Thanks to jgrosseo!
Fix https://github.com/root-project/root/issues/19241

[hist] Fix error calculation in THnBase::ProjectionAny.

---

.github/workflows/root-docs-ci.yml

Backport of https://github.com/root-project/root/pull/19296

[skip-ci] ci: Checkout explicit branch in root-docs [v6.36]

---

bindings/pyroot/pythonizations/test/uhi_indexing.py
bindings/pyroot/pythonizations/test/uhi_plotting.py

See the error [here](https://github.com/root-project/root/actions/runs/16117467961/job/45474611710?pr=19299).

[Python][UHI] Fix floating point comparisons of effective entries

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
cmake/modules/RootMacros.cmake
core/cont/inc/TClassTable.h
core/cont/src/TClassTable.cxx

BP of https://github.com/root-project/root/pull/19286

[636] An option for the second part of #19022

---

hist/hist/src/TH1.cxx
hist/hist/test/test_TH1.cxx

[630][hist] Ignore buffer in TH1::Sumw2

---

bindings/pyroot/cppyy/cppyy/test/templates.xml
bindings/pyroot/cppyy/patches/cppyy-Remove-unused-template-instance-pattern-rule.patch
bindings/pyroot/cppyy/sync-upstream

as there are no instances to match.
This PR fixes #19189

[cppyy] Remove unused template instance pattern rule

---

hist/hist/src/THnBase.cxx
hist/hist/test/THn.cxx

Fixes https://github.com/root-project/root/issues/19366
fyi @Zehvogel

[hist] Skip empty bins when add/filling sparse hist

---

hist/hist/src/THnBase.cxx
hist/hist/test/THn.cxx

BP of https://github.com/root-project/root/pull/19367

[632][hist] Skip empty bins when add/filling sparse hist

---

hist/hist/src/THnBase.cxx
hist/hist/test/THn.cxx

[636][hist] Skip empty bins when add/filling sparse hist

---

tree/ntuple/src/RColumnElement.hxx

The assert in QuantizeReals() should not assume that all values are in range, as we want to throw an exception at the end of the function if that is the case.
Another mistake conspired to hide this bug from all non-windows builds:  except on Windows, LeadingZeroes() and TrailingZeroes() were incorrectly using the 64-bit version of the intrinsics, where they should have used the 32-bit one. This means they effectively never fired as they ranged from 0 to 63 rather than the intended 0 to 31.

[ntuple] Fix wrong assert in Real32Quant

---

main/python/cmdLineUtils.py

Fixes https://github.com/root-project/root/issues/7051

[main] clarify wording of rootcp recursive warning

---

main/python/cmdLineUtils.py

Introduced during this refactoring https://github.com/root-project/root/pull/3697/files

[main] fix bug in function name

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

The new release introduces improvements across both forward and reverse automatic differentiation modes, including the adoption of static scheduling by default and expanded support for custom derivatives, such as those involving STL containers and iterators. The release enhances compatibility with Clang versions 10 through 20 and extends support for CUDA through updated tape handling. Additional updates include improved error diagnostics, support for more complex object types, and infrastructure for benchmarking.

[clad] Bump to v2.0

---

hist/histpainter/src/THistPainter.cxx

[636][hist] clip color to minimum if below with COLZ TH2

---

main/src/hadd.cxx

Fixes https://github.com/root-project/root/issues/19485
Bug introduced in https://github.com/root-project/root/commit/217441dc2c2346a92c78eb96b0486b7cde8eed18

[hadd] Fix missing argument in parallel merger

---

requirements.txt

[Python][UHI] Add matplotlib dependency for UHI tutorials

---

roottest/root/dataframe/test_branchoverwrite.ref
roottest/root/dataframe/test_columnoverride.cxx
tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RDFSnapshotHelpers.cxx
tree/dataframe/src/RInterface.cxx
tree/dataframe/src/RInterfaceBase.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/src/RTTreeDS.cxx
tree/dataframe/test/dataframe_utils.cxx

See every commit for a summary

Remove further TTree-specific logic from the codebase [1/N]

---

roottest/main/CMakeLists.txt

Allows run individual tests with proper invocation of all required tests first

[roottest] use fixtures in main tests

---

roofit/hs3/src/RooJSONFactoryWSTool.cxx

Backport of https://github.com/root-project/root/pull/18209

[v630][RF] Fix implementation of HS3 importers

---

geom/gdml/src/TGDMLWrite.cxx

This PR fixes https://github.com/root-project/root/issues/19592

Fix handling for CONST properties in CreateOpticalSurfaceN method

---

tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/src/RNTupleDescriptor.cxx
tree/ntuple/src/RPageStorageDaos.cxx
tree/ntuple/src/RPageStorageFile.cxx
tree/ntuple/test/ntuple_cluster.cxx
tree/ntuple/test/ntuple_compat.cxx
tree/ntuple/test/ntuple_descriptor.cxx
tree/ntuple/test/ntuple_evolution.cxx
tree/ntuple/test/ntuple_serialize.cxx

[ntuple] Renormalize type name before comparing

---

roofit/roofitcore/src/RooRealIntegral.cxx

Backport of https://github.com/root-project/root/pull/19654

[v636][RF] Don't warn about duplicates in temporary RooArgSet in RealIntegral

---

tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/CustomStruct.hxx
tree/ntuple/test/CustomStructLinkDef.h
tree/ntuple/test/rfield_class.cxx

[ntuple] fix for I/O rule handling [v6.36]

---

roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/LinkDef.h
roofit/roofitcore/inc/RooMultiReal.h
roofit/roofitcore/src/RooMultiReal.cxx
roofit/roofitcore/test/CMakeLists.txt
roofit/roofitcore/test/testRooMulti.cxx

This change wants to implement a new class which work like RooMultiPdf , but instead of pdfs it deals with RooRealVars.
testRooMultiPdf.cxx was changed to testRooMultiReal.cxx  in order everything to be more compact. All the tests are passing

[RF] Adding RooMultiReal to per request from ATLAS

---

hist/hist/src/TF1.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_tf1_drawcopy.cxx

BP of #19627
(a redo of #19669)

[636] Fix TF1::DrawCopy issue

---

tmva/sofie/inc/TMVA/ROperator_BatchNormalization.hxx

The previous implementation has been replaced with a new that generates a single, fused C++ loop, eliminating the need for BLAS calls and costly memory allocations for this operator.

[tmva][sofie] Optimized performance and memory usage of BatchNorm

---

.github/workflows/root-docs-ci.yml

It looks like the `xrdcp` commands might have be miss-configured. 
This PR is an attempt to fix them.

[skip-ci] try to fix the doc CI

---

.github/workflows/root-docs-ci.yml

Fix EOS CI run with correct xrdcp paths

[skip-ci] Fix EOS CI run with correct xrdcp paths

---

tmva/sofie/inc/TMVA/ROperator_BasicBinary.hxx

In the initialization of BasicBinary operator  do not change the inputshapes of the tensors, just compute the output shape. Do instead broadcasting of tensors and implement the binary operation at initialization phase  if input tensors are constant.

[tmva][sofie] Fix initialisation of BasicBinary operator

---

gui/browserv7/src/RBrowser.cxx

Fixes https://github.com/root-project/root/issues/10259

[nfc] improve rbrowser docu

---

roottest/root/treeproxy/CMakeLists.txt
roottest/root/treeproxy/stlvec/CMakeLists.txt

Follow up of https://github.com/root-project/root/pull/19565
Trying to compile generated selector before using them

[roottest] adjust treeproxy tests

---

cmake/scripts/std_modulemap_darwin_fix.py

[6.36] Backport of #19749

---

hist/histv7/inc/ROOT/RAxes.hxx
hist/histv7/inc/ROOT/RBinIndexRange.hxx
hist/histv7/test/hist_regular.cxx
hist/histv7/test/hist_variable.cxx

Also exclude unreachable lines from coverage.

[hist] Test missed check in `GetNormalRange`

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RLoopManager.cxx

In an effort improve coverage percentage, remove some dead code that is never hit. See the individual commit messages for more details.

[df] Remove some dead code

---

tree/ntuple/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/ntuple_evolution_type.cxx

[ntuple] fix automatic schema evolution of variant

---

cmake/modules/RootMacros.cmake

Fixup copy-paste error in previous commit 4020a58ac51564.
Follows up on https://github.com/root-project/root/pull/19766.

[CMake] Fixup copy-paste error in previous commit

---

tree/ntuple/src/RFieldBase.cxx
tree/ntuple/test/ntuple_evolution.cxx

[v6.36][ntuple] fix bulk read of artificial fields

---

gui/webdisplay/src/RWebDisplayHandle.cxx
js/files/canv_batch.htm

Backport of https://github.com/root-project/root/pull/19900

[webgui] fix screenshot functionality [6.36]

---

tree/tree/src/TChain.cxx
tree/tree/src/TChainElement.cxx
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/test/regressions.cxx

Sibling roottest PR at https://github.com/root-project/roottest/pull/1347
Backport of https://github.com/root-project/root/pull/19873

[6.36] Rework TChain::GetEntries to avoid side-effects

---

tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/CustomStruct.hxx
tree/ntuple/test/CustomStructLinkDef.h
tree/ntuple/test/ntuple_types.cxx

[v636][ntuple] Backport fixes to backing type handling of enum and collection proxy

---

hist/histv7/benchmark/hist_benchmark_engine.cxx
hist/histv7/doc/CodeArchitecture.md
hist/histv7/doc/Terminology.md
hist/histv7/headers.cmake
hist/histv7/inc/ROOT/RBinWithError.hxx
hist/histv7/inc/ROOT/RHistEngine.hxx
hist/histv7/test/hist_engine.cxx
hist/histv7/test/hist_test.hxx

A special bin content type to compute the bin error in weighted filling.

[hist] Implement `RBinWithError`

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py

1. Use JavaScript `import()` function to load jsroot. Avoiding by-hand creation of script elements
2. Solves problem of multiple jsroot loading by different plots
3. Make code much more compact, produce the only global function per plot
4. Keep requirejs part to support Visual Studio Code
5. Tested both in `jupyter lab` and `jupyter notebook`

[jupyter] optimize jsroot loading

---

tree/ntuple/inc/ROOT/RFieldBase.hxx
tree/ntuple/src/RFieldBase.cxx
tree/ntuple/test/ntuple_bulk.cxx

Exercise some untested code (according to coverage) and simplify impossible case.

[ntuple] Extend testing of `RBulkValues`

---

tree/dataframe/src/RDataFrame.cxx

Fixes https://github.com/root-project/root/issues/19879

[nfc][RDF] mention shortcut for omitting NaNs when calculating mean

---

tree/treeplayer/test/regressions.cxx

Closes https://github.com/root-project/root/issues/10423
by adding a test to it.
The issue seems solved in the meanwhile.

[test] Add test for vector of XYZVector in TTreeReaderValue
