gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowsManager.cxx

Backport of #15867 
For security reasons this option is off by default. 
Only when desired `win.SetUseCurrentDir(true)` should be invoked. 
It happens automatically when "localapp." namespace configured as main ui5 panel for the window

[webgui] let enable usage of currentdir [6.32]

---

tree/ntuple/v7/src/RPageStorageFile.cxx

[ntuple] avoid some memory allocations in RPageStorageFile

---

tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_packing.cxx

In preparation of adding page checksums. The `GetSize()` getter will later be split in `GetPayloadSize()` (page size without checksum) and `GetTotalPageSize()` (page size with checksum).

[ntuple] turn RSealedPage into class with getters/setters

---

tree/ntuple/v7/src/RNTupleMerger.cxx

the calling code in TFileMerger is not exception-safe and this ends up hiding the original exception under some bogus error

[ntuple] don't bubble up exceptions from RNTuple::Merge

---

geom/geom/src/TGeoNode.cxx
geom/geom/src/TGeoVolume.cxx

Propagate user- and system-extensions in TGeoAssemblyVolumes to cloned entities.
This was missing in the sub-class of TGeoVolume and then tends to fail on
re-alignments using TGeoPhysicalNode.
Buggy volume clones if the volume has user extensions.

Propagate TGeoVolume extensions to TGeoAssemblyVolume

---

.github/workflows/root-ci-config/buildconfig/mac-beta.txt

Clad currently has problems with some new headers in `MacOSX15.0.sdk` and crashes / errors due to `__builtin_pow`. Disable it for now while a solution is worked on, so we can upgrade the nodes and keep the build green.

[ci] Disable clad on mac-beta

---

graf2d/gpad/src/TRatioPlot.cxx

[before.pdf](https://github.com/user-attachments/files/15914243/before.pdf)
[after.pdf](https://github.com/user-attachments/files/15914241/after.pdf)
This PR fixes #15883 
@dpiparo @couet

TRatioPlot: use Left/Right pad margins from gStyle

---

tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_processor.cxx
tutorials/v7/ntuple/ntpl012_processor.C

This PR provides the first steps to the `RNTupleProcessor`, which is envisioned as an interface for reading vertically and horizontally composed RNTuples (i.e., chains and friends), and combinations thereof. The interface provides an iterator which gives access to the `REntry` containing the field values of the current entry index, as well as some additional bookkeeping information.
At this point, only vertically composed RNTuples (i.e., chains) are supported. Horizontal compositions in the form of (unaligned) friends and the ability to combine vertical and horizontal compositions will be addressed in a future PR.
Other additions that will be accounted for in one or more follow-up PRs include:
- The possibility for users to provide their own entries/value pointers to the processor.
- The …

[ntuple] Add initial `RNTupleProcessor` prototype

---

tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx

In preparation of adding page checksums, it makes sense to enable `LoadSealedPage()` support with DAOS and the caging option (caging: storage of multiple pages in a single object). Even though the implementation is not very performant, it will later allow to streamline the test for checksum verification.

[ntuple] fix LoadSealedPage with DAOS/caging

---

interpreter/cling/docs/ReleaseNotes.md

Fixes https://github.com/root-project/cling/issues/339
From main RawGit Webpage: If you're currently using RawGit, please stop using it as soon as you can.

[skip-ci] Remove link to rawgit as it will shut down

---

roofit/RDataFrameHelpers/inc/LinkDef.h
roofit/histfactory/inc/LinkDef.h
roofit/roofit/inc/LinkDef1.h
roofit/roofitcore/inc/LinkDef.h
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitmore/inc/LinkDef.h
roofit/roostats/inc/LinkDef.h
roofit/xroofit/inc/LinkDef.h

Minor backports such that the RooFit sources don't diverge between 6.32 patch releases and `master` just yet.

[RF][v632] Backports to 6.32

---

tutorials/graphs/scatter.C

this was done by couet, I just copy-pasted from https://root-forum.cern.ch/t/scatter-plot-with-colorbar/59562/14
There is one outstanding issue though:
- Save the object as .C and reload it, then the axis title is lost.
So the function SavePrimitive should be amended, too.
Also: 
`scat->GetHistogram()->SetMinimum(100);`
has no effect, it seems there is not an easy way to control the color range?

[skip-ci] mention how to change z axis title in tscatter

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_datasetspec.cxx

Fixes problem reported on the forum at https://root-forum.cern.ch/t/issue-with-root-rdf-experimental-fromspec-when-ttree-is-inside-a-sub-directory/59719

[df] Correctly update sample info when dataset is in TFile subdirectory 

---

hist/hist/src/THStack.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_THStack.cxx
tutorials/hist/hstackpads.C

1. Errors for stacked histogram were not taken into account. Therefore methods were returning wrong values
2. Protect GetMinimum method for case of log scale
3. Improve pads options:
3.1.   Always ensure that subpad is clear when drawing stack histograms
3.2.   Reuse existing subpads, no need to divide canvas again
3.3.  Use TPad::Add() method to add histograms to subpads

[thstack] fix GetMinimum/GetMaximum, improve "pads" drawing

---

tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx

Adds `RPageSource::LoadStructure[Impl]()`. This allows to load header and footer without processing them. Decompression and deserialization will still happen in Attach(), which calls LoadStructure if it hasn't been called before.
This will facilitate asynchronous open of files for RDF MT scheduling.

[ntuple] split loading and processing meta-data

---

.github/workflows/root-ci-config/build_root.py

To differentiate between versions installed on runners with identical labels.

[ci] Add MacOS version to build artifacts path

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMetrics.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RNTupleReader.cxx

- use "\n" instead of `std::endl` for all but last newline in PrintInfo
- avoid copying strings from getters when possible

[ntuple] minor cleanups to some RNTuple classes

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_checksum.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/ntuple_test.cxx
tree/ntuple/v7/test/ntuple_test.hxx

Implements writing page checksums and checksum verification on read.
Page checksums are written on `SealPage()`. They are verified on `LoadSealedPage()` and on `UnsealPage()`.
Note that the page size stored in locators does not change. Pages flagged as having a checksum are serialized with additional trailing 8 bytes.

[ntuple] Add page checksum creation and verification

---

tmva/sofie/inc/TMVA/RModel.hxx
tmva/sofie/inc/TMVA/ROperator_Gather.hxx
tmva/sofie/inc/TMVA/ROperator_Reshape.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx

We need to add a new category of initialized tensors in RModel that are not written in the weight file. These are for example tensors defining the shape and use as input to some operator such as Reshape. Its data are used when parsing and hard-coded then in the model. There is no need to generate or getting t heir value when using the model for inference
This Pull request should fix a failure reported in master after merging the PR on constant operator ( #15837 )

[tmva][sofie] Introduce not writable initialized tensors in RModel

---

roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooAbsMinimizerFcn.cxx
roofit/roofitcore/src/RooAbsMinimizerFcn.h
roofit/roofitcore/src/RooMinimizer.cxx
roofit/roofitcore/src/RooMinimizerFcn.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodGradientJob.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
roofit/roofitcore/src/TestStatistics/LikelihoodJob.h
roofit/roofitcore/src/TestStatistics/LikelihoodSerial.cxx
roofit/roofitcore/src/TestStatistics/MinuitFcnGrad.cxx
roofit/roofitcore/src/TestStatistics/RooBinnedL.cxx
roofit/roofitcore/src/TestStatistics/RooRealL.cxx
roofit/roofitcore/src/TestStatistics/RooUnbinnedL.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/TestStatistics/testPlot.cxx

This PR mainly adds error handling to the `MultiProcess`-based fitting stack. Error signaling in RooFit happens through two mechanisms: `logEvalError` calls and `RooNaNPacker`-enhanced `nan` doubles. Both are now implemented and working.
With this addition, we can now (finally!) run the most recent ATLAS Higgs combination fits again without issues.
The actual error handling is implemented in the 5th commit of this PR.
The first two commits are really unrelated, minor refactorings of existing code. I add them in this PR because I touched these while working on the error handling and just wanted to rebase to keep history clean and don't think they need a separate PR, since they are quite trivial changes.
The same goes for the last commit; it's a refactoring that could have been done in a …

[RF] MultiProcess error handling

---

tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleReader.cxx

adds the possibility of requesting metrics in `RNTupleReadOptions`. 
Since one normally has to call `EnableMetrics()` on the RNTupleReader to start collecting metrics, it is currently not possible to query the metrics gathered during construction of the reader itself. With this new option you can request metrics to be enabled at construction time.
As a somewhat arbitrary choice, an RNTupleReader created via `Clone()` will inherit this option from the one it is cloned from.

[ntuple] Reader: add option to enable metrics on construction

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx
tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx

Implement two improvements to the RNTuple RDF scheduler for the multi-threaded case:
1. Files of a chain are opened in batches the background: while a batch of files (batch size == number of slots) is processed, the next batch is opened.
2. For the tail scheduling (multiple slots sharing the same files), the clones of the page source pointing to the same file do not need to re-read meta-data (anchor, header, footer) again.
The patch results in a speed improvement of about 10% for AGC, EOS cached, 32 cores.

[ntuple] Improve RDF MT scheduling

---

tree/ntuple/v7/inc/ROOT/RField.hxx

Instead of (incorrectly) constructing a signed 16-bit int, now an unsigned 16-bit int is constructed.

[ntuple] Fix `ConstructValue` for `uint16_t` fields

---

core/metacling/src/TClingCallbacks.cxx

I implemented `AutoloadLibraryGenerator` in commit 9b2041e300 during the upgrade to LLVM 13 and wasn't sure if it should return an error if some symbols cannot be found. In practice, it didn't make a big difference because it was the last generator of the only `JITDylib`. This will change with LLVM 18 where we have at least one additional `JITDylib` for platform symbols (like `__cxa_atexit`) and search must continue, so remove the error.
In contrast, `AutoloadLibraryMU`s continue to fail the materialization if they promised to find a symbol but there is an error.

TCling: Remove error if symbols cannot be autoloaded

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py

Canvas name was used as identifier to track HTML element. 
If new canvas with same name was created, old HTML name was overwritten.
Therefore add unique ID (pointer) to the canvas name to handle new canvas properly.
Also update jsroot link to latest version

[jupyter] correctly handle TCanvases with same name

---

tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorageFile.cxx

In RPageStorageFile we're currently either writing all pages in a single vector write or, if their total size exceeds `maxKeySize`, we commit one at a time.
With this change we try to commit as many consecutive pages as possible and split the vector write as soon as the next page would exceed `maxKeySize`. If a single page is bigger than `maxKeySize` we take care to write it in the non-vectorized fashion, since splitting a key is only supported through `WriteBlob()`.

[ntuple] RPageStorageFile: commit vectorized pages in chunks

---

tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/test/ntuple_zip.cxx

Avoids some memory allocations when the internal unzip buffer is never used throughout the decompressor's lifetime (since RNTupleDecompressor allocates a Buffer_t when default constructed).
With this change, RPageStorageDaos doesn't need to allocate a decompressor anymore.

[ntuple] Make RNTupleDecompressor::Unzip overload static

---

gui/CMakeLists.txt
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindowsManager.cxx

`RBrowser` is no longer experimental and can be compiled once `webgui` is enabled.
It also required to implement file dialogs in other widgets (like TWebCanvas) therefore need to be compiled together.
Add `ROOT::RWebWindowsManager::SetUseConnectionKey` method to let change security settings via method call.
Before only rootrc file can be used.
Small fix in URL generation when token is used.

[webgui] always compile RBrowser (no root7), add `SetUseConnectionKey()` method

---

math/minuit2/src/SimplexSeedGenerator.cxx

fixes a warning due to an unused param in SimplexSeedGenerator (becomes a compile error with dev=ON)

[math] remove unused param from SimplexSeedGenerator::operator()

---

core/base/src/TUri.cxx

[core] Make TUri class PCRE2 compatible
PCRE2 has a stricter regular expression syntax parsing than PCRE.
Some non-conforming regular expressions that were accepted by PCRE are
correcrly rejected by PCRE2.
Some of the regular expressions used by the TUri class do not follow
the syntax rules and were relying on them being acceped by PCRE
anyway. This commit corrects the syntax of these expressions so that
they are now accepted by PCRE2. The corrected expressions still work
correctly with the old PCRE.
[core] Correct the regular expression for the scheme part in TUri class
RFC 3986 (https://datatracker.ietf.org/doc/html/rfc3986) defines the
scheme part of a URI as:
scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
The regular expression for finding the scheme part in the TUri class …

TUri fixes

---

core/base/src/TUri.cxx

Backport of #15988. Doesn't need to backported further, because 6.32 is the first release that supports PCRE 2.

[v632] TUri fixes for PCRE 2

---

tree/ntuple/v7/src/RNTupleDescriptor.cxx

This is a minor fix/improvement. The RNTupleReader will figure out the field ID if not set by RFieldDescriptor::CreateField() but this requires another descriptor lookup.

[ntuple] set id for unsplit field in RFieldDescriptor::CreateField()

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx

adds the use of `RClusterPool` to preload clusters during merging of RNTuples.

[ntuple] use RClusterPool in RNTupleMerger

---

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_processor.cxx

This PR adds the possibility to specify which fields should be read by the `RNTupleProcessor` by passing an `RNTupleModel` to its constructor. The processor will create and own an `REntry` based on this, but it will use the pointers from the model's default entry to hold the field values during iteration. This way, the pointers returned by `RNTupleModel::MakeField` can be used in the processor iteration to access the values being read.
Passing a model is optional; if not provided, one will be created from the descriptor of the first specified RNTuple.
A follow-up PR will add the possibility to change the model after the processor has been created (useful when the set of fields to read cannot be decided at compile-time).

[ntuple] Add `RNTupleModel` argument to `RNTupleProcessor` constructor

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx

When one runs with `root -b --web=server:port`,
http server will be started and widget URL will be printed. 
Before this commit -b flag fully suppress http server creation.
Partially resolves: https://root-forum.cern.ch/t/60086/

[webgui] disable web batch mode for `--web=server:port` 

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx

Backport of #15993 
When one runs with `root -b --web=server:port`,
http server will be started and widget URL will be printed. 
Before this commit -b flag fully suppress http server creation.
Partially resolves: https://root-forum.cern.ch/t/60086/

[webgui] disable web batch mode for --web=server [6.32]

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx

The call to `Unwrap` in the `RNTupleInspector` documentation is a remnant from when `Create` still returned an `RResult` pointer. This is not the case anymore, so the code example should reflect that.

[skip-ci][ntuple] Remove `Unwrap` from inspector doc

---

tmva/pymva/test/testPyKerasRegression.C

Given the very small statistics used (especially on MAcoS) due to th eslow time in evaluating we disable the check on the regression error obtained

[Pymva] disable regression keras check

---

gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webgui6/src/TWebCanvas.cxx
js/build/jsroot.js
js/modules/core.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/webwindow.mjs
ui5/canv/canvas.html
ui5/canv/canvas6.html

Up to now only Ctrl-R handler was able to correctly reload ROOT web window,
Now new connection key generated immediately after connection established and provided to the client.
Client insert new key in widget URL. Therefore direct page reload with browser buttons will work as well.
And reload can be started immediately - no need to wait on response from server.
Partially address https://root-forum.cern.ch/t/web-gui-in-root-6-32-00-how-to-handle-multiple-windows/60086/
Provide special handling for Qt5/Qt6/CEF displays - there disconnect event missing by reload 
and therefore newkey is not activated. 
In web canvas preserve reconnected client on first place if it was before. 
This ensure that only that client can modify canvas - all others are just "observers"

[webgui] Improve web page reload

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx

gives RNTupleMerger the capability of changing the source RNTuples' compression while doing the merging. This can also be used to change the compression of a single RNTuple.
Depends on #15954

[ntuple] Allow changing compression of sources in RNTupleMerger

---

tree/ntuple/v7/src/RNTupleMerger.cxx

Fix merge issue for latest commit (using `columnDesc.GetModel()` which was recently removed)

[ntuple] fix RNTupleMerger using old API

---

tree/ntuple/v7/src/RNTupleMerger.cxx

fixes a copy-paste error resulting in the wrong index being used to assign the new buffer to the sealedPage in RNTupleMerger.
This could result not only in errors in the merged file, but also in memory corruption.

[ntuple] fix wrong index being used in RNTupleMerger

---

interpreter/cling/README.md

I noticed an issue at https://github.com/root-project/cling/issues/515#issue-2092431022 created six months ago that describes the same problem. Sadly this issue has persisted for such a long time not fixed. 😣
I'm not certain if it's just me, but after spending an entire day to building Cling, CMake consistently reported that the target `nvptx` was not found. This is quite perplexing, especially for someone with limited experience with CMake like myself. After searching the LLVM repository, I discovered that the target name should be capitalized as `NVPTX`. If this is not just me, then there appears to be a discrepancy in the build guide.
Simply changed `nvptx` to `NVPTX`. Additionally, CMake requires the explicit passing of `-DCMAKE_BUILD_TYPE`, which I have included as well.
Fixes …

Update build guide for cling

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/test/backend/test_common.py

Revert is needed due to changes introduced with
PR #15672.

Revert "[rdf] Restrict distributed initialization to executors only"

---

bindings/pyroot/pythonizations/test/import_load_libs.py

Whitelist libtbbmalloc in library import test
```
6/1344 Test   #12: pyunittests-pyroot-import-load-libs .......................................***Failed    1.35 sec
test_import (import_load_libs.ImportLoadLibs.test_import)
Test libraries loaded after importing ROOT ... ERROR
======================================================================
ERROR: test_import (import_load_libs.ImportLoadLibs.test_import)
Test libraries loaded after importing ROOT
----------------------------------------------------------------------
Exception: Found not whitelisted libraries after importing ROOT:
- libtbbmalloc
If the test fails with a library that is loaded on purpose, please add it to the whitelist.
----------------------------------------------------------------------
Ran 1 test in 1.186s
FAILED …
```

[pyroot] Whitelist libtbbmalloc in library import test

---

roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
tutorials/roofit/rf508_listsetmanip.py

* Make ROOT compile again also with -DROOFIT_MEMORY_SAFE_INTERFACES
* Don't showcase `RooAbsCollection::addOwned()` in PyROOT
* Add overload of `RooAbsCollection::replace` for owning collections

[RF] Some improvements in RooFits memory management

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_test.hxx

- makes it so that RNTupleMerger reads the outFile's compression settings and changes the destination RNTuple's compression accordingly. Effectively, this allows users to select the out RNTuple compression with the `-f[0-9]` flag of `hadd`.
- fixes a couple of bugs in the compression changing code
- adds some tests for it
- related PR in [roottest](https://github.com/root-project/roottest/pull/1143)

[ntuple] fix change compression in RNTupleMerger, add tests

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx

The first commit is to directly fix the following scenario. Consider
```python
import ROOT
ROOT.gInterpreter.Declare("class foo{};")
ROOT.foo()
```
Then
```
$: valgrind python simple_class.py
```
Will report
```
==2728568== Mismatched free() / delete / delete []
==2728568==    at 0x4845B2C: free (vg_replace_malloc.c:985)
==2728568==    by 0x1380385C: Cppyy::Destruct(unsigned long, void*) (clingwrapper.cxx:716)
==2728568==    by 0x317B3E14: CPyCppyy::op_dealloc_nofree(CPyCppyy::CPPInstance*) (CPPInstance.cxx:222)
==2728568==    by 0x317B4563: CPyCppyy::op_dealloc(CPyCppyy::CPPInstance*) (CPPInstance.cxx:418)
==2728568==    by 0x4AA0834: subtype_dealloc (typeobject.c:2051)
==2728568==    by 0x498B90B: _PyEval_EvalFrameDefault.cold (generated_cases.c.h:256)
==2728568==    by 0x4AE8B35: …
```

Two updates to clingwrapper for memory management

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_project.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Projected fields, so far, were read back as plain fields. This is useful for typical reading use cases. When we want to merge, e.g., it is more useful however to reconstruct the model exactly as it was written, including the projected fields.
For this to work, the field mappings need to be written to disk (forward incompatible change). While projected fields use alias columns, not all fields have an attached column. So from the column relationship it is in general not possible to reconstruct the field relationship described by projected fields.
Note that we still don't support models with projected fields in the RNTuple reader. The reason is the mismatch between RNTupleReader and RNTupleWriter: the RNTupleWriter effectively writes all the fields, projected or not. The RNTupleReader, …

[ntuple] Add support for reconstructing projected fields

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/doc/tuning.md
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx

For the file backend only, map identical pages within a cluster to the same locator. That effectively de-duplicates identical pages on disk (not in memory though). 
As a result, reading code has to be able to deal with pages that don't necessarily reference pair-wise distinct byte ranges. This is difficult to combine with the DAOS caging feature. Same page merging needs explicit support from the backend and is turned off for the DAOS backend.
For the nanoAOD and ATLAS OpenData samples, same page merging reduces the file size by about 3.5%.

[ntuple] Deduplicate identical pages in a cluster

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

The current API forces the user to copy the entire fColumnRanges map and do a map lookup if they want to iterate the column ranges. With this change, one can simply access the underlying map directly, avoiding extra work in most cases.

[ntuple] replace RClusterDescriptor::GetColumnIds with GetColumnRanges

---

tree/ntuple/v7/src/RField.cxx

This reverts commit b5d751c069df2725dbc0d96bb1a6a677addc3895.
The problem that lead to adding additional debug output is understood and turned out to be a CMSSW memory issue.

Revert "[ntuple] add debug output to RVectorField"

---

core/foundation/inc/RtypesCore.h

C++ guarantees that `long long` has at least 64 bits, so we don't need the extra code for Windows.
FYI @jblomer @enirolf

[core] Simplify typedef of `[U]Long64_t`

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/tpython/src/TPython.cxx

Now that the CPyCppyy::ExecScript method is synced with the TPython
version, we can just call the CPyCppyy API in TPython::ExecScript.

[PyROOT] Implement TPython::ExecScript with CPyCppyy API

---

tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx

RPageSource and all its children are using exclusively the static version of RNTupleDecompressor::Unzip, so there's no need to keep it there for now.

[ntuple] remove RPageSource::fDecompressor

---

math/mathcore/test/testGradient.cxx
roofit/roofitcore/test/testRooRombergIntegrator.cxx

Found by the conda nightly 
```
2024-07-17T04:49:33.5552609Z /home/conda/feedstock_root/build_artifacts/root_base_1721190805440/work/root-source/math/mathcore/test/testGradient.cxx:467:36: error: 'setprecision' is not a member of 'std'
2024-07-17T04:49:33.5632853Z   467 |    std::cout << std::fixed << std::setprecision(4);
```

[math][roofit] Include missing header in two tests

---

gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowWSHandler.hxx
net/http/inc/THttpServer.h
net/http/inc/THttpWSHandler.h
net/http/src/THttpServer.cxx

Only backport functionality to insert `importmap` script into HTML files.
If no magic string appears in HTML code - old functionality will be used.
Let use newer JSROOT with older ROOT versions.
Also let use jsroot ES6 modules directly in HTML files.

[webgui] support importmap in `THttpServer` [6.32]

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx
tutorials/v7/ntuple/ntpl008_import.C

- RNTupleInspector::Create
- RNTupleReader::Open (2 overloads)

[ntuple] replace pointers with references in some factory API

---

gui/canvaspainter/src/RCanvasPainter.cxx
gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
js/build/jsroot.js
js/modules/base/TAttFillHandler.mjs
js/modules/core.mjs
js/modules/draw/TArrowPainter.mjs
js/modules/draw/TPolyLinePainter.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/hist/TF1Painter.mjs
js/modules/hist/TF2Painter.mjs
js/modules/hist/TPavePainter.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/webwindow.mjs
net/http/src/THttpServer.cxx
tutorials/webgui/ping/ping.cxx
tutorials/webgui/ping/ping.html
ui5/browser/browser.html
ui5/browser/controller/Browser.controller.js

Fix URL handling when widgets are embed and many connections must be established from same browser tab
Now any widget URL must include connection key therefore workaround with relative URL like `../win2/root.websocket`  no longer works.
Remove duplicated entry in "importmap", Use "importmap" in `RBrowser`
Generate new connection key only by direct request from client

[webgui] fix widgets embeding

---

net/http/src/THttpServer.cxx

"jsrootsys/" appears two times which was not correct Improve formatting
Backport from #16056

[http] exclude duplicated entry from generated importmap [6.32]

---

.github/workflows/root-ci-config/build_root.py

Revert the changes to `build_root.py` from commit 542b98b2cc ("[ci] Add alma9 clang build") since they were not reflected when uploading the artifacts which could consequently not be found. The extra logic of appending the image doesn't seem needed, the compiler is part of the options.

[ci] Restore incremental builds

---

core/metacling/src/CMakeLists.txt

Fix an issue reported on the forum: https://root-forum.cern.ch/t/windows-stream-failed-to-materialize-symbols

[skip-ci] Fix MSVC version for exporting symbols

---

core/metacling/src/CMakeLists.txt

Fix an issue reported on the forum: https://root-forum.cern.ch/t/windows-stream-failed-to-materialize-symbols

[skip-ci][v6-32] Fix MSVC version for exporting symbols

---

builtins/cfitsio/CMakeLists.txt

Like this, we make sure the static library is where we expect it to be: `CFITSIO-prefix/lib/libcfitsio.a`, and not for example in the `lib64` directory.
This is already done for other builtins, like `xrootd` and `zeromq`.
Inspired by this forum post:
https://root-forum.cern.ch/t/6-32-02-will-not-build-from-source-with-option-dbuiltin-cfitsio/60270

[CMake] Always use `lib` as library directory in builtin CFITSIO prefix

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/rfield_class.cxx

For custom classes with dictionaries, store the streamer checksum in the field metadata. The checksum is used to apply read rules that use checksums to identify the source class.

[ntuple] Store streamer checksum if available

---

roofit/roofit/test/testRooCrystalBall.cxx

The memory leaks were introduced on purpose in that test, but they are probably not necessary anymore.
Also, suppress unneeded logging and format code.

[RF] Fix memory leaks in testRooCrystalBall

---

tree/ntuple/v7/src/RNTupleMerger.cxx

This was added in commit d950e9903a ("[ntuple] use RClusterPool in RNTupleMerger") with no explicit mention, and I believe it's wrong because every column yields exactly one page group that contains all pages for that column.

[ntuple] Remove incorrect std::vector::reserve

---

gui/webdisplay/src/RWebWindowsManager.cxx

Fix compile error (happening with `DEV=on` due to missing include):
```
/home/jp/root/gui/webdisplay/src/RWebWindowsManager.cxx:215:13: error: no matching constructor for initialization of 'TIter'
TIter next(arr);
^    ~~~
/home/jp/root/core/cont/inc/TCollection.h:244:4: note: candidate constructor not viable: cannot convert argument of incomplete type 'TObjArray *' to 'const TCollection *' for 1st argument
TIter(const TCollection *col, Bool_t dir = kIterForward)
^
/home/jp/root/core/cont/inc/TCollection.h:246:4: note: candidate constructor not viable: cannot convert argument of incomplete type 'TObjArray *' to 'TIterator *' for 1st argument
TIter(TIterator *it) : fIterator(it) { }
^
/home/jp/root/core/cont/inc/TCollection.h:247:4: note: candidate constructor not viable: cannot convert …
```

[gui] fix compile error in RWebWindowsManager.cxx

---

tree/ntuple/v7/src/RNTupleMerger.cxx

Moves some code out of the parallel tasks in RNTupleMerger (particularly, `ThrowOnError` which is not necessarily happily parallelizable).
It also avoids spawning the parallel tasks if not needed, i.e. if we don't need to change the compression of the pages.

Ntuple merger fixes

---

net/rpdutils/CMakeLists.txt
net/rpdutils/src/DaemonUtils.cxx
net/rpdutils/src/DaemonUtils.h
tutorials/net/authclient.C
tutorials/net/authserv.C

Fixes https://github.com/root-project/root/issues/13387
Reported by @xkzl
DaemonUtils files have been restored from latest version before removal by @amadio in https://github.com/root-project/root/pull/2704 although it is unclear to me how these files ended up reaching SrvAuth, as they were removed from the glob there before that change (and in another target).
Edit: Probably the problem dates back to the change from Make to CMake, see https://github.com/root-project/root/blob/79d2161aa4df0f169b2821db05e8254cdfda746c/net/auth/Module.mk vs https://github.com/root-project/root/blob/79d2161aa4df0f169b2821db05e8254cdfda746c/net/auth/CMakeLists.txt

[net] Restore files erroneously removed from SrvAuth library

---

bindings/r/inc/TRInternalFunction.h

From the Rcpp changelog:
* inst/include/Rcpp/: Added variadic templates to be used instead of
the generated code in `Rcpp/generated` and `Rcpp/module` when
compiling with C++11 or later.
This PR adapts ROOT's R interface code to this change,

Update ROOT's R interface for Rcpp 1.0.13

---

roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
roofit/RDataFrameHelpers/test/testActionHelpers.cxx
roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/RooAbsDataFiller.h
roofit/roofitcore/src/RooAbsDataFiller.cxx

Support weighted filling from RDF to RooFit in RooAbsDataHelper and also
implement a test for it.
Closes https://github.com/root-project/root/issues/7223.

[RF] Support weighted filling from RDF to RooFit in RooAbsDataHelper

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx

Currently RColumnDescriptorIterable's ctor wants a RFieldDescriptor even though it only uses the field's id internally. One of the overloads of GetColumnIterable accepts a fieldId but it is forced to retrieve back the field descriptor before constructing an Iterable object, only for the object itself to extract back the id, wasting work.

[ntuple] change RColumnDescriptorIterable to accept a fieldID

---

roofit/roofitcore/inc/RooAbsSelfCachedReal.h
roofit/roofitcore/inc/RooArgSet.h
roofit/roofitcore/inc/RooSimGenContext.h
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooCompositeDataStore.cxx
roofit/roofitcore/src/RooConvGenContext.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooErrorVar.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/src/RooSimGenContext.cxx
roofit/roofitcore/src/RooVectorDataStore.cxx
roofit/roofitcore/src/RooWorkspace.cxx
roofit/roofitcore/src/TestStatistics/ConstantTermsOptimizer.cxx
roofit/roofitcore/test/testProxiesAndCategories.cxx

The difference is only that the return type is casted to the actual
`RooArgSet` type. We avoid a few static casts all over the place like
this.
A second commit in this PR applies some general improvements in memory management.

[RF] Implement RooArgSet::selectCommon() and selectByName()

---

README/ReleaseNotes/v634/index.md
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/test/testRooAbsCollection.cxx

Setting `useHashMapForFind(true)` is not supported for RooArgLists
anymore, since hash-assisted finding by name hash can be ambiguous: a
RooArgList is allowed to have different elements with the same name.
If one wants to use name-lookups on a RooArgList, one can just convert
it to a RooArgSet, which is cheap anyway (copy of a vector of pointers).
Also inside RooFit itself, `useHashMapForFind` is only used for
RooArgSets, most notably the RooArgSet that contains all the components
of a RooWorkspace.
Closes https://github.com/root-project/root/pull/9425.

[RF] Forbid RooArgList::useHashMapForFind(true)

---

gui/browsable/src/RFieldProvider.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldVisitor.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/ntuple_view.cxx

This already used to work for some types, such as `int`, which happen to have the same underlying storage as a fixed width type. This change adds a general `RIntegralTypeMap` with specializations for standard integer types. As a result, RNTuple gains support for `(unsigned) long long` on Linux, which is now mapped to `[u]int64_t`.

[ntuple] Map integral types to fixed width equivalents

---

tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_model.py

`RPageSinkBuf` internally clones the model, which also allocates the column page buffers.

[ntuple] Account for buffer model in memory estimation

---

README.md
roofit/doc/index.md
roofit/roofit/doc/index.md
roofit/roofitcore/inc/RooGlobalFunc.h
roofit/roostats/doc/index.md

Since we re-organized a few things on the website, the links in doxygen need to be updated accordingly.

[skip-ci] correct a few  website links in doxygen

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx

It's not needed anymore since we can now just take the column ids from the field descriptor.

[ntuple] remove CollectColumnIds from ColumnIterable

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_checksum.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/ntuple_test.cxx
tree/ntuple/v7/test/ntuple_test.hxx

Provides the foundations for multiple, alternative column representations of a single field. Extends the binary format to store multiple sets of columns per field and handles (de-)serialization and the descriptor representation (backwards compatible).
A follow-up PR will use this capability from the RField/RColumn classes.

[ntuple] Multiple column representations: foundation

---

interpreter/cling/docs/chapters/implementation.rst

[skip-ci] fix typo in cling docu

---

js/build/jsroot.js
js/changes.md
js/modules/core.mjs
js/modules/hist2d/TH1Painter.mjs
js/modules/hist2d/THistPainter.mjs
tutorials/hist/haxis.C

"haxis" draw option draw histogram axis as for hbar - with swapped X/Y. 
Swapped axis must be specially handled by painters.
Therefore only limited options are supported for TH1.
These are: B - bar, P - marker, L - line, TEXT
Provide demo macro "haxis.C"

[web graphics] support of haxis draw option

---

io/io/src/TFileMerger.cxx
main/src/hadd.cxx

Currently hadd is only checking the compression levels to determine whether fast merging should be used or not. This is wrong, as it will incorrectly skip compression change when a file is changed from e.g. 101 to 201. With this commit, hadd (actually, TFileMerger) will check for equality of compression settings instead.
This PR fixes #11245

[hadd] properly change compression when levels are the same

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/Backends/Dask/Backend.py
bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
bindings/experimental/distrdf/python/DistRDF/HeadNode.py

Every worker stores the RDataFrame created and the computation graph jitted during the first task in a process-wide dictionary serving as a cache. This is required in order to avoid having to re-jit the computation graph at each task.
This commit introduces a post-execution cleanup job for the Dask workers so that when a distributed execution ends, the workers are instructed to remove the artifacts generated by the execution from the caches.
In particular, if the RDataFrame execution was processing a TTree-based dataset, removing the artifact from the cache also notably deallocates the corresponding TTreeCache, one per RDataFrame in-flight in the process.
Here are some memory usage flamegraphs obtained with memray running the AGC analysis script
https://cernbox.cern.ch/s/YPEmBfULdvy8CbN …

[df] Cleanup execution artifacts from worker caches in Dask

---

tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/src/RField.cxx

For all fields but the nullable field, all the column representations of a given field have the same in-memory type. This is used to create a central helper in `RFieldBase` that implements the column creation logic, given the list of in-memory types.

[ntuple] Streamline RField<>::GenerateColumns()

---

roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx

Updates the HistoToWorkspaceFactoryFast code to add an option to disable the per-region WS production. This might be relevant in cases where the WS creation takes a long time as the per-region WS might not be needed in many cases

[RF] Add an option to disable per-region WS creation in HistFactory

---

README/ReleaseNotes/v634/index.md
core/dictgen/src/rootcling_impl.cxx

to easily get the rootcling invocation that corresponds to the current genreflex invocation, to ease the migration from genrelfex to rootcling.
Update the genreflex usage as well, stating that the tool does not support C++ modules generation.
Memorialise the change to the Release Notes, too.
Fixes #13481

[dictgen] Introduce --print-rootcling-invocation for genreflex

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_types.cxx

Makes the following changes:
- The default representation is now always a vector of 0/1 elements. There are very few cases where the bitmask plus default constructed NULL values are better. Users now need to explicitly request that representation.
- Remove IsDense(), IsSparse(), which will be hard to maintain once the representation can change from cluster to cluster
- Use kSplitIndex64 (instead of 32bit) as a default column type for the vector representation
Fixes #12842

[ntuple] fix column representation of nullable field

---

hist/histpainter/src/TGraphPainter.cxx

This PR fixes the 1st issue described here: https://github.com/root-project/root/issues/16070
When error-bars exceed to y range limits the end of error bars are nevertheless displayed on the x-bottom and top axis. So it looks like it is the total error bar while it is indeed not.

Non correct display of error bars when exceeding y-range

---

tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

The cluster descriptor should contain no page range for suppressed columns. This fix prevents the accidental creation of an empty page range during deserialization of the page list.

[ntuple] ensure empty page ranges for suppressed columns

---

tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx

Moves the task of finding the page number for a given column and element index into the `RPageSource` base class. This code was implemented twice, in the file source and the DAOS source. There is, I think, still room for improvement for the `PopulatePage()` API but that's for another PR.

[ntuple] remove code duplication in PopulatePage()

---

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
tree/ntupleutil/v7/src/RNTupleImporter.cxx
tree/ntupleutil/v7/test/ntuple_importer.cxx

This provides a mechanism to adjust the column representation (and other things, such as the field description) in the model created by the RNTupleImporter. We can use it, e.g., to import the AGC with half-precision floats.

[ntuple] add field modifier to importer

---

graf2d/gpad/src/TCanvas.cxx

Fixes https://github.com/root-project/root/issues/16051
What I did was to copy using the full constructor which updates the list.
Another solution could to be change the Streamer so that it interacts with the list of colors directly, but don't know how to.

[gpad] update list of free colors when streaming canvas from file

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx

Direct I/O bypasses the OS page cache and allows to reach much higher bandwidths. However, it introduces strict alignment requirements to the offset and size of all write requests, as well as the userspace pointer.

[ntuple] Add option to enable Direct I/O

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RPage.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_importer.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

Completes the support for fields with multiple column representations. For the moment, only the unit tests can change the column representation between clusters on writing. Eventually, we may add a proper interface. Merging will also lead to this situation.
In all cases but the nullable field, we can exploit the fact that the number of columns of multiple representations is the same and the corresponding columns have the same number of elements and cluster boundaries. Therefore, when reading we team up the corresponding columns of multiple representations. When we map another page, the column teams can then figure out amongst each other the column that is not suppressed for the given page / element index and forward the call.
Follow-up of #16054

[ntuple] Multiple column representations: high-level support

---

interpreter/cling/lib/Utils/ParserStateRAII.cpp

Upstream Clang keeps `TemplateIdAnnotation`s around "if they might still be in the token stream." See upstream commit for more details: https://github.com/llvm/llvm-project/commit/6163aa96799cbad7f2f58e02c5bebee9647056a5 (included in Clang 11, in ROOT since the upgrade to LLVM 13)
This reasoning doesn't apply when we fully reset the `Parser` state in `ParserStateRAII`'s destructor, and we expect the swapped out vector of `TemplateIdAnnotation`s to be empty in order to not leak.
Fixes #16121

[cling] Forcefully clean up `TemplateIdAnnotation`s

---

interpreter/cling/lib/Utils/ParserStateRAII.cpp
tree/ntuple/v7/doc/architecture.md
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx
tutorials/v7/ntuple/ntpl008_import.C

Builds on https://github.com/root-project/root/pull/16150

[ntuple] Fix some issues found by Valgrind

---

bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.h
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx

Applying the following commit from CPyCppyy upstream: https://github.com/wlav/CPyCppyy/commit/9a792b231c73452d08686ea83c6588f5e98ca9a7
Closes #1523.

[CPyCppyy] Auto-cast elements of std::vector<T*>, with T a class type

---

gui/webdisplay/src/RWebDisplayHandle.cxx

By mistake all created file names - including paths - were transformed into lower case.
Backport of #16154

[webgui] fix usage of lower case in saved file names [6.32]

---

gui/webdisplay/src/RWebDisplayHandle.cxx

By mistake all created file names - including paths - were trnasformed into lower case.

[webgui] fix usage of lower case in saved file names

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roocategory.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodatahist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimultaneous.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_utils.py
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooGlobalFunc.h
roofit/roofitcore/inc/RooSimultaneous.h
roofit/roofitcore/src/RooGlobalFunc.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
tutorials/CMakeLists.txt

Introduce an internal elper class to build a map object that only uses `std::vector`, which can be implicitly converted to `std::map` in C++.
This avoids using `std::map` in pythonizations, which can cause assertion failures in Windows debug builds.

[RF] Avoid using `std::map` in RooFit pythonizations

---

tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx

Since commit 3b623b2cfa ("[DF] Use dtors to perform clean-up tasks in column readers"), the destructor resets the `std::unique_ptr` holding a `TTreaderValue`, which is the default of the pointer's destructor.

[DF] Simplify RTreeColumnReader destructor

---

io/io/src/TStreamerInfoActions.cxx

Fixes https://github.com/root-project/root/issues/8194

[io] prevent nullptr access if oldclass not found

---

bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/API.h
bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx

This PR fixes https://github.com/root-project/root/issues/15161
Applying the following commit from CPyCppyy upstream:
https://github.com/wlav/CPyCppyy/commit/9a792b231c73452d08686ea83c6588f5e98ca9a7
Adds a Sequence_Check which does not pass objects not supporting indexing.

[PyROOT] Add Sequence_Check to the public API

---

bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/API.h
bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx

Backporting fix from https://github.com/root-project/root/pull/16180
Applies the following commit from CPyCppyy upstream: wlav/CPyCppyy@a02ceeb
Closes #15161.

[v632][PyROOT] add Sequence_Check to the public API

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPEnum.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPExcInstance.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
bindings/pyroot/cppyy/CPyCppyy/src/TupleOfInstances.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx
bindings/pyroot/cppyy/cppyy/doc/source/changelog.rst
bindings/pyroot/cppyy/cppyy/doc/source/conf.py
bindings/pyroot/cppyy/cppyy/etc/valgrind-cppyy-cling.supp
bindings/pyroot/cppyy/cppyy/test/Makefile
bindings/pyroot/cppyy/cppyy/test/advancedcpp.h
bindings/pyroot/cppyy/cppyy/test/stltypes.cxx
bindings/pyroot/cppyy/cppyy/test/test_api.py
bindings/pyroot/cppyy/cppyy/test/test_fragile.py
bindings/pyroot/cppyy/cppyy/test/test_leakcheck.py
bindings/pyroot/cppyy/cppyy/test/test_overloads.py
bindings/pyroot/cppyy/cppyy/test/test_regression.py
bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
bindings/pyroot/cppyy/patches/CPyCppyy-Revert-Fix-bugs-introduced-by-73cbd9bde436afbc6e4d39.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Revert-do-not-allow-implicit-conversions-to-an-std-s.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Revert-don-t-allow-implicit-conversions-for-string_v.patch
bindings/pyroot/cppyy/patches/CPyCppyy-TString_converter.patch
bindings/pyroot/cppyy/sync-upstream

Closes #15104.
Thank you very much @wlav for helping out here!
Also adds revert patches for a sequence of upstream commits that broke our `string_view` conversion usecases. Needs to be followed-up later.
Needs to be backported to 6.32.

[PyROOT] Sync with upstream cppyy

---

bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx

Fixes https://github.com/root-project/root/issues/15315
This enables the failing example in the manual with `ROOT.Math.IMultiGenFunction` that failed due to an invalid zero initialization of an `unsigned int`

[v632] [PyROOT] Perform function-style casts when returning multi-keyword types

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_conversion_maps.py

The `np.float_` was removed in the NumPy 2.0 release. One should use `np.float64` instead, which is already in the same dictionary.

[PyROOT] Avoid using deprecated `numpy._float`

---

interpreter/cling/include/cling/Utils/ParserStateRAII.h
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/IncrementalParser.cpp
interpreter/cling/lib/Interpreter/Interpreter.cpp
interpreter/cling/lib/Interpreter/LookupHelper.cpp
interpreter/cling/lib/Utils/ParserStateRAII.cpp

We are relying on this since a while, for example for reemission of template symbols. At the moment, we get the incremental extensions because `Preprocessor::enableIncrementalProcessing()` turns them on internally, but this will change with LLVM 18 where this method only controls incremental processing of a single `Preprocessor` object.
---
This should mean no change in `master` with LLVM 16, but given that we already rely on this we should enable the incremental extensions properly outside of the upgrade to LLVM 18.

[cling] Globally enable incremental extensions

---

README/ReleaseNotes/v634/index.md
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/src/RooAbsReal.cxx

The `RooAbsReal::plotSliceOn()` function that was deprecated since at least ROOT 6 was removed. Use `plotOn(frame,Slice(...))` instead.

[RF] Remove `RooAbsReal::plotSliceOn()`

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

I discovered that the current 6th-order polynominal + exponential interpolation (interpCode 5 in PiecewiseInterpolation class, 4 in FlexibleInterpVar class) does something quite bizarre if the nominal value is not equal to 1. See:
```
RooRealVar alpha("alpha","alpha",-5,5);
RooRealVar nom("nom","nom",10);
RooRealVar up("up","up",11);
RooRealVar down("down","down",9);
PiecewiseInterpolation pi("pi","pi",nom,{down},{up},{alpha});
pi.setAllInterpCodes(5);
TGraph gr;
alpha = -3;
while (alpha.getVal()<3) {
gr.AddPoint(alpha.getVal(),pi.getVal());
alpha.setVal(alpha.getVal()+0.1);
}
gr.Draw("ALP");
```
This strange behaviour can be fixed with the proposed modification, which doesn't affect the behaviour of the usual FlexibleInterpVar where nominal = 1. (i.e. it is used as a scale factor). 
This …

[RooFit] : fix 6thorder+exponential interpolation if nominal is not equal to 1

---

requirements.txt

This reverts commit d6b623fff5a6d47ae66ec6db09dad26e987deb4e to no longer restrict numba versions to <0.6 which also unlocks support for numpy 2.0. The corresponding PR in rootest (https://github.com/root-project/roottest/pull/1162) updates the error style in the numba test to be backwards compatible.
The numpy version is temporarily locked to below 2.0 to prevent both upgrades at the same time.
Fixes https://github.com/root-project/root/issues/16201

[ci] Revert Numba restrictions and lock NumPy version for upgrades

---

tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TTreeReader.cxx

therewith avoiding memory hogging because of the attached TTreeChaches.
This code has been written by David Smith and minimally edited for its integration in root.
See sister PR in roottest: https://github.com/root-project/roottest/pull/1161
This PR fixes [ROOT-6286](https://its.cern.ch/jira/browse/ROOT-6286)

[TTreeReader] Properly cleanup non-owned chains

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/src/RDFActionHelpers.cxx

Clang 18 changed the name mangling of function templates, see https://releases.llvm.org/18.1.0/tools/clang/docs/ReleaseNotes.html#c-specific-potentially-breaking-changes
The first mentioned case is "When a template parameter in a function template depends on a previous template parameter", for example:
```
struct A {
template <typename T, std::enable_if_t<std::is_integral_v<T>, int> = 0>
void Member(T p) {}
};
template void A::Member(int);
```
With Clang < 18 and current versions of GCC, this will mangle to `_ZN1A6MemberIiLi0EEEvT_`, but Clang 18 and later will mangle it to `_ZN1A6MemberIiTnNSt9enable_ifIXsr3stdE13is_integral_vIT_EEiE4typeELi0EEEvS2_` (unless reverted for compatibility with `-fclang-abi-compat=17`).
For ROOT's use of Cling, this poses a bidirectional problem:
* If …

[DF] Remove extern template function declarations

---

core/base/src/TApplication.cxx

Currently this is the behaviour
```
~> root -b -q -l NotExistingFile.C
Warning in <TApplication::GetOptions>: macro pippo.C not found
root: unrecognized option 'pippo.C'
Try 'root --help' for more information.
~> echo $?
0
```
the root executable simply warns about the file not existing but returns 0, as everything went well. This has several downsides, including not protecting us from our typos when adding tests to the suite (see original JIRA issue)
- [v] updated the docs (if necessary)
This PR fixes [ROOT-9365](https://its.cern.ch/jira/browse/ROOT-9395)

[core] Return 2 if root macro.C and macro.C does not exist as it is done for the Python interpreter

---

README/ReleaseNotes/v634/index.md
roofit/roofit/src/RooNonCPEigenDecay.cxx
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooNLLVarNew.cxx
roofit/roofitcore/src/RooNormalizedPdf.h
roofit/roofitcore/src/RooSuperCategory.cxx

Add methods to create owning RooFit proxies via `std::unique_ptr`.
At the same time, deprecate the constructors with manual memory
ownership.

[RF] Add methods to create owning RooFit proxies via `std::unique_ptr`

---

requirements.txt

Constrain requirements to numpy 1.26.4 and minimum numba version for py3.8

[ci] Lock max numpy, min numba version

---

.github/workflows/root-ci.yml

Until the issue with module maps https://github.com/root-project/root/issues/16219 is fixed.

[ci] Temporarily disable the mac-beta builds

---

cint/cint/src/init.cxx

Fixes a "buffer overflow" in `G__defineMacro` of `cint`, where `snprintf` is given buffer length that is 1 byte longer that the actual buffer.
It is seems like this never caused any actual buffer overflows - at least while building ROOT, where `cint` or rather `rootcint_tmp` is already used. However, this causes issues in certain scenarios, where GCC's (?) fortify mechanism causes `cint` (or rather `rootcint_tmp`) to abort during `G__DEFINE_MACRO(__linux__);`.
Notes on my encounter with this issue:
- using GCC 13.2.0 on Ubuntu 24.04
- does not occur in `Debug` build mode, but was debuggable when using `RelWithDebInfo`
- the ROOT version is some legacy patched tarball apparently based on v5.34.00
I did not reproduce this issue using this branch, nor do I plan to, since I encountered other …

Fix buffer overflow in cint's G__defineMacro

---

interpreter/cling/lib/Interpreter/CIFactory.cpp

It is "a deprecated technique".

[cling] Turn off delayed template parsing on Windows

---

tree/ntupleutil/v7/src/RNTupleImporter.cxx
tree/ntupleutil/v7/test/ntuple_importer.cxx

When `SetConvertDotsInBranchNames`, dot characters in field names are converted into underscores. This flag previously did not take into account count leafs, which in the RNTuple are represented as a projected fields. With this commit, the conversion is also done for these kinds of fields.

[ntuple] Convert count leaf names for `SetConvertDotsInBranchNames`

---

hist/hist/src/TProfile2D.cxx
hist/hist/test/test_projections.cxx

these two lines will ensure any bin labels are propagated to projection histograms

Update TProfile2D.cxx - copy all attributes of axis to projection histograms

---

README/ReleaseNotes/v634/index.md
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py

Call typed overload of `SetBranchAddress` for array types like `np.ndarray` or `array.array`. The correct C++ template parameter is inferred from the array interface type information.
This is an improvement for two reasons:
1. We don't need to cast the arrays to a `void *` to avoid template resolution problems anymore.
2. More importantly: ROOT will do a runtime check for type compatibility, which was requested in the JIRA ticked linked below.
To see the benefit of the added type check, take for example this code, where the branch address is set to an array address with a mismatched type:
```python
import array
import ROOT
def create():
f = ROOT.TFile("dummy.root", 'RECREATE')
t = ROOT.TTree("tree", 'A tree')
a = array.array('f', [42])
br = t.Branch('a', a, 'a/F')
for x in (21, 42, 1337): …
```

[PyROOT] Call typed overload of `SetBranchAddress` for array types

---

graf3d/gl/src/gl2ps.cxx
net/rpdutils/src/DaemonUtils.cxx

changes a couple of usages of `vsprintf` to `vsnprintf` to fix some compiler warnings

[net][graf3d] fix some warnings (vsprintf -> vsnprintf)

---

cmake/modules/RootMacros.cmake
roofit/roofitcore/test/CMakeLists.txt

The comments in `ROOT_ADD_GTEST` suggest that the macro can also be used
in your own projects based on ROOT, only that when ROOT was configured
with `testing=OFF`, the ROOT::TestSupport library is not available.
However, in the case where ROOT::TestSupport is not available, the
ROOT_ADD_GTEST macro is dysfunctional because the linkage against
`gtest` is missing. It is only indirectly picked up via
ROOT::TestSupport. This breaks the compilation of all tests, even if
they don't use the TestSupport library. To make this work again without
the user having to explicitly link against `gtest`, this PR suggests
to always link against `gtest` in the ROOT_ADD_GTEST macro.
Also, make the linking against ROOT::TestSupport in RooFit tests explicit.

[CMake] Always link against gtest in ROOT_ADD_GTEST 

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_test.hxx

clang-format some files + add some typedefs to `ntuple_test.hxx` to reduce namespace noise in the tests

[ntuple] clang-format pass

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Fixes the following potential error when building clad:
```
Command failed: 2
‘/usr/local/bin/cmake’ ‘–build’ ‘.’ ‘–config’ ‘.’
```

[v6-32][cmake][clad] Fix potential Clad build error

---

README/ReleaseNotes/v634/index.md
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
roofit/roofit/CMakeLists.txt
roofit/roofit/inc/LinkDef1.h
roofit/roofit/inc/RooMomentMorphFuncND.h
roofit/roofit/inc/RooPyBindFunction.h
roofit/roofit/src/RooMomentMorphFuncND.cxx
roofit/roofit/src/RooPyBindFunction.cxx
tutorials/CMakeLists.txt
tutorials/roofit/rf615_simulation_based_inference.py

- created new tutorial for simulation based inference (SBI)

[RF] Add tutorial SBI

---

cmake/modules/RootMacros.cmake

Following up on 1bd63965cf1 to avoid warnings like these on macOS:
```
ld: warning: ignoring duplicate libraries: 'googletest-prefix/src/googletest-build/lib//libgtest.a'
```

[CMake] Avoid duplicate linking against gtest

---

core/base/src/TSystem.cxx
core/metacling/src/TCling.cxx

Sets the verbosity level of rootcling in ACLiC to the default, therewith printing also warnings and not only fatal errors.
This PR fixes [ROOT-10975](https://its.cern.ch/jira/browse/ROOT-10975)
Linked roottest PR https://github.com/root-project/roottest/pull/1168 and  https://github.com/root-project/roottest/pull/1169, that fixes a test which becomes broken once the verbosity is increased because some unused rules start to generate warnings. The rules are unused simply because the name of some template instantiations are not spelled correctly.

[Core] ACLiC: set default verbosity level for rootcling

---

tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/test/basic.cxx

instead of allowing a spurious iteration with zero entries.
Fixes #16249

[treereader] Correctly treat empty trees with range loop iteration

---

graf2d/asimage/src/libAfterImage/config.guess

Now that `builtin_afterimage` is deprecated and always `ON`, it has to build on all platforms. Update `config.guess` to the latest upstream version to auto-detect `riscv64-unknown-linux-gnu` and fix the build.

[afterimage] Update to latest config.guess

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

Commit 785c9df34d ("Restore symbol lookup in child interpreters") added a `DefinitionGenerator` to allow symbol lookup in the parent `IncrementalJIT` after the upgrade to LLVM 13. It appears that instead of the unmangled name, we need to lookup already linker mangled names.
This fixes the tests `CodeUnloading/AtExit.C` and `MultipleInterpreters/MultipleInterpreters.C` on macOS, which adds an underscore during linker mangling. No change on Linux because there is no additional linker name mangling.

[cling] Fix `DelegateGenerator` on macOS

---

cmake/modules/SearchInstalledSoftware.cmake

Our CMake code modifies `find_package` to ignore any ROOT builtins, such that the builtin LLVM doesn't find and use system versions of the builtin dependencies.
This is a bit hacky, but fortunately this needs to be done only when builtins are used.
Therefore, this commit suggests to only do this redefinition of `find_package` if any builtins are used.
This closes #8633, where it was requested to avoid this hack for the sake of being compatible with the `vcpkg` package manager.
Although the hack is not completely removed, it is removed for the case where not builtins are used, which is probably what is done when using a C++ package manager to manage dependencies.

[CMake] Only replace `find_package` if required

---

core/base/inc/TSystem.h
core/unix/src/TUnixSystem.cxx

@vepadulano @dpiparo 
This PR fixes
- https://github.com/root-project/root/issues/7196
This issue is very case-dependent.
When trying to calculate memory usage, normally the actual free memory on the system is `free + buffer + cached `
If shared memory usage is high (e.g mmaping a big cache) the calculation is slightly different:
`(free + buffer/cache) - shared`
The author of **htop** mentions on [this](https://stackoverflow.com/questions/55090900/how-can-i-calculate-memory-utilisation-of-a-linux-server-using-sar-report) question that htop uses this convention(in 2016):
- Total used memory = MemTotal - MemFree
- Non cache/buffer memory = Total used memory - (Buffers + Cached memory)
Now htop (managed by htop-dev) uses this (on https://github.com/htop-dev/htop/blob/main/linux/LinuxMachine.c …

[TUnix] RAM stats (gSystem->GetMemInfo) to htop/procps style

---

cmake/modules/SearchInstalledSoftware.cmake

This reverts commit 2a265a3a, which caused failures in the nightlies even though the CI in #16274 was green.

Revert "[CMake] Only replace `find_package` if required"

---

cmake/modules/RootMacros.cmake
roofit/roofitcore/test/CMakeLists.txt

Backport two PRs to fix the usage of the `ROOT_ADD_GTEST` macro in builds with `testing=OFF`.
* https://github.com/root-project/root/pull/16243
* https://github.com/root-project/root/pull/16255

[v632][CMake] Fix ROOT_ADD_GTEST in builds with `testing=OFF`

---

interpreter/cling/tools/packaging/cpt.py

This PR fixes #406 mentioned in meta-issue list (https://github.com/root-project/cling/issues/406)

[cling-cpt] Formatted the beginning functions of the cpt [skip-ci]

---

tutorials/.enableImplicitMTWrapper.py
tutorials/CMakeLists.txt

to avoid excessive memory usage, which can lead to issues on machines with a low memory per core.
- [v] updated the docs (if necessary)
Fixes #16252

[Tutorials] Fix Thread Pool size for tutorials

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py

Improve the error message when you try to build NumPy arrays with types
that the interpreter doesn't know about.
Running the reproducer from the JIRA ticket, one now gets this output:
```txt
TClass::Init:0: RuntimeWarning: no dictionary for class Foo is available
{ "a", "b", "foo", "foo.a", "foo.b" }
File "/home/rembserj/root-support/jira/ROOT-10930/reproducer.py", line 13, in <module>
print(df.AsNumpy())
^^^^^^^^^^^^
File "/home/rembserj/spaces/master/install/lib/root/ROOT/_pythonization/_rdataframe.py", line 243, in RDataFrameAsNumpy
raise RuntimeError(
RuntimeError: The column named "foo" is of type "Foo", which is not known to the ROOT interpreter. Please load the corresponding header files or dictionaries.
```
This was the output before:
```txt …
```

[PyROOT] Improve error handling for AsNumpy with unreadable objects

---

tree/tree/src/TFriendElement.cxx

Return value of `Compress()` function must be always deleted

[tree] fix potential memory leak in TFriendElement constructor

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx

moves most of the nested classes definitions in RNTupleDescriptor.cxx out of line, for ease of reading.
(Unfortunately, since the types are all public, they cannot be moved to the cxx).

[ntuple] RNTupleDescriptor: moved nested type defs out of class

---

math/matrix/inc/TMatrixTSparse.h
math/matrix/src/TMatrixTSparse.cxx
math/matrix/test/testMatrixTSparse.cxx

Implements fast conservative Sparse Matrix Multiplication (SpMM), i.e. C=A*B, where A, B and C are sparse matrices, with remarkable savings in operation count and memory usage.
In the current implementation, the number of nonzeros in C is guessed as the number of rows in A containing at least a nonzero entry times the number of columns in B containing at least a nonzero entry. The matrix C is subsequently shrunk to delete entries corresponding to zero elements. This choice is far from optimal: for example, if A and B are diagonal matrices, C is initially allocated as fully dense even if it is diagonal too, with a tremendous waste of resources.
In this PR, the number of nonzeros in C is computed in a conservative fashion (i.e. without dropping numerically zero entries in the result matrix …

[matrix] Fast SpMM

---

tree/ntuple/v7/test/CMakeLists.txt

The RDF dependencies were cleaned up in commit 8d7fa5f87c and commit f215692b3d removed the RDF unit test.

[ntuple] Remove outdated test dependency on RDF

---

tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/src/RField.cxx

With the helpers for column creation introduced by #16116, memory consumption during compilation significantly increases (from ~200MB to ~600MB using clang) due to the fact that templated field types, and therefore all possible column representations are automatically instantiated. This commit prevents this automatic instantiation from happening by `extern`-alizing all `RSimpleField` template specializations and only instantiating them in `RField.cxx`, bringing down memory consumption to ~230MB.

[ntuple] Prevent automatic instantiation of `RSimpleField<T>`

---

core/base/src/TUrl.cxx

`ATOMIC_VAR_INIT` is not useful anymore and deprecated in c++20.

[core] remove deprecated ATOMIC_VAR_INIT from TUrl.cxx

---

hist/unfold/src/TUnfoldDensity.cxx

`Int_t nbin` is only used in debug - marked as [[maybe_unused]]. `sumSquare` is unused - removed.

[hist] fix unused variable warnings

---

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
tree/ntuple/v7/src/RColumnElement.cxx

The `src` of `RColumnElement::Pack/Unpack` is not intended to be modifiable. Updated the signatures to reflect that.

[ntuple] make src argument of RColumnElement::Pack/Unpack const

---

tutorials/CMakeLists.txt

Fixes [ROOT-9420](https://its.cern.ch/jira/browse/ROOT-9420)

[CMake] Tutorials as tests: fail if function not found

---

tree/ntuple/v7/test/ntuple_storage.cxx

Read only one column from the remote file to speed up the test.

[ntuple] speed up HTTP test

---

roofit/roofitcore/inc/RooDataHist.h

Add a getter for the "arraySize" memeber function RooDataHist.
The weightArray getters are way more useful when actually being able to loop over the list.

[RF] RooDataHist arraySize getter

---

README/ReleaseNotes/v634/index.md
bindings/tpython/inc/TPython.h
bindings/tpython/src/TPython.cxx

The implementation of `TPython::Eval()` is fragile, and the funcitonality it provides is redundant. One can always communicate between Python and C++ using variables known to the ROOT interpreter.
To make the output-variable-pattern easy to use in `TPython::Exec()`, a new output parameter of type `std::any` is introduced.
Closes #12182.

[PyROOT] Deprecate `TPython::Eval()`

---

tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
tree/ntuple/v7/test/ntuple_types.cxx

With the addition of `RIntegralTypeMap` (PR https://github.com/root-project/root/pull/16039), most of the type
name deduction for type-erased fields was moved from the type
translation map to `RField`'s template specialization. Upon creation of
type-erased STL map(-like) types, originally only the type translation
map was used. This now can cause issues where the map's item types may
be non-normalized. By using the type names of the subfields of the
`std::pair` item field, we ensure the correct inner type names are used.

[ntuple] Fix item type names for STL map fields

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
tree/ntuple/v7/test/ntuple_types.cxx

This PR adds support for `std::multiset` and `std::unordered_multiset` fields. The on-disk representation is exactly the same as `std::(unordered)_set`, so the only addition is the type name resolution for type-erased fields and the `RField` template specializations.

[ntuple] Add support for `std::(unordered)_multiset`

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ProxiedSTLContainerLinkDef.h
tree/ntuple/v7/test/ntuple_types.cxx

This PR adds support for `std::multimap` and `std::unordered_multimap` fields. The on-disk representation is exactly the same as `std::(unordered)_map`, so the only addition is the type name resolution for type-erased fields and the `RField` template specializations.

[ntuple] Add support for `std::(unordered)_multimap` fields

---

README/ReleaseNotes/v634/index.md
roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
roofit/histfactory/src/ConfigParser.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/histfactory/src/Measurement.cxx
roofit/histfactory/test/stressHistFactory.cxx
roofit/histfactory/test/testHistFactory.cxx
roofit/histfactory/test/testHistFactoryPlotting.cxx
roofit/roofitcore/CMakeLists.txt

If you build a HistFactory workspace with `MakeModelAndMeasurementFast`, by default there is also a fit and some plotting happening. Nobody uses that. People use HistFactory to build models and then they use their own plotting and fitting code.
Therefore, this commit suggests to enable
`RooStats::HistFactory::Measurement::ExportOnly()` by default and deprecate the code related to the internal plotting and fitting.
Instead, an example on how to do plotting and fitting with HistFactory models will be added to the `hf001` tutorial by another commit (#16323).

[RF] Deprecate HistFactory-internal fitting and plotting routine

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roostats.py
tutorials/roostats/rs301_splot.py

Adds pythonizations for the `RooStats::SPlot` class. The constructor(which automatically calls `AddSWeight()`) and the `AddSWeight` method follows command argument pythonization ( `**kwargs` -> `RooCmdArgs`) which makes configuring options more pythonic.
Also adds a translated RooStats tutorial which uses the added pythonisations

[RF][PyROOT] Pythonize RooStats SPlot constructor and AddSWeights

---

README/ReleaseNotes/v634/index.md
roofit/roofitcore/inc/RooAbsData.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooDataSet.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roostats/inc/RooStats/MarkovChain.h
roofit/roostats/src/MCMCInterval.cxx
roofit/roostats/src/MarkovChain.cxx

Removes MarkovChain interfaces that are one-time used in `MCMCInterval`  
Now obtain the reduced markov chain data (also as Hist ) by calling `reduce` on the RooDataSet  (which can be directly accessed through  `MarkovChain::GetAsConstDataSet`).  
Updates all `reduce` and `reduceEng`methods to const across `RooAbsData` and other RooFit classes with overrides.

[RF] Improve `MarkovChain` interfaces and `MCMCInterval`

---

bindings/CMakeLists.txt
cmake/modules/RootBuildOptions.cmake

The TPython library has one big caveat: it requires linking against `libpython`, which is not allowed in some context like the Python package manager.
To avoid this problem that is blocking `pip install root`, this commit suggests to make TPython optional at build time. This makes also sense considering how TPython and PyROOT are used: if you intend to use ROOT via PyROOT from pip install ROOT, you probably won't need the functionality to run Python code from C++ that TPython provides.
Possibly supersedes #15891, @vepadulano.

Make it possible to disable TPython in build

---

roofit/roostats/inc/RooStats/MarkovChain.h

The semicolons were at the wrong place, making the deprecation macros refer to the wrong funciton. Follows up on f1bc9d96df.

[RF] Fixup deprecation warnings in MarkovChain.h

---

tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
tree/dataframe/test/dataframe_simple.cxx

Add a specialization of RTreeColumnReader that reads values from a branch of type std::array. The specialization uses the non-adopting view from RVec to expose the contents of the array to nodes of the graph.
Fixes #16160

[df] Allow reading std::array branches from TTree

---

.github/workflows/root-ci.yml

for all builds since it is subject to timeouts when the build happens from scratch.
This is of course a temporary measure, until we find a future proof solution for this issue.

[ci] Disable the win x86 dbg platform

---

documentation/doxygen/MakeRCanvasJS.C
documentation/doxygen/MakeTCanvasJS.C

Let use browser `import()` function to control proper loading of JSROOT modules. 
No need to use older `JSRoot.core.js`
To be tested

[doxygen] use jsroot v7 modules for embeding

---

tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_test.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

by @hahnjo suggestion, since we are exposing a type-erased virtual interface for `RColumnElement` through `RColumnElementBase`, we can hide all the concrete definitions into a cxx file.
This has the benefit of reducing the compile time of any translation unit that includes `RColumnElementBase.hxx` significantly, as the compiler won't have to instantiate all the combination matrix of `RColumnElement<CppT, ColumnType>` every time.
It also let us have better control on exactly which types of `RColumnElement` we allow to instantiate by explicitly listing them into a proxy enum.
- renamed `RColumnElement.hxx` to `RColumnElementBase.hxx`
- moved all concrete definitions from `RColumnElementBase.hxx` to `src/RColumnElement.hxx`. This is a private header file that is included by …

[ntuple] Move RColumnElement concrete definitions out of the header file

---

math/minuit2/src/MnPlot.cxx

gcc14 issue warning when `std::vector<char>` is used.
Also simplify loop over points
```
In file included from /usr/include/c++/14/x86_64-suse-linux/bits/c++allocator.h:33,
from /usr/include/c++/14/bits/allocator.h:46,
from /usr/include/c++/14/vector:63,
from /home/linev/git/webgui/math/minuit2/inc/Minuit2/MnPlot.h:14,
from /home/linev/git/webgui/math/minuit2/src/MnPlot.cxx:10:
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = char]’,
inlined from ‘constexpr void std::allocator< <template-parameter-1-1> >::deallocate(_Tp*, std::size_t) [with _Tp = char]’ at /usr/include/c++/14/bits/allocator.h:208:35,
inlined from ‘static constexpr void std::allocator_traits<std::allocator<_Up> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = char]’ …
```

[minuti] fix gcc14 warning in MnPlot

---

core/meta/src/TClass.cxx

Last argument in strncpy is length of destination buffer and should not depend from length of source string. Fixes warning from gcc14:
```
git/webgui/core/meta/src/TClass.cxx:701:20: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound depends on the length of the source argument [-Wstringop-truncation]
701 |             strncpy(line + kvalue, *ppointer, std::min( i, kline - kvalue));
|             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
git/webgui/core/meta/src/TClass.cxx:691:20: note: length computed here
691 |          i = strlen(*ppointer);
|              ~~~~~~^~~~~~~~~~~
```

[core] Do not provide source string length to `strncpy`

---

gui/gui/src/TGFSContainer.cxx

Size of single element is second argument in the `calloc` call. 
Fix warning from gcc14:
```
git/webgui/gui/gui/src/TGFSContainer.cxx: In member function ‘void TGFileItem::SetDNDData(TDNDData*)’:
git/webgui/gui/gui/src/TGFSContainer.cxx:468:28: warning: ‘void* calloc(size_t, size_t)’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
468 |    fDNDData.fData = calloc(sizeof(unsigned char), data->fDataLength);
|                            ^~~~~~~~~~~~~~~~~~~~~
git/webgui/gui/gui/src/TGFSContainer.cxx:468:28: note: earlier argument should specify number of elements, later size of each element
```

[gui] fix calloc usage in TGFileItem

---

roofit/roostats/inc/RooStats/RooStatsUtils.h
roofit/roostats/src/RooStatsUtils.cxx

* The `RooStatsUtils::MakeCleanWorkspace` function was implemented by ATLAS framework developers, who remain its only users until now
* They requested changing the function in #7823 and there is no clear reason to deny this request
Closes #7823.

[RF] Rename and improve RooStatsUtils::MakeCleanWorkspace

---

documentation/doxygen/MakeRCanvasJS.C
documentation/doxygen/MakeTCanvasJS.C

Avoid expansion of JSROOT drawing on full HTML page
Like this one: https://root.cern/doc/master/rbox_8cxx.html

[doxygen] use relative position for JSROOT drawings [skip-ci]

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/src/RNTupleSerialize.cxx

The meta-data envelope will not be part of the v1.0 specification. It will likely come later as a minor format update.
Note that this change breaks forward compatibility.

[ntuple] Remove stub serialization of meta-data envelope

---

tree/treeplayer/src/TBranchProxy.cxx
tree/treeplayer/test/basic.cxx

When setting the branch proxy, report info about a missing branch to the user. This is done in the form of a printed error. The logic is only triggered if there are no other branch names in the list of available branches that begin with the current branch name being searched. This situation could arise for example with a skeleton analysis produced by TTree::MakeProxy and a TTree with a split object. In that case the generated code will try to create a TBranchProxy for the top-level branch, even though that branch is not available from the TTree, only the sub-branches are.
See for more details the discussion at https://github.com/root-project/root/pull/3746

[tree] Report info about missing branch from TBranchProxy

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/inc/ROOT/RPage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

- Adds a locator type that can reference blocks >4GB on disk
- The new locator replaces the previously available but unused string locator
- Makes that DAOS locator support >4GB blocks
- Adds some fixes for pages >2GB

[ntuple] Add support for "large locators", drop string locator

---

hist/histpainter/src/TGraphPainter.cxx

In TGrpahErrors TGraphAsymmErrors and TGraphBentErrors, the error bars were drawn inside the marker when the marker was bigger than the error bars. This was reported in this forum post: https://root-forum.cern.ch/t/error-bars-inside-markers-with-draw-same/60631

Do not draw error bars when they are smaller than the marker.

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
interpreter/cling/lib/Interpreter/IncrementalJIT.h

The `ClingMMapper` must remain available until all `ClingMemoryManager`s are destructed, which is typically during shutdown of `IncrementalJIT`. This was not the case for the global object `MMapperInstance` that was introduced during the upgrade to LLVM 13 because `libCling` variables are destructed before running `TROOT` `atexit` handlers that shut down the JIT. In practice, it happened to work but this will change with the upgrade to LLVM 18 where we see crashes in some tests, potentially because of upstream commit https://github.com/llvm/llvm-project/commit/47f5c54f997a59bb2c65abe6b8b811f6e7553456
See also commits e0f6c04660 ("Prevent static destruction from ending DefaultMMapper too early") and 80c14bb948 ("Extend lifetime of SectionMemoryManager::DefaultMMapper, again") for the same …

[cling] Fix lifetime of `ClingMMapper` [v6.30]

---

interpreter/cling/lib/Interpreter/IncrementalJIT.cpp
interpreter/cling/lib/Interpreter/IncrementalJIT.h

The `ClingMMapper` must remain available until all `ClingMemoryManagers` are destructed, which is typically during shutdown of `IncrementalJIT`. This was not the case for the global object `MMapperInstance` that was introduced during the upgrade to LLVM 13 because `libCling` variables are destructed before running `TROOT` `atexit` handlers that shut down the JIT. In practice, it happened to work but this will change with the upgrade to LLVM 18 where we see crashes in some tests, potentially because of upstream commit https://github.com/llvm/llvm-project/commit/47f5c54f997a59bb2c65abe6b8b811f6e7553456
See also commits e0f6c04660 ("Prevent static destruction from ending DefaultMMapper too early") and 80c14bb948 ("Extend lifetime of SectionMemoryManager::DefaultMMapper, again") for the same …

[cling] Fix lifetime of ClingMMapper [v6.28]

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_packing.cxx

adds a new ColumnType `Real32Trunc`, that stores a real value as a tightly-packed, IEEE-754 single precision float using less than 32 bits. The missing bits are simply truncated from the mantissa, causing the value to be rounded towards zero.
The valid range of bit widths is `[10, 31]` inclusive.
This is the first ColumnType with a variable bit width, therefore it requires some extra handling on the RColumnElement and RField side, but it uses a single type id on disk (`0x1D`) and a single enum value `EColumnType::kReal32Trunc`.
The way to use it is by calling the new `SetTruncated(nBits)` method on `RField<float>`.

[ntuple] Add support for truncated single-precision float columns

---

tree/ntuple/v7/test/ntuple_packing.cxx

It produces false positives on memcpy "out of bounds".

[ntuple] disable -Warray-bounds in ntuple_packing.cxx

---

tree/tree/inc/TTree.h

Showcasing the main strength of this function compared to TTree::GetEntries

[skip-ci] Add docs to TTree::GetEntriesFast

---

CMakeLists.txt

This is required to build LLVM18.
This version of CMake was eleased in March 2021
https://github.com/Kitware/CMake/releases/tag/v3.20.0

[CMake] Set the minimum required version to 3.20

---

tree/ntuple/v7/doc/specifications.md

change wording in the specification from "event range" to "entry range"

[skip-ci][ntuple] spec: change 'event' range to 'entry' range

---

tree/ntuple/v7/test/ntuple_packing.cxx

clang doesn't know about -Wstringop-overflow (problem introduced in #16386)

[ntuple] disable a #pragma ignored for clang in ntuple_packing

---

tree/ntuple/v7/doc/tuning.md
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptionsDaos.hxx
tree/ntuple/v7/inc/ROOT/RPage.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageSourceFriends.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RNTupleWriteOptions.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_model.py
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_view.cxx
tree/ntuple/v7/test/rfield_string.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

Moves from fixed page sizes on write to adaptive page sizes, following the original idea of @hahnjo 
The new mechanism is explained in the tuning.md document in the PR.
The PR also bumps the target compressed cluster size to 150MB. We may want to reduce that still. Evaluation of the new method is currently ongoing and the PR description will be amended with the results.
EDIT: [Comparison](https://docs.google.com/spreadsheets/d/1maJhgvgVU8RkX7QXd7B3QiTBfKuYbTbvgkoHzBUOurY/edit?usp=sharing) of current write performance vs adaptive page sizes with 50MB, 100MB, 150MB target cluster size. To me it seems that there is not a good argument to go to 150 MB clusters. There may be an argument for 100 MB clusters. For the moment, I'll remove the commit that changes the default settings from the PR. …

[ntuple] Adaptive page sizes

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py
bindings/pyroot/pythonizations/test/tf_pycallables.py
hist/hist/inc/TF1.h
hist/hist/src/TF1.cxx

Allows the user to pass a dataset (2D NumPy array) where `ROOT::TF1/TF2/TF3` classes can call `EvalPar` on a functor object/pycallable
This no longer requires a looped call the the TF classes evaluation but returns a buffer that contains the result, evaluated for each subarray in the dataset. This also adds support for non-contiguous array calls(e.g sliced arrays) via the pythonization which was not previously supported even in the 1D array case.
Motivating example:
```py
def func(x, pars):
return pars[0] * x[0] * x[0] + x[1] * pars[0]
my_func = ROOT.TF1("my_func", func, -10, 10, npar=2, ndim=2)
x_non_contiguous = np.array([[2., 2, 1],
[1., 2, 3],
[2., 2, 1],
[4., 3, 2]])
x = np.array([[2., 1],
[1., 3],
[2., 1],
[4., 2]])
pars = np.array([2.])
y = np.zeros(len(x))
for i in range(len(x)): …
```

[hist][PyROOT] Pythonize the TF1 EvalPar interface for 2D NumPy arrays

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
roofit/roofitcore/inc/RooCustomizer.h
roofit/roofitcore/src/RooCustomizer.cxx

The `gMainDict` should be borrowed, i.e. we are not calling Py_INCREF(gMainDict). Like this, we avoid unexpectedly affecting how long `__main__` is kept alive. The `gMainDict` is only used in `Exec()`, `ExecScript()`, and `Eval()`, which should not be called after `__main__` is garbage collected anyway.
Closes #16402.
Needs to be backported to 6.32.
Equivalent CPyCppyy PR:
https://github.com/wlav/CPyCppyy/pull/37

[CPyCppyy] Avoid holding reference to `__main__` in the CPyCppyy API

---

gui/webdisplay/src/RWebDisplayHandle.cxx

When producing images via web browsers,
fully suppress debug printout of browsers in the console.

[webgui] suppress browsers log output in batch headless mode

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_modelext.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx
tree/ntuple/v7/test/ntuple_types.cxx

We need to decide between the sparse and the dense representation because they result in different structural roles for the field (collection vs. leaf). Since there was very little measured benefit of the dense representation, this PR keeps the sparse representation as one and only representation.

[ntuple] remove dense representation of nullable field

---

tree/dataframe/test/dataframe_simple.cxx

See in-code comment for more details.
Note: this bug is routinely seen on the CI, where it causes occasional failures to the tests in question. Despite this solution being very suboptimal (the bug is most likely still present in many places of our codebase and can be encountered by users in the wild) we should at least be able to remove the random CI failures on our side.
A proper solution would be nice, but it seems hard to come up with one that doesn't have big performance implications.

[RDF] work around a bug that causes attempts to delete stack memory

---

interpreter/cling/lib/Interpreter/ClangInternalState.cpp
interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp

Fix deprecation warnings when compiling cling standalone
Fix warnings in a standalone Cling build

[cling] Migrate to `FileEntryRef` and `DirectoryEntryRef`

---

ui5/eve7/lib/GlViewerRCore.js

The RenderCore changes introduced a bug in the secondary selection. 
The change was created with the PR #15812.
Temprary solution is that the GLViewerRCore.js overrides RenderQuTor pick function. 
The related change is  pending in RenderCore  https://github.com/UL-FRI-LGM/RenderCore/pull/21

[reve] Correct secondary selection in RC.RendeQuTor.

---

gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
gui/webdisplay/src/RWebDisplayHandle.cxx
gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx
tutorials/graphics/save_batch.C

Enabled with `TWebCanvas::BatchImageMode()` static method.
Allows to process many images with single headless browser invocation and
increase performance of image production - without change of user code. 
When many canvases are stored as image in difference places, 
they first collected in batch as JSON and then processed
when at least `n` images are there. Only then headless browser invoked
and create all these images at once. 
Provide macro demonstrating this functionality.

[webcanvas] introduce batch mode for images

---

gui/webdisplay/src/RWebDisplayHandle.cxx

Wrong condition was used to generate temporary HTML file.

[webgui] fix usage of tmp file in RWebDisplayHandle

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_conversion_maps.py

This mapping should be fixed before shipping the RDF Numba execution pipeline to users

[DF] Fix typo in RDF conversion map

---

geom/geom/src/TGeoNavigator.cxx
geom/geom/src/TGeoParallelWorld.cxx
geom/geom/src/TGeoPhysicalNode.cxx
geom/geom/src/TGeoVoxelFinder.cxx

This pull request provides a bug fix:
- fixing wrong safety in TGeoParallelWorld due to double application of coordinate transformation) 
- fix a crash in VoxelFinder when we have only 1 primitive
as well as some optimizations for TGeoPallelWorld usage:
- call TGeoParallelWorld::Safety with existing limit from normal safety to speedup search
- make TGeoPhysicalNode::IsMatchingState faster

Improvements for TGeoParallelWorld (part 1)

---

tree/dataframe/test/dataframe_simple.cxx

fixes the order of declaration of TTree/TFile in a test function of RDF, that was mistakenly changed in 5f56b95832d0f31d0d85dc0a6cc93aa9cb375159.

[RDF] fix order of declarations (and destruction) of TTree/TFile

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabscollection.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsdata.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabspdf.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreal.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreallvalue.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooarglist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooargset.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roocategory.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roochi2var.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodatahist.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodecays.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roogenfitstudy.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roojsonfactorywstool.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roomcstudy.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roomsgservice.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roonllvar.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooprodpdf.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roorealvar.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimultaneous.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roosimwstool.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roostats.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roovectordatastore.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py
documentation/doxygen/print_roofit_pyz_doctrings.py

This introduces a `__cpp_name__` member to include classes under a namespace which is not captured by the pythonized class name. Fixes the bug where the generated PyROOT block would not show up on the class page for `RooStats::SPlot` but only for member functions. Also adds the missing anchors for `RooVectorDataStore` and `RooArgList`

[RF][PyROOT] Change the way pyzdocs generate pyroot blocks for classes

---

net/net/src/TGrid.cxx

This makes the reason for TGrid::Connection issues apparent, instead of failing silently.

Add error message for failing TGrid::Connect issues

---

math/minuit2/inc/Minuit2/AnalyticalGradientCalculator.h
math/minuit2/inc/Minuit2/ExternalInternalGradientCalculator.h
math/minuit2/inc/Minuit2/FCNBase.h
math/minuit2/inc/Minuit2/FCNGradAdapter.h
math/minuit2/inc/Minuit2/FCNGradientBase.h
math/minuit2/inc/Minuit2/FumiliFCNBase.h
math/minuit2/inc/Minuit2/FumiliMinimizer.h
math/minuit2/inc/Minuit2/FunctionMinimizer.h
math/minuit2/inc/Minuit2/MnApplication.h
math/minuit2/inc/Minuit2/MnHesse.h
math/minuit2/inc/Minuit2/MnMigrad.h
math/minuit2/inc/Minuit2/MnMinimize.h
math/minuit2/inc/Minuit2/ModularFunctionMinimizer.h
math/minuit2/src/AnalyticalGradientCalculator.cxx
math/minuit2/src/ExternalInternalGradientCalculator.cxx
math/minuit2/src/FumiliMinimizer.cxx
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnApplication.cxx
math/minuit2/src/MnHesse.cxx
math/minuit2/src/ModularFunctionMinimizer.cxx

By introducing a virtual `FCNBase::HasGradient()` method and moving the
former `FCNGradientBase` interface to the base class, we don't need to
repeat lots of code just for dealing with both the `FCNBase` and
`FCNGradientBase` types.
This is a completely backwards compatible change that makes the Minuit 2
code more maintainable.
Another commit in this PR removed the unused `FCNGradientBase::CheckGradient()` member function.

[Minuit2] Add virtual `FCNBase::HasGradient()` method 

---

README/ReleaseNotes/v634/index.md
roofit/roofitcore/inc/RooAbsArg.h

Some RooAbsArg member functions were replaced a long time ago with drop-in alternatives that everyone uses since forever.
We might as well deprecate these member functions now to slim down the interface.

[RF] Deprecate legacy interface of RooAbsArg

---

tree/ntuple/v7/doc/architecture.md
tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
tree/ntuple/v7/inc/ROOT/RNTupleFillStatus.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RNTupleFillContext.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tutorials/v7/ntuple/ntpl013_staged.C

With multiple concurrent `RNTupleFillContext`s, the order of clusters is generally indeterminate and entries are only partially ordered. With staged cluster committing, this restriction can be partially lifted by splitting a cluster commit into two phases:
1. Once full, or when manually triggered, all fields are committed which triggers flushing of all columns. All pages are compressed and staged via the page sink. The result is a `RStagedCluster` that records all information for the second phase. This step can be repeated multiple times as entries are filled into the context.
2. When appropriate for the application, all staged clusters can be committed, which logically appends them to the RNTuple. This is implemented in a single critical section, which guarantees that the clusters and …

[ntuple] Implement staged cluster committing

---

roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooProdPdf.h
roofit/roofitcore/src/ConstraintHelpers.cxx
roofit/roofitcore/src/ConstraintHelpers.h
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/test/testTestStatistics.cxx

In trying to debug the fit to the CMS higgs discovery workspace, I found that the way the constraintTerm is determined will be buggy if doing a stripDisconnected determination of the constraint terms (i.e. not using the `Constrain` option). The cause is that the RooArgSet of parameters passed to `RooAbsPdf::getConstraints` gets modified, and therefore subsequent components don't see the full list of parameters of the parent pdf, so the list of constraint terms ends up being incomplete.
I think this PR fixes things

[RF] Fix behaviour of getAllConstraints

---

tree/ntuple/v7/doc/specifications.md

Adding an explicit section for the ROOT File embedding rather than having it in the Introduction. Slight rewording of the anchor schema introduction.

[skip-ci][ntuple] separate ROOT embedding paragraph

---

gui/browserv7/src/RBrowser.cxx

It is most probable place where new canvases are created or existing are modified. 
Therefore need check for update.
Simple workaround for some macros execution

[rbrowser] Check modified widgets after macro execution

---

gui/browserv7/src/RBrowser.cxx

It is most probable place where new canvases are created or existing are modified. Therefore need to update.

[rbrowser] Check modified widgets after macro execution [6.32]

---

core/cont/src/TClonesArray.cxx

This PR fixes [ROOT-7173](https://its.cern.ch/jira/browse/ROOT-7137)
Corresponding PR in roottest https://github.com/root-project/roottest/pull/1186

[Core] TClonesArray: protect against erroneously setting of owner bit

---

gui/browserv7/inc/ROOT/RBrowser.hxx
gui/browserv7/src/RBrowser.cxx
gui/browserv7/src/RBrowserTCanvasWidget.cxx
gui/browserv7/src/RBrowserWidget.hxx
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindowsManager.cxx
ui5/browser/controller/Browser.controller.js

When ROOT macros running, they typically create canvas "c1".
If run macro again and again - new canvas will be created but old will be deleted.
This was not handled before in RBrowser.
Now widget is closed if correspondent RWebWindow is destroyed.
Also change logic how TCanvas widget handle canvas pointer.
While ROOT manage canvas itself one cannot use `std::unique_ptr<TCanvas>` to hold pointer.
Instead canvas always searched by name and if gone - widget automatically closed.
Update slightly client part

[rbrowser] correctly handle TCanvas recreation in macros

---

core/metacling/test/TClingTests.cxx
interpreter/cling/lib/Interpreter/BackendPasses.cpp

LLVM had a bug where constructors with the same priority would not be stably sorted. This has been fixed upstream by https://github.com/llvm/llvm-project/pull/95532, but to avoid relying on a backport this commit works around the issue: The idea is that we lower the default priority of concerned constructors to make them sort correctly.
---
As discussed, this provides a bit of magic :magic_wand: to work around the bug if we don't have the backport, for example in the Conda releases. I propose we still leave the backport in our copy of LLVM though.

[cling] Work around constructor priority bug

---

core/metacling/test/TClingTests.cxx
interpreter/cling/lib/Interpreter/BackendPasses.cpp

LLVM had a bug where constructors with the same priority would not be stably sorted. This has been fixed upstream by
https://github.com/llvm/llvm-project/pull/95532, but to avoid relying on a backport this commit works around the issue: The idea is that we lower the default priority of concerned constructors to make them sort correctly.
(cherry picked from commit https://github.com/root-project/root/commit/7db43f776d191807c1e4893312fabce7c60160bd, backport of https://github.com/root-project/root/pull/16420)

[cling] Work around constructor priority bug [v6.32]

---

tree/ntuple/v7/test/ntuple_evolution.cxx

Differently from `Evaluate()`, `ProcessLine()` returns a `Longptr_t` value and errors must be checked by passing a second argument. The old check would fail when assigning 0 to a member.

[ntuple] Fix error check of ProcessLine

---

ui5/browser/controller/Browser.controller.js
ui5/browser/view/Browser.view.xml

It is not standard feature, but now with resize of browsable columns one will get resize of browsable area

[rbrowser] Let resize browsable area

---

roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooAbsMinimizerFcn.cxx
roofit/roofitcore/src/RooAbsMinimizerFcn.h
roofit/roofitcore/src/RooMinimizer.cxx
roofit/roofitcore/test/CMakeLists.txt
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/testTestStatistics.cxx

Use one abstraction layer less when interacting with the minimizers in
RooFit.

[RF] Use `ROOT::Math::Minimizer` in RooMinimizer directly

---

roofit/roofitcore/inc/RooFit/Detail/CodeSquashContext.h
roofit/roofitcore/inc/RooFuncWrapper.h
roofit/roofitcore/src/RooAddition.cxx
roofit/roofitcore/src/RooFit/Detail/CodeSquashContext.cxx
roofit/roofitcore/src/RooFormulaVar.cxx
roofit/roofitcore/src/RooFuncWrapper.cxx
roofit/roofitcore/src/RooGenericPdf.cxx
roofit/roofitcore/src/RooRealIntegral.cxx

Fix the debug macro for the case where some functions are only known to the interpreter, by adding a new mechanism to register such functions in the code generation context.

[RF] More systematic way to write debug macro from generated code

---

ui5/browser/model/BrowserListBinding.js

Add missing function which required now by recent openui5 versions. 
Let use this and previos ROOT versions with newest openui5

[rbrowser] fix BrowserListBinding.js [skip-ci]

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_test.hxx

refactors RNTupleMerger to properly support late model extension.
The "Union"  merging mode is added, allowing the merger to late-model-extend the destination to include all the fields of the input ntuples (instead of ignoring unknown fields / complaining when models don't match).
Likewise, the "Strict" merging mode is added that checks that all inputs have the exact same structure.
By default, the old behavior (named "Filter") is used.
To better compare the RNTuples structures, the merging logic is now more properly considering the fields of each input, rather than just the columns as it was previously. This also allows for more descriptive messages to the user if some mismatch is found.
NOTE: the `RNTupleMerger::Merge` function now returns a RResult instead of throwing exceptions on …

Add late model extension to RNTupleMerger

---

cmake/modules/SetUpWindows.cmake

Use `/Ob2` (Inline Function Expansion 2) with `RelWithDebInfo`.
This is the default value under `/O1` and `/O2`. Allows the compiler to expand any function not explicitly marked for no inlining.
This fixes the failing `test-check-nullptr` and `roottest-cling-exception-nullderef-e` tests with ROOT built in `RelWithDebInfo`.

[cmake][win] Change the `/Ob` compiler flag

---

ui5/browser/model/BrowserListBinding.js

Add missing function which required now by recent openui5 versions. 
Let use this and previous ROOT versions with newest openui5

 [rbrowser] fix BrowserListBinding.js [6.32] [skip-ci]

---

geom/geom/inc/TGeoParallelWorld.h
geom/geom/inc/TGeoVoxelGrid.h
geom/geom/inc/bvh/v2/CMakeLists.txt
geom/geom/inc/bvh/v2/README.md
geom/geom/inc/bvh/v2/bbox.h
geom/geom/inc/bvh/v2/binned_sah_builder.h
geom/geom/inc/bvh/v2/bvh.h
geom/geom/inc/bvh/v2/default_builder.h
geom/geom/inc/bvh/v2/executor.h
geom/geom/inc/bvh/v2/index.h
geom/geom/inc/bvh/v2/mini_tree_builder.h
geom/geom/inc/bvh/v2/node.h
geom/geom/inc/bvh/v2/platform.h
geom/geom/inc/bvh/v2/ray.h
geom/geom/inc/bvh/v2/reinsertion_optimizer.h
geom/geom/inc/bvh/v2/split_heuristic.h
geom/geom/inc/bvh/v2/stack.h
geom/geom/inc/bvh/v2/stream.h
geom/geom/inc/bvh/v2/sweep_sah_builder.h
geom/geom/inc/bvh/v2/thread_pool.h
geom/geom/inc/bvh/v2/top_down_sah_builder.h
geom/geom/inc/bvh/v2/utils.h
geom/geom/inc/bvh/v2/vec.h
geom/geom/src/TGeoParallelWorld.cxx

This commit provides a rewrite of key functions of TGeoParallelWorld, achieving: 
(a) faster initialization
(b) faster execution of the Safety function (from ~O(N) to ~O(1)) 
(c) faster or equal execution of FindNode/FindBoundary functions (~log(N)) 
(d) less memory consumption (better memory scalability)
The development for this commit was motivated from a use case in ALICE, in which the parallel world "scene" can be very large (~100K volumes). In this case, TGeoVoxelFinder takes very long
to construct and consumes a very large amount of memory (GBs). In addition, the evaluation of the Safety function dominates the Geant simulation time.
The improvements in this commit are mainly achieved through:
* The use of a boundary volume hierarchy (BVH) as the base acceleration entity, replacing …

[geom] New BVH/VoxelGrid-based implementation of TGeoParallelWorld routines

---

bindings/tpython/test/CMakeLists.txt
bindings/tpython/test/testTPython.cxx
bindings/tpython/test/test_tpython.py
cmake/modules/RootMacros.cmake

Except for Windows, but doing these new tests on some platforms is
better than on no platform. Otherwise we have no test coverage for using
TPython from different threads.

[TPython] Enable TPython tests

---

core/base/src/TApplication.cxx

A bug of dupe quotes that was introduced by this commit: https://github.com/root-project/root/commit/73039d1ab4e3487c71c45270f5c8129c6871170d

[core] Fix dupe quotes in forum bug report

---

math/vecops/inc/ROOT/RVec.hxx

Seen while building latest master with -Dasan=ON
```
/home/vpadulan/Programs/rootproject/rootbuild/master-2024-09-16-testing-asan/include/ROOT/RVec.hxx:515:4: error: non-stati
c data member cannot be constexpr; did you intend to make it static?
constexpr std::size_t cacheLineSize = std::hardware_destructive_interference_size;
^
static
```

[vecops] declare constexpr data member also static

---

geom/geom/inc/TGeoNavigator.h
geom/geom/src/TGeoNavigator.cxx

This commit provides an (optional) optimization to reduce the cost of safety evaluations associated with TGeoParallelWorld.
The approach consists in the introduction of additional cache-state in TGeoNavigator. This state remembers the last location for which TGeoParallelWorld::Safety was evaluated, together with the corresponding value returned.
Since TGeoNavigator follows the evolution of tracks step-by-step, we have some sort of history-locality. This means that the cache-state has a high-probability of being relevant for multiple track locations in a row.
The optimization proposed here is orthogonal to other improvements. It adds on top of algorithmic improvements within TGeoParallelWorld (bounding volume hierarchies, see separate PR), gaining a few extra percent in speed.
By default, …

[geom] Add cache layer for TGeoParallelWorld safeties in TGeoNavigator

---

roofit/RDataFrameHelpers/inc/RooAbsDataHelper.h
roofit/RDataFrameHelpers/test/testActionHelpers.cxx

We support only RooRealVar columns anyway, and by doing the cast to double explicit we can also support filling such datasets from arbitrary column types that convert to `double`.
This is a small quality-of-life improvement that addresses this forum post:
https://root-forum.cern.ch/t/dataframe-roofit-dataset-maker-with-mixture-of-column-types-crashes/61734/8

[RF] Explicitly cast to double in RooAbsDataHelper

---

bindings/experimental/distrdf/python/DistRDF/HeadNode.py
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/src/RInterface.cxx

Introduce a new method to get a label for the data source that the current RDataFrame is processing. There are three major types:
* The dataframe will process a TTree dataset
* The dataframe will process an empty dataset
* The dataframe will process data from an RDataSource
The function returns a label with the suffix "DS" also for the first two cases, to be aligned as much as possible with the RDataSource infrastructure.
Make use of this function in distributed RDataFrame to create the headnode of the Python computation graph. This also avoids extra parsing in the factory function which includes opening the first input file once more to distinguish between TTree or RNTuple input (in case the first input argument is a string).

Use data source label in distributed HeadNode factory

---

tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/RNTupleIndex.hxx
tree/ntuple/v7/src/RNTupleIndex.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_index.cxx
tree/ntuple/v7/test/ntuple_test.hxx

This PR adds (a first version of) the `RNTupleIndex`, which is an in-memory structure that maps RNTuple field values (or combinations thereof) to an entry index in the RNTuple for which the index was built. Currently, the index only resides in memory and thus has to be (re)build each time. `RNTupleIndex` will be used by the `RNTupleProcessor` to enable dataset joins and will be as transparent as possible to users. Currently, no public interface is foreseen.
At this point, no persistification is foreseen, but this might be added in the future. The implementation of the `RNTupleIndex` in this PR is hash-based. An implementation that is vector-based (but with the same interface) will also be considered.
The idea is to benchmark and evaluate both implementations (and potentially more). Based …

[ntuple] Add initial in-memory index prototype

---

core/base/src/TListOfTypes.cxx
core/meta/src/TEnum.cxx
core/metacling/src/TCling.cxx

The current code goes through different codepaths depending on the platform. One of the codepaths relies on a non-standard extension (variable-length arrays) and the other manually allocates and frees a char array.
Using a std::string, while losing a bit of performance on Linux/Mac, simplifies and unifies the codepaths and avoids using non-standard C++ (which in turns enable building with -Werror).
The perf hit is most likely negligible, especially given the use of dynamic_cast in the same block.

[core] avoid using VLA in TListOfTypes

---

cmake/modules/SetUpMacOS.cmake

The `c++ --print-file-name` command now seems to work, and it is indeed the more appropriate way to get the location of the asan shared library on MacOS.
Also fix the following problems occurring when building on MacOS with -Dasan=ON
Error:
```
CMake Error at cmake/modules/CheckAtomic.cmake:59 (message):
Host compiler appears to require libatomic, but cannot find it.
```
Fix: fix typos in asan symbols (extra `_`) and specify correct linker flag (-U)
Error:
```
error: static AddressSanitizer runtime is not supported on darwin
```
Fix: remove `-static-libsan` flag. This is required by latest MacOS Xcode

[asan] Fix asan configuration for MacOS

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Reserves the "sharded cluster" flag in the cluster summary but removes any additional s11n logic. Extends the cluster summary flags field to 8bits so that it can be handled with a standard C++ type.

[ntuple] fix treatment of "sharded cluster" flag

---

tree/ntuple/v7/doc/architecture.md
tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleFillContext.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_packing.cxx

adds the `Real32Quant` column type to RNTuple. This column type stores floating point values on disk as integers with a user-defined precision (from 3 to 32 bits) and a user-defined value range. This allows to reduce the storage space required to save floats with a well-defined range with more precision than a simple truncation.
The conversion is defined as (pseudocode): 
```
def quantize(value, min, max, n_precision_bits)
{
quantized_max = (1 << n_precision_bits) - 1;
scale = quantized_max / (max - min);
quantized = round((value - min) * scale);
return quantized;
}
```
This change requires adding metadata to the on-disk information, more specifically in the Field Description (see specifications.md for more details).

[ntuple] add Real32Quant column type

---

net/davix/src/TDavixFile.cxx

Replacing the use of non-standard variable arrays with heap-allocated arrays in TDavixFile.

[davix] avoid using VLA

---

tree/ntuple/v7/doc/specifications.md

#16390 should have bumped the specification minor version, but due to simultaneous changes to the specs, it didn't really get bumped

[skip-ci][ntuple] bump specification minor

---

interpreter/cling/lib/Utils/AST.cpp
interpreter/cling/test/.clang-format
interpreter/cling/test/Lookup/named.C

This PR fixes https://github.com/root-project/root/issues/15407

[cling] Make cling::utils::Lookup::Named look into using directives

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx

the argument of a RNTupleInspector is now a ref, not a pointer, so the class documentation is incorrect

[skip-ci][ntuple] fix RNTupleInspector documentation

---

tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx

When cloning a frozen `RNTupleModel`, the schema ID will not change. This allows to use one set of field tokens for all model clones during parallel writing. Also allow creating tokens during model construction, before freezing, with already works when going via the default entry.
Closes #16236

[ntuple] Introduce schema IDs and use for field tokens

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

moves the dtor of RNTupleInspector to the cxx to avoid including (or having the user include) RPageStorage.hxx (otherwise ~unique_ptr<RPageSource> complains about incomplete type).

[ntuple] outline dtor of RNTupleInspector

---

tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RField.cxx

moves various definitions outside of `RFieldBase` for improved readability

[ntuple] outline several definitions from RFieldBase

---

core/metacling/src/TCling.cxx
core/metacling/test/TClingTests.cxx

Fixes #8828
```
root [0] namespace std { namespace Detail {} }
root [1] auto c = TClass::GetClass("Detail")
(TClass *) 0x12ef3d7b0
root [2] namespace Detail {}
Error in <TInterpreter::RefreshClassInfo>: Should not need to update the classInfo a non type decl: Detail
```

TCling::RefreshClassInfo: Error if shadowing namespace.

---

cmake/modules/SetUpMacOS.cmake
config/root-config.in

**TLDR: Assume macOS 10.15 or newer. This is upstreaming one of the patches from nix Darwin.**
In some environments that are indepent of the Apple SDKs like nix Darwin, the `sw_vers` executable that is used in `SetUpMacOS.cmake` is not available.
However, it is not actually needed anymore, because the most recent macOS version for which there are different code branches in the CMake is OS X 10.8 Mountain Lion, which is end of life since about 10 years.
Therefore, this commit suggests to remove the macOS version check and assume we always have OS X 10.9 or newer.
Furthermore, the following simplifications are suggested:
* remove 32-bit code branch, since the last macOS version that
supported 32 bit CPUs was 10.14 Mojave, end-of-life since three
years: …

[CMake] Assume macOS 10.15 Catalina or newer

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/src/RMiniFile.cxx

Also don't allocate them when using `RProperFile`.

[ntuple] Make write buffer size configurable

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/test/dataframe_snapshot.cxx

Fixes #14132
Also check if `fOutputFiles` is empty before giving warning "A lazy Snapshot action was booked but never triggered".
This PR fixes #14132 (the other issue with broken `gDirectory` seems to have gone in latest ROOT (6.32.06), so can consider as this bug is fixed)

[DF] Also check if fOutputFiles is empty before warning untriggered snapshot

---

interpreter/cling/include/cling/Interpreter/Interpreter.h
interpreter/cling/lib/Interpreter/IncrementalExecutor.h
interpreter/cling/lib/Interpreter/IncrementalJIT.h
interpreter/cling/lib/Interpreter/Interpreter.cpp

This allows us to access the `llvm::orc::LLJIT` similar to the `getExecutionEngine` interface in clang-repl which is required for the functioning of libInterOp starting from LLVM 16
cc: @vgvassilev @devajithvs

[cling] Add interfaces that expose JIT

---

tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/test/ntuple_basics.cxx

Addresses point 9 in the HEP-CCE/SOP interface review.

[ntuple] add default constructor to REntry::RFieldToken

---

tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

avoids throwing an exception when creating the descriptor for an RNTuple containing an unknown column type. We want to support this case for forward compatibility. Also adds a unit test testing this specific case.
Some dedicated code needs to be added to the internals of RNTuple to support this kind of test case, but it's not exposed to the user.
Currently the test just checks that we can read back the descriptor. A future PR will add a "fwd compatibility mode" to the read options that'll allow a user to reconstruct the model skipping over fields containing unknown column types.

[ntuple] Add test for reading an unknown column type

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx

Prevents failures induced by #16338 for python3.8

[PyROOT] Prevent construction of aggregate initializer for std::tuple

---

roofit/roofitcore/inc/RooAbsCategory.h
roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/src/RooAbsCategory.cxx
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooAbsReal.cxx

Harmless change to circumvent errors like these when building RooFit standalone:
```
Error in <TProtoClass::FindDataMember>: data member with index 0 is not found in class tuple<TreeReadBuffer*,default_delete<TreeReadBuffer> >
Error in <CreateRealData>: Cannot find data member # 0 of class tuple<TreeReadBuffer*,default_delete<TreeReadBuffer> > for parent RooAddPdf!
Error in <TProtoClass::FindDataMember>: data member with index 1 is not found in class tuple<TreeReadBuffer*,default_delete<TreeReadBuffer> >
Error in <CreateRealData>: Cannot find data member # 1 of class tuple<TreeReadBuffer*,default_delete<TreeReadBuffer> > for parent RooAddPdf!
Error in <TProtoClass::FindDataMember>: data member with index 0 is not found in class tuple<TreeReadBuffer*,default_delete<TreeReadBuffer> >
Error …
```

[RF] Avoid using transient `std::unique_ptr`

---

roofit/roofitcore/src/TestStatistics/LikelihoodJob.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx

Set the default LikelihoodJob tasks to be component-wise splits rather than event-wise splits

[RF] change default LikelihoodJob task splitting mode

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_cast.cxx
tree/ntuple/v7/test/ntuple_packing.cxx

Introducing the intermediate class RFloatField<T> that is inherited by RField<float> and RField<double> which exposes the SetHalfPrecision(), SetTruncated() and SetQuantized() methods for both classes.
This also adds the previously-missing but advertised `double -> Real16` mapping and the `double -> Real32Trunc` mapping

[ntuple] allow double -> Real32Quant mapping

---

tree/ntuple/v7/src/RField.cxx

adds UInts to `RField::AutoAdjustColumnTypes` to make sure we don't split them when compression is 0, similarly to Int and Real types.

[ntuple] don't split UInts when compression is 0

---

.github/workflows/root-ci.yml

Due to the automatically assigned github runner labels, the GPU runner will pick up CPU builds, so their labels had to be made more specific.

[CI] Update runner labels to avoid running on GPUs.

---

tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/rfield_vector.cxx

Add custom implementation of RBitsetField::ReadInClusterImpl(). Without, in an attempt to read the field with cluster-local addressing, the implementation in the base class translates the cluster-local index to a global index.  It does it incorrectly though because RFieldBase::ReadInClusterImpl() does not take into account the fact that the bitset field is backed by a repetitive column.
When reading the sub field of vectors, reading with cluster-local addressing is used.

[ntuple] Fix reading vectors of bitsets

---

core/base/src/TObject.cxx

On Windows, even `__declspec(no_sanitize_address)` does not prevent the `heap-use-after-free` errors when using the `/fsanitize=address` compiler flag, so don't even try.
Fixes https://github.com/root-project/root/issues/9445

[win][ASAN] Fix ASAN build on Windows

---

math/minuit2/inc/Minuit2/FCNAdapter.h
math/minuit2/inc/Minuit2/FCNBase.h
math/minuit2/inc/Minuit2/FCNGradAdapter.h
math/minuit2/inc/Minuit2/FumiliChi2FCN.h
math/minuit2/inc/Minuit2/FumiliFCNAdapter.h
math/minuit2/inc/Minuit2/FumiliFCNBase.h
math/minuit2/inc/Minuit2/FumiliMaximumLikelihoodFCN.h
math/minuit2/inc/Minuit2/FumiliStandardChi2FCN.h
math/minuit2/inc/Minuit2/FumiliStandardMaximumLikelihoodFCN.h
math/minuit2/inc/Minuit2/GenericFunction.h
math/minuit2/inc/Minuit2/ParametricFunction.h
math/minuit2/src/FumiliStandardChi2FCN.cxx
math/minuit2/src/FumiliStandardMaximumLikelihoodFCN.cxx
math/minuit2/src/ParametricFunction.cxx
math/minuit2/test/MnSim/GaussFcn.cxx
math/minuit2/test/MnSim/GaussFcn.h
math/minuit2/test/MnSim/GaussFcn2.cxx
math/minuit2/test/MnSim/GaussFcn2.h
math/minuit2/test/MnSim/GaussianModelFunction.h
math/minuit2/test/MnSim/ParallelTest.cxx
math/minuit2/test/MnSim/PaulTest4.cxx
math/minuit2/test/MnSim/ReneTest.cxx
math/minuit2/test/MnTutorial/Quad12F.h
math/minuit2/test/MnTutorial/Quad1F.h
math/minuit2/test/MnTutorial/Quad4F.h
math/minuit2/test/MnTutorial/Quad8F.h

This reverts part of 63636f6aeb3 from a few days ago, which also changed the interface of virtual functions, which was not the intention and breaks user code.

[Minuit2] Revert recent changes to virtual function signature

---

cmake/modules/RootConfiguration.cmake
config/__cplusplus.cxx

This PR is a successor to #14139, allowing CMake to configure ROOT when nvc++ is used as C++ compiler.

Allow CMake to configure with nvc++

---

roofit/roofitcore/test/TestStatistics/testRooRealL.cxx

Even if this only happens via the interpreter, it can cause trouble. This is also why the test was disable on Windows.
The point of the unit test is to cover the case of a Gaussian constraint, so we can just constrain another parameter and don't do the interpolation with the `PiecewiseInterpolation` class from HistFactory.

[RF] Avoid using HistFactory class in RooFitCore tests

---

bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx

[This commit](https://github.com/python/cpython/commit/ea2c0016502472aa8baa3149050ada776d17a009#diff-87272721a5cf1cd9915d6f503f6a7bbefa2f26c935c7ce83ca78706afd0ad05a) changed a PyObject field from a ssize_t to a union, so clang now wants parentheses around the object (this prevents building root with -Werror).
This was introduced in 3.12.0-beta1, aka PY_VERSION_HEX == 0x30c00b1.

[pyroot] fix clang warning due to changes in PyObject

---

core/testsupport/CMakeLists.txt

This allows downstream packages to also use the `ROOT_ADD_GTEST` macro in CMake with all its convenience.

[Core] Also build test support in case of `testing=OFF`

---

core/base/inc/Rtypes.h
core/base/inc/TColor.h
core/base/src/TColor.cxx
documentation/users-guide/Graphics.md
graf2d/gpad/src/TPad.cxx
hist/histpainter/src/THistPainter.cxx
tutorials/graphics/accessiblecolorschemes.C
tutorials/graphics/triangles.C
tutorials/hist/thstackcolorscheme.C

Choosing an appropriate color scheme is essential for making results easy to understand and
interpret. Factors like colorblindness and converting colors to grayscale for publications
can impact accessibility. Furthermore, results should be aesthetically pleasing. The following
three color schemes, recommended by M. Petroff in [arXiv:2107.02270v2](https://arxiv.org/pdf/2107.02270)
and available on [GitHub](https://github.com/mpetroff/accessible-color-cycles)
under the MIT License, meet these criteria.
- Implement the new three colors scheme in TColor.cxx et RTypes.h
- Add 3 missing colors (kBrown, kGrape and kAsh)
- Automaticallically set the name of a new color to its hexadecimal value
- Implement two new tutorials illustrating these new color schemes
- Update the doc
- Improve the dark …

New color schemes

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_cast.cxx

Enables reading a double on disk to a float in memory (relevant for schema evolution).
There is no bounds checking yet for floating point conversions. That will come as a separate PR.

[ntuple] Add type cast support from double to float

---

hist/hist/src/TH2.cxx

[skip-ci] Correcting minor typos in TH2.cxx

---

.github/workflows/root-ci.yml

- [CI] Update upload-artifact action to v4: Github will deprecate the v3 action soon.
- [CI] Add a 'cpu' label to self-hosted runner selection: Don't want it to run on GPU-enabled nodes.

[v6-28][CI] Update upload-artifact action; refine runner selection

---

gui/webgui6/src/TWebCanvas.cxx
hist/hist/inc/THStack.h
hist/hist/src/THStack.cxx

Extend `THStack::BuildPrimitives()` method and let rebuild list of stacked histograms.
Fixes problem when `THStack::GetXaxis()` called in web mode - internal redrawing of the current pad lead to creation but then deletion of `fHistogram`. 
Behavior of normal graphics not changed

[webcanvas] Fix THStack handling

---

.github/workflows/root-ci.yml

- [CI] Update upload-artifact action to v4: Github will deprecate the v3 action soon.
- [CI] Add a 'cpu' label to self-hosted runner selection: Don't want it to run on GPU-enabled nodes.

[v6-26][CI] Update upload-artifact action; refine runner selection

---

.github/workflows/root-ci.yml
.github/workflows/test-coverage.yml
.github/workflows/testsecurity.yml

The GPU runner was attracting CPU-only jobs, since all runner labels in use so far were automatic github labels. Here, a unique label is added to steer the jobs correctly.
Furthermore, the upload-artifact action starts warning about an imminent deprecation, so it's updated to v4 here.
This uncovered a name clash, where two builds on the same image would race to upload artifacts. This seems to be OK in v3, but not in v4.

[CI] Add a cpu label to github workflows; update actions.

---

gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx

While webcanvas has internal batch buffer, one can reuse it also 
for creating PDF with several pages. Directly syntax supported:
```
c1->Print("kern.pdf(");
c2->Print("kern.pdf");
c3->Print("kern.pdf");
c4->Print("kern.pdf");
c5->Print("kern.pdf)");
```
It is equivalent to:
```
TCanvas::SaveAll({c1,c2,c3,c4,c5}, "kern.pdf");
```
Also one can use "kern.pdf[" and "kern.pdf]" arguments, when PDF is open/closed without including of canvas into the output PDF

[webcanv] support multipage PDF syntax

---

tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/rfield_check.cxx

Also adjust `rfield_check` that was checking the wrong message.

[ntuple] fix missing return in RField::Check

---

tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_project.cxx

We may want to add support for this in the future, especially if the array is the leaf (e.g. to make an alias field of a fixed-size array).

[ntuple] Forbid projections across arrays

---

test/CMakeLists.txt

Seems to be headless usage of Firefox not yet tested there

Disable `test-stressgraphics-firefox` on Mac

---

builtins/glew/CMakeLists.txt
cmake/modules/SearchInstalledSoftware.cmake
graf2d/cocoa/CMakeLists.txt
graf2d/cocoa/src/TGCocoa.mm

1) Don't force user to build graf3d OpenGL features if `cocoa=ON`
2) Require asimage=ON in case of opengl=ON
More detail in the commit description. I have tested on macOS that the first commit does what it should.
Closes #16250.

[CMake] Improvements related to `opengl` build configuration flag

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_packing.cxx

The RField<ClusterSize_t> field must only be used for reading.

[ntuple] Remove RField<ClusterSize_t>

---

tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tree/ntuple/v7/test/ntuple_test.hxx
tutorials/v7/ntuple/ntpl012_processor.C

This PR moves the `RNTupleProcessor` out of the internal namespace. The rationale behind this change is that it will not only be used internally (e.g. RDataFrame), but we also foresee use by (experiment framework) developers looking for ways to combine multiple RNTuples at runtime.

[ntuple] Move `RNTupleProcessor` out of `Internal`

---

tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/ntuple_compat.cxx

adds an option to CreateModel: `fForwardCompatible`. If true, the model will be created successfully even if the RNTuple contains unknown column types, and all fields that recursively contain one will be skipped and won't appear in the model.
Depends on #16627
#16602 will be rebased on this.

[ntuple] add forward-compatibility mode to read unknown column types

---

io/io/src/TFileMerger.cxx

fixes `getDirectory` inside `TFileMerger.cxx` which is looking up objects by name rather than by full path.
Added regression test: https://github.com/root-project/roottest/pull/1191
This PR fixes #16190 and #16474

[io] Fix TFileMerger getDirectory not considering full path

---

roofit/histfactory/src/HistFactoryImpl.cxx
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx

xRooFit wants all floating parameters to have errors defined on them, so this PR gives them some default values (0 for normFactors, and the correct uncert for gamma factors)

[RooFit] - Set initial errors on some parameters that are missing their initial errors (norm and gamma factors)

---

tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tutorials/v7/ntuple/ntpl012_processor.C

This PR provides some refactoring around the `RNTupleProcessor`. Most notably, the `RNTupleProcessor` class has been changed into an abstract class only providing the generic interfaces. A subclass, `RNTupleChainProcessor` has been added to take care of the internal machinery for vertically concatenated ("chained") ntuples.
The rationale behind this refactoring is that in this way, we can also provide an `RNTupleJoinProcessor` subclass which takes care of horizontal concatenations, using the same class design. Once this has been added, the `RNTupleProcessor` base class could be used to take care of combinations of chain- and join-based processors and the scheduling thereof.

[ntuple] Refactor `RNTupleProcessor`, add `RNTupleChainProcessor` subclass

---

net/netxng/inc/TNetXNGFile.h
net/netxng/src/TNetXNGFile.cxx

This means that we won't have to install any headers from xrootd when using `builtin_xrootd=ON`. This makes systems that have both XRootD standalone and ROOT with builtin XRootD installed more stable.

Avoid XRootD dependency in public headers

---

builtins/davix/CMakeLists.txt
builtins/xrootd/CMakeLists.txt

In preparation for ubuntu 24.10
(see also https://github.com/root-project/root/issues/16654)

[ci] Update builtin xrootd and davix versions

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreal.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
roofit/roofit/inc/RooPyBind.h
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/src/RooAbsReal.cxx
tutorials/CMakeLists.txt
tutorials/roofit/rf207_comptools.py
tutorials/roofit/rf408_RDataFrameToRooFit.py
tutorials/roofit/rf508_listsetmanip.py
tutorials/roofit/rf515_hfJSON.py
tutorials/roofit/rf613_global_observables.py
tutorials/roofit/rf615_simulation_based_inference.py
tutorials/roofit/rf616_morphing.C
tutorials/roofit/rf616_morphing.py
tutorials/roofit/rf617_simulation_based_inference_multidimensional.py
tutorials/roofit/rf618_mixture_models.py
tutorials/roofit/rf710_roopoly.py

Fixed output by Morphing and SBI tutorials.

[RF] Fixed tutorial ouputs and other imporvements to SBI tutorials

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx
tree/ntuple/v7/test/ntuple_view.cxx

When we open an RNTuple from an anchor, we don't read the anchor with the mini file reader and therefore we must initialize the max key size manually from the given anchor. Otherwise, page coalescing won't work.

[ntuple] Fix read request coalescing when opening file from anchor

---

roofit/histfactory/CMakeLists.txt
roofit/histfactory/test/stressHistFactory.cxx

If `xml=OFF`, the test can still be compiled, which is always good for coverage. But it can't be run: the `hist2workspace` executable is missing.
This was discovered in this PR:
* https://github.com/root-project/root/pull/16674

[RF] Disable `stressHistFactroy` tests if ROOT was not built with XML

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/test/dataframe_snapshot.cxx

This Pull request makes the conversion of stl vectors to RVec optional when using Snapshot() 
Propagating the relevant flag to the Snapshot() call
This PR fixes #15503

[DF] Make vector to RVec conversion optional in Snapshot() of RDF

---

tree/ntuple/v7/test/ntuple_view.cxx

[NFC][ntuple] add clarifying comments

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/ntuple_basics.cxx

adds a `fCreateBare` option to `RCreateModelOptions that allows reconstructing a model without a default entry.
This PR fixes #16324

Ntuple model create bare

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Instead of throwing when deserializing a field with an unknown structural role, we assign to it structure == ENTupleStructure::kUnknown. 
FieldDescriptors with Unknown structural role will generate RInvalidFields upon calling CreateField(). 
This allows getting the descriptor for a future RNTuple from an old ROOT version.
A `fForwardCompatible` option is added to RCreateModelOptions to tell RNTuple to not throw when reconstructing the model for an RNTuple containing fields with an unknown structural role.

[ntuple] add fwd compat for unknown field structural role

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

fixes #16654
See also https://github.com/root-project/root/pull/16667 that on top of these changes adds a Ubuntu 24.10 build.

[cmake] Build clad with one core only

---

gui/webdisplay/src/RWebDisplayHandle.cxx

Chrome requires this option in headless mode - when run as superuser in CI
But for normal interactive mode newest chrome complains that option does not exists

[webgui] do not use `--no-sandbox` in interactive session

---

cmake/scripts/ROOTConfig.cmake.in

If components are not specified, we should assume nlohmann_json is not required. Propagating the dependency on nlohmann_json just for the sake of one ROOT feature (ROOTEve) that might be used is unreasonable. We can expect from the users that link against ROOTEve to list this component explicitly.

[CMake] Don't require `json` in ROOTConfig if no components specified

---

js/modules/base/latex.mjs
js/modules/core.mjs
net/http/src/THttpServer.cxx
tutorials/CMakeLists.txt
tutorials/webcanv/haxis.cxx
tutorials/webcanv/latex_url.cxx
tutorials/webcanv/triangle.cxx
tutorials/webgui/geom/geom_threejs.cxx
tutorials/webgui/geom/geom_threejs.html
tutorials/webgui/panel/webpanel.cxx
tutorials/webgui/webwindow/webwindow.cxx
tutorials/webgui/webwindow/webwindow.html

1. Fixing several formatting errors preventing doxygen generation
2. Rename files in `tutorials\webgui` to let correctly create doxygen
3. Fix jsroot_importmap generation for `jsroot/geom` and `jsroot/three`
4. Fix minimal error in JSROOT

[webgui] adjust tutorials, minimal jsroot fix

---

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/ntuple_view.cxx

This conveniently also allows looking at columns through a `typedef` that might only be available with a dictionary.

[ntuple] Allow casting with RNTupleViews

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_model.cxx

As a user-visible effect, fixes buffered writing when the model contains a class field or a TObject field and the column representation of (nested) members inside those fields were changed.

[ntuple] Fixes to model/field cloning

---

tutorials/CMakeLists.txt
tutorials/tmva/TMVA_SOFIE_GNN.py

[tmva] Impose correct test dependencies, avoid multiple invocations of Declare, avoid races when writing model files

---

tutorials/CMakeLists.txt
tutorials/roofit/rf615_simulation_based_inference.py
tutorials/roofit/rf617_simulation_based_inference_multidimensional.py
tutorials/roofit/rf618_mixture_models.py

Set the environment for the tutorials, which is the eventual ROOT_environ plus some environment variables related to limiting the number of threads used by NumPy.
See: https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy
Possibly related to #16552, but the main motivation is to avoid an excessive number of threads when running the RooFit tutorials for simulation based inference. So far, the environment was set inside these tutorials, but this is distracting to users who look at these tutorials.
Also, make sure that the same environment is used for all tutorials that are wrapped in `ROOT_ADD_TEST`.
Furthermore, remove unused helper function.

Limit number of threads used by NumPy in tutorials

---

tree/ntuple/v7/doc/specifications.md
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_modelext.cxx

Fixes the situation where the regular header uses projections and is then extended.

[ntuple] Fix column ID order

---

graf3d/ftgl/inc/FTContour.h
graf3d/ftgl/src/FTContour.cxx
graf3d/ftgl/src/FTVectoriser.cxx

Fixes a compiler warning.
Freetype 2.13.3 changed the type of a data member from char* to
unsigned char*, so we need to pass the correct type to FTContour to
avoid compiler warnings

[graf3d] use the proper type when interfacing with FT_Outline and FTContour

---

tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

This is causing `hadd` to ignore the compression options when merging RNTuples. We didn't catch this bug because the unit tests were bypassing TFileMerger and calling directly into RNTupleMerger.

[ntuple] fix RNTuple::Merge not passing mergeOpts to RNTupleMerger

---

hist/hist/src/TH2Poly.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_TH2Poly_GetNumberOfBins.cxx

This pull request fixes a segfault when calling `GetNumberOfBins()` on an empty TH2Poly by first checking whether `fBins` is null.
To reproduce the original segfault:
```c++
TH2Poly h; h.GetNumberOfBins();
```

[hist] Fix segfault when calling `GetNumberOfBins()` on an empty TH2Poly

---

roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
tutorials/CMakeLists.txt

The rf615 tutorial occasionally fails on cleanup on different platforms, hinting to a PyROOT issue. We disable the rf617 tutorial for now. as the covered RooFit functionality is also covered by rf617 (the multidimensional case).

[RF] Disable `rf615` tutorial test and `testLikelihoodJob` test that is prone to time out

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_types.cxx

* Mark (most) `RField` specializations as `final`; the only exception is `RField<std::array<ItemT, N>>` which is the base class of `RField<ItemT[N]>`.
* Mark (most) overriden functions in the `RFieldBase` hierarchy as final; the only exception is `RSimpleField::GenerateColumns` which is overriden by `RRealField`.
* Remove many duplicate implementations in the compile-time specialized classes: The reasoning is that we use the type-erased implementations with `RFieldBase::Create`, when reconstructing a model from disk, or when `Clone`ing a model. So if they are not performant, we have to fix them anyway. For completeness, there seems to be no performance change in the `iotools` benchmarks (with hot cache, to put emphasis on the RNTuple implementation).

[ntuple] Mark RField methods as final and remove duplicate implementations

---

tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/src/RField.cxx

Non-trivial clones go through a special constructor that resembles a copy constructor.

[ntuple] streamline field's CloneImpl() implementation

---

roofit/roofit/test/CMakeLists.txt
roofit/roofit/test/vectorisedPDFs/CMakeLists.txt
roofit/roofit/test/vectorisedPDFs/VectorisedPDFTests.cxx
roofit/roofit/test/vectorisedPDFs/VectorisedPDFTests.h
roofit/roofit/test/vectorisedPDFs/testAddPdf.cxx
roofit/roofit/test/vectorisedPDFs/testArgusBG.cxx
roofit/roofit/test/vectorisedPDFs/testBernstein.cxx
roofit/roofit/test/vectorisedPDFs/testBifurGauss.cxx
roofit/roofit/test/vectorisedPDFs/testBreitWigner.cxx
roofit/roofit/test/vectorisedPDFs/testBukin.cxx
roofit/roofit/test/vectorisedPDFs/testCBShape.cxx
roofit/roofit/test/vectorisedPDFs/testChebychev.cxx
roofit/roofit/test/vectorisedPDFs/testChiSquarePdf.cxx
roofit/roofit/test/vectorisedPDFs/testCompatMode.cxx
roofit/roofit/test/vectorisedPDFs/testDstD0BG.cxx
roofit/roofit/test/vectorisedPDFs/testExponential.cxx
roofit/roofit/test/vectorisedPDFs/testGamma.cxx
roofit/roofit/test/vectorisedPDFs/testGauss.cxx
roofit/roofit/test/vectorisedPDFs/testGaussBinned.cxx
roofit/roofit/test/vectorisedPDFs/testJohnson.cxx
roofit/roofit/test/vectorisedPDFs/testLandau.cxx
roofit/roofit/test/vectorisedPDFs/testLegendre.cxx
roofit/roofit/test/vectorisedPDFs/testLognormal.cxx
roofit/roofit/test/vectorisedPDFs/testNestedPDFs.cxx
roofit/roofit/test/vectorisedPDFs/testNovosibirsk.cxx
roofit/roofit/test/vectorisedPDFs/testPoisson.cxx
roofit/roofit/test/vectorisedPDFs/testPolynomial.cxx
roofit/roofit/test/vectorisedPDFs/testProductPdf.cxx
roofit/roofit/test/vectorisedPDFs/testVoigtian.cxx

These useful tests are relatively short (runtime 28 seconds in total) and test lower-level RooFit functionality.
Moving them from roottest to roofit has the following benefits:
* Faster RooFit development experience: it's not necessary anymore to also add and compile all of `roottest`, if you want to make sure locally that the vectorized pdf tests always compile and pass.
* The vectorized pdf tests will be able to consider the RooFit-internal preprocessor macros at build time, like `ROOFIT_CUDA` and `ROOFIT_LEGACY_EVAL_BACKEND`. Like this we can ensure that the tests will pass no matter how RooFit was configured at compile time. This is for me personally the strongest reason and was the motivator for this commit.
* Avoid code repetition in `root` and `roottest`, because now the vectorized …

[RF] Move vectorised PDF tests from roottest to roofit

---

hist/hist/src/TH2Poly.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_TH2Poly_GetNumberOfBins.cxx

Fix segfault when calling `GetNumberOfBins()` on an empty TH2Poly

---

hist/hist/src/TH2Poly.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_TH2Poly_GetNumberOfBins.cxx

Fix segfault when calling GetNumberOfBins() on an empty TH2Poly

---

tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RField.cxx

Allocate unique pointer pointees with `new`, so that it matches the default deleter.
This appears actually already in our unit tests when ran under valgrind.
In general, it would be useful to regularly run the unit tests under valgrind.

[ntuple] fix memory allocation in unique pointer field

---

CMakeLists.txt

This should partially solve the issue with the rebuild (linking) of ROOT when building the tests
See also: https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_TEST_ALL_DEPENDENCY.html
Requires CMake v3.29

[cmake][win] Set the CMAKE_SKIP_TEST_ALL_DEPENDENCY variable

---

requirements.txt

Some packages that we use in some unit tests and tutorials don't support Python 3.13 yet. They should be listed conditionally on the Python version to make the environment resolve.
This is required for building the Fedora 41 CI images.
Tested with Python 3.13 on Arch Linux.

Make `requirements.txt` resolvable in Python 3.13

---

tree/ntuple/v7/src/RNTupleSerialize.cxx

Fix a warning in RNTupleSerializer

[ntuple] rearrange code to avoid a compiler warning

---

CMakeLists.txt

This should partially solve the issue with the rebuild (linking) of ROOT when building the tests
See also: https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_TEST_ALL_DEPENDENCY.html
Requires CMake v3.29

[v6-30][cmake][win] Set the CMAKE_SKIP_TEST_ALL_DEPENDENCY variable

---

math/mathcore/inc/Math/CladDerivator.h
math/mathcore/inc/Math/PdfFuncMathCore.h
math/mathmore/inc/Math/SpecFuncMathMore.h
math/mathmore/src/SpecFuncMathMore.cxx
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

This is to avoid any num-diff fallback in RooFit, which results in annoying warnings for the user.
A new function `ROOT::Math::digamma` is added to the public interface, which wraps `gsl_sf_psi`. The digamma function is the derivative of `lgamma`, so it is used in `CladDerivator.h` to define the derivatives of `TMath::LnGamma` and the related gamma functions that are used to define Poisson cdfs.

[math] Support AD for `TMath::LnGamma` using functions from GSL

---

roofit/multiprocess/test/utils.h
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx

These VLAs are not part of the C++ standard and cause compiler warnings.
In this case, the arrays were only used to contain reference values, which can absolutely be done with `std::vector` on the heap.

[RF] Avoid using variable-length arrays in RooFit multiprocessing tests

---

tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_show.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntupleutil/v7/src/RNTupleImporter.cxx

* Remove dangerous `RField` constructors, where the user could pass subfields into typed `RField<std::pair<T1, T2>>` and `RField<std::tuple<ItemTs...>>` without checks.
* Avoid UB in `RRecordField` construction, related to unspecified order of evaluation of function arguments.
* Take container of `unique_ptr`'s by value, to signal ownership handover.
* Fix `fSize` calculation in `RRecordField::AttachItemFields`, to have less (critical) logic in the typed `RField` constructors.

[ntuple] Fixes and cleanups for `RRecordField` and subclasses

---

gui/webdisplay/src/RWebDisplayHandle.cxx

While Microsoft does not allow to use headless mode by default, 
do not try to use it without explicit argument `--web=edge`

[webgui] do not use Edge browser for headless by default

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
documentation/doxygen/MakeTCanvasJS.C
gui/webdisplay/src/RWebDisplayHandle.cxx
gui/webgui6/src/TWebCanvas.cxx
js/changes.md
js/modules/core.mjs
js/modules/geom/TGeoPainter.mjs
js/scripts/JSRoot.core.js

When created JSON should be used outside ROOT application and without running THttpServer,
it is better to use batch mode for generation of  JSON files. Places are:
1. jupyter
2. doxygen
3. c1->SaveAs("file.json")
Produced JSON is more robust and can be processed as is - how it is performed by the batch image production.
Main difference - extra JS modules directly embed into JSON. And `TF1` always store its values
Also configure `source_dir` of JSROOT when producing images. This let use local mathjax.
Update JSROOT with Android/TGeo fix.

[webcanv] use batch mode for stored JSON

---

tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

allows loading a RNTuple containing locators of unknown types. Rather than failing upon reading the RNTuple, we will throw an exception only when attempting to load a page containing an unknown locator type. This allows reconstructing the model and reading the descriptor.

[ntuple] allow reading a RNTuple with an unknown locator type

---

tree/ntuple/v7/doc/tuning.md
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx
tree/ntupleutil/v7/src/RNTupleImporter.cxx

Following the experience with AGC testing, double the default compressed cluster size to 100 MB and also double the maximum uncompressed cluster size to 1 GiB.

[ntuple] Adjust default cluster size

---

hist/hist/src/TH2Poly.cxx

Fixes https://github.com/root-project/root/issues/16771

[hist] prevent nullptr access with copy from default constructor

---

tmva/tmva/test/DNN/LSTM/CMakeLists.txt

The test TMVA-DNN-LSTM-BackpropagationCudnn crashes on ubuntu2404 cuda-12.6.1 with cudnn with the following stack trace:
```
0x00007fda7f0b5540 in <unknown> from /usr/lib64/libcuda.so.1
0x00007fda7ed1491e in <unknown> from /usr/lib64/libcuda.so.1
0x00007fda7f08f040 in <unknown> from /usr/lib64/libcuda.so.1
0x00007fda7ed0ef22 in <unknown> from /usr/lib64/libcuda.so.1
0x00007fda7eed2bae in <unknown> from /usr/lib64/libcuda.so.1
0x00007fdaaa248b01 in <unknown> from /usr/local/cuda-12.6/targets/x86_64-linux/lib/libcudart.so.12
0x00007fdaaa218baa in <unknown> from /usr/local/cuda-12.6/targets/x86_64-linux/lib/libcudart.so.12
0x00007fdaaa270721 in cudaMemcpy + 0x211 from /usr/local/cuda-12.6/targets/x86_64-linux/lib/libcudart.so.12
0x000055d25af29e37 in bool …
```

[TMVA] Disable a crashing cuDNN test.

---

.github/workflows/root-ci-config/buildconfig/fedora39.txt
.github/workflows/root-ci-config/buildconfig/fedora40.txt

There was an update to Pythia8 8.310 with my fix for compatibility with C++20.

[ci] Enable Pythia8 on Fedora + C++20

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTuple.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTuple.cxx

This allows programs (such as 3rd party readers) to create a RNTuple anchor while keeping it clear that "regular" users are not meant to do that.

[ntuple] make CreateAnchor a public internal free function

---

tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/src/RNTupleView.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx
tree/ntuple/v7/test/ntuple_view.cxx

There is not a well-defined good way to determine the number of things in a field without any further input. This has been used by the views, to iterate all the data of a (sub)field, independent of entry boundaries. This field range is now determined directly by the view from the descriptor.
Fixes #16588

[ntuple] Remove RFieldBase::GetNElements()

---

core/metacling/src/TClingCallbacks.cxx
core/metacling/test/TClingTests.cxx

This PR fixes https://github.com/root-project/root/issues/8367

[TCling] Do not add decls for control statements if already annotated 

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md

The original table format cannot be properly rendered by GH flavored markdown. This PR attempts to clear up the formatting, respecting the formatting specs (and limits thereof) of GH flavored Markdown.

[skip-ci][NFC][ntuple] Fix fundamental type table formatting

---

core/base/src/TROOT.cxx
main/python/cmdLineUtils.py
main/python/rootbrowse.py

Let configure web display kind when running `rootbrowse`
More important - run event loop when web-based browser is started.
In contrary to normal `TBrowser` one needs event loop running
Fix web-display configuration problem when `WebGui.Display: something` configured in rootrc file.
In such case always web-batch-mode kind was selected.
Addressing [question on forum](https://root-forum.cern.ch/t/is-there-an-option-to-customize-rootbrowse/62066/)

Fix problem with rootbrowse in web mode

---

math/mathcore/inc/Math/Minimizer.h
math/mathcore/src/Minimizer.cxx
math/minuit2/inc/Minuit2/Minuit2Minimizer.h
math/minuit2/inc/Minuit2/MnUserParameterState.h
math/minuit2/inc/Minuit2/MnUserTransformation.h
math/minuit2/inc/Minuit2/SinParameterTransformation.h
math/minuit2/inc/Minuit2/SqrtLowParameterTransformation.h
math/minuit2/inc/Minuit2/SqrtUpParameterTransformation.h
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnFunctionCross.cxx
math/minuit2/src/MnSeedGenerator.cxx
math/minuit2/src/MnUserParameterState.cxx
math/minuit2/src/MnUserTransformation.cxx
math/minuit2/src/SinParameterTransformation.cxx
math/minuit2/src/SqrtLowParameterTransformation.cxx
math/minuit2/src/SqrtUpParameterTransformation.cxx
math/minuit2/test/CMakeLists.txt
math/minuit2/test/testCovariance.cxx
roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooMinimizer.cxx

Modifies Minuit2 interface to pass initial error/covariance matrix or second derivatives (G2) vector.
This PR exploits existing code in `MnSeedGenerator` and introduces some improvements, namely:
1. Check whether provided matrix has positive diagonal (G2 must be positive) and larger than working precision `Eps`; if it is not the case, numerical computation is carried out.
2. Disable `NegativeG2LineSearch` whenever point 1 is satisfied.
Furthermore, this PR provides an interface to pass the error/covariance matrix or second derivatives (G2) vector via `ROOT::Math::Minimizer`. The user can provide either the error/covariance matrix in compressed format (column-major upper triangular part), OR the g2 vector, see the code snippet below. The matrix or second derivatives must take into account …

[Minuit2] Add interface to pass initial values/cov matrix

---

core/base/src/TROOT.cxx
main/python/cmdLineUtils.py

If web mode enabled (via .rootrc parameter), run event loop.
Correctly set web mode from .rootrc
Partial backport of #16807

Fix rootbrowse problem in web mode [6.32]

---

core/gui/inc/TBrowser.h
core/gui/inc/TBrowserImp.h
gui/browserv7/inc/ROOT/RWebBrowserImp.hxx
gui/webdisplay/src/RWebWindowsManager.cxx
main/python/cmdLineUtils.py

Returns kTRUE if web-based browser is used.
Works exactly the same way as `TWebCanvas::IsWeb()` - via TBrowserImp class.
Use flag in `cmdLineUtils.py` to run event loop for web-based TBrowser.
Also add check of `gROOT.IsInterrupted()` and `gSystem.ProcessEvents()` to break such event loop.

Implement `TBrowser::IsWeb()` method

---

config/rootssh

Exclude usage of local displays like `cef` or `qt6` on remote nodes 
By default such displays are used before real http server is started 
Therefore set explicitly such variable
Checked that rootssh from Linux to Mac is working.

[rootssh] export ROOT_WEBDISPLAY=server [skip-ci]

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Always-convert-returned-std-string.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Remove-implicit-conversion-of-any-ctypes-ptr.patch
bindings/pyroot/cppyy/sync-upstream

The `IsCTypesArrayOrPointer` gives false positives in Python 3.13, resulting the void pointer converter to take the wrong code path and crash. See:
https://github.com/wlav/cppyy/issues/272
This code path is used for implicit conversion from other `ctypes` pointer types to `void*`, which is not strictly required. One can always do an explicit cast:  `ctypes.cast(my_ptr, ctypes.c_void_p )`.
Given that this a niche feature that broke Python 3.13 support for functions taking `void*`, which is quite common, it can be argued that it's better to remove this implicit conversion.
This commit fixes the following tests under Python 3.13:
```
roottest-python-basic-datatype
roottest-python-cpp-cpp
```
This reverts the following commit from upstream: …

[CPyCppyy] Remove implicit conversion of any ctypes ptr type to `void*`

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Always-convert-returned-std-string.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Remove-implicit-conversion-of-any-ctypes-ptr.patch
bindings/pyroot/cppyy/sync-upstream

Backport of https://github.com/root-project/root/pull/16816.

[v634][CPyCppyy] Remove implicit conversion of any ctypes ptr type to `void*`

---

CMakeLists.txt
cmake/modules/SearchInstalledSoftware.cmake

- The first error fixed is an unquoted variable that creates an error in the case that the remote repos of roottest are not called origin. It's relatively common to give the remotes useful names, and those users shouldn't be punished with weird errors.
- Re-enable FindGLEW. ROOT claims that the latest version of CMake has an error in FindGLEW. In fact, the error was fixed after cmake 3.25, so we can use system GLEW again starting from 3.26

Fix two CMake errors

---

tree/ntuple/v7/inc/ROOT/RColumnElementBase.hxx
tree/ntuple/v7/inc/ROOT/RPagePool.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RPagePool.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_pages.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

Fixes reading in IMT mode (parallel decompression) of columns that are unpacked into non-default in-memory types. This has been a conceptional issue: the parallel decompression and the page pool were not aware, so far, of the possibility of non-default in-memory types of pages. The issues was discovered in IMT reading of `Double32_t` in CMS MiniAODs.
Both, parallel decompression and the page pool are now fixed to handle non-default and multiple target in-memory types into which pages can be unsealed. The page pool will require more work. That's for a follow-up PR.
Fixes #16815

[ntuple] fix IMT reading with type cast

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md

document the default values in `RNTupleWriteOptions` next to the `Limits` section for reader's convenience.

[skip-ci][NFC][ntuple] document default RNTupleWriteOptions

---

README/ReleaseNotes/v636/index.md
roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
roofit/histfactory/src/ConfigParser.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/roofitcore/inc/RooAbsArg.h
roofit/roofitcore/inc/RooPlot.h
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooPlot.cxx
roofit/roostats/inc/RooStats/MarkovChain.h
roofit/roostats/src/MarkovChain.cxx

Execute on what was announced in the 6.34 release notes and indicated by deprecation macros and doxygen tags.
As ROOT 6.36 will be the next release after ROOT 6.34 and the current `master` branch is leading up to that next release, the code should be removed now.

[RF] Remove the deprecated RooFit code to be removed in ROOT 6.36

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md

[skip-ci][v6.34][NFC][ntuple] document default RNTupleWriteOptions

---

config/rootssh
gui/webdisplay/src/RWebWindowsManager.cxx

On the MacOS same unix sockets cannot be opened twice for listening - 
when using with `netcat` or `socat`
Therefore start `nc -k -l -U $socketfile > $socketfile.log` to redirect
socket output into the plain file permanently. 
And then monitor this file content - line by line.
Use `trap` command to cleanup all temporary files afterwards.
And from ROOT side need to send `\n` to ensure new lines in produced log file
This changes required to be able use `rootssh` from the MacOS

[rootssh] improve unix sockets handling

---

config/rootssh
gui/webdisplay/src/RWebWindowsManager.cxx

Backport #16819
On the MacOS same unix sockets cannot be opened twice for listening -
when using with netcat or socat
Therefore start nc -k -l -U $socketfile > $socketfile.log to redirect
socket output into the plain file permanently.
And then monitor this file content - line by line.
Use trap command to cleanup all temporary files afterwards.
And from ROOT side need to send \n to ensure new lines in produced log file
This changes required to be able use rootssh from the MacOS

[rootssh] improve unix sockets handling [6.34]

---

hist/hist/src/TH1.cxx

BP of https://github.com/root-project/root/pull/16793

[BP][hist] remove default parameter in TH1::GetQuantiles, as is the case with TF1::GetQuantiles

---

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/rfield_basics.cxx
tree/ntuple/v7/test/rfield_vector.cxx

Before, field name checking only took place in `RNTupleModel`. This PR performs the check upon construction of the `RFieldBase`. To still allow for special cases where fields can have an empty name, e.g. the zero field, this specific check has been moved out of `RFieldBase::EnsureValidFieldName` and to the places where this should actually be enforced.
Fixes #16834

[ntuple] Enforce valid naming upon field creation

---

config/rootrc.in
documentation/users-guide/WebDisplay.md
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowsManager.cxx
tutorials/webgui/ping/ping.cxx

For all widgets default will be single connection. Each widget can be connected only once.
Only when such default mode disabled, some widgets will be possible to connect multiple times

[webgui] Make default single connection

---

config/rootrc.in
documentation/users-guide/WebDisplay.md
graf3d/eve7/src/REveManager.cxx
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowsManager.cxx
tutorials/webgui/ping/ping.cxx

For all widgets default will be single connection. Each widget can be connected only once.
Only when such default mode disabled, some widgets will be possible to connect multiple times
Backport of #16455 and https://github.com/root-project/root/pull/16849

[webgui] Make default single connection [6.34]

---

.github/workflows/root-ci-config/buildconfig/fedora41.txt
.github/workflows/root-ci.yml
bindings/pyroot/cppyy/CPyCppyy/include/CPyCppyy/DispatchPtr.h
bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPEnum.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/DispatchPtr.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx
bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/cppyy/doc/source/changelog.rst
bindings/pyroot/cppyy/cppyy/python/cppyy/__init__.py
bindings/pyroot/cppyy/cppyy/python/cppyy/_stdcpp_fix.py
bindings/pyroot/cppyy/cppyy/test/advancedcpp.cxx
bindings/pyroot/cppyy/cppyy/test/test_datatypes.py
bindings/pyroot/cppyy/cppyy/test/test_fragile.py
bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
bindings/pyroot/cppyy/patches/CPyCppyy-Always-convert-returned-std-string.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Don-t-attempt-to-expose-protected-data-members.patch
bindings/pyroot/cppyy/patches/CPyCppyy-Prevent-construction-of-agg-init-for-tuple.patch
bindings/pyroot/cppyy/sync-upstream
bindings/tpython/src/TPyClassGenerator.cxx

1. Sync with upstream cppyy, mostly to avoid warnings when building with Python 3.13.
2. Use GetOptional family of C Python API where necessary
A regression in ROOT 6.32 was unearthed in the process: #16852.

Python 3.13 support

---

tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/test/ntuple_basics.cxx

RMiniFile only knows how to write into proper ROOT files. 
I went with the blacklist approach because there are a bunch of valid cases that are not just TFiles that we want to support (e.g. TMemFile, TBufferMergerFile, ...).

[ntuple] forbid creating a RNTupleWriter with an XML TFile

---

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/src/RNTupleView.cxx
tree/ntuple/v7/test/ntuple_view.cxx

The field range of a view is determined on construction. If the field is empty (no columns), the field range remains undefined. Currently, in this case the creation of the view fails. Change this to instead only fail on the attempt to actually access the field range (as opposed to, e.g., iterate over the entry range of the empty field).
Backport of #16832 
Fixes #16826

[v634][ntuple] Check field range validity only on access

---

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/src/RPageSinkBuf.cxx

There is a zip timer in `RPagePersistentSink`, used in `RPageSink{File,Daos}::CommitPageImpl`, but this code path not taken with buffered writing.

[ntuple] Add zip timer to `RPageSinkBuf`

---

js/changes.md
js/modules/base/FontHandler.mjs
js/modules/core.mjs
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/hist/TH2Painter.mjs
js/modules/hist/hist3d.mjs
js/modules/hist2d/TGraphPainter.mjs
ui5/canv/controller/Ged.controller.js
ui5/canv/view/Axis.fragment.xml

1. Select title and labels fonts for axis
2. Support labels and title rotation on lego plots
3. Properly center labels on 3d plots
4. Fix toggling 2d/3d mode with canvas resize in-between
Backport of #16865

[webcanvas] select axes fonts in GED [6.34]

---

CMakeLists.txt
cmake/modules/SearchInstalledSoftware.cmake

This is a backport of #16465, fixing
- An error with ROOT refusing to `FindGLEW` although the bug was fixed
- ROOT stopping to configure when roottest's remote is checked out under a different name than origin

[CMake] Fix two CMake errors

---

tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleUtil.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/rfield_basics.cxx

RNTuple naming rules are enforced when creating a field or a new RNTuple for writing. The function responsible for doing this check is extracted into a utility header.

[ntuple] Enforce RNTuple naming rules

---

.ci/format_script.sh

Avoid parsing of JavaScritpt code by tool primary dedicated for C++
Like in this case: https://github.com/root-project/root/actions/runs/11779886401/job/32809280148?pr=16883

Exclude JSROOT modules from clang-format check

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_regression.cxx

Extend the checks done on the file name string in the RDataFrame constructor(s) to be more resilient against different token types (e.g. wildcards vs URL options).
Fixes https://github.com/root-project/root/issues/16475

[rdf] Allow for more complex file names in constructor

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

The merger was calling RColumnElementBase::Generate() without specifying
the in-memory type. This would lead the element to be created with the
default in-memory type, which is wrong in some cases (e.g. when dealing
with fields with a different representation than the default)

[ntuple] Merger: properly handle columns with different representations 

---

tree/ntuple/v7/inc/ROOT/RNTupleIndex.hxx
tree/ntuple/v7/src/RNTupleIndex.cxx
tree/ntuple/v7/test/ntuple_index.cxx

The error message format was inconsistent with (most of) the other RNTuple error messages, which are typically not capitalized and don't end with a period.
In addition, the error message in the constructor when a join field is not present has been expanded to now also contain the name of the RNTuple.

[ntuple] Fixup `RNTupleIndex` error messages

---

core/testsupport/src/TestSupport.cxx
tree/ntuple/v7/doc/BinaryFormatSpecification.md
tree/ntuple/v7/inc/ROOT/RNTuple.hxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/rfield_class.cxx
tutorials/v7/ntuple/ntpl001_staff.C
tutorials/v7/ntuple/ntpl002_vector.C
tutorials/v7/ntuple/ntpl004_dimuon.C
tutorials/v7/ntuple/ntpl005_introspection.C
tutorials/v7/ntuple/ntpl006_friends.C
tutorials/v7/ntuple/ntpl007_mtFill.C
tutorials/v7/ntuple/ntpl008_import.C
tutorials/v7/ntuple/ntpl009_parallelWriter.C
tutorials/v7/ntuple/ntpl010_skim.C
tutorials/v7/ntuple/ntpl011_global_temperatures.C
tutorials/v7/ntuple/ntpl012_processor.C
tutorials/v7/ntuple/ntpl013_staged.C
tutorials/v7/ntuple/ntpl014_framework.C

[ntuple] Binary format version 1.0.0.0

---

gui/gui/src/TGNumberEntry.cxx

Fedora 40 build for 6.32.06 crashes when opening the parameter dialog of the Fit Panel
with a "buffer overflow detected" message.
Such behavior is caused by calls to `strlcpy` with an incorrect size of the destination buffer,
which this PR fixes.

Fix buffer overflow when opening the Fit Panel

---

.github/workflows/root-ci.yml

Due to DNS problems on the GPU runner, the build is too unstable to be part of the CI.

[CI] Disable GPU runs.

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tstyle.py
bindings/pyroot/pythonizations/test/memory.py

Similar to 18a7c1fd74c, since also any instantiated TStyle is owned by ROOT.
Closes #16918.
See:
https://github.com/root-project/root/blob/master/core/base/src/TStyle.cxx#L212

[PyROOT] Retain C++ memory ownership for TStyle

---

documentation/doxygen/filter.cxx
tutorials/graphics/AtlasExample.C
tutorials/graphics/accessiblecolorschemes.C
tutorials/graphics/archi.C
tutorials/graphics/arrows.C
tutorials/graphics/canvas.C
tutorials/graphics/canvas2.C
tutorials/graphics/ellipse.C
tutorials/graphics/inside.C
tutorials/graphics/mandelbrot.C
tutorials/graphics/schroedinger_hydrogen.C

Display a preview of the tutorial graphics output.
a new directive `\preview` allows to do that.

[skip-ci] Implement the preview of the tutorials

---

tree/tree/src/TTree.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-9961
The "bug" was introduced by https://github.com/root-project/root/commit/cd678fce958f93f18175a50017b105366c98f3e6

[tree] remove stray newline when printf with toponly

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/roofit/roocmdarg.py
roofit/roofitcore/inc/RooCmdArg.h
roofit/roofitcore/src/RooCmdArg.cxx

- Adds new Constructor interfaces to RooCmdArg
- Adds new printouts to RooCmdArg
RooCmdArg is a bit of an old-style piece of code that doesn't really work well with python.
Also, when talking among statistics code developers, it's commonplace to have to "exchange" fit arguments between codes ("what arguments to you pass to make it converge?").
For this purpose, it's very convenient to:
- be able to print the command arguments in a human-readable format, and
- directly use these printouts to copy&paste them into some other piece of code to make comparison studies
The changes in this PR make this possible with little effort.

[RF] Added new printout RooCmdArg to recreate constructor call

---

tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/test/ntuple_compat.cxx

This internal header should only be included once into the `ROOTNTuple` library and as little as possible in the tests because it defines symbols in anonymous namespaces, to avoid ODR violations in the test `ntuple_endian.cxx`.
Achieve this by moving `kTestFutureType` to `RNTupleUtil.hxx`, next to other definitions used for compatibility tests. This leaves includes in `RColumnElement.cxx` (for the `ROOTNTuple` library), as well as the two tests `ntuple_endian.cxx` and `ntuple_packing.cxx` that unit test individual instantiations. This should also avoid compiler warnings seen recently.

[ntuple] Reduce includes of RColumnElement.hxx

---

tree/ntuple/v7/inc/ROOT/RPage.hxx
tree/ntuple/v7/inc/ROOT/RPageAllocator.hxx
tree/ntuple/v7/inc/ROOT/RPagePool.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RPageAllocator.cxx
tree/ntuple/v7/src/RPagePool.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageSourceFriends.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_pages.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx

Improve the lookup complexity for pages in the page pool from linear to constant in well-behaved cases, i.e. if there is a small number of pages per column and cluster. Some smaller cleanups around the RPage/RPagePool logic.

[ntuple] Improve RPagePool

---

.github/workflows/root-ci-config/buildconfig/alma8.txt
.github/workflows/root-ci-config/buildconfig/alma9-clang.txt
.github/workflows/root-ci-config/buildconfig/alma9.txt
.github/workflows/root-ci-config/buildconfig/debian125.txt
.github/workflows/root-ci-config/buildconfig/fedora39.txt
.github/workflows/root-ci-config/buildconfig/fedora40.txt
.github/workflows/root-ci-config/buildconfig/fedora41.txt
.github/workflows/root-ci-config/buildconfig/ubuntu22.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2404.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2410.txt
.github/workflows/root-ci.yml

- Configure ccache at the beginning of the actions workflow.
- Use a large cache of 5G for special builds
- Use a a smaller one of 1.5G for the "standard" ones. This is to protect the general-purpose nodes from running out of space, as they are running many different containers over time.
- Enable ccache for all Linux builds in `master`.

[CI] Enable ccache for linux builds.

---

roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooMinimizer.cxx

In older ROOT versions, `RooMinimizer::FitResult` used to have a method called `GetCovarianceMatrix`.
This MR reinstates that old method for compatibility reasons. 

[RF] Add old getter for covariance matrix

---

roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h
roofit/histfactory/src/FlexibleInterpVar.cxx
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

As noted in GitHub issue #7103, the interpolation code 3 is the same as code 2 in the `FlexibleInterpVar` and the `PiecewiseInterpolation` classes.
According to some comments in the source code, interpolation code 3 was meant to be "a parabolic version of log-normal".
There were two options to fix this:
1) Actually implement this parabolic interpolation with linear
extrapolation, analogous to code 2 but in log space.
2) Clearly mark interpolation code 3 as non-existing.
This commit implements solution 2, because the interpolation code 3 is not mentioned anywhere outside the ROOT source code. Especially not is the HistFactory paper:
https://cds.cern.ch/record/1456844/files/CERN-OPEN-2012-016.pdf
Implementing a new interpolation scheme that apparently was not needed in the last 10 years …

[RF][HF] Clearly mark interpolation code 3 as unknown

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/roofit/roocmdarg.py
roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h
roofit/histfactory/src/FlexibleInterpVar.cxx
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofitcore/inc/RooCmdArg.h
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/src/RooCmdArg.cxx
roofit/roofitcore/src/RooMinimizer.cxx

Backport recent RooFit fixes to the release branch.

[v634][RF] Backport recent RooFit fixes to the release branch

---

core/metacling/src/TCling.cxx

exit with error1 code instead of crashing
Fixes https://its.cern.ch/jira/browse/ROOT-10239

[metacling] Prevent nullptr access if compiler instance was not created

---

tree/ntuple/v7/src/RNTuple.cxx

This makes the writing and reading paths symmetric.

[ntuple] Simplify `RNTuple::Streamer()`

---

geom/geom/inc/bvh/v2/bvh.h
graf3d/gl/src/TGLSdfFontMakerLowLevel.icxx

1. If you are using the `[[unlikely]]` attribute for your `if` of `else`, the curly brackets need to be written. Otherwise, the attribute will refer to the first statement in the code branch, which is meaningless because the statement will always be executed once the code branch is taken.
2. The `if constexpr` can be tricky with unused variables, because if the branch is not taken, it's clear at compile time and all variables only used in that branch are effectively unused. There was a case where the `if constexpr` branch used one variable, and the corresponding `else` used another variable of the same type. To avoid redundant computations and compiler warnings, only a single variable is now defined to what is needed respecively.
3. The return value of `fread` was unchecked. This commit …

Avoid compiler warnings

---

main/src/hadd.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

Currently the RNTupleMerger has a pretty confusing and unintuitive handling of `hadd`'s compression options.
To simplify the situation, this PR implements these simpler rules:
1. the output RNTuple and its container file always have the same compression
2.  if the user explicitly passes a compression settings (`-f[0-9]`), use that compression
3. if the user doesn't pass any compression flag, use 505 as the output compression
4. if the user passes `-ff` or `-fk`, open the first source file, grab the RNTuple inside it, peek the first column range we can find and use its compression settings as the output compression. This is different from the current behavior of using the same compression as the first source *file*, as that behavior is probably not what the user wants.
This requires …

[ntuple] Merger: fix handling of compression-related options

---

main/src/hadd.cxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

Backport of https://github.com/root-project/root/pull/16939, https://github.com/root-project/root/pull/16944/ and https://github.com/root-project/root/pull/16949.
This set of changes prevents the RNTupleMerger and hadd to write corrupted data in some circumstances and fixes hadd's behavior wrt the compression-related flags.

[6.34] Various fixes to RNTupleMerger

---

core/clingutils/src/TClingUtils.cxx

Suppose a TTree with valid branch names: "1_coef", "2_coef". With TTree MakeSelector, the converted cpp names now would lead to a duplication of variables. Fix this by prepending a char instead of removing the digits. Also, for the corner case that one passes an empty string, return the "minimally valid variable name in C++", ie just a "_". int _ is a valid variable name.
Related to https://github.com/root-project/root/pull/16992

[core] Ensure non-repeated converted ids and valid return if empty input

---

bindings/pyroot/pythonizations/test/pythonization_decorator.py

Fixes the following potential failure on some Windows machines:
```
2: ======================================================================
2: FAIL: test_all_global_classes_prefix (pythonization_decorator.PythonizationDecorator.test_all_global_classes_prefix)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "C:\root-dev\git\master\bindings\pyroot\pythonizations\test\pythonization_decorator.py", line 269, in test_all_global_classes_prefix
2:     self.assertEqual(executed.pop(0), class_name)
2: AssertionError: 'TApplication' != 'Foo'
2: - TApplication
2: + Foo
```

[win] Fix potential test failure on Windows

---

gui/gui/inc/TGClient.h
gui/gui/inc/TGPicture.h
gui/gui/inc/TGScrollBar.h
gui/gui/src/TGClient.cxx
gui/gui/src/TGPicture.cxx
gui/gui/src/TGScrollBar.cxx

Currently if any of the arrow_*.xpm pictures are not found, the ctor of TG[HV]Scrollbar returns early, causing some pointers to not be initialized. The application later dereferences those pointers and crashes.
This commit changes the behavior by returning a valid empty picture when the expected ones are not found, which allows the following logic to work normally.

[gui] Fix TGScrollbar handling of missing pictures

---

io/io/src/TDirectoryFile.cxx

Applies the warning that @silverweed suggested.
See https://github.com/root-project/root/issues/17003

[io] warn user about the trailing blanks being stripped from keyname upon writing

---

io/io/src/TDirectoryFile.cxx

BP of https://github.com/root-project/root/pull/17008

[6.34] [io] warn user about the trailing blanks being stripped from keyname upon writing

---

hist/hist/src/TAxis.cxx

[This issue](https://github.com/root-project/root/issues/16976) revealed a graphics bug when displaying underflow and overflow bins for non-equidistant histogram bins with error bars. The problem arose from a mismatch in the bin width computation in TAxis::GetBinWidth. When the range included underflow or overflow bins, the bin width was calculated using the closest bins, unlike the approach in TAxis::GetBinLowEdge and TAxis::GetBinUpEdge, which apply a specific computation in such cases. This PR updates TAxis::GetBinWidth to follow the same logic as these methods.
This PR also updates the documentation for TAxis::SetRange and TAxis::SetRangeUser, clarifying the interpretation of ranges that extend beyond the normal bin limits. With these clarifications, the warning about bin numbers …

Several fixes in TAxis

---

tree/ntuple/v7/test/ntuple_packing.cxx

A wrong copypaste caused UB in a test for Real32Quant (allocating only 1 byte of storage when 4 were needed)

[ntuple] fix out-of-bounds in Real32Quant test

---

tree/ntuple/v7/src/RFieldMeta.cxx

Fixes a compiler error:
```
no matching conversion for functional-style cast from 'const TObjArray' to 'ROOT::Detail::TRangeStaticCast<TObjString>' (aka 'TRangeCast<TObjString, false>')
```

[ntuple] add missing include in RFieldMeta

---

core/dictgen/src/rootcling_impl.cxx
core/metacling/src/TCling.cxx
core/metacling/src/TCling.h

applies vassilevs suggestions from https://github.com/root-project/root/pull/16928#discussion_r1845196637

[metacling] return instead of exit if no compiler instance

---

core/rint/src/TTabCom.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-6636 reported by @olifre
Sibling PR in https://github.com/root-project/roottest/pull/1218

[core] fix bug in tab completion with cv qualifiers

---

.clang-format

Without this, clang-format will try to collapse "short" enums on a single line.
Unfortunately, this hinders readability in some cases, as this for example is considered "short":
```
enum ENTupleStructure { kInvalid, kLeaf, kCollection, kRecord, kVariant, kUnsplit, kUnknown };
```

[skip-ci][clang-format] +AllowShortEnumsOnASingleLine: false

---

tutorials/CMakeLists.txt

This reverts commit 95e6d5949ee7c52758fffe6ff2e21a889b9a2227.
Fixes https://github.com/root-project/root/issues/15364

[ci] Re-enable tutorial-roostats-rs101_limitexample-py on Win

---

etc/runfirefox.sh

The `runfirefox.sh` script uses the shebang `#!/bin/sh` but uses bash constructs (like `[[`).

[etc] use bash instead of sh in runfirefox.sh

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tarray.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tcontext.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectoryfile.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfile.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py

Adding a `python` Doxygen anchor tag adds the possibility to directly link to PyROOT-specific docs, by appending "#python" to the doxygen link. For example, to get the PyROOT documentation for TTree, one can now use "https://root.cern/doc/master/classTTree.html#python".

[skip-ci] Add `python` anchor tag to PyROOT docs

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/src/RColumn.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleWriteOptions.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_model.py
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

... instead of the initial number of elements. This allows the user to turn off the adaptive page size algorithm completely by specifying the same values for the initial and maximum page size.

[ntuple] Allow configuration of initial page size

---

core/imt/inc/ROOT/TThreadExecutor.hxx

Fixes https://github.com/root-project/root/issues/16915

[core] Move TThreadExecutor::Map to public interface

---

core/base/src/TColor.cxx

[core] Adjust kp6Violet to the correct Petroff value, #7a21dd

---

core/base/src/TColor.cxx

BP of https://github.com/root-project/root/pull/17043

[6.34][core] Adjust kp6Violet to the correct Petroff value, #7a21dd

---

roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx

If only one of the pdfs in the RooSimultaneous can't provide an expected
number of events, calculating the relative number of events is futile
and will result in exceptions when trying to ask these pdfs for the
expected number of events.
This fixes a bug reported by @gartrog from ATLAS (crash when printing
workspaces with such pdfs).

[RF] Skip normalization over nEvents in RooSimultaneous if necessary

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py

Adds `TH1` PyROOT documentation on:
- how to fit histograms (with short <10 line examples) to ROOT built-in and user-defined functions
- how to access best-fit parameters and their errors
- a list to the other `.py` tutorials available.
Please feel free to suggest changes to the tone, style, contents or anything in this PR. 
The PyROOT documentation box that appears on the `TH1` class page.
This PR addresses https://github.com/orgs/root-project/projects/18.

[skip-ci] Add th1 pyroot fit documentation

---

test/CMakeLists.txt
tutorials/tree/copytree.C
tutorials/tree/copytree2.C
tutorials/tree/copytree3.C
tutorials/tree/tree4.C

- Copy ${ROOTSYS}/test/$<CONFIG>/libEvent.dll to ${ROOTSYS}/test/
- Fix dll name in several tree tutorials

[windows] Fix several tree tutorials

---

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/src/RNTupleFillContext.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx

Allows for explicit dataset commits. This is useful
- for the use in Python
- to extract the final metrics before destruction
- to properly handle exceptions during the final commit

[ntuple] Add RNTuple[Parallel]Writer::CommitDataset()

---

tmva/sofie/test/Conv1dModelGenerator.py
tmva/sofie/test/Conv2dModelGenerator.py
tmva/sofie/test/Conv3dModelGenerator.py
tmva/sofie/test/ConvTrans2dModelGenerator.py
tmva/sofie/test/LinearModelGenerator.py
tmva/sofie/test/RecurrentModelGenerator.py
tutorials/histfactory/makeQuickModel.py
tutorials/pyroot/graph.py
tutorials/pyroot/gui_ex.py
tutorials/pyroot/parse_CSV_file_with_TTree_ReadStream.py
tutorials/roofit/rf109_chi2residpull.py
tutorials/roofit/rf110_normintegration.py
tutorials/roofit/rf203_ranges.py
tutorials/roofit/rf308_normintegration2d.py
tutorials/roofit/rf402_datahandling.py
tutorials/roofit/rf403_weightedevts.py
tutorials/roofit/rf404_categories.py
tutorials/roofit/rf505_asciicfg.py
tutorials/roofit/rf508_listsetmanip.py
tutorials/roofit/rf602_chi2fit.py
tutorials/roofit/rf604_constraints.py
tutorials/roofit/rf607_fitresult.py
tutorials/roofit/rf901_numintconfig.py

This is not necessary anymore, as ROOT is only supporting Python 3 anyway.

[Python] Don't import print function from `__future__` in tutorials

---

tree/dataframe/test/dataframe_unified_constructor.cxx
tree/dataframe/test/datasource_ntuple.cxx
tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_checksum.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_extended.cxx
tree/ntuple/v7/test/ntuple_friends.cxx
tree/ntuple/v7/test/ntuple_index.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_modelext.cxx
tree/ntuple/v7/test/ntuple_project.cxx
tree/ntuple/v7/test/ntuple_storage.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/ntuple_test.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/ntuple_view.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx
tutorials/v7/ntuple/ntpl010_skim.C

Remove the parameter pack from RNTupleModel::MakeField() that has been
used to set an initial value for a field. This API only makes sense with
a default model. E.g., it is confusing with bare models (initial value
ignored) or with the parallel writer or if multiple entries are created.
In practice, the functionality to set an initial value is only useful
for tests and can in many cases be replaced by immediately dereferencing
the shared pointer returned from MakeField().
Companion PR: https://github.com/root-project/roottest/pull/1228

[ntuple] remove ArgsT template from MakeField

---

core/metacling/src/TClingCallbacks.cxx

Fixes commit https://github.com/root-project/root/commit/e601bf8032175c63780dcf5fb441bea2fa82bf5a and then removes the check from `AutoloadLibraryMU` (as I had requested in the original PR review).

[core] Fix early return in AutoloadLibraryGenerator

---

core/metacling/src/TClingCallFunc.cxx
core/metacling/test/CMakeLists.txt
core/metacling/test/TClingCallFuncTests.cxx
core/metacling/test/TClingCallFuncTests.py
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_basics.py

If a type is passed by value but cannot be copy-constructed, instead move the argument. This is important to make `std::unique_ptr` interfaces work from Python code. Note that there are corner cases where checking for a deleted copy constructor is not sufficient; for example the STL always declares a copy constructor for `std::vector<std::unique_ptr<T>>`
which fails to instantiate if `T` is only moveable.
Closes #14425, alternative to #14426

[core] Move arguments with deleted copy ctor in TClingCallFunc

---

.gitignore

This gets generated by running `make` in the doxygen directory

[gitignore] ignore more stuff in documentation/doxygen

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooworkspace.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py

This makes it more efficient to explore files with RooFit workspaces in ipython and the jupyter notebook.

Support ipython tab completion when getting item TFile and RooWorkspace

---

core/metacling/src/TClingCallFunc.cxx

Commit 23bdb810d9 ("Optimize IsCopyConstructorDeleted") removed the fall-through return statement, leading compilers to complain that "control reaches end of non-void function".

[core] Fix compiler warning about missing return

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/th1_fillN.py
tutorials/dataframe/df017_vecOpsHEP.py
tutorials/fit/fitConvolution.py
tutorials/hist/twoscales.py
tutorials/math/tStudent.py
tutorials/roofit/rf102_dataimport.py
tutorials/roofit/rf401_importttreethx.py

This makes `Fill()` more pythonic as one can do:
```python
import numpy as np
data = np.array([1., 2, 2, 3, 3, 3, 4, 4, 5])
hist = ROOT.TH1F("hist", "hist", 5, 0, 10)
hist.Fill(data)
```
instead of
```py
hist.FillN(len(data), data, np.ones(len(data)))
```

Allow passing numpy array to TH1::Fill()

---

test/stressProof.cxx

Fix path to `getProof.C` in test

---

bindings/pyroot/pythonizations/doc/index.md
bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
documentation/doxygen/Doxyfile
documentation/doxygen/filter.cxx
documentation/doxygen/makeinput.sh

Adds dedicated documentation page for listing PyROOT specific functions (such as `@pythonization`) and all the classes with python specific documentation.
The page should appear in the Reference Guide, left menu under `Functional Parts`.
- `\ingroup Pythonizations` can be used to add classes/functions/files to this page. The directive is added to `\pythondoc` #17052 so all the classes with `Python Interface` box should be added automatically
- `\cond` ,`\endcond` directives in `bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py` to hide internal functions from doxygen so they don't appear in search-box or file documentation
-  `PYTHON_DOCSTRING = YES`  in Doxyfile to have `"""`, `"""!` and `'''` docstrings appear as formated with Doxygen instead of `verbatim`
- …

[skip-ci] Add dedicated page for python specific user documentation

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_thistpainter.py

Creates a new Pythonization file `ROOT/_pythonization/_thistpainter.py` which only contains documentation on how to keep the TBrowser open in several simple PyROOT examples, and adds `_thistpainter.py` to the `CMakeLists.txt`. Based on interaction/information in this [forum post](https://root-forum.cern.ch/t/oop-pyroot-histogram-plotted-from-file-disappears-on-click/59303).
Please let me know if there is anything to fix/change.
Addresses hackathon item ["Document TH1 drawing with Python functions"](https://github.com/orgs/root-project/projects/18?pane=issue&itemId=88465159).

add PyROOT THistPainter documentation for keeping the TBrowser open

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectoryfile.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/tclass_dynamiccast.py
bindings/pyroot/pythonizations/test/tf_pycallables.py
bindings/pyroot/pythonizations/test/tobject_comparisonops.py
bindings/pyroot/pythonizations/test/tobject_contains.py

Unifies spelling of 'pythonization' across the codebase.
Typos in docstrings and comments: 'pythonisation' -> 'pythonizations'
Luckily all the file-names already have the form with 'z'

unify 'pythonization' spelling

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tf1.py

Adds a short code snippet where a TF1 is initialized in the ROOT constructor, and parameters are set from a np.array (also tested with array.array) using SetParameters.
This PR addresses the [Hackathon to-do item "Explore setting multiple parameters for a fit at once"](https://github.com/orgs/root-project/projects/18?pane=issue&itemId=88467009).

[skip-ci] Add documentation with short example with TF1.SetParameters from numpy array

---

graf2d/graf/inc/TGraphPolar.h
graf2d/graf/inc/TGraphPolargram.h
graf2d/graf/src/TGraphPolar.cxx
graf2d/graf/src/TGraphPolargram.cxx
gui/webgui6/src/TWebCanvas.cxx
hist/histpainter/src/TGraphPainter.cxx
js/changes.md
js/modules/core.mjs
js/modules/draw/TGraphPolarPainter.mjs
tutorials/graphs/graphpolar.C
tutorials/graphs/graphpolar2.C
tutorials/graphs/graphpolar3.C

These three options clearly specify angle axis range in `TGraphPolar`.
No longer required to update pad and access `TGraphPolargram` to change this setting.
Implement `TGraphPolar::CreatePolagram()` method to directly create `TGraphPolargram` instance 
which is match to data. Use it in native painter and in TWebCanvas.
Fix handling of 'O' option (orthogonal labels) for TGraphPolar, was not working. Used in `graphpolar3.C` tutorial.
Mention these and several other existing options in documentation.
Implement support of new options in JSROOT.

Implement 'R','D','G' draw options for `TGraphPolar`, fix 'O' option

---

gui/webdisplay/test/CMakeLists.txt

For some reasons chrome does not exit normally after the test, therefore disable it until problem is identified

Disable test-webgui-ping for Mac

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py

Avoids the following warning
```
lib/ROOT/_pythonization/__init__.py:27: SyntaxWarning: invalid escape sequence '\i'
```
caused by the `\ingroup` doxygen tag, by writing the docstring as a raw string literal.

[skip-ci] [python] Fix syntax warning in docstring

---

math/genvector/doc/index.md

Adds a short note about an unintuitive behavior of 4-vector negation for coordinate systems based on mass instead of energy (#15842)
This the same note as in #17049 but this time it will also appear in the Reference Documentation

[skip-ci] Add a note in reference about the coordinate system negation pitfalls

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/ntuple/v7/test/ntuple_basics.py

Forbid default entries in Python, pythonize `REntry` to behave as a dict, and provide context manager functions for `RNTupleWriter`.

[ntuple] Implement minimal Python API

---

gui/webdisplay/src/RWebDisplayHandle.cxx

This mode used in ping.cxx test.
In some cases chrome browser does not close gracefully or
start crash reported.
Usage of `posix_spawn` allows kill chrome
Should solve problem with webgui-ping-test on Mac
Also Linux will be improved
Suppress stdout/stderr when using `posix_spawn`

[webgui] use posix_spawn to start chrome in headless for ping 

---

gui/webdisplay/test/CMakeLists.txt

For some reasons chrome does not exit normally after the test, therefore disable it until problem is identified

Disable test-webgui-ping for Mac [6.34] [skip-ci]

---

.github/workflows/code_analysis.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/test/ntuple_view.cxx

Some improvements to the `*Range` classes, adding a test for collection views, and then adding `RNTupleViewBase<T>::CreateBulk()` to support bulk-reading, which is most useful with `RNTupleCollectionView`s.

[ntuple] Support bulk-reading with views

---

math/minuit2/src/CMakeLists.txt

`math/minuit2/inc/Minuit2/FunctionMinimizer.h` was removed in 91bb4d7 (https://github.com/root-project/root/pull/16443) but there is still a reference to `FunctionMinimizer.h` in `math/minuit2/src/CMakeLists.txt` and this is causing the Minuit2 build to fail (e.g., https://github.com/Homebrew/homebrew-core/pull/199470#pullrequestreview-2470163494).

[Minuit2] Remove deleted header file reference

---

bindings/experimental/distrdf/python/DistRDF/HeadNode.py
bindings/experimental/distrdf/python/DistRDF/Node.py
bindings/experimental/distrdf/python/DistRDF/Proxy.py
bindings/experimental/distrdf/test/test_callable_generator.py
bindings/experimental/distrdf/test/test_proxy.py

Fixes #17145
In distributed RDataFrame, transformation operations (such as Define) from which other parts of the API depend upon (such as GetColumnNames or GetColumnType) are executed not only in the distributed tasks but also locally, to ensure those other functions can be called. Before this commit, this was done by simply appending the call to the local RDataFrame instance attached to the head node. This behaviour was limited, for example in case the same column name was used in two separate branches of the computation graph, one could see errors such as:
```
File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3cuda/Tue/x86_64-el8-gcc11-opt/lib/DistRDF/Proxy.py", line 275, in get_proxy_for
_update_internal_df_with_transformation(node, operation)
File …
```

[df] Ensure proper graph dependencies for local info in distributed mode

---

hist/histpainter/src/TGraphPainter.cxx
hist/histpainter/src/THistPainter.cxx

In `THistPainter::PaintTitle` the pave title is Drawn and Painted the Paint call should be done with the same option
used when the pave was created. 
Fixes #17076

Call TPaveText::Paint with the right option.

---

graf2d/graf/src/TPave.cxx

The handling of TPave options differed between `TPave::PaintPave` and `TPave::PaintPaveArc`. Specifically, in `TPave::PaintPaveArc`, the absence of one of the drawing options (`TR`, `TL`, `BR`, or `BL`) caused an incorrect shadow that completely obscured the TPave rendering. To address this, the default value when no valid drawing option is specified has been set to `BR`. Additionally, the `NB` option (no border) is now processed as documented in the `TPave::Paint` header.

The handling of TPave options was incorrect.

---

tutorials/v7/ntuple/ntpl012_processor_chain.C
tutorials/v7/ntuple/ntpl015_processor_join.C

This PR adds a tutorial for using the `RNTupleProcessor` to join two RNTuples. Once RNTupleProcessors are fully composable (see #17132), we might consider merging it with `ntpl012_processor_chain.C`.

[ntuple] Add a join processing tutorial

---

core/metacling/src/TClingCallbacks.cxx

Use `AbsoluteSymbolsMaterializationUnit` to define the symbols.

[core] Fold AutoloadLibraryMU into AutoloadLibraryGenerator

---

math/mathcore/inc/TMath.h
math/mathcore/test/testTMath.cxx

Dear All. This pull request adds gradient and Laplacian methods for arrays. These can be used to calculate one-dimensional first and second order derivatives. Should there also be methods for calculating higher order derivatives and dimensions?
I am open to any feedback regarding the code.
This PR fixes #14304

[TMath] Add Gradient and Laplacian methods for arrays

---

bindings/pyroot/pythonizations/test/import_load_libs.py

On some platforms, the low-level runtime library provided by GCC will also be loaded when importing ROOT. Therefore, it needs to be added to the whitelist such that the ROOT Python module tests don't fail because of it.
Fixes a test failure that I saw on my workstation with NixOS.

[PyROOT] Whitelist `libgcc_s` library in imported library test

---

tmva/sofie/inc/TMVA/ROperator_Reshape.hxx

Fix the following warning on 32 bit:
```
TMVA/ROperator_Reshape.hxx(82,74): warning GECC553F5: result of comparison of constant 9223372036854775807 with expression of type 'size_t' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
if ((output_length == 0 && fAllowZero == 0) || output_length > INT64_MAX) {
```

[TMVA] Fix warning on x86

---

documentation/users-guide/Graphics.md
tutorials/graphics/gaxis.C
tutorials/hist/reverseaxis.C

To change labels align `TGaxis` was slightly tilt.
Same can be achieved just by providing "L" as draw option of the `TGaxis`. 
This looks much more logical.
Adjust in tutorials and in documentation.

Do not use tilted `TGaxis` in tutorials

---

tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
tree/dataframe/inc/ROOT/RDF/RResultMap.hxx

In case VariationsFor is called on a branch of the computation graph without a Vary, the resulting map should be created just with the nominal value. When interacting with GetMergeableValue, it was instead creating a corrupted mergeable value for the map of variations, leading to segfaults. This commit cleanes the function logic and ensures that a correct, empty RMergeableVariations<T> is created when there are no variations in the branch, so that the nominal value can be added right after.
Fixes #17158 
Sibling roottest PR at https://github.com/root-project/roottest/pull/1229

Fix wrong interaction between VariationsFor,Vary,GetMergeableValue

---

tutorials/multicore/mp103_processSelector.C
tutorials/multicore/mp104_processH1.C
tutorials/multicore/mp105_processEntryList.C

Fixes failures caused by https://github.com/root-project/root/pull/17097
```
1031:tutorial-multicore-mp103_processSelector
1032:tutorial-multicore-mp104_processH1
1033:tutorial-multicore-mp105_processEntryList
```

[tutorials] Fix paths in multicore tutorials

---

roofit/roofitcore/src/RooDataSet.cxx

Commit b0d96bf3 from 5 years ago invalidated some part of the documentation which needs to be updated accordingly: the TTrees underlying the RooTreeDataStore are not attached to any TFile anymore, therefore we should not write about how the tree-backed store could help to reduce RAM usage.
Inspired by this forum post:
https://root-forum.cern.ch/t/large-tree-based-roodataset/62366/4

[RF] Clarify ownership of underlying TTree for RooDataSet

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooabsreal.py
roofit/histfactory/test/testHistFactory.cxx
roofit/roofit/test/testRooPoisson.cxx
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/test/testRooAbsPdf.cxx
roofit/roofitcore/test/testRooDataHist.cxx
roofit/roofitcore/test/testRooProdPdf.cxx
roofit/roofitcore/test/testRooWrapperPdf.cxx

Calling RooAbsReal::getVal() with r-value references to the normalization set (i.e. with RooArgSets that are created in place) is a bad idea, because it breaks RooFits caching logic and potentially introduces significant overhead.
There was even a dedicated Pythonization to deal with the related memory problems.
Since to avoid the problems and the need for a workaround in Python, this commit simply suggests to forbid calling getVal() with r-value references at runtime by printing a clear exception.

[RF] Forbid calling `getVal()` with r-value references to norm set

---

README/ReleaseNotes/v636/index.md
core/foundation/inc/ROOT/RConfig.hxx
roofit/roofitcore/inc/RooDataSet.h
roofit/roofitcore/test/stressRooFit_tests.h
roofit/roofitcore/test/testSumW2Error.cxx
tutorials/roofit/rf403_weightedevts.C
tutorials/roofit/rf403_weightedevts.py

The `RooDataSet` constructors to construct a dataset from a part of an
existing dataset are deprecated and will be removed in ROOT 6.38. This
is to avoid interface duplication. One should use `RooAbsData::reduce()`
instead, or to change the weight column, the universal constructor with
the `Import()`, `Cut()`, and `WeightVar()` arguments.
The tutorials and tests were adjusted accordingly.
Also, fix a wrong comment in the `rf403` tutorials: they said that the
existing dataset is changed to interpret a different column as the
weight, but actually a new dataset was created. The comment is fixed in
this commit.

[RF] Deprecate RooDataSet constructors other than universal constructor

---

bindings/experimental/distrdf/python/DistRDF/Operation.py
tree/dataframe/src/RDataFrame.cxx

Adds `Alias()` to the list of actions supported in distributed RDF.
Alias is just added to the list of operations supported (and to the documentation).
Nothing more is needed to get it working.

[df] Add support for Alias() in DistRDF

---

graf2d/graf/inc/TPaveStats.h
graf2d/graf/src/TPaveStats.cxx
graf2d/graf/src/TPaveText.cxx
gui/webgui6/src/TWebCanvas.cxx
hist/histpainter/src/TGraphPainter.cxx
hist/histpainter/src/THistPainter.cxx

1. It must be used for TPaveStats - while it never appears in list of primitives
2. When call stats->Paint() - specify draw option, otherwise always default is used
3. Mark `TPaveStats::SetOption()` with `**MENU**` qualifier, hide from menu `TPaveStats::SetDrawOption()`
4. Let change margin in `TPaveStats` via context menu
5. Fix bug in `TPaveText::SetAllWith()` method
6. Adjust TWebCanvas to always add object to primitives with draw option

Clarify SetOption() usage in TPave classes

---

gui/webdisplay/src/RWebDisplayHandle.cxx
js/files/canv_batch.htm

Use of `posix_spawn()` allows directly control child process
and terminate it if something completely wrong happens.
Use `alarm()` to avoid endless wait for browser process.
After timeout alarm signal will be created and `waitpid()` function
will be interrupted.
Every time alarm signal is produced one can check that content of
dump file is ready. In such case one can terminate browser process early than reported by system.
Add small change in canv_batch.htm to add such special string
Ensure that environment exported to `posix_spawn()`. Important for firefox, 
which relies on shell variables.
Enable for chrome and firefox.

[webgui] Use `posix_spawn()` for batch image production

---

builtins/davix/CMakeLists.txt

Updates Davix when used from builtins. It uses a tarfile with an applied patch for rapidjson bundled inside Davix.
This PR fixes #17190

builtins: update Davix to add patch for gcc14 in rapidjson

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py
bindings/pyroot/pythonizations/test/memory.py

Just like in the case of the TTree constructor, Python does not own the TTree if the current directory is a TFile.
Fixes a failure in the CMSSW unit tests: https://github.com/cms-sw/cmsdist/pull/9542
Needs to be backported to the 6.34 release branch.

[PyROOT] Don't assume ownership of TTree created by `CloneTree()`

---

io/io/src/TBufferJSON.cxx
io/io/test/TBufferJSONTests.cxx

There is principal difference between `lst->Add(obj)` and `lst->Add(obj, "")`
In first case `TObjLink` is created, in second `TObjOptLink`.
When such `TList` was stored in JSON and read back, all entries in the `TList` were `TObjOptLink`
Now such situation marked specially and reconstructed `TList` object is correct.
Modify storage and reading part.
Add correspondent test.
IMPORTANT!!!
Normal ROOT I/O also has problem with such `TList`. When read from the buffer, 
all entries with **empty** options converted into `TObjLink`. But `TObjLink::GetOption()` returns not empty string 
but `obj->GetOption()`. 
This can change drawing of TCanvas, when such canvas read from the file. 
There are many classes like `TH1` or `TPave` implementing `GetOption()` method and 
potentially returning non-empty …

[json] correctly store/restore `TList`

---

core/winnt/src/TWinNTSystem.cxx

Try to fix this kind of error when running `testUnfold7c`
```
Error in <TPostScript::Text>: Cannot open temporary file: exampleTR.eps_tmp_7812`
```

[win] use `std::rename` instead of `::rename`

---

builtins/davix/CMakeLists.txt

BP of https://github.com/root-project/root/pull/17192

[6.34] builtins: update Davix to add patch for gcc14 in rapidjson

---

documentation/doxygen/Makefile

The doc Makefile produced an error because the unfold folder was moved. This prevented to build the master version of the doc.

[skip-ci] tutorials/unfold was moved

---

core/meta/inc/TClass.h
core/meta/inc/TStreamerElement.h
core/meta/src/TStreamerElement.cxx
io/io/inc/TStreamerInfoActions.h
io/io/src/TStreamerInfo.cxx
io/io/src/TStreamerInfoActions.cxx
io/io/src/TStreamerInfoReadBuffer.cxx

Backport #16995
Companion to https://github.com/root-project/roottest/pull/1240

[v634] Expansion of the TStreamerInfo actions.  

---

tree/ntuple/v7/src/RFieldSequenceContainer.cxx

For simple types, it can directly `AppendV` to the principal column (as other sequence containers already do).
---
We probably want to do the same for reading...

[ntuple] Optimize `RArrayField`

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx

Fixes https://github.com/root-project/root/issues/6607
Related: https://github.com/root-project/root/issues/10749
Sibling roottest PR: https://github.com/root-project/roottest/pull/1237

[core] remove class prefix if any in IsDefAlloc

---

tree/ntuple/v7/src/RNTupleProcessor.cxx

Fix the following runtime error with `ntuple-processor-join`:
```
[ RUN      ] RNTupleJoinProcessorTest.UnalignedSingleJoinField
C:\...\include\vector(1889) : Assertion failed: vector subscript out of range
```

Fix vector subscript out of range

---

hist/hist/inc/TAxis.h
hist/hist/inc/THnBase.h
hist/hist/inc/THnSparse.h
hist/hist/src/TAxis.cxx
hist/hist/src/THnBase.cxx
hist/hist/src/THnSparse.cxx

With ROOT6 understanding STL containers, there is no reason to pass arrays as two parameters ``(int size, some_t* array)``. 
A TAxis with custom bins can now be constructed from a ``std::vector<double>``, which will be convenient later. 
A THnSparseT can now be constructed from either a ``std::vector<TAxis*>`` (more in the spirit "always use pointers" of ROOT) or ``std::vector<TAxis>`` (which allows neatly filling the vector from a initializer list, but does not allow the reuse of one TAxis object in different vectors, not that I personally care). 
Both forms will allow providing some TAxis in the (bins, min, max) scheme and other axes as an explicit list, which previous constructors did not support. (I have not yet tested such histograms much yet.)
One might discuss marking the new TAxis …

New constructors for TAxis, THnSparse and friends.

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx

* Fix directory of `RBlob`s from `RFileProper`
* Simplify methods and implementations for reserving / writing `RBlob` keys
* Allow reserving blobs without writing key

[ntuple] `RMiniFile` improvements and preparations for parallel writing

---

core/base/src/TUrl.cxx
core/foundation/src/TClassEdit.cxx
core/meta/src/TClass.cxx
core/metacling/src/TCling.cxx
graf3d/gl/src/gl2ps.cxx
hist/hist/src/HFitImpl.cxx
interpreter/cling/lib/Interpreter/ForwardDeclPrinter.cpp
io/io/src/TFile.cxx
io/io/src/TMakeProject.cxx
io/io/src/TStreamerInfo.cxx
io/sql/src/TSQLObjectData.cxx
main/src/h2root.cxx
main/src/hadd.cxx
tree/tree/src/TBranch.cxx
tree/tree/src/TBranchElement.cxx
tree/tree/src/TBranchSTL.cxx
tree/tree/src/TTree.cxx
tree/treeplayer/src/TFormLeafInfo.cxx
tree/treeplayer/src/TTreePlayer.cxx

`strlen` cannot be a constexpr in all platforms otherwise.
This has probably no measurable performance gain, so feel free to close if you deem it's not worth.

strlen microoptimization: use compiletime-constant instead of runtime-constant

---

tree/treeplayer/inc/TFileDrawMap.h
tree/treeplayer/src/TFileDrawMap.cxx

1. Draw frame histogram and object only once
2. Use TH2 as frame histogram to properly handle zooming
3. In Paint method paint only TFileDrawMap itself
4. Keep generated branch colors to make reproducible painting
5. Make non-persistent TFile pointer, otherwise fails when reading
This version also reasonably works with web canvas

Many fixes in `TFileDrawMap`

---

tmva/pymva/src/MethodPyAdaBoost.cxx

Since scikit version 1.4 the SAMME.R algorithm is deprecated and it has been removed since version 1.6. Change default to use SAMME
See https://scikit-learn.org/1.5/modules/generated/sklearn.ensemble.AdaBoostClassifier.html
This should fix test failures observed since upgrading to latest scikit-version

[tmva][pymva] Change default algorithm for AdaBoost to SAMME

---

core/cont/inc/TCollectionProxyInfo.h
io/io/inc/TVirtualCollectionIterators.h
io/io/src/TEmulatedCollectionProxy.cxx
io/io/src/TEmulatedMapProxy.cxx
io/io/src/TGenCollectionProxy.cxx
io/io/src/TStreamerInfoActions.cxx

Fix the following error on Windows:
```
Debug assertion Failed!
Can't dereference value-initialized vector iterator
```
As the standard says:
`std::vector::end()` returns an iterator to the element following the last element of the vector.
This element acts as a placeholder; attempting to access it results in undefined behavior.
See https://en.cppreference.com/w/cpp/container/vector/end 
And with empty vectors, vector.begin() == vector.end()

Fix dereference value-initialized vector iterator

---

tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/src/RDFUtils.cxx

[df] Early return if empty string in InterpreterCalc

---

tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/test/ntuple_packing.cxx

- fix wrong calculation for maxErr in ntuple_packing
- fix wrong emin/emax adjustment in UnquantizeReals
- ensure min and max values of ValueRange are normal
This should fix an assertion failure observed on AArch64 by @hahnjo.
These bugs do *not* have the potential of generating corrupted data (barring users that pass exotic floats as min/max values), but they can trigger false positives of the "out of range" assertion failures.

[ntuple] some fixes to Real32Quant

---

.github/workflows/test-result-comment.yml

We always want to look at the latest test results; for example when rerunning a job with test failures in a workflow, its results should overwrite previous results.

[ci] Overwrite files when unzipping test results

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfilemerger.py
io/io/inc/TFileMerger.h
io/io/src/TFileMerger.cxx
tutorials/io/mergeFiles.py

`TFileMerger` lacks a reliable way to close the underlying output file when used from Python, as it relies on the destructor to do it.
This PR adds an explicit `CloseOutputFile` method and makes `TFileMerger` a context manager in pyroot, allowing for uses such as:
```
with ROOT.TFileMerger() as merger:
merger.OutputFile("foo.root")
```
This PR fixes #17223

[io] Add a reliable way to close the TFileMerger's output file from Python

---

graf2d/gpad/src/TPad.cxx

Fix the following error in Debug mode with Runtime Check on Windows:
Debug Assertion Failed!
Expression: vector<bool> subscript out of range

[gpad] Fix Debug Assertion Failure in libGpad

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/inc/ROOT/RNTupleParallelWriter.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_minifile.cxx

With the patch, `RNTupleWriter::Append()` can take a sub directory in a TFile. On the reading side, the RNTupleReader understands a ntuple name of the form `[/]foo/bar/ntpl` and opens it correctly. Opening from the anchor directly anyway worked.
Fixes #14007

[ntuple] allow for writing into TFile subdir

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tfilemerger.py
io/io/inc/TFileMerger.h
io/io/src/TFileMerger.cxx
tutorials/io/mergeFiles.py

Bp of https://github.com/root-project/root/pull/17226

[6.34][io] Add a reliable way to close the TFileMerger's output file from Python

---

cmake/modules/RootBuildOptions.cmake
interpreter/cling/lib/Interpreter/BackendPasses.cpp

It was disabled in commit a67863d33a ("Disable modules on aarch64 due to ODR violation") in 2019. I cannot reproduce these problems on `lxplus-arm`, so try to turn it back on.

[runtime_cxxmodules] Enable on AArch64

---

tree/ntuple/v7/inc/ROOT/RClusterPool.hxx
tree/ntuple/v7/src/RClusterPool.cxx

Backport of #16931
Skips expanding the random access test from the original PR because that would require backporting further performance optimizations.

[v6.34][ntuple] Fix race in cluster pool

---

roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx

And ensure only current category state is considered, even in case where same pdf used for two states

RooSimultaneous: fix bug with category fraction calculation. 

---

io/io/src/TKey.cxx
io/io/test/TFileTests.cxx

Currently, the default title for a TKey is "object title". Objects that do not derive from TObject have no means to change this title. Change the default title to the empty string to save a few bytes per non-TObject object and to reduce the "noise" when listing directory contents.
Companion PR: https://github.com/root-project/roottest/pull/1242

[io] Set empty TKey default title

---

tutorials/CMakeLists.txt

Disable the testUnfold7c tutorial until we understand why it's sometimes failing with errors like:
Error in <TPostScript::Text>: Cannot open temporary file: iterative21.eps_tmp_735

Disable the testUnfold7c.C tutorial on Windows

---

graf3d/eve7/inc/ROOT/REveCaloData.hxx
graf3d/eve7/src/REveCaloData.cxx
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.cpp
interpreter/cling/tools/Jupyter/kernel/clingkernel.py
roofit/histfactory/inc/RooStats/HistFactory/HistRef.h
roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h

C++23 support of ROOT (see https://root-forum.cern.ch/t/enable-c-23-in-root-6-34-00-rc1/62433).
Some changes are needed for code using `std::unique_ptr`. According to C++ standards, in the context that `T` is declared but not defined, `std::unique_ptr<T>` is constructible but not destructible, thus we need to move the definitions of some functions calling `std::unique_ptr<T>::~unique_ptr` from the header file into the source file. This rule is not new in C++ 23, but it causes compile failure when `-std=c++23` is specified, so we must fix it to support C++ 23.

Add C++23 support

---

core/meta/inc/TClass.h
core/meta/inc/TStreamerElement.h
core/meta/src/TStreamerElement.cxx
io/io/inc/TStreamerInfoActions.h
io/io/src/TStreamerInfo.cxx
io/io/src/TStreamerInfoActions.cxx
io/io/src/TStreamerInfoReadBuffer.cxx

The PR https://github.com/root-project/root/pull/17202 changes the way that the enum with non-default size are stored (from one incorrect way to another incorrect way) and thus would make the challenge of writing rules/code to read those incorrectly written files harder.
We need https://github.com/root-project/root/pull/17009 to merge within the same release than this releases. #17009 is changing the file format and is waiting on confirmation that it is a complete solution
Companion to https://github.com/root-project/roottest/pull/1243

Revert v634 io actions expansion

---

roofit/roofitcore/inc/RooAbsFunc.h
roofit/roofitcore/src/RooBinIntegrator.cxx
roofit/roofitcore/src/RooBinIntegrator.h

Fixes https://its.cern.ch/jira/browse/ROOT-9996
Currently it failed silently for more than 3 dimensions

[RF] extend RooBinIntegrator to N-dimensions

---

tree/ntuple/v7/inc/ROOT/RCluster.hxx
tree/ntupleutil/CMakeLists.txt
tree/ntupleutil/v7/inc/ROOT/RNTupleExporter.hxx
tree/ntupleutil/v7/src/RNTupleExporter.cxx
tree/ntupleutil/v7/test/CMakeLists.txt
tree/ntupleutil/v7/test/ntuple_exporter.cxx
tree/ntupleutil/v7/test/ntupleutil_test.hxx

This is an internal utility used to dump pages of an RNTuple. In the future it might be extended to also dump other interesting things or accept a wider range of options (e.g. customize the output file names).
Ideally it should supersede [ntuple_dump.C](https://github.com/jblomer/iotools/blob/master/ntuple_dump.C).

[ntuple] create RNTupleExporter

---

README/ReleaseNotes/v634/index.md

(cherry picked from commit 0beff5893a1978fa45d3d63aeac58602709de013)

[skip-ci] wrong link in 6.34.02 release notes and add missing

---

tree/ntuple/v7/src/RColumnElement.hxx

Fix the following error on Windows:
```
Assertion failed: LeadingZeroes(q) >= unusedBits, file tree\ntuple\v7\src\RColumnElement.hxx, line 1038
```
`_BitScanReverse` returns the bit position of the first set bit (1) found,
so subtract it from the position of the last bit (31)

[rntuple] Fix assertion failure in RNtuple

---

tree/ntuple/v7/test/ntuple_processor_join.cxx

Fixes the mismatch between the test ntuple description and what was actually created. In addition, attempts to make a clearer separation between join scenarios, and adds a few extra test cases.
Related to #17132.

[ntuple] Refactor and add more `RNTupleJoinProcessor` tests

---

bindings/experimental/distrdf/python/DistRDF/HeadNode.py

This [PR](https://github.com/root-project/root/commit/08ef067250ed06de772579cbe8cb4c9c95a4dd10#diff-49294aaf61ddd05ba43b40ae651b081a608ee7b27e3c716e9b3a2d928cbf7ebfL363) changed the ownership model of external objects in distributed RDataFrame and now the module 'DistRDF.Ranges' does not include the attribute 'get_clusters_and_entries'.
However, Ranges.get_clusters_and_entries() is still being called in  DistRDF.HeadNode.py( [line486](https://github.com/root-project/root/blob/master/bindings/experimental/distrdf/python/DistRDF/HeadNode.py#L486), [line 666](https://github.com/root-project/root/blob/master/bindings/experimental/distrdf/python/DistRDF/HeadNode.py#L666) )
This PR fixes this issue.
This PR fixes https://github.com/root-project/root/issues/17263

Fix Ranges.get_clusters_and_entries in DistRDF.HeadNode.py

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/test/ntuple_evolution.cxx
tree/ntuple/v7/test/ntuple_types.cxx

They are skipped while reading in the same way as a transient member.

[ntuple] Mark missing fields for automatic schema evolution

---

tree/ntuple/v7/src/RNTupleProcessor.cxx

Refactoring `RNTupleJoinProcessor::LoadEntry`, along with the added documentation should make it easier to follow the entry loading logic (in particular between the primary ntuple and the auxiliary one, and the different code paths for aligned and unaligned joins) and more robust to other (future) code changes.
Related to #17132.

[ntuple] Refactor `RNTupleJoinProcessor::LoadEntry`

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Fixes several instances of lookups in the descriptor from linear to logarithmic complexity. As a result, many of the limit tests results improve significantly. So much so that I think we can turn on most of them on a regular basis.
Relies on #16986

[ntuple] Fixes lookup & searching in the descriptor

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tree/ntuple/v7/test/ntuple_processor_chain.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx

This PR improves the bookkeeping of entries in the `RNTupleProcessor`. Most importantly, a clearer distinction is made between the current entry number (relative to the currently open page source) and the number of entries processed. There was an incorrectness where this value was equal, whereas (assuming we linearly process one page source) `fNEntriesProcessed` should be higher than `fLocalEntryNumber` (e.g., after loading the first entry, `fNEntriesProcessed == 1`, and `fLocalEntryNumber == 0`).
In the process, some variables have been renamed to better capture their meaning.
As a consequence of this refactoring, the `RNTupleSingleProcessor` can now also handle empty ntuples.
Related to #17132.

[ntuple] Improve `RNTupleProcessor` entry number bookkeeping

---

core/base/src/TColor.cxx

The quotient of extremes 65535/255 was taken as calibration factor, but this is not a proper way of resampling integer variables, that only works well for doubles.
Related: https://root-forum.cern.ch/t/understanding-root-color-indexes/62464/30
There is this debug comment (still on master) that might be related:
https://github.com/root-project/root/commit/a09e2869bdec00bf1342b0c370e60316f9bb2da9#diff-479b410550ebac192a78a3adb39fa0c9b7bfdd162b92670b863219da062eeb80R1210

[core] fix non-proportional color resampling

---

bindings/pyroot/pythonizations/test/roofit/roodataset_numpy.py
math/matrix/inc/TVectorT.h
roofit/jsoninterface/CMakeLists.txt
roofit/jsoninterface/inc/RooFit/Detail/JSONInterface.h
roofit/jsoninterface/test/CMakeLists.txt
roofit/jsoninterface/test/testJSONInterface.cxx
roofit/roofitcore/inc/RooDataSet.h
tutorials/roostats/rs301_splot.C
tutorials/roostats/rs301_splot.py

… TVectorD
adds new `<<` operators to the RooFit JSONInterface
- add a new operator that can pipe `std::vector<T>` directly into json without explicit use of `fill_seq`.
- add a new operator that can pipe `std::map<T_string,T>` directly into json (using the `set_map` method`
- add an implicit conversion for `TVectorT` to `std::vector<T>` to facilitate direct piping of `TVectorT` into json as well via the new `std::vector<T>` operator

[RF] new pipe operators for JSONInterface

---

graf2d/postscript/src/TTeXDump.cxx

box stroke is only painted if opacity is 100%, as is the case with TPDF
See https://root-forum.cern.ch/t/image-quality-issue-when-saving-th2ds-drawn-with-colz-option-as-a-pdf/62334/18?u=ferhue

[graf2d] mimick TPDF behavior with box strokes also in TLatex

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Using the -DCLAD_SOURCE_DIR currently does not disable the git checkout. From the cmake documentation for ExternalProject_Add:
Note: If a download method is specified, any existing contents of the source directory may be deleted. Only the URL download method checks whether this directory is either missing or empty before initiating the download, stopping with an error if it is not empty. All other download methods silently discard any previous contents of the source directory.
Currently cmake deletes the source directory defined by -DCLAD_SOURCE_DIR and then tries to recreate it using a git checkout, but fails if there is no network available:
Cloning into 'clad-1.7'...
fatal: unable to access 'https://github.com/vgvassilev/clad.git/': Could not resolve host: github.com Cloning into …

Make -DCLAD_SOURCE_DIR option work

---

tutorials/CMakeLists.txt

Disable `run_h1analysis.C` because of Endpoint Security HTTP traffic scanning, which is corrupting the data on Windows

Disable run_h1analysis.C on Windows

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/test/ntuple_basics.py

The value held by an REntry for a particular field is retrieved as a shared_ptr to the underlying data. The actual type of the cppyy proxy depends on the type of the pointee. For most types, the Python proxy is exposed as a the type of the pointee: a `std::shared_ptr<std::vector>` is exposed as a `cppyy.gbl.std.vector`. For fundamental types, this does not happen: a `std::shared_ptr<int>` is exposed as `cppyy.gbl.std.shared_ptr[int]`. In the first case, we can retrieve the actual smart pointer via the `__smartptr__` method of the cppyy proxy. In the latter case, this method will return None.
For reading, it's sufficient to retrieve the smart pointer and return a read-only reference to the pointee via the `__deref__` method.
For writing, there is no automatic support for assignment to the …

[ntuple][python] Generalise getting and setting values of an REntry

---

tree/dataframe/inc/ROOT/RCsvDS.hxx
tree/dataframe/src/RCsvDS.cxx
tree/dataframe/test/datasource_csv.cxx
tree/dataframe/test/datasource_csv.py

adds a check that the number of items in the imposed column vector matches the number of columns in the CSV file. This avoid accessing `fHeaders` out of bounds and increases the robustness of the interface.
Also adding a test to `datasource_csv` and making sure all tests are run when needed (a couple of tests were mistakenly under the IMT ifdef guards)

[DF] add validation for number of column names imposed to CSV source

---

roofit/hs3/src/JSONFactories_RooFitCore.cxx

The parameter ordering bug in RooFormulaArgStreamer. I changed the code to remove the `vector< pair<RooAbsArg*, size_t> >` and just directly loop in reverse order over the parameters of the formula.
This PR fixes #17291

[RF] Fix parameter ordering bug in RooFormulaArgStreamer

---

core/base/src/TApplication.cxx
core/textinput/src/textinput/KeyBinding.cpp
core/textinput/src/textinput/SignalHandler.cpp
core/textinput/src/textinput/SignalHandler.h
core/textinput/src/textinput/TextInput.cpp

Finally, a way to hard-terminate ROOT with keyboard shortcut, without having to write .qqqqqqqqqq or closing the terminal.
Fixes https://its.cern.ch/jira/browse/ROOT-9906

[textinput] add CTRL-backslash as keyboard shortcut for sigquit 

---

tutorials/CMakeLists.txt

This PR does two things:
- Adds to the tutorials ran `tutorial-roostats-CreateExampleFile-py`. We want to test as many tutorials we distribute as possible. Proper dependencies are expressed (this takes something like 2 seconds, it will not affect ~at all the total duration of the builds)
- Changes the way in which the RS python tutorials depend on `CreateExampleFile-py`, properly expressing the dependency on the file created. This caused rare, but visible failures (e.g. https://github.com/root-project/root/actions/runs/12450432999/job/34757241276)

[RS] Increase test coverage (slightly) and streamline dependencies

---

tree/dataframe/test/dataframe_incomplete_entries.cxx
tree/tree/src/TChain.cxx

After merging #17301 , there is no need to create the logic to suppress the TChainIndex build error presently. The invalid read found by valgrind is still there, so this PR includes a test for the global join case and fixes the memory error.

Fix invalid read in TChain

---

.github/workflows/root-ci-config/build_root.py

Fixes:
```
/__w/root/root/.github/workflows/root-ci-config/build_root.py:539: SyntaxWarning: invalid escape sequence '\('
""", "Failed capture of lastest-stable underlying branch name")
```

CI: proper escaping of parentheses

---

hist/hist/src/HFitInterface.cxx

Unlike histograms, `TGraph` points are not necessarily stored in memory in ascending "X" coordinate pattern. Generaly speaking, when adding points to the `TGraph`, they are not sorted with respect to their X values. I noticed that this breaks the fitting algorithm. 
In my particular case, the `TGraph` was filled "backwards" - starting with points with larger X values and adding points in decreasing X. Graph plots just fine and visually looks just the same the same as if it was filled in ascending X manner. However, a simple `"gaus"` fit did not converge and ended up having a negative normalization constant (`Constant` fitting parameter).
Modifies the way the `BinData` object is populated with `TGraph` points. Instead of adding `TGraph`'s points to the `BinData` in the same pattern they …

Tweak fitting for TGraph to no assume points are in ascending order

---

interpreter/cling/tools/packaging/cpt.py

This PR fixes #406 mentioned in meta issue list (https://github.com/root-project/cling/issues/406)

[cling-cpt] Added some more fixes to the download_llvm_binary function [skip-ci]

---

hist/hist/inc/TH1.h
hist/hist/src/TH1.cxx

This is a follow up of https://github.com/root-project/root/pull/13748, which was modified by 
@guitargeek to fix the unnecessary use of exceptions.
Associated roottest PR:
* https://github.com/root-project/roottest/pull/1040
Made the static function `TH1::CheckConsistency` public, and changed its return type to `Int_t`.
Since the meaning of the returned integer is actually part of `EInconsistencyBits`, I made the `enum` public as well (but left the return value type to `Int_t`). This is done in a separate commit in case it is decided to keep the `enum` itself as an implementation detail.
At the moment `TH1::CheckConsistency` is called internally by `TH1::Add`, and error messages are print in case of failure, but continues the execution. Making it public allows user code to manually check …

Made public TH1::CheckConsistency (2)

---

README/ReleaseNotes/v636/index.md
math/smatrix/inc/Math/CholeskyDecomp.h

Many years ago, when I originially wrote the CholeskyDecompGenDim class, I argued that the class does not need copy constructor or assignment operator implementations because nobody would ever want to copy a decomposition. Well, it turns out that in today's world, one wants to be able to move (and potentially also copy) CholeskyDecompGenDim, so you can put it into an std::optional, for example, so you can return a std::nullopt if the decomposition state is not okay, and a decomposition otherwise. The code as it was up to this MR does not behave correctly if a CholeskyDecompGenDim is copied, moved or assigned. In the old code, if you copy or move a CholeskyDecompGenDim, you're likely to read garbage from the decomposition because of a potential for use-after-free, and/or get a double free …

[smatrix] fix potential double free in CholeskyDecompGenDim

---

tutorials/roostats/StandardBayesianMCMCDemo.py

This caused the file `example_combined_GaussExample_model.root` to be written again while other tutorials were already running, potentially resulting in short reads and test failures.

[RF] Fix inverted `gSystem.AccessPathName` in tutorial

---

tree/dataframe/src/RDataFrame.cxx

The `#distrdf` anchor is now not unique anymore, a new one has been written in https://github.com/root-project/root/blob/master/tutorials/analysis/dataframe/index.md . The anchor to the Python interface section has been updated, also that one needs disambiguation to avoid clashes with every other class with a Python interface section in the docs.

[skip-ci] Disambiguate URLs to sections in RDF docs

---

tutorials/roofit/rf615_simulation_based_inference.py
tutorials/roofit/rf617_simulation_based_inference_multidimensional.py
tutorials/roofit/rf618_mixture_models.py

Since we're not calling `ClearProxiedObjects()` anymore anyway, we don't need the hack to avoid it.

[Python] Remove hack to bypass `ClearProxiedObjects()` in tutorials

---

roofit/roofit/inc/RooCrystalBall.h

The RooCrystalBall class didn't have getters to its parameters yet, which we generally need for all commonly-used PDFs for model inspection and IO (other than IO with ROOT files).
Requested by @VanyaBelyaev.

[RF] Add parameter getters to RooCrystalBall

---

roofit/histfactory/src/RooBarlowBeestonLL.cxx
roofit/roofit/inc/RooChi2MCSModule.h
roofit/roofit/src/RooChi2MCSModule.cxx
roofit/roofitcore/inc/RooArgSet.h
roofit/roofitcore/src/ConstraintHelpers.cxx
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooProfileLL.cxx
roofit/roofitcore/src/RooRealMPFE.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/src/RooTreeDataStore.cxx
roofit/roofitcore/src/TestStatistics/ConstantTermsOptimizer.cxx
roofit/roofitcore/src/TestStatistics/buildLikelihood.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx

Support also `createNLL` in case of partially-extended simultaneous fits
with the new default CPU backend (and hence also "codegen").
This problem was reported by @gartrog in private communication.
The fix needs to be backported to the next 6.34 patch release.
Add also a corresponding test.
Some more commits in this PR improve the `RooArgSet` interface, fix a memory leak, and avoid manual memory management.

[RF] Support also `createNLL` in case of partially-extended simul. fits 

---

roofit/histfactory/src/RooBarlowBeestonLL.cxx
roofit/roofit/inc/RooChi2MCSModule.h
roofit/roofit/inc/RooCrystalBall.h
roofit/roofit/src/RooChi2MCSModule.cxx
roofit/roofitcore/inc/RooArgSet.h
roofit/roofitcore/src/ConstraintHelpers.cxx
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooProfileLL.cxx
roofit/roofitcore/src/RooRealMPFE.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/src/RooTreeDataStore.cxx
roofit/roofitcore/src/TestStatistics/ConstantTermsOptimizer.cxx
roofit/roofitcore/src/TestStatistics/buildLikelihood.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx
tutorials/roofit/rf615_simulation_based_inference.py
tutorials/roofit/rf617_simulation_based_inference_multidimensional.py
tutorials/roofit/rf618_mixture_models.py

Backports of recent fixes and improvements in RooFit to the 6.34 branch.

[v634][RF] Backports of recent fixes and improvements

---

tree/ntuple/v7/test/SimpleCollectionProxy.hxx

Dereferencing the end() iterator is UB, so we apply the same fix as commit 77c33187e3d678772870038e2874e803b1818619
This PR fixes #13568

[ntuple] fix UB in SimpleCollectionProxy

---

tree/ntuple/v7/src/RFieldSequenceContainer.cxx

Use `ReadV` when reading simple types in `RArrayField` 
This PR fixes #17214

[ntuple] use vector reads for simple types in RArrayField

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/test/ntuple_basics.py

As discussed around the RNTuple workshop, forbid calling `RNTupleModel::CreateEntry()` directly from Python. This allows to clone the passed `RNTupleModel` when creating a reader or writer, and avoid destructively passing the user argument.

[ntuple] Improvements of Python interface and tests

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx

When iterating over entries in the `RNTupleProcessor`, the entry is currently loaded twice: once on `RNTupleProcessor::Advance`, which is called when the iterator is incremented, and once when the iterator is dereferenced. This second call is unnecessary and only slows down the processor, so we should remove it.

[ntuple] Remove redundant `RNTupleProcessor::LoadEntry` call

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx

For non-fundamental types, we can avoid getting the smartptr just to deference or assign to it. Also forbid calling `REntry::GetPtr` from Python, it does not map well.

[ntuple] Simplify `REntry` pythonizations

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx

Experience with TTree processing has shown that the constructor taking an object is limited. Notably, it makes it more complicated to fully specify the input dataset in an isolated way, may be susceptible to side-effects and also complicates the logic when running distributedly. Thus, we can avoid having to suffer the same problems with RNTuple.

Remove limiting RNTuple factory function

---

net/http/src/THttpServer.cxx

If for any reasons `libRHTTPSniff.so` library not provided, 
create at least basic sniffer instead of ROOT crash
Address https://root-forum.cern.ch/t/thttpserver-crash/62615

[http] use basic sniffer if TRootSnifferFull cannot be created

---

hist/histpainter/src/THistPainter.cxx

This commit [1] completely screwed up the THispainter documentation. All the tables describing the options were destroyed.
[1] https://github.com/root-project/root/commit/0326ba02d4967beabef8613c02d6c79c72cd995e

[skip-ci] Fix THistpainter tables

---

hist/histpainter/src/TGraphPainter.cxx

This commit [1] screwed up the TGraphPainter documentation. 
[1] https://github.com/root-project/root/commit/0326ba02d4967beabef8613c02d6c79c72cd995e

[skip-ci] TGraphPainter doc

---

README/ReleaseNotes/v636/index.md
roofit/roofitcore/inc/RooRealVar.h
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooMCStudy.cxx
roofit/roofitcore/src/RooRealVar.cxx
roofit/roofitcore/test/testGlobalObservables.cxx

Returning a TString by raw pointer that the caller needs to delete is not memory safe and an outdated pattern, which merits a breaking change documented in the 6.36 release notes.

[RF] Change return type of `RooRealVar::format()` to std::string

---

config/root-config.bat.in

Fix an issue with `root-config.bat` when used in PowerShell like:
`Invoke-Expression "cl test.cpp $(root-config --cflags --libs)"`
as reported [on the Forum](https://root-forum.cern.ch/t/root-6-34-windows-compilation-w32pragma-issue-cea-43597/62630)

[windows] Fix root-config.bat for PowerShell

---

io/io/src/TFile.cxx

See related discussion: https://github.com/root-project/root/pull/14929
It was removed by https://github.com/ferdymercury/root/commit/41f67b698150140342e28560046266756f0570d5#comments but it shouldn't be exclusive, one can have Python interface open by default, and TFile format details closed by default.

[skip-ci] rescue collapsed-by-default section of TFile details

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/test/dataframe_snapshot.cxx

The current message is not clear enough and may lead to confusing situations such as the one reported at https://root-forum.cern.ch/t/some-problem-with-lazy-snapshots-in-rdataframe/46740

[df] Improve warning message when lazy Snapshot is not triggered

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RDF/RAction.hxx
tree/dataframe/inc/ROOT/RDF/RActionImpl.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/test/dataframe_vary.cxx

This commit introduces the behaviour of the Report action in case systematic variations were requested, i.e. it is now possible to call VariationsFor(report). In order to create a different report per variation, the proper branch of the computation graph with the filters of the "varied universe" must be retrieved. This requires knowing which is the variation being requested when cloning the ReportHelper instance. To this end, the signature of the MakeNew protocol used by the action helpers is extended to optionally take the name of the variation being requested. When creating the varied helpers, the action also passes the name of the variation. A test for this new functionality has been added.
Fixes https://github.com/root-project/root/issues/10551

[df] Integrate Report action with systematic variations

---

gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowWSHandler.hxx
js/modules/core.mjs
js/modules/gpad/TAxisPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/menu.mjs
js/modules/hist/TH3Painter.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/webwindow.mjs

There are different settings parameters for JSROOT, 
which normally changed from JS code. 
But some of these parameters need to be configured from C++ - like image resolution or usage of shortcut buttons.
Now it will be possible to done with method:
```
ROOT::RWebWindow::SetJSROOTSettings("{ ToolBar: false, CanEnlarge: false, CanvasScale: 2 }");
```

[webgui] let configure custom JSROOT `settings` with RWebWindow

---

geom/webviewer/inc/ROOT/RGeomData.hxx
geom/webviewer/src/RGeomData.cxx
geom/webviewer/src/RGeomViewer.cxx

If configuration parameters are changed, drawing data need to be rebuild 
Provide internal method to clear such draw data without mutex lock. 
Do not reset/create draw data without established connection
Fix problem with `web_cms.cxx` demo where draw options was not applied

[webgeom] correctly handle configuration change

---

tree/ntupleutil/v7/test/ntuple_exporter.cxx

[ntuple] check return value of fread in ntuple_exporter

---

tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_storage.cxx

Also add a bunch of `reserve()` where appropriate

[ntuple] set NEntries in RPagePersistentSink::InitFromDescriptor

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleExporter.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

Instead represent undefined/unknown compression settings by std::optional<>. Also allows for representing compression settings as _unsigned_ integer.
Companion PR: https://github.com/root-project/roottest/pull/1249

[ntuple] remove kNTupleUnknownCompression

---

bindings/experimental/distrdf/python/DistRDF/Backends/Dask/__init__.py
bindings/experimental/distrdf/python/DistRDF/Backends/Spark/__init__.py
bindings/experimental/distrdf/python/DistRDF/__init__.py
bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_facade.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py
tree/dataframe/src/RDataFrame.cxx
tutorials/analysis/dataframe/distrdf001_spark_connection.py
tutorials/analysis/dataframe/distrdf002_dask_connection.py
tutorials/analysis/dataframe/distrdf004_dask_lxbatch.py

Unify the main common entry points between local and distributed RDataFrame API. Currently these changes:
- The ROOT.RDataFrame constructor
- ROOT.RDF.RunGraphs
- ROOT.RDF.Experimental.VariationsFor
Anytime one of the above is called, a pythonization will dispatch to the appropriate RDataFrame flavour, depending on the arguments.
Previous usage of the distributed module with fully qualified names of functions still works, although usage of the unified API is preferrable and advisable.

[df] Unify local and distributed API

---

tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_packing.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntuple/v7/test/ntuple_test.hxx
tree/ntuple/v7/test/ntuple_zip.cxx

Minor optimization: use `MakeUninitArray` instead of `make_unique<T[]>` when the buffers don't need to be initialized.

[ntuple] use MakeUninitArray when appropriate in tests

---

interpreter/CMakeLists.txt

LLVM prints which projects and targets are enabled on every CMake invocation. This information is noise for most users of ROOT, so turn it off unless the user explicitly decided to see it.

[interpreter] Suppress STATUS messages from LLVM

---

graf2d/gpadv7/inc/ROOT/RVirtualCanvasPainter.hxx
tmva/tmva/inc/TMVA/RTensor.hxx

When fixed-size integer types are in use, gcc-15 requires the inclusion of `<cstdint>`.

Fix two includes to compile with gcc-15

---

geom/geom/src/TGeoBoolNode.cxx

Fixes a bug introduced by commit bb00507321
Points checked to be on surface were converted to a wrong reference frame.
Added protection against the number of points on mesh being zero

[geom] Fix for setting mesh points for composite shapes.

---

tree/ntupleutil/v7/src/RNTupleExporter.cxx

adds a check to RNTupleExporter that the given output path can be written to (currently it fails silently if not).

[ntupleutil] exporter: check that the output file is writable

---

roofit/codegen/src/CodegenImpl.cxx
roofit/histfactory/test/testHistFactory.cxx
roofit/roofitcore/inc/RooAbsBinning.h
roofit/roofitcore/inc/RooBinning.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h
roofit/roofitcore/inc/RooUniformBinning.h
roofit/roofitcore/src/RooAbsBinning.cxx
roofit/roofitcore/src/RooBinning.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooFit/CodegenContext.cxx
roofit/roofitcore/src/RooUniformBinning.cxx

Support the code generation also for template histograms with
non-uniform binning, to enable automatic differentiation for template
fits with non-uniform bins.
This was requested both by CMS and ATLAS users, because they use
non-uniform binnings in their Higgs combinations.

[RF] Support non-uniform binnings in codegen to enable AD for non-uniform template fits

---

README/ReleaseNotes/v636/index.md
core/clingutils/res/TClingUtils.h
core/clingutils/src/TClingUtils.cxx
core/dictgen/src/rootcling_impl.cxx
core/foundation/res/RConversionRuleParser.h
core/foundation/src/RConversionRuleParser.cxx
core/meta/inc/TClass.h
core/meta/inc/TSchemaRule.h
core/meta/src/TClass.cxx
core/meta/src/TGenericClassInfo.cxx
core/meta/src/TSchemaRule.cxx
core/meta/src/TSchemaRuleSet.cxx
core/meta/src/TStreamerElement.cxx
etc/class.rules
io/io/src/TBufferFile.cxx
io/io/src/TKey.cxx
io/io/src/TStreamerInfo.cxx
io/io/src/TStreamerInfoReadBuffer.cxx
io/io/src/TStreamerInfoWriteBuffer.cxx
tree/tree/src/TBranchElement.cxx
tree/treeplayer/src/TBranchProxy.cxx
tree/treeplayer/test/leafs.cxx

With these changes, one can request the schema evolution (usually implicit) of the input data members from the on-file type to a custom type.  Example of the changes support in the test  roottest/root/io/evolution/rules/execSourceTypes.cxx added by the [companion roottest PR](https://github.com/root-project/roottest/pull/1247)
This fixes #17346 17346

I/O Customizaton Rules: add support for changing the input type.

---

geom/geom/src/TGeoParallelWorld.cxx

Disables a c++20 [[unlikely]] hint to prevent a `-Wattributes` compilation warning
I just commented, not removed entirely, to disable the warning on c++17 or less mode. We have `R__unlikely`, which cannot be used in a multiple-branch statement.

[geom][mini] Disabling (temporarily) c++20 [[unlikely]] compiler hint.

---

gui/webdisplay/src/RWebWindowsManager.cxx

If web window requires usage of current directory, configure it earlier. 
Fix problem that `webpanel.cxx` example not working with `--web=server` mode
Fixes https://root-forum.cern.ch/t/webpanel-tutorial-error/62704

[webgui] properly configure usage of current dir

---

gui/webdisplay/src/RWebWindowsManager.cxx

If web window requires usage of current directory, configure it earlier. 
Fix problem that `webpanel.cxx` example not working with `--web=server` mode
Fixes https://root-forum.cern.ch/t/webpanel-tutorial-error/62704
Backport of  #17457

[webgui] properly configure usage of current dir [6.34]

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

Building ROOT with Clang 18 currently warns:
```
MathFuncs.h:784:34: warning: unused parameter 'args' [-Wunused-parameter]
```

[RF] Address Clang compiler warning

---

misc/minicern/src/cernlib.c

These changes make it possible to compile root 6.34.02 using gcc 15 on Fedora 42.
Also the following commits need to be backported from master:
commit 2884f67f5a145ef5d2ba1f8050b2b1a543d97881
commit cfc922131c8a977e14c6611ed991f0889b0c47c8
... and the following commits from LLVM:
commit llvm/llvm-project@7e44305041d96b064c197216b931ae3917a34ac1
commit llvm/llvm-project@7abf44069aec61eee147ca67a6333fc34583b524 (see PR llvm/llvm-project#123320)

Fixes for compiling with GCC 15 (Fedora 42)

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Adapt-to-no-std-in-ROOT.patch

Fixes issue: https://github.com/root-project/root/issues/17442 and re-enables the expected behaviour of:
```py
import cppyy
cppyy.cppdef(
"""
std::byte byVal() { return std::byte{2}; }
std::byte *byPtr() { return new std::byte{2}; }
"""
)
print(cppyy.gbl.byVal())
print(cppyy.gbl.byPtr())
print(cppyy.gbl.byPtr()[0])
```

[PyROOT] Add executors and converters for `std::byte`

---

hist/hist/inc/TH2Poly.h
hist/hist/src/TH2Poly.cxx

The `TH1` base class already implements the `Clone()` method in such a way that no TH1-derived class needs to re-implement it, also cloning the fit functions correctly:
https://github.com/root-project/root/blob/master/hist/hist/src/TH1.cxx
However, there is one TH1-derived class that again overrides `Clone()` with a fallback to `TNamed::Clone()`, falling back to the wrong base class.
This is one of the blockers for #17399, where such crashes appeared in the newly added tests.
One might also consider marking `TH1::Clone()` as `final` to avoid these kind of mistakes in the future.

[RF] Don't override `TObject::Clone()` in TH2Poly

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_memory_utils.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
bindings/pyroot/pythonizations/test/memory.py

Following up on #17250, also pythonizing the `TObject::Clone()` overrides to automatically give up the ownership.
Thanks to the following forum post for noticing this problem: https://root-forum.cern.ch/t/a-question-about-root/62617

[python] Pythonize `TObject::Clone()` overrides for correct ownership

---

tree/ntuple/v7/inc/ROOT/RCreateFieldOptions.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_emulated.cxx
tree/ntuple/v7/test/ntuple_evolution.cxx
tree/ntuple/v7/test/ntuple_fork.hxx

adds the option to "emulate" fields of unknown user-defined types (i.e. types for which we lack dictionaries) as RecordFields whose structure is reconstructed from the on-disk information. This is off by default but can be toggled via `RCreateModelOptions`.

[ntuple] allow RNTuple to emulate fields of unknown types via RecordFields

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Adapt-to-no-std-in-ROOT.patch

Backport changes from #17469 to the 6.32 branch

[v632] [PyROOT] Add executors and converters for `std::byte`

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Adapt-to-no-std-in-ROOT.patch

Backport changes from #17469 to the 6.34 branch. This is required to fix #17442

[v634] [PyROOT] Add executors and converters for `std::byte`

---

hist/hist/inc/TH1.h
hist/hist/inc/TH1K.h
hist/hist/inc/TH2.h
hist/hist/inc/TH2Poly.h
hist/hist/inc/TH3.h
hist/hist/src/TH1.cxx
hist/hist/src/TH1K.cxx
hist/hist/src/TH2.cxx
hist/hist/src/TH2Poly.cxx
hist/hist/src/TH3.cxx

The TH1K class implementation forgot to implement some abstract methods
from the TH1 class that need to be implemented.
As the TH1K is almost identical to TH1F (besides the KDE algorithm in
the bin lookup), the TH1F implementations are copy-pasted.
The incomplete implementation was noticed thanks to the test in #17399.
To make sure that these mistakes can't happen anymore, the virtual methods of `TH1` are made truly virtual in the sense of the C++ language standard. So far, the implementation was only telling you at runtime that the method should be overridden.

[hist] Make abstract TH1,2,3 methods truly abstract and add missing implementations

---

js/changes.md
js/modules/core.mjs
js/modules/draw.mjs

[jsroot] support RooEllipse class

---

tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
tree/dataframe/test/dataframe_vary.cxx

Fixes https://github.com/root-project/root/issues/17486

[df] Fix Vary sanity check for typedefs

---

CMakeLists.txt

Backport of #17498 for the convenience of packagers.

[v634] Support linking with mold>=2.32.0

---

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/src/RDataFrame.cxx

An action that fixes #11959. 
It was decided that we will refrain from adding another action to RDataFrame as the existing one already covers the functionality required. This PR enhances the documentation of GraphAssymErrors which should solve doubts of the users.

[skip-ci][df][doc] Enhance GraphAssymErrors description.

---

roofit/roofitcore/src/RooFit/Evaluator.cxx

This change is needed to also consider categorical parameters.
Closes #15701.

[RF] Include any fundamental args as variables of RooFit::Evaluator

---

interpreter/cling/lib/Interpreter/CMakeLists.txt

[cmake] macOS isysroot switch argument: fix typo

---

roofit/roofitcore/inc/RooFit/Detail/RooNormalizedPdf.h
roofit/roofitcore/src/RooAddHelpers.cxx
roofit/roofitcore/src/RooAddPdf.cxx
roofit/roofitcore/test/CMakeLists.txt
roofit/roofitcore/test/testRooAddPdf.cxx

By already normalizing the pdf components integrals to the right fit range, one can elide some potentially expensive numeric correction factor integrals.
The code that calculates the predicted number of events was updated accordingly, since it containts also some integrals that depend on the components normalization range.
Closes #12645.
A unit test that validates that there are no superfluous integrals in the case of the GitHub reproducer was also added.

[RF] Avoid unneeded cached projection integrals in RooAddPdf

---

README/ReleaseNotes/v636/index.md
roofit/roofitcore/src/RooCompositeDataStore.cxx
roofit/roofitcore/test/testRooDataSet.cxx

The `reduce` implementation for `RooCompositeDataStore` currently delegates all of its logic to the children datastores. 
The index category, however, is not contained inside the children and should be handled by the composite datastore itself.
This PR also adds a unit test that validates that the cut is correctly applied.
This PR fixes #15744

[RF] Account for cuts over the index category inside RooCompositeDataStore::reduce

---

README/ReleaseNotes/v636/index.md
roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooSimultaneous.h
roofit/roostats/src/ToyMCSampler.cxx
tutorials/roofit/roostats/TwoSidedFrequentistUpperLimitWithBands.C
tutorials/roofit/roostats/TwoSidedFrequentistUpperLimitWithBands.py

The `RooAbsPdf::generateSimGlobal()` method is deprecated and will be removed in ROOT 6.38. It only contains some workarounds that are not necessary anymore. One can just use the regular `RooAbsPdf::generate()` function.
Getting rid of these redundant functions will avoid user confusion.

[RF] Deprecate `RooAbsPdf::generateSimGlobal()`

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

It doesn't make much sense to return the descriptor by unique_ptr, because it's not polymorphic and it's not copyable, so value+move semantics do a better job (and they are consistent with the other descriptors).
Also marked all descriptor classes final because they're not meant to be overridden by users.

[ntuple] Make RNTupleDescriptor::Clone() return it by value

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_checksum.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/rfield_streamer.cxx

RNTupleMerger should share the lifetime of its destination file to better support incremental merging, e.g.
```c++
// open the destination file once
auto destination = CreatePageSink();
RNTupleMerger merger { *destination };
auto opts = RNTupleMergeOptions{};
opts.fMergingMode = ENTupleMergingMode::kUnion;
// keep merging stuff into it as it arrives (e.g. from the network)
while (auto result = AcquireSources()) {
merger.Merge(result->sources, opts);
}
```

[ntuple] Merger: pass the destination in the ctor rather than in Merge()

---

documentation/doxygen/filter.cxx

remove warning while generating the doc

[skip-ci] remove warning: multiple use of section label 'python' 

---

core/base/inc/TStyle.h
core/base/src/TStyle.cxx
graf2d/graf/src/TCandle.cxx

Implement:
```
gStyle->SetCandleCircleLineWidth(w);
gStyle->SetCandleCrossLineWidth(w);
```
As requested here: https://root-forum.cern.ch/t/how-to-make-marker-thicker/62338
Example:
```
void candleplot() {
gStyle->SetTimeOffset(0);
TDatime dateBegin(2010,1,1,0,0,0);
TDatime dateEnd(2011,1,1,0,0,0);
auto h1 = new TH2I("h1","Machine A + B",12,dateBegin.Convert(),dateEnd.Convert(),1000,0,1000);
h1->GetXaxis()->SetTimeDisplay(1);
h1->GetXaxis()->SetTimeFormat("%m/%y");
h1->GetXaxis()->SetTitle("Date [month/year]");
float Rand;
for (int i = dateBegin.Convert(); i < dateEnd.Convert(); i+=86400*30) {
for (int j = 0; j < 1000; j++) {
Rand = gRandom->Gaus(500+sin(i/10000000.)*100,50); h1->Fill(i,Rand);
}
}
gStyle->SetCandleCircleLineWidth(5);
gStyle->SetCandleCrossLineWidth(3); …
```

Allow to set the line width of candle markers

---

graf2d/graf/src/TLegend.cxx

I have encountered the case where the legend is being drawn to a separate pad from the object, which means the `GetDrawOption()` returns a blank string no matter how it was drawn in the other pad.
It would surely make most sense to have the decision about endcaps be determined from the TLegendEntry option, like all the other aspects of the drawing of the legend entry. 
This PR makes that change.

Use legend entry's option instead of object's DrawOption when deciding endcaps

---

graf2d/gpadv7/inc/ROOT/RVirtualCanvasPainter.hxx
misc/minicern/src/cernlib.c
tmva/tmva/inc/TMVA/RTensor.hxx

These are the backports for #17444

Backport missing includes for compilation with gcc-15

---

roofit/roofitcore/inc/RooProdPdf.h
roofit/roofitcore/src/RooProdGenContext.cxx
roofit/roofitcore/src/RooProdPdf.cxx

While trying to address the several GitHub issues related to
integrals of RooProdPdfs, I saw some opportunities to refactor the code
to avoid duplication, especially in `RooProdPdf::processProductTerm()`.
Besides refactoring to avoid code repetition, this PR includes commits that remove unnecessary commented-out lines with `std::cout`, and to introduce proper datastructures to move data around the `RooProdPdf` helper functions.

[RF] Refactor RooProdPdf for more concise code

---

core/winnt/src/TWinNTSystem.cxx

If TWinNTSystem::ExpandPathName is executed before gROOT is fully initialized, error messages were hiddem (for example about missing pcms)

core: Avoid TWinNTSystem::ExpandPathName suppressing real error.

---

core/base/src/TSystem.cxx

This might address the instability in roottest-root-io-evolution.
The companion roottest PR is https://github.com/root-project/roottest/pull/1254

ACLiC: use user provided library name for dependency filename

---

tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/inc/TTreeReaderArray.h
tree/treeplayer/inc/TTreeReaderValue.h
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/src/TTreeReaderArray.cxx
tree/treeplayer/src/TTreeReaderValue.cxx

This is just  running `clang-format -i filename`, also done in preparation for more changes needed by TTree-based processing in RDataFrame.

[tree] Apply clang-format to TTreeReader[,Value,Array].[h,cxx]

---

tree/dataframe/src/RLoopManager.cxx

When the input files are paths to FUSE-mounted EOS files, during the event loop these paths will be redirected to the corresponding xroot EOS URL, in TFile::Open.
This was causing a bad interaction with the sample metadata and the subsequent usage in the event loop, e.g. through DefinePerSample. Specifically, we fill a map with the metadata at construction time, which includes the input file paths (without redirection). These will then be irretrievable during the event loop since the map key will not correspond to the redirected path. Fix this by also adding the redirected path during the filling of the map in ChangeSpec.
This PR fixes #17449 
@TomasDado FYI, this is an alternative to  https://github.com/root-project/root/pull/17537

Fix interaction between RSampleInfo and redirected EOS paths

---

io/io/src/TFile.cxx

Sometimes the `getxattr` call returns a valid string, but the string is incomplete. Namely, part of the full URL to the file on EOS is missing (usually the filename itself). Workaround by checking for the presence of the filename in the xurl string and in case it is not present, avoid calling TFile::Open.

[io] Silently fallback if full xroot path is not found on EOS

---

tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

The default mode - the same we did so far - is "for reading": this means that we not only load the on-disk information into the in-memory descriptor, but we also fixup the suppressed column ranges and the clusters with the info coming from the header extension (deferred columns); this is a required step for reading the rntuple correctly.
We then add two additional modes: "for writing" and "raw". "for writing" is the same as "for reading" except it doesn't do the header extension fixup - this mode will be used by the RNTupleMerger to properly write out an incrementally-merged RNTuple. "raw" simply deserializes the on-disk information without doing any fixup.

[ntuple] add different modes of descriptor loading to RNTupleSerializer

---

io/io/src/TFile.cxx

Micro-optimization in `TFile::MakeFree()`

[io] avoid unnecessary heap allocation in TFile::MakeFree

---

tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/src/RNTupleSerialize.cxx

The offset can be easily derived without the need to store it.

[ntuple] Remove RContext::fHeaderExtensionOffset

---

.github/workflows/root-docs-ci.yml

When building ROOT for the doc, `minimal=on` was set. this prevented to build `geom`.

[skip-ci] disable minimal=on

---

tutorials/hist/hist048_Graphics_candle_hist.C
tutorials/hist/hist049_Graphics_candle_plot.C
tutorials/hist/hist050_Graphics_candle_plot_options.C
tutorials/hist/hist051_Graphics_candle_plot_stack.C
tutorials/hist/hist052_Graphics_candle_plot_whiskers.C
tutorials/hist/hist053_Graphics_candle_scaled.C

Use tcanvas_js to display candle plot examples.
Remove sprintf

[skip-ci] use tcanvas_js

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/test/ntuple_basics.cxx

Mirroring the behavior for `RNTupleWriter::Fill`, with this PR, calling `RNTupleReader::LoadEntry` with an entry that does not belong to the model of that `RNTupleReader` now properly throws an exception.
Fixes #16841.

[ntuple] Detect mismatch between entry and model in `RNTupleReader::LoadEntry`

---

README/ReleaseNotes/v636/index.md
core/meta/inc/TEnum.h
core/meta/src/TDataMember.cxx
core/meta/src/TEnum.cxx
core/meta/src/TStreamerElement.cxx
io/io/inc/TStreamerInfo.h
io/io/src/TGenCollectionProxy.cxx
io/io/src/TStreamerInfo.cxx
tree/treeplayer/src/TTreeReaderArray.cxx
tree/treeplayer/src/TTreeReaderValue.cxx

This PR Is chained (includes all commit from) https://github.com/root-project/root/pull/16995.
The companion roottest PR is https://github.com/root-project/roottest/pull/1226
It also requires an increase in the TStreamerInfo class version number (to mark which files/StreamerInfo have weird data for non-default size enum and which files are correct).
This fixes https://github.com/root-project/root/issues/16312.  However files produced without this PR and with enum with a non default size will have data that is incorrectly saved but potential recoverable.   The way the data is written will dependent on the size of the enum at the time of writing.  Since this size is not recorded in the file, we can ***not*** have a general solution to read those corrupted files. However when that enum size …

Add support for enums with non-default size

---

hist/hist/inc/TH2.h
hist/hist/inc/TH3.h
hist/hist/test/test_TH1.cxx

Fixes https://github.com/root-project/root/issues/17552
Alternative to https://github.com/root-project/root/pull/17573

 [hist] fix regression in AddBinContentND and add test

---

hist/histpainter/src/THistPainter.cxx

If you fill a TH1 using only AddBinContent, the resulting nEntries=0, and call Draw(), it works. If you fill a TH2 using only AddBinContent, the resulting nEntries=0, and call Draw("COLZ"), it does not work. This commit tries to fix it so that it also works for the 2D case, for consistency.
Fixes https://github.com/root-project/root/issues/14153

[hist] paint TH2 even if nEntries==0, as already happens for TH1

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx

Resulted from an offline discussion with Jakob: the word "add" is a bit ambiguous because we already Add the extended columns/fields to the descriptor, but we also mark them as extended if we're extending the header.

[ntuple] rename RHeaderExtension::AddExtended* to MarkExtended*

---

bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx

```
526/1416 Test   #63: pyunittests-bindings-pyroot-pythonizations-pyroot-pyz-tf-pycallables ..........................***Failed   75.51 sec
test_callable (tf_pycallables.TF1.test_callable)
Test function provided as callable ... /usr/include/c++/15/bits/stl_bvector.h:1134: std::vector<bool, _Alloc>::reference std::vector<bool, _Alloc>::operator[](size_type) [with _Alloc = std::allocator<bool>; reference = std::vector<bool>::reference; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
*** Break *** abort
=========================================================== The lines below might hint at the cause of the crash. If you see question marks as part of the stack trace, try to recompile with debugging information enabled and export CLING_DEBUG=1 environment variable …
```

Fix out-of-bounds error in pyroot

---

tutorials/CMakeLists.txt

ntpl013_staged should take 15-25 seconds but fails (timeout) often in the CI on Windows,
so decrease its timeout to 2 minutes to prevent waiting hours to complete the tests

[cmake][win] Decrease timeout of ntpl013_staged

---

tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx

Preparation for moving read options out of experimental.

[ntuple] Fix-up read options

---

tree/ntuple/v7/inc/ROOT/RMiniFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx

Currently RMiniFile doesn't honor the compression settings set in the RNTupleWriteOptions when writing out the StreamerInfo, but instead it always ZLIB-compresses it.
With this change, it will use the same compression as it was specified in the options (or 505 if unspecified).
This makes the behavior more consistent with the TFile, where the TFile compression determines also the StreamerInfo's compression (whereas now RNTuple may export a compressed StreamerInfo even if the TFile's compression is 0).

[ntuple] RMiniFile: write StreamerInfo with the correct compression

---

math/mathcore/src/PdfFuncMathCore.cxx

Improve the numerical behavior and performance of
`ROOT::Math::landau_pdf` by rearranging the computation with power rules, avoiding some divisions and `std::sqrt` calls.
This fixes #17564, because the vectorized Landau implementation in RooFit alrady applied this improvement (implemented by Manos):
https://github.com/root-project/root/blob/master/roofit/batchcompute/src/ComputeFunctions.cxx#L521

[math] Improve `ROOT::Math::landau_pdf` by using power rules

---

io/io/src/TFile.cxx
io/io/test/TFileTests.cxx

Fixes https://github.com/root-project/root/issues/16189

[io] Apply TFile::k630forwardCompatibility when creating new file if set in rootrc

---

math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/LinkDef_GenVector.h
math/genvector/inc/Math/Vector4D.h
math/genvector/inc/Math/Vector4Dfwd.h

This finishes their removal started by commit 7a2f77140ae715dde292d842c680525d4f64ce47 in 2005

math: Remove commented out code for PtEtaPhiMSystem EEtaPhiMSystem.

---

roofit/roofitcore/src/RooMinimizer.cxx
roofit/roofitcore/test/TestStatistics/testInterface.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodJob.cxx
roofit/roofitcore/test/TestStatistics/testLikelihoodSerial.cxx
roofit/roostats/inc/RooStats/ProfileLikelihoodTestStat.h
roofit/roostats/inc/RooStats/RatioOfProfiledLikelihoodsTestStat.h
roofit/roostats/inc/RooStats/RooStatsUtils.h
roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h
roofit/roostats/inc/RooStats/ToyMCSampler.h
roofit/roostats/src/AsymptoticCalculator.cxx
roofit/roostats/src/LikelihoodInterval.cxx
roofit/roostats/src/ProfileLikelihoodCalculator.cxx
roofit/roostats/src/ProfileLikelihoodTestStat.cxx
roofit/roostats/src/RooStatsUtils.cxx
roofit/roostats/src/ToyMCSampler.cxx
tutorials/roofit/roostats/HybridInstructional.py
tutorials/roofit/roostats/HybridStandardForm.py
tutorials/roofit/roostats/StandardHypoTestInvDemo.C
tutorials/roofit/roostats/StandardHypoTestInvDemo.py

Turn the relevant variables for the likelihood offsetting mode from type
`bool` to `std::string`. Like this, any offsetting mode can be set
("none", "initial", and "bin").
Closes https://github.com/root-project/root/issues/15959.
Note that the issue also requested to support setting `Offset("bin")` at the level of the RooMinimizer, but this is not intended: this offsetting strategy is only changing the mathematical definition of the likelihood function, which the minimizer interface should not change. For the existing offsetting by subtracting the initial evaluation value, this was as different story, because to subtract the initial evaluation value one doesn't need to look inside the function.

[RF] Make Offset("bin") usable for CLs method

---

core/base/inc/TSystem.h
core/base/src/TSystem.cxx
core/unix/inc/TUnixSystem.h
core/unix/src/TUnixSystem.cxx
core/winnt/inc/TWinNTSystem.h
core/winnt/src/TWinNTSystem.cxx
net/net/CMakeLists.txt
net/net/inc/TServerSocket.h
net/net/inc/TSocket.h
net/net/src/TServerSocket.cxx
net/net/test/CMakeLists.txt
net/net/test/nettests.cxx

in a backwards compatible way. An enumerator, ESocketBindOption, is introduced to specify the option.

[net] Allow users to specify binding options when opening sockets

---

tree/ntuple/v7/src/RNTupleSerialize.cxx

This assert was introduced in da99545d831, but it is wrong (it may be the case that we call MapSchema when a header extension is already there). This code path will be exercised (and tested) in an upcoming PR about incremental merging (https://github.com/root-project/root/pull/17563/commits/9469b920c31be9fb03500b633946d83a1ea1c657)

[ntuple] remove wrong assert in RNTupleSerialize.cxx

---

requirements.txt

The relevant Python packages are now available on Python 3.13 as well, so we should include them also in the requirements.txt for Python 3.13.
Like this, we increase test coverage in the CI, as the requirements.txt file is used to build the docker images.
It can be tested locally with Python 3.13 that the updated requirements.txt resolves.

Remove Python 3.13 constraints from requirements.txt

---

tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx

This PR adds a check to `RNTupleDS::GetTypeName` for the existence of the provided column name, and throws a `std::runtime_error` if this is not the case.
To simplify, we could also use `RNTupleDS::HasColumn`, but that would mean calling `std::find` on `fColumnNames` twice, so I opted for this slightly duplicated approach instead.

[DF] Check if column exists on `GetTypeName`

---

tmva/tmva/src/MethodDNN.cxx

Add missing `#include <chrono>`
Fix many compilation errors like the following on Windows:
```
tmva\tmva\src\MethodDNN.cxx(1186,44): error C2039: 'system_clock': is not a member of 'std::chrono' 
tmva\tmva\src\MethodDNN.cxx(1186,44): error C2065: 'system_clock': undeclared identifier 
tmva\tmva\src\MethodDNN.cxx(1187,42): error C2039: 'now': is not a member of 'std::chrono' 
tmva\tmva\src\MethodDNN.cxx(1187,42): error C3861: 'now': identifier not found
```

[tmva] Fix compilation errors on Windows

---

hist/histpainter/src/TPaletteAxis.cxx

View automatically deleted when `gPad->SetView(nullptr)` called 
Therefore there is no need to to call destructor

Properly delete 3dview in TPaletteAxis::UnZoom

---

math/foam/src/TFoam.cxx
tree/dataframe/src/RDataFrame.cxx
tutorials/analysis/dataframe/index.md
tutorials/hist/index.md

fix doxygen warnings,: anchors were defined several times
foam_kanwa.C moved

[skip-ci] fix doxygen warnings

---

io/io/inc/TFile.h
io/io/src/TFile.cxx

refactors `TFile::Map` into 2 methods: `Map` and `WalkTKeys`. The latter contains the logic of traversing the TKeys in the file and returns an array with information about keys, gaps and errors. `Map` now simply calls that method and prints out the relevant information, in the same format as before.
The main advantage of splitting `WalkTKeys` is that it can be used by other places (like unit tests or client code) that are interested in the internal TKey structure.

[io] Extract tkey walk logic from TFile::Map()

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py

Fixes https://github.com/root-project/root/issues/17634

[skip-ci] Fix broken python tutorial links

---

net/net/inc/TMessage.h
net/net/src/TMessage.cxx

Rebased version of https://github.com/root-project/root/pull/17601
Fixes https://github.com/root-project/root/issues/14557 reported by @cpulvermacher

TMessage honour kIsOwner bit when compression is used

---

tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/ntuple_minifile.cxx

depends on https://github.com/root-project/root/pull/17575.
Fixes the case in RMiniFileWriter where a RBlob is allocated inside a free slot that is bigger than the blob itself. In that case allocating the TKey also needs to update the header of the remaining free slot after the space for the blob was reserved (see [TKey::Create](https://github.com/root-project/root/blob/master/io/io/src/TKey.cxx#L510-L516)). This is normally done by `TKey::WriteFile`, but since RMiniFile bypasses that it needs to write the updated nbytes to disk manually.

[ntuple] RMiniFile: properly write the free slot's nbytes

---

tutorials/roofit/roostats/rs401d_FeldmanCousins.C

avoid the error:
```
/github/home/ROOT-CI/src/tutorials/roofit/roostats/rs401d_FeldmanCousins.C:139:49: error: use of undeclared identifier 'False'
RooMsgService::instance().setStreamStatus(0, False);
^
```

[skip-ci] True and False are not defined

---

hist/hist/src/TF1.cxx
hist/hist/src/TF2.cxx
hist/hist/src/TGraph2D.cxx
hist/hist/src/THStack.cxx

In classes like `THStack`, `TGraph2D`, `TF1`, `TF2` created histogram may have Sumw2 array - 
if  `TH1::SetDefaultSumw2();` was activated before. Always remove such array to save memory and 
to avoid paint artifacts as in #17470

Always remove Sumw2 in object painting

---

tutorials/roofit/index.md

`tutorial_histfactory` was defined twice

[skip-ci] tutorial_histfactory was defined twice

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

Based on #17596, derived from #17563.
Introduces a new method in RNTupleDescriptor/Builder to allow cloning only the "schema" part of a descriptor, then uses this new method to fix `RPagePersistentSink::InitFromDescriptor` in the general case where the given descriptor already contains a header extension.
The RNTupleSerializer also needs a couple of changes to cope with this case, because we don't want to move the fields and columns from the header extension to the regular header (which would hinder the Merger's capability of doing incremental merging).

[ntuple] Fix serialization when a header extension is already present

---

tutorials/CMakeLists.txt
tutorials/io/tree/imt_parTreeProcessing.C

[tut] Avoid races caused by Davix 0.8.8

---

tutorials/CMakeLists.txt
tutorials/multicore/imt101_parTreeProcessing.C

BP of https://github.com/root-project/root/pull/17640 , adapted to the old tutorials structure

[BP][634][tut] Avoid races caused by Davix 0.8.8

---

tutorials/CMakeLists.txt
tutorials/multicore/imt101_parTreeProcessing.C

BP of https://github.com/root-project/root/pull/17640 , adapted to the old tutorials structure

[BP][626][tut] Avoid races caused by Davix 0.8.8

---

tutorials/CMakeLists.txt
tutorials/multicore/imt101_parTreeProcessing.C

BP of https://github.com/root-project/root/pull/17640 , adapted to the old tutorials structure

[BP][630][tut] Avoid races caused by Davix 0.8.8

---

tutorials/CMakeLists.txt
tutorials/multicore/imt101_parTreeProcessing.C

BP of https://github.com/root-project/root/pull/17640 , adapted to the old tutorials structure

[BP][628][tut] Avoid races caused by Davix 0.8.8

---

tutorials/roofit/roostats/ModelInspector.C

Correct an error where `kFALSE` was changed to `false`. This instance was missed and remains as `False`, but it should be `false`. This issue doesn't appear in the Doxygen log because the macro isn't executed because no image is generated for it since there's no `\macro_image` directive; only the code is displayed. The error was discovered using a `grep` search.

[skip-ci] replace False by false

---

tutorials/analysis/dataframe/df105_WBosonAnalysis.py
tutorials/analysis/dataframe/df107_SingleTopAnalysis.py
tutorials/experimental/rcanvas/df105.py

The conversion of Python tuples to TColorNumber doesn't work for older Python versions. Therefore, `TColor::GetColor()` is brought back to the tutorials, following up on 8eefabd.
The underlying problem is a wrong overload resolution because of implicit conversion from double to integer, see also the error that one gets for example with Python 3.9:
```txt
/Users/couet/git/couet-root/tutorials/analysis/dataframe/df105_WBosonAnalysis.py:176: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
h.SetFillColor(color)
```
Comments are added to clarify that this would not be needed with Python 3.11 onwards, reminding us that we have the option to revert this commit once the …

[tutorials] Don't rely on conversion of Python tuple to TColorNumber

---

io/io/src/TBufferJSON.cxx
io/io/src/TStreamerInfo.cxx

The roottest companion PR is https://github.com/root-project/roottest/pull/1255

io: Allow implicit conversion from  vector<pair<A<B> > to map<A,B>

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tree/ntuple/v7/test/ntuple_processor_chain.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx
tutorials/io/ntuple/ntpl012_processor_chain.C

This PR introduces the possibility to create `RNTupleChainProcessor`s from other processor objects. In turn, this makes it possible to, for example, create a chain of joined ntuples.
This PR is part of a bigger set of (foreseen) changes, collected and tracked in https://github.com/root-project/root/issues/17132.

[ntuple] Make `RNTupleChainProcessor` composable

---

tree/dataframe/src/RDataFrame.cxx

Should fix the doc from looking like this
I did not test this, though (and from what I heard about building the documentation I will also not do it...)

RDataFrame fix broken link in documentation

---

roofit/histfactory/src/ParamHistFunc.cxx

When connecting preprocessing functions to nuisance parameters via `Measurement::AddPreprocessFunction`, the nuisance parameter is replaced by a RooAbsReal that is not a RooRealVar, and the implementation of `ParamHistFunc::createParamSet` should be able to deal with that.
So far, `createParamSet` assumed that any pre-existing argument in the workspace with the nuisance parameter name is of type RooRealVar, which is not valid in that case. Therefore, using preprocessing functions in place of these parameters resulted in a segfault.
To fix this, the code is generalized to any RooAbsArg type.
Closes #12225.

[RF][HF] Re-use any type of RooAbsArgs in ParamHistFunc::createParamSet

---

geom/geom/src/TGeoManager.cxx

In this case do not use stored "GeomPainter.Name" value, but directly check configured web display for pad
Should behaves like TCanvas when web mode checked if batch flag enabled.

[geompainter] correctly handle drawing on the pad

---

CMakeLists.txt

This was factored out of #17607.
In contrast to the initial proposal in #17607, I managed to keep the artifact copy at build time. This should alleviate all problems where an out-of-date file might surprise developers.
I used `cmake -E copy_directory` instead of going file-by-file, which again significantly reduces build targets and makes the initial copy much faster. We don't gain on the second invocation of make, and when tutorials are touched, one pays a 5s penalty, but I think the 15s saved on first invocation and the reduced number of targets make this worthwhile.
| `make -j6 move_artifacts` | Old | New |
|--------|--------|--------|
| 1st invocation | 25.5 | 10.4 |
| 2nd invocation | 2.5 | 2.6 |
| Touch a RooFit tutorial | 2.5 | 7.8 | 
- Although all tutorials that run as part of …

Speed up the copy of artifacts

---

core/foundation/src/RConversionRuleParser.cxx
core/meta/inc/TClassRef.h
core/meta/src/TClassRef.cxx
io/io/src/TStreamerInfo.cxx

This fixes the issue seen in https://github.com/cms-sw/cmsdist/pull/9643#issuecomment-2632063998
and is the companion PR of https://github.com/root-project/roottest/pull/1256

io: in UpdateFromRule properly handle case of std::string and alias without dictionary

---

tree/dataframe/inc/ROOT/RDF/RDisplay.hxx

When compiling ROOT `master`, I saw the following kind of warnings [1].
While I don't understand exactly why these happen, then can be prevented by directly putting the return values of the function on the stack.
I guess this is worth doing anyway, to avoid manual memory allocation.
Like this, we also don't need to carry around the `fIsCollection` data member just for the sake of heap memory reuse.
[1] :
```txt
In file included from /nix/store/zs2gq6fkglrd28g1nxlb8waqq37cdc2z-gcc-14-20241116/include/c++/14-20241116/string:51,
from /home/rembserj/code/root/core/meta/inc/TSchemaHelper.h:17,
from /home/rembserj/code/root/core/meta/inc/TGenericClassInfo.h:21,
from /home/rembserj/code/root/core/base/inc/Rtypes.h:198,
from /home/rembserj/code/root/core/base/inc/TObject.h:17,
from …
```

[DF] Avoid unnecessary `std::vector` in RDisplay.hxx to fix warnings

---

main/src/hadd-argparse.py
main/src/hadd.cxx

depends on #17609. 
It's a new take on #4615, which adds two flags to hadd:
* `-L <FILE>`: specify a file that contains object or directory names, one per line, to be used as a filter. The filter type is specified by the second flag:
* `-Ltype <OnlyListed|SkipListed>`: determines whether the list of object names contained in FILE should be used as a whitelist or a blacklist to know which objects to merge. This internally uses `TFileMerger::AddObjectNames`, so it has the same restrictions, notably you cannot specify a subobject name such as `dir/object`. If this is a desired feature, it should be added to TFileMerger directly, in a separate PR.
Companion roottest PR: https://github.com/root-project/roottest/pull/1257

[hadd] add option to filter objects/directories to merge

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx

Calling `GetNEntries` on the page source each time is expensive, so instead we store this as a member of the processor.
Mostly relevant for the `RNTupleSingleProcesor`, because the chain processor already is composed of other processors, and the join processor will do the same soon.

[ntuple] Store number of entries in the `RNTupleProcessor`

---

tree/ntuple/v7/src/RNTupleProcessor.cxx

The current implementation loads the number of entries in the *next* processor in the loop, if this is not known yet, which might not be necessary. This change instead only loads the number of entries in the loop's current processor.
It also removes the requirement to load the number of entries in the first processor on construction (even though this will get loaded in the first iteration of the `LoadEntry` loop anyways, so in the end it won't make much difference).

[ntuple] Remove superfluous `GetNEntries` call in `RNTupleChainProcessor::LoadEntry`
