root-project/root

- tmva/pymva/src/PyMethodBase.cxx
- tmva/tmva/inc/TMVA/Factory.h
- tmva/tmva/inc/TMVA/ROCCurve.h
- tmva/tmva/src/Factory.cxx
- tmva/tmva/src/ROCCurve.cxx
Hi Guys 
This pull request have the new ROC plot in Factory to show the results in notebooks.
Best Regards,
Omar.
> TMVA: added ROC plots in factory

- cmake/modules/RootConfiguration.cmake
- graf3d/gl/Module.mk
> A few changes lost in conflict resolution

- cint/cint/Module.mk
- cmake/modules/SetUpLinux.cmake
- config/Makefile.linuxx8664gcc
See https://sft.its.cern.ch/jira/browse/ROOT-8180 
This pull request implements the proposed patches there.
> Fix GCC 6 compilation (tested on ArchLinux)

- graf2d/gpad/inc/TRatioPlot.h
- graf2d/gpad/src/TRatioPlot.cxx
- tutorials/hist/ratioplot1.C
- tutorials/hist/ratioplot2.C
- tutorials/hist/ratioplot3.C
- tutorials/hist/ratioplot4.C
- tutorials/hist/ratioplot5.C
- tutorials/hist/ratioplot6.C
@couet 
/cc @karies 
* Rearrange main doc block
* Hiding of axis labels / titles / ticks is different now ( "A" instead of setting sizes to 0 on h1), fit drawing is handled explicitly by the class
* copy constructor builds TObject explicit
* a couple of methods were inlined
> Implement fixes and changes suggested

- documentation/doxygen/converttonotebook.py
- tutorials/hist/ratioplot1.C
- tutorials/hist/ratioplot2.C
- tutorials/hist/ratioplot3.C
- tutorials/hist/ratioplot4.C
- tutorials/hist/ratioplot5.C
- tutorials/hist/ratioplot6.C
Tests and documentation for the converttonotebook script are improved. Also, the new ratioplot tutorials were converted to notebooks.
> Converttonotebook tests, ratioplot notebooks

- graf2d/gpad/src/TRatioPlot.cxx
> Attempt to fix Coverity problems

- tree/treeplayer/src/TDataFrame.cxx
- add Histo{2D,3D}, Profile{1D,2D} to docs
- Extra actions are now called Queries
- temporary branch -> temporary column
- Histo -> Histo1D
> [TDF] Update user guide

- tutorials/mlp/mlpHiggs.C
- tutorials/quadp/portfolio.C
These files are available in the source tree. By trying these local copies before trying the remote copies it is possible to run the tests without network access.
> Try local file before trying remote file

- core/base/src/TQObject.cxx
- tree/tree/src/TLeaf.cxx
- tree/treeviewer/src/TTreeViewer.cxx
Per conversion with Philippe, this pull request includes cherry-picked fixes for #ROOT-8714 and #ROOT-8222 from the master branch, which applied clean.
> V6 08 00 patches

- .travis.yml
Sorry @vgvassilev, I forgot to let `echo` escape the tabs :)
> [BOT] Fix clang-format-bot message

- core/cont/inc/ROOT/TSeq.hxx
> Make TSeq iterator standard-compliant (II)

- math/mathmore/inc/Math/LinkDef_Func.h
- math/mathmore/inc/Math/SpecFuncMathMore.h
- math/mathmore/src/SpecFuncMathMore.cxx
- math/mathmore/test/testSpecFunc.cxx
Added generalized expint from GSL.
> Generalized expint from GSL

- core/cont/CMakeLists.txt
- core/cont/test/TSeqTests.cxx
PR coming in roottest to remove it from there
> Move the TSeq iterators test to google test

- geom/geom/src/TGeoPgon.cxx
Fixes issue reported in the forum.
> Fixed TGeoPGon::GetPhiCrossList for point on the Z axis

- tmva/tmva/inc/TMVA/DNN/Minimizers.h
- tmva/tmva/inc/TMVA/HyperParameterOptimisation.h
- tmva/tmva/src/HyperParameterOptimisation.cxx
This has a couple more fixes from the study of a previous bug, some typo fixes, etc. The commit messages have more details.
> Small TMVA improvements

- math/smatrix/test/testSMatrix.cxx
Test file: `math/smatrix/test/testSMatrix.cxx`
Failing test on CDash:
http://cdash.cern.ch/testDetails.php?test=24128678&build=345047
> Fix for failing test (too strict tolerances for floating point values)

- tmva/tmva/inc/TMVA/ROCCurve.h
- tmva/tmva/src/Factory.cxx
- tmva/tmva/src/ROCCurve.cxx
- ROC curve and integral now respects event weights
- Includes changes introduced by https://github.com/root-project/root/pull/454
- Fixes bug in GetROCIntegral were you would get a different result if called two times in a row
- Fixes line interpolation in plotting
- Some display fixes like labelling of axes
> Roc curve weights + update

- tree/treeplayer/inc/ROOT/TDataFrameInterface.hxx
This PR concludes ROOT-8766. Tests for this functionality are added by a separate PR to roottest.
> [TDF] Add branch type inference for `Fill` and `Snapshot` actions

- core/dictgen/src/rootcling_impl.cxx
The previous assert was not only ugly but also did the inverse
check (failed when it could open the file correctly).
> WriteAST now correctly checks for errors.

- core/dictgen/src/rootcling_impl.cxx
Reverts the unintentional change in #539
> revert making WriteAST non-static

- tree/treeplayer/inc/ROOT/TDataFrame.hxx
- tree/treeplayer/inc/ROOT/TDataFrameInterface.hxx
- tree/treeplayer/src/TDataFrame.cxx
- tree/treeplayer/src/TDataFrameInterface.cxx
* never jit `TActionResultProxies`, so that their lifetime is always as expected
* more move semantics :)
* minor fixes
> [TDF] Misc fixes

- README/ReleaseNotes/v610/index.md
> Add TBufferMerger to release notes

- graf3d/eve/inc/TEveArrow.h
- graf3d/eve/inc/TEveGedEditor.h
- graf3d/eve/src/TEveArrow.cxx
- graf3d/eve/src/TEveArrowEditor.cxx
- graf3d/eve/src/TEveArrowGL.cxx
- graf3d/eve/src/TEveGedEditor.cxx
- graf3d/eve/src/TEveVector.cxx
- gui/ged/inc/TGedEditor.h
- gui/ged/src/TGedEditor.cxx
Also sanitize setting of TEveArrow parameters and propagation of bounding-box updates to GL viewer.
> Fix updating of GED editors from EVE GL Viewer

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
The default setting has been determined to be near the optimal
value from tests runs on a 4 core machine (up to 8 threads), by
creating up to 1GB of data with lightweight calculations both to
tmpfs, and to ext4 filesystem on an SSD drive.
> [TDF] Add file cache size option setting to snapshot action

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
Please take a look. Although the tests pass, this is not supposed to be merged yet, as I have yet to understand why it's so slow when we pass a positive auto-flush value to snapshot the tree.
> Change Snapshot option from file cache to TTree auto-flush parameter

- math/mathmore/test/CMakeLists.txt
- math/mathmore/test/StatFunction.cxx
- math/mathmore/test/StatFunction.h
- math/mathmore/test/testStress.cxx
This is a general refactoring of the class test/stressMathMore.cxx.
It involves using Google test for assertions, test fixtures, and general
refactoring of the code.
Ping @lmoneta
> Refactoring of stressMathMore

- tmva/tmva/src/MethodDNN.cxx
- tutorials/tmva/TMVAClassification.C
- tutorials/tmva/TMVAClassificationApplication.C
- tutorials/tmva/TMVAMulticlass.C
- tutorials/tmva/TMVAMulticlassApplication.C
- tutorials/tmva/TMVARegression.C
- tutorials/tmva/TMVARegressionApplication.C
Removes the DNN option with Architecture=Standard from ordinary
and multiclass settings.
Smaller fixups for output and homogenisation of DNN options.
> Fix DNN in tutorial examples

- interpreter/cling/.travis.yml
- interpreter/cling/lib/Interpreter/ClangInternalState.cpp
- interpreter/cling/lib/Interpreter/DeclUnloader.cpp
- interpreter/cling/lib/Interpreter/TransactionUnloader.cpp
- interpreter/cling/test/lit.cfg
> Cling fixes after the LLVM upgrade

- math/mathcore/test/fit/testLogLExecPolicy.cxx
Commented this part on request until we figure out why is it failing in
specific machines.
> Commented multithreaded execution policy test.

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFInterface.cxx
The corresponding regression test is submitted in a PR to roottest.
> [TDF] Fix jitting in the case of no data source

- interpreter/cling/lib/Interpreter/ClingPragmas.cpp
- interpreter/cling/test/Pragmas/P0.h
- interpreter/cling/test/Pragmas/P0.h P1.h P2.h
- interpreter/cling/test/Pragmas/P1.h
- interpreter/cling/test/Pragmas/P2.h
- interpreter/cling/test/Pragmas/multiArgument.C
- interpreter/cling/test/Pragmas/opt.C
https://github.com/root-project/cling/pull/144
> cling PR 144

- interpreter/cling/lib/MetaProcessor/InputValidator.cpp
- interpreter/cling/lib/MetaProcessor/MetaLexer.cpp
- interpreter/cling/lib/MetaProcessor/MetaLexer.h
- interpreter/cling/test/Prompt/Continuation.C
https://github.com/root-project/cling/pull/143
> cling PR 143

- interpreter/cling/lib/Interpreter/BackendPasses.cpp
- interpreter/cling/lib/Interpreter/ValuePrinter.cpp
Can we enable diagnostics for value printing, to be more helpful in case of errors?
> Value print diags [WIP]

- interpreter/cling/lib/Interpreter/CIFactory.cpp
https://github.com/root-project/cling/pull/152
> cling PR 152

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDFNodes.cxx
Various clean-ups to the even loop logic of TDF
> [TDF] Refactor TDF::TLoopManager::Run

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
The logic of `SnapshotImpl` has been refactored to move the single-thread initialization and execution inside the `SnapshotHelper` class, and the multi-thread in `SnapshotHelperMT`.
This code simplification also puts `Snapshot` in line with other actions, moving most of the logic inside `TDFActionHelpers.hxx`.
> [TDF] Refactor SnapshotImpl

- interpreter/cling/lib/Interpreter/IncrementalParser.cpp
- interpreter/cling/lib/Interpreter/IncrementalParser.h
https://github.com/root-project/cling/pull/145
> cling Pr 145

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDataFrame.cxx
- tutorials/dataframe/tdf001_introduction.C
- tutorials/dataframe/tdf002_dataModel.C
- tutorials/dataframe/tdf003_profiles.C
- tutorials/dataframe/tdf004_cutFlowReport.C
- tutorials/dataframe/tdf006_ranges.C
- tutorials/dataframe/tdf007_snapshot.C
- tutorials/dataframe/tdf101_h1Analysis.C
The PR changes TDF's source code as well as the tutorials. A related PR that changes the tests is open in roottest.
I also added an extra commit with a minor fix to TDF's user guide.
> [TDF] Misc fixes -- was "Use TH*D instead of TH*F in Histo actions"

- core/textinput/src/textinput/StreamReaderWin.cpp
- interpreter/cling/lib/Interpreter/CIFactory.cpp
- interpreter/cling/lib/UserInterface/UserInterface.cpp
- interpreter/cling/test/Driver/EOF.C
https://github.com/root-project/cling/pull/163
NOTE: commit "Windows: Fix infinite loop when piping to cling with < operator." must be separately applied to cling!
> cling PR 163

- core/textinput/src/textinput/History.h
- interpreter/cling/lib/UserInterface/UserInterface.cpp
https://github.com/root-project/cling/pull/158
NOTE: fix to textinput must be separately applied to cling!
> cling Pr 158

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDFNodes.cxx
The `max template recursion depth reached` error is due to the
implementation of std::tuple's move constructor in some STL
implementations (notably, gcc).
The logic has been modified to avoid copying large tuples:
- the number of slots is now fixed for each node at construction time
- all the logic that was implemented by the `CreateSlot` methods has
been moved to the corresponding nodes' constructors.
> [TDF] Fix compilation error when reading 66+ columns in the same node

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDFNodes.cxx
The `max template recursion depth reached` error is due to the
implementation of std::tuple's move constructor in some STL
implementations (notably, gcc).
The logic has been modified to avoid copying large tuples:
- the number of slots is now fixed for each node at construction time
- all the logic that was implemented by the `CreateSlot` methods has
been moved to the corresponding nodes' constructors.
Cherry-pick conflicts:
tree/treeplayer/inc/ROOT/TDFNodes.hxx
tree/treeplayer/src/TDFNodes.cxx
> Cherry pick `fix max template recursion depth reached` to 6.10-patches

- tree/tree/src/TTree.cxx
If IMT is disabled, TTree::Fill() is constructing and destructing the
imtHelper object at every call and never using it. By moving its
declaration into the #ifdef, we avoid this penalty. This commit also
avoids the penalty of checking for fIMTEnabled if IMT is disabled.
VTune performance analysis (comparison of two basic hotspots analyses):
Note the time difference in `TTree::Fill()`.
> Avoid useless construction/destruction of imtHelper in TTree::Fill()

- math/mathcore/inc/Math/ParamFunctor.h
Adding an include so Double_t is defined
> Fix for the modules build

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
Reduce(Op, 0) is nicer than Reduce(Op, "", 0).
> [TDF] Add convenience overload for Reduce.

- core/base/v7/inc/ROOT/TDrawable.hxx
- core/base/v7/src/TDrawable.cxx
- graf2d/gpad/inc/LinkDef.h
- graf2d/gpad/v7/inc/ROOT/TDisplayItem.hxx
- graf2d/gpad/v7/inc/ROOT/TMenuItem.hxx
- graf2d/gpad/v7/inc/ROOT/TObjectDrawable.hxx
- graf2d/gpad/v7/inc/ROOT/TVirtualCanvasPainter.hxx
- graf2d/gpad/v7/src/TDisplayItem.cxx
- graf2d/gpad/v7/src/TObjectDrawable.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- hist/hist/v7/inc/ROOT/THistDrawable.hxx
There is special MenuItem class which describes menu item properties.
I put it into graph2d/gpad, but one can move it into canvaspainter
> webgui: Introduce Menu Handling to the ROOT7 GUI

- tmva/tmva/CMakeLists.txt
- tmva/tmva/inc/TMVA/Factory.h
- tmva/tmva/src/Factory.cxx
- tmva/tmva/src/ResultsMulticlass.cxx
- tmva/tmva/test/ROC/CMakeLists.txt
- tmva/tmva/test/ROC/testRocWeights.cxx
- tmva/tmvagui/inc/TMVA/efficienciesMulticlass.h
- tmva/tmvagui/src/TMVAMultiClassGui.cxx
- tmva/tmvagui/src/efficienciesMulticlass.cxx
Updated EvaluateAllMethods to output confusion matrix and 1vsRest data for both test data and training data for easier overtraining check.
The TMVAMultiClassGui now supports generating 1v1 roc curves.
Fixes bug where generated multiclass roc curves were not save to disk when created.
Adds correctness tests for the ROCCurve class.
> TMVA Multiclass gui updates

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
Fix ROOT-8918 in master. See issue for more details.
> [TDF] Fix bug in parallel Snapshot

- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.hierarchy.js
- etc/http/scripts/JSRootPainter.js
- gui/canvaspainter/v7/qt5/rootqt5.cpp
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
Like with chromium, perform drawing without creation of real window.
> webgui: enablle batch mode for qt5-based canvas painter

- etc/http/changes.md
- etc/http/openui5/Component.js
- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/controller/Panel.controller.js
- etc/http/openui5/view/Canvas.view.xml
- etc/http/openui5/view/Panel.view.xml
- etc/http/scripts/JSRoot3DPainter.js
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootGeoBase.js
- etc/http/scripts/JSRootGeoPainter.js
- etc/http/scripts/JSRootIOEvolution.js
- etc/http/scripts/JSRootPainter.hierarchy.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.jquery.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.openui5.js
- etc/http/scripts/JSRootTree.js
- etc/http/scripts/ThreeCSG.js
- gui/canvaspainter/v7/cef/cef_main.cxx
- gui/canvaspainter/v7/cef/simple_app.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
Introduce OpenUI5 as GUI library for Canvas
Also solves several minor issues
> Openui5 canvas

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
- tree/treeplayer/src/TDFNodes.cxx
- tree/treeplayer/src/TDataFrame.cxx
- tree/treeplayer/src/TTreeProcessorMT.cxx
This PR includes the commits of
* PR #833 
* a fix (dependent on #833) for task-unsafety in TDataFrame's TColumnValue
* PR #828 
* a patch for task-unsafety in TDataFrame's thread-slot distribution by @dpiparo (commit 2787af2)
If we want to push these commits little by little, PR #833 and PR #828 should be merged first, then I can open a third PR with the second (and fourth?) fix.
> [TDF+IMT] Fix nested parallelism

- interpreter/llvm/src/tools/clang/lib/Serialization/ASTWriter.cpp
This fixes the issue visible by adding Vc to the PCH.
Thanks to Raphael for spending his time with me debugging this!
> Fix terrible bug where the literal data is written as token begin to EOF.

- main/src/hadd.cxx
This PR is a part of LZ4 testing
> Adding support of LZ4 agorithm in hadd

- etc/http/changes.md
- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/controller/Ged.controller.js
- etc/http/openui5/controller/Panel.controller.js
- etc/http/openui5/view/Canvas.view.xml
- etc/http/openui5/view/Ged.view.xml
- etc/http/openui5/view/TAttFill.fragment.xml
- etc/http/openui5/view/TAttLine.fragment.xml
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootMath.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.openui5.js
- graf2d/gpad/v7/src/TCanvas.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
Very preliminary prototype for graphical editor elements
Now only TAttLine and TAttFill are handled (again, very primitive) 
Idea to test main functionality, see relationship between components.
Also testing of OpenUI5 components.
Layout and concrete implementation should be improved a lot
I set @Axel-Naumann as reviewers while @bellenot is in vacations.
> webgui: GED prototyping for Canvas

- math/mathcore/inc/Fit/FitUtil.h
- math/mathcore/src/FitUtil.cxx
If IMT is disabled, force the execution policy to be `ROOT::Fit::ExecutionPolicy::kSerial`, warning the user that a change in the execution policy has been made.
This should fix the errors in the tests built without IMT.
When the support for `kMultitProcess` is finished, maybe we should change this and force the execution policy to be `kMultitProcess`.
> Fix execution policy error when IMT is OFF

- hist/hist/src/TGraphAsymmErrors.cxx
See https://sft.its.cern.ch/jira/browse/ROOT-8969
> Fix y-error bars for TGraphAsymmErrors(TH1)

- cmake/modules/FindPythia6.cmake
- tutorials/CMakeLists.txt
- tutorials/pythia/pythiaExample.C
The tutorials required minor changes to make them run successfully.
> Added the pythia[6|8] tutorials as tests

- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/controller/FitPanel.controller.js
- etc/http/openui5/controller/Ged.controller.js
- etc/http/openui5/controller/Inspector.controller.js
- etc/http/openui5/controller/Panel.controller.js
- etc/http/openui5/view/Canvas.view.xml
- etc/http/openui5/view/FitPanel.view.xml
- etc/http/openui5/view/Inspector.fragment.xml
- etc/http/openui5/view/Inspector.view.xml
- etc/http/openui5/view/TAttMarker.fragment.xml
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.hierarchy.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.openui5.js
- graf2d/gpad/v7/src/TMenuItem.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- net/http/src/THttpServer.cxx
New components in GED editor
Show inspector in openui5 dialog
Special dialog for menu commands arguments
Dummy FitPanel 
Many bugfixes and improvements in JSROOT itself
> webgui: more functionality in openui5 canvas

- core/lz4/Module.mk
@bbockelm @pcanal Fixes for ROOT classic build
> Fixing includes for classic build LZ4 after adding new checksum feature

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFInterface.cxx
- tree/treeplayer/src/TDataFrame.cxx
Prefer string_view in function signatures.
Avoid instantiating strings whenever possible.
> [TDF] More string_views, less strings.

- hist/hist/inc/LinkDef.h
- hist/hist/inc/TF1.h
- hist/hist/inc/TF1AbsComposition.h
- hist/hist/inc/TF1Convolution.h
- hist/hist/inc/TF1NormSum.h
- hist/hist/src/TF1.cxx
- hist/hist/src/TF1Convolution.cxx
- hist/hist/src/TF1NormSum.cxx
- hist/hist/test/test_tf1.cxx
This PR extends the functionality of `TF1` functions based on `NSUM` or `CONV` (namely the classes `TF1NormSum` and `TF1Convolution` respectively). We are now able to:
* Set parameters and ranges directly from the `TF1`
* Copy these functions
* Stream these functions (for cloning and file I/O)
> Nsum range

- tmva/tmvagui/src/efficienciesMulticlass.cxx
Fixes 1vs1 roc curve drawing and minor refactoring.
> [TMVA] Small improvements to TMVA Multiclass GUI

- graf3d/g3d/src/TMaterial.cxx
- graf3d/g3d/src/TPolyLine3D.cxx
Let normally store these classes in JSON and XML.
Required to run some ROOT macros (like graphs/annotations.C) in webcanvas and JSROOT
> Equip custom streamer for TPolyLine3D and TMaterial

- core/base/inc/Rtypes.h
- core/base/src/TBuffer.cxx
- core/cont/inc/TCollection.h
- core/cont/src/TCollection.cxx
- core/cont/test/CMakeLists.txt
- core/cont/test/testTypedIteration.cxx
- core/meta/src/TStatusBitsChecker.cxx
- io/io/src/TFile.cxx
Introduce TRangeCast and TTypedIter
```c++
TTypedIter<TBaseClass> next(cl->GetListOfBases());
while(auto bcl = next()) {
... use bcl as a TBaseClass*
}
for(auto bcl : TRangeCast<TBaseClass>( *cl->GetListOfBases() )) {
... use bcl as a TBaseClass*
}
```
> TRangeCast

- interpreter/cling/lib/Utils/SourceNormalization.cpp
> Also recognize templates as identifier.

- interpreter/cling/lib/Interpreter/ASTTransformer.h
- interpreter/cling/lib/Interpreter/Interpreter.cpp
- interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFInterface.cxx
Backport of [PR 972](https://github.com/root-project/root/pull/972) to v6.10.
> [TDF+CLING] Avoid instrumenting jitted code when possible

- hist/hist/inc/Foption.h
- hist/hist/src/HFitImpl.cxx
- math/mathcore/test/fit/testBinnedFitExecPolicy.cxx
...so we don't need to write "MULTITHREAD" as fit option. Update the test.
> Let ImplicitMT influence on THN::Fit() execution policy

- README/ReleaseNotes/v612/index.md
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/inc/ROOT/TDataFrame.hxx
- tree/treeplayer/inc/ROOT/TDataSource.hxx
- tree/treeplayer/inc/ROOT/TRootDS.hxx
- tree/treeplayer/inc/ROOT/TTrivialDS.hxx
- tree/treeplayer/src/TDFInterface.cxx
- tree/treeplayer/src/TDFNodes.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/src/TDataFrame.cxx
- tree/treeplayer/src/TRootDS.cxx
- tree/treeplayer/src/TTrivialDS.cxx
- tree/treeplayer/test/CMakeLists.txt
- tree/treeplayer/test/dataframe/dataframe_utils.cxx
- tree/treeplayer/test/dataframe/datasource_root.cxx
- tree/treeplayer/test/dataframe/datasource_trivial.cxx
Test PR to check build issues and incompatibilities with current test suite.
> [TDF] Let TDataFrame use TDataSources to read data

- montecarlo/vmc/inc/TVirtualMC.h
> Added new TVirtualMC functions TrackPosition|Momentum(Float_t& ...):

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFInterface.cxx
- tree/treeplayer/test/dataframe/datasource_root.cxx
- tree/treeplayer/test/dataframe/datasource_trivial.cxx
* fix interaction of data-source columns and user-defined columns  
* add tests
> [TDF] Datasource fixes

- interpreter/cling/lib/Interpreter/InterpreterCallbacks.cpp
With the module generation in rootcling Clang rlies on AST consumers
to do the module generation work for it. Right now this doesn't work
however with the interpreter, as we just overwrite the deserialization
listener that clang added which will cause strange errors during
the module generation (the most prompinent error is that the number
of recorded submodules will be incorrect, as this it the first thing
that Clang checks before writing a module and which is recorded by
an ASTDeserializationListener).
This patch just adds a multiplexer here that allows us to keep the
old listener while also adding the one we have.
> [cxxmodules] Don't overrite the DeserializationListener.

- cmake/modules/SearchInstalledSoftware.cmake
Fixing failed builds for aarch and fedora24/fedora25
> V6-10-patches fix order commits

- core/foundation/inc/ROOT/TypeTraits.hxx
- tree/treeplayer/src/TDFInterface.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_simple_tests.hxx
- tree/treeplayer/test/dataframe/dataframe_utils.cxx
Solves the reading-related part of issue [ROOT-8979](https://sft.its.cern.ch/jira/browse/ROOT-8979).
> [TDF] Fix reading of c-style arrays from jitted transformations and actions

- tree/treeplayer/src/TDataFrame.cxx
This reverts part of commit 5059f594.
> [TDF] Revert some doc-breaking clang-format fixes (NFC)

- tmva/tmvagui/src/mvasMulticlass.cxx
- tmva/tmvagui/src/tmvaglob.cxx
- Fix segfault if class name has underscore in name
- Fix segfault if no identity variable transformation is booked
> [TMVA] Fix various segfaults in multiclass GUI

- core/clingutils/src/TClingUtils.cxx
When we add modules for system headers we are breaking this part
of the code that tries to track back via the include chain
the original header that includes this system header. In the
modules case we hit the "module-includes:X" include which
we then can't track down with the normal PP anymore.
The reason for this code seems to be that we never know what header
is actually possible to be included and what is just some internal
(possibly non-standalone) header like "bits/sys/types.h".
For normal rootcling informations we have to track down until
we leave the system includes or reach the top-level system
include to be sure that we can now actually include the
given path.
For modules we already know when we are in the header that
is possible to be included by someone as this is the top
level …
> [cxxmodules] Fix TMetaUtils::GetFileName with system modules

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/CMakeLists.txt
- tree/treeplayer/test/dataframe/dataframe_cache.cxx
First implementation of the caching mechanism and minimal testing. 
This is here to start the testing in the CI, the development is not finished yet.
> [WIP] TDF caching mechanism

- math/mathcore/test/fit/testBinnedFitExecPolicy.cxx
Add speedup printing, improve legibility, refactorization.
Speedup printing can still be improved.
> Improve BinnedFit test

- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/controller/CanvasPanel.controller.js
- etc/http/openui5/controller/Panel.controller.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
plus few other small fixes from current JSROOT master
> jsroot: correct draw of TH2 projections in web canvas

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDFUtils.cxx
One more complicated [issue](https://coverity.cern.ch/reports.htm#v14989/p10001/fileInstanceId=761497765&defectInstanceId=395401393&mergedDefectId=97393&eventIds=395393458-0) remains to be addressed.
> [TDF] Coverity fixes

- documentation/spectrum/Spectrum.md
Better English, better Markdown formatting, less typos, updated references.
> Improved readability of Spectrum.md

- tree/treeplayer/inc/ROOT/TDataFrame.hxx
- tree/treeplayer/test/dataframe/dataframe_interface.cxx
> [TDF] Fix ROOT-9037

- tree/treeplayer/inc/ROOT/TDataFrame.hxx
> [TDF] Fix ctor with single filename as string.

- cmake/modules/SearchInstalledSoftware.cmake
Asked the originator to test. See https://sft.its.cern.ch/jira/browse/ROOT-9032
> Fix for ROOT-9032

- hist/hist/inc/TF1.h
- hist/hist/test/test_tf1.cxx
Bug found in the forum: https://root-forum.cern.ch/t/tf1-constructor-with-custom-class-broken-with-xcode-9-0/26422/9
> Fix constructor for pointer to functor

- tree/treeplayer/src/TDFUtils.cxx
If friend trees are present, search them for valid column names.
> [TDF] Also look for valid column names in friend trees

- core/metacling/src/TCling.cxx
At the moment we use modules for ROOT and the PCH conflicts with
that, so let's not when modules are activated (at least for now).
> [cxxmodules] Disable PCH with modules activated for now.

- tree/treeplayer/test/dataframe/dataframe_friends.cxx
Two more unit tests and a slight refactoring of the existing ones.
> [TDF] Test friend trees' branches which contain arrays 

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/test/dataframe/dataframe_cache.cxx
- tree/treeplayer/test/dataframe/dataframe_callbacks.cxx
not sure why they did not appear in the PR builds
> [TDF] Remove warnings in nightly builds

- tree/treeplayer/test/dataframe/dataframe_callbacks.cxx
> [TDF] Remove warning in clang6

- core/base/inc/ROOT/StringConv.hxx
- core/base/inc/TString.h
- core/clingutils/src/RStl.cxx
- core/clingutils/src/TClingUtils.cxx
- core/dictgen/src/BaseSelectionRule.cxx
- core/dictgen/src/rootcling_impl.cxx
- core/foundation/inc/RStringView.h
- core/foundation/inc/TClassEdit.h
- core/foundation/src/TClassEdit.cxx
- core/metacling/src/TCling.cxx
- hist/hist/src/TFormula.cxx
- io/io/inc/TFile.h
- io/io/inc/TFileMerger.h
- io/io/src/TCollectionProxyFactory.cxx
- io/io/src/TEmulatedCollectionProxy.cxx
- io/io/src/TFile.cxx
- io/io/src/TGenCollectionProxy.cxx
- io/io/src/TMakeProject.cxx
- main/src/nbmain.cxx
- math/minuit/src/TMinuitMinimizer.cxx
- roofit/roofitcore/src/RooSharedPropertiesList.cxx
- roofit/roostats/src/ToyMCSampler.cxx
- test/stressTMVA.cxx
- tmva/tmva/src/Factory.cxx
- tmva/tmva/src/MethodBoost.cxx
- tmva/tmva/src/MethodCategory.cxx
- tmva/tmva/src/MethodCompositeBase.cxx
- tmva/tmva/src/Reader.cxx
New way of addressing compatibility with XCode9 while preserving auto-conversion from TString to std::string (at the expense on making the conversion from TString to std::string_view non-automatic).
> XCode9 compatibility

- bindings/pyroot/src/Converters.cxx
- bindings/pyroot/test/conversions.py
> [PyROOT] Convert python string to string_view also on XCode9

- tutorials/dataframe/tdf001_introduction.C
- tutorials/dataframe/tdf001_introduction.py
- tutorials/dataframe/tdf002_dataModel.C
- tutorials/dataframe/tdf004_cutFlowReport.C
- tutorials/dataframe/tdf004_cutFlowReport.py
- tutorials/dataframe/tdf005_fillAnyObject.C
- tutorials/dataframe/tdf006_ranges.C
- tutorials/dataframe/tdf006_ranges.py
- tutorials/dataframe/tdf007_snapshot.C
- tutorials/dataframe/tdf007_snapshot.py
- tutorials/dataframe/tdf008_createDataSetFromScratch.C
- tutorials/dataframe/tdf008_createDataSetFromScratch.py
- tutorials/dataframe/tdf009_FromScratchVSTTree.C
- tutorials/dataframe/tdf011_ROOTDataSource.C
- tutorials/dataframe/tdf011_ROOTDataSource.py
- tutorials/dataframe/tdf013_InspectAnalysis.C
- tutorials/dataframe/tdf101_h1Analysis.C
This work on the C++ tutorial really shows that we need a fake column with the entry number. If we agree, this would be easy to achieve thanks to the recent developments done for cache :)
> [TDF] Generate datasets in the C++ tutorials with TDF and Snapshot

- tree/treeplayer/src/TDFNodes.cxx
- tree/treeplayer/test/dataframe/dataframe_nodes.cxx
> [TDF] Fix bug preventing double loop on a tdf based on real files

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/test/dataframe/dataframe_snapshot.cxx
The fix relies on:
- users only ever using `array_view<T>` in `Define`, `Filter` and TDF
actions to read c-style arrays from TTrees, and not for std::vector,
for example
- the fact that for TTree branches that contain c-style arrays one can
use the title of the input branch as the title of the output branch,
as is
The fix requires to `const_cast` away the constess of the pointer
returned by `array_view::data` to pass it to `TTree::Branch` as `void *`.
Because of this last issue and because of the first point above,
in the future it might be better to not use `array_view` but our
own custom type `TDFArray` to let users signal c-style arrays.
Or maybe `TTree::Branch` could be made to accept a `const void*`, I'm not sure about that.
> [TDF] Fix ROOT-8979: write c-style arrays with Snapshot

- hist/hist/src/TGraph2D.cxx
This was reported here: https://root-forum.cern.ch/t/tgraph2d-plotting-issues/26562
> Fix precision issue when the min and max values are equal on TGraph2D axis.

- tree/treeplayer/inc/LinkDef.h
- tree/treeplayer/inc/ROOT/TCsvDS.hxx
- tree/treeplayer/src/TCsvDS.cxx
- tree/treeplayer/test/CMakeLists.txt
- tree/treeplayer/test/dataframe/TCsvDS_test_headers.csv
- tree/treeplayer/test/dataframe/TCsvDS_test_noheaders.csv
- tree/treeplayer/test/dataframe/datasource_csv.cxx
- tutorials/CMakeLists.txt
- tutorials/dataframe/tdf014_CSVDataSource.C
- tutorials/dataframe/tdf014_CSVDataSource.py
This commit provides the implementation of a new data source for TDataFrame that is able to read CSV files.
Some of its features include:
- File content stored in memory
- Type inference (int, double, bool, string)
- Configurable delimiter
- Quoted fields & quote escaping support
> TDataFrame - CSV data source

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFActionHelpers.cxx
- tree/treeplayer/test/dataframe/dataframe_regression_tests.hxx
Otherwise we return a double as before. In case of a column of a container type, we return the real value_type when the container type is passed as parameter, otherwise we return double.
> [TDF] Return real column type from Min/Max when passed as template param

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
Better failing with a static_assert than letting compilation explode in the face of TDF users.
> [TDF] static_assert that the `Define` callables do not 

- core/foundation/inc/ROOT/RMakeUnique.hxx
The required version of Visual Studio already support make_unique. Thanks Enrico Guiraud for the suggestion.
> Simplify the test for std::make_unique

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFUtils.hxx
Also in this PR: a very minor fix to `MinHelper`.
> [TDF] Add `Sum` action

- tmva/tmva/CMakeLists.txt
- tmva/tmva/inc/LinkDef1.h
- tmva/tmva/inc/TMVA/Classification.h
- tmva/tmva/inc/TMVA/CrossValidation.h
- tmva/tmva/inc/TMVA/DataLoader.h
- tmva/tmva/inc/TMVA/DataSetManager.h
- tmva/tmva/inc/TMVA/Envelope.h
- tmva/tmva/inc/TMVA/MethodBase.h
- tmva/tmva/inc/TMVA/MethodBoost.h
- tmva/tmva/inc/TMVA/MethodCategory.h
- tmva/tmva/inc/TMVA/OptionMap.h
- tmva/tmva/inc/TMVA/ROCCurve.h
- tmva/tmva/inc/TMVA/Results.h
- tmva/tmva/src/Classification.cxx
- tmva/tmva/src/CrossValidation.cxx
- tmva/tmva/src/Envelope.cxx
- tmva/tmva/src/HyperParameterOptimisation.cxx
- tmva/tmva/src/ROCCurve.cxx
- tmva/tmva/src/VariableImportance.cxx
- tutorials/tmva/envelope/classification.C
- Code to support book multiple ml methods in the envelope class.
- A new class Classification to perform two class classification in the new architecture of TMVA.
> Mater tmva classification

- interpreter/cling/lib/Interpreter/Transaction.cpp
When generating the GQt module in rootcling, we hit the assertions
in forceAppend assertions about "Duplicates?!" with this declaration:
```
CXXRecordDecl 0x55555643fae8 </usr/include/qt4/QtCore/qglobal.h:1658:1, line:1794:1> line:1658:21 in GQt.TGQt.h hidden class QSysInfo definition
|-also in GQt.TQtClientWidget.h
|-CXXRecordDecl 0x55555643fc30 <col:1, col:21> col:21 in GQt.TGQt.h hidden implicit class QSysInfo
|-AccessSpecDecl 0x55555643fce8 <line:1659:1, col:7> col:1 in GQt.TGQt.h public
|-EnumDecl 0x55555643fd18 <line:1660:5, line:1662:5> line:1660:10 in GQt.TGQt.h hidden Sizes
| `-EnumConstantDecl 0x55555643fe98 <line:1661:9, col:38> col:9 in GQt.TGQt.h hidden WordSize 'enum QSysInfo::Sizes'
|   `-ImplicitCastExpr 0x55555643fee0 <col:20, col:38> 'unsigned int' <IntegralCast>
| …
```
> [cxxmodules] Fix assert failure with duplicate decls.

- tutorials/tmva/TMVACrossValidation.C
small fix in tutorial of CrossValidation.
> TMVA: small fix in tutorial of CrossValidation

- etc/http/files/panel.htm
- etc/http/openui5/GuiPanelController.js
- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/controller/FitPanel.controller.js
- etc/http/openui5/view/FitPanel.view.xml
- gui/fitpanel/CMakeLists.txt
- gui/fitpanel/inc/LinkDef.h
- gui/fitpanel/v7/inc/ROOT/TFitPanel.hxx
- gui/fitpanel/v7/src/TFitPanel.cxx
- gui/webdisplay/cef/simple_app.cxx
- gui/webdisplay/cef/simple_app.h
- gui/webdisplay/src/TWebWindowsManager.cxx
- tutorials/v7/fitpanel.cxx
Special model allows to set FitPanel openui5 elements directly.
Also when "Fit" button pressed, draw dummy histogram in new canvas or in the bound canvas
Let open many windows with CEF (was not possible before)
> webgui: special model for FitPanel

- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- gui/fitpanel/v7/src/TFitPanel.cxx
- gui/webdisplay/cef/simple_app.cxx
- gui/webdisplay/cef/simple_app.h
- gui/webdisplay/inc/ROOT/TWebWindow.hxx
- gui/webdisplay/inc/ROOT/TWebWindowsManager.hxx
- gui/webdisplay/qt5/rootqt5.cpp
- gui/webdisplay/qt5/rootwebview.cpp
- gui/webdisplay/qt5/rootwebview.h
- gui/webdisplay/src/TWebWindow.cxx
- gui/webdisplay/src/TWebWindowsManager.cxx
In CEF and Qt5WebEngine set window size.
Use for FitPanel 300x500 as initial size for demonstration
Also chrome browser allows to set window size and show HTML page without typical browser decoration
One can set shell variable WEBGUI_WHERE which allows to change default behavior
> webgui: introduce window geometry

- graf3d/gl/inc/TGLEmbeddedViewer.h
- graf3d/gl/inc/TGLOrthoCamera.h
- graf3d/gl/inc/TGLSAViewer.h
- graf3d/gl/inc/TGLViewer.h
- graf3d/gl/src/TGLOrthoCamera.cxx
- graf3d/gl/src/TGLSAViewer.cxx
- graf3d/gl/src/TGLViewer.cxx
Patch currently applied to the SHiP software stack. It would be nice if this could be merged upstream after review.
> Add new projections to TGLViewer

- gui/webdisplay/src/TWebWindow.cxx
Assert does not work on Linux?
> webgui: fix assert condition

- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- gui/fitpanel/v7/src/TFitPanel.cxx
- gui/webdisplay/cef/base_handler.cxx
- gui/webdisplay/cef/base_handler.h
- gui/webdisplay/cef/simple_app.cxx
- gui/webdisplay/cef/simple_app.h
Also small improvement in CEF handlers
> wbgui: use lambdas instead of std::bind

- core/metacling/src/TClingCallbacks.cxx
We don't need this code for now and just use the old way.
> [cxxmodules] Remove modules specific code in TClingCallbacks.

- interpreter/cling/lib/Interpreter/Interpreter.cpp
See the two commits for more information.
> [cxxmodules] Prevent modules from overwriting our AST/Sema sources

- interpreter/cling/lib/Interpreter/Interpreter.cpp
Reverts root-project/root#1262
> Revert "[cxxmodules] Prevent modules from overwriting our AST/Sema sources"

- graf2d/gpad/v7/inc/ROOT/TVirtualCanvasPainter.hxx
- graf2d/gpad/v7/src/TDrawingOptsReader.cxx
- graf2d/gpad/v7/src/TVirtualCanvasPainter.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- hist/histdraw/v7/inc/ROOT/THistDrawable.hxx
- hist/histdraw/v7/src/THistDrawable.cxx
> ROOT7 win symbol fixes

- interpreter/cling/test/Interfaces/evaluate.C
- interpreter/cling/test/Pragmas/opt.C
- interpreter/cling/test/Prompt/DontWrap.C
- interpreter/cling/test/Prompt/MetaProcessor/DotO.C
- interpreter/cling/test/Prompt/OutputRedirect.C
- interpreter/cling/test/Prompt/ValuePrinter/Assignments.C
- interpreter/cling/test/Prompt/ValuePrinter/Regression.C
- interpreter/cling/test/Prompt/ValuePrinter/TuplesAndPairs.C
After .O0 and new floating point formatting.
> Cling test fixes

- geom/geom/CMakeLists.txt
- geom/geom/inc/LinkDef1.h
- geom/geom/inc/TGeoElement.h
- geom/geom/inc/TGeoMaterial.h
- geom/geom/inc/TGeoPhysicalConstants.h
- geom/geom/inc/TGeoSystemOfUnits.h
- geom/geom/src/TGeoElement.cxx
- geom/geom/src/TGeoMaterial.cxx
Contribution of Marko Petric for synchonizing TGeo material properties with Geant4 ones.
> Petricm g4formulas

- math/mathcore/inc/Math/IParamFunction.h
Reported here: https://connect.microsoft.com/VisualStudio/feedback/details/3143729
> Work around a MVSC++ bug

- tree/tree/src/TChain.cxx
- tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
- tree/treeplayer/src/TTreeProcessorMT.cxx
This implementation intends to pave the way for the support of tree/chain friends in TDataFrame MT. For that purpose, now TTreeProcessorMT stores the information about the friends of the processed tree/chain.
In order to provide support for friends, this implementation proposes a new way of dealing with chains in TTreeProcessorMT. The old way consisted in operating file by file, obtaining a TTree from each file and then constructing a TTreeReader for the particular range a task was going to process in that TTree.
The aforementioned implementation prevented the support for friend chains, since there was no chain to add the friends to, only trees. In this new implementation, TTreeProcessorMT always constructs a chain per TTreeView, from which TTreeReaders are created to operate on ranges of …
> Support tree/chain friends in TTreeProcessorMT.

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/src/TDFInterface.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/src/TDataFrame.cxx
The tests for this pr are in PR1148 (test driven development!)
> [TDF] Support friend columns in jitted Define's and Filter's

- tree/treeplayer/test/dataframe/dataframe_friends.cxx
Thanks @etejedor for noticing the error messages I missed.
> [TDF] Fix dataframe_friends test after array_view->TArrayBranch change

- graf2d/gpad/v7/inc/ROOT/TObjectDrawable.hxx
- math/mathcore/v7/inc/ROOT/TFit.hxx
- tutorials/CMakeLists.txt
- tutorials/v7/concurrentfill.cxx
- tutorials/v7/histops.cxx
- tutorials/v7/perf.cxx
- tutorials/v7/perfcomp.cxx
Fix v7 tutorials and enable them for CTest.
> V7 tutorial fix

- tree/treeplayer/test/dataframe/dataframe_friends.cxx
...jitted and non-jitted version
> [TDF] Add tests for using friend trees in `Define`

- tree/treeplayer/inc/TTreeReaderArray.h
- tree/treeplayer/test/readerarray_iterator.cxx
> [TTreeReader] Fix "int + TTreeReaderArray::Iterator_t"

- README/ReleaseNotes/v612/index.md
Please check that none of your contributions was forgotten!
> [DOC] Update TDF release notes

- geom/gdml/src/TGDMLParse.cxx
- geom/geom/src/TGeoManager.cxx
- graf2d/asimage/src/libAfterImage/afterbase.c
- graf2d/asimage/src/libAfterImage/libungif/gifalloc.c
- graf2d/graf/src/TMathText.cxx
- graf2d/mathtext/src/fontembed.cxx
- graf2d/mathtext/src/fontembedps.cxx
- graf2d/mathtext/src/mathrender.cxx
- graf2d/mathtext/src/mathrendertoken.cxx
- graf2d/mathtext/src/mathtext.cxx
- graf2d/mathtext/src/mathtextparse.cxx
- graf2d/mathtext/src/mathtextview.cxx
- graf2d/win32gdk/src/TGWin32.cxx
- graf3d/eve/src/TEveCalo2DGL.cxx
- graf3d/eve/src/TEveCaloLegoGL.cxx
- graf3d/eve/src/TEvePointSet.cxx
- graf3d/gl/src/TGLAxisPainter.cxx
- graf3d/gl/src/TGLCameraOverlay.cxx
- graf3d/gl/src/TGLScene.cxx
- graf3d/gl/src/gl2ps.cxx
- hist/hist/src/TFormula.cxx
- hist/hist/src/TGraphSmooth.cxx
- hist/hist/src/TPrincipal.cxx
- hist/histpainter/src/TGraph2DPainter.cxx
- hist/unfold/src/TUnfold.cxx
- hist/unfold/src/TUnfoldDensity.cxx
...and squashing some reverts. Supersedes PR #1239
> PR1239 with reduced clang-format

- core/dictgen/src/rootcling_impl.cxx
Some tests are failing with modules such with redefinition errors
(for example `roottest-cling-parsing-scopeDict-build`).
The reason for this is that we include all headers that form
the C++ module again to make sure the module is complete (some
rootcling invocations don't have all headers of the module as
arguments, most notably the Core module). The first inclusion
of these headers happens from the normal rootcling code.
This patch changes this behavior that we only include the
*missing* headers that are necessary to make the C++ module
complete and not all headers.
> [cxxmodules] Don't include existing headers again in rootcling.

- graf2d/graf/src/TEllipse.cxx
Added a missing space in a comment, which propagates into the documentation.
> Added a missing space

- hist/hist/inc/TMultiGraph.h
- hist/hist/src/TMultiGraph.cxx
works even is the multigraph is not drawn.
As requested here: https://root-forum.cern.ch/t/tmultigraph-getxaxis-settitle-version-4-01/3928/5
> TMultiGraph::GetHistogram 

- graf2d/gpad/inc/TCanvas.h
This fix was suggested here: https://root-forum.cern.ch/t/tcanvas-setwindowsize-extension-proposal/26226
> To get the same window size in interactive mode and batch mode.

- interpreter/llvm/src/tools/clang/include/clang/Sema/Sema.h
Original commit message:
"Constify. NFC."
> [llvm][backport] Backport r319037.

- core/base/src/TDirectory.cxx
- io/io/src/TDirectoryFile.cxx
This resolved https://epsft-jenkins.cern.ch/job/root-incremental-master/BUILDTYPE=Debug,COMPILER=native,LABEL=mac1012/5509/testReport/projectroot.tree.treeplayer/test/gtest_tree_treeplayer_test_dataframe_snapshot/
> TDirectory Constructor

- io/xml/inc/TXMLEngine.h
- io/xml/src/TXMLEngine.cxx
- tutorials/xml/xmlmodifyfile.C
- tutorials/xml/xmlnewfile.C
- tutorials/xml/xmlreadfile.C
Provide missing feature, which probably required here:
https://root-forum.cern.ch/t/27044
Add correspondent tutorial, adjust older tutorials as well.
> Add possibility to insert XML node in the middle of childs list

- core/base/inc/Rtypes.h
- core/cont/src/TClassTable.cxx
- core/meta/inc/TGenericClassInfo.h
- core/meta/src/TGenericClassInfo.cxx
Please see commit messages for more information. This probably also fixes [ROOT-9139](https://sft.its.cern.ch/jira/browse/ROOT-9139).
> Fix type deduction bug

- README/ReleaseNotes/v612/index.md
@dpiparo can you please check whether I forgot something important?
> [DOC] Add more TDF tutorials to the release notes

- core/base/inc/CommandLineOptionsHelp.h
- core/base/src/TApplication.cxx
- rootx/src/rootx.cxx
They are meant to be identical but diverged.
> Merge help text from TApplication and rootx.

- net/rootd/src/rootd.cxx
Address security threat reported by S. Luders.
Using the same technology used in TSystem::ExpandFileName.
This is a backport of commit 88ccff152604e0f1012653a596d802ff7ede3145. This is a fix for [CVE-2017-1000203](https://nvd.nist.gov/vuln/detail/CVE-2017-1000203).
> rootd: do not use popen() to expand path names

- geom/gdml/src/TGDMLParse.cxx
- tmva/tmva/src/Classification.cxx
fixed bug on mac for class classification.
> TMVA: fix mac bug on class classification

- tutorials/math/principal.py
Clear data row every time add a row to principal
> Fix error in python version of principal

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDataFrame.cxx
This also addresses [ROOT-9124](https://sft.its.cern.ch/jira/browse/ROOT-9124)
> [TDF] Misc fixes for the documentation and interface

- tutorials/hist/candledecay.C
- tutorials/hist/candlehisto.C
- tutorials/hist/candleplot.C
- tutorials/hist/candleplotoption.C
- tutorials/hist/candleplotstack.C
- tutorials/hist/candleplotwhiskers.C
- tutorials/hist/candlescaled.C
- tutorials/hist/histpalettecolor.C
> Fix for ROOT-9030 - Several notebook tutorials show errors

- tutorials/sql/sqlselect.C
See [1], I add some lines to improve the comprehension of the tutorial. 
[1] https://root.cern.ch/root/html534/tutorials/sql/index.html
> Improving the documentation in sql sample

- man/man1/hist2workspace.1
- man/man1/pq2-ana-dist.1
- man/man1/pq2-cache.1
- man/man1/pq2-info-server.1
- man/man1/pq2-ls-files-server.1
- man/man1/pq2-ls-files.1
- man/man1/pq2-ls.1
- man/man1/pq2-put.1
- man/man1/pq2-redistribute.1
- man/man1/pq2-rm.1
- man/man1/pq2-verify.1
- man/man1/pq2.1
- man/man1/proofd.1
- man/man1/root.1
- man/man1/root.exe.1
- man/man1/roota.1
- man/man1/rootn.exe.1
- man/man1/roots.exe.1
- man/man1/setup-pq2.1
- man/man1/xpdtest.1
- man/man1/xproofd.1
ran `aspell -d en -n -c <filename>` on the man pages.
> spellcheck on man pages

- test/CMakeLists.txt
- test/periodic/CMakeLists.txt
- test/periodic/LoadXS.C
- test/periodic/NdbEndfIO.cxx
- test/periodic/NdbEndfIO.h
- test/periodic/NdbMTDir.cxx
- test/periodic/NdbMTDir.h
- test/periodic/NdbMTReacDesc.cxx
- test/periodic/NdbMTReactionXS.cxx
- test/periodic/NdbMTReactionXS.h
> Added 'test-periodic-build' test

- core/cont/inc/THashTable.h
- core/cont/src/THashTable.cxx
- core/meta/inc/TClass.h
- core/meta/src/TCheckHashRecurveRemoveConsistency.h
- core/meta/src/TClass.cxx
- core/meta/test/testHashRecursiveRemove.cxx
- core/thread/src/TReentrantRWLock.cxx
- Correct TReentrantRWLock::Restore
- Assert on Add during THashTable::Rehash
-  Add 'details' option to THashTable::Print
> Various fixes related to the change made for the RW Lock 

- tree/treeplayer/inc/ROOT/TRootDS.hxx
- tree/treeplayer/src/TRootDS.cxx
cleaining the task local chain at the end of the task via the FinaliseSlot method.
> [TDF] Further improve TRootDS implementation

- hist/hist/src/TH1.cxx
New PR as discussed here (https://github.com/root-project/root/pull/1496)
> Fix Error Location on TH1.cxx Error Statements

- README/ReleaseNotes/v612/index.md
- core/base/src/TObject.cxx
- core/meta/inc/TClass.h
- core/meta/src/TCheckHashRecursiveRemoveConsistency.h
- core/meta/src/TClass.cxx
- core/meta/test/testHashRecursiveRemove.cxx
- core/thread/test/testRWLock.cxx
- net/net/inc/TSocket.h
- net/net/src/TSocket.cxx
- tutorials/CMakeLists.txt
> Root 9182 v612

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_cache.cxx
- tree/treeplayer/test/dataframe/dataframe_snapshot.cxx
Simple backport of the latest fixes that landed in master.
> [TDF] Backport tdf fixes

- io/xml/src/TXMLEngine.cxx
While formatting of sources was changed dramatically, pick only bug fix from #1548
> xml: fix problem with comments at the end of the file in v6.10 branch

- io/xml/src/TXMLEngine.cxx
> xml: comments at the end of the file in 6.12 branch

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_interface.cxx
With this, master and v6.12 are synced with respect to bugfixes and doc improvements.
> [TDF]  more backports

- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/src/TCsvDS.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/src/TRootDS.cxx
- tree/treeplayer/src/TTrivialDS.cxx
- tree/treeplayer/test/dataframe/datasource_csv.cxx
- tree/treeplayer/test/dataframe/datasource_root.cxx
- tree/treeplayer/test/dataframe/datasource_trivial.cxx
Checking the type of the columns also when provided by a data source.
> [TDF] Fix ROOT-9218

- tree/treeplayer/inc/ROOT/TCsvDS.hxx
- tree/treeplayer/src/TCsvDS.cxx
- tree/treeplayer/test/dataframe/datasource_csv.cxx
This PR fixes [ROOT-9219](https://sft.its.cern.ch/jira/browse/ROOT-9219) and optimises and streamlines the access to columns.
A test was of course added.
> [TDF] Fix ROOT-9219

- hist/hist/inc/TGraph.h
- hist/hist/src/TGraph.cxx
This was reported here: https://sft.its.cern.ch/jira/browse/ROOT-9222
> TGraph:SetNameTitle didn't change the underlying histogram title

- math/mathcore/test/fit/testMinim.cxx
- math/minuit2/inc/Minuit2/BFGSErrorUpdator.h
- math/minuit2/inc/Minuit2/Minuit2Minimizer.h
- math/minuit2/inc/Minuit2/VariableMetricBuilder.h
- math/minuit2/inc/Minuit2/VariableMetricMinimizer.h
- math/minuit2/src/BFGSErrorUpdator.cxx
- math/minuit2/src/Minuit2Minimizer.cxx
Add BFGS update as an additional minimiser option. This a slight variation compared to Migrad and it could be useful and work better in some cases.
> Add BFGS update as a new algorithm in Minuit2

- graf2d/primitives/v7/inc/ROOT/TStyle.hxx
- graf2d/primitives/v7/src/TColor.cxx
- graf2d/primitives/v7/src/TStyle.cxx
- graf2d/primitives/v7/src/TStyleReader.cxx
- graf2d/primitives/v7/src/TStyleReader.hxx
Next stop: use CSS-style and attribute base. But that's details.
> Read style files

- tmva/tmva/test/crossvalidation/TestCrossValidationSerialise.cxx
Two dynamic objects were not properly destroyed at program exit.
> [TMVA] TestCrossValidationSerialise memory handling

- core/winnt/src/TWinNTSystem.cxx
- graf2d/qt/src/TGQt.cxx
- graf2d/qt/src/TQtClientGuard.cxx
- graf3d/eve/src/TEveElement.cxx
- html/src/TDocDirective.cxx
- io/sql/src/TSQLStructure.cxx
- math/mathcore/src/Delaunay2D.cxx
- net/http/civetweb/handle_form.inl
- roofit/histfactory/src/hist2workspace.cxx
- roofit/roofitcore/src/BidirMMapPipe.cxx
- roofit/roofitcore/src/RooClassFactory.cxx
- roofit/roofitcore/src/RooFactoryWSTool.cxx
- roofit/roostats/src/MetropolisHastings.cxx
- tmva/tmva/src/CostComplexityPruneTool.cxx
- tmva/tmva/src/DataSet.cxx
- tmva/tmva/src/Reader.cxx
- tmva/tmva/src/VariableGaussTransform.cxx
> Fix some cppcheck reports

- etc/http/changes.md
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
> jsroot 5.4.0

- core/base/v7/inc/ROOT/TLogger.hxx
"And make sure we didn't see any errors or warnings."
> Add diagnostic counts, suuuper nice for tests!

- hist/hist/inc/TGraph2D.h
- hist/hist/inc/TGraph2DErrors.h
- hist/hist/src/TGraph2D.cxx
- hist/hist/src/TGraph2DErrors.cxx
As requested here: https://root-forum.cern.ch/t/print-content-of-tgraph2derrors/27972
> Implement "Print" for TGraph2D and TGraph2DErrors.

- hist/hist/src/TFormula.cxx
A few minimal fixes/improvements to TFormula.
> Misc fixes for TFormula

- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/src/TDFInterfaceUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_utils.cxx
These changes test and provide the functionality to access quantities called "mybranch.mysubbranch"
> [TDF] [WIP] Allow to read nested branches/leaves

- graf2d/primitives/v7/test/text.cxx
> new test for v7 text

- roofit/roofit/src/RooCFunction1Binding.cxx
- roofit/roofit/src/RooCFunction2Binding.cxx
- roofit/roofit/src/RooCFunction3Binding.cxx
- roofit/roofit/src/RooCFunction4Binding.cxx
There files were not using RooCintUtils.h which is an implementation for old interpreter.
> Remove redundant RooCintUtils.h

- interpreter/cling/lib/Interpreter/ValueExtractionSynthesizer.cpp
- interpreter/cling/test/Prompt/ValuePrinter/Regression.C
This should have landed in 7554be9571.
> Add forgotten to commit protection and check clause.

- tree/treeplayer/inc/ROOT/TVec.hxx
- tree/treeplayer/test/vecops/vecops_tvec.cxx
> [VecOps] Add Variance and Std Deviation for TVecs

- roofit/roofitcore/src/RooFactoryWSTool.cxx
This is a trivial change, but I saw it was using char* not std::string
and I couldn't resist rewriting it.
> Rewrite some RooFactory::createArgs code

- tree/treeplayer/inc/ROOT/TDFHistoModels.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/src/TDFHistoModels.cxx
- tree/treeplayer/test/dataframe/dataframe_histomodels.cxx
This PR fixes the jira item, refactors the code of the models in order to simplify and reduce code duplication and extends significantly the test coverage.
> [TDF] Fix ROOT-9295: fix variable bin sizes models

- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFUtils.hxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_snapshot.cxx
An Info message is printed when this happens.
This resolves [ROOT-9270](https://sft.its.cern.ch/jira/browse/ROOT-9270).
> [TDF] Replace dots with underscores in snapshotted columns

- tmva/tmva/inc/TMVA/CrossValidation.h
- tmva/tmva/inc/TMVA/Envelope.h
- tutorials/tmva/TMVACrossValidation.C
Small update. When working with the cross validation manual, I came across these inconveniences.
> [TMVA] Enhance usability of CVResults and Envelope interfaces

- roofit/roofitcore/src/RooFactoryWSTool.cxx
> Attempt isValidEnumValue to the semantic of TEnum::GetEnum.

- math/mathcore/inc/Fit/FitData.h
- math/mathcore/inc/Math/WrappedParamFunction.h
- math/mathcore/src/BinData.cxx
- math/mathcore/src/FitData.cxx
- math/mathcore/src/TKDTreeBinning.cxx
- math/mathcore/test/binarySearchTime.cxx
- math/mathcore/test/testkdTreeBinning.cxx
- math/mathmore/test/testPermute.cxx
- tree/tree/test/TBasket.cxx
Here are some fixes for failing tests.
> Test fixes

- interpreter/cling/include/cling/Interpreter/InvocationOptions.h
- interpreter/cling/lib/Interpreter/CIFactory.cpp
- interpreter/cling/lib/Interpreter/Interpreter.cpp
- interpreter/cling/lib/Interpreter/InvocationOptions.cpp
- interpreter/cling/test/Driver/CUDAMode.C
- interpreter/cling/test/Interfaces/invocationFlags.C
- interpreter/cling/test/lit.cfg
> cling PR-220

- man/man1/root-config.1
Improved documentation, made minor changes to spelling.
> Edited grammatical errors

- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFInterfaceUtils.hxx
- tree/treeplayer/src/TDFInterfaceUtils.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_interface.cxx
- tree/treeplayer/test/dataframe/dataframe_snapshot.cxx
- tree/treeplayer/test/dataframe/dataframe_utils.cxx
This PR addresses [this ticket](https://sft.its.cern.ch/jira/browse/ROOT-9271).
> [TDF] Support "branch.subbranch.leaf" syntax in JITted expressions

- hist/hist/src/TH1.cxx
TH1::Clone calls TH1::Copy which might published the copy-into object. to the ListOfCleanups.
Clone can call RecursiveRemove, for example via TCheckHashRecursiveRemoveConsistency
when dictionary information is initialized, so we need to keep obj->fFunction valid
during its execution and protect the update with the write lock.
This issues was seen as a crash in roottest-root-multicore-threadExecutor.
> Avoid access to deleted object (indirectly) from TH1::Clone.

- tmva/tmva/src/PDF.cxx
log message was missing a closing parenthesis
> closing parenthesis in tmva/tmva/src/PDF.cxx

- tutorials/v7/lineStyle.cxx
- tutorials/v7/lineWidth.cxx
New examples for lineWidth and lineStyle
> New Line Example for v7

- core/dictgen/res/Scanner.h
- core/dictgen/src/Scanner.cxx
- core/dictgen/src/rootcling_impl.cxx
Do not create template specializations during AST visitation.
> Fix spec creation rec ast visitor

- config/rootrc.in
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- gui/cefdisplay/src/base_handler.cxx
- gui/fitpanel/v7/src/TFitPanel.cxx
- gui/webdisplay/inc/ROOT/TWebWindow.hxx
- gui/webdisplay/src/TWebWindow.cxx
- gui/webdisplay/src/TWebWindowsManager.cxx
- net/http/civetweb/civetweb.c
- net/http/inc/LinkDef.h
- net/http/inc/TCivetweb.h
- net/http/inc/THttpCallArg.h
- net/http/inc/THttpLongPollEngine.h
- net/http/inc/THttpServer.h
- net/http/inc/THttpWSEngine.h
- net/http/src/TCivetweb.cxx
- net/http/src/TFastCgi.cxx
- net/http/src/THttpCallArg.cxx
- net/http/src/THttpLongPollEngine.cxx
- net/http/src/THttpServer.cxx
- net/http/src/THttpWSEngine.cxx
Plus additional cleanup of interface in THttpServer class
Changing arguments order in TWebWindow::Send() methods
Address most comments from #1785
> webgui: support https for TWebWindow

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
this is https://sft.its.cern.ch/jira/browse/ROOT-9366
> [TDF] Read into TVec also when memory of TTreeReaderArray is not contiguous

- tree/treeplayer/inc/ROOT/TArrowDS.hxx
- tree/treeplayer/inc/ROOT/TDFActionHelpers.hxx
- tree/treeplayer/inc/ROOT/TDFInterface.hxx
- tree/treeplayer/inc/ROOT/TDFInterfaceUtils.hxx
- tree/treeplayer/inc/ROOT/TDFNodes.hxx
- tree/treeplayer/inc/ROOT/TDataFrame.hxx
- tree/treeplayer/inc/ROOT/TResultProxy.hxx
- tree/treeplayer/inc/ROOT/TResultPtr.hxx
- tree/treeplayer/inc/ROOT/TSnapshotOptions.hxx
- tree/treeplayer/src/TDFInterfaceUtils.cxx
- tree/treeplayer/src/TDFNodes.cxx
- tree/treeplayer/src/TDFUtils.cxx
- tree/treeplayer/test/dataframe/dataframe_nodes.cxx
Also make a (human-checked) `clang-format` pass on all TDF files.
> [TDF] Update/improve naming of internal variables and methods

- tutorials/pyroot/pyroot001_arrayInterface.py
- tutorials/pyroot/pyroot002_TTreeAsMatrix.py
Examples for the mentioned features. Dependent on PR #1872.
> [PyROOT] Add tutorials for array interface and TTree.AsMatrix features

- montecarlo/vmc/inc/LinkDef.h
- montecarlo/vmc/inc/TVirtualMC.h
- montecarlo/vmc/inc/TVirtualMCApplication.h
- montecarlo/vmc/inc/TVirtualMCSensitiveDetector.h
- montecarlo/vmc/src/TVirtualMCSensitiveDetector.cxx
Support for user defined sensitive detectors; new TVirtualMC::NIELEdep(); clean-up:
Details:
o TVirtualMCSensitiveDetector: the interface class for a user sensitive detector
o New functions in TVirtualMC:
void SetSensitiveDetector(const TString &volName, TVirtualMCSensitiveDetector *sd);
TVirtualMCSensitiveDetector *GetSensitiveDetector(const TString &volName) const;
void SetExclusiveSDScoring(Bool_t exclusiveSDScoring);
o New function in TVirtualMCApplication:
void ConstructSensitiveDetectors();
- Added new TVirtualMC::NIELEdep() function
- Removed default implementation for  TVirtualMC::TrackPosition/Momentum with Float_t arguments
> VMC update: Added support for user defined sensitive detectors; plus few more features

- cmake/modules/RootConfiguration.cmake
- config/rootrc.in
- graf2d/gpadv7/v7/inc/ROOT/TVirtualCanvasPainter.hxx
- graf2d/gpadv7/v7/src/TCanvas.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- gui/webdisplay/inc/ROOT/TWebWindowsManager.hxx
- gui/webdisplay/src/TWebWindowsManager.cxx
If found, value will be used as first candidate when searching for browser on file system
Provide functionality to dump JSON file for canvas painting
Window error should be resolved by @bellenot
> webgui: try to find chrome/firefox browser during building

- tree/treeplayer/inc/ROOT/TDFNodes.hxx
This should fix failures in `test_readTotemNtuple` that started happening after the switch from `Calc` to `ProcessLine` (the access to the zero-length ReaderArrays was caught by `ProcessLine`'s instrumentation).
> [TDF] Avoid accessing zero-length TTreeReaderArray

- tree/treeplayer/inc/ROOT/TCsvDS.hxx
- tree/treeplayer/src/TCsvDS.cxx
- tree/treeplayer/test/dataframe/datasource_csv.cxx
This PR addresses https://sft.its.cern.ch/jira/browse/ROOT-9165
> [TDF] Allow TCsvDS to read input in bunches

- etc/http/changes.md
- etc/http/openui5/GuiPanelController.js
- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/view/Canvas.view.xml
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootIOEvolution.js
- etc/http/scripts/JSRootPainter.hierarchy.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.v6.js
- etc/http/scripts/JSRootPainter.v7.js
- etc/http/scripts/JSRootPainter.v7more.js
- etc/http/scripts/JSRootTree.js
Also all bugfixes from 5.4.1 are included
> jsroot with latest v7 code from 27.04

- cmake/modules/RootConfiguration.cmake
Add standard "Program Files" location on Windows to find chrome.exe and firefox.exe
> Try to Find Chrome and Firefox on Windows

- cmake/modules/SearchInstalledSoftware.cmake
> Update XRootD version to cope with new compilers (gcc 8.1)

- CMakeLists.txt
This was originally part of #1959.
> Removing spaces after -L in linker flags

- tree/tree/inc/TBranchElement.h
- tree/tree/inc/TLeaf.h
- tree/tree/inc/TLeafB.h
- tree/tree/inc/TLeafC.h
- tree/tree/inc/TLeafElement.h
- tree/tree/inc/TLeafI.h
- tree/tree/inc/TLeafL.h
- tree/tree/inc/TLeafO.h
- tree/tree/inc/TLeafS.h
- tree/tree/src/TLeafB.cxx
- tree/tree/src/TLeafC.cxx
- tree/tree/src/TLeafElement.cxx
- tree/tree/src/TLeafI.cxx
- tree/tree/src/TLeafL.cxx
- tree/tree/src/TLeafO.cxx
- tree/tree/src/TLeafS.cxx
- tree/tree/src/TTree.cxx
- tree/tree/src/TTreeCloner.cxx
i.e. allocate enough memory for the data!
> Fix ROOT-9393

- documentation/tmva/UsersGuide/TMVAdef.tex
- documentation/tmva/UsersGuide/UsingTMVAQuickStart.tex
Changes build instructions, where to get help and code examples.
> [TMVA] Doc -- Modernise Quick Start chapter

- hist/hist/src/TFormula.cxx
This PR superseedes  PR 1821. The code to check if the function is valid looking at TClass and gROOT->GetListOfGlobalFunctions is not needed.
This, as pointed in PR 1821 makes the code more efficient
> Remove check if function is valid in TFormula  

- tmva/tmva/inc/TMVA/DNN/Architectures/Cpu.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Reference.h
- tmva/tmva/inc/TMVA/DNN/DeepNet.h
- tmva/tmva/inc/TMVA/DNN/Functions.h
- tmva/tmva/inc/TMVA/DNN/RNN/RNNLayer.h
- tmva/tmva/inc/TMVA/DNN/ReshapeLayer.h
- tmva/tmva/inc/TMVA/MethodDL.h
- tmva/tmva/src/DNN/Architectures/Cpu.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/Initialization.cxx
- tmva/tmva/src/DNN/Architectures/Cuda/Initialization.cu
- tmva/tmva/src/DNN/Architectures/Reference.cxx
- tmva/tmva/src/DNN/Architectures/Reference/Initialization.cxx
- tmva/tmva/src/MethodDL.cxx
- tmva/tmva/src/MethodDNN.cxx
This PR adds several improvements and fixes to MethodDL
- Several training strategies are now supported
- Have now correct Xavier and Xavier normal (glorot) initialisation of weights
- Add option to give a seed to weight initialisation (weightInitSeed)
> Add several improvements and fixes to MethodDL

- interpreter/cling/lib/Interpreter/BackendPasses.cpp
- interpreter/cling/test/CodeGeneration/CUDACtorDtor.C
https://github.com/root-project/cling/pull/233
> cling PR 233

- core/clingutils/src/TClingUtils.cxx
> [cxxmodules] Fix failing modules master

- tree/dataframe/test/dataframe_simple.cxx
To merge in case these faliures become unbearable.
> [TDF] Temporarily disable CArraysFromTree test in dataframe_simple

- README/ReleaseNotes/v614/index.md
- added a couple of clarifications
- entries are now *roughly* ordered by importance
- added an entry on faster jitting of Filters and Defines
> [DOC] Small improvements to RDF release notes

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/test/dataframe_ranges.cxx
...with fixed namings of variables/types
This PR replaces #2062
> Reload #2062

- tree/dataframe/src/RDataFrame.cxx
The result is visible here: https://root.cern/doc/master/classROOT_1_1RDataFrame.html
> [RDF][NFC] Update cheat sheet with links to the RDFInterface methods

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
This works around an ABI compatibility issue between cling and gcc
on 32bit machines in which they disagree in the way arguments should
be passed to such a function.
> [DF] Fix 32bit failures

- tree/treeplayer/test/CMakeLists.txt
> [TREEPROCMT] Do not build test if not an imt build

- tree/tree/src/TTree.cxx
Hi, please check this makes sense :smile:
> [TREE] Only trigger parallel GetEntry if number of branches > 1

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/test/dataframe_snapshot.cxx
>  [DF] Fix Snapshot of aliased custom columns

- tree/tree/src/TBranch.cxx
> Use buf->ResetMap() only if necessary when filling branch

- tutorials/dataframe/df003_profiles.py
- tutorials/dataframe/df008_createDataSetFromScratch.py
- tutorials/dataframe/df017_vecOpsHEP.py
Lest they step on each other's feet when running all tutorials
e.g. via ctest.
> [DF] Use different filenames in python and C tutorials

- graf2d/gpad/src/TCanvas.cxx
- graf2d/graf/src/TCandle.cxx
- graf2d/graf/src/TGaxis.cxx
- graf2d/graf/src/TGraphPolargram.cxx
- graf3d/gl/src/TGLUtil.cxx
- hist/hist/src/TF1.cxx
- hist/hist/src/THStack.cxx
- hist/hist/src/TMultiGraph.cxx
- hist/histpainter/src/TGraphPainter.cxx
- hist/histpainter/src/THistPainter.cxx
- hist/histpainter/src/TPaletteAxis.cxx
Hopefully better fix for Gcc8 warnings.
> Fix gcc8 warnings (see https://sft.its.cern.ch/jira/browse/ROOT-9433)

- README/ReleaseNotes/v614/index.md
Teaching Xavi what alphabetically means
> Order contributors alphabetically

- core/textinput/src/textinput/SignalHandler.cpp
- core/textinput/src/textinput/SignalHandler.h
- core/textinput/src/textinput/Text.h
- core/textinput/src/textinput/TextInput.cpp
- core/textinput/src/textinput/TextInput.h
https://github.com/root-project/cling/pull/243
> cling PR 243

- tree/dataframe/test/CMakeLists.txt
See ROOT-9174: https://sft.its.cern.ch/jira/browse/ROOT-9174
> [DF][TOREVERT] Disable datasource_root gtest while it's being debugged

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
- tree/dataframe/test/dataframe_snapshot.cxx
Backport of @dpiparo 's fix for ROOT-9466.
> [DF] Fix ROOT-9466

- core/metacling/src/TCling.cxx
Bloom filter in header section of so files is well described by:
https://blogs.oracle.com/solaris/gnu-hash-elf-sections-v2
and
lld/ELF/SyntheticSections.cpp
The point is that the static linker puts bloom filter value to .gnu.hash section
in so files. We just have to read this value and compare to the
mangled_name hash that we're looking for. Bloom filter is a false posive
probability data structure, so it might say "yes" to library which
"doesn't" contain mangled_name, but it won't say "no" to library which
"do" contain mangled_name.
Modules W/O this patch
```
Processing tutorials/hsimple.C...
hsimple   : Real Time =   0.04 seconds Cpu Time =   0.03 seconds
(TFile *) 0x562b37a14fe0
Processing /home/yuka/CERN/ROOT/memory.C...
cpu  time = 0.362307 seconds
sys  time = 0.039741 seconds
res …
```
> [cxxmodules] Implement Bloom Filter

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDFNodes.hxx
- tree/dataframe/src/RDFNodes.cxx
- tree/dataframe/test/dataframe_snapshot.cxx
To be merged if nightlies are green tonight :)
> [DF] Fix ROOT-9471 in v6.14

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
To be merged after #2226 (the first commits belong to #2226).
> [DF] Fix ROOT-9456, "[Jenkins][DF] Sporadic failures in test_snapshotNFiles"

- core/metacling/src/TClingClassInfo.cxx
the full method was protected with the global lock. Now we split it in two parts, the first one where the cache is looked at and no state is modified with a read lock. The second, where the cache is filled and the interpreter is invoked with a write lock.
This helps considerably scaling MT workflows.
> [Core] Split critical section in TClingClassInfo::GetBaseOffset

- tree/dataframe/inc/ROOT/RDFNodes.hxx
- tree/dataframe/src/RDFNodes.cxx
- tree/dataframe/test/dataframe_nodes.cxx
This reloads #2238 fixing the TSlotStack.
> [DF] Fix slot stack

- README/ReleaseNotes/v614/index.md
- core/meta/inc/TStreamerElement.h
- io/io/inc/TStreamerInfoActions.h
- io/io/src/TStreamerInfoActions.cxx
- io/io/src/TStreamerInfoReadBuffer.cxx
- io/io/src/TStreamerInfoWriteBuffer.cxx
- tree/tree/inc/TBranchElement.h
- tree/tree/src/TBranchElement.cxx
- tree/tree/src/TTree.cxx
backport of Fix for https://github.com/cms-sw/cmssw/pull/22594
> schema evolution update for v614

- tmva/tmva/inc/TMVA/DNN/CNN/ConvLayer.h
Fixes warnings introduced at #2229
> Fix warnings introduced by #2229

- io/xml/src/TXMLEngine.cxx
Copy of https://github.com/root-project/root/pull/2280
> Xml expand 614

- geom/gdml/src/TGDMLParse.cxx
- geom/geom/src/TGeoElement.cxx
- geom/geom/src/TGeoNavigator.cxx
Fixes for ROOT-9402 and ROOT-7917 and reducing printout verbosity in the GDML parser
> Geom fixes

- io/xml/src/TXMLEngine.cxx
Copy of https://github.com/root-project/root/pull/2280
> Xml expand 612

- etc/http/changes.md
- etc/http/files/draw.htm
- etc/http/files/online.htm
- etc/http/index.htm
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootGeoPainter.js
- etc/http/scripts/JSRootIOEvolution.js
- etc/http/scripts/JSRootPainter.hierarchy.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.jquery.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.v6.js
- etc/http/scripts/JSRootPainter.v7.js
- etc/http/scripts/JSRootPainter.v7hist.js
- etc/http/scripts/JSRootPainter.v7more.js
See https://github.com/root-project/jsroot/releases/tag/5.5.0 for details
> jsroot 5.5.0

- tree/dataframe/inc/ROOT/RDataSource.hxx
Fixed doxygen list here: https://root.cern.ch/doc/master/classROOT_1_1RDF_1_1RDataSource.html
> updated doxygen list

- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/test/dataframe_interface.cxx
@etejedor @dpiparo do we agree that this is the behavior we want?
> [DF] Throw if name of defined column is not a valid C++ var name

- tmva/tmva/inc/TMVA/DNN/Architectures/Cpu.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Cuda.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Cuda/CudaMatrix.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Reference.h
- tmva/tmva/inc/TMVA/DNN/CNN/ConvLayer.h
- tmva/tmva/src/DNN/Architectures/Cpu/Arithmetic.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/Propagation.cxx
- tmva/tmva/src/DNN/Architectures/Cuda/Arithmetic.cu
- tmva/tmva/src/DNN/Architectures/Cuda/Kernels.cuh
- tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu
- tmva/tmva/test/DNN/CNN/CMakeLists.txt
- tmva/tmva/test/DNN/CNN/TestConvBackpropagationCuda.cxx
- tmva/tmva/test/DNN/CNN/TestConvLayer.h
- tmva/tmva/test/DNN/CNN/TestConvLayerCpu.cxx
- tmva/tmva/test/DNN/CNN/TestConvLayerCuda.cxx
- tmva/tmva/test/DNN/CNN/TestConvNet.h
- tmva/tmva/test/DNN/CNN/TestReshape.cxx
- tmva/tmva/test/DNN/CNN/TestReshapeCpu.cxx
- tmva/tmva/test/DNN/CNN/TestRotateWeights.cxx
- tmva/tmva/test/DNN/CNN/TestRotateWeights.h
- tmva/tmva/test/DNN/CNN/TestRotateWeightsCuda.cxx
This is a PR including a lot of work on the convolutional layer.
It can be logically divided the following parts:
1. Back propagation in CUDA (this was the most complex)
2. Forward propagation in CUDA (this was a comparatively simpler task)
3. Helper static methods such as a column based sum reduction and matrix equality checkers for every architecture.
4. An element by element detailed test case for backward and forward propagation. The one on forward propagation was designed and solved on paper. I was not able to do the same for back-propagation, instead I considered the CPU implementation to be correct and asserted that the CUDA outputs the same result.
5. Trivial bug fixes.
> Convolutional Layer in CUDA

- hist/hist/inc/LinkDef.h
- hist/hist/v7/inc/ROOT/RHist.hxx
- hist/hist/v7/inc/ROOT/RHistData.hxx
- hist/hist/v7/inc/ROOT/RHistImpl.hxx
- hist/hist/v7/inc/ROOT/RHistView.hxx
- hist/hist/v7/test/atomics.cxx
- hist/hist/v7/test/binning.cxx
- hist/histdraw/v7/inc/ROOT/RHistDrawable.hxx
- hist/histdraw/v7/test/io.cxx
Simplifies types, considerably.
> [v7hist] Make STORAGE a type template arg, remove from STAT.

- tutorials/dataframe/df022_useKahan.C
Introduced tutorial on how to create a Kahan summation, with a simple example on how it can give better results than the classical one.
This issue solves the Jira issue ROOT-9461
> [DF] [ROOT-9461] Introduced Kahan Sum as a custom action

- tree/dataframe/src/RDataFrame.cxx
@bluehood Do I understand this correctly?
> [Doc] Fix friend trees example of RDF

- geom/geom/inc/TGeoMatrix.h
- geom/geom/src/TGeoMatrix.cxx
- geom/geom/test/TestMatrix.C
Fixes thread safety issues in the matrix package. Adds consistent operators for TGeoMatrix-derived types.
> Matrix updates

- tmva/tmva/src/MethodBDT.cxx
Typo, parallel loop should have been looping over fEventSample instead of local variable eventSample.
> [TMVA] ROOT-9495 BDTG erroneous output

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/test/dataframe_interface.cxx
This is just a proposal for a simple but hopefully useful feature.
The idea is to let people check the type of a given RDF column:
```cpp
df.GetColumnType("x"); // returns e.g. "int"
```
Some usecases in which `GetColumnType` might be useful:
1. a help to use RDF in interpreted C++ (check the type of a column, then call `df.Take<T>("x")` with the right type
2. a help to write PyROOT utilities on top of RDF: often such utilities need to jit some RDF call but have no way to know what are the required template types
3. easy way to programmatically get the type of a TTree branch (`TTree::Print` is easy but does not return anything, `TLeaf::GetTypeName` is less straightforward to use correctly, e.g. if I'm not mistaken it returns `int` for an `int[n]`)
What do people think? Pinging @stwunsch …
> [DF] Add GetColumnType utility to RInterface

- tmva/tmva/src/DNN/Architectures/Cuda/Kernels.cuh
- tmva/tmva/src/DNN/Architectures/Cuda/Propagation.cu
This is achieved by parallelizing the weight update process.
This PR does not fix the code quality issues mentioned by @Axel-Naumann or the warnings, since these issues are handled by #2321
> Significantly speed-up back-propagation

- tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuMatrix.h
- tmva/tmva/inc/TMVA/DNN/Architectures/Cuda/CudaMatrix.h
- tmva/tmva/src/DNN/Architectures/Cpu/Arithmetic.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/Dropout.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/LossFunctions.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/Propagation.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/RecurrentPropagation.cxx
- tmva/tmva/src/DNN/Architectures/Cpu/Regularization.cxx
- tmva/tmva/test/DNN/CNN/TestConvNet.h
Make sure that our matrix types (CPU and GPU) use the same method name so that we can call them in a polymorphic manner from templates.
> Matrix compatibility

- tmva/tmva/src/CvSplit.cxx
The fold assignment is relying on a conversion from a double to an integer (due to using a TTreeFormula). It was previously enforced that the formula output should be "close" to an integer. The semantics are now changed to assume the output is an integer (and truncate any fractional part).
This should ensure that the valid range is increased significantly.
> [TMVA] CVSplit -- Improve fold assignment for large values

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDFNodes.hxx
- tree/dataframe/src/RDFActionHelpers.cxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/src/RDFNodes.cxx
- tree/dataframe/test/dataframe_cache.cxx
- tree/dataframe/test/dataframe_interface.cxx
- tree/dataframe/test/dataframe_nodes.cxx
- tree/dataframe/test/dataframe_regression_tests.hxx
- tree/dataframe/test/dataframe_snapshot.cxx
- tree/dataframe/test/dataframe_utils.cxx
A collection of minor fixes that I accumulated over the last month.
> [DF][Mostly NFC] Small fixes

- core/metacling/src/TCling.cxx
This is related to the fix of includeInLinkdef. Load
"./module.modulemap" if it exists. User can cd to different directory
and LoadModule loads the new modulemap.
> [cxxmodules] Load modulemap in current directory

- geom/geom/src/TGeoElement.cxx
(cherry picked from commit 4f477ee4fd4a4ee2fb2f941fd2279522dec08bb2)
> Added protection for ComputeLradTsaiFactor when Z=0

- tmva/tmva/inc/TMVA/DNN/Adagrad.h
- tmva/tmva/inc/TMVA/DNN/Functions.h
- tmva/tmva/src/MethodDL.cxx
- tmva/tmva/test/DNN/CMakeLists.txt
- tmva/tmva/test/DNN/TestMethodDLAdagradOptimizationCpu.cxx
- tmva/tmva/test/DNN/TestMethodDLOptimization.h
- tmva/tmva/test/DNN/TestOptimization.h
- tmva/tmva/test/DNN/TestOptimizationCpu.cxx
* Implement Adagrad Optimizer.
* Add Unit tests and MethodDL tests.
Reference Implementation: [Tensorflow Adagrad Optimizer](https://www.tensorflow.org/api_docs/python/tf/train/AdagradOptimizer)
> [TMVA] Add API Support for Adagrad Optimizer.

- geom/geom/inc/TGeoMatrix.h
- geom/geom/src/TGeoMatrix.cxx
- geom/geom/test/TestMatrix.C
(cherry picked from commit 9999fb552c400538d0250c436c4983cefa34f216)
> Consistency for copy constructors and assignment.

- core/base/src/TVirtualPad.cxx
- graf3d/g3d/src/X3DBuffer.c
Removing source code dependency on Graf3d for Core. Code is dead and look like not used anywhere.
> [pm] Cleaning dead code and includes

- build/unix/module.modulemap
> Adjust a modulemap file to be able to treat separate .c files

- tree/dataframe/src/RDataFrame.cxx
- tree/dataframe/test/dataframe_simple.cxx
- Introduced tests for some use case of the Display action
- Added the Display action to the documentation.
> [DF] Tests and doc for the Display action

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
- tree/dataframe/test/dataframe_simple.cxx
...and add a test for this case
> [DF] Fix ROOT-9542 "RDataFrame Sum gets confused by std::string"

- tree/dataframe/inc/ROOT/RDFInterface.hxx
Fixes ROOT-9646.
@JavierCVilla what do you think?
> [DF][NFC] Improve Cache documentation

- tree/dataframe/src/RDataFrame.cxx
- Ordered entries
- Added GetFilterNames
> [DF][Doc] Updated the doc

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/src/RooAbsArg.cxx
therewith for tens of widely used classes such as variables, constants,
distributions and combinations thereof.
For example:
```
root [1]    // Create two Gaussian PDFs g1(x,mean1,sigma) anf g2(x,mean2,sigma) and their parameters
root [2]    RooRealVar mean("mean","mean of gaussians",5,0,10) ;
root [3]    RooRealVar sigma1("sigma1","width of gaussians",0.5) ;
root [4]    RooRealVar sigma2("sigma2","width of gaussians",1) ;
root [5]    RooGaussian sig1("sig1","Signal component 1",x,mean,sigma1) ;
root [6]    RooGaussian sig2("sig2","Signal component 2",x,mean,sigma2) ;
root [7]    // Build Chebychev polynomial p.d.f.
root [8]    RooRealVar a0("a0","a0",0.5,0.,1.) ;
root [9]    RooRealVar a1("a1","a1",0.2,0.,1.) ;
root [10]    RooChebychev bkg("bkg","Background",x,RooArgSet(a0,a1)) ;
root …
```
> [RooFit] Add cling value printing for RooAbsArg

- tree/dataframe/inc/ROOT/RDFGraphUtils.hxx
- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/inc/ROOT/RDFNodes.hxx
- tree/dataframe/inc/ROOT/RResultPtr.hxx
- tree/dataframe/src/RDFGraphUtils.cxx
- tree/dataframe/src/RDataFrame.cxx
- RResultPtr now stores a raw pointer intead of a weak_ptr
- weak_ptr validity checks have been removed since RLoopManager cannot
go out of scope before these other entities
> [DF] Simplify logic now that lifetimes are simpler

- bindings/r/CMakeLists.txt
- core/base/inc/ROOT/RConfig.h
- math/rtools/CMakeLists.txt
- tmva/rmva/CMakeLists.txt
Fixes [ROOT-9620](https://sft.its.cern.ch/jira/browse/ROOT-9620).
> Fix incompatibility with R on case-insensitive file systems

- tree/tree/inc/TTree.h
- tree/tree/src/TTree.cxx
- tree/tree/test/TBranch.cxx
Per request from @pcanal, this is a backport of the fix for ROOT-9574.
> Create event cluster at flush - backport for v614

- hist/hist/src/TH1.cxx
- hist/hist/src/TPolyMarker.cxx
> Implement the saving of TPolymarker from a list of primitives in a TH1

- tutorials/CMakeLists.txt
- tutorials/roofit/rf104_classfactory.C
> [RooFit] Re-add a modified version of rf104 tutorial which works in ROOT6

- core/imt/inc/ROOT/TThreadExecutor.hxx
- core/imt/src/TThreadExecutor.cxx
- hist/hist/inc/TF1.h
- math/mathcore/test/fit/testLogLExecPolicy.cxx
- tmva/tmva/inc/TMVA/DecisionTree.h
- tmva/tmva/inc/TMVA/LossFunction.h
- tmva/tmva/inc/TMVA/MethodBDT.h
- tmva/tmva/src/DecisionTree.cxx
- tmva/tmva/src/LossFunction.cxx
- tmva/tmva/src/MethodBDT.cxx
Fixing some spotted bugs/inefficiencies in TMVA and the mathematical libraries.
> Multithreading fixes and improvements

- tree/dataframe/inc/ROOT/RNodeBase.hxx
The missing include broke modules
> [DF] Add missing include to help modules

- core/imt/inc/ROOT/TThreadExecutor.hxx
- tmva/tmva/CMakeLists.txt
- tmva/tmva/inc/TMVA/LossFunction.h
- tmva/tmva/src/LossFunction.cxx
- tutorials/tmva/TMVARegression.C
Also fix TMVA-IMT dependencies and improve some of the memory allocations in LossFunction.
> Implement built-in chunking in TThreadExecutor::Foreach and apply it in BDT-LossFunction

- tmva/tmva/test/crossvalidation/TestCrossValidationMultiProc.cxx
Ensures that data is actually read from the TTree. Silly mistake that is consisted with the problems we've seen.
> [TMVA] CrossValidation multiproc fix

- core/base/src/TApplication.cxx
- core/rint/src/TRint.cxx
**Changes:** 
Added feature to get root version using (root --version) command.
**Screenshot:**
> Added root --version feature

- hist/hist/src/TFormula.cxx
This is a better version that #2622 which removes entirely the need to use new and delete...
> [Math] Remove memory leaks in TFormula using variables on the stack

- core/metacling/src/TCling.cxx
- core/metacling/test/TClingTests.cxx
- interpreter/cling/include/cling/Utils/AST.h
- interpreter/cling/lib/Utils/AST.cpp
- interpreter/cling/test/Lookup/tag.C
and put it to a good use in Cling
> [Cling] ROOT-6967 Add direct way too lookup tags and put it to a good use in TCling

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/src/RDFHistoModels.cxx
- tree/dataframe/test/dataframe_histomodels.cxx
thanks to daniel savoiu for the report and suggested fix: https://root-forum.cern.ch/t/custom-binning-with-tprofile1dmodel/30780
> [DF] ROOT-9476 Fix treatment of custom x axis of profile 1d models

- graf2d/gpadv7/v7/src/RVirtualCanvasPainter.cxx
(cherry picked from commit 9482a9e0e4459e783700cb916e77248fa373e41b)
> [gpadv7] Only load pointer lib once.

- interpreter/cling/lib/Utils/PlatformWin.cpp
Visual Studio 2017 doesn't use the registry anymore, so no need to try to find keys. This prevent picking wrong directories in the case there is another version installed on the computer, and prevent also the following errors when starting ROOT:
RegQueryValueEx: returned 2: The system cannot find the file specified.
RegOpenKeyEx: returned 2: The system cannot find the file specified.
> Fix lookup of Visual Studio directories + improve error messages

- interpreter/cling/lib/Utils/PlatformPosix.cpp
With 16 threads, the cache is simply too small.
These are thread specific values anyway.
> [cling] Use TLS for pointer check cache:

- tree/dataframe/inc/ROOT/RDFInterface.hxx
- tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDFUtils.hxx
> [DF][NFC] Improve doc of RDFInterface, e.g. describing return values

- tree/tree/inc/TBranchElement.h
- tree/tree/src/TBranchElement.cxx
This solves the 2nd schema evolution problem seen at https://github.com/cms-sw/cmssw/pull/22594#issuecomment-422105335.
> Rule scheduling

- core/thread/inc/ROOT/TThreadedObject.hxx
if the size is bigger than the default value. Document better the behaviour, too.
> [Core] ROOT-9696 adjust size of TThreadedObjects automatically to IMT pool size

- interpreter/cling/tools/plugins/clad/CMakeLists.txt
The new release includes some improvements in both Forward and
Reverse mode:
* Better correctness of C++ constructs -- handle scopes properly; allow proper
variable shadowing; and preserve namespaces.
* Efficient evaluation in forward mode.
* Reduced cloning complexity.
* Handle more C++ constructs -- variable reassignments and for loops.
See more at: https://github.com/vgvassilev/clad/blob/v0.3/docs/ReleaseNotes.md
> [clad] Bump clad version to v0.3.

- tree/dataframe/inc/ROOT/RDFActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDFInterfaceUtils.hxx
and use a simple vector of pointers.
> [DF] Remove usage of TThreadedObject

- interpreter/cling/tools/plugins/clad/CMakeLists.txt
> [clad] Also update the version on unix.

- math/mathcore/test/fit/testBinnedFitExecPolicy.cxx
- math/mathcore/test/fit/testLogLExecPolicy.cxx
> Apply clang-tidy changes to the vectorized fitting tests

- tree/treeplayer/inc/TTreeReaderArray.h
- tree/treeplayer/inc/TTreeReaderValue.h
- tree/treeplayer/src/TTreeReaderArray.cxx
- tree/treeplayer/test/array.cxx
> [TTreeReader] Fix ROOT-9570 Allow TTreeReaderArray to read vector of booleans

- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RActionBase.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
- tree/dataframe/src/RActionBase.cxx
- tree/dataframe/src/RJittedAction.cxx
To be merged after #2709 (depends on it).
Only the last 5 commits of this PR are new, the rest are already present in #2709 .
This resolves ROOT-9468 ("[DF] Jitting of large Snapshots is too slow").
> [DF] Faster Snapshot compiletimes

- tree/treeplayer/src/TTreeReaderArray.cxx
- tree/treeplayer/test/array.cxx
...and add a test for the broken case
> [TreePlayer] Fix `TTreeReaderArray::GetSize`

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
- tree/dataframe/test/dataframe_snapshot.cxx
- tree/dataframe/test/dataframe_vecops.cxx
Fixes at least the reading part of [ROOT-9666](https://sft.its.cern.ch/jira/browse/ROOT-9666).
> [DF] Fix handling of vector<bool>

- core/base/inc/TCanvasImp.h
- graf2d/gpad/src/TCanvas.cxx
Use such flag in TCanvas::Paint(), preventing direct X11 calls for web canvas
> [TCanvas] Add flag to TCanvasImp indicating web output

- net/http/src/THttpServer.cxx
- tutorials/http/custom.htm
It always returns default JSROOT web page disregard of custom settings
Requested here https://root-forum.cern.ch/t/31086
>  http: implement default.htm request in THttpServer 

- interpreter/cling/test/Interfaces/print.C
> Fix print.C

- etc/http/scripts/JSRootCore.js
This should be done every time JSROOT copied into ROOT
> jsroot: enable local openui

- tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
- tree/treeplayer/src/TTreeProcessorMT.cxx
- tree/treeplayer/test/CMakeLists.txt
- tree/treeplayer/test/treeprocmt/treeprocessormt.cxx
> [TTreeProcessorMT][ROOT-9563]

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/histfactory/src/Measurement.cxx
- roofit/roofitcore/inc/RooWorkspace.h
- roofit/roofitcore/src/RooWorkspace.cxx
- roofit/roostats/src/AsymptoticCalculator.cxx
Fix memory leaks in HistFactory.
> [roofit/hf] [ROOT-5236] Memory leaks in HistFactory

- tree/treeplayer/test/RErrorIgnoreRAII.hxx
- tree/treeplayer/test/basic.cxx
- tree/treeplayer/test/leafs.cxx
> [TreePlayer][ROOT-9713] Remove printing of error messages 

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/histfactory/src/Measurement.cxx
- roofit/roofitcore/inc/RooWorkspace.h
- roofit/roofitcore/src/RooWorkspace.cxx
- roofit/roostats/src/AsymptoticCalculator.cxx
(cherry picked from commit 09f1082)
> [ROOT-5236] Memory leaks in HistFactory

- etc/http/changes.md
- etc/http/openui5/controller/Canvas.controller.js
- etc/http/openui5/view/Canvas.view.xml
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.v6.js
- etc/http/scripts/JSRootPainter.v7.js
- graf2d/gpad/src/TCanvas.cxx
- gui/webgui6/src/TWebCanvas.cxx
* Remove/hide unused items
* Provide commands to save ROOT, PS, C files
* Allow to perform TPad::Paint() for the case when TVirtualPS is used
* Include preliminary JSROOT 5.6.0 with bugfixes
> Improve menu in TWebCanvas

- math/mathcore/src/PdfFuncMathCore.cxx
This is part of PR #2820. Fixes Windows!
> Remove the definitions of inline funcs.

- math/mathcore/inc/Math/PdfFuncMathCore.h
- math/mathcore/src/PdfFuncMathCore.cxx
> Inline crystalball

- core/base/src/TROOT.cxx
- core/metacling/src/TCling.cxx
- interpreter/cling/lib/Interpreter/CIFactory.cpp
This feature can be enabled by setting an env variable ROOT_CLING_TIMING.
It prints some information about how much time different parts of clang
take.
Example use:
```
ROOT_CLING_TIMING=1 root.exe -l -b -q tutorials/hsimple.C  
Processing tutorials/hsimple.C...
hsimple   : Real Time =   0.12 seconds Cpu Time =   0.12 seconds
(TFile *) 0x37430c0
===-------------------------------------------------------------------------===
Clang front-end time report
===-------------------------------------------------------------------------===
Total Execution Time: 3.0650 seconds (3.0786 wall clock)
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
2.1559 ( 72.3%)   0.0469 ( 55.7%)   2.2028 ( 71.9%)   2.2163 ( 72.0%)  Reading modules
0.6367 ( 21.4%)   0.0087 ( 10.4%) …
```
> [cxxmodules] [cling] Enable timing counters in clang's frontend.

- tutorials/CMakeLists.txt
Fixes some of the test failures of the nightlies.
> [Tutorial] Veto df103 if xrootd not enabled

- graf2d/cocoa/CMakeLists.txt
- net/krb5auth/src/TKSocket.cxx
> Mac1014warnings v6 14

- tmva/tmva/src/DNN/Architectures/Cpu/ActivationFunctions.cxx
- tmva/tmva/test/DNN/TestActivationFunctions.cxx
- tmva/tmva/test/DNN/TestActivationFunctionsCpu.cxx
- tmva/tmva/test/DNN/TestDerivatives.h
- tmva/tmva/test/DNN/TestDerivativesCpu.cxx
When VDT is available use for the CPU implementation the fast implementation of tanh
> Use in the Deep Learning the Fast implementation of Tanh from VDT

- tree/dataframe/inc/ROOT/RDF/RCustomColumnBase.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/inc/ROOT/RDF/Utils.hxx
- tree/dataframe/src/RCustomColumnBase.cxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/src/RDFUtils.cxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_simple.cxx
- tree/dataframe/test/dataframe_utils.cxx
>  [DF][ROOT-9754] Allow definition of jitted custom columns with same name 

- tmva/tmva/inc/TMVA/MethodDL.h
- tmva/tmva/src/MethodDL.cxx
- tmva/tmva/test/DNN/CMakeLists.txt
- tmva/tmva/test/DNN/TestRegressionMethodDL.cxx
This PR replaces #2278 from the GSOC student Sidharta and provides the regression support (including a test) for MethodDL. 
The test has been improved to check the obtained deviations.
> Add regression support for MethodDL  (new PR replacing #2278)

- tmva/tmva/inc/TMVA/CrossValidation.h
- tmva/tmva/src/CrossValidation.cxx
- tutorials/tmva/TMVACrossValidation.C
Adds drawing possibilities for average ROC curves with cross validation.
This integrates the work of @mohammaduzair9. Superseeds PR #2454.
> [TMVA] CV Avg ROC

- README/ReleaseNotes/v616/index.md
- etc/http/changes.md
- etc/http/scripts/JSRoot3DPainter.js
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.more.js
- etc/http/scripts/JSRootPainter.v6.js
- gui/webgui6/inc/TWebSnapshot.h
- gui/webgui6/src/TWebCanvas.cxx
- gui/webgui6/src/TWebSnapshot.cxx
Create TView3D only when not exists in the pad
Scan and create custom colors list after objects painting done
Configure webwindow geometry before showing canvas
Few small fixes on JSROOT side
> TWebCanvas: several fixes for custom object painters

- io/io/inc/TStreamerInfoActions.h
- io/io/src/TStreamerInfoActions.cxx
- tree/tree/inc/TBranchElement.h
- tree/tree/src/TBranchElement.cxx
> Fix for schema evolution

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
following https://root-forum.cern.ch/t/rvec-argsort-issues/31442/5
> [DF][NFC] Improve Take doc, including example usage snippet

- tree/treeplayer/src/TTreeReaderValue.cxx
- When a leaf name contains the name of its parent branch on it and a
branch with the desired name has already been found, the priority
given by SearchBranchWithCompositeName should not be considered.
- Test added in [#250](https://github.com/root-project/roottest/pull/250)
> [TTreeReader][ROOT-9757] Return the correct branch

- roofit/roofitcore/src/MemPoolForRooSets.h
> Fix RooArgSets for windows.

- README/ReleaseNotes/v616/index.md
Should we mention @stwunsch 's nanoaod tutorials? Are we missing anything else?
> [DOC] Update release notes for RDF+TTreeProcessorMT

- math/mathcore/src/AdaptiveIntegratorMultiDim.cxx
This fixes a compilation problem observed on mac 10.14
> Use in Mathcore macros defined in Math/Error.h for reporting error

- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.js
- etc/http/scripts/JSRootPainter.v6.js
- etc/http/scripts/JSRootPainter.v7.js
Provide methods to check if sending via websocket is possible
Fix - correctly handle negative parameter values in TF1/TF2
Fix - clear range flag when drawings are cleared
Fix - do not forget reset pads cache when changing TWebCanvas
> jsroot: several fixes from dev

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/test/dataframe_simple.cxx
> [DF] Set axes titles of histos and graphs obtained w/o models

- README/ReleaseNotes/v614/index.md
- cmake/modules/SearchInstalledSoftware.cmake
- core/imt/src/TThreadExecutor.cxx
- tree/dataframe/test/CMakeLists.txt
- tree/dataframe/test/dataframe_concurrency.cxx
- Upgrade builtin tbb to 2019 and require at least 2018
- Isolate work in TThreadedExecutor
- Add test for concurrency in RDF
> Remove reentrancy 

- etc/http/changes.md
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootPainter.hist.js
- etc/http/scripts/JSRootPainter.hist3d.js
- etc/http/scripts/JSRootPainter.openui5.js
- etc/http/scripts/JSRootPainter.v6.js
- etc/http/scripts/JSRootPainter.v7.js
Dedicated branch now created in JSROOT repository
Same code will be submitted in v6-16-00-patches branch
> jsroot: for ROOT 6.16

- io/io/src/TStreamerInfo.cxx
- tree/tree/inc/TTreeCache.h
- tree/tree/src/TTreeCache.cxx
backport to v6-14 of:
https://github.com/root-project/root/pull/2960
https://github.com/root-project/root/pull/2959
> V614 catchup

- tree/dataframe/inc/ROOT/RDF/RBookedCustomColumns.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFBookedCustomColumns.cxx
- tree/dataframe/test/CMakeLists.txt
- tree/dataframe/test/dataframe_colnames.cxx
this feature has been suggested by the ATLAS H->gamma gamma folks.
> [DF][ROOT-9792] Hascolumn feature

- cmake/modules/RootConfiguration.cmake
- config/root-config.in
unless we are not on osx and gcc the gcc major is 4.
> [CMake][ROOT-9637] Adopt c++14 flag in root-config

- tree/tree/inc/TChain.h
- tree/tree/src/TChain.cxx
- tree/tree/test/CMakeLists.txt
- tree/tree/test/TChainSaveAsCxx.cxx
Definition of TChain composed of ROOT files with TTrees is stored to C++ macro file together with friend TChain's.
> TChain::SavePrimitive() implemented.

- tree/dataframe/inc/ROOT/RDFHelpers.hxx
- tree/dataframe/test/dataframe_helpers.cxx
Simplify test code as a consequence, add a test.
> [DF] Let SaveGraph return a string rather than print to stdout

- README/CREDITS
- README/README.CXXMODULES.md
- README/ReleaseNotes/v616/index.md
> Update release notes

- tree/dataframe/src/RLoopManager.cxx
- tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
> Remove workaorounds for spurious TTreeReader warnings

- README/ReleaseNotes/v616/index.md
- tree/dataframe/src/RDataFrame.cxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_regression_tests.hxx
> [DF] Fix entry numbers in MT runs

- bindings/pyroot/src/PyRootType.cxx
Backport of https://github.com/root-project/root/pull/3055
> [ROOT-9836] Include templated function in list of overloads (backport to 6.16)

- bindings/pyroot_experimental/cppyy/CMakeLists.txt
- builtins/openssl/CMakeLists.txt
- core/base/src/TROOT.cxx
- core/base/src/TVirtualGL.cxx
- core/clingutils/res/TClingUtils.h
- graf3d/gl/src/TGLFaceSet.cxx
- net/auth/src/TAuthenticate.cxx
- net/net/src/TSecContext.cxx
Note that some commits are fixed up, so correspondence with master is not 1 to 1.
> Backport warning fixes

- cmake/modules/RootBuildOptions.cmake
- cmake/modules/SearchInstalledSoftware.cmake
Will be merged into v6-16, too.
@gganis FYI re LCG releases - please make sure we don't have mismatched expectations here :-)
> V618 deprecation

- bindings/pyroot/src/TMemoryRegulator.cxx
Backport of https://github.com/root-project/root/pull/3111
> [ROOT-9809] Only invoke Python C API if Python is initialized (backport to 6.16)

- bindings/pyroot/src/TMemoryRegulator.cxx
> [ROOT-9809] Only invoke Python C API if Python is initialized (backport to 6.14)

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- IsImplicitMTEnabled
- EnableImplicitMT
- DisableImplicitMT
> [DF] Add fwd decls of critical routines in RInterface

- core/base/src/TSystem.cxx
- core/meta/src/TClass.cxx
- io/io/src/TStreamerInfo.cxx
warnings fixes and fix for ROOT-9784.
> backport to v6.16

- tutorials/demos.C
Fixed Issue #9764
**Before:**
**After:**
> Fixed demos.C redefinition error of dirName

- bindings/pyroot/src/Pythonize.cxx
- bindings/pyroot/test/pretty_printing.py
- bindings/pyroot_experimental/PyROOT/src/GenericPyz.cxx
- bindings/pyroot_experimental/PyROOT/test/pretty_printing.py
- tutorials/pyroot/pyroot003_prettyPrinting.py
> [ROOT-9859] Fall-back to __repr__ in __str__ if cling returns an address (backport 6.16)

- etc/eve7/GL.controller.js
Only when scene has all necessary data make geometry draw
> eve7: fix in GL view update

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/test/dataframe_snapshot.cxx
> [DF][ROOT-9860][ROOT-9865] Fix

- tree/tree/inc/TTreeCacheUnzip.h
- tree/tree/src/TTreeCacheUnzip.cxx
the documentation was outdated, the implementation was sligthly
modernised.
> [TTreeCacheUnzip] Improve documentation and implementation

- bindings/pyroot/src/RootWrapper.cxx
- bindings/pyroot/src/Utility.cxx
This PR fixes the Python3.7-related issues in PyROOT described at:
https://sft.its.cern.ch/jira/browse/ROOT-9871
https://sft.its.cern.ch/jira/browse/ROOT-9880
> [ROOT-9871] [ROOT-9880] Fixes for Python3.7

- bindings/pyroot/src/RootWrapper.cxx
- bindings/pyroot/src/Utility.cxx
This is a backport of https://github.com/root-project/root/pull/3195
> Python3.7 fixes (6.16 backport)

- bindings/pyroot/JupyROOT/__init__.py
- bindings/pyroot/JupyROOT/helpers/cppcompleter.py
- bindings/pyroot/JupyROOT/helpers/handlers.py
- bindings/pyroot/JupyROOT/helpers/utils.py
- bindings/pyroot/JupyROOT/kernel/magics/jsrootmagic.py
- bindings/pyroot/JupyROOT/kernel/rootkernel.py
- bindings/pyroot/JupyROOT/kernel/utils.py
- bindings/pyroot/JupyROOT/magics/cppmagic.py
- bindings/pyroot/JupyROOT/magics/jsrootmagic.py
Backport of https://github.com/root-project/root/pull/3204
> [PyROOT] Prevent module confusion when running doctest tests (backport 6.16)

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/test/dataframe_take.cxx
See here: https://cdash.cern.ch/viewBuildError.php?type=1&buildid=604376
> [RDF] Fix build warnings introduced in TakeHelper

- interpreter/cling/lib/Interpreter/BackendPasses.cpp
- interpreter/cling/lib/Interpreter/CIFactory.cpp
With `#pragma cling optimize (3)`:
```
$ root.exe -l -b -q enrico_clingopt.C
Processing enrico_clingopt.C...
1.13e-07
(int) 0
```
And `#pragma cling optimize (0)`:
```
$ root.exe -l -b -q enrico_clingopt.C
Processing enrico_clingopt.C...
2.15174
(int) 0
```
> Cling no noopt

- hist/hist/inc/TKDE.h
- hist/hist/src/TKDE.cxx
- hist/hist/test/CMakeLists.txt
- hist/hist/test/test_tkde.cxx
This PR allows the writing and reading from a file of a TKDE. 
It contains also a bug fix in  TKDE::SetNBins
> Provide I/O support for TKDE class

- etc/eve7/EveElements.js
- etc/eve7/GL.controller.js
- etc/eve7/GeomViewer.controller.js
- etc/http/scripts/JSRootCore.js
- etc/http/scripts/JSRootGeoBase.js
- etc/http/scripts/JSRootGeoPainter.js
- graf3d/eve7/inc/ROOT/REveGeomViewer.hxx
- graf3d/eve7/src/REveGeoPolyShape.cxx
- graf3d/eve7/src/REveGeomData.cxx
- graf3d/eve7/src/REveGeomViewer.cxx
- graf3d/eve7/src/REveGluTess.cxx
- graf3d/eve7/src/REveTrack.cxx
- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- gui/webdisplay/src/RWebDisplayArgs.cxx
- tutorials/eve7/geodemo.C
1. Fix error with normals production for TGeo shapes
2. Catch exception in GluTess code
3. Support TGeoNode with finders
4. Provide geodemo.C macro with all supported shapes
> Bugfixes in web geometry viewer

- documentation/users-guide/InputOutput.md
Copied over the correct info from TFile.cxx.
> Fix documentation error (Bytecount in RootFile layout)

- core/metacling/src/TClingBaseClassInfo.cxx
This fixes the errors in #3222. Patch by Oksana and me!
> [RM] Add a RAII to TClingBaseClassInfo

- tutorials/CMakeLists.txt
To address:
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/12/
> [Exp PyROOT] Another round of test disabling for experimental PyROOT builds

- core/base/inc/LinkDef2.h
- core/base/inc/TNotifyLink.h
- tree/tree/src/TTree.cxx
- tree/treeplayer/inc/LinkDef.h
- tree/treeplayer/inc/TBranchProxy.h
- tree/treeplayer/inc/TBranchProxyDirector.h
- tree/treeplayer/inc/TFriendProxy.h
- tree/treeplayer/inc/TTreeReader.h
- tree/treeplayer/inc/TTreeReaderUtils.h
- tree/treeplayer/inc/TTreeReaderValue.h
- tree/treeplayer/src/TBranchProxy.cxx
- tree/treeplayer/src/TBranchProxyDirector.cxx
- tree/treeplayer/src/TTreeReader.cxx
- tree/treeplayer/src/TTreeReaderArray.cxx
- tree/treeplayer/src/TTreeReaderValue.cxx
This is PR #3216 minus the unrelated (and not applicable) 44c484facf43bbc19a5733ddd48721ba477037bf
> TTreeReader speed v6.16

- bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_tcollection.py
- bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_titer.py
Small fixes proposed for changes in #3298
> [Exp PyROOT] Follow up of #3298

- core/base/inc/Rtypes.h
- core/base/src/TApplication.cxx
- core/base/src/TPluginManager.cxx
- core/base/src/TUrl.cxx
- core/clingutils/src/TClingUtils.cxx
- core/meta/src/TDataMember.cxx
- core/meta/src/TMethod.cxx
- hist/hist/src/TGraph.cxx
- hist/hist/src/TGraph2D.cxx
- hist/hist/src/TGraphAsymmErrors.cxx
- hist/hist/src/TGraphErrors.cxx
- roofit/roofitcore/src/RooCustomizer.cxx
- roofit/roofitcore/src/RooFactoryWSTool.cxx
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/src/RooSimPdfBuilder.cxx
and protect the TUrl class from races.
> [MT][ROOT-9901] Replace usage of strtok in core and hist

- etc/http/scripts/JSRootGeoBase.js
- etc/http/scripts/JSRootGeoPainter.js
- graf3d/eve7/src/REveGluTess.cxx
Minimal bugfixes for eve7 v6.16
> Eve7 fixes for v6-16 branch

- tree/dataframe/inc/ROOT/RDF/RAction.hxx
- tree/dataframe/inc/ROOT/RDF/RActionBase.hxx
- tree/dataframe/inc/ROOT/RDF/RFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedAction.hxx
- tree/dataframe/inc/ROOT/RDF/RJittedFilter.hxx
- tree/dataframe/inc/ROOT/RDF/RRange.hxx
- tree/dataframe/src/RActionBase.cxx
- tree/dataframe/src/RFilterBase.cxx
- tree/dataframe/src/RRangeBase.cxx
> [RDF] Fix ROOT-9898

- io/io/inc/TMemFile.h
- io/io/src/TMemFile.cxx
and adapt the size of the block for TBufferMergerFile
> [IO][ROOT-6145] Allow user to set the size of the memory block of TMemFiles

- tutorials/CMakeLists.txt
- tutorials/roofit/rf502_wspacewrite.py
Part of the ongoing campaign to turn the experimental PyROOT builds green.
> [Exp PyROOT] Re-enable tutorials, fix test

- roofit/histfactory/inc/RooStats/HistFactory/MakeModelAndMeasurementsFast.h
- roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
- roofit/histfactory/src/hist2workspace.cxx
- roofit/roofit/inc/RooPolynomial.h
- roofit/roofit/src/RooPolynomial.cxx
- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/src/RooHistFunc.cxx
- roofit/roofitcore/src/RooRealSumPdf.cxx
Fix doxygen problems / extend docstrings in
- RooPolynomial
- HistFactory
- RooAbsReal
- RooRealSumPdf
> [RF] Improve documentation of RooFit

- core/base/src/TApplication.cxx
https://sft.its.cern.ch/jira/browse/ROOT-9927
> webgui: allow --web also when ROOTWebDisplay library already load, ROOT-9927

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/test/dataframe_interface.cxx
and a test.
This PR includes also #3363 just to avoid conflicts
> [DF][ROOT-9933] Add GetNSlots method to RInterface

- roofit/roofitcore/src/RooWorkspace.cxx
https://root-forum.cern.ch/t/rooworkspace-import-roofit-silence-does-not-work-when-importing-datasets/32591
> [RF] Silence importing datasets to RooWorkspace.

- tmva/tmva/src/MethodBDT.cxx
- tmva/tmva/src/MethodBase.cxx
Standalone C++ class generation was not implemented for multiclass BDTG. This change uses the logic of TMVA::MethodBDT::GetMulticlassValues() and uses it in a new function ReadBDTG::GetMulticlassValues() when the multiclass training is used.
Tested on multiclass BDTG and binary BDTG training, in both cases a compiling and functioning standalone class is generated.
> Implement standalone class generation for multiclass BDTG

- tmva/tmva/inc/TMVA/DataLoader.h
- tmva/tmva/inc/TMVA/Envelope.h
- tmva/tmva/src/DataLoader.cxx
- tmva/tmva/src/Factory.cxx
The DataLoader had a number of extraneous includes and friends. Removing them also reduces compilation time!
> [TMVA] Dataloader includes spring cleaning

- bindings/pyroot_experimental/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
https://github.com/root-project/root/pull/3386 reloaded.
This intends to fix PyROOT experimental until https://bitbucket.org/wlav/cppyy-backend/pull-requests/17/remove-special-handling-for-ginterpreter is merged and ROOT's copy of Cppyy is updated with a future release.
> [Exp PyROOT] Remove special handling of gInterpreter in pyroot_experimental

- README/ReleaseNotes/v618/index.md
- hist/histpainter/inc/Hoption.h
- hist/histpainter/src/THistPainter.cxx
- hist/histpainter/src/TPainter3dAlgorithms.cxx
Equivalent to the gStyle->SetHistMinimumZero(), but can be specified individually.
Resolves https://sft.its.cern.ch/jira/browse/ROOT-8446
> ROOT-8446 - introduce min0 draw option for TH1/TH2 histograms

- tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
- tree/dataframe/test/dataframe_simple.cxx
> [DF] Let Filter accept return values convertible to bool

- core/metacling/src/TCling.cxx
The OSX linker stores the symbols in a shared library by adding an
extra "_" as prefix to the mangled name. However, the llvm JIT gives
us a unix mangled name.
This patch adds a the missing extra prefix if we are on OSX.
> [cxxmodules] Implement autoloading support for OSX.

- bindings/pyroot_experimental/PyROOT/CMakeLists.txt
- bindings/pyroot_experimental/PyROOT/python/ROOT/pythonization/_tclass.py
- bindings/pyroot_experimental/PyROOT/src/PyROOTModule.cxx
- bindings/pyroot_experimental/PyROOT/src/PyROOTPythonize.h
- bindings/pyroot_experimental/PyROOT/src/TClassPyz.cxx
- bindings/pyroot_experimental/PyROOT/test/CMakeLists.txt
- bindings/pyroot_experimental/PyROOT/test/tclass_dynamiccast.py
This PR adds a pythonisation for {{TClass::DynamicCast}}:
https://sft.its.cern.ch/jira/browse/ROOT-9973
> [Exp PyROOT] Pythonisations for TClass

- README/ReleaseNotes/v618/index.md
Hi, please check I have not forgotten anything :)
> [DOC][skip ci] Update RDF release notes

- etc/eve7/EveManager.js
- etc/eve7/EveScene.js
- etc/eve7/EveTable.controller.js
- etc/eve7/EveTable.view.xml
- graf3d/eve7/inc/ROOT/REveTableProxyBuilder.hxx
- graf3d/eve7/src/REveDataClasses.cxx
- graf3d/eve7/src/REveDataProxyBuilderBase.cxx
- graf3d/eve7/src/REveTableInfo.cxx
- graf3d/eve7/src/REveTableProxyBuilder.cxx
- tutorials/eve7/collection_proxies.C
…collection filtering and event loops.
> Add possibility to set collection in the table views

- graf3d/eve7/src/REveSelection.cxx
Bugfix - was causing segvs when deleting selected objects.
> [REve] Fix removal of objects from selection.

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
- roofit/roofitcore/inc/RooProdPdf.h
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roostats/src/AsymptoticCalculator.cxx
[ROOT-5236] The RooProdPdf was leaking memory when caching values.
> [RF] RooProdPdf leaks memory

- roofit/histfactory/src/FlexibleInterpVar.cxx
- roofit/roofit/src/RooKeysPdf.cxx
- roofit/roofit/src/RooPoisson.cxx
- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooCachedPdf.cxx
- roofit/roofitcore/src/RooCurve.cxx
- roofit/roofitcore/src/RooExtendPdf.cxx
- roofit/roofitcore/src/RooGenProdProj.cxx
- roofit/roofitcore/src/RooNLLVar.cxx
- roofit/roofitcore/src/RooProdPdf.cxx
- roofit/roofitcore/src/RooSimultaneous.cxx
- roofit/roofitcore/src/RooWorkspace.cxx
- tutorials/roofit/rf205_compplot.C
Collection of various documentation updates/fixes.
> [RF] Improve RooFit documentation.

- README/ReleaseNotes/v618/index.md
Done like requested in [PR 2751](https://github.com/root-project/root/pull/2751#issuecomment-472801594)
> Release Notes for changes in TNetXNGFile

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
> [DF] Fix custom actions depending on RDF+RDataSource

- build/unix/stl.modulemap
Added some stl headers to stl.modulemap
> Added some STL headers to stl.modulemap

- tutorials/spectrum/Background_width2.C
> Fixes typo in TSpectrum tutorials

- hist/hist/inc/TH2Poly.h
- hist/hist/src/TH1.cxx
- hist/hist/src/TH2Poly.cxx
- hist/hist/test/CMakeLists.txt
- hist/hist/test/test_TH2Poly_BinError.cxx
This fixes ROOT-7608.
Move to protected also the functions of TH1 that do not make sense for TH2Poly.
Add a test for getting/setting the bin error
> Fix a bug in TH2Poly::GetBinError() and add an implementation of TH2Poly::SetBinError. 

- bindings/pyroot_experimental/cppyy/cppyy-backend/cling/python/cppyy_backend/loader.py
This is a cherry pick of the `loader.py` in cppyy-backend version clingwrapper-1.7.2, which has the new treatment of `CLING_STANDARD_PCH` and its setting to `'none'` to prevent the PCH check by Cppyy. It should fix the new test failures that appeared last night in the experimental PyROOT builds.
https://epsft-jenkins.cern.ch/job/root-exp-pyroot/76/
A complete update will come for the three packages of Cppyy once the functionality of this PR:
https://github.com/root-project/root/pull/3579
is merged into `TCling`.
> [Exp PyROOT] Update loader with new use of CLING_STANDARD_PCH

- .mailmap
Hi,
Hope everyone is doing well. I noticed my mail address_es_, nicknames and full names in this file and I want it removed since. I noticed it on Google after I looked up my mail address there. Idk if this PR will make it go away completely from GitHub but I guess it proves the point I am trying to make. 
Thanks!
PS: How is GDPR going?
> Removing mail address

- tree/dataframe/src/RDataFrame.cxx
- tree/dataframe/test/dataframe_entrylist.cxx
- tree/dataframe/test/dataframe_friends.cxx
- tree/dataframe/test/dataframe_simple.cxx
- tree/dataframe/test/dataframe_snapshot.cxx
- tree/dataframe/test/dataframe_vecops.cxx
...wherever it's more readable, less error-prone than the alternatives.
> [DF] Use the new template TFile::Get overload

- tutorials/dataframe/df007_snapshot.C
- tutorials/multicore/imt001_parBranchProcessing.C
- tutorials/multicore/mp103_processSelector.C
- tutorials/multicore/mt102_readNtuplesFillHistosAndFit.C
in order to make of this code the most up-to-date set of examples possible.
> [Tutorials] Use in RDF/Multicore tutorials the new TFile::Get<T> method

- tree/treeplayer/src/TTreeReaderGenerator.cxx
See  http://root-forum.cern.ch/t/tselector-ttreereader-and-fchain-setentry/30170/1
and http://root-forum.cern.ch/t/problem-with-multiple-files-in-tchain-with-makeselector-class/32534/7
> Fix TTreeReader's use of Set[Local]Entry

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooAbsTestStatistic.cxx
- roofit/roofitcore/src/RooChi2Var.cxx
- roofit/roofitcore/src/RooCustomizer.cxx
- roofit/roofitcore/src/RooFFTConvPdf.cxx
- roofit/roofitcore/src/RooLinearVar.cxx
Add pending updates of the RooFit documentation such as fixing typos, adding clarifications and pulling comments outside of functions such that doxygen can find them.
Meant to be an NFC, but run CI to be sure.
> [RF] Documentation updates.

- tutorials/CMakeLists.txt
- tutorials/dataframe/df014_CSVDataSource.C
- tutorials/dataframe/df014_CSVDataSource.py
- tutorials/dataframe/df015_LazyDataSource.C
therewith making them standalone.
> [Tutorials] CsvDS: download csv in the macro and not in CMake

- interpreter/cling/lib/Interpreter/LookupHelper.cpp
This prevents the vector to be reallocated if the size exceeds the capacity of
the vector causing invalid pointer accesses.
Fixes ROOT-7749.
> [cling] Resize the memory cache before entering the loop.

- README/README.CXXMODULES.md
- interpreter/cling/README.md
@Axel-Naumann maybe we should put the cling reference on the main ROOT readme page as well...
> Citing Cling and C++Modules

- interpreter/cling/tools/packaging/cpt.py
Signed-off-by: Vassil Vassilev <v.g.vassilev@gmail.com>
> Add non-interactive mode to cpt

- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomData.cxx
- graf3d/eve7/src/REveGeomViewer.cxx
- gui/canvaspainter/v7/src/TCanvasPainter.cxx
- gui/webdisplay/src/RWebWindowsManager.cxx
Very useful for debugging of dump data, 
used in v7 canvas painter and geometry viewer
> WebUI: let configure JSON compression for transferred data

- cmake/modules/RootBuildOptions.cmake
I also adjusted indentation in if-else statement.
> [NFC] Clarification of error message in case of root7 option

- montecarlo/vmc/README.md
- montecarlo/vmc/README.multiple.md
Moved README.md added with Multiple Engines development in README.multiple.md and added a new README.md (Md version of the Drupal VMC main page)
> Updated documentation in vmc:

- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_simple.cxx
rather than waiting for the jitting to fail.
> [RDF][ROOT-9984] Throw early if file in chain does not exist

- README/ReleaseNotes/v618/index.md
- core/base/src/TSystem.cxx
- core/metacling/src/TCling.cxx
- test/stressTMVA.cxx
This patch actually loads the modulemap as previously it wrongly detected
it was already loaded.
> [cxxmodules] Rework the loading of the modulemap in the working dir.

- bindings/pyroot_experimental/cppyy/CPyCppyy/src/Executors.cxx
The fix is taken from the official CPyCppyy repository (commit 590cc73).
Opened this PR in favor of #3710.
> [PyROOT exp] Fix GIL control

- interpreter/cling/tools/packaging/cpt.py
Signed-off-by: Vassil Vassilev <v.g.vassilev@gmail.com>
> Fix cpt.py a careless mistake

- CMakeLists.txt
Together with PR in rootest.git it resolves [ROOT-10032]
> [ROOT-10032]Enable to dump LZ4_VERSION for root-config --config output

- gui/CMakeLists.txt
- gui/browserv7/CMakeLists.txt
- gui/browserv7/inc/LinkDef.h
- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/src/RBrowser.cxx
- ui5/browser/Component.js
- ui5/browser/browser.html
- ui5/browser/controller/Browser.controller.js
- ui5/browser/manifest.json
- ui5/browser/model/BrowserListBinding.js
- ui5/browser/model/BrowserModel.js
- ui5/browser/view/Browser.view.xml
First implementation of the ROOT7 Browser, using OpenUI5 Web GUI
To try it:
root[0] #include "ROOT/RBrowser.hxx"
root[1] using namespace ROOT:Experimental;
root[2] RBrowser browser;
> Add ROOT7 RBrowser using OpenUI5

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/test/dataframe_simple.cxx
- tutorials/dataframe/df031_Stats.C
- tutorials/dataframe/df031_Stats.py
increase test coverage accordingly and add 2 tutorials, one in C++ and one in Python.
> [RDF] Make the Stats method templated (on top of #3741)

- geom/gdml/inc/TGDMLWrite.h
- geom/gdml/src/TGDMLParse.cxx
- geom/gdml/src/TGDMLWrite.cxx
- geom/geom/inc/TGeoManager.h
- geom/geom/inc/TGeoMaterial.h
- geom/geom/src/TGeoManager.cxx
- geom/geom/src/TGeoMaterial.cxx
Added support for material constant properties, including GDML persistence.
> Support for constant tag in GDML

- interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
stupid change but nice to have :)
> [Cling] Add value printers for unique/shared_ptr

- README/ReleaseNotes/v618/index.md
@etejedor Shall we add a PyROOT section to the release notes?
> [NFC] Add release notes

- geom/geom/src/TGeoPgon.cxx
Bug fix in navigation of TGeoPgon when ray was hitting  the Z axis.
> Fix fot ROOT-9938. 

- core/meta/inc/TInterpreter.h
- core/meta/src/TClass.cxx
- core/meta/src/TProtoClass.cxx
- core/metacling/src/TCling.cxx
- core/metacling/src/TCling.h
- tree/treeplayer/src/TFormLeafInfo.cxx
Note the separate commits are intended to simplify bisecting if necessary as this is very fragile logic in ROOT.
> Add suspend autoload raii

- tree/tree/src/TChain.cxx
- tree/tree/src/TTree.cxx
- tree/treeplayer/src/TBranchProxy.cxx
- tree/treeplayer/src/TBranchProxyDirector.cxx
- tree/treeplayer/src/TTreeReader.cxx
- tree/treeplayer/test/basic.cxx
Prompt error message and stop the event loop instead.
> [IO][ROOT-10019] Prevent segfault if branch disappears from chain

- tutorials/CMakeLists.txt
Fixed by https://github.com/root-project/root/pull/3787
> [Exp PyROOT] Re-enable some graphics tutorials

- tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_friends.cxx
This should be enough to transform ROOT-9559 in a feature request.
> [DF][ROOT-9559] Throw if processing of indexed friend trees is triggered

- tree/dataframe/test/dataframe_cache.cxx
- tree/dataframe/test/dataframe_friends.cxx
- tree/dataframe/test/dataframe_interface.cxx
- tree/dataframe/test/dataframe_leaves.cxx
- tree/dataframe/test/dataframe_nodes.cxx
- tree/dataframe/test/dataframe_report.cxx
- tree/dataframe/test/dataframe_simple.cxx
- tree/dataframe/test/dataframe_snapshot.cxx
- tree/dataframe/test/dataframe_utils.cxx
- tree/dataframe/test/datasource_lazy.cxx
the code becomes more readable than before without loosing any functionality.
> [DF] Unit tests: use EXPECT_ANY_THROW where it makes sense

- README/ReleaseNotes/v618/index.md
- math/mathcore/inc/TComplex.h
- math/mathcore/src/TComplex.cxx
stupid change the effect of which is nice to stumble upon
> [Math] Add value printer for TComplex

- README/CREDITS
- README/ReleaseNotes/v618/index.md
Folks on the review list, please let me know possible corrections / omissions.
> Add v6.18 contributors! [NFC][skip-ci]

- tree/forest/v7/inc/ROOT/RField.hxx
- tree/forest/v7/inc/ROOT/RForestView.hxx
- tree/forest/v7/src/RField.cxx
- tree/forest/v7/src/RForest.cxx
- tree/forest/v7/src/RForestDescriptor.cxx
- tree/forest/v7/src/RPageStorageRoot.cxx
since it does not exist in the c++17 stl.
> [forest] Convert to string stringview w/o using the to_string method

- math/vecops/inc/ROOT/RVec.hxx
Thanks @couet for spotting the cause of the problem!
>  [Doc][ROOT-10124] Close code example for ROOT::VecOps::Construct

- gui/fitpanelv7/inc/LinkDef.h
- gui/fitpanelv7/inc/ROOT/RFitPanel.hxx
- gui/fitpanelv7/inc/ROOT/RFitPanelModel.hxx
- gui/fitpanelv7/src/RFitPanel.cxx
- gui/fitpanelv7/src/RFitPanelModel.cxx
- hist/hist/inc/TFitResult.h
- hist/hist/src/TFitResult.cxx
- math/mathcore/inc/Fit/FitResult.h
- math/mathcore/src/FitResult.cxx
- tutorials/v7/fitpanel.cxx
- tutorials/v7/fitpanel6.cxx
- ui5/fitpanel/controller/ColorButton.js
- ui5/fitpanel/controller/FitPanel.controller.js
- ui5/fitpanel/view/FitPanel.view.xml
Require extension of ROOT::Fit::FitResult and TFitResult classes
> web fitpanel: provide advanced drawings of fit results

- bindings/pyroot/src/Converters.cxx
- bindings/pyroot/src/Cppyy.cxx
- bindings/pyroot/src/Cppyy.h
- bindings/pyroot/src/Executors.cxx
- bindings/pyroot/src/ObjectProxy.h
> [pyroot] Support libstdc++ shared_ptr:

- tree/tree/src/TTree.cxx
- tutorials/io/double32.C
in the tutorial and in the TTree doc
> [NFC] Better document the usage of the Double32_t and Float16_t types

- geom/geom/inc/TGeoNode.h
Backport requested by CMS in ROOT-10139
> Added Up operation in TGeoIterator.

- documentation/doxygen/filter.cxx
Fix a problem when a tutorial generate many pictures.
> Fix a bug when a tutorial generates a lot of pictures

- bindings/pyroot/cppyy.py
- bindings/pyroot_experimental/cppyy/cppyy/python/cppyy/__init__.py
- core/base/inc/TROOT.h
- core/base/src/TApplication.cxx
- core/base/src/TROOT.cxx
- core/dictgen/src/rootcling_impl.cxx
- core/meta/inc/TInterpreter.h
- core/metacling/src/TCling.cxx
- core/metacling/src/TCling.h
- core/metacling/src/rootclingTCling.cxx
- core/unix/src/TUnixSystem.cxx
- core/winnt/src/TWinNTSystem.cxx
- gui/gui/src/TGApplication.cxx
- main/src/pmain.cxx
- main/src/roots.cxx
- roofit/roofitcore/src/RooClassFactory.cxx
This PR has misc improvements and depends on PR #3769.
> Reduce calls to enable autoloading, reduce cxxmodules work at shutdown

- tutorials/v7/ntuple/ntpl001_staff.C
- tutorials/v7/ntuple/ntpl002_vector.C
- tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
- tutorials/v7/ntuple/ntpl004_dimuon.C
> [ntuple] make tutorials more concise

- core/dictgen/res/TModuleGenerator.h
- core/dictgen/src/TModuleGenerator.cxx
- core/dictgen/src/rootcling_impl.cxx
This patch makes the implementation reusable and ready to configure it such
that we can remove the redundant information for modules.
> [dict] Refactor the dictionary initialization. NFC.

- cmake/modules/SearchInstalledSoftware.cmake
- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomViewer.cxx
- gui/browserv7/src/RBrowser.cxx
- js/scripts/JSRoot.openui5.js
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoPainter.js
- tutorials/CMakeLists.txt
- tutorials/eve7/viewer.C
- tutorials/v7/browser.cxx
- ui5/browser/browser.html
- ui5/browser/model/BrowserModel.js
- ui5/eve7/controller/GeomViewer.controller.js
RBrowser requires "codeviewer" component, which was not provided in openui5.tar.gz tarball
Also when using openui5 from web, use fixed version 1.64.1, latest does not work for us yet
Provide minimal browser.cxx tutorial
> Update JSROOT and ui5 code

- cmake/modules/SearchInstalledSoftware.cmake
- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomViewer.cxx
- gui/browserv7/src/RBrowser.cxx
- js/scripts/JSRoot.openui5.js
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoPainter.js
- tutorials/CMakeLists.txt
- tutorials/eve7/viewer.C
- tutorials/v7/browser.cxx
- ui5/browser/browser.html
- ui5/browser/model/BrowserModel.js
- ui5/eve7/controller/GeomViewer.controller.js
* RBrowser requires "codeviewer" component, which was not provided in openui5.tar.gz tarball
* Also when using openui5 from web, use fixed version 1.64.1, latest does not work for us yet
* Provide minimal browser.cxx tutorial
Cherry-pick of https://github.com/root-project/root/pull/3885
> Update JSROOT and ui5 code, v6.18

- core/clingutils/CMakeLists.txt
This works better for me (i.e. I have multiple clang versions installed and it works as well). Please check that it works for you and let me know so I can merge. The Jenkins builds are not able to actually test this.
> ROOT-9661 Improve configuration using external clang

- roofit/roofitcore/inc/RooExpensiveObjectCache.h
- roofit/roofitcore/inc/RooMsgService.h
- roofit/roofitcore/inc/RooNameReg.h
- roofit/roofitcore/inc/RooNumGenConfig.h
- roofit/roofitcore/inc/RooNumGenFactory.h
- roofit/roofitcore/inc/RooNumIntConfig.h
- roofit/roofitcore/inc/RooNumIntFactory.h
- roofit/roofitcore/inc/RooRealConstant.h
- roofit/roofitcore/inc/RooResolutionModel.h
- roofit/roofitcore/src/RooExpensiveObjectCache.cxx
- roofit/roofitcore/src/RooMsgService.cxx
- roofit/roofitcore/src/RooNameReg.cxx
- roofit/roofitcore/src/RooNumGenConfig.cxx
- roofit/roofitcore/src/RooNumGenFactory.cxx
- roofit/roofitcore/src/RooNumIntConfig.cxx
- roofit/roofitcore/src/RooNumIntFactory.cxx
- roofit/roofitcore/src/RooRealConstant.cxx
- roofit/roofitcore/src/RooResolutionModel.cxx
- roofit/roofitcore/src/RooSentinel.cxx
RooFit uses a lot of global statics in factories. These have been replaced by function-local statics.
> [RF] Reduce global statics

- core/dictgen/res/TModuleGenerator.h
- core/dictgen/src/TModuleGenerator.cxx
- core/dictgen/src/rootcling_impl.cxx
> Cxxmodules simplify lib registration

- core/metacling/src/TCling.cxx
This patch moves code which does similar things into standalone routines. This
way we make more clear the intent of use.
> [tcling] Refactor code in separate routines and reduce include for modules.

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
HistFactory normally collects histograms automatically, but not if
`HistoToWorkspaceFactoryFast::MakeSingleChannelWorkspace` is used.
This commit fixes this defect, and adds sanity checks.
> [RF] Trigger collection of histograms in HistFactory.

- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomData.cxx
- graf3d/eve7/src/REveGeomViewer.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.v6.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/lib/GeomDrawing.js
- ui5/eve7/view/GeomViewer.view.xml
* use m.SplitApp for main layout
* provide info page to draw separate geometry node and extra info
* experimental support of TGeoShape transport to client instead of binary data
* try to transport binary as std::vector<unsigned char> in JSON, ok for small data
* latest JSROOT as in v6-18-00-patches branch
> web geometry viewer: SplitApp with info page

- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomData.cxx
- graf3d/eve7/src/REveGeomViewer.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.v6.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/lib/GeomDrawing.js
- ui5/eve7/view/GeomViewer.view.xml
Same as #3901 
Suppose to be latest sync from master for JS/ui5 code
> web geometry viewer: SplitApp with info page 6.18

- core/thread/src/TReentrantRWLock.cxx
However older gcc version can not implicitly convert a unique_ptr for derived class to
a unique_ptr for the base class of the derived class.
> Address gcc9 warning about redundant move.

- io/io/src/TBufferJSON.cxx
Same fix will be provided for master with new feature PR
> json: fix for reading array packed as JSON object { "$arr": ... }

- hist/hist/src/THStack.cxx
Fix gcc9 warnings mentioned in ROOT-10137
> Suppress gcc9 warnings in THStack

- core/metacling/src/TCling.cxx
- interpreter/cling/include/cling/Interpreter/DynamicLibraryManager.h
- interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
@axel Philippes commit were already backported: https://github.com/root-project/root/pull/3932
> [6-18 backport] Backport fixes for incrementals (TCling)

- core/metacling/src/TCling.cxx
This patch should fix an assert in the incrementals.
> [tcling] Check if the triggerFunc is in a library.

- bindings/pyroot_experimental/PyROOT/python/ROOT/_facade.py
- bindings/pyroot_experimental/cppyy/CPyCppyy/src/ProxyWrappers.cxx
- bindings/pyroot_experimental/cppyy/CPyCppyy/src/Utility.cxx
The attempt to fix the following test that was failing:
roottest-python-basic-operator
led to the necessity of adding the possibility for the user to call a namespace inside cppyy.gbl.ROOT by simply typing ROOT.Namespace instead of ROOT.ROOT.Namespace. 
Two bugs in cppyy were also found during this attempt, both fixed by the maintainer of the repo.
The test mentioned above now succeeds.
> [Exp PyROOT] ROOT.Namespace instead of ROOT.ROOT.Namespace

- net/net/inc/TSQLStatement.h
- net/net/src/TSQLStatement.cxx
- sql/mysql/inc/TMySQLStatement.h
- sql/odbc/inc/TODBCStatement.h
- sql/oracle/inc/TOracleStatement.h
- sql/sqlite/inc/TSQLiteStatement.h
After #3961 one should inform users that method not yet implemented for all plugins
Also fix introduced compiler warnings
> Provide warnings in TSQLStatement

- tutorials/webgui/webwindow/client.html
- tutorials/webgui/webwindow/server.cxx
It shows simple communication between c++ server and JS client
> [webgui] introduce simple RWebWindow tutorial

- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/inc/ROOT/RBrowserItem.hxx
- gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
- gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
- gui/webdisplay/inc/ROOT/RWebWindow.hxx
- gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
- gui/webdisplay/src/RWebDisplayArgs.cxx
- gui/webdisplay/src/RWebDisplayHandle.cxx
- gui/webdisplay/src/RWebWindow.cxx
- gui/webdisplay/src/RWebWindowWSHandler.hxx
- gui/webdisplay/src/RWebWindowsManager.cxx
It shows provided Url in "normal" browser window
Improve usage of custom browsers like "opera"
>  [webgui] provide convenience RWebDisplayHandle::DisplayUrl method

- graf2d/gpadv7/v7/inc/ROOT/RPad.hxx
- graf2d/gpadv7/v7/inc/ROOT/RPadDisplayItem.hxx
- graf2d/gpadv7/v7/src/RPad.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.hist3d.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.v7.js
- js/scripts/JSRootPainter.v7hist.js
- js/scripts/JSRootPainter.v7more.js
- ui5/fitpanel/view/FitPanel.view.xml
Patch for 6.18 version will follow
> [v7] Fix v7 webgui tutorials

- graf2d/gpadv7/v7/inc/ROOT/RPad.hxx
- graf2d/gpadv7/v7/inc/ROOT/RPadDisplayItem.hxx
- graf2d/gpadv7/v7/src/RPad.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.hist3d.js
- js/scripts/JSRootPainter.v7.js
- js/scripts/JSRootPainter.v7hist.js
- js/scripts/JSRootPainter.v7more.js
- ui5/fitpanel/view/FitPanel.view.xml
Same as #4039, only JSROOT used from appropriate branch
> [v7] fix all webgui tutorials for 6.18

- gui/cefdisplay/src/simple_app.cxx
As usual, CEF changes API. Now try to support older version as well, why newest CEF still fails for me.
> [webgui] let compile with newest CEF version

- gui/qt5webdisplay/rootqt5.cpp
Mixed up hexadecimal and decimal numbers
> [webgui] using proper qt5 version in ifdef to register scheme handler

- tmva/tmva/CMakeLists.txt
- tmva/tmva/inc/TMVA/RStandardScaler.hxx
- tmva/tmva/inc/TMVA/RTensor.hxx
- tmva/tmva/test/CMakeLists.txt
- tmva/tmva/test/rstandardscaler.cxx
- tutorials/tmva/tmva004_RStandardScaler.C
> [TMVA experimental] Add RStandardScaler method

- graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilder.hxx
- graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilderTemplate.hxx
- graf3d/eve7/src/REveDataClasses.cxx
- graf3d/eve7/src/REveDataSimpleProxyBuilder.cxx
- graf3d/eve7/src/REveStraightLineSet.cxx
- tutorials/eve7/collection_proxies.C
This is continuation of  #4023.
I have replaced 'unsigned int' with 'int' and deactivated print in REveDataTable.
> Pass additional argument in REveDataProxyBuilder build methods

- README/ReleaseNotes/v620/index.md
- js/changes.md
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootGeoWorker.js
- js/scripts/JSRootPainter.js
- tutorials/http/httpgeom.C
Now JSROOT.TGeoPainter can be used with THttpServer for "monitoring" of
geometry object. Exactly like a histogram, TGeoManager can be regularly
received and dsiplayed. Also tracks can be monitored together
Provide tutorial macro
> [http] enables monitoring of TGeo objects in THttpServer

- graf3d/eve7/inc/ROOT/REveDataClasses.hxx
- graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilder.hxx
- graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilderTemplate.hxx
- graf3d/eve7/inc/ROOT/REveElement.hxx
- graf3d/eve7/inc/ROOT/REveManager.hxx
- graf3d/eve7/inc/ROOT/REveScene.hxx
- graf3d/eve7/inc/ROOT/REveTrack.hxx
- graf3d/eve7/src/REveElement.cxx
This should fix newly introduced warnings from @alja
> [eve7] fix new warnings, use override specifier at fixed files

- tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
- tree/dataframe/inc/ROOT/RDF/RAction.hxx
> [RDF] Avoid unused variable warning

- interpreter/cling/lib/Interpreter/Value.cpp
If the constructor of the contained object is not run (e.g. because
assembling its arguments triggered an exception), the dtor must not
be run when destructing the cling::Value. Detect this case by imprinting
canary bytes into the contained object bytes: if they have changed,
run the dtor, if not assume that the constructor has failed.
This will cause false positives in those cases where the constructor
is not modifying the first object bytes: in these cases, the dtor
is not run even though the ctor is run. That is still better than
the other case (where the dtor crashes because no ctor was run).
> [cling] Use canary bytes to determine whether to run dtor:

- bindings/pyroot_experimental/PyROOT/src/CPPInstancePyz.cxx
Update of the previous pull request #4077
> [Exp PyROOT] Silenced some warnings after commit 466e582

- roofit/roofitcore/inc/RooGlobalFunc.h
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
Added "PrefitDataFraction" parameter in fitTo method in RooAbsPdf.
This can speed up fitting by computing better starting values
out of a small subset of the data.
> [RF] Implement prefit option for roofit.

- roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
When HistFactory constructs gamma parameters, they don't have initial errors.
When trying to plot the prefit model, the missing errors will make problems.
By assigning the relative errors caused by the constraint terms, pre-fit plots
will succeed.
> [RF] Set reasonable pre-fit errors for gammas in HistFactory.

- bindings/pyroot_experimental/cppyy/CPyCppyy/src/Pythonize.cxx
We incorporate a commit made originally in Cppyy in order to fix a difference of behavior between Linux and MacOs machines. For the full details please refer to:
https://bitbucket.org/wlav/cppyy/issues/132/missing-assignment-of-tp_iternext-in
This commit should make the following test:
tutorial-vecops-vo004_SortAndSelect-py
succeed also on MacOs machines.
> [Exp PyROOT] Missing assignment of tp_iternext in vector-like classes on MacOs

- tree/dataframe/test/CMakeLists.txt
The following test:
pyunittests-dataframe-histograms
was fixed by the commit mentioned in the title.
> [Exp PyROOT] Other test fixed by commit 267179

- tmva/tmva/inc/TMVA/DNN/BatchNormLayer.h
- tmva/tmva/inc/TMVA/DNN/DeepNet.h
- tmva/tmva/inc/TMVA/DNN/GeneralLayer.h
- tmva/tmva/inc/TMVA/DNN/ReshapeLayer.h
- tmva/tmva/inc/TMVA/MethodDL.h
- tmva/tmva/src/MethodDL.cxx
- tmva/tmva/test/DNN/CMakeLists.txt
- tmva/tmva/test/DNN/TestBatchNormalization.cxx
- tmva/tmva/test/DNN/TestBatchNormalization.h
- tmva/tmva/test/DNN/TestBatchNormalizationCpu.cxx
- tmva/tmva/test/DNN/TestBatchNormalizationCuda.cxx
This PR add support for batch normalisation for MethodDL (deep learning in TMVA)
The code has been developed mainly by Liam Bartsch (trainee in June 2019)
> Add Batch normalisation layer (from Liam Bartsch)

- math/vecops/inc/ROOT/RVec.hxx
> [VecOps] Avoid allocating temporaries on heap in InvariantMass[es]

- interpreter/cling/lib/Utils/PlatformPosix.cpp
The POSIX does not contains /dev/random [1]. Moreover the /dev/random
might not have write permissions. The better way is to use an another
solution which is based on the msync system call [2]. Also this solution
reduces the number of context switching.
[1] -- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap10.html
[2] -- https://pubs.opengroup.org/onlinepubs/009695399/functions/msync.html
> Change pointer check method to msync.

- core/dictgen/src/rootcling_impl.cxx
- etc/dictpch/makepch.py
This PR is part of a larger (future) PR improving the argument parsing. The final goal is to fix the incremental builds when ROOT is built with -Druntime_cxxmodules=On.
> Rootcling minor refactoring

- geom/geom/CMakeLists.txt
- geom/geom/inc/TGeant4PhysicalConstants.h
- geom/geom/inc/TGeant4SystemOfUnits.h
- geom/geom/src/TGeoElement.cxx
- geom/geom/src/TGeoMaterial.cxx
- geom/geom/src/TGeoUnit.cxx
(cherry picked from commit b81396c4037e76d614bbf7ffa913ed1ce28813a8)
> Allow to select system of units (TGeo/Geant4) at run-time

- interpreter/cling/lib/Utils/PlatformPosix.cpp
Use precalculated PAGE_MASK which is equals to ~(page_size - 1) at
pointer check instead of recalculate it each check.
This a small addition to the #4136 and #4159.
> Little optimization for the cling pointer check.

- bindings/pyroot/src/Cppyy.cxx
- bindings/pyroot/src/Cppyy.h
- bindings/pyroot/src/RootWrapper.cxx
- bindings/pyroot/src/TemplateProxy.cxx
- bindings/pyroot/src/Utility.cxx
- bindings/pyroot/src/Utility.h
- core/metacling/src/TClingMethodInfo.cxx
- core/metacling/src/TClingMethodInfo.h
This is a backport of https://github.com/root-project/root/pull/3911 that fixes, for 6.18:
https://sft.its.cern.ch/jira/browse/ROOT-10256
> [PyROOT] [ROOT-10256] Fix return value of templated function

- bindings/pyroot/src/Converters.cxx
- bindings/pyroot/src/Cppyy.cxx
- bindings/pyroot/src/Cppyy.h
- bindings/pyroot/src/Executors.cxx
- bindings/pyroot/src/PropertyProxy.cxx
- bindings/pyroot/src/PyRootType.cxx
- bindings/pyroot/src/RootModule.cxx
- core/meta/inc/TDictionary.h
- core/meta/inc/TEnum.h
- core/meta/inc/TInterpreter.h
- core/meta/src/TEnum.cxx
- core/meta/test/CMakeLists.txt
- core/meta/test/testTEnum.cxx
- core/metacling/src/TCling.cxx
- core/metacling/src/TCling.h
- core/metacling/src/TClingClassInfo.cxx
- core/metacling/src/TClingClassInfo.h
Backport of:
https://github.com/root-project/root/pull/4031
https://github.com/root-project/root/pull/4121
> Backport 6.18: Better enum support in TCling and PyROOT

- graf3d/eve7/inc/ROOT/REveDataProxyBuilderBase.hxx
- graf3d/eve7/inc/ROOT/REveManager.hxx
- graf3d/eve7/inc/ROOT/REveTableInfo.hxx
- graf3d/eve7/inc/ROOT/REveTableProxyBuilder.hxx
- graf3d/eve7/src/REveManager.cxx
- graf3d/eve7/src/REveTableInfo.cxx
- graf3d/eve7/src/REveTableProxyBuilder.cxx
- tutorials/eve7/collection_proxies.C
- ui5/eve7/controller/EveTable.controller.js
- ui5/eve7/view/EveTable.view.xml
* Reuse REveData table in REveTableProxyBuilder::Build() function
* Add interface in  REveManager for client version
> WebEve: Optimize table proxy builder

- ui5/eve7/controller/Summary.controller.js
This is a minor change, to enable other controllers to set expand level like:
https://github.com/alja/EveWebApp/blob/custom/ui5/controller/MyNewSummary.controller.js#L10
> WebEve: Add parameter for expand level

- tmva/tmva/inc/TMVA/RTensor.hxx
Thanks @lmoneta for pointing out!
> [TMVA experimental] Make RTensor getter return const refs

- tree/ntuple/v7/test/ntuple.cxx
- tree/ntuple/v7/test/ntuple_print.cxx
Use random numbers in the file names created during unit tests, so that concurrent unit tests don't remove each others files.
> [ntuple] Fix flakey unit tests

- core/dictgen/src/rootcling_impl.cxx
Rootcling builds a set of modules implicitly based on #including of a header
contained in the nominated module. The build system has no way to track such
dependencies and even if it could there would be no rule to execute to
regenerate the outdated module.
This patch extends rootcling to also keep track of the implicitly generated
modules and delete them (to regenerate them). A more sustainable solution is to
request each module to be built explicitly which requires a bit of refactoring
in rootcling.
> [cxxmodules] Fix incremental builds.

- js/changes.md
- js/scripts/JSRoot3DPainter.js
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootIOEvolution.js
- js/scripts/JSRootMath.js
- js/scripts/JSRootPainter.hierarchy.js
- js/scripts/JSRootPainter.hist.js
- js/scripts/JSRootPainter.hist3d.js
- js/scripts/JSRootPainter.jquery.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.more.js
- js/scripts/JSRootPainter.v6.js
- js/scripts/JSRootPainter.v7.js
- js/scripts/JSRootPainter.v7hist.js
- js/scripts/JSRootPainter.v7more.js
- js/scripts/JSRootTree.js
- js/scripts/ThreeCSG.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/geom.html
- ui5/eve7/view/GeomViewer.view.xml
Use very nice feature of openui5 SplitApp to manage different pages together!
* Re-implement GUI which was designed before using dat.GUI.
* Change a lot TGeoPainter interface - especially for setting control parameters
* Newest JSROOT code with several improvements
> [Web geom] provide control GUI for geometry viewer

- graf3d/eve7/inc/ROOT/REveGeomViewer.hxx
- graf3d/eve7/src/REveGeomViewer.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.hist.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.v6.js
- ui5/canv/controller/Ged.controller.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/view/GeomViewer.view.xml
1. Provide image storing in geometry viewer. Can be triggered from client and from server side
2. Fix pgon shape - was missing scale factor
3. Improve GED editor for object attributes in TWebCanvas6
> [Web geom] save image, fix pgon

- core/metacling/src/TCling.cxx
This removes the false positive dependencies in the rootbench builds.
> [tcling] Do not trace weak symbols when resolving library dependencies.

- net/http/src/THttpServer.cxx
- net/http/src/TRootSniffer.cxx
- net/httpsniff/src/TRootSnifferFull.cxx
In sniffer use gROOT->GetVersionCode() instead
> [http] do not use RVersion.h

- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveGeomData.hxx
- graf3d/eve7/src/REveGeomData.cxx
- graf3d/eve7/src/REveGeomViewer.cxx
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.v6.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/view/GeomViewer.view.xml
1. Let interactively change configuration for draw object selection - like visibility level or maximal number of nodes. All these parameters combined together in configuration object, which can be send to server as JSON.
2. Show actual statistic about number of meshes and faces in produced three.js geometry
3. Let configure different light source (like in normal geometry viewer)
4. Provide JSROOT with correspondent changes
> [web geom] improve control GUI

- tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/src/RNTupleDescriptor.cxx
- tree/ntuple/v7/test/ntuple.cxx
In particular
- Add support for 8 bit unsigned integer
- Add support for directly accessing a class member with a view
> [ntuple] several improvements for nanoaod support

- core/dictgen/src/rootcling_impl.cxx
Since root-project/root@10a0dec we do not expose flags from the build system
directly to rootcling. We use that opportunity to simplify the setup while
preparing rootcling for the new argument parser.
> [rootcling] We do not need to filter the build system junk.

- io/io/inc/ROOT/RRawFile.hxx
- io/io/inc/ROOT/RRawFileUnix.hxx
- io/io/inc/ROOT/RRawFileWin.hxx
- io/io/src/RRawFileUnix.cxx
- io/io/src/RRawFileWin.cxx
- io/io/test/RRawFile.cxx
- net/davix/inc/ROOT/RRawFileDavix.hxx
- net/davix/src/RRawFileDavix.cxx
- tree/ntuple/CMakeLists.txt
- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleOptions.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorageRaw.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorageRoot.hxx
- tree/ntuple/v7/src/RNTuple.cxx
- tree/ntuple/v7/src/RNTupleDescriptor.cxx
- tree/ntuple/v7/src/RPageStorage.cxx
- tree/ntuple/v7/src/RPageStorageRaw.cxx
- tree/ntuple/v7/src/RPageStorageRoot.cxx
- tree/ntuple/v7/test/CMakeLists.txt
- tree/ntuple/v7/test/ntuple.cxx
- tree/ntuple/v7/test/ntuple_raw.cxx
First working implementation without support for mmap.  Writing is done with C file I/O, it might move to RawFile once RawFile supports writing.
> [ntuple] Add support for page storage in raw files

- core/metacling/src/TCling.cxx
This should fix the CMSSW relocation issue where the symlinks may contain
relative paths. In that case when ROOT is embedded the returned relative path
points to the wrong location.
cc @davidlange6
> [tcling] Return absolute paths when resolving a symlink.

- io/io/src/TBufferJSON.cxx
Wrong optimization was used.
Fixes https://root-forum.cern.ch/t/35782/
> [json] fix problem with conversion vector<vector<vector<int>>>

- tutorials/CMakeLists.txt
@phsft-bot build with `-Dpyroot_experimental=ON`
> [PyROOT exp] Assume TTree.AsMatrix tutorial as passing

- io/io/src/TBufferJSON.cxx
Wrong optimization was used.
Fixes https://root-forum.cern.ch/t/35782/
@Axel-Naumann Can you open branch for commits again?
> [json] fix problem with conversion vector<vector<vector<int>>>, v6.18

- graf2d/graf/src/TArrow.cxx
- graf2d/graf/src/TCutG.cxx
- graf2d/graf/src/TLine.cxx
- hist/hist/inc/TGraph.h
- hist/hist/src/TGraph.cxx
1. Provide support of NDC for TArrow. 
2. Fix interactive movement of TLine/TArrow when NDC coordinates are used
3. Fix TCutG assign operator
4. Provide TGraph::MovePoints() method
> [graf2d] improving TGraph, TCutG, TLine and TArrow classes

- bindings/pyroot_experimental/PyROOT/CMakeLists.txt
- bindings/pyroot_experimental/PyROOT/python/JsMVA/DataLoader.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/Factory.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/JPyInterface.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/JsMVAMagic.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/OutputTransformer.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/Utils.py
- bindings/pyroot_experimental/PyROOT/python/JsMVA/__init__.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/README.md
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/__init__.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/helpers/cppcompleter.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/helpers/handlers.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/helpers/utils.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/html/cpphighlighter.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/kernel/magics/cppmagic.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/kernel/magics/jsrootmagic.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/kernel/rootkernel.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/kernel/utils.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/magics/cppmagic.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/magics/jsrootmagic.py
- bindings/pyroot_experimental/PyROOT/python/JupyROOT/src/IOHandler.cxx
- bindings/pyroot_experimental/PyROOT/python/ROOT/__init__.py
The packages mentioned in the title were implemented, basically copying them from the current PyROOT.
> [Exp PyROOT] Implementation of JupyROOT and JsMVA

- tutorials/pyroot/pyroot001_arrayInterface.py
- tutorials/pyroot/pyroot002_TTreeAsMatrix.py
- tutorials/pyroot/pyroot003_prettyPrinting.py
Print the stdout on the doxygen pages!
> [NFC][Doc][PyROOT exp] Add tutorial output to notebooks

- bindings/pyroot_experimental/PyROOT/CMakeLists.txt
- bindings/pyroot_experimental/PyROOT/python/ROOT/__init__.py
The commit mentioned in the title was leading to a build failure, fixed with this PR.
>  [Exp PyROOT] Changes to fix failing build after commit 00dcee

- js/changes.md
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootGeoWorker.js
- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/view/GeomViewer.view.xml
One can expand drawing in Z and Radial directions - many hidden volumes will be visible then.
Also provide control elements to enable axes drawing and animation.
Main functionality implemented in JSROOT
> [web geom] let transform drawn geometry

- interpreter/cling/tools/Jupyter/CMakeLists.txt
- interpreter/cling/tools/Jupyter/Kernel.cpp
ROOT version of https://github.com/root-project/cling/pull/272
> Fixing the jupyter Kernel to be able to handle exceptions

- core/clingutils/CMakeLists.txt
- core/clingutils/res/TClingUtils.h
- core/clingutils/src/TClingUtils.cxx
- core/clingutils/test/CMakeLists.txt
- core/clingutils/test/TClingUtilsTests.cxx
- core/metacling/src/TCling.cxx
- core/metacling/src/TClingRdictModuleFileExtension.cxx
> [cxxmodules] Use canonical paths when resolving a symlink

- CMakeLists.txt
- cmake/modules/RootMacros.cmake
Please see commit messages for more details.
> Use dictionary object files as dependencies for the PCH

- bindings/pyroot_experimental/PyROOT/python/ROOT/__init__.py
- bindings/pyroot_experimental/PyROOT/python/ROOT/_application.py
- bindings/pyroot_experimental/PyROOT/python/ROOT/_facade.py
- bindings/pyroot_experimental/cppyy/cppyy/CMakeLists.txt
This contributes to fix `roottest-python-regression-regression`.
> [Exp PyROOT] Allow from ROOT import * in Python2

- gui/canvaspainter/v7/src/TCanvasPainter.cxx
Reserve extra space for canvas menu
> [rcanvas] use RCanvas size when starting new web browser window

- core/dictgen/src/rootcling_impl.cxx
Should address the Gaudi failures reported in ROOT-10303.
> [rootcling] Support rootcling -U arguments.

- io/io/src/TGenCollectionProxy.cxx
> [IO] Add support unique_ptr in the 'Streaming' part of TGenCollectionProxy

- bindings/pyroot/src/Converters.cxx
A previous commit dropped the use of PyROOT_PyUnicode_AsStringChecked, which in Py2 corresponds to PyString_AsString, which accepts unicode objects.
This PR should fix this test failure seen in the nightlies:
http://cdash.cern.ch/testSummary.php?project=1&name=roottest-python-JupyROOT-simpleCppMagic_notebook&date=2019-09-10
> [PyROOT] Allow again conversion from Py2 unicode -> C string

- graf3d/eve7/src/REveDataProxyBuilderBase.cxx
- graf3d/eve7/src/REveStraightLineSet.cxx
- graf3d/eve7/src/REveTableProxyBuilder.cxx
- tutorials/eve7/collection_proxies.C
- ui5/eve7/controller/EveTable.controller.js
- ui5/eve7/lib/EveManager.js
* change binding of sap.ui.table.Table with JSON model
* get table view info from from REveDataCollection's item type
* comment out debug prints
> WebEve: optimizations in EveTable.js controller

- hist/hist/inc/TMultiGraph.h
- hist/hist/src/TMultiGraph.cxx
- hist/histpainter/src/TGraphPainter.cxx
Implement reverse axis drawing options, RX and RY, for TMultiGraph as requested in ROOT-10310
> RX and RY options for TMultiGraph

- core/metacling/src/TCling.cxx
This should appease the nightly bots while working on a real fix.
> [cxxmodules] Disable RMVA for the moment.

- core/base/src/TROOT.cxx
- core/clingutils/res/TClingUtils.h
- core/clingutils/src/TClingUtils.cxx
- core/dictgen/src/rootcling_impl.cxx
- core/foundation/inc/TClassEdit.h
- core/foundation/src/TClassEdit.cxx
- core/metacling/src/TCling.cxx
This extents commit 292b5d5c08c213a89e5f01a6ad3fcfbe155542fa.
> Address [cling] shutdown issues/tear-down-ordering challenges

- tutorials/v7/ntuple/ntpl003_lhcbOpenData.C
- tutorials/v7/ntuple/ntpl004_dimuon.C
Prevent accidental use of ntuple file with incompatible binary format while the format is still subject to changes.
> [ntuple] Make tutorials more robust

- core/metacling/src/TCling.cxx
If a TClass is in fClassesToUpdate, we must run the dictionary
function to replace it (move it from kInterpreted/kEmulated/kForwardDeclared
to kHasTClassInit).
Whether the classes on the list need to be processed is not related to whether
parsing on demand or module are turned on (even if those can affect the likely
hood that the list is populated or not)
This fixes the problem see in the test 'pyunittests-pyroot-ttree_asmatrix':
```
Fatal in <TClass::SetUnloaded>: The TClass for __gnu_cxx::__normal_iterator<double*,vector<double> > is being unloaded when in state 3
```
seen in the builds with cxxruntime_module turned on.
> Always process the list of "ClassesToUpdate"

- core/foundation/src/TClassEdit.cxx
This fixes ROOT-8396
The issues was the normalization of
"std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >"
into vector<string> due to the inline namespace (__cxx11).
Prior to this commit, it would work but only if the name for normalized twice.
This because the order of operation was
1. check if the name is std::basic_string or basic_string
2. do more stuff
3. remove std and std::[any-inlined-namespace-name]
now we extended 1 to also search for std::[any-inlined-namespace-name]::basic_string
> Fix handling of inline namespace std::__cxx11 in TClassEdit::GetSplit

- tree/ntuple/v7/inc/ROOT/RColumn.hxx
- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
- tree/ntuple/v7/test/ntuple.cxx
Fix implementation for the case where a std::string goes over the page limit. A small test is also added to test it.
> [ntuple] fix vector read from columns

- graf2d/gpad/inc/TCanvas.h
- graf2d/gpad/src/TCanvas.cxx
> Make sure canvases are named

- hist/histpainter/src/THistPainter.cxx
- hist/histpainter/src/TPaletteAxis.cxx
In TPaletteAxis: Implement justifying labels at color boundaries
> Palette cjust

- README/ReleaseNotes/v618/index.md
- tree/tree/src/TBasket.cxx
- tree/tree/src/TBranch.cxx
This was first reported at https://cdcvs.fnal.gov/redmine/issues/23348.
> Leak uncompressed tree read v618

- tutorials/tree/tree1.C
- tutorials/tree/tree2.C
> Add missing call to TTree::ResetBranchAddresses.

- gui/browserv7/src/RBrowser.cxx
- ui5/browser/browser.html
- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/Browser.view.xml
This PR add the possibility to read a root file graph and display it into the javascript browser
> v7Browser Graph display

- hist/hist/inc/TH2.h
- hist/hist/inc/TH3.h
This PR revert the changes introduced in #4427
> Revert moving TH2,3::GetBinErrorLow,Up to private

- core/base/src/TMemberInspector.cxx
- core/metacling/src/TCling.cxx
off by hand allocation and infinite recursion.
> fix ROOT-10343 ROOT-10344

- roofit/roofitcore/inc/RooGenericPdf.h
adding back default constructor for RooGenericPdf (for I/O)
> [RooFit] RooGenericPdf default Constructor

- gui/browserv7/CMakeLists.txt
- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/src/RBrowser.cxx
> Rbrowser use TFile directly

- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
This PR do that when drawing or adding a canvas, selected tab will change to the correct one
> [RBrowser] tabs canvas selection

- graf2d/gpadv7/v7/inc/ROOT/RDrawable.hxx
- graf2d/primitives/CMakeLists.txt
- graf2d/primitives/inc/LinkDef.h
- graf2d/primitives/v7/inc/ROOT/RBox.hxx
- graf2d/primitives/v7/inc/ROOT/RLegend.hxx
- graf2d/primitives/v7/src/RLegend.cxx
- gui/webdisplay/src/RWebDisplayHandle.cxx
- js/scripts/JSRootPainter.v7.js
- js/scripts/JSRootPainter.v7more.js
- tutorials/v7/draw_legend.cxx
It directly reference RDrawable objects.
Using existing solution for I/O
While automatic colors need to be introduced, special solution will be provided later.
> Introduce RLegend class

- roofit/roofitcore/inc/RooDataHist.h
Add back default to Clone() for RooDataHist.
> [RooFit] RooDataHist Clone

- gui/webdisplay/src/RWebDisplayHandle.cxx
Allows to avoid several problems when browser app already running.
Used for chrome and firefox browsers
> Use incognito mode to start RWebWindow widgets

- core/base/inc/TBuffer3D.h
- core/base/inc/TObjectSpy.h
- core/base/src/TObjectSpy.cxx
- core/meta/inc/TRealData.h
- graf2d/gpad/src/TCanvas.cxx
- graf2d/gpad/src/TClassTree.cxx
- graf2d/gpad/src/TPad.cxx
- gui/gui/src/TGFileBrowser.cxx
- net/httpsniff/src/TRootSnifferFull.cxx
- tree/treeplayer/src/TBranchProxy.cxx
Use clear =delete statements in TObjectSpy and TBufer3D classes declarations
> Remove TObjectSpy.h and TBuffer3D.h includes from some GPad sources

- core/dictgen/src/rootcling_impl.cxx
When calling rootcling we expect a set of header files and a selection file. In some cases it is more convenient to include all of them in a single header and give it to rootcling. In cases where the header files are so many and exceed the maximum characters allowed by the console the umbrella header is the only way to work it around.
In cases where the umbrella header is temporary (such as in cmssw) we cannot add it as a part of the module, however, we have added its direct includes in the module definition. Then rootcling should not complain if the umbrella header file is not part of the module definition.
This patch should fix the issues in cmssw when building a dictionary for DataFormats/StdDictionaries.
cc: @smuzaffar, @oshadura, @davidlange6
> [rootcling] Support umbrella headers for dictionaries.

- interpreter/llvm/src/tools/clang/lib/Serialization/ASTReader.cpp
https://sft.its.cern.ch/jira/browse/ROOT-10361
> [6.18] [cxxmodules][pch] Disable validation of transent files

- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/model/BrowserModel.js
- ui5/browser/view/Browser.view.xml
This PR add the breadcrumbs to the RBrowser, and allow to move the working directory
> RBrowser breadcrumbs

- core/base/src/TMD5.cxx
- core/clingutils/src/TClingUtils.cxx
- core/dictgen/src/Scanner.cxx
- core/dictgen/src/SelectionRules.cxx
- core/dictgen/src/rootcling_impl.cxx
- core/meta/src/TDataMember.cxx
- core/rint/src/TTabCom.cxx
- core/textinput/src/textinput/Editor.cpp
- graf2d/gpad/src/TCanvas.cxx
- gui/gui/src/TGText.cxx
- gui/guihtml/src/TGHtmlImage.cxx
- hist/hist/src/TFormula_v5.cxx
- io/io/src/TFile.cxx
- io/io/src/TFileCacheRead.cxx
- io/io/src/TStreamerInfoActions.cxx
- math/mathcore/inc/Fit/LogLikelihoodFCN.h
- proof/proof/src/TProofServ.cxx
- roofit/roofitcore/src/RooAbsCategory.cxx
- tree/treeplayer/src/TFormLeafInfo.cxx
Address some of the issues described at https://www.viva64.com/en/b/0682/
> Pvs studio

- tmva/tmva/inc/LinkDef1.h
- tutorials/CMakeLists.txt
- tutorials/tmva/tmva100_DataPreparation.py
- tutorials/tmva/tmva101_Training.py
- tutorials/tmva/tmva102_Testing.py
- tutorials/tmva/tmva103_Application.C
Depends on #4401, requires rebase.
> [TMVA experimental] Add tutorials illustrating the new TMVA workflow

- tmva/tmva/src/MethodMLP.cxx
See the respective [JIRA ticket](https://sft.its.cern.ch/jira/browse/ROOT-10375)
> [ROOT-10375] V523 The 'then' is equivalent to the 'else' case

- core/metacling/src/TCling.cxx
Fix warning in macOS/cxx17 platform
> Remove unsused capture in TCling

- core/clingutils/CMakeLists.txt
- core/dictgen/src/rootcling_impl.cxx
- interpreter/cling/include/cling/cuda.modulemap
- interpreter/cling/lib/Interpreter/CIFactory.cpp
This should fix our TMVA cuda builds.
> [cxxmodules] Add an initial version of a modulemap for cuda.

- interpreter/cling/include/cling/cuda.modulemap
This should fix the cuda failures.
> [cxxmodules] Move curand_discrete and remove curand_poisson.

- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/Browser.view.xml
One should use FlexBox that ui5 TreeTable correctly resized
> RBrowser: fix layout for TreeTable

- core/dictgen/src/rootcling_impl.cxx
This will help cmssw specify their generated modulemap files on the command line.
cc: @oshadura, @davidlange6
> [cxxmodules] Add a new argument which takes a list of modulemap files.

- ui5/eve7/controller/GeomViewer.controller.js
- ui5/eve7/view/GeomViewer.view.xml
Need to find better solution later
> [web geom] provide laoyout fix for TreeTable WIP

- bindings/pyroot_experimental/cppyy/CPyCppyy/src/CPPScope.cxx
- bindings/pyroot_experimental/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
Seen here:
http://cdash.cern.ch/viewBuildError.php?type=1&buildid=755033
> [Exp PyROOT] Warning and logic fixes

- gui/browserv7/src/RBrowsableTDirectory.cxx
- gui/browserv7/src/RBrowsableTObject.cxx
- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/model/BrowserListBinding.js
- ui5/browser/model/BrowserModel.js
- ui5/browser/view/Browser.view.xml
- ui5/browser/view/imageviewer.fragment.xml
@Falcort I rebase your branch and creating PR for master
Do you want to submit it now or later?
> RBrowser: support different tabs types

- cmake/modules/SearchInstalledSoftware.cmake
See https://gitlab.kitware.com/cmake/cmake/issues/19763
> [cmake] Use FindPython for newer CMake, fixes MacOS 10.14 with Xcode 11:

- roofit/roofitcore/inc/RooAbsArg.h
- roofit/roofitcore/inc/RooAbsReal.h
- roofit/roofitcore/inc/RooAbsRealLValue.h
- roofit/roofitcore/inc/RooAddPdf.h
- roofit/roofitcore/inc/RooRealVar.h
- roofit/roofitcore/src/RooAbsArg.cxx
- roofit/roofitcore/src/RooAbsReal.cxx
- roofit/roofitcore/src/RooAddGenContext.cxx
- roofit/roofitcore/src/RooAddPdf.cxx
- roofit/roofitcore/src/RooFormulaVar.cxx
- roofit/roofitcore/src/RooRealVar.cxx
Backports for
[ROOT-10367] Crash
[ROOT-10358] Broken assignment
[ROOT-6008] Buffer overlow
> [RF] Backport a couple of bugfixes to 6.18.

- tree/ntuple/CMakeLists.txt
- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
- tree/ntuple/v7/inc/ROOT/RNTupleMetrics.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorageRaw.hxx
- tree/ntuple/v7/inc/ROOT/RPageStorageRoot.hxx
- tree/ntuple/v7/src/RNTuple.cxx
- tree/ntuple/v7/src/RNTupleMetrics.cxx
- tree/ntuple/v7/src/RPageStorageRaw.cxx
- tree/ntuple/v7/src/RPageStorageRoot.cxx
- tree/ntuple/v7/test/CMakeLists.txt
- tree/ntuple/v7/test/ntuple_metrics.cxx
Adds infrastructure to instrument code parts with counters and timers -- either thread-safe atomics or simple integers. Adds a few key counters to the raw page source.
> [ntuple] Add support for performance instrumentation

- interpreter/CMakeLists.txt
- interpreter/cling/CMakeLists.txt
- interpreter/cling/include/cling/Interpreter/Interpreter.h
- interpreter/cling/include/cling/Interpreter/InvocationOptions.h
- interpreter/cling/lib/Interpreter/CIFactory.cpp
- interpreter/cling/lib/Interpreter/CMakeLists.txt
- interpreter/cling/lib/Interpreter/DeviceKernelInliner.cpp
- interpreter/cling/lib/Interpreter/DeviceKernelInliner.h
- interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.cpp
- interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.h
- interpreter/cling/lib/Interpreter/IncrementalParser.cpp
- interpreter/cling/lib/Interpreter/IncrementalParser.h
- interpreter/cling/lib/Interpreter/Interpreter.cpp
- interpreter/cling/lib/Interpreter/InvocationOptions.cpp
- interpreter/cling/lib/Utils/SourceNormalization.cpp
- interpreter/cling/test/CUDADeviceCode/CUDADefineArg.C
- interpreter/cling/test/CUDADeviceCode/CUDAHostPrefix.C
- interpreter/cling/test/CUDADeviceCode/CUDAInclude.C
- interpreter/cling/test/CUDADeviceCode/CUDAKernelArgument.C
- interpreter/cling/test/CUDADeviceCode/CUDAKernelTemplateComplex.C
- interpreter/cling/test/CUDADeviceCode/CUDAKernelTemplateSimple.C
- interpreter/cling/test/CUDADeviceCode/CUDARegression.C
- interpreter/cling/test/CUDADeviceCode/CUDASharedMemory.C
- interpreter/cling/test/CUDADeviceCode/CUDASimpleKernel.C
- interpreter/cling/test/CUDADeviceCode/CUDAStreams.C
- interpreter/cling/test/CUDADeviceCode/include/foo.h
- interpreter/cling/test/Driver/CUDAMode.C
- interpreter/cling/test/Interfaces/invocationFlags.C
- interpreter/cling/tools/packaging/cpt.py
See root-project/cling#284
The original pull request was: https://github.com/root-project/root/pull/4616/commits
> Cling PR 284

- ui5/browser/controller/Browser.controller.js
This PR does :
* Solve some TODO in the browser controller (Change the Tab text AFTER the server reply)
* Change TreeTables selectors into UI5 selectors
*  Add the functionality of on close editor tab closing if the documents is modified and not saved, then add a warning popup before closing the tab and losing the data
> WebBrowser TODOs

- tree/tree/src/TTree.cxx
Previously it was 'just' updating the global state and not affecting (directly) the current TTree,
which is ... surprising ... for a non-static function.
> Make TTree::SetParallelUnzip behavior non-static.

- builtins/davix/CMakeLists.txt
One server is more stable than two servers.
> [cmake davix] Bump to 0.7.5; get from lcgpackages:

- gui/webdisplay/src/RWebWindowWSHandler.hxx
- gui/webdisplay/src/RWebWindowsManager.cxx
- js/changes.md
- js/scripts/JSRoot.openui5.js
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoPainter.js
- js/scripts/JSRootPainter.hist.js
- js/scripts/JSRootPainter.js
- js/scripts/JSRootPainter.v7hist.js
- ui5/eve7/geom.html
- ui5/eve7/view/GeomViewer.view.xml
Now basic openui5 config parameters can be provided via rootrc file:
* WebGui.openui5src:   alternative location for openui5 like https://openui5.hana.ondemand.com/
* WebGui.openui5libs:  list of pre-loaded ui5 libs like sap.m, sap.ui.layout, sap.ui.unified
* WebGui.openui5theme:  openui5 theme like sap_belize (default) or sap_fiori_3
Extend light configuration in webgeom - let configure kind and intensity of the light
> [webgui] let configure openui5 with rootrc file, provide light configurations in webgeom

- cmake/modules/SearchInstalledSoftware.cmake
- gui/browserv7/inc/ROOT/RBrowsable.hxx
- gui/browserv7/inc/ROOT/RBrowser.hxx
- gui/browserv7/inc/ROOT/RFileDialog.hxx
- gui/browserv7/src/RBrowsable.cxx
- gui/browserv7/src/RBrowser.cxx
- gui/browserv7/src/RFileDialog.cxx
- gui/webdisplay/src/RWebWindowWSHandler.hxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/controller/FileDialog.controller.js
Now there is always top element for browsing, which normally defined in the beginning
Relative to that top element working path is defined. Any changes in working path cannot go beyond top element. 
Provide latest openui 1.72.0 with base and fiori_3 themes
> RBrowser - change logic with top and current element

- bindings/pyroot_experimental/PyROOT/CMakeLists.txt
These two commits were initially included in PR #4279, but since they're completely unrelated it's probably better to put them in a separate one.
> [Exp PyROOT] Trivial changes fixing installation troubles and tests

- bindings/pyroot/src/TemplateProxy.cxx
Adds the support for square bracket syntax when instantiating function templates, in addition to the parenthesis syntax.
The goal is to be forward compatible with the new PyROOT, which only supports the square bracket syntax for instantiation of function templates (see https://sft.its.cern.ch/jira/browse/ROOT-10436).
This was discussed in the following experiments meeting:
https://indico.cern.ch/event/860690/
> [PyROOT] Support square bracket syntax for template instantiation

- gui/browserv7/inc/LinkDef.h
- gui/browserv7/inc/ROOT/RBrowsable.hxx
- gui/browserv7/inc/ROOT/RBrowserItem.hxx
- gui/browserv7/src/RBrowsable.cxx
- gui/browserv7/src/RBrowsableSysFile.cxx
- gui/browserv7/src/RBrowsableTDirectory.cxx
- gui/browserv7/src/RBrowsableTObject.cxx
- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
One can construct relatively complex structures of elements for using them in RBrowser
Like adding different items to top-level - home directory or top file directory
Provide support of ROOT collections and TFolder. 
Access top ROOT folder (and all sub-folders)
Access already opened files
Now data structures approximately that I want to see in RBrowser!
> RBrowser - support TFolder, TCollection, list of opened files

- ui5/eve7/controller/Summary.controller.js
This change colors tree items in Summary view according to REveSelection state. The colors have been chosen by sap_belize theme.
> [eve-7] Highlight tree items on EveElement selection

- bindings/pyroot/JupyROOT/helpers/utils.py
Jupyter may be configured to be served on different base url's, so we cannot assume that is accessible in `/`. This is the case, for example, when it's used together with JupyterHub (like SWAN), where the base url is `/user/_username_/`.
This PR fixes the way jsROOT is loaded in order to take that into account. 
For that, I've removed `/static/`, which forced the absolute url to the file, and let requireJs apply its own configuration (which takes the base url into account).
For Jupyterlab, I also load requireJs with the base url. In case requireJs is not available (maybe it will be possible to install Jupyterlab without Jupyter Notebooks in the future?), it falls back to a cdn to load it.
> [jupyter] correctly load jsroot

- gui/browserv7/src/RBrowser.cxx
- ui5/browser/browser.html
- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/Browser.view.xml
This PR add a terminal to the Javascript Browser
it can send commands and display the output
> [RBrowser] Web terminal

- interpreter/cling/lib/Interpreter/CIFactory.cpp
This patch allows us to resolve system-specific header search directories such as the location of libc.
This patch fixes experimental runtime_cxxmodules on OSX where libc is in /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/
cc: @oshadura
> [cxxmodules] Resolve modulemaps after the HeaderSearch is initialized.

- math/matrix/src/TMatrixDEigen.cxx
- math/matrix/src/TMatrixDSymEigen.cxx
> Implement assignment operator for TMatrixDEigen and TMatrixDSymEigen

- math/minuit2/src/Minuit2Minimizer.cxx
- tmva/tmva/inc/TMVA/BDTEventWrapper.h
- tmva/tmva/inc/TMVA/Event.h
- tmva/tmva/inc/TMVA/MethodPDERS.h
- tmva/tmva/test/DNN/CNN/TestMixedArchitectures.cxx
The header file is not needed and causes some failure on some architecture when compiling DNN GPU tests
Fix also a warning in a test
> Remove from Event.h ThreadLocalStorage.h header file

- README/CREDITS
I would prefer not to have my private mail address online available to everyone.
Please change it to my office mail address.
> Changed my E-Mail Address in the Credits

- core/base/inc/TVersionCheck.h
Pick up leftover breadcrumbs from https://github.com/root-project/root/pull/4625
Address Vassil's comment in second commit - see how it goes!
> Move gVersionCheck into ROOT::

- core/dictgen/src/rootcling_impl.cxx
> Fix FIXME: Print help info

- README/ReleaseNotes/v620/index.md
- core/dictgen/src/rootcling_impl.cxx
> [rootcling] Deprecate -r flag

- bindings/pyroot_experimental/pythonizations/python/ROOT/pythonization/_rtensor.py
- Warning: SyntaxWarning: "is not" with a literal. Did you mean "!="?
- See here for full discussion: https://bugs.python.org/issue34850
> [PyROOT exp] Fix syntax warning with py3.8

- core/dictgen/src/rootcling_impl.cxx
This fixes the deprecation taken root-project/root#4716.
We print the deprecation message but we still do what's intended.
cc: @reikdas
> Fix "Deprecation of -r flag from rootcling" 

- gui/browserv7/inc/LinkDef.h
- gui/browserv7/inc/ROOT/RBrowsable.hxx
- gui/browserv7/inc/ROOT/RBrowsableSysFile.hxx
- gui/browserv7/inc/ROOT/RBrowserItem.hxx
- gui/browserv7/inc/ROOT/RFileDialog.hxx
- gui/browserv7/src/RBrowsable.cxx
- gui/browserv7/src/RBrowsableSysFile.cxx
- gui/browserv7/src/RBrowser.cxx
- gui/browserv7/src/RFileDialog.cxx
- net/http/src/TCivetweb.cxx
- tutorials/v7/filedialog.cxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/controller/FileDialog.controller.js
- ui5/browser/model/BrowserModel.js
- ui5/browser/view/filedialog.fragment.xml
1. List all windows volumes like C:, Q:,...
2. Resolve windows links when appears
3. Let configure file types in FileDialog (also when starts from client)
> [rbrowser] better windows support, filters in FileDialog

- bindings/pyroot_experimental/pythonizations/python/ROOT/__init__.py
- bindings/pyroot_experimental/pythonizations/python/ROOT/_facade.py
- bindings/pyroot_experimental/pythonizations/src/PyROOTModule.cxx
- bindings/pyroot_experimental/pythonizations/src/PyROOTWrapper.cxx
- bindings/pyroot_experimental/pythonizations/src/PyROOTWrapper.h
- bindings/pyroot_experimental/pythonizations/src/TClonesArrayPyz.cxx
- bindings/pyroot_experimental/pythonizations/src/TMemoryRegulator.cxx
- bindings/pyroot_experimental/pythonizations/src/TMemoryRegulator.h
Port to PyROOT experimental the new teardown that was introduced in old PyROOT by:
https://github.com/root-project/root/pull/4687
> [Exp PyROOT] Port to experimental the new teardown introduced in old PyROOT

- bindings/pyroot_experimental/cppyy/CPyCppyy/src/CPPMethod.cxx
- bindings/pyroot_experimental/cppyy/CPyCppyy/src/Converters.cxx
- bindings/pyroot_experimental/pythonizations/src/CppCallablePyz.cxx
- bindings/pyroot_experimental/pythonizations/src/PyROOTWrapper.cxx
- bindings/pyroot_experimental/pythonizations/src/PyROOTWrapper.h
- bindings/pyroot_experimental/pythonizations/src/RVecPyz.cxx
- bindings/pyroot_experimental/pythonizations/src/TTreePyz.cxx
Fix a few warnings in PyROOT experimental builds observed e.g. here:
https://github.com/root-project/root/pull/4753
> [Exp PyROOT] Fix warnings

- roofit/roofitcore/src/RooCurve.cxx
[RF-8932] When a RooCurve is plotted as a filled polygon, one point has
to be added at the lower left of the plot to close the polygon.
A few lines of code have been cleaned up and simplified.
> [RF] Fix filled plotting of RooCurve.

- roofit/roofit/inc/RooNDKeysPdf.h
- roofit/roofit/src/RooNDKeysPdf.cxx
After enabling I/O for the NDKeysPdf, some members that are not being
streamed had to be initialised properly. Further, most 'mutable's have
been removed.
> [RF] Fix initialisation and const-correctness of RooNDKeysPdf.

- gui/browsable/inc/ROOT/Browsable/RProvider.hxx
- gui/browsable/inc/ROOT/Browsable/RSysFile.hxx
- gui/browsable/src/RProvider.cxx
- gui/browsable/src/RSysFile.cxx
- tutorials/v7/browser.cxx
- tutorials/v7/filedialog.cxx
1. Support .lnk file
2. Add R__LOAD_LIBRARY to tutorials macros
3. Use RProvider methods to check if file extension is supported
> RBrowser windows improvments

- bindings/pyroot_experimental/pythonizations/src/PyzCppHelpers.cxx
- bindings/pyroot_experimental/pythonizations/test/CMakeLists.txt
Fixes for the following test failures:
https://github.com/root-project/root/pull/4766#issuecomment-573859694
> [Exp PyROOT] Fixes for 32 bits

- README/CREDITS
- README/ReleaseNotes/v620/index.md
@Axel-Naumann Should we mention the the RooFitMore migration?
[no-ci]
> [NFC][RF] Release notes for RooFit

- graf3d/eve7/inc/ROOT/REveTableInfo.hxx
- graf3d/eve7/src/REveDataClasses.cxx
- graf3d/eve7/src/REveTableInfo.cxx
- ui5/eve7/controller/EveTable.controller.js
- ui5/eve7/view/EveTable.view.xml
* fixes in layout to remove unnecessary scrollbars
* implement tabular complete, show suggestions starting with "i." syntax
* provide public method list for tab complete of current and derived classes
* look for predefined column definition in current and base classes
> WebEve: Improvements in REveDataTable

- README/ReleaseNotes/v620/index.md
> [relnotes] Fix alphabet; wording improvement

- cmake/modules/RootConfiguration.cmake
Use `PATH_SUFFIXES` parameter of `find_program` macro of cmake
> [webgui] search Chrome and Firefox browsers in default dirs

- cmake/modules/SearchInstalledSoftware.cmake
> [webgui] add sap.tnt lib to openui5 package

- roofit/roofitcore/src/RooTreeDataStore.cxx
- roofit/roofitcore/src/RooVectorDataStore.cxx
[ROOT-10517] When reducing a RooDataSet, selecting multiple
ranges separated by ',' was ignored.
(cherry picked from commit 1da7698b7cbeccccc52fd9d66f826b92fdb521b8)
> [RF] Fix reducing a dataset with multipe ranges.

- hist/hist/inc/TGraphMultiErrors.h
- hist/hist/src/TGraphMultiErrors.cxx
- hist/histpainter/src/TGraphPainter.cxx
> Import PRs  #4777 and #4780

- ui5/browser/controller/Browser.controller.js
[skip-ci]
PR to resolve the bug of double full-screen buttons on window resize
> [Browser] Debug of the full-screen button on resize

- js/scripts/JSRoot.openui5.js
- js/scripts/JSRootCore.js
> JSROOT for ROOT 6.20

- hist/hist/src/TGraph.cxx
> remove reference to graphics in the TGraph definition

- rootx/CMakeLists.txt
- rootx/src/rootx.cxx
> [Backport 6.20] Disable SetLibraryPath for RPATH builds

- cmake/modules/SearchInstalledSoftware.cmake
> [master] Ensure PYTHON_PREFER_VERSION matches the version from PYTHON_EXECUTABLE

- README/ReleaseNotes/v620/index.md
Insert info about Eve-7 development in 3D Graphics Libraries chapter.
> Eve-7: add updates in v6-20 ReleaseNotes

- graf2d/gpad/src/TPad.cxx
> Fix memory leak in TPad::Print() 6.20

- roofit/roofitcore/src/RooStudyManager.cxx
Actual fix is in very end of PR, all others are formatting changes applied automatically by my editor
> Fix gSystem->ExpandPathName() memory leak in roofitcore

- io/io/src/TStreamerInfoActions.cxx
See https://mattermost.web.cern.ch/root/pl/4xn9mxn6hfy1zgog8ybe915sar
and https://gitlab.cern.ch/olupton/DictProblems
> In StreamerInfoActions always respect vecotr's custom-allocator

- html/src/THtml.cxx
Return value should be deleted
> THtml: fix memory leak with ConcatFileName

- io/io/src/TMapFile.cxx
char* members fName, fTitle, fOption should be released in destructor
> Fix memory leak in TMapFile

- tree/ntuple/inc/LinkDef.h
- tree/ntuple/v7/inc/ROOT/RField.hxx
- tree/ntuple/v7/inc/ROOT/RFieldValue.hxx
- tree/ntuple/v7/inc/ROOT/RFieldVisitor.hxx
- tree/ntuple/v7/inc/ROOT/RNTuple.hxx
- tree/ntuple/v7/src/RField.cxx
- tree/ntuple/v7/src/RFieldVisitor.cxx
- tree/ntuple/v7/src/RNTuple.cxx
- tree/ntuple/v7/test/CMakeLists.txt
- tree/ntuple/v7/test/CustomStruct.hxx
- tree/ntuple/v7/test/ntuple_print.cxx
- tutorials/v7/ntuple/ntpl001_staff.C
- tutorials/v7/ntuple/ntpl002_vector.C
Uses the field visitor to show values of a given entry. PR comes with general improvements of the field visitor.
> [ntuple] Implement RNTupleReader::Show()

- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/src/RooAbsData.cxx
- roofit/roofitcore/src/RooAbsPdf.cxx
- roofit/roostats/inc/RooStats/SPlot.h
- roofit/roostats/src/SPlot.cxx
- tutorials/roofit/rf402_datahandling.py
Collection of three short improvements:
- Better docs for SPlot
- Shorten run time of rf402 tutorial by removing unnecessary printouts
- [ROOT-10521] Better const-correctness in RooAbsData interface
> [RF] Improve documentation and interfaces.

- interpreter/llvm/src/tools/clang/lib/Basic/Diagnostic.cpp
This fixes ROOT-10504.
the script:
```
namespace boost { namespace mpl {
// Commenting the next line make the assert failure go away
struct TTUBE {};
}}
```
reproduce the problem with 'just' ROOT.  The trigger is the auto-loading of a library that has a dictionary with has forward decl string .. which all starts with:
```
static const char* fwdDeclCode = R"DICTFWDDCLS(
extern int __Cling_Autoloading_Map;
....
```
The order of parsing is (with many ellipsis):
```
"<<< cling interactive line includer >>>" : line 9  : #include “standalone.C”
standalone.C : line 1 : #pragma GCC diagnostic push
standalone.C : line 2 : #pragma GCC diagnostic ignored "-Wuninitialized"    // Inserted in Diag map
standalone.C : line 3 : #pragma GCC diagnostic ignored "-Wsign-conversion"  // Inserted in Diag map …
```
> Add support for DiagnosticEngine state change within recursive parsing.

- gui/gui/inc/TGApplication.h
- gui/gui/src/TGApplication.cxx
Wrong delete operator was used (it is @a5db401 commit)
To avoid any confusion in the future - just use TString instead
> Fix in TGApplication

- core/clingutils/test/CMakeLists.txt
- interpreter/cling/lib/Interpreter/CMakeLists.txt
- interpreter/cling/lib/Utils/CMakeLists.txt
Backport #4749: [ROOT-10472] Fix building clingutils
> Backport #4749: [ROOT-10472] Fix building clingutils

- core/base/src/TBase64.cxx
Remove unnecessary checks, use R__likely macro to gain performance of
main loop
> Improve performance of TBase64 coding/encoding

- tutorials/eve7/event_demo.C
- ui5/eve7/controller/GL.controller.js
- ui5/eve7/controller/Summary.controller.js
- ui5/eve7/lib/EveElements.js
1. Show element title as tooltip in summary and 3D views
2. Correctly handle dashes in drawing tracks
3. Highlight elements when selected in summary view
> Several Eve7 improvments

- js/changes.md
- js/scripts/JSRootCore.js
- js/scripts/JSRootGeoBase.js
- js/scripts/JSRootPainter.hist.js
- js/scripts/JSRootPainter.js
- tutorials/geom/geodemo.C
- tutorials/geom/webdemo.C
- tutorials/geom/webdemo.html
> Add support of TGeoTessellated to JSROOT

- core/base/src/TQCommand.cxx
Wrong delete operator was used
> Fix mem leak in TQCommand

- sql/mysql/src/TMySQLServer.cxx
Fix problem introduced by #4927
> [mysql] correctly handle table names in TMySQLServer::GetTablesList

- gui/browserv7/src/RBrowser.cxx
- ui5/browser/controller/Browser.controller.js
- ui5/browser/view/settingsmenu.fragment.xml
If enable double click on C, CPP or CXX file will run the macro, if the current that is not a code editor
> [Browser] Add option to run macro on double click

- cmake/modules/RootConfiguration.cmake
Fix for 423c8d203e3ea810c9b2d2f6606cf8f85c54916b
> [code] Add missing #include to operator+= probe

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDataFrame.cxx
> [NFC][RDF][Doc] Add more documentation for GetNRuns

- math/mathcore/src/GaussLegendreIntegrator.cxx
- math/mathcore/test/testIntegrationMultiDim.cxx
- math/mathmore/test/testMCIntegration.cxx
> Fix memory leak in GaussLegendreIntegrator::CalcGaussLegendreSamplingPoints

- tutorials/geom/visualizeWavefrontObj.C
No need to add "*" with "auto"
> Remove "useless" pointer

- ui5/eve7/controller/EveTable.controller.js
- ui5/eve7/controller/Ged.controller.js
- ui5/eve7/controller/Main.controller.js
- ui5/eve7/controller/Summary.controller.js
- ui5/eve7/css/eve.css
- ui5/eve7/lib/EveManager.js
- ui5/eve7/lib/EveScene.js
- ui5/eve7/view/Ged.view.xml
- ui5/eve7/view/Summary.view.xml
* Optimize items height in SummaryView
* Use check boxes for fRnrSelf 
* Handle elements highlight in SummaryView in both directions
* Move GED functionality to separated controller and view file
* Provide "Close" button for GED
* Handle elements update also for SummaryView and GED
> [eve7] optimize layout, separate GED, 

- tree/dataframe/inc/ROOT/RDF/RInterface.hxx
- tree/dataframe/src/RDFInterfaceUtils.cxx
- tree/dataframe/test/dataframe_cache.cxx
See https://sft.its.cern.ch/jira/browse/ROOT-10563
> [RDF][ROOT-10563] Allow caching of aliased columns

- ui5/eve7/controller/GL.controller.js
- ui5/eve7/lib/EveElementsRCore.js
- ui5/eve7/lib/EveScene.js
- ui5/eve7/lib/GlViewer.js
- ui5/eve7/lib/GlViewerJSRoot.js
- ui5/eve7/lib/GlViewerRCore.js
- ui5/eve7/lib/GlViewerThree.js
Renderer specific code has been moved to GlViewer classes:
* GlViewer is the "base class"
* GlViewerJSRoot for JSRoot GeoPainter
* GlViewerThree for THREE.js
* GlViewerRCore for the experimental RenderCore interface (just starting)
> [EVE-7] Refactor GL.controller for clean support of different renderers.

- roofit/roofitcore/inc/RooAbsData.h
- roofit/roofitcore/src/RooDataHist.cxx
- roofit/roofitcore/src/RooDataSet.cxx
- roofit/roofitcore/src/RooGlobalFunc.cxx
- roofit/roofitcore/src/RooIntegrator1D.cxx
- roofit/roostats/inc/RooStats/ProposalHelper.h
- test/stressRooFit_tests.cxx
Collection of two commits:
- Make errors for RooDataSet more obvious to users when reading from ascii.
- Strip down unnecessary includes.
> [RF] Small fixes for data classes in RooFit.

- graf3d/gl/src/TGLBoxPainter.cxx
- graf3d/gl/src/TGLVoxelPainter.cxx
> Manage the the Z minimum and maximum like for the BOX option

- ui5/eve7/controller/Ged.controller.js
- ui5/eve7/controller/Summary.controller.js
- ui5/eve7/view/Summary.view.xml
One can add more elements in the future
No need special workarounds to "hide" HTML elements of StandardItem.
Simplify data organization in model of SummaryView.
> WebEve - use fully custom item in SummaryView

- roofit/roofitcore/src/RooXYChi2Var.cxx
- test/stressRooFit_tests.cxx
- test/stressRooStats_tests.cxx
- tutorials/roofit/rf901_numintconfig.C
- tutorials/roofit/rf901_numintconfig.py
This fixes ROOT-10540 and ROOT-10536
> Apply fixes for when RooFitMore (MathMore) is not available.

- js/scripts/JSRootCore.js
- js/scripts/JSRootPainter.js
- ui5/eve7/controller/GL.controller.js
- ui5/eve7/controller/Ged.controller.js
- ui5/eve7/controller/Main.controller.js
- ui5/eve7/controller/Summary.controller.js
- ui5/eve7/css/eve.css
- ui5/eve7/index.html
- ui5/eve7/lib/EveManager.js
- ui5/eve7/lib/EveScene.js
- ui5/eve7/view/Summary.view.xml
Now highlight, selection, color, render flag can be changed offline - without running with the server.
Allows to reasonably use stored application like this one:
https://linev.github.io/eve7/
Fix small problem with switching to subview like:
https://linev.github.io/eve7/#/view/Default
> WebEve - implement offline functions, fix small problems

- core/dictgen/src/rootcling_impl.cxx
- core/meta/inc/TInterpreter.h
- core/metacling/src/TCling.cxx
- core/metacling/src/TCling.h
> Remove the deprecated in the previous release code.

- ui5/eve7/controller/Ged.controller.js
- ui5/eve7/controller/Summary.controller.js
- ui5/eve7/lib/EveManager.js
Provide hook to create custom model in SummaryView
Use proper method for setting fRnrSelf field (used in checkbox)
Prevent from using undefined values
> WebEve - small improvments

- test/sqlitetest.cxx
It is not good style to keep mem leak in test macro
> Fix mem leak in sqlitetest.cxx

- README/ReleaseNotes/v620/index.md
> [RF] Add line about SPlot to release notes.

- math/splot/src/TSPlot.cxx
Do not create TList dynamically - just use stack object
> [math] fix memory leak in TSPlot::SetTreeSelection

- io/io/inc/ROOT/RRawFile.hxx
- io/io/src/RRawFile.cxx
- io/io/test/RRawFile.cxx
- tree/ntuple/v7/src/RPageStorageFile.cxx
- tree/ntuple/v7/test/ntuple_minifile.cxx
> [rawfile] Return unique pointer from Create()

- tree/dataframe/CMakeLists.txt
- tree/dataframe/src/RSqliteDS.cxx
> [DF] Use RRawFile in SQlite data source

- core/foundation/test/testClassEdit.cxx
Part of root-project/root#5026
> Add regression test for ROOT-10574.

- graf3d/eve7/CMakeLists.txt
- graf3d/eve7/inc/LinkDef.h
- graf3d/eve7/inc/ROOT/REveBox.hxx
- graf3d/eve7/inc/ROOT/REveBoxSet.hxx
- graf3d/eve7/inc/ROOT/REveDigitSet.hxx
- graf3d/eve7/inc/ROOT/REveFrameBox.hxx
- graf3d/eve7/inc/ROOT/REveRGBAPalette.hxx
- graf3d/eve7/inc/ROOT/REveShape.hxx
- graf3d/eve7/src/REveBox.cxx
- graf3d/eve7/src/REveBoxSet.cxx
- graf3d/eve7/src/REveDigitSet.cxx
- graf3d/eve7/src/REveFrameBox.cxx
- graf3d/eve7/src/REveRGBAPalette.cxx
- tutorials/eve7/box.C
- tutorials/eve7/boxset.C
- ui5/eve7/lib/EveElements.js
Import BoxSet casses from original Eve.
> Eve-7 Import EveBox and EveBoxSet

- gui/gui/src/TGFileDialog.cxx
- gui/gui/src/TGListView.cxx
One should delete list of selected items
> [gui] fix memory leak in TGFileDialog 

- core/multiproc/src/TMPClient.cxx
Returned object must be destroyed
> [mutiproc] fix memory leak with use of fMon.GetListOfActivities()

- tree/treeplayer/src/TTreeReader.cxx
Related Jira issue: https://sft.its.cern.ch/jira/projects/ROOT/issues/ROOT-10544
> [NFC][ROOT-10544] Fix code example for TTreeReader

- graf3d/eve7/inc/ROOT/REveDataClasses.hxx
- graf3d/eve7/inc/ROOT/REveElement.hxx
- graf3d/eve7/src/REveDataClasses.cxx
- graf3d/eve7/src/REveDataProxyBuilderBase.cxx
> Eve7 - consistently use Bool_t in overriden methods

- hist/histv7/inc/ROOT/RAxis.hxx
- hist/histv7/src/RAxis.cxx
- hist/histv7/test/axis.cxx
...and make it part of the common RAxisBase interface.
> [RHist] Generalize GetBinIndexForLowEdge to irregular axes

- tutorials/multicore/mtbb101_fillNtuples.C
Made ARM 256 core builds fail!
> [tutorials] Do not overwrite files of other tutorials:

- hist/hist/inc/TGraphErrors.h
- hist/hist/src/TGraphErrors.cxx
> Add ApplyX function to TGraphErrors

- tutorials/CMakeLists.txt
- tutorials/dataframe/df104_HiggsToTwoPhotons.py
RDF tutorial using the new ATLAS Open Data analyzing Higgs to two photons events
Still needs some tuning of the plot, e.g., the xlabel is not shown properly.
Here a preview:
> [NFC][RDF] Add ATLAS Higgs to two photons example

- core/base/inc/TFileInfo.h
- core/rint/inc/TTabCom.h
- hist/hist/inc/TF1.h
- hist/hist/src/HFitImpl.cxx
- hist/unfold/inc/TUnfoldBinningXML.h
- io/io/inc/TMapFile.h
- io/io/src/TMapFile.cxx
- math/mathcore/inc/TStatistic.h
- math/mathcore/src/TStatistic.cxx
- math/mathcore/test/testGradient.cxx
- math/mathcore/test/testGradientFitting.cxx
- math/mathcore/test/testTStatistic.cxx
- roofit/roofitcore/inc/RooProofDriverSelector.h
Avoid exposing of such big class when not necessary - especially for TF1.h
> Remove TROOT.h from several ROOT includes

- README/ReleaseNotes/v622/index.md
> Update readme about web geom viewer

- README/ReleaseNotes/v620/index.md
> [Docs] Remove link to non-closed bug from release notes.

- etc/plugins/ROOT@@Detail@@RRawFile/P010_RRawFileDavix.C
- etc/plugins/ROOT@@Internal@@RRawFile/P010_RRawFileDavix.C
- io/io/inc/LinkDef.h
- io/io/inc/ROOT/RRawFile.hxx
- io/io/inc/ROOT/RRawFileUnix.hxx
- io/io/inc/ROOT/RRawFileWin.hxx
- io/io/src/RRawFile.cxx
- io/io/src/RRawFileUnix.cxx
- io/io/src/RRawFileWin.cxx
- io/io/test/RRawFile.cxx
- net/davix/inc/LinkDef.h
- net/davix/inc/ROOT/RRawFileDavix.hxx
- net/davix/src/RRawFileDavix.cxx
- net/davix/test/RRawFileDavix.cxx
- tree/dataframe/CMakeLists.txt
- tree/dataframe/src/RSqliteDS.cxx
- tree/ntuple/v7/inc/ROOT/RPageStorageRaw.hxx
- tree/ntuple/v7/src/RPageStorageRaw.cxx
> [DF] Turn hard dependency on Davix into a plugin

- bindings/pyroot_experimental/pythonizations/src/GenericPyz.cxx
- bindings/pyroot_experimental/pythonizations/test/pretty_printing.py
This solves (and tests) ROOT-9935.
> [Exp PyROOT][ROOT-9935] Handle case of pretty printing null objects

- tutorials/tmva/TMVACrossValidationApplication.C
Allows TMVACrossValidationApplication to run.
> correct jobname in TMVACrossValidationApplication

- tree/tree/src/TTree.cxx
Add actual number of cluster included in a Range.
Fix ROOT-10594
> Improve TTree::Print("clusters") output.

- js/scripts/JSRootCore.js
- js/scripts/JSRootPainter.v7.js
- tutorials/v7/draw_legend.cxx
Also update JSROOT for RColor handling
> Fix draw_legend.cxx tutorial [skip-ci]

- roofit/roofit/src/RooGamma.cxx
- tmva/tmva/src/DNN/Architectures/Reference/Propagation.hxx
- tmva/tmva/src/Factory.cxx
- tmva/tmvagui/src/efficienciesMulticlass.cxx
1. Implicit bool->double conversion
2. Minus operator for unsigned types
3. 32bit->64bit automatic conversion
> Fix several Windows warnings

- tmva/pymva/src/MethodPyKeras.cxx
> Backport: Fix in MethodPyKeras for using the new Tensorflow version 2

- cmake/modules/RootBuildOptions.cmake
> Change deprecation message for python option

- core/base/src/TSystem.cxx
> Protect multi-thread access to TSystem::fHelper.

- tutorials/v7/ntuple/ntpl004_dimuon.C
> [ntuple, tutorial] fix bad assert expression

- tutorials/tmva/TMVACrossValidation.C
- tutorials/tmva/TMVACrossValidationApplication.C
Add by default Deterministic splitting so the following tutorial TMVACrossValidationApplication can be run 
Add plotting of result histograms in TMVACrossValidationApplication tutorial
> Improve TMVA CrossValidation tutorials.

- tutorials/dataframe/df104_HiggsToTwoPhotons.py
- tutorials/dataframe/df105_WBosonAnalysis.py
* Remove empty lines
* Remove unnecessary braces in expressions
> [RDF] Clean-up df104 and df105

- graf3d/ftgl/CMakeLists.txt
> add missing GL includes in FTGL, v6.18  [ROOT-10631]

- tree/dataframe/src/RLoopManager.cxx
Even if something within the event loop throws, we still need to call `CleanUpTask` to make sure `SnapshotHelperMT::FinalizeTask` gets called, to avoid teardown issues due to input and output TTrees of a Snapshot being deleted concurrently.
> [DF] Call CleanUpTask even if event loop throws

- tree/dataframe/src/RLoopManager.cxx
- tree/dataframe/test/dataframe_simple.cxx
- tree/treeplayer/src/TTreeProcessorMT.cxx
> [DF] Throw instead of logging an error if a file or tree is unreadable

- bindings/jupyroot/python/JupyROOT/helpers/utils.py
> [notebook] add custom colors and gStyle in JSROOT drawings v6.20 [ROOT-10624][skip-ci]

- proof/proofx/src/TXProofServ.cxx
Otherwise one has to set dependency from ProofPlayer lib
> Use TVirtualProofPlayer in proofx

- core/metacling/src/TClingDeclInfo.cxx
- core/metacling/src/TClingDeclInfo.h
- core/metacling/src/TClingMethodArgInfo.cxx
- core/metacling/src/TClingMethodInfo.cxx
- core/metacling/src/TClingTypedefInfo.cxx
> [metacling] Refactor Property into base class. NFC.

- tree/tree/inc/TVirtualIndex.h
- tree/tree/src/TTree.cxx
- tree/treeplayer/inc/TChainIndex.h
- tree/treeplayer/inc/TTreeIndex.h
- tree/treeplayer/src/TChainIndex.cxx
- tree/treeplayer/src/TTreeIndex.cxx
This is a backport of #5246 , which fixes the same issue in master (#5239 introduced the problem in v6.20 too).
> [tree] avoid dependency from TreePlayer

- core/metacling/src/TClingTypeInfo.cxx
- core/metacling/src/TClingTypeInfo.h
> [metacling]Remove unused code - TClingTypeInfo::StemName()

- tree/treeplayer/src/TTreeProcessorMT.cxx
...to make it clear that we only use these functions in this same source file.
> [TreeProcMT] Move static functions to anonymous namespace

- test/CMakeLists.txt
> Add back excluded tests for C++ modules

- core/dictgen/src/rootcling_impl.cxx
Remove setting dicstream to /dev/null.
@vgvassilev
> rootcling: do not pipe to /dev/null
