tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_test.hxx

depends on #17597 and it's the other half of #17563. 
Copy-pasted text from it:
This is the last(*) PR of a series that adds proper support for incremental merging with Union mode, i.e. proper handling of deferred columns in the Merger.
With this change we should be able to support [ATLAS-like workflows](https://gitlab.cern.ch/amete/rootparallelmerger/-/blob/master/src/ParallelFileMerger.cpp?ref_type=heads) where the TFileMerger is used to incrementally construct an RNTuple from a sequence of files that may contain additional fields compared to the already-merged ones.
(*) at least for a minimal working case - more edge cases remain to be tested and likely fixed.
When Union-merging files containing compatible-but-different models (e.g. the second file contains an additional field), we …

[ntuple] properly support incremental merging with Union mode

---

tutorials/io/tree/imt_parTreeProcessing.C

This is explicitly recommended in the [TTreeReaderValue](https://root.cern/doc/v628/classTTreeReaderValue.html) documentation.

[tutorials] Use TTreeReaderArray to access collections

---

tree/treeplayer/inc/TTreeFormula.h
tree/treeplayer/src/TTreeFormula.cxx

since fManager is null and could lead to crashes if object is used later on
See https://github.com/root-project/root/pull/17707#discussion_r1953453947

[tree] reserve use of default TTreeFormula constructor only for ROOT I/O

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/NTupleStruct.hxx
tree/dataframe/test/NTupleStructLinkDef.h
tree/dataframe/test/datasource_ntuple.cxx

Not all collection-type fields should be read as RVecs, given that some collection types have different semantic meaning (e.g., sets). With this change, only `std::vector`, `std::array` and `ROOT::RVec` collection fields are added to the data source as RVecs.
The implemented change corresponds to the way collection column types are determined in TTree-based RDFs.

[DF][ntuple] Only create `RVec`-type columns for vectors, arrays and `RVec` fields

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTuple.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RFieldUtils.cxx
tree/ntuple/v7/src/RFieldUtils.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/test/CMakeLists.txt
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/ntuple_minifile.cxx
tree/ntuple/v7/test/ntuple_type_name.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/rfield_class.cxx

Fixes type name and type alias normalization, especially for types that involve meta (TClass etc.). Introduces patch version 1.0.0.1 of the specification.
Fixes #17570

[ntuple] fix type name normalization

---

documentation/doxygen/modifyNamespacesWebpage.sh

ROOT combines C++ and Python code. However, Doxygen incorrectly treats Python tutorials as namespaces. To address this, Doxygen developers suggested creating separate documentation for C++ and Python. This approach, however, does not align with ROOT's preference to integrate both languages in a single documentation.
The preferred solution is to post-process the documentation to remove incorrect namespaces. The script modifyNamespacesWebpage.sh was designed for this purpose. However, the script was incomplete, and some incorrect references remained, particularly in the search functionality. This new version of the script performs a more thorough cleanup.

[skip-ci] Clean namespaces

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx

With gcc-15, the lookups of `std::hash<xxx>` lead to the following error:
```
input_line_50:1:16: error: explicit instantiation of 'std::__hash_not_enabled' must occur in namespace 'std'
template class __hash_not_enabled<RooRealVar>;
```
Adding this class to the list of names that require "std::" fixes the error.
Fix #17456.

[PyROOT] Add __hash_not_enabled to names from std namespace.

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/rfield_class.cxx

Fix execution of I/O customization rules that have on-disk data member sources (inputs). Previously, `TVirtualObject::fObject` pointed to the target object, which is plain wrong (but happens to work in some cases). Now, rule inputs are examined, fields are created according to the provided input's type, and the data is read in a staging area that follows the memory layout of the on-disk class given by TClass. This staging area is now what `TVirtualObject::fObject` points to. 
Note that the target still has to be a transient member. This restriction is going to be lifted in a second PR.

[ntuple] Fix handling of I/O rules' inputs

---

.github/workflows/root-ci-config/buildconfig/alma9.txt

The new Pythia version 8.313 is missing to add the `inline` keyword to some functions in header files, resulting in linker errors like below.
This commit suggest to disable the Pythia8 interfaces until this regression is fixed upstream.
It was validated in the `alma9` docker container that adding the `inline` keywords indeed fixes the problem.
```
/usr/bin/ld: CMakeFiles/EGPythia8.dir/src/TPythia8.cxx.o: in function `TPythia8::ReadString(char const*) const':
/github/home/ROOT-CI/src/montecarlo/pythia8/src/TPythia8.cxx:302: undefined reference to `Pythia8::Pythia::readString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)'
/usr/bin/ld: CMakeFiles/EGPythia8.dir/src/TPythia8.cxx.o: in function `TPythia8::ReadConfigFile(char const*) const': …
```

[CI] Disable `pythia8` on alma9 gcc configuration

---

math/minuit/src/TLinearFitter.cxx
math/splot/inc/TSPlot.h
math/splot/src/TSPlot.cxx

Fix warnigs related to `snprintf`, like for example in TSplot.cxx:
```txt
/home/rembserj/code/root/math/splot/src/TSPlot.cxx: In member function ‘void TSPlot::FillXvarHists(Int_t)’:
/home/rembserj/code/root/math/splot/src/TSPlot.cxx:535:39: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
535 |       snprintf(name,sizeof(name), "x%d", i);
|
```

[math] Fix warnings related to `snprintf`

---

graf2d/graf/src/TCutG.cxx

Warn user about automatic overwrite of TCutG if same name
As done also in TDirectory::Append or when constructing a TH1
Suggested by https://root-forum.cern.ch/t/resolved-report-bug-lack-of-warning-with-crash-for-multiple-tcutg-object-having-the-same-name/62774/5

[graf] Warn user about automatic overwrite of TCutG if same name

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tree/ntuple/v7/test/ntuple_processor_chain.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx

Naming `RNTupleProcessors` is necessary to make the `RNTupleJoinProcessor` composable. Currently, we use the name of the auxiliary ntuple as prefix to the field names, but when this is abstracted to another processor, we need something else to identify these fields. Adding names to processors also fixes the current issue where two RNTuples with the same name cannot be joined. 
Providing a name is optional; by default, for single processors the name of the ntuple is used. For chain processors, the name of the first ntuple/inner processor in the chain is used. For join processors, the name of the primary ntuple is used.

[ntuple] Assign names to `RNTupleProcessor`s 

---

README/ReleaseNotes/v636/index.md
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/test/CMakeLists.txt
roofit/roofitcore/test/testRooAbsReal.cxx

When using the `Extended()` keyword argument in `createHistogram()` the
[docs](https://root.cern.ch/doc/master/classRooAbsReal.html#a9451168bb4159899fe1854f591f69814) say it has the following effect:
> Plot event yield instead of probability density (for extended pdfs only)
However, to get yields out of the probability densities, one has to not
only multiply with the total number of expected events, but also with
the bin volumes. I don't understand why the bin volume multiplication is
disable in *exactly* this case. This commit suggests to not do that
anymore, in order to be able to correctly produce predicted yields
histograms.
Thanks to the following forum post for noticing this:
https://root-forum.cern.ch/t/bin-content-of-pdf-and-generated-data/62370
This change of behavior is also …

[RF] Fix creating yield histograms from extended pdfs

---

roofit/roofitcore/res/RooFitImplHelpers.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooFitImplHelpers.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/stressRooFit_tests.h
roofit/roofitcore/test/testRooDataSet.cxx
roofit/roostats/src/MarkovChain.cxx

Consistently use `RooAbsData::reduce()` overload that takes RooFit command arguments in the RooFit code.
This allows us to deprecate all the other overloads one day, in the spirit of avoiding duplicate interfaces and user confusion.
Also, avoid some code repetition in setting up the cut expressions for slicing in RooAbsReal.cxx and RooSimultaneous.cxx.

[RF] Consistently use universal `RooAbsData::reduce()` overload

---

roofit/roofitcore/inc/RooAbsDataStore.h
roofit/roofitcore/inc/RooDataSet.h
roofit/roofitcore/inc/RooTreeDataStore.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsDataStore.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooTreeDataStore.cxx

1. The RooAbsDataStore has a virtual function `tree()` which is not meaningful for a general data store. This function should be removed.
2. The RooTreeDataStore has one `const` version on `tree()` and one non-const version. One returns a pointer and the other a reference, which is very confusing.
3. The RooTreeDataStore has some methods that just forward to the underlying TTree, but they were not used.
Changes to the data store classes can be made without impacting users because they are implementation details of the RooFit dataset classes.

[RF] Fix some design issues with the RooTreeDataStore

---

interpreter/CMakeLists.txt
interpreter/cling/CMakeLists.txt

This gives CMake full information about (transitive) library dependencies.
Fixes https://github.com/root-project/root/issues/17461

[interpreter] Use `find_package({LLVM,Clang})`

---

.github/workflows/root-ci-config/buildconfig/global.txt
cmake/modules/RootBuildOptions.cmake
cmake/modules/RootConfiguration.cmake
cmake/modules/RootMacros.cmake
config/Makefile.in
graf3d/CMakeLists.txt
interpreter/CMakeLists.txt
test/CMakeLists.txt

`cxxmodules` was deprecated at https://github.com/root-project/root/pull/12746

Some cleanups of CMake options

---

interpreter/cling/lib/Interpreter/CMakeLists.txt

This was deprecated in CMake version 3.20.0
https://cmake.org/cmake/help/latest/module/AddFileDependencies.html

[cling][NFC] Replace use of deprecated `AddFileDependencies`

---

core/gui/inc/TBrowser.h
core/gui/inc/TBrowserImp.h
core/gui/src/TBrowser.cxx
core/gui/src/TBrowserImp.cxx
gui/browserv7/src/RBrowser.cxx

Now dummy canvas is drawn. 
Instead create browser implementation again if it was deleted before
Correctly reset `TBrowser::fImp` pointer when 'normal' TRootBrowser is closed and deleted.
Up to now TBrowser was using no-longer-valid pointer
Small fix in `RBrowser::Show()` method - which is invoked by `TBrowser::Draw()` now

Implement `TBrowser::Draw()` method

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

The RNTupleMerger needs to bypass RUpdater and directly use RNTupleModelChangeset because it doesn't interface with a RNTupleWriter. So far it was duplicating the functionality of RUpdater::AddField() and RUpdater::AddProjectedField(), but the latter was incomplete and therefore late-model extending a projected field was broken. This PR moved the functionality of Add*Field() from RUpdater to RNTupleModelChangeset and has the Merger call those methods instead of duplicating their functionality. This fixes the bug. In addition, two unit tests are added related to projected fields, one of which covers this feature.

[ntuple] Properly late-model extend projected fields in the merger

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py
bindings/pyroot/pythonizations/src/PyROOTModule.cxx
bindings/pyroot/pythonizations/test/rdataframe_misc.py
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RInterface.cxx
tree/dataframe/src/RLoopManager.cxx

If a TTree dataset is created in a Python application and the RDataFrame constructor that takes in a `TTree &` parameter is used, the ownership of the TTree might result ambiguous for the user. Specifically, a Python user might expect the following to work out of the box:
```py
def foo():
ch = ROOT.TChain()
return ROOT.RDataFrame(ch)
```
Whereas it won't since the chain will become a dangling reference by the end of the function scope.
To cope with this unfortunate interaction of the C++ API and Python, we introduce an internal mechanism to keep track of the shared ownership of the *Python* proxy object. The implementation features a C++ wrapper in the ROOT CPython extension, which increases/decreases the Python reference count of a `PyObject *` data member. If this Python object is …

[df] Extend lifetime of Python-bound TTree dataset

---

math/minuit/src/TLinearMinimizer.cxx

since the verb see is what we meant to use.
Fixes #17754

[skip-ci][math][nfc] Do not use doxy \see special command

---

core/meta/inc/TClass.h
core/meta/src/TClass.cxx
core/meta/src/TProtoClass.cxx

`TClass` objects that do not have a dictionary and do not have interpreter info (this happens forwarded classes and in some cases STL collection) do not have enough information for a final value of their "Properties" and thus `TClass::Property` is set for them to re-run at each invocations.  In addition the start of the `Property` calculation was to reset `fStreamerImpl` to the default.  Consequently if 1 thread execute `Property` while the other is reading `fStreamerImpl`, the 2nd one will get an incorrect value.
This fixes the problem seen at https://github.com/cms-sw/cmssw/issues/47287#issuecomment-2657729709
The companion roottest PR is https://github.com/root-project/roottest/pull/1262
This fixes #17753

Prevent a race condition in fStreamerImpl value

---

core/meta/inc/TClass.h
core/meta/src/TClass.cxx
core/meta/src/TProtoClass.cxx

Backport of https://github.com/root-project/root/pull/17714.
`TClass` objects that do not have a dictionary and do not have interpreter info (this happens forwarded classes and in some cases STL collection) do not have enough information for a final value of their "Properties" and thus `TClass::Property` is set for them to re-run at each invocations.  In addition the start of the `Property` calculation was to reset `fStreamerImpl` to the default.  Consequently if 1 thread execute `Property` while the other is reading `fStreamerImpl`, the 2nd one will get an incorrect value.
This fixes the problem seen at https://github.com/cms-sw/cmssw/issues/47287#issuecomment-2657729709
This fixes #17753 for v6-32-00-patches.

[v632] Prevent a race condition in fStreamerImpl value

---

core/meta/inc/TClass.h
core/meta/src/TClass.cxx
core/meta/src/TProtoClass.cxx

Backport of https://github.com/root-project/root/pull/17714.
`TClass` objects that do not have a dictionary and do not have interpreter info (this happens forwarded classes and in some cases STL collection) do not have enough information for a final value of their "Properties" and thus `TClass::Property` is set for them to re-run at each invocations.  In addition the start of the `Property` calculation was to reset `fStreamerImpl` to the default.  Consequently if 1 thread execute `Property` while the other is reading `fStreamerImpl`, the 2nd one will get an incorrect value.
This fixes the problem seen at https://github.com/cms-sw/cmssw/issues/47287#issuecomment-2657729709
This fixes #17753 for v6-34-00-patches.

[v634] Prevent a race condition in fStreamerImpl value

---

geom/webviewer/src/RGeomHierarchy.cxx
geom/webviewer/src/RGeomViewer.cxx
gui/browserv7/src/RBrowser.cxx
gui/canvaspainter/src/RCanvasPainter.cxx
gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webgui6/src/TWebCanvas.cxx
tree/webviewer/src/RTreeViewer.cxx

Usage of `Reset()` method allows to avoid complex invocation tree 
during "trivial" cleanup of all sub-widgets of the `RBrowser`. 
Without such method "close connection callback" may try to invoke directly widget methods
at the moment when widgets were already destroyed.
Resolve problem with simple use case:
```
auto br = new TBrowser();
delete br;
```
Use in `TWebCanvas`, `RCanvasPainter`, `RGeomViewer`, `RTreeViewer`, `RBrowser`.
All these widgets used together in `RBrowser` and may affect destructor calling sequence.
Method has no effect for standalone widgets while there `RWebWindow` destructor 
called directly in context of widget (aka `TCanvas` or `RGeomViewer`) destructor.

Introduce `RWebWindow::Reset()` method

---

tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/test/ntuple_emulated.cxx

When constructing a RClassField we now require that the TClass is at least Interpreted. If not, we follow the same logic as when we have no TClass at all (i.e. either create an emulated field or fail, depending on the user options).
This PR fixes #17648

[ntuple] don't try to construct an Emulated TClass as a RClassField

---

core/metacling/src/CMakeLists.txt

No longer force `CppInterOpUnitTests` to build in metacling by adding a dependency to libCling (a bad hack). This target is not built since it is excluded from the build tree. Setting the property to off, triggers the `check-cppinterop` target, so ninja no longer complains about not finding the executables while building dictionaries

fix broken ninja builds with cppinterop

---

hist/hist/inc/TBackCompFitter.h
hist/hist/inc/TVirtualFitter.h
hist/hist/src/TVirtualFitter.cxx
math/minuit/inc/TFitter.h
math/minuit/inc/TLinearFitter.h
math/minuit/src/TLinearFitter.cxx

Provided implementation was wrong while
include pointer copy for `fCache` and `fMethodCall`
Plus copy/assign was forbidden for `TFitter` anyway, do it now for all fitter classes

[math] remove copy constr and assign operator for `TVirtualFitter`

---

net/net/src/TS3HTTPRequest.cxx
net/net/src/TSSLSocket.cxx
net/net/src/TWebFile.cxx

- Fix use of posix functions in `TS3HTTPRequest.cxx`
- Add SSL debug info in `TSSLSocket.cxx`
- Make `TWebFile` working with OpenSSL on Windows and simplify the code

[windows] Fix compilation with OpenSSL on Windows

---

hist/hist/src/THStack.cxx

Only when hstack painted for the first time, create subpads and
paint them immediately. Also check if histogram
was already painted on the pad - to avoid permanent repainting of subpads

Improve THStack pads painting

---

tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
tree/treeplayer/inc/TTreeReaderArray.h
tree/treeplayer/inc/TTreeReaderUtils.h
tree/treeplayer/src/TTreeReaderArray.cxx

TTreeReaderArray now exposes information on whether the underlying array type uses contiguous memory. This info is in turn used by RDataFrame to optimise reading collections as RVec.
Fixes https://its.cern.ch/jira/browse/ROOT-10823

Expose contiguousness from TTreeReaderArray and use it

---

roofit/roofitcore/src/RooFuncWrapper.cxx

Clad `master` provides different overloads for the gradient, and we need to resolve to the one that we want. Without the `static_cast` introduced in this commig, getting the function pointer to the gradient function would be ambiguous.

[RF] Compatibility fix with Clad master in getting gradient function

---

documentation/doxygen/filter.cxx
tutorials/hist/hist001_TH1_fillrandom.C
tutorials/hist/hist001_TH1_fillrandom.py
tutorials/hist/hist005_TH1_palettecolor.C
tutorials/hist/hist006_TH1_bar_charts.C
tutorials/hist/hist007_TH1_liveupdate.py
tutorials/hist/hist008_TH1_zoom.C
tutorials/hist/hist009_TH1_normalize.C
tutorials/hist/hist012_TH1_hksimple.C
tutorials/hist/hist015_TH1_read_and_draw.py
tutorials/hist/hist020_TH2_draw.C
tutorials/hist/hist022_TH2_palette.C
tutorials/hist/hist025_THStack_2d_palette_color.C
tutorials/hist/hist027_THStack_palette_color.C
tutorials/hist/hist029_TRatioPlot_simple.C
tutorials/hist/hist041_TProfile2Poly_realistic.C
tutorials/visualisation/graphics/compile.C
tutorials/visualisation/graphics/perceptualcolormap.C
tutorials/visualisation/graphs/gr010_approx_smooth.C
tutorials/visualisation/graphs/gr015_smooth.C
tutorials/visualisation/graphs/gr104_palettecolor.C

- Improve the preview display. The text was not wrapped correctly around the icon
- format some tutorials (missing dot)

[skip-ci] Improve preview display

---

tmva/pymva/test/Classification.C
tmva/pymva/test/testPyAdaBoostClassification.C
tmva/pymva/test/testPyGTBClassification.C
tmva/pymva/test/testPyKerasClassification.C
tmva/pymva/test/testPyKerasRegression.C
tmva/pymva/test/testPyRandomForestClassification.C
tmva/rmva/test/Classification.C
tmva/tmva/inc/TMVA/Classification.h
tmva/tmva/test/rreader.cxx
tutorials/machine_learning/RBatchGenerator_NumPy.py
tutorials/machine_learning/RBatchGenerator_PyTorch.py
tutorials/machine_learning/RBatchGenerator_TensorFlow.py
tutorials/machine_learning/TMVACrossValidationRegression.C
tutorials/machine_learning/TMVAMinimalClassification.C
tutorials/machine_learning/envelope/classification.C
tutorials/machine_learning/keras/ApplicationClassificationKeras.py
tutorials/machine_learning/keras/ApplicationRegressionKeras.py
tutorials/machine_learning/keras/ClassificationKeras.py
tutorials/machine_learning/keras/RegressionKeras.py

Use as input to TMVA tutorials and tests local files uploaded in github in the tutorials/machine_learning/data directory instead of getting them from root.cern.ch

[tmva] Use local input files instead of downloading them from root.cern.ch for tmva tests and tutorials

---

graf2d/graf/inc/TCrown.h
graf2d/graf/src/TCrown.cxx
hist/histpainter/src/THistPainter.cxx
js/modules/draw/more.mjs
js/modules/geom/geobase.mjs

Allows to draw ellipse segments with arbitrary Y to X ratio
Default is 1, can be optionally changed after object is created
Required for THistPainter, when `TCrown` used for 'col pol' drawing
Add support in JSROOT as well.

Add YXRatio paramater for `TCrown`

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx

The `RNTupleJoinProcessor` still referred to "index" in its member, method and variable names, as well as some comments. This PR renames them to properly reflect the new naming.

[ntuple] Reflect `RNTupleJoinTable` name change in `RNTupleJoinProcessor`

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
tree/dataframe/test/dataframe_snapshot.cxx

Introduces a new option in RSnapshotOptions.hxx to allow users to configure the default basket size of new branches when using RDataFrame::Snapshot. Modify SetBranchesHelper in ActionHelpers.hxx to honor this option.
1. Add a fBasketSize field to RSnapshotOptions to store the user-defined basket size.
2. Update SetBranchesHelper to apply the specified basket size when creating output.
3. Ensure backward compatibility by maintaining the current default behavior if no custom size is set.
:)
- [✅] tested changes locally
- [❌] updated the docs (if necessary)
This PR fixes #17418

[RDF] Add option to change default basket size in RDataFrame Snapshot

---

tree/dataframe/test/dataframe_nodes.cxx

Small followup to https://github.com/root-project/root/pull/17739
Use the RLoopManager constructor without a data source in the simple tests that just check for the validity of the constructed RLoopManager.

Use appropriate constructor in test

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx
tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/RFieldUtils.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RFieldUtils.cxx

This PR adds the possibility of using different (valid) types for RDF columns in the `RNTupleDS`. A notable example is the interchangeable use of `std::vector<T>` and `ROOT::RVec<T>`. We enable this by introducing *alternative prototype fields*, which are created on-demand when a column reader is requested for a type other than the original prototype field that was added when the datasource was constructed. 
An error is thrown in `RNTupleColumnReader` in case the alternative column type is incompatible with the on-disk type of the corresponding field.
Fixes #16034 and #10749.

[ntuple] Allow for alternative column types in `RNTupleDS`

---

tree/ntuple/v7/inc/ROOT/RNTupleJoinTable.hxx
tree/ntuple/v7/src/RNTupleJoinTable.cxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_join_table.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx

This is the first PR (out of a yet unknown number) related to the refactoring and extension of the `RNTupleJoinTable` to enable more complex join table structures which may contain entries from more than one RNTuple. This is necessary to make the `RNTupleJoinProcessor` fully composable (see also #17132).
The changes in this PR are twofold:
1. Join tables have to now be build explicitly through a call to `RNTupleJoinTable::Build`.
2. The `RNTupleJoinTable` doesn't store the page source as a data member anymore. Instead, this page source is passed to `RNTupleJoinTable::Build`.

[ntuple] Decouple `RPageSource` from `RNTupleJoinTable`

---

core/clingutils/src/TClingUtils.cxx
core/metacling/src/TClingCallbacks.cxx
core/metacling/src/TClingClassInfo.cxx
interpreter/cling/include/cling/Interpreter/DynamicLibraryManager.h
interpreter/cling/lib/Interpreter/AutoSynthesizer.cpp
interpreter/cling/lib/Interpreter/AutoloadCallback.cpp
interpreter/cling/lib/Interpreter/BackendPasses.cpp
interpreter/cling/lib/Interpreter/DeclUnloader.cpp
interpreter/cling/lib/Interpreter/DynamicLookup.cpp
interpreter/cling/lib/Interpreter/Interpreter.cpp
interpreter/cling/lib/Interpreter/InvocationOptions.cpp
interpreter/cling/lib/Interpreter/LookupHelper.cpp
interpreter/cling/lib/Interpreter/Transaction.cpp
interpreter/cling/lib/MetaProcessor/MetaParser.cpp
interpreter/cling/lib/Utils/AST.cpp
interpreter/cling/lib/Utils/Paths.cpp
interpreter/cling/lib/Utils/SourceNormalization.cpp

This was removed in LLVM19
https://github.com/llvm/llvm-project/commit/deffae5da123b32098914d8346bf4358a6792bdc
This will reduce the changes needed when upgrading LLVM versions

[cling][NFC] Use StringRef::operator== instead of StringRef::equals

---

hist/histpainter/src/THistPainter.cxx

When demonstrating drawing of shifted text,
draw first histogram with "COL" option,
then other with "TEXT SAME" option.

[histpainter] adjust macros in docu [skip-ci]

---

hist/hist/src/TFormula.cxx
hist/hist/test/test_TFormula.cxx

Extend TFormula's syntax for polynomials
1. Modified HandlePolN to accept named parameters and variables
2. Modified the HandlePolN to use modern c++ functions like std::getline
3. Added tests for the same in test_TFormula.cxx
Allow variables in TFormula Pol functions like
`TF1 f1("f1", "pol1(x, 0)");`
`TF1 f1("f1", "pol1(x, [A], [B])");`
- [✅] tested changes locally
- [❌] updated the docs (if necessary)
This PR fixes #16794

[TFormula] TFormula: Pol functions do not accept variable name as arguments 

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx

The PR fixes typos, makes sure the tenses are consistent, adds missing documentation, etc.

[skip-ci][ntuple] Fixup `RNTupleProcessor` docs

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

The interpolation code for HistFactory excessively used `std::pow` since the code was written ages ago (see here in [ROOT 5](https://github.com/root-project/root/blob/v5-34-00-patches/roofit/histfactory/src/FlexibleInterpVar.cxx#L329)).
Replacing it with simple multiplications and in one place trading it for the faster `std::exp` results in significant speedups: roughly 30 % faster in the ATLAS Higgs combination benchmark (even 50 % faster in the case of AD, further increasing the benefit you get from using AD in that benchmark. Also the legacy evaluation backend is affected by this improvement thanks to the shared code in `MathFuncs.h`, so any HistFactory user will benefit from this change.

[RF] Avoid using `std::pow` in interpolation code

---

hist/hist/src/TFormula.cxx

#17623 introduced a warning (that is, a compile error in `dev=ON`) due to improper int comparisons.
This PR fixes it. I chose to cast to `Int_t` rather than `size_t` to automatically handle the case where `degree < 0` (which I assume is "impossible" but you never know, given that `degree` is derived from string parsing above...)

[hist] Fix invalid int comparison and printf usage in TFormula

---

tree/ntuple/v7/src/RFieldUtils.cxx
tree/ntuple/v7/test/ntuple_emulated.cxx

... in `GetCanonicalTypePrefix`: This is required so substring operations work correctly in `RFieldBase::Create`, for example to get the item type of containers. It is hard to observe from the outside since template parameters are further processed in `GetRenormalizedTypeName` and `GetNormalizedUnresolvedTypeName` respectively. As a test, check field emulation of a templated type inside a vector.

[ntuple] Remove blanks between angle brackets earlier

---

tree/ntuple/v7/test/ntuple_emulated.cxx

Commit 3df3375912 made the fields of `RCreateModelOptions` into getters/setters.

[ntuple] Fix build of ntuple_emulated test

---

cmake/modules/RootMacros.cmake

In CMake, `foreach(.. RANGE start stop)` is inclusive for both start and stop, so we need to decrement the LIST_LENGTH to get the desired logic.
I noticed this logic error when I changed something in ROOT that resulted one package to have *exactly* 100 header files, triggering the following error:
```txt
CMake Error at cmake/modules/RootMacros.cmake:1293 (list):
list begin index: 100 is out of range 0 - 99
Call Stack (most recent call first):
CMakeLists.txt:391 (ROOT_CREATE_HEADER_COPY_TARGETS)
```
Follow-up on 4d0f60386ce.

[CMake] Fix range splitting logic in ROOT_CREATE_HEADER_COPY_TARGETS

---

tree/dataframe/test/datasource_ntuple.cxx

The return type from the previous Define call is float, so use the same type for the Take action.
This is a completely non-functional change for the test, but in a local branch it was detected by some other modifications I am doing that anticipate the time of checking for type mismatch in the requested type of computation graph nodes.

[df] Specify more precisely action type in test

---

tree/ntuple/v7/inc/ROOT/RNTupleJoinTable.hxx
tree/ntuple/v7/src/RNTupleJoinTable.cxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_join_table.cxx

With this change, `RNTupleJoinTable` returns all matching entries in all cases, and the responsibility of deciding which entry to use is more explicitly put on the downstream application. This is fine, because these decisions need to be made downstream anyways. The templated interface is removed as well, as its practical use is currently not clear enough.
The `RNTupleJoinTable` itself is in the process of a redesign, where it will store the mappings of join values to entry indexes in partitions. With this change, it won't be possible to directly return the pointer to the list of entry indexes stored in the join table anymore. The changes in this commit already anticipate this redesign by changing the return type of `GetEntryIndexes`.

[ntuple] Simplify `RNTupleJoinTable` probe interface

---

hist/hist/inc/TGraph2D.h
hist/hist/src/TGraph.cxx
hist/hist/src/TGraph2D.cxx
hist/hist/src/TH1.cxx
hist/hist/src/TMultiGraph.cxx

Fixes https://github.com/root-project/root/issues/17809

[hist] Add TGraph2D::GetFunction as with TGraph

---

.ci/format_script.sh

The main purpose of this PR is to expose directly the version number of the clang-format used by the CI.
The secondary purpose is to shorten and clarify the output.
NOTE: An intentional formatting error is introduced to show the error output and will (of course) be removed before merging.

ci: improvement of clang-format step

---

core/base/inc/TNamed.h
core/base/inc/TObject.h
core/base/src/TNamed.cxx
core/base/src/TObject.cxx
hist/hist/src/TGraph.cxx
hist/hist/src/THStack.cxx
hist/hist/src/TMultiGraph.cxx
hist/hist/src/TPolyMarker.cxx

Store invocation of object constructor in the created macro.
Replaces several lines in typical `SavePrimitive()` implementation.
PR also includes `TNamed::SavePrimitiveNameTitle` method as small extension.
And several examples for classes like TGraph, THStack, TPolyMarker how introduced methods can be used.
If approach is fine, one can simplify most of existing `SavePrimitive()` implementations.
At the same time one can revise code there.

Introduce `TObject::SavePrimitiveConstructor()` method

---

math/minuit2/inc/Minuit2/MnHesse.h
math/minuit2/inc/Minuit2/MnUserFcn.h
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnHesse.cxx
math/minuit2/src/MnUserFcn.cxx
math/minuit2/src/ModularFunctionMinimizer.cxx

It was figured out with `perf` and `flamegraph.pl` that the main
performance bottleneck when using Minuits Hesse on RooFit likelihoods is
the transformation to internal Minuit parameters in MnHesse, which is a
relatively expensive trigonometric operation. It is done for all
parameters at every function operation, even if only one parameter is
changed. We need to do order n-squared function calls for the Hessian.
The total runtime of calling the RooFit function itself scales only
linearly with the number of parameters, thanks to the caching in RooFit.
However, the parameter transformation in MnHesse implements no caching
and therefore has quadratic cost.
This PR implements caching for the transformed parameters to make
this bottleneck go away completely.
With the changes in this PR, the …

[Minuit2] Cache transformed parameter values in MnHesse

---

io/io/test/TFileMergerTests.cxx
tree/tree/src/TTree.cxx

Alternative to https://github.com/root-project/root/pull/17650 as suggested by pcanal
Fixes #14558
Fixes #12510

 [TTree] when merging, ignore trees without branches

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx
tree/ntuple/v7/test/rfield_streamer.cxx

fixes all remaining known cases of mishandling of deferred columns in the RNTupleMerger, most notably the inability of merging a file with a deferred column in the first source and mishandling of sources with a deferred column unaligned with cluster boundaries.
Several tests are added to cover those cases.
- properly compress synthesized zero pages
- don't generate leading zero pages for columns when not needed (use the deferred column machinery instead).

[ntuple] Fix remaining issues with deferred columns in RNTupleMerger

---

requirements.txt

The newest `ipython` broke the newest  metakernel package.
See also the upstream report:
https://github.com/Calysto/metakernel/issues/288
Restricting the ipython version, at least until the problem is fixed upstream in the ipython/metakernel duo, will solve the problem for all ROOT branches, because the `requirements.txt` is used for all CI images.
I was a bit hesitant if this is really the solution because the problem seems to be platform-dependent. However, that seems to be because ipython 9.0.0 has not reached all of pips channels yet. Compare for example these build logs:
Ubuntu 24.04, picks up `ipython==8.33.0`
https://productionresultssa15.blob.core.windows.net/actions-results/7a5c1f23-ff80-468b-80dd-33e4511651f6/workflow-job-run-5f5bc846-a2a7-5fbf-b892-8ca7512cbcea/logs/job/job-logs …

Restrict `ipython<9.0.0` in requirements.txt

---

io/io/test/TFileMergerTests.cxx

A missing include in #17652 causes a compiler warning (aka an error in dev=ON)

[io] TFileMergerTest: add missing TBranch include

---

tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_endian.cxx
tree/ntuple/v7/test/ntuple_zip.cxx

... eventually removing all member methods of RNTuple(De)Compressor; see the individual commits for more details. As a visible result, this saves 16 MiB of internal compression buffer per page sink.

[ntuple] Simplify and clean up compression

---

tree/ntuple/v7/doc/BinaryFormatSpecification.md

This PR fixes a minor typo in the RNTuple spec. It showed `SplitInt32` as having 64 bits instead of 32.

[rntuple] Fix minor typo in the spec

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RInterfaceBase.hxx
tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/inc/ROOT/RSnapshotOptions.hxx
tree/dataframe/src/RDFActionHelpers.cxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/src/RInterface.cxx
tree/dataframe/src/RInterfaceBase.cxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/NTupleStruct.hxx
tree/dataframe/test/NTupleStructLinkDef.h
tree/dataframe/test/dataframe_snapshot_ntuple.cxx

This PR adds a first iteration of snapshotting to RNTuple from an RDataFrame. It uses the existing `Snapshot` interface, with an addition to `RSnapshotOptions`, `kOutputFormat`. This option can be set to write to either TTree, RNTuple, or take the default choice. Currently the default choice means that TTree will be used as the output format, also if the input format is RNTuple. In this case, a warning will be issued to the user. With the changes in this PR, snapshotting from TTree to RNTuple is not yet possible, because it requires additional conversion for certain branch types considered out of scope for this PR, similar to what is currently done with the RNTupleImport. Using this functionality a follow-up PR will add support for Snapshots from TTree to RNTuple.
As mentioned, the …

[DF] Add initial implementation for snapshotting to RNTuple

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

The problem around for which the added `-j 1` was a workaround was reported and solved upstream in CMake:
https://gitlab.kitware.com/cmake/cmake/-/issues/26398
It's better to not do the workaround for the fixed CMake versions anymore, because actually the increase in build time can be quite significant.
On my machine, building ROOT `master` with a warm ccache takes 5m33s with 32 threads, which reduces to 4m6s without the workaround. I did the measurements twice each, so they are reproducible!
Follows up on #16682.

[CMake] Only build Clad on a single core if the workaround if needed

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx

':' was the previous separator, but we now use '.'

[skip-ci][ntuple] Fix doc comment of RNTupleMergeOptions

---

tree/tree/src/TChain.cxx
tree/treeplayer/src/TTreeIndex.cxx
tree/treeplayer/test/CMakeLists.txt
tree/treeplayer/test/ttreeindex_getlistoffriends.cxx

Fixes https://github.com/root-project/root/issues/17820
Full analysis of the issue follows:
1. TChain::GetEntries calls TChain::LoadTree(TTree::kMaxEntries - 1)
2. Internally, this will set fReadEntry == -2, due to how LoadTree works and the fact it's trying to read beyond the last entry in the chain
3. This has an effect here https://github.com/root-project/root/blob/f33985dca2d6bc505e83498f7b4561ddd969be17/tree/tree/src/TChain.cxx#L1675-L1679 where `t` is the current friend being traversed in the list of friends of the *chain*. We call `t->LoadTree(TTree::kMaxEntries - 1)`.
4. Inside the call to LoadTree on the friend, we reach this line https://github.com/root-project/root/blob/f33985dca2d6bc505e83498f7b4561ddd969be17/tree/tree/src/TChain.cxx#L1484 where the fTree data member of the …

[tree] Fix interaction between GetEntries and GetListOfFriends

---

tree/ntuple/v7/src/RFieldUtils.cxx
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/ntuple_type_name.cxx

Templated classes can have nested types that can themselves be templated. Until now, `SplitTypePrefixFromTemplateArgs` assumed that there is only one set of template arguments at the end. The function is replaced by `FindTemplateAngleBrackets` which is then used by `GetRenormalizedTypeName` and `GetNormalizedUnresolvedTypeName` to extract the template arguments and construct a normalized type name.
Fixes #17848

[ntuple] Fix type normalization in template classes

---

tree/ntuple/v7/src/RFieldUtils.cxx

```
warning: declaration of ‘i’ shadows a previous local [-Wshadow]
```

[ntuple] Fix GCC shadow warning

---

core/base/inc/TObject.h
core/base/src/TObject.cxx
hist/hist/inc/TGraph.h
hist/hist/src/TGraph.cxx
hist/hist/src/TGraphAsymmErrors.cxx
hist/hist/src/TGraphBentErrors.cxx
hist/hist/src/TGraphErrors.cxx
hist/hist/src/TGraphMultiErrors.cxx
hist/hist/src/TPolyMarker.cxx

1. Let store array of doubles as plain C array in output macro
2. Returns unique variable name which used then in other operation
3. Use in `TPolyMarker` to speedup creation of such objects, for 50K markers speedup from 37s to 0.5s
4. Use method in `TGraph` classes, removing `TGraph::SaveArray` 
5. Improve `SavePrimitive` methods of `TGraph` - based classes

Introduce TObject::SavePrimitiveArray

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Follows up on e3fbf24ea1ed8c8, fixing a typo in a number that was committed there and not detected in the PR because of no full rebuild.

[CMake] Compare to the right CMake version for `-j 1` workaround

---

tree/ntuple/v7/inc/ROOT/RColumn.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleRange.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/inc/ROOT/RPage.hxx
tree/ntuple/v7/inc/ROOT/RPagePool.hxx
tree/ntuple/v7/src/RNTupleView.cxx
tree/ntuple/v7/test/ntuple_pages.cxx

- renames `RNTupleClusterRange` to `RNTupleLocalRange` as we previously decided.
- moves `RNTupleGlobalRange` and `RNTupleLocalRange` out of Experimental

[ntuple] Move RNTuple*Range out of Experimental

---

geom/geom/src/TGeoManager.cxx

In this case do not use stored "GeomPainter.Name" value, but directly check configured web display for pad
Should behaves like TCanvas when web mode checked if batch flag enabled.
Backport of https://github.com/root-project/root/pull/17680

[geompainter] correctly handle drawing on the pad [6.34]

---

tree/tree/src/InternalTreeUtils.cxx

as suggested by pcanal in https://github.com/root-project/root/issues/17843#issuecomment-2698615806
Leak is as follows:
```
==1641195==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 120 byte(s) in 3 object(s) allocated from:
#0 0x7f59e336f1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
#1 0x7f59e2c9c34b in TStorage::ObjectAlloc(unsigned long) /opt/root_src/core/base/src/TStorage.cxx:293
#2 0x557a56766ec9 in TObject::operator new(unsigned long) /home/user/builds/build-root_src-Desktop-Debug/include/TObject.h:183
#3 0x7f59e20064e2 in ROOT::Internal::TreeUtils::RecursiveGlob(TList&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /opt/root_src/tree/tree/src/InternalTreeUtils.cxx:491
#4 …
```

[tree] fix memleak detected by asan

---

README/ReleaseNotes/v632/index.md

as discussed in https://github.com/root-project/root/pull/16410#issuecomment-2345647671

[skip-ci] mention auto deprecation in release notes

---

tmva/sofie/inc/TMVA/ROperator_Shape.hxx
tmva/sofie/inc/TMVA/ROperator_TopK.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/SOFIE_common.cxx

Fix the broadcasting function to use as input a constant pointer to the data or a std::span<const T>
Fix also the generated code for Shape in cse the output tensor is constant

[tmva[sofie] Fixes Broadcasting for constant input data

---

math/minuit2/inc/Minuit2/MnMatrix.h
math/minuit2/inc/Minuit2/Numerical2PGradientCalculator.h
math/minuit2/src/CMakeLists.txt
math/minuit2/src/MnFcnCaller.h
math/minuit2/src/MnHesse.cxx
math/minuit2/src/Numerical2PGradientCalculator.cxx
math/minuit2/src/ParametricFunction.cxx

Just like it was already done in MnHesse, the
Numerical2PGradientCalculator now caches the transformed parameter
values.
This speeds up the minimization in the ATLAS Higgs combination benchmark
by 10 % from 30.7 seconds down to 27.6 s.
In more optimized RooFit-based likelihoods, the relative speedup is even
more significant. Minimizing the CMS Higgs discovery likelihood is 50 %
faster, for example.

[Minuit2] Also cache transformed parameter values in gradient evaluation

---

bindings/pyroot/pythonizations/test/string_view.py

The string representation of the dataframe might change and it is not the purpose of this test anyway.
Part 2 of N for https://github.com/root-project/root/pull/17895

[NFC] Do not rely on string representation in test

---

hist/hist/src/TAxis.cxx

See https://root-forum.cern.ch/t/bug-or-feature-in-ttree-draw/62862/16
Related: https://github.com/root-project/root/pull/17689

[skip-ci] clarify behavior and rounding precision limitations of FindBin

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

fixes an edge case in the Merger where the input source(s) have an empty schema. Adds unit tests for the various cases.

[ntuple] Merger: handle RNTuples with empty schemas

---

tree/dataframe/inc/ROOT/RArrowDS.hxx
tree/dataframe/inc/ROOT/RCsvDS.hxx
tree/dataframe/inc/ROOT/RDF/RLazyDSImpl.hxx
tree/dataframe/inc/ROOT/RDataSource.hxx
tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/inc/ROOT/RRootDS.hxx
tree/dataframe/inc/ROOT/RSqliteDS.hxx
tree/dataframe/inc/ROOT/RTrivialDS.hxx
tree/dataframe/inc/ROOT/RVecDS.hxx
tree/dataframe/src/RSqliteDS.cxx
tree/dataframe/test/RStreamingDS.hxx

The fNSlots data member is used by all data sources, thus it can be upstreamed to the base class.
Part 3 of N for https://github.com/root-project/root/pull/17895

Simplify nslots in RDataSource

---

tree/ntuple/v7/test/ntuple_zip.cxx

GCC complains (with -O0):
```
warning: ‘x’ may be used uninitialized [-Wmaybe-uninitialized]
```

[ntuple] Initialize variable in ntuple_zip test

---

bindings/jupyroot/python/JupyROOT/helpers/handlers.py

Only waiting 0.25 seconds before printing "Asyncronous" should increase the probability to have this string printed by the time the main thread waits one second, which is what the unit test expects.
Hopefully avoids test failures like these:
https://github.com/root-project/root/actions/runs/13712379279/job/38351177011#step:13:22736

[Python] Reduce time before asyncronous run in JupyROOT unit test

---

tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/src/RColumnElement.hxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleSerialize.cxx
tree/ntuple/v7/src/RNTupleUtil.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_compat.cxx
tree/ntuple/v7/test/ntuple_test.hxx

Moving the following out of Experimental:
- `MakeAliasedSharedPtr`
- `MakeUninitArray`
- `EnsureValidNameForRNTuple`
- Some internal test values (e.g. `kTestFutureType`)

[ntuple] Move Internal RNTupleUtils out of Experimental

---

tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx
tree/treeplayer/inc/TBranchProxy.h
tree/treeplayer/inc/TTreeReaderArray.h
tree/treeplayer/inc/TTreeReaderUtils.h
tree/treeplayer/inc/TTreeReaderValue.h
tree/treeplayer/src/TBranchProxy.cxx
tree/treeplayer/src/TTreeReaderArray.cxx

TTreeReaderValue and TTreeReaderArray now expose APIs to get the current value of the branch they are proxying without knowing its type. For the case of arrays, the size of the type of the value is also exposed, so that readers can correctly interpret the collection type when giving it back to the user. The new APIs are used in RTreeColumnReader classes, thus RDataFrame does not need anymore to know the type of the value being requested by the user when reading from TTree.
Part 1 of N for https://github.com/root-project/root/pull/17895

Enable untyped reading of TTree data

---

documentation/doxygen/makeinput.sh

If the tutorials build is deactivated the script CleanNamesspaces.sh is not generated and we get an error.

[skip-ci] activate back the tutorials

---

tutorials/machine_learning/TMVA_RNN_Classification.C

When generating the doc for this tutorial it seems that from time tot time it enters an infinite loop of messages like:
```
Error in <TString::AssertElement>: out of bounds: i = 75, Length = 74
```
I was not able able to reproduce it locally. Lettsee if disabling its execution during the doc build will avoid that loop.

[skip-ci] Disable the execution of TMVA_RNN_Classification.C

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RPageNullSink.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RFieldBase.cxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RFieldSequenceContainer.cxx
tree/ntuple/v7/src/RFieldVisitor.cxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleParallelWriter.cxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/src/RNTupleWriter.cxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx
tree/ntuple/v7/test/ntuple_emulated.cxx
tree/ntuple/v7/test/ntuple_limits.cxx
tree/ntuple/v7/test/ntuple_model.cxx
tree/ntuple/v7/test/ntuple_modelext.cxx
tree/ntuple/v7/test/ntuple_multi_column.cxx
tree/ntuple/v7/test/ntuple_type_name.cxx
tree/ntuple/v7/test/ntuple_types.cxx
tree/ntuple/v7/test/rfield_streamer.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleImporter.cxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

Following the same pattern as in `RNTupleModel`, the const version of `GetSubFields` become `GetConstSubfields` and the non-const becomes `GetMutableSubfields`.
Note that the `F` is not capitalized anymore because we decided to keep "subfields" as a single word throughout the whole API.
In addition, the `GetRegisteredSubfields` method becomes `GetRegisteredSubfieldNames` for clarity.

[ntuple] Rename Subfields related methods to be more consistent

---

hist/hist/inc/TEfficiency.h
hist/hist/inc/TF1.h
hist/hist/inc/TGraph2D.h
hist/hist/inc/TH1.h
hist/hist/src/TEfficiency.cxx
hist/hist/src/TF1.cxx
hist/hist/src/TF2.cxx
hist/hist/src/TF3.cxx
hist/hist/src/TGraph.cxx
hist/hist/src/TGraph2D.cxx
hist/hist/src/TGraphMultiErrors.cxx
hist/hist/src/TH1.cxx
hist/hist/src/TH1K.cxx
hist/hist/src/TH2Poly.cxx
hist/hist/src/THStack.cxx
hist/hist/src/TMultiGraph.cxx
hist/hist/src/TPolyMarker.cxx
hist/hist/src/TProfile.cxx
hist/hist/src/TProfile2D.cxx
hist/hist/src/TProfile3D.cxx
hist/hist/test/test_TH1_SaveAs.cxx

1. Use common method to store list of functions for `TH1`, `TGraph`, `TGraph2D`, `TEfficiency`
2. Provide `RecursiveRemove` for TGraph2D and `TEfficiency` to properly work with list of functions
3. Use SavePrimitiveArray to store irregular axes bins, support in all classes saving with irregular bins
4. Use SavePrimitiveArray for large histogram and profile objects when more than 100 non-empty bins are detected
5. Fix storage of `TProfile3D` and `TH1K` 
6. Use `gInterpreter->MapCppName` when variable name should be derived from object name
7. Avoid usage of `quote` and `std::endl`

Improve `SavePrimitive()` methods in hist classes

---

tree/tree/inc/TTree.h
tree/tree/src/TChain.cxx
tree/tree/src/TTree.cxx

Fixes https://github.com/root-project/root/issues/17843

[tree] Avoid stack-use-after-scope by also resetting friends branch addresses

---

documentation/doxygen/Doxyfile

Temporarily exclude the ML tutorials to remove the huge dump of error messages

[skip-ci] Temporarily exclude the ML tutorials

---

math/minuit2/inc/Minuit2/MnMatrix.h

This is to accommodate the mathematical operations in recent Fumili developments:
* https://github.com/root-project/root/pull/17558

[Minuit2] Add missing operator to add algebraic vector objects

---

math/minuit2/inc/Minuit2/MnMatrix.h

Avoid potential double free that would happen if the LASymMatrix or LAVector is move-constructed.
The subsequent undefined behavior might be resulting in the sporadic build failures that we currently have.
The problem has been there since forever, but my suspicion is that the undefined behavior only got visible now by chance with other changes to Minuit2.

[Minuit2] Rule of five for Minuit2 linear algebra classes

---

tree/dataframe/inc/ROOT/RDF/RDefaultValueFor.hxx
tree/dataframe/inc/ROOT/RDF/RFilterWithMissingValues.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/treeplayer/inc/ROOT/TTreeProcessorMT.hxx
tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TTreeProcessorMT.cxx
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/src/TTreeReaderArray.cxx
tree/treeplayer/src/TTreeReaderValue.cxx

Change the data member holding the column names which should be ignored in case of TTreeReader errors regarding missing branches, from std::vector to std::set. The column names should not be repeated to avoid having multiple times the same column name left in the data member, which results in leftover names even after the corresponding operation of the computation graph has finished. Once a column is found, it will be available for all nodes of the computation graph anyway.
Part 4 of N for https://github.com/root-project/root/pull/17895

Improve semantics of data member

---

math/minuit2/src/MnMatrix.cxx

I must have made a mistake in the translation to more idiomatic C++ code for these functions in the previous PR:
* https://github.com/root-project/root/pull/17852
The mistake led to sporadic failures on Windows when using Minuit 2.
This PR suggests to use the old implementation again.

[Minuit2] Bring back old implementation of `mndspr` and `Mndspmv`

---

tree/ntuple/v7/src/RPageStorageFile.cxx

Fixes a couple of warnings seen e.g. [here](https://productionresultssa0.blob.core.windows.net/actions-results/eabe3d86-8e05-4d80-bc61-11f6a51832be/workflow-job-run-e2de9dfa-13eb-5b6c-b554-6d55fd0c2ac9/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-03-11T10%3A35%3A14Z&sig=qjJ5c740GztuEQO9LtEKEjnrQRwR39KpG%2FpsxUeQluo%3D&ske=2025-03-11T19%3A40%3A05Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-03-11T07%3A40%3A05Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-03-11T10%3A25%3A09Z&sv=2025-01-05) (latest nightly)
NB: the assert + static cast should be fine because they happen in the branch where we checked that `fAnchor->GetNBytesHeader() + fAnchor->GetNBytesFooter() < readvLimits.fMaxTotalSize` (which should be less than `size_t::max()` on …

[ntuple] cast uint64_t to size_t to avoid warnings on windows 32 bit

---

bindings/pyroot/pythonizations/test/memory.py

This test is fragile because we cannot be sure that RSS is a stable metric to evaluate the absence of a memory leak. The test itself has already demonstrated to be limited, in fact it was already modified or relaxed twice before:
https://github.com/root-project/root/commit/038054b3e5fdec0a499f0e25f571f88016565557 https://github.com/root-project/root/commit/015f44025d607d793922ba1eaae4aa9297339b07
It now starts also causing intermittent failures on MacOS which are not representative of a new memory leak, so it is better to just remove it.

[python] Remove fragile test

---

tree/ntuple/v7/test/ntuple_merger.cxx

They were left there by mistake

[ntuple] Remove some PreserveFile() in ntuple_merger.cxx

---

cmake/modules/SetUpWindows.cmake

Prevent this potential linker error:
```
Error LNK1140: too many modules for program database; link with /PDB:NONE
```

[cmake][win][skip-ci] Disable incremental linking

---

bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/uhi_plotting.py

This PR introduces the [Unified Histogram Interface](https://uhi.readthedocs.io/en/latest/index.html) plottable histogram functionality to the `TH1`-derived classes in ROOT. The changes include the addition of the methods described by the UHI `PlottableHistogram` protocol, ensuring compatibility with third party plotting libraries that support the protocol.
**Note:**  Currently, support is limited to 1D histograms.

[python] Add UHI PlottableHistogram protocol Support to 1D TH1 Derived Classes

---

.github/workflows/root-ci-config/buildconfig/fedora42.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2504.txt
.github/workflows/root-ci.yml

Add Ubuntu 25.04 and Fedora 42 configurations
We have to set `vdt=OFF` and `builtin_vdt=OFF` for now. The [minimum required CMake version for vdt is 3.2](https://github.com/dpiparo/vdt/blob/master/CMakeLists.txt#L2), but Fedora 42 ships with CMake 4.0, which [removed compatibility with CMake < 3.5](https://github.com/eclipse-ecal/ecal/issues/2041). Same for the builtin `zeromq` and the `roofit_multiprocess` feature that depends on it. Also `unuran` had to be disabled. I think the configuration should be revisited once Fedora 42 is actually released.
We also require `BLA_VENDOR=OpenBLAS` to avoid using flexiblas, like we currently have on `alma9` (flexiblas collides with the blas loaded inside numpy).
So far, a copy of the 24.10 configuration.

[ci] Add Ubuntu 25.04 and Fedora 42 configurations

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Backports of:
* https://github.com/root-project/root/pull/16682
* https://github.com/root-project/root/pull/17880
* https://github.com/root-project/root/pull/17888
Closes #17978.

[v632][cmake] Build Clad with one core only when needed

---

hist/hist/src/TH1.cxx

If only number of levels was provided,
only such numbers will be preserved in saved script

Save custom TH1 contour only is such was configured

---

etc/plugins/ROOT@@Math@@Minimizer/P040_GSLNLSMinimizer.C
hist/hist/src/HFitImpl.cxx
hist/hist/src/TF1Convolution.cxx
math/fumili/src/TFumili.cxx
math/fumili/src/TFumiliMinimizer.cxx
math/mathcore/inc/Math/MinimizerOptions.h
math/mathcore/src/FitConfig.cxx
math/mathcore/src/FitResult.cxx
math/mathmore/inc/Math/GSLNLSMinimizer.h
math/mathmore/src/GSLMultiFit.h
math/mathmore/src/GSLMultiFit2.h
math/mathmore/src/GSLMultiFitFunctionAdapter.h
math/mathmore/src/GSLMultiFitFunctionWrapper.h
math/mathmore/src/GSLNLSMinimizer.cxx
math/minuit2/inc/Minuit2/FumiliBuilder.h
math/minuit2/inc/Minuit2/FumiliFCNAdapter.h
math/minuit2/inc/Minuit2/FumiliFCNBase.h
math/minuit2/inc/Minuit2/FumiliMinimizer.h
math/minuit2/inc/Minuit2/MinimumError.h
math/minuit2/inc/Minuit2/MinimumSeed.h
math/minuit2/src/FumiliBuilder.cxx
math/minuit2/src/FumiliErrorUpdator.cxx
math/minuit2/src/FumiliGradientCalculator.cxx
math/minuit2/src/FumiliMinimizer.cxx
math/minuit2/src/InitialGradientCalculator.cxx
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnLineSearch.cxx
math/minuit2/src/MnPosDef.cxx

Implement a new version of the Fumili algorithm for minimization in Minuit2 using trust-region instead of line search for finding the next step. See this [presentation](https://indico.jlab.org/event/459/contributions/11597/attachments/9469/13862/Minuit2_CHEP2023.pdf). 
This PR implements also: 
-  the possibility to change the verbosity in fitting histograms. In addition to option `V`, the fitting options `VV` and `VVV` have been added
- a new version of gsl non-linear multidimensional fit algorithm. New classes were impelmented in GSL  versions 2, and now this PR impelments a new wrapper for the new GSL routines. Various different solver can be used for the `GSLMultiFit` minimization algorith, when fitting histograms.

[math][minuit2] Add new version of Fumili algorithm using trust region method

---

tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RLoopManager.cxx

Create an internal RAII struct to manage the calls to the initialization and finalization routines for the nodes of the computation graphs and the data source.
Part 7 of N for https://github.com/root-project/root/pull/17895

Improve exception safety of RDataSource range processing

---

hist/histpainter/src/THistPainter.cxx

As suggested [here](https://root-forum.cern.ch/t/not-plotting-zero-bins-in-th2-with-negative-entries/19633/15) this PR differentiate empty bins and bins with zero content when using the drawing option COL. The following little taste shows how it is working.
```
void col1(){
auto h = new TH2D ("h2","h2",10,0.5,10.5,10,0.5,10.5);
h->Fill(1.,1.,1.);
h->Fill(2.,2.,2.);
h->Fill(3.,3.,3.);
h->Fill(4.,4.,4.);
h->Fill(5.,5.,5.);
h->Fill(6.,6.,6.);    
h->Fill(6.,6.,-6.);
printf("Error for bin #%d = %g\n",6,h->GetBinError(6,6));
h->Fill(7.,7.,-7.);
printf("Error for bin #%d = %g\n",8,h->GetBinError(8,8));
h->Draw("COL1 Z");
}
```

Differentiate empty bins and bins with 0 content

---

hist/hist/src/TGraphAsymmErrors.cxx

The TGraphAsymmErrors constructor from a data file did not work properly when the value separator was not " " and with more than 4 parameters. This was reported in[ this forum post.](https://root-forum.cern.ch/t/tgraphasymmerrors-error-with-constructor-from-file/63118)

Fix an error in the ctor from a file

---

core/base/src/TColor.cxx
documentation/doxygen/filter.cxx

Some files still referred to old tutorial names.
`\preview` did not generate the right reference when clicking on the image.

[skip-ci] Some doc fixes

---

roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/RooFitResult.h
roofit/roofitcore/src/RooFitResult.cxx

These methods were specific to the old Fortran Minuit that provides the `gMinuit` pointer, and therefore don't work anymore nowadays now that RooFit uses Minuit2 by default.

[RF] Remove RooFitResult methods that use `gMinuit`

---

roofit/roofitcore/res/RooFitImplHelpers.h
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooFitImplHelpers.cxx
roofit/roofitcore/src/RooFuncWrapper.cxx

This patch was already applied locally to create benchmark results for conferences, but of course it would be better to have this merged inside ROOT to get benchmark results quicker and in a more reproducible way.
With the changes in this PR, it is finally possible to reproduce the results presented on [slide 11 in the ICHEP 2024 talk](https://indico.cern.ch/event/1291157/contributions/5889615/attachments/2900877/5087038/roofit_ichep_2024.pdf) easily.
In particular, this is very useful to validate new releases of Clad.
Below are the required scripts to do that. You can use them as follows:
1. Create a new clean directory
2. Create the files `analyze.py`, `fit_macro.C`, and `run.sh` with the content below
3. Run `./run.sh`
With current ROOT master, the plot looks like this:
Compared to the …

[RF] Add timing printouts to RooFit likelihood creation

---

math/minuit2/inc/Minuit2/MinimumSeedGenerator.h
math/minuit2/inc/Minuit2/MnPrint.h
math/minuit2/inc/Minuit2/MnSeedGenerator.h
math/minuit2/inc/Minuit2/SimplexSeedGenerator.h
math/minuit2/src/MnHesse.cxx
math/minuit2/src/MnPrint.cxx
math/minuit2/src/MnSeedGenerator.cxx
math/minuit2/src/ModularFunctionMinimizer.cxx
math/minuit2/src/NegativeG2LineSearch.cxx
math/minuit2/src/SimplexSeedGenerator.cxx
math/minuit2/src/VariableMetricBuilder.cxx

Add timing output to Minuit2.
This is a commit that was already used for months to produce benchmark results. Having this integrated will make this much easier in the future.
Also, do some general code improvements in Minuit2.
To see how the output looks like, here is the output of the basic RooFit tutorial with it:
```txt
Processing rf101_basics.C...
[#1] INFO:Fitting -- RooAbsPdf::fitTo(gauss_over_gauss_Int[x]) fixing normalization set for coefficient determination to observables in data
[#1] INFO:Fitting -- using CPU computation library compiled with -mavx2
[#1] INFO:Fitting -- RooAddition::defaultErrorLevel(nll_gauss_over_gauss_Int[x]_gaussData) Summation contains a RooNLLVar, using its error level
[#1] INFO:Minimization -- RooAbsMinimizerFcn::setOptimizeConst: activating const …
```

[Minuit2] Add timing printouts to Minuit2 info logging

---

config/thisroot.sh

Fixes https://github.com/root-project/root/issues/17969
This prevents errors in freebsd and macos, with the cut command being implemented differently vs Linux and complaining about a bad delimiter (empty) when using `-d ''`. While this might be a 'bug' in the freebsd and macos implementation of "cut", it makes sense to find an alternative here that is more cross-platform compliant.
All credit for the solution goes to eamjensen and mkelement0
Related: https://apple.stackexchange.com/questions/268352/how-to-use-cut-with-null-delimiter
https://stackoverflow.com/questions/23011370/how-to-recognize-whether-bash-or-dash-is-being-used-within-a-script/23011530?noredirect=1#comment140210695_23011530

cut command splitting by null bytes fails on MacOS and BSD

---

math/mathmore/inc/Math/LinkDef_Func.h
roofit/histfactory/inc/LinkDef.h
roofit/roofit/inc/LinkDef1.h
roofit/roostats/inc/LinkDef.h

The `CLING_USE_AUTLOADING` is not defined anywhere, and hence the code is presumably not needed.

Remove unused code about autoloading from LinkDef files

---

hist/hist/src/TGraphSmooth.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-8397
See https://root-forum.cern.ch/t/tgraphsmooth-approx-bug-in-root-5-and-6/22039/3
See https://root-forum.cern.ch/t/bug-or-feature-in-ttree-draw/62862/16

[hist] TGraphSmooth alleviate rounding errors at borders

---

core/metacling/src/CMakeLists.txt

Use `clangCppInterOp` directly as input for Cling target, just like the other objects that are used (like `MetaCling`).
This fixes the following CMake generation error on my system:
```txt
CMake Error: install(EXPORT "ROOTExports" ...) includes target "Cling" which requires target "clangCppInterOp" that is not in any export set.
CMake Error in CMakeLists.txt:
export called with target "Cling" which requires target "clangCppInterOp"
that is not in any export set.
```

[CMake] Use `clangCppInterOp` directly as input for Cling target

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/test/dataframe_snapshot_ntuple.cxx
tree/dataframe/test/datasource_ntuple.cxx

This PR lifts the restriction of not being able to Snapshot to RNTuple in a TDirectory (i.e., `dir/ntuple`). I naively/wrongly assumed that it wasn't possible to read back RNTuples in sub-directories, but it actually just works fine.

[DF][ntuple] Enable RNTuple Snapshotting to `TDirectory`

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
cmake/modules/RootMacros.cmake

Follow up to https://github.com/root-project/root/pull/17950
In the linked PR we found ourselves in need to create a Python ctest test that uses `pytest` as the test driver. The currently available `ROOT_ADD_PYUNITTEST` cmake function is limited because it only allows Python tests written with `unittest`, so we can introduce a new one more generic.

Add option for generic Python tests

---

core/base/src/TROOT.cxx

The global list of colours was not owning its objects, so if it gets cloned, the clones would leak.
Fix #18002.

[Core] Fix leak in list of colours.

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Right now, I get the following error when building ROOT with `builtin_llvm=OFF` and `clad=ON`:
```txt
CMake Error at CMakeLists.txt:94 (find_package):
Could not find a package configuration file provided by "LLVM" with any of
the following names:
LLVMConfig.cmake
llvm-config.cmake
Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
"LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
provides a separate development package or SDK, be sure it has been
installed.
CMake Error at /home/rembserj/code/root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-stamp/clad-configure-RelWithDebInfo.cmake:47 (message):
Stopping after outputting logs.
```
This commit suggests to set the `LLVM_DIR` to Clad to the actual `LLVM_DIR` that is found by …

[CMake] Fix building Clad with `builtin_llvm=OFF`

---

tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_serialize.cxx

As discussed offline with @jblomer and @hahnjo, we decided to move these nested classes up one level, mostly for simplification.

[ntuple] Move RPageInfo(Extended) up one level of nesting

---

tree/dataframe/inc/ROOT/RDF/RInterface.hxx

DefaultValueFor, FilterAvailable and FilterMissing register the column which might have missing values during the creation of a RDefaultValueFor or RFilterWithMissingValues object. Move the creation of the data source column readers after this is done, to avoid creating a reader for a column that might potentially be missing at that time.
Part 9 of N for https://github.com/root-project/root/pull/17895

[df] Avoid creating readers for unavailable columns

---

tree/dataframe/inc/ROOT/RDataSource.hxx
tree/dataframe/inc/ROOT/RVecDS.hxx
tree/dataframe/test/RArraysDS.hxx
tree/dataframe/test/RNonCopiableColumnDS.hxx
tree/dataframe/test/RStreamingDS.hxx

The SetNSlots method can now have a default implementation since the recent upstream of the fNSlots data member to the base class RDataSource.
Part 8 of N for https://github.com/root-project/root/pull/17895

Provide default implementation of virtual method

---

roofit/roofitcore/test/TestStatistics/testLikelihoodGradientJob.cxx
roofit/roofitcore/test/testNaNPacker.cxx

This would clip to the nearest in-range value anyway, so we should pass the lower limit directly.

[RF] Avoid setting out-of-range value in NaNPacker tests

---

tutorials/roofit/roostats/StandardHistFactoryPlotsWithCategories.C
tutorials/roofit/roostats/StandardHistFactoryPlotsWithCategories.py

The StandardHistFactoryPlotsWithCategories tutorial assumed that the nominal and plus-minus one sigma values of all nuisance parameters was zero, plus one, and minus one respectively. This is not true, especially for `gamma` parameters, where the nominal value is one.
The actual values and uncertainties should be taken from the parameters with `getVal()` and `getError()`. This also fixes the output plot in the tutorial for the gamma parameters:
https://root.cern/doc/master/StandardHistFactoryPlotsWithCategories_8C.html

[RF][RS] Fix StandardHistFactoryPlotsWithCategories tutorial

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Backport of:
* https://github.com/root-project/root/pull/18026

[v634][CMake] Fix building Clad with `builtin_llvm=OFF`

---

hist/hist/src/TF1.cxx
hist/hist/src/TH1.cxx

- Improve documentation of TH1::GetQuantiles and TF1::GetQuantiles
- Remove manual allocation and a const_cast in `TH1::GetQuantiles`.
This PR is an attempt to fix #16793, which proposed to remove the default parameter of `TH1::GetQuantiles`. As discussed there, the removal is not a good idea.
The existing documentation also created confusion about what the function does when the last parameter is left at its default value, which is clarified here.
So TL;DR: Don't change the default parameter, but clarify what it does.
Fix #16793

[hist] Improve TH1::GetQuantiles

---

gui/webdisplay/src/RWebDisplayHandle.cxx

From versions 120 to 132 chrome supports two different kinds of headless modes, but finally remove old in version 132.
https://developer.chrome.com/blog/removing-headless-old-from-chrome
Therefore use plain headless mode in newest Chrome. 
Do it by default on Windows where version is not tested.

[webgui] exclude old headless mode for newest chrome browser

---

gui/webdisplay/src/RWebDisplayHandle.cxx

From versions 120 to 132 chrome supports two different kinds of headless modes, but finally remove old in version 132.
https://developer.chrome.com/blog/removing-headless-old-from-chrome
Therefore use plain headless mode in newest Chrome. Do it by default on Windows where version is not tested.

[webgui] exclude old headless mode for newest chrome browser [6.34]

---

roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/LinkDef.h
roofit/roofitcore/inc/RooFit/Detail/NormalizationHelpers.h
roofit/roofitcore/inc/RooFit/Detail/RooNLLVarNew.h
roofit/roofitcore/inc/RooFit/Detail/RooNormalizedPdf.h
roofit/roofitcore/inc/RooProdPdf.h
roofit/roofitcore/src/BatchModeDataHelpers.cxx
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooAbsAnaConvPdf.cxx
roofit/roofitcore/src/RooAbsCachedPdf.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAddition.cxx
roofit/roofitcore/src/RooNLLVarNew.cxx
roofit/roofitcore/src/RooNormalizedPdf.cxx
roofit/roofitcore/src/RooProdPdf.cxx
roofit/roofitcore/src/RooRealSumPdf.cxx

Move some private inaccessible implementation details to the public `RooFit::Detail` namespace.
This non-functional change enables to compile the ongoing CMS Combine developments also against the upcoming ROOT 6.34.06, which makes it easier to test and validate these developments.
Basically backporting parts of #16772.

[v634][RF] Move some private implementation details to `RooFit::Detail`

---

.github/workflows/code_analysis.yml
CONTRIBUTING.md
ruff.toml

This PR introduces Ruff to the CI workflow for checking and formatting Python code. 
Uses the default ruff configuration and sets `line-length = 120` to be consistent with our [C++ code style](https://github.com/root-project/root/blob/master/.clang-format#L63)
This PR closes #17142

[ci] Add ruff python linter and formatter to the code analysis workflow

---

interpreter/cling/CMakeLists.txt
interpreter/cling/tools/demo/CMakeLists.txt

The recent cmake version 3.31.5 gives the following warning:
```txt
CMake Deprecation Warning at interpreter/cling/CMakeLists.txt:8 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
```
Raise the minimum version to CMake 3.10, which was released in 2017: https://www.kitware.com/cmake-3-10-0-available-for-download/
Whoever is reviewing this, please also take a look at this related `roottest` PR with the same branch name so they are tested together:
https://github.com/root-project/roottest/pull/1284

[CMake] Raise minimum CMake version for Cling to 3.10

---

gui/gui/src/TGColorSelect.cxx
gui/gui/src/TGFrame.cxx
gui/gui/src/TGListBox.cxx
gui/gui/src/TGNumberEntry.cxx
gui/gui/src/TGSplitter.cxx
gui/gui/src/TGTab.cxx
test/stressGUI.cxx

In stressGUI disable web mode and with `-keep` flag also preserve created macro files
Running all these macro, found and fix several old and new errors.
Now all these macros are usable

Improve stressGUI, fix TG SavePrimitive methods

---

.github/workflows/root-docs-ci.yml

execute only debugging commands. In principle this should not produce errors.

[skip-ci] execute only debugging commands

---

.github/workflows/root-docs-ci.yml

add `set -x` to see which command does not work. Might be `source`

[skip-ci] add set -x

---

graf3d/g3d/src/THelix.cxx
graf3d/g3d/src/TMarker3DBox.cxx
graf3d/g3d/src/TPolyLine3D.cxx

Improve `TPolyLine3D` and `TMarker3DBox`. 
Replace `THelix::SavePrimitive`. 
Implementation is broken and not usable.
For real implementation many changes are required.

Fix/improve SavePrimitive in g3d classes

---

cmake/modules/SearchInstalledSoftware.cmake
graf2d/asimage/CMakeLists.txt

There is probably no reason to do this anymore. These libraries should be installed on the system, and if not, the automatic detection a few lines above the removed lines will take care of it.
Both the ROOT conda package and the nix package have patches to circumvent this already, and it would be better to do this upstream too.

[CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS

---

tmva/sofie/CMakeLists.txt
tmva/sofie/README.md
tmva/sofie/inc/TMVA/ROperator_ScatterElements.hxx
tmva/sofie/test/TestCustomModelsFromONNX.cxx
tmva/sofie/test/input_models/ScatterElements.onnx
tmva/sofie_parsers/CMakeLists.txt
tmva/sofie_parsers/src/ParseScatterElements.cxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

Add support for a new operator, ScatterElements, needed for parsing the GNN models such as the tracking one used by ATLAS
Add also test for ScatterElements

[tmva][sofie] Add support for ScatterElements operator

---

tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

Fix the fusing for operators looking at all the children of a specific node in the ONNX graph and do not assume that the nodes are contiguous in the topological ONNX order

[tmva][sofie] Fix fusing of operators for generic cases

---

tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor.cxx
tree/ntuple/v7/test/ntuple_processor_chain.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx
tutorials/io/ntuple/ntpl012_processor_chain.C

This PR changes `RNTupleOpenSpec` to accept a `TDirectory` (or one of its descendants) instead of a plain file name, and create a `RNTupleProcessor` from there. This provides more flexibility for creating `RNTupleProcessor` objects. Among others, it enables processing RNTuples stored in subdirectories and `TMemFile`s.
One caveat is that the use of `std::variant` is not very ergonomic in Python. After discussing different solutions with @vepadulano, we concluded that the specification would/should not be used for anything beyond creating `RNTupleProcessor`s, and that public access to its data members is not strictly required. It has therefore been changed to a write-only class, and the `RNTupleProcessor` creation factory arguments have been updated accordingly.

[ntuple] Extend `RNTupleOpenSpec` to allow creating processors from a `TDirectory`

---

hist/hist/src/TH1.cxx

introduced in refactoring commit https://github.com/root-project/root/commit/9ef86d578954406440504aec31edcd1ea701671d#diff-f9554db4e8f6e87a454392c3387c28fb198444cea915e6365fac55317f9ea5f2R23-R6823 Found out by https://root-forum.cern.ch/t/useless-check-bug-in-th1-smooth/63183/3

[hist] fix smootharray bug

---

core/meta/src/TClass.cxx

This fixes #17992
Technically the fix is in commit 3812e5e8a3a0852b6e95b9516752f0ae0d73c59f
However analysis of the surrounding code showed that 
* one of the code path was missing a call to PostLoadCheck (74a7abbb77de51e9479d7bbb69e6213082fdbc2b)
* the code could be simplified a tad bit.

Fix spurrious auto parsing when looking up a TClass

---

core/meta/src/TClass.cxx

BP of https://github.com/root-project/root/pull/17994

[BP 632] Fix spurrious auto parsing when looking up a TClass 

---

documentation/users-guide/WebDisplay.md
js/files/draw.htm
js/files/online.htm
js/modules/core.mjs
js/modules/hist/TGraph2DPainter.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/THStackPainter.mjs
js/modules/hist2d/TMultiGraphPainter.mjs
js/modules/io.mjs
net/http/src/THttpServer.cxx
tutorials/http/custom.htm
tutorials/http/httptextlog.mjs
ui5/canv/ctrlbar.html
ui5/eve7/index.html
ui5/panel/Controller.js
ui5/panel/panel.html
ui5/tree/index.html

Such map automatically inserted in HTML file by `THttpServer` if `` comment
appears in HTML file. 
1. Better formatting of produced output - detect indentation
2. Include several JSROOT modules which can be used
3. Use importmap in most files and tutorials
4. Also in JSROOT use it and fix histogram type for TGraph/TGraph2D drawing

[webgui] more use of <jsroot-importmap> 

---

.github/workflows/root-ci-config/buildconfig/fedora40.txt
.github/workflows/root-ci.yml

since its EOL is coinciding with the foreseen release date of ROOT 6.36.00

[skip-ci][ci] Remove Fedora40 builds

---

gui/browserv7/src/RBrowser.cxx
gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx
js/modules/base/ObjectPainter.mjs
js/modules/base/RObjectPainter.mjs
js/modules/core.mjs
js/modules/draw/TASImagePainter.mjs
js/modules/geom/geobase.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist/TPavePainter.mjs
ui5/canv/view/Canvas.view.xml

1. On JSROOT side fix problem with sub-pads update. New logic was failing when only subpad data were modified
2. Fix problem when canvas first drawn and then browser window was closed. In such case pending connection remains and blocked `gPad->Update()` for very long time
3. Correctly handle `canv->Show()` now. After it called `gPad->Update()` will really wait for next drawing
4. Use `win.Sync()` in TWebCanvas to handle (re-)connection timeouts properly
5. If JSROOT fails, show error indicator more clearly
PR solves several problem with demos.C macro which can run several canvases. If any of canvas closed there, `TWebCanvas::Update` was blocking for very long time making it unusable.

[webcanv] fix several TCanvas::Update() problems

---

tutorials/index.md

On the main page of tutorials, we first have a description in which we link to the most often used categories. Because of that, the table below can now be ordered in an alphabetical order instead of "priority" order.

[skip-ci][tutorials] Show categories of tutorials in an alphabetical order.

---

math/mathmore/src/GSLInterpolator.h

Fixes https://its.cern.ch/jira/browse/ROOT-8725

[mathmore] make GSLinterpolator Eval error printing thread-safe

---

tutorials/math/index.md

adds doxygen macro addtogroup to show tables implemented in https://github.com/root-project/root/pull/18143

[skip-ci][tutorials] Add doxygen macro addtogroup

---

core/base/inc/TSystem.h
core/base/src/TSystem.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-4663

[core] GetPipe: allow storing return value and redirect stderr

---

tree/tree/src/TChain.cxx
tree/tree/test/TChainRegressions.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-7067
Fixes https://its.cern.ch/jira/browse/ROOT-8505
Alternative version of https://github.com/root-project/root/pull/17789 using pcanals algorithm

 [tree] Respect TChain's entryList when GetMinimum/Maximum v2

---

tutorials/CMakeLists.txt

Adds some missing changes to the tutorials `CMakeLists.txt`  that are required after moving the parallel analysis tutorials into `tutorial/analysis/parallel` #18145

[tutorials][skip-ci] Fix paths to analysis/parallel in CMake

---

tutorials/io/ntuple/ntpl001_staff.C
tutorials/io/ntuple/ntpl002_vector.C
tutorials/io/ntuple/ntpl005_introspection.C
tutorials/io/ntuple/ntpl007_mtFill.C
tutorials/io/ntuple/ntpl011_global_temperatures.C
tutorials/io/ntuple/ntpl015_processor_join.C

...distinguishing more explicitly between the use of `RNTupleReader` and `RNTupleWriter`.

[tutorials] Rename `ntuple` to `reader` and `writer`

---

tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/test/ntuple_processor_join.cxx

To reflect the interface changes introduced in #17964, instead of a single list of models (one per primary/auxiliary ntuple), a distinction is made between the models of the primary and auxiliary ntuples.
Same as before, internally they are combined into one singular model used by the processor. This model has to have the schemas of auxiliary RNTuples as untyped record fields, where the name of the record field is the name of the RNTuple.
A new addition is the added support for _partial_ model specification in the list of auxiliary models. This means that users can pass a null pointer in the position of the corresponding ntuple, and then only for that ntuple, the processor will infer the model from the on-disk descriptor.
Helps move forward #17132.

[ntuple] Split primary and auxiliary models in  `RNTupleJoinProcessor::CreateJoin`

---

tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RFieldUtils.hxx
tree/ntuple/v7/src/RFieldUtils.cxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/ntuple_type_name.cxx

To avoid inconsistencies between the full type name of a custom class reported by the RNTuple IO and the type name reported by ROOT meta. The commit adds a unittest. Previously, the test would fail with exceptions such as:
```
321: unknown file: Failure
321: C++ exception with description "type mismatch for field f2: DataVector<std::int32_t,std::vector<CustomStruct>> vs. DataVector<int,vector<CustomStruct> >
321: At:
321:   void ROOT::Experimental::REntry::EnsureMatchingType(RFieldToken) const [with T = DataVector<int, std::vector<CustomStruct> >]
321: " thrown in the test body.
```

[ntuple] Ensure type name given by RField<T> is renormalized

---

io/io/inc/TFile.h
io/io/src/TFileMerger.cxx
io/io/test/TFileMergerTests.cxx
tree/tree/src/TTree.cxx

Fixes https://github.com/root-project/root/issues/6640

[io] Bypass TTree::ChangeFile when using TFileMerger

---

graf2d/gpad/inc/TCanvas.h
graf2d/gpad/src/TCanvas.cxx
gui/browserv7/src/RBrowserTCanvasWidget.cxx
gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx
tutorials/visualisation/webgui/bootstrap/Readme.md
tutorials/visualisation/webgui/bootstrap/dist/css/styles.css
tutorials/visualisation/webgui/bootstrap/dist/index.html
tutorials/visualisation/webgui/bootstrap/dist/js/scripts.js
tutorials/visualisation/webgui/bootstrap/webwindow.cxx
tutorials/visualisation/webgui/qtweb/TCanvasWidget.cpp

1. Extend `TCanvas::SetCanvasImp()` method to correctly set web-based implementation. One need to change some private fields of the TCanvas. Before workaround was used to set private fields from outside
2. Implement `TWebCanvas::CreateWebCanvas()` method. It creates TCanvas instance and assign correctly configure `TWebCanvas` implementation to it. Such canvas can be shown or used as embed canvas in different applications
3. Use `TWebCanvas::CreateWebCanvas()` in `RBrowser` and `qtweb` tutorial simplifying code
4. Introduce `tutorials/visualization/webgui/bootstrap` demo with usage of bootsrtap framework to generate HTML page for RWebWindow. Source code can be found here https://github.com/linev/bootstrap-example.
5. Show embed TWebCanvas in bootstrap demo. One can periodically change …

[webcanv] provide example of `TWebCanvas` embeding in `bootstrap` web page

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/src/RNTupleProcessor.cxx
tree/ntuple/v7/src/RNTupleReader.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntupleutil/v7/inc/ROOT/RNTupleImporter.hxx

Moves `REntry` out of Experimental.

[ntuple] Move REntry out of Experimental

---

.github/workflows/code_analysis.yml

This PR updates the ruff formatting workflow to detect and act on the changed lines instead of the whole file.
On failure, the command to run is highlighted so that it can directly be copied and applied locally
**Note**: linting still applies to the full file.
Could be improved once astral-sh/ruff#12800 is implemented
This PR closes #18167

[ci] Format only changed lines with ruff

---

hist/hist/src/TEfficiency.cxx

Add a reference to:
D. Casadei, Estimating the selection efficiency, 2012 JINST 7 P08021, https://doi.org/10.1088/1748-0221/7/08/P08021 (https://arxiv.org/abs/0908.0130).
As requested by D. Casadei in an email to root-dev@cern.ch

[skip-ci] Add reference in Bayesian methods section

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.h
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/MemoryRegulator.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx

Use macros from the C Python API for better compatibility between Python versions and also to compile with Python builds with free threading (aka. without the GIL).

[CPyCppyy] Use macros from the C Python API for better compatibility

---

roofit/roofitcore/src/RooRealIntegral.cxx

The problem is that `dependsOnValue` has to traverse the full computation graph itself, to check whether any of the nodes depends on "branch". And since the code calls "dependsOnValue" in a loop over all branches, we have an expensive double loop that is the bottleneck for the creation of toy data for large HistFactory workspaces.
The solution is to use `treeNodeServerList`, which can figure out the value servers in a single pass over the computation graph.

[RF] Avoid a double-loop over computation graph in RooRealIntegral ctor

---

hist/hist/inc/TEfficiency.h
hist/hist/src/TEfficiency.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-10907
As follow-up of / together with https://github.com/root-project/root/pull/14821
See: https://root-forum.cern.ch/t/tefficiency-with-floats/40146/5?u=ferhue

[hist] number of TH1 events is floating point in general

---

tutorials/io/ntuple/index.md

This PR adds a description table, similar to the one introduced for RDataFrame, for the various RNTuple tutorials. Additionally, the general description has been updated and extended a bit.

[skip-ci][tutorials] Organise RNTuple tutorials section

---

hist/hist/inc/TFormula.h
hist/hist/inc/v5/TFormula.h
hist/hist/src/TFormula.cxx
hist/hist/src/TFormula_v5.cxx
test/TFormulaParsingTests.h
tree/tree/test/TTreeRegressions.cxx
tree/treeplayer/src/TTreeFormula.cxx

Fixes https://github.com/root-project/root/issues/10769

[hist] allow specifying the floating point precision in GetExpFormula

---

roofit/doc/developers/roofit_hs3.md
roofit/hs3/src/RooJSONFactoryWSTool.cxx
roofit/jsoninterface/CMakeLists.txt
roofit/jsoninterface/src/JSONInterface.cxx

Due to lack of time, only one RooFit backend can be supported. On CMake configure, it, however, looked like RapidYML should be found. Here, the corresponding YML messages and mentions throughout the documentation are removed.
If the backend should be revived, this commit can be reverted.
Fix #18128.

[RFHS3] Remove mention of RapidYML backend, which is not supported.

---

core/base/inc/TObject.h
core/base/src/TObject.cxx
graf2d/graf/src/TCutG.cxx
graf2d/graf/src/TPolyLine.cxx
graf3d/g3d/src/TPolyLine3D.cxx
graf3d/g3d/src/TPolyMarker3D.cxx
hist/hist/src/TEfficiency.cxx
hist/hist/src/TF1.cxx
hist/hist/src/TF2.cxx
hist/hist/src/TGraph.cxx
hist/hist/src/TGraph2D.cxx
hist/hist/src/TGraph2DAsymmErrors.cxx
hist/hist/src/TGraph2DErrors.cxx
hist/hist/src/TGraphAsymmErrors.cxx
hist/hist/src/TGraphBentErrors.cxx
hist/hist/src/TGraphErrors.cxx
hist/hist/src/TH1.cxx
hist/hist/src/TH1K.cxx
hist/hist/src/TPolyMarker.cxx
hist/hist/src/TProfile.cxx
hist/hist/src/TProfile2D.cxx
hist/hist/src/TProfile3D.cxx
hist/hist/src/TScatter.cxx

Plain array is allocated in stack and therefore depending on platform maximal array size is limited.
Therefore instead of storing array store vector like:
```
std::vector<Double_t> hp0__1_vect0{
1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0
};
```
Adjust all places where array was used and remove `SavePrimitiveArray` - it was introduced several weeks ago and was never released.

Replace `SavePrimitiveArray` by `SavePrimitiveVector`

---

gui/browsable/src/RFieldProvider.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/src/RNTupleView.cxx
tree/ntuple/v7/test/ntuple_test.hxx
tree/ntuple/v7/test/ntuple_view.cxx

Moves out of Experimental the `RNTupleView` class directory

[ntuple] Move RNTupleView out of Experimental

---

requirements.txt

Now that https://github.com/pytorch/pytorch/issues/138333 is fixed, commit 24fd0d89b4e5c750e can be reverted.

No constraints to torch version in `requirements.txt`

---

bindings/pyroot/pythonizations/test/rdf_define_pyz.py
bindings/pyroot/pythonizations/test/rdf_filter_pyz.py

On my machine, the RDF pythonization tests don't run when I build ROOT with `builtin_llvm=OFF`. There is a crash unless I do `import numba` in the beginning.
I guess it's not a priority to understand the underlying problem because not many people build ROOT like this and the workaround is easy, but at least the tests should be green.
We do the same "magically ordered imports" also in other Python tests where ROOT doesn't work together with xgboost because of `std::regexp` symbol clashes, unless you do the import in a certain order:
https://github.com/root-project/root/pull/15183

[Python] Fix RDF Pythonization tests with `builtin_llvm=OFF`

---

roofit/hs3/src/RooJSONFactoryWSTool.cxx

Fix by @guitargeek.
The RooWSFactoryTool expression handler was not correctly matching branckets, leading to failures when importing valid JSON filed with RooProdPdf objects.
Can be tested with the following reproducer:
```python3 dump_json_to_workspace.py datacard_part1_nosys.json```
where ```dump_json_to_workspace.py``` is
```
import ROOT
import sys
import os
if len(sys.argv) != 2:
print("Usage: python script.py <input_json_file>")
sys.exit(1)
input_file = sys.argv[1]
if not os.path.isfile(input_file):
print(f"Error: File '{input_file}' not found.")
sys.exit(1)
base_name = os.path.splitext(os.path.basename(input_file))[0]
output_file = f"{base_name}_imported.root"
ws = ROOT.RooWorkspace("w")
tool = ROOT.RooJSONFactoryWSTool(ws)
tool.importJSON(input_file)
ws.writeToFile(output_file)
``` …

[RF] Fix implementation of HS3 importers

---

tree/dataframe/src/RLoopManager.cxx

The '%lu' token used in RLoopManager::RunDataSource does not correspond to the correct integer representation of `std::uint64_t` on all platforms. We use a stringstream instead to construct the warning message.
Possibly also fixes the recent failures seen on Windows x86

[df] Avoid bad integer substitution in string formatting

---

roofit/roofitcore/src/RooFitResult.cxx

segfault shown in https://root-forum.cern.ch/t/extracting-global-correlation-causes-a-seg-fault-with-sumw2error/55138
This does not fully solve https://github.com/root-project/root/issues/12935, it's just adding safety.

[RF] fix segfault in fillLegacyCorrMatrix

---

ui5/browser/browser.html
ui5/eve7/eve.mjs
ui5/eve7/index.html
ui5/geom/controller/GeomViewer.controller.js
ui5/geom/index.html
ui5/panel/Controller.js
ui5/tree/index.html

This is location of JSROOT scripts, 
but normally one should use `import {something } from 'jsroot'` statement
Now `` used in all widgets
Fix geometry resize in qt6

[webgui] reduce `source_dir` usage in widgets [skip-ci]

---

hist/hist/inc/v5/TFormula.h
hist/hist/src/TFormula_v5.cxx

Revert part of recent changes (https://github.com/root-project/root/pull/18194) since it breaks backward compatibility as the function was virtual.
Fixes https://github.com/root-project/root/issues/18214
thanks guitargeek for finding out

[hist] revert changes to v5 GetExpFormula fl_format

---

graf2d/gpadv7/inc/ROOT/RPadLength.hxx

Use `const` references as one should for `operator+` and `operator-`.
This fixes the following warning I get when building ROOT with tests:
```txt
In file included from /nix/store/aw0qxjd1phf16qhlwpdb4x87yymfv9rp-gcc-14-20241116/include/c++/14-20241116/x86_64-unknown-linux-gnu/bits/c++allocator.h:33,
from /nix/store/aw0qxjd1phf16qhlwpdb4x87yymfv9rp-gcc-14-20241116/include/c++/14-20241116/bits/allocator.h:46,
from /nix/store/aw0qxjd1phf16qhlwpdb4x87yymfv9rp-gcc-14-20241116/include/c++/14-20241116/memory:65,
from /nix/store/qf61vad876jgyd4vnn147cz2jyvy23vl-gtest-1.16.0-dev/include/gtest/gtest.h:55,
from /home/rembserj/code/root/root_src/graf2d/gpadv7/test/coords.cxx:12:
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = double]’,
inlined from ‘static …
```

Fix warning caused by RPadLength arithmetic operators

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_rooglobalfunc.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/rdataframe_misc.py
bindings/pyroot/pythonizations/test/stl_vector.py
bindings/pyroot/pythonizations/test/ttree_branch_attr.py
tutorials/CMakeLists.txt
tutorials/analysis/dataframe/df036_missingBranches.py
tutorials/analysis/dataframe/df037_TTreeEventMatching.py
tutorials/roofit/roostats/StandardHypoTestDemo.py
tutorials/roofit/roostats/rs_numberCountingCombination.py

The dependency on Python libraries like NumPy needs to be declared in the CMakeLists.txt, such that the test gets disabled when the library is not available.
In some cases, the dependency on NumPy could be avoided by using the builtin "array" library.

[Python] Correctly manage NumPy dependencey in pythonization tests

---

cmake/modules/SearchInstalledSoftware.cmake

```
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:43 (message):
No internet connection.  Please check your connection, set
'-D$(option_name)=OFF' or disable 'fail-on-missing' to automatically
disable options requiring internet access
Call Stack (most recent call first):
cmake/modules/SearchInstalledSoftware.cmake:57 (ROOT_CHECK_CONNECTION)
cmake/modules/SearchInstalledSoftware.cmake:66 (ROOT_CHECK_CONNECTION_AND_DISABLE_OPTION)
CMakeLists.txt:280 (include)
```
will now become 
```
CMake Error at cmake/modules/SearchInstalledSoftware.cmake:43 (message):
No internet connection.  Please check your connection, set
'-Dclad=OFF' or disable 'fail-on-missing' to automatically
disable options requiring internet access
Call Stack (most recent call first): …
```

SearchInstalledSoftware.cmake: correctly report name of option to disable

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Disable_std-vector-numpy-array-pythonization.patch
bindings/pyroot/cppyy/sync-upstream

The addition of the `__array__` utility to std::vector Python proxies causes a bug where the resulting array is a single dimension, causing loss of data when converting to numpy arrays, for >1dim vectors. The recursive nature of this
function `VectorArray`, passes each subarray (pydata) to the next call and only the final buffer is cast to a lowlevel view and resized (in VectorData), resulting in only the first 1D array to be returned.
Since this C++ pythonization was added with the upgrade in 6.32, and is only defined and used recursively, the safe option is to disable this function and no longer add it. It is temporarily removed to prevent errors due to `-Wunused-function`
Fixes: https://github.com/root-project/root/issues/17729

[CPyCppyy] Drop `__array__` from std::vector pythonizations

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Disable_std-vector-numpy-array-pythonization.patch
bindings/pyroot/cppyy/sync-upstream
cmake/modules/SearchInstalledSoftware.cmake
roofit/hs3/src/RooJSONFactoryWSTool.cxx
roofit/roofitcore/src/RooAbsPdf.cxx

This PR is motivated especially by these two bugfixes:
* https://github.com/root-project/root/pull/18208
* https://github.com/root-project/root/pull/18209

[v634] Backport of recent fixes to the 6.34 release branch

---

core/thread/inc/ROOT/RConcurrentHashColl.hxx

`less` is defined in functional according to the C++ standard.

Fix build issue on macOS 15.4 / XCode 16.3

---

interpreter/cling/lib/Interpreter/LookupHelper.cpp

This fixes #18236
As seen in https://github.com/cms-sw/cmssw/issues/47763#issue-2966412921 there are cases where the ROOT global lock is taken too late:
In the stack trace below the lock is requested on frame #7 where as it should really be (also) requested on frame #12 as soon as the transaction is being generated.
A follow up PR should consider migrating the lock acquisition into the `Interpreter::PushTransactionRAII` constructor after measuring whether this has measurable performance and scalability issues.
<details>
<summary>Details</summary>
```
#6  0x00001501421f55ea in ROOT::TVirtualRWMutex::Lock() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02883/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_15_1_RNTUPLE_X_2025-03-31-2300/external/el8_amd64_gcc12/lib/libCore.so
#7  0x0000150133a680ca in …
```

cling: Add ROOT lock to LookupHelper::findType

---

graf2d/gpad/src/TPad.cxx
hist/hist/src/TAxis.cxx
hist/histpainter/src/THistPainter.cxx

Fixes https://github.com/root-project/root/issues/13880

[hist] reset kAxisRange bit when fully unzooming

---

cmake/modules/SearchInstalledSoftware.cmake
graf2d/asimage/CMakeLists.txt

There is probably no reason to do this anymore. These libraries should be installed on the system, and if not, the automatic detection a few lines above the removed lines will take care of it.
Backport of:
* https://github.com/root-project/root/pull/18074

[v632][CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS

---

cmake/modules/SearchInstalledSoftware.cmake
graf2d/asimage/CMakeLists.txt

There is probably no reason to do this anymore. These libraries should be installed on the system, and if not, the automatic detection a few lines above the removed lines will take care of it.
Backport of:
* https://github.com/root-project/root/pull/18074

[v634][CMake] Don't force builtin libpng/gif/tiff/jpeg on macOS

---

gui/browserv7/inc/ROOT/RBrowser.hxx
gui/browserv7/src/RBrowser.cxx
js/changes.md
js/modules/core.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/io.mjs
ui5/browser/controller/Browser.controller.js
ui5/browser/model/BrowserModel.js
ui5/browser/view/Browser.view.xml
ui5/browser/view/settingsmenu.fragment.xml
ui5/geom/controller/GeomHierarchy.controller.js

1. Use `user-select: none` for text in list view to avoid text selection
2. Implement `drag-and-drop` functionality for items in Tree view
3. Let optionally use single-click handler for display, as openui5 default behavior does
4. Suppress custom context menu in Tree view
5. Provide other columns context menu for enabling/disabling and resize of columns
6. Update JSROOT with `user-select: none` for drawings

RBrowser improve [skip-ci]

---

cmake/modules/SearchInstalledSoftware.cmake

to address the new behaviour of the compiler shipped with XCode 16.3

[cmake] Update the version of VDT to 0.4.6

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rntuple.py
tree/ntuple/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RFieldToken.hxx
tree/ntuple/v7/inc/ROOT/RNTupleFillContext.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/inc/ROOT/RRawPtrWriteEntry.hxx
tree/ntuple/v7/src/RNTupleModel.cxx
tree/ntuple/v7/test/ntuple_basics.cxx
tree/ntuple/v7/test/ntuple_parallel_writer.cxx
tutorials/io/ntuple/ntpl014_framework.C

It is a container of `const` raw pointers that can be used to write constant data products in frameworks.
Closes #17900

[ntuple] Implement `Detail::RRawPtrWriteEntry`

---

tmva/sofie/inc/TMVA/ROperator_Conv.hxx
tmva/sofie/inc/TMVA/ROperator_ConvTranspose.hxx
tmva/sofie/inc/TMVA/ROperator_ConvTranspose.icc

This PR adds the intermediate tensors convK and imcol into the memory optimization mechanism in SOFIE.

[tmva][sofie] memory optimization in convK and imcol for ConvTranspose

---

tmva/sofie/inc/TMVA/ROperator_LayerNormalization.hxx
tmva/sofie/inc/TMVA/ROperator_Sigmoid.hxx

For square operations, do not use std::pow with base 2 since it is slower than simple multiplication This speeds up evaluation on ATLAS GNN tracking model by 40%
Also avoids allocating a small shape vector in LayerNorm and improve the indentation of the sigmoid operator

[tmva][sofie]  Optimize LayerNormalization operator

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/patches/CPyCppyy-Disable_std-vector-numpy-array-pythonization.patch
bindings/pyroot/cppyy/sync-upstream

[v632][CPyCppyy] Drop `__array__` from std::vector pythonizations

---

graf2d/quartz/src/QuartzLine.mm

Fix a warning when compiling quartz on macos 15.4 with clt 16.3

Fix a warning when compiling quartz on macos 15.4 with clt 16.3

---

core/base/inc/TDirectory.h
core/base/src/TDirectory.cxx

- avoid scanning the string twice
- allow `name` to be null if one only wants the cycle
- return the actual name length so the caller can know whether the name was truncated or not
- improve function documentation

[core] improve TDirectory::DecodeNameCycle

---

cmake/modules/SearchInstalledSoftware.cmake
core/clingutils/CMakeLists.txt
core/thread/inc/ROOT/RConcurrentHashColl.hxx
graf2d/asimage/README
graf2d/asimage/src/libAfterImage/libpng/pngpriv.h
interpreter/cling/include/cling/std_darwin.MacOSX15.2.sdk.modulemap
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/IncrementalJIT.cpp

Backports of:
- https://github.com/root-project/root/pull/18238
-  https://github.com/root-project/root/pull/18231
- https://github.com/root-project/root/pull/18250
-  https://github.com/root-project/root/pull/18240
- https://github.com/root-project/root/pull/18254
Fixing macOS15.4 builds

[v632] Fix macOS15.4 builds

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

Some C++ functions defined in CPyCppyy are passed to CPython API, e.g. to build Python methods that use some C++ functionality. This is done by creating a instance of a PyMethodDef struct
(https://docs.python.org/3/c-api/structures.html#c.PyMethodDef). One data member of this struct is of type PyCFunction
(https://docs.python.org/3/c-api/structures.html#c.PyCFunction), a typedef of a function with signature
```
PyObject *PyCFunction(PyObject *self,
PyObject *args);
```
In many cases, the C++ functions that are used as the data member of the PyMethodDef are not directly implemented as PyCFunction, thus need to be cast. This cast is often invalid, since many of such functions do not really respect the function signature prescribed by the API. This pattern is actually encouraged for CPython …

[cppyy] Disable warnings for invalid function casts

---

tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/src/TTreeReaderValue.cxx
tree/treeplayer/test/leafs.cxx
tutorials/CMakeLists.txt

- Since the missing value feature has been added to RDF and TTreeReader, a crash was observed when running RDF with the missing value feature. When changing to another tree, branches didn't didn't get recreated, leaving them in an inconsistent state.
- Another crash only observed on Mac15 beta seems to have been a line in a test that's dereferencing a nullptr. It doesn't do anything with that value, but it still generated a SIGTRAP.
- Python tutorials were running in unspecified order, because a string comparison with an empty string in CMake was taking the wrong branch and removing all dependencies.
Note:

Fixes for Mac beta

---

tree/treeplayer/test/leafs.cxx

BP of what's needed of https://github.com/root-project/root/pull/18265

[BP][6.34][tree] Don't dereference a nullptr in TTreeReaderValue test.

---

tree/treeplayer/test/leafs.cxx

BP of what's needed of https://github.com/root-project/root/pull/18265/

[BP][6.32][tree] Don't dereference a nullptr in TTreeReaderValue test.

---

io/io/src/TBufferJSON.cxx

When stream directly `std::map` object in macro like:
```
std::map<int,string> m;
m[1] = "number 1";
m[2] = "number 2";
auto json = TBufferJSON::ToJSON(&m);
```
Real dictionary class for `std::map` is required.
It checked automatically when map is member of user class,
but was not checked when map object itself streamed

[json] Check dictionary for std::map object in streaming

---

cmake/modules/RootBuildOptions.cmake

Some improvements to the handling of RPATH options, which are necessary on my system because I need to add a custom RPATH to make my CUDA package from nix packages findable.
1. Don't set CMake variables to `FALSE` if the default is `FALSE` already. This makes it impossible to change these variables from the CMake user configuration, unnecessarily taking flexibility out of the build system.
2. If `rpath=ON`, ROOT adds the relative path from the binary directory to the lib directory to the RPATH. But it doesn't append it, overriding any `CMAKE_INSTALL_RPATH` that the user might set in the CMake configuration. This commit suggests to append instead.
3. If `rpath=OFF`, ROOT sets `CMAKE_SKIP_INSTALL_RPATH` to `TRUE` without any apparent reason, again, preventing the user from defining the …

[CMake] Improve handling of RPATH options

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

Although `bad-function-cast` is present for both Clang and GCC, on the latter it is only used for C and Objective-C code. Using `no-cast-function-type` seems to already disable the PyCFunction-cast-related warnings seen with AppleClang.

[cppyy] Do not use non-C++ GCC warning

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

Backport of https://github.com/root-project/root/pull/18284

[6.32] [cppyy] Do not use non-C++ GCC warning

---

gui/browsable/src/RProvider.cxx
js/modules/gpad/RAxisPainter.mjs
js/modules/gpad/RPadPainter.mjs
tutorials/experimental/rcanvas/rcanvas_mt.cxx

Previous version was deleted because usage of RH1D.
Now use TH1D instead.
Fix problem with RCanvas update in jsroot
Add again entry for RBrowser to load library for RCanvas

Reintroduce rcanvas_mt.cxx tutorial [skip-ci]

---

math/mathcore/inc/Fit/FitUtil.h

[math] Bypass clang warning only when it can actually occur

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx
tutorials/io/ntuple/ntpl004_dimuon.C

And into the ROOT::RDF namespace, aligning it with all other RDataSource implementations.

[df] Move RNTupleDS out of experimental

---

roofit/roofitcore/src/RooFormula.cxx
roofit/roofitcore/src/RooFormula.h
roofit/roofitcore/test/testRooFormula.cxx

Fixes https://github.com/root-project/root/issues/18013

[RF] correctly detect undefined variables in RooArgList

---

tree/dataframe/inc/ROOT/RResultPtr.hxx
tree/dataframe/src/RDataFrame.cxx
tutorials/analysis/dataframe/df039_RResultPtr_basics.C
tutorials/analysis/dataframe/df040_RResultPtr_lifetimeManagement.C
tutorials/analysis/dataframe/index.md

Users reported problems with losing the underlying object when the RResultPtr goes out of scope. By adding GetSharedPtr(), this can be avoided.
Fix #14766.

[RDF] Provide access to the shared_ptr in RResultPtr.

---

tree/dataframe/test/CMakeLists.txt

Fix the following compilation errors on Windows:
```
error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

[cmake][win] Fix compilation errors on Windows

---

gui/webdisplay/src/RWebDisplayArgs.cxx
gui/webdisplay/src/RWebWindowsManager.cxx

Minorly improves documentation for `--web=server` since I didn't find it immediately and also the environment variable `ROOT_WEBDISPLAY` was not documented at all.
Note that I believe that the `embed`/`embedded` option should also be documented in `RWebDisplayArgs` but I don't understand it enough to do so.

[skip-ci] Minor documentation improvement for --web=server

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RSnapshotOptions.hxx

The type given to the fBasketSize member of the RSnapshotOptions, std::optional<int>, is not serializable by ROOT. This can lead to warnings and potentially faulty behaviour in distributed RDataFrame (and similar scenarios that require objects to be serializable). For example, this can be seen in the test output:
TStreamerInfo::Build:0: RuntimeWarning: ROOT::RDF::RSnapshotOptions: optional<int> has no streamer or dictionary, data member "fBasketSize" will not be saved
TStreamerInfo::Build:0: RuntimeWarning: _Optional_base<int,true,true>: base class _Optional_base_impl<int,_Optional_base<int,true,true> > has no streamer or dictionary it will not be saved
TStreamerInfo::Build:0: RuntimeWarning: _Optional_base<int,true,true>: _Optional_payload<int,true,true,true> has no streamer or …

Make basket size option a serializable type

---

roofit/batchcompute/src/RooBatchCompute.cu
roofit/batchcompute/src/RooBatchCompute.cxx
roofit/roofitcore/inc/RooFit/Detail/RooNLLVarNew.h
roofit/roofitcore/src/BatchModeDataHelpers.cxx
roofit/roofitcore/src/RooNLLVarNew.cxx
roofit/roofitcore/test/stressRooFit.cxx
roofit/roofitcore/test/testTestStatistics.cxx

Fix likelihood fits with constant probabliliy, which is an edge case but it should still work with the new vectorizing CPU and CUDA backends.
If the probability is a scalar, the assumption that the number of events can be retrieved by `probas.size()` is wrong. The proposed solution is to always fill the weight buffer, even in case of unity weights, because then the number of events can be retrieved like `weights.size()`.
A new unit test to cover this case was implemented, and I verified locally that it also works with the CUDA backend.
Thanks to @Moelf for noticing this!

[RF] Fix likelihood fits with constant probabliliy

---

roofit/roofit/src/RooBernstein.cxx
roofit/roofit/src/RooChebychev.cxx
roofit/roofit/src/RooTFnBinding.cxx
roofit/roofitcore/inc/RooCollectionProxy.h
roofit/roofitcore/src/RooPolyFunc.cxx
roofit/roofitcore/src/RooProfileLL.cxx
roofit/roofitcore/src/RooProjectedPdf.cxx

We want consistent collection proxy names, because it doesn't make sense
to set different names in the different constructors of the same class.
This only breaks code that assumes a certain proxy name, like the RooFit
HS3 JSON I/O.
Also implement a new collection proxy constructor that just copies the
name. This constructor is now the recommended one.

[RF] Consistent collection proxy names between constructors

---

proof/proof/inc/TProof.h
proof/proof/inc/TProofLite.h

since the tools will be removed in 6.38.00. RDataFrame and DistRDF can be used instead.

[proof] Deprecate PROOF and PROOFLITE with warnings

---

tmva/sofie/inc/TMVA/RModel.hxx
tmva/sofie/inc/TMVA/RModel_Base.hxx
tmva/sofie/src/RModel.cxx

The move constructor and assignment were defined manually, leading to the classic oversight that it was not updated when data members and base classes were added.
It is safer to let it get defined by the compiler, since also all data members are trivially movable and there is no manual memory management.
The only other channge that was required to make the default move work was to avoid a `const std::vector` data member of the RModel_Base class.

[TMVA][SOFIE] Fix RModel move constructor and assignment

---

roofit/roofitcore/src/RooAbsCollection.cxx

Fixes https://github.com/root-project/root/issues/18322

[RF] fix memleak in rooabscollection::find

---

documentation/users-guide/WebDisplay.md
gui/cefdisplay/inc/RCefWebDisplayHandle.hxx
gui/cefdisplay/src/RCefWebDisplayHandle.cxx
gui/qt6webdisplay/rootqt6.cpp

Method `ROOT::RWebDisplayHandle::DisplayUrl()` let display arbitrary web page in pre-configured web browser.
Now  Qt6 or CEF engine will work.
Update WebDisplay.md docu - add threads, TWebCanvas, widgets embeding

[webgui] let use `ROOT::RWebDisplayHandle::DisplayUrl` with qt6 and cef

---

cmake/modules/RootConfiguration.cmake
gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
gui/webdisplay/src/RWebDisplayHandle.cxx
gui/webdisplay/src/RWebWindow.cxx

Partially resolves https://root-forum.cern.ch/t/63182/ 
Let use snap installation of chromium on the platform where pre-compiled ROOT version is used
Also add special handling of temporary directory. 
snap version of chromium has limitation that files from `/tmp`
cannot be accessed. Therefore if TMPDIR is not set, try to use directly home directory.
Adjust batch code to use new functionality with temp directory
Delete temporary HTML file as soon as connection is established

[webgui] testing /snap/bin/chromium

---

bindings/pyroot/pythonizations/inc/TPyDispatcher.h
bindings/tpython/inc/TPyArg.h
bindings/tpython/inc/TPyReturn.h
bindings/tpython/inc/TPython.h
core/gui/inc/TContextMenu.h
core/gui/inc/TContextMenuImp.h
core/gui/inc/TControlBarImp.h
core/gui/inc/TInspectorImp.h
core/meta/inc/TInterpreterValue.h
core/meta/inc/TStreamerElement.h
core/metacling/src/TClingValue.h
core/winnt/inc/TWinNTSystem.h
geom/geom/inc/TGeoBoolNode.h
geom/geom/inc/TGeoCompositeShape.h
geom/geom/inc/TGeoElement.h
geom/geom/inc/TGeoPatternFinder.h
geom/geom/inc/TGeoPhysicalNode.h
math/physics/inc/TGenPhaseSpace.h
net/netxng/inc/TNetXNGFile.h
net/netxng/inc/TNetXNGFileStager.h
net/netxng/inc/TNetXNGSystem.h
tmva/pymva/inc/TMVA/PyMethodBase.h
tree/treeviewer/inc/TTVSession.h

Many classes have a proper web documentation in ROOT5 and 'lost' it in ROOT6.
See e.g.:
https://root.cern/root/html534/TMessage.html
vs
https://root.cern/doc/master/classTMessage.html
See also a lot of classes with no 'brief' description:
https://root.cern.ch/doc/master/annotated.html
This PR tries to fix 'some of these occurrences', not all cause it'll take some time to doxygenize all these.

[skip-ci] convert old THtml class comments to doxygen format

---

gui/webdisplay/src/RWebDisplayHandle.cxx

Probably caused by `clang-format` in commit 2361862592, but the suffix is not needed because `std::to_string` is already a `std::string`.

[webgui] Fix build on Windows

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/test/ntuple_view.cxx

Enables passing a type name string to `GetView<void>` to signal that the pointer has a different underlying type than the on-disk field's type. The field used by `RNTupleView` will be constructed with this type, in turn benefitting from RNTuples built-in type- and bounds-checking.
To illustrate further, assuming `myInt` is a `std::uint64_t` on-disk:
```cpp
std::int32_t myInt;
void* myIntPtr = &myInt;
auto myIntView = reader->GetView<void>("myInt", myIntPtr);
myIntView(0);
doSomething(myInt);
```
`GetView<void>` will currently always reconstruct the field used for loading the values from the on-disk descriptor. However, in the example above this can lead to undefined behavior when the actual values on disk don't fit in `std::int32_t`. The change proposed in this PR enables passing the type …

[ntuple] Add `GetView<void>` with type name string or `std::type_info` argument

---

tree/ntuple/v7/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/v7/src/RNTupleMerger.cxx
tree/ntuple/v7/test/ntuple_merger.cxx

ensures that the synthesized zero pages in the RNTupleMerger are properly compressed.
This PR fixes #18298

[ntuple] Merger: properly compress generated zero pages

---

tmva/sofie/inc/TMVA/ROperator_Gemm.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx

Clad can't do reverse mode AD if you use functions that take parameters that are at the same time an input and an output, like the matrix C in `sgemm_`.
This can be avoided by creating a wrapper where the input and output arrays are separate, and then there is an internal copy.
Having a wrapper like this improves the SOFIE code anyway, because the copying code is now written out by SOFIE before the `sgemm_` call. So by having a wrapper, one also reduces the verbosity of the generated code.

[TMVA][SOFIE] Implement wrapper for `BLAS::sgemm_` call

---

tmva/sofie/CMakeLists.txt
tmva/sofie/src/RModel.cxx
tmva/sofie/test/CMakeLists.txt

Make it possible to build SOFIE without TFile support with a hidden flag. We already use many of such hidden flags in RooFit. This will make it easy to build SOFIE without the ROOT dependency if one wants to.

[TMVA][SOFIE] Make it possible to build SOFIE without TFile support

---

cmake/modules/SetUpMacOS.cmake

This will fix a build error when building with the latest CMake (4.0) version
Related: https://github.com/root-project/root/issues/18312

[cmake][macOS] Auto-detect `CMAKE_OSX_SYSROOT` when not set

---

bindings/pyroot/pythonizations/python/ROOT/_facade.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th1.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/uhi_indexing.py

This PR introduces the [Unified Histogram Interface](https://uhi.readthedocs.io/en/latest/index.html) indexing functionality to the `TH1`-derived classes in ROOT. The changes include the addition of pythonizations to allow accessing, setting and slicing the histograms as per the UHI specifications.
Special "tag" functors added are `underflow`, `overflow`, `loc`, `rebin`, and `sum`.
See POC in #17111

[python] Add UHI Indexing Support (Access, Setting, and Slicing) to TH1 Derived Classes

---

roofit/roofitcore/src/RooAbsCollection.cxx

Fixes memory leaks found by valgrind. Similar to #18327

[RF] Fixing memory leak in RooAbsCollection::find

---

builtins/zlib/zutil.h

This applies https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9 from upstream.
fdopen() is not used by zlib anymore. The #defines are vestigial.
This make the build with builtin zlib fails on lastest MacOS/XCode

zlib: Remove fdopen #defines.

---

hist/histpainter/src/THistPainter.cxx

Fixes https://github.com/root-project/root/issues/18374

[hist] remove default 1deg offset in th2poly textn

---

tutorials/visualisation/graphs/gr001_simple.py
tutorials/visualisation/graphs/gr002_errors.py
tutorials/visualisation/graphs/gr003_errors2.py
tutorials/visualisation/graphs/gr004_errors_asym.py
tutorials/visualisation/graphs/gr005_apply.py
tutorials/visualisation/graphs/gr006_scatter.py
tutorials/visualisation/graphs/gr007_multigraph.py
tutorials/visualisation/graphs/gr009_bent_err.py
tutorials/visualisation/graphs/gr010_approx_smooth.py
tutorials/visualisation/graphs/gr011_graph2d_errorsfit.py
tutorials/visualisation/graphs/gr012_polar.py
tutorials/visualisation/graphs/gr013_polar2.py
tutorials/visualisation/graphs/gr014_polar3.py
tutorials/visualisation/graphs/index.md

Adds PyROOT equivalents to many of the Graphs tutorials.
Adds PyROOT equivalents to:
- gr001_simple
- gr002_errors
- gr003_errors2
- gr004_errors_asym
- gr005_apply
- gr006_scatter
- gr007_multigraph
- gr010_approx_smooth
- gr011_graph2d_errorsfit
- gr012_polar
- gr013_polar2
- gr014_polar3

[tutorials] Add Python equivalents to graphs tutorials

---

requirements.txt

A new release of `metakernel` that is compatible with ipython 9 came out last week:
https://github.com/Calysto/metakernel/releases/tag/v0.30.3
Hence, we don't need to restrict the ipython version anymore.
This reverts commit 795a48d609474e82f81ff759c3effc07a42eef19.

Revert "Restrict `ipython<9.0.0` in requirements.txt"

---

bindings/tpython/CMakeLists.txt
bindings/tpython/src/TPyArg.cxx
bindings/tpython/src/TPyClassGenerator.cxx
bindings/tpython/src/TPyReturn.cxx
bindings/tpython/src/TPython.cxx

This is recommended by the C Python documentation for runtime dynamic embedding of Python.
This prevents linker errors when building TPython against GIL-less Python.

[TPython] Use functions and not macros for reference counting

---

tmva/sofie/inc/TMVA/RModel.hxx
tmva/sofie/inc/TMVA/RModel_Base.hxx
tmva/sofie/inc/TMVA/RModel_GNN.hxx
tmva/sofie/inc/TMVA/RModel_GraphIndependent.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/src/RModel_GNN.cxx
tmva/sofie/src/RModel_GraphIndependent.cxx

Follows up on 035cf0c12cda8.
* Remove IO constructors of classes that don't support IO anyway because there is no `ClassDef` macro call, etc.
* Use implicit move constructors and assignments for GNN RModel classes, because all data members can be correctly moved
* Delete explicit destructors of helper classes that only reset the unique pointers, which would happen by default anyway
* Don't delete copying of RModel and derived classes explicitly. Copying is already implicitly deleted because of the `std::unique_ptr` data members

[tmva][sofie] Remove explicit function definitions that can be implicit

---

tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/test/TestCustomModelsFromONNX.cxx

The `std::vector<bool>` is a special class that doesn't wrap contiguous
memory. It limits the usability of the return object (e.g. the memory
can't be adopted copy-free by a NumPy array). It prevents us
from using C-style arrays under the hood and differentiating through the
inference function.
Also, further simplify the code that deals with the return objects.

[TMVA][SOFIE] Use `uint8_t` instead of `bool` in return types

---

tree/ntuple/v7/doc/README.md

(there may be more documentation updates required, this PR is to improve https://root.cern/doc/master/group__NTuple.html specifically)

[skip-ci][ntuple] Update documentation in Doxygen group

---

core/textinput/CMakeLists.txt

[skip-ci] fix typo in CMake comment

---

.github/workflows/root-ci.yml

6.36 will be released at the end of May. EOL of that distro is scheduled for July 11th.
This will also free one linux build slot for each and every PR to the main and future v6-36-00-patches branch.

[ci] Remove Ubuntu 24.10 builds

---

tree/ntuple/v7/inc/ROOT/RCreateFieldOptions.hxx
tree/ntuple/v7/inc/ROOT/REntry.hxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/v7/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/v7/inc/ROOT/RFieldBase.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleFillStatus.hxx
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx
tree/ntuple/v7/inc/ROOT/RNTupleRange.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReadOptions.hxx
tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/v7/inc/ROOT/RNTupleView.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/v7/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/v7/test/ntuple_basics.py
tutorials/io/ntuple/ntpl011_global_temperatures.C

removes the deprecated `using` declarations for the RNTuple public types moved out of Experimental.

[ntuple] Remove deprecated typedefs

---

tutorials/io/ntuple/ntpl001_staff.C
tutorials/io/ntuple/ntpl002_vector.C
tutorials/io/ntuple/ntpl004_dimuon.C
tutorials/io/ntuple/ntpl005_introspection.C
tutorials/io/ntuple/ntpl007_mtFill.C
tutorials/io/ntuple/ntpl008_import.C
tutorials/io/ntuple/ntpl009_parallelWriter.C
tutorials/io/ntuple/ntpl010_skim.C
tutorials/io/ntuple/ntpl011_global_temperatures.C
tutorials/io/ntuple/ntpl012_processor_chain.C
tutorials/io/ntuple/ntpl013_staged.C
tutorials/io/ntuple/ntpl014_framework.C
tutorials/io/ntuple/ntpl015_processor_join.C

... if they use only public interfaces that will be stable in 6.36.

[ntuple] Remove experimental notice from tutorials

---

tree/ntuple/v7/inc/ROOT/RNTupleReader.hxx
tree/ntuple/v7/src/RFieldMeta.cxx
tree/ntuple/v7/src/RNTupleView.cxx
tree/ntuple/v7/test/CustomStruct.hxx
tree/ntuple/v7/test/CustomStructLinkDef.h
tree/ntuple/v7/test/rfield_class.cxx

[ntuple] support rules with source class != dest class

---

tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx

This makes it possible to avoid memory allocations during inference, also also will help when differentiating through the code with Clad.
Here is a showcase of how the output code of SOFIE would look like with this change. Note that I chose the name `doInfer` for the new function to better distinguish it from the existing `infer` method, but I'm happy to rename it to anything including `infer` as well.
```c++
struct Session {
...
// Inference implementation is forward declared:
void doInfer(float *tensor_x,
float *tensor_theory_params,
std::vector<float> &output_tensor_linear_3);
...
std::vector<float> infer(float *tensor_x, float *tensor_theory_params)
{
std::vector<float> output_tensor_linear_3;
doInfer(tensor_x, tensor_theory_params, output_tensor_linear_3);
return …
```

[tmva][sofie] Add overload for inference code that takes output params

---

core/base/inc/TMemberInspector.h
core/base/src/TMemberInspector.cxx
core/meta/inc/TProtoClass.h
core/meta/src/TClass.cxx
core/meta/src/TProtoClass.cxx
core/metacling/src/TCling.cxx

In `GetRealData`, do not complain about missing information about data members that are directly or indirectly within a transient member of the top level class.
This solves the underlying problem from https://github.com/root-project/root/pull/15733

TProtoClass: do not complain innards of transients.

---

.github/workflows/root-docs-master.yml

Force the full build of ROOT for doc master. The incremental build might be the cause
of the problem we have now to build the doc after this [root-project/root#17722](https://github.com/root-project/root/pull/17722)

[skip-ci][doc] force full build of root

---

graf2d/graf/src/TLatex.cxx

Set the TMathText color in TLatex when a TLatex is painted with TMathText.
The problem was seen here https://root-forum.cern.ch/t/issue-with-text-size-and-color-in-tlatex/63380

[graphics] set TMathText color in TLatex

---

tmva/sofie/inc/TMVA/ROperator.hxx
tmva/sofie/inc/TMVA/ROperator_Shape.hxx

This PR modifies the ShapeInference method of the base ROperators class that is not needed to be pure virtual since not every ROperator will not be implementing or using it, like the Shape Operator.

[tmva][sofie] shape and type inference methods need not be pure virtual

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx

The heuristic checks if the token "Clone" is present in the method name being called and gives Python the ownership of the returned object. This is valid behaviour for methods such as `TObject::Clone` where the ownership of the returned value is given to the caller. But the `CPPOverload::Set` method gets as the method name being called the actual function name concatenated with the full template argument list. For example, given the function
```
template <typename T>
void foo();
```
When it passes through this method its name will be `foo<T>`. This behaviour has an undesired side-effect. When `T` is a type with the token `Clone` in its name, then the heuristic will trigger and Python will take ownership of the return value. This is the root cause of the problem seen at …

[python] Improve CPyCppyy heuristic for Clone methods

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py

This PR introduces some refactoring to the current UHI implementation in ROOT:
- Updated the slicing logic to include or exclude flow bins as needed: setting with a scalar excludes flow bins; setting with an `ndarray` may or may not include flow bins depending on the shape of the array.
- Added an equality operator to validate histogram shape and values (this is particularily needed for testing).
- Implemented -1 to access the last valid bin in an axis.

[python] UHI Refactoring: Slicing Logic, Equality Operator, and Negative Indexing

---

tutorials/machine_learning/index.md

Add tables for grouping the machine learning tutorials

[skip-ci][tutorials] Enhance machine learning tutorial presentation

---

core/clingutils/CMakeLists.txt
interpreter/CMakeLists.txt

This reverts commit https://github.com/root-project/root/commit/02b0dc129d0c62e6bf7252bb89e8ec0777a40640. It was partially incorrect and should not use LLVM_DIR, which is only a hint specified by the user.   We need more time to decide on and test a better solution.
This reverts commit https://github.com/root-project/root/commit/3ef1193b0bd3d937e87815d0dfdc12370f8d190d. The
taken approach is not the right direction, this should be handled on the linking side of libCling as discussed post-merge in the pull request:  https://github.com/root-project/root/pull/18386

Revert PR #18386

---

math/mathcore/inc/Math/CladDerivator.h
tmva/sofie/test/CMakeLists.txt
tmva/sofie/test/TestGemmDerivative.cxx

This PR introduces the pullback for the Gemm operator (`Gemm_Call `, introduced in #18349), such that this can be differentiated by Clad. A test is added to ensure that a function incorporating `Gemm_Call` is differentiated correctly.
Cc @guitargeek

[TMVA][SOFIE] Implement custom pullback for Gemm operator and corresponding test

---

core/base/src/TROOT.cxx
core/meta/inc/TProtoClass.h
core/meta/src/TProtoClass.cxx
io/io/src/TGenCollectionProxy.cxx
io/io/src/TStreamerInfo.cxx

In the case when we need a TStreamerInfo for a pair and:
* There is no dictionary for that pair
* There is not yet a TClass created for that pair
* There is interpreter information about that pair
Then the interpreter information takes precedence over the one
`TStreamerInfo::GenerateInfoForPair` is generating and thus the
one being generated need to be deleted.
This fixes #18343 
A side effect of the investigation was fixing double deletes and additional memory leak when deleting TClass which could now be enable in 'TROOT::~TROOT`.

[io] Delete unused std::pair StreamerInfo.

---

tree/tree/inc/LinkDef.h

The class is transient so the dictionary is not needed by itself.  However not having the dictionary leads to a lookup for the class namespace 'ROOT::Experimental' and this leads to loading of the 'first' library that has a dictionary for something in 'ROOT::Experimental'. This is undesirable (i.e. load the Eve library for a simple TTree job), so we create the dictionary for TBulkBranchRead.
This solves the unexpected test failures seen in https://github.com/root-project/root/pull/18396
The test will be added in the roottest companion PR for https://github.com/root-project/root/pull/18402 (as it makes testing this much easier).

Add dictionary for TBulkBranchRead.

---

README/ReleaseNotes/v636/index.md

People are aware that the parameter transformations can be a bottleneck in Minuit (see for example [this
discussion](https://github.com/scikit-hep/pyhf/issues/2585#issue-2988084145)). It's worth it to mention the caching of transformed parameter values with the new ROOT release, such that people know that the situation improved with Minuit2.

[skip-ci] Mention Minuit2 optimizations in release notes

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th2.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_th3.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/conftest.py
bindings/pyroot/pythonizations/test/uhi_indexing.py
bindings/pyroot/pythonizations/test/uhi_plotting.py

As a follow-up to #17950, this PR extends the [Unified Histogram Interface](https://uhi.readthedocs.io/en/latest/index.html) plottable histogram functionality in ROOT to `TH2` and `TH3` derived classes.

[python][UHI] Add UHI plotting pythonizations to TH2 and TH3 derived classes

---

cmake/modules/RootConfiguration.cmake
gui/webdisplay/inc/ROOT/RWebDisplayHandle.hxx
gui/webdisplay/src/RWebDisplayHandle.cxx

Like for chromium, create temporary files
in home directory rather than in /tmp directory where it may not have access.
Also firefox profile create in such directory
Cleanup should be better while `runfirefox.sh` ensure remove of tmp files

[webgui] detect firefox in /snap/bin

---

math/mathcore/inc/Math/CladDerivator.h

Forward declare `sgemm_` in custom derivatives header, instead of using the forward declaration wrapped inside the SOFIE namespace. Otherwise, the `CladDerivator.h` header is broken in case ROOT was built without TMVA.
This change is covered by the SOFIE unit test `TestGemmDerivative`, and it was verified locally that the RooFit AD tests work again after this PR, even if ROOT was built with `tmva=OFF`.
Follows up on #18364.

[math] Forward declare `sgemm_` in custom derivatives header

---

hist/hist/src/TFormula.cxx

Under the hood, a TFormula declares a function to the interpreter. This function is then used also for differentiating through the TFormula with Clad. However, only the gradient with respect to the parameters `p` is requested, and the upcoming Clad release expects the other input arguments to be marked `const` for optimization purposes.
This will fix the problems that we saw in the draft PR that tries to update the Clad version inside ROOT to the current `master`:
https://github.com/root-project/root/pull/18383

[hist] Mark input `x` of the declared TFormula function as `const`

---

io/io/test/CMakeLists.txt
io/io/test/TFileTests.cxx
net/net/src/TWebFile.cxx
roottest/python/cmdLineUtils/CMakeLists.txt
roottest/root/io/webfile/CMakeLists.txt

Fixes https://github.com/root-project/root/issues/18453
Sibling PR: https://github.com/root-project/roottest/pull/1308

[test] disable web tests if davix is OFF

---

tutorials/CMakeLists.txt
tutorials/analysis/dataframe/df101_h1Analysis.py
tutorials/analysis/dataframe/index.md

Adds the PyROOT equivalent to the tutorial `df101_h1Analysis.c` which uses RDataFrame for the H1 example analysis.
Includes and links to tutorial `df101_h1Analysis.py`

[tutorials] Add Python tutorial for h1 analysis in RDF

---

CMakeLists.txt

Build on lxplus was failing after this commit:
dd2ec8be32539b31e6f1e65f4f3fa9e19c25984d

[cmake] Use consistent uppercase in `if(NOT WIN32)`

---

core/cont/inc/TCollectionProxyInfo.h
math/mathcore/inc/Math/DistSampler.h
math/mathcore/inc/Math/Functor.h
tree/ntuple/inc/ROOT/RNTupleMetrics.hxx

This will fix build errors like:
`error: declaration of 'type_info' must be imported from module 'std.std_typeinfo' before it is required`
in https://github.com/root-project/root/pull/18369 when building with C++23

[core] Add missing includes

---

io/io/src/TStreamerInfoActions.cxx

BP of https://github.com/root-project/root/pull/18456

[BP 636][io] fix small memleak in streamerInfoActions

---

tree/dataframe/test/dataframe_nodes.cxx

Fix the following compiler error on Windows:
```
dataframe_nodes.cxx(86,40): error C3493: 'N' cannot be implicitly captured because no default capture mode has been specified
```

[DF][Win] Fix compiler error C3493

---

tree/dataframe/test/CMakeLists.txt

Fix the following compiler error on Windows:
```
datasource_ntuple.cxx(1,1): error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

[DF][Win] Fix compiler error C1128

---

tree/ntuple/doc/BinaryFormatSpecification.md

Fix minor typos in BinaryFormatSpecification.md

[skip-ci][ntuple][doc] RNTuple Binary Spec: fix typos in Page Locations section

---

roottest/root/io/bigevent/IoBigEventGeneration.cxx

Fix the following compilation warning on Windows:
```
IoBigEventGeneration.cxx(355): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'unsigned __int64'
IoBigEventGeneration.cxx(355): note: consider using '%zd' in the format string
```

[Windows] Fix warning C4477 + code formatting

---

js/LICENSE
js/changes.md
js/modules/core.mjs
js/modules/draw/TTree.mjs
js/modules/gui/utils.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/tree.mjs
js/modules/webwindow.mjs

1. New draw options:
- 'pol' and 'arr_colz' draw option for `TH2`
- 'col7' uses bar offset and width for `TH2`
- 'cont5' for `TGraph2D` using Delaunay algorithm
- 'chord' drawing of `TH2` implements zooming
- 'box1' for `TH3` with negative bins
- 'same' option for first histogram on pad, draw without creating `TFrame`
- 'rangleNN' for `TGraphPolargram`, also support fAxisAngle member
- 'N' and 'O' for `TGraphPolargram` for angle coordinate systems
- 'arc' for `TPave` and derived classes
- 'allbins' for histograms to display underflow/overflow bins
- Poisson errors for `TH1`/`TH2`, https://root-forum.cern.ch/t/62335/
- test fSumw2 when detect empty `TH2` bin, sync with https://github.com/root-project/root/pull/17948
2. New supported classes:
- `TF12` - projection of `TF2`
- `TLink` and …

[jsroot] version 7.9.0 for [6.36]

---

graf2d/gpad/src/TPad.cxx

Use integer conversion once and then just check boundary with ymin
Alternative to #18494

[gpad] avoid potential float precision lost in PaintHatches

---

tree/ntuple/inc/ROOT/RCluster.hxx
tree/ntuple/inc/ROOT/RClusterPool.hxx
tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/inc/ROOT/RNTupleMerger.hxx
tree/ntuple/inc/ROOT/RPageStorage.hxx
tree/ntuple/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/src/RCluster.cxx
tree/ntuple/src/RClusterPool.cxx
tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/src/RPageStorage.cxx
tree/ntuple/src/RPageStorageDaos.cxx
tree/ntuple/src/RPageStorageFile.cxx
tree/ntuple/test/ntuple_cluster.cxx
tree/ntuple/test/ntuple_endian.cxx
tree/ntupleutil/v7/src/RNTupleExporter.cxx

BP of https://github.com/root-project/root/pull/18473

 [6.36][ntuple] Move RCluster/RClusterPool out of Experimental

---

roottest/cling/staticinit/CMakeLists.txt
roottest/cling/staticinit/execROOT-7775.C

The copy is unnecessary, we just have to use the existing `RootExternalIncludes` CMake variable to accomplish the same goal.

roottest: Do not use copy in test execROOT-7775

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
net/http/src/THttpServer.cxx

JSROOT 7.9.0 is base version for ROOT 6.36 and has to be used as fallback for jupyter

Use jsroot 7.9.0 in jupyter and http server docu [6.36]

---

math/genvector/inc/Math/GenVector/Rotation3D.h

Fixes https://root-forum.cern.ch/t/tvector3-rotate-to-arbitrary-rotation-using-xyzvector/63244
Alternative to https://github.com/root-project/root/pull/18462

[math][GenVector] Add access operator for Rotation3D

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

This release introduces significant updates, including support for clang versions 10 through 20 and improved diagnostics for unsupported features. Forward mode now handles variadic functions, while reverse mode sees major enhancements like marking const methods as non-differentiable, enabling differentiation of global variables and static member functions, generating constructor pullbacks automatically, and reducing tape usage through optimizations. CUDA support has been expanded with better handling of device pullbacks and kernel variables. For details, please see the release [notes](https://github.com/vgvassilev/clad/releases/tag/v1.10).

[clad] Bump clad to v1.10.

---

bindings/pyroot/pythonizations/test/import_load_libs.py

```
5/1406 Test   #12: pyunittests-bindings-pyroot-pythonizations-pyroot-import-load-libs ............................***Failed    1.35 sec
test_import (import_load_libs.ImportLoadLibs.test_import)
Test libraries loaded after importing ROOT ... ERROR
======================================================================
ERROR: test_import (import_load_libs.ImportLoadLibs.test_import)
Test libraries loaded after importing ROOT
----------------------------------------------------------------------
File "/builddir/build/BUILD/root-6.34.06/bindings/pyroot/pythonizations/test/import_load_libs.py", line 124, in test_import
raise Exception('Found not whitelisted libraries after importing ROOT:' \
Exception: Found not whitelisted libraries after importing ROOT: …
```

Add oqsprovider and liboqs to whitelist to address CentOS 10 failure

---

graf2d/gpad/src/TPad.cxx

applies fixes to clang-tidy diagnostics in class TPad

[gpad] TPad fix clang-tidy warnings

---

tree/ntuple/inc/ROOT/RFieldBase.hxx
tree/ntuple/inc/ROOT/RNTupleJoinTable.hxx
tree/ntuple/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/src/RNTupleJoinTable.cxx
tree/ntuple/src/RNTupleProcessor.cxx
tree/ntuple/test/ntuple_processor.cxx
tree/ntuple/test/ntuple_processor_chain.cxx
tree/ntuple/test/ntuple_processor_join.cxx

This PR adds the possibility to compose `RNTupleJoinProcessor`s from existing processor objects. Similar functionality is already in place for the `RNTupleChainProcessor` (see #17393), so with these additions the `RNTupleProcessor` is (almost*) fully composable.
*One caveat: the case where an auxiliary processor in the join is a join itself is not yet properly handled. This will be handled in a follow-up PR.

[ntuple] Make `RNTupleJoinProcessor` composable

---

core/clingutils/src/TClingUtils.cxx
interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h

Those routines are at the very least looking up information into Clang and thus need to prevent concurrent updates.  Some of the routines can also sometimes induces changes in Clang (eg. template instantiation).
This fixes #18520 and #18519

[cling] The LookupHelper routines need the ROOT lock.

---

roofit/roofitcore/src/RooFormula.cxx
roofit/roofitcore/src/RooFormula.h
roofit/roofitcore/src/RooFormulaVar.cxx
roofit/roofitcore/src/RooGenericPdf.cxx

This fixes problems when the variable ist in the RooFormula gets out of
sync with the proxies in the RooFormulaVar or the RooGenericPdf, which
are using the RooFormula under the hood. This can happen when the
variables are renamed using `SetName()`, for example in the NLL creation
for simultaneous pdfs with the new RooFit CPU backend.
This fixes a bug reported by ATLAS.
Also some general `RooFormula` improvements in separate PRs.

[RF] Use the actual proxy list as input for RooFormula::doEval()

---

core/clingutils/src/TClingUtils.cxx
interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h

Back-port of https://github.com/root-project/root/pull/18522
Those routines are at the very least looking up information into Clang and thus need to prevent concurrent updates. Some of the routines can also sometimes induces changes in Clang (eg. template instantiation).
This fixes https://github.com/root-project/root/issues/18520 and https://github.com/root-project/root/issues/18519

[v636][cling] The LookupHelper routines need the ROOT lock

---

CMakeLists.txt
core/clingutils/src/TClingUtils.cxx
interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h
test/CMakeLists.txt

Those routines are at the very least looking up information into Clang and thus need to prevent concurrent updates. Some of the routines can also sometimes induces changes in Clang (eg. template instantiation).
This fixes https://github.com/root-project/root/issues/18520 and https://github.com/root-project/root/issues/18519
Back-port of https://github.com/root-project/root/pull/18522

[v634][cling] The LookupHelper routines need the ROOT lock.

---

roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx

The following code provided by Tomas Dado lead to a crash:
```
RooStats::HistFactory::Measurement meas("meas", "meas");
meas.SetOutputFilePrefix("test");
meas.SetPOI("pt0_m0_y0_XSec");
meas.CollectHistograms();
std::unique_ptr<RooWorkspace> work(RooStats::HistFactory::MakeModelAndMeasurementFast(meas));
```
This is caused by a nullptr being passed to a HistFactory function. By returning early, the crash is avoided, and the following error message is produced:
`Error in <RooStats::HistFactory::HistoToWorkspaceFactoryFast::MakeCombinedModel>: Input vectors are empty - return a nullptr`

[HF] Prevent a crash when an empty measurement is created.

---

gui/webdisplay/src/RWebWindowWSHandler.hxx
gui/webdisplay/src/RWebWindowsManager.cxx
js/LICENSE
js/changes.md
js/modules/base/ObjectPainter.mjs
js/modules/base/RObjectPainter.mjs
js/modules/core.mjs
js/modules/draw/TTree.mjs
js/modules/gpad/RCanvasPainter.mjs
js/modules/gpad/RFramePainter.mjs
js/modules/gpad/RPadPainter.mjs
js/modules/gpad/TCanvasPainter.mjs
js/modules/gpad/TFramePainter.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/gui/menu.mjs
js/modules/gui/utils.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THStackPainter.mjs
js/modules/hist2d/THistPainter.mjs
js/modules/tree.mjs
js/modules/webwindow.mjs
ui5/canv/controller/Canvas.controller.js

1. Fix - colz handling on `THStack`, avoid multiple palette drawings
2. Fix - bug in pad.Divide context menu command
3. Fix - palette not adjusted when 'same' draw option used for histogram
4. Fix - drag and drop of histograms on empty sub-pads
Also introduce `WebGui.Debug` gEnv variable to enable more debug output on JSROOT side.
More messages will be printed on console

[jsroot] dev 29/04/2025

---

js/changes.md
js/modules/core.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/hist2d/TH2Painter.mjs
js/modules/hist2d/THStackPainter.mjs
js/modules/hist2d/THistPainter.mjs

1. Fix - colz handling on `THStack`, avoid multiple palette drawings
2. Fix - bug in pad.Divide context menu command
3. Fix - drag and drop of histograms on empty sub-pads

[jsroot] 7.9.x 29/04/2025 [6.36]

---

core/meta/src/TClass.cxx

Prevent memory hoarding for `GetClass("int")` or any other numerical types.
This addresses https://root-forum.cern.ch/t/repeatedly-mapping-branches-slowly-fills-memory/63412.
This fix #18536.
This relates to https://github.com/root-project/root/issues/9029 but does not solve it completely.  It solves the sub-cases of #9029 where the typedef is known to `TROOT::GetListOfTypes`.

meta: Prevent memory hoarding for `GetClass("int")`

---

geom/vecgeom/inc/TGeoVGShape.h
geom/vecgeom/src/TGeoVGShape.cxx

The signature of the function ComputeNormal has changed in the base class TGeoBBox. Add const qualifier to the function also in the derived class.
this PR introduce the fix from the v6-36-00-patches branch (#18508) to the master branch.

[geom] Fix vecgeom interface

---

core/meta/src/TClass.cxx

or any other numerical types.
Backport of https://github.com/root-project/root/pull/18537

[v632] meta: Prevent memory hoarding for `GetClass("int")`

---

core/meta/src/TClass.cxx

or any other numerical types.# This Pull request:
Backport of https://github.com/root-project/root/pull/18537

[v634] meta: Prevent memory hoarding for `GetClass("int")`

---

core/meta/src/TClass.cxx

or any other numerical types.
Backport of https://github.com/root-project/root/pull/18537

[v636] meta: Prevent memory hoarding for `GetClass("int")`

---

core/clingutils/CMakeLists.txt
interpreter/CMakeLists.txt

This allows configuring with `builtin_llvm=OFF` and a system-provided LLVM with `LLVM_LIBDIR_SUFFIX`, for example on Alma Linux.

[CMake] Fix build with LLVM_LIBDIR_SUFFIX

---

graf2d/gpadv7/inc/ROOT/RPadLength.hxx

Fixes warning: "space between quotes and suffix is deprecated in C++23 [-Wdeprecated-literal-operator]"

[graf2d] Fix C++23 warnings about spaces in literal operator

---

core/base/test/CMakeLists.txt
core/base/test/TRefTests.cxx
core/meta/src/TStreamerElement.cxx

Instead of all data members the type of which has a name beginning with "TRef".
Fixes [ROOT-7052](https://its.cern.ch/jira/browse/ROOT-7052)
This PR builds on top of the solid work done here https://github.com/root-project/root/pull/14930.

[meta] Return exec id of TRef, TRefArray and derived data members

---

roofit/histfactory/inc/RooStats/HistFactory/Systematics.h
roofit/histfactory/src/Channel.cxx
roofit/histfactory/src/HistRef.cxx

For HistFactory models with numerous histograms, a significant amount of time (minutes) could be spend cleaning the list of cleanups. Here, the registration of histograms to directories is blocked, so the list of cleanups stays empty.
Fix #18172.

[v636][HF] Prevent histograms from registering in the list of cleanups.

---

.github/workflows/root-ci-config/buildconfig/alma9.txt
.github/workflows/root-ci-config/buildconfig/fedora41.txt
.github/workflows/root-ci-config/buildconfig/fedora42.txt

A new version of Pythia 8 was released recently and propagated to the Fedora and AlmaLinux packages, which should have fixed the build failures of our Pythia 8 bindings.
This reverts #17732 and also adds the pythia8 interface to the Fedora builds.

[ci] Add back `pythia8=ON` to alma9 and Fedoras

---

.github/workflows/root-ci-config/buildconfig/alma9-clang.txt
.github/workflows/root-ci-config/buildconfig/alma9.txt
.github/workflows/root-ci-config/buildconfig/fedora41.txt
.github/workflows/root-ci-config/buildconfig/fedora42.txt

When these configurations were created, it was thought that AlmaLinux and Fedora don't have any package for nlohmann-json. I guess that was an understandable oversight, because the package doesn't have "nlohmann" in the name. It's just called `json-devel`, and was added to all relevant CI images earlier today.

[ci] Set `builtin_nlohmannjson=OFF` also for AlmaLinux and Fedora

---

README/ReleaseNotes/v638/index.md
roofit/roofitcore/inc/RooRealVar.h
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooRealVar.cxx
roofit/roofitcore/test/stressRooFit_tests.h
roofit/roofitcore/test/test_lib.h
tutorials/roofit/roofit/rf111_derivatives.C
tutorials/roofit/roofit/rf111_derivatives.py

In previous ROOT versions, if you set the value of a variable with
`RooRealVar::setVal()`, the value was silently clippend when it was
outside the variable range. This silent mutation of data can be
dangerous. With ROOT 6.36, an exception will be thrown instead. If you
know what you are doing and want to restore the old clipping behavior,
you can do so with `RooRealVar::enableSilentClipping()`, but this is not
recommended.
This change caught a logic error in `stressRooFit` where a background
fraction was randomized to be outside the `[0,1]` interval. That part of
the test was therefore removed (it was already removed from the
corresponding tutorial).
Closes https://github.com/root-project/root/issues/6937.

[RF] Error out when setting out-of-range variable value instead of clipping

---

geom/vecgeom/inc/TGeoVGShape.h
geom/vecgeom/src/TGeoVGShape.cxx

BP of https://github.com/root-project/root/pull/18530
The signature of the function ComputeNormal has changed in the base class TGeoBBox. Add const qualifier to the function also in the derrived class.
(cherry picked from commit 8dc927038f56b3a91997dda4d22fdde7a00febc6)
This supersedes https://github.com/root-project/root/pull/18508

[BP 6.36][geom] Fix vecgeom interface

---

builtins/zlib/inffast.c

**Description**
This PR fixes a potential vulnerability in inflate_fast() that was cloned from zlib but did not receive the security patch. The original issue was reported and fixed under https://github.com/madler/zlib/commit/9aaec95e82117c1cb0f9624264c3618fc380cecb.
This PR applies the same patch to eliminate the vulnerability.
References
https://nvd.nist.gov/vuln/detail/cve-2016-9841
https://github.com/madler/zlib/commit/9aaec95e82117c1cb0f9624264c3618fc380cecb

[zlib] Fix potential vulnerable cloned functions

---

builtins/zlib/inftrees.c

Description
This PR fixes a potential vulnerability in inflate_table() that was cloned from zlib but did not receive the security patch. The original issue was reported and fixed under https://github.com/madler/zlib/commit/6a043145ca6e9c55184013841a67b2fef87e44c0.
This PR applies the same patch to eliminate the vulnerability.
References
https://nvd.nist.gov/vuln/detail/CVE-2016-9840
https://github.com/madler/zlib/commit/6a043145ca6e9c55184013841a67b2fef87e44c0

[zlib-table] Fix potential vulnerable cloned functions

---

bindings/pyroot/pythonizations/src/TTreePyz.cxx

It's not clear to me how it can even happen that TClass::GetClass() is `nullptr` for the type of a TTree branch.
It looks like the check is superfluous, and by not doing it we can avoid the memory hogging of `GetClass()` for standard vector types.
My suspicion is that the `klass` variable was there because many years ago, cppyy used ROOT casting via TClass, which got replaced at some point from `BindRootObjectNoCast( *(char**)branch->GetAddress(), klass )` to `BindCppObjectNoCast( *(char**)branch->GetAddress(), Cppyy::GetScope( branch->GetClassName() ) )` (see commit 968759856e777). Before that refactor, making the sanity check that `klass` was not `nullptr` made sense. But it looks like this is not needed anymore since the casting is done exclusively with cppyy.
Closes #18524.

[Python] Don't call `TClass::GetClass()` on branch type in TTreePyz

---

gui/gui/src/TGNumberEntry.cxx

An attempt to fix and improve some old code in `TGNumberEntry` by:
- fixing some broken logic
- simplifying some functions
- improving safety by adding bounds checks where appropriate
This is not an exhaustive pass on the file, as there are many other places that could use a pass or a rewrite. However it should address some of the more glaring safety concerns - particularly, it removes all uses of `strcpy` and the coverity annotations.
I haven't tested this code yet so I'm opening this as a draft PR. Feel free to comment on it already.
This PR fixes #17334

[gui] Some fixes to TGNumberEntry

---

gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowsManager.cxx

By default it is 10 and normally not used - 
all  messages directly send by ROOT via WebSocket to the clients. 
But in some special applications default value too low and need to be adjusted.
Now default value can be changed with "WebGui.QueueLength" rootrc parameter.
Print more info in error message

[webgui] let configure window queue length

---

tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/test/ntuple_merger.cxx

For consistency with the rest of the RNTuple codebase, use the RLogger macros rather than the TError ones.
Notably, this changes the log category from `RNTuple::Merge` to `ROOT.NTuple`.

[ntuple] RNTupleMerger: use RLogger instead of TError-style logging

---

math/genvector/inc/Math/GenVector/VectorUtil.h
math/genvector/test/testGenVector.cxx
math/physics/src/TRotation.cxx

Fixes https://root-forum.cern.ch/t/tvector3-rotate-to-arbitrary-rotation-using-xyzvector/63244

[math] implement genvector custom axis rotation

---

config/root-config.in

...where `ROOTNTupleUtil` only gets added when the `root7` feature is enabled.

[config] Add `ROOTNTuple` and `ROOTNTupleUtil` to libs

---

io/io/src/TFile.cxx

since the entire netx code was removed for 6.34 by 65088a9
Fixes #18623

[io] Remove from url parameters parsed by TXNetFile

---

tree/ntuple/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/src/RNTupleProcessor.cxx
tree/ntuple/test/ntuple_processor.cxx
tree/ntuple/test/ntuple_processor_chain.cxx
tree/ntuple/test/ntuple_processor_join.cxx

As discussed in https://github.com/root-project/root/pull/18224#discussion_r2055968876, having a separate overload for `processorName` causes a lot of bloat. With this PR, instead of having an overload that takes `processorName`, now it is just an optional argument with the empty
string as a default argument. This simplifies and de-bloats the interface quite significantly.
The constructors for each `RNTupleProcessor` subclass have been refactored to reflect this new argument order, and the "burden" of inferring the processor's name has been moved from the factories to the constructors.

[ntuple] Simplify `RNTupleProcessor` factory methods

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rvec.py
bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py
bindings/pyroot/pythonizations/test/rvec_asrvec.py

This PR extends support for strings stored in NumPy arrays with `dtype=object` or `dtype=numpy.str_` in `AsRVec`, enabling conversions of dataframes with string columns to `RDataFrame` using `FromNumpy` and `FromPandas`.
This PR fixes #18534

[python][RDF] Add Support for String Columns in AsRVec

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdataframe.py
bindings/pyroot/pythonizations/test/rdataframe_makenumpy.py

> [!NOTE]  
> This PR should be merged **after**  #18571.
This PR introduces logic to detect and handle the creation of empty RDataframes from empty numpy arrays, as long as the array's `dtype` is supported by `RVec`, see the [docs](https://root.cern/doc/master/classROOT_1_1VecOps_1_1RVec.html).
As explained on the issue's thread, the issue's reproducer will still not work with this PR.
This PR fixes #18581

[python][RDF] Handle the creation of an empty RDataFrame in _MakeNumpyDataFrame

---

tmva/sofie/inc/TMVA/ROperator_GRU.icc
tmva/sofie/inc/TMVA/ROperator_LSTM.icc
tmva/sofie/inc/TMVA/ROperator_RNN.icc
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/src/SOFIE_common.cxx

This is good practice, as it makes it clear to the reader and compiler that the data will not be modified. This also helps Clad in generating optimized gradients. Actually, it is a requirement for differentiation through the emitted code with the new Clad v1.10, which is now part of ROOT.
In a separate commit, refactor the reading of tensors from an input stream to avoid duplicating boilerplate code in the generated inference session code.

[tmva][sofie] Mark input arrays to interence function as `const`

---

tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/StreamerField.hxx
tree/ntuple/test/StreamerFieldLinkDef.h
tree/ntuple/test/rfield_streamer.cxx

Before, classes without explicit constructor / destructor but containing a non-trivial member would still be flagged as trivial.
This fixes the first of two issues causing crashes found by CMS: https://github.com/cms-sw/cmssw/issues/48005

[ntuple] Fix setting of trivial traits for `RStreamerField`

---

tree/ntuple/inc/ROOT/RField.hxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/CustomStruct.hxx
tree/ntuple/test/CustomStructLinkDef.h
tree/ntuple/test/rfield_class.cxx

... and delete them in the destructor of `RClassField`. This is important for non-trivial types where zero-initialization is not sufficient or that need to free resources in their destructor (for example a `std::vector` constructed by an `RVectorField`).
This fixes the second issue causing crashes found by CMS: https://github.com/cms-sw/cmssw/issues/48005

[ntuple] Correctly construct values in staging area

---

math/mathcore/inc/Math/Minimizer.h
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnMinos.cxx

Fixes https://root-forum.cern.ch/t/what-is-the-default-value-of-maxfunctioncalls/62794

[skip-ci][nfc][math] Improve docu wrt max function calls in Minuit2

---

tmva/sofie/inc/TMVA/ROperator_Comparision.hxx
tmva/sofie/inc/TMVA/ROperator_Where.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/src/SOFIE_common.cxx

The `std::vector<bool>` is a special type that doesn't wrap contiguous memory. For compatibility with basic C interfaces and to be differentiable with Clad, it would be better to not use it.

[tmva][sofie] Avoid `std::vector<bool>` for tensor types

---

.github/workflows/root-ci-config/build_utils.py

When there is a problem during upload, the exception is correctly caught but then during handling, another exception occurs:
```
File "/__w/root/root/.github/workflows/root-ci-config/build_utils.py", line 261, in upload_file
build_utils.print_warning(f"""Attempt {attempt} to upload {src_file} to {dest_object} failed. Retrying in {sleep_time} seconds...""")
NameError: name 'build_utils' is not defined
```
---
Note: I didn't test if this fully fixes the try logic...

[ci] Try to fix retry logic

---

tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/test/ntuple_merger.cxx

Followup of https://github.com/root-project/root/pull/18609#discussion_r2076695639

[ntuple] Use bespoke log channel in RNTupleMerger (ROOT.NTuple.Merge)

---

config/rootssh

Use `chmod -f` to avoid potential error messages
Use unique prefixes for remote/local listener sockets names.
Fixes #18663

[webgui] improve rootssh [skip-ci]

---

core/foundation/inc/ROOT/RError.hxx

We now wrap fValue in a std::optional.

[core] Allow using RError with non-default-constructible types

---

interpreter/CMakeLists.txt

We don't want to "optimize `llvm_unreachable()` as undefined behavior" but trap if we hit this in production builds.
I think this would have found https://github.com/root-project/root/issues/18624 in CMSSW production environment.

[interpreter] Disable `LLVM_UNREACHABLE_OPTIMIZE`

---

tree/ntuple/inc/ROOT/REntry.hxx

Both `UpdateValue` and `GetValue` were originally added to be used by the `RNTupleProcessor`, but are not used there anymore. Since they are private methods and have no uses anywhere else in the code base, there's no reason to keep them around.

[ntuple] Remove unused private `REntry` methods

---

core/base/inc/Riostream.h

Including `chrono` first forces the private clock module to be imported before `fstream` transitively includes `filesystem`
Fixes the warning:
```
[79/2727] Generating G__Core.cxx, ../lib/Core.pcm
In module 'std' imported from input_line_1:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/__chrono/time_point.h:33:52: error: definition of '_FilesystemClock' must be imported from module 'std.std_private_chrono_file_clock' before it is required
template <class _Clock, class _Duration = typename _Clock::duration>
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/__chrono/time_point.h:33:1: note: in instantiation of default argument for …
```

[runtime_cxxmodules] Fix  '_FilesystemClock' build warning with macos 15.4 and mac-beta

---

README.md

In the direction of updating references to "PyROOT" to ROOT's Python Interface/Bindings

[skip-ci] Drop PyROOT from the README

---

roottest/root/io/json/.rootrc
roottest/root/io/json/CMakeLists.txt
roottest/root/io/json/LinkDef.h
roottest/root/io/json/runBasicTypes.C
roottest/root/io/json/runMap.C
roottest/root/io/json/runObjects.C
roottest/root/io/json/runPolyMarker.C
roottest/root/io/json/runRootClasses.C
roottest/root/io/json/runSTL.C
roottest/root/io/json/runSTL0.C
roottest/root/io/json/runSTL1.C
roottest/root/io/json/runStreamerLoop.C
roottest/root/io/json/runString.C
roottest/root/io/json/test_classes.h

1. Generate dictionary for custom tested classes
2. Load this library when running test macros
3. Avoid multiple cling workarounds
4. All ref files remains as is

[json] improve roottest/io/json testing

---

tree/dataframe/inc/ROOT/RDataSource.hxx
tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/inc/ROOT/RTTreeDS.hxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RDataSource.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/src/RTTreeDS.cxx
tree/dataframe/test/dataframe_definepersample.cxx

The information of each sample is populated at every new `GetEntryRanges` call. For the single thread case, every call corresponds to a new file. For the MT case, different ranges might be accessing the same file. Extra logic is needed to expose the storage location of the RNTuple of the current range, since this is not available directly from the RPageSource.
Fixes #15086

[df] Support DefinePerSample for RNTuple

---

documentation/doxygen/modifyNamespacesWebpage.sh

This pull request fixes this issue https://github.com/root-project/root/issues/18631
rf408_RDataFrameToRooFit.C was corrupted.
The script cleaning the faulty namespaces was not general enough.
This PR also remove tabs in that script.

[skip-ci] Fix the script filtering the wrong namespaces

---

tutorials/index.md

updates the index of tutorials' landing page, removing the experimental tutorial category

[skip-ci][tutorials] Remove Experimental category

---

roofit/roofitcore/inc/RooFit/Detail/MathFuncs.h

This makes the code more portable, and the `TMath` functions call the standard library functions internally anyway.
Also gives test coverage for https://github.com/vgvassilev/clad/issues/1289.

[RF] Use `std::erf` and `std::erfc` in RooFit math functions

---

tmva/tmva/src/MethodDNN.cxx

Add missing #include <chrono>
Fix many compilation errors like the following on Windows: tmva\tmva\src\MethodDNN.cxx(1186,44): error C2039: 'system_clock': is not a member of 'std::chrono' tmva\tmva\src\MethodDNN.cxx(1186,44): error C2065: 'system_clock': undeclared identifier tmva\tmva\src\MethodDNN.cxx(1187,42): error C2039: 'now': is not a member of 'std::chrono' tmva\tmva\src\MethodDNN.cxx(1187,42): error C3861: 'now': identifier not found

[v6-34][tmva] Fix compilation errors on Windows

---

core/base/inc/Riostream.h

Backport of: https://github.com/root-project/root/pull/18515

[macOS] Include <chrono> to fix `_FilesystemClock` build warning

---

roofit/hs3/CMakeLists.txt
roofit/xroofit/CMakeLists.txt

`LIBRARIES` is for external libraries.
Closes #18697.

[CMake][RF] Correctly declare dependencies in RooFitHS3 and xRooFit

---

core/clingutils/src/TClingUtils.cxx
core/foundation/inc/TClassEdit.h
core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx
core/meta/test/testTClass.cxx

Updates the name normalisation routines in order to properly take into accoung the C11 atomic type specifier `_Atomic`. In absence of this treatment, ill formed type names end up in the lexer of Clang, causing an infinite recursion.
- [v] updated the docs (if necessary)
This PR fixes #18643

[meta] Properly handle _Atomic type specifier

---

tmva/tmva/src/MethodDNN.cxx

Add missing #include <chrono>
Fix many compilation errors like the following on Windows: tmva\tmva\src\MethodDNN.cxx(1186,44): error C2039: 'system_clock': is not a member of 'std::chrono' tmva\tmva\src\MethodDNN.cxx(1186,44): error C2065: 'system_clock': undeclared identifier tmva\tmva\src\MethodDNN.cxx(1187,42): error C2039: 'now': is not a member of 'std::chrono' tmva\tmva\src\MethodDNN.cxx(1187,42): error C3861: 'now': identifier not found

[v6-32][tmva] Fix compilation errors on Windows

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx
core/meta/test/testTClass.cxx

When looking up a TClass via name vs via typeid, the lookup proceeded
without default template arguments in the former, and with default
arguments in the latter case.
This lead to a situation where
`tclass->GetActualClass(std::map<x,y>*)`
could delete itself while performing the lookup, since a new instance
was created that replaced the existing instance.
In the df014 tutorial, cppyy was essentially calling
```c++
auto first = TClass::GetClass("unordered_map<string,char>", true, true);
std::unordered_map<std::string,char> map;
auto second = first->GetActualClass(&map);
```
Before this PR, `first != second`, and `first` was being deleted while `first->GetActualClass` was still running.
Now, the class lookup in such a case is retried without the default STL arguments, which should lead to …

[core] Improve class name normalisation | fix crash in tutorial-analysis-dataframe-df014_CSVDataSource-py

---

math/genvector/inc/Math/GenVector/Cylindrical3D.h
math/genvector/inc/Math/GenVector/CylindricalEta3D.h
math/genvector/inc/Math/GenVector/EulerAngles.h
math/genvector/inc/Math/GenVector/Polar2D.h
math/genvector/inc/Math/GenVector/Polar3D.h
math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/GenVector/RotationX.h
math/genvector/inc/Math/GenVector/RotationY.h
math/genvector/inc/Math/GenVector/RotationZ.h
math/genvector/inc/Math/GenVector/RotationZYX.h
math/genvector/inc/Math/GenVector/VectorUtil.h
math/genvector/src/3DConversions.cxx
math/genvector/src/RotationZYX.cxx
math/genvector/src/VectorUtil.cxx

Replaces `M_PI*` occurences with `TMath` function calls, following discussion in https://github.com/root-project/root/pull/18462

[Math][GenVector] Replace `M_PI*` with `TMath` function calls

---

cmake/modules/RootMacros.cmake
roofit/jsoninterface/CMakeLists.txt

backport of https://github.com/root-project/root/pull/18696
Also mark explicitly the dependency of a dictionary source file and its pcm on the pcm of the libraries it depends on.
This fixes #18669.
#18669 was due to the missing dependency of `[G__]RooFitJSONInterface` on `Core`.
See more detail in #18669

[v636] build: Actually record dep from RooFitJSONInterface to Core.

---

math/mathcore/inc/TMath.h

I am sorry, I had fixed this bug in V2 of the pull request, but then we merged V1 and I forgot to 'backport' this modification.

[math] fix initialization bug in halfsamplemode algorithm

---

roottest/root/io/newstl/TestHelpers.C
roottest/root/io/newstl/test.C
roottest/root/tree/cloning/runtreeCloneTest2.C

Return value must be released.

[roottest] fix leak when using TSystem::ConcatFileName

---

math/genvector/inc/Math/GenVector/LorentzVector.h
math/genvector/test/testGenVector.cxx

Fixes https://root-forum.cern.ch/t/usage-of-deltar/63543
since TLorentzVector is a legacy class

[math] add DeltaR to GenVector

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/ClassWithNestedSameName.hxx
tree/dataframe/test/ClassWithNestedSameNameLinkDef.hxx
tree/dataframe/test/datasource_tree.cxx
tree/tree/inc/TTree.h
tree/tree/src/TTree.cxx

When the input `TTree` has a large dataset schema `O(10k)` and when the branch types are non trivial (i.e. many of the branches store some kind of nested data structure with possibly multiple levels of sub-branches representing the data members), retrieving the full list of available branches in the tree may become a costly operation. Anecdotally, a `TTree` used by an ATLAS analysis with >30k total leaves results in a retrieval time of around 2 minutes on my machine. With the changes in this PR, this time goes down **to around 6 seconds**. Main two contributors:
* a new transient map data member in `TTree`. When the `TTree` is being read, it already needs to traverse all its branch hierarchy. Take this opportunity to fill a map that connects the string with the full name of the leaf to …

Speedup retrieval of branch names

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx
core/imt/inc/ROOT/RTaskArena.hxx
core/imt/src/ROpaqueTaskArena.hxx
core/imt/src/RTaskArena.cxx
core/imt/src/TImplicitMT.cxx
core/imt/test/CMakeLists.txt
core/imt/test/testEnableImt.cxx

Instead of specificy the number of core, the new overload can be specified to select a configuration type.  Currently the following 2 configuration are supported:
ROOT::EIMTConfig::kWholeMachine
ROOT::EIMTConfig::kExistingTBBArena
calling
```
ROOT::EnableImplicitMT(ROOT::EIMTConfig::kExistingTBBArena);
```
will attach to an existing TBB Arena instead of creating a new one.
This fixes #18301

core: Add semantic ROOT::EnableImplicitMT

---

roofit/roofitcore/src/RooWorkspace.cxx

Fix a memory leak of the `TSystem::ConcatFileName()` return value in RooWorkspace, and also refactor the code to avoid repetition.
Thanks a lot to @ferdymercury for noticing this!
https://github.com/root-project/root/pull/18726#issuecomment-2880508421

[RF] Fix memory leak of ConcatFileName return value in RooWorkspace

---

core/foundation/src/TClassEdit.cxx

Fixes https://github.com/root-project/root/issues/18751
Please squash.
All credit goes to vepadulano and guitargeek
Alternatives to https://github.com/root-project/root/pull/18753 and https://github.com/root-project/root/pull/18756/
Of course, I could also make a version 4 which just does `lengths {5,5,8}` which is even more compact :) and this array did not change in 22 years, so...

[core] make static vars constexpr for thread safety v3

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx
core/imt/inc/ROOT/RTaskArena.hxx
core/imt/src/ROpaqueTaskArena.hxx
core/imt/src/RTaskArena.cxx
core/imt/src/TImplicitMT.cxx
core/imt/test/CMakeLists.txt
core/imt/test/testEnableImt.cxx

Instead of specificy the number of core, the new overload can be specified to select a configuration type.  Currently the following 2 configuration are supported:
ROOT::EIMTConfig::kWholeMachine
ROOT::EIMTConfig::kExistingTBBArena
calling
```
ROOT::EnableImplicitMT(ROOT::EIMTConfig::kExistingTBBArena);
```
will attach to an existing TBB Arena instead of creating a new one.
(cherry picked from commit eb0b90311b0d39ff1e93fd5804be1b63954ee08b)
This backports https://github.com/root-project/root/pull/18694
This fixes https://github.com/root-project/root/issues/18301

v634, core: Add semantic ROOT::EnableImplicitMT (#18694)

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx
core/imt/inc/ROOT/RTaskArena.hxx
core/imt/src/ROpaqueTaskArena.hxx
core/imt/src/RTaskArena.cxx
core/imt/src/TImplicitMT.cxx
core/imt/test/CMakeLists.txt
core/imt/test/testEnableImt.cxx

Instead of specificy the number of core, the new overload can be specified to select a configuration type.  Currently the following 2 configuration are supported:
ROOT::EIMTConfig::kWholeMachine
ROOT::EIMTConfig::kExistingTBBArena
calling
```
ROOT::EnableImplicitMT(ROOT::EIMTConfig::kExistingTBBArena);
```
will attach to an existing TBB Arena instead of creating a new one.
(cherry picked from commit eb0b90311b0d39ff1e93fd5804be1b63954ee08b)
This backports  #18694
This fixes #18301

v636, core: Add semantic ROOT::EnableImplicitMT

---

core/base/inc/TROOT.h
core/base/src/TROOT.cxx
core/imt/inc/ROOT/RTaskArena.hxx
core/imt/src/ROpaqueTaskArena.hxx
core/imt/src/RTaskArena.cxx
core/imt/src/TImplicitMT.cxx
core/imt/test/CMakeLists.txt
core/imt/test/testEnableImt.cxx

Instead of specificy the number of core, the new overload can be specified to select a configuration type.  Currently the following 2 configuration are supported:
ROOT::EIMTConfig::kWholeMachine
ROOT::EIMTConfig::kExistingTBBArena
calling
```
ROOT::EnableImplicitMT(ROOT::EIMTConfig::kExistingTBBArena);
```
will attach to an existing TBB Arena instead of creating a new one.
(cherry picked from commit eb0b90311b0d39ff1e93fd5804be1b63954ee08b)
This backports https://github.com/root-project/root/pull/18694
This fixes https://github.com/root-project/root/issues/18301

v632, core: Add semantic ROOT::EnableImplicitMT (#18694)

---

cmake/modules/RootConfiguration.cmake
config/RConfigure.in
core/metacling/test/TClingDataMemberInfoTests.cxx
main/src/g2root.f
tutorials/CMakeLists.txt

Building on top of the nice PR by dpiparo (https://github.com/root-project/root/pull/18639), I tried to add some more guards.
Fixes https://github.com/root-project/root/issues/18736

[build] Protections for disabled geom and davix

---

roofit/batchcompute/res/RooBatchCompute.h
roofit/batchcompute/src/Initialisation.cxx
roofit/roofitcore/inc/RooGlobalFunc.h
roofit/roofitcore/src/RooGlobalFunc.cxx

Change the default policy for selecting an optimized computation library from `"auto"` to `"generic"`. This ensures that results are reproducible across different hardware.
Also, add an easy-to-use interface to globally change the `BatchCompute` setting.
Closes #18738.

[RF] Disable loading architecture-specific RooBatchCompute by default

---

roottest/root/treeformula/array/execOutOfBounds.C
tree/treeplayer/src/TTreeFormula.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-7348
(And/or the dupe https://its.cern.ch/jira/browse/ROOT-7465)
This PR is a mere re-organisation of the commits here https://github.com/root-project/root/pull/18610 - all the work has been done by @ferdymercury (thanks for this contribution).

[tree] return NaN instead of zero when out of bonds in TreeFormula

---

roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/roofitcore/inc/RooFit/ModelConfig.h
roofit/roofitcore/src/ModelConfig.cxx
roofit/roostats/src/FeldmanCousins.cxx
roofit/roostats/src/HypoTestCalculatorGeneric.cxx

Creating the per-channel asimov dataset is only meaningful if we
actually create the files with the stored per-channel workspaces.
Otherwise, we just spend time calculating something that gets thrown
away anyway (for the combined workspace, we'll create a new Asimov).
This improves the performance for large workspace creation in TRexFitter
by about 20 %, which can be significant if the total runtime is in the
order of hours.
FYI @TomasDado, @superharz

[RF][HF] Avoid unnecessary creation of Asimov datasets

---

.github/workflows/root-ci-config/buildconfig/alma9.txt
.github/workflows/root-ci-config/buildconfig/ubuntu20.txt
.github/workflows/root-ci.yml
tutorials/CMakeLists.txt

AlmaLinux 9 is the main platform supported by ROOT, so if the 6.26 build can also succeed for this platform, it would be good to add it to the CI matrix. Like this we can be sure that there is still some way to build older ROOT releases.

[v626][ci] Also run on `alma9`

---

tree/ntuple/inc/ROOT/RField/RFieldFundamental.hxx
tree/ntuple/src/RColumnElement.hxx
tree/ntuple/test/ntuple_packing.cxx

See the commit message for more details.
This PR should be backported, probably even to 6.34 to make it work with the rntuple validation suite.

[ntuple] Cast min/max to the actual type when quantizing/unquantizing in Real32Quant

---

core/meta/src/TClass.cxx
roottest/root/meta/tclass/CMakeLists.txt
roottest/root/meta/tclass/InitOrder.h
roottest/root/meta/tclass/execInitOrder.cxx

This fixes #18556.
We should keep trying to try to load a `ClassInfo` until we try the auto-parsing.  `TClass::LoadClassInfo` should set `fCanLoadClassInfo` to `false` when the `ClassInfo` is found *and* set it to false also when we tried auto parsing but did not find the `ClassInfo`.
In the later case, the `ClassInfo` might still be loaded (via a different routine/mechanims) if information about the class is later loaded/parsed.

[meta] Correct TClass::LoadClassInfo.

---

io/io/src/TDirectoryFile.cxx
io/io/src/TFile.cxx

Fixes https://root-forum.cern.ch/t/file-size-with-a-clonetree/27648/12
And avoid duplicated out-of-sync docu

[skip-ci][io] clarify behavior of Delete

---

.github/workflows/root-ci-config/buildconfig/alma9.txt

Set `dataframe=ON` for the build on AlmaLinux 9.

[v626][ci] Enable `dataframe` on alma9

---

core/meta/src/TClass.cxx

This fixes #18556.
We should keep trying to try to load a ClassInfo until we try the auto-parsing. TClass::LoadClassInfo should set fCanLoadClassInfo to false when the ClassInfo is found *and* set it to false also when we tried auto parsing but did not find the ClassInfo.
In the later case, the ClassInfo might still be loaded if information about the class is later loaded/parsed.
Backport of https://github.com/root-project/root/pull/18587

[v634][meta] Correct TClass::LoadClassInfo.

---

core/meta/src/TClass.cxx

This fixes #18556.
We should keep trying to try to load a ClassInfo until we try the auto-parsing. TClass::LoadClassInfo should set fCanLoadClassInfo to false when the ClassInfo is found *and* set it to false also when we tried auto parsing but did not find the ClassInfo.
In the later case, the ClassInfo might still be loaded if information about the class is later loaded/parsed.
Backport of https://github.com/root-project/root/pull/18587

[v636] [meta] Correct TClass::LoadClassInfo.

---

tree/ntuple/inc/ROOT/RNTupleJoinTable.hxx

On 32-bit platforms or platforms where `std::size_t` is 32-bit instead of 64-bit, the current `mix` function doesn't work. The alternative added with this change also originates from the [`boost::hash_combine` writeup](https://www.boost.org/doc/libs/1_87_0/libs/container_hash/doc/html/hash.html#notes_hash_combine) linked in the `RCombinedJoinFieldValueHash` class documentation.

[ntuple] Adapt hashing to 32-bit

---

roofit/roofitcore/inc/RooFit/ModelConfig.h

This follows up on commit f15e44c26cb3, which missed to get the `RooArgSet` from the `RooDataSet` in the backwards-compatibility overload of `ModelConfig::GuessObsAndNuisance`.
Thanks to @hahnjo for noticing this!

[RF] Avoid infinite recursion in `ModelConfig::GuessObsAndNuisance`

---

tree/ntuple/doc/Architecture.md
tree/ntuple/inc/ROOT/RFieldBase.hxx
tree/ntuple/inc/ROOT/RNTupleModel.hxx
tree/ntuple/inc/ROOT/RNTupleView.hxx
tree/ntuple/src/RFieldBase.cxx
tree/ntuple/src/RNTupleModel.cxx
tree/ntuple/test/ntuple_bulk.cxx
tree/ntuple/test/ntuple_multi_column.cxx

This better represents what the class is actually responsible for (i.e., managing the values that are read as a result of a bulk read).

[ntuple] Rename `RBulk` to `RBulkValues`

---

.clang-format

Avoid failures when formatting C++ string literals as shown in #18785

[clang-format] change standard to c++17 [skip-ci]

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx

Since the removal of the corresponding factory function in https://github.com/root-project/root/commit/a85fc79a51cc9415397cad40c3e068d7831ff889, this constructor is not necessary anymore. Remove it for good measure.

[df] Remove unused constructor in RNTupleDS

---

tutorials/CMakeLists.txt

Some PROOF tutorial doesn't work on AlmaLinux 10, so veto it for the el10 Linux flavor. PROOF is deprecated in later ROOT versions, hence this failure is not worth debugging at this point.
Follows up on the addition of Alma 10 to the CI

[v630][ci] Follow up on adding AlmaLinux 10

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx
tree/dataframe/src/RNTupleDS.cxx

Since the removal of the corresponding factory function in https://github.com/root-project/root/commit/a85fc79a51cc9415397cad40c3e068d7831ff889, this constructor is not necessary anymore. Remove it for good measure.

[6.36] [df] Remove unused constructor in RNTupleDS

---

interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
interpreter/cling/lib/Interpreter/LookupHelper.cpp

LockCompilationDuringUserCodeExecutionRAII: to be used right before compiling/executing user code
InterpreterAccessRAII: to be used during loookups

cling: Deduplicate lock code. Keep semantic distinction.

---

cmake/modules/RootMacros.cmake

This reverts commit 5cb988860f06ea39e51327386aa4bf6b950c46c4.
It has side effects when building the tests

Revert "[cmake] Add rootcling dependencies for Windows"

---

roofit/roofit/test/CMakeLists.txt

Fixes the following errors:
```
roofitstats\stabilityTests.cxx(13,10): error C1083: Cannot open include file: 'gtest/gtest.h': No such file or directory
LINK : error LNK2001: unresolved external symbol _tls_index/EXPORT:_Init_thread_abort
roofit/roofit/test/Release/stabilityTests.lib : fatal error LNK1120: 1 unresolved externals`
```

[v6-36][test][win] Fix compiler error with stabilityTests on Windows

---

tree/dataframe/test/dataframe_friends.cxx

Another instance of the bug as seen in
https://github.com/root-project/root/commit/5f56b95832d0f31d0d85dc0a6cc93aa9cb375159 https://github.com/root-project/root/commit/de63ccc901cc114e40a84169917a5c0baccabee9
This time seen in CI failures on Alma8.
For example see https://github.com/root-project/root/actions/runs/15130519341/job/42530481374#step:11:5400

[df] Another workaround for attempt to delete stack memory

---

core/base/src/TROOT.cxx
core/cont/src/TClassTable.cxx
core/meta/src/TClass.cxx
core/meta/src/TEnum.cxx
core/meta/src/TProtoClass.cxx
core/metacling/src/TCling.cxx

The code within GetEnum change the autoparsing state (inside `searchEnum\') and thus needs to have the Write lock (instead of just the read lock)
Fixes https://github.com/root-project/root/issues/18792

[meta] Correct thread behavior in TEnum::GetEnum.

---

interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
interpreter/cling/lib/Interpreter/LookupHelper.cpp

Backport of https://github.com/root-project/root/pull/18237 and and https://github.com/root-project/root/pull/18551
This fixes #18236
As seen in cms-sw/cmssw#47763 (comment)
there are cases where the ROOT global lock is taken too late:
In the stack trace below the lock is requested on frame #7 where as
it should really be (also) requested on frame #12 as soon as the
transaction is being generated.
```
#6  0x00001501421f55ea in ROOT::TVirtualRWMutex::Lock() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02883/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_15_1_RNTUPLE_X_2025-03-31-2300/external/el8_amd64_gcc12/lib/libCore.so
#7  0x0000150133a680ca in TCling::HandleNewTransaction(cling::Transaction const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02883/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_15_1_R …
```

[v634] [cling] Add ROOT lock to LookupHelper::findType

---

interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
interpreter/cling/lib/Interpreter/LookupHelper.cpp

LockCompilationDuringUserCodeExecutionRAII: to be used right before compiling/executing user code InterpreterAccessRAII: to be used during loookups
(cherry picked from commit 9dd3b80c3e747445234e82d332aee3507bf6c1e3)
BP of https://github.com/root-project/root/pull/18551

[636] cling: Deduplicate lock code. Keep semantic distinction.

---

roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx

default initialise a variable to avoid warnings in the test which cause it to fail on many Linux flavours.
```
roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx: In function ‘bool CheckNestedCollectionStreamerInfo(bool)’:
Warning: roottest/root/io/TFile/execNestedCollectionStreamerInfo.cxx:28:14: warning: ‘in.Inside::fValue’ may be used uninitialized [-Wmaybe-uninitialized]
28 |       Inside in;
|              ^~
```
@martamaja10 as shifter

🚨  [test] Remove compilation warning during ACLiC

---

tree/dataframe/test/dataframe_friends.cxx

Since title of test and called function do not match. It seems a copy-paste typo from the function just above?

[RDF] fix typo in called test function

---

core/clingutils/src/TClingUtils.cxx
interpreter/cling/include/cling/Interpreter/InterpreterAccessRAII.h
interpreter/cling/lib/Interpreter/EnterUserCodeRAII.h
interpreter/cling/lib/Interpreter/LookupHelper.cpp

Backport of #18522, #18237 and #18551

[v632] [cling] The LookupHelper routines need the ROOT lock.

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/uhi_indexing.py
hist/hist/inc/TH1.h

Previously, slicing was implemented at the pythonization level: when slicing a histogram, the values within the specified slice were kept and the ones outside were set to 0, without resizing the sliced axis (leading to inconsistencies..).
This PR implements the slicing logic in `TH1` directly, adapting the pythonizations to make use of the new internal functions.
Other changes are made to enhance the interface and fully comply with the UHI specifications, improvements can be summarized here:
- The sliced axis is resized after slicing, which correctly adjusts the statistics.
- Integration operations now support full-range integration, non-flow integration, and ranged integration.
- Histograms can now be set with either a scalar, numpy.ndarray, or any ArrayLike instance.
- Broadcasting is …

[python][UHI] Implement Slicing in TH1 and adapt the UHI backend and tests

---

README/ReleaseNotes/v636/index.md

Forward port of https://github.com/root-project/root/commit/15b760377c79a8d8baa04d5a6a44f37283fcd2cb which was present only in v6-36-00-patches branch

[skip-ci][ReleaseNotes] Updates for 6.36

---

.github/workflows/root-ci-config/build_root.py
.github/workflows/root-ci-config/build_utils.py
.github/workflows/test-coverage.yml
roottest/cling/functionTemplate/testcint.py
roottest/root/aclic/load/CMakeLists.txt
roottest/root/meta/tclass/CMakeLists.txt

We 'could' enable the test coverage for all pull (master) request but ... it takes 2 or 3 hours to run the tests.
So we introduce a label 'test coverage' to enable it explicitly for a PR.
Once the nightly runs, we will see the result at https://app.codecov.io/github/root-project/root/tree/master.
From there we can see the results obtained for running at part of this PR and we get 33.74% so far ...

[ci] Testing code coverage workflow 

---

.github/workflows/test-coverage.yml

Fixes https://github.com/root-project/root/actions/runs/15213020746/job/42791613768
```
Run .github/workflows/root-ci-config/build_root.py --binaries       true --buildtype      Debug --platform       alma9 --incremental    {{ inputs.incremental }} --coverage       true --base_ref       master --sha            5dbc9611e1efb03eb7de96ee4ee47d0ef833bef3 --head_ref       master --head_sha       master --repository     https://github.com/root-project/root 
##[debug]sh -e /__w/_temp/2073e9ca-7a31-45ba-b0f3-9532d3a901a2.sh
Using wrapper for podman, see `less $(which docker)` for details
Using wrapper for podman, see `less $(which docker)` for details
usage: build_root.py [-h] [--platform PLATFORM] [--dockeropts DOCKEROPTS]
[--incremental INCREMENTAL] [--buildtype BUILDTYPE]
[--coverage COVERAGE] …
```

[skip-ci][coverage] Fix typo in workflow command

---

core/base/src/TExec.cxx
core/base/src/TPRegexp.cxx
geom/geom/doc/materials.md
geom/geom/src/TGeoManager.cxx
graf2d/gpad/src/TButton.cxx
graf3d/gl/src/TGLHistPainter.cxx
graf3d/gl/src/TGLParametric.cxx
hist/hist/src/TGraph2DAsymmErrors.cxx
hist/hist/src/TGraphSmooth.cxx
hist/hist/src/TGraphTime.cxx
hist/histpainter/src/TGraphPainter.cxx
hist/histpainter/src/THistPainter.cxx
main/python/cmdLineUtils.py
math/mathcore/src/TKDTreeBinning.cxx
math/minuit/src/TMinuit.cxx
math/physics/src/TFeldmanCousins.cxx
montecarlo/pythia8/src/TPythia8.cxx
tree/tree/src/TTree.cxx
tutorials/evegen/evegen_000_pythia8.C
tutorials/io/tree/tree502_staff.C

- doxygen automatically makes reference links to tutorials when then are simply named `tutorial.C`. In several  places some tutorials were mentioned as `$ROOTSYS/tutorials/path_to_the_tutorial/tutorial.C`. This prevented doxygen to automatically make the link to the `tutorial.C`. This PR simplify  `$ROOTSYS/tutorials/path_to_the_tutorial/tutorial.C` to `tutorial.C` to allow doxygen to make the link.
- remove `\macro_image` from`tree502_staff.C` because the macro does not generate any image when run in batch.
- in Pythia8.cxx: remove the reference to `pythia8.C` which does not exist and change it to evegen_000_pythia8.C.

[skip-ci] Some small improvements in the doc

---

bindings/pyroot/cppyy/cppyy/test/CMakeLists.txt

These leakcheck tests, similar to the regression test for https://github.com/root-project/root/issues/15703 that was dropped, tend to sporadically fail and should be disabled

[cppyy] Fix incremental builds with rootcling, disable leakcheck tests

---

bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
bindings/pyroot/cppyy/cppyy/test/test_numba.py

The numba extension does not necessarily always outperform a pure python hotloop and can lead to sporadic failures in tests that compare execution times. This patch continues running these tests, while expecting failures so the CI is no longer fragile.

[cppyy] expect failures in numba tests, disable chrono test

---

bindings/pyroot/cppyy/cppyy/test/CMakeLists.txt
bindings/pyroot/cppyy/cppyy/test/test_aclassloader.py
bindings/pyroot/cppyy/cppyy/test/test_advancedcpp.py
bindings/pyroot/cppyy/cppyy/test/test_conversions.py
bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py
bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py
bindings/pyroot/cppyy/cppyy/test/test_datatypes.py
bindings/pyroot/cppyy/cppyy/test/test_doc_features.py
bindings/pyroot/cppyy/cppyy/test/test_fragile.py
bindings/pyroot/cppyy/cppyy/test/test_lowlevel.py
bindings/pyroot/cppyy/cppyy/test/test_operators.py
bindings/pyroot/cppyy/cppyy/test/test_overloads.py
bindings/pyroot/cppyy/cppyy/test/test_pythonify.py
bindings/pyroot/cppyy/cppyy/test/test_pythonization.py
bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
bindings/pyroot/cppyy/cppyy/test/test_streams.py
bindings/pyroot/cppyy/cppyy/test/test_templates.py

This fixes build errors with `builtin_clang=OFF` that appeared after https://github.com/root-project/root/pull/18671.

[cppyy] Use ROOT dictionary generation macro in cppyy tests

---

roofit/roofitcore/inc/RooEllipse.h
roofit/roofitcore/src/RooEllipse.cxx
roofit/roofitcore/src/RooFitResult.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-8730 by @wiso

[RF] bivariate ellipse confidence contour is not at 1-sigma confidence level

---

bindings/pyroot/cppyy/cppyy/test/test_templates.py

This test leads to the following interpreter error when parsing the `AttrTesting` class defined in `libtemplatesDict.so`
```
input_line_25:7:55: error: address of overloaded function 'has_var1' is ambiguous
new (ret) (bool) (((bool (&)(AttrTesting::Obj1))AttrTesting::has_var1<AttrTesting::Obj1>)(*(AttrTesting::Obj1*)args[0]));
^
input_line_21:9:16: note: candidate function [with T = AttrTesting::Obj1]
constexpr auto has_var1(T t) -> decltype(t.var1, true)
^
input_line_21:15:16: note: candidate function [with Args = <AttrTesting::Obj1>]
constexpr bool has_var1(Args...)
^
input_line_25:11:44: error: address of overloaded function 'has_var1' is ambiguous
(void)(((bool (&)(AttrTesting::Obj1))AttrTesting::has_var1<AttrTesting::Obj1>)(*(AttrTesting::Obj1*)args[0]));
^
input_line_21:9:16: note: …
```

[cppyy] disable error prone `test06_variadic_sfinae`

---

tree/dataframe/test/CMakeLists.txt

Fix runtime failures (seen on Debian notes):
```
<<< cling interactive line includer >>>: fatal error: module file '/github/home/ROOT-CI/build/lib/RIO.pcm' is out of date and needs to be rebuilt: module file out of date
it means to be say
```
but this is a lie, it is meant to say:
```
<<< cling interactive line includer >>>: fatal error: module file '/github/home/ROOT-CI/build/tree/dataframe/test/datasource_tree.pcm' is out of date and needs to be rebuilt: module file out of date as it depends on the new file '/github/home/ROOT-CI/build/lib/RIO.pcm'
```

[df] Add missing dict dependency for datasource_tree

---

roottest/root/tree/cloning/CMakeLists.txt
roottest/root/tree/cloning/generate-eventfile.sh
test/MainEvent.cxx

Remove unused variables and code branches.
Updated version of the following `roottest` PR:
* https://github.com/root-project/roottest/pull/669

[roottest] Fixes to tree/cloning/CMakeLists.txt

---

.github/workflows/root-ci.yml

AlmaLinux 10 is now released, so the builds should not be marked as
special anymore.

[ci] Make alma10 regular build

---

.github/workflows/root-ci.yml

This should resolve the new test failues on `alma9 march_native` and `alma9 arm64` that showed up the the transition from AlmaLinux 9.5 to AlmaLinux 9.6.

[v636][ci] Use builtin compression libraries for special alma9 builds

---

.github/workflows/root-ci.yml

AlmaLinux 10 is now released, so the builds should not be marked as special anymore.

[v632][ci] Make alma10 regular build

---

tree/ntuple/src/RMiniFile.cxx

Do:
(read into unzipBuf) -> (unzip into finalBuf)
instead of:
(read into finalBuf) -> (unzip into unzipBuf) -> (copy back to finalBuf)

[ntuple] Save a memcpy when reading a compressed Anchor in RMiniFile

---

bindings/jupyroot/python/JupyROOT/helpers/handlers.py
bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_application.py
bindings/pyroot/pythonizations/python/ROOT/_facade.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_generic.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_namespace.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tclass.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tobject.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_ttree.py

Closes https://github.com/root-project/root/issues/14917.

[PyROOT] Move CPython extensions in subdirectories

---

geom/test/test_boolean_extrusion.cxx
geom/webviewer/inc/ROOT/RGeoPainter.hxx
geom/webviewer/src/RGeoPainter.cxx

TGeoChecker can be used only with `--web=off` mode. To avoid confusion print warning that checker methods not implemented. Later checker can be moved into separate library and used intepdendent from GL painters

[webgeom] provide warnings that checker not implemented #18881

---

.github/actions/issues-nudge.js

See current status of https://github.com/root-project/root/issues/?q=is%3Aissue%20is%3Aclosed%20no%3Aproject%20reason%3Acompleted
I get daily emails about adding a "Project" to closed issues (which I have no rights to close). It's probably unnecessary to force won't fix issues to have a project called "Fixed in not applicable".
So reduce the number of emails by only complaining about completed issues.
An alternative would be to make the JS query add the project automatically instead of relying on the user.
Another alternative would be to collect all issues in the same single email and centralize that task into a single person, rather than having N emails for all non-completed issues.

[skip-ci] do not nudge on issues closed as not planned

---

core/metacling/src/TCling.cxx

The return value has its own storage and can be used without a lock.
See #18863 for reproducer (in particular https://github.com/root-project/root/issues/18863#issuecomment-2927500035)
Fixes #18863

[metacling] Add missing lock to TCling::Evaluate.

---

core/clingutils/src/TClingUtils.cxx
core/clingutils/test/TClingUtilsTests.cxx

This PR fixes #18811
All the credit for this solution goes to @hahnjo .

[meta] Remove redundant check when resubstituting template arguments

---

core/metacling/src/TCling.cxx

BP of https://github.com/root-project/root/pull/18938
The return value has its own storage and can be used without a lock.
(cherry picked from commit https://github.com/root-project/root/commit/3ecb1d14febe9fb23d3d034e50fae411cada6191)

[634][metacling] Add missing lock to TCling::Evaluate. 

---

README/ReleaseNotes/v636/index.md
io/io/inc/TFileMerger.h
io/io/src/TFileMerger.cxx
main/src/hadd.cxx

BP of https://github.com/root-project/root/pull/18800

[6.36][io] TFileMerger: fail by default on invalid keys

---

core/metacling/src/TCling.cxx

BP of https://github.com/root-project/root/pull/18938
The return value has its own storage and can be used without a lock.
(cherry picked from commit https://github.com/root-project/root/commit/3ecb1d14febe9fb23d3d034e50fae411cada6191)

[632][metacling] Add missing lock to TCling::Evaluate.

---

core/foundation/src/TClassEdit.cxx
core/foundation/test/testClassEdit.cxx
roottest/root/meta/rootcling/CMakeLists.txt
roottest/root/meta/rootcling/streamerInfoStdFunction.C
roottest/root/meta/rootcling/streamerInfoStdFunction.h
roottest/root/meta/rootcling/streamerInfoStdFunction.xml

This commit fixes #18833, by reverting 0f8670. 
It also honours #18842, without breaking DD4HEP.
Moreover it adds back a test and enhances it.

[meta] Correctly treat data member types containing functions

---

hist/hist/src/TGraph.cxx

According to the standard, comparison functions require `comp(a, a) == false` for all `a`:
https://en.cppreference.com/w/cpp/named_req/Compare
The `TGraph::Sort()` method is implemented with `std::stable_sort`, which requires such a comparator. However, it's also possible to flip the comparator with the `ascending` flag, meaning it's very eary to end up in a situation where the comparison is not strict anymore. To avoid this, it's better to shortcut the comparison with an additional `a != b` check.
Superseeds:
* https://github.com/root-project/root/pull/17211

[hist] Ensure strict comparison in `std::stable_sort`

---

tree/ntuple/inc/ROOT/RNTupleProcessor.hxx
tree/ntuple/src/RNTupleProcessor.cxx
tree/ntuple/test/ntuple_processor.cxx
tree/ntuple/test/ntuple_processor_chain.cxx
tree/ntuple/test/ntuple_processor_join.cxx

`PrintStructure` graphically shows how different RNTuples are composed, which can be useful for, among others, debugging purposes.
For example, a processor representing a join between a single primary ntuple and a chain of two auxiliary ntuples will be represented as follows:
```
+-----------------------------+ +-----------------------------+
| ntuple                      | | ntuple_aux                  |
| ntuple.root                 | | ntuple_aux1.root            |
+-----------------------------+ +-----------------------------+
+-----------------------------+
| ntuple_aux                  |
| ntuple_aux2.root            |
+-----------------------------+
```
More example outputs can be found in the unit tests.

[ntuple] Add `RNTupleProcessor::PrintStructure`

---

io/io/src/TZIPFile.cxx

`TZIPFile::DecodeZip64ExtendedExtraField` is incorrectly assuming that the Usize and Csize extra fields are always required to be there if the extra Offset field is to be parsed; in reality the fields are all optional, therefore an extra field with size 8 may only contain the offset field (this is indicated by the value 0xffffffff in the non-extended Csize, Usize and offset).
Concretely this means that ROOT cannot parse ZIP files that contain entries with offset > 4GB but size < 4GB (as seen for example in #18953).
This PR fixes #18953

[io] Fix ZIP64 extra entry field parsing in TZIPFile

---

builtins/cfitsio/CMakeLists.txt

and not NASA's as all other packages.
(cherry picked from commit 2ae01b55e8c0f79cced60077f86509c0cae33109)

[634][cmake] Use cfitsio sources from the lcg website

---

io/io/src/TZIPFile.cxx

The TZIPFile code was incorrectly assuming that the Usize and Csize extra fields were always required to be there if the extra Offset field was to be parsed; in reality the fields are all optional, therefore an extra field with size 8 may only contain the offset field (this is indicated by the value 0xffffffff in the non-extended Csize, Usize and offset).
Concretely this means that ROOT could not parse ZIP files that contain entries with offset > 4GB but size < 4GB (as seen for example in #18953).
(cherry picked from commit a435cf3a2824d96a2ff70b2281e616771dcccc38)
BP of https://github.com/root-project/root/pull/18958

[636][io] Fix ZIP64 extra entry field parsing in TZIPFile

---

io/io/src/TZIPFile.cxx

The TZIPFile code was incorrectly assuming that the Usize and Csize extra fields were always required to be there if the extra Offset field was to be parsed; in reality the fields are all optional, therefore an extra field with size 8 may only contain the offset field (this is indicated by the value 0xffffffff in the non-extended Csize, Usize and offset).
Concretely this means that ROOT could not parse ZIP files that contain entries with offset > 4GB but size < 4GB (as seen for example in #18953).
(cherry picked from commit a435cf3a2824d96a2ff70b2281e616771dcccc38)
BP of https://github.com/root-project/root/pull/18958

[632][io] Fix ZIP64 extra entry field parsing in TZIPFile

---

bindings/pyroot/pythonizations/CMakeLists.txt

Absolute install paths can't be used for CMake targets on Windows of macOS. Commit 9bb2f50 changed the install paths of the pythonization library to be absolute paths, so that it's simple to calculate the relative paths. But this broke the installation step on Windows and macOS, and therefore has to be reverted. For the `rpath` step, the full path is obtained with `CMAKE_INSTALL_PREFIX`, and it was checked that the rpaths are still correctly computed, similar to https://github.com/root-project/root/pull/18969#discussion_r2128987289
```txt
[nix-shell:~/code/root]$ readelf -d root_build/lib/ROOT/libROOTPythonizations.so | grep RUNPATH
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../:/home/rembserj/code/root/root_build/lib::/nix/store/0896fyzn4l1gczab8qmlsliipq0js31x-nix- …
```

[Python] Use relative install path for pythonization library

---

bindings/pyroot/pythonizations/test/import_load_libs.py

Fixes the ruff format error in this PR: https://github.com/root-project/root/pull/17209

[NFC] Apply ruff-format to import_load_lib pythonization test

---

CMakeLists.txt

Fixes the ninja cyclic dependency issue reported in https://github.com/root-project/root/issues/18998 due to special character `+` in the `CMAKE_SOURCE_DIR`. Instead of using `list(TRANSFORM ...)` (which uses regexp) to replace `CMAKE_SOURCE_DIR` with `CMAKE_BINARY_DIR` this PR suggests to use [string(REPLACE )](https://cmake.org/cmake/help/latest/command/string.html#replace) which does a string substitution 
ninja, build system, cyclic dependency issue
This PR fixes #18998

Fix for CMAKE_SOURCE_DIR with special characters `. and +`

---

interpreter/CppInterOp/unittests/CppInterOp/VariableReflectionTest.cpp

Offsets should use size_t. Using int causes test failures on Big Endian (s390x).
```
[ RUN      ] VariableReflectionTest.StaticConstExprDatamember
/builddir/build/BUILD/root-6.36.00/interpreter/CppInterOp/unittests/CppInterOp/VariableReflectionTest.cpp:545: Failure
Expected equality of these values:
3
*(int*)offset
Which is: 0
/builddir/build/BUILD/root-6.36.00/interpreter/CppInterOp/unittests/CppInterOp/VariableReflectionTest.cpp:561: Failure
Expected equality of these values:
5
*(int*)offset
Which is: 0
/builddir/build/BUILD/root-6.36.00/interpreter/CppInterOp/unittests/CppInterOp/VariableReflectionTest.cpp:580: Failure
Expected equality of these values:
2
*(int*)offset
Which is: 0
[  FAILED  ] VariableReflectionTest.StaticConstExprDatamember (9 ms)
```

Use size_t for offset

---

.ci/format_script.sh
.github/workflows/code_analysis.yml

Related github discussion: https://github.com/orgs/community/discussions/59677
For a given PR, the value of `github.event.pull_request.base.sha` always corresponds to the SHA of the head/tip of the base branch at the moment of either creation of the PR or the last force-push (regardless of whether that force-push actually rebased the PR branch against base or was just modifying an existing commit in it) to the PR branch.
In addition the merge commit is updated whenever a new commit is push onto the PR branch but this merge commit is not against the (fixed) `github.event.pull_request.base.sha` but is instead against the (moving) tip of the target branch.
Currently (before this commit), our clang-format action will check the differences between that commit and the merge commit.
In practice …

[ci] Restrict clang-format to PR changes

---

tree/ntuple/inc/ROOT/RNTupleUtil.hxx
tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/test/ntuple_merger.cxx

With this change, we explicitly refuse to merge any 2 untyped records that don't have compatible subfields (in the proper order). This was de facto already the case before this change, but instead of failing with an error the merger would simply assert.

[ntuple] Merger: properly handle untyped records

---

roottest/cmake/modules/RoottestMacros.cmake
roottest/python/JupyROOT/CMakeLists.txt

Follows up on #5938, adding support for the `PYTHON_DEPS` argument also to the `ROOTTEST_ADD_TEST` macro.
Use this functionality to disable JupyROOT tests if the relevant libraries are not available.

[roottest] Use `PYTHON_DEPS` argument also in Roottest macro

---

bindings/pyroot/pythonizations/test/tdirectory_attrsyntax.py
bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py
roottest/python/memory/PyROOT_memorytests.py

There are several unit tests that assert if different variables actually
point to the same histogram object, using the `==` operator.
Until now, this was correct by accident, because the default equality
check for TObject-derived classes in PyROOT is to call
`TObject::IsEqual()`, which does checks the pointer identity (if not
overridden is not implemented). See:
https://github.com/root-project/root/blob/master/bindings/pyroot/pythonizations/src/TObjectPyz.cxx#L49
Since PR https://github.com/root-project/root/pull/17950 (introduction of UHI interface), an equality operator is
implemented for histograms on the Python side. Therefore, we really need
to correctly use Pythons `is` function to explicitly check for identity
(meaning both variables point to the same object).

[Python] Check for identity and not equality where appropriate

---

roottest/cmake/modules/RoottestMacros.cmake

On Windows `ROOTTEST_COMPILE_MACRO` creates number of files in source directory. 
Copy necessary to build directory and then remove all files from source dir

[roottest] remove files from source dir after macro compilation [win]

---

math/minuit2/StandAlone.cmake

[v636][Minuit2] Correctly copy ROOT's `std::span` headers for standalone build

---

tree/dataframe/test/dataframe_interface.cxx

Fixes a race condition observed in the nightlies.

[RDF] Change a filename in a test to prevent a race condition.

---

roottest/python/basic/CMakeLists.txt
roottest/python/basic/PyROOT_datatypetest.py
roottest/python/basic/PyROOT_datatypetest_numpy.py

Disable tests that require NumPy if NumPy is not available by factorizing the relevant tests out into a separate tests, where the NumPy dependency is correctly registered.
This helps when testing ROOT with newer Python versions where NumPy is not readily available yet.

[roottest] Disable tests that require NumPy if NumPy is not available

---

README/ReleaseNotes/v638/index.md
core/dictgen/src/BaseSelectionRule.cxx
interpreter/cling/lib/Interpreter/LookupHelper.cpp
roottest/root/meta/rootcling/CMakeLists.txt
roottest/root/meta/rootcling/selectTemplateInvalidArg.LinkDef.h
roottest/root/meta/rootcling/selectTemplateInvalidArg.h
roottest/root/meta/rootcling/selectTemplateInvalidArg.ref

for example, when they are only forward declared.
Side effect: less lookups are carried out during the selection, therefore less memory and runtime is used for dictionary generation.
Fixes #18982

[core] Do not select template instances if their template arguments are invalid decls in the AST

---

CMakeLists.txt
bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/python/ROOT/__init__.py

The JsMVA package is undocumented, [untested](https://github.com/root-project/root/blob/master/roottest/python/JsMVA/CMakeLists.txt), and lagging behind in terms
of the [JsROOT version that it uses](https://github.com/root-project/root/issues/12441).
At this point, there is no clear reason for including it in the ROOT
builds, so this commit suggests to remove it from the build and install
tree temporarily, until we are sure that it works (also with the newest
JsROOT version).
Alternative to #12484.
Closes #12441.

[Python] Don't include JsMVA in builds

---

README/ReleaseNotes/v638/index.md
roofit/roofit/CMakeLists.txt
roofit/roofit/inc/LinkDef1.h
roofit/roofit/inc/RooGaussExpTails.h
roofit/roofit/src/RooGaussExpTails.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-8093
It's a simpler alternative to RooCrystalBall with potentially less instabilities

[RF] New PDF: gaussian with double sided exponential tails

---

tutorials/visualisation/gl/glViewerExercise.C
tutorials/visualisation/gl/viewer3DLocal.C
tutorials/visualisation/gl/viewer3DMaster.C

If run in web mode canvas not automatically created and therefore `gPad` can be `nullptr`. 
Add simple check to avoid crash.
Disable web mode for viewer3DLocal.C and viewer3DMaster.C while features with TBuffer3D not supported by web graphics yet.
Fixes https://github.com/root-project/root/issues/19045

[tutorials] check gPad in gl tutorials

---

core/foundation/inc/ROOT/StringUtils.hxx
core/foundation/src/StringUtils.cxx
core/foundation/test/testStringUtils.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-11017
Pinging @linev and @couet since they might be interested in (re-)using this function for cleaning up a bit the StatsPanel of the GUI when drawing histograms.

[core] Utility to round number and error in sync with 1 or 2 digits

---

graf3d/eve7/src/REveGeoTopNode.cxx

String size has different type on windows.

[reve] fix windows compiler warning

---

core/metacling/src/CMakeLists.txt

Fix the following compiler error:
```
msvcprt.lib(vector_algorithms.obj) : error LNK2005: __std_find_trivial_1 already defined in libCling.lib(libCling.dll)
```
when compiling `roottest-root-io-datamodelevolution`

[v6-36][cmake][win][skip-ci] fix duplicate symbol error

---

core/metacling/src/CMakeLists.txt

This reverts commit 8a7d481b02afa3f3b05b56e21c10424f65849847.

Revert "[camke][win][skip-ci] fix duplicate symbol error"

---

tree/ntuple/inc/ROOT/RMiniFile.hxx
tree/ntuple/src/RMiniFile.cxx

refactors a bit `RMIniFile::GetNTupleProper` adding a `GetNTupleProperAtLocation` subroutine to load the anchor once its location in the file is known. This will be useful for the RNTuple Attributes prototype as it will need to load the Attributes' anchor from the same file from a known location.

[ntuple] Add RMiniFile::GetNTupleProperAtOffset

---

core/foundation/inc/ROOT/StringUtils.hxx

Required for std::next.
mac-beta seems to fail on the CI without it.

[core] Add #include <iterator> to StringUtils.hxx

---

math/vecops/inc/ROOT/RVec.hxx

This should fix the error:
```
2025-06-17T14:18:21.1084400Z [ 53%] Built target StreamerFieldXMLDict
2025-06-17T14:18:21.1339530Z [ 53%] Generating G__ROOTVecOps.cxx, ../../lib/ROOTVecOps.pcm
2025-06-17T14:18:21.4156690Z In file included from input_line_10:3:
2025-06-17T14:18:21.4163110Z build/include/ROOT/RVec.hxx:345:36: error: no member named 'make_move_iterator' in namespace 'std'
2025-06-17T14:18:21.4286310Z       std::uninitialized_copy(std::make_move_iterator(I), std::make_move_iterator(E), Dest);
```
on mac-beta

[math] Add missing includes for std::iterator

---

.github/workflows/root-ci-config/buildconfig/mac-beta.txt
math/mathcore/inc/Math/StdEngine.h
math/minuit2/inc/Minuit2/MnPlot.h
tmva/tmva/inc/TMVA/Pattern.h

- [ci] Remove built-in Vc from mac-beta builds: https://github.com/VcDevel/Vc/issues/367
- Missing include for uint64_t
- And more...

[xcode26] Misc fixes

---

math/mathcore/inc/Fit/Chi2FCN.h
math/mathcore/inc/Fit/LogLikelihoodFCN.h
math/mathcore/inc/Fit/PoissonLikelihoodFCN.h
math/mathcore/inc/Math/IFunction.h
math/mathmore/src/GSLNLSMinimizer.cxx
roofit/roofit/test/GaussFunction.h
roottest/root/meta/execTypedefList.C
roottest/root/meta/typelist.v5.txt
roottest/root/meta/typelist_win32.v5.txt

Move the gradient-related methods from the
`IGradientFunctionMultiDimTempl` to the `IBaseFunctionMultiDimTempl` base class, and the same for the 1D version.
This makes the `IGradientFunction` classes pure "indicator" classes that indicate whether the gradient is implemented by the user or not. The actual function interface is unified in the IBaseFunctions.
This fixes the problem that the override keywords could not be used consistently in I*Function-derived classes where the base class was templated to be either `IBaseFunction` or `IGradientFunction`.
Alternative to:
* https://github.com/root-project/root/pull/19058

[Math] Move gradient methods to IBaseFunction classes

---

tree/dataframe/test/CMakeLists.txt

Following the move of RNTuple out of the `root7` build option and into the default ROOT build in #18410, the RDF tests concerning RNTuple should reflect this.

[df] Move RNTuple-related tests out of ROOT 7

---

README/ReleaseNotes/v638/index.md
bindings/jupyroot/python/JupyROOT/helpers/utils.py
config/rootrc.in

JSROOT is on by default when opening a new notebook, [users](https://root-forum.cern.ch/t/disable-jsroot-by-default-in-jupyter/63741) may want to disable it for their sessions without having to add one line per notebook, but instead one line in .rootrc that applies for all.
This PR adds the functionality to disable JSROOT in Jupyter notebooks by default through a new .rootrc parameter `JSROOT.Disable`.
- see root-project/web#1128
This PR fixes #19068

[jupyter] Add option in .rootrc to disable jsroot by default when opening notebooks

---

tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/dataframe_snapshot_ntuple.cxx

So it can actually be compiled and run even with `root7=OFF`.

[df] Remove dependency from RNTupleUtil in test

---

README/ReleaseNotes/v638/index.md
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_tdirectory.py
bindings/pyroot/pythonizations/test/tdirectoryfile_attrsyntax_get.py
bindings/pyroot/pythonizations/test/tfile_attrsyntax_get_writeobject_open.py

- Removes the deprecated `_TDirectory_getattr` pythonization that, according to the deprecation notice, should have already been removed in 6.34.
I just saw this while scrolling through and did no local testing. Do whatever you want with this ;)

Remove deprecated _TDirectory_getattr pythonization

---

math/genvector/inc/Math/GenVector/Cartesian2D.h
math/genvector/inc/Math/GenVector/Cartesian3D.h
math/genvector/inc/Math/GenVector/Cylindrical3D.h
math/genvector/inc/Math/GenVector/CylindricalEta3D.h
math/genvector/inc/Math/GenVector/Polar2D.h
math/genvector/inc/Math/GenVector/Polar3D.h
math/genvector/inc/Math/GenVector/PositionVector3D.h
math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h
math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/GenVector/PxPyPzE4D.h
math/genvector/inc/Math/GenVector/PxPyPzM4D.h
math/genvector/test/CMakeLists.txt
math/genvector/test/staticTests.cxx

- Make genvector classes nothrow move constructible. Old user-defined copy constructors and assignment operators were preventing the auto-generated ones.
- Add a test that statically asserts their moveability / trivially copyable
- ~~Fix a doxygen link [here](https://root.cern.ch/doc/master/classROOT_1_1Math_1_1Cartesian2D.html) The "see also" generates a dead link because doxygen tries to link to "Overview" and "the".~~
Fixes #19042

[GenVector] Make most vector and point classes nothrow move constructible.

---

roottest/root/treeformula/stl/mapvector.C

the class std::pair<int,std::vector<int>> was not selected correctly.
This macro, aclic'd in a test, sporadically failed on macbeta.

[test] Correct typo in linkdef pragma

---

bindings/pyroot/pythonizations/test/uhi_indexing.py
hist/hist/inc/TH1.h

When using UHI for slicing, `GetEntries()` value of a histogram did not correctly reflect the state after the operation.
Note that after this fix, calling `GetEntries()` on a sliced histogram will reflect the effective total count (the same value returned by `GetEffectiveEntries()`). 
The following:
```python
import ROOT
h = ROOT.TH1D("h", "h", 10, 0, 10)
h.SetBinContent(1, 5)
h_slice = h[...]
h.Print()
h_slice.Print()
```
Will output:
```
TH1.Print Name  = h, Entries= 1, Total sum= 5
TH1.Print Name  = h, Entries= 5, Total sum= 5
```
This PR fixes #19113

[Python][UHI] Fix entry count after slicing operations

---

bindings/pyroot/cppyy/cppyy/test/CMakeLists.txt

A subset of these tests fail when calling `std::make_unique` (`test15_unique_ptr_template_deduction ` and `test16_unique_ptr_moves `). This stems from incorrect type info collected in TClingCallFunc, that goes through `cling::utils::Transform::GetPartiallyDesugaredType`, which explicitly adds a 0 to the arg pack of `make_unique` during codegen, which is illegal:
```
2025-06-21T02:05:14.3073430Z ../../../../../../src/bindings/pyroot/cppyy/cppyy/test/test_cpp11features.py::TestCPP11FEATURES::test15_unique_ptr_template_deduction input_line_132:7:124: error: address of overloaded function 'make_unique' does not match required type 'std::unique_ptr<int, std::default_delete<int> > ()'
2025-06-21T02:05:14.3074880Z       new (ret) (std::unique_ptr<int, std::default_delete<int> >) …
```

[cppyy] disable C++11 tests on mac-beta

---

tutorials/visualisation/eve7/single_dark.C
ui5/eve7/controller/Main.controller.js
ui5/eve7/controller/MainMini.controller.js

This PR adds new demo and minor correction for single view type when view is not mandatory (e.g. its scenes are not streamed or subscribed to client by the default)
The screenshots is here of server windows in multi client mode:

[reve] New demo for dark openui5 theme and single/detached view

---

core/base/inc/TMathBase.h
tmva/tmva/src/TSpline1.cxx
tmva/tmva/src/TSpline2.cxx

PR https://github.com/root-project/root/pull/17179 got stuck because there were three different opinions on how to resolve undefined behavior in case the search value is smaller than the smallest element in the collection. In particular, the problem was that in TMVA, the undefined behavior was used, because in practice for a `std::vector()`, the expression `std::distance(v.begin(), v.begin() - 1)` evaluates to -1, even though it's actually UB to take the iterator before the beginning of a vector. So there is no backwards compatible way to resolve the undefined behavior.
The only way out that I see is to deprecate the `TMath::BinarySearch` overload for iterators, and tell people to use the standard library instead. This is implemented in this commit.
Alternative to #17179.
One can use this …

[Core] Deprecate `TMath::BinarySearch` overload for iterators

---

gui/webgui6/src/TWebCanvas.cxx

When new TCanvas(kFALSE) invoked to create canvas without TCanvasImp, many attributes do not set from gStyle. Therefore copy correspondent part from TCanvas::Init().
Backport of https://github.com/root-project/root/pull/19127

[webcanvas] set default attributes for created TCanvas [6.36]

---

net/http/civetweb/CREDITS.md
net/http/civetweb/LICENSE.md
net/http/civetweb/README.md
net/http/civetweb/civetweb.c
net/http/civetweb/civetweb.h
net/http/civetweb/handle_form.inl
net/http/civetweb/match.inl
net/http/civetweb/md5.inl
net/http/civetweb/response.inl
net/http/civetweb/sort.inl
net/http/src/TCivetweb.cxx
net/http/src/THttpServer.cxx

Unfortunately, since 2 years `civetweb` does not making official releases,
but there are many updates and fixes which are provided to master branch - also from us.
Therefore:
* update `civetweb` to recent master branch as of 23.06.2025 - https://github.com/civetweb/civetweb/tree/5864b55a94f4b5238155cbf2baec707f0fa2ba6d
* apply our small patch - exclude `openssl/engine.h` include
* add more CORS headers with `cred_cors` URL option, enables partial access to ROOT files with CORS and enabled authentication.
[Use-case from the forum](https://root-forum.cern.ch/t/thttpserver-with-cors-and-htdigest-auth/63769/) is not directly affected by this PR while there not ROOT but JSON files are requested - which do not use partial 206 requests.

[http] upgrade civetweb, enable more CORS headers

---

interpreter/cling/lib/Interpreter/DeclUnloader.cpp
interpreter/cling/test/CodeUnloading/Exception.C

Fixes the assertion error with the following:
```
[cling]$ #include <exception>
[cling]$ try {} catch (std::exception &) {}
[cling]$ .undo 1
```
This PR fixes https://github.com/root-project/root/issues/14012

[cling] Handle unloading unnamed `VarDecl`s in catch statements

---

cmake/modules/RootMacros.cmake

This does the same thing as CMakes find package now, printing the version of the Python module in the same style if available.
This will make it easier to debug compatibility problems from the build logs.

[CMake] Also print version of found Python module

---

.github/workflows/root-ci-config/buildconfig/alma8.txt
.github/workflows/root-ci-config/buildconfig/ubuntu2404-cuda.txt
.github/workflows/root-ci.yml
main/src/h2root.cxx
misc/minicern/CMakeLists.txt

By adding a space, we create an extra char that, on Fortran's side will be substituted by c, rather than appending to the (temporary passed as argument C-)string.
Related discussion: https://github.com/root-project/root/pull/15915/files
Fixes https://github.com/root-project/root/issues/14155

[h2root] explore/circumvent if occassional memory corruption issue stems from substring replacement

---

bindings/pyroot/pythonizations/doc/index.md

The link to the pythonizations seems cut-off and/or outdated.

[skip-ci] Fix incorrect URL in PyROOT documentation

---

roottest/root/io/autoptr/CMakeLists.txt
roottest/root/io/autoptr/TestAutoPtr_v2.hxx
roottest/root/io/autoptr/TestAutoPtr_v2_LinkDef.h
roottest/root/io/autoptr/TestAutoPtr_v3.hxx
roottest/root/io/autoptr/TestAutoPtr_v3_LinkDef.h
roottest/root/io/autoptr/evolve_autoptr.cxx
roottest/root/io/autoptr/write_autoptr.cxx

Test evolution of auto_ptr into unique_ptr both as a split and unsplit member. Uses an emulated auto_ptr class instead of the real std::auto_ptr because the actual one may have been removed.
Tests the fix of PR #18320
Moved from https://github.com/root-project/roottest/pull/1306, including initial set of review comments.

Add auto_ptr schema evolution test

---

tree/tree/src/TTree.cxx

https://root-forum.cern.ch/t/string-format-of-datatypes-in-branchdescriptor/63802/2

[skip-ci][tree] Fix typo in type of array and improve docu

---

core/clingutils/res/TClingUtils.h
core/clingutils/src/TClingUtils.cxx
core/dictgen/src/rootcling_impl.cxx
core/foundation/inc/TClassEdit.h
core/foundation/src/TClassEdit.cxx
core/metacling/src/TCling.cxx
roottest/root/ntuple/CMakeLists.txt
roottest/root/ntuple/atlas-datavector/AtlasLikeDataVector.hxx
roottest/root/ntuple/atlas-datavector/CMakeLists.txt
roottest/root/ntuple/atlas-datavector/read.cxx
roottest/root/ntuple/atlas-datavector/selection.xml
roottest/root/ntuple/atlas-datavector/write.cxx

Fixes #19022 
See first commit description for an explanation.
Third commit provides a reproducer of the linked issue, removing the first commit will produce the same exception from RField

Check for existing type before removing whitespaces

---

.github/workflows/root-ci-config/buildconfig/windows10.txt
cmake/modules/CheckCompiler.cmake

Motivated by https://github.com/root-project/root/pull/19184
FYI, @ferdymercury.
The first CI run will fail because not all platforms have Fortran installed. In a second pass, `fortran` will then be disabled for all platforms where it failed (probably only Windows).

[CMake] Also consider fail-on-missing for `fortran` features

---

js/changes.md
js/modules/base/svg2pdf.mjs
js/modules/core.mjs
js/modules/gui/HierarchyPainter.mjs
js/modules/tree.mjs

1. Fix - reading TLeafC leafs
2. Fix - support BigInt in object inspector
3. Fix - svg2pdf.js URL bounding box

[jsroot] 7.9.x 26/06/2025

---

tree/treeplayer/test/CMakeLists.txt
tree/treeplayer/test/regressions.cxx

Tests https://its.cern.ch/jira/browse/ROOT-8577

[test] add test for misspelled branch name in ttree draw

---

tree/dataframe/src/RDataFrame.cxx

There was not much information about this variable, which can be very useful in batch environments.
This is how it renders:

[skip-ci][Docs] Add info about ROOT_MAX_THREADS to the RDF documentation.

---

tree/ntuple/src/RNTupleMerger.cxx
tree/ntuple/test/ntuple_merger.cxx

- nElements was used to grow each zero page instead of nElementsPerPage
- only the last zero page was added to the page groups
This bug manifested as a crash when Union-merging big-enough RNTuples, so that GenerateZeroPagesForColumns actually generates more than 1 page.
This fix will be backported to 6.36.
cc @amete

[ntuple] Merger: fix bugs in GenerateZeroPagesForColumns

---

hist/hist/inc/TF1.h

Before, the requirement was that the wrapped function had a call operator that *exactly* took C-style arrays as arguments.
To be more general, we check if the function can be invoked with C-style arrays as arguments, even if implicit conversions are involved. This is done using `std::is_invocable_r_v` from C++17.
Care was taken that the detection of vectorized functions still works, which can be tested like this (requires `veccore` and `vc`):
```c++
// Modified reproducer from ROOT-10251
auto originalFF = [](ROOT::Double_v *x , double *par){ (void)par; return *x; };
auto boundFF = std::bind (originalFF,std::placeholders::_1, std::placeholders::_2);
TF1 myFitFunct("myFitFunct", boundFF,0, 1 , 0 );
myFitFunct.Print("v");
std::cout << myFitFunct.IsVectorized() << std::endl;
```
Closes …

[Hist] Generalize TF1 constructor using C++17

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/uhi_indexing.py

This PR removes the `__eq__` operator pythonization for TH1 and its derived classes, which was introduced as part of the UHI implementation. The operator caused unintended backward-incompatible behavior and potential confusion for python users. Instead of extending the operator to address concerns raised in #19061, this PR reverts it entirely.
This PR fixes #19038

[Python][UHI] Remove __eq__ Pythonization for TH1 Derived Classes

---

tree/tree/src/TBranchElement.cxx

[tree] Avoid redundant calls to GetInfoImp

---

roottest/root/io/hadd/CMakeLists.txt

Change CMake function from ROOTTEST_ADD_TEST to ROOT_ADD_PYUNITTEST

Ensure that hadd python tests are run only if pytest is available

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/uhi_indexing.py

[636][Python][UHI] Remove __eq__ Pythonization for TH1 Derived Classes

---

tree/tree/src/TTree.cxx

Fixes https://root-forum.cern.ch/t/string-format-of-datatypes-in-branchdescriptor/63802/2

[skip-ci][tree] crosslink to datatypes

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.h
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_cppinstance.py
bindings/pyroot/pythonizations/src/CPPInstancePyz.cxx
bindings/pyroot/pythonizations/src/PyROOTModule.cxx

The CPPIntance type is immutable, and new attributes can't be set:
```txt
import cppyy
>>> setattr(cppyy._backend.CPPInstance, "test", 10)
File "<python-input-3>", line 1, in <module>
setattr(cppyy._backend.CPPInstance, "test", 10)
~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot set 'test' attribute of immutable type 'cppyy.CPPInstance'
>>>
```
In our pythonizations, we still want to monkey-patch a `__reduce__` method anyway, and to make Python not complain we to a hack by setting the attribute with the C Python API using `PyObject_GenericSetAttr`. This function doesn't normally do any safety checks, and our monkey patching works.
However, the Python debug build is not having any of that, thanks to a new assert that was added a year ago: …

[Python] Avoid hack in setting `__reduce__` attribute of CPPInstance

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPScope.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Utility.cxx

The changes here collects residual exceptions thrown by Python, before calling into Python C API.
Towards fixing #19224

[cppyy] Enable using cppyy with debug build of Python

---

.github/workflows/root-ci.yml
core/multiproc/inc/TMPWorkerExecutor.h
roottest/root/io/abstractclass/DataBlock1.h
roottest/root/io/abstractclass/DataBlock2.h
roottest/root/io/abstractclass/DataBlockBase.h
roottest/root/io/arrayobject/foo.h
roottest/root/io/clones/RtObj.h
roottest/root/io/compression/Event.h
roottest/root/io/evolution/equivalent/ioReadRuleEquivalentCode.h
roottest/root/io/evolution/pragma_read/v1/AliAODForwardMult.h
roottest/root/io/evolution/pragma_read/v2/AliAODForwardHeader.h
roottest/root/io/evolution/pragma_read/v2/AliAODForwardMult.h
roottest/root/io/json/test_classes.h
roottest/root/io/rootcint/foo.hh
roottest/root/io/treeproblem/Foo.h
roottest/root/io/xml/test_classes.h
roottest/root/meta/iotypeioname/classes.h
roottest/root/ntuple/streamerfield/Event_v2.hxx
roottest/root/ntuple/streamerfield/Event_v3.hxx

Currently, many override warnings remain unnoticed since the gcc-problem-matcher of the GitHub CI does not work correctly, and it's also easy to forget those annotations if you do not visit the "Files changed" tab.
If some devs later use dev=ON and testing=ON, this leads to failures for compilers that auto-enable -Winconsistent-missing-override.
To prevent this, we enable the suggest-override warning in the build of debian with dev=ON instead of in the one from alma, this way we are sure of always failing if some does a PR that forgets an override, forcing pull-requesters to fix their issues before merging.
Within this PR: also fix missing overrides uncovered by turning ON this flag in the dev=ON build.

[ci] Fail CI if missing override instead of just warning

---

core/rint/src/TRint.cxx
core/rint/test/TRintTests.cxx
roottest/root/core/CMakeLists.txt

Followup to #19195:
RDF IMT tutorials didn't run since 10 months, since the following passed with a 0 exit status:
```
$ root '-e "ROOT::EnableImplicitMT(4)"' ...
root: unrecognized option '-e "ROOT::EnableImplicitMT(4)"'
Try 'root --help' for more information.
2965/2993 Test tutorial-analysis-dataframe-df102_NanoAODDimuonAnalysis ............. Passed 0.15 sec
```
To avoid similar problem in the future, I suggest here to exit with a non-zero exit status. I chose 2 because 1 usually means that the script/macro/command that was running *in the interpreter* failed:
```
bin/root -b -q -e "invalid"; echo $?
1
```
Whereas a failure to parse the argument would now be:
```
$ root '-e "ROOT::EnableImplicitMT(4)"'; echo $?
2
```

[root.exe] Use non-zero exit status when invalid arguments are passed

---

interpreter/cling/tools/Jupyter/CMakeLists.txt
interpreter/cling/tools/libcling/CMakeLists.txt

Reported here: https://github.com/root-project/cling/issues/551
We check if a variable exists named with the value of LLVM_SUBMIT_VERSION instead of checking if it is defined.

[cling] Check if `LLVM_SUBMIT_VERSION` is defined, not its value

---

roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/src/FitHelpers.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
roofit/roofitcore/test/testRooSimultaneous.cxx

`RooSimultaneous` is a PDF class that performs the simultaneous fitting of multiple pairs of a PDF and a dataset.
`RooFit::ConditionalObservables(RooAbsArgs...)` is a command argument to the `fitTo()` method of the `RooAbsPdf` classes, which specifies variables that should be excluded from the normalization set of a PDF when fitting.
If I use the command argument for fitting using the class, the class does not deal with the conditional variable well, and the conditional variables become floating parameters. This should be fixed.
This PR addresses the bug. Please see the details of the issue in the link: https://github.com/root-project/root/issues/19166

Fixing issues in RooSimultaneous with ConditionalObservables

---

.github/workflows/root-docs-ci.yml

This is most relevant for scheduled builds of branches.

[skip-ci] ci: Checkout explicit branch in root-docs

---

main/CMakeLists.txt
main/src/rootls.cxx
main/src/wildcards.hpp
roottest/main/CMakeLists.txt

Adds a native version of the `rootls` executable. This allows running rootls without Python, meaning one can use it from a ROOT build with pyroot=off.
As a bonus, this version is ~3 to 4x faster than the python version on all the tests I did locally (bringing the "minimal" latency from ~0.5s to ~0.15s).
The output format should be exactly the same, except for some cases I found which rootls.py doesn't handle correctly.
The executable is currently called `rootlscxx` and the original `rootls` is preserved, but ideally it should be phased out after verifying that everything is covered.
I copied the tests for rootls.py and made sure they all pass with rootlscxx as well.
To handle globbing I imported a small header-only library called [wildcards.hpp](https://github.com/zemasoft/wildcards). The …

[main] Rewrite rootls in c++

---

tree/tree/inc/TChain.h
tree/tree/inc/TChainElement.h
tree/tree/inc/TTree.h
tree/tree/src/TChain.cxx
tree/tree/src/TTree.cxx
tree/treeplayer/test/CMakeLists.txt
tree/treeplayer/test/gh16804.cxx

In the case of a TTree with a friend TChain, the call to `GetEntry` that needs to move to a new tree in the friend TChain was not correctly updating the branch addresses. SetBranchAddress now makes a distinction between the case of the branch belonging to the main tree versus the case of the branch belonging to one of the friends. In order for this to work, GetBranch functionality has been split in two: GetBranchFromSelf checks whether the branch name corresponds to a branch of this tree and returns it if so; GetBranchFromFriends checks whether the branch name corresponds to a branch found in one of the trees and returns it if so.
Fixes #16804

[tree] Delegate SetBranchAddress to friends if necessary

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_uhi.py
bindings/pyroot/pythonizations/test/uhi_indexing.py

Implemented `__iter__` to return an immutable copy of bin contents, including flow bins.
This PR fixes #19311

[Python][UHI] Add implementation of __iter__ to fix list(h)

---

roottest/root/tree/gh-18782/CMakeLists.txt
roottest/root/tree/gh-18782/MyParticle.cxx
roottest/root/tree/gh-18782/MyParticle.hxx
roottest/root/tree/gh-18782/MyParticleLinkDef.hxx
roottest/root/tree/gh-18782/runtest.cxx
tree/tree/src/TBranchElement.cxx

A call to `TTree::Branch` with the branch type being an STL collection with an element type derived from an unsplittable base class (i.e. with a custom streamer) would fail with the following error message:
```
Fatal in <TBranchElement::InitializeOffsets>: Could not find the real data member 'objects' when constructing the branch 'objects' [Likely an internal error, please report to the developers].
aborting
```
Due to the fact that InitializeOffsets was not able to properly compute the offset of the base class of the element type. Unfortunately the error message itself was obscure, since the repetition of the word 'objects' in this case simply refers to the top-level branch name.
What is really happening is that the function logic mixes the calculation of the offsets of base classes with …

Properly calculate offset of unsplittable base class of STL collection element type

---

core/testsupport/inc/ROOT/TestSupport.hxx

Adds a `_PARTIAL` macro to allow matching only a piece of a dialog.
Also clang-formatted the code and made a small refactor to avoid repetition.

[core] add macros in TestSupport to match partial dialogs

---

tree/ntuple/test/ntuple_show.cxx

Aesthetic-only change: use raw strings instead of string concatenation for the expected values in ntuple_show.

[ntuple] use raw strings in ntuple_show for ease of reading

---

cmake/modules/SearchInstalledSoftware.cmake
math/vecops/CMakeLists.txt
roofit/batchcompute/CMakeLists.txt
tmva/tmva/CMakeLists.txt

VecOps was linking to "VDT" even if that target wasn't declared. This
means that CMake generated the link recipe "-lVDT", although the library
is actually named libvdt.so / .dylib.
Therefore:
- Use the canonical target name VDT::VDT throughout ROOT.
- Make the link to VDT private where possible (not possible for VecOps).
- Ensure that there's always an imported CMake target behind VDT::VDT,
whose imported location is set correctly.
Fix #19313

[CMake] Correct linking to VDT.

---

roofit/roofitcore/src/RooDerivative.cxx
tutorials/roofit/roofit/rf111_derivatives.C
tutorials/roofit/roofit/rf111_derivatives.py

Avoid using out-of-range values for the numerical differentiation in RooDerivative.
This adds three new special cases:
* derivative is first order and x-value is close to limit: just use one-directional derivative already implemented in the RichardsonDerivator
* higher-order derivative but function is constant within floating point precision: just return zero
* higher-order derivative for non-constant function: throw error, because we don't want to risk wrong derivatives by evaluating outside the range, which will result in x-value-clipping and therefore invalid y value differences
The tutorials fortunately hit the second case with the locally constant function, so we can remove the workaround with the sub-range introduced in #10470.
Closes #18615.
FYI, @VanyaBelyaev

[RF] Avoid using out-of-range values in RooDerivative

---

roofit/roofit/src/RooBifurGauss.cxx
roofit/roofit/src/RooBreitWigner.cxx
roofit/roofit/src/RooChiSquarePdf.cxx
roofit/roofit/src/RooPoisson.cxx

As requested in #7210, adds parameters checks to:
- Breit-Wigner distribution
- Chi-Square distribution
- Decay distribution
- Exponential distribution
- I know there is more distributions to check the param of, I just wanted to be sure I was doing what requested before submitting 10+ commits.
- My statistics knowledge is not the best, so I hope I did not make mistakes on parameters ranges :see_no_evil: 
- I used [skip-CI] tag just because I wanted to trigger Jenkins just once after I have created parameter checks on all (or more) distributions. I guess that when removing the tag it will run the tests on the full PR and not only on the last commit, correct?
- I have also inserted the [skip-CI] tag in the commit messages, is this correct or unnecessary?
This PR (partially) fixes #7210 …

[RF] Implement checking param range

---

.github/workflows/root-ci-config/buildconfig/rawhide.txt
.github/workflows/root-ci.yml
bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx
bindings/tpython/src/TPyClassGenerator.cxx
bindings/tpython/src/TPython.cxx
roottest/python/cling/runPyClassTest.C

Like this, we have a Python debug interpreter run in our CI and also test the cutting edge of Fedora development.
Quoting from the [Python docs](https://devguide.python.org/getting-started/setup-building/index.html):
> You should always develop under a pydebug build of CPython (the only instance of when you shouldn’t is if you are taking performance measurements). Even when working only on pure Python code the pydebug build provides several useful checks that one should not skip.
Closes https://github.com/root-project/root/issues/19224.

[ci] Add Fedora Rawhide special build with Python debug interpreter

---

tree/ntuple/CMakeLists.txt

The file was split some time ago, it should not exceed limits anymore.

[ntuple] Remove `/bigobj` flag for `RField.cxx`

---

tmva/sofie/inc/TMVA/ROperator_TopK.hxx

This PR fixes a bug introduced by mistake in the code used to generate the C++ code for TopK

[tmva][sofie] Fix bug in getting stride of output of TopK operator

---

tree/ntuple/inc/ROOT/RNTupleView.hxx
tree/ntuple/src/RField.cxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntuple/src/RFieldVisitor.cxx
tree/ntuple/test/rfield_vector.cxx

See the individual commits for the case-by-case changes and explanations.

[ntuple] Correct `RValue::GetRef<T>` usage or use `RValue::GetPtr<void>`

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

This PR introduces the method `RNTupleInspector::GetFieldsTreeAsDot` which gives a string that represents the tree structure of RNTuple fields in .dot language (that can then be displayed in graphviz for example)

[ntuple] Fields tree as dot

---

roottest/python/JsMVA/nbdiff.py
roottest/python/JupyROOT/nbdiff.py

This was caught by the Python interpreter with `pydebug`.

[roottest] Correctly close opened files in `nbdiff`

---

CMakeLists.txt

With linkers that rescan libraries, link recipes can be shortened. On Mac, the linker even emits a warning when `libgtest.a` is linked to twice. By moving to modern policies, CMake is allowed to deduplicate link recipes (if the linker supports it).
The first policy enables this feature on Windows, LLVM LD and Mac linkers. The second just means to keep the first occurrence.
This should fix the warning @dpiparo 
`ld: warning: ignoring duplicate libraries: '../../../googletest-prefix/src/googletest-build/lib//libgtest.a'`

[CMake] Deduplicate static libraries if supported by linker.

---

hist/hist/src/TH1.cxx
hist/hist/test/test_TH1.cxx

Before, `Sumw2()` would first allocate `fSumw2`, then empty the buffer, and finally compute the weights squared. However, this last step assumed unweighted filling and would override weighted fills that happened as part of the buffering. Instead I believe it's possible to just leave the entries in the buffer and take care of them later.
Fixes #19359

[hist] Ignore buffer in `TH1::Sumw2`

---

hist/histv7/doc/CodeArchitecture.md

To enable incremental review, the start of this architecture document is provided upfront. Further classes will be added when implemented.

[skip-ci][hist] Document architecture for initial set of classes

---

tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/dataframe_snapshot.cxx
tree/dataframe/test/dataframe_snapshot_ntuple.cxx

`dataframe_snapshot.cxx`: Fix the following compilation error:
```
dataframe_snapshot.cxx(1000,34): error C2326: 'RDFSnapshotMore_CompositeTypeWithNameClash_Test::TestBody::FileGuard::~FileGuard(void)': function cannot access 'fName'
```
and the following run-time error:
```
467: [ RUN      ] RDFSnapshotMore.Lazy
467: C:\root-dev\git\master\tree\dataframe\test\dataframe_snapshot.cxx(860): error: Value of: gSystem->AccessPathName(fname1)
467:   Actual: false
467: Expected: true
```
`dataframe_snapshot_ntuple.cxx`: Fix the following error:
```
469: [ RUN      ] RDFSnapshotRNTupleTest.InnerFields
469: ROOT::TestSupport::ForbidDiagnostics::handler(): Diagnostic in 'Snapshot':
469: Column electron.pt will be saved as electron_pt
469: ROOT::TestSupport::ForbidDiagnostics::handler(): Diagnostic …
```

[rdf] Fix dataframe_snapshot tests on Windows

---

bindings/pyroot/cppyy/cppyy/test/stltypes.xml
tree/tree/inc/LinkDef.h

The third warning that I see locally is addressed in https://github.com/root-project/root/pull/19202.

Remove two unused dictionary rules

---

tree/tree/src/TChain.cxx
tree/treeplayer/test/gh16804.cxx

Followup to https://github.com/root-project/root/pull/18871.
When calling TChain::SetBranchAddress, the dataset schema is loaded in case it
hasn't been done yet. This happens so that we can actually check whether the
input branch name can be found in the TChain or not. When this in turn happens
as part of a previous call to SetBranchAddress which is querying all the friends
of a main tree to understand in which friend the branch might be, then we just
can't print an error in case of a seemingly missing branch name in any single
friend.
It can happen that any, or all, the friend TChains have no files. One simple
scenario to imagine is a user calling `TChain::Add` later than
`TChain::SetBranchAddress`. In this situation, we can't tell whether the input
branch name will exist at a later …

Mitigate TChain with no files and SetBranchAddress call 

---

io/io/src/TKey.cxx
roottest/root/io/customStreamer/CMakeLists.txt
roottest/root/io/customStreamer/StreamerThrow.C
roottest/root/io/customStreamer/StreamerThrow.ref
roottest/root/io/customStreamer/StreamerThrowClass.h
roottest/root/io/customStreamer/StreamerThrowClass_LinkDef.h

This avoids corrupting the in-memory `TFile` structure with throwing `Streamer()` functions.

[io] Register TKey after successful Streamer()

---

roottest/main/CMakeLists.txt

ROOT_8197.C calls gSystem->Exec("rootcp --recreate ...

[cmake][skip-ci] disable ROOT_8197 if no PyROOT

---

hist/histv7/CMakeLists.txt
hist/histv7/doc/DesignImplementation.md
hist/histv7/inc/ROOT/RLinearizedIndex.hxx
hist/histv7/inc/ROOT/RRegularAxis.hxx
hist/histv7/inc/ROOT/RVariableBinAxis.hxx
hist/histv7/test/CMakeLists.txt
hist/histv7/test/hist_regular.cxx
hist/histv7/test/hist_test.hxx
hist/histv7/test/hist_variable.cxx

The first versions of these classes expose only `ComputeLinearizedIndex` with simple implementations. Further improvements and optimizations are possible in the future.
This PR also includes basic build system additions and setup for unit testing.

[hist] Implement initial `RRegularAxis` and `RVariableBinAxis`

---

core/imt/inc/ROOT/RTaskArena.hxx

This is confusing in the Doxygen documentation, and the comment is actually the explanation why we need `RTaskArenaWrapper`.

[skip-ci][imt] Remove documentation on ROOT namespace

---

tree/ntuple/inc/ROOT/RField/RFieldSTLMisc.hxx
tree/ntuple/src/RField.cxx

std::bitset on windows behaves differently from clang/gcc: it allocates an array of type T where T may be a u32 or u64 depending on the number of bits of the bitset itself. As we are currently assuming std::bitset is always backed up by an array of `unsigned long` (which is 32 bits on windows), we are miscalculating the required size for a bitset of > 64 bits (e.g. we only allocate 3 words of 32 bits for a bitset<65>, but it really is backed up by 2 64-bit words), resulting in memory corruption.
This PR should fix #19410.
Opening as a draft to let the CI run as I can't seem to run all tests locally.

[ntuple] Fix RBitsetField memory corruption on Windows

---

core/meta/inc/TClass.h
core/meta/src/TClass.cxx

TClass: inline initialize most members

---

bindings/pyroot/cppyy/CPyCppyy/src/DispatchPtr.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx
bindings/pyroot/cppyy/cppyy/test/test_concurrent.py

[cppyy] fix usage of Python GIL to support threading

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.h
bindings/pyroot/cppyy/CPyCppyy/src/CPPOverload.cxx
bindings/pyroot/cppyy/CPyCppyy/src/PyCallable.h
bindings/pyroot/cppyy/patches/get-names-and-types-of-all-overloads-signature.patch

This PR introduces a machinery to get the names and types (separately) of the signature of each overload of a particular `CPPOverload` object. This allows for example for something like.
**EDIT**
Here is the latest status of this feature after some discussion:
```python
>>> import ROOT
>>> ROOT.gInterpreter.Declare("""
int foo(int a, float b);
int foo(int a);
float foo(float b);
double foo(int a, float b, double c);
... """)
True
>>> ROOT.foo
<cppyy.CPPOverload object at 0x7fc470789fd0>
>>> from pprint import pprint
>>> pprint(ROOT.foo.func_overloads_names)
{'double ::foo(int a, float b, double c)': ('a', 'b', 'c'),
'float ::foo(float b)': ('b',),
'int ::foo(int a)': ('a',),
'int ::foo(int a, float b)': ('a', 'b')}
>>> pprint(ROOT.foo.func_overloads_types)
{'double ::foo(int a, float b, …
```

[PyROOT] Get names and types of all overloads' signature

---

tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RNTupleDS.cxx
tree/dataframe/test/datasource_ntuple.cxx

Discovered when trying to read an RNTuple `std::int8_t`-type field, which is typedeffed as a `signed char`.

[DF] Add `signed char` to `TypeID2TypeName`

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx

Removed constness from returned vectors and made GetColumnsByFieldId public in RNTupleInspector

[ntuple] Change RNTupleInspector return type of methods

---

hist/hist/src/TFormula.cxx

Fixes https://github.com/root-project/root/issues/19452
@Zehvogel would this help? Or you would get the error somewhere else?

[math] return early if clad not available

---

bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
bindings/pyroot/cppyy/cppyy/test/test_templates.py
interpreter/cling/lib/Interpreter/LookupHelper.cpp

When instantiating with another templated function

[cppyy] fix: instantiation of templated functions

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt
interpreter/cling/tools/plugins/clad/patches/Add-missing-exception-include.patch

There was a `#include <exception>` missing in case `NDEBUG` is not defined.

Patch builtin Clad version to add missing include

---

tree/tree/inc/TChain.h
tree/tree/inc/TFriendElement.h
tree/tree/src/TChain.cxx
tree/treeplayer/test/CMakeLists.txt
tree/treeplayer/test/gh16805.cxx

Fixes #16805 
Part of the logic of TChain::LoadTree deals with updating the status of friend
trees. First, the current entry is loaded on all friends. In case the friend
tree is a chain that needs to switch to a new tree, the branch addresses of the
friend are also updated.
This logic only considered the case of top-level friends of a TChain. Notably,
it did not consider the case of a main TChain where one (or more) of the trees
in the chain have themselves some friends, but not the main chain itself:
TChain c1
--> TTree t1 <friendswith> TChain c2
This commit condenses the logic that updates friends in a separate method of
TChain. The new method is called in TChain::LoadTree, either in the pre-existing
case of top-level friends or in the new case of friends of the current tree.
The new …

Improve logic to refresh branch addresses of TChain friends 

---

bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
bindings/pyroot/cppyy/patches/cppyy-Get-overload-from-template-proxy-using-tmpl-args.patch
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_rdf_pyz.py
bindings/pyroot/pythonizations/test/rdf_define_pyz.py
bindings/pyroot/pythonizations/test/rdf_filter_pyz.py

This PR extends the `RDataFrame` pythonizations by adding support for passing C++ free functions to `.Define()` and `Filter` operations, with support for:
- Templated functions
- Overloaded functions
- Functions taking any input/output combination  of
- Fundamental types
- ROOT types (e.g. TObject-derived classes)
- User-defined C++ classes
The implementation works by converting the free function to `std::function` using the function's signature.
> [!warning]
> This currently doesn't work if the function takes templated types as input arguments like STL containers (e.g. `std::vector<T>`) because of #19358
> Concretely, this doesn't work:
> ```cpp
> bool has_even_sum(const RVec<int>& v) {
>    return Sum(v) % 2 == 0;
> } 
> ```
> [!important]
> Prerequisites / TODO:
> - [x] Bring #9138 up …

[Python][RDF] Enable Support for C++ Free Functions in RDF Define and Filter

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.h
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyPyModule.cxx
bindings/pyroot/pythonizations/CMakeLists.txt
bindings/pyroot/pythonizations/test/import_load_libs.py
bindings/tpython/CMakeLists.txt

Restructure Python libraries to not require system links.

[Python] Restructure Python libraries to not require system links

---

hist/hist/src/TFractionFitter.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_TFractionFitter.cxx
tutorials/math/fit/fitFraction.C
tutorials/math/fit/index.md

Fixes https://its.cern.ch/jira/browse/ROOT-9330
This would be also a good excuse to revive https://github.com/root-project/root/pull/18090

[test] add test/tutorial for TFractionFitter

---

cmake/modules/RootMacros.cmake
roottest/CMakeLists.txt
roottest/root/tree/fastcloningeventtree/CMakeLists.txt

It's not needed anymore now that `roottest` was merged into the main repository.
Follows up on a comment by @pcanal:
* https://github.com/root-project/root/pull/19370#discussion_r2242930620

[CMake] Remove `ROOTTEST_DIR` variable

---

roottest/root/io/evolution/pragma_read/v1/AliAODForwardMult.cxx
roottest/root/io/evolution/pragma_read/v2/AliAODForwardHeader.cxx

On my machine, the AliAOD tests fail with the following warning:
```txt
99/1338 Test  #373: roottest-root-io-evolution-pragma_read-libRoottestIoEvolutionPragmaV1-build .......................***Failed   18.22 sec
Generating libRoottestIoEvolutionPragmaV1.cxx, libRoottestIoEvolutionPragmaV1_rdict.pcm
Building CXX object roottest/root/io/evolution/pragma_read/CMakeFiles/libRoottestIoEvolutionPragmaV1libgen.dir/libRoottestIoEvolutionPragmaV1.cxx.o
Building CXX object roottest/root/io/evolution/pragma_read/CMakeFiles/libRoottestIoEvolutionPragmaV1libgen.dir/v1/AliAODForwardMult.cxx.o
/home/rembserj/code/root/root_src/roottest/root/io/evolution/pragma_read/v1/AliAODForwardMult.cxx: In static member function ‘static UInt_t AliAODForwardMult::MakeTriggerMask(const char*)’: …
```

[roottest] Fix warnings in AliAOD tests

---

tutorials/CMakeLists.txt

Mark `RBatchGenerator_TensorFlow.py` tutorial as multithreaded so it is not schedeuled at the same time with other tutorials, risking to use more memory than available on the CI.
Hopefully fixes #19125, after I have seen this happen twice in the same CI run again:
https://github.com/root-project/root/pull/19482

[CMake] Mark `RBatchGenerator_TensorFlow.py` tutorial as multithreaded

---

.github/workflows/cibuildwheel-impl/action.yml
.github/workflows/python_wheel_build.yml
bindings/pyroot/pythonizations/python/ROOT/_rootcli.py
cmake/modules/SearchInstalledSoftware.cmake
pyproject.toml
setup.py

Now that the workflow is fully functional, see e.g. https://github.com/root-project/root/actions/runs/16493485486, I am reopening this PR.
The wheels can be installed on any Linux x86_64 node via:
```
$: pip install ROOT --index-url=https://root-experimental-python-wheels.web.cern.ch
```

Add workflow to build Python wheels

---

tree/ntuple/inc/ROOT/RField/RFieldRecord.hxx
tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/src/RField.cxx
tree/ntuple/src/RFieldBase.cxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntuple/src/RNTupleReader.cxx
tree/ntuple/test/ntuple_emulated.cxx

Previously to this PR, if the user tried to load an emulated user-defined class using a custom CollectionProxy, they would get an untyped Record field which doesn't represent the collection properly.
With this change we instead detect if the field with unknown type is a Collection and, if so, we create an untyped Vector field rather than a Record field, allowing for proper inspection of the underlying values.
Another minor related change: in case of non-emulated fields (so if we have a proper TClass backing the user type) we don't require anymore that the class is at least Interpreted in case of collection proxies, as that is not necessary.
TODO: 
- add a test for the case where we have the dictionary for the user defined class but it's not associated to its original collection proxy …

[ntuple] Add support for emulating user collections with unknown collection proxies

---

io/io/src/TDirectoryFile.cxx
io/io/test/TFileTests.cxx

Fixes https://its.cern.ch/jira/browse/ROOT-10352

[io] seek parent should point to mother dir, not to top level dir

---

bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

This follows up on 85e74b88b04, where I accidentally used the `CMAKE_INSTALL_INCLUDEDIR` in the context of copying files to the build directory.
This breaks cases where the `CMAKE_INSTALL_INCLUDEDIR` is not equal to `include` (like for `gnuinstall=ON`). The include directory in the build tree is always just called `include`.
Also, remove some dead code that was left over from copy pasting CMake code when splitting up `libcppyy` into a regular C++ library and a CPython extension.

[Python] Fixup to Python library restructuring

---

core/testsupport/src/TestSupport.cxx

Tests randomly fail because the uring memory is exhausted.
Here are some examples:
```
[ RUN      ] RNTuple.RandomAccess
.../root-6.36.00/core/testsupport/src/TestSupport.cxx:79: Failure
Failed
Received unexpected diagnostic of severity 2000 at 'RIoUring' reading 'io_uring is unexpectedly not available because:
Failed to allocate memory for the smallest possible io_uring instance. 'memlock' memory has been exhausted for this user'.
Suppress those using ROOT/TestSupport.hxx
.../root-6.36.00/core/testsupport/src/TestSupport.cxx:79: Failure
Failed
Received unexpected diagnostic of severity 2000 at 'RRawFileUnix' reading 'io_uring setup failed, falling back to blocking I/O in ReadV'.
Suppress those using ROOT/TestSupport.hxx
[  FAILED  ] RNTuple.RandomAccess (20472 ms)
[ RUN      ] …
```

Ignore warnings from uring IO

---

tree/ntupleutil/v7/inc/ROOT/RNTupleInspector.hxx
tree/ntupleutil/v7/src/RNTupleInspector.cxx
tree/ntupleutil/v7/test/ntuple_inspector.cxx

- Renamed `GetColumnsByFieldId` to `GetAllColumnsOfField`
- Added unit tests for `GetAllColumnsOfField` because it also recently became a public method

[ntuple] Change GetColumn methods in Inspector

---

graf2d/gpad/src/TPad.cxx
graf2d/gpad/test/CMakeLists.txt
graf2d/gpad/test/pdftitle.cxx

With pdf output it is possible to define a table of content of a multi-pages file. Each page has its name specified using the option "Titlle:" followed by the title of the page. If the title contains a string matching a possible file extension like, for instance, "tex"o r "png", then the pdf generation went wrong and might crash. This PR fixes the problem.
Fixes https://github.com/root-project/root/issues/19390

Option Title: with title containing tex

---

.github/workflows/python_wheel_build.yml

Now that the workflow file is in the master branch, we should be able to run more triggers from PRs. Let's see

[build] Enable running wheel workflow on label

---

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
bindings/pyroot/pythonizations/test/numbadeclare.py

This PR adds support for using `std::vector<T>` and `std::array<T>` as input and return types in functions declared with `ROOT.Numba.Declare` used in RDataFrame `.Define` operations.
This makes it possible to define and use functions like:
```python
@ROOT.Numba.Declare(["std::array<int, 3>"], "std::vector<int>")
def square_vec(x):
return x * x
rdf = ROOT.RDataFrame(3) \
.Define("xvec", "std::array{(int)rdfentry_, (int)rdfentry_ + 1, (int)rdfentry_ + 2}") \
.Define("xvec_square", "Numba::square_vec(xvec)")
```
The implementation reuses the logic for handling RVecs.

[Python][RDF] Add support for std::vector and std::array in numba jitted functions

---

cmake/modules/RootBuildOptions.cmake
cmake/modules/RootMacros.cmake

**Backport of #19501 to fix the build errors on Spack and MacPorts with the next 6.36.04 patch release**
When using the `rpath=ON` option, the global CMake variable `CMAKE_INSTALL_RPATH` is mutated, which is problematic in several corner cases.
This commit suggests to append the rpaths at the target property level, and also set the rpaths for the build tree separately so they make sense.
A new ROOT macro is introduced for this rpath setting, which are also used for the PyROOT libraries, which also need custom rpaths.
Closes #19327 and #19134.

[v636][CMake] Set `rpath` for individual targets and not globally

---

interpreter/cling/include/cling/Interpreter/CIFactory.h
interpreter/cling/include/cling/Interpreter/ClingCodeCompleteConsumer.h
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/ClingCodeCompleteConsumer.cpp
interpreter/cling/lib/Interpreter/Interpreter.cpp
interpreter/cling/test/AutoComplete/AutoComplete.C

This patch eliminates the need to create a nested interpreter for code
completion.
In LLVM 19, some Sema internals became private:
See https://github.com/llvm/llvm-project/commit/874f511
Without this, we would require an additional patch on top of Clang to
access `Sema::CodeCompleter` after upgrading to LLVM 20.
This will fix one of the failing test during [upgrade](https://github.com/root-project/root/pull/19242) in CppInterOp (autocomplete)

[cling] Use clang-repl-style code completion

---

graf2d/gpad/src/TPad.cxx
graf2d/gpad/test/CMakeLists.txt
graf2d/gpad/test/pdftitle.cxx

Backport the "Title:" directive fix in PDF file

Backport the "Title:" directive fix in PDF file

---

roofit/roofitcore/inc/RooFit/Evaluator.h
roofit/roofitcore/src/RooFit/Evaluator.cxx

About 2 years ago in 85c5cb4, I made the mistake of introducing a potentially expensive double loop when setting the data for a likelihood: the `RooEvaluatorWapper` iterates over all data variables to set, and for each of them it calls `RooFit::Evaluator::setInput()`, which has a loop over all nodes in the computation graph to identify for which one the data is set.
This caused a big performance hit when instantiating likelihoods with the new vectorizing CPU backend, manifesting in 10 minutes for `createNLL` for the big ATLAS Higgs combination benchmark instead of 1 min.
This commit fixes the problem by caching all nodes in the compute graph in a hash map for fast lookup.

[RF] Avoid expensive double loop in `setData()` for likelihooods

---

tree/ntuple/inc/ROOT/RField.hxx
tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/src/RNTupleDescriptor.cxx
tree/ntuple/test/ntuple_compat.cxx

makes RNTupleDescriptor::CreateModel properly handle unknown column types.
- check all columns at the start of CreateModel to check for unknown column types. If any are found, we normally throw, but if ForwardCompatible is true we use the information to skip the invalid fields.
- improve the checks done in ntuple_compat to see that we're throwing for the right reason.
This PR fixes #19533

[ntuple] Properly handle unknown columns in CreateModel

---

bindings/pyroot/cppyy/cppyy/test/test_crossinheritance.py

This covers https://github.com/root-project/root/pull/16197, and having a unit test is a prerequisite for merging the fix upstream in CPyCppyy.
I verified locally that the added test is failing when reverting #16197.

[Python] Unit test for overriding C++ function returning `unsigned int`

---

.github/workflows/python_wheel_build.yml
bindings/pyroot/cppyy/CPyCppyy/CMakeLists.txt

I noticed the workflow is being skipped (e.g. https://github.com/root-project/root/actions/runs/16792883609). The gh UI doesn't say why. I have a suspicion that it is yet another undocumented behaviour. This commit suggests to add extra code to specify each and every  scenario where the workflow can run.
Even though it is redundant with the `on` section, it looks like this is the way to have the workflow properly run.

Add extra code to specify workflow conditions

---

tree/ntuple/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/test/ntuple_modelext.cxx

[ntuple] add test for model extension with streamer fields

---

io/xmlparser/src/TXMLParser.cxx

Some data members of the libxml2 context are deprecated, and instead one should change the options flag.
See:
* https://gnome.pages.gitlab.gnome.org/libxml2/html/parser_8h.html#a6ef6b5c034fb76b5091cd1cbe95f3029
* https://gnome.pages.gitlab.gnome.org/libxml2/html/parser_8h.html#a245dd5654f2c6538e305a1fb99766365
* https://gnome.pages.gitlab.gnome.org/libxml2/html/parser_8h.html#acf14c9a79459dbc52c8c986cffba536f
This commit fixes the following warnings:
```txt
/home/rembserj/code/root/root_src/io/xmlparser/src/TXMLParser.cxx: In member function ‘virtual void TXMLParser::InitializeContext()’:
/home/rembserj/code/root/root_src/io/xmlparser/src/TXMLParser.cxx:154:14: warning: ‘_xmlParserCtxt::linenumbers’ is deprecated [-Wdeprecated-declarations]
154 |    fContext->linenumbers = 1; // TRUE - …
```

Fix deprecation warnings in `TXMLParser.cxx`

---

tree/ntuple/inc/ROOT/RField.hxx
tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/src/RNTupleDescriptor.cxx
tree/ntuple/test/ntuple_compat.cxx

BP of https://github.com/root-project/root/pull/19536

[6.36][ntuple] properly handle unknown columns in CreateModel()

---

tutorials/CMakeLists.txt

* Disabling `exampleFit3D.C` tutorial for `NOT clad` is not needed anymore because #15091 was fixed.
* The `df107_SingleTopAnalysis.py` and `df103_NanoAODHiggsAnalysis.*` should now work on macOS too
* Disabling the `machine_learning/keras` tutorials was misleading because it suggested that these tutorials only fail on macOS, while they actually fail on on all platforms with TensorFlow>=2.16, which is why `tmva-pymva` was globally disabled in the CI and in the builds.

[tutorials] Remove vetos that are not needed anymore

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx

This also makes sure that the `string_view` converts to Python strings correctly.
Closes #19476.

[CPyCppyy] Add pythonizations for `string_view`

---

math/genvector/inc/Math/GenVector/LorentzVector.h

Fixes https://github.com/root-project/root/issues/19338
Fyi @Rik002

[math][genvector] Implement pair acoplanarity and asymmetry functions

---

math/genvector/inc/Math/GenVector/GenVector_exception.h
math/genvector/inc/Math/GenVector/LorentzVector.h
math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h
math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/GenVector/PxPyPzE4D.h
math/genvector/inc/Math/GenVector/PxPyPzM4D.h
math/genvector/inc/Math/GenVector/Rotation3D.h
math/genvector/inc/Math/GenVector/VectorUtil.h
math/genvector/src/Boost.cxx
math/genvector/src/BoostX.cxx
math/genvector/src/BoostY.cxx
math/genvector/src/BoostZ.cxx
math/genvector/src/LorentzRotation.cxx

With free functions being added to for the GenVector package in #19618, it will be a problem to find these functions in the ROOT documentation. This is because of a name clash between the GenVector namespace vs the GenVector doxygen group.
Doxygen links to the former, whereas the latter has all the documentation. Since the namespace was only wrapping the Throw function, GenVector::Throw can be replaced by GenVector_Throw, and the namespace can be removed. This should make the doxygen documentation more useful.

[math] Remove the GenVector namespace to improve doxygen.

---

tree/ntuple/inc/ROOT/RNTupleFillContext.hxx
tree/ntuple/inc/ROOT/RNTupleWriteOptions.hxx
tree/ntuple/inc/ROOT/RNTupleWriter.hxx
tree/ntuple/src/RNTupleParallelWriter.cxx
tree/ntuple/src/RNTupleWriter.cxx
tree/ntuple/test/ntuple_parallel_writer.cxx

Contrary to the (sequential) `RNTupleWriter`, it is off by default and has to be explicitly requested by the user. This avoids interference with explicit parallelism by increasing memory usage and additional memory copies that can result in overall worse performance.
Closes #18398
FYI @Dr15Jones

[ntuple] Allow usage of IMT with `RNTupleParallelWriter`

---

hist/hist/inc/TF1.h
hist/hist/src/TF1.cxx
hist/hist/test/CMakeLists.txt
hist/hist/test/test_tf1_drawcopy.cxx

TF1::Copy didn't copy fHistogram if it exited.
It fixes this issue: https://github.com/root-project/root/issues/13122

Fix TF1::DrawCopy issue

---

bindings/pyroot/cppyy/cppyy/python/cppyy/__init__.py
bindings/pyroot/pythonizations/python/ROOT/__init__.py
roottest/python/basic/CMakeLists.txt
roottest/python/cling/CMakeLists.txt
roottest/python/regression/CMakeLists.txt
roottest/root/meta/tclass/regression/CMakeLists.txt

Follows up on #19470, where the Python part of the cppyy backend was removed from ROOT. That means we should also not run the function in `cppyy` that tries to import it.
Also, any code that manipulates the `CLING_STANDARD_PCH` environment variable can be removed, as this variable was only relevant for the Python libs of the cppyy backend.
Closes #19505 and fixes `import cppyy` with ROOT master.

[Python] Remove all code related to `CLING_STANDARD_PCH` check

---

tutorials/machine_learning/RBatchGenerator_TensorFlow.py
tutorials/machine_learning/TMVA_CNN_Classification.py
tutorials/machine_learning/TMVA_RNN_Classification.py

TensorFlow has to be imported after ROOT to avoid LLVM symbol clashes if
ROOT was built with LLVM in Debug mode and TensorFlow>=2.20.0.

[tutorials] Don't import TensorFlow before ROOT

---

roofit/roofitcore/src/RooRealIntegral.cxx

Adding duplicates to a RooArgSet is intended in this case, profiting from the automatic de-duplication. But that means the duplicate errors should be suppressed with the "silent" flag.
Thanks to the following forum post for spotting this problem: https://root-forum.cern.ch/t/ownership-errors-generating-data-from-morphed-pdfs/64028

[RF] Don't warn about duplicates in temporary RooArgSet in RealIntegral

---

core/base/CMakeLists.txt
core/base/src/TROOT.cxx
core/unix/src/TUnixSystem.cxx

The problem with `TROOT::GetLibDir()` was that it either hardcodes the install directory inside it if `ROOTLIBDIR` was set (which is the case for `gnuinstall=ON`), or it assumes that it's always called `lib` and is inside the `$ROOTSYS`, which might or might not be set. This is broken if the `CMAKE_INSTALL_LIBDIR` is different from the default `lib`.
This commit suggests to automatically figure out the ROOT library directory instead.
Closes the following JIRA ticket:
https://its.cern.ch/jira/browse/ROOT-9569

[core] Generalize TROOT::GetLibDir()

---

.github/workflows/root-docs-ci.yml

On S3: Add option `--delete` to the `sync` command to remove files not present in the source
on EOS: before copying the new doc remove the old version of the doc to make sure the obsolete pages are removed. This is done using some tempory directory to avoid doc unavailibility.

[skip-ci] Make sure obsolete doc pages are not kept

---

roottest/root/tree/branches/CMakeLists.txt

Both roottest-root-tree-branches-abc_rflex and
roottest-root-tree-branches-abc_rflx-libgen-build were producing the file roottest/root/tree/branches/abc_rflx_rdict.pcm leading to a race condition leading to failure such as:
```
--- /github/home/ROOT-CI/src/roottest/root/tree/branches/abc.ref	Wed Aug 20 09:27:06 2025
+++ /github/home/ROOT-CI/build/roottest/root/tree/branches/abc-cint-reflex-read.log	Wed Aug 20 10:49:39 2025
@@ -1,4 +1,6 @@
+Error in <TFile::ReadBuffer>: error reading all requested bytes from file /github/home/ROOT-CI/build/roottest/root/tree/branches/abc_rflx_rdict.pcm, got 63 of 300
+Error in <TFile::Init>: /github/home/ROOT-CI/build/roottest/root/tree/branches/abc_rflx_rdict.pcm failed to read the file type data.
20: read d.abc==20, d.derived==19
40: read d.abc==40, …
```

roottest: root-tree-branch avoid output name clash.

---

CMakeLists.txt

The internet says that newer CMake versions got more reliable in figuring out the SDK path. So setting `CMAKE_OSX_SYSROOT` ourselves is maybe not needed anymore.
Follows up on #19218.

[CMake] Remove overriding `CMAKE_OSX_SYSROOT`

---

roofit/roofitcore/src/RooFormula.cxx
roofit/roofitcore/test/testRooFormula.cxx

As requested in #11992 changes the way RooFormulaVar performs variable names substitutions.
Before performing a substitution in the formula based on variable name, the code now checks if the variable to be substituted has a number as name. 
Variables where the name is a number are now only be matched by index. If there is a variable with a name that is a number that is not a RooConstVar where the value is equal to the name, an exception will be thrown. 
This PR fixes #11992

[RF] Handle variables having numeric value as name in RooFormula

---

roofit/codegen/src/CodegenImpl.cxx
roofit/roofit/inc/RooLagrangianMorphFunc.h
roofit/roofitcore/inc/RooFit/CodegenContext.h
roofit/roofitcore/inc/RooNumber.h
roofit/roofitcore/src/RooFit/CodegenContext.cxx
roofit/roofitcore/src/RooNumber.cxx
roofit/roofitcore/test/testRooFuncWrapper.cxx
tmva/tmva/inc/TMVA/DNN/GeneralLayer.h

By now, Clad should have learned how to deal with the `inf` infinities.
The unit tests are tweaked the check this.

[RF] Don't format infinities to large numbers anymore in `codegen`

---

bindings/pyroot/cppyy/cppyy/test/support.py
bindings/pyroot/cppyy/cppyy/test/test_operators.py
bindings/pyroot/cppyy/cppyy/test/test_stltypes.py
core/foundation/inc/ROOT/span.hxx

The `vector<T> const&` constructor needs to be disabled if T is not a const type, because we don't want to create `span<T>` from `vector<T> const&`. The explicit disabling via SFINAE is necessary to this overload is not accidentally taken by cppyy, resulting in the failure of constructor wrapper code compilation.
Avoids errors like these when compiling ROOT with C++17:
```txt
In module 'Core':
/home/rembserj/code/root/root_install/include/ROOT/span.hxx:208:27: error: cannot initialize a member subobject of type 'pointer' (aka 'double *') with an rvalue of type 'const double *'
: length_(v.size()), data_(v.empty() ? nullptr : v.data())
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
input_line_45:7:41: note: in instantiation of member function 'std::span<double>::span' requested here …
```

[core] Avoid errors when using std::span backport from Python

---

roottest/root/tree/array/execStdArray.C

see https://github.com/root-project/root/actions/runs/17157474273/job/48677881584?pr=19688
since TestObj.cpp creates same-named file in same directory.

[test] fix name conflict when multithreading

---

hist/hist/inc/TFormula.h
hist/hist/src/TFormula.cxx
test/TFormulaParsingTests.h

In #18194, an optional parameter to `TFormula::GetExpFormula()` was introduced, which can be used to customize the precision when putting parameters into the jitted code.
However, I don't see the reason why wouldn't like to always print the floating point numbers with maximum precision, which is suggested in this commit.
This is achieved using modern C++ functions, which are also not respecting the users locale setting, but instead use the classic C locale by default, which is what we need when generating code.
Follows up on #18194 (and its partial revert #18216).
Closes #17225.
Replaces #17327.

[hist] Always use maximum floating point precision in `GetExpFormula`

---

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py
bindings/pyroot/pythonizations/test/numbadeclare.py

This PR extends `Numba` support in the `@ROOT.Numba.Declare` decorator to ROOT C++ classes recognized by the `cppyy` `Numba` extension (see [cppyy docs](https://cppyy.readthedocs.io/en/latest/numba.html)).
- `Numba` can infer supported types automatically when using `@numba.jit(nopython=True)` without passing an explicit signature. Any class understood by cppyy’s Numba extension is now supported.
- For `numba.cfunc`, generating a native C callback for these classes fails. As a workaround, we manually create the C function using `ctypes.CFUNCTYPE` and pass its address to the C++ wrapper.
>[!WARNING]
> This is an experimental feature. It is still incomplete and has only been tested on Linux on x86_64.
> See https://cppyy.readthedocs.io/en/latest/numba.html#numba-support
```python …
```

[Python][RDF] Add support for (some) root classes in numba jitted functions

---

roofit/roofitcore/src/RooAbsPdf.cxx

This PR fixes an issue where the `plotOn` function incorrectly normalizes an extended PDF to the number of events in a dataset, rather than to its own predicted number of events. This behavior is misleading when the PDF's normalization is a key part of the model's prediction.
The default logic in `RooAbsPdf::plotOn` is modified to check if a PDF is extended by calling `expectedEvents()`. If it is, the function now uses the PDF's prediction for normalization; otherwise, it retains the old behavior of scaling to the data for non-extended PDFs.
I have verified this fix locally with several tests:
1.  **Reproducer Script:** Confirmed that for an extended PDF, the plotted curve is now normalized to the PDF's `expectedEvents()`.
```cpp
#include "RooRealVar.h"
#include "RooUniform.h"
#include …
```

RooFit: Fix plotOn normalization for extended PDFs

---

tree/ntuple/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/inc/ROOT/RNTupleRange.hxx
tree/ntuple/inc/ROOT/RNTupleReader.hxx

* Fix input iterators that cannot be forward iterators
* Implement `RFieldDescriptorIterable::operator->`
* Optimize `R{Cluster,ClusterGroup}DescriptorIterable`, `RExtraTypeInfoDescriptorIterable`
* Fix operators for descriptor iterators
More details in the individual commit messages.

[ntuple] Fixes to iterators

---

cmake/scripts/std_modulemap_darwin_fix.py

Note: this needs to be backported to 6.32 as well

[build] Fix script for conda MacOS

---

roofit/roofitcore/src/RooWorkspace.cxx

Fixes https://github.com/root-project/root/issues/19770

[RF] proper error handling and return value when file-write

---

roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx

Currently, the documentation seems to show an empty section, since a section title is followed by a \see command, which generates its own section.
It's better to replace it by the plain word "See xxx".
See the second section [here](https://root.cern/doc/master/classRooDataHist.html):

[RF][Docs] Remove a \see in the RooDataHist/Set documentation.

---

roottest/root/meta/genreflex/ROOT-5768/PyCool.h

explore https://github.com/root-project/root/pull/19721#issuecomment-3241839961

[test] remove no longer needed workaround

---

tmva/sofie/inc/TMVA/ROperator_Softmax.hxx

An optimized code path has been added for the common case where the Softmax axis is the last dimension (axis == size - 1).

[tmva][sofie] Softmax contiguous memory fast path

---

CMakeLists.txt
cmake/modules/SetUpFreeBSD.cmake
cmake/modules/SetUpLinux.cmake

* `SearchInstalledSoftware` before adding linker flags, to avoid interference with `-z undefs`
* Look for new `libclang_rt.asan.so` in architecture dependent directory

[CMake] Fix `asan` builds with Clang

---

hist/histv7/benchmark/CMakeLists.txt
hist/histv7/benchmark/hist_benchmark_engine.cxx
hist/histv7/doc/DesignImplementation.md
hist/histv7/headers.cmake
hist/histv7/inc/LinkDef.h
hist/histv7/inc/ROOT/RAxes.hxx
hist/histv7/inc/ROOT/RHistEngine.hxx
hist/histv7/test/CMakeLists.txt
hist/histv7/test/hist_axes.cxx
hist/histv7/test/hist_engine.cxx
hist/histv7/test/hist_io.cxx
hist/histv7/test/hist_test.hxx

It combines an `RAxes` object and storage of bin contents.

[hist] Implement initial `RHistEngine`

---

roofit/roofitcore/src/RooAbsReal.cxx

As already done in RooAbsReal::moment (followed the same format)
Fixes https://github.com/root-project/root/issues/19820
Please squash-on-merge

[RF] avoid WS name collision between derivatives of different order

---

gui/treemap/CMakeLists.txt
gui/treemap/inc/LinkDef.h
gui/treemap/inc/ROOT/RTreeMapBase.hxx
gui/treemap/inc/ROOT/RTreeMapPainter.hxx
gui/treemap/src/RTreeMapBase.cxx
gui/treemap/src/RTreeMapImporter.cxx
gui/treemap/src/RTreeMapPainter.cxx

This PR adds a new directory `treemap` in `/gui/` with the following features:
- Logic for generating treemap
- [Squarification algorithm](https://vanwijk.win.tue.nl/stm.pdf) is used
- Drawing a treemap on a `TVirtualPad`
- This is the non-interactive version without web graphics (interactive JS treemaps will be in a separate PR)
- Importing the treemap given an RNTuple
- `CMakeLists.txt` that makes this a root library `ROOTTreeMap`
- Should this be renamed to `ROOTTreeMapv7`?
- Should this file be moved to a separate "CMake integration" PR?
- `LinkDef.h` so that the treemap structure can be encoded to JSON for use in JS

[gui] Add RTreeMap

---

graf2d/gpad/src/TRatioPlot.cxx

In the `TRatioPlot(TH1 *h1, THStack *st, Option_t *option)` constructor the internal variable `fHistDrawProxy` was not set correctly.
This problem was seen ihere https://github.com/root-project/root/issues/19776

Fix the (TH1*, THStack*) ctor

---

roofit/roofitcore/src/RooLinkedList.cxx

Thanks to #7818, where the `RooHashTable` was migrated to `std::unordered_map`, we can now use proper `reserve()` functions to increase the hash table size when adding elements.
The current mechanism deleting and recreating the hash tables from scratch when the list size changed incurred a pretty large overhead. In fact, it made adding to the list a `O(n)` operation, because it has to iterate over the collection to fill the hash table again. Consequently, copying a `RooLinkedList` was `O(n^2)`, which is unexpected to the user.
This change will speed up the handling of objects in a RooWorkspace, which uses `RooLinkedLists` to manage the elemens.
Taken from #19459 to be merged before, because this is in principle independent of the RooWorkspace developments.

[RF] Don't recreate hash tables in `RooLinkedList::Add()`

---

tree/tree/inc/TTree.h
tree/tree/inc/TVirtualTreePlayer.h
tree/tree/src/TTree.cxx
tree/treeplayer/inc/TChainIndex.h
tree/treeplayer/inc/TTreeIndex.h
tree/treeplayer/inc/TTreePlayer.h
tree/treeplayer/src/TChainIndex.cxx
tree/treeplayer/src/TTreeIndex.cxx
tree/treeplayer/src/TTreePlayer.cxx

as requested by ATLAS
BP of https://github.com/root-project/root/pull/19625

[632][tree] Allow skipping longdoubles when building tree index

---

tree/ntuple/inc/ROOT/RNTupleRange.hxx
tree/ntuple/inc/ROOT/RNTupleView.hxx

[v6.36] fixes for RNTuple views

---

core/base/src/root-argparse.py

The description was trying to refer to a website but no URL was there. The message was also compactified a bit to save vertical space.

[main] Fix a bit help message of root.

---

roottest/root/meta/autoloading/CMakeLists.txt
roottest/root/meta/autoloading/MissingEntriesROOT-5759.ref

This test can be fragile, after removing this [snippet](https://github.com/root-project/root/pull/19672/files#diff-170f7f5b5ea149128527bc143d6aa35b3c6264650b2b6bd9e6968e2cb905b16dL69-L73)
```
MissingEntriesROOT-5759.log: FullMissingEntriesROOT-5759.log
$(CMDECHO) cat FullMissingEntriesROOT-5759.log |sed 's/input_line_[0-9]*://g' > MissingEntriesROOT-5759.log 2>&1
```
This can result in a different line number based on the platform or simply adding/removing `-e '#define ANYTHING'`
See this [failing](https://github.com/root-project/root/actions/runs/17575584191/job/49919975307#step:11:15458) test. Simply having a different set of `#define`s can break this test.
This patch restores the previous behaviour.

[roottest] Make `MissingEntriesROOT-5759` test stable

---

net/http/inc/THttpCallArg.h
net/http/inc/THttpServer.h
net/http/src/TCivetweb.cxx
net/http/src/THttpCallArg.cxx
net/http/src/THttpServer.cxx
tutorials/http/httpchunked.C

These are very special requests when http reply returned not as single buffer
but rather as chunks of many smaller buffers.
This allow to send huge amount of data with single reply - without need of allocate all such memory at once.
Do not used in normal THttpServer requests processing.
Provide `httpchunked.C` tutorial showing usage of such requests.

[http] implement chunked requests

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
core/clingutils/src/TClingUtils.cxx
core/dictgen/src/rootcling_impl.cxx
core/foundation/src/FoundationUtils.cxx
core/metacling/src/TCling.cxx
core/rootcling_stage1/src/rootcling_stage1.cxx
core/textinput/src/textinput/TerminalDisplayUnix.cpp
core/unix/src/TUnixSystem.cxx
core/winnt/src/TWinNTSystem.cxx
documentation/doxygen/filter.cxx
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/DynamicLibraryManager.cpp
interpreter/cling/lib/UserInterface/UserInterface.cpp
interpreter/cling/lib/Utils/Paths.cpp
interpreter/cling/lib/Utils/PlatformWin.cpp
interpreter/cling/lib/Utils/UTF8.cpp
interpreter/cling/test/Pragmas/add_env_path.C
interpreter/cling/tools/driver/cling.cpp
main/src/rmain.cxx
net/davix/src/TDavixFile.cxx
net/rpdutils/src/rpdutils.cxx
roottest/root/meta/genreflex/ROOT-5768/RelationalCool/tests/Common/CoolDBUnitTest.h
roottest/scripts/pt_collector.cpp
roottest/scripts/pt_mymalloc.cpp
rootx/src/rootx.cxx
test/MainEvent.cxx
tmva/tmvagui/src/tmvaglob.cxx
tutorials/legacy/rootalias.C

Fixes https://github.com/root-project/root/issues/19850

[core] fix getenv namespace error with libc++

---

config/mimes.unix.in
config/mimes.win32.in
tree/ntuplebrowse/CMakeLists.txt
tree/ntuplebrowse/src/RNTupleClassicBrowse.cxx
tree/ntuplebrowse/test/ntuple_browse.cxx

- Add the icon for RNTuple-visualization node in `config/mimes.unix.in` and `config/mimes.win32.in`
- Visualization node represented by `RVisualizationBrowsable` class, which visualizes the corresponding ntuple on click as a treemap
- Use RTreeMap classes from included `ROOTTreeMap` module for treemap visualization
- Adapting the `ntuple_browse` test to the changes

[ntuplebrowse] Add treemap visualization in classic ntuplebrowser

---

math/mathcore/doc/index.md
math/mathcore/inc/Math/Integrator.h
math/mathcore/inc/Math/Math.h
math/mathcore/inc/Math/PdfFuncMathCore.h
math/mathcore/inc/Math/SpecFuncMathCore.h
math/mathmore/doc/index.md
math/mathmore/inc/Math/QuasiRandom.h

Since the documentation of both math groups share the same subgroups, doxygen fails to create a stable index that can be navigated. One gets thrown around between MathCore and MathMore in an unpredictable way. Here, groups such as probability density functions and smiliar are only listed in MathCore, and MathMore is moved as a subgroup into MathCore.
It is explained what MathMore is, how it can be (de-)activated, and why it's separate from MathCore.
Fix #7440

[docs] Merge documentation of MathMore and MathCore.

---

tree/dataframe/src/RDataFrame.cxx

The RDataFrame documentation page incorrectly guides to use `ROOT::Experimental::RLogScopedVerbosity` when the correct namespace in recent versions is `ROOT::RLogScopedVerbosity`.
Related: fcbf76c
Note: I haven't built root using this change as no code has been modified

[Docs][df] Remove Experimental scope from RLogScopedVerbosity usage

---

cmake/modules/RootMacros.cmake
roottest/scripts/build.C

Instead of running the `root ... <macro>.C+` build step as the command
associated with a custom CMake target, just run the command directly in
the test added with `add_test`.
This simplification is possible because for the custom CMake target, no
dependencies are ever specified. This makes building it not different
from just running the underlying command directly.
Do some further CMake code simplifications in a second commit (more detail in the commit description).

[CMake] Don't wrap command in `ROOTTEST_COMPILE_MACRO` in CMake target

---

roottest/root/io/references/CMakeLists.txt

Macro lostRef.C updates file several times,
so one only can execute it sequntially

[roottest] add missing dependency to io-references-lostRef test

---

tree/dataframe/inc/ROOT/RDF/RInterface.hxx

Reply to https://root-forum.cern.ch/t/increase-accuracy-of-leaves-when-using-rdataframe-mean/64130/5

[RDF][Docs] Explain that RDF uses Kahan sums for the mean.

---

builtins/nlohmann/json.hpp

This gets rid of the deprecation warning about `operator ""`

[builtins] Update nlohmann::json from 3.10.5 to 3.12.0

---

roofit/roofitcore/inc/RooAbsData.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooDataSet.h
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx

This PR refactors and improves the dataset printing functionality in RooFit. The previous `RooDataHist::printDataHistogram` function was limited to 1D, had a redundant interface, and was not consistently available for all dataset types.
This contribution addresses these issues by:
1.  Renaming the function to the more general `printContents()`.
2.  Moving the function's interface to the `RooAbsData` base class as a pure virtual function, ensuring all future dataset types must implement it.
3.  Providing a new, robust implementation for both `RooDataHist` and `RooDataSet`.
4.  The new implementation is now fully multi-dimensional and correctly handles mixed data types (`RooRealVar`, `RooCategory`).
The new feature was validated with a comprehensive local test. This script confirms that the …

[RF] Add and refactor printContents() for RooAbsData

---

cmake/modules/RootConfiguration.cmake
geom/CMakeLists.txt

[CMake] Avoid installing unneeded files with `gnuinstall=OFF`

---

gui/webdisplay/src/RWebDisplayHandle.cxx
js/files/canv_batch.htm

With chrome and firefox browser one can use screenshot functionality.
It activated when canvas stored in file like `file.screenshot.png` or `file.screenshot.pdf`
In such case --screenshot arg add to args
Problem appeared when `fork:` start to be used for batch jobs. 
In such case screenshot does not appears immedeately but with some timeout.
Now this handled correctly - ROOT will wait some time for it.
Also repair handling of screenshot in firefox - extra args were not handled properly.
Correctly delete HTML file only after browser processing really finished.

[webgui] fix screenshot functionality

---

cmake/modules/RootMacros.cmake

Add a dummy preprocessor macro that includes the `CMAKE_CXX_STANDARD` in the name to the dictionary generation command. This forces rebuilding the dictionaries when the C++ standard is changed in incremental builds.
Closes #8642.

[CMake] Make dictionary generation command depend on C++ standard

---

roottest/root/tree/chain/execChainElementStatus.C
tree/tree/src/TChain.cxx
tree/tree/src/TChainElement.cxx
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/test/regressions.cxx

Fixes #19814 and also the recent CI failures such as https://github.com/root-project/root/actions/runs/17610706130/job/50031825233?pr=19860#step:6:4762
The second commit contains the main change: reworking the `TChain::GetEntries` method. The issue with it was that it was causing one side-effect too many: the last opened file was not being properly closed. This in turn triggered the if condition in `TTreeReader::Restart` and the segfaults due to bad memory accesses. This is an alternative solution to https://github.com/root-project/root/pull/19866 . The advantage IMHO is that it requires changing fewer places and better conveys the intent of the method: a for loop opening the files as opposed to calling LoadTree until all files have been opened. On top of course of having far less …

Rework TChain::GetEntries to avoid side-effects 

---

tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/test/CustomStruct.hxx
tree/ntuple/test/CustomStructLinkDef.h
tree/ntuple/test/ntuple_types.cxx

Enables bool as an underlying type for custom enums, which was previously overlooked.
Follow-up of #19907

[ntuple] fix bool-backed enums

---

CMakeLists.txt
core/metacling/src/CMakeLists.txt
interpreter/CMakeLists.txt

Cached variables end up in `root-config --config`, and we don't want to have absolute paths to the bulid directory inside its output.
After this change, no trace of the full ROOT source or build directory path is left in the output of `root-config --config`.
Closes https://its.cern.ch/jira/browse/ROOT-9481

[CMake] Don't cache `CPPINTEROP_INCLUDE_DIRS` and `CLING_INCLUDE_DIRS`

---

tree/ntuple/inc/ROOT/RField/RFieldProxiedCollection.hxx
tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntuple/test/ntuple_emulated.cxx

Several collection fields still had a public GetCollectionInfo() method. It was an oversight not to remove them earlier. These methods are unneeded and potentially dangerous to expose.

[ntuple] remove GetCollectionInfo() from collection fields

---

core/metacling/src/CMakeLists.txt
interpreter/CMakeLists.txt

The code was in `interpreter/CMakeLists.txt`, but the definition of libCling is in `core/metacling`. After moving, symbols are correctly resolved by the linker and not anymore during dynamic loading.
Fixes #19889

[core] Fix libCling linking with `-Bsymbolic`

---

CMakeLists.txt
cmake/modules/RootMacros.cmake
cmake/unix/module.modulemap

Instead of a two-step process that writes the dynamic contents at CMake configure time, and a build-time step that concatenates the static and dynamic part of the modulemap, CMake's configure_file is used to directly write the full contents at configure time.
This is carrying the simplifications in #19786 even further.

[CMake] Simplify writing of modulemap.

---

tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/inc/ROOT/RField.hxx
tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/inc/ROOT/RFieldBase.hxx
tree/ntuple/inc/ROOT/RNTupleReader.hxx
tree/ntuple/inc/ROOT/RNTupleView.hxx
tree/ntuple/src/RField.cxx
tree/ntuple/src/RFieldBase.cxx
tree/ntuple/src/RFieldMeta.cxx
tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntuple/src/RNTupleProcessor.cxx
tree/ntuple/src/RNTupleReader.cxx
tree/ntuple/test/CMakeLists.txt
tree/ntuple/test/ntuple_evolution_shape.cxx
tree/ntuple/test/ntuple_evolution_type.cxx
tree/ntuple/test/ntuple_largevector.cxx

In contrast to other automatic evolution mechanisms, this one cannot use `ReconcileOnDiskField()` because for proper support the type of the field itself must change. In principle, we could stuff all the logic into RRecField, but it would be quite messy. We also discussed adding a "virtual column" for the fixed-size indexes; this doesn't work, however, because the index column stores offsets and not vector lengths, and it is also used to translate between global and local indexing.
Thus, this PR adds the infrastructure to replace fields of just created field hierarchies (models). This is legit as long as the fields weren't exposed to the user yet, where the user, e.g., could have already created entries. As a result, the automatic evolution from fixed-size to RVec (and later std::vector) …

[ntuple] automatic evolution from fixed-size array to RVec

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py
io/io/inc/TBufferJSON.h
io/io/src/TBufferJSON.cxx
js/changes.md
js/modules/base/BasePainter.mjs
js/modules/base/latex.mjs
js/modules/core.mjs
js/modules/draw/RTreeMapTooltip.mjs
js/modules/gpad/TPadPainter.mjs
js/modules/hist2d/TGraphPainter.mjs
js/modules/hist2d/TScatterPainter.mjs
js/modules/io.mjs
js/modules/main.mjs

Up to now plain json code embed into ipython notebooks.
This is very inefficient and can make notebook huge.
Especially because of fact that notebook stored as json - so any double-quote `"` symbol should be escaped.
Therefore use standard compression function of ROOT and then base64 encoding to produce string suitable for embeding. This done in `TBufferJSON::zipJSON()` method.
On JSROOT side just provide correspondent `unzipJSON()` function.
And modify jupyter `utils.py` code to use such functionality.

[jupyter] use zipping for stored json

---

roottest/root/tree/stl/CMakeLists.txt
roottest/root/tree/stl/execPartialMap.cxx
roottest/root/tree/stl/execPartialMap.ref
tree/tree/src/TBranchElement.cxx

TTree: Prevent access to already deleted scratch area

---

tree/ntuple/inc/ROOT/RField/RFieldSequenceContainer.hxx
tree/ntuple/inc/ROOT/RNTupleTypes.hxx
tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntuple/test/ntuple_bulk.cxx

[ntuple] Optimize bulk read for (RVec of) array of PoD

---

tree/ntuple/test/CustomStruct.hxx
tree/ntuple/test/CustomStructLinkDef.h
tree/ntuple/test/ntuple_evolution_type.cxx

Mirrors classic I/O. Eventually, we may want to take a safer approach and look if the two enums are compatible (to be defined) or if there is an explicit rename rule.

[ntuple] test automatic schema evolution between enums

---

gui/browserv7/inc/ROOT/RBrowser.hxx
gui/browserv7/src/RBrowser.cxx
gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webdisplay/src/RWebWindow.cxx
gui/webdisplay/src/RWebWindowsManager.cxx

`RWebWindow::ClearOnClose` let destroy handle when all connections are closed by widget - or when widget is destroyed.
But if pending connection is not reconnected and finally removed, `ClearOnClose` was not emptied. 
Therefore add such check when pending connections processed.
Add separate timeout for reconnecting of pending connections.
Default is 15 seconds - while in such case browser process already exists and only JavaScript has to be reinitialized.
Can be changed via ` WebGui.ReconnectTmout` rootrc parameter.
If such timeout zero or negative - connection is not possible to reconnect.

[webgui] handle ClearOnClose for pending connections

---

core/metacling/src/CMakeLists.txt
interpreter/CMakeLists.txt

The code was in `interpreter/CMakeLists.txt`, but the definition of libCling is in `core/metacling`. After moving, symbols are correctly resolved by the linker and not anymore during dynamic loading.
Fixes #19889, backport of https://github.com/root-project/root/pull/19953
(cherry picked from commit db22551bd064f4911c906e6e5816692e9cf971d3)

[core] Fix libCling linking with `-Bsymbolic` [v6.32]

---

gui/browsable/CMakeLists.txt
tutorials/CMakeLists.txt

* Always compile RNTuple providers
* Simplify ROOT 7 vetos

More updates after moving RNTuple from `root7` flag

---

core/metacling/src/CMakeLists.txt
core/metacling/src/libCling.script

We already use `-fvisibility=hidden` and `-fvisibility-inlines-hidden` to generate symbols that are not exported from the shared object. However, these two options don't apply for non-inline template instantiations, which can still cause problems when a STL container is instantiated with an LLVM type that may change size between LLVM versions.
Related to https://github.com/root-project/root/issues/19889

[core] Use version script to hide symbols in libCling

---

tree/ntuple/src/RPageStorageFile.cxx
tree/ntuple/test/ntuple_storage.cxx

The previous code would always set the name to the empty string as the descriptor builder was not initialized yet by that point.

[ntuple] Properly set the NTupleName in sources created from anchors

---

interpreter/CMakeLists.txt
interpreter/CppInterOp/unittests/CMakeLists.txt

With llvm's include(Googletest), CppInterOp might download its own
googletest, ignoring the system installation. This created several
problems:
- An existing system installation might be ignored.
- When used in ROOT with builtin gtest, a conflicting gtest might be
downloaded.
- When ROOT is configured with fail-on-missing while offline, the
configuration fails, because it is assumed that gtest needs to be
downloaded. This is not the case, though, if gtest is present in the
system.
Therefore:
- Test if the targets GTest::gtest or gtest exist. If found, no further
actions are required.
- New: If not found, run find_package(GTest). If found, continue as normal.
- New: If not found, warn and disable the interop tests.
With the above, the logic in ROOT can be simplified:
- ROOT switches On/Off …

[InterOp] Fix a build failure when configuring offline

---

hist/histv7/benchmark/CMakeLists.txt
hist/histv7/benchmark/hist_benchmark_stats.cxx
hist/histv7/headers.cmake
hist/histv7/inc/LinkDef.h
hist/histv7/inc/ROOT/RHistStats.hxx
hist/histv7/test/CMakeLists.txt
hist/histv7/test/hist_io.cxx
hist/histv7/test/hist_stats.cxx
hist/histv7/test/hist_test.hxx

Histogram statistics of unbinned values to compute the number of effective entries as well as the arithmetic mean and other statistical quantities per dimension.

[hist] Implement `RHistStats`

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/uhi_test_suite.py

- This PR integrates the [UHI indexing test suite](https://uhi.readthedocs.io/en/latest/testing.html) for ROOT histograms by adding `Indexing1D`,  `Indexing2D` and `Indexing3D` test helpers specialized for `ROOT.TH1` histograms.
- For all tests to pass, a temporary equality patch (`__eq__)` for `ROOT.TH1` within the test context is implemented checking histogram values instead of default object identity.
- Since serialization is not yet implemented, the histograms are manually created and set in `make_histogram`.

[Python][UHI] Integrate the UHI testing suite

---

README/ReleaseNotes/v638/index.md
math/mathcore/inc/Math/Minimizer.h
math/mathcore/src/FitResult.cxx
math/mathcore/src/Minimizer.cxx
math/minuit/inc/TMinuitMinimizer.h
math/minuit/src/TMinuitMinimizer.cxx
math/minuit2/inc/Minuit2/Minuit2Minimizer.h
math/minuit2/inc/Minuit2/MnUserParameterState.h
math/minuit2/src/Minuit2Minimizer.cxx
math/minuit2/src/MnPrint.cxx
math/minuit2/src/MnUserParameterState.cxx
roofit/roofitcore/src/RooMinimizer.cxx

The function `double ROOT::Math::Minimizer::GlobalCC(unsigned int ivar)` was changed to `std::vector<double> ROOT::Math::Minimizer::GlobalCC()`, always returning the full list of global correlations.
This change was needed because global correlations are not unconditionally computed and cached in the minimizer anymore. Only computing them when calling `GlobalCC()` avoids unneeded overhead when global correlations are not required.

[Minuit2] Only compute global correlation matrix when needed

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/th2.py
bindings/pyroot/pythonizations/test/th3.py
hist/hist/inc/TH2.h
hist/hist/inc/TH3.h

The operators for `TH2*` and `TH3*` were declared only as friend functions inside the class, without matching free-function declarations in the header, which prevented them from being picked up in [BuildScopeProxyDict](https://github.com/root-project/root/blob/4157d78bbce6a6e4b1147c71addefabf802ab7b6/bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx#L175-L206) and therefore could not be exposed in Python.
This PR adds the missing free-function declarations for `TH2*`  and `TH3*` operators ensuring that the proper Python bindings are generated.
This PR fixes #20014

Fix TH2 and TH3 arithmetic operators in Python

---

tree/ntuple/test/ntuple_show.cxx

Remove a left-over test, now doing nothing, from the time where the friends functionality was implemented by a virtual page source.

[ntuple] remove unused test

---

roofit/roofitcore/src/RooProdPdf.cxx

After getting confused for some time why some fits don't work with the new CPU backend, I found one of the problems: the `std::ostringstream` was used incorrectly since 916a180 (commit from 10 years ago).
The `std::ostringstream` constructor arguments do not initialize the stream with that string — the argument sets the open mode, not the contents.
This can be seen with this little example in the interpreter.
```txt
root [0] const char *pfx = "hello";
root [1] std::ostringstream os(pfx);
root [2] os << " world";
root [3] os.str()
(std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::__string_type) " world"
root [4] .q
```
The result is that the prefix doesn't get added, and hence it can happen that many nodes in the computation graph can have the same name, …

[RF] Fix wrong usage of `std::ostringstream` in RooProdPdf

---

roofit/codegen/src/CodegenImpl.cxx
roofit/roofitcore/inc/RooProdPdf.h
roofit/roofitcore/src/RooProdPdf.cxx

The RooFixedProdPdf used an antipattern that should be avoided, and it was actually causing some problems in fits with the new CPU evaluation backend.
The problem was that the class held on to some RooAbsArgs for its evaluation in some containers that were separate from RooFit server-client interface (the container was the
`std::unique_ptr<RooProdPdf::CacheElem>`).
This commit fixes the situation by avoiding this cache element member completely and consistently using the server proxies instead.

[RF] Avoid compute graph desync in RooFixedProdPdf

---

roofit/roofitcore/inc/RooNumRunningInt.h
roofit/roofitcore/src/RooNumRunningInt.cxx

Fixes this error when using the RooNumRunningInt class:
```
what():  calling RooAbsReal::getVal() with r-value references to the
normalization set is not allowed, because it breaks RooFits caching
logic and potentially introduces significant overhead. Please
explicitly create the RooArgSet outside the call to getVal().
```

[RF] Avoid implicit creation of normalization set in RooNumRunningInt

---

roofit/histfactory/test/stressHistFactory.cxx

Since 6ff6266, Minuit 2 is always build with ROOT, so the fallback to the old Minuit in stressHistFactory has no effect.

[RF] Remove fallback to Minuit 1 in stressHistFactory

---

graf2d/graf/src/TTF.cxx

See https://root-forum.cern.ch/t/compilation-error-due-to-font-not-found-in-path/64260

[graf] more informative error message

---

tree/ntuple/src/RFieldSequenceContainer.cxx
tree/ntupleutil/v7/src/RNTupleImporter.cxx

Collection items must have "_0" as item field name, which can be violated in RVectorField::CreateUntyped().
(cherry picked from commit 2f8d30d048dd9cfc2393241b54e50fce685273f0)
Backport from #20007

[v6.36][ntuple] enforce correct subfield name in untyped collection

---

hist/histv7/benchmark/hist_benchmark_axes.cxx
hist/histv7/benchmark/hist_benchmark_engine.cxx
hist/histv7/benchmark/hist_benchmark_regular.cxx
hist/histv7/inc/ROOT/RHist.hxx
hist/histv7/inc/ROOT/RHistEngine.hxx
hist/histv7/inc/ROOT/RRegularAxis.hxx
hist/histv7/test/hist_axes.cxx
hist/histv7/test/hist_engine.cxx
hist/histv7/test/hist_hist.cxx
hist/histv7/test/hist_io.cxx
hist/histv7/test/hist_regular.cxx
tutorials/hist/histv7/hist001_RHist_basics.C

This forces the user to make a distinction between the number of bins and the axis interval.

[hist] Accept regular axis interval as `std::pair`
