tmva/pymva/inc/TMVA/MethodPyKeras.h

Minor fixes in comments to MethodPyKeras.h include file.

[TMVA] Fix PyKeras comments

---

interpreter/cling/include/cling/libc.modulemap
interpreter/cling/include/cling/libc_msvc.modulemap
interpreter/cling/include/cling/std.modulemap
interpreter/cling/include/cling/std_msvc.modulemap
interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/llvm/src/tools/clang/docs/Modules.rst
interpreter/llvm/src/tools/clang/lib/Basic/Module.cpp

This PR should unblock the progress made in #5284

[wincxxmodules] Backport D51910 and add stub windows modulemaps

---

tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_concurrency.cxx

...and add a test. This fixes ROOT-10346.

[DF] Throw if thread pool size changed after RDF construction

---

core/metacling/src/TClingDataMemberInfo.cxx
core/metacling/src/TClingDataMemberInfo.h
core/metacling/src/TClingDeclInfo.cxx
core/metacling/src/TClingDeclInfo.h
core/metacling/src/TClingMethodInfo.cxx
core/metacling/src/TClingMethodInfo.h
core/metacling/src/TClingTypeInfo.cxx
core/metacling/src/TClingTypeInfo.h
core/metacling/src/TClingTypedefInfo.cxx
core/metacling/src/TClingTypedefInfo.h

[metacling]Refactor Property into base class by passing reference

---

roofit/roofit/src/RooFunctorBinding.cxx
roofit/roofitcore/inc/RooRecursiveFraction.h
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooAddModel.cxx
roofit/roofitcore/src/RooAddPdf.cxx
roofit/roofitcore/src/RooFactoryWSTool.cxx
roofit/roofitcore/src/RooRealVar.cxx
roofit/roofitcore/src/RooRecursiveFraction.cxx
roofit/roofitcore/src/RooWorkspace.cxx
tutorials/roofit/rf212_plottingInRanges_blinding.C

Documentation updates and sometimes also code changes that e.g. format warning messages or replace ineffective `assert`s by `throw`s.

[RF] Documentation updates, improvement of warning and error messages

---

tmva/tmva/test/DNN/GRU/TestGRUForwardPass.h
tmva/tmva/test/DNN/GRU/TestGRUForwardPassCpu.cxx
tmva/tmva/test/DNN/LSTM/TestLSTMForwardPass.h
tmva/tmva/test/DNN/LSTM/TestLSTMForwardPassCpu.cxx
tmva/tmva/test/DNN/RNN/TestRecurrentForwardPassCpu.cxx

Improve and fix rnn forward tests for simple RNN cells and GRU
This commit fixes a failure observed in incremental builds with debug mode

Fix test failures observed in TMVA for DNN/GRU

---

core/dictgen/src/rootcling_impl.cxx

Fixes failing clang-tidy travis instance
@vgvassilev

[rootcling]Simplify dictionary stream splitting logic

---

core/dictgen/src/rootcling_impl.cxx

This is an urgent fix to adjust root-project/root@c7ca01f to root-project/root@6b70c86

Fix compilation error due to a change merged before.

---

tutorials/roofit/rf502_wspacewrite.py
tutorials/roofit/rf504_simwstool.py
tutorials/roofit/rf509_wsinteractive.py
tutorials/roofit/rf511_wsfactory_basic.py

Replay 710a13e7b659ecc2eec11d635a512859c9055dca,
which got lost in 8c64905e0a12e577eac23ee61323d3736999bef3.

[Exp PyROOT] Replay "Use pythonised RooWorkspace.Import() in tutorials."

---

bindings/jupyroot/CMakeLists.txt
bindings/pyroot_experimental/cppyy/CPyCppyy/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy-backend/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy/CMakeLists.txt
bindings/pyroot_experimental/pythonizations/CMakeLists.txt

This fixes:
- The installation of `libJupyROOTX_Y`
- The compilation, at installation time, of the Python source files of the various PyROOT packages

[Exp PyROOT] Fixes for installation of PyROOT packages

---

README/CREDITS

Non ascii characters in CREDITS pollute the splash screen as said in this
ticket https://sft.its.cern.ch/jira/browse/ROOT-10684

Avoid non ASCII characters in CREDITS

---

core/dictgen/src/rootcling_impl.cxx

cc: @oshadura, @davidlange6, @smuzaffar

[rootcling] Convert diagnostic to a proper rootcling error.

---

geom/gdml/inc/TGDMLWrite.h
geom/gdml/src/TGDMLParse.cxx
geom/gdml/src/TGDMLWrite.cxx
geom/geom/src/TGeoManager.cxx
graf2d/graf/src/TGaxis.cxx
graf2d/graf/src/TMarker.cxx
graf3d/eve/inc/TEveStraightLineSet.h
graf3d/eve/src/TEveCaloVizEditor.cxx
graf3d/eve/src/TEveParamList.cxx
graf3d/eve/src/TEveTrackPropagatorEditor.cxx
graf3d/g3d/src/TAxis3D.cxx
graf3d/gl/src/TGLAxisPainter.cxx
graf3d/gl/src/TGLPShapeObjEditor.cxx
graf3d/gl/src/TGLPadPainter.cxx
graf3d/gl/src/TGLParametric.cxx
graf3d/gl/src/TGLSAViewer.cxx
graf3d/gl/src/TGLViewer.cxx
gui/fitpanel/src/TFitEditor.cxx
gui/ged/src/TAttMarkerEditor.cxx
gui/ged/src/TPieEditor.cxx
gui/gui/src/TGCanvas.cxx
gui/gui/src/TRootContextMenu.cxx
gui/guibuilder/src/TGuiBldDragManager.cxx
gui/sessionviewer/src/TSessionDialogs.cxx
gui/sessionviewer/src/TSessionViewer.cxx
net/http/src/THttpServer.cxx
proof/proof/src/TDSet.cxx
proof/proof/src/TProofServ.cxx
proof/proofbench/src/TProofBenchRunCPU.cxx
proof/proofplayer/src/TProofPlayer.cxx

Just remove line where same include appears second time

Remove duplicated includes in gui/graf2d/graf3d/geom/proof classes

---

tree/dataframe/src/RArrowDS.cxx
tree/dataframe/test/datasource_arrow.cxx

[DF] Do not use C++14 in RArrowDS

---

gui/webdisplay/src/RWebDisplayHandle.cxx

On some systems (CentOS 8) latest chrome not allows to run HTML files,
which are situated in /tmp directory. Only if such situation detected,
try to place HTML files into home directory and run headless chrome from such file
Fixes problem like this:
https://lcgapp-services.cern.ch/root-jenkins/job/root-nightly-master/LABEL=ROOT-ubuntu2004,SPEC=cxx17,V=master/2435/testReport/projectroot/runtutorials/tutorial_v7_line_cxx/

[webgui] provide fallback solution when chrome not run with files from tmp

---

hist/hist/src/TBinomialEfficiencyFitter.cxx
hist/histpainter/src/THistPainter.cxx
hist/unfold/inc/TUnfoldBinningXML.h
math/genvector/inc/Math/GenVector/CylindricalEta3D.h
math/genvector/src/AxisAngleXother.cxx
math/genvector/src/EulerAngles.cxx
math/genvector/src/Quaternion.cxx
math/genvector/src/RotationZYX.cxx
math/genvector/test/testGenVector.cxx
math/genvector/test/testIterator.cxx
math/mathmore/inc/Math/GSLMCIntegrator.h
math/mathmore/src/Polynomial.cxx
math/mathmore/test/VavilovTest.cxx
math/mathmore/test/testMCIntegration.cxx
math/minuit2/src/FumiliMinimizer.cxx
math/minuit2/src/Minuit2Minimizer.cxx
tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuMatrix.h
tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h
tmva/tmva/inc/TMVA/Envelope.h
tmva/tmva/inc/TMVA/Tools.h
tmva/tmva/src/DataSet.cxx
tmva/tmva/src/DecisionTree.cxx
tmva/tmva/src/Event.cxx
tmva/tmva/src/MethodBase.cxx
tmva/tmva/src/ROCCalc.cxx
tmva/tmva/src/Tools.cxx
tmva/tmva/src/VariableTransform.cxx
tmva/tmvagui/src/efficienciesMulticlass.cxx

Just remove line where same include appears second time

Remove duplicated includes in hist/math/tmva classes

---

graf3d/g3d/inc/TPolyLine3D.h
graf3d/g3d/src/TPolyLine3D.cxx

This was suggested here:
https://sft.its.cern.ch/jira/browse/ROOT-9745

Allows to create TPolyLine3D object with pointer to const

---

CMakeLists.txt
core/base/src/TROOT.cxx
tree/dataframe/src/RArrowDS.cxx
tree/dataframe/test/datasource_arrow.cxx

This is the complete set of patches used by ALICE on top of v6-20-02. AFAICT they are all in master already. Any chance we can get them included in the next v6-20-XX tag?

Extra patches used by ALICE

---

tutorials/dataframe/df026_AsNumpyArrays.py

* Increases the test coverage of interacting with third-party python packages
* Improve message to user if the pandas package is not found

[RDF][Doc] Return non-zero exit code for df026 

---

documentation/doxygen/filter.cxx

Undo commit bed0e943466f5cc5c86bfaf434858ba1ab8202ca.
It has some side effects for images inline via Macro_Begin/Macro End

undo fix to remove extra ///

---

ui5/eve7/lib/GlViewerThree.js

Change in resetThreejsRenderer() : set frustum size to contain entire scene.

Eve-7 show entire scene on camera reset

---

hist/hist/src/TH1.cxx

This PR fixes https://sft.its.cern.ch/jira/browse/ROOT-10700

LabelsOption did not work for histograms with buffer

---

math/genvector/inc/Math/GenVector/AxisAngle.h
math/genvector/inc/Math/GenVector/Boost.h
math/genvector/inc/Math/GenVector/DisplacementVector3D.h
math/genvector/inc/Math/GenVector/EulerAngles.h
math/genvector/inc/Math/GenVector/LorentzRotation.h
math/genvector/inc/Math/GenVector/LorentzVector.h
math/genvector/inc/Math/GenVector/PositionVector3D.h
math/genvector/inc/Math/GenVector/Quaternion.h
math/genvector/inc/Math/GenVector/Rotation3D.h
math/genvector/inc/Math/GenVector/RotationZYX.h
math/genvector/inc/Math/GenVector/Transform3D.h
math/smatrix/inc/Math/SVector.icc

Backport fixes required by ART

---

core/metacling/src/TClingCallbacks.cxx

In setups where we have debug symbols in a separate library the .gnu.hash
section appears invalid. Clients can strip the debug symbols into a separate
library by:
objcopy --only-keep-debug libA.so libA.so.dbg
objcopy --strip-debug libA.so
objcopy --add-gnu-debuglink=libA.so.dbg libA.so
This should fix an issue reported by ATLAS when migrating to ROOT v6.20.

[dyld-v620] Ignore ELF libraries which contain no symbols.

---

tmva/tmva/CMakeLists.txt
tree/dataframe/CMakeLists.txt
tree/tree/CMakeLists.txt
tree/treeplayer/CMakeLists.txt

Make IMT an optional dependency.

---

README/ReleaseNotes/v622/index.md

For fixing ROOT-10654 and ROOT-10599.

[DOCS][NFC] Add Renato Quagliani to v6.22 contributors

---

hist/hist/inc/TGraph2DErrors.h
hist/hist/src/TGraph2DErrors.cxx

RemovePoint did not remove the errors in TGraph2DErrors.
This was reported here: https://sft.its.cern.ch/jira/browse/ROOT-10695

Implement RemovePoint for TGraph2DErrors

---

bindings/CMakeLists.txt
bindings/jupyroot/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy-backend/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy/CMakeLists.txt
bindings/pyroot_experimental/pythonizations/CMakeLists.txt

The variable contains the path to installation_directory/lib, where the
python packages are installed.

[CMake][Exp PyROOT] Change name of 'd' to 'install_dir_lib'

---

core/base/src/TColor.cxx

following https://root-forum.cern.ch/t/error-using-tcolor

Complete TColor doc with reference to SetColorThreshold

---

tutorials/pyroot/demo.py

raw_input is simply input in Python 3
suggested in https://sft.its.cern.ch/jira/browse/ROOT-10721

[Exp PyROOT] Make tutorials/pyroot/demo.py run also for Python3

---

graf3d/g3d/inc/THelix.h
graf3d/g3d/src/THelix.cxx

Change THelix Ctor and doc

---

cmake/modules/CTestCustom.cmake

This is connected to the `rootspi` PR here https://github.com/root-project/rootspi/pull/76

[Build system] Add script to load envvars to CTestCustom.cmake

---

config/rootrc.in
core/base/src/TSystem.cxx
core/dictgen/src/rootcling_impl.cxx

See PR #5296
Addresses the request in PR #5510 
cc: @ktf

Backport PR5296-related commits "Move {std namespace} declaration..."

---

README/ReleaseNotes/v622/index.md
graf2d/gpad/src/TPad.cxx

There was the need to redraw the frame plot in some cases.
This was requested here:
https://root-forum.cern.ch/t/change-background-color-only-in-a-region-of-a-th1

Implement the F option in RedrawAxis to redraw the plots frame

---

roofit/roofit/inc/RooBernstein.h
roofit/roofit/src/RooBernstein.cxx
roofit/roofit/test/CMakeLists.txt
roofit/roofit/test/testRooBernstein.cxx

Hello developers, 
I had closed the previous MR as there was some issues in rebasing. I have added the changes for the bernstein to exhibit the correct behaviour when dealing with ranged observables.
Cheers,
Rahul

[RF] update bernstein using std::tie for xmin and xmax

---

roofit/roofitcore/inc/RooAbsArg.h
roofit/roofitcore/inc/RooRealVar.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooRealVar.cxx

Given that functions were moved to a different location in the headers to group them for doxygen, this needs a CI run.

[RF] Documentation upgrades in RooFit.

---

README/ReleaseNotes/v622/index.md
documentation/doxygen/Doxyfile
roofit/roofit/doc/index.md
roofit/roofitcore/doc/index.md
roofit/roofitcore/inc/RooAbsCategory.h
roofit/roofitcore/inc/RooCategory.h
roofit/roofitcore/inc/RooGlobalFunc.h
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooCategory.cxx
roofit/roofitcore/src/RooFitLegacy/RooAbsCategoryLegacyIterator.h
roofit/roofitcore/src/RooFitLegacy/RooCatTypeLegacy.cxx
roofit/roofitcore/src/RooFitLegacy/RooCategorySharedProperties.cxx
roofit/roofitcore/src/RooFitLegacy/RooMultiCatIter.cxx
roofit/roostats/doc/index.md

- Add R__SUGGEST_ALTERNATIVE to macros ignored by doxygen.
- Improve doxygen of RooFit.
- Add section about categories to RooFit release notes.
[skip-ci]

[RF] Improve doxygen and add release notes.

---

math/matrix/doc/Matrix.md

Fix markdown syntax in matrix.md

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RCustomColumn.hxx
tree/dataframe/inc/ROOT/RDF/RCustomColumnBase.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RJittedCustomColumn.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RCustomColumnBase.cxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/src/RJittedCustomColumn.cxx
tree/dataframe/src/RLoopManager.cxx

...and simplify function signatures accordingly.

[DF] Remove code that's now unused and other now useless calls

---

interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp

This is part of root-project/root#4717

Adjust asserts.

---

README/README.CXXMODULES.md
README/ReleaseNotes/v622/index.md

Improve modules docs. Add readme entry.

---

core/base/src/TStyle.cxx

I'm not sure what the policy here is with inclusion of these styles and I didn't see another way to include a style in ROOT without patching at least one file.
So feel free to decline this PR. If there's a different way to do this (in rootrc or a simple config file in some style directory) I would be happy to hear that

Add Belle2 style to the list of styles

---

README/ReleaseNotes/v622/index.md
core/base/src/TStyle.cxx

Complete BELLE II Style

---

roofit/roostats/src/SPlot.cxx
roofit/roostats/test/CMakeLists.txt
roofit/roostats/test/testSPlot.cxx

Add the possibility to use ratios as yield parameters in SPlot.
Also update the documentation of SPlot, and add a test.

[RS] Fix ROOT-2558, SPlot cannot deal with ratios.

---

roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooTreeDataStore.cxx
roofit/roofitcore/test/testRooDataSet.cxx

In checking old bug reports, tests for two bugs were written. Although
the bugs had been fixed as side effects of modernisations or other bug
fixes, having those tests in place won't do harm.

[RF] Add tests ROOT-4580 and ROOT-9528.

---

interpreter/cling/tools/packaging/cpt.py

[cling-cpt]Fix broken requirements check for cpt - Cling's installer

---

cmake/modules/RootMacros.cmake

Same patch applied in master within bigger PR #5181

Provide correct include dirs for dictionary (ROOT-10658), v 6.20 

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/inc/ROOT/RDF/RCustomColumn.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RCustomColumnBase.cxx

[DF] Fix use after delete of RLoopManager in RCustomColumnBase

---

bindings/r/CMakeLists.txt
bindings/r/src/TRInterface.cxx
tutorials/r/Interpolation.C

Fixed Issue reported on 
https://sft.its.cern.ch/jira/browse/ROOT-10755
https://root-forum.cern.ch/t/rootr-root-r-interface-problems-with-x11-graphics/39299

[ROOT-10755] fixed X11 thread initialization

---

tmva/tmva/src/DataSetInfo.cxx
tutorials/tmva/TMVARegression.C

Use methodDL instead of methodDNN for TMVARegression and set the correct options

Fix TMVARegression.C for MethodDL

---

roofit/roofitcore/inc/RooLinkedListIter.h

See here: https://gcc.gnu.org/gcc-10/porting_to.html
Jira: https://sft.its.cern.ch/jira/browse/ROOT-10782

[RF] Add missing include of stdexcept

---

interpreter/cling/lib/Interpreter/IncrementalCUDADeviceCompiler.cpp

- now the ptx code should be aligned correctly

Backport bugfix in the ptx generator

---

ui5/eve7/controller/EveTable.controller.js
ui5/eve7/css/eve.css
ui5/eve7/view/EveTable.view.xml

This PR changes sort behaviour and coloring of table cells (gray/black) depending on REveDataItem filter status.

Eve-7 Use two-level sort in tables and color cells relative to REveDataItem filter value 

---

tutorials/fitsio/FITS_tutorial1.C
tutorials/fitsio/FITS_tutorial3.C

following  [link](https://github.com/root-project/root/pull/5680)

using std::unique_ptr the right way

---

bindings/jsmva/CMakeLists.txt
bindings/jupyroot/CMakeLists.txt
bindings/pyroot_experimental/cppyy/CPyCppyy/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy-backend/CMakeLists.txt
bindings/pyroot_experimental/cppyy/cppyy/CMakeLists.txt
bindings/pyroot_experimental/pythonizations/CMakeLists.txt

Backport of https://github.com/root-project/root/pull/5663 and https://github.com/root-project/root/pull/5666

[Exp PyROOT][CMake] 6.22 backport: fixes for "make package"

---

README/CREDITS
README/ReleaseNotes/v620/index.md

Add Johannes in CREDITS and release-notes

Add Johannes in CREDITS

---

README/ReleaseNotes/v622/index.md
roofit/roofitcore/inc/RooHelpers.h
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooHelpers.cxx

[RF] Update release notes.

---

test/stressTMVA.cxx
tmva/tmva/src/DataSetInfo.cxx
tmva/tmva/src/MethodDL.cxx
tmva/tmva/src/MethodDNN.cxx
tutorials/tmva/TMVARegression.C
tutorials/tmva/TMVA_CNN_Classification.C
tutorials/tmva/TMVA_RNN_Classification.C

These fixes replace using MethodDNN with MethodDL  in tests and tutorials

Backport in 6.22 some fixes in tmva 

---

interpreter/cling/lib/Interpreter/CIFactory.cpp

cc: @oshadura, @davidlange6, @smuzaffar

[cling] Adjust the location of the boost modulemap.

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/test/dataframe_snapshot.cxx

i.e. fix ROOT-10792 (and add a test).

[DF] Fix Snapshot of TClonesArrays

---

roofit/roofitcore/src/RooAbsPdf.cxx

This addresses the crash observed in ROOT-9347

Avoid using NumCpu with strategy=3 (hybrid case) for a pdf which is not a RooSimultaneous (ROOT-9347)

---

roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/inc/RooArgSet.h
roofit/roofitcore/inc/RooWorkspace.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooCustomizer.cxx
roofit/roofitcore/src/RooDirItem.cxx
roofit/roofitcore/src/RooFFTConvPdf.cxx
roofit/roofitcore/src/RooHistFunc.cxx
roofit/roofitcore/src/RooSimPdfBuilder.cxx
roofit/roofitcore/src/RooWorkspace.cxx
roofit/roofitcore/test/testWorkspace.cxx

This reduces run times of workspace transformations by factor ~7 for ATLAS workflows with heavy searching.

[RF] Backport unordered-map-assisted searches for RooWorkspace.

---

core/dictgen/src/rootcling_impl.cxx

@gargvaibhav64 please let us know if that fixes the issues you see with modules on windows.

[rootcling] Misc NFC refactoring

---

core/base/src/TError.cxx

Replace TString by std::string in TError

---

tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx

[DF] Fix diagnostic of sparse/contiguous storage in TTreeReaderArray (v6.22)

---

tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx

[DF] Fix diagnostic of sparse/contiguous storage in TTreeReaderArray (v6.20)

---

test/stressGraphics.cxx

backport stressgraphics fix to 6.22

backport stressgraphics fix

---

interpreter/cling/.travis.yml

[cling]Fix travis not triggering

---

tutorials/dataframe/df025_RNode.C

Show a few more cool tricks, in particular building computation graphs
using C++ control flow.
This also removes a memleak of the return value of
TClassEdit::DemangleName (thanks for pointing it out Sergei!).

[DF] Improve RNode.C tutorial

---

tree/dataframe/src/RDFInterfaceUtils.cxx

Thanks Sergei for pointing it out!

[DF] Fix memleak in helper function

---

interpreter/cling/tools/packaging/cpt.py

llvm_vers variable required earlier for linux platform initialization

[skip-ci][cling][cpt]Move declarations up to fix faulty logic

---

roofit/roofit/src/RooTFnBinding.cxx
roofit/roofitcore/inc/RooAbsData.h
roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooHelpers.h
roofit/roofitcore/inc/RooHistFunc.h
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooCategory.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooHelpers.cxx
tutorials/roofit/rf101_basics.C
tutorials/roofit/rf102_dataimport.C
tutorials/roofit/rf103_interprfuncs.C

Collection of documentation updates that accumulated over a few weeks.

[RF] Documentation updates

---

interpreter/cling/tools/packaging/cpt.py

Should fix https://github.com/root-project/cling/issues/347

[skip-ci][cling][cpt]Fix llvm binary tarball requirement

---

README/ReleaseNotes/v622/index.md

Two tweaks for release notes.
[Skip-ci]

[RF] Tweak release notes.

---

README/ReleaseNotes/v622/index.md

[RF] Release notes.

---

bindings/tpython/src/TPython.cxx
documentation/doxygen/Doxyfile

[TPython][Docs] Fix docstrings of TPython.

---

bindings/tpython/src/TPython.cxx
documentation/doxygen/Doxyfile

Fix TPython docs.

---

core/dictgen/src/rootcling_impl.cxx

[rootcling] Provide better information about the potential missing dependency

---

roofit/roofitcore/src/RooNLLVar.cxx

https://root-forum.cern.ch/t/roonllvar-documenation/40066

fix RooNLLVar doc

---

documentation/doxygen/htmlheader.html

Reference guide version changer. first try. Needs more test and tuning.

Ref guide version changer

---

core/base/inc/TError.h
core/base/src/TError.cxx
core/base/test/TErrorTests.cxx

Same as #5951 but without creating a new branch in the upstream repository.

Revert "Remove obsolete compatibility layers from TError"

---

tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
tree/dataframe/test/dataframe_display.cxx

[DF] Display: treat chars arrays as strings, not collections

---

bindings/pyroot/pythonizations/python/ROOT/_numbadeclare.py

Backport of https://github.com/root-project/root/pull/5960

[PyROOT] Backport 6.22: Compatibility with python 2.7 versions before 2.7.9

---

tmva/pymva/src/MethodPyKeras.cxx

Remove extra redundant tensorboard Option

[PyMVA] Fix DeclareOptions PyKeras

---

tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/test/dataframe_display.cxx
tree/dataframe/test/dataframe_utils.cxx

This fixes the report in ROOT-10889.

[DF] Treat RVec<bool> as a collection in Display 

---

graf3d/gl/src/gl2ps.cxx
roofit/histfactory/inc/RooStats/HistFactory/Systematics.h

Fix clang-10 warnings

---

interpreter/CMakeLists.txt
interpreter/cling/tools/plugins/clad/CMakeLists.txt
interpreter/llvm/src/CMakeLists.txt

ROOT-10812: Fix building clad with external clang

ROOT-10812: Fix building clad with external clang (#5945)

---

bindings/pyroot/pythonizations/CMakeLists.txt

[Backport][PyROOT] Install additional PyROOT headers

---

roofit/roofitcore/inc/RooAbsCategory.h
roofit/roofitcore/inc/RooCategory.h
roofit/roofitcore/src/RooAbsCategory.cxx
roofit/roofitcore/src/RooCategory.cxx
roofit/roofitcore/src/RooMappedCategory.cxx
roofit/roofitcore/src/RooSimPdfBuilder.cxx
roofit/roofitcore/test/testProxiesAndCategories.cxx

Fix a missing state update in RooAbsCategory, and prevent an invalid state in uninitialised categories.
On the way to finding this bug, I managed to get some indentation fixes and loop modernisations done, which are included here.

[RF] Fix ROOT-10913

---

tutorials/roofit/rf204b_extendedLikelihood_rangedFit.C

[RF][NFC] Fix doxygen tags in rf204b tutorial.

---

tutorials/CMakeLists.txt
tutorials/dataframe/df103_NanoAODHiggsAnalysis.C
tutorials/launcher.py
tutorials/roofit/rf514_RooCustomizer.C

In addition to the fixes, I added the `longtest` label for a few long-running tutorials.

[Tutorials] Some fixes for various tutorials.

---

graf3d/eve7/CMakeLists.txt
graf3d/eve7/inc/LinkDef.h
graf3d/eve7/inc/ROOT/REveCalo.hxx
graf3d/eve7/inc/ROOT/REveCaloData.hxx
graf3d/eve7/src/REveCalo.cxx
graf3d/eve7/src/REveCaloData.cxx
graf3d/eve7/src/REveManager.cxx
tutorials/eve7/calorimeters.C
ui5/eve7/lib/EveElements.js
ui5/eve7/lib/EveManager.js
ui5/eve7/lib/EveScene.js

This is import of calorimeters from original EVE to server-client model of event display.
Macro tutorials/eve7/calorimeters.C is an example of 3D and projected visualization.

Eve-7 Import of calorimeter visalization 

---

js/scripts/JSRootPainter.v6.js

Most probable reason for error described in ROOT-10916 issue

[jsroot] fix TStyle handling when drawing TCanvas (ROOT-10916)

---

core/winnt/src/TWinNTSystem.cxx

Filter out internal DLLs, not supposed to be linked when using ACLiC

Fix Jira issue #ROOT-10925 Can not compile ROOT macro on Windows

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPExcInstance.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPPInstance.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx
bindings/pyroot/cppyy/CPyCppyy/src/ProxyWrappers.cxx

Backport of https://github.com/root-project/root/pull/6024

 [PyROOT][ROOT-10870] Backport 6.22: Fixes/additions for CPPExcInstance 

---

interpreter/cling/include/cling/boost.modulemap

Reduce the headers and adapt it to boost 1.72

Make the modulemap more maintainable.

---

documentation/primer/macros/macro3.C

Fix according to: https://root-forum.cern.ch/t/redundant-argument-in-tgraphpolar/40368

fix macro3

---

README/ReleaseNotes/v622/index.md

Fix wrong link and remove white spaces.

Fix wrong link

---

graf3d/eve7/inc/ROOT/REveGeoPolyShape.hxx
graf3d/eve7/inc/ROOT/REveGluTess.hxx
graf3d/eve7/inc/ROOT/REvePolygonSetProjected.hxx
graf3d/eve7/inc/ROOT/REveRenderData.hxx
graf3d/eve7/inc/ROOT/REveTrackProjected.hxx
graf3d/eve7/src/REveCalo.cxx
graf3d/eve7/src/REveGeoPolyShape.cxx
graf3d/eve7/src/REveGluTess.cxx
graf3d/eve7/src/REvePolygonSetProjected.cxx
graf3d/eve7/src/REveTrackProjected.cxx
ui5/eve7/lib/EveElements.js
ui5/eve7/lib/EveManager.js

Store index buffer as unsigned integer as it is convention in Web GL graphics:
https://github.com/alja/root/blob/uint-idxBuff/ui5/eve7/lib/EveManager.js#L447

Eve-7:  Use REveRenderData index buffer as unsigned integer array 

---

core/metacling/src/TCling.cxx

This allows users to specify the modulemap name not just the folder. The CLING_MODULEMAP_FILES env variable should have a list of space-separated files which cling will try to load as modulemaps.
This should allow cmssw to load the boost modulemap and use it.
cc: @davidlange6

[cxxmodules] CLING_MODULEMAP_PATH becomes CLING_MODULEMAP_FILES

---

graf2d/cocoa/src/TGQuartz.mm
graf2d/win32gdk/src/TGWin32.cxx
graf2d/x11/src/TGX11.cxx

Hello,
these are exactly the same changes as PR #6027
Since it is a pure bugfix, I think it should be added also to the patches branch.
In case this second PR for the patches branch is not necessary to get the changes into the patches branch, I'm sorry, however I am no expert on using git tools and this is the only way I know.
All the best,
Simon

[Fix][graf2d] Fix drawing performance of marker styles 6 and 7

---

tutorials/dataframe/df002_dataModel.py
tutorials/dataframe/df003_profiles.py
tutorials/dataframe/df007_snapshot.py
tutorials/dataframe/df010_trivialDataSource.py
tutorials/dataframe/df014_CSVDataSource.py
tutorials/dataframe/df016_vecOps.py
tutorials/dataframe/df017_vecOpsHEP.py
tutorials/dataframe/df019_Cache.py
tutorials/dataframe/df021_createTGraph.py

* In Python script mode the canvases dont stay on screen, therefore
the figures are saved and an according notification is printed.
* Fixes ROOT-10960

[RDF][Doc] Save figures in the Python tutorials also to disk

---

tree/dataframe/inc/ROOT/RDF/RColumnValue.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDFHelpers.hxx
tree/dataframe/src/RDFInterfaceUtils.cxx

* Use new naming convention for helper type
* Remove unnecessary fwd decl and include
* clang-format pass on RInterface.hxx

[DF] Beauty fixes

---

tree/dataframe/test/dataframe_helpers.cxx

Otherwise tests run concurrently can write on each other's feet.

[DF] Use unique file names in tests (6.20)

---

hist/hist/src/TAxis.cxx
hist/hist/src/TH1.cxx
main/src/hadd.cxx
roofit/roofitcore/inc/RooAbsData.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooPlot.cxx
roofit/roofitcore/src/RooWorkspace.cxx

A (possibly growing) collection of documentation updates. Adding things as forum questions etc are coming in.

[Docs] Collection of documentation updates.

---

documentation/doxygen/Doxyfile

[skip-ci] Add hadd.cxx in Doxyfile

---

cmake/modules/SearchInstalledSoftware.cmake

@bellenot I'm not sure what to do about windows, the configure command is empty there?

Build built-in LZMA with O3 optimization level

---

tmva/tmva/src/DNN/Architectures/Cudnn/Propagate.cu
tmva/tmva/src/DNN/Architectures/Cudnn/RecurrentPropagation.cu

WIP: As the title says - trying to update TMVA to support cuDNN 8, but also be backwards compatible.
More commits to come

[ROOT-10936] Adapt TMVA to support cuDNN 8

---

tmva/tmva/src/DNN/Architectures/Cudnn/Propagate.cu

dynamically ask cuDNN about available number of algorithms

---

cmake/modules/RootConfiguration.cmake
cmake/modules/SearchInstalledSoftware.cmake
config/RConfigure.in
tmva/tmva/inc/TMVA/DNN/Architectures/Cuda/CudaMatrix.h
tmva/tmva/src/DNN/Architectures/Cuda.cu
tmva/tmva/src/DNN/Architectures/Cudnn.cu
tmva/tmva/src/DNN/Architectures/Cudnn/Propagate.cu
tmva/tmva/src/DNN/Architectures/Cudnn/RecurrentPropagation.cu
tmva/tmva/test/Method/TestMethodDNNValidationSize.cxx

Backport fixes from #6058,  #6148,  #6079 for supporting cudnn version 8 in 6.22 patches

Backport cudnn v8

---

bindings/jupyroot/python/JupyROOT/helpers/utils.py

Port the changes done in the old JupyROOT by @diocas in https://github.com/root-project/root/pull/4652

[JupyROOT][ROOT-10956] Port fix for JupyterLab to new JupyROOT

---

interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp

On Windows, the .dll files contain symbol information in COFF Format which DLM currently fails to understand properly. This leads to unrecognized symbol errors while starting ROOT with modules.
This commit teaches DLM to correctly read symbols when the Object File is in COFF executable format.
@vgvassilev @bellenot

Teach DLM to recognise symbols in COFF Object Files.

---

core/metacling/src/TClingRdictModuleFileExtension.cxx

On windows, there are instances when the rdict file is still in use when we try to remove it.
This happens due to some problem with file handling in LLVM5 which got resolved in D63453(https://reviews.llvm.org/D63453). But it was difficult to backport.
With this commit, we switch to the standard C++ library functions for generating rdict files and avoid using this particular API of LLVM.
@vgvassilev @bellenot

Shift to standard C++ filestreams when generating _rdict files

---

bindings/pyroot/cppyy/CPyCppyy/src/Cppyy.h
bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx
bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/cpp_cppyy.h
core/metacling/src/TClingMethodInfo.cxx

Backport of https://github.com/root-project/root/pull/6185 and https://github.com/root-project/root/pull/6173

[PyROOT][TCling] Backport 622: Fixes for inheritance

---

CMakeLists.txt
config/thisroot.csh
config/thisroot.fish
config/thisroot.sh
etc/notebook/jupyter_notebook_config.py
etc/notebook/jupyter_notebook_config.py.in

[Backport][JupyROOT] Make jupyter working without root --notebook

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_generic.py
bindings/pyroot/pythonizations/test/pretty_printing.py

Backport of https://github.com/root-project/root/pull/6119

[Backport][PyROOT] Respect existing __str__ method in pretty printing

---

graf3d/eve7/inc/ROOT/REveCaloData.hxx
graf3d/eve7/src/REveCaloData.cxx
ui5/eve7/controller/Ged.controller.js
ui5/eve7/lib/GlViewerThree.js

This change required some restructuring in Ged.controller.js because some class editors need more flexibility in GUI definition.

Eve-7 Add REveCaloData editor

---

core/winnt/src/TWinNTSystem.cxx

Re-implement TWinNTSystem::GetLibraries() to make sure the list of libraries contains only existing - and reachable - `.lib` files.
- Get the list of DLLs loaded in the current process
- Get the list of directories from the `%LIB%` environment variable
- For every DLL, check if the matching `.lib` file is found in one of the `LIB` directories
- Keep only the found ones and the `/LIBPATH:dir` linker option, if any
This also allows the user to add a directory in the `%LIB%` environment variable if a custon library is needed

Re-implement TWinNTSystem::GetLibraries()

---

bindings/jupyroot/python/JupyROOT/helpers/handlers.py
bindings/jupyroot/python/JupyROOT/kernel/magics/cppmagic.py
bindings/jupyroot/python/JupyROOT/kernel/rootkernel.py
bindings/jupyroot/python/JupyROOT/kernel/utils.py
bindings/pyroot_legacy/JupyROOT/helpers/handlers.py
bindings/pyroot_legacy/JupyROOT/kernel/magics/cppmagic.py
bindings/pyroot_legacy/JupyROOT/kernel/rootkernel.py
bindings/pyroot_legacy/JupyROOT/kernel/utils.py

https://sft.its.cern.ch/jira/browse/ROOT-10992

[JupyROOT] ROOT kernel files have same license as ROOT

---

roofit/roofit/src/RooGaussian.cxx
roofit/roofitcore/src/RooAbsPdf.cxx

Two small things:
- Disable level 2 optimisation when batch mode in use. It just wastes time.
- Check that sigmas of Gaussians are positive.

[RF] Speed improvement and a little usability

---

core/imt/test/testRTaskArena.cxx

This proves that ROOT-10762 is not an issue.

[IMT] Test thread safety of task arena and TThreadExecutor.

---

roofit/roostats/src/HypoTestInverterResult.cxx

Update the cleanup routine. Add cleaning up failed fits as well, i.e.,
CLs < 0.

[RS] Update HypoTestInverterResult::ExclusionCleanup.

---

interpreter/cling/lib/Interpreter/CIFactory.cpp
interpreter/cling/lib/Interpreter/DefinitionShadower.cpp

- default argument specified for lambda parameter [-Wpedantic];
- will be initialized after [-Wreorder]

[cling] Fix warnings:

---

roofit/histfactory/inc/RooStats/HistFactory/Channel.h
roofit/histfactory/inc/RooStats/HistFactory/Data.h
roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
roofit/histfactory/inc/RooStats/HistFactory/PreprocessFunction.h
roofit/histfactory/inc/RooStats/HistFactory/Sample.h
roofit/histfactory/inc/RooStats/HistFactory/Systematics.h
roofit/histfactory/src/Channel.cxx
roofit/histfactory/src/Data.cxx
roofit/histfactory/src/FlexibleInterpVar.cxx
roofit/histfactory/src/Measurement.cxx
roofit/histfactory/src/Sample.cxx
roofit/roofitcore/inc/RooAbsArg.h

First part of PR #5324, which can be split off, because it's paving the way for future work.

[HF] Adding getters and const-correctness

---

tmva/pymva/src/MethodPyKeras.cxx

Fix minor redundant code in PyKeras

[PyMVA] PyKeras minor fixes

---

roofit/roofitcore/inc/RooFitResult.h
roofit/roofitcore/inc/RooMinimizerFcn.h
roofit/roofitcore/inc/RooRealSumPdf.h
roofit/roofitcore/src/RooAddPdf.cxx
roofit/roofitcore/src/RooMinimizerFcn.cxx
roofit/roofitcore/src/RooRealSumPdf.cxx

While working on a feature, these commits piled up. They could be split off from the feature branch.
I hope they are (mostly) NFCs, but small things are changing. For example, floating point computations are reordered, and `assert(0)` are replaced by `throw` and `#include`s are fixed.

[RF] Cleanups

---

hist/hist/src/TH1.cxx

values calculates from bin content -> values calculated from bin content

Fixing a typo in TH1.cxx documentation

---

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C

To help debug the timeouts seen on MacOS.

[TO REVERT] Add verbose printouts to df103_NanoAODHiggsAnalysis.C

---

cmake/modules/RootConfiguration.cmake
geom/geom/src/TGeoPcon.cxx
geom/geom/src/TGeoPgon.cxx
js/scripts/JSRootCore.js
js/style/JSRootPainter.css

- jsroot fixes
- chrome handling on Ubuntu 20.04
- pcon/pgon without inner surface

Backport several fixes to 6.22

---

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C

This reverts commit 2cb2308f207f1899e4a5a7b8e27f6f6701a74f18.

Revert "[TO REVERT] Add verbose printouts to df103_NanoAODHiggsAnalysis.C" (6.22)

---

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C

This reverts commit 2cb2308f207f1899e4a5a7b8e27f6f6701a74f18.

Revert "[TO REVERT] Add verbose printouts to df103_NanoAODHiggsAnalysis.C"

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_ttree.py

[skip-ci]
Please @stwunsch have a look, and could you also add a commit with what you would like to document for `TTree.AsMatrix`?

[PyROOT] Add TTree pythonization docs

---

interpreter/cling/tools/packaging/README.md

addresses https://github.com/root-project/cling/issues/307

[cling] Remove statement about "policy restrictions" wrt repos (NFC);

---

core/base/src/TStyle.cxx

fix https://root-forum.cern.ch/t/fixing-tstyle-default-settings-if-name-atlas/41038

fix atlas style

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RDF/RDisplay.hxx
tree/dataframe/test/dataframe_display.cxx

@vvolkl got bit by this and it's easy to work around, so why not :D

[DF] Add support for calling Display on move-only types

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_tdirectory.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_tdirectoryfile.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_tfile.py

[PyROOT][Doc] Document pythonizations of TDirectory, TDirectoryFile and TFile

---

hist/hist/inc/TH3.h
hist/hist/src/TAxis.cxx
hist/hist/src/TH1.cxx
hist/hist/src/TH1Merger.cxx
hist/hist/src/TH2.cxx
hist/hist/src/TH3.cxx
test/stressHistogram.cxx

Fix merging of multi-dimensional histogram when one axis has labels and the other not

---

bindings/pyroot/pythonizations/src/PyzCppHelpers.cxx
bindings/pyroot/pythonizations/test/TreeHelper.h
bindings/pyroot/pythonizations/test/ttree_branch_attr.py

Reported in:
https://sft.its.cern.ch/jira/browse/ROOT-11030

[PyROOT] Fix getattr pythonization of TTree

---

bindings/pyroot/pythonizations/src/PyzCppHelpers.cxx
bindings/pyroot/pythonizations/test/TreeHelper.h
bindings/pyroot/pythonizations/test/ttree_branch_attr.py

Backport of https://github.com/root-project/root/pull/6303

[PyROOT] Backport 6.22: Fix getattr pythonization of TTree

---

tutorials/graphics/perceptualcolormap.C

remove unused variable

---

bindings/pyroot/pythonizations/python/ROOT/__init__.py

Backport - for PR #6305 

---

tutorials/graphics/perceptualcolormap.C

Formatting and help editing of perceptualcolormap.C

Formatting and help editing

---

tmva/tmva/inc/TMVA/DecisionTreeNode.h
tmva/tmva/src/DecisionTreeNode.cxx
tmva/tmva/src/MethodBDT.cxx
tmva/tmva/src/MethodDT.cxx
tmva/tmva/src/MethodRuleFit.cxx
tmva/tmvagui/inc/TMVA/BDT.h
tmva/tmvagui/inc/TMVA/BDT_Reg.h
tmva/tmvagui/src/BDT.cxx

[TMVA] Remove double definition of a static variable.

---

bindings/pyroot/pythonizations/python/ROOT/__init__.py

Backport of https://github.com/root-project/root/pull/6319

[PyROOT][ROOT-11027] Backport 622: Revert activation of batch mode made by cppyy

---

tree/treeplayer/inc/TTreeReaderValue.h

@Axel-Naumann @pcanal up to you, we can live without these commits but since I had them hanging around...

[TTreeReader] Formatting and better error message

---

cmake/modules/RootMacros.cmake
tmva/pymva/CMakeLists.txt
tmva/pymva/inc/LinkDef.h
tmva/pymva/inc/TMVA/MethodPyTorch.h
tmva/pymva/src/MethodPyTorch.cxx
tmva/pymva/test/CMakeLists.txt
tmva/pymva/test/generatePyTorchModelClassification.py
tmva/pymva/test/generatePyTorchModelMulticlass.py
tmva/pymva/test/generatePyTorchModelRegression.py
tmva/pymva/test/testPyTorchClassification.C
tmva/pymva/test/testPyTorchMulticlass.C
tmva/pymva/test/testPyTorchRegression.C
tmva/tmva/inc/TMVA/Types.h

This is a pull request for the development of PyTorch Interface in TMVA leveraging the PyMVA module. Feel free to comment and share feedback.
I'm also maintaining a [blog](https://anirudhdagar.github.io/gsoc/) for updating my progress and sharing some insights about my project.
These are implemented in #6273

[GSoC][TMVA] PyTorch Interface TMVA

---

documentation/HttpServer/HttpServer.md
net/http/src/TFastCgi.cxx

Fix FastCGI support for Apache 2.4, v6.22

---

tree/dataframe/test/dataframe_interface.cxx
tree/tree/inc/TBranch.h
tree/tree/inc/TBranchElement.h
tree/tree/src/TBranchElement.cxx
tree/tree/src/TLeafElement.cxx
tree/tree/src/TTree.cxx

Use FullName in TTree::GetLeaf.

---

roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/roofit/src/RooDstD0BG.cxx
roofit/roofit/src/RooLognormal.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooMsgService.cxx
roofit/roofitcore/src/RooSimultaneous.cxx
tutorials/roofit/rf501_simultaneouspdf.C

[RF][Docs] Documentation updates.

---

core/base/src/TStyle.cxx
documentation/users-guide/Trees.md
tutorials/tree/cernbuild.C

Update the TTree user's as requested in: 
https://sft.its.cern.ch/jira/browse/ROOT-10809

TTree users guide

---

tutorials/dataframe/df105_WBosonAnalysis.py
tutorials/dataframe/df106_HiggsToFourLeptons.py
tutorials/dataframe/df107_SingleTopAnalysis.py

Streamlines the behaviour with respect to df105 and df107

[RDF][Doc] Add print to df106

---

README/ReleaseNotes/v624/index.md

[skip-ci][relnotes] Mention behavior change w.r.t. tbb::task_scheduler_init

---

tree/dataframe/test/datasource_ntuple.cxx

Currently a draft because reading RVecs is not working.

[RNTupleDS] Test reading data

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

This fixes ROOT-10886 for v6.22

v622 allow building Clad with Clang compiler

---

tree/dataframe/inc/ROOT/RCsvDS.hxx
tree/dataframe/inc/ROOT/RDFHelpers.hxx
tree/dataframe/src/RCsvDS.cxx
tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/src/RDefineBase.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_concurrency.cxx

Done! I think I've integrated all changes.
**TODO:**

[RDF] Enable thread safety

---

core/thread/src/TReentrantRWLock.cxx

[skip-ci] Correct assert condition (missing negation).

---

roofit/roofitcore/inc/RooMinimizer.h
roofit/roofitcore/inc/RooMinimizerFcn.h
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooMinimizer.cxx
roofit/roofitcore/src/RooRealSumPdf.cxx

Took these out of a feature branch, because they are unrelated to the feature.

[RF] Various small improvements

---

graf2d/gpad/src/TPad.cxx

Fix https://github.com/root-project/root/issues/6374

Avoid pad creation with W<=0 or H<=0

---

tmva/tmva/src/DataSetFactory.cxx

When using in TMVA Variable Array (via DataLoader::AddVariableArray) in DataSetFactory::BuildEventVector 
add a check that the data collection  (in the TTree) have a size  at least large as requested.
If size is smaller add a Fatal message
If size is larger add the first time a warning message

[TMVA] Check consistency of arrays when reading the data

---

js/changes.md
js/scripts/JSRootCore.js
js/scripts/JSRootGeoBase.js
js/scripts/JSRootGeoPainter.js
js/scripts/JSRootPainter.hist.js
js/scripts/JSRootPainter.hist3d.js
js/scripts/JSRootPainter.js
js/scripts/JSRootPainter.v6.js
js/scripts/JSRootPainter.v7.js
js/scripts/JSRootPainter.v7hist3d.js

Fix stats update in historgam when running in THttpServer
Many small fixes with usage of undefined variables -
discovered when developing jsroot v6

[jsroot] dev 23/09/2020 with several fixes [skip-ci]

---

js/scripts/JSRootGeoBase.js
js/scripts/JSRootGeoPainter.js
js/scripts/JSRootPainter.hist.js
js/scripts/JSRootPainter.hist3d.js
js/scripts/JSRootPainter.js
js/scripts/JSRootPainter.v7.js

Fix histogram stat box update
Do not use variables before define them
Remove unused variables

[jsroot] several fixes for v6-22-00-patches [skip-ci]

---

graf2d/gpad/src/TCanvas.cxx

fix for: https://github.com/root-project/root/issues/6379

prevent invalid canvas height

---

graf2d/gpad/src/TPad.cxx

Fix https://github.com/root-project/root/issues/6428

Protection if l does not exist

---

bindings/pyroot/cppyy/CPyCppyy/src/CPPConstructor.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx

Backport of https://github.com/root-project/root/pull/6434

[PyROOT][6376] Backport 6.22: Fix calculation of offset of dispatch pointer

---

graf2d/gpad/src/TPad.cxx

Avoid null pointer dereference
Tag @couet

 Avoid null pointer dereference

---

graf2d/gpad/src/TPad.cxx

fix https://github.com/root-project/root/issues/6453

Protection if fCanvas does not exist

---

io/io/inc/ROOT/RRawFile.hxx
io/io/test/RRawFile.cxx

[rawfile] Add GetFilePos() method

---

documentation/doxygen/makeimage.py

See the discussion in the commit messages. This should fix #6360.

[Doc] Fix makeimage.py script

---

graf2d/gpad/src/TPad.cxx

Fix: https://github.com/root-project/root/issues/6449

GetWh/w return UInt_t

---

roofit/roofitcore/src/RooTreeDataStore.cxx
roofit/roofitcore/test/testRooDataSet.cxx

(cherry picked from commit 7c5da08cf7392f9feda60da55645b64216ccf599)
Fix #6408

[RF] Fix root-project/root#6408.

---

graf2d/gpad/src/TPad.cxx

Fix two more places in TPad with potential  division by zero.
Tag @couet

Fix two more places in TPad with potential  division by zero

---

etc/gdb-backtrace.sh

Change http to https in gdb message

Change http to https

---

graf2d/gpad/src/TPad.cxx

Avoid null pointer dereference
Tag @couet

Avoid null pointer dereference

---

graf2d/gpad/src/TCanvas.cxx

previous PR made stressGraphics crash

previous PR made stressGraphics crash

---

core/metacling/src/TClingMethodInfo.cxx
core/metacling/src/TClingMethodInfo.h

Backport of https://github.com/root-project/root/pull/6389

[metacling] Backport: Only add special function ctors to SpecFunIter:

---

bindings/pyroot/pythonizations/CMakeLists.txt

Fixes for:
- Installation of TPyDispatcher.h. Fixes #6579 
- Removal of pythonization files that are no longer there

[PyROOT] A few CMake fixes

---

tmva/pymva/inc/TMVA/MethodPyKeras.h
tmva/pymva/src/MethodPyKeras.cxx

This is a backport of #6568 in 6.22 branch

[tmva] Backport in 6.22 for pymva support of tf keras

---

bindings/pyroot/cppyy/patches/multi_python_cppyy.patch

The previous version was wrongly inverted: the deletions and
additions had to be additions and deletions, respectively.

[PyROOT] Redo patch for multi-python

---

tree/dataframe/src/RLoopManager.cxx

This prevents certain ugly error messages in case an exception is
thrown during a multi-thread event loop: before this patch, in that
case the thread's slot number was never returned to the RSlotStack
and it could result in some misleading error messages being printed on
screen.

[DF] Use a RAII helper to pop/push slots from RSlotStack

---

bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx
bindings/pyroot/cppyy/patches/using-data-members.patch
core/base/src/TROOT.cxx
core/meta/inc/TClass.h
core/meta/inc/TDataMember.h
core/meta/inc/TDictionary.h
core/meta/inc/TInterpreter.h
core/meta/inc/TListOfDataMembers.h
core/meta/src/TClass.cxx
core/meta/src/TDataMember.cxx
core/meta/src/TListOfDataMembers.cxx
core/metacling/src/TCling.cxx
core/metacling/src/TCling.h
core/metacling/src/TClingDataMemberInfo.cxx
core/metacling/src/TClingDataMemberInfo.h
core/metacling/src/TClingMemberIter.h
core/metacling/src/TClingMethodInfo.cxx
core/metacling/src/TClingMethodInfo.h
interpreter/cling/lib/Utils/AST.cpp
io/io/src/TStreamerInfo.cxx

v6.22: TClingDataMemberInfo: use TClingMemberIter

---

bindings/pyroot/cppyy/cppyy/python/cppyy/__init__.py
bindings/pyroot/cppyy/patches/multi_python_cppyy.patch
bindings/pyroot/pythonizations/python/ROOT/__init__.py

Backport of:
https://github.com/root-project/root/pull/6618
and
https://github.com/root-project/root/pull/6621

[PyROOT] Backport fixes for installation of PyROOT

---

core/metacling/src/TClingCallFunc.cxx
core/metacling/src/TClingMethodInfo.cxx
core/metacling/test/TClingMethodInfoTests.cxx

Backport of  #6612, fixing #6578

v6.22: Fix #6578: TGMainFrame all-default ctor

---

graf2d/graf/src/TArrow.cxx
graf2d/graf/src/TBox.cxx
graf2d/graf/src/TEllipse.cxx
graf2d/graf/src/TMarker.cxx
graf2d/graf/src/TPave.cxx
graf2d/graf/src/TPaveLabel.cxx
graf2d/graf/src/TPolyLine.cxx
graf2d/graf/src/TText.cxx

Added some protection for gpad==null cases
Tag @couet

Added some protection for gpad==null cases

---

hist/histpainter/src/THistPainter.cxx

improve cont3 doc

---

hist/hist/src/THStack.cxx

fix https://github.com/root-project/root/issues/6642

Set THStack maximum like TH1

---

build/gdbPrinters/libRooFitCore.so-gdb.py
roofit/roofitcore/inc/RooVectorDataStore.h
roofit/roofitcore/src/RooMsgService.cxx
roofit/roofitcore/src/RooVectorDataStore.cxx

Collection of small patches that piled up during work on a larger branch.

[RF] Collection of small patches.

---

graf2d/graf/src/TPaveLabel.cxx

Prevent division by zero in TPaveLabel.cxx
Tag @couet

[Bugfix] Prevent division by zero in TPaveLabel.cxx

---

graf3d/eve7/inc/ROOT/REveElement.hxx
io/io/res/json.hpp
io/io/res/json_fwd.hpp

Backport of #6663 to v6.22 branch

Upgrade nlohmann/json.hpp to version 3.9.1 (ROOT-10993) v6.22

---

bindings/pyroot/pythonizations/src/TTreePyz.cxx
bindings/pyroot/pythonizations/test/TreeHelper.h
bindings/pyroot/pythonizations/test/ttree_setbranchaddress.py

Fixes https://github.com/root-project/root/issues/6468

[PyROOT][6468] Fix SetBranchAddress pythonization for class branch with array member

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/test/dataframe_histomodels.cxx

[DF] Allow to fill histos with vector<bool> types

---

tree/dataframe/src/RNTupleDS.cxx
tree/ntuple/v7/inc/ROOT/RField.hxx
tree/ntuple/v7/src/RField.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleModel.cxx

[ntuple] Return unique pointer from RFieldBase::Create and Clone

---

html/src/THtml.cxx

[bug][improvement] Fix warning message in THtml

---

roofit/roofitcore/inc/RooHelpers.h
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooAbsTestStatistic.cxx
roofit/roofitcore/src/RooNLLVar.cxx
roofit/roofitcore/src/RooXYChi2Var.cxx
roofit/roofitcore/src/RunContext.cxx

While working on another PR, these piled up. They are not really related, so put them here for easier reviewing.

[RF] Collection of a few small patches.

---

roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/inc/RooBinSamplingPdf.h
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooBinSamplingPdf.cxx

Since the bin sampling PDF is a binned distribution, one can greatly improve plotting by implementing plot sampling hints.

[RF] Improve plotting or RooBinSamplingPdf

---

tutorials/fit/FitHistoInFile.C

Tutorial submitted by Eckhard v. Toerne.
Apparently, a tutorial showing the complete workflow of retrieving a histogram from a file, fitting it, and plotting the results is missing. This is demonstrated here.

[Tutorial] Add tutorial for fitting a histogram in a file.

---

geom/geom/src/TGeoNode.cxx
geom/geom/src/TGeoVolume.cxx

The problem is visible when calling the reflection factory in TGeoManager - reported by @ianna

Fix for copying title to cloned volumes and nodes.

---

interpreter/cling/.github/workflows/ci.yml
interpreter/cling/tools/packaging/cpt.py

(Mirror of https://github.com/root-project/cling/pull/365)

[Cling]Setup Github Actions CI for Linux and macOS

---

interpreter/cling/.github/workflows/ci.yml

Mirror of https://github.com/root-project/cling/pull/367

[Cling] Fix Cling's Github Actions CI for PRs

---

core/cont/src/TClassTable.cxx
core/dictgen/res/SelectionRules.h
core/dictgen/src/Scanner.cxx
core/dictgen/src/SelectionRules.cxx
core/meta/inc/TClass.h
core/meta/src/TClass.cxx
core/meta/src/TProtoClass.cxx

see https://github.com/root-project/root/pull/6680

v6-22: Fix issue #6670. Avoid infinite recursion from TClass::InheritsFrom.

---

interpreter/cling/lib/Interpreter/CIFactory.cpp

we need this in 6-22 
https://github.com/root-project/root/issues/6465#issuecomment-714700958
to fix the resulting error.

[cling] Force char-signedness of host. Fixes #6465. [to 6-22]

---

geom/geom/src/TGeoNode.cxx
geom/geom/src/TGeoVolume.cxx

Fix for copying title to cloned volumes and nodes [6-22]

---

montecarlo/vmc/doc/index.md

Closes issue 458 on root-project/web

Fixed broken links in the VMC group

---

geom/geom/src/TGeoVolume.cxx

Clone also name in the reflected shape.

---

interpreter/cling/lib/Interpreter/DefinitionShadower.cpp

These changes allow the `DefinitionShadower` to shadow declarations whose first definition was possibly in a system header.
As discussed on ROOT's meeting last Monday, this should solve the problem of declaring a variable `data` that might conflict with `std::data` (by allowing `std::data` to be shadowed).
Additionally, this PR also fixes the handling of variable templates.

[cling] DefinitionShadower: allow shadowing of non-user-defined declarations

---

graf2d/win32gdk/gdk/src/gdk/win32/gdkdrawable-win32.c

The selected filling stipple was overflowing the combo box boundaries

Fix a long standing issue with stipple filling on Windows

---

hist/hist/inc/TAxis.h
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx

[RF][Docs] Documentation updates

---

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
tree/ntuple/v7/inc/ROOT/RNTupleDescriptor.hxx
tree/ntuple/v7/inc/ROOT/RNTupleMetrics.hxx
tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RNTupleDescriptor.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_descriptor.cxx

Preparation for the change set implementing the RNTuple merger (as sketched in #6105)

[ntuple] Various smaller improvements

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Mentioned on Gitter with @vgvassilev .

cmake: clad config failures shown on CMake 3.14+

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

Using this in conda-forge. Backport of #6816

backport: #6816 for 6.22

---

tutorials/eve7/error_ellipse.C
tutorials/eve7/event_demo.C

Eve-7 New macro to error_ellipse.C macro to demonstrate REveEllipsoid

---

roofit/CMakeLists.txt
roofit/roofit/CMakeLists.txt

I added an explanation of the roofit-arch-libs boolean in roofit/CMakeLists.txt. [skip-ci]

[RF] Improved CMake documentation for the `roofit-arch-libs` option.

---

core/base/src/TUrl.cxx

Fixes MT overhead of TChain::Add

[core] Reduce lock contention in TUrl::GetSpecialProtocols().

---

js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.geoworker.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.openui5.js
js/scripts/JSRoot.tree.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
js/scripts/JSRootCore.js

Fix cont drawing when contours are not closed
Fix I/O for std::map
Let use JSROOT from web server together with web widgets
Fix geoworker.js script
Add ZSTD support
Many improvements concerning Promise usage in internal API

[jsroot] dev 25/11/2020 [skip-ci]

---

core/metacling/src/TCling.cxx

Walking the dyld map manually is missing the libc lock. Instead, use the
official interface for this. Make sure that any call to UpdateListOfLoadedSharedLibraries
is actually locked by gInterpreterMutex.

[metacling] Use dl_iterate_phdr() to collect shlibs, fixes #6797:

---

tree/dataframe/inc/ROOT/RDFHelpers.hxx

[DF][NFC][skip-ci] Document that SaveGraph ignores hanging Define nodes

---

tree/dataframe/inc/ROOT/RDF/RLoopManager.hxx
tree/dataframe/src/RDFGraphUtils.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_helpers.cxx

[DF] Fix ROOT-9977, empty SaveGraph output in some cases

---

tree/dataframe/inc/ROOT/RDF/RBookedDefines.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/src/RDFBookedDefines.cxx

Really just a clean-up kind of patch.

[DF] Comments and refactoring around RBookedDefines

---

tutorials/roostats/StandardHypoTestDemo.C

Fixing a few typos in comments of StandardHypoTestDemo.C

Fixing a few typos in comments of StandardHypoTestDemo.C

---

README/ReleaseNotes/v618/index.md

[RelNotes] Clarify statement in 6.18 release notes.

---

roofit/roofitcore/src/RooBinSamplingPdf.cxx
roofit/roofitcore/src/RooNLLVar.cxx
roofit/roofitcore/src/RooPlot.cxx

In preparing a paper about recent RF developments, I improved plotting a bit.

[RF] Optimise plots of RooBinSamplingPdf

---

tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
tree/ntuple/v7/inc/ROOT/RColumnModel.hxx
tree/ntuple/v7/src/RColumnElement.cxx
tree/ntuple/v7/src/RNTupleDescriptorFmt.cxx

Picks up a discussion in #6756

[ntuple] Add static method to access on-disk size of column elements

---

tmva/tmva/inc/TMVA/RTensor.hxx

This should fix Copy, Transpose, Squeeze, ExpandDims, and Reshape for const RTensor.

[TMVA] Fix tensor operations for const RTensor

---

io/io/CMakeLists.txt
tree/ntuple/v7/inc/ROOT/RNTupleMetrics.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_metrics.cxx
tree/ntuple/v7/test/ntuple_test.hxx

Continuation of https://github.com/root-project/root/pull/6896

Implement calculated RNTuple metrics (and fix uring linking), v2

---

js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.jq2d.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.tree.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
js/scripts/JSRoot.v7hist3d.js
js/scripts/JSRoot.webwindow.js
tutorials/http/httptextlog.js

These are new problems, were introduced by jsroot v5->v6 transition
Plus continues with naming convention

[jsroot] fix several problems in sub-pads drawing [skip-ci]

---

roofit/roofitcore/src/RooAbsArg.cxx

[RF][Docs] Fix docs of RooAbsArg.

---

core/cont/inc/TVirtualCollectionProxy.h
core/meta/inc/TClass.h
core/meta/inc/TVirtualArray.h
core/meta/src/TClass.cxx
io/io/inc/TEmulatedCollectionProxy.h
io/io/inc/TStreamerInfo.h
io/io/src/TStreamerInfo.cxx
io/io/src/TStreamerInfoWriteBuffer.cxx
tree/tree/src/TBranchElement.cxx

v6-22 thread object repository scaling improvement

---

tree/tree/src/TTree.cxx

Better formatting & fixing a few typos

Better formatting of the documentation on saving the result of TTree::Draw to a histogram

---

bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx

Fixes #6345 .
This PR changes the way base-class protected methods are handled in the
Dispatcher class in cross inheritance. Instead of exposing them with a "using"
declaration in the Dispatcher class, they are redeclared and the call is forwarded
to the base class. This prevents the issues described in #6345 , when:
- There is more than one protected overload of a method
- There is a protected and a private overload of a method
Adapted from cppyy's:
https://bitbucket.org/wlav/cpycppyy/commits/1f158f4ad7cbe9951f43d24a217e60c009dd046c
for the case of just one base class.

[PyROOT][6345] Fix for protected methods in cross inheritance

---

tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RLoopManager.cxx

Now using the new and improved RLogger!

[DF] Log begin/end of event loop and processing of each entry range

---

roofit/roofitcore/inc/RooAbsReal.h

i made changes in spell mistake for line 389 of word analytical

spell correction

---

graf3d/eve7/inc/ROOT/REveCaloData.hxx
graf3d/eve7/src/REveCalo.cxx
graf3d/eve7/src/REveCaloData.cxx
graf3d/eve7/src/REveDataCollection.cxx
graf3d/eve7/src/REveManager.cxx
graf3d/eve7/src/REveTableInfo.cxx
graf3d/eve7/src/REveTableProxyBuilder.cxx
tutorials/eve7/collection_proxies.C
ui5/eve7/controller/EveTable.controller.js

* Add check for empty tables (without column definition or empty collection)
* Introduce slice selector for use of different collection types in calorimeter representations
* Catch exceptions in REveManager::WindowData()

Eve-7 Add necessary checks  for the use in CMS web event display

---

core/dictgen/src/rootcling_impl.cxx
math/genetic/CMakeLists.txt
tmva/tmva/CMakeLists.txt

Do not build a cuda module as TMVA does not need it anymore.

---

gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
gui/webdisplay/src/RWebDisplayArgs.cxx
js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.painter.js
tutorials/webgui/qt5web/ExampleWidget.cpp
tutorials/webgui/qt5web/ExampleWidget.h
tutorials/webgui/qt5web/ExampleWidget.ui
tutorials/webgui/qt5web/Makefile
tutorials/webgui/qt5web/RCanvasWidget.cpp
tutorials/webgui/qt5web/RGeomViewerWidget.cpp
tutorials/webgui/qt5web/RGeomViewerWidget.h
tutorials/webgui/qt5web/TCanvasWidget.cpp
tutorials/webgui/qt5web/qt5web.pro

Also provide final JSROOT 6.0.0

[qt5web] Add geometry viewer to tutorial

---

core/imt/inc/ROOT/TExecutor.hxx

To not rely on cpp macros rewriting code.
Suggested by Axel in https://github.com/root-project/root/issues/7039

improve defines on TExecutor [https://github.com/root-project/root/issues/7039]

---

tutorials/CMakeLists.txt
tutorials/tmva/PyTorch_Generate_CNN_Model.py
tutorials/tmva/TMVA_CNN_Classification.C

Re-add pytorch model building file that was removed by mistake in  a previous commit and move it in pytorch sub-diretory

Add missing pytorch model building file for TMVA_CNN_Classification tutorial

---

core/imt/inc/ROOT/TExecutor.hxx

Remove unnecessary private chunking Map methods from TExecutor

---

core/base/inc/TVirtualPerfStats.h
proof/proofplayer/inc/TPerfStats.h
tree/tree/src/TChain.cxx
tree/treeplayer/inc/TTreePerfStats.h
tree/treeplayer/src/TTreePerfStats.cxx

Related to https://sft.its.cern.ch/jira/browse/ROOT-5079.

Add TChain support in TTreePerfStats.

---

hist/hist/src/THStack.cxx

The THStack specific drawing options were not easy to find.

clarify THStack drawing options

---

net/http/src/TFastCgi.cxx

Need to be compiled also with c++11 (without root7)

[http] add ROOT/MakeUnique.hxx to fastcgi

---

tree/tree/inc/TBranchBrowsable.h
tree/tree/src/TBranchBrowsable.cxx

Use comments supported by doxygen
Provide "override" specifier for virtual methods

[tree] adjust TBranchBrowsable code formatting

---

gui/browsable/inc/ROOT/Browsable/RItem.hxx
gui/browsable/inc/ROOT/Browsable/RLevelIter.hxx
gui/browsable/inc/ROOT/Browsable/RProvider.hxx
gui/browsable/inc/ROOT/Browsable/TObjectElement.hxx
gui/browsable/src/RGroup.cxx
gui/browsable/src/RLevelIter.cxx
gui/browsable/src/RProvider.cxx
gui/browsable/src/RSysFile.cxx
gui/browsable/src/TBranchBrowseProvider.cxx
gui/browsable/src/TDirectoryElement.cxx
gui/browsable/src/TLeafDraw6Provider.cxx
gui/browsable/src/TLeafDraw7Provider.cxx
gui/browsable/src/TLeafProvider.hxx
gui/browsable/src/TObjectElement.cxx
gui/browserv7/src/RBrowser.cxx
gui/browserv7/src/RBrowserGeomWidget.cxx
ui5/browser/browser.html
ui5/browser/controller/Browser.controller.js

1. Support drawing of `TGeoVolume`
2. Correctly browse and draw `TBranchBrowsable` object (appears when browsing TBranch)
3. Provide title for items in the RBrowser    
4. Load RCanvas/TCanvas code on client side only when required
5. Several API adjustments in `RBrowsable`

RBrowser improvments

---

sql/pgsql/inc/TPgSQLStatement.h
sql/pgsql/src/TPgSQLStatement.cxx

Fixing issue #7127.
Plus two small bugfixes

[pgsql] Use binary buffer to set binary data

---

sql/pgsql/inc/TPgSQLStatement.h
sql/pgsql/src/TPgSQLStatement.cxx

Fix TPgSQLStatement::SetBinary v6.22

---

graf3d/eve7/inc/ROOT/REveDataCollection.hxx
graf3d/eve7/inc/ROOT/REveManager.hxx
graf3d/eve7/src/REveDataCollection.cxx
graf3d/eve7/src/REveDataProxyBuilderBase.cxx
graf3d/eve7/src/REveDataSimpleProxyBuilder.cxx
tutorials/eve7/collection_proxies.C
ui5/eve7/controller/EveTable.controller.js
ui5/eve7/lib/EveScene.js
ui5/eve7/lib/GlViewerThree.js

These changes are needed for use of CMS web event display.

Eve-7 Additional checks and minor corrections

---

hist/hist/src/TH1.cxx

[skip-ci]
Pls approve and merge without my assistance.

[Docs] Add missing documentation to TH1 functions.

---

montecarlo/vmc/src/TGeoMCGeometry.cxx

Not very important, just stumbled upon it randomly. Might aswell fix it.

Spelling Mistake

---

README/ReleaseNotes/v624/index.md
net/davix/inc/TDavixFile.h
net/davix/src/TDavixFile.cxx

Discovery schema: https://github.com/WLCG-AuthZ-WG/bearer-token-discovery/blob/master/specification.md
(adopted based on the implementation in htcondor/htcondor.git by @bbockelm)
Fixes: https://github.com/root-project/root/issues/6802
(based on https://github.com/root-project/root/pull/6818)

Add support for WLCG Bearer tokens

---

tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TTreeReader.cxx

Include two new status values, may cause problem when
showing error messages for such value

[treereader] extend fgEntryStatusText array

---

graf3d/eve7/src/REveJetCone.cxx
ui5/eve7/controller/GL.controller.js
ui5/eve7/lib/EveElements.js
ui5/eve7/lib/EveElementsRCore.js
ui5/eve7/lib/GlViewer.js
ui5/eve7/lib/GlViewerJSRoot.js
ui5/eve7/lib/GlViewerRCore.js
ui5/eve7/lib/GlViewerThree.js
ui5/eve7/lib/RendeQuTor.js
ui5/eve7/shaders/custom/copyDepth2RReve.frag
ui5/eve7/shaders/custom/copyDepth2RReve.vert
ui5/eve7/shaders/custom/highPassReve.frag
ui5/eve7/shaders/custom/highPassReve.vert
ui5/eve7/shaders/custom/lowPassReve.frag
ui5/eve7/shaders/custom/lowPassReve.vert
ui5/eve7/shaders/programs.json

Picking, lights, render-queue/multi-pass rendering, support for most EveElements.

[REve] RenderCore integration

---

tutorials/eve/MultiView.C
tutorials/eve/alice_esd.C
tutorials/eve/run_alice_esd.C

Simply load MultiView.C macro and does not try to compile it
It only defines some simple service GUI structures

[eve] adjust alice_esd.C macro [skip-ci]

---

graf2d/gpad/inc/TButton.h
graf2d/gpad/inc/TCanvas.h
graf2d/gpad/inc/TColorWheel.h
graf2d/gpad/inc/TDialogCanvas.h
graf2d/gpad/inc/TGroupButton.h
graf2d/gpad/inc/TPad.h
graf2d/gpad/inc/TRatioPlot.h
graf2d/gpad/inc/TSlider.h
graf2d/gpad/inc/TViewer3DPad.h
graf2d/gpad/src/TDialogCanvas.cxx
graf2d/gpad/src/TPaveClass.cxx
graf2d/gpad/src/TSliderBox.cxx
graf2d/gpad/src/TView.cxx
graf2d/gpad/src/TViewer3DPad.cxx

* use override declarations in TPad.h and TCanvas.h
* mark non-implemented copy constructors as deleted
* use in some headers **nullptr**

Modernize gpad classes

---

core/base/inc/TQObject.h
core/base/src/TQObject.cxx
documentation/users-guide/WritingGUI.md
gui/gui/inc/TGComboBox.h
gui/gui/src/TGComboBox.cxx

* New signal added to TGComboBox
* Document also better the signal slot mechanism with arguments passed by value
* Fix a couple of typos in the documentation
Fixes https://github.com/root-project/root/issues/7195

Emit a Changed() signal on TGComboBox whenever entry changes

---

tree/dataframe/inc/ROOT/RResultPtr.hxx
tree/dataframe/test/dataframe_resptr.cxx

Dear Mentor,
Here's my pull request for the issue https://github.com/root-project/root/issues/7047.
Can you please review this. I will squash the commits after the review.
Thanks in advance !
@eguiraud

RResultPtr<T>::Release method added to RResultPtr.hxx

---

core/gui/inc/GuiTypes.h

Change the comments format to make them visible in the ref guide.

Use INT_MAX

---

roofit/roofitcore/inc/RooVDTHeaders.h

[RF] Bugfix in RooVDTHeaders.h.

---

hist/hist/src/TH1.cxx
hist/hist/src/TH2.cxx
hist/hist/src/TH3.cxx

use INT_MAX in TH classes

---

core/base/src/TString.cxx
core/base/test/CMakeLists.txt
core/base/test/TStringTest.cxx

Sorry, this is my third PR on this subject.
This patch will fix [this](https://github.com/root-project/root/issues/6748) issue.

Fixed TString File

---

ui5/eve7/controller/EveTable.controller.js
ui5/eve7/controller/Main.controller.js
ui5/eve7/css/eve.css
ui5/eve7/lib/EveManager.js
ui5/eve7/lib/EveScene.js
ui5/eve7/lib/GlViewerThree.js
ui5/eve7/lib/OutlinePass.js
ui5/eve7/view/Main.view.xml

This PR adds a message viewing accessible through top left  menu.
At the moment the view content is browser console messages and a checkbox to enable/disable debug mode.
There are also minor changes in log messages and additional try/catch blocks.

Eve-7 The first implementation of log view

---

tree/dataframe/inc/ROOT/RResultPtr.hxx
tree/dataframe/test/dataframe_resptr.cxx

Return false/nullptr if the object is inspected, throw if a method
is called that requires a non-null RResultPtr as pre-condition.
This is consistent with the behavior of shared_ptr, minus the
undefined behavior.

[DF] Make semantics of null RResultPtrs more consistent 

---

ui5/eve7/lib/GlViewerThree.js

[eve7] fix three.js warnings [skip-ci]

---

tree/tree/src/TTree.cxx

See https://root-forum.cern.ch/t/serious-degradation-of-i-o-performance-from-6-20-04-to-6-22-06/43584/10

Shortcut in TTree::GetBranch for exact match to top level branches

---

core/meta/src/TEnum.cxx
core/metacling/src/TCling.cxx

Fix #7093: race condition tripping TEnum::GetEnum

---

gui/webgui6/src/TWebCanvas.cxx
js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.interactive.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.menu.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.painter.js

Update JSROOT, where TRatioPlot now supported
Make use of functionality: https://jsroot.gsi.de/dev/examples.htm#tratioplot_r6

[webcanvas] Add TRatioPlot to list of supported classes

---

hist/hist/inc/TGraph.h
hist/hist/src/TGraph.cxx

Cloned histogram should not be assign to current directory

Fix TGraph copy constructor and assign operator (#7302)

---

html/src/THtml.cxx

As requested her : https://github.com/root-project/root/issues/7295

Make clear THtml is legacy code

---

tutorials/tmva/keras/ClassificationKeras.py
tutorials/tmva/keras/MulticlassKeras.py
tutorials/tmva/keras/RegressionKeras.py

Updating the usage of the Keras package to the presumable most commonly used version in tensorflow itself. Also updating the API to be compatible with keras2.

[TMVA] Update Keras tutorials using tensorflow.keras

---

interpreter/cling/tools/plugins/clad/CMakeLists.txt

[clad] Allow building clad as a cling plugin via -DCLING_BUILD_PLUGINS=On

---

gui/browsable/src/TObjectElement.cxx

Let show images, stored in ROOT file, in TWebCanvas

[webgui] mark TASImage as supported class in RBrowser

---

gui/browsable/src/TObjectElement.cxx

Let show images, stored in ROOT file, in TWebCanvas

[webgui] mark TASImage as supported class in RBrowser, backport 6.24

---

ui5/eve7/controller/EveTable.controller.js
ui5/eve7/controller/Main.controller.js
ui5/eve7/manifest.json
ui5/eve7/view/Main.view.xml

This change can be tested only in collection_proxies.C demo.

Eve-7 Enable routing to table views

---

proof/proof/src/TProof.cxx

doxygen flag "deprecated" on PROOF

Add deprecated flag on PROOF

---

tree/tree/src/TChain.cxx

[TChain] Do not try to look up index when loading non-existing entries

---

tree/tree/src/TChain.cxx

[TChain] Do not try to look up index when loading non-existing entries (v6.24)

---

core/dictgen/src/rootcling_impl.cxx

Enables incremental builds again

[rootcling] add extra check for MathCore dependency from Vc

---

core/base/src/TSystem.cxx

ACLiC: enable O *and* g

---

bindings/CMakeLists.txt
bindings/experimental/distrdf/CMakeLists.txt
bindings/experimental/distrdf/test/backend/CMakeLists.txt
cmake/modules/FindPySpark.cmake
cmake/modules/RootBuildOptions.cmake
cmake/modules/SearchInstalledSoftware.cmake

Adding https://github.com/root-project/root/pull/7371 to master as well

Add distributed RDataFrame pyspark build option

---

roofit/roofitcore/src/RooNLLVar.cxx

In the case of unweighted datasets, the current implementation of
`RooNLLVar::computeBatched` retreived the weight for every event with
`RooDataSet::get()`. This has a lot of overhead and significantly slows
down the evaluation.
With this commit, it is correctly assumed that the weight is the same
for every event. This has been done in the code already before but it
was changed accidentally in 0e7c394.
Hence, this commit partially reverts the changes made in commit 0e7c394.

[RF] Assume uniform weights in computeBatched if weights vector is empty

---

roofit/batchcompute/src/Initialisation.cxx

When RooFit starts for the first time it automatically loads the most optimal batch computation library. In response to issue #7361 I introduce an environment variable that permits the user to explicitly select the library to be used.

Pin the Roofit batch computation library to be used.

---

tree/dataframe/src/RDFInterfaceUtils.cxx
tree/dataframe/test/dataframe_friends.cxx
tree/tree/inc/TFriendElement.h

Fixes and adds a test for #7181.

[DF] Snapshot friend branches also when a branch with same name exists

---

README/ReleaseNotes/v624/index.md
roofit/roofit/src/RooParamHistFunc.cxx
roofit/roofitcore/inc/RooAddModel.h
roofit/roofitcore/inc/RooAddPdf.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooHistPdf.h
roofit/roofitcore/inc/RooProdPdf.h
roofit/roofitcore/inc/RooProduct.h
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooHistFunc.cxx
roofit/roofitcore/src/RooHistPdf.cxx
roofit/roofitcore/test/testRooDataHist.cxx
roofit/roostats/inc/RooStats/MCMCInterval.h

This PR fixes several issues/Jira tickets, maybe even more:
* https://sft.its.cern.ch/jira/browse/ROOT-10483
* https://sft.its.cern.ch/jira/browse/ROOT-7413
* https://github.com/root-project/root/issues/7182

[RF] Correct the handling of bin volumes in RooDataHist::sum()

---

README/ReleaseNotes/v624/index.md

[skip-ci]
Pretty much all things worth mentioning that came out of
`git log $(git merge-base master v6-22-00)..$(git merge-base master v6-24-00-rc1) roofit/`

[RelNotes] Update release notes for RooFit.

---

interpreter/cling/CMakeLists.txt

[cling] Install the modulemap files

---

README/ReleaseNotes/v624/index.md

[RelNotes] Backport small tweaks for RF-related release notes.

---

roofit/batchcompute/inc/RooBatchCompute.h
roofit/batchcompute/inc/RooVDTHeaders.h
roofit/batchcompute/inc/RunContext.h
roofit/batchcompute/src/Initialisation.cxx
roofit/batchcompute/src/RooBatchCompute.cxx
roofit/batchcompute/src/RunContext.cxx

[skip-ci]
Some documentation updates to populate empty doxygen pages.

[RF][Docs] Documentation updates for RooFit

---

roofit/batchcompute/inc/RooBatchCompute.h
roofit/batchcompute/inc/RooVDTHeaders.h
roofit/batchcompute/inc/RunContext.h
roofit/batchcompute/src/Initialisation.cxx
roofit/batchcompute/src/RooBatchCompute.cxx
roofit/batchcompute/src/RunContext.cxx

(cherry picked from commit 549629aa0815cb3ba5d0f1d2f5863597a712458a)

[RF][Docs] Improve doxygen reference of objects in roofit/batchcompute.

---

core/base/src/TQCommand.cxx

Wrong delete operator for array

Fix memory leak in TQCommand

---

roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
roofit/histfactory/src/FlexibleInterpVar.cxx
roofit/roofitcore/inc/RooAbsReal.h
roofit/roofitcore/inc/RooArgList.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooDerivative.h
roofit/roofitcore/inc/RooTemplateProxy.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooArgList.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooFFTConvPdf.cxx
roofit/roofitcore/src/RooHist.cxx
roofit/roofitcore/src/RooHistFunc.cxx
roofit/roofitcore/src/RooNLLVar.cxx

In working on the HistFactory, there were many small things that I encountered on the way.
This is a collection of fixes, modernisations, improved warnings, better error handling and similar small things.
This is step 1 flushing those from the branch before actually putting up the histfactory stuff.

[RF] Many small updates/fixes

---

gui/browsable/CMakeLists.txt
gui/browsable/inc/ROOT/Browsable/RProvider.hxx
gui/browsable/src/RFieldHolder.hxx
gui/browsable/src/RFieldProvider.hxx
gui/browsable/src/RNTupleBrowseProvider.cxx
gui/browsable/src/RNTupleDraw6Provider.cxx
gui/browsable/src/RNTupleDraw7Provider.cxx
gui/browsable/src/RNTupleProvider.cxx
gui/browsable/src/RProvider.cxx
gui/browsable/src/TDirectoryElement.cxx
gui/browsable/src/TLeafDraw6Provider.cxx
gui/browsable/src/TLeafDraw7Provider.cxx
gui/browsable/src/TLeafProvider.hxx

Provide necessary components in RBroesable classes to browse RNTuple and implement basic draiwing using TH1F class

RNTuple support in RBrowser

---

core/meta/src/TDataMember.cxx
gui/gui/src/TGButton.cxx
gui/gui/src/TGListView.cxx
gui/sessionviewer/src/TProofProgressLog.cxx
hist/hist/src/THnBase.cxx
net/alien/src/TAlienFile.cxx
roofit/roofitcore/src/RooMappedCategory.cxx
roofit/roostats/src/MCMCInterval.cxx
tmva/tmva/src/MethodCategory.cxx
tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx

Fix potential double-deletion of objects in ROOT

---

gui/gui/inc/TGTab.h
gui/gui/src/TGTab.cxx

For fast/easy switching between tabs. Quite useful when you want to compare two very similar canvases on each tab, to see the differences.
As implemented e.g. in Firefox.

TGTab: support tab scrolling with mouse wheel

---

graf2d/gpadv7/inc/ROOT/RPadLength.hxx
roofit/roostats/src/SPlot.cxx
tmva/tmva/src/ROCCurve.cxx
tree/tree/src/TEntryListBlock.cxx

Fix small issues reported by DeepCode

Properly use boolean values in ROOT

---

graf2d/cocoa/inc/QuartzWindow.h
graf2d/cocoa/inc/X11Buffer.h
graf2d/cocoa/src/QuartzWindow.mm
graf2d/cocoa/src/TGCocoa.mm
graf2d/cocoa/src/TGQuartz.mm
graf2d/cocoa/src/X11Buffer.mm
gui/fitpanel/src/TFitEditor.cxx

Because the XOR mode was not properly implemented on Cocoa the fit panel range di not work.
This problem was mentioned here: https://root-forum.cern.ch/t/bugs-in-tfit-errors-when-trying-to-fit-a-histogram/43789
Am issue was open there: https://github.com/root-project/root/issues/7340
The fix was provided by Timur

Fit panel range did not work on Cocoa

---

documentation/doxygen/Doxyfile

"gui" folder should be fully in INPUT (in Doxyfile)

Entire GUI folder should be in INPUT

---

tree/tree/src/TEntryList.cxx
tree/tree/src/TEntryListArray.cxx
tree/tree/src/TLeaf.cxx
tree/tree/src/TTreeCacheUnzip.cxx

Discovered by clang-tidy #7429 
Plus few minor fixes tree sources

Fix memory leak in TTreeCacheUnzip

---

roofit/roofit/doc/index.md
roofit/roofitcore/doc/index.md
roofit/roofitcore/inc/RooGlobalFunc.h

fix dead link

---

interpreter/cling/test/CodeUnloading/RunAgainstClangTestSuite/RunAgainstClangTestSuite.C
interpreter/cling/test/lit.cfg

https://github.com/root-project/root/pull/7514 for v6.24.

Bring `vanilla_cling` lit feature back: v624

---

interpreter/cling/lib/Interpreter/ClingPragmas.cpp
interpreter/cling/test/Pragmas/load.C
interpreter/cling/test/Pragmas/multiArgument.C

https://github.com/root-project/root/pull/7509 for v6.24

 Fix diagnostics for `cling pragma load` with missing library

---

io/sql/src/TBufferSQL2.cxx
io/sql/src/TSQLFile.cxx
io/xml/src/TBufferXML.cxx
io/xml/src/TXMLEngine.cxx
io/xml/src/TXMLFile.cxx
io/xml/src/TXMLPlayer.cxx

Plus fix several places found with clang-tidy in #7431

Fix allocated memory size in TBufferXML, TBufferSQL2 methods

---

graf2d/graf/src/TCandle.cxx
graf2d/graf/src/TCurlyLine.cxx
graf2d/graf/src/TGaxis.cxx
graf2d/graf/src/TLegend.cxx
graf2d/graf/src/TPaveStats.cxx
graf2d/graf/src/TPaveText.cxx
graf2d/graf/src/TPie.cxx
graf2d/postscript/src/TPDF.cxx
graf2d/postscript/src/TSVG.cxx
graf2d/postscript/src/TTeXDump.cxx

Lot of unused code / unused values
Plus small fix in TPaveStats text parsing

Remaining clang-tidy issues in graf2d classes 

---

tree/tree/src/TEntryList.cxx
tree/tree/src/TEntryListArray.cxx
tree/tree/src/TLeaf.cxx
tree/tree/src/TTreeCacheUnzip.cxx

Fix memory leak in TTreeCacheUnzip [6.24]

---

graf2d/asimage/src/TASImage.cxx
net/httpsniff/src/TRootSnifferFull.cxx

Fix memory leak in TASImage::GetImageBuffer, 6.24

---

js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geobase.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.jq2d.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.math.js
js/scripts/JSRoot.menu.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.openui5.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.tree.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
js/scripts/JSRoot.v7hist3d.js
js/scripts/JSRoot.webwindow.js

Resolve majority of warnings from lgtm.com analyzer
Fix bug with MathJax loading

[jsroot] dev 16/03/2021 [skip-ci]

---

README/ReleaseNotes/v624/index.md
roofit/batchcompute/README.md
roofit/roofitcore/inc/RooAbsReal.h

[RF] Add instructions for writing custom PDFs in the BatchCompute library.

---

tree/ntuple/v7/src/RPageStorageFile.cxx

plus two minor clang-reported issues.

[ntuple] fix memory leak in page decompression

---

html/inc/TDocParser.h
html/src/TClassDocOutput.cxx
html/src/TDocDirective.cxx

Fix clang-tidy issues in html classes

---

tree/tree/src/TLeaf.cxx

Leaf name with dot was not properly tested

Fix TLeaf::GetLeafCounter function

---

tree/tree/src/TLeaf.cxx

Leaf name with dot was not properly tested

Fix TLeaf::GetLeafCounter function, 6.22

---

tree/tree/src/TLeaf.cxx

Leaf name with dot was not properly tested

Fix TLeaf::GetLeafCounter function, 6.24

---

core/base/inc/TDirectory.h

Improve TContext doc as requested here: https://github.com/root-project/root/issues/6500

Improve TContext doc

---

math/vecops/inc/ROOT/RVec.hxx
math/vecops/test/vecops_rvec.cxx

[VecOps] Add Argsort with custom comparator

---

gui/browsable/src/RProvider.cxx
gui/webgui6/src/TWebCanvas.cxx

Solves correspondent warnings from #7533

Fix clang-tidy issues in webgui

---

graf3d/eve7/src/REveCalo.cxx

[eve7] fix memory leak in REveCalo

---

core/clingutils/src/TClingUtils.cxx
core/metacling/src/TCling.cxx
core/metacling/src/TCling.h
interpreter/cling/lib/Interpreter/IncrementalParser.cpp
interpreter/cling/lib/Interpreter/Interpreter.cpp
interpreter/cling/lib/Interpreter/LookupHelper.cpp
interpreter/cling/test/Lookup/template.C

v6.24 version of https://github.com/root-project/root/pull/6880

Fix ROOT-10895: accelerate DeepAutoLoadImpl() [v6.24]

---

hist/hist/src/AnalyticalIntegrals.cxx
hist/hist/src/HFitImpl.cxx
hist/hist/src/TF1.cxx
hist/hist/src/TFormula.cxx
hist/hist/src/TH1Merger.cxx
hist/histpainter/src/THistPainter.cxx

Fing clang-tidy issues in hist classes

---

tmva/tmva/inc/TMVA/DNN/Minimizers.h
tmva/tmva/src/DataLoader.cxx
tmva/tmvagui/src/likelihoodrefs.cxx

Fix several calng-tidy warnings in TMVA

---

gui/guihtml/src/TGHtmlUri.cxx

Simplify complex code to build URI string from components

[guihtml] add missing strlcpy.h include

---

net/auth/src/TAuthenticate.cxx
net/net/src/TNetFile.cxx
net/net/src/TSQLMonitoring.cxx
net/net/src/TWebFile.cxx
net/rpdutils/src/net.cxx

Fixes #7528 
Civetweb not touched, need to be updated soon anyway

Fix clang-tidy issues in net classes

---

roofit/histfactory/inc/RooStats/HistFactory/RooBarlowBeestonLL.h
roofit/histfactory/src/ConfigParser.cxx
roofit/histfactory/src/HistFactoryModelUtils.cxx
roofit/histfactory/src/HistFactoryNavigation.cxx
roofit/histfactory/src/HistoToWorkspaceFactory.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/histfactory/src/RooBarlowBeestonLL.cxx
roofit/roofitcore/inc/RooCacheManager.h
roofit/roofitcore/src/RooAbsTestStatistic.cxx

Also apply several fixes according clang-tidy warnings from #7536

Fix several memleaks in histfactory

---

roofit/batchcompute/inc/RooSpan.h
roofit/roofitcore/src/BidirMMapPipe.cxx
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooBinning.cxx
roofit/roofitcore/src/RooCategory.cxx
roofit/roofitcore/src/RooLinkedList.cxx
roofit/roofitcore/src/RooMsgService.cxx
roofit/roofitcore/src/RooWorkspace.cxx
roofit/roostats/src/AsymptoticCalculator.cxx

Each commit address its own issue.
Please revise each commit separately and prove that my understanding of code correct.
There is at least one memory leak fix https://github.com/root-project/root/commit/be2464ca3655898d871ebef9a14a1cddbf1e2554

Address several RooFit issues found by clang-tidy

---

core/dictgen/src/rootcling_impl.cxx

`using namespace std` can have detrimental side effects on user headers.
Assume that they are compilable, given that they will be included in the
dictionary source. Given this, move the using directive after the inclusion
of user headers, to not affect them, but only the generated dictionary
source code (CINT-compatible std-less type names etc).

[rootcling] Emit using std after user headers, fixes #6343:

---

tree/ntuple/v7/inc/ROOT/RCluster.hxx
tree/ntuple/v7/inc/ROOT/RColumnElement.hxx
tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RMiniFile.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_zip.cxx

Follow up from a [review comment](https://github.com/root-project/root/pull/6106/files#r543642592) in #6106

[ntuple] Factor out sealing and unsealing of pages

---

bindings/pyroot/pythonizations/src/TDirectoryPyz.cxx
bindings/pyroot/pythonizations/src/TTreePyz.cxx
tree/dataframe/src/RDataFrame.cxx

[Doc][NFC] Fix Python syntax highlighting

---

js/changes.md
js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geobase.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.jq2d.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.math.js
js/scripts/JSRoot.menu.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.openui5.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.tree.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
js/scripts/JSRoot.v7hist3d.js
js/scripts/JSRoot.webwindow.js

Add new draw options for TGraph/TMultiGraph

[jsroot] update 6.24 with many fixes [skip-ci]

---

js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.math.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.tree.js

Do not draw TFrame for TASImage if not used
Provide gridx/y, logx/y, tickx/y for graphs
Use proper methods to identify Array
Fixing several lgtm.com warnings

[jsroot] dev 23/03/2021 [skip-ci]

---

cmake/modules/RootConfiguration.cmake
config/rootrc.in

ROOT should be compiled with webgui and root7 options

Show RBrowser when TBrowser is invoked in the ROOT

---

roofit/roofitcore/inc/RooSimPdfBuilder.h
roofit/roofitcore/src/RooSimPdfBuilder.cxx
roofit/roofitcore/test/CMakeLists.txt
roofit/roofitcore/test/testRooSimPdfBuilder.cxx

* modernize RooSimPdfBuilder
* fix documentation
* add test for RooSimPdfBuilder
* fix logic error reported in https://github.com/root-project/root/issues/7481
The `RooSimPdfBuilder` is superseeded by the RooSimWSTool, but I still think it's a good idea to update this class which might still be used in the wild.

[RF] Modernize RooSimPdfBuilder, fix a logic error and implement test

---

tree/tree/src/TSelector.cxx
tree/treeplayer/src/TBranchProxy.cxx
tree/treeplayer/src/TBranchProxyClassDescriptor.cxx
tree/treeplayer/src/TBranchProxyDescriptor.cxx
tree/treeplayer/src/TBranchProxyDirector.cxx
tree/treeplayer/src/TFileDrawMap.cxx
tree/treeplayer/src/TFormLeafInfo.cxx
tree/treeplayer/src/TFormLeafInfoReference.cxx
tree/treeplayer/src/TFriendProxyDescriptor.cxx
tree/treeplayer/src/TMPWorkerTree.cxx
tree/treeplayer/src/TSelectorEntries.cxx
tree/treeplayer/src/TTreeFormula.cxx
tree/treeplayer/src/TTreeIndex.cxx
tree/treeplayer/src/TTreeProxyGenerator.cxx
tree/treeplayer/src/TTreeReader.cxx
tree/treeplayer/src/TTreeReaderGenerator.cxx

Update TSelector doc according to https://sft.its.cern.ch/jira/browse/ROOT-3992

update tselector doc

---

tree/dataframe/src/RDataFrame.cxx

Backport of https://github.com/root-project/root/pull/7664

[skip-ci][backport][DF] Add a section about distributed rdf in doxygen page

---

README/ReleaseNotes/v624/index.md
README/ReleaseNotes/v626/index.md

[relnotes][skip-ci] Mention deprecation of SetMaxTasksPerFilePerWorker

---

math/mathcore/inc/Math/IntegratorOptions.h
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooAbsReal.cxx
roofit/roofitcore/src/RooBinSamplingPdf.cxx

[RF][NFC] Improve documentation

---

tutorials/pyroot/numberEntry.py

[PyROOT] avoid using wildcard import in pyroot tutorial

---

README/ReleaseNotes/v624/index.md
core/thread/inc/ROOT/TReentrantRWLock.hxx
core/thread/src/TReentrantRWLock.cxx
core/thread/src/TThread.cxx
core/thread/test/testRWLock.cxx

- Some code formatting fixes
- Add myself to list of contributors for 624
- Add descriptions in the release notes related to the changes in:
https://github.com/root-project/root/pull/6857
https://github.com/root-project/root/pull/7105
https://github.com/root-project/root/pull/7260

Code formatting and release notes for recent lock contention improvements

---

README/ReleaseNotes/v624/index.md

This is a backport of the release notes updates contained in #7680 .

[relnotes][skip-ci] Backport some updates to v624

---

ui5/canv/controller/Ged.controller.js

do not use isNaN
Use proper method to change axis labels size
Discovered in DeepCode analyzer

[rcanvas] fix two issues in GED [skip-ci]

---

hist/hist/src/TH2Poly.cxx
hist/histpainter/src/THistPainter.cxx

- Implement option AXIS for TH2Poly as requested here https://github.com/root-project/root/issues/7673
- Fix typos

Implement option AXIS for TH2Poly

---

tree/tree/inc/TBranch.h
tree/tree/inc/TBranchCacheInfo.h
tree/tree/inc/TBranchClones.h
tree/tree/inc/TBranchElement.h
tree/tree/inc/TBranchObject.h
tree/tree/inc/TChain.h
tree/tree/inc/TChainElement.h
tree/tree/inc/TLeafObject.h
tree/tree/inc/TSelectorScalar.h
tree/tree/inc/TreeUtils.h
tree/tree/src/TBasket.cxx
tree/tree/src/TBranch.cxx
tree/tree/src/TBranchBrowsable.cxx
tree/tree/src/TBranchElement.cxx
tree/tree/src/TBranchIMTHelper.h
tree/tree/src/TBranchSTL.cxx
tree/tree/src/TChain.cxx
tree/tree/src/TEntryList.cxx
tree/tree/src/TEntryListArray.cxx
tree/tree/src/TEntryListFromFile.cxx
tree/tree/src/TEventList.cxx
tree/tree/src/TIOFeatures.cxx
tree/tree/src/TLeaf.cxx
tree/tree/src/TLeafObject.cxx
tree/tree/src/TQueryResult.cxx
tree/tree/src/TSelectorList.cxx
tree/tree/src/TSelectorScalar.cxx
tree/tree/src/TTreeCacheUnzip.cxx
tree/tree/src/TTreeSQL.cxx

A few doxygen and typos fixes in tree

A few doxygen and typos fixes in tree

---

roofit/roofitcore/src/RooChi2Var.cxx
roofit/roofitcore/src/RooPlot.cxx

[skip-ci]
Pls merge if you are happy with it.

[RF][Docs] Clarify documentation of chi2 calcuations.

---

io/io/src/TFileMerger.cxx

[v620][io] Correct cycle order in file merging for non-mergeable obj.

---

README/ReleaseNotes/v624/index.md

Added PyTorch TMVA Interface to release notes. PTAL @lmoneta

Add TMVA PyTorch Interface to Release Notes v6-24-00

---

io/io/inc/TFileMerger.h
io/io/src/TFileMerger.cxx

https://github.com/root-project/root/pull/7679
Fixes #7676

[v624][io] Correct cycle order in file merging for non-mergeable obj.

---

io/io/inc/TFileMerger.h
io/io/src/TFileMerger.cxx

https://github.com/root-project/root/pull/7679
Fixes #7676

[v622][io] Correct cycle order in file merging for non-mergeable obj.

---

tutorials/roofit/rf204a_extendedLikelihood.py

@guitargeek PR for the translated Tutorial file, completed as a part of the pre-exercise.

Translated the rf204a_extendedLikelihood.C example script from C++ to Python.

---

math/vecops/inc/ROOT/RVec.hxx

Fixes #7699
@couet This should work, right?
I followed the docs here: https://www.doxygen.nl/manual/grouping.html

[Doc][VecOps][NFC] Add all functions in VecOps to the Doxygen group

---

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C
tutorials/dataframe/df103_NanoAODHiggsAnalysis.py

[DF] Use RunGraphs in the tutorials df103*.(py|C)

---

bindings/experimental/distrdf/python/DistRDF/Backends/Spark/Backend.py

skip-ci
Backport of https://github.com/root-project/root/pull/7705

[DF] Use ImportError for Python2 compatibility

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roopythonize.py
bindings/pyroot/pythonizations/test/roofit/rooabsreal_ploton.py

@guitargeek PR for pythonization and test for RooAbsReal::plotOn() Pythonization

Pythonization for RooAbsReal::plotOn() RooAbsPdf::fitTo() functions.

---

tutorials/CMakeLists.txt
tutorials/dataframe/distrdf001_spark_connection.py

backport of https://github.com/root-project/root/pull/7698

[DF] Add first tutorial for distributed rdf

---

io/io/inc/TStreamerInfoActions.h
io/io/src/TStreamerInfoActions.cxx
tree/tree/src/TBranchElement.cxx

It was using the wrong signature leading to the configuration to be mis-read.
Fixes #7754

Fix the action PushDataCache for TClonesArray.

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py

Backport of https://github.com/root-project/root/pull/7769

[skip-ci] [DF] Lazily import numpy in distributed reduce step

---

bindings/experimental/distrdf/python/DistRDF/Operation.py
bindings/experimental/distrdf/test/test_operation.py

Backport of https://github.com/root-project/root/pull/7772

[skip-ci] [DF] Remove enum from distributed RDataFrame

---

core/metacling/src/TCling.cxx

[cxxmodules] Do not push a transaction per LoadModule.
Prior to this patch, we push/pop transaction for each LoadModule call. This is reasonable if we assume modules are perfectly layered. That is, no eager module deserialization require definitions from another module. This is hard to achieve for dependent on ROOT codebases during their incremental migration process.
The current patch push/pops once per loading of all modules. This should perform slightly better and allow entangled modules to still load.
This patch should address the CMSSW Modules IB:
Assertion `OldBuilder->DeferredDeclsToEmit.empty() && "Should have emitted all decls deferred to emit."' failed.
```
0  0x00007ffff6f113d7 in raise () from /lib64/libc.so.6
1  0x00007ffff6f12ac8 in abort () from /lib64/libc.so.6
2 …
```

[cxxmodules] Do not push a transaction per LoadModule.

---

io/io/inc/TStreamerInfoActions.h
io/io/src/TStreamerInfoActions.cxx
tree/tree/src/TBranchElement.cxx

It was using the wrong signature leading to the configuration to be mis-read.
Fixes #7754

[v624][io] Fix the action PushDataCache for TClonesArray.

---

math/genvector/doc/index.md

eta -> theta

---

math/mathcore/inc/Math/AllIntegrationTypes.h
math/mathcore/inc/Math/GaussIntegrator.h
math/mathcore/inc/Math/GaussLegendreIntegrator.h
math/mathcore/inc/Math/Integrator.h
math/mathcore/inc/Math/IntegratorMultiDim.h
math/mathcore/inc/Math/IntegratorOptions.h
math/mathcore/inc/Math/VirtualIntegrator.h
math/mathmore/inc/Math/GSLIntegrator.h
math/mathmore/inc/Math/GSLMCIntegrator.h
math/mathmore/src/GSLMonteFunctionWrapper.h

Doxygen fixes in integrator classes
Typos

Doxygen fixes in integrator classes

---

roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooFitResult.h
roofit/roofitcore/src/RooAbsPdf.cxx

Backport of https://github.com/root-project/root/pull/7711.

[RF] Define cov matrix quality for correction strategies in fitTo

---

hist/hist/src/TGraph.cxx
hist/hist/src/TGraphAsymmErrors.cxx
hist/hist/src/TGraphBentErrors.cxx
hist/hist/src/TGraphErrors.cxx
hist/hist/src/TGraphMultiErrors.cxx
hist/hist/src/TGraphSmooth.cxx

Fix several doxygen formatting issues,

Several fixes in graphs doc

---

bindings/experimental/distrdf/python/DistRDF/Node.py
bindings/experimental/distrdf/test/test_headnode.py

[DF] Do not support in-memory-only trees in distributed rdf

---

bindings/experimental/distrdf/python/DistRDF/Node.py
bindings/experimental/distrdf/test/test_headnode.py

Backport of https://github.com/root-project/root/pull/7791

[DF][skip-ci] Do not support in-memory-only trees in distributed rdf

---

roofit/roofit/CMakeLists.txt
roofit/roofit/inc/LinkDef1.h
roofit/roofit/inc/RooLagrangianMorphFunc.h
roofit/roofit/src/RooLagrangianMorphFunc.cxx
roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/Floats.h
roofit/roofitcore/inc/LinkDef.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooHistFunc.h
roofit/roofitcore/inc/RooLinearCombination.h
roofit/roofitcore/inc/RooRatio.h
roofit/roofitcore/inc/RooWorkspace.h
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooLinearCombination.cxx
roofit/roofitcore/src/RooRatio.cxx
roofit/roostats/inc/LinkDef.h
roofit/roostats/inc/RooStats/RooStatsUtils.h
roofit/roostats/src/RooStatsUtils.cxx

Hi Jonas (@guitargeek) and  Lorenzo (@lmoneta) ,
I am opening a draft pull request with the bulk of the code for the morphing class. The morphing class consist of the RooLagrangianMorphFunc which builds the necessary morphing function and is assisted by a lightweight config class which allows to configure the morphfunc in various ways. 
The code is WIP and there are more updates expected in subsequent PRs. The main discussion is the way the objects are handled by the config and the morphfunc and support for factory style syntax. The code for the tutorials and the optimizer for the choice of input templates is also postponed to a subsequent PR as this is tied to the previous issue. There are some more issues regarding having boost high precision which can be a separate PR.
Feel free to …

[RF] RooLagrangianMorphFunc class for performing effective lagrangian morphing

---

tutorials/dataframe/df032_MakeNumpyDataFrame.py
tutorials/dataframe/df107_SingleTopAnalysis.py

Fix a couple of typos in the dataframe tutorials.

Fix typos in DF tutorials

---

test/stressIOPlugins.cxx

Needs to be backported +/- everywhere

Update location of stressIOPlugin eos files

---

README/ReleaseNotes/v624/index.md
io/io/src/TStreamerInfoActions.cxx
io/io/src/TStreamerInfoWriteBuffer.cxx
tree/tree/src/TBranchElement.cxx
tree/tree/src/TLeafElement.cxx

The intent was to prevent the creation of sub branch with 2 consecutives dots
and to avoid a dot between the branch name of the collection and the underscore
for name of the index leaf.
The major problem of the first try is that the name of the top level branch
was changed from "t." to "t" making existing code search for the branch by
fullname failing.
Fix #7281
This effectively ammends/corrects d225f942b59b5b022cf635a16e90f84cad59819d
Before v6.23
```
******************************************************************************
*Tree    :tree      : treelibrated tree                                      *
*Entries :    10000 : Total =          485042 bytes  File  Size =     177202 *
*        :          : Tree compression factor =   2.74                       * …
```

Redo part of 'Correct FullName of the index leaf of a collection'

---

README/ReleaseNotes/v624/index.md

Some numbered list did not show properly in release notes 6.24

more fixes in the rel notes

---

README/ReleaseNotes/v624/index.md

Back port fix on release note 624 (a numbered list was not correct)

back port release notes fix

---

tree/dataframe/inc/ROOT/RNTupleDS.hxx

In the wake of https://github.com/root-project/root/issues/7828 :)

[RNTuple] Add RDataSource::GetLabel impl

---

README/ReleaseNotes/v624/index.md

Update release notes with missing items, fixes #7858

Update release notes for v6 24 00

---

README/ReleaseNotes/v626/index.md
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/Utils.hxx
tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RDataFrame.cxx
tree/dataframe/test/dataframe_interface.cxx
tutorials/dataframe/df032_Describe.py

See the linked issue (#7561) for the discussion of the programming model

[DF] Add convenience function to describe dataset

---

tutorials/CMakeLists.txt

This should go in together with https://github.com/root-project/rootspi/pull/102. Though each of the PRs on its own won't break anything, just not veto the tutorial.

[DF][Python] Ignore tutorial using pandas based on envvar

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/DataFrame.py
bindings/experimental/distrdf/test/backend/test_spark.py

6.24 backport of https://github.com/root-project/root/pull/7841

[skip-ci][DF] Give priority to user provided npartitions

---

bindings/pyroot/pythonizations/python/ROOT/_facade.py

Fixes #6764 , see the comment with explanation there

[PyROOT] Add __reduce__ method to ROOTFacade to help serialization tools

---

tree/dataframe/src/RDFUtils.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/dataframe_interface.cxx

[DF] Add branch name to list of valid column names if it has one leaf (v6.24)

---

tree/dataframe/src/RDFUtils.cxx

..rather than building the leaf name "by hand".

[DF] Use TLeaf::GetFullName in error message

---

core/meta/src/TDictionary.cxx

For `std::string`, we have both a TClass and a TDataType (as it is a typedef).
We should prefer the TClass (which fixes issue #7169), but not at the cost
of calling `TClass::GetClass()` first: that is just too slow. So instead,
check for "is it a datatype, not numeric, do we have a TClass?" which will
still prefer the TClass even if *also* a TDataType exists.
Provide documentation!

[meta] TDictionary::GetDictionary() prefer class over typedef:

---

gui/browsable/inc/ROOT/Browsable/RElement.hxx
gui/browsable/inc/ROOT/Browsable/RItem.hxx
gui/browsable/inc/ROOT/Browsable/RSysFile.hxx
gui/browsable/inc/ROOT/Browsable/RWrapper.hxx
gui/browsable/src/RGroup.cxx
gui/browsable/src/RSysFile.cxx
gui/browsable/src/TLeafDraw6Provider.cxx
gui/browsable/src/TLeafDraw7Provider.cxx
gui/browsable/src/TLeafProvider.hxx
gui/browsable/src/TObjectElement.cxx
gui/browserv7/src/RBrowser.cxx
ui5/browser/controller/Browser.controller.js
ui5/browser/view/Browser.view.xml

1. Support plain TBranch
2. Fix error with item double-click
3. When any ROOT files opened, show "ROOT Files" subfolder with files inside
4. Show warning message when double-click action takes too long time
5. Provide toggle button between current dir and top folder

[rbrowser] support plain TBranch, fix several problems

---

documentation/doxygen/Doxyfile

This flag screwed up the TOC of datagram and histpainter

TOC flag has weird side effects

---

core/base/src/TAttFill.cxx
core/base/src/TAttLine.cxx
core/base/src/TAttMarker.cxx
core/base/src/TAttText.cxx
core/base/src/TColor.cxx
documentation/doxygen/Doxyfile
graf2d/graf/src/TGaxis.cxx
graf2d/graf/src/TLatex.cxx
graf2d/graf/src/TPaveStats.cxx
hist/hist/src/TF1.cxx
hist/hist/src/THStack.cxx
hist/hist/src/TMultiDimFit.cxx
hist/hist/src/TMultiGraph.cxx
hist/histpainter/src/TGraphPainter.cxx
hist/histpainter/src/THistPainter.cxx
io/doc/TFile/README.md
math/matrix/doc/index.md
math/vecops/inc/ROOT/RVec.hxx
tree/dataframe/src/RDataFrame.cxx
tree/tree/src/TTree.cxx
tree/tree/src/TTreeCache.cxx

Reactivate the doxygen TOC for \page

Better TOCs at the beginning of classes headers

---

io/io/inc/TMapFile.h
io/io/src/TBufferFile.cxx
io/io/src/TBufferIO.cxx
io/io/src/TBufferJSON.cxx
io/io/src/TFile.cxx
io/io/src/TFileMerger.cxx
io/io/src/TMapFile.cxx
io/io/src/TMemFile.cxx
io/io/src/TStreamerInfo.cxx
io/sql/src/TBufferSQL2.cxx
io/xml/src/TBufferXML.cxx
io/xml/src/TKeyXML.cxx

- Replace `long` types by `Longptr_t`
- Fix pointer formatting (use `%zx` and `size_t` for architecture dependent format)

[io] Next bunch of changes for Win64

---

bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/TemplateProxy.cxx
bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx

From issue #7400 and:
https://bitbucket.org/wlav/cppyy-backend/commits/4a2d9dfa1a6f8b7cf8e8033eadfffdd0dc9f79a5
https://bitbucket.org/wlav/cpycppyy/commits/8a2af080d20c093cbe21128f13c3ad72ea5f9599

[PyROOT] Clang-tidy suggestions

---

roofit/roofitcore/src/MemPoolForRooSets.h
roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h
roofit/roostats/inc/RooStats/ToyMCSampler.h
roofit/roostats/src/ToyMCSampler.cxx

Backport of:
* https://github.com/root-project/root/pull/7935
* https://github.com/root-project/root/pull/7954
* second commit in https://github.com/root-project/root/pull/7904

[v620][RF] Improve MemPoolForRooSets and fix memory leak in ToyMCSampler

---

roofit/roofitcore/src/MemPoolForRooSets.h
roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h
roofit/roostats/inc/RooStats/ToyMCSampler.h
roofit/roostats/src/ToyMCSampler.cxx

Backport of:
* https://github.com/root-project/root/pull/7935
* https://github.com/root-project/root/pull/7954
* second commit in https://github.com/root-project/root/pull/7904

[v618][RF] Improve MemPoolForRooSets and fix memory leak in ToyMCSampler

---

roofit/roofitcore/src/MemPoolForRooSets.h
roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h
roofit/roostats/inc/RooStats/ToyMCSampler.h
roofit/roostats/src/ToyMCSampler.cxx

Backport of:
* https://github.com/root-project/root/pull/7935
* https://github.com/root-project/root/pull/7954
* second commit in https://github.com/root-project/root/pull/7904

[v622][RF] Improve MemPoolForRooSets and fix memory leak in ToyMCSampler

---

roofit/roofitcore/src/MemPoolForRooSets.h
roofit/roostats/inc/RooStats/ToyMCImportanceSampler.h
roofit/roostats/inc/RooStats/ToyMCSampler.h
roofit/roostats/src/ToyMCSampler.cxx

Backport of:
* https://github.com/root-project/root/pull/7935
* https://github.com/root-project/root/pull/7954
* second commit in https://github.com/root-project/root/pull/7904

[v624][RF] Improve MemPoolForRooSets and fix memory leak in ToyMCSampler

---

roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/roostats/src/HypoTestInverter.cxx

Two more leaks found while looking at #7890

[RF] Fix memory leaks

---

core/meta/src/TDictionary.cxx

For `std::string`, we have both a TClass and a TDataType (as it is a typedef).
We should prefer the TClass (which fixes issue #7169), but not at the cost
of calling `TClass::GetClass()` first: that is just too slow. So instead,
check for "is it a datatype, not numeric, do we have a TClass?" which will
still prefer the TClass even if *also* a TDataType exists.
Provide documentation!

[meta] TDictionary::GetDictionary() prefer class over typedef: (v6.24)

---

roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooBinSamplingPdf.cxx
roofit/roofitcore/src/RooCurve.cxx
roofit/roofitcore/src/RooPlot.cxx

A few improvements that I implemented when helping out a user.

[RF] Documentation and usability improvements

---

tree/ntuple/v7/inc/ROOT/RPageSinkBuf.hxx
tree/ntuple/v7/inc/ROOT/RPageStorage.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageSinkBuf.cxx
tree/ntuple/v7/src/RPageStorage.cxx
tree/ntuple/v7/src/RPageStorageFile.cxx
tree/ntuple/v7/test/ntuple_cluster.cxx
tree/ntuple/v7/test/ntuple_merger.cxx
tree/ntuple/v7/test/ntuple_test.hxx

One of the building blocks for fast merged, as sketched in #6105

[ntuple] Implement reading and writing of sealed pages

---

math/genvector/inc/Math/GenVector/Cartesian2D.h
math/genvector/inc/Math/GenVector/Cartesian3D.h
math/genvector/inc/Math/GenVector/Cylindrical3D.h
math/genvector/inc/Math/GenVector/CylindricalEta3D.h
math/genvector/inc/Math/GenVector/LorentzVector.h
math/genvector/inc/Math/GenVector/Plane3D.h
math/genvector/inc/Math/GenVector/Polar2D.h
math/genvector/inc/Math/GenVector/Polar3D.h
math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h
math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/GenVector/PxPyPzE4D.h
math/genvector/inc/Math/GenVector/PxPyPzM4D.h
math/genvector/inc/Math/GenVector/RotationX.h
math/genvector/inc/Math/GenVector/RotationY.h
math/genvector/inc/Math/GenVector/RotationZ.h
math/genvector/inc/Math/GenVector/VectorUtil.h
math/genvector/inc/Math/GenVector/eta.h
math/genvector/inc/Math/GenVector/etaMax.h

This PR should solve [this](https://github.com/root-project/root/issues/7905) issue. (Closes #7905)
I looked for all of the standars library functions in the file, but std::sqrt() seemed to be the only one (not even std::cout was present).
I accidentally added another commit to this branch, but I reverted that, so this pr only fixed the named issue.
This *should* solve the issue, but let me know if it doesn't. 
Kind Regards,
Advait

Sqrt issue

---

io/io/src/TStreamerInfo.cxx

Fix #7912.
In this report, the v5 file has a 'map<TString, RooExpensiveObjectCache::ExpensiveObject*>'
however it is recorded as 'map<TString, ExpensiveObject*>'.  However the map stored in
the file is empty and thus no information was recorded about `ExpensiveObject`,
consequently when the map's StreamerInfo request the TClass for the underlying pair,
it is returned nullptr (since we no longer create the TClass for a pair where one or
more of the component is unknown).
The routine `FixCollectionV5` needed to be updated to handle this situation.

[v622] Properly handle v5 file with missing information.

---

roofit/roostats/src/RooStatsUtils.cxx

This addresses Jira issue [ROOT-4988](https://sft.its.cern.ch/jira/browse/ROOT-4899).

[RF] Replace typeid with dynamic_cast in RooStatsUtils

---

documentation/doxygen/makerootfile.C

Update makerootfile.C to the new JSRoot API

Update makerootfile.C to the new JSRoot API

---

README/ReleaseNotes/v626/index.md

[relnotes][skip-ci] Mention addition of jitted Book

---

bindings/jupyroot/python/JupyROOT/helpers/handlers.py

[JupyROOT][8055] Make poller thread a daemon

---

roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooBinSamplingPdf.cxx
roofit/roofitcore/src/RooCurve.cxx
roofit/roofitcore/src/RooPlot.cxx

Collection of small tweaks that came up in recent discussions.

[RF] Improve some documentation and usability

---

roofit/histfactory/inc/RooStats/HistFactory/HistFactoryException.h
roofit/histfactory/src/ConfigParser.cxx
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/roofitcore/inc/RooAbsArg.h
roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/inc/RooAbsPdf.h
roofit/roofitcore/inc/RooBinIntegrator.h
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooBinIntegrator.cxx
roofit/roofitcore/src/RooHelpers.cxx
roofit/roofitcore/src/RooProduct.cxx
roofit/roofitcore/src/RooRealVar.cxx

This is a collection small things I found while working on HistFactory models -- the last batch before getting to the actual HistFactory stuff.
@guitargeek Maybe the last commit is interesting for some things you tweaked? (Only in tests or debug builds of course)

[RF] A few small tweaks

---

README.md

This is a minor clarification in the README installation instructions.

Minor clarification in README [skip-CI]

---

config/root-config.in

Addressing issue #7662 for bash root-config
Pretty much mirrored what was done for root-config.bat in #7663
Handle unknown feature. Unknown option is already handled.
Preview:
spectre@localhost ~/root/compiled/bin
(improve-root-config-bash)> ./root-config --has-xml --has-cxx14 --has-improved
yes yes --has-improved: unknown feature!

[config] improve root-config --has handling

---

roofit/histfactory/inc/RooStats/HistFactory/RooBarlowBeestonLL.h
roofit/histfactory/src/RooBarlowBeestonLL.cxx
roofit/roofitcore/inc/RooAbsArg.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsReal.cxx

Backport of https://github.com/root-project/root/pull/8142.

 [v624][RF] Add RooAbsArg::getParameters RooAbsArg::getObservables overloads that takes output parameter

---

README/CREDITS

Add Johannes Hentrich in CREDITS

Add Johannes in CREDITS [skip-ci]

---

tree/treeplayer/src/TTreeIndex.cxx

`long double` is the most precise type for evaluating the TTreeFormula expressions.
For some platforms - notably Apple M1 - `long double` has the same precision as `double`,
and thus not enough bits to represent large numbers, as shown by roottest/tree/index/runindex64.C
failing on M1. The most reasonable way to deal with this is to warn if any of the relevant
indexing values exceeds the precision of `long double`.

[treeplayer] Warn if indexed values too large for `long double`: (v6.24)

---

net/net/inc/TSQLServer.h
net/net/src/TSQLServer.cxx
sql/sqlite/inc/TSQLiteServer.h
sql/sqlite/src/TSQLiteServer.cxx

[sql] provide TSQLServer::HasTransactionInFlight() method

---

roofit/roofitcore/inc/RooAbsCollection.h

Another little change, this makes some nice features available in python such as ```"var" in collection```

FindObject for rooabscollection

---

hist/histpainter/src/TGraphPainter.cxx

x+ and y+ options combined with rx and ry produces an horizontal
line at 0.

The previous change was not complete.

---

tutorials/dataframe/df103_NanoAODHiggsAnalysis.C

Otherwsie legend disappears after leaving function scope

Use legend.DrawClone() in tutorial [skip-ci]

---

math/genvector/inc/Math/Vector2Dfwd.h
math/genvector/inc/Math/Vector3Dfwd.h
math/genvector/inc/Math/Vector4Dfwd.h

Improve math doc as requested in issue #8051

[skip-ci] improve doc. Fix #8051

---

gui/browsable/src/TDirectoryElement.cxx
gui/browserv7/inc/ROOT/RBrowser.hxx
gui/browserv7/inc/ROOT/RWebBrowserImp.hxx
gui/browserv7/src/RBrowser.cxx
gui/browserv7/src/RBrowserTCanvasWidget.cxx
gui/browserv7/src/RBrowserWidget.hxx
gui/browserv7/src/RWebBrowserImp.cxx
gui/webgui6/src/TWebCanvas.cxx
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
tutorials/dataframe/df013_InspectAnalysis.C

1. Add new TCanvas when RBrowser created via calling `new TBrowser`. Used in `df013_InspectAnalysis.C` macro
2. Also select `ROOT Files` folder when `new TBrowser("b", dfDirectory);` called.
3. Fix problem with updating of TWebCanvas - one have to set some private members in TCanvas
4. Fix minor problems in JSROOT with TF1, TH1 and TLegend drawing
5. All RDF tutorials correctly run with web mode `root --web` 
6. Add `pad->Update()` in `df013_InspectAnalysis.C` macro to correctly update canvas at the end

Improve TWebCanvas and RBrowser for RDF tutorials

---

net/davix/src/TDavixFile.cxx

Fix the bug in the check if Bearer token for Davix actually was discovered (not empty)
Fixes #8155 and #8092

Fix the #8155 and #8092

---

core/clingutils/CMakeLists.txt
core/dictgen/CMakeLists.txt
core/foundation/CMakeLists.txt
core/metacling/src/CMakeLists.txt
interpreter/CMakeLists.txt
interpreter/cling/CMakeLists.txt
interpreter/cling/include/cling/Interpreter/CValuePrinter.h
interpreter/cling/include/cling/Interpreter/DynamicLookupRuntimeUniverse.h
interpreter/cling/include/cling/Interpreter/RuntimePrintValue.h
interpreter/cling/include/cling/Interpreter/RuntimeUniverse.h
interpreter/cling/include/cling/Interpreter/Value.h
interpreter/cling/include/cling/Interpreter/Visibility.h
interpreter/cling/include/cling/module.modulemap.build
interpreter/cling/lib/Interpreter/Exception.cpp
interpreter/cling/lib/Interpreter/Interpreter.cpp
interpreter/cling/lib/Interpreter/RequiredSymbols.cpp
interpreter/cling/lib/Interpreter/ValueExtractionSynthesizer.cpp
interpreter/cling/lib/Interpreter/ValuePrinter.cpp
main/CMakeLists.txt

Cling visibility and semantic interposition

---

io/io/src/TDirectoryFile.cxx

Fix issue #8046 by only iterating the bucket that corresponds to the object name.

[io] Accelerate TDirectoryFile::GetObjectChecked (NFCI):

---

graf2d/gpadv7/inc/ROOT/RAttrAxis.hxx
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.v7gpad.js
tutorials/v7/draw_symlog.cxx

Triggered by discussion on forum:
https://root-forum.cern.ch/t/symlog-scale-for-plotting/
Include tutorial

Provide symlog scale for RAxis

---

core/meta/src/TClass.cxx
core/meta/src/TClassRef.cxx
core/meta/src/TDataMember.cxx
core/meta/src/TDataType.cxx
core/meta/src/TDictAttributeMap.cxx
core/meta/src/TDictionary.cxx
core/meta/src/TEnum.cxx
core/meta/src/TFunction.cxx
core/meta/src/TFunctionTemplate.cxx
core/meta/src/TGenericClassInfo.cxx
core/meta/src/TGlobal.cxx
core/meta/src/TInterpreter.cxx
core/meta/src/TListOfDataMembers.cxx
core/meta/src/TListOfEnums.cxx
core/meta/src/TListOfEnumsWithLock.cxx
core/meta/src/TListOfFunctionTemplates.cxx
core/meta/src/TListOfFunctions.cxx
core/meta/src/TMethod.cxx
core/meta/src/TMethodArg.cxx
core/meta/src/TMethodCall.cxx
core/meta/src/TProtoClass.cxx
core/meta/src/TRealData.cxx
core/meta/src/TSchemaRule.cxx
core/meta/src/TSchemaRuleSet.cxx
core/meta/src/TStreamerElement.cxx
core/meta/src/TViewPubDataMembers.cxx
core/meta/src/TViewPubFunctions.cxx
core/meta/src/TVirtualStreamerInfo.cxx

meta nullptr modernize

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/tpython/src/TPython.cxx

[PyROOT][8128] Fixes for Python3.9

---

bindings/pyroot/cppyy/CPyCppyy/src/Pythonize.cxx

This fixes the iteration over a TTreeReader, since incrementing its
iterator before the loop body of the first iteration runs causes
the current entry of the reader to always be one position ahead.
From:
https://bitbucket.org/wlav/cpycppyy/commits/8222848093bd687d67f2b89172764e0964cb14f0
Fixes #8183

[PyROOT][8183] Do not increment STL-like iterator in first iteration

---

test/Makefile.win32

Cleanup and remove obsolete options and compiler flags

Fix Makefile.win32 for latest versions of Visual Studio

---

roofit/roofitcore/CMakeLists.txt
roofit/roofitcore/inc/RooFitLegacy/RooHashTable.h
roofit/roofitcore/src/RooFitLegacy/RooHashTable.cxx
roofit/roofitcore/src/RooLinkedList.cxx

This is a followup on https://github.com/root-project/root/pull/7818.

[RF] Deprecate RooHashTable

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx
tree/dataframe/test/dataframe_interface.cxx

[DF] Fix compilation of Foreach with mutable lambdas 

---

gui/gui/src/TGNumberEntry.cxx
gui/gui/src/TGText.cxx

Bug in TGtextLine::GetText method

Fix gui bugs and warnings found by gcc11

---

tree/dataframe/inc/ROOT/RDF/InterfaceUtils.hxx

[DF] Fix compilation of Foreach with mutable lambdas (v6.24)

---

graf2d/x11/src/GX11Gui.cxx
graf3d/eve7/glu/tess.c
io/io/inc/TMapFile.h
tree/tree/inc/TLeaf.h

gcc11 warns about the intentionally broken code.

Fix some gcc11 warnings (GX11Gui, TGNumberFormat, TMapFile)

---

graf3d/eve7/inc/ROOT/REveDataProxyBuilderBase.hxx
graf3d/eve7/inc/ROOT/REveDataTable.hxx
graf3d/eve7/inc/ROOT/REveProjectionManager.hxx
graf3d/eve7/src/REveDataCollection.cxx
graf3d/eve7/src/REveDataTable.cxx
graf3d/eve7/src/REveManager.cxx
graf3d/eve7/src/REveProjectionManager.cxx

Change Log:
- Enable RFileDialog through REveManager
- Add checks for validity of table and filter expressions
- Clear unnecessary REveManager printouts

Eve7 Handle RFileDialog response 

---

math/mathcore/inc/Math/RanluxppEngine.h
math/mathcore/src/RanluxppEngineImpl.cxx
math/mathcore/src/ranluxpp/helpers.h
math/mathcore/src/ranluxpp/mulmod.h
math/mathcore/src/ranluxpp/ranlux_lcg.h
math/mathcore/test/CMakeLists.txt
math/mathcore/test/RanluxppEngine.cxx
math/mathcore/test/mulmod.icc
math/mathcore/test/ranlux_lcg.cxx

backport of https://github.com/root-project/root/pull/8293

Fix bias in RANLUX++ [v6.24]

---

graf3d/eve/inc/TEveFrameBox.h
graf3d/eve/inc/TEveRGBAPalette.h
graf3d/eve7/inc/ROOT/REveFrameBox.hxx
graf3d/eve7/inc/ROOT/REveRGBAPalette.hxx

Backport of https://github.com/root-project/root/pull/8354

Fix [R/T]EveRefCnt::OnZeroRefCount() bug in 6.24

---

documentation/users-guide/ALittleC++.md

Cosmetic changes in ALittleC++.md for better readability

---

documentation/users-guide/FittingHistograms.md

Adding a missing closing double quote.

Fixing a typo in FittingHistograms.md

---

tree/tree/inc/TLeaf.h
tree/tree/inc/TLeafB.h
tree/tree/inc/TLeafD.h
tree/tree/inc/TLeafD32.h
tree/tree/inc/TLeafElement.h
tree/tree/inc/TLeafF.h
tree/tree/inc/TLeafF16.h
tree/tree/inc/TLeafG.h
tree/tree/inc/TLeafI.h
tree/tree/inc/TLeafL.h
tree/tree/inc/TLeafO.h
tree/tree/inc/TLeafS.h
tree/tree/src/TBranch.cxx
tree/tree/src/TLeafElement.cxx
tree/tree/test/BulkApiMultiple.cxx

Correct the value of 'GetSerializedType'.

Fix for bulkio issue #6520

---

graf2d/gpadv7/CMakeLists.txt
graf2d/gpadv7/inc/ROOT/RDisplayItem.hxx
graf2d/gpadv7/inc/ROOT/TObjectDisplayItem.hxx
graf2d/gpadv7/inc/ROOT/TObjectDrawable.hxx
graf2d/gpadv7/src/RDisplayItem.cxx
graf2d/gpadv7/src/TObjectDrawable.cxx
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.interactive.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
tutorials/v7/draw_v6.cxx

Let use RDrawable attributes to overwrite some basic properties like line attributes or fill attributes.
Let use CSS styling for such attributes

[rcanvas] improve TObjectDrawable

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx
tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/inc/ROOT/RDF/RMergeableValue.hxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/DataFrameSimpleLinkDef.h
tree/dataframe/test/MaxSlotHelperLinkDef.h
tree/dataframe/test/SimpleFiller.h
tree/dataframe/test/dataframe_simple.cxx

[DF] Allow using RDF Fill with types that do not inherit from TH1

---

.github/pull_request_template.md

I have seen other repos with this and it is usually quite handy.
There was no demand for this, just thought it would be nice

Added a PR template file 

---

math/unuran/inc/TUnuranContDist.h
math/unuran/src/TUnuranContDist.cxx

This fixes the ROOT issue #8196

Fix bug in using the pdf derivative in TUnuranContDist

---

math/unuran/src/TUnuranContDist.cxx

This Pull request is a backport in 6.24 for #8196 using a commit of #8254

Backport in 6.24 fix in TUnuranContDist

---

math/genvector/inc/Math/GenVector/Cartesian2D.h
math/genvector/inc/Math/GenVector/Cartesian3D.h
math/genvector/inc/Math/GenVector/Cylindrical3D.h
math/genvector/inc/Math/GenVector/CylindricalEta3D.h
math/genvector/inc/Math/GenVector/LorentzVector.h
math/genvector/inc/Math/GenVector/Plane3D.h
math/genvector/inc/Math/GenVector/Polar2D.h
math/genvector/inc/Math/GenVector/Polar3D.h
math/genvector/inc/Math/GenVector/PtEtaPhiE4D.h
math/genvector/inc/Math/GenVector/PtEtaPhiM4D.h
math/genvector/inc/Math/GenVector/PxPyPzE4D.h
math/genvector/inc/Math/GenVector/PxPyPzM4D.h
math/genvector/inc/Math/GenVector/RotationX.h
math/genvector/inc/Math/GenVector/RotationY.h
math/genvector/inc/Math/GenVector/RotationZ.h
math/genvector/inc/Math/GenVector/VectorUtil.h
math/genvector/inc/Math/GenVector/eta.h
math/genvector/inc/Math/GenVector/etaMax.h

Backport in 6.24  sqrt issue in Genvector

---

tutorials/tmva/TMVAClassification.C
tutorials/tmva/TMVAClassificationApplication.C
tutorials/tmva/TMVAClassificationCategoryApplication.C
tutorials/tmva/TMVACrossValidation.C
tutorials/tmva/TMVACrossValidationApplication.C
tutorials/tmva/TMVACrossValidationRegression.C
tutorials/tmva/TMVAGAexample.C
tutorials/tmva/TMVAGAexample2.C
tutorials/tmva/TMVAMinimalClassification.C
tutorials/tmva/TMVAMulticlassApplication.C
tutorials/tmva/TMVAMultipleBackgroundExample.C
tutorials/tmva/TMVARegression.C
tutorials/tmva/TMVARegressionApplication.C
tutorials/tmva/TMVA_CNN_Classification.C
tutorials/tmva/TMVA_Higgs_Classification.C
tutorials/tmva/TMVA_RNN_Classification.C
tutorials/tmva/tmva100_DataPreparation.py

- remove trailing spaces
- remove tabs

[skip-ci] Fix TMVA tutorials typos

---

io/io/inc/LinkDef.h
io/io/inc/ROOT/TBufferMerger.hxx
io/io/src/TBufferMerger.cxx
io/io/src/TBufferMergerFile.cxx
io/io/test/TBufferMerger.cxx
tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx

[IO] Take TBufferMerger out of the Experimental namespace

---

hist/hist/inc/TF1Convolution.h
hist/hist/src/TF1.cxx
hist/hist/src/TF1Convolution.cxx

Fix setting convolution range when using the CONV operator.

---

math/mathcore/src/TStatistic.cxx

[TStatistic] fix typo

---

bindings/pyroot/cppyy/CPyCppyy/src/API.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyy.h
bindings/pyroot/cppyy/CPyCppyy/src/CPyCppyyModule.cxx
bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx
bindings/pyroot/cppyy/CPyCppyy/src/CustomPyTypes.cxx
bindings/pyroot/pythonizations/src/PyROOTWrapper.cxx
bindings/tpython/src/TPython.cxx
geom/geom/src/TGeoManager.cxx
graf2d/x11/src/GX11Gui.cxx
graf3d/eve7/glu/tess.c
gui/gui/src/TGNumberEntry.cxx
interpreter/llvm/src/CMakeLists.txt
io/io/inc/TMapFile.h
tree/tree/inc/TLeaf.h

GCC 11 warning fixes (v624 backport)

---

tutorials/v7/concurrentfill.cxx

This reverts commit 19929b63022af972f3fa78041026c047ee0e3fc8.

Revert "Update concurrentfill.cxx (#8492)" [skip-ci]

---

net/davix/src/RRawFileDavix.cxx

[RRawFileDavix] Silence 'maybe uninitialized' warning

---

gui/webdisplay/src/RWebDisplayHandle.cxx
tutorials/webgui/ping/ping.cxx

Should avoid problems on 32bit debian

[webgui] use `--single-process` for chrome, improve ping.cxx test

---

core/metacling/src/TClingDataMemberInfo.cxx
core/metacling/test/TClingDataMemberInfoTests.cxx

[metacling] Add missing Transaction for member enumeration:

---

cmake/modules/CheckCompiler.cmake
interpreter/llvm/src/include/llvm/ADT/AllocatorList.h
interpreter/llvm/src/include/llvm/ADT/DenseMap.h
interpreter/llvm/src/include/llvm/ADT/DenseSet.h
interpreter/llvm/src/include/llvm/ADT/STLExtras.h
interpreter/llvm/src/include/llvm/ADT/StringMap.h
interpreter/llvm/src/include/llvm/ADT/iterator.h
interpreter/llvm/src/include/llvm/CodeGen/DIE.h
interpreter/llvm/src/include/llvm/CodeGen/LiveInterval.h
interpreter/llvm/src/include/llvm/DebugInfo/DWARF/DWARFDie.h
interpreter/llvm/src/include/llvm/DebugInfo/DWARF/DWARFExpression.h
interpreter/llvm/src/include/llvm/IR/Attributes.h
interpreter/llvm/src/include/llvm/IR/BasicBlock.h
interpreter/llvm/src/include/llvm/Object/StackMapParser.h
interpreter/llvm/src/include/llvm/ProfileData/Coverage/CoverageMappingReader.h
interpreter/llvm/src/include/llvm/ProfileData/InstrProfReader.h
interpreter/llvm/src/include/llvm/Support/BinaryStreamRef.h
interpreter/llvm/src/lib/CodeGen/PeepholeOptimizer.cpp
interpreter/llvm/src/lib/IR/Attributes.cpp
interpreter/llvm/src/lib/IR/DebugInfo.cpp
interpreter/llvm/src/lib/Transforms/Scalar/GVNHoist.cpp
interpreter/llvm/src/tools/clang/include/clang/AST/RecursiveASTVisitor.h
interpreter/llvm/src/tools/clang/include/clang/AST/StmtIterator.h

[cmake] Allow C++20, fwiw given llvm9.

---

tutorials/roofit/rf212_plottingInRanges_blinding.py
tutorials/roofit/rf303_conditional.py
tutorials/roofit/rf514_RooCustomizer.py
tutorials/roofit/rf612_recoverFromInvalidParameters.py
tutorials/roofit/rf709_BarlowBeeston.py

- Translation of RooFit tutorial files based on this issue https://github.com/root-project/root/issues/8523

[RF] Translated RooFit tutorial files

---

core/base/src/TROOT.cxx

gGlobalMutex memory leak
This PR fixes https://github.com/root-project/root/issues/8297

prevent gGlobalMutex memory leak

---

core/sanitizer/README.md

[NFC][skip-ci] Fix some typos in sanitizer/README.md

---

cmake/modules/RootBuildOptions.cmake

To be removed in v6.28, early 2022.

[cmake] Deprecate Alien, as agreed with ALICE.

---

tree/dataframe/inc/ROOT/RDF/RTreeColumnReader.hxx

[DF] Remove redundant call to TTreeReaderArray::GetSize

---

roofit/roofitcore/inc/RooAddPdf.h
roofit/roofitcore/src/RooAddPdf.cxx

This addresses https://github.com/root-project/root/issues/8000.
The actual check is introduced in the 4th commit, all other commits contain general RooAddPdf code modernization.

[RF] Check that no two distinct input pdfs have same name in RooAddPdf and general RooAddPdf modernization

---

core/base/inc/TSystem.h
core/thread/inc/TThread.h
core/thread/src/TThread.cxx
etc/helgrind-root.supp
gui/gui/inc/TGClient.h

All (but one) of the data races described in https://github.com/root-project/root/issues/8365

Fix thread safety data races

---

core/metacling/test/CMakeLists.txt
core/metacling/test/TClingDataMemberInfoTests.cxx
core/metacling/test/TClingDataMemberInfoTestsROOT7.cxx

RBox TCling tests vs ROOT7

---

io/io/src/TFile.cxx

Clarify how to check for non existing file when using TFile Open

Clarify difference TFile::Open and new TFile() when file does not exist

---

documentation/doxygen/Doxyfile

As suggested here: https://root-forum.cern.ch/t/root-reference-guide-broken/45741

[skip-ci] Set ALWAYS_DETAILED_SEC to YES

---

README/CREDITS
README/ReleaseNotes/v626/index.md

Adds Max to the Credits and the v6.26 README.

Add Max to credits

---

roofit/roofitcore/inc/LinkDef.h
roofit/roofitcore/inc/RooAbsArg.h
roofit/roofitcore/inc/RooAbsCollection.h
roofit/roofitcore/inc/RooMinuit.h
roofit/roofitcore/src/RooAbsArg.cxx
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooAbsData.cxx
roofit/roostats/src/AsymptoticCalculator.cxx
test/stressRooFit_tests.h

Various small fixes and improvements to RooFit, described further in the commit messages.

[RF] Various small fixes and improvements

---

tutorials/hist/NormalizeHistogram.C

Adds a tutorial demonstrating the 7 ways to normalize a histogram.
Above

Added Histogram Normalization Tutorial

---

bindings/r/CMakeLists.txt

Use -isystem for RCpp, suppresses its warnings.

---

gui/webgui6/src/TWebCanvas.cxx
js/changes.md
js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.v7hist3d.js

1. When doing interactive zooming, do not reset zoom range from TCanvas range
2. When apply changes from client, avoid `TPad::Modified()` if nothing is changed
3. Update JSROOT with code of 6.2.0 release

Fix `TWebCanvas` update and zooming

---

README.md

Rationale: document that we do The Right Thing, and remind the future project what that might be :-) Also shows that the project is healthy according to more "bureaucratic measures".

Show ROOT passing CII best practices. [skip-ci]

---

tutorials/hist/RangeChange.C
tutorials/hist/ZoomHistogram.C

Adds a tutorial demonstrating how the changing of the range can zoom into the histogram.
As discussed in [this](https://root-forum.cern.ch/t/histogram-x-axis-range/12815) forum post.

Added Histogram X-Axis Range Change tutorial

---

.github/actions/issues-nudge.js

[NFC] Fix a typo.

---

core/winnt/src/TWinNTSystem.cxx
tmva/tmva/src/DNN/Architectures/Reference/Dropout.hxx

Add missing #include <time.h> (on Windows with /std:c++17)

---

tree/ntuple/v7/doc/README.md
tree/ntuple/v7/inc/ROOT/RNTupleModel.hxx

[NFC][skip-ci] Sall updates to RNTuple docs

---

tmva/tmva/inc/TMVA/DataSetFactory.h

This Pull request fixes a C++17 compilation issue on Windows

[tmva] Remove functor objects that are not anymore used

---

roofit/roofitcore/inc/RooAbsData.h
roofit/roofitcore/inc/RooAbsDataStore.h
roofit/roofitcore/inc/RooCompositeDataStore.h
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooDataSet.h
roofit/roofitcore/inc/RooTreeDataStore.h
roofit/roofitcore/inc/RooVectorDataStore.h
roofit/roofitcore/src/RooAbsData.cxx
roofit/roofitcore/src/RooAbsDataStore.cxx
roofit/roofitcore/src/RooCompositeDataStore.cxx
roofit/roofitcore/src/RooDataHist.cxx
roofit/roofitcore/src/RooDataSet.cxx
roofit/roofitcore/src/RooTreeDataStore.cxx
roofit/roofitcore/src/RooVectorDataStore.cxx

This is done with the intention ultimately making it easier to add more data storage implementations.

[RF] Start reorganizing RooFit data storage code

---

hist/hist/src/TH1.cxx

Makes the descriptions for TH1::GetMaximum etc more descriptive.

[skip-ci] More descriptive descriptions in TH1

---

tree/dataframe/test/dataframe_snapshot.cxx

Some Snapshot output files were not being checked.

[DF] Add more tests to dataframe_snapshot.cxx

---

tree/dataframe/inc/ROOT/RDF/RInterface.hxx
tree/dataframe/src/RDFDisplay.cxx
tree/dataframe/src/RLoopManager.cxx
tree/dataframe/test/datasource_csv.cxx

[DF] Fix some clang-tidy warnings

---

tree/dataframe/inc/ROOT/RRootDS.hxx
tree/dataframe/test/CMakeLists.txt
tree/dataframe/test/datasource_root.cxx

[DF] Re-enable RRootDS test

---

roofit/roofitcore/inc/RooFFTConvPdf.h
roofit/roofitcore/src/RooAbsPdf.cxx
roofit/roofitcore/src/RooFFTConvPdf.cxx

See the individual commit messages.

[RF] Some RooFit code modernization

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roocategory.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roodatahist.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooglobalfunc.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_utils.py
tutorials/roofit/rf108_plotbinning.py
tutorials/roofit/rf310_sliceplot.py
tutorials/roofit/rf401_importttreethx.py
tutorials/roofit/rf404_categories.py
tutorials/roofit/rf406_cattocatfuncs.py
tutorials/roofit/rf408_RDataFrameToRooFit.py
tutorials/roofit/rf514_RooCustomizer.py
tutorials/roofit/rf701_efficiencyfit.py
tutorials/roofit/rf702_efficiencyfit_2D.py
tutorials/roofit/rf708_bphysics.py

- Dictionary pythonizations for std::map constructors ( RooDataHist, RooCategory) 
- Pythonization and formatting of tutorial files

[RF] Dictionary, RooCategory Pythonizations for RooFit

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooworkspace.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_utils.py
tutorials/roofit/rf403_weightedevts.py
tutorials/roofit/rf503_wspaceread.py
tutorials/roofit/rf509_wsinteractive.py
tutorials/roofit/rf510_wsnamedsets.py
tutorials/roofit/rf511_wsfactory_basic.py
tutorials/roofit/rf903_numintcache.py

- Implemented RooWorkspace pythonizations with bracket operator alternative for `RooWorkspace::obj()`
- Command argument pythonization for RooWorkspace::import()
- Pythonization of tutorial files

[RF] Implemented RooWorkspace pythonizations

---

roofit/roofitcore/inc/RooAbsCachedPdf.h
roofit/roofitcore/src/RooAbsCachedPdf.cxx

The usual RooFit code modernizations.

[RF] Code modernization of RooAbsCachedPdf

---

math/mathcore/test/stress/testGenVector.cxx
test/stressMathCore.cxx

Fix two failing tests on s390x.
Apply the same fix for s390x as was already done for arm.

Adjust tests for s390x

---

bindings/r/inc/TRDataFrame.h
bindings/r/inc/TRFunctionExport.h
bindings/r/inc/TRFunctionImport.h
bindings/r/inc/TRInterface.h
bindings/r/inc/TRObject.h
bindings/r/src/TRInterface.cxx

Solve the problem with a segfault in the tests
* Changed the routines to eval R code in several methods on TRInterface.
* Fixed link to the documentation (ROOT-R Users Guide)
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-v6-24-00-patches/93/LABEL=ROOT-centos7,SPEC=noimt,V=6-24/testReport/projectroot.roottest.root/core/roottest_root_core_execStatusBitsCheck/

ROOT R fixes

---

.gitignore

It can be created by some tools like clangd.

Add .cache directory to .gitignore

---

bindings/r/inc/TRDataFrame.h
bindings/r/inc/TRFunctionExport.h
bindings/r/inc/TRFunctionImport.h
bindings/r/inc/TRInterface.h
bindings/r/inc/TRObject.h
bindings/r/src/TRInterface.cxx

Cherry-pick from #8822 for v6-20-00
fixes execStatusBitsCheck segfault for centos
fixes execStatusBitsCheck segfault for centos

V6 20 00 patches r backport

---

bindings/r/inc/TRDataFrame.h
bindings/r/inc/TRFunctionExport.h
bindings/r/inc/TRFunctionImport.h
bindings/r/inc/TRInterface.h
bindings/r/inc/TRObject.h
bindings/r/src/TRInterface.cxx

Cherry-pick from #8822 for v6-22-00
fixes execStatusBitsCheck segfault for centos
fixes execStatusBitsCheck segfault for centos

V6 22 00 patches r backport

---

bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabscollection.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabsdata.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabspdf.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabsreal.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooabsreallvalue.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roocategory.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roochi2var.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roodatahist.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roodataset.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roodecays.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roogenfitstudy.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooglobalfunc.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roomcstudy.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roomsgservice.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roonllvar.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooprodpdf.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roosimultaneous.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_roosimwstool.py
bindings/pyroot/pythonizations/python/ROOT/pythonization/_roofit/_rooworkspace.py
documentation/doxygen/print_roofit_pyz_doctrings.py

[RF] Documentation for RooFit Pythonizations 259c30b

---

bindings/r/inc/TRDataFrame.h
bindings/r/inc/TRFunctionExport.h
bindings/r/inc/TRFunctionImport.h
bindings/r/inc/TRInterface.h
bindings/r/inc/TRObject.h
bindings/r/src/TRInterface.cxx

Cherry-pick from #8822 for v6-24-00
fixes execStatusBitsCheck segfault for centos 
- [x ] updated the docs (if necessary)
fixes execStatusBitsCheck segfault for centos

V6 24 00 patches r cherry pick from master.

---

tmva/sofie/src/RModel.cxx

Added support for operators and models with multiple outputs.
This PR is for the Google Summer of Code project [Inference Code Generation for Recurrent Neural Networks](https://summerofcode.withgoogle.com/projects/#5885532631990272).

[GSoC][TMVA][SOFIE] Add support for operators with multiple outputs

---

tree/tree/src/TChain.cxx

Update documentation of `TChain::Add(const char* name, Long64_t nentries ` :
* show correct way to add a file with a sub tree name using the "?#treename" syntax
* Provide better separation of contents, highlighting different sections according to the description of the various behaviours with respect to the input parameters
* Modernize a bit the code example to loop over the files in the chain

[skip-ci] Update TChain::Add(name, nentries) doc

---

geom/geompainter/src/TGeoTrack.cxx

New text mentioning alternatives.

[skip-ci] TGeoTrack deprecation

---

documentation/doxygen/filter.cxx

[skip-ci] fix typos

---

tmva/pymva/src/PyMethodBase.cxx
tutorials/tmva/TMVA_SOFIE_Keras.C
tutorials/tmva/TMVA_SOFIE_ONNX.C
tutorials/tmva/TMVA_SOFIE_PyTorch.C

This Pull request adds tutorials for RModelParser_ONNX, RModelParser_Keras, and RModelParser_PyTorch.
This depends on the SOFIE's  Keras Parser (#8430) & PyTorch Parser (#8684).
This work is a part of my project **ROOT Storage of Deep Learning Models**  of Google Summer of Code'21.
Project Link: https://summerofcode.withgoogle.com/projects/#5424575602491392

[GSoC][TMVA][SOFIE] Tutorials for RModelParsers

---

tmva/pymva/inc/TMVA/RModelParser_PyTorch.h
tmva/pymva/src/RModelParser_Keras.cxx
tmva/pymva/src/RModelParser_PyTorch.cxx

This Pull request makes minor formatting of code and documentation in RModelParsers

[TMVA][SOFIE] Format Code & Documentation of RModelParsers

---

hist/hist/inc/THStack.h
hist/hist/src/THStack.cxx

As suggested here https://root-forum.cern.ch/t/stacking-1d-histograms-into-a-3d-contour-plot/46635/9

Add GetZaxis for THStack

---

documentation/doxygen/makeinput.sh

[skip-ci] Add missing "s"

---

graf2d/cocoa/src/CocoaPrivate.mm
graf2d/cocoa/src/QuartzWindow.mm

Fix in Cocoa. XSGui crashed on Mac M1

---

io/io/src/TDirectoryFile.cxx

Fix issue root-project#8046 by implementing the fix from Axel for other similar functions in TDirectoryFile.

[io] Accelerate TDirectoryFile Find/Get functions

---

tutorials/dataframe/df000_simple.C
tutorials/dataframe/df000_simple.py

To be linked from the ROOT manual in the "First Steps" section.

[DF] Add two simple tutorials in C++ and Python

---

tmva/pymva/src/RModelParser_PyTorch.cxx
tmva/sofie/CMakeLists.txt
tmva/sofie/inc/TMVA/OperatorList.hxx
tmva/sofie/inc/TMVA/ROperator_Selu.hxx
tmva/sofie/inc/TMVA/ROperator_Sigmoid.hxx
tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

Add support for Selu activation function for pytorch parser.

[TMVA][SOFIE]Selu and Sigmoid activation functions for PyTorch Parser

---

core/base/src/TAttAxis.cxx
core/base/src/TStyle.cxx
graf2d/graf/src/TLine.cxx
graf2d/graf/src/TMarker.cxx

Move documentation from the manual to the reference guide.

[skip-ci] move doc from the manual

---

core/base/src/TAttAxis.cxx

[skip-ci] doc update.

---

tmva/sofie/inc/TMVA/ROperator_Conv.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/SOFIE_common.cxx

This PR fixes an issue in parsing correctly the Convolution operator from an ONNX file. 
In addition an utility funciton to convert the tensor shape to a string is added to improve the produced error messages

[TMVA][SOFIE] Fix problem with  broadcasting bias tensor in the Conv operator.

---

hist/hist/src/TGraph2D.cxx

[skip-ci] add a TOC 

---

README/CREDITS
README/ReleaseNotes/v626/index.md

This pull-request updates the release notes for v6.26 and the `CREDITS` file.

[skip-ci][relnotes] Update v6.26 release notes and CREDITS file

---

graf3d/eve7/CMakeLists.txt
graf3d/eve7/inc/ROOT/REveDataCollection.hxx
graf3d/eve7/inc/ROOT/REveDataProxyBuilderBase.hxx
graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilder.hxx
graf3d/eve7/inc/ROOT/REveManager.hxx
graf3d/eve7/inc/ROOT/REveSystem.hxx
graf3d/eve7/inc/ROOT/REveTableInfo.hxx
graf3d/eve7/src/REveDataProxyBuilderBase.cxx
graf3d/eve7/src/REveDataSimpleProxyBuilder.cxx
graf3d/eve7/src/REveManager.cxx
graf3d/eve7/src/REveTableInfo.cxx
ui5/eve7/controller/EveTable.controller.js
ui5/eve7/controller/GL.controller.js
ui5/eve7/controller/Lego.controller.js
ui5/eve7/controller/Main.controller.js
ui5/eve7/manifest.json

* Add server status info
* Corrections in accessing table expression for derived classes
* Enable navigation to Lego view
It is a correction  to #9005

Eve-7 Add server status info (No.2)

---

bindings/pyroot/cppyy/cppyy/python/cppyy/__init__.py

[PyROOT] Allow multiple digits in version numbers

---

graf3d/eve7/inc/ROOT/REveSystem.hxx
graf3d/eve7/src/REveManager.cxx

[Eve-7] Fix compilation error using gcc8

---

README/ReleaseNotes/v626/index.md
math/vecops/inc/ROOT/RVec.hxx
math/vecops/test/vecops_rvec.cxx

[VecOps] Add the Drop operation

---

interpreter/cling/lib/Interpreter/CIFactory.cpp

Likely will improve root-project/root#8157

[cxxmodules] Complain if glibc is not installed.

---

core/base/src/TApplication.cxx
gui/webdisplay/inc/ROOT/RWebDisplayArgs.hxx
gui/webdisplay/src/RWebDisplayArgs.cxx
gui/webdisplay/src/RWebDisplayHandle.cxx
gui/webdisplay/src/RWebWindowsManager.cxx
js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.painter.js

1. When `root --web=off` started, do not try to load `libROOTWebGUI`
2. Switch back to default `TBrowser` implementation
3. Prevent `RWebWindow::Show` and starting correspondent `THttpServer`
4. Fix problem with newest chromium 95 - `--app` no longer work with incognito mode
5. Update JSROOT with fully redesigned TLatex parser

[webgui] correctly handle --web=off arg

---

tree/dataframe/src/RSqliteDS.cxx

[sqliteds] Prevent temporary tables from being written to disk

---

core/cont/inc/TArrayL.h
core/cont/src/TArrayL.cxx

Revert changes in TArrayL (use Long_t instead of Longptr_t)

---

tree/dataframe/inc/ROOT/RDF/ActionHelpers.hxx

This also fixes an unused variable warning. Thanks for the ping @couet !

[DF] Avoid useless computation when we don't need its result.

---

hist/hist/src/TEfficiency.cxx

Fix using TDirectory::TContext in TEfficiency constructor
This PR fixes #9189

Fix automatic addition of TEfficiency to current directory

---

tree/dataframe/src/RSqliteDS.cxx

[dataframe] Silence RSqliteDS warning / var used only in assert.

---

core/base/inc/TColor.h
core/base/inc/TStyle.h
core/base/src/TColor.cxx
core/base/src/TStyle.cxx
documentation/users-guide/Graphics.md

Fixes https://github.com/root-project/root/issues/8098

Add helper function to define color palette from ASCII file.

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/HeadNode.py

This commit refactors the mapper function so that the logic responsible
for creating the correct RDataFrame instance based on the type of data
source is done in its corresponding HeadNode class. This makes the
interface more uniform and will contribute to adding new data sources in
the future more easily. In each HeadNode class there is now a method
called `generate_rdf_creator`, responsible for creating a function that
in turns knows how to build an RDataFrame instance from one metadata
range (i.e. the information sent to a distributed task).

[DF] Move mapper logic to create RDF in headnode

---

tree/dataframe/inc/ROOT/RDF/ColumnReaderUtils.hxx

Remove one layer of indirection by merging MakeColumnReadersHelper
and MakeColumnReader.
Less code, we avoid some repeated checks,
and MakeColumnReader is not a bit simpler to call directly, which
we will need to implement RVariedColumnReaders for systematic variations.
CC: @bendavid -- I think you are touching this code too, sorry! :sweat_smile:

[DF] Simplify MakeColumnReaders

---

core/base/inc/TVirtualMutex.h
core/base/inc/TVirtualRWMutex.h

Clarifies documentation on R__LOCKGUARD macro.
Fixes https://github.com/root-project/root/issues/9294

[skip-ci] clarify nature of the lockguard macro and difference to std

---

tree/dataframe/src/RSlotStack.cxx

[DF] Silence unused variable warning in RSlotStack

---

graf2d/cocoa/src/TGCocoa.mm
gui/gui/src/TGClient.cxx

macOS: handle the case of GUI without interactive session

---

tree/dataframe/src/RDFUtils.cxx

Instead, split the code RDataFrame jits every 1k newlines and jit
in chunks. This avoids an explosion in the time required by
optimizer passes, which seem to not deal well with very large
function bodies.
See https://github.com/root-project/root/issues/9312 and
https://github.com/root-project/root/issues/7604 for more discussion.
@hahnjo can you confirm this helps? It brings jitting times down to reasonable (<1m times) for the cases I tested.

[DF] Avoid jitting a very large function body, which is slow

---

js/changes.md
js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.interactive.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.menu.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.painter.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js

This should be code also for next ROOT 6.26 release.
Next JSROOT version will have many changes and will be applied only after 6.26

[jsroot] production 6.3.1 version [skip-ci]

---

tutorials/roofit/rf408_RDataFrameToRooFit.C

Simplify code, remove race condition. It didn't do much harm, but it's also not a good idea to show this in a tutorial ...

[RF] Improve rf408 tutorial.

---

tmva/sofie/CMakeLists.txt
tmva/sofie/inc/TMVA/OperatorList.hxx
tmva/sofie/inc/TMVA/ROperator.hxx
tmva/sofie/inc/TMVA/ROperator_Add.hxx
tmva/sofie/inc/TMVA/ROperator_BatchNormalization.hxx
tmva/sofie/inc/TMVA/ROperator_Conv.hxx
tmva/sofie/inc/TMVA/ROperator_Gemm.hxx
tmva/sofie/inc/TMVA/ROperator_Pool.hxx
tmva/sofie/inc/TMVA/ROperator_Relu.hxx
tmva/sofie/inc/TMVA/ROperator_Reshape.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/src/RModel.cxx
tmva/sofie/test/CMakeLists.txt
tmva/sofie/test/Conv2dModelGenerator.py
tmva/sofie/test/TestCustomModelsFromONNX.cxx
tmva/sofie/test/TestCustomModelsFromROOT.cxx
tmva/sofie/test/TestSofieModels.cxx
tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

This Pull requests adds new Pooling operators: MAxPool, AveragePool, GlobalAveragePool, Add, and Flatten
In addition it provides a new faster implementation of ROPerator_COnv using a faster im2col inplementation.
After this PR Sofie is able to parse Resnet like models such as resnet18 (see https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet18-v1-7.onnx )

[TMVA][SOFIE] Add new operators: MaxPool,AveragePool, Add, Reshape (Flattten) and faster Conv

---

tmva/sofie/CMakeLists.txt
tmva/sofie/inc/TMVA/OperatorList.hxx
tmva/sofie/inc/TMVA/ROperator_Reshape.hxx
tmva/sofie/inc/TMVA/ROperator_Slice.hxx
tmva/sofie/inc/TMVA/ROperator_Transpose.hxx
tmva/sofie/test/CMakeLists.txt
tmva/sofie/test/RecurrentModelGenerator.py
tmva/sofie/test/TestSofieModels.cxx
tmva/sofie_parsers/inc/TMVA/RModelParser_ONNX.hxx
tmva/sofie_parsers/src/RModelParser_ONNX.cxx

With this PR SOFIE can parse simple recurrent networks containing RNN /LSTM layers combined with fully connected layer. 
The new added operators are: 
- Slice
- Squeeze/Unsqueeze

[TMVA][SOFIE] New operators (SLice, Squeeze) to support recurrent networks 

---

roofit/roofit/test/testRooExponential.cxx
roofit/roofitcore/inc/RooDataHist.h
roofit/roofitcore/inc/RooSTLRefCountList.h
roofit/roofitcore/test/testProxiesAndCategories.cxx
roofit/roofitcore/test/testRooDataHist.cxx
roofit/roofitcore/test/testRooRealVar.cxx
roofit/roostats/test/testHypoTestInvResult.cxx

This PR is to address GitHub issue https://github.com/root-project/root/issues/9353.
So far, it is only a revert of d91509e so I can see the failures in the CI (on my system, the RooFit tests are still passing even after reverting said commit).

[RF] Fix streamer info warnings in RooFit

---

README/ReleaseNotes/v626/index.md

Add RooFit::MultiProcess and TestStatistics to release notes.

[relnotes] Add RooFit::MultiProcess and TestStatistics

---

bindings/pyroot/cppyy/CPyCppyy/src/Executors.cxx

Fixes #9315 
From upstream:
https://bitbucket.org/wlav/cpycppyy/commits/8428544a46d29dad43feb8f85f0b7d4bddf062e0

[PyROOT] Fix memory leak in iterators

---

gui/webdisplay/src/RWebDisplayHandle.cxx

warning: reached end of file while inside a ~~~ block!

Fix doxygen warning

---

roofit/roofitcore/inc/RooBinSamplingPdf.h
roofit/roofitcore/inc/RooSimultaneous.h
roofit/roofitcore/src/RooAbsOptTestStatistic.cxx
roofit/roofitcore/src/RooBinSamplingPdf.cxx
roofit/roofitcore/src/RooSimultaneous.cxx

This is a placeholder PR to be referenced in the ACAT 2021 presentation. More detailed description will follow.

[RF] Helper functions for bin integration for simultaneous fits

---

graf2d/cocoa/src/TGCocoa.mm
gui/gui/src/TGClient.cxx

macOS: handle the case of GUI without interactive session [v6.24]

---

tmva/sofie/inc/TMVA/ROperator.hxx
tmva/sofie/inc/TMVA/ROperator_GRU.hxx
tmva/sofie/inc/TMVA/ROperator_GRU.icc
tmva/sofie/inc/TMVA/ROperator_LSTM.hxx
tmva/sofie/inc/TMVA/ROperator_LSTM.icc
tmva/sofie/inc/TMVA/ROperator_RNN.hxx
tmva/sofie/inc/TMVA/ROperator_RNN.icc
tmva/sofie/test/TestSofieModels.cxx

This Pull request fixes an issue with the LSTM operator and provides some performance improvement for all recurrent operators

[TMVA][SOFIE] Improvements in RNN, LSTM and GRU operators

---

tmva/sofie/inc/TMVA/ROperator_Conv.hxx
tmva/sofie/test/CMakeLists.txt
tmva/sofie/test/Conv1dModelGenerator.py
tmva/sofie/test/TestSofieModels.cxx

Fix the support for 3d input tensors when performing 1d convolution.
Add also a test for 1D convolution in TestSofieModels

[TMVA][SOFIE] Fix Conv operator for the 1D convolution

---

tmva/sofie/inc/TMVA/ROperator_Conv.hxx
tmva/sofie/inc/TMVA/SOFIE_common.hxx
tmva/sofie/test/CMakeLists.txt
tmva/sofie/test/Conv3dModelGenerator.py
tmva/sofie/test/TestSofieModels.cxx

This Pull request provides the support for 3d convolution. 
A test is added in TestSofieModel

[TMVA][SOFIE] Fix for the 3D convolution in ROperator_Conv

---

roofit/roofitcore/src/RooNLLVar.cxx

* replace `Double_t` with `double` and `Int_t` with `int`
* replace `kTRUE` with `true` and `kFALSE` with `false`
* remove redundant member initializations
* avoid code duplication in internal-use constructors
* replace C-style casts with C++ casts
* add missing `_binnedPdf->setAttribute("BinnedLikelihoodActive") ;` to
one of the internal-use constructors to be consistent with the other
internal-use constructor
* fix memory leak of a `std::list<Double_t>`
* replace `fabs` with `std::abs`

[RF] Some code modernization of RooNLLVar

---

roofit/roofit/test/testRooParamHistFunc.cxx

The `RooAbsReal::createIntegral()` function returns an owning pointer,
so the return value needs to be wrapped in an `std::unique_ptr`.

[RF] Fix memory leaks in `testRooParamHistFunc` and silence test output

---

graf3d/eve7/inc/ROOT/REveDataProxyBuilderBase.hxx
graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilder.hxx
graf3d/eve7/inc/ROOT/REveDataSimpleProxyBuilderTemplate.hxx
graf3d/eve7/inc/ROOT/REveTableProxyBuilder.hxx
graf3d/eve7/src/REveCalo.cxx
graf3d/eve7/src/REveDataCollection.cxx
graf3d/eve7/src/REveDataProxyBuilderBase.cxx
graf3d/eve7/src/REveDataSimpleProxyBuilder.cxx
graf3d/eve7/src/REveStraightLineSet.cxx
graf3d/eve7/src/REveTableProxyBuilder.cxx
tutorials/eve7/collection_proxies.C
ui5/eve7/controller/Lego.controller.js
ui5/eve7/lib/EveElements.js
ui5/eve7/lib/EveManager.js
ui5/eve7/lib/GlViewerThree.js

* Add additional check on:
- empty collections
- empty calorimeters
* Put client's scene change updates in try/catch block to improve stability of code when navigating events 
* Make proxy builder functions more descriptive

Eve-7: Improvements in error handling

---

gui/gui/src/TGText.cxx

(cherry picked from commit 29c5501983ff3945478014000de06a1fd6ef619a)

GUI: removed erroneous delete from TGText::AsString().  Closes #7460.

---

tutorials/hist/tprofile2polyRealistic.C

Same TProfile2D was drawn twice

Fix tprofile2polyRealistic.C tutorial [skip-ci]

---

tutorials/hist/tprofile2polyRealistic.C

Same TProfile2D was drawn twice

Fix tprofile2polyRealistic.C tutorial, 6.26 [skip-ci]

---

tree/dataframe/test/dataframe_interface.cxx

This is the last piece missing to fix #9428.

[DF] Add test for Fill with object with arbitrary signature

---

sql/sqlite/CMakeLists.txt

Correcting the comment with the package name sql/sqlite.

Cosmetics, correcting the package name.

---

graf2d/graf/inc/TArc.h
graf2d/graf/inc/TArrow.h
graf2d/graf/inc/TCrown.h
graf2d/graf/inc/TEllipse.h
graf2d/graf/inc/TGaxis.h
graf2d/graf/inc/TMarker.h
graf2d/graf/inc/TPave.h
graf2d/graf/inc/TPaveLabel.h
graf2d/graf/inc/TPolyLine.h
graf2d/graf/inc/TWbox.h
graf2d/graf/src/TArc.cxx
graf2d/graf/src/TArrow.cxx
graf2d/graf/src/TCrown.cxx
graf2d/graf/src/TEllipse.cxx
graf2d/graf/src/TGaxis.cxx
graf2d/graf/src/TMarker.cxx
graf2d/graf/src/TPave.cxx
graf2d/graf/src/TPaveLabel.cxx
graf2d/graf/src/TPolyLine.cxx
graf2d/graf/src/TWbox.cxx

This was not uniform as explain in this issue:
https://github.com/root-project/root/issues/6966

Return pointer to XXX object in DrawXXX methods.

---

ui5/eve7/controller/ClientLog.controller.js
ui5/eve7/controller/Main.controller.js
ui5/eve7/lib/EveManager.js
ui5/eve7/view/ClientLog.view.xml
ui5/eve7/view/Main.view.xml

Improve logging:
* Add button in menu bar to show the highest severity message
* Show client log message in Dialog instead of popover
Add simple window management:  in view menu add items to switch sides, make single, and hide/show views

Eve-7 Add simple window management and improve message log

---

core/metacling/src/TClingCallFunc.cxx
core/rint/src/TRint.cxx
interpreter/cling/include/cling/Interpreter/ClingOptions.inc
interpreter/cling/include/cling/Interpreter/InvocationOptions.h
interpreter/cling/lib/Interpreter/InvocationOptions.cpp
interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp
interpreter/cling/test/NullDeref/BinOp.C
interpreter/cling/test/NullDeref/Cast.C
interpreter/cling/test/NullDeref/ExecutionTermination.C
interpreter/cling/test/NullDeref/If.C
interpreter/cling/test/NullDeref/InvalidMemoryAddress.C
interpreter/cling/test/NullDeref/Load.C
interpreter/cling/test/NullDeref/MethodCalls.C
interpreter/cling/test/NullDeref/NonNullArg.C
interpreter/cling/test/NullDeref/NonNullArgCustom.C
interpreter/cling/test/NullDeref/Store.C
interpreter/cling/test/NullDeref/ValidAccesses.C

Addresses https://github.com/root-project/root/issues/9112

[TCling] callfunc: O1, no ptrchecks:

---

tmva/pymva/test/CMakeLists.txt

Fix TMVA PyTorch tests on Windows. Resolves #9487

---

core/metacling/src/TClingCallFunc.cxx
core/rint/src/TRint.cxx
interpreter/cling/include/cling/Interpreter/ClingOptions.inc
interpreter/cling/include/cling/Interpreter/InvocationOptions.h
interpreter/cling/lib/Interpreter/InvocationOptions.cpp
interpreter/cling/lib/Interpreter/NullDerefProtectionTransformer.cpp
interpreter/cling/test/NullDeref/BinOp.C
interpreter/cling/test/NullDeref/Cast.C
interpreter/cling/test/NullDeref/ExecutionTermination.C
interpreter/cling/test/NullDeref/If.C
interpreter/cling/test/NullDeref/InvalidMemoryAddress.C
interpreter/cling/test/NullDeref/Load.C
interpreter/cling/test/NullDeref/MethodCalls.C
interpreter/cling/test/NullDeref/NonNullArg.C
interpreter/cling/test/NullDeref/NonNullArgCustom.C
interpreter/cling/test/NullDeref/Store.C
interpreter/cling/test/NullDeref/ValidAccesses.C

6-26 version of https://github.com/root-project/root/pull/9531

[TCling] callfunc: O1, no ptrchecks (v6-26)

---

gui/browsable/src/TDirectoryElement.cxx
gui/browserv7/inc/ROOT/RWebBrowserImp.hxx
gui/browserv7/src/RWebBrowserImp.cxx
gui/webdisplay/src/RWebWindowsManager.cxx

Provides minimal information that happens and how original
browser implementation can be enabled

[rbrowser] add warning message when RBrowser stared for TBrowser

---

gui/browsable/src/TDirectoryElement.cxx
gui/browserv7/inc/ROOT/RWebBrowserImp.hxx
gui/browserv7/src/RWebBrowserImp.cxx
gui/webdisplay/src/RWebWindowsManager.cxx
js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.v7hist3d.js

Provides minimal information that happens and how original
browser implementation can be enabled

[rbrowser] add warning message when RBrowser stared for TBrowser, 6.26

---

interpreter/cling/lib/Interpreter/CIFactory.cpp

https://github.com/root-project/root/issues/9379

[cling] With O1 being default, also set NDEBUG.

---

gui/gui/src/TGToolTip.cxx
roofit/roofitcore/src/RooAbsCategoryLValue.cxx

fix doxygen typo

---

README/CREDITS

Add Fernando Hueso-González in CREDITS

Change CREDITS

---

geom/geom/doc/materials.md
geom/geom/inc/TGeoTessellated.h
geom/geom/src/TGeoBuilder.cxx
geom/geom/src/TGeoManager.cxx
geom/geom/src/TGeoMaterial.cxx
geom/geom/src/TGeoVolume.cxx
geom/geombuilder/src/TGeoVolumeEditor.cxx

doxygen warnings from geom classes

geom doxygen warnings

---

core/base/inc/ROOT/TExecutorCRTP.hxx
core/base/src/Stringio.cxx
core/base/src/TDirectory.cxx
core/base/src/TVirtualX.cxx
core/clingutils/src/TClingUtils.cxx
core/dictgen/res/OptionParser.h
core/dictgen/src/TModuleGenerator.cxx
core/dictgen/src/rootcling_impl.cxx
core/foundation/src/TClassEdit.cxx
core/meta/src/TDataMember.cxx
core/meta/src/TStatusBitsChecker.cxx
core/metacling/src/TCling.cxx
core/multiproc/inc/TMPWorker.h
core/rint/inc/TRint.h
core/rint/src/TRint.cxx
core/rint/src/TTabCom.cxx
core/thread/inc/ROOT/TThreadedObject.hxx
core/winnt/src/TWinNTSystem.cxx
geom/geom/src/TGeoCone.cxx
tutorials/proof/runProof.C
tutorials/pyroot/pyroot002_pythonizationDecorator.py

Several doxygen warnings in core classes

Fix doxygen warnings in core 

---

tree/ntuple/v7/inc/ROOT/RNTupleSerialize.hxx
tree/ntuple/v7/inc/ROOT/RNTupleZip.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageDaos.hxx
tree/ntuple/v7/inc/ROOT/RPageStorageFile.hxx
tree/ntuple/v7/src/RPageStorageDaos.cxx
tree/ntuple/v7/test/ntuple_storage_daos.cxx

This pull-request is a backport of #9483.

[ntuple,daos] Backport PR #9483 to v6.26-00

---

montecarlo/pythia6/src/TPythia6.cxx

This pull-request is a port of #9563 to `master`.

Add missing include for strlcpy() [port to master]

---

montecarlo/pythia6/src/TPythia6.cxx

This pull-request is a backport of #9563 to v6.24.

Add missing include for strlcpy() [backport to v6.24]

---

tutorials/dataframe/df001_introduction.py

refactor: changed print statements to use a newer style of string formatting. Back compatible with 2.7.

Refactored df001_introduction.py

---

tutorials/graphics/tmathtext.C

The previous fix made test fail.
The return was suppressed.

fit tmathtext.C

---

roofit/roofit/inc/RooLagrangianMorphFunc.h
roofit/roofit/src/RooLagrangianMorphFunc.cxx
roofit/roofitcore/src/RooFactoryWSTool.cxx

Add factory interface for the RooLagrangianMorphFunc in `RooFactoryWSTool.cxx`. The interface case be used 
along the following lines,
```
ws.factory( “lagrangianmorph::func($filename(‘inputs.root’),  $couplings({cHq3[-10,10],SM[1]},  $NewPhysics(cHq3=1,SM=0)),  $folders({‘input1’,’input2’,’input3’})”)
```

[RF] factory interface for RooLagrangianMorphFunc

---

io/io/src/TStreamerInfo.cxx

This fixes #8987 (case where the base class deletes operator=).
In case where the class generated by MakeProject derived from a class that deletes the operator= then in some compiler we get the error  below (which is expected since the class generated by MakeProject has a copy constructor which is needed by stl collection).
```
SRChh_ROOT6_mcgenProjectSource.cxx: In copy constructor ‘KKceex::KKceex(const KKceex&)’:
SRChh_ROOT6_mcgenProjectSource.cxx:922:54: error: use of deleted function ‘KKpart& KKpart::operator=(const KKpart&)’
922 |    for (Int_t i=0;i<101;i++) m_Phot[i] = rhs.m_Phot[i];
|                                                      ^
In file included from KKceex.h:21,
from KKhh2f.h:22,
from SRChh_ROOT6_mcgenProjectHeaders.h:1,
from SRChh_ROOT6_mcgenProjectSource.cxx:3: …
```

MakeProject: generate operator=

---

gui/webgui6/src/TWebCanvas.cxx
js/scripts/JSRoot.core.js
js/scripts/JSRoot.painter.js

Add TSpline as supported class in TWebCanvas

[webgui] add TSpline to TWebCanvas, 6.26

---

io/io/src/TStreamerInfo.cxx

This fixes #8987 (case where the base class deletes operator=).
In case where the class generated by MakeProject derived from a class that deletes the operator= then in some compiler we get the error  below (which is expected since the class generated by MakeProject has a copy constructor which is needed by stl collection).
```
SRChh_ROOT6_mcgenProjectSource.cxx: In copy constructor ‘KKceex::KKceex(const KKceex&)’:
SRChh_ROOT6_mcgenProjectSource.cxx:922:54: error: use of deleted function ‘KKpart& KKpart::operator=(const KKpart&)’
922 |    for (Int_t i=0;i<101;i++) m_Phot[i] = rhs.m_Phot[i];
|                                                      ^
In file included from KKceex.h:21,
from KKhh2f.h:22,
from SRChh_ROOT6_mcgenProjectHeaders.h:1,
from SRChh_ROOT6_mcgenProjectSource.cxx:3: …
```

v6-26: MakeProject: generate operator=

---

graf3d/eve7/src/REveJetCone.cxx
graf3d/eve7/src/REveProjectionManager.cxx

* Include missing commit in REveProjectionManager
* Support the new projections in REveJetCone

Backport changes related to XZ, ZY, nad ZX in eve-7 to 6.24 branch

---

graf3d/eve7/src/REveDataTable.cxx
graf3d/eve7/src/REveJetCone.cxx
graf3d/eve7/src/REveManager.cxx

* Try/catch exceptions in steaming of table
* Stream REveLog message conent in the the end-change content form server
* Add support for different projections than RPhi RhoZ in REveJetCone

Eve-7: Handle exception in table content streaming 

---

geom/geom/doc/index.md
graf2d/doc/v600/index.md
graf2d/mathtext/inc/mathtext.h
graf3d/ftgl/inc/FTFace.h
graf3d/ftgl/inc/FTFont.h
graf3d/ftgl/inc/FTPolyGlyph.h
gui/webdisplay/src/RWebWindow.cxx
hist/hist/inc/THnChain.h
hist/hist/src/THnChain.cxx
io/doc/TFile/tprocessid.md
io/mpi/src/TMPIFile.cxx
main/src/xpdtest.cxx
math/fftw/src/TFFTComplexReal.cxx
math/fftw/src/TFFTRealComplex.cxx
math/mathcore/inc/Math/PdfFuncMathCore.h
math/mathcore/src/TRandom1.cxx
math/mathmore/test/VavilovTest.h
math/minuit2/test/MnSim/GaussianModelFunction.h
math/splot/src/TSPlot.cxx
net/rpdutils/src/rpdutils.cxx
sql/odbc/src/TODBCServer.cxx
sql/oracle/src/TOracleResult.cxx
sql/oracle/src/TOracleRow.cxx
sql/oracle/src/TOracleStatement.cxx
sql/pgsql/src/TPgSQLServer.cxx
tutorials/proof/getProof.C
tutorials/proof/runProof.C
tutorials/tree/h1analysisProxy.C

some remaining Doxygen warnings across the packages

[misc] solve doxygen warnings

---

tree/dataframe/src/RDataFrame.cxx
tree/dataframe/test/RArraysDS.hxx
tree/tree/inc/TTreeRow.h
tree/tree/src/InternalTreeUtils.cxx
tree/tree/src/TChain.cxx
tree/tree/src/TTree.cxx
tree/treeplayer/inc/ROOT/TTreeProcessorMP.hxx
tree/treeplayer/inc/TTreeReader.h
tree/treeplayer/src/TTreeProcessorMP.cxx
tree/treeplayer/src/TTreeReader.cxx

Several documentation errors found by doxygen.
Supersedes https://github.com/root-project/root/pull/9650

[tree] fix documentation doxygen warnings

---

graf3d/eve7/src/REveDataTable.cxx
graf3d/eve7/src/REveJetCone.cxx
graf3d/eve7/src/REveManager.cxx

Eve-7 Backport of #9643 to v6-26 patches branch

---

interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp
interpreter/cling/test/DynamicLibraryManager/cached_realpath.C
interpreter/cling/test/DynamicLibraryManager/call_pie.c
interpreter/cling/test/DynamicLibraryManager/callable_lib_L_AB_order1.C
interpreter/cling/test/DynamicLibraryManager/pie.C
interpreter/llvm/src/include/llvm/BinaryFormat/ELF.h

Backport fix for ACLiC (#7366)

---

graf3d/eve7/src/REveDataCollection.cxx
graf3d/eve7/src/REveDataTable.cxx
graf3d/eve7/src/REveSelection.cxx
gui/gui/src/TGDNDManager.cxx
gui/webgui6/src/TWebCanvas.cxx

* unused variables
* mixing `int` and `bool` in comparison

Fix some windows warnings in gui/webgui classes

---

bindings/jsmva/python/JsMVA/DataLoader.py
bindings/jsmva/python/JsMVA/Factory.py
bindings/pyroot/pythonizations/src/PyzPythonHelpers.cxx
bindings/pyroot/pythonizations/src/RDataFramePyz.cxx
bindings/pyroot/pythonizations/src/RPyROOTApplication.cxx
bindings/pyroot/pythonizations/src/RTensorPyz.cxx
bindings/pyroot/pythonizations/src/RVecPyz.cxx
bindings/pyroot_legacy/JsMVA/Factory.py
bindings/pyroot_legacy/src/Converters.cxx
bindings/pyroot_legacy/src/Executors.cxx
bindings/pyroot_legacy/src/TMemoryRegulator.cxx
bindings/pyroot_legacy/src/TMethodHolder.cxx
bindings/pyroot_legacy/src/TPySelector.cxx
bindings/pyroot_legacy/src/Utility.cxx

Several errors in the documentation of bindings

[bindings] doxygen errors

---

gui/webdisplay/inc/ROOT/RWebWindow.hxx
gui/webdisplay/inc/ROOT/RWebWindowsManager.hxx
gui/webgui6/inc/TWebMenuItem.h
gui/webgui6/inc/TWebPainting.h
gui/webgui6/inc/TWebSnapshot.h

- fix some incline comments
- spell checking

Doxgen fixes [skip-ci]

---

interpreter/cling/lib/Interpreter/AutoSynthesizer.cpp

This was an oversight in commit 34590aeef4: After fixing the handler blocks, the code needs to create new `CXXCatchStmt`s to eventually construct the `CXXTryStmt`.
Fixes #9664

[cling] Fix AutoSynthesizer on CXXTryStmt

---

gui/webgui6/inc/TWebCanvas.h
gui/webgui6/src/TWebCanvas.cxx

Fully avoid blocking in TCanvas::Update().
Only for expert use.

[webgui6] provide async mode for TWebCanvas (6.26)

---

math/mathcore/inc/Math/Delaunay2D.h

Formatting [skip-ci]

---

hist/hist/src/TH1.cxx
tutorials/graphs/hlGraph1.C
tutorials/graphs/hlGraph2.C
tutorials/hist/hlHisto1.C
tutorials/hist/hlHisto2.C
tutorials/hist/hlHisto3.C
tutorials/hist/hlHisto4.C
tutorials/math/hlquantiles.C
tutorials/tree/temperature.C

Call  `TCanvas::HighlightConnect` before canvas draw for the first time.
This let in case of `TWebCanvas` immediately detect such state and configure canvas.
Also avoid forward declaration of functions just by resorting their order.
Use more c++11 syntax.
Important - adjust `TH1::SetHighlight()` to use it without histogram painting, as with `TWebCanvas`.

Adjust tutorials with `TCanvas::HighlightConnect`

---

roofit/histfactory/inc/RooStats/HistFactory/EstimateSummary.h
roofit/histfactory/inc/RooStats/HistFactory/FlexibleInterpVar.h
roofit/histfactory/inc/RooStats/HistFactory/HistFactoryModelUtils.h
roofit/histfactory/inc/RooStats/HistFactory/HistFactoryNavigation.h
roofit/histfactory/inc/RooStats/HistFactory/HistFactorySimultaneous.h
roofit/histfactory/inc/RooStats/HistFactory/HistRef.h
roofit/histfactory/inc/RooStats/HistFactory/HistoToWorkspaceFactoryFast.h
roofit/histfactory/inc/RooStats/HistFactory/LinInterpVar.h
roofit/histfactory/inc/RooStats/HistFactory/Measurement.h
roofit/histfactory/inc/RooStats/HistFactory/ParamHistFunc.h
roofit/histfactory/inc/RooStats/HistFactory/PiecewiseInterpolation.h
roofit/histfactory/inc/RooStats/HistFactory/RooBarlowBeestonLL.h
roofit/histfactory/inc/RooStats/HistFactory/Sample.h
roofit/histfactory/inc/RooStats/HistFactory/Systematics.h

- remove tab
- spell check
- doxygen comments

[RF][skip-ci] HistFactory code formatting

---

README/ReleaseNotes/v628/index.md
roofit/roofitcore/inc/RooCmdArg.h
roofit/roofitcore/inc/RooCmdConfig.h
roofit/roofitcore/src/RooAbsCollection.cxx
roofit/roofitcore/src/RooCmdConfig.cxx

This PR suggests some modernization of the RooCmdConfig class, which has no effect on the functionality but saves many lines of code and bad patterns like friend classes.
This development was made many months ago, and it was taken from the still open PR https://github.com/root-project/root/pull/8427.
The linked PR combines the modernization with fixing the JIRA issue [ROOT-2784](https://sft.its.cern.ch/jira/browse/ROOT-2784), but I think it's better to separate code refactoring from changing functionality. This PR contains the first five commits from the linked PR.

[RF] Modernize RooCmdConfig

---

README/ReleaseNotes/v626/index.md

Hi @guitargeek , this PR adds the `RooLagrangianMorphFunc` to the release note as noted by you [here](https://github.com/root-project/root/blob/master/README/ReleaseNotes/v626/index.md#creating-roofit-datasets-from-rdataframe). 
Cheers,
Rahul

[relnotes][skip-ci] Add information on RooLagrangianMorphFunc

---

core/rint/src/TRint.cxx
interpreter/cling/lib/Interpreter/IncrementalParser.cpp
test/CMakeLists.txt

[cling] Only add NullPtrChk if enabled (6-26)

---

hist/hist/inc/THnBase.h
hist/hist/src/THnBase.cxx

Backport of https://github.com/root-project/root/pull/9512 (cc @bendavid )

fix copy/move constructors/assignment for THnBase

---

js/scripts/JSRoot.webwindow.js

[jsroot] patch WebWindowHandle code [skip-ci]

---

tree/dataframe/inc/ROOT/RDataSource.hxx

As ROOT cannot catch JITted exceptions on Apple Silicon (see the bug report https://github.com/root-project/root/issues/7541 for context), some tests are currently failing there due to the use of exceptions in the compatibility code for `RDataSource`. Implement this with a boolean flag and a pattern inspired by `errno`.

[DF] Compatibility in RDataSource without exceptions

---

roofit/hs3/inc/RooFitHS3/JSONInterface.h
roofit/hs3/src/JSONInterface.cxx
roofit/hs3/src/JSONParser.cxx
roofit/hs3/src/JSONParser.h
roofit/hs3/src/RooJSONFactoryWSTool.cxx

This PR refactors the iterator implementation for the JSON interface to avoid performance issues with reading workspaces from JSON.
Reading JSON files is much faster now.

[RF] RooFitHS3 performance improvements

---

README/ReleaseNotes/v626/index.md
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roojsonfactorywstool.py
roofit/hs3/README.md
roofit/hs3/inc/RooFitHS3/JSONInterface.h
roofit/hs3/src/JSONInterface.cxx
roofit/hs3/src/JSONParser.cxx
roofit/hs3/src/JSONParser.h
roofit/hs3/src/RooJSONFactoryWSTool.cxx

This PR adds documentation for the new RooFitHS3 library.

[RF] RooFitHS3 documentation and fix clang compiler warnings

---

core/metacling/src/TClingCallbacks.cxx

[v624][cxxmodules] Use the global module index only when no rootmap candidate is found

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/stl_vector.py

Fixes #9632  (see the text of the first commit for more details).

[PyROOT] Fix std::vector<char> iteration

---

graf2d/x11/src/GX11Gui.cxx

Revert changes made to fix drag and drop on Linux, it has side effects, as described in GitHub issue #9740

Revert commit #4ab7215 (should fix #9740)

---

graf2d/x11/src/GX11Gui.cxx

Revert changes made to fix drag and drop on Linux, it has side effects, as described in GitHub issue #9740

[v6.26] Revert commit #4ab7215 (should fix #9740)

---

ui5/eve7/lib/EveElements.js
ui5/eve7/lib/GlViewerRCore.js
ui5/eve7/lib/GlViewerThree.js

Minimal changes that make REve GlViewerThree work again.
There is still the mystery of:
- pointerleave event being generated before pointerdown
- dblclick event not making it through
I was suspecting SAP modifications to jQuery to be bugged.

Replace mouse event with pointer ones.

---

bindings/pyroot/cppyy/cppyy-backend/cling/python/cppyy_backend/loader.py
bindings/pyroot/cppyy/patches/mac12soversion.patch
bindings/pyroot/pythonizations/python/ROOT/_pythonization/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_stl_vector.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/stl_vector.py

A few backports of the changes merged in master by the following PRs:
https://github.com/root-project/root/pull/9708
https://github.com/root-project/root/pull/9725
https://github.com/root-project/root/pull/9729

[PyROOT] Backports for 6.26

---

js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.jq2d.js
js/scripts/JSRoot.tree.js

[jsroot] latest fixes for 6.26 branch [skip-ci]

---

tmva/tmva/inc/TMVA/RBDT.hxx

[TMVA] Throw an exception when input file for using RBDT does not exist.

---

math/unuran/inc/TUnuran.h
math/unuran/inc/TUnuranBaseDist.h
math/unuran/inc/TUnuranContDist.h
math/unuran/inc/TUnuranDiscrDist.h
math/unuran/inc/TUnuranEmpDist.h
math/unuran/inc/TUnuranMultiContDist.h
math/unuran/inc/TUnuranSampler.h

- spell check
- indentation
- comment ins doxygen format
- remove dead code
- remove trailing spaces
- remove tab

Unuran formatting

---

math/mathcore/inc/Fit/BasicFCN.h
math/mathcore/inc/Fit/BinData.h
math/mathcore/inc/Fit/Chi2FCN.h
math/mathcore/inc/Fit/DataOptions.h
math/mathcore/inc/Fit/DataRange.h
math/mathcore/inc/Fit/FitConfig.h
math/mathcore/inc/Fit/FitData.h
math/mathcore/inc/Fit/FitResult.h
math/mathcore/inc/Fit/FitUtil.h
math/mathcore/inc/Fit/Fitter.h
math/mathcore/inc/Fit/LogLikelihoodFCN.h
math/mathcore/inc/Fit/ParameterSettings.h
math/mathcore/inc/Fit/PoissonLikelihoodFCN.h
math/mathcore/inc/Fit/UnBinData.h

- spell check
- comment ins doxygen format
- remove trailing spaces

Mathcore-fit formatting

---

math/mathcore/inc/TKDTree.h
math/mathcore/inc/TKDTreeBinning.h
math/mathcore/inc/TRandomGen.h

- spell check
- comment ins doxygen format
- remove trailing spaces

mathcore formatting

---

cmake/modules/SearchInstalledSoftware.cmake
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.io.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.openui5.js
js/scripts/JSRoot.v7gpad.js
ui5/browser/browser.html
ui5/browser/model/BrowserListBinding.js
ui5/browser/model/BrowserModel.js
ui5/canv/canvas.html
ui5/canv/canvas6.html
ui5/eve7/geom.html
ui5/eve7/index.html
ui5/panel/panel.html

Need small adjustment in `RBrowser` - internal openui5 API changed
Adjust JSROOT code, use everywhere link to new openui5 version

[webgui] upgrade openui5 to 1.98.0

---

bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/__init__.py
bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roojsonfactorywstool.py
bindings/pyroot/pythonizations/test/CMakeLists.txt
bindings/pyroot/pythonizations/test/roofit/roojsonfactorywstool.py
roofit/hs3/README.md
roofit/hs3/inc/RooFitHS3/HistFactoryJSONTool.h
roofit/hs3/inc/RooFitHS3/JSONInterface.h
roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h
roofit/hs3/src/HistFactoryJSONTool.cxx
roofit/hs3/src/JSONFactories_HistFactory.cxx
roofit/hs3/src/JSONFactories_RooFitCore.cxx
roofit/hs3/src/JSONInterface.cxx
roofit/hs3/src/JSONParser.cxx
roofit/hs3/src/JSONParser.h
roofit/hs3/src/RYMLParser.cxx
roofit/hs3/src/RYMLParser.h
roofit/hs3/src/RooJSONFactoryWSTool.cxx
roofit/hs3/src/static_execute.h

Adds a documentation generator helper function to RooJSONFactoryWSTool and explains its usage in the class documentation.

[RF] RooFitHS3 latex documentation generator

---

README/ReleaseNotes/v626/index.md

Update also contributor list adding the GSOC and summer student of 2021
that have contributed to the TMVA developments

[skip-ci]Update 6.26 release notes for SOFIE

---

README/ReleaseNotes/v626/index.md
math/mathcore/inc/Math/MinimizerOptions.h
math/mathcore/src/GenAlgoOptions.cxx
math/mathcore/src/MinimizerOptions.cxx
tmva/tmva/inc/TMVA/Event.h
tmva/tmva/inc/TMVA/RBDT.hxx
tmva/tmva/src/DataSetFactory.cxx
tmva/tmva/src/Event.cxx
tmva/tmva/test/crossvalidation/CMakeLists.txt
tmva/tmva/test/crossvalidation/TestCrossValidationIntVar.cxx

This PR back ports fixes from these PR's:
- #9499
- #9513 
- #9718 (in Math)
- #9776 (release notes)

Back-port some TMVA fixes for the 6.26 branch

---

bindings/pyroot/pythonizations/test/CMakeLists.txt
roofit/hs3/inc/RooFitHS3/RooJSONFactoryWSTool.h
roofit/hs3/src/RooJSONFactoryWSTool.cxx

[RF] Enable again the RooJSONFactoryWSTool Python tests on Mac

---

README/ReleaseNotes/v626/index.md

[skip-ci][relnotes] Reintroduce accidentally deleted paragraph about RNTuple

---

README/ReleaseNotes/v626/index.md

Backport of https://github.com/root-project/root/pull/9833.

[v626][RF][RelNotes] Mention removal of `const char*` to RooCmdArg conversion

---

graf3d/eve7/CMakeLists.txt
graf3d/eve7/inc/LinkDef.h
gui/webgui6/src/TWebCanvas.cxx
js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hierarchy.js
js/scripts/JSRoot.hist.js
js/scripts/JSRoot.hist3d.js
js/scripts/JSRoot.math.js
js/scripts/JSRoot.menu.js
js/scripts/JSRoot.more.js
js/scripts/JSRoot.tree.js
js/scripts/JSRoot.v7gpad.js
js/scripts/JSRoot.v7hist.js
js/scripts/JSRoot.v7hist3d.js
js/scripts/JSRoot.v7more.js
js/scripts/JSRoot.webwindow.js
tutorials/webgui/qt5web/ExampleWidget.cpp
tutorials/webgui/qt5web/ExampleWidget.h
tutorials/webgui/qt5web/ExampleWidget.ui
tutorials/webgui/qt5web/RCanvasWidget.cpp
tutorials/webgui/qt5web/Readme.md

Required to display geometry in web mode with normal macros
like root --web tutorials/geom/south_gate.C

[webgeom] enable REveGeoPainter, support TGeo drawings in TCanvas

---

graf3d/eve7/CMakeLists.txt
graf3d/eve7/inc/LinkDef.h
gui/webgui6/src/TWebCanvas.cxx
js/changes.md
js/scripts/JSRoot.base3d.js
js/scripts/JSRoot.core.js
js/scripts/JSRoot.geom.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.hist3d.js
tutorials/webgui/qt5web/ExampleWidget.cpp
tutorials/webgui/qt5web/ExampleWidget.h
tutorials/webgui/qt5web/ExampleWidget.ui
tutorials/webgui/qt5web/RCanvasWidget.cpp
tutorials/webgui/qt5web/Readme.md

Required to display geometry in web mode with normal macros
like root --web tutorials/geom/south_gate.C

[webgeom] enable REveGeoPainter, support TGeo drawing in TCanvas (6.26)

---

io/io/src/TBufferFile.cxx
io/io/test/CMakeLists.txt
io/io/test/TBufferFileTests.cxx

[io] Enable auto schema conversion for vector<ARITH_TYPE>:

---

tutorials/graphs/waves.C

Use proper "samecol" draw options for TF2 instead of "samecolorz"
Use TColor::GetColor() to create new TColor instances
Format code

Adjust waves.C tutorials [skip-ci]

---

CMakeLists.txt

Reverts root-project/root#9834

Revert "[cmake] simplify copies of misc files into build directory"

---

core/base/inc/TVirtualQConnection.h
core/cont/inc/TBits.h
graf2d/postscript/src/TImageDump.cxx
hist/hist/src/TH1.cxx
hist/hist/src/TH2.cxx
hist/unfold/src/TUnfoldDensity.cxx
io/io/src/TMemFile.cxx
io/io/src/TStreamerInfo.cxx
math/mathmore/test/testGSLIntegration.cxx
math/mathmore/test/testRandomDist.cxx
math/minuit2/inc/Minuit2/FumiliFCNAdapter.h
net/net/src/TMessage.cxx
roofit/roofitcore/src/RooDataHist.cxx
test/TFormulaParsingTests.h
test/stressTMVA.cxx
tmva/sofie/inc/TMVA/ROperator_BatchNormalization.hxx
tmva/tmva/inc/TMVA/NeuralNet.icc
tmva/tmva/src/DataSetFactory.cxx
tmva/tmva/src/Factory.cxx
tmva/tmva/src/MethodBoost.cxx
tmva/tmva/src/MethodFDA.cxx
tmva/tmva/src/PDEFoam.cxx
tmva/tmva/src/RuleEnsemble.cxx
tmva/tmva/src/RuleFitAPI.cxx
tmva/tmva/src/RuleFitParams.cxx
tmva/tmva/src/VariableImportance.cxx
tree/tree/src/TTree.cxx

Building with current Clang `main` produced a number of warnings.

Resolve Clang warnings

---

graf2d/mathtext/CMakeLists.txt
graf2d/postscript/CMakeLists.txt
net/netx/CMakeLists.txt
net/netxng/CMakeLists.txt

Backport of https://github.com/root-project/root/pull/9088 https://github.com/root-project/root/pull/9582

[6.24] Prevent various build warnings

---

graf2d/mathtext/CMakeLists.txt
graf2d/postscript/CMakeLists.txt
net/netx/CMakeLists.txt
net/netxng/CMakeLists.txt

[6.22] Prevent various build warnings

---

js/changes.md
js/scripts/JSRoot.core.js
js/scripts/JSRoot.gpad.js
js/scripts/JSRoot.latex.js
js/scripts/JSRoot.painter.js

Fix several issues in TLatex parsing
Fix labels drawing for axes

[jsroot] release 6.3.4 with several fixes for 6.26 [skip-ci]

---

tree/dataframe/inc/ROOT/RDF/RFilter.hxx
tree/dataframe/inc/ROOT/RDF/RFilterBase.hxx
tree/dataframe/inc/ROOT/RDF/RNodeBase.hxx
tree/dataframe/inc/ROOT/RDF/RRange.hxx
tree/dataframe/inc/ROOT/RDF/RRangeBase.hxx
tree/dataframe/inc/ROOT/RDF/RVariedAction.hxx

- fix interaction of Vary and Range
- avoid useless clones of the nominal filters
@ikabadzhov will soon open a PR with a test for this as well as many other cases.

[DF] Fixes and improvements to syst. variations

---

hist/hist/src/TMultiGraph.cxx

histogram and functions should be handled as well
Backport of #9919

Fix TMultiGraph::RecursiveRemove (6.26)

---

geom/geom/src/TGeoMaterial.cxx

see: https://root-forum.cern.ch/t/what-are-the-meaning-of-the-parameters-of-tgeomaterial-name-a-z-rho/48705/4

[skip-ci] document ctor

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
bindings/experimental/distrdf/python/DistRDF/DataFrame.py
bindings/experimental/distrdf/python/DistRDF/Node.py
bindings/experimental/distrdf/python/DistRDF/Operation.py
bindings/experimental/distrdf/python/DistRDF/Proxy.py
bindings/experimental/distrdf/test/test_operation.py

Create Operation subclasses to tag different operation types

---

documentation/doxygen/Doxyfile

Prevents many doxygen warnings regarding 'Streamer' function.

[doxy] add some more folders to include path

---

bindings/experimental/distrdf/python/DistRDF/Backends/Base.py
bindings/experimental/distrdf/python/DistRDF/Backends/Utils.py
bindings/experimental/distrdf/python/DistRDF/ComputationGraphGenerator.py
bindings/experimental/distrdf/python/DistRDF/Operation.py

Also removing usage of `if operation.name == ["Snapshot", "AsNumpy"]`. Leaving out CppWorkflow for now, it will be modified in the future

[DF] Subclass AsNumpy and Snapshot Operation tags

---

interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp

[cling] DynamicLibraryManagerSymbol.cpp formatting (NFC). [skip-ci]

---

documentation/doxygen/Doxyfile

Speeds up building the documentation (the graphviz dot part).

[skip-ci] [doxy] speedup dot generation in docu

---

bindings/experimental/distrdf/python/DistRDF/Proxy.py

[DF] Respect lazyness of instant actions in distributed mode

---

tmva/tmva/test/crossvalidation/TestCrossValidationIntVar.cxx

This PR back ports in 6.26 #10018

[TMVA] Backport of using a unique XML file for the CV tests

---

tree/treeplayer/test/basic.cxx

TreePlayer-test: avoid use after delete of TEntryList by TTree

---

tree/tree/test/BulkApiMultiple.cxx

This fixes Issue #10012.
TTreeReader is not in any cleanup list but retain a reference to the TTree and thus the TTree (and its TFile) must be deleted
after the TTreeReader object(s) using them.# This Pull request:

BulkApi test: TFile used by TTreeReader needs to be delete last.

---

roofit/histfactory/inc/RooStats/HistFactory/LinInterpVar.h
roofit/histfactory/src/FlexibleInterpVar.cxx
roofit/histfactory/src/HistFactoryModelUtils.cxx
roofit/histfactory/src/HistFactoryNavigation.cxx
roofit/histfactory/src/HistoToWorkspaceFactory.cxx
roofit/histfactory/src/HistoToWorkspaceFactoryFast.cxx
roofit/histfactory/src/LinInterpVar.cxx
roofit/histfactory/src/MakeModelAndMeasurementsFast.cxx
roofit/histfactory/src/PiecewiseInterpolation.cxx
roofit/histfactory/src/RooBarlowBeestonLL.cxx

PR includes migration of all the flies from Roofit/histfactory/src
This PR fixes #8777

[RF] Migrate HistFactory from legacy iterators to range-based loops

---

roofit/roofitcore/inc/RooAbsProxy.h
roofit/roofitcore/src/RooAbsPdf.cxx

- fix an error message (text was misleading)
- correclty initialize a data member
- allow initialHesse to be used with Minimizer option in fitTo

[RF] Some small roofit improvements:

---

tree/ntuple/v7/inc/ROOT/RField.hxx

[ntuple] Fix ASAN detected buffer overflow

---

README/ReleaseNotes/v626/index.md
roofit/batchcompute/README.md

The title says it all, needs to be backported to the 6.26 branch where I forgot to add such release notes.

[RF][RelNotes] Mention new BatchMode with CUDA support in 6.26 RelNotes

---

bindings/experimental/distrdf/python/DistRDF/Proxy.py

Logical backport of #9995 . In the 6.26 sources the new implementation that dispatches proxy creation by the operation type is not present. Porting this to 6.26 should still be worth it since it fixes a bug

[6.26] Respect lazyness of instant actions in distributed mode

---

core/base/src/TApplication.cxx
core/base/src/TROOT.cxx
net/http/src/THttpServer.cxx

1. webgui batch only configured when no any extra args specified with `--web` call
2. Let configure server port with argument like `--web=server:9200`

Let use webgui server also in batch mode

---

gui/browsable/src/RSysFile.cxx
gui/browsable/src/TDirectoryElement.cxx

[rbrowser] let browser custom trees (6.26)

---

documentation/doxygen/Makefile

as requested here https://github.com/root-project/root/issues/10066

compress tag and qch files

---

math/foam/src/TFoam.cxx
math/mathcore/test/stressTMath.cxx
tmva/sofie/src/RModel.cxx

Either remove or uncomment output.

[math/tmva] Resolve warnings about unused variables
